### ISSUE TITLE
Document maximum size seed accepted for setRandomNumberSeed()

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#1013]
I've run into an `OverflowError` with `LangevinIntegrator.setRandomNumberSeed()`:

```
  File "/Users/choderaj/anaconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-macosx-10.5-x86_64.egg/yank/repex.py", line 1095, in _propagate_replica
    integrator.setRandomNumberSeed(int(np.random.randint(0, sys.maxint)))
  File "/Users/choderaj/anaconda/lib/python2.7/site-packages/simtk/openmm/openmm.py", line 11891, in setRandomNumberSeed
    return _openmm.LangevinIntegrator_setRandomNumberSeed(self, *args)
OverflowError: in method 'LangevinIntegrator_setRandomNumberSeed', argument 2 of type 'int'
```

It seems that we don't document what kinds of values are acceptable here, except that this is type `int`, which is what we should we should definitely be getting from `int(np.random.randint(0, sys.maxint))`.

**Comment by jchodera** [comment]
What if we 
1. Document the maximum allowed seed, if it is universal?
2. If not universal, cast the seed to something to avoid an overflow?
3. If it is important to know the maximum seed, add a `getMaxAllowedRandomNumberSeed()` method?

**Comment by rmcgibbo** [comment]
What sizes are overflowing? I assume the max is 2**31-1.

**Comment by rmcgibbo** [comment]
> which is what we should we should definitely be getting from int(np.random.randint(0, sys.maxint)).

No, I think you're mistaken. The exception refers to the C type `int`, which is a 32-bit signed integer on essentially all platforms I've used (linux 32/64, OS-X, windows 32, windows 64) except for Arduino. But the python2 `int` type is a C `long` on 64-bit platforms.

**Comment by jchodera** [comment]
Ah, excellent point!

**Comment by jchodera** [comment]
Well, I can definitely say that using `MAX_SEED = 2**32 - 1` in
```
integrator.setRandomNumberSeed(int(np.random.randint(0, MAX_SEED))) 
```
can also trigger the same `OverflowError`.

**Comment by rmcgibbo** [comment]
2**31-1, not 2**32-1.

**Comment by jchodera** [comment]
D'oh.  That works fine.  Thanks!

Still something we should at least document, especially for the Python API users?  Or maybe even cast?

**Comment by rmcgibbo** [comment]
This is a common feature for all of the swig wrappers.

**Comment by jchodera** [comment]
So, just let everybody discover for themselves the difference between Python and C `int`?

**Comment by rmcgibbo** [comment]
My point was that you should think of this in a broader context -- the `OverflowError` applies generally when translating from a python type to a C `int` for any function in the swig API, of which there are probably a couple hundred. You could add a note to the User Guide, sure, but changing a single method doesn't make sense.

By the same token, any time you have a function in the C++ API that takes a `float`, users should realize that this is a 32-bit single precision floating point type, notwithstanding the fact that Python uses the name "float" for a 64-bit floating point type.

**Comment by jchodera** [comment]
I think there is a bit of a difference here.  If we're talking about something like an addressable particle number, it is likely this number will be less than `2**31-1`, and there will be no problem.  But for a random number seed, one generally wants to use a number drawn as randomly as possible from a set of integers that is as large as possible, so it is much more likely that reminding the user of the maximum allowable value strategically in these places (specifically for random number seeds in `Context`, `LangevinIntegrator`, and `MonteCarloBarostat` variants) would be useful.

I'm happy to put together a PR for this, but I think we just need agreement about the best way to handle it first.

**Comment by rmcgibbo** [comment]
I'd be fine with a short note in the docstring on a couple methods.

**Comment by swails** [comment]
> I'd be fine with a short note in the docstring on a couple methods.

+1.  I don't think anything more is really required.

Besides, shouldn't the default behavior be good enough?  Don't we have microsecond resolution on the seed drawn from the clock?  I've never seen even a multithreaded application launching simulations "simultaneously" (e.g., through REMD) draw the same seed from the clock.  Really what you're doing is basically the same thing, right?  You're relying on how Python seeds *its* generators, which is probably no better than how OpenMM seeds ours...

**Comment by jchodera** [comment]
If we really have *microsecond* resolution, yes, we probably don't need those methods (but then why do we have them?).  

If it was *millisecond* resolution, I've seen MPI programs launch processes essentially simultaneously and proceed to generate identical or synchronizing trajectories by being assigned the same random number seeds from the clock.

In my MPI code, we specifically assign numpy *distinct* seeds (by adding in the MPI rank), and then use numpy to reseed `LangevinIntegrator`, `MonteCarloBarostat`, and `setVelocitiesToTemperature` based on the next random integer.  Maybe that isn't necessary, even if we create/destroy `Context` objects over and over again?

**Comment by swails** [comment]
> If it was millisecond resolution, I've seen MPI programs launch processes essentially simultaneously and proceed to generate identical or synchronizing trajectories by being assigned the same random number seeds from the clock.

Actually I was wrong.  I believe it draws seeds from `/dev/urandom`, which is even better I think.  I'll see if I can demo this at some point.

**Comment by jchodera** [comment]
Does it draw at time of `Context` creation, or at time of creation of `LangevinIntegrator` or `MonteCarloBarostat` objects?

**Comment by swails** [comment]
Context creation IIRC (I think it was one of my PRs awhile ago).

**Comment by swails** [comment]
cc #765

**Comment by jchodera** [comment]
Ah!  It's even in the manual!  Thanks.  I can clean up my code then.

Still worth documenting the `int32` in a few places, IMHO.  I'll create a PR soon.
