### ISSUE TITLE
Release plugin binaries linked against multiple versions of CUDA?

### ISSUE THREAD

**Issue by rmcgibbo** [openmm/openmm#1038]
This might take a bit of work, and it could be a little tricky to test. But, it would be nice if we could come up with a way for the release binaries to work with multiple versions of CUDA, regardless of what the user has installed (e.g. either 6.5 or 7.0). The rationale for this is that on clusters, users would like to install the newest versions of OpenMM but the CUDA version might lag behind, and they lack the privileges to upgrade it.

Conceptually, you'd just compile once with each version of CUDA and then throw the all of the plugin files together. Then at runtime when the plugins are loaded, presumably only the plugin corresponding to the user's version of CUDA would actually load successfully. Obviously some machines have multiple versions of CUDA installed, so you'd get into a mess if both loaded successfully (multiple plugins with the same name), so we'd need some way to have one take priority over the other.

I'm not sure if this is worth the extra work, but it's an idea.

**Comment by jchodera** [comment]
I'm +1 for this, though we discussed it to some degree earlier:
https://github.com/pandegroup/openmm/issues/812#issuecomment-84090131

**Comment by rmcgibbo** [comment]
I tried casually just dropping another libOpenMMCUDA.so (renamed) into the plugin directory, and it seems to cause a double-free when the process exits, so :shrug:.

**Comment by jlmaccal** [comment]
At least for linux, can't we just setup different `omina-build-box` images with different version of cuda? Then release `openmm-cuda-6-5`, `openmm-cuda-7-0`, etc? This would be a huge timesaver when working on a cluster.

**Comment by jchodera** [comment]
Different package names could lead users to install multiple versions at the same time accidentally. We unfortunately can't tell `conda` that some packages are incompatible yet.

I do wonder if we could build versions with different CUDA versions and upload them to different `labels`, however.  Then, a user would `conda install -c omnia/labels/cuda7.0 openmm` to get the CUDA 7.0 version.

**Comment by jlmaccal** [comment]
It seems like using [features](http://conda.pydata.org/docs/building/meta-yaml.html#id1) might be a good fit. This is how windows builds use the correct version of visual studio, for example. There would be a meta-package that tracks a particular cuda feature, so installation would go something like:
```
conda install omnia-cuda-7-5
conda install openmm
```
This would cause the user to end up with the cuda 7.5 version of openmm.

The install script for the metapacakge can check if any other `omnia-cuda-*` is installed and fail if this is the case to prevent multiple versions from being installed.

**Comment by peastman** [comment]
One important consideration: currently, we only test against one version of CUDA.  (And yes, it's *very* common for differences between CUDA releases to cause things to work in one version but fail in another.)  We tell people that it *might* work if they compile against a different version, but we don't make any promises.

If we're going to start distributing builds compiled against multiple CUDA releases, that pretty much commits us to testing and supporting all of them.  That isn't to say we can't do it, but we need to recognize the consequences and make sure we have the resources to deal with them.

**Comment by jchodera** [comment]
> If we're going to start distributing builds compiled against multiple CUDA releases, that pretty much commits us to testing and supporting all of them. 

If we do build a few docker images for different combinations of CUDA/AMD APP SDK (e.g. CUDA 7.0 / APP SDK 2.9.1 and CUDA 7.5 / AMD APP SDK 3.0) we could have different branches of Travis test with different docker images.  That shouldn't be too hard.

**Comment by peastman** [comment]
Does travis have GPUs now?

**Comment by jchodera** [comment]
No, sorry.  We would be testing that we can correctly compile against these versions.  Once we build them, you're right, we would have to test them on different CUDA versions.

The most fruitful approach might be to explore doing that with EC2 instances that boot with different CUDA versions.

**Comment by jlmaccal** [comment]
@peastman That's certainly a good point regarding support. I do agree that this potentially creates more work, but I think the benefits outweigh the costs.

My main motivation for conda packaging is to make it easier for people to deploy MELD and get work done. That's both within my group and for external users. The problem is that the cuda version is often a feature of the environment, rather than something I can control. If we only support cuda-7.5 that effectively eliminates all of the sites where my group would run calculations, which makes conda packaging a wasted effort.

On an alternative note, if we're only going to build packages for a single version of cuda, I would advocate using something relatively old. My understanding is that old libraries work with new drivers, but not the other way around. Even on a machine where I don't have root, it's conceivable that I can install a version of the toolkit and runtime locally, even when I can't change the driver.

**Comment by jlmaccal** [comment]
@jchodera My plan for MELD was to build `meld-test` packages and push those to a private conda channel. The final step of build script would be to ping a local jenkins instance that would then pull down the conda packages and run the test suites. I was planning to set this up using `nvidia-docker` which allows one to test against different versions of the cuda libraries. Spinning up EC2 instances would be another good alternative. For mac testing, there are also a couple of companies that host co-located mac-mini instances.

All of this would be much easier if travis had GPUs.

**Comment by peastman** [comment]
> I do agree that this potentially creates more work, but I think the benefits outweigh the costs.

Does that mean you're volunteering to do it?  Or did you mean the benefits to you of having the feature outweigh the cost to you of someone else doing the work? :)

**Comment by jlmaccal** [comment]
Obviously the second one :)

But I don't see the point of making conda packages if many of our users won't be able to use them. I would guess the vast majority of clusters / supercomputers are not running cuda-7.5.

**Comment by mpharrigan** [comment]
Our clusters at stanford have cuda 6.5, 7.0, and 7.5 through the module system. I don't think it's unreasonable to ask sysadmins for the current version of cuda on a gpu cluster

**Comment by jlmaccal** [comment]
I don't think it's unreasonable either, but that doesn't mean it's going to happen...

In my experience, getting a version of cuda toolkit installed is fine, but there is sometimes more resistance to getting drivers updated.

**Comment by jchodera** [comment]
> I don't think it's unreasonable either, but that doesn't mean it's going to happen...

100% agree.  Try asking the [ORNL Titan](https://www.olcf.ornl.gov/titan/) folks to upgrade to the latest CUDA and see how far you get.

**Comment by jchodera** [comment]
I'm wondering if we can use the AWS Deploy features of travis to automate testing. If we had images on AWS with the various CUDA versions, we could have them run through tests and generate logs/badges that get stored in S3.  Trying to find examples where other people have done this...

**Comment by peastman** [comment]
Closing this old discussion.  We've decided to go with the conda-forge method of supporting different CUDA versions.
