### ISSUE TITLE
Stochastic RESPA integrator by Leimkuhler et al.

### ISSUE THREAD

**Issue by franknoe** [openmm/openmm#1042]
Consider implementing this stochastic RESPA integrator by Leimkuhler, Margul and Tuckerman:
    http://www.tandfonline.com/doi/abs/10.1080/00268976.2013.844369

According to @peastman this can be done as a CustomIntegrator (using devel ?) after 6.3 has been declared final.

**Comment by peastman** [comment]
You could even do it now with the CPU platform.  But on the CUDA and OpenCL platforms, you wouldn't be able to split nonbonded forces into short range and long range parts, which would make it less useful.  #1030 fixes that.

**Comment by peastman** [comment]
Closing this old issue, since we have no plans to implement it.  This integrator turned out not to work as well as originally hoped.
