### ISSUE TITLE
Create CustomCollectiveBondForce

### ISSUE THREAD

**Issue by jlmaccal** [openmm/openmm#1112]
This is to discuss John's idea for a new force:

A generalization of that idea would be a force that would"
- for each specified pair of atom groups
- map a function onto each pair of atoms in each group
- reduce these distances according to some reduction operation
- compute an energy as a function of that reduced value

I think this would be a great addition, but we need to give some thought to the API. The reduction step, in particular, seems to have no clear counterpart in any of the existing custom forces.

**Comment by jchodera** [comment]
I envision something like this:
```
# Soft half-harmonic potential to keep ligand near protein
# Soft approximation to min: r_{eff} = -r_0*\log[\sum_{ij} e^{-r_{ij} / r_0}]
pair_function = 'exp(-r/r0)' 
reduction_operation = CustomGroupInteractionForce.sum
energy_function = 'step(r)*K*reff^2; reff=-r0*log(reduction)'
force = CustomGroupInteractionForce(pair_function, reduction_operation, energy_function)
group1 = force.addParticleGroup([0,1,2])
group2 = force.addParticleGroup([3,4,5,6])
force.addInteraction(group1, group2)
```
There could be a number of different common reduction operations, like `sum`, `prod`, `min`, `max`.  Think `MPI_Reduce`.

**Comment by jlmaccal** [comment]
Another possibility would be to provide a reducing function in the functional programming sense, where the function combines a new value with an accumulator, which could be implemented as a parallel reduction. You example might look like:

```python
# Soft half-harmonic potential to keep ligand near protein
# Soft approximation to min: r_{eff} = -r_0*\log[\sum_{ij} e^{-r_{ij} / r_0}]
pair_function = 'exp(-r/r0)' 
reduction_operation = 'data + accum'
initial_accumulator_value = 0.0
energy_function = 'step(r)*K*reff^2; reff=-r0*log(reduction)'
force = CustomGroupInteractionForce(pair_function, function, energy_function,
                                                              initial_accumulator_value)
force.addGlobalParameters('r0', 0.5 * unit.angstrom) # softness parameter
group1 = force.addParticleGroup([0,1,2])
group2 = force.addParticleGroup([3,4,5,6])
force.addInteraction(group1, group2)
```

**Comment by jchodera** [comment]
> Another possibility would be to provide a reducing function in the functional programming sense

I really like that, though it may not allow for efficient vectorized reducing operations.

**Comment by peastman** [comment]
We now have CustomCompoundBondForce.
