### ISSUE TITLE
Add AppVeyor badge to README.md

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#1166]
@peastman, it would be useful to add the AppVeyor build status badge to the main `README.md`.

Only you can do this, since it is under your account.  Follow the directions here to get the URL from AppVeyor:

Then, add a line like this to the `Badges` section of the `README.md`, substituting the appropriate identifier for `sqjgx3jh14vuxks5`:

```
* AppVeyor `windows` build status: [![Windows Build status](https://ci.appveyor.com/api/projects/status/sqjgx3jh14vuxks5/branch/master?svg=true)](https://ci.appveyor.com/project/peastman/openmm/branch/master)                                                                                                                                                                             
```

**Comment by jchodera** [comment]
I think you're still the only one who can look up the AppVeyor identifier, @peastman

**Comment by peastman** [comment]
I know, but since AppVeyor is currently broken, I don't want to add a badge until we get it working.  I started debugging it a few weeks ago, but got sidetracked by other things.  See #1421.

**Comment by peastman** [comment]
We no longer use AppVeyor.
