### ISSUE TITLE
Segmentation fault running "first examples" 

### ISSUE THREAD

**Issue by ld1988** [openmm/openmm#1167]
I am a new user of OpenMM, but I am having problems performing a simulation.
I installed it successfully on my machine:
Linux 3.2.0-4-amd64 #1 SMP Debian 3.2.68-1+deb7u3 x86_64 GNU/Linux

but If I run the example files, I often (but not always), get segmentation fault errors.
For example:

---

python simulateGromacs.py
# "Step","Potential Energy (kJ/mole)","Temperature (K)"

1000,-123802.120017,248.744571116
2000,-118201.228656,284.558599917
3000,-116004.13001,292.393578518
4000,-115575.97142,299.425490796
5000,-115382.53991,301.768690217
6000,-115507.116395,301.767244065
7000,-115296.597272,302.677236673
8000,-115681.070808,301.491951995
[1]    252122 segmentation fault  python simulateGromacs.py

---

This usually happens with the files simulateGromacs.py and simulatePdb.py, but not with simulateAmber.py.

Can you help me with this problem? 

Thanks for your attention.

**Comment by peastman** [comment]
Hi,

Which platform are you using?  What sort of hardware are you running it on?  For example, do you have a GPU?  If so, what kind?  If you're using the CUDA platform, what version of CUDA do you have installed?

**Comment by ld1988** [comment]
The GPU is a NVIDIA  GT218, but I didn't install CUDA.
The processor is Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz.
I have 8GB of RAM.
The linux version is:
Linux version 3.2.0-4-amd64 (debian-kernel@lists.debian.org) (gcc version 4.6.3 (Debian 4.6.3-14) ) #1 SMP Debian 3.2.68-1+deb7u3

**Comment by peastman** [comment]
Ok, so it's using the CPU platform.  Could you try running it in gdb?  That is, type

    gdb python

Then at the gdb prompt, type

    run simulateGromacs.py

Let it run until it segfaults.  Then type

    bt

That will print out a stack trace showing where the segfault occurred.  Post the output here.  Hopefully it will give some information about what's going on.

**Comment by ld1988** [comment]
Thanks for the reply.
This is the output:
____________________
#"Step","Potential Energy (kJ/mole)","Temperature (K)"
1000,-123995.796656,255.866876369
2000,-118108.595536,284.231492999
3000,-115818.647159,295.522907905
4000,-115769.819114,298.863406512

Program received signal SIGSEGV, Segmentation fault.
0x00007fffef466f4f in OpenMM::CpuNeighborList::computeNeighborList(int, OpenMM::AlignedArray<float> const&, std::vector<std::set<int, std::less<int>, std::allocator<int> >, std::allocator<std::set<int, std::less<int>, std::allocator<int> > > > const&, OpenMM::RealVec const*, bool, float, OpenMM::ThreadPool&) ()
   from /home/ldonati/openmm/lib/plugins/libOpenMMCPU.so
(gdb) 
(gdb) bt
#0  0x00007fffef466f4f in OpenMM::CpuNeighborList::computeNeighborList(int, OpenMM::AlignedArray<float> const&, std::vector<std::set<int, std::less<int>, std::allocator<int> >, std::allocator<std::set<int, std::less<int>, std::allocator<int> > > > const&, OpenMM::RealVec const*, bool, float, OpenMM::ThreadPool&) ()
   from /home/ldonati/openmm/lib/plugins/libOpenMMCPU.so
#1  0x00007fffef44b609 in OpenMM::CpuCalcNonbondedForceKernel::execute(OpenMM::ContextImpl&, bool, bool, bool, bool) ()
   from /home/ldonati/openmm/lib/plugins/libOpenMMCPU.so
#2  0x00007ffff5db825a in OpenMM::ContextImpl::calcForcesAndEnergy(bool, bool, int) () from /home/ldonati/openmm/lib/libOpenMM.so
#3  0x00007ffff5df3b3e in OpenMM::LangevinIntegrator::step(int) ()
   from /home/ldonati/openmm/lib/libOpenMM.so
#4  0x00007ffff6249154 in _wrap_LangevinIntegrator_step (args=<optimized out>)
    at src/swig_doxygen/OpenMMSwig.cxx:30141
#5  0x00007ffff7af237f in ext_do_call (nk=-317367480, na=<optimized out>, 
    flags=<optimized out>, pp_stack=0x7fffffffdf78, func=0x7ffff660a290)
    at Python/ceval.c:4345
#6  PyEval_EvalFrameEx (f=<optimized out>, throwflag=<optimized out>)
    at Python/ceval.c:2720
#7  0x00007ffff7af3dbe in PyEval_EvalCodeEx (co=0x7ffff7e521b0, 
    globals=<optimized out>, locals=<optimized out>, args=<optimized out>, 
    argcount=2, kws=0x7fff8406dd10, kwcount=0, defs=0x0, defcount=0, 
    closure=0x0) at Python/ceval.c:3267
---Type <return> to continue, or q <return> to quit---
#8  0x00007ffff7af23fa in fast_function (nk=<optimized out>, na=2, 
    n=<optimized out>, pp_stack=0x7fffffffe178, func=0x7fffef6cc398)
    at Python/ceval.c:4131
#9  call_function (oparg=<optimized out>, pp_stack=0x7fffffffe178)
    at Python/ceval.c:4056
#10 PyEval_EvalFrameEx (f=<optimized out>, throwflag=<optimized out>)
    at Python/ceval.c:2681
#11 0x00007ffff7af3dbe in PyEval_EvalCodeEx (co=0x7fffee5695b0, 
    globals=<optimized out>, locals=<optimized out>, args=<optimized out>, 
    argcount=1, kws=0x7fffed32a750, kwcount=1, defs=0x7fffee5798d8, 
    defcount=2, closure=0x0) at Python/ceval.c:3267
#12 0x00007ffff7af23fa in fast_function (nk=<optimized out>, na=1, 
    n=<optimized out>, pp_stack=0x7fffffffe378, func=0x7fffee57ef50)
    at Python/ceval.c:4131
#13 call_function (oparg=<optimized out>, pp_stack=0x7fffffffe378)
    at Python/ceval.c:4056
#14 PyEval_EvalFrameEx (f=<optimized out>, throwflag=<optimized out>)
    at Python/ceval.c:2681
#15 0x00007ffff7af2750 in fast_function (nk=<optimized out>, 
    na=<optimized out>, n=<optimized out>, pp_stack=0x7fffffffe4c8, 
    func=0x7fffee57eb18) at Python/ceval.c:4121
#16 call_function (oparg=<optimized out>, pp_stack=0x7fffffffe4c8)
    at Python/ceval.c:4056
---Type <return> to continue, or q <return> to quit---
#17 PyEval_EvalFrameEx (f=<optimized out>, throwflag=<optimized out>)
    at Python/ceval.c:2681
#18 0x00007ffff7af3dbe in PyEval_EvalCodeEx (co=0x7ffff7e729b0, 
    globals=<optimized out>, locals=<optimized out>, args=<optimized out>, 
    argcount=0, kws=0x0, kwcount=0, defs=0x0, defcount=0, closure=0x0)
    at Python/ceval.c:3267
#19 0x00007ffff7af3ed2 in PyEval_EvalCode (co=<optimized out>, 
    globals=<optimized out>, locals=<optimized out>) at Python/ceval.c:669
#20 0x00007ffff7b13e10 in run_mod (arena=0x680ad0, flags=0x7fffffffe7c0, 
    locals=0x7ffff7f60168, globals=0x7ffff7f60168, filename=<optimized out>, 
    mod=0x6abe10) at Python/pythonrun.c:1371
#21 PyRun_FileExFlags (fp=0x6ba010, filename=<optimized out>, 
    start=<optimized out>, globals=0x7ffff7f60168, locals=0x7ffff7f60168, 
    closeit=1, flags=0x7fffffffe7c0) at Python/pythonrun.c:1357
#22 0x00007ffff7b13fef in PyRun_SimpleFileExFlags (fp=0x6ba010, 
    filename=0x7fffffffeb77 "simulateGromacs.py", closeit=1, 
    flags=0x7fffffffe7c0) at Python/pythonrun.c:949
#23 0x00007ffff7b298f4 in Py_Main (argc=<optimized out>, argv=<optimized out>)
    at Modules/main.c:645
#24 0x00007ffff6de8ead in __libc_start_main ()
   from /lib/x86_64-linux-gnu/libc.so.6
#25 0x0000000000400649 in _start ()
_________

**Comment by ld1988** [comment]
I just want to tell you that I was able to run a simulation of 20000ps of the alanine in water using the files from amber turorial:
http://ambermd.org/tutorials/basic/tutorial0/

But if I run a simulation of the alanine using pdb files:
https://github.com/pandegroup/openmm/blob/master/wrappers/python/tests/systems/alanine-dipeptide-implicit.pdb
https://github.com/pandegroup/openmm/blob/master/wrappers/python/tests/systems/alanine-dipeptide-explicit.pdb

...I still get segmention fault error.
