### ISSUE TITLE
Q: Updating forces from host during dynamics

### ISSUE THREAD

**Issue by mj-harvey** [openmm/openmm#1179]
Hi,

I'm looking at coupling PLUMED with OpenMM which, as far as I can tell, hasn't already been done.
At every iteration during dynamics I need to add in biasing forces that have been calculated on the host. I see that the forces are available with context.getForces(), but  there seems to no complementary setForces() - is that correct?
I'd be grateful if you could give me your thoughts on how I might best approach implementing this.
cheers,
Matt

**Comment by rmcgibbo** [comment]
I think the most straightforward way is to write a new Force (e.g. `PLUMEDForce`) as a plugin, like, https://github.com/peastman/openmmexampleplugin, so that you can do the interface in C++.

**Comment by swails** [comment]
> I think the most straightforward way is to write a new Force (e.g. PLUMEDForce) as a plugin, like, https://github.com/peastman/openmmexampleplugin, so that you can do the interface in C++.

AFAIK, this is the only way to modify the state in a context during MD.  Even if it's not, it is almost certainly the only way to do it *efficiently* (since you can take optimal advantage of Plumed's abilities to download and upload *just* the forces associated with atoms involved in the colvar to minimize CPU<->GPU communication).

You can't do it in Python; C++ is really your only option.

**Comment by peastman** [comment]
Actually, there's a fairly easy way to do this using only Python.  Doing it *efficiently* is another matter.  A plugin would certainly be more efficient.  But the cost of doing it the easy way depends on various factors, such as which platform you're using, how many atoms you're applying the force to, and how often the applied force changes.  And of course, if you're already doing a lot of computation on the host at every time step, the cost may be negligible in comparison.

Anyway, here's the basic idea:

```Python
force = CustomExternalForce("-fx*x-fy*y-fz*z")
force.addPerParticleParameter("fx")
force.addPerParticleParameter("fy")
force.addPerParticleParameter("fz")
system.addForce(force)
```

That will apply a constant force (fx, fy, fz) to each particle.  Now call `force.addParticle()` once for every particle you want to apply the force to, specifying the values of fx, fy, and fz for each one.

To modify the forces being applied, call `setParticleParameters()` for each one, specifying the new values of the per-particle parameters, then finish by calling `updateParametersInContext()`.

**Comment by rmcgibbo** [comment]
Clever.

**Comment by swails** [comment]
Haha.  Wow.  This belongs in some kind of cookbook.

**Comment by swails** [comment]
Plumed would compute the entire colvar on the host, which could be expensive (for a large, complicated colvar) or cheap (like a simple distance) -- but the cheaper ones will typically need to add fewer particles.

It *still* can't be done purely in Python, though, since there's no Plumed Python API to hook into.  That part, at least, will need to be done in C/C++ (with a little bit of Cython or SWIG to expose it to Python).

**Comment by mj-harvey** [comment]
Thanks for the advice, all. Should be enough there to get me going.

**Comment by jchodera** [comment]
I wonder if it wouldn't be possible to just create CustomForce terms for
nearly every kind of plumed collective variable.  That would be the way to
make this really fast if the bias is only changing every few hundred steps
or so---though this would be a lot more effort and the overhead of updating
the system and creating a new context when the bias is updated may kill
that efficiency gain.

**Comment by swails** [comment]
> I wonder if it wouldn't be possible to just create CustomForce terms for
> nearly every kind of plumed collective variable.

Impossible in the current infrastructure to my knowledge (unless @peastman knows how to be *super* clever with `CustomExternalForce`).  In fact, OpenMM really only supports the simplest collective variables that Plumed has now (through `CustomCentroidBondForce`).  Other stuff, like RMSD, radius of gyration, ... etc. are completely out of the scope of any Custom force that I can think of.

I believe there is a *lot* of stuff in Plumed that you can't reinvent through a custom force or integrator: http://plumed.github.io/doc-v2.1/user-doc/html/_colvar.html

**Comment by jchodera** [comment]
> I believe there is a lot of stuff in Plumed that you can't reinvent through a custom force or integrator:

You're right---that's a lot of much more complex CVs.

**Comment by peastman** [comment]
I've begun work on a plugin to implement a proper interface between OpenMM and PLUMED.  It isn't finished yet (only reference platform implemented so far) and it requires some changes to PLUMED that haven't been merged into the master branch yet, but it's progressing quickly.  Take a look if you're interested.

https://github.com/peastman/openmm-plumed

**Comment by swails** [comment]
Cool!  Have you been in contact with the PLUMED devs on this?

This seems like a very natural combination, I suspect they're pretty excited about this combo (if they know about this work, of course).

**Comment by peastman** [comment]
Yes, we've been emailing back and forth a lot over the last few days.  They've been really helpful about adding API calls I needed.

**Comment by peastman** [comment]
There's now a supported plugin for PLUMED integration.
