### ISSUE TITLE
RFC: Proposal for extensions to ffxml format for multiple protonation/tautomeric states

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#1183]
Since we are also working on extending the `ffxml` format in #1168, now is a good time to also discuss extensions of the `ffxml` format to deal with multiple protonation/tautomeric states for constant-pH dynamics (currently being prototyped in https://github.com/choderalab/openmm-constph).

An [early version of the proposed format](https://github.com/pgrinaway/openmm-constph/blob/master/t4_ex/cpxml_out.xml) was developed by @pgrinaway, and @bas-rustenburg is now working on extending it.

Here's a stab at an updated proposed format.
- We augment the `<Residue>` block with `<TitrationStates>` block that lists two or more `<TitrationState>` entries that individually correspond to a single protomer or tautomer.  The original draft used `<TitratableResidue>` but then we would need special machinery to handle the normal setup and parameterization.
- The `<Atom>` elements define the residue in a default titration state index corresponding to a specified `defaultTitrationState` attribute, including dummy atoms for any atoms that might be switched on in any protomer/tautomer state.
- Each `<TitrationState>` optionally specifies a `proton_count` attribute (otherwise assumed to be "0") that is used in computing the acceptance probabilities given the current pH for protonation states.  Pure tautomers do not need to specify a proton_count, since it will be assumed "0" for all specified states.
- Each `<TitrationState>` optionally specifies a `pKa` attribute that is used in the acceptance/rejection for protonation state changes; this is assumed to be "0" if omitted (for pure tautomers).
- Each `<TitrationState>` specifies a list of `<Atom>` entries that contain a `name` attribute (that matches an atom name defined in the residue) and optionally other attributes used to specify how `charge`, `sigma`, and `epsilon` parameters differ in the different protomer/tautomer states.  Future extensions may also specify AMOEBA multipoles, etc.  Not all atoms have to be matched---only a subset could be modified by the titration state; the default parameters defined by the initial `<Atom>` elements in the residue are assumed for all other atoms for which the `<TitrationState>` entry does not define overrides.

Here's an example:

``` XML
 <Residue name="HIS" defaultTitrationState="0">
   <Atom name="N" type="N"/>
   <Atom name="H" type="H"/>
   <Atom name="CA" type="CT"/>
   ...
   <Bond fromName="N" toName="H"/>
   <Bond fromName="N" toName="C"/>
   ...
   <ExternalBond fromName="N"/>
   <ExternalBond fromName="C"/>
  <TitrationStates>
     <TitrationState proton_count="2">
         <Atom name="N" charge="+0.124616"/>
         ...
     </TitrationState>
     <TitrationState proton_count="1" pKa="6.5">
         <Atom name="N" charge="+0.124616"/>
         ...
     </TitrationState>
     <TitrationState proton_count="1" pKa="7.1">
         <Atom name="N" charge="+0.124616"/>
         ...
     </TitrationState>
  </TitrationStates>
  </Residue>
```

I'm still trying to sort out whether the `pKa` attribute is simple enough to capture what we need to for residues with multiple coupled titration states.

Comments/feedback welcomed!

**Comment by jchodera** [comment]
One issue I realize I neglected: Calibration of the reference energies (the relative free energy among titration states in the given solvent) must be carried out for any particular choice of solvent model, forcefield, and choice of nonbonded parameters.  We also therefore need a way to define what the standard "calibration" form of the residue is.  For small molecules that do not have `<ExternalBond>` elements, this is just the residue itself.  For polymeric residues like peptides, however, this is generally done with capping groups, such as `ACE` and `NME`.  We would need some way to either specify what capping residues should be used, or some way to specify what form of the residue should be used for calibration.

**Comment by peastman** [comment]
This doesn't make sense to me.  I think there must be some pieces missing.

The job of a ForceField is to construct a System.  Once the System is created, its job is done, and the ForceField no longer has anything to do with the simulation.  Constant pH simulations are not about how you construct a System.  They're about how that System changes over the course of a simulation.

Yes, there a some issues it needs to deal with.  If any dummy atoms are needed, the ForceField needs to add them.  But most of the work of running a constant pH simulation is outside the scope of a ForceField.  What is it that does that?

**Comment by jchodera** [comment]
I should comment on how I envision this to work:
1. The user prepares the system using `Modeller`, using the `addHydrogens` method and the `variants` argument to identify the desired titratable residues in their fully protonated forms (e.g. `AS4`, `GL4`, `CYS`, `THR`, 'HIP', 'LYS', 'DAP', 'DCP', 'DG', 'DT', 'AP', 'CP', 'G', 'U').  We can add a flag to make every titratable residue fully protonated for convenience.
2. The user includes a modified form of the residue definition file (e.g. `amber99sbildn.xml`) that contains titratable residue definitions (`amber99sbildn-titratable.xml`).  Alternatively, we could decide that we want to define just the titratable residues in a separate XML file and allow these to override previous definitions.
3. `ForceField` prepares the system as normal using only the normal `<Atom>` elements, creating a usable system in the default protonation state.

Subsequent steps depend whether we will be doing this in Python or at the C++ API level.

At the Python level, we can add some objects that allow one to use the standard API, something like:
```python
mc_titration = MonteCarloTitration(system, topology, variants, ffxml_files, context, temperature, pH)
...
for iteration in range(niterations):
    integrator.step(nsteps)
    mc_titration.update()    
```
or we could fold this into the `Simulation` class (which gives downstream applications like YANK less flexibility):
```python
simulation = Simulation(topology, system, integrator)
simulation.useMonteCarloTitration(forcefield=forcefield, pH=7, temperature=300*kelvin, updateInterval=50)
simulation.step(nsteps)
```
We could fold this into the C++ API with a `MonteCarloTitration` `Force` object, much like `MonteCarloBarostat`, where configuring the force would look something like this:
```python
from simtk.openmm import MonteCarloTitration
force = MonteCarloTitration(pH=7, temperature=300*kelvin, updateInterval=50)
for titratable_group in range(ngroups):
    force.addTitratableGroup(atom_indices[titratable_group])
    for titration_state in range(nstates[titratable_group]):
        force.addTitrationState(titratable_group, pKref[titratable_group][titration_state], relative_energy[titratable_group][titration_state], charges[titratable_group][titration_state], proton_count[titratable_group][titration_state])
    force.setTitrationState(default_titration_state[titratable_group])
system.addForce(force)
```
but convenience methods would be provided to use the `ffxml` files to do this automatically inside `Simulation`.  The `addTitrationState` is the least well-developed method, since we may want to allow more than `charge` to change (e.g. `sigma` and `epsilon` too).  This approach needs the most refinement, especially if we want to allow explicit solvent constant pH, but it would fit into the same spirit as `MonteCarloBarostat`.

**Comment by jchodera** [comment]
> This doesn't make sense to me. I think there must be some pieces missing.
> The job of a ForceField is to construct a System. Once the System is created, its job is done, and the ForceField no longer has anything to do with the simulation. Constant pH simulations are not about how you construct a System. They're about how that System changes over the course of a simulation.
> Yes, there a some issues it needs to deal with. If any dummy atoms are needed, the ForceField needs to add them. But most of the work of running a constant pH simulation is outside the scope of a ForceField. What is it that does that?

It appears I was typing the answer to some of what you were asking as you made this comment!

I think I simply neglected to set this proposal in context: Yes, most of the work in a constant-pH simulation happens after the `ForceField` creates a `system` object.  But we need to specify some additional information about how titration states are defined in order to do that.

Here's the main point:

**We can either specify all of this metadata in a completely separate file and duplicate a lot of machinery for reading this additional data, or we can make some small extensions to the `ffxml` format and keep all the related data together and make maximum reuse of code.**

This proposal presumes we want to keep the related data together in a `<Residue>` definition (which seems completely logical to me, since we are just specifying variants of the same residue) and make maximum reuse of the `Modeller` and `ForceField` machinery.


 **but we still need to make a few changes to extend the `ffxml` method

**Comment by jchodera** [comment]
I should also note that the prototype we have in https://github.com/choderalab/openmm-constph currently only handles reading AMBER `prmtop`/`inpcrd` systems along with `cpin` files generated via the `cpinutils` script from @swails.  This proposal is an attempt to move beyond that limitation by bringing the ability to create constant-pH simulations into the `simtk.openmm.app`, rather than requiring the user to go through AMBER to set things up (which can be a pain).

**Comment by peastman** [comment]
Let's focus first on the MonteCarloTitration object.  What exactly does it do?  Obviously it needs to change the charges of atoms, but anything beyond that?  In particular:

- Does it need to change any other parameters, like LJ or bonded parameters?
- Does it need to work with implicit solvent?
- Does it need to work with custom forces?
- Does it need to work with AMOEBA?

Also, how often will it attempt changes?  That will have a big impact on how efficient it needs to be, which will affect what types of implementations are acceptable.

By the way, is "titration" really the standard term used for this feature in MD packages???  I would have no idea what the name "MonteCarloTitration" meant.  If I were forced to guess, I would speculate it maybe had something to do with changing properties of the solvent.  But I certainly wouldn't have thought it meant changing the protonation states of sidechains.

**Comment by swails** [comment]
> Does it need to change any other parameters, like LJ or bonded parameters?

Ideally, yes.

> Does it need to work with implicit solvent?

Yes.

> Does it need to work with custom forces?

Yes.

> Does it need to work with AMOEBA?

Ideally at some point this would be very cool (and a truly unique functionality).

> Also, how often will it attempt changes?

This is a tunable parameter.  In Amber in implicit solvent, I have it attempt changes to a *single* residue (on rare occasion, two residues simultaneously) every ~5 steps.  In explicit solvent, it attempts changes to every residue sequentially in random order every 100-500 steps, since the explicit solvent exchange attempts are a lot more expensive.

> By the way, is "titration" really the standard term used for this feature in MD packages???

Definitely.

> I would have no idea what the name "MonteCarloTitration" meant.

Anybody familiar with the field of constant pH simulations would know what it meant.  What you're *really* doing during titration is probing the ionization equilibrium for a molecule (or in this case, a side-chain).  That's exactly what the `MonteCarloTitrator` is doing (I prefer that to `MonteCarloTitration`, myself).

**Comment by swails** [comment]
So what this force needs to be able to do is take a set of residues and a set of states for each of those residues, as well as a set of Forces it needs to modify.

Each of those states will need associated with it a reference energy, the total proton count for that state, and then a list of `Force`s that it will need to modify, the subset of those parameters it needs to modify, and the *new* values of those parameters it needs to add for those `Force`s.

If you can generalize that somehow, then it will have everything you need to do custom forces, `AmoebaMultipoleForce`, etc.

**Comment by jchodera** [comment]
@swails has addressed some of these questions already, but I want to answer in detail so there is no potential for confusion.

> Let's focus first on the MonteCarloTitration object. What exactly does it do? Obviously it needs to change the charges of atoms, but anything beyond that? In particular:
> Does it need to change any other parameters, like LJ or bonded parameters?

As @swails points out, at minimum, it must change charges, but it would be ideal if it could also change other parameters.  Nonbonded parameters are the biggest candidate (charge, sigma, epsilon), but for research purposes, it would also be good if we could support the modification of other parameters.

> Does it need to work with implicit solvent?

Absolutely.

> Does it need to work with custom forces?

Ideally, yes.

> Does it need to work with AMOEBA?

Again, ideally, yes.  Mike Schnieders is working on this within FFX, but it would be great to eventually carry that into OpenMM as well.

> Also, how often will it attempt changes? That will have a big impact on how efficient it needs to be, which will affect what types of implementations are acceptable.

Approximately as often as `MonteCarloBarostat`, as @swails points out.  However, if this would be highly inefficient, we could set the update frequency long enough to minimize impact on sampling efficiency.

> By the way, is "titration" really the standard term used for this feature in MD packages??? I would have no idea what the name "MonteCarloTitration" meant. If I were forced to guess, I would speculate it maybe had something to do with changing properties of the solvent. But I certainly wouldn't have thought it meant changing the protonation states of sidechains.

"Titration" certainly immediately brings to mind the concept of changing protonation states to anyone who has taken a physical chemistry course.

I wanted to choose a general term to encompass the fact that different protomers or tautomers can be selected by the facility.  `MonteCarloTitration` or `MonteCarloTitrator` are both decent, but could potentially be improved.  `ChemicalMonteCarlo` might be another choice, since in principle, we can extend this facility for use in the kind of Monte Carlo sampling over chemical species that @pgrinaway is working on if we can also control how the bias on each chemical species is computed in the acceptance criteria.

My [proposed API for `MonteCarloTitration`](https://github.com/choderalab/openmm-constph/blob/master/constph.py#L370-L734) was focused on the ability to just change charges, but it would be ideal if we could also more generally modify forces.  How to specify this in a straightforward manner---as well as make it efficient---is a more difficult question.

**Comment by peastman** [comment]
So this needs to be pretty general.  If it's written in C++, that means having hardcoded support for every force it can work with.  At a minimum, it sounds like that includes NonbondForce, CustomNonbondedForce, GBSAOBCForce, CustomGBForce, AmoebaMultipoleForce, and AmoebaGeneralizedKirkwoodForce.  Maybe also AmoebaWCADispersionForce?  Then what about bonded parameters?  What does it need to support?

If it's written in Python, we can support lots of these in a more generic way.  Simply require the force to have an appropriate set of get/set methods for parameters, plus an updateParametersInContext.

The difference in efficiency between Python and C++ largely depends on how many atoms get modified.  If you're only modifying a handful of them, looping over them in Python won't be a lot more expensive than C++.  But if you modify hundreds or thousands at a time, the difference will become quite significant.

**Comment by jchodera** [comment]
There is another complication here that came up in our in-person discussions: To permit explicit solvent constant pH, we will want to allow NCMC-like switching between protonation states, where dynamics is integrated for `nsteps` using a symplectic integrator and the parameters are switched from one protomer/tautomer to another.  The final configuration is accepted/rejected with a Metropolis-like criteria.

I'm not yet sure if this will be easy or hard to work into the C++ API.  

We've been considering alternative ways to do this at the Python level.  One of them is based on a [multitopology alchemical approach](https://github.com/choderalab/examol/blob/master/examol/multitopology/multitopology.py), where for each residue with multiple protomer/tautomer states, we would append all atoms for each protomer/tautomer to the system.  This would allow us to define different `charge`, `sigma`, and `epsilon` parameters for each protomer/tautomer variant, along with different bonded terms if needed.  We would need to handle switching between them with `Custom*Force` terms, but this is similar to what we do for alchemically-modified systems anyway.

Each residue would have a few context parameters associated with it:
* `alchemical_variant_[resid]` would be an integer that would select either a shared scaffold (0) or a distinct protomer/tautomer variant (1...N)
* `alchemical_lambda_[resid]` would be a real number in [0,1] that would allow the protomer/tautomer variant to be turned fully on (1) or off (0), or somewhere in between

There are some details that ensure only one set of valence terms are active at once, but those are details that are straightforward to work out.

We would build some machinery in Python to construct the appropriate multitopology system and handle the switching between protonation states during dynamics.  Without support for multiple simultaneous integrators, we would be limited in what kind of integration we could support: Essentially, we could build a Langevin integrator based on VVVR that would carry out Langevin dynamics normally and velocity Verlet during NCMC switching, but it would be harder to support more beyond that without support for multiple integrators associated with the same `Context`.

This approach also has other drawbacks: Because of the duplication of atoms, it might just look weird if you try to write out trajectories, so we'd need some other code to support making sensible representations of the systems.

**Comment by peastman** [comment]
I'm getting back to this issue again.  Rereading the most recent comments, it looks like the following are the main requirements.

1. CompoundIntegrator (#1196) will be important for implementing this, so that should probably be a top priority.

2. It needs to be able to modify many different parameters of many different forces.  It's hard to even come up with a complete list of all of them.

3. The number of atoms changed in any one MC move will be fairly small.  Usually less than 10 I would guess?

4. MC moves will be attempted on the order of once every 100 time steps or so.

Is that all correct?

If those are the actual requirements, a Python implementation seems like the best approach.  The overhead when modifying parameters should be small, and it will be much easier to support arbitrary parameters of arbitrary forces.

**Comment by jchodera** [comment]
OK, @bas-rustenburg and I will forge ahead with a Python implementation for
now.

Would it make sense to aim to bring this into the app.Simulation layer?

Also, can you comment on the overhead incurred by
updateParametersInContext?  We are still trying to figure out which scheme
we will need to use---context parameters and CustomForce objects or
changing parameters directly with updateParametersInContext---for explicit
solvent.  Only a small number---maybe tens of particles --- will have their
parameters changing this way.

**Comment by peastman** [comment]
updateParametersInContext() is far less expensive than creating a new context, but it's certainly not free either.  I suggest benchmarking it.  Try running a simulation, then adding a call to updateParametersInContext() after every step, or every 10 steps, or every 100 steps, and see how much that slows it down.

**Comment by swails** [comment]
An idea to get around needing `updateParametersInContext` is to offload the changing parameters to a CustomForce and encode all of the new parameters in lookup tables.  The state can then be set and switched via global variables that are easy and cheap to modify (it's only uploading a single number to the device, rather than *all* of the charges and L-J interactions.

The main impediment here is that when you give up `NonbondedForce`, you lose PME.  So if we could find some way to get the benefits of `CustomNonbondedForce` with standard electrostatic PME, that could be a win (not only for this, but also for TI in Yank).

**Comment by jchodera** [comment]
> An idea to get around needing updateParametersInContext is to offload the changing parameters to a CustomForce and encode all of the new parameters in lookup tables. The state can then be set and switched via global variables that are easy and cheap to modify (it's only uploading a single number to the device, rather than all of the charges and L-J interactions.

Can you elaborate on how the lookup tables would work for, say, charges and LJ parameters?  We haven't used those yet.

Our current idea for using `CustomForce`s was to *duplicate* every atom that would have multiple parameters and use context parameters to switch different variants on and off (in a softcore way).  A model of this is seen [here](https://github.com/choderalab/examol/blob/master/examol/multitopology/multitopology.py#L205).

**Comment by jchodera** [comment]
> The main impediment here is that when you give up NonbondedForce, you lose PME. So if we could find some way to get the benefits of CustomNonbondedForce with standard electrostatic PME, that could be a win (not only for this, but also for TI in Yank).

YANK's alchemical facility was recently split out into [alchemy](https://github.com/choderalab/alchemy) so we could use it in more projects.  Our current workaround for YANK is to at least handle the [direct-space component](https://github.com/choderalab/alchemy/blob/master/alchemy/alchemy.py#L819-L830) as a `CustomNonbondedForce`, meaning only the reciprocal-space contribution is omitted.  That means we still need to use real unmodified systems at the "endpoints" of alchemical free energy calculations.  That wouldn't easily work for the constant-pH scheme, however.
