### ISSUE TITLE
No XTCReporter in OpenMM?

### ISSUE THREAD

**Issue by jadeshi** [openmm/openmm#1186]
Sorry if this is a really dumb question, but can OpenMM output xtc trajectory files? I only found reporters for pdb and dcd format. Thanks!

**Comment by rmcgibbo** [comment]
No, there's no XTC reporter.

**Comment by swails** [comment]
If you write a Reporter class, you can have OpenMM write *any* kind of trajectory.  `simtk.openmm.app` only comes bundled with 3 trajectory reporter classes (PDB, DCD, and PDBx/mmCIF).  However, you can find implementations of other reporters as well.  For instance, you can use MDTraj's `NetCDFReporter`, `HDF5Reporter`, or `DCDReporter` classes, or you can use ParmEd's `NetCDFReporter` or `MdcrdReporter` classes.

MDTraj is probably the easiest way to get started writing an XTCReporter class if you wanted to give it a try.  It has an `XTCTrajectoryFile` class that you can use to build a new reporter from (and the existing reporter classes in MDTraj can serve as helpful examples).

**Comment by peastman** [comment]
No plans to add this.  MDTraj already provides a XTCReporter that should work fine.
