### ISSUE TITLE
Set nvcc path at build time?

### ISSUE THREAD

**Issue by rmcgibbo** [openmm/openmm#1189]
Currently the path to nvcc is either set by the `OPENMM_CUDA_COMPILER` env variable or it's `/usr/local/cuda/bin/nvcc` https://github.com/pandegroup/openmm/blob/master/platforms/cuda/src/CudaPlatform.cpp#L120-L122. The build system has a `CUDA_NVCC_EXECUTABLE` variable. I think we can use that to set the default.

**Comment by rmcgibbo** [comment]
If it makes sense to do this with cmake's `configure_file`, I think I can implement it.

**Comment by jchodera** [comment]
+1

**Comment by swails** [comment]
+1 for building from source. -1 for the binaries we build and distribute. 

Can that distinction be made?

**Comment by mpharrigan** [comment]
Make sure the build machines have nvcc at /usr/local/cuda/bin/nvcc?

**Comment by swails** [comment]
That's one way :). Is it, though?

**Comment by peastman** [comment]
This makes me nervous.  The default value is documented, and I'm worried about what will happen with different versions floating around with different values for it.  And sooner or later, there *will* be a case where an official binary ends up getting the wrong path compiled into it, and then it will fail on users' machines.

**Comment by rmcgibbo** [comment]
How about on only using the path set at build time if the file exists and is executable, otherwise using the /usr/local path?

**Comment by rmcgibbo** [comment]
Or just search the PATH. It would be nice not to require special openmm env variables to be set (which we've mostly eliminated so far with plugin loading)

**Comment by swails** [comment]
But this one should be largely temporary.  CUDA 7+ eliminates the need for this environment variable altogether with real JIT capabilities (currently implemented through the CUDA compiler plugin).

Maybe it's worth seeing if we can pick a more sensible default (I like the idea of using `/usr/local/cuda/bin/nvcc` as a fallback if the build-time version is not there) and just wait it out, letting the environment variable go away on its own?

**Comment by rmcgibbo** [comment]
It's really like 5 line change. Lots of machines won't have Cuda 7 for a while.

**Comment by boegel** [comment]
I was very surprises that OpenMM defaults to trying to use `/usr/local/cuda/bin/nvcc` rather than just `nvcc`...

Why isn't `nvcc` the default value, while allowing to specify a specific `nvcc` via `$OPENMM_CUDA_COMPILER`? That would make a lot more sense imho...

Right now I get around by simply setting `OPENMM_CUDA_COMPILER=nvcc`, which works fine.

**Comment by peastman** [comment]
Defaulting to `nvcc` would only work if the user had specifically added it to their `PATH`.

**Comment by boegel** [comment]
I would say most people have `nvcc` available via `$PATH` already, and I'm pretty sure it's way more likely to have `nvcc` available via `$PATH` than to have it installed in `/usr/local/cuda/bin/nvcc`...

**Comment by jchodera** [comment]
I'm with @boegel here: Most cluster environments use some module management scheme that puts the currently active CUDA version of `nvcc` in their `PATH`.

What about trying to use `nvcc` first and falling back to `/usr/local/cuda/bin/nvcc` if `nvcc` is not in the `PATH`?

**Comment by peastman** [comment]
This issue is no longer relevant, because we no longer use nvcc.

**Comment by boegel** [comment]
@peastman Any source for more info to what's being used instead?

**Comment by peastman** [comment]
We use nvrtc.  That's been the default behavior for a long time, but we still supported nvcc as a fallback.  But that caused more problems than it solved.  See #4105.
