### ISSUE TITLE
Consider dropping support for Windows with Python < 3.5

### ISSUE THREAD

**Issue by rmcgibbo** [openmm/openmm#1246]
We currently support Win-64 with Python 3.3+. We should consider bumping that up to 3.5+.

Whereas 3.3 and 3.4 are built with Visual Studio 2010, Python 3.5 is build with Visual Studio 2015, which has essentially full C++11 support. Dropping support for Python 3.3 and 3.4 on Windows, would, I think, remove the only remaining barrier from using C++11 in OpenMM, which would be really convenient.

**Comment by swails** [comment]
+1

**Comment by jchodera** [comment]
No objections.

**Comment by mpharrigan** [comment]
+1

**Comment by peastman** [comment]
Long term, I definitely would like to do this.  For the short term, though, I wonder if it would be better to add Python 3.5 support in 7.0, then wait until the next release to drop 3.3 and 3.4 support.  It's less disruptive for users if we give them some time to migrate.

**Comment by jchodera** [comment]
Can't we let them know now that there would be no 3.3/3.4 support in 7.0?  That's presumably at least a couple of months of warning.

7.0 is a major version number change anyway, so it should be less disruptive to make a change like this.

Simplifying and automating the win build chain would be a big win.

**Comment by peastman** [comment]
Our supported versions have moved on since this issue was opened.
