### ISSUE TITLE
OpenCL FFT performance comparison

### ISSUE THREAD

**Issue by swails** [openmm/openmm#1247]
@peastman -- have you seen this project: https://github.com/clMathLibraries/clFFT

Any ideas how it compares with your FFT here?

**Comment by peastman** [comment]
I've seen it, but I've never tried it out.

**Comment by swails** [comment]
OK -- just curious.

**Comment by peastman** [comment]
Let's keep this open.  It's definitely something we should investigate at some point.  I just haven't done it yet.

**Comment by swails** [comment]
Fair enough, I just didn't want to be the one to contribute to the clutter :)
