### ISSUE TITLE
Automated builds for Windows

### ISSUE THREAD

**Issue by peastman** [openmm/openmm#1266]
For the next OpenMM release, it would be really nice if we could have automated builds for Windows.  The last few releases have had automated builds for Mac and Linux, but we've had to do the Windows ones by hand.  What would it take to get those automated as well?

**Comment by rmcgibbo** [comment]
- Off the top of my head, the main question is the (virtual) hardware. What box do we do the builds on? We currently can do testing on Appveyor, but don't have CUDA or OpenCL there so it's not suitable for releases.
- Writing the script that runs the build is not particularly challenging. E.g. for conda-build, we have https://github.com/omnia-md/conda-recipes/blob/master/openmm/bld.bat. Producing other types build artifacts (`python setup.py bdist_wheel`, `python setup.py bdist_msi`, etc) is nothing major.

**Comment by jchodera** [comment]
I wonder if we should be migrating our builds to travis/appveyor build matrix branches, where we have build artifacts pushed to an S3 bucket.  We could limit our builds to tagged releases, but it may be useful to be able to multiple candidates.

**Comment by rmcgibbo** [comment]
I don't see how that's going to work with Windows, without CUDA and OpenCL on Appveyor.

**Comment by jchodera** [comment]
Ah, good point. I hadn't realized there wasn't a way to install those on appveyor, though someone has a suggestion asking CUDA be provided: https://github.com/appveyor/ci/issues/342

**Comment by rmcgibbo** [comment]
I wouldn't hold my breath.

**Comment by dr-nate** [comment]
Can I rehash an old thread? https://github.com/pandegroup/openmm/issues/1117 

It looks like Azure now supports GPUs as of Sept 29: 
https://azure.microsoft.com/en-us/documentation/videos/azurecon-2015-applications-that-scale-using-gpu-compute/
http://www.hpcwire.com/2015/09/29/microsoft-puts-gpu-boosters-on-azure-cloud/

Could you now use Jenkins on Azure?

**Comment by jchodera** [comment]
Could this scheme be used to at least do automated OpenCL builds in AppVeyor?
https://github.com/clMathLibraries/clFFT/blob/master/appveyor.yml

**Comment by rmcgibbo** [comment]
Yeah, that could work.

**Comment by peastman** [comment]
This seems like a good time to revive this thread.  Do we have any good options for building Windows releases in an automated way?  The machine doesn't need to have a GPU.  It just needs to be able to build and package releases that we can test elsewhere.

**Comment by rmcgibbo** [comment]
- Yes, we have the ability to automate the building and deployment with `conda` on Windows. We have all the tools and scripts for this, and they run, sometimes successfully and sometimes unsuccessfully on Windows on Appveyor-CI.
- But, we do not have any solution for automatically _provisioning_ a Windows machine that has the CUDA headers / libraries installed. I could not figure out how to install CUDA on Windows on Appveyor, because you need to use a GUI graphical installer.

The possible solutions are to:
 - Figure out how to get the CUDA headers / libraries onto Appveyor
    * If nothing else, it might be possible for someone to install CUDA onto their desktop, `zip` up the install directory, and then post it on the web. :)
 - Or, figure out a different Windows infrastructure, like using Azure or AWS.

Personally, I've sunk too much time into this stuff already, and have some other higher priority stuff right now (graduating) so don't count on me for this one.

**Comment by peastman** [comment]
This doesn't need to be on Appveyor or any other cloud provider.  This isn't for CI.  It's just to build releases once every few months.  We also need to be able to do the zip installers, not just the conda ones.

Is there some way we can automatically provision a Windows VM?

**Comment by rmcgibbo** [comment]
>  This doesn't need to be on Appveyor or any other cloud provider.

Maybe I'm not clear about the requirements then. What's wrong with just building on your workstation then? Is the only problem that we don't have scripts that do things automatically?

**Comment by peastman** [comment]
It's not well controlled and reproducible.  Ideal would be something that automatically builds and provisions a VM, then does the build inside that.  I believe that's how the Linux and Mac builds are done?

**Comment by rmcgibbo** [comment]
> Ideal would be something that automatically builds and provisions a VM, then does the build inside that.

Right, so someone needs to figure out how to do that. I could be a VM running on local hardware (Virtualbox), or on cloud hardware.

IMO, the best solution, if you want to do this, is to log into AWS, start a Windows machine, remote desktop in, set up everything the way you like it (Visual Studio, CUDA, AMD APP SDK) and then freeze it as an [AMI](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AMIs.html) and save that in your AWS account.

And then boot up a fresh instance from that AMI for every build (and then throw away the instance right afterward). And if you want, this could probably scripted, assuming you install an ssh daemon into your AMI.

**Comment by peastman** [comment]
One other thing that would be really nice for both the conda and zip installers: can we include a version for Python 3.5 built with Visual Studio 2015?  That's the first step toward eventually dropping support for earlier Python versions on Windows, which would allow us to finally use C++11.

**Comment by rmcgibbo** [comment]
Yes, I agree. (cc: #1246)

**Comment by peastman** [comment]
Windows builds are now automated.
