### ISSUE TITLE
test script providing info why platforms are (not) available [feature request]

### ISSUE THREAD

**Issue by jhprinz** [openmm/openmm#1268]
I thought about this for a while now.Background is that I used to not install OpenMM using conda, but had it compiled from source and I have a machine with Nvidia graphics card. At some point (after OS X upgrade and upgrade of CUDA) currently only `CPU` and `OpenCL` work while before usually only `CUDA` and `CPU` worked. Right now I assume that my CUDA version is incomaptible or so, but I don't know. I also had points where old installation even broke the CPU. 

Besides me messing the installation up: Is it possible to add a part in the `test.py` that does not simply list the installed platforms, but also lists why other platforms are (potentially) not available? Examples would include the things that are also listed in the manual, like
- missing CUDA Toolkit, drivers
- missing set PATH variables
- cannot find dylib xyz...
- your machine supports CUDA, please install ... from ...

I think the common mistakes are not too many to make certain platforms work and a hint in the test.py would be VERY helpful.

**Comment by rmcgibbo** [comment]
If you have any ideas how to extract and parse the relevant information, I'm all ears. The best current tool is `Platform.getPluginLoadFailures`, which gives the error strings returned by the OS (`dlopen`), but figuring out the root cause is nontrivial.
