### ISSUE TITLE
customgbforces don't automatically convert to appropriate units

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#1277]
This is not particularly worrisome because this is in `simtk.openmm.app.internal`, but the [`customgbforces.py`](https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/internal/customgbforces.py) force implementations don't automatically convert function arguments like `cutoff` to the appropriate MD unit system before including their contents in expressions, e.g. [this line](https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/internal/customgbforces.py#L198):

``` python
    if cutoff is not None:
        params += "; cutoff=%.16g" % cutoff
```

It would be good to overhaul these files to automatically convert value-carrying units to the appropriate unit system (e.g. `cutoff.value_in_unit_system(unit.md_unit_system)`) and to thoroughly document all arguments to facilitate reuse in other components of OpenMM.

Do we also have some internal automated tests of these implementations?  If not, we might want to pull those in at some point.

**Comment by swails** [comment]
Is the unit conversion done in the calling functions (e.g., `CharmmPsfFile` and `AmberPrmtopFile`)?

**Comment by peastman** [comment]
As currently written, it expects a number, not a Quantity.  If you passed a Quantity, the string substitution would produce a nonsense expression and you would get an exception when you tried to create the Context.

**Comment by jchodera** [comment]
There is really no danger here right now. I was just flagging wanting to
clean these up for future reuse as we are overhauling the ffxml
parameterization scheme to also allow for better GB mix and match with
small molecule support.

@swails: Did you have some GB validation code sitting around?

**Comment by ctk3b** [comment]
It's been a long time since this was touched but the (inelegant) code that I originally used to validate the implementations against AMBER is still living [here](https://simtk.org/home/gbmodels/). Running the full comparison for the set of 504 molecules is probably impractical for the unit testing setup but perhaps a subset of them?

However, replicating these tests would necessitate calling sander which may be undesirable.

**Comment by swails** [comment]
> @swails: Did you have some GB validation code sitting around?

Nothing general, but I could whip something up without much problem.  I've validated all of the implementations, though ([you can see the comparisons in the ParmEd tests](https://github.com/ParmEd/ParmEd/blob/master/test/test_openmm_amber.py#L226-L398)).  The worst agreement occurs between Amber and OpenMM with igb=7 and 8 where the radii are randomized and do not land on one of the vertices of the lookup table (the interpolation scheme differs between OpenMM and Amber).  The remaining comparisons are quite good.

It would only take a handful of lines of Python (with ParmEd) to write a script to compare OpenMM GB and Amber GB energies and forces.  Something like the following:

```Python
import parmed as pmd
import simtk.openmm.app as app
import sander

parm = pmd.load_file('prmtop', 'inpcrd')
inp = sander.gas_input(1) # HCT model
with sander.setup(parm, parm.coordinates, None, inp):
    e, f = sander.energy_forces()
system = parm.createSystem(implicitSolvent=app.HCT, nonbondedMethod=NoCutoff)
omm_e = pmd.openmm.energy_decomposition_system(parm, system)
```

Now you have a struct `e` with Amber energies and a list of tuples `omm_e` with OpenMM energies...  That's it.

**Comment by jchodera** [comment]
Thanks, @ctk3b and @swails!  This is super helpful.
