### ISSUE TITLE
New packaging/installers for OpenMM 7.0?

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#1309]
This might be a good opportunity to revisit the way we build installers and packages for OpenMM releases.

**Comment by peastman** [comment]
As far as features are concerned, I think we're ready to release the beta, so the installers are the only thing left to do.  What needs to be done?  Were there specific aspects of them you thought we should change?

**Comment by jchodera** [comment]
Is there some sort of open source cross-platform installer that could be easily harnessed to give a nice installation experience (with the ability to uninstall)?  I have very little experience with this.

Some options from quick searchin:
* lzPack: http://izpack.org
* InstallJammer: http://www.installjammer.com

The main goals, in my mind, would be:
* Convenient experience for user
* Eliminate need to manually futz with paths or environment variables
* Add some flexibility in install location
* Easy uninstall
* Minimal command-line stuff

On the other hand, I don't really use this route for installation, so I'm not really the target audience.  It's possible that users that *do* use this route have much more important feedback to consider?

**Comment by peastman** [comment]
At the meeting last week, we tentatively set the goal of eventually dropping the zip installers and relying entirely on the conda installers.  So I don't think it's worth putting a lot of work into completely redoing them if we're just going to drop them in another couple of versions.

**Comment by mpharrigan** [comment]
cpack (included with cmake) can generate native installers for a variety of targets easily. e.g. `.deb` or `.rpm` for linux and msi installers for windows

**Comment by jchodera** [comment]
If `cpack` is included with `cmake`, that at least sounds like a great idea.

It looks like `cpack` even supports multiple "package generators", which include [several options for `osx`](https://cmake.org/Wiki/CMake:CPackPackageGenerators#DragNDrop_.28OSX_only.29).
