### ISSUE TITLE
minimize is very slow

### ISSUE THREAD

**Issue by isjoung** [openmm/openmm#1321]
Hi,
First, I like to appreciate the efforts of developers for maintaining this nice project. Currently, I am using openmm for minimizing various conformations of a molecule. However, it seems that the native minimizer is very slow for some reason.

I have two examples below for comparing minimization methods. I used a single CPU thread.

The first one uses the native minimizer.

``` python
import os
os.environ['OPENMM_CPU_THREADS'] = '1'
from simtk.openmm.app import *
from simtk.openmm import *
from simtk.unit import *
import numpy as np

prmtop = AmberPrmtopFile('model.prmtop')
inpcrd = AmberInpcrdFile('model.inpcrd')
system = prmtop.createSystem(nonbondedMethod=NoCutoff,implicitSolvent=GBn2, nonbondedCutoff=999.0*nanometer, constraints=HBonds)
integrator = LangevinIntegrator(300*kelvin, 1/picosecond, 0.002*picoseconds)
simulation = Simulation(prmtop.topology, system, integrator)
simulation.context.setPositions(inpcrd.positions)
simulation.minimizeEnergy(tolerance=Quantity(value=10.0,unit=kilojoule/mole),maxIterations=20)
st = simulation.context.getState(getPositions=True,getEnergy=True)
print st.getPotentialEnergy()
```

The second one uses scipy's L-BFGS-B minimizer

``` python
import os
os.environ['OPENMM_CPU_THREADS'] = '1'
from simtk.openmm.app import *
from simtk.openmm import *
from simtk.unit import *
import numpy as np
from scipy import optimize

prmtop = AmberPrmtopFile('model.prmtop')
inpcrd = AmberInpcrdFile('model.inpcrd')
system = prmtop.createSystem(nonbondedMethod=NoCutoff, implicitSolvent=GBn2, nonbondedCutoff=999.0*nanometer, constraints=HBonds)
integrator = LangevinIntegrator(300*kelvin, 1/picosecond, 0.002*picoseconds)
simulation = Simulation(prmtop.topology, system, integrator)
pos = np.array( inpcrd.positions.value_in_unit(nanometer) )
con = simulation.context

def target_function(xyz):
    con.setPositions(xyz.reshape(-1,3))
    state = con.getState(getEnergy=True, getForces=True)
    frc = state.getForces(asNumpy=True)
    ene = state.getPotentialEnergy().value_in_unit(kilojoule_per_mole)
    frc = frc.value_in_unit(kilojoule_per_mole/nanometer)
    return ene, -frc.flatten()

results = optimize.minimize(target_function, pos, method='L-BFGS-B',
                            jac=True, options=dict(maxiter=20, disp=True, gtol=0.1))
```

This is the result

| measure | script1 | script2 |
| --- | --- | --- |
| Time | 2m9.3s | 30.5s |
| Energy | -7778.68 kJ/mol | -8693.76 kJ/mol |

The native minimizer is worse in terms of both speed and performance.
Can anyone tell me what could be wrong?

**Comment by rmcgibbo** [comment]
Can you try turning off the HBond constraints and see what happens? That makes it a lot trickier for the minimizer.

**Comment by isjoung** [comment]
Ok. no constraint helps. Now the time is 29.1s and the energy is -7784.99 kJ/mol. This is much better than the previous result.

Here is another experiments with various maxIter (no constraints)

script1

maxIter | time | energy
---- | ---- | ----
20 | 29.1s | -7784.99 kJ/mol
40 | 51.61s | -7919.85 kJ/mol
100 | 1m52.44s | -8140.16 kJ/mol

script2

maxIter | time | energy
---- | ---- | ----
20 | 26.33s | -7817.01 kJ/mol
40 | 47.37s | -7938.45 kJ/mol
100 | 1m49.93s | -8146.77 kJ/mol

Interestingly, with no constraint, the performance of the second one became lower.
Overall, the performance of the native minimizer is still slightly worse. BTW, I think the second script should be slower because coordinates are passed via the python-C++ interface. :( Or, am I overestimating the overhead?

**Comment by rmcgibbo** [comment]
Without constraints, they should be essentially the same (as they appear to be). The call overhead is not very significant. The only difference, I think, is slightly different versions of the L-BFGS(-B) library, which could have slightly different behavior in the linesearch or tolerance. When you look at the source code for LocalEnergyMinimizer, apart from dealing with the constraints, there's nothing fancy going on: https://github.com/pandegroup/openmm/blob/master/openmmapi/src/LocalEnergyMinimizer.cpp.

**Comment by peastman** [comment]
Are you sure it's actually using the CPU platform?  Try adding this line:

```Python
print(simulation.context.getPlatform().getName())
```

**Comment by swails** [comment]
> Are you sure it's actually using the CPU platform?

Presumably that shouldn't matter, though, right?  What @isjoung is comparing here is the scipy L-BFGS minimizer to `LocalEnergyMinimizer` in OpenMM with the same algo.  Based on the above timings, both scripts seem to be pulling the same platform, whatever it is...

**Comment by peastman** [comment]
Yes, but it's still good to know.  Especially because the script is setting `OPENMM_CPU_THREADS` and expecting that to have an effect.

**Comment by swails** [comment]
> Yes, but it's still good to know. Especially because the script is setting OPENMM_CPU_THREADS and expecting that to have an effect.

Ah, OK.  Just wondering if I was missing something obvious.

**Comment by isjoung** [comment]
```python
print(simulation.context.getPlatform().getName())
```
It prints 'CPU'
