### ISSUE TITLE
Problem with runtime linking on OS X El Capitan

### ISSUE THREAD

**Issue by jlmaccal** [openmm/openmm#1342]
The System Integrity Protection (SIP) feature in El Capitan prevents setting of all `DYLD_*` variables:

```
    % export DYLD_LIBRARY_PATH=foo   
    % env | grep DYLD_LIBRARY_PATH
    %
```

When I compile OpenMM from source (github) using a standard `ccmake`, `make install`, `make PythonInstall` workflow, OpenMM cannot load the CUDA plugin:

```
% ipython
'Error loading library /usr/local/openmm/lib/plugins/libOpenMMCUDA.dylib: dlopen(/usr/local/openmm/lib/plugins/libOpenMMCUDA.dylib, 9): Library not loaded: @rpath/libcufft.7.5.dylib\n  Referenced from: /usr/local/openmm/lib/plugins/libOpenMMCUDA.dylib\n  Reason: image not found',
 'Error loading library /usr/local/openmm/lib/plugins/libOpenMMRPMDCUDA.dylib: dlopen(/usr/local/openmm/lib/plugins/libOpenMMRPMDCUDA.dylib, 9): Library not loaded: @rpath/libOpenMMCUDA.dylib\n  Referenced from: /usr/local/openmm/lib/plugins/libOpenMMRPMDCUDA.dylib\n  Reason: image not found',
 'Error loading library /usr/local/openmm/lib/plugins/libOpenMMDrudeCUDA.dylib: dlopen(/usr/local/openmm/lib/plugins/libOpenMMDrudeCUDA.dylib, 9): Library not loaded: @rpath/libOpenMMCUDA.dylib\n  Referenced from: /usr/local/openmm/lib/plugins/libOpenMMDrudeCUDA.dylib\n  Reason: image not found',
 'Error loading library /usr/local/openmm/lib/plugins/libOpenMMAmoebaCUDA.dylib: dlopen(/usr/local/openmm/lib/plugins/libOpenMMAmoebaCUDA.dylib, 9): Library not loaded: @rpath/libOpenMMCUDA.dylib\n  Referenced from: /usr/local/openmm/lib/plugins/libOpenMMAmoebaCUDA.dylib\n  Reason: image not found',
 'Error loading library /usr/local/openmm/lib/plugins/libOpenMMCudaCompiler.dylib: dlopen(/usr/local/openmm/lib/plugins/libOpenMMCudaCompiler.dylib, 9): Library not loaded: @rpath/libnvrtc.7.5.dylib\n  Referenced from: /usr/local/openmm/lib/plugins/libOpenMMCudaCompiler.dylib\n  Reason: image not found'
```

Running `otool -L libOpenMMCUDA.dylib' gives:

```
libOpenMMCUDA.dylib:
    @rpath/libOpenMMCUDA.dylib (compatibility version 0.0.0, current version 0.0.0)
    @rpath/CUDA.framework/Versions/A/CUDA (compatibility version 1.1.0, current version 7.5.20)
    @rpath/libOpenMM.dylib (compatibility version 0.0.0, current version 0.0.0)
    /usr/local/cuda/lib/libcuda.dylib (compatibility version 1.1.0, current version 7.5.20)
    @rpath/libcufft.7.5.dylib (compatibility version 0.0.0, current version 7.5.20)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
    /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.1.0)
```

Running `otool -l libOpenMMCUDA.dylib` gives:

```
... snipped ...

Load command 11
          cmd LC_LOAD_DYLIB
      cmdsize 64
         name /usr/local/cuda/lib/libcuda.dylib (offset 24)
   time stamp 2 Wed Dec 31 17:00:02 1969
      current version 7.5.20
compatibility version 1.1.0
Load command 12
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name @rpath/libcufft.7.5.dylib (offset 24)
   time stamp 2 Wed Dec 31 17:00:02 1969
      current version 7.5.20
compatibility version 0.0.0

... snipped ...
```

It looks like for some reason, the load path is baked in for `libcuda`, but not for `libcufft`. Because we can't set `DYLD_*` anymore, there doesn't seem to be any way to allow the linker to find `libcufft`.

Is there some linker / cmake magic to properly encode the load path into the library? I believe there is also a similar problem with `libOpenMMCudaCompiler.dylib` and `libnvrtc`.

**Comment by rmcgibbo** [comment]
> The System Integrity Protection (SIP) feature in El Capitan prevents setting of all DYLD_* variables:

Noooooo!!!!

**Comment by rmcgibbo** [comment]
If you run `otool -l libOpenMMCUDA.dylib | grep LD_RPATH`, do you get any output?

**Comment by rmcgibbo** [comment]
sorry, `LC_RPATH`

**Comment by jlmaccal** [comment]
No output.

**Comment by jlmaccal** [comment]
Full output: https://gist.github.com/jlmaccal/233eb43b240ba90f326a

**Comment by rmcgibbo** [comment]
I don't think OpenMM does anything special with install_name_tool for `libOpenMMCUDA`, and the paths come from FindCUDA.cmake which is included with CMake. Do you know what version of CMake you're using?

**Comment by rmcgibbo** [comment]
What if you try `install_name_tool -add_rpath /usr/local/cuda/lib <path/to/libOpenMMCUDA.dylib>`?

**Comment by jlmaccal** [comment]
I was using 2.8.11, which is fairly ancient. But 3.3.1 gives the same results.

**Comment by jlmaccal** [comment]
OK, that works.

**Comment by rmcgibbo** [comment]
This seems like the same problem as http://stackoverflow.com/questions/32775344/dynamic-libraries-passed-to-the-linker-as-absolute-paths-being-loaded-by-relativ. I'm not sure what causes the linker to use the full path or the rpath-relative path.

**Comment by jlmaccal** [comment]
Actually, based on that page, it looks like it's an issue with how NVIDIA has compiled the libraries.

```
% otool -D libcuda.dylib                                                                                                       !1186
libcuda.dylib:
/usr/local/cuda/lib/libcuda.dylib

% otool -D libcufft.7.5.dylib                                                                                                  !1184
libcufft.7.5.dylib:
@rpath/libcufft.7.5.dylib

% otool -D libcudart.7.5.dylib                                                                                                 !1185
libcudart.7.5.dylib:
@rpath/libcudart.7.5.dylib
```

The two libraries causing problems are only built with relative names.

**Comment by peastman** [comment]
> The System Integrity Protection (SIP) feature in El Capitan prevents setting of all DYLD_* variables:

By the way, my understanding is that it's only "built in" applications and libraries that can't see those variables.  So the system python won't see them, but anaconda python will.  Not that it helps us much, since we certainly need to keep supporting the system python.

**Comment by jlmaccal** [comment]
That might be correct, but python scripts are typically launched with `/usr/bin/env`, which has those variables stripped. You also can't set it in `.bashrc` et al, because those are protected as well.

**Comment by rmcgibbo** [comment]
Perhaps that install_name_tool invocation should be added to the cmakelists

**Comment by peastman** [comment]
Perhaps we could edit libOpenMMCUDA.dylib either at build time or install time to make it contain an absolute path to libcufft?

I would guess the reason they've done it this way is that libcufft and libcudart are both supposed to be redistributable, whereas libcuda is always something they install.

**Comment by rmcgibbo** [comment]
> Perhaps we could edit libOpenMMCUDA.dylib either at build time or install time to make it contain an absolute path to libcufft?

Right. If you grep the code for install_name_tool, we already use it on some plugins so this should be similar.

**Comment by peastman** [comment]
CUDA is no longer supported on Mac, so this issue is obsolete.
