### ISSUE TITLE
Conda linux packages still being built with debug on?

### ISSUE THREAD

**Issue by nhstanley** [openmm/openmm#1394]
Hi all,

I'm still getting debug errors for some of the linux conda binaries (and perhaps I need to figure out what's causing them, but the fact is I shouldn't be seeing them on one platform and not another for the same system). Same error as [seen here](https://github.com/pandegroup/openmm/issues/1352#issuecomment-173006319). I don't get them on OS X. Is there a chance they're still being built with them on linux? I thought @jchodera fixed this [here](https://github.com/pandegroup/openmm/issues/1352#issuecomment-173073416).

I totally uninstalled all OpenMM versions from Conda and cleaned my `pkgs` directory, then downloaded [the file](https://anaconda.org/omnia/openmm/6.3.1/download/linux-64/openmm-6.3.1-py35_1.tar.bz2) directly and resinstalled, but I still see the error.

**Comment by jchodera** [comment]
Can you try installing `openmm-dev` instead and see if that also has the same issues?
```bash
conda remove --yes openmm
conda clean -pltis --yes
conda install --yes openmm-dev

**Comment by dr-nate** [comment]
Yup. Still getting them :-/

**Comment by dr-nate** [comment]
In case it matters, my OS X package is: openmm-6.3.1-py35_1.tar.bz2 (MD5: 5c68282063c2128bbe3911b657c58143)

**Comment by jchodera** [comment]
Totally stumped.

@peastman, what do we need to do [besides `-DCMAKE_BUILD_TYPE=Release`](https://github.com/omnia-md/conda-dev-recipes/blob/master/openmm-dev/build.sh#L6) to build OpenMM without debug messages on `linux`?

You can see the build logs [here](https://travis-ci.org/omnia-md/conda-dev-recipes/jobs/108302806) to diagnose what is going on during the build.

**Comment by peastman** [comment]
That should be all you need to do.  I notice in the build log:

```
CFLAGS: -g -O2 -fvisibility=hidden -I/hbb_exe/include
```

That's what I'd expect you to get if CMAKE_BUILD_TYPE were set to RelWithDebInfo.  When it's set to Release, you should get `-O3` instead of `-O2`, and no `-g`.

What are the values of the following CMake variables?

```
CMAKE_CXX_FLAGS
CMAKE_CXX_FLAGS_RELEASE
CMAKE_C_FLAGS
CMAKE_C_FLAGS_RELEASE
```

**Comment by jchodera** [comment]
I had it `cat CMakeCache.txt` on `linux` for you, @peastman:
https://travis-ci.org/omnia-md/conda-dev-recipes/jobs/108410004#L8732-L9377

**Comment by peastman** [comment]
That all looks correct.  I think the CFLAGS line I mentioned must refer to something else.  It's very early in the log (line 155), long before it starts compiling OpenMM.

**Comment by peastman** [comment]
Was this ever resolved?

**Comment by dr-nate** [comment]
No. I ran into this the other day and, after trying purging and reinstalling the latest, had to build from source to get around it. It was still a problem with both `openmm` and `openmm-dev` from anaconda.org.
