### ISSUE TITLE
OpenMM-Amoeba crashes

### ISSUE THREAD

**Issue by swails** [openmm/openmm#1427]
AMOEBA simulations still seem to have some subtle issues leading them to blow up with a fair amount of regularity.  It pretty reliably happens every few hundred thousand steps.  I suspect there is some kind of numerical instability somewhere in one of the AMOEBA forces still.

It happens with many integrators (Verlet and Langevin with a variety of friction coefficients) using the mixed precision model (we didn't test double precision since it was pretty slow).

You can [download the tarball with the necessary files here](https://www.dropbox.com/s/cajoswcr7jnb0c9/bugreport.tar.gz?dl=0) which has a run.sh file (the path to `runmd.py` is wrong, but the `runmd.py` script is included in the tarball).  It extracts one file to `OMM_Amoeba_Scripts/` and the rest to a `4yula_soln_amoeba/` directory.

Tagging @dacase so he can provide more information if necessary.  These calculations are run mainly on GTX 980 Ti cards, but the crashes also happen on GTX 980s.

**Comment by jchodera** [comment]
I wonder if checkpointing at a regular interval could let you resume from a checkpoint just before the explosion and produce a test that rapidly blows up for easier debugging.

**Comment by swails** [comment]
Already tried that.  It helps a little, but it certainly doesn't fail in the same place.  I didn't send a checkpoint file, though, since those are hardware specific.

**Comment by peastman** [comment]
I've had it running for several hours on a Titan X.  No errors yet after 250,000 steps.  I'll let it keep going and see what happens.

**Comment by peastman** [comment]
Since the earlier crashes were caused by errors in computing angles, I searched through the code for any uses of acos(), asin(), and atan() that weren't properly guarded.  I found one:

https://github.com/pandegroup/openmm/blob/master/plugins/amoeba/platforms/cuda/src/kernels/amoebaOutOfPlaneBendForce.cu#L44

It's not obvious to me whether that could ever actually cause problems, but maybe try sticking in a guard to clip the argument of asin() to [-1,1]?

**Comment by swails** [comment]
I saw that one back when I added guards for a bunch of other forces.  But the out-of-plane force shouldn't ever get far from ~0 degrees -- certainly not near 90...

I'll give that a shot tomorrow.  In the meantime, I created a reporter that looks at the energy every step and if it blows up or NaNs, it computes each component and reports each Force's energy.

Starting from a checkpoint, it fails almost immediately with a very large bond component, which seemed weird.  I'm starting from what I know to be a saner structure and I'll report what I see.  Fortuitously, the watchdog reporter only cuts the simulation speed roughly in half, so it should still be feasible.

**Comment by peastman** [comment]
I left it running all night.  Still no errors after more than 1.5 million steps.

**Comment by swails** [comment]
Dave and I are still working at generating a failure which should hopefully print out the offending `Force`.  We could probably also provide an account on our machine where crashes happen frequently.

As an aside -- do dipole convergence failures result in a thrown exception, or does it silently soldier on in CUDA?

**Comment by peastman** [comment]
It will just continue on, using whatever dipoles it had after the specified number of iterations.

**Comment by swails** [comment]
I wonder if that may be happening here.  Would it maybe make sense for OpenMM to print a warning to stderr if this happens?  It would be very helpful in debugging.

Anyway, I got some output from a simulation that blew up:

```
               AmoebaBondForce 6262.206601 kcal/mol
     AmoebaOutOfPlaneBendForce 124.027312 kcal/mol
              AmoebaAngleForce 3482.322965 kcal/mol
       AmoebaInPlaneAngleForce 527.488386 kcal/mol
        AmoebaStretchBendForce -13.341843 kcal/mol
          PeriodicTorsionForce 271.714683 kcal/mol
          AmoebaPiTorsionForce 58.888596 kcal/mol
     AmoebaTorsionTorsionForce -101.071430 kcal/mol
                AmoebaVdwForce 140594.569240 kcal/mol
          AmoebaMultipoleForce -101918.722574 kcal/mol
             HarmonicBondForce -153.255298 kcal/mol
               CMMotionRemover 0.000000 kcal/mol
                  Total Energy 205580.116720 kcal/mol
Bad energy! Look at components
```

Looks like a spurious collision...  Certainly doesn't look like the OOP bend is getting near the undefined region.  @peastman -- did it ever crash for you?  I'm not sure if/how we're supposed to tell whether this is just possible with the 14-7 potential (moreso than the 12-6) and it's only popping up now because we're running much longer with lower precision, or if it's a code issue.

I suppose one of the next things to try might be using double precision?

**Comment by dacase** [comment]
On Wed, Mar 23, 2016, Jason Swails wrote:

> 
> Anyway, I got some output from a simulation that blew up:
> 
> Bad energy! Look at components

My run on the same system (with a different starting point) is still going,
but this system usually blows up every 2-4 million steps.

Jason: do you have a way to getting the force components for an "ordinary"
step?  It looks to me like the vdW force is the culprit, but it may be
that other components (esp. the multipole force) are also out of whack.

...thx...dac

**Comment by swails** [comment]
> Jason: do you have a way to getting the force components for an "ordinary"
> step?  It looks to me like the vdW force is the culprit, but it may be
> that other components (esp. the multipole force) are also out of whack.

The energies, or also the actual forces on the atoms? (OpenMM calls everything a `Force`, so I'm not sure if you're just using OMM terminology or if you really want the atomic forces in a NetCDF file or something).

The energies would be pretty easy -- I'll modify the `OMM_Amoeba_Scripts/runmd.py` script to do that every time it uses the watchdog reporter.  I won't get to that until tomorrow night, though.  The forces are no harder, it would just take a little more time to implement.

**Comment by peastman** [comment]
If you want to verify whether that's what's happening, the relevant code is here: https://github.com/pandegroup/openmm/blob/master/plugins/amoeba/platforms/cuda/src/AmoebaCudaKernels.cpp#L1646.  You could make it print out something when it fails to converge after the maximum number of iterations.

None of the energies in your output look especially unreasonable.  Are they similar to what they were in other steps, or is there a significant change to any of them just before it fails?

What exactly did you mean when you said, "Certainly doesn't look like the OOP bend is getting near the undefined region?"  There isn't an undefined "region", and if you did all calculations to infinite precision you wouldn't see anything strange anywhere.  But in finite precision, numerical error can cause bad behavior at discrete points.  That was the behavior I saw with the earlier bugs in computing angles: the energy looked reasonable and showed no sign of anything going wrong right up until it abruptly became nan.

**Comment by swails** [comment]
The average potential energy for that system is ~-60K kcal/mol, and it doesn't fluctuate much.  So the energy jump here (entirely due to vdW) up to ~+205580.116720 kcal/mol represents over a 250K *kcal/mol* jump, which is over 1M kJ/mol.  That's highly anomalous.

And sorry, I meant "unstable" instead of "undefined"... :)

I guess I can just hack in a print statement if the dipoles don't converge.  But it would still be helpful to know when that happens in general, I think.

**Comment by dacase** [comment]
On Wed, Mar 23, 2016, Jason Swails wrote:

> > Jason: do you have a way to getting the force components for an "ordinary"
> > step?  It looks to me like the vdW force is the culprit, but it may be
> > that other components (esp. the multipole force) are also out of whack.
> 
> The energies, or also the actual forces on the atoms? 

I meant the energies.....dac

**Comment by peastman** [comment]
Ok, that makes sense.  Can you make it save a complete state when the energy jump happens?  Then we can see exactly what's causing it.

Something's not right with the energy breakdown you posted.  The various components don't add up to the total energy listed at the bottom.  Also, the multipole energy is similar in magnitude to the vdw energy (but opposite in sign).

**Comment by swails** [comment]
> Ok, that makes sense. Can you make it save a complete state when the energy jump happens? Then we can see exactly what's causing it.

Yea, I can do that.

> Something's not right with the energy breakdown you posted. The various components don't add up to the total energy listed at the bottom. Also, the multipole energy is similar in magnitude to the vdw energy (but opposite in sign).

The code is very simple.  [See here for what it's doing](https://github.com/apes-soft/OMM_Amoeba_Scripts/blob/master/runmd.py#L119-L125).  The code for breaking down the groups [is also very simple](https://github.com/apes-soft/OMM_Amoeba_Scripts/blob/master/runmd.py#L87-L93).  The fact that these don't add up is disturbing (I haven't checked that they don't yet)...

**Comment by peastman** [comment]
Shortly before 11:00 last night my simulation finally hit the error and wrote out a state file.  I'm analyzing that now.

**Comment by peastman** [comment]
In the state it wrote out, the jump in energy comes from two bonds that are badly strained.  One is about twice as long as it should be, the other about three times as long.  They're O-H bonds in two water molecules that are right next to each other.  Looking at the arrangement of atoms, I would guess that in the previous time step, two hydrogens got too close to each other.  That led to large repulsion and they jumped apart, leading to the badly strained bonds in the next step.

Perhap a 1 fs time step is pushing the edge of stability?  With other flexible water models it's more standard to use 0.5 fs.  Try using a multiple time step integrator, with 0.5 fs for the bonded forces and 2 fs for the nonbonded ones.

**Comment by swails** [comment]
I'm pretty sure @dacase has tried using a 0.5 fs timestep with both the Langevin and Verlet integrator and still saw the crashes.

However, your observations are also consistent with a crash that I had been seeing, and is also consistent with the large vdW interactions I saw (it's just that I killed the simulation *before* the NaN).

I'll start off a simulation with the 0.5 fs inner timestep and see if I still get crashes.  Dave may also chime in here to share what he's tried before, too.

Thanks!

**Comment by jchodera** [comment]
I think that 1 fs might also be pushing things.  An MTS integrator with much smaller (0.25 or 0.5 fs) valence integration would probably improve stability here, even if it doesn't speed things up any.

**Comment by dacase** [comment]
On Fri, Mar 25, 2016, peastman wrote:
> 
> Perhap a 1 fs time step is pushing the edge of stability?  With other
> flexible water models it's more standard to use 0.5 fs.  Try using a
> multiple time step integrator, with 0.5 fs for the bonded forces and 2
> fs for the nonbonded ones.

As jason noted, will try this.  It will be of interest to see if evaluating only
the bonded forces more often will help with what look to be occasional bad
nonbonded collisions.

FWIW, Amber implements a "vmax" parameter that clips any large elements of
the velocity array (during MD integration) to a maximum value well above
what one would expect for a Maxwell-Boltzmann distribution.  This is not
very legitimate, but allows an occasional bad collision to self-correct.
(This is *not* in the Amber GPU code, however, so may no longer be
needed.)  It's some sort of compromise between wanting bigger time steps,
and wanting to avoid ad hoc fixes to Newton's equations.

I also wonder if it would cost much for openMM to at least log any steps at
which the mutual polarization calculation fails to converge.

....dac

**Comment by peastman** [comment]
> It will be of interest to see if evaluating only the bonded forces more often will help with what look to be occasional bad nonbonded collisions.

I'd expect it to help a little, because the bonds won't get strained as badly.  But probably only a little.

> FWIW, Amber implements a "vmax" parameter that clips any large elements of the velocity array

It would be easy enough to implement that with a CustomIntegrator, if you want to try it.  Another option would be to clip the forces so they can never get too large.  Of course, this is exactly the problem that error controlled integrators are intended to solve.  It might be interesting to try VariableLangevinIntegrator to see how it behaves with that.

> I also wonder if it would cost much for openMM to at least log any steps at which the mutual polarization calculation fails to converge.

It would be easy to do, though I'm doubtful that's actually the problem.  The default iteration limit is many times higher than the maximum number of iterations that's actually expected to happen.  And the only way I've ever seen it fail to converge is if something else had already gone wrong (like coordinates becoming nan).

**Comment by jchodera** [comment]
> I'd expect it to help a little, because the bonds won't get strained as badly. But probably only a little.

There is recent work from Ben Leimkuhler that suggests that this can help integrator stability a great deal.

**Comment by jchodera** [comment]
>> FWIW, Amber implements a "vmax" parameter that clips any large elements of the velocity array
> It would be easy enough to implement that with a CustomIntegrator, if you want to try it. Another option would be to clip the forces so they can never get too large.

You might as well just let the simulation explode at that point, since it will be generating unreliable garbage without letting you know if you start clipping velocities or truncating forces.

**Comment by dacase** [comment]
I'd like to get feedback on what thermostats and integrators people are actually using with Amoeba/openMM/GPU simulations.  As far as I can tell (apologies that I haven't had to time to really study the code), one cannot use RESPA with the openMM Langevin integrator.  I'd be OK with the Andersen thermostat, but would appreciate recommendations on the frequency to use.  I seem to get even more frequent crashes with Andersen than with Langevin, but that is just anectdotal: I've not had the time to run any systematic tests.  (In addition to crashes, I have also seen wild temperature swings with Andersen).

I'm *not* expecting anyone to identify the problem with such little input.  Rather, I'm hoping to get details of the exact parameters that seem to work for others.  I'd also be very grateful to get a system.xml, coordinates, and the associated python script that doesn't exhibit these crashes: it seems that Jason and I are the only ones reporting this problem, so we may be inadvertently doing something wrong.

...thx....dac

**Comment by leeping** [comment]
Hi Dave,

I have two ways of running these simulations: (1) Langevin integrator with a 0.5 fs time step and a 1.0 ps^-1 friction coefficient (this works up to 600 K or above), and (2) Multiple timestep velocity-Verlet integrator with velocity randomization (that's a mouthful, I know) with a 0.25 fs time step for bonded degrees of freedom, and 2.0 fs time step for nonbonded.  The code for the MTS-VVVR integrator was provided by John and I have a copy of it in ForceBalance: https://github.com/leeping/forcebalance/blob/master/src/openmmio.py#L365

I think 2.5 fs works as well for the MTS integrator, but I was running some very "cold" simulations.  My simulations were all on pure water.

When I used 1.0 fs time steps in the normal Langevin integrator, I saw that the temperature was several degrees higher than the set temperature, which indicates the time step was too large.  Personally I think that 0.5 fs in the Langevin integrator and 0.25/2.0 fs in the MTS integrator are both safe choices, and for long sampling simulations I definitely recommend the MTS integrator.

Thanks,

- Lee-Ping

**Comment by dacase** [comment]
On Thu, Mar 31, 2016, Lee-Ping wrote:
> 
> I have two ways of running these simulations: (1) Langevin integrator
> with a 0.5 fs time step and a 1.0 ps^-1 friction coefficient (this
> works up to 600 K or above), and (2) Multiple timestep velocity-Verlet
> integrator with velocity randomization (that's a mouthful, I know)
> with a 0.25 fs time step for bonded degrees of freedom, and 2.0
> fs time step for nonbonded.

Thanks for the info....I'm giving MTSVVVR a try right now.

> When I used 1.0 fs time steps in the normal Langevin integrator, I
> saw that the temperature was several degrees higher than the set
> temperature, which indicates the time step was too large.

I haven't seen that behavior, but I was using a larger collision frequency (5
ps^-1), which may explain some differences.

...dac

**Comment by jchodera** [comment]
> Thanks for the info....I'm giving MTSVVVR a try right now.

Let me know if you have trouble!  

@leeping: I actually don't see that we put MTS-VVVR into [`openmmtools`](https://github.com/choderalab/openmmtools).  Would you mind if I pulled it into the `integrators` module there?

**Comment by leeping** [comment]
Of course, you wrote the code.  :)  I think I will still keep a copy in ForceBalance because it's convenient and doesn't require importing another module.

**Comment by peastman** [comment]
I'm curious, why did you choose such a small inner time step for the MTS integrator?  I mean, if a standard integrator works well with 0.5 fs, that indicates the bonded degrees of freedom can be integrated accurately with that time step.  So why did you reduce it to 0.25?

**Comment by jchodera** [comment]
0.5 fs is still a large timestep for AMOEBA's valence degrees of freedom.
They are so stiff for AMOEBA water that we were seeing big issues in the
atomic virial in Tinker with larger timesteps.

Unfortunately, I think 0.25 fs is pushing the lower limit of OpenMM's
gracefully handled machine precision limits for timestep, even in mixed
precision mode.  Will have to do more testing on this issue though.

**Comment by peastman** [comment]
In mixed precision, it should be fine.  In my own testing (not with AMOEBA, but that shouldn't matter), single precision starts to see increasing error when you get down to 0.25 fs, but mixed precision remains very solid.  Every calculation that involves the time step is done in double.

**Comment by peastman** [comment]
Are we now confident the problem is the step size?  If so, this can probably be closed.

**Comment by dacase** [comment]
On Mon, Apr 11, 2016, peastman wrote:

> Are we now confident the problem is the step size?  If so, this can
> probably be closed.

Sorry to be slow with the updates.  But I've been keeping lots of GPUs
occupied with these simulations for the past two weeks.  Here's what I've
found:

1. Lee-Ping's suggestion: MTSVVVR with gamma=1.0 ps^-1, dt=2.0 fs, inner time
step of 0.25 fs (i.e. 8 inner steps per outer step) *mostly* works, at least
for temperatures around 300K.  (I've not tried anything at elevated
temperatures.)

2. However, for one system (cyclophilin A, 161 residues, in water, MC
barostat with default parameters) I get NaN crashes.  Not sure what is
special here, since the same protein in a crystal environment works OK
with the above parameters: the crystal, however is at 280K, if that makes
a difference.  For the solution, I tried reducing dt to 1.0 fs (still
with a 0.25 fs inner time step).  This is better, but will still crash
every 2-4 million steps.  If I change the gamma_ln to some nearby value
(e.g. 1.5 ps^-1) I often get lucky and get through 2000000 steps (my
typical individual run), after which I can return to gamma = 1 ps^-1.

3. Of course, I need to run the cyclophilin with a shorter time step to see
what happens.  Just had too much on my plate this past week, and no Jason any
more to dump this on  :-(.

4. Apologies for just posting anecdotal evidence.  Only one system is failing,
and then only every few million steps.  I'll try to be more systematic.

Peter: since I don't think it's a big deal to keep the issue open, I'd prefer
that.  I can then post shorter outer time step results as I get them, and
everything will still be one one place in the logs.

...thx...dac

**Comment by dacase** [comment]
On Mon, Apr 11, 2016, peastman wrote:

> Are we now confident the problem is the step size?  If so, this can
> probably be closed.

OK: I am seeing NaN failures for the cyclophilin A protein in solution
using Leeping's MTSVVVR integrator with an outer time step of 0.5 fs,
bonded time step of 0.25 fs (i.e. nrespa=2), and a collision frequency of 1.0,
an isotropic MC barostat with default parameters.

Of course, it could still be a step-size problem, but this is 2 to 4 times
smaller than what others are using (apparently with success), so it doesn't
have the feel of being *just* a step-size problem.

I'm travelling right now, so it's not simple for me to figure out how to post
the failure details.  Jason has access to them on casegroup4.rutgers.edu
in /home/case/4yula_soln_amoeba  (most recent run there).  I'll try to get
files for people to study posted next week.  In the meantime, I'll re-run
this with Jasons --watch-for-errors flag; I should probably also learn how
to create a better crash file when the problem occurs.

....dac

**Comment by leeping** [comment]
Hi Dave,

Thanks for the update.  I agree this is alarming.  With an outer time step of 0.5 fs, I seriously doubt this is a time step problem.

To diagnose the issue, my recommendation would be to write a trajectory with a time resolution of one step.  This is similar to what Peter already has for analyzing the state immediately leading up to the crash.  Even if it's not possible to store the whole simulation trajectory, you could probably save the coordinates of the most recent 1000 steps.  When the simulation crashes, you may write out the trajectory and see which bonds are badly stretched, and whether the atoms in the stretched bond is sitting on top of some other atom.  (This is similar to the cameras they have in airport shuttle vans, which are continuously recording but only save data when a sudden acceleration is detected.) 

I'll go out on a limb and say that AMOEBA may be having a polarization catastrophe for this system, and it might not be completely integrator related.

- Lee-Ping
