### ISSUE TITLE
Tabulated function for CustomBondForce

### ISSUE THREAD

**Issue by isjoung** [openmm/openmm#1434]
I want to add DFIRE potential (http://www.ncbi.nlm.nih.gov/pubmed/12381853). It is a statistical potential acting between any two heavy atoms in proteins. Each pair has tabulated values (27 data points ranging from 1.25 angstrom to 14.25 angstrom). The number of total interaction types is 14,028.

Since CustomBondForce does not support tabulated functions, I used CustomNonbondForce:

``` python
for key in dfire_table: # 14,028 types
    key1 = (key[0],key[1])
    key2 = (key[2],key[3])
    if not atom_ind.has_key(key1) or not atom_ind.has_key(key2):
        continue
    dfire_force = mm.CustomNonbondedForce('dfire_func(r)')
    dfire_force.addFunction('dfire_func',dfire_table[key], 0.125, 1.425)
    dfire_force.setCutoffDistance(1.425) # maybe this is ignored?
    for i in xrange(system.getNumParticles()): 
        dfire_force.addParticle()
    dfire_force.addInteractionGroup(atom_ind[key1], atom_ind[key2])
    system.addForce(dfire_force)
```

The numbers of atoms in interaction groups are actually very small (<~10). This code seems to work but it is fairly slow. (only tested on CPU)

Alternative way of doing is writing symbolic functions using CustomBondForce. The equation with many step() functions will be very long though and I suspect that the performance is also not good.

If CustomBondForce supports tabulated function, it would be a reasonable solution. If anyone can suggest alternative ways of solving the problem without the new feature, please also comment.

**Comment by swails** [comment]
Oooohh... don't do that.  Use `CustomCompoundBondForce` instead.  You can use a tabulated function there as well, and you are perfectly allowed to use `numParticles=2` and only do bonds.  This is *way* simpler than using a `CustomNonbondedForce`.  Also, using a nonbonded force to model bonds may completely break OpenMM's imaging capabilities (since OpenMM detects what bonds are by looking at bonded forces).

**Comment by isjoung** [comment]
```python
for key in dfire_table:
    key1 = (key[0],key[1])
    key2 = (key[2],key[3])
    if not atom_ind.has_key(key1) or not atom_ind.has_key(key2):
        continue
    dfire_force = mm.CustomCompoundBondForce(2,'step(1.425-distance(p1,p2))*step(distance(p1,p2)-0.125)*dfire_func(distance(p1,p2))')
    dfire_force.addFunction('dfire_func',dfire_table[key], 0.125, 1.425)
    if key1 == key2:
        for ii in xrange(len(atom_ind[key1])-1):
            i = atom_ind[key1][ii]
            for jj in xrange(i+1,len(atom_ind[key2])):
                j = atom_ind[key2][jj]
                dfire_force.addBond([i,j],[])
    else:
        for i in atom_ind[key1]:
            for j in atom_ind[key2]:
                dfire_force.addBond([i,j],[])
    system.addForce(dfire_force)
```
Ok. This is my new code and it seems to work fine. Thank you, Jason.

**Comment by isjoung** [comment]
I get an error message below if I try the `CustomCompoundBondForce` as shown above.

  File "/home/isjoung/.local/lib/python2.7/site-packages/simtk/openmm/app/simulation.py", line 101, in __init__
    self.context = mm.Context(self.system, self.integrator)
  File "/home/isjoung/.local/lib/python2.7/site-packages/simtk/openmm/openmm.py", line 6525, in __init__
    this = _openmm.new_Context(*args)
Exception: Error compiling kernel: (): Error: Formal parameter space overflowed (4352 bytes max) in function computeBondedForces

The platform is 'OpenCL'. It seems that it is related to the number(size?) of customized forces. If I add only a few(~3) customized forces, I don't see the error message. How can I solve the problem?

**Comment by peastman** [comment]
How many bonded forces do you have when you get that error?  Also, what OpenCL implementation are you using?

The kernel that computes bonded forces needs a few arguments for each force.  And the error message indicates that your OpenCL implementation sets an upper limit on the amount of data that can be passed as argument.  But arguments don't need much space, so that should be enough for several dozen forces.

**Comment by isjoung** [comment]
The number of `CustomCompoundBondForce` is 14,028. Each customized function has 27 points. The OpenCL platform causes the error when the number exceeds around 600. It was same with CUDA platform. CUDA allows up to ~400. 

The error message from CUDA platform:
  File "/usr/local/lib/python2.7/dist-packages/simtk/openmm/app/simulation.py", line 77, in __init__
    self.context = mm.Context(system, integrator)
  File "/usr/local/lib/python2.7/dist-packages/simtk/openmm/openmm.py", line 9388, in __init__
    this = _openmm.new_Context(*args)
Exception: Error launching CUDA compiler: 256
/tmp/openmmTempKernel0x3e8c7a0_15536.cu(691): Error: Formal parameter space overflowed (4096 bytes max) in function computeBondedForces

OpenCL implementation is by intel. Is there a way to increase the limit?

**Comment by peastman** [comment]
Whoa!  I'm almost certain that is not what you want to do!  Is there a reason you need thousands for separate Force objects, rather than a single Force with lots of bonds?

**Comment by isjoung** [comment]
The reason is that 14,028 types of bonds use different tabulated functions. Please see the source code above. If I use only 1 force object, how can I differentiate the added functions?

**Comment by peastman** [comment]
How about a single 2D function where each of your separate functions is one row?  Then you can use a per-bond parameter to specify the row for each bond.

**Comment by isjoung** [comment]
```python
dfire_key_list = dfire_table.keys()
ntype = len(dfire_key_list)
npoint = len(dfire_table[dfire_key_list[0]])
dfire_2d_table =  [None]*ntype
for i in xrange(ntype):
    key = dfire_key_list[i]
    table1d = dfire_table[key]
    dfire_2d_table[i] = table1d
    assert(npoint == len(table1d))
dfire_2d_table = np.array(dfire_2d_table).T.ravel()
dfire_function = mm.Continuous2DFunction(ntype,npoint,dfire_2d_table,0.0,float(ntype-1),0.125,1.425)

force = mm.CustomCompoundBondForce(2,'dfire_func(itype,distance(p1,p2))')
force.addPerBondParameter('itype')
force.addTabulatedFunction('dfire_func',dfire_function)
force.setForceGroup(fgroup_num)
count = 0
for itype in xrange(ntype):
    key = dfire_key_list[itype]
    key1 = (key[0],key[1])
    key2 = (key[2],key[3])
    if not atom_ind.has_key(key1) or not atom_ind.has_key(key2):
        continue
    if key1 == key2:
        for ii in xrange(len(atom_ind[key1])-1):
            i = atom_ind[key1][ii]
            for jj in xrange(ii+1,len(atom_ind[key2])):
                j = atom_ind[key2][jj]
                force.addBond([i,j],[float(itype)])
                count += 1
    else:
        for i in atom_ind[key1]:
            for j in atom_ind[key2]:
                force.addBond([i,j],[float(itype)])
                count += 1
if count:
    system.addForce(force)
```

This is the modified version. It is a bit weird that the value vector passed to `Continuous2DFunction` should be Fortran-contiguous but anyway I confirmed that the two results are practically identical on CPU. On CUDA, the compilation error has disappeared but the calculated energy was different. For this, I will start a new thread.
