### ISSUE TITLE
[Feature request] Additions to CustomIntegrator syntax

### ISSUE THREAD

**Issue by pgrinaway** [openmm/openmm#1445]
This is a set of feature requests--I'm not sure how difficult they are to implement, so I understand if they'd have to be on the back burner, but basically, these would make it easier to do various Monte Carlo moves inside a `CustomIntegrator`. I'm thinking of methods like [Configurational Bias Monte Carlo](http://towhee.sourceforge.net/algorithm/cbmc.html) and the Pruned-Enriched Rosenbluth Method. For those unfamiliar, these techniques involve atom-by-atom insertion, where new atom insertion involves proposal of internal degrees of freedom as fast "trial" moves, then accepts one of those based on the entire potential. 

More specifically, I was thinking:
- Ability to address individual particle coordinates:
  e.g. `self.addComputeGlobal('x[3]', 'x[3]+gaussian')`
- Conveniences for rotating a particle about a vector:
  - exposed cross and dot product, as well as rotation convenience:
    e.g,. suppose there is a torsion defined by {x[0], x[1], x[2], x[3]} and we want to rotate
    x[0] about the torsion axis.
  
  ``` python
      self.addComputeGlobal('axis', 'x[2]-x[1]')
      self.addComputeGlobal('axis_u', 'a/dot(a, a)')
      self.addComputeGlobal('x[0]', 'rotate(x[0], axis, pi/2')
  ```
  
  (the cross product might be needed, for example, to set a bond angle).
- Array-valued variables, along with some kind of loop construct:
  This example is for generating a torsion scan, which is necessary to normalize the torsion probabilities:

``` python
    #assuming we have already calculated the above axis
    self.addGlobalVariable('torsion_energies[n_trials]')
    generate_torsion_scan = """
    for(int i=0; i<n_trials, i++)
    {
    x[0] = rotate(x[0], axis, 2*pi/n_trials);
    torsion_energies[i] = energy();
    }
    """
    self.addComputeGlobal(generate_torsion_scan)
```
- Convenience to draw from a categorical distribution--this would arise in the CBMC example where you have generated a set of trial distributions, and want to choose one based on the total potential energies. Assuming we have normalized `torsion_energies` above:

``` python
    self.addComputeGlobal('torsion_idx', 'choose(torsion_energies)')
```
- Exposing the Lagrangian of the constraint algorithm to make Metropolis-Hastings a bit easier.

I realize this is quite a list, and that some of the things on this list are probably pretty challenging to implement, so I'm by no means trying to underestimate the difficulty here. But if some of these are not too difficult, and they are useful to others, it'd be great to have them in here. If you'd like any further elaboration or examples, please let me know!

Tagging @gregoryross and @maxentile in case they are interested as well, and @jchodera.

**Comment by pgrinaway** [comment]
Noting also that we'd like a way to extract these array-valued variables as well:

```python
torsion_energies = integrator.getGlobalVariableByName('torsion_energies', asNumpy=True)
```

Thanks again, and if this isn't clear, feel free to ask.

**Comment by peastman** [comment]
That's... ambitious!

A few of those are already possible.  For example:

```Python
self.addComputeGlobal('x[3]', 'x[3]+gaussian')
```

That's really a per-DOF calculation, not a global one.  It just happens that you're only doing it for the degrees of freedom associated with a single atom.  So multiply `gaussian` by a per-DOF parameter set to 1 for that atom and 0 for all others.

Loops are also possible with the new features in 7.0.

But the others would involve pretty major changes to the whole paradigm of CustomIntegrator.  I think you're better off writing a plugin.

**Comment by pgrinaway** [comment]
>That's... ambitious!

Yeah, I realize this is quite a lot, and I'm pretty naive as to how this would be implemented.

>That's really a per-DOF calculation, not a global one. It just happens that you're only doing it for the degrees of freedom associated with a single atom. So multiply gaussian by a per-DOF parameter set to 1 for that atom and 0 for all others.

Good point. I'll give this a try.

>Loops are also possible with the new features in 7.0.

Cool! Sorry I missed it!

>But the others would involve pretty major changes to the whole paradigm of CustomIntegrator. I think you're better off writing a plugin.

I think this does make sense. Thanks so much for your input!

**Comment by jchodera** [comment]
It may be worth thinking about some way to handle matrices and vectors. We had talked about rigid body brownish dynamics integrators at some point---those would also require matrix and vector operations. Perhaps it would be a different CustomIntegrator, but would definitely be broadly useful.

And, as Patrick suggests, this opens up lots of avenues for efficient Monte Carlo.

**Comment by peastman** [comment]
Perhaps a new type of computation, `computePerParticle()`, that treats the per-DOF values as vectors and computes a new vector value for each particle?  It could then support `dot()` and `cross()` functions.  It could also have a `vector()` function that would assemble three scalars into a vector.  Among other things, that would let you implement a matrix-vector multiply as three dot products.

**Comment by pgrinaway** [comment]
That would certainly be useful!

**Comment by pgrinaway** [comment]
Here's another idea that @jchodera and I were just discussing:

What if we had a `CudaKernelIntegrator` or `OpenCLKernelIntegrator` (open to name changes there :) ) which accepted a string of C code implementing a function with a defined signature? I'd imagine (correct me if I'm wrong) that this would not be too burdensome to implement, since OpenMM 

We were thinking of how straightforward it is to use libraries like [PyCUDA](https://documen.tician.de/pycuda/), which allow you to provide a string of C code implementing just the kernel, while the library takes care of the rest. Since OpenMM already has the machinery to load positions, etc., as well as compile on the fly (since that's what happens with `CustomIntegrator` anyway), I was wondering if something like:

```python
kernel = """
extern "C" __global__ void doIntegration(float scaleX, float scaleY, float scaleZ, int numMolecules, real4 periodicBoxSize,
        real4 invPeriodicBoxSize, real4 periodicBoxVecX, real4 periodicBoxVecY, real4 periodicBoxVecZ, real4* __restrict__ posq,
        const int* __restrict__ moleculeAtoms, const int* __restrict__ moleculeStartIndex)
{
//do some integration
}
"""

integrator = openmm.CudaKernelIntegrator(kernel)
```
(I took the signature from `monteCarloBarostat.cu`--not suggesting any particular signature).

Thoughts? 

Thanks!

**Comment by jchodera** [comment]
Just wanted to say that [`pycuda`](https://mathema.tician.de/software/pycuda/) and [`pyopencl`](https://mathema.tician.de/software/pyopencl/) are awesome because they do all the boilerplate stuff for you, allowing you to concentrate on just writing a kernel that does what you need. A capability like this could offer much more flexibility than the `CustomIntegrator` but still be super fast and quite easy to code up.

I supposed we'd need some way to compute forces and energies, though. Perhaps through some magic keywords that get substituted with code?

**Comment by peastman** [comment]
Interesting idea.  Could you discuss what the scope of this would be?  What features would it support that aren't possible with CustomIntegrator?  And just as important, what features would it *not* attempt to support?

I take it you've already looked at the implementation of LangevinIntegrator, so you know that even as simple an integrator as that involves multiple kernels, alternating with code that gets executed on the CPU side.

**Comment by peastman** [comment]
Vector functions were added in 7.3.  I think most of the requested features are now available, so closing this.
