### ISSUE TITLE
Clean development docs

### ISSUE THREAD

**Issue by mpharrigan** [openmm/openmm#1458]
cc https://github.com/pandegroup/openmm-org/pull/10

A reminder to make it so files get deleted on sync

**Comment by mpharrigan** [comment]
Looks like we're using travis s3 deploy

https://docs.travis-ci.com/user/deployment/s3

No easy way to cause destination folder to be cleaned before upload from an initial read

**Comment by mpharrigan** [comment]
https://github.com/travis-ci/docs-travis-ci-com/issues/519

**Comment by mpharrigan** [comment]
We can switch to a manual deployment script using the `aws` python cli or periodically clear the development folder manually

**Comment by peastman** [comment]
Is this still an issue or has it been fixed?
