### ISSUE TITLE
Reporting the pressure

### ISSUE THREAD

**Issue by trendelkampschroer** [openmm/openmm#147]
Hi,

I am runnning simulations with the MC barostat. How can I log the pressure?

Best,

Benjamin

**Comment by nbzy1995** [comment]
I wonder whether newer versions of openmm have implemented the pressure estimator? Now I have to write an external code to calculate virials on the configurations generated during simulation...
I am trying to modify the stateDataReporter... in principle, we can retrieve at any instant, the force expression and positions, then the virial shall be straightforward.

**Comment by peastman** [comment]
There's still no virial calculation.

**Comment by nbzy1995** [comment]
> There's still no virial calculation.

I see, thanks!  I found a partial workaround [here](https://github.com/openmm/openmm/issues/1989) , in which you can get the force.
