### ISSUE TITLE
Add flag to Python API for retrieving quantities without units

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#1490]
Units are a fantastic "baked in" feature of the Python API, but in cases where a lot of data is being retrieved inside an inner loop, adding units and immediately removing them can be a performance bottleneck.

I wonder how much work it would be to add an optional argument to all Python API calls to retrieve values without units?

I haven't grokked all of the magical python wrapper-generating code yet, but this may be simple. Currently, [this code](https://github.com/pandegroup/openmm/blob/master/wrappers/python/src/swig_doxygen/swigInputBuilder.py#L520-L537) wraps the returned value in a `simtk.unit.Quantity` if the units are specified [here](https://github.com/pandegroup/openmm/blob/master/wrappers/python/src/swig_doxygen/swigInputConfig.py#L152-L436). We'd want to also add an optional method argument like `useUnits=True` (or `disableUnits=False`) and add code to wrap the returned value depending on whether this flag is set to the default.

**Comment by jchodera** [comment]
(Tagging @pgrinaway who would benefit from this feature most immediately.)

**Comment by rmcgibbo** [comment]
It's possible already to call methods on _openmm and bypass the Python side of the swig wrappers if you really want to.

**Comment by swails** [comment]
You can also access the `_value` attribute of each `Quantity` to get a unitless number, rather than doing the dimensional analysis.  I think the expensive part is taking units *off*, rather than putting the units on.

At the very least, it's worth seeing if that (or @rmcgibbo's suggestion) get you the required performance gains without having to resort to some kludge like asking the API to remove unit protection.

**Comment by jchodera** [comment]
> It's possible already to call methods on _openmm and bypass the Python side of the swig wrappers if you really want to.

Mind blown!

**Comment by jchodera** [comment]
Do we have something about that solution in the docs?

**Comment by rmcgibbo** [comment]
No. It's not really anything recommended, but you can see how to do it by just reading `openmm.py` which is autogenerated by swig, and calling the same methods/functions it calls.

**Comment by jchodera** [comment]
Ah, you mean instead of calling
```python
value_with_units = nonbonded_force.getCutoffDistance()
```
I can call
```python
import _openmm
value_without_units = _openmm.NonbondedForce_getCutoffDistance(nonbonded_force)
```
?

That's...nontrivial, but could work in a pinch.

**Comment by rmcgibbo** [comment]
Something like that, yeah.

**Comment by jchodera** [comment]
OK, it seems like it could be worth investing time into making this a bit more sensible looking to the end user, like
```python
value_without_units = nonbonded_force.getCutoffDistance(units=False)
```

**Comment by peastman** [comment]
You should definitely try just calling `._value` on the returned Quantity.  I don't know how much of the overhead comes from wrapping and how much from unwrapping.  It would be good to find out.

I assume you already know that if you're getting, for example, a list of atom positions with `getPositions()`, you should unwrap the entire list at once rather than each element individually.

**Comment by pgrinaway** [comment]
>You should definitely try just calling ._value on the returned Quantity. I don't know how much of the overhead comes from wrapping and how much from unwrapping. It would be good to find out.

I do have some code that has to generate `System`s pretty frequently, and suspect that the wrapping/unwrapping is expensive. I'm at a conference until tomorrow night, but Thursday I'll try to get some profiling data on that code and post the results here.

**Comment by rmcgibbo** [comment]
I don't think the wrapping has any greater complexity than wrapping the data in a list, tuple or other object would

```
value = ...
wrapped_value = [value]
```

(which happens in the invocation sequence any times you call a python function too.) But the unwrapping could be more significant.

**Comment by swails** [comment]
The cost of adding and stripping units is highly asymmetric.  Adding units to a raw number costs you the evaluation of 2 or 3 conditionals (if you use the `Quantity` constructor directly), the construction of a new object (similar to the construction of a non-cached integer or string), and assigning 2 attributes in the object initializer -- pretty cheap in Python.  If you make a unit using the `*` operator, it costs an extra conditional evaluation or two.

By comparison, dimensional analysis is *expensive*.  You have to reduce all of the units to determine if they are compatible, do the necessary conversion maths (on each element unless you're using a numpy array), and for mutable types like lists and numpy arrays, deep copies of everything (see #536 and #538).

There have been several instances where I've found the dimensional analysis overhead disabling and needed to make it cheaper.  Using the `_value` attribute on `Quantity` objects directly has always been sufficient for me.

**Comment by rmcgibbo** [comment]
I assume the deep copy is really the killer, but it would be cool to benchmark. My intuition is often wrong.

**Comment by Lnaden** [comment]
I have personally found that assigning units or `stripUnits` adds a fair amount of overhead to calls. I have some basic timing information to put some numbers down by subclassing the `openmm.py` classes without a unit call:

```python
import cProfile, pstats, StringIO
import simtk.unit as unit
import simtk.openmm as mm
from simtk.openmm import _openmm

class noUnit(mm.NonbondedForce):
    '''
    Nonbonded force without wrapping units
    '''
    def getCutoffDistance(self):
        val = _openmm.NonbondedForce_getCutoffDistance(self)
        return val

ncalls = 10000

NBF = mm.NonbondedForce()
noUnitNBF = noUnit()
for force in [NBF, noUnitNBF]:
    force.setCutoffDistance(1*unit.nanometer)
    pr = cProfile.Profile()
    pr.enable()
    for i in xrange(ncalls):
        force.getCutoffDistance()
    pr.disable()
    s = StringIO.StringIO()
    sortby = 'cumulative'
    ps = pstats.Stats(pr, stream=s).sort_stats(sortby)
    ps.print_stats()
    print s.getvalue()
```

And I get out this timing profiling.
```
         50001 function calls in 0.023 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
    10000    0.009    0.000    0.023    0.000 /home/ln8dc/anaconda/lib/python2.7/site-packages/simtk/openmm/openmm.py:14564(getCutoffDistance)
    10000    0.006    0.000    0.012    0.000 /home/ln8dc/anaconda/lib/python2.7/site-packages/simtk/unit/quantity.py:97(__init__)
    10000    0.003    0.000    0.005    0.000 /home/ln8dc/anaconda/lib/python2.7/site-packages/simtk/unit/quantity.py:785(is_quantity)
    10000    0.003    0.000    0.003    0.000 {_openmm.NonbondedForce_getCutoffDistance}
    10000    0.003    0.000    0.003    0.000 {isinstance}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}



         20001 function calls in 0.005 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
    10000    0.003    0.000    0.005    0.000 timeunits.py:12(getCutoffDistance)
    10000    0.002    0.000    0.002    0.000 {_openmm.NonbondedForce_getCutoffDistance}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
```

If you are only calling values a few times, it does not add much, but if you are calling it many times as in @pgrinaway's case (or my own), it can add up. My work-around has been sub classing since by the time it gets to the Python level of my scripts, the `Quantity` has already been invoked and the time has been spent. The trade off in my workaround though is I obviously have to know what I am passing/fetching.

**Comment by peastman** [comment]
Closing this issue, since we don't plan to add the requested feature.  We should of course continue looking for ways to make units as low overhead as possible.
