### ISSUE TITLE
Decrease pcie bandwidth usage on Windows

### ISSUE THREAD

**Issue by informatorius** [openmm/openmm#1551]
In folding@home fast GPUs like gtx 1080ti use up to 50% of pcie bandwidth on pcie 3.0 x8 slots.
On slower pcie slots the performance goes down.
Maybe it is possible to reduce bandwidth usage somehow?

**Comment by peastman** [comment]
The bandwidth used will depend entirely on what communication you're doing between the GPU and CPU.  If you request states frequently, that will take a lot of bandwidth and hurt performance.  And of course that will depend on the relative speed of the GPU and the bus.

**Comment by Squall-Leonhart** [comment]
using a gtx 1080, i see maximum 40% bus usage on a PCI-E 2.0 slot,

i don't know where you get your numbers informatorius, but they are not what im seeing.

**Comment by informatorius** [comment]
It is on Windows lower than pcie 3.0 x8 fast GPUs PPD goes down for folding@home. On Linux there is no such problem.

**Comment by bb30994** [comment]
As peastman has suggested, the amount of data being moved depends on the structure of the Project, and the utilization depends on the bandwidth of the PCIe bus and on how fast the GPU consumes that data.  When you compare Windows and Linux, unless you have normalized the factors he has mentioned, attributing the differences to the differences in the OS is without foundation.
