### ISSUE TITLE
Invalidate only forces affected by change in global or force parameters?

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#1580]
During our discussion of how to optimize various calculations involving changing either force parameters or force parameters a week or so ago, @peastman suggested that only certain `Force` terms might need to be recomputed when global context parameters or force parameters are modified. Reading through the current code, it looks like the CUDA and OpenCL platforms only have a global `forcesAreValid` flag that invalidates _all_ forces and causes them to be recomputed. It might be interesting to explore how difficult it would be to allow individual forces to be invalidated instead, since there are many cases (e.g. alchemical free energy calculations, umbrella sampling simulations, constant-pH simulations) where we loop over and recompute energies or forces after changing some parameters. While this can in principle be handled now with force groups (perhaps we can profile this way?), transparent handling of updating only forces that need it could be much more convenient for API users.

**Comment by peastman** [comment]
Closing this issue, since I don't think there's a good way of doing it.  On the other hand, we have made changes to reduce the cost of calling `updateParametersInContext()` when only one Force is changing.  That will usually be a bigger bottleneck than the force calculation anyway.
