### ISSUE TITLE
Should 1,4 coulombic exceptions change functional form based on nonbonded method?

### ISSUE THREAD

**Issue by andrrizzi** [openmm/openmm#1590]
OpenMM currently [uses normal coulombic interactions](https://github.com/pandegroup/openmm/blob/master/platforms/reference/src/SimTKReference/ReferenceLJCoulomb14.cpp#L137) regardless of the nonbonded method used.

Playing with custom forces and a simple host-guest system (i.e. `openmmtools.testsystems.HostGuestExplicit`) with `CutoffPeriodic`, I found that if we compute 1,4 interactions using the reaction field correction even for only 30 atoms, there's a change in potential energy of about 30kJ/mol.

I'm now confused on which functional form should actually be used to compute the electrostatics part of exceptions.

**Comment by jchodera** [comment]
@lnaden suggests that gromacs applies the reaction-field form of electrostatics to nonbonded exceptions.

**Comment by peastman** [comment]
I'm not sure there's a good answer in that case.  For all methods other than reaction field, we clearly should not modify them.  In the case of PME, for example, the combination of direct+reciprocal equals the total interaction with no cutoff.  So it would make no sense to treat 1-4 interactions in any other way.

But with RF it does make a difference, though generally only a very small one.  It kind of depends on whether you think of 1-4 interactions as bonded (which you would not expect to be modified) or as nonbonded (which you would expect to be).  And of course, they're not clearly one or the other, but part way in between.

To measure the size of the effect, though, you need to look at changes in relative energies, not absolute energies.  One of the things RF does is add a constant shift to the energy of every interaction, so it will exactly equal 0 at the cutoff distance.  But that has no effect on dynamics or thermodynamics.  So you really should look at how much the energy changes *without* the shift.

**Comment by swails** [comment]
> And of course, they're not clearly one or the other, but part way in between.

Or perhaps they are one *and* the other :)

Many force fields (especially most of the fixed-charge force fields I'm familiar with), parametrize torsions by 'correcting' the profile obtained with simple bonds, angles, and 1-4 interactions with torsion terms to match either an experimentally-derived or QM-derived profile.

So I agree, ambiguous.

**Comment by Lnaden** [comment]
But even then, some are parameterized with the 1-4 assumption and others (like GLYCAM) are not as I understand, so yes, quite ambiguous. I would prefer if it was consistent though across all nonbonded treatments in the end.

**Comment by swails** [comment]
> But even then, some are parameterized with the 1-4 assumption and others (like GLYCAM) are not as I understand,

GLYCAM does not modify 1-4 nonbonded interactions (which is different than both Amber, which scales electrostatics by 1.2 and Lennard-Jones by 2.0 and CHARMM, which uses different parameters for 1-4 L-J).  But they *do* assign dihedral parameters "around" the 1-4 nonbonded interactions (i.e., the torsion parameter assignment follows the standard Amber philosophy of using them to "correct" deficiencies in the nonbond-only model for 1-4 interactions).

**Comment by peastman** [comment]
Closing this since we never reached a consensus of what (if anything) should be changed.
