### ISSUE TITLE
Dealing with small molecules

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#160]
I'm starting a thread to discuss how we should best deal with small molecules.

I'd love for YANK to make use of the nice OpenMM app tools `Modeller` and `ForceField` to set up protein systems, but the thing that has been preventing this is the fact that OpenMM doesn't yet have a way to add and parameterize small molecules.

There are a number of different possibilities for how this could be implemented, and how we could help.

The simplest approach could be for us to simply write a script that takes one or more mol2 | sdf | pdb files of small molecules as input, runs them through AmberTools `antechamber`, and then compiles an XML forcefield file that `ForceField` can read for these residue types.  Some additional support may need to be added to `Modeller` to allow small molecules to be merged into (or removed from) `Topology` objects, and `ForceField` would have to be OK with recognizing non-polymer molecules besides water.

Does this sound like a logical first step, or is there more extensive small molecule support planned at this time?

**Comment by pyeguy** [comment]
what's the status on this? my research focuses on peptidic macrocycles like the natural product cyclosporin a and parameterizing a forcefield to accept the non-standard AA's is always a tremendous pain filled with hacks and the use of often flaky online servers. Building in an automated way to type (even badly) unknown residues using  GAFF or MMFF in openMM would be very useful.

**Comment by jchodera** [comment]
Robust small molecule support will come with OpenMM 7.2. For now, experimental small molecule support is possible through [openmoltools](http://github.com/choderalab/openmoltools) via the GAFF forcefield generator.

**Comment by davidlmobley** [comment]
Oddly, this issue just got tweeted for some reason.

**Comment by davidsaezsan** [comment]
> Robust small molecule support will come with OpenMM 7.2. For now, experimental small molecule support is possible through [openmoltools](https://github.com/choderalab/openmoltools) via the GAFF forcefield generator.

Hello everyone. I have installed OpenMM 7.2.2.   Is the robust small molecule support already available or should I use openmoltools?

Thanks for your help.

**Comment by gcorso** [comment]
Hi,
How is the chemical .xml file generated (for example see the example below referenced above)?

https://github.com/choderalab/openmoltools/blob/affdcc2ccf4832305502cf670e7bddfad09e5d9f/examples/test_protein_ligand.py#L9

Thanks for the help,
Gabriele

**Comment by peastman** [comment]
Could you open a new issue for your question, rather than resurrecting one that was closed many years ago?  Give full context for exactly what you're asking.  Also, if your question is about a file from openmoltools, it would probably be better to ask there.

**Comment by gcorso** [comment]
Thank you, I've raised [an issue](https://github.com/choderalab/openmoltools/issues/309) on openmoltools. However, given that all the code used is part of OpenMM, I thought this repo is the most relevant. The following is the code I specifically use:

```
    #pdb is a PDBFile object and rd_mol is an RDKit molecule coming from a mol2 file
    molpdb_file = io.StringIO(Chem.MolToPDBBlock(rd_mol))
    molpdb = openmm_app.PDBFile(molpdb_file)
    model = openmm_app.modeller.Modeller(pdb.topology, pdb.positions)
    model.add(molpdb.topology, molpdb.positions)

    force_field = openmm_app.ForceField("amber10.xml", ..., "tip3p.xml")  # this is where the .xml I'm missing should go  
    system = force_field.createSystem(model.topology, nonbondedMethod=openmm_app.PME, nonbondedCutoff=1.0 * unit.nanometers,  constraints=openmm_app.HAngles)
```

**Comment by niccolo93** [comment]
Hi, 

> Robust small molecule support will come with OpenMM 7.2. For now, experimental small molecule support is possible through [openmoltools](https://github.com/choderalab/openmoltools) via the GAFF forcefield generator.

Hi, just wanted to know if anything was ever done in regard to this. Up to date it looks like there's no support for adding small molecules, but maybe I missed it.

Thank you!

**Comment by davidlmobley** [comment]
You may want to check out the Open Force Field toolkit (openforcefield.org) which interfaces well with OpenMM and smoothly handles small molecules. Also it has docs and examples to suit a lot of use cases.

**Comment by peastman** [comment]
The OpenMM user guide also [describes](http://docs.openmm.org/latest/userguide/application/02_running_sims.html#small-molecule-parameters) how to parameterize small molecules with OpenFF Toolkit.
