### ISSUE TITLE
Add Zenodo DOI badge to README.md once OpenMM 7.1 release is cut

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#1627]
We might want to use the [GitHub Zenodo integration](https://guides.github.com/activities/citable-code/) so that the releases we cut receive citable DOIs.

**Comment by jchodera** [comment]
@peastman : Let's enable this before we cut a release, since we can't enable it afterwards.

**Comment by peastman** [comment]
I'll take a look at it.

**Comment by peastman** [comment]
I've enabled the webhook.  I think that's all that has to be done until after we create the release.

**Comment by jchodera** [comment]
Correct! Thanks!

I'll change this issue to just be a reminder to add the Zenodo badge to `README.md` once the DOI is issued.
