### ISSUE TITLE
invalid value for --gpu-architecture

### ISSUE THREAD

**Issue by pscadmin** [openmm/openmm#1653]
Hello,  by any chance does anybody knows how/from where testInstallation.py get --gpu-architecture flag? Thanks !!!
###### ############# here are details

Here is why:
- on our HPC nodes ( Warewulf like stateless cluster) testInstallation.py is failing with this error:
  CUDA platform error: Error compiling program: nvrtc: error: invalid value for --gpu-architecture (-arch)

Here is how: 
python /openmm/latest/simtk/testInstallation.py

There are 3 Platforms available:

1 Reference - Successfully computed forces
2 CUDA - Error computing forces with CUDA platform
3 OpenCL - Error computing forces with OpenCL platform   

OpenCL platform error: Error initializing context: clGetPlatformIDs (-1001)
CUDA platform error: Error compiling program: nvrtc: error: invalid value for --gpu-architecture (-arch)

Median difference in forces between platforms: ...

(OpenCL problem was because /etc/OpenCL/vendors/nvidia.icd was missing on the nodes which we found by searching for clGetPlatformIDs (-1001), but cannot get any solution for the CUDA error)

More details here:
- we use
  Driver Version: 367.44
  CUDA Version: 7.5.18
  GPU card: GTX 1080
  openMM: 7.0.1
- we can run without any problem
  nvidia-smi 
  deviceQuery
  simpleMultiCopy
  matrixMulCUBLAS ... and other CUDA samples/tests 
- but openmm install test will give us that CUDA error (all is fine when running on regular workstation and on previous VNFS capsule that supports GTX980 GPUs with CUDA  6.5 which unfortunately cannot be used with these new GTX1080 .. on that capsule we use openmm 6.2)
  ###### ##########

I'm sure there is some simple solution as for the OpenCL error (missing one files on the nodes). By finding out how testInstallation.py get and use the  --gpu-architecture flag, we are hoping to find out what is missing on the new VNFS capsules for GTX 1080. Thanks again !!!

**Comment by peastman** [comment]
The problem is that CUDA 7.5 isn't entirely compatible with Pascal GPUs like the GTX 1080.  That's not surprising, since it was released long before them.  More specifically, OpenMM queries the compute capability of whatever GPU you're running on, which for the 1080 is 6.1.  It then tells CUDA to compile its kernels for that architecture, and that fails because the compiler in CUDA 7.5 doesn't know about any compute capability above 5.3.

The best solution is to install CUDA 8.0, then compile OpenMM from source against that.  But if upgrading CUDA isn't an option, I've also put a workaround for this problem into the current version of the source code: https://github.com/pandegroup/openmm/blob/master/platforms/cuda/src/CudaContext.cpp#L220-L228.  I don't recommend using development code for production simulations, but you could copy just that block into the 7.0.1 source code, then compile that.

**Comment by pscadmin** [comment]
thanks -- you made my day 
* it also explained why the test was fine on the workstation (because older GPU)
* I'll talk with the developers here which way they want to go; then try and post how it went.
thanks again

**Comment by pscadmin** [comment]
Well; this was fun. testInstallation.py now works(no CUDA error), but our simulations crash after few minutes with "Particle coordinate is nan" error. The good part is that the computational chemists see 80% speedup in this system CUDA8/OpenMM7.0 on GTX1080 vs CUDA6.5/OpenMM6.2 on GTX980 (now just to get their simulation to finish). 

######### details here

* the workaround (patching the CudaContext.cpp) did not work for me -- kept failing to compile it with "not defined this and that" in  the patched CudaContext.cpp (I'm sure my mistake)

so since I could not get anywhere with the workaround, I just went with

* installing CUDA 8.0, then compile OpenMM from source against it which had its own hurdles

(openmm compile kept "finishing" with error -- most of them related looking for gl.h "No such file or director GL/gl.h", so in ccmake I deselected options that gave the error and eventual the compilation finished successfully .. I know, I know, I should find the header file)

and
(for some reason on the node capsule now we have to include /usr/local/lib/python2.7/dist-packages/simtk which we did not have to include in the past)

and (the main thing)
the computational chemists' bluet proof drude simulation that runs on cuda 6.5.19 with openmm 6.2 keeps crashing with "Particle coordinate is nan" error
 p.s. (in the past we could use the  pre-compiled binary of OpenMM; but they won't work with CUDA 8)

##########

Any pointers are appreciated. If we stumble on solution, I'll post it here. (my hint is that during the openmm compilation I turn off something the drude simulations needs .. or just,again, I'm missing something on the node's capsule)  Thanks for all !!!

**Comment by peastman** [comment]
Are you using the OpenCL platform?  If so, you may be running into #1651.  If this is the CUDA platform, though, it's probably something different.

> most of them related looking for gl.h

CUDA requires that you have OpenGL development headers installed.  You didn't say what OS you're on, but I assume it's Linux of some sort?  Which package you need to install to get them depends on your distro, but it's probably called mesa-dev or something similar.

**Comment by pscadmin** [comment]
Yup, I saw the post from  John, but the guys here using CUDA (I'll double check with them)

All on Linux  -- Debian 8 Jessie (Will get the dev headers for OpenGL and see where it get us)

**Comment by pscadmin** [comment]
few updates in case somebody find it helpful to troubleshoot  the nan thing.
*  we get the "Particle coordinate is nan" error trying our bluet proof drude simulation even on GTX980 when on CUDA8/OpenMM7.0 which same simulation ran just fine on CUDA6.5/OpenMM6.2 (CUDA is used .. no OpenCL here)

however
* the computational chemists just told me that all is fine without the MonteCarloBarostat  on CUDA8/OpenMM7.0 (nevertheless the solution should be for OpenCL) .. they tried on GTX1080

and here is the funny/best part
* remember my compilation hurdles/problems : yup, after installing OpenGL development headers and compile OpenMM from source against CUDA 8 again, but this time without turning anything off, the guys here are saying that now they can run their simulation even with the MonteCarloBarostat

I'm leaving it alone for now .. letting the guys having fun with it .. hoping they can test something production level (so far they only run short 1 ns simulations) that we can finalize the vnfs capsule for the nodes, do few more benchmarks and then just buy truck load of these GTX1080s

I still think that we are not out of the woods; but peastman having our back I have no doubt all be chirping great soon ... thanks peatman !!! have a great weekend.

**Comment by peastman** [comment]
Don't you love it when problems disappear and you don't know why?  It makes me nervous.

I have to wonder though.  If you didn't have OpenGL headers installed before, you wouldn't have been able to compile the CUDA platform.  So you *must* have been using OpenCL.  Now that you've compiled the CUDA platform, it would pick that by default.  So I still suspect this may be #1651.

**Comment by pscadmin** [comment]
;) ... the thing is that even without the OpenGL headers installed and the minimum of OpenMM that would successfully compile, the testInstallation.py  CUDA test  "Successfully computed forces" which was the original goal to get done by this post.

... let's see if the computational chemists will have any issues ... if they'll have something useful, I'll post it here unless they will  ;)

... (if any help for someone/something) this was off in order to finish the compile without the OpenGL header (and what get the testInstallation.py  pass the CUDA test)

 BUILD_TESTING ON
 CMAKE_BUILD_TYPE Release
 CMAKE_INSTALL_PREFIX /opt/openmm/7.0.1
 CUDA_NVCC_FLAGS
 CUDA_SDK_ROOT_DIR CUDA_SDK_ROOT_DIR-NOTFOUND
 CUDA_SEPARABLE_COMPILATION OFF
 CUDA_TOOLKIT_ROOT_DIR /opt/cuda/latest
 CUDA_nvrtc_LIBRARY /opt/cuda/latest/lib64/libnvrtc.so
 DOXYGEN_EXECUTABLE /usr/bin/doxygen
 OPENCL_INCLUDE_DIR /opt/cuda/latest/include
 OPENCL_LIBRARY /opt/cuda/latest/lib64/libOpenCL.so
 OPENMM_BUILD_AMOEBA_CUDA_LIB OFF
 OPENMM_BUILD_AMOEBA_PLUGIN OFF
 OPENMM_BUILD_CPU_LIB ON
 OPENMM_BUILD_CUDA_COMPILER_PLU ON
 OPENMM_BUILD_CUDA_DOUBLE_PRECI ON
 OPENMM_BUILD_CUDA_LIB ON
 OPENMM_BUILD_CUDA_TESTS ON
 OPENMM_BUILD_C_AND_FORTRAN_WRA ON
 OPENMM_BUILD_DRUDE_CUDA_LIB OFF
 OPENMM_BUILD_DRUDE_OPENCL_LIB OFF
 OPENMM_BUILD_DRUDE_PLUGIN OFF
 OPENMM_BUILD_EXAMPLES ON
 OPENMM_BUILD_OPENCL_DOUBLE_PRE OFF
 OPENMM_BUILD_OPENCL_LIB OFF
 OPENMM_BUILD_OPENCL_TESTS OFF
 OPENMM_BUILD_PME_PLUGIN OFF
 OPENMM_BUILD_PYTHON_WRAPPERS OFF
 OPENMM_BUILD_RPMD_CUDA_LIB OFF
 OPENMM_BUILD_RPMD_OPENCL_LIB OFF
 OPENMM_BUILD_RPMD_PLUGIN OFF
 OPENMM_BUILD_SHARED_LIB ON
 OPENMM_BUILD_STATIC_LIB OFF
 OPENMM_GENERATE_API_DOCS OFF
 PYTHON_EXECUTABLE /usr/bin/python
 SWIG_EXECUTABLE                  /usr/bin/swig

**Comment by youxu0** [comment]
I also encountered the problem `exception: Error compiling program: nvrtc: error: invalid value for --gpu-architecture (-arch)` when I excuted `./TestCudaCompiler` after compile. How can I solve it?
The system is CentOS7.4; Cuda 9.0 or Cuda10.0 both tried, and the newest OpenMM v7.3

**Comment by peastman** [comment]
What's the complete error message?  Post the entire output.

Do you also get an error when running simulations, or is it just TestCudaCompiler that fails?

I haven't tried RTX cards, but other people have reported success using them: #2213.

**Comment by youxu0** [comment]
Thanks for response, Peter. That was the full error ouput when I did `TestCudaCompiler`. In case I ran a simulation, I would get such error,
"
Traceback (most recent call last):
  File "./zmrun.py", line 48, in <module>
    simulation = app.Simulation(psf.topology, system, integrator, platform)
File "/usr/lib64/python2.7/site-packages/simtk/openmm/app/simulation.py", line 103, in \_\_init\_\_
    self.context = mm.Context(self.system, self.integrator, platform)
  File "/usr/lib64/python2.7/site-packages/simtk/openmm/openmm.py", line 6262, in\ _\_init\_\_
    this = _openmm.new_Context(*args)
Exception: Error launching CUDA compiler: 256
nvcc fatal   : Value 'sm_75' is not defined for option 'gpu-architecture'
"
Yes I noticed that thread which mentioned successful RTX testing, but I couldn't pass this problem in my case. I didn't got this error in another system which has Cuda9.1 and GTX1080Ti.

**Comment by peastman** [comment]
It looks to me like it's probably finding an older version of the CUDA toolkit.  The important line is this one:

```
 nvcc fatal : Value 'sm_75' is not defined for option 'gpu-architecture'
```

sm_75 indicates a Turing GPU.  The error message means it's linking to a version of the nvrtc library that doesn't support that architecture, so something before CUDA 10.  Check your LD_LIBRARY_PATH to see which CUDA library directory you're linking against.

**Comment by youxu0** [comment]
Got it now. You are right. It is the issue of library link. I failed in compilation before because a CUDA 9 library was accidentally linked, but only CUDA10 is compatible with RTX2080Ti here. Thank you again!

**Comment by MatthewMasters** [comment]
I am having a similar issue as I get the error
`Exception: Error launching CUDA compiler: 256
nvcc fatal   : Value 'sm_75' is not defined for option 'gpu-architecture'`

I am trying to use it inside an nvidia-docker container running on CUDA 10.1 with an RTX series card. The simulation works using older CUDA on GTX series.

**Comment by peastman** [comment]
Are you sure you're really using the CUDA 10.1 version of nvcc?  According to the documentaton, `sm_75` is a valid choice: https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#gpu-feature-list

**Comment by MatthewMasters** [comment]
Thanks for your swift reply, Peter! When I type nvidia-smi into the docker container, it states it is using CUDA 10.1 and appears like this:
`+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.43       Driver Version: 418.43       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|   0  GeForce RTX 2070    Off  | 00000000:01:00.0  On |                  N/A |
|  0%   38C    P8    29W / 185W |   1392MiB /  7949MiB |     12%      Default |
+-------------------------------+----------------------+----------------------+
...
`

**Comment by peastman** [comment]
That's telling you what driver version it's using.  What matters here is what version of nvcc it's using.  Try executing `/usr/local/cuda/bin/nvcc --version` and see what it prints.  Or if you've set `OPENMM_CUDA_COMPILER`, execute whatever you've set it to.

**Comment by e-osipov** [comment]
Is it possible to trick openMM that GPU has architecture sm_70 without compilation?

**Comment by peastman** [comment]
I'm not sure what you mean?  If your CUDA is new enough to support Turing GPUs, specifying sm_75 should work fine.  And if you have an old CUDA installed that doesn't support Turing GPUs, it probably won't work no matter what you specify.

**Comment by e-osipov** [comment]
Peastman, sorry, I will try to expain what I want to do and why:
I am trying to use WATsite 3.0, which is built on top of OpenMM. Authors have slightly modified OpenMM source code and added several new attributes to  WATsite authors provide their software in form of docker container with OpenMM 7.2 and CUDA 9.1. My host system has RTX2080 GPU which has gpu-architecture sm_75 and which is not available in CUDA 9.1
Here comes the problem: I can compile OpenMM with CUDA 10.1 and it works fine but WATsite is not working due to missing modifications in OpenMM code. Authors of WATsite do not respond to my mails so I thought it is somehow possible to trick system into using sm_70 instead of sm_75

**Comment by peastman** [comment]
I don't think that would work.  The real problem is that CUDA 9.1 doesn't support Turing GPUs.  If you're using a recent GPU, you have to have a CUDA toolkit that's new enough to support it.

**Comment by e-osipov** [comment]
Does it means that Turing GPUs do not support sm_70?

**Comment by peastman** [comment]
No, there's no way to change that.  That function is built into the driver.

It isn't just a question of what compilation flags you use.  The CUDA toolkit also comes with a bunch of libraries for things like FFTs and matrix operations.  You need versions of those libraries that work with your GPU.

**Comment by e-osipov** [comment]
Okay, that's sad. Thank you for response.

**Comment by huanyusb** [comment]
Hi, I am using a RTX 3090 server, the driver version is  455.32.00 and the CUDA version is 11.1
the 

> python -m simtk.testInstallation

 return a similar error:
`OpenMM Version: 7.5
Git Revision: b49b82efb5a253a7c891ca084b3370e181de2ea3

There are 4 Platforms available:

1 Reference - Successfully computed forces
2 CPU - Successfully computed forces
3 CUDA - Error computing forces with CUDA platform
4 OpenCL - Successfully computed forces

CUDA platform error: Error compiling program: nvrtc: error: invalid value for --gpu-architecture (-arch)`

Could anyone give me some advise? Many Thanks!

**Comment by peastman** [comment]
That ought to work.  Are you sure it's really using CUDA 11.1?  For example, you may have multiple toolkits installed, and conda may have installed one or more additional ones.  That error is what I would expect if it's somehow linking to an older CUDA toolkit.

**Comment by huanyusb** [comment]
> That ought to work. Are you sure it's really using CUDA 11.1? For example, you may have multiple toolkits installed, and conda may have installed one or more additional ones. That error is what I would expect if it's somehow linking to an older CUDA toolkit.

Thanks for your reply. I checked the CUDA toolkit version and found that the server version is 11.1.1 but the conda version installed with openmm is 11.0.3. I tried to install a 11.1 version  conda environment with the command:

> conda install -c conda-forge openmm cudatoolkit=11.1
but it returns the following conflict informations:

> Collecting package metadata (current_repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Collecting package metadata (repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: |
> Found conflicts! Looking for incompatible packages.
> This can take several minutes.  Press CTRL-C to abort.
> failed
> 
> UnsatisfiableError: The following specifications were found to be incompatible with each other:
> 
> Output in format: Requested package -> Available versions
> 
> Package cudatoolkit conflicts for:
> openmm -> cudatoolkit[version='10.0|10.0.*|11.0|11.0.*|10.1|10.1.*|10.2|10.2.*|9.2|9.2.*']
> cudatoolkit=11.1The following specifications were found to be incompatible with your system:
> 
>   - feature:/linux-64::__glibc==2.31=0
>   - feature:|@/linux-64::__glibc==2.31=0
>   - openmm -> __glibc[version='>=2.17']
>   - openmm -> cudatoolkit[version='11.0|11.0.*'] -> __glibc[version='>=2.17,<3.0.a0']
> 
> Your installed version is: 2.31

**Comment by peastman** [comment]
We're attempting to address the above problem in a few ways.  One is to support newer CUDA toolkits with conda (see #3016).  In #3017 I also tried to make it automatically handle this situation better, so it would never request an architecture your toolkit didn't support.  Unfortunately, that turns out to require a feature that was only added in CUDA 11, so we can't use it at present.  Finally, in #3018 I made it easier to work around the problem.  If you get errors with the runtime compiler, you can just set `OPENMM_CUDA_COMPILER` to force it to use a compiler that you know is up to date.

**Comment by greglandrum** [comment]
I'm encountering the same error message on a new (to me) Centos 7.9 workstation:
```
(py39_rdkit) [glandrum@belgium mdfptools]$ python -m simtk.testInstallation

OpenMM Version: 7.5.1
Git Revision: a9cfd7fb9343e21c3dbb76e377c721328830a3ee

There are 4 Platforms available:

1 Reference - Successfully computed forces
2 CPU - Successfully computed forces
3 CUDA - Error computing forces with CUDA platform
4 OpenCL - Successfully computed forces

CUDA platform error: Error compiling program: nvrtc: error: invalid value for --gpu-architecture (-arch)


Median difference in forces between platforms:

Reference vs. CPU: 6.31163e-06
Reference vs. OpenCL: 6.75891e-06
CPU vs. OpenCL: 8.14411e-07

All differences are within tolerance.
```

According to nvidia-smi I've got a GeForce GTX650 with these driver/cuda versions:
```
| NVIDIA-SMI 460.39       Driver Version: 460.39       CUDA Version: 11.2     |
```

I installed the cudatoolkit (v11.2.0) and openmm (v7.5.1)  from conda-forge 

I don't seem to have any other cuda toolkits installed; at least there's nothing in /usr/local/conda.

Is there any way I can collect more information about what's going on here to help track down the problem?
