### ISSUE TITLE
Issues with Linear Molecules like Acetonitrile in OpenMM

### ISSUE THREAD

**Issue by leelasd** [openmm/openmm#1672]
Hi all, 
 
I am trying to simulate pure acetonitrile in OpenMM. For some reason, OpenMM complains about Nan in positions  when I try to minimize one CH3CN molecule. Anyone has any suggestions about solving this issue.   I attached .pdb and forcefield .xml files

```
from simtk.openmm.app import *
from simtk.openmm import *
from simtk.unit import *
import os, re, sys
pdb = PDBFile('CH3CN.pdb')

for atom in pdb.topology.atoms():
    if atom.element.symbol == 'D':
        atom.element = None
forcefield = ForceField('CCN.xml')
modeller= Modeller(pdb.topology,pdb.positions)
system = forcefield.createSystem(modeller.topology)
integrator = LangevinIntegrator(300*kelvin, 1/picosecond, 0.001*picoseconds)
simulation = Simulation(modeller.topology, system, integrator)
simulation.context.setPositions(modeller.positions)

print('Minimizing...')
LocalEnergyMinimizer.minimize(simulation.context)
```
[CH3CN.pdb.txt](https://github.com/pandegroup/openmm/files/601639/CH3CN.pdb.txt)
[CCN.xml.txt](https://github.com/pandegroup/openmm/files/601641/CCN.xml.txt)

**Comment by jchodera** [comment]
Didn't we run into this problem before? I believe the issue had to do with linear harmonic angle terms.

The only related issue I can find through searching is this one:
https://github.com/pandegroup/openmm/pull/54

My guess is that:
* (1) the angle terms don't behave well near 180 degrees
* (2) torsions don't behave correctly when three sequential atoms are collinear

Bill Swope proposed some more robust energy and force expressions [for just this case](10.1002/jcc.540130508).

**Comment by leelasd** [comment]
@jchodera  

Yes, I tried to take care of issue 1 by a dummy atom to divide the angle into 90 and 90 instead of 180.  But it still gives Nan

**Comment by leelasd** [comment]
@jchodera Link you posted for Bill Swopes work is not working, can you please send me the name of the paper ?

**Comment by jchodera** [comment]
Whoops! Here you go:

http://dx.doi.org/10.1002/jcc.540130508

**Comment by leelasd** [comment]
How did you deal with these molecules in your Liquid Benchmark paper with OpenMM. Any suggestions or scripts  would be a great help
