### ISSUE TITLE
[Discussion] Implementing Pair-Specific Parameters for AmoebaVdwForce

### ISSUE THREAD

**Issue by yudongqiu** [openmm/openmm#1705]
Dear Developers,

We were curious that how feasible it is to implement the pair-specific interactions in AmoebaVdwForce. An example xml file we have in mind would look like:

```  
<AmoebaVdwForce type="BUFFERED-14-7" radiusrule="CUBIC-MEAN" radiustype="R-MIN" radiussize="DIAMETER" epsilonrule="HHG" vdw-13-scale="0.0" vdw-14-scale="1.0" vdw-15-scale="1.0" >
    <!-- H2O params from amoeba2013.xml -->
    <Vdw class="43" sigma="0.3405" epsilon="0.46024" reduction="1.0" />
    <Vdw class="44" sigma="0.2655" epsilon="0.056484" reduction="0.910" />
    <!-- ion params from amoeba2013.xml -->
    <Vdw class="46" sigma="0.302" epsilon="1.08784" reduction="1.0" />
    <Vdw class="54" sigma="0.413" epsilon="1.42256" reduction="1.0" />
    <!-- pair-specific parameters -->
    <Vdwpair class1="43" class2="46" sigma="0.3" epsilon="0.6"/>
</AmoebaVdwForce>
```
Here the pair-specific parameters sigma and epsilon may overwrite the ones generated by the combining rules. The reduction factor may be inherited from the atom-specific keys. This will give us a great boost in the flexibility when parameterizing the VdW parameters of a forcefield.

Thanks,

Yudong Qiu

**Comment by jchodera** [comment]
While this sounds like it would be a great extension to `ForceField`'s `ffxml` format, it should be possible to implement this as a `CustomNonbondedForce`. Here's [an example](https://github.com/choderalab/alchemy/blob/master/alchemy/alchemy.py#L1308-L1351) of a partial implementation of the Halgren potential. The pair-specific combining rules could be implemented by a [tabulated function](http://docs.openmm.org/7.0.0/api-python/generated/simtk.openmm.openmm.CustomNonbondedForce.html#simtk.openmm.openmm.CustomNonbondedForce.addTabulatedFunction).

**Comment by peastman** [comment]
The problem with using a CustomNonbondedForce is that AmoebaVdwForce computes forces based on modified positions for the hydrogens instead of their actual positions.

**Comment by zhi-wang** [comment]
The "vdwpair" has been implemented here.

[https://github.com/pren/tinker-openmm/blob/master/plugins/amoeba/openmmapi/include/openmm/AmoebaVdwForce.h#L187](url)

Combined r-min and epsilons will be computed in the first place, and then be updated by the special vdwpair parameters.

This force handles the positions of the hydrogens properly.

**Comment by mjschnie** [comment]
Any thoughts on where this is at? It seems there are at least 3 alternatives:
1) Start from what John linked, and extend CustomNonbondedForce to handle reduced hydrogen positions.
2) Pull in the additions to the AmoebaVdWForce from Pengyu's code. This may be the easiest short term solution.
3) Create a new class "CustomAmoebaVdWForce" that combines the support for reduced hydrogen positions in AmoebaVdWForce with the support for an arbitrary energy function from CustomNonbondedForce. This might be a more general solution?

**Comment by jchodera** [comment]
One other idea: Could the hydrogen interaction sites be implemented as [virtual sites](http://docs.openmm.org/latest/userguide/theory.html#virtual-sites)?

**Comment by mjschnie** [comment]
Virtual sites are an interesting idea - would there be a performance hit since the number of particles would increase by a factor of ~1.6x for a water box?

**Comment by jchodera** [comment]
We could benchmark this to see if it would make a significant impact, but my guess is that, since this will only impact the number of vdW interactions in a `CustomNonbondedForce` but not the electrostatics, it would have minimal impact.

**Comment by mjschnie** [comment]
Cool - I'll give Virtual sites a try and report back.

**Comment by jchodera** [comment]
BTW, we're working on a new forcefield format definition that is intended to be more generalizable, with the goal of making it easy to try experiments like this (e.g. adding virtual sites that move the charges off hydrogens):
https://github.com/openforcefield/openforcefield/blob/master/The-SMIRNOFF-force-field-format.md

It would be great if you had a chance to give some feedback on extensions you might like to see for better polarizable forcefield support in the future!

**Comment by peastman** [comment]
Using virtual sites will hurt performance.  Even though you only care about them for the vdw force, the multipole force is still going to have to include them.  This is an unfortunate consequence of how GPUs work.  Trying to exclude uncharged particles from the calculation just leads to thread divergence.  If even one particle in a block of 32 is charged, you end up paying the cost of computing the interaction for all 32 of them.

I'd be inclined to just add the features to AmoebaVdwForce.

**Comment by peastman** [comment]
This was added in #2765.
