### ISSUE TITLE
View generated source code for Custom* objects?

### ISSUE THREAD

**Issue by pgrinaway** [openmm/openmm#1762]
Hi,

I was wondering if there is currently a way to view the code that the Custom* objects generate from Lepton expressions (does it get cached somewhere?). If not, no big deal, but I figured I'd ask in case there was a straightforward answer. The reason I ask is that I think it would help understand and debug Custom*Force and CustomIntegrator implementations--but again, I'm just checking to see if there's an easy way to do this.

Thanks!

**Comment by peastman** [comment]
There's no public API for doing it, but if you don't mind adding a bit of debugging code, it's pretty easy to pull it out.  For example in the CUDA platform, all kernels get compiled by `CudaContext::createModule()`, so you can have that print out the source code it's compiling.

**Comment by jchodera** [comment]
I don't think these functions are exposed from the Python swig wrappers though---are they?

**Comment by pgrinaway** [comment]
They're in the C++ layer. That's fine (for my purpose anyway). Thanks @peastman !
