### ISSUE TITLE
Drude particles have zero mass

### ISSUE THREAD

**Issue by peastman** [openmm/openmm#1766]
The CHARMM polarizable force field lists all Drude particles as having zero mass.  This causes the simulation to blow up as soon as you start simulating it.  This happened because CHARMM's definition file `toppar_drude_master_protein_2013a.str` lists all of them as massless, and the conversion script faithfully copied that over:

```
MASS   225 DRUD      0.00000 H  ! drude particle 
```

Apparently when you actually use the force field, you're supposed to override that with a command line argument (see https://www.charmm.org/charmm/documentation/by-version/c40b1/params/doc/drude/).  They recommend a value between 0.1 and 1.0.

Of course you can do the same thing in OpenMM by having your script loop over the drude particles and adjust their masses, but that's not very user friendly.  The simplest solution would be to change the force field file to specify a non-zero mass.  That's how force fields are expected to work: they define the masses of all your atom types.  If we do that, we need to pick a value for the mass.  Alternatively we could add an option somewhere for overriding drude masses, though that becomes more awkward, and could cause issues if a polarizable force field actually does specify correct masses.

**Comment by jchodera** [comment]
For purposes of maintaining provenance information of the origin of parameters and making it easy to update them in the future, it would be best if we could avoid modifying the parameter files directly.

Is there a way to override the parameters, if they are present, by specifying an additional CHARMM stream file `openmm.str` that could be included to do this?

If not, it might be best to add an optional argument added to the CHARMM loaders that specifies the override mass for massless particles, and set this to a sensible default.

For choosing a sensible default, we presumably want to select a mass such that the period of oscillation `T = sqrt(K/m) / (2*pi)` is ten times larger than the timestep. Where do we find the spring constants for these?

**Comment by peastman** [comment]
Note this is only relevant if you're using `DrudeLangevinIntegrator`.  For `DrudeSCFIntegrator`, it's fine for the drude particles to be massless.

**Comment by peastman** [comment]
This isn't about the CHARMM loaders.  This is when you load a PDB file and specify the built in XML file for the CHARMM polarizable force field.  The CHARMM loaders should work fine (as far as I know).

**Comment by peastman** [comment]
> we presumably want to select a mass such that the period of oscillation T = sqrt(K/m) / (2*pi) is ten times larger than the timestep.

If that were the criterion, the Drude particles would need as a large a mass as real atoms.  Instead, you generally use a smaller mass, but maintain stability by coupling them to a very low temperature thermostat with a large friction coefficient.

**Comment by jchodera** [comment]
> This isn't about the CHARMM loaders. This is when you load a PDB file and specify the built in XML file for the CHARMM polarizable force field. The CHARMM loaders should work fine (as far as I know).

Ah, I see---so we'd need to either modify `ForceField` to substitute zero masses (seems undesirable), modify the conversion scripts to specify a mass (probably reasonable), or specify the masses to be tags that *require* the user to provide `ForceField` with a drude mass (probably also undesirable unless we set a sensible default).

> If that were the criterion, the Drude particles would need as a large a mass as real atoms. Instead, you generally use a smaller mass, but maintain stability by coupling them to a very low temperature thermostat with a large friction coefficient.

Isn't the period of a harmonic oscillator independent of temperature? I don't see how using a smaller temperature gets around that issue. 

I think the typical `KDRUDE` spring constant is 500 kcal/mol/A**2.
For `m = 1 amu`, this works out to
```python
T = unit.sqrt((1*unit.amu) / (500*unit.kilocalories_per_mole/unit.angstroms**2)) / (2*pi)
= 0.348*unit.femtoseconds
```
So, I'm not sure what makes sense here.

From a statistical mechanical perspective, this turns out to be equivalent to simulating an NVT Hamiltonian system at the standard temperature `T` with the spring constant modified to `K*(T/T_low)`, but that is only an equilibrium distribution effect.

**Comment by peastman** [comment]
The formula is different for a damped harmonic oscillator.  The frequency decreases with the friction coefficient, and once it reaches the point of being critically damped, it no longer oscillates at all.  Also, the definition of "stability" changes when you have damping.  Instead of needing errors to add negligible energy to the system, you just need them to add less energy than the damping takes out.

The CHARMM documentation recommends a mass in the range of 0.1 to 1.0 amu.

**Comment by jchodera** [comment]
Is it really overdamped? What collision rate is typically used for the Drude particles---the OpenMM [`DrudeLangevinIntegrator`](http://docs.openmm.org/7.1.0/api-python/generated/simtk.openmm.openmm.DrudeLangevinIntegrator.html#simtk.openmm.openmm.DrudeLangevinIntegrator) doesn't seem to list a default.

As I understand it, the relevant [damping ration](https://en.wikipedia.org/wiki/Damping_ratio) is
```
zeta = (m * gamma) / (2 * sqrt(k*m))
```
where `m = 1*amu`, `k = 500*kilocalories_per_mole/angstroms**2`. If `gamma=91/picoseconds`, as in a typical Langevin simulation, that gives for `zeta`
```python
>>> (m * gamma) / (2 * sqrt(k*m))
0.09947880429910742
```
which is not even close to being critically damped or overdamped.

At this point, the choice of integrator also becomes extremely important. Here is Figure 3 from [Leimkuhler and Matthews](https://arxiv.org/abs/1304.3269), showing how the error in `<x^2>` for a harmonic oscillator with `m=k=gamma=beta=1` (equivalent to `zeta = 0.5`, period `T=2*pi`) can accumulate horrifically large errors for step sizes approaching `1/(2*pi)*T`:
![image](https://cloud.githubusercontent.com/assets/3656088/24325710/39bd558a-1175-11e7-83b9-76077e56394c.png)

**Comment by jchodera** [comment]
I can't seem to figure out what Langevin integrator the Drude oscillator plugin implements. The [user documentation](http://docs.openmm.org/7.1.0/userguide/library.html#drude-plugin) doesn't specify a reference, nor does the [API reference](http://docs.openmm.org/7.1.0/api-python/generated/simtk.openmm.openmm.DrudeLangevinIntegrator.html#simtk.openmm.openmm.DrudeLangevinIntegrator). The [code](https://github.com/pandegroup/openmm/blob/f7935fef719ed0cd8292afef676c39d881b6a960/plugins/drude/platforms/cuda/src/CudaDrudeKernels.cpp) makes no reference to a citation nor the equations being integrated, and it's quite difficult for me to figure out what kind of integrator splitting scheme is used here. 

It might also be useful to add some additional information on what the "hard wall" constraints do to the [API docs](http://docs.openmm.org/7.1.0/api-python/generated/simtk.openmm.openmm.DrudeLangevinIntegrator.html#simtk.openmm.openmm.DrudeLangevinIntegrator). The [CHARMM docs](https://www.charmm.org/charmm/documentation/by-version/c40b1/params/doc/drude/) are fairly specific:

> When drudes go too far away from nucleus, simulations could be very unstable. Introducing hard wall constraints on the length of drude bonds is a possible way to avoid such instability. In each MD step, the length of drude bonds are checked and compared with "L_WALL". When the length of drude bond is larger than "L_WALL", the relative velocities along bond vector are flipped and scaled down according to  the temperature of drude bond. The displacement relative to "L_WALL" is flipped and scaled down according to new velocities along bond vector to make sure drude bond is not longer than "L_WALL".

I can add some documentation about the hard wall, but I can't quite figure out the Langevin integrator here.

**Comment by jchodera** [comment]
Perhaps it's [this paper](http://dx.doi.org/10.1021/jz101461d), which documents a Langevin scheme for NAMD based on the [BBK integrator](http://atbweb.stanford.edu/scripts/papers.php?sendfile=273) implemented in CHARMM? If so, we may also want to replace it with a better integrator.

**Comment by peastman** [comment]
All the Langevin integrators in OpenMM use the method described in this paper:

Jesús A. Izaguirre, Chris R. Sweet, and Vijay S. Pande. Multiscale dynamics of macromolecules using Normal Mode Langevin. Pacific Symposium on Biocomputing, 15:240–251, 2010.

**Comment by jchodera** [comment]
This is the Langevin Leapfrog method (Section 2.2)?
![image](https://cloud.githubusercontent.com/assets/3656088/24382115/3852d1ee-1322-11e7-8bdd-8fade9aa67f8.png)
If so, this seems to be equivalent to OVRVO / OBABO / VVVR / Bussi-Parrinello, which thankfully behaves quite well for the harmonic oscillator. 

I wonder if they've considered using multiple timestep methods for the Drude oscillators...

**Comment by peastman** [comment]
> This is the Langevin Leapfrog method (Section 2.2) of the paper?

Correct.

**Comment by peastman** [comment]
`createSystem()` now sets a non-zero mass for Drude particles by default.
