### ISSUE TITLE
Replacing the standard functional forms in OpenMM with non-standard ones 

### ISSUE THREAD

**Issue by janeyin600** [openmm/openmm#1770]
We are currently interested in incorporating generic functional forms with the APR-OpenMM workflow, to allow people to test all kinds of force fields with our standard benchmark systems. I've used the CustomBondForce( ) function to define additional interactions (e.g. restraints ) in my APR scripts, but I don't know how to overwrite the standard functions.

I wonder if there is a way to void the standard functional form in OpenMM, or only include part of it in my Python scripts, then I don't need to heavily hack the OpenMM code or write a new plugin. Examples would be appreciated. Thanks!

**Comment by peastman** [comment]
OpenMM doesn't have a "standard functional form".  It just gives you a large collection of forces you can include in your System.  Some of those have fixed functional forms (such as HarmonicBondForce) while others let you pick your own functions (like CustomBondForce).  But either way you're free to pick which ones you want.  If you don't add a HarmonicBondForce, you won't get harmonic bonds.  Same for all the others.

Reading between the lines, my guess is that you're using one of the bundled force fields, and you want to change its form?  Each force field is defined by an XML file.  The bundled ones are included in the `simtk/openmm/app/data` directory.  You can also create your own, or start from one of the standard ones and create a modified version.  For example, if the force field uses harmonic bonds but you want a different form, create a copy of the XML file, then replace the `<HarmonicBondForce>` tag with a `<CustomBondForce>` tag.  You can find documentation at http://docs.openmm.org/7.1.0/userguide/application.html#creating-force-fields.

**Comment by Janeyin600** [comment]
Thanks for your reply! OK so If I start with a PDB file of a protein system, I could easily change the XML file that defines the force field:

pdb = app.PDBFile('input.pdb')
forcefield = app.ForceField('MyOwnFF.xml', 'tip3p.xml')

But, if I start with AMBER topology files, since OpenMM currently cannot parameterize small molecules, the force field is not explicit defined in the script. Would modifying the XML file still work?
