### ISSUE TITLE
Minimum OSX version to support for conda packages for eventual conda-forge migration

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#1791]
@peastman : @Lnaden has put in a huge amount of work migrating our omnia build systems to a [CentOS 6 image based on the conda-forge `linux-anvil`](https://hub.docker.com/r/jchodera/omnia-linux-anvil/) as part of a multi-stage process that will soon allow non-OpenMM packages to start migrating to conda-forge.

As part of this build infrastructure upgrade, we are trying to figure out how best to deal with the [imminent deprecation of the travis `xcode6.4` build image](https://docs.travis-ci.com/user/osx-ci-environment/#OS-X-Version), which was to [be retired Jan 20 (of presumably 2017)](https://docs.travis-ci.com/user/osx-ci-environment/#Xcode-6.4). The oldest available image will be [Xcode 7.3.1](https://docs.travis-ci.com/user/osx-ci-environment/#Xcode-7.3.1), which appears to support the 10.11 build framework as the earliest pre-installed framework.

Do we want to continue to support osx versions as early as 10.7? If so, we may have to go through [some gymnastics to do that on travis](https://forums.developer.apple.com/thread/43381), if this is even possible.

Note that conda-forge will have to deal with this soon, since they currently use the same `xcode6.4` image.

Tagging @mpharrigan or input too.

**Comment by peastman** [comment]
Based on the discussion at https://github.com/omnia-md/conda-dev-recipes/pull/86#issuecomment-296752993, it sounds like we can reasonably keep supporting versions back to 10.9.  I'm ok with moving to that as the minimum requirement.

Note that the conda build can set this by setting the `CMAKE_OSX_DEPLOYMENT_TARGET` CMake variable.  By doing that, the conda builds will require 10.9, but users who build from source can still build for earlier versions.

**Comment by Lnaden** [comment]
What about the [hard coded](https://github.com/pandegroup/openmm/blob/fbf193fe366dbd1a9c39eec754f737b42d24acac/wrappers/python/setup.py#L195) python build version in the `setup.py` file?

**Comment by peastman** [comment]
I'm not sure if that will be a problem or not.  According to http://stackoverflow.com/questions/2923502/what-does-macosx-version-min-imply, it's ok to specify an older minimum version along with a newer SDK, so that might not cause any problems.  But we'll have to try it and find out.

**Comment by Lnaden** [comment]
Okay. So the clang part of the build will work backwards, so long as the version is not less than the compiled python min version. I'm fine with this fix for now then.

The big problem I see is that `conda-forge` is also on xcode6.4 through travis where I'm pretty sure all their packages are built from. When they are also kicked off xcode6.4, I would imagine all their packages will rebuild on the new xcode7.3.1 with macosx10.11. This will again rebuild the python against a min deployment version of 10.11 and we will be right back here once more.

We should get a much better idea about the severity and timescale of this problem once I hear back from the Travis support about the actual timeline of the xcode6.4 image, and once I hear back from the [python-feedstock](https://github.com/conda-forge/python-feedstock/issues/137) maintainers about the fact that anaconda-python and conda-forge-python differ in minimum macosx versions.

**Comment by Lnaden** [comment]
We can actually de-prioritize this issue. The Travis site had a typo. They retired xcode 6.**1** on Jan 20th, there is no time-line right now to retire 6.**4** based on the reply I got from Travis Support.

**Comment by jchodera** [comment]
@Lnaden : We still have to bump the minimum supported OSX version from 10.7 to 10.9 if we want to migrate to `conda-forge` though, right?

**Comment by Lnaden** [comment]
Yes, but we will have much more time to use the 10.9 macosx instead of having to bump to 10.11 than I originally thought.

**Comment by Lnaden** [comment]
I should have been more clear, we can de-prioritize the xcode version part of this issue. I'll update my comment to avoid confusion
