### ISSUE TITLE
Should LangevinIntegrator really use computeShiftedKineticEnergy?

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#1795]
I just happened to notice that the `CPU` platform [uses `computeShiftedKineticEnergy` to compute the kinetic energy for `LangevinIntegrator`](https://github.com/pandegroup/openmm/blob/master/platforms/cpu/src/CpuKernels.cpp#L1331-L1333). However, `LangevinIntegrator` implements the [Langevin Leapfrog method of Sweet and Izaguirre](https://github.com/pandegroup/openmm/issues/1766#issuecomment-289615072) actually has a symplectic velocity Verlet core, and the positions and velocities are not lagged by half a timestep (unlike for `VerletIntegrator`), so it doesn't seem like the best kinetic energy estimator is to use a half-time-lagged kinetic energy. 

[Our paper on VVVR / OVRVO / Langevin Leapfrog (all equivalent)](https://static1.squarespace.com/static/530562f9e4b06fd3c041e221/t/570565b8859fd0cd178da184/1459971513029/Time+step+rescaling+recovers+continuous-time+dynamical+properties+for+discrete-time+Langevin+intergration+of+nonequilibrium+systems.pdf) showed the optimal estimate for mean-squared velocity (and hence kinetic energy) for both zero-force and uniform-fore conditions occurs on-timestep, not at half-timestep (see [Table 2](https://static1.squarespace.com/static/530562f9e4b06fd3c041e221/t/570565b8859fd0cd178da184/1459971513029/Time+step+rescaling+recovers+continuous-time+dynamical+properties+for+discrete-time+Langevin+intergration+of+nonequilibrium+systems.pdf), column for `OVRVO`).

**Comment by peastman** [comment]
This is essential so that `getKineticEnergy()+getPotentialEnergy()` gives the total energy of the system.  Otherwise you're adding kinetic energy at one time to potential energy at a different time, which isn't anything meaningful.

**Comment by jchodera** [comment]
The question is whether the integrator is implemented as in the linked equations. If so, the velocities and positions are SYNCHRONIZED in time, unlike in VerletIntegrator where they are time lagged by half a timestep.

If you implemented a different set of equations or derived a new integrator shifted by half a timestep, it's a different story of course. But the Sweet and Izaguirre integrator shown in the link has positions and velocities synchronized in time.

**Comment by jchodera** [comment]
Specifically: https://github.com/pandegroup/openmm/issues/1766#issuecomment-289615072

**Comment by peastman** [comment]
The positions and velocities are *not* synchronized.  It's a leapfrog integrator where they're offset by half a step.  That's why they call the method "Langevin leapfrog".

**Comment by jchodera** [comment]
Which of the expressions are stored as positions and velocities at the end of the timestep?
![image](https://cloud.githubusercontent.com/assets/3656088/25460283/945e7c5e-2ab0-11e7-8373-52ec64dd4b05.png)
If it is (X^{n+1}, V^{n+1}), they are synchronized. If you've split the steps up in some different way, it's something else (and not equivalent to their integrator).

**Comment by peastman** [comment]
Here's the implementation.  See for yourself:

https://github.com/pandegroup/openmm/blob/master/platforms/reference/src/SimTKReference/ReferenceStochasticDynamics.cpp#L89-L135

What we're doing *is* exactly equivalent to those equations.  They've moved half of the velocity update to the end of the previous step so the velocities will come out synchronized, but that's nothing more than changing what you call the "end" of the time step.

**Comment by jchodera** [comment]
It looks like you've combined the two velocity half-steps into one full velocity step to make the positions and velocities out of phase by one half-step, though it's not clear to me that the constants were correctly combined for both the forces (algebra) and the stochastic steps (which requires correctly scaling the variance).

Assuming the combining of half-steps was done correctly, you're right that the sequence of positions is equivalent in the absence of constraints, though I believe the application of constraints renders these mathematically inequivalent. In any case, this reworking amounts to a Trotter factorization, which yields an inequivalent integrator if velocities and positions are used at the end of the timestep cycle. The original Eqs. 14-16 above describe a splitting equivalent to `OVRRVO`, where `O` denotes velocity perturbation, `V` velocity update, and `R` position update; your reformulation is the non-symmetric `VOOVRR`, which yields very different properties. (That's why you find you need to correct the velocities to get a more accurate estimate of the kinetic energy.)

You can see some of this effect illustrated in the diagram below (credit to @maxentile) that shows the error in phase space and projection into configuration space for a 1D potential for different stages along the cycle for two different integrators: `OVRRVO` and `VROOVR`. Splitting the cycle in different ways can significantly impact the nature and magnitude of errors. 
![image](https://cloud.githubusercontent.com/assets/3656088/25490479/f71eb108-2b3a-11e7-854d-2543931204df.png)
We're working on a paper that describes and quantifies these errors in detail, but I think it will be useful to present a suite of high-quality integrators (implemented via `CustomIntegrator`) to OpenMM users in a future update (maybe OpenMM 7.3). I think this will also tie nicely into @peastman's work on [measures of simulation accuracy](http://biorxiv.org/content/early/2016/10/24/083055), since we now have a tool to explain and quantify the source of errors that are observed.
