### ISSUE TITLE
Drop zip installers?

### ISSUE THREAD

**Issue by peastman** [openmm/openmm#1822]
I'm wondering if the time has come (starting in version 7.2) to stop building zip installers and rely on conda as the only prebuilt binaries.  We've now recommended it as the preferred way of installing for a few versions, and I haven't heard of anyone having trouble with it.  Only having to build one type of installer would simplify the release process and save us work.

The only cases where the zip installers are clearly better are 1) when you want to install on a computer with restricted network access so it can't use conda (the zip installer gives you a single file to copy over), or 2) when you're using OpenMM as a C++ library rather than through Python (it installs in the location of your choice rather than a hidden location deep inside your anaconda install).  But I doubt either of those is a major issue for many people.

I'll also post on the simtk.org forum to get feedback from users there.

**Comment by jchodera** [comment]
+1000 for getting rid of zip installers.

You can still install via conda using a [local tarball file](https://conda.io/docs/commands/conda-install.html), which should handle case (1):
```
 conda  can  also  be called with a list of explicit conda package file‐
       names (e.g. ./lxml-3.2.0-py27_0.tar.bz2).  Using  conda  in  this  mode
       implies the --force option, and should likewise be used with great cau‐
       tion. Explicit filenames and package specifications cannot be mixed  in
       a single command.
```
For case (2), if you need OpenMM to be installed into a special place, you might already have pulled your other dependencies into an automated build framework, so wouldn't necessarily benefit from the ZIP installer. I could maybe see utility in a pure C++ (no Python) library and headers install as an RPM or .deb package, however (like fftw), but I'm not sure demand is high enough.

**Comment by jchodera** [comment]
Anybody else have any opinions about this as we get ready for OpenMM 7.2?

**Comment by mpharrigan** [comment]
+1 from me
