### ISSUE TITLE
Getting Individual Potential Energies

### ISSUE THREAD

**Issue by thomasklau** [openmm/openmm#1830]
Hi All,
I was wondering if a features such as Schrodinger's 'getBondedEnergyComponents' or 'getNBEnergyForTwoAtomLists' in OPLS3 exists as a part of the OpenMM API. These functions evaluate the energy from bonded and unbonded force terms, given two lists of atom numbers (assuming that you know the atom numbering for your structure).

I am interested in getting the energy between unbonded (electrostatic + L-J) and bonded energies (bond energy) between pairs of atoms.

From what I can understand, Forces in OpenMM are grouped be ForceGroups and energies of the forces in ForceGroups are summed whenever we call context.getState(getEnergies = True). We can get the energies of specific forces by assigning that force to a new ForceGroup and passing a group argument.

This solves my problem for bond energies. However, it is unclear to me how to get individual energies for unbonded forces since it appears that an unbonded force is defined per atom and the calculation of unbonded force is summed within a certain cutoff - even before its added to the ForceGroup. I could create an Unbonded Force with only two atoms active, however, that seems like a lot of hackery to get this to work. 

Am I simply overlooking part of the OpenMM API, or was it not designed to do such a thing? Can you think of a simpler way to get energies between atoms for a specific force, using one of the pre-defined force fields?

**Comment by Lnaden** [comment]
Just to clarify what you are trying to do:

During a simulation, you want to select specific pairs of atoms, and compute the energies between them in general, but then further divide the pairs by bonded vs. non-bonded interactions. In effect, you can query at any time:
1. For any number of atomic pairs:
    1. The bonded energy between a pair of atoms (if bonded)
    1. The non-bonded energy between another pair of atoms (if not bonded)
1. The total energy of the system

And then some question about the scope:
1. How many pairs would you be looking at for any given simulation? 
    * Also, how large are your simulations in general?
1. Are the pairs a static set? e.g. Always looking at Pair A-B vs Looking at Pair A-B at one time step and pair A-C at another time step
1. Do you care about individual pairs, or do you care about sets of pairs?
    * Individual pairs: 3 energies from A-B separate from C-D separate from E-F
    * Sets of pairs: 1 energy from A-B + C-D + E-F

As I understand, there is not a strait-forward way to do the arbitrary pairs of atoms which would behave like `context.getState(getParticles=[0,1], ...)` (that argument does not exist, but its just an example). I have a few ideas on how to do some combinations of the things I listed above, but I'd like to get some more information before I rattle off ideas.

**Comment by thomasklau** [comment]
I'm actually mainly interested in looking at these atom-wise interaction energies for crystal structures after a short minimization (with heavy atoms fixed). I'm not worried about doing a query during an MD simulation so there should t be a worry about computational complexity. Right now, I'm simply querying OPLS 3 for non bonded energies for atom pairs within a 5 A cutoff. I calculate bonded energy via schrodinger's structure API.

OPLS allows me to do this for a given structure at one moment of time, however I would like to try out other force fields, specifically polarized force fields. Additionally, it would be nice to eventually release the work in the form of open source code that can be run on other structures (this energy step is a smaller part of a larger project). 

I care about individual pairs, not sets of pairs. I am building a graph of atoms for both a ligand and receptor with energies (bonded and unbounded) serving as the edge weight between atoms. This is why I care about atom pairs and not sets of pairs.

Thanks a bunch for your time. Hope that clears things up. If I can get things working for this I'd happily submit a PR if it could help others in the future.

**Comment by peastman** [comment]
There's no API for doing what you want.  Also keep in mind that what you described isn't necessarily well defined.  For example, you mentioned polarized force fields.  But those are inherently multibody, since the "interaction energy" of a pair of particles actually depends on every other particle in the system as well (since each particle is polarized by its environment).  Also, if you're using PME each "particle" really represents an infinite grid of particles.

Whether all of that matters to you depends on what you're trying to do.  If you just want a measure of how strongly two particles are interacting, you can just compute `q1*q2/r` and leave it at that.  But it's hard to say more without knowing a bit more about what you want to accomplish.

**Comment by Bio-Otto** [comment]
You are looking some thing like grinn program. For openmm there is no specific interface. But you can try to do this by  changing system forces parameters
