### ISSUE TITLE
Continuous3DFunction fails on GPU for large arrays

### ISSUE THREAD

**Issue by tristanc1** [openmm/openmm#1849]
I've been using Continuous3DFunction to define the map potential for MDFF simulations, and on my GTX1080 it fails once the map passes somewhere between 4 and 8 million grid points, with the message:

`Error creating array TabulatedFunction: CUDA_OUT_OF_MEMORY`

The reason I'm reporting this as a bug is that the memory error seems a bit premature. For a 4 million point map and ~50,000 atoms, GPU memory usage sits at about 2 of 8 GB (at least according to the NVIDIA Gnome widget). The memory usage for the TabulatedFunction array itself, if I understand correctly, should be:

`nx * ny * nz * 64 * sizeof(float)`

~ 1GB for a 4 million point map. Yet for a simulation roughly twice the size (111k atoms, 8.8 million grid points) it fails despite theoretical memory usage being <50%.

A fairly obscure problem, I think, but I thought I should report it anyway. Not a big deal to me any more - it made me realise that 3D cubic interpolation is substantial overkill for MDFF (where in almost every case the map has already been oversampled to three times the true resolution anyway), so I went ahead and made a CustomCompoundBondForce based on linear interpolation from a Discrete3DFunction that seems to be working quite nicely.

**Comment by peastman** [comment]
If CUDA is throwing CUDA_OUT_OF_MEMORY, it probably knows what it's talking about, so we should assume it really has run out of memory.  So the question is what is using that memory.  You could try modifying the CudaArray constructor to print out `size*elementSize` just before the call to `cuMemAlloc()`.  That will tell you the size of every array that has been allocated so far, including the one it's trying to allocate when it gets the error.

Also make sure that you aren't creating multiple contexts (if you do, they have to share the device memory), and that no other programs are running that might be using significant amounts of device memory.

**Comment by tristanc1** [comment]
Will try that once I have a few other pressing issues out of the way. I only ever have the one context created, and GPU memory usage from other processes is less than 1GB. One other clue: in one case (which I haven't yet been able to reproduce), after the simulation initialisation crashed with CUDA_OUT_OF_MEMORY I noticed that my 3D graphics performance was significantly degraded (maybe a 3x loss in frame rate), and when attempting to start a new sim with a much smaller map (maybe 100k grid points) it failed with the same error despite the NVIDIA X Server widget showing well under 2GB memory use. That behaviour persisted until I closed and restarted the Python session, at which point it worked again without trouble. Very odd.

**Comment by tristanc1** [comment]
It would appear this boils down to a hard limit on the size of any given 1D array of 2^27 elements (see Table 14 at http://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#compute-capabilities).

Not a problem for me any more, and really just a fundamental hardware limit rather than a bug. Closing.

**Comment by peastman** [comment]
That's good to know about  Thanks for tracking it down.

**Comment by tristanc1** [comment]
Would it be possible to add a check to see if a TabulatedFunction is going to lead to an array bigger than `CL_DEVICE_MAX_MEM_ALLOC_SIZE` (I think the CUDA equivalent is `cudaDeviceProp.maxTexture1D`)  before uploading it to the GPU, and crash gracefully if so? Even better, it would be great to have a Python call to get these limits via the OpenMM API. I have a memory-efficient (if slightly slower) alternative cubic interpolation implementation that only requires the actual map values as a `Discrete3DFunction`, but it would be nice to still be able to use the `Continuous3DFunction` implementation where possible.

**Comment by peastman** [comment]
You could use [PyOpenCL](https://github.com/inducer/pyopencl) to check those limits.
