### ISSUE TITLE
Lambda dynamics

### ISSUE THREAD

**Issue by schrodinger83** [openmm/openmm#1884]
Hello,
Custom integrator in the newest version allows calculating derivative per specific DOF like lambda. I wonder if anyone can share an example that can make use of this feature to run lambda dynamics (or more specifically a multisite-lambda dynamics) calculation for a simple system. I don't know if there is already an example for that even in charmm-openmm which originally implemented the lambda-dynamics.

I would greatly appreciate your help.

**Comment by jchodera** [comment]
We don't yet have a working lambda-dynamics example in OpenMM, but the `CustomIntegrator` in principle allows capabilities like this to be expressed through the use of global parameter derivatives that can be used in integration schemes.

One major challenge to implementing something like multisite lambda-dynamics is the definition of a potential energy function similar to that used in standard CHAMRM multisite lambda-dynamics:
```
U(x; \{ \lambda_{ij} \}) = U_0(x) + \sum_{i=1}^{N_{sites}} \sum_{j = 1}^{M_i} \lambda_{ij} U_{ij}(x)
```
where `i` indexes the sites and `j` the substituent at site `i`. We don't yet have a way to express a potential energy function like this where `\lambda_{ij}` are global context variables and the electrostatics are treated with PME. A discussion about how best to support functionality like this can be found in #1702, but we haven't yet finalized what the API would look like or the features would encompass.

A simple form of this that supports reaction field or GBSA (without cutoffs) could be expressed using `CustomNonbondedForce`, but it would still be somewhat tricky to implement using global context variables. Nobody has yet attempted this to my knowledge.
