### ISSUE TITLE
openmm CustomExternalForce

### ISSUE THREAD

**Issue by maysaylay** [openmm/openmm#1892]
Need some help trying to update per particle parameter using updateParametersInContext() but can't seem to get the syntax right.

**Comment by Lnaden** [comment]
Can you provide a few lines of the code you are trying to run and then what the error actually is? That would help us better diagnose what is happening.

Thanks!

**Comment by maysaylay** [comment]
Thanks. The External force I am using is listed below:

force = mm.CustomExternalForce("-fx*x-fy*y-fz*z")
force.addPerParticleParameter("fx")
force.addPerParticleParameter("fy")
force.addPerParticleParameter("fz")
system.addForce(force)
for i in range(system.getNumParticles()):
    force.addParticle(i, [2.0,3.0,4.0])

#I then change the parameters using a list of bias forces (fcs) calculated during the simulation

for i in range(self.system.getNumParticles()): 
            self.force.setParticleParameters(i,1,fcs[i])

#Question is how do I update the parameters I just set using the updateParametersInContext?

Thank you!

**Comment by peastman** [comment]
Just call `force.updateParametersInContext(context)`, where `context` is the Context you want to copy the parameters to.  Or am I misunderstanding your question?

**Comment by maysaylay** [comment]
That's my question. I tried that but doesn't seem to be efficient for my
system. My goal is to be able to bias the forces on atoms after a certain
number of time steps and this is often done frequently as the bias on the
force also tends to change frequently.  I am calculating the bias within a
python class object akin to your simulated tempering approach. Is the
CustomForce the best option to do this using python or do you suggest a
different approach?

Thank you

**Comment by peastman** [comment]
I'm not sure what you're asking.  Are you saying calling `updateParametersInContext()` doesn't work?  Or that it does work, but it's slow?  Depending on the nature of your bias force, there may be a faster way of implementing it.  But to know that, you need to tell us what you're trying to do and how your bias force is calculated.  Try to be as specific as possible, including equations if possible.

**Comment by maysaylay** [comment]
[ITS.txt](https://github.com/pandegroup/openmm/files/1285824/ITS.txt)
updateParametersInContext() gives this exception "getImplInContext: This Force is not present in the Context". I have attached a copy of the python script and it includes the method used to calculate and update the force bias and update. I am trying to implement the integrated tempering sampling from The Journal of Chemical Physics 128, 064105 (2008) that involves simulating a system over a range of temperatures with each temperature having a 'weight factor' that determines the different contribution of the temperatures to the force acting on the system. 

The calculation of the bias force which is done at every simulation time step requires that I first provide a set of initial 'weight factors'. The calculated force bias is a function of the product of the weight factors and exp(-beta*potentialEnergy). There's also a recipe to update the weight factors after some time interval. It is the fact that the bias force is constantly changing that requires that I set this as new parameters in the custom force that I created.

The part of the python script (attached to this mail) that calculates the bias force and updates the ''weights" is shown below : 
 #***this is where I set up the equations to generate the custom force used to bias the system forces    
    def  _biasForces(self,state):
        potEne = -1.00*state.getPotentialEnergy()
        gfe = [potEne*invt for invt in self.betas]
        gft = [gfe[i] + self._forceBias[i] for i in range(len(self.betas))]
        gf =  [gfe[i] + self._forceBias[i] + math.log(self.betas[i].value_in_unit(unit.mole/unit.kilojoules)) for i in range(len(self.betas))]
        gff = gf[0]
        gftt = gft[0]
        for i in range(1,len(self.betas)):
            if ( gff >  gf[i]):
                gff = gff + math.log(1.000 + math.exp(gf[i] - gff))
            else:
                gff = gf[i] + math.log(1.00 + math.exp(gff - gf[i]))
            if ( gftt >  gft[i]):
                gftt = gftt+ math.log(1.000 + math.exp(gft[i] - gftt))
            else:
                gftt = gft[i] + math.log(1.00 + math.exp(gftt - gft[i]))

        if not (self._constantForceBias):
            if (self.simulation.currentStep%self.forceBiasChangeInterval == 0 or self.counter == 1):
                self.rbfb = gft
            else:
                for i in range(len(self.betas)):
                    if (self.rbfb[i] > (gft[i] - gff)):
                        self.rbfb[i] = self.rbfb[i] + math.log(1.00 + math.exp(gft[i] - gff - self.rbfb[i]))
                    else:
                        self.rbfb[i] = gft[i] - gff + math.log(1.00 + math.exp(self.rbfb[i] - gft[i] + gff))

        f_its = math.exp(gff - gftt)/self.referenceBeta
        fbs = f_its.value_in_unit(unit.kilojoule/unit.mole)
        fcs = [v*fbs for v in self.stur.getForces().value_in_unit(unit.kilojoules_per_mole/unit.nanometer)]
      #***this is where I try to update the parameters after they have been set, this is the source of the error
        for i in range(self.system.getNumParticles()):
            self.force.setParticleParameters(i,i,list(fcs[i]))
        self.force.updateParametersInContext(self.simulation.context)


    #*** this is where I try to update the self._forceBias term used to generate the custom force parameters
    def _attemptForceBiasChange(self, state):
        """change the external factor to bias the forces on atoms."""
        self.updateCount += 1
        for i in range(len(self.betas)-1):
            self.rb[i] = (self.rbfb[i] + self.rbfb[i+1])*0.5
            self.ratio [i] = self._forceBias[i] - self._forceBias[i+1]
            self.normold[i] = self._normalization[i]
            self.value[i] = self.rbfb[i+1] - self.rbfb[i] + self.forceBiasInitializer +  self.rb[i]
        if (self.updateCount == 1 and self._first_ITS):
            for i in range(len(self.betas)-1):
                self._normalization[i] = self.rb[i]
                self.normold[i] = math.pow(-10.0,10)
        else:
            for i in range(len(self.betas)-1):
                if (self._normalization[i] > self.rb[i]):
                    self._normalization[i] = self._normalization[i] + math.log(1.0 - math.exp(self.rb[i] - self._normalization[i]))
                else:
                    self._normalization[i] = self.rb[i] + math.log(1.0 + math.exp(-self.rb[i] + self._normalization[i]))
   
        self.pratio[0] = 0.0
        self._forceBias[0] = -self.pratio[0]



        for i in range(len(self.betas)-1):
            if (self.normold[i] > self.value[i]):
                self.ratio[i] = self.ratio[i] + self.normold[i] - self._normalization[i] + math.log(1.0 + math.exp(-self.normold[i] + self.value[i]))
            else:
                self.ratio[i] = self.value[i] + self.ratio[i] - self._normalization[i] + math.log(1.0 + math.exp(self.normold[i] - self.value[i]))
            self.pratio[i+1] = self.pratio[i] + self.ratio[i]
            self._forceBias[i+1] = -self.pratio[i+1]
        self.rbfb = 0

Thanks!

**Comment by peastman** [comment]
The error message means the force isn't part of the system.  The general procedure is 1) create a system, 2) add forces to that system, and 3) create a context for that system.  Now you're calling `force.updateParametersInContext(context)`, but it's telling you that `force` is not part of that context's system.

I'm not familiar with the algorithm you're implementing.  The important thing is to remember that `updateParametersInContext()` is a bit expensive.  You don't want to be calling it every time step, or you'll slow things down a lot.  If you have parameters that really need to be updated every step, can you reformulate it in terms of a few global parameters?  Those are much faster to update.
