### ISSUE TITLE
Tips on evaluating energies

### ISSUE THREAD

**Issue by stefdoerr** [openmm/openmm#1900]
Sorry if this is covered in some tutorial which I could not find.

I would like to obtain per-atom potential energy.
Looking at issues https://github.com/pandegroup/openmm/issues/1463 and https://github.com/pandegroup/openmm/issues/387 I see that it's possible to separate the energies into bonded, non-bonded etc.

I was wondering rather how I could get a potential energy per-atom. I understand that due to the nature of force-field forces not being just pair forces (i.e. dihedrals being 4 atom forces) there is no unique way of assigning a potential energy to an atom.
Could I however maybe obtain the energy per force evaluation i.e. a `PeriodicTorsionForce` on a group of 4 atoms so that I can average the energy between those atoms?

So is there some way of obtaining the energy of each force object applied to each atom(group?) for each frame of a simulation?

Many thanks in advance!

**Comment by peastman** [comment]
No, there's nothing like that.  As you say, per-atom energies aren't well defined.  What problem are you trying to solve?

**Comment by stefdoerr** [comment]
I practically need this:
http://lammps.sandia.gov/doc/compute_pe_atom.html

They seem to split the energy equally as I was suggesting for 3/4 atom forces.
> For an energy contribution produced by a small set of atoms (e.g. 4 atoms in a dihedral or 3 atoms in a Tersoff 3-body interaction), that energy is assigned in equal portions to each atom in the set. E.g. 1/4 of the dihedral energy to each of the 4 atoms.

From a development perspective how doable do you think it is for us to implement it in OpenMM? 
I could work on it with some help from another labmate if we get a rough idea of where to look.
Speed would not be a huge issue for the moment so if it's easier to do a CPU version I'm fine by that.

**Comment by peastman** [comment]
What I meant is, why do you want to calculate that?  It seems a fairly arbitrary calculation.  Depending on what you want to accomplish, there might be another way of accomplishing the same thing.

You would need to implement it separately for each force, so the complexity depends on what forces you want.

**Comment by forddwork** [comment]
@peastman: atom-centred potential energy is important if you want to find potential energy of a subsystem. Everyone needs to be curious about this, and therefore the code/tutorials should be readily available by now.
