### ISSUE TITLE
Exception raised by getPotentialEnergy() on a State without energies has unintentionally changed

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#1916]
We seem to have unintentionally changed the `Exception` type raised by `State.getPotentialEnergy()` if no potential energy is present:
```
lski2414:ParmEd choderaj$ conda install --yes openmm==7.1.1
Fetching package metadata .................
Solving package specifications: .

# All requested packages already installed.
# packages in environment at /Users/choderaj/miniconda:
#
openmm                    7.1.1                    py36_0    omnia
lski2414:ParmEd choderaj$ python get_energy.py 
Traceback (most recent call last):
  File "get_energy.py", line 6, in <module>
    state.getPotentialEnergy()
  File "/Users/choderaj/miniconda/lib/python3.6/site-packages/simtk/openmm/openmm.py", line 1835, in getPotentialEnergy
    raise TypeError('Energy was not requested in getState() call, so it is not available.')
TypeError: Energy was not requested in getState() call, so it is not available.
lski2414:ParmEd choderaj$ conda install --yes openmm==7.2
Fetching package metadata .................
Solving package specifications: .

Package plan for installation in environment /Users/choderaj/miniconda:

The following packages will be UPDATED:

    openmm: 7.1.1-py36_0 omnia --> 7.2.0-py36_0 omnia/label/dev

lski2414:ParmEd choderaj$ python get_energy.py 
Traceback (most recent call last):
  File "get_energy.py", line 6, in <module>
    state.getPotentialEnergy()
  File "/Users/choderaj/miniconda/lib/python3.6/site-packages/simtk/openmm/openmm.py", line 18371, in getPotentialEnergy
    val = _openmm.State_getPotentialEnergy(self)
Exception: Invoked getPotentialEnergy() on a State which does not contain energies.
```
Since we moved from a specific exception (`TypeError`) to a generic exception (`Exception`) I'm guessing this was unintentional, and that the previous behavior (or at least a more appropriate specific exception) should be restored.

Here's the contents of the `get_energy.py` script:
```python
from simtk import openmm, unit

with open('test/files/state_974wat.xml', 'r') as infile:
    state = openmm.XmlSerializer.deserialize(infile.read())

state.getPotentialEnergy()
```
[`test/files/state_974wat.xml`](https://github.com/ParmEd/ParmEd/blob/master/test/files/state_974wat.xml) is simply a serialized `State` without energies.

**Comment by peastman** [comment]
Not really.  This was caused by reimplementing how States are represented in Python.  Previously, we had a pure Python implementation of states, and a lot of code for translating back and forth between Python and C++ state objects.  #1746 changed that to use SWIG wrapped state objects directly.  The C++ code throws an OpenMMException, and SWIG translates that to the generic Exception class.  That's how we handle all exceptions coming from the C++ library.  The fact that it threw a TypeError before was an anomaly.

**Comment by jchodera** [comment]
Throwing general Exceptions is not helpful to Python code, where good practice is to catch exceptions narrowly. I wonder if there's a simple way we can add a translation table to tell Swig how to translate these exceptions to be more useful at the Python level.

**Comment by peastman** [comment]
We would have to change the C++ code to throw many different exception types.

**Comment by jchodera** [comment]
> We would have to change the C++ code to throw many different exception types.

Not necessarily. It looks like SWIG supports a few different ways of defining code that translates C++ exceptions into Python exceptions, such as [`%exception`](http://www.swig.org/Doc3.0/SWIGDocumentation.html#Customization_exception), [`%throws` typemaps](http://www.swig.org/Doc3.0/SWIGDocumentation.html#throws_typemap), [`%catches`](http://www.swig.org/Doc3.0/SWIGDocumentation.html#SWIGPlus_catches). 

I haven't fully digested this yet, but it looks like we could use [`%exception`](http://www.swig.org/Doc3.0/SWIGDocumentation.html#Customization_exception) blocks to dispatch specific Python exceptions based on the string content of the exception message. This might allow us to define a minimal set of OpenMM exceptions that are translated into relevant Python exceptions without much coding effort.
