### ISSUE TITLE
Support for OPLS-AA style LJ combination rules

### ISSUE THREAD

**Issue by leelasd** [openmm/openmm#1918]
I ran into a problem trying to use OpenMM-Yank Combination to perform FEPs with OPLS-AA force field. I realized that OpenMM does not support Combination rule 3 when Gromacs input files are used. Can you please add support this feature? 

For MD simulations, I have been implementing the OPLS-AA rules using CustomNonBonded force, but seems like Yank does not support such Custom forces.

**Comment by peastman** [comment]
Good idea.  We should be able to do that.

**Comment by leelasd** [comment]
@peastman That would be great. Will be a great help for people who want to do Free energy calculations with OpenMM

**Comment by swails** [comment]
FWIW Parmed’s GROMACS parsers can create an OpenMM System (same api) and it does support combination rule 3. 

So that’s a potential workaround to get you going today.

**Comment by jchodera** [comment]
I'll also need to add support for `CustomNonbondedForce` terms to the alchemical factory here: https://github.com/choderalab/openmmtools/issues/172

If you can make sure the `CustomNonbondedForce` energy expressions use the names `sigma` and `epsilon` for LJ (or `charge` for charges), it will be much easier to make sure we are able to handle this case correctly when metaprogramming the alchemically-modified forces.

**Comment by peastman** [comment]
It looks like Parmed currently uses the names `sig` and `eps`:

https://github.com/ParmEd/ParmEd/blob/3e92cd9cf0ec650cb6966744cfed92bcbb8f1668/parmed/structure.py#L2795-L2798

**Comment by swails** [comment]
@jchodera - those names aren't part of what I consider my public API, so if you want to wrap those name changes into your PR in ParmEd/ParmEd#895 we can take care of this requirement in the latest version of ParmEd.

**Comment by peastman** [comment]
This was added in #2101.
