### ISSUE TITLE
Add System.getMolecules()?

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#1941]
Instead of having to resort to the idiom
```python
        reference_platform = openmm.Platform.getPlatformByName('Reference')
        integrator = openmm.VerletIntegrator(1.0*unit.femtosecond)
        context = openmm.Context(system, integrator, reference_platform)
        molecules_atoms = context.getMolecules()
        del context, integrator
```
to get the definition of molecules in the `System`, what about adding a `getMolecule()` method to `System`?

**Comment by peastman** [comment]
The definition of which atoms are in the same molecule is partly determined by calling `getBondedParticles()` on every ForceImpl.  There's no corresponding method on Force.  It has to create all the ForceImpls before it can identify the molecules.
