### ISSUE TITLE
Possible PBC issue with Context setPositions with multi-unit-cell translations

### ISSUE THREAD

**Issue by jacob-litman** [openmm/openmm#1945]
Hello,

Short version: could you check to see if, for the AMOEBA-CUDA platform, that the Context setPositions method is robust to the possibility that a molecule might have moved by more than one unit cell?

A bit of introduction: I'm a member of the Schnieders lab, working to accelerate some of our algorithms by shifting a lot of the energy calculations to OpenMM running on the GPU. For the most part, it's been amazingly successful, and I really have to thank you for making it so easy to utilize OpenMM as a library.

Our Force Field X software package is written primarily in Java, and while we have our own MD machinery and force field implementation, we've turned to OpenMM for GPU acceleration. We have two paradigms that utilize OpenMM for GPU acceleration. The first one is simply pushing coordinates to the GPU, getting energy and forces back, and using our own machinery to generate new coordinates for the GPU. This is simple, but comes at the cost of lots of PCI bus latency. The second paradigm is requesting that OpenMM take the coordinates, and run a set number of steps on the GPU before returning to FFX running on the CPU. I'll mostly be talking about our second paradigm.

One of the recent issues I ran into was in attempting to restart OpenMM-accelerated MD from one of our restart files. We'd create the OpenMM Context, perform an energy evaluation to ensure certain things were initialized properly, then load our restart file. After loading the restart file, we'd call setPositions on the Context to load the new positions from the restart file.

Where we ran into issues: I ran an explicit-solvent, CUDA-accelerated AMOEBA MD simulation using the OpenMM MD machinery for 10 nanoseconds. When I attempted to restart from the final .dyn file, however, I got NaN energies and general misbehavior if I tried to use OpenMM in any way. If we used our native Java all the way through (energy evaluations and MD), it worked, but not if we sent the coordinates to OpenMM. I was unable to reproduce these errors using short MD runs; the only thing that reproduced it was this DYN from a long trajectory.

How I finally solved things was to load the DYN, recenter molecules into the primary unit cell on the CPU, and only then send updated coordinates to OpenMM. My suspicion is that, due to the relatively long 10 nsec trajectory, some of the water molecules moved by more than one unit cell, and that the Context's setPosition method was unable to handle these multi-unit-cell translations.

If it helps: our fix was commit mjschnie/ffx@40e3f8a87b881006b008916563dcb1818f276948.

The system, our DYN restart, and a PDB saved out from the DYN coordinates:
[errorReproduction.tar.gz](https://github.com/pandegroup/openmm/files/1518853/errorReproduction.tar.gz)

Thank you,
Jacob Litman

**Comment by peastman** [comment]
Yes, it's totally fine with that.  Most likely the problem is that something else in the system isn't getting reset correctly.  For example, are you sure you're setting the box size correctly?  If you have a barostat, it may have changed.

The one place I can see this causing problems is if you're using single precision, and you have positions that are *very* far outside the first periodic box.  Internally, the CUDA platform tries to maintain precision by keeping all the positions within a single periodic box, and separately storing an integral number of box widths that each position has been translated by along each axis.  But when you call `setPositions()`, it initially just records the exact positions you set, converted to single precision.  It then separately calls a routine to translate them into the first periodic box.  But if some of the positions were very large, it may have lost enough precision by initially storing them in single precision to cause the energy to become large.

**Comment by jacob-litman** [comment]
It was an NVT simulation with a standard cubic P1 cell with 8.065 nm box lengths. I don't think the issue stems from sending single-precision coordinates; while some of them had drifted multiple unit cells, none of them had drifted outside an approximately 60x60x60 nm box, and that's not a large enough distance that single-precision error would cause NaN values; it shouldn't even be large enough to cause a noticeable change in energy.

We know the NaN issues were resolved by moving all the molecules back to the primary unit cell before calling setPositions, so it probably has something to do with sending coordinates that are outside either the primary unit cell or adjacent unit cells.

**Comment by peastman** [comment]
What precision mode are you using?  Does switching to double precision affect it?

**Comment by jchodera** [comment]
The CUDA and OpenCL platforms do some processing that involves the current box vectors when calling `setPositions()`. Are you potentially setting the new box vectors *after* `setPositions()`, rather than before?

**Comment by jacob-litman** [comment]
The precision is whatever the default is for AMOEBA-CUDA. The only thing I see in our code is one stray, commented-out reference to setting mixed-precision. I'm assuming switching to double-precision would entail calling the Platform's setPropertyValue(Context context, "Precision", value)?

The box vectors should not be an issue.
1) The box vectors stay absolutely consistent at a 8.065 nm from start to finish.
2) We call setCrystal (which then calls System's setDefaultPeriodicBoxVectors method) before setting the coordinates.
3) It's an NVT simulation.

Thanks for helping track down why we got this issue.

**Comment by peastman** [comment]
You need to set the precision before creating the Context.  The easiest way is to specify it in the `properties` map passed to the Context's constructor: `properties["Precision"] = "double"`.  If you don't specify, it defaults to single.

Another thing you might try: once you're all done setting up the system and context, and just before you're about to start simulating it, call `getState()` and check the positions it returns to make sure they're correct.

**Comment by jacob-litman** [comment]
I've called getState() to print out a PDB file, with the "enforcePeriodicBox" flag set to both true and false. When true, it's pretty reasonable; a box of water with a protein sticking out the side, and an obvious cavity on the other side where the protein's periodic copy is. When false, it's a diffuse cloud of water around a protein, and it's obvious that some of the waters have migrated through multiple periodic boxes to get where they are.

Nevertheless, if I call setPositions() without first mapping the coordinates back to the primary unit cell, I get NaN potential energy.

This works:
Create system from the FFX data structure.
Load periodic box vectors.
Load positions.
Read restart file.
Apply restart file positions to FFX data structure.
Have FFX data structure move its positions back to the primary unit cell.
Send FFX positions and velocities to OpenMM.
Obtain a fresh State (positions, velocities, forces, and energy).
Begin simulating.

What does not work is if I attempt to send the restart file positions directly to OpenMM without first mapping them back to the primary unit cell.

**Comment by peastman** [comment]
> When false, it's a diffuse cloud of water around a protein

But are they the same as the positions you originally specified to `setPositions()`?  What's the maximum amount by which any of them differs from the original position?

What is the largest distance of any atom from the origin?  That will tell us how much precision is potentially being lost.

You also could try using `getState()` to query the initial forces and energy.  Do they look reasonable?  What's the largest force magnitude on any atom?  If it's unreasonably large (more than a few thousand kJ/mol/nm), can you tell what interaction it's coming from?

**Comment by jacob-litman** [comment]
One possible hint is something I should've checked before. If I set it to use the fixed-charge Amber99SB force field, even using the AMOEBA CUDA platform, it works as it should. The code paths on our end are almost the same, except that if we're using fixed-charge, we add a "NonbondedForce", whereas AMOEBA adds an "AmoebaMultipoleForce" and an "AmoebaVdwForce".

With just the van der Waals force, the potential energy is +407108 kJ/mol, which has the strong advantage of being finite. With just the AMOEBA multipole force, the potential energy returns to its full NaN glory.

They're the same positions that were originally specified to setPositions, plus or minus floating-point precision issues. They superimpose perfectly in PyMol, and diffing the PDB file outputs comes up with nothing that can't be explained as a rounding error in the last digit.

The range of coordinates is (-29.3315, -27.2671, -33.9135) to (29.5856, 25.7543, 26.6192), in nanometers.

Our first getState call produces an energy of NaN. None of the forces are reasonable (unless I disable the multipole force as above).

Mean force: 8.367*10^6
Unsigned mean force: 1.166*10^10
Unsigned min force: 1.156*10^5

Min force: -2.147*10^10
Max force: 2.147*10^10

**Comment by peastman** [comment]
Ok, that's a good clue.  Can you use XmlSerializer to write out the System and State (including positions, velocities, and parameters) to XML files and send them to me?  That should hopefully let me reproduce it and see where the large forces are coming from.

**Comment by jacob-litman** [comment]
We're working on getting those XML files generated, but it may take a bit; the auto-generated JNA wrappers aren't very helpful, so we'll probably need to custom-write JNA wrappers for the XMLSerializer.

In the meantime, there is still the workaround of first translating all the coordinates back to the primary unit cell before sending them to OpenMM, and I've added a flag our code to request that States enforce PBC.

Thanks again,
Jacob Litman

**Comment by peastman** [comment]
If serializing it is hard, we can just move forward on trying to debug it directly.  Here are some things you can check:

- Try changing the nonbonded method to NoCutoff.  Does that make the energy become reasonable?
- What if you change the polarization type to Direct?  If that fixes the energy, it suggests the problem is somehow related to polarization.
- Try calling `getInducedDipoles()`.  Do the dipoles look reasonable?  Or perhaps some are and some aren't, which would give a clue as to where the problem is coming from.  (Try this with both direct and mutual polarization.)

**Comment by jacob-litman** [comment]
So, a few updates:

We might still be able to write JNA wrappers for the XML serializer, but nothing there yet so far.

Testing the NoCutoff method awaits GPU availability; my local machine has only 512 MB of VRAM, which struggles even with PME turned on. The supercompute cluster here has P100s, but we keep them rather busy.

Direct polarization works, so it's probably a mutual polarization issue.

While I'm not calibrated to what the units are on induced dipoles, I can at the very least say mutual polarization should not be that many orders of magnitude larger than the induced dipoles from direct polarization.

[directDipoles.txt.gz](https://github.com/pandegroup/openmm/files/1540855/directDipoles.txt.gz)
[iDipoles.txt.gz](https://github.com/pandegroup/openmm/files/1540856/iDipoles.txt.gz)

Thank you,
Jacob Litman
