### ISSUE TITLE
Tools for verifying if pressure coupling is working correctly?

### ISSUE THREAD

**Issue by bmanubay** [openmm/openmm#1947]
Hey folks,

Question: are there any tests built into `openmm` to test whether pressure coupling (say using the `MonteCarloBarostat`) is working correctly? I've been running some NPT simulations in order to compare results to estimates from `pymbar` reweighting. After doing some ensemble checks using software being developed in my lab, I'm finding that the temperature coupling seems to be working fine, but the pressure coupling seems to be not so good. Here's a snippet from my simulation code on how I'm initializing the system and adding pressure coupling:
```
system = forcefield.createSystem(pdb.topology,mols,nonbondedMethod=PME,nonbondedCutoff=1.2*nanometers)
integrator = LangevinIntegrator(293.15*kelvin, 1./picosecond, 0.001*picoseconds)
barostat = MonteCarloBarostat(1.01*bar, 293.15*kelvin, 25)
system.addForce(barostat)
```
As far as I can tell, this is pretty standard, so I'm at a bit of a loss as to what's going on. Note that I'm re-running some simulations with the frequency lowered to 10 to see what happens. I'm simulating 250 molecules of cyclohexane in a box which I created using `solvationtoolkit` and the system is being created using the `openforcefield` module (which uses tools from `openmm`).

**Comment by peastman** [comment]
When you say it's "not so good", what does that mean?  What exactly do you observe?

**Comment by bmanubay** [comment]
The ensemble validation software uses statistical tests to confirm whether simulations carried out at two different state points (different temperatures, pressures, etc.) give observable trajectories that have sampled distributions at analytically expected ratios (calculated using MBAR). 

For an NPT ensemble, you can check the enthalpy at different temperatures (which would give some information about the goodness of temperature coupling). For the simulations that I made, the enthalpy trajectories gave a ratio that indicated the sampling was from the correct distribution (and that the simulations were carried out ~at the true deltaT). You can also check the volumes at different pressures (which would give some information about the goodness of the pressure coupling). The two volume trajectories produced from simulation were not sampled at a ratio consistent with expectation, meaning that there is likely an issue with the pressure coupling.

**Comment by bmanubay** [comment]
But I guess, more what I'm getting down to, is that: "is there a check that you might use to assure yourself that the barostat is working as it should and is it something built into `openmm` or `openmmtools` @jchodera?"

**Comment by peastman** [comment]
There are various test cases to make sure the code is working correctly.  See, for example, https://github.com/pandegroup/openmm/blob/master/tests/TestMonteCarloBarostat.h.

**Comment by jchodera** [comment]
A few things here:
* Can you present some data on how long your simulation was and what the trace of volume vs time looks like?
* Note that the barostat initially adjusts the proposal size using the current windowed acceptance rates, so during the initial burn-in period, detailed balance will be violated; the initial part of the simulation must be discarded.
* The C++ unit tests use an [ideal atomic gas](https://github.com/pandegroup/openmm/blob/master/tests/TestMonteCarloBarostat.h) to ensure that the correct analytical statistics are reproduced. 
* A long time ago, I ran a series of more extensive ideal molecular gas tests in [this repository](https://github.com/choderalab/openmm-validation/blob/master/tests/test_ideal_gas.py), but I haven't run them recently.

**Comment by bmanubay** [comment]
![image](https://user-images.githubusercontent.com/7988989/33467130-8164daca-d60f-11e7-9917-17cdff1f6648.png)

Here's a trace of the volumes vs. time. Seems pretty normal to me. Simulation definitely converged. I'll take a look at some of the repos you linked (and continue to scrutinize my analysis script haha). Thanks @jchodera!

**Comment by jchodera** [comment]
@bmanubay : Those traces look reasonable to me. Presumably you discarded the initial transients in your analysis?

Did you manage to discover anything further here? We can re-run our ideal molecular gas tests, but I imagine reweighting from one pressure to another is probably a good indicator of what is going on---which is I think what your tests assess.

**Comment by bmanubay** [comment]
I'm working on figuring out the issue still. The ideal gas test gave a result that indicated that the barostat is working, yet the tests from our postdoc's `physical-validation` package still fail with my bulk simulations. I'm trying to reproduce the simulations in GROMACS to confirm that it is indeed something wrong with something in the OpenMM implementation.

**Comment by jchodera** [comment]
Can you provide us with input files to reproduce these simulations?

We'd found issues with other codes, for example, when either constraints were not converged to sufficient tolerance or the PME tolerance was too low. OpenMM in particular uses a potentially too-lax default PME tolerance of 5e-4; I've found that 1e-4 at the very maximum is needed for high-quality simulations.

Also, note that PME with CUDA does not yield reproducible energies by default. If you are reweighting, you will want to either use OpenCL (which produced reproducible energies) or set the [`DeterministicForces`](https://github.com/pandegroup/openmm/blob/master/platforms/cuda/include/CudaPlatform.h#L122-L126) platform property.

**Comment by bmanubay** [comment]
Sure! Here's the python script (`run_molecule.py`):
```
import time
from simtk.unit import *
import numpy as np
from mdtraj.reporters import NetCDFReporter
import sys
import numpy as np
from simtk.openmm.app import *
from simtk.openmm import *
from simtk.unit import *
from openforcefield.typing.engines.smirnoff import *
from openforcefield.utils import get_data_filename, generateTopologyFromOEMol, read_molecules
from sys import stdout
from solvationtoolkit.solvated_mixtures import *
import os

cwd = os.getcwd()

# Set up box of cyclohexane
# using specified numbers of each component
mixture = MixtureSystem(cwd)
mixture.addComponent(label=sys.argv[1], smiles=sys.argv[2], number=int(sys.argv[3]))

#Generate output files for AMBER
mixture.build()

num_steps = 5000000
traj_freq = 1000
data_freq = 1000
mol2files = ['monomers/'+sys.argv[1]+'.mol2']

flavor = oechem.OEIFlavor_Generic_Default | oechem.OEIFlavor_MOL2_Default | oechem.OEIFlavor_MOL2_Forcefield
mols = []
mol = oechem.OEMol()
for mol2file in mol2files:
    ifs = oechem.oemolistream(mol2file)
    ifs.SetFlavor( oechem.OEFormat_MOL2, flavor)
    mol = oechem.OEGraphMol()
    while oechem.OEReadMolecule(ifs, mol):
        oechem.OETriposAtomNames(mol)
        mols.append(oechem.OEGraphMol(mol))

name = sys.argv[1]+'_'+sys.argv[3]
filename = 'packmol_boxes/'+name+'.pdb'
pdb = PDBFile(filename)
FF_filename = get_data_filename('forcefield/smirnoff99Frosst.ffxml')
forcefield = ForceField(FF_filename)

params = forcefield.getParameter(smirks='[#1:1]-[#8]')
params['rmin_half']='0.01'
params['epsilon']='0.01'
forcefield.setParameter(params, smirks='[#1:1]-[#8]')

smirkseries = sys.argv[4]
eps = sys.argv[5]
rmin = sys.argv[6]
epsval = sys.argv[7]
rminval = sys.argv[8]

param = forcefield.getParameter(smirks=smirkseries)
param[eps] = epsval
param[rmin] = rminval
forcefield.setParameter(param, smirks=smirkseries)

#############################################################
# Simulation Parameters
#############################################################
kinetic_temperature = 293.15*kelvin
collision_frequency = 1./picosecond
step_size = 0.001*picoseconds

pressure = np.float(sys.argv[9])*bar
barostat_frequency = 1
#############################################################
#############################################################

system = forcefield.createSystem(pdb.topology,mols,nonbondedMethod=PME,nonbondedCutoff=1.2*nanometers)

integrator = LangevinIntegrator(kinetic_temperature, collision_frequency, step_size)
barostat = MonteCarloBarostat(pressure, kinetic_temperature, barostat_frequency)
system.addForce(barostat)

#platform = mm.Platform.getPlatformByName('Reference')
#properties = {'None'}
platform = Platform.getPlatformByName('CUDA')
properties = {'CudaPrecision': 'mixed','DeterministicForces': 'true'}

simulation = Simulation(pdb.topology, system, integrator, platform, properties)
simulation.context.setPositions(pdb.positions)
simulation.context.setVelocitiesToTemperature(kinetic_temperature)
simulation.minimizeEnergy()

netcdf_reporter = NetCDFReporter('traj_cychex_neat/NPT_val_stuff/'+name+'_'+smirkseries+'_'+eps+epsval+'_'+rmin+rminval+'_'+sys.argv[9]+'bar_1fs.nc', traj_freq)
simulation.reporters.append(netcdf_reporter)
simulation.reporters.append(StateDataReporter(stdout, data_freq, step=True, potentialEnergy=True, temperature=True, density=True))
simulation.reporters.append(StateDataReporter('StateData_cychex_neat/NPT_val_stuff/'+name+'_'+smirkseries+'_'+eps+epsval+'_'+rmin+rminval+'_'+sys.argv[9]+'bar_1fs.csv', data_freq, step=True, potentialEnergy=True, temperature=True, density=True))

print("Starting simulation")
start = time.clock()
simulation.step(num_steps)
end = time.clock()

print("Elapsed time %.2f seconds" % (end-start))
netcdf_reporter.close()
print("Done!")
```
and here's the `cyclohexane.mol2` file I use to generate the packmol box:
```
@<TRIPOS>MOLECULE
ZGI
18 18 1 0 1
SMALL
USER_CHARGES
@<TRIPOS>ATOM
       1 C1          -0.8670     0.5780    -1.0450 c3            1 ZGI       -0.076100
       2 C2          -1.3840     0.3490     0.3730 c3            1 ZGI       -0.075500
       3 C3          -0.2550     0.3960     1.3980 c3            1 ZGI       -0.075500
       4 C4           0.8670    -0.5780     1.0450 c3            1 ZGI       -0.075500
       5 C5           1.3840    -0.3490    -0.3730 c3            1 ZGI       -0.075500
       6 C6           0.2550    -0.3960    -1.3980 c3            1 ZGI       -0.075500
       7 H1          -0.4980     1.6070    -1.1370 hc            1 ZGI        0.037800
       8 H2          -1.6900     0.4670    -1.7600 hc            1 ZGI        0.037800
       9 H3          -2.1360     1.1080     0.6190 hc            1 ZGI        0.037800
      10 H4          -1.8840    -0.6260     0.4260 hc            1 ZGI        0.037800
      11 H5           0.1500     1.4140     1.4490 hc            1 ZGI        0.037800
      12 H6          -0.6490     0.1580     2.3930 hc            1 ZGI        0.037800
      13 H7           1.6900    -0.4680     1.7600 hc            1 ZGI        0.037800
      14 H8           0.4980    -1.6070     1.1360 hc            1 ZGI        0.037800
      15 H9           1.8840     0.6260    -0.4250 hc            1 ZGI        0.037800
      16 H10          2.1360    -1.1070    -0.6170 hc            1 ZGI        0.037800
      17 H11          0.6490    -0.1580    -2.3930 hc            1 ZGI        0.037800
      18 H12         -0.1500    -1.4140    -1.4490 hc            1 ZGI        0.037800
@<TRIPOS>BOND
       1        1        6 1
       2        1        2 1
       3        2        3 1
       4        3        4 1
       5        4        5 1
       6        5        6 1
       7        1        7 1
       8        1        8 1
       9        2        9 1
      10        2       10 1
      11        3       11 1
      12        3       12 1
      13        4       13 1
      14        4       14 1
      15        5       15 1
      16        5       16 1
      17        6       17 1
      18        6       18 1
@<TRIPOS>SUBSTRUCTURE
       1 ZGI             1 RESIDUE    0 **** ROOT      0
```

**Comment by jchodera** [comment]
* I feel silly asking this since I wrote the code, but do you know if this uses constraints to hydrogens?
* I really really wouldn't use `simtk.openmm.LangevinIntegrator` if you can avoid it. It uses a variant of OVRVO (VVVR) where the velocities are lagged by half a timestep. If you're interested in configurational properties, you should try `openmmtools.integrators.LangevinIntegrator` which defaults to VRORV (BAOAB).
* While the default PME tolerance is 5e-4 and you probably want 1e-4 or smaller, I don't think it should be hugely problematic for this system since it's just cyclohexane.

**Comment by bmanubay** [comment]
Thanks for the info John! I'll try those changes! Also, no, H-bonds aren't constrained. I thought to add them, but that isn't implemented in `smirnoff` yet, unfortunately :/

**Comment by jchodera** [comment]
Constraints are implemented, but you can't just add `constraints=app.HBonds` to the `createSystem()` call like `simtk.openmm.app.ForceField`. You have to use the SMIRNOFF XML spec for doing this:
https://github.com/openforcefield/openforcefield/blob/master/The-SMIRNOFF-force-field-format.md#constraints

That means adding the following to the XML file:
```XML
<Constraints>
  <!-- constrain all bonds to hydrogen to their equilibrium bond length -->
  <Constraint smirks="[#1:1]-[*:2]" />
</Constraints>
```
You can also add that to its own XML file and include it in the list of files you pass to `ForceField` or call `forcefield.loadFile(ffxml)` afterwards:
```
<SMIRNOFF version="0.1">
<Constraints>
  <!-- constrain all bonds to hydrogen to their equilibrium bond length -->
  <Constraint smirks="[#1:1]-[*:2]" />
</Constraints>
</SMIRNOFF>
```

**Comment by bmanubay** [comment]
Ahh, gotcha. Thanks for the tip!

**Comment by bmanubay** [comment]
Hey @jchodera, what would be the best way to go about adding a new `ffxml` file to the `openforcefield/data/forcefield/` directory in my conda distro? If I just add a new `ffxml`, it says I need to reinstall the package. I tried to uninstall the conda package, fork the main git repo, clone it, add the new `ffxml` and then do a `python3 setup.py install` from the git repo, but it still doesn't install correctly. Any ideas?

**Comment by jchodera** [comment]
What's the goal for this file? Is it
* another `ffxml` file to use in the nosetests
* a forcefield we want to distribute
* something you need to run locally for a project

`ForceField` should also search local paths if you just want to specify one or more `ffxml` files locally.

**Comment by bmanubay** [comment]
I just wanted to add HBond constraints to ‘smirnoff99frosst’. Something that I just want to use locally for a project. I’ll see if I can load the forcefield from a local file path

**Comment by jchodera** [comment]
You should just be able to do
```python
forcefield = ForceField('smirnoff99Frosst.ffxml', 'localfile.ffxml')
```
where `smirnoff99Frosst.ffxml` is conda-installed and `local-file.ffxml` is a file in your local path. If that doesn't work for you, let me know and we'll fix it!

**Comment by bmanubay** [comment]
Got it to work by making a local copy of  `smirnoff99Frosst.ffxml` and tagging the following on the end:
```
  <Constraints>
  <!-- constrain all bonds to hydrogen to their equilibrium bond length -->
    <Constraint smirks="[#1:1]-[*:2]" id="c1"/>
  </Constraints>
```
It appears `forcefield.py` requires an XML attribute id to parse the forcefield, so I added a dummy one. Quick question regarding the implementation here: how does `smirnoff` know what length to constrain the bond to without specifying it in the `Constraints` section of the `ffxml`? Does it make the connection between the smirks I specify and link it back to the bond length parameters?

**Comment by jchodera** [comment]
@bmanubay : Can you clarify if you're saying that
```
forcefield = ForceField('smirnoff99Frosst.ffxml', 'localfile.ffxml')
```
doesn't work?

**Comment by bmanubay** [comment]
@jchodera: I just did

`forcefield = ForceField('smirnoff99Frosst_w_HConstraints.ffxml')`

where `'smirnoff99Frosst_w_HConstraints.ffxml'` is a local copy of `'smirnoff99Frosst.ffxml'` with the `Constraints` section appended to it.

I think, alternatively, one can call

`forcefield = ForceField(get_data_filename('smirnoff99Frosst.ffxml'), 'localfile.ffxml')`

which would load the native copy of `'smirnoff99Frosst.ffxml'` that's installed with `openforcefield` and the `'localfile.ffxml'` that is local.

**Comment by bmanubay** [comment]
Quick test confirms that the proper call for that second method is something like

`forcefield = ForceField(get_data_filename('forcefield/smirnoff99Frosst.ffxml'),'localfile.ffxml')`

**Comment by jchodera** [comment]
You shouldn't need the `get_data_filename` since `loadFile` already checks this path if it can't find the file locally:
https://github.com/openforcefield/openforcefield/blob/master/openforcefield/typing/engines/smirnoff/forcefield.py#L552-L557
