### ISSUE TITLE
Precedence of topology rules by 'class' and 'type' definitions

### ISSUE THREAD

**Issue by summeraz** [openmm/openmm#1959]
As I understand, within the `createForce` method of each force generator the rules contained within the relevant section of the force field XML file are iterated over for each topology item in attempt to find a match (e.g. [attempting to match rules for bonds within the `createForce` method of the `HarmonicBondGenerator`](https://github.com/pandegroup/openmm/blob/2eb2c4647d2ff0e7917591948c2cd62cdde24e1e/wrappers/python/simtk/openmm/app/forcefield.py#L1892)). Once a match is found, those parameters are assigned and the process is repeated for the next item (e.g. the next bond). However, because both `type` and `class` are available for specifying these rules, it is possible that multiple rules could match a given topology item. For example I could have a section in my XML file that looks something like this:
```
<HarmonicBondForce>
    <Bond class1="C" class2="H" length="0.1" k="100.0"/>
    <Bond class1="C" type2="foo_1" length="0.2" k="200.0"/>
    <Bond type1="foo_2" type2="foo_1" length="0.3" k="300.0"/>
</HarmonicBondForce>
```
Here, bond types are defined for a generic C-H bond, a more specific C-H bond where the H must be of type foo\_1, and an even more specific C-H bond where the two types involved must be foo\_2 and foo\_1. However, because all three of these rules describe C-H bonds, the first one listed (the most generic) will always be assigned. Currently, the only way to assign the more specific rules is to define those earlier in the XML file than the more generic rules.

The reason this is of interest to me is that I am involved in the development of the [Foyer package](https://github.com/mosdef-hub/foyer) (which we are using for automating the atomtyping process) where we are relying on OpenMM for much of the backend - specifically where force field parameters are actually assigned. We are interested in reducing ambiguity in the case where multiple rules match a given topology item (such as a bond), by adding precedence to these rules based on the number of `type` definitions the rule contains (where more `type` definitions would indicate a more specific rule that should be given higher precedence).

Is this a feature that you would find useful within OpenMM as well? This could easily be implemented by creating a list of matching parameters instead of breaking on the first match, as shown here (just as an example, there is likely a more elegant approach that could be taken):
```
@@ -1900,19 +1900,28 @@ class HarmonicBondGenerator(object):
         for bond in data.bonds:
             type1 = data.atomType[data.atoms[bond.atom1]]
             type2 = data.atomType[data.atoms[bond.atom2]]
+            match_ids = []
+            type_definitions = []
             for i in self.bondsForAtomType[type1]:
                 types1 = self.types1[i]
                 types2 = self.types2[i]
                 if (type1 in types1 and type2 in types2) or (type1 in types2 and type2 in types1):
-                    bond.length = self.length[i]
-                    if bond.isConstrained:
-                        data.addConstraint(sys, bond.atom1, bond.atom2, self.length[i])
-                    if self.k[i] != 0:
-                        # flexibleConstraints allows us to add parameters even if the DOF is
-                        # constrained
-                        if not bond.isConstrained or args.get('flexibleConstraints', False):
-                            force.addBond(bond.atom1, bond.atom2, self.length[i], self.k[i])
-                    break
+                    n_type = 0
+                    if isinstance(types1, (list,)):
+                        n_type += 1
+                    if isinstance(types2, (list,)):
+                        n_type += 1
+                    match_ids.append(i)
+                    type_definitions.append(n_type)
+            bond_index = match_ids[type_definitions.index(max(type_definitions))]
+            bond.length = self.length[bond_index]
+            if bond.isConstrained:
+                data.addConstraint(sys, bond.atom1, bond.atom2, self.length[i])
+            if self.k[i] != 0:
+                # flexibleConstraints allows us to add parameters even if the DOF is
+                # constrained
+                if not bond.isConstrained or args.get('flexibleConstraints', False):
+                    force.addBond(bond.atom1, bond.atom2, self.length[i], self.k[i])

 parsers["HarmonicBondForce"] = HarmonicBondGenerator.parseElement
```
If this is a feature that would be of interest to the OpenMM community I could make the relevant changes to the `createForce` methods of each of the force generators and submit a PR, as opposed to handling this problem only within Foyer.

**Comment by peastman** [comment]
That actually isn't how it works.  ForceField has no concept of overriding.  If multiple rules match the same pair of atoms, it will create multiple bonds, one for every matching rule.

The distinction between "types" and "classes" isn't fixed, and different force fields use it in very different ways.  It's only intended to be a shortcut with no semantic meaning.  That is, a single definition specified by class is supposed to produce exactly the same result as multiple definitions specified by type.  Changing that could easily lead to confusion.

As an alternative, what about allowing explicit specification of overriding behavior?  We already have something like that for residue templates, where a template can specify an override level (an integer).  We could allow bond rules to do the same thing.  If a rule with override level >0 matched, it would automatically discard any matches with lower override level.

**Comment by summeraz** [comment]
I'm still a bit confused as to the idea that for each matching rule a bond is created.

Looking through the code for `createSystem` one of the first bits of code is to [identify all of the bonds from the topology and store them in `data`](https://github.com/pandegroup/openmm/blob/2eb2c4647d2ff0e7917591948c2cd62cdde24e1e/wrappers/python/simtk/openmm/app/forcefield.py#L1069):
```
for bond in topology.bonds():
    data.bonds.append(ForceField._BondData(bond[0].index, bond[1].index))
```
Later, [`createForce` is called for each force generator](https://github.com/pandegroup/openmm/blob/2eb2c4647d2ff0e7917591948c2cd62cdde24e1e/wrappers/python/simtk/openmm/app/forcefield.py#L1274):
```
for force in self._forces:
    force.createForce(sys, data, nonbondedMethod, nonbondedCutoff, args)
```
where, in the case of `HarmonicBondGenerator` OpenMM will attempt to assign bond forces to each of the bonds in `data` based on the rules defined in the XML file. The relevant code in `createForce` is:
```
for bond in data.bonds:
    type1 = data.atomType[data.atoms[bond.atom1]]
    type2 = data.atomType[data.atoms[bond.atom2]]
    for i in self.bondsForAtomType[type1]:
        types1 = self.types1[i]
        types2 = self.types2[i]
        if (type1 in types1 and type2 in types2) or (type1 in types2 and type2 in types1):
            bond.length = self.length[i]
            if bond.isConstrained:
                data.addConstraint(sys, bond.atom1, bond.atom2, self.length[i])
            if self.k[i] != 0:
                # flexibleConstraints allows us to add parameters even if the DOF is
                # constrained
                if not bond.isConstrained or args.get('flexibleConstraints', False):
                    force.addBond(bond.atom1, bond.atom2, self.length[i], self.k[i])
            break
```
where we iterate over each un-parameterized bond in the system (`for bond in data.bonds`) and attempt to assign parameters by looping over possible bond types (`for i in self.bondsForAtomType[type1]:`). If a match is found, parameters are assigned and a `break` occurs, indicating that we no longer look for matches to that bond, and move on to the next bond in `data.bonds`. Does this not then mean that parameters for the first rule defined in the XML file that matches this bond will be assigned?

Your suggestion of adding an override level to bonded parameters in the XML file would indeed be one way to solve this (where more "specific" bonds could be provided with a higher override level). However, this does require a little more work from the user.

I understand that `type` and `class` can have different definitions for different force fields, but is `class` not always more general than `type` (as it can contain multiple `types`)? My idea was not to change the meaning of `class` and `type`, but just to alter the current functionality so that assigning forces becomes agnostic to the order of rules in the XML file. Specifically, so that rules that contain more `type` definitions (e.g. a bond rule can have either 0, 1, or 2 `type` definitions) should be considered more "specific". From the user's end, the only change should be yielding the ability to define force rules in the XML in an arbitrary order.

**Comment by peastman** [comment]
> I understand that type and class can have different definitions for different force fields, but is class not always more general than type (as it can contain multiple types)?

Yes, but not necessarily in a way that's relevant to overriding.  For example, consider how they're used in the Amber14 force field:

```xml
    <Type class="CA" element="C" mass="12.01" name="protein-CA"/>
```

The class is the standard Amber atom type.  And we would have made the type name be the same thing, except that would have led to naming conflicts due to quirks of how Amber force fields are organized.  So we had to add a different prefix for each file.  The above definition is from a file with protein parameters.  The RNA parameter file defines a type called "RNA-CA", and the DNA files define types called "DNA-CA".  All of those are really supposed to be the same type, and the distinction isn't useful for any sort of overriding behavior.

Even when classes are being used the way you describe, simply counting "type" attributes might not always be general enough.  What if you had the following definitions?

```xml
<Bond class1="C" class2="C" length="0.1" k="100.0"/>
<Bond class1="C" type2="C_1" length="0.2" k="200.0"/>
<Bond class1="C" type2="C_2" length="0.3" k="300.0"/>
```

Now suppose you had a bond between two atoms of types `C_1` and `C_2`.  It would match all three rules, and there would be no way to tell it whether you wanted the second or third rule to take precedence.

Here's another potential advantage.  Currently we only let an atom type belong to one class, but I've had it in mind for a long time that it might be useful to let a type belong to multiple classes.  In that case, you might have two classes where one was a subset of the other, and you could then have exactly the same issues.

Of course, part of this is also just my bias in favor of making things explicit, rather than relying on implicit behaviors that may not be obvious. :)

> However, this does require a little more work from the user.

True, but not a lot more.  Just set the override level for each tag to the number of type attributes it contains, and then you get exactly the behavior you described!

**Comment by summeraz** [comment]
> Just set the override level for each tag to the number of type attributes it contains, and then you get exactly the behavior you described!

This is a good point, and introducing an override attribute would help to reduce ambiguity for certain force fields that don't follow the standard "class" and "type" conventions. I can try to take a crack at a PR to implement this. Should be as simple as removing the `break` in `createForce` and instead keeping a list of the possible bond types to assign and choosing the one with the highest override level (this will also require adding an `override` attribute to each force generator).

**Comment by peastman** [comment]
Sure, go for it!
