### ISSUE TITLE
CUDA platform error: Error loading CUDA module: CUDA_ERROR_UNKNOWN (999)

### ISSUE THREAD

**Issue by duxinzheng** [openmm/openmm#1962]
When I ran test.py there come as follwing

**There are 4 Platforms available:

1 Reference - Successfully computed forces
2 CPU - Successfully computed forces
3 CUDA - Error computing forces with CUDA platform
4 OpenCL - Error computing forces with OpenCL platform

OpenCL platform error: Error initializing context: clCreateContext (999)

CUDA platform error: Error loading CUDA module: CUDA_ERROR_UNKNOWN (999)

Median difference in forces between platforms:

Reference vs. CPU: 1.9781e-05**

What happened?
Thanks alot.

**Comment by peastman** [comment]
That's hard to say.  The CUDA driver reported an error, but didn't give any information about what the error was.  My first guess is that there's some sort of incompatibility going on between two pieces of software, or perhaps software and hardware.  Could you provide all of the following information?

- The operating system you're using (exact version).
- The type of GPU you have.
- The version of the CUDA toolkit you have installed.
- The version of the NVIDIA driver you have installed (you can get this by running `nvidia-smi`).
- The version of OpenMM you're using, including whether it's a precompiled binary or whether you built it from source.

Also, are you able to run any other programs that use CUDA?  Or is OpenMM the only one you've tried?

**Comment by samfux84** [comment]
Same problem over here. A user on our cluster reports:

> The version of OpenMM (7.1) I was using required cuda8. If I use the platform testing script OpenMM provides by submitting this job: bsub -n 1 -W 4:00 -R "rusage[mem=2048, ngpus_excl_p=1]" "module load cuda/8.0.61 && python -m simtk.testInstallation" , the cuda platform can be found, but I get the error : "CUDA platform error: Error loading CUDA module: CUDA_ERROR_UNKNOWN (999)" as before (jobid 278218).
> 
> I then tried to update my OpenMM to 7.2, which required cuda9 and submitting bsub -n 1 -W 4:00 -R "rusage[mem=2048, ngpus_excl_p=1]" "module load cuda/9.0.176 && python -m simtk.testInstallation", cuda platform is again found, but I get the same error as above (jobid 278220).

* Operating system: CentOS Linux release 7.4.1708 (Core)
* Kernel: 3.10.0-693.11.6.el7.x86_64
* GPU type:  GeForce GTX 1080 Ti
* CUDA toolkit version: 8.0.61 and 9.0.176 (depending on which cuda module the user loads)
* NVIDIA driver version (from nvidia-smi): 390.30
* User installed openmm 7.1 and 7.2 through miniconda

Any idea ?

We recently upgraded the driver from  375.51 to 390.30, but according to

https://github.com/NVIDIA/nvidia-docker/wiki/CUDA#requirements

"NVIDIA drivers are backward-compatible with CUDA toolkits versions"

**Comment by peastman** [comment]
Error 999 is "unknown error".  CUDA is reporting that something went wrong, but doesn't provide any information about what.  I just did a search for other people encountering that error code.  In [this thread](https://github.com/nicehash/excavator/issues/108) it turned out to be caused by not having a big enough power supply for the GPUs.  [This one](https://github.com/nicehash/excavator/issues/190) also concluded it was caused by not enough power for the GPUs.  But in [this thread](https://github.com/JuliaGPU/CUDAdrv.jl/issues/50) they found it was caused by the computer going to sleep, and was solved by rebooting.  I don't know if any of that applies to you.

**Comment by samfux84** [comment]
@peastman Thank you for your reply. I doubt that the problem is related to power, but I can ask our system administrator to check. If insufficient power would be the cause of the error, then I would expect to see the problem also with other software using the GPU.

It seems that all other software runs fine after the upgrade of the NVIDIA driver, except openmm.

I would also exclude the possibility of  a computer going to sleep, since our GPU compute nodes are not workstations, they are racked servers that usually do not go to sleep.

Would it make sense to test the precompiled binary of openmm ?

**Comment by jchodera** [comment]
If you have CUDA 9.0 installed and would be willing to try the conda-installable version, you can easily install precompiled `openmm` that way:
```bash
# Install miniconda
wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/miniconda
export PATH=$HOME/miniconda/bin:$PATH
# Add conda-forge and omnia to your channel list
conda config --add channels omnia --add channels conda-forge
# Update to conda-forge versions of packages
conda update --yes --all
# Install the 'openmm' a package
conda install openmm
```

**Comment by samfux84** [comment]
@jchodera Thank you for your help.

The user tried the commands that you provided, and with the precompiled binary the same error occurs.

**Comment by hjuinj** [comment]
Hi Peter and John, I am the user that Sam has been quoting from. Could it be possible that OpenMM is somehow not compatible with the driver version of 390.30? I have been successfully running OpenMM jobs with CUDA on the cluster and it is only recently that it stopped working, I presume that was when the driver was upgraded from 375.51.

**Comment by peastman** [comment]
It's possible.  Where did you get that driver from?  The most recent one I've been able to find is 387.26.

**Comment by jchodera** [comment]
@peastman: The NVIDIA driver page is showing the latest driver I can download for GTX-1080Ti is 390.48 [here](http://www.nvidia.com/download/driverResults.aspx/132530/en-us):
![image](https://user-images.githubusercontent.com/3656088/38164302-24d3573a-34d0-11e8-9614-35097382d3e7.png)

**Comment by peastman** [comment]
What set of choices did you select to get that page?  If I tell it I have a Titan V and Ubuntu 16.04, it lists 387.34 as the most recent.  If I tell it I have a Titan X (Pascal), it tells me there are no drivers at all available!  But if I tell it I have a Tesla, then if finds 390.46.

I conclude that (at least) one of two things is true: their driver download page is messed up, or the latest driver isn't compatible with all GPUs.

**Comment by jchodera** [comment]
I selected the GPU in question (GTX-1080Ti) and Linux. I can grab a screenshot later.

I *was* logged into my dev account at the time. Could this make the difference?

**Comment by peastman** [comment]
No, I can get to it to.  I just have to lie about what kind of GPU I have.

**Comment by jchodera** [comment]
That's super weird.

Here's exactly what I did:
* I went to http://www.nvidia.com/Download/index.aspx
* Select these options:
![image](https://user-images.githubusercontent.com/3656088/38178639-ff0c7138-35e4-11e8-9aa8-7946a8a23c6c.png)
* Get this download page for 390.48
![image](https://user-images.githubusercontent.com/3656088/38178641-1341e2aa-35e5-11e8-896e-90cfb696079b.png)

I've confirmed I am not logged into my developer account.

**Comment by peastman** [comment]
I know, I get exactly the same thing.  But if I tell it I have a Titan X, I get a different result.  And if I tell it I have a Titan V, I get yet a different result.

**Comment by samfux84** [comment]
@jchodera @peastman : We donwgraded the driver to 384.37, but the error is still the same.
