### ISSUE TITLE
Drude: Particle coordinate is nan

### ISSUE THREAD

**Issue by chemlove** [openmm/openmm#1968]
I am new to openMM and I want to use the charmm_polar_2013.xml to perform MD on the protein-water system. The openMM version is 7.1.

When I placed just 4 (water-4.pdb) or 100 (water-100.pdb) water molecules in the box, the simulation could go on with the DrudeSCFIntegrator and print the potential energy. 
However, when I placed ~1000 water molecules in this box, or only placed my protein in this box, the simulation crashed with DrudeSCFIntegrator and the error information is:
```
In [328]: for i in range(1,10):
   .....:         simulation.step(1000)
   .....:         
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-328-14cc9c512e83> in <module>()
      1 for i in range(1,10):
----> 2         simulation.step(1000)
      3 

/opt/gpu/anaconda-2.3.0/lib/python2.7/site-packages/simtk/openmm/app/simulation.pyc in step(self, steps)
    130     def step(self, steps):
    131         """Advance the simulation by integrating a specified number of time steps."""
--> 132         self._simulate(endStep=self.currentStep+steps)
    133 
    134     def runForClockTime(self, time, checkpointFile=None, stateFile=None, checkpointInterval=None):

/opt/gpu/anaconda-2.3.0/lib/python2.7/site-packages/simtk/openmm/app/simulation.pyc in _simulate(self, endStep, endTime)
    217                 for reporter, next in zip(self.reporters, nextReport):
    218                     if next[0] == nextSteps:
--> 219                         reporter.report(self, state)
    220 
    221     def saveCheckpoint(self, file):

/opt/gpu/anaconda-2.3.0/lib/python2.7/site-packages/simtk/openmm/app/pdbreporter.pyc in report(self, simulation, state)
     90             self._topology = simulation.topology
     91             self._nextModel += 1
---> 92         PDBFile.writeModel(simulation.topology, state.getPositions(), self._out, self._nextModel)
     93         self._nextModel += 1
     94         if hasattr(self._out, 'flush') and callable(self._out.flush):

/opt/gpu/anaconda-2.3.0/lib/python2.7/site-packages/simtk/openmm/app/pdbfile.pyc in writeModel(topology, positions, file, modelIndex, keepIds, extraParticleIdentif
ier)    328             positions = positions.value_in_unit(angstroms)
    329         if any(math.isnan(norm(pos)) for pos in positions):
--> 330             raise ValueError('Particle position is NaN')
    331         if any(math.isinf(norm(pos)) for pos in positions):
    332             raise ValueError('Particle position is infinite')

ValueError: Particle position is NaN
```

Then I tried DrudeLangevinIntegrator as the integrator, all of these systems crashed. 

So, I want to know how to use drude force field for the protein-water system especially using DrudeLangevinIntegrator and what is the reason that 100 waters system can run but 1000 waters system not.

Thank you in advance for your help.

Below is my script to use drude force field:
```
from simtk.openmm.app import *
from simtk.openmm import *
from simtk.unit import *
from sys import stdout

#pdb = PDBFile('water-4.pdb')
#pdb = PDBFile('water-100.pdb')
#pdb = PDBFile('water-1000.pdb')
#pdb = PDBFile('pro_only.pdb')

modeller = Modeller(pdb.topology, pdb.positions)
forcefield = ForceField('charmm_polar_2013.xml')
modeller.addExtraParticles(forcefield)

system = forcefield.createSystem(modeller.topology, nonbondedMethod=PME, nonbondedCutoff=1*nanometer, constraints=HBonds, rigidWater=True)
#system.addForce(AndersenThermostat(300*kelvin, 10/picosecond))
#integrator = DrudeSCFIntegrator(0.001*picoseconds)
integrator = DrudeLangevinIntegrator(300*kelvin, 10/picosecond, 1*kelvin, 200/picosecond, 0.001*picoseconds)

platform = Platform.getPlatformByName('CUDA')
properties = {'DeviceIndex': '0', 'Precision': 'mixed'}
simulation = Simulation(modeller.topology, system, integrator, platform, properties)

simulation.context.setPositions(modeller.positions)
simulation.context.setVelocitiesToTemperature(300*kelvin)

position = simulation.context.getState(getPositions=True).getPositions()
PDBFile.writeFile(simulation.topology, position, open('init.pdb', 'w'))

print('Wrote initial positions')
print('Minimizing...')
simulation.minimizeEnergy(maxIterations=2000)


position = simulation.context.getState(getPositions=True).getPositions()
PDBFile.writeFile(simulation.topology, position, open('min.pdb', 'w'))

simulation.reporters.append(PDBReporter('output.pdb', 100))
simulation.reporters.append(StateDataReporter(stdout, 100, step=True, potentialEnergy=True, temperature=True, density=True,kineticEnergy=True))
print('Simulating...')
for i in range(1,10):
    simulation.step(1000)
```

And my structures: https://simtk.org/plugins/phpBB/download/file.php?id=1783&sid=34b184f1869e2b29953b3b5383166b56

**Comment by peastman** [comment]
That means your simulation is blowing up.  It can happen for lots of reasons, so let's start trying to narrow them down.

The first thing I'd look for is whether the initial conformation isn't well minimized.  We can check that by printing out the potential energy immediately before minimizing and then again immediately after:

```python
print(simulation.context.getState(getEnergy=True).getPotentialEnergy())
simulation.minimizeEnergy(maxIterations=2000)
print(simulation.context.getState(getEnergy=True).getPotentialEnergy())
```

What does that print?

**Comment by chemlove** [comment]
I have noticed that the value is positive and very big. For a water box of ~4500 waters, the output is:

```
In [475]: 

In [475]: energy = simulation.context.getState(getEnergy=True).getPotentialEnergy()

In [476]: print(energy)
2.47800057193e+14 kJ/mol

In [477]: simulation.minimizeEnergy(maxIterations=2000)

In [478]: energy = simulation.context.getState(getEnergy=True).getPotentialEnergy()

In [479]: print(energy)
2.54553764404e+14 kJ/mol
```

**Comment by peastman** [comment]
Try switching to the CPU platform.  Is that able to minimize it more successfully?  If so, you might be running into the problem described in #1857.  The workaround is just to use the CPU platform for minimizing.  Once that's done, you can still use the CUDA platform for the simulation.  I also have it on my to-do list to implement a more robust fix.  See #1961.

You also should try to figure out why the initial energy is so high.  It might indicate some other problem, not just a failure in minimization.  For example, if you set the periodic box size incorrectly, that could cause water molecules to be coming out on top of each other.

**Comment by chemlove** [comment]
The potential energy is still very high when I switched to CPU platform. 

```
In [78]: energy = simulation.context.getState(getEnergy=True).getPotentialEnergy()

In [79]: print(energy)
14004765149.6 kJ/mol

In [80]: simulation.minimizeEnergy(maxIterations=2000)

In [81]: energy = simulation.context.getState(getEnergy=True).getPotentialEnergy()

In [82]: print(energy)
14040660316.3 kJ/mol
```

However, I have another system of protein in water box. For this system, I saw the potential energy before and after minimization are both negative. Then I could use this system to run minimization and simulation with a timestep 0.2 fs, but the simulation crashed after some steps. 

So, the reason might be that the initial structure of my systems are not good enough?

**Comment by peastman** [comment]
> So, the reason might be that the initial structure of my systems are not good enough?

Well, there's clearly *something* wrong with it.  You need to figure out what.  A good place to start is by identifying which atoms are responsible for the large energy.  You can write something like this:

```python
forces = simulation.context.getState(getForces=True).getForces()
for i, f in enumerate(forces):
  if norm(f) > 1e4*kilojoules_per_mole/nanometer:
    print(i, f)
```

**Comment by chemlove** [comment]
Sorry for the late reply. I tried another system with a small protein in the water box, and I can run minimization but not NVT simulation.
When I printed the forces, I found that every force was smaller than 1e4 kj/mol/nm after I had minimized the system. Then, I could not run even only one step of NVT, and it gave me the error "position is nan". Next, I found that nearly half of all the forces were larger than 1e4 kj/mol/nm.

I got the initial structure without drude atoms after I ran the NPT simulation of amber force field in OpenMM, does it matter?

**Comment by peastman** [comment]
Can you use XmlSerializer to write out your System and initial State (with positions) to XML files and post those?  That would let me figure out what's going on.

**Comment by chemlove** [comment]
Thank you for your help.
Here is my initial structure in pdb and xml format, as well as the script I used.
 

[pdb.zip](https://github.com/pandegroup/openmm/files/1689247/pdb.zip)
[rst.zip](https://github.com/pandegroup/openmm/files/1689250/rst.zip)
[scripts.zip](https://github.com/pandegroup/openmm/files/1689251/scripts.zip)

**Comment by peastman** [comment]
Sorry for taking so long on this issue!  I got sidetracked by all the work to get 7.2 released, and just came back to it today.

If I use DrudeSCFIntegrator, it's working fine for me.  I need to energy minimize it first, but then I can run dynamics and it has no problem.  Except, of course, that DrudeSCFIntegrator is really slow.

If I use DrudeLangevinIntegrator, many of the coordinates become NaN on the first step.  That's because of issue #1766, which we never settled on a completely acceptable solution for.  The files CHARMM uses to define the polarizable force field specify that all Drude particles have a mass of 0.  The OpenMM definition was generated by converting those files, so it also specifies a mass of 0.  That's fine for SCF, but the Langevin integrator requires them to have a non-zero mass.

It's not exactly elegant, but as a workaround you can just manually set all Drude particles to have a small but non-zero mass:

```python
for i in range(system.getNumParticles()):
    if system.getParticleMass(i) == 0*amu and not system.isVirtualSite(i):
        system.setParticleMass(i, 0.4*amu)
```

But we really should provide a proper mechanism for handling this.  Possibly just adding a `drudeMass` argument to `createSystem()`.

**Comment by chemlove** [comment]
Thank you for your reply. 
I tried again with the drude particle mass 0.4*amu and the DrudeLangevinIntegrator. And the time step is 1 fs. Then I can run dynamics but the system will crash after 25 ps giving the error "ValueError: Particle position is NaN".
Will the system crash when you test it if you run the simulation a little longer?

**Comment by jchodera** [comment]
According to my calculations in #1766, you could try `10*amu` in order for the Drude particle to be critically damped.

**Comment by chemlove** [comment]
According to what @peastman has said in  calculations in #1766 

> Apparently when you actually use the force field, you're supposed to override that with a command line argument (see https://www.charmm.org/charmm/documentation/by-version/c40b1/params/doc/drude/). They recommend a value between 0.1 and 1.0.

The  recommended mass should be between 0.1 to 1.0. If I set this value to 10.0\*amu or larger, will it be overdamped? 
By the way, if I use this 10.0\*amu mass, can I try a larger time step?

**Comment by jchodera** [comment]
> The recommended mass should be between 0.1 to 1.0.

That may be recommended by the CHARMM developers, but it is physically impossible for that to be overdamped. I do not understand how this could possibly work.

**Comment by chemlove** [comment]
@jchodera I just tried again with drude particle mass 10*amu, and the simulation can run 43 ps and then crash. The error message is:
```
Traceback (most recent call last):
  File "run-test.py", line 62, in <module>
    simulation.step(1000)
  File "/opt/gpu/anaconda-2.3.0/lib/python2.7/site-packages/simtk/openmm/app/simulation.py", line 132, in step
    self._simulate(endStep=self.currentStep+steps)
  File "/opt/gpu/anaconda-2.3.0/lib/python2.7/site-packages/simtk/openmm/app/simulation.py", line 219, in _simulate
    reporter.report(self, state)
  File "/opt/gpu/anaconda-2.3.0/lib/python2.7/site-packages/simtk/openmm/app/pdbreporter.py", line 92, in report
    PDBFile.writeModel(simulation.topology, state.getPositions(), self._out, self._nextModel)
  File "/opt/gpu/anaconda-2.3.0/lib/python2.7/site-packages/simtk/openmm/app/pdbfile.py", line 330, in writeModel
    raise ValueError('Particle position is NaN')
ValueError: Particle position is NaN
```
Should I use a larger drude particle mass? Or my system is not stable enough?

**Comment by chemlove** [comment]
Can you help me to test my system on your computer? That will be much appreciated. 
Here is my pdb structure and OpenMM script:

[amd-1.zip](https://github.com/pandegroup/openmm/files/1817924/amd-1.zip)
[run-test.zip](https://github.com/pandegroup/openmm/files/1817925/run-test.zip)
