### ISSUE TITLE
writing only protein to dcd

### ISSUE THREAD

**Issue by euhruska** [openmm/openmm#1972]
I haven't found any options of the DCDReporter to write only a subsystem (just the protein). Writing the whole system with water and then removing the water later works, but seems to be inefficient. 
I saw a similar feature in mdtraj, but it was slow: http://mdtraj.org/1.8.0/api/generated/mdtraj.reporters.DCDReporter.html#mdtraj.reporters.DCDReporter

Is there a way to just write a subset of the atoms in openmm?

**Comment by peastman** [comment]
Not currently.  What exactly did you mean when you said the reporter from MDTraj was slow?  If you tell it to write only a subset of atoms, the only effect is to extract a slice from a numpy array, which should add very little overhead:

https://github.com/mdtraj/mdtraj/blob/master/mdtraj/reporters/basereporter.py#L217

**Comment by euhruska** [comment]
hmm, I did a quick comparison, but might have had a bug there
