### ISSUE TITLE
Using more than 32 collective variables for the CustomCVForce 

### ISSUE THREAD

**Issue by msultan** [openmm/openmm#1973]
I am currently trying to implement a complex linear CustomCVForce in OpenMM and was running into interesting issues. 

Basically, the CV depends on >32 distances/angles/torsions etc so its not immediately obvious to me how to implement it in OpenMM since it raises the following exception:

``` python 
Exception: CustomCVForce cannot have more than 32 collective variables
```

One option might be to divide the CV into CV/32 sub-sections and then add all of them together though I am hoping someone else might have a better suggestion.

**Comment by peastman** [comment]
Do you really need more than 32 CVs?  That is, does every distance, torsion, etc. really need to be its own CV, or could you combine some of them?

This limitation comes from the way CustomCVForce is implemented.  It creates its own internal system and context, adds all the Forces you provided to it, and puts each one into its own force group so they can be evaluated independently.  And a system can only have 32 force groups.  In principle CustomCVForce could work around this by creating multiple internal systems and contexts.  But working with such large numbers of CVs is going to get really inefficient.  If you can do everything with just a single force, or a small number of forces, that will be a lot faster.  What about using a CustomCompoundBondForce?

**Comment by msultan** [comment]
I think I might be able to combine all of them into a single ```CustomCompoundBondForce ``` expression but I am not sure about the API.  For example, if we have 2 bonds between p0,p1 and p0,p3, I am not sure what the expression should be.  The following code :

```python
expr = "distance(p0,p1) +  2 * distance(p0,p2)"
force = mm.CustomCompoundBondForce(3,expr)
ainds = [0,1,2]
force.addBond(int(ainds[0]),int(ainds[1]))
force.addBond(int(ainds[0]),int(ainds[2]))

```
gives a wrong number or type error.

```
NotImplementedError: Wrong number or type of arguments for overloaded function 'CustomCompoundBondForce_addBond'.
  Possible C/C++ prototypes are:
    OpenMM::CustomCompoundBondForce::addBond(std::vector< int,std::allocator< int > > const &,std::vector< double,std::allocator< double > > const &)
    OpenMM::CustomCompoundBondForce::addBond(std::vector< int,std::allocator< int > > const &)
```

**Comment by peastman** [comment]
That should be

```python
force.addBond(ainds)
```

As far as the CustomCompoundBondForce is concerned, this is a single bond.  The argument to `addBond()` is a list of the particles involved in the bond.

**Comment by msultan** [comment]
Interesting, that makes programmatically generating this a bit more trickier. Lemme take another stab at this, and report back.

**Comment by msultan** [comment]
Hmm, so it is possible to have the same atom involved in multiple dihedrals for the CustomCompoundBondForce. I have the following expression involving backbone dihedrals:

``` python
expr = "+3.78464062942*(sin(dihedral(p4,p6,p8,p14))--0.815241623066)+0.984827650367*(cos(dihedral(p4,p6,p8,p14))--0.131125790906)+0.239609635308*(sin(dihedral(p6,p8,p14,p16))-0.286726096227)+0.21932004493*(cos(dihedral(p6,p8,p14,p16))--0.314836222992)"
```
This involves 5 unique atoms ( 4,6,8,14,16) but I am not sure how to express it as a CustomCompoundBondForce.

**Comment by peastman** [comment]
In your expression, change `p4` to `p1`, `p6` to `p2`, etc.  The first atom is always called `p1`, the second is always called `p2`, etc.  Then add a bond as

```python
force.addBond([4, 6, 8, 14, 16])
```

**Comment by msultan** [comment]
alright, I think i got a basic version working. Thanks a bunch @peastman .

Fyi for anyone getting to here using Google, I was also curious as to if it might be possible to have a ```CustomCentroidBondForce``` that can do a combination of groups and individual atoms. So for the dihedral example above, the following code can treat an atom as a group of atoms, allowing for a combination of atoms and groups of atoms within the same CV. 

```python 
full_expr = "3.78464062942*(sin(dihedral(g1,g2,g3,g4))--0.815241623066)+0.984827650367*(cos(dihedral(g1,g2,g3,g4))--0.131125790906)+0.239609635308*(sin(dihedral(g2,g3,g4,g5))-0.286726096227)+0.21932004493*(cos(dihedral(g2,g3,g4,g5))--0.314836222992)"
    force = mm.CustomCentroidBondForce(n_atoms, full_expr)
    for i in atom_inds:
        force.addGroup([int(i)])
    force.addBond(range(n_atoms))

```
