### ISSUE TITLE
Obtaining really different potential energies to GROMACS, what am I doing wrong?

### ISSUE THREAD

**Issue by hjuinj** [openmm/openmm#1975]
Sorry for asking this very dumb question, but this has been bugging me for a while.

In short, I am trying to run simulations of SAMPL5 solvated ligands in order to examine certain energy components. I have been getting relatively small (but still significant) differences with the water-solvated systems when compared to what was calculated originally with another MD package and I have been trying to resolve this. But today when I tried to run some of the cyclohexane-solvated systems I found even the sign in the total potential energies were different...

I am illustrating this with simple code adapted from [parmed](https://github.com/ParmEd/ParmEd/blob/master/examples/amber/simulate_amber_pme.py)

```python
from __future__ import division, print_function

import sys

# OpenMM Imports
import simtk.openmm as mm
import simtk.openmm.app as app

# ParmEd Imports
from parmed import load_file, unit as u
from parmed.openmm import StateDataReporter, NetCDFReporter

# Load the Amber files
print('Loading AMBER files...')
ala2_solv = load_file(prmtop_path,inpcrd_path)


# Create the OpenMM system
print('Creating OpenMM System')
system = ala2_solv.createSystem(nonbondedMethod=app.PME,
                                nonbondedCutoff=1.5*u.nanometer,
                                constraints=app.AllBonds,
)


barostat = MonteCarloBarostat(1.013 * bar, 300 * kelvin)
system.addForce(barostat)
# Create the integrator to do Langevin dynamics
integrator = mm.LangevinIntegrator(
                        300*u.kelvin,       # Temperature of heat bath
                        1.0/u.picoseconds,  # Friction coefficient
                        2.0*u.femtoseconds, # Time step
)

# Define the platform to use; CUDA, OpenCL, CPU, or Reference. Or do not specify
# the platform to use the default (fastest) platform
platform = mm.Platform.getPlatformByName('CUDA')
prop = dict(CudaPrecision='mixed') # Use mixed single/double precision

# Create the Simulation object
sim = app.Simulation(ala2_solv.topology, system, integrator, platform, prop)

# Set the particle positions
sim.context.setPositions(ala2_solv.positions)

# Minimize the energy
print('Minimizing energy')
sim.minimizeEnergy(maxIterations=500)

# Set up the reporters to report energies and coordinates every 100 steps
sim.reporters.append(
        StateDataReporter(sys.stdout, 1000, step = False, time = False, kineticEnergy = False, potentialEnergy=True,
                           temperature=True, volume=True,
                          density=True)
)


# Run dynamics
print('Running dynamics')
sim.step(10000)

```
When I calculate the energies using these input files: [cyclohexane-SAMPL5_024.tar.gz](https://github.com/pandegroup/openmm/files/1652864/cyclohexane-SAMPL5_024.tar.gz), I get total potential energies on the order of  > +3600 kcal/mol, while according to the calculations done previously from SAMPL5 coordinators, the energies should be the following (in kcal/mol):

```
****************
cyclohexane-SAMPL5_024
****************
                      AMBER      GROMACS       LAMMPS      DESMOND
         Angle    171.8899000    171.8903767    171.8903800    171.8893030
          Bond      0.0000000      0.0000116      0.0000116      0.0000316
      Dihedral   1420.2906000   1420.2905968   1420.2906000   1420.2907300
         LJ-14   1455.8911000   1455.8854595            n/a   1455.8851900
    Coulomb-14   -456.1966000   -456.2122009            n/a   -456.2122430
 Electrostatic    232.4321000    232.4330154    232.4343000            n/a
    Dispersive  -3000.6447000  -3000.6323374  -3000.6596000            n/a
     Potential  -1176.0321000  -1176.0183369  -1176.0444000  -1176.1332500
     Potential  -1176.0321000  -1176.0183369  -1176.0444000  -1176.1332500

```

I must be misinterpreting something very obvious here...

**Comment by peastman** [comment]
What set of coordinates do those energies correspond to?  Your script doesn't print the energy of any specific conformation (such as the initial coordinates) that you could compare to them.  No energies will get printed until after it's done an energy minimization and run 1000 steps of Langevin dynamics.  At that point, who knows what conformation it's in?  Nothing you can directly compare to the other listed numbers.
