### ISSUE TITLE
OpenMM command

### ISSUE THREAD

**Issue by leeping** [openmm/openmm#198]
Hi there,

Robert and I have written an OpenMM command line executable which is planned to be in the next release.  It can be downloaded here:

https://github.com/rmcgibbo/openmm-cmd.git

I've also made a forum post announcing it here:

https://simtk.org/forums/viewtopic.php?f=161&t=4492

If you're interested in having a single command for running a MD simulation without writing a script each time, please check it out and let us know what you think.

**Comment by peastman** [comment]
Closing an old issue.  I don't think there's anything in here we're currently planning on adding.
