### ISSUE TITLE
Manually set molecule id?

### ISSUE THREAD

**Issue by ymwangg** [openmm/openmm#2007]
I'm doing simulations of topology based model using OpenMM C++ API. In this kind of model, it's more convenient to use the bonded forces like `CustomBondForce`, `CustomCentroidBondForce` etc to describe the non-bond native interactions between two proteins. 

I noticed if a bonded force is added between two molecules, then one molecule could drift away and possibly lead to NaN coordinates error. This issue could be solved by manually placing the two molecules back to the original box every time the coordinates were saved.

Is it possible to let users manually set the molecule id of each particle using APIs like this?
```
system->setParticleMoleculeId(int index, int id)
```
Or, are their any other ways to let users manually define the molecule id?

**Comment by peastman** [comment]
Do you have a test case that shows the problem?  It's not clear to me exactly what you're describing.  If there's a bonded force connecting two molecules, they shouldn't be able to drift apart.

**Comment by jchodera** [comment]
Could the issue be due to the periodic boundary conditions flag not being set correctly?

http://docs.openmm.org/latest/api-python/generated/simtk.openmm.openmm.CustomBondForce.html#simtk.openmm.openmm.CustomBondForce.setUsesPeriodicBoundaryConditions

**Comment by ymwangg** [comment]
Attached is the test case. 
[testcase.tar.gz](https://github.com/pandegroup/openmm/files/1786866/testcase.tar.gz)

1. Do the proper modifications of the `Makefile` and run `make` to get `kernel.out`. Then run `./kernel.out` to do the simulation.

2. In the example trajectory, protein B (chain=B) drifted apart from the original box in the end.  In some cases, the OpenMM could throw an error of NaN coordinates.

3. It contains the following files:

`simulate.cpp` is the code calling OpenMM, `parameters.h` is the force field parameter file, `dcdhandle.h` is the code handling dcd file IO, `binary.pdb` is the PDB file containing two protein molecules, `example.dcd` is an example trajectory.

4. The simulation is doing the following simulation:

The test case is a study of the binding mechanism between two protein molecules in a (150,150,150) (angstrom) cubic box.  Each protein residue was represented by a single particle. The default units are angstrom, kcal/mol. 


In addition to the regular bond, angle, and dihedral terms, the force field uses `CustomBondForce` to describe the native protein-protein interactions, it uses `CustomBondForce` to describe the electrostatics interactions by enumerating all possible (charged-residue)-(charged-residue) pairs, it also uses `CustomNonbondedForce` to describe the  generic non-native nonbond interactions. 

Protein A was restrained in the box center (75,75,75) (angstrom) by `CustomCentroidBondForce` while Protein B was free to move. 


Thank you so much!

**Comment by peastman** [comment]
What behavior were you expecting to see?

There's nothing about `elecBondForce` (I assume that's the one you're talking about) to prevent the molecules from drifting apart.  You call `setUsesPeriodicBoundaryConditions(true)` on it, so if they drift apart by more than half a box width, it will just switch to having a different pair of periodic copies interact.  Which is fine—that doesn't cause any harm, as long as that's really how you want it to behave.

Also note this interaction is very short ranged, due to the exp(-r) dependence.  Long before r reaches half the box width it will have become negligible.

What is the actual problem?  Is it that the molecules are drifting apart?  If so, why do you expect them not to?  Or is the actual problem something else?  (You mentioned NaNs, and didn't say why you thought it was related to particles drifting apart.)

**Comment by ymwangg** [comment]
\\1. The following is what I'm expecting to see:
\-----------------------------------------------------------------------------------------------------
The OpenMM `context->getState` API has a flag named `enforcePeriodicBox`:
`State getState(int types, bool enforcePeriodicBox = false, int groups = 0xFFFFFFFF) const`.

It has the following description:
"enforcePeriodicBox – if false, the position of each particle will be whatever position is stored in the Context, regardless of periodic boundary conditions. If true, particle positions will be translated so the center of every molecule lies in the same periodic box."

But in my case, even when I set `enforcePeriodicBox=true`, the two protein molecules did not lie in the same periodic box because they are identified to be the same molecule by OpenMM. 

I want to know if it is possible to manually differentiate the two protein molecules so that the `enforcePeriodicBox=true` flag could correctly enforce "particle positions will be translated so the center of every molecule lies in the same periodic box".
\-----------------------------------------------------------------------------------------------------


\\2. The following is what I thought why NaN coordinates exception is related to molecules drifting apart:
\-----------------------------------------------------------------------------------------------------
I have verified that OpenMM correctly calculated the energy using periodic boundary conditions. So, a particle at location `(0, 0, 0)` of Molecule A will interact the same with particles of Molecule B at locations `(1, 1, 1), (101, 101, 101), (1001, 1001, 1001) ... (n*bx + 1, n*by + 1, n*bz + 1) when bx=by=bz=100` in a cubic box.

I though if `n` is too large, rounding errors may be significant enough to cause very large angle or dihedral forces acting on particles and therefore cause the `NaN coordinate errors`. 

The evidence is that I never got any `NaN errors` when I manually enforce the center of every molecule to be in the same periodic box every time I called the `context->getState` function.
\-----------------------------------------------------------------------------------------------------

So, the simple question is how could `enforcePeriodicBox=true` work as expected for my system?

Thank you so much for your help. 
OpenMM is a great tool to do science.

**Comment by peastman** [comment]
> the two protein molecules did not lie in the same periodic box because they are identified to be the same molecule by OpenMM.

That's because of the CustomBondForce.  It doesn't know you're really using that to emulate a nonbonded force.  It considers two particles to be in the same molecule if there's any bond or constraint connecting them.  Since you've added bonds connecting them, it thinks they're all one molecule.

> I though if n is too large, rounding errors may be significant

Two questions.  1) How far apart do they get before the NaNs appear?  2) What platform are you using?

The reference and CPU platforms store particle positions in double precision, so they would have to get *very* far apart before that becomes an issue.  The CUDA and OpenCL platforms store them in single precision (unless you specify a higher precision mode).  But internally they keep bringing the molecules back to a single periodic box, keeping track of how many box widths each particle has been translated by so they can report the "true" position when you call `getState()`.  Normally that keeps this from being a problem, but in your case it might not since you effectively have a single "molecule" whose size keeps growing.

It sounds like the root of these problems may be using a bonded force to represent nonbonded interactions.  You said that was more convenient.  In what way?  What makes it difficult to use a nonbonded force for them?

**Comment by ymwangg** [comment]
> Two questions. 1) How far apart do they get before the NaNs appear? 2) What platform are you using?

1) By watching the trajectories, the two molecules seem to be separated by a few box widths. I didn't measure the exact number.
2) I'm using the single precision CUDA platform and I used a very large timestep of 22fs. This might lead to more numerical errors.

> It sounds like the root of these problems may be using a bonded force to represent nonbonded interactions. You said that was more convenient. In what way? What makes it difficult to use a nonbonded force for them?

I'm working on a topology-based coarse-grained model to simulate protein-protein interactions. There are some scenarios that I think using a bonded force to represent a non-bonded force is more convenient. 

\-----------------------------------------------------------------------------------------------------
1) Non-bonded interactions that have different functional forms and parameters per type of interacting pairs.

Topology-based models often have different types of non-bonded interactions. 

For example, If the system has two molecules PROA and PROB. Then, there are three types of non-bonded interactions. 
Type A) `Native intra-molecular interactions`: all native interactions within a molecule. 
Type B) `Native inter-molecular interactions`: all native interactions between two molecules. 
Type C) `Non-native interactions`: all other non-bonded interactions.

Native interactions are pre-defined by the user which often the atom pairs whose distance is below some cutoff.

Type A interaction have a functional form `V( r ) = k_ij * ( r - r_ij) ^ 2` where `k_ij and r_ij` are pre-defined parameters that are different for different native pairs and cannot be calculated by some combing rules. 

Type B interactions have a functional form `V( r ) = k_ij * (  13*( r_ij / r ) ^ 12 - 18*( r_ij / r ) ^ 10 + 4*( r_ij / r ) ^ 6 )` with similar definitions of `k_ij and r_ij`. 

Type C interactions have a functional form `V( r ) = epsilon*((sigma/r)^12-(sigma/r)^6); sigma=0.5*(sigma1+sigma2); epsilon=sqrt(epsilon1*epsilon2) ` which is the normal L-J potential. 

In this case, Type A and Type B interactions are all non-bonded in nature, but they have `"per-bond"` functional forms and parameters that cannot be treated using a single functional form and a simple combining rule to calculate the `"per-bond"` parameters.

Another issue I noticed is the non-bonded exclusion list. For the CUDA or OpenCL platform, all non-bonded forces need to have the same non-bonded exclusion list. 

In the above example, even If I add three types of non-bonded forces, due to the different non-bonded exclusion list, OpenMM will not work on CUDA or OpenCL platform.

Therefore, I believe for those native interactions, it's more convenient to use the `CustomBondedForce`.

\-----------------------------------------------------------------------------------------------------
2) CustomCompoundBondForce

Sometimes this is useful to do umbrella sampling to calculate the potential of mean force between two molecules. 

In this case, the interaction is non-bonded in nature but it is more convenient to use `CustomCompoundBondForce`. I'm not sure if two molecules connected by `CustomCompoundBondForce` are also treated as a single molecule.

\-----------------------------------------------------------------------------------------------------

Above are some scenarios I thought it might be useful to allow users to manually set molecule id.

**Comment by peastman** [comment]
Have you considered using a CustomNonbondedForce with interaction groups?  It sounds to me like that might do exactly what you want, while avoiding the problems of a bonded force.  You create the force in the normal way for a nonbonded force, but then call `addInteractionGroup(particles1, particles2)` to restrict it to only a subset of interactions.  See http://docs.openmm.org/latest/api-python/generated/simtk.openmm.openmm.CustomNonbondedForce.html#simtk.openmm.openmm.CustomNonbondedForce for details.

By the way, I should explain that the definition of molecules isn't arbitrary.  It's deeply tied in to how nonbonded forces get calculated.  In addition to translating molecules by multiples of the box width, it also exchanges whole molecules to produce a more efficient ordering for calculating interactions.  So the boundaries between molecules can't be arbitrarily redefined.  It needs to be able to guarantee the above operations won't affect the results.

In principle we could split those operations apart: have one definition of molecules for purposes of applying periodic boundary conditions, and another definition for purposes of reordering.  In that case, a bonded force that used periodic boundary conditions would only affect the second definition, not the first.  That would have some performance consequences, though.

**Comment by ymwangg** [comment]
I'll try Interaction Groups.
Thank you for your help!
