### ISSUE TITLE
[Discussion] PME support for alchemical free energy codes

### ISSUE THREAD

**Issue by jmichel80** [openmm/openmm#2011]
I’m opening this issue to discuss the best strategy to support PME in alchemical free energy calculations with OpenMM.

What is not straightforward for us is to handle the reciprocal space calculation correctly for particles that have lambda dependent partial charges. 

I know that @jchodera and other YANK developers have implemented a workaround. My understanding from past discussions is that this involves (loosely) setting up end-states with full PME; duplicate alchemical states with a CustomNonBondedForce that only has the lambda dependency for the direct space component for the interactions of the alchemical region; reweighing to full PME at the end states to correct the calculated free energy change.

I’m wondering how effective this scheme has proven across various systems (including charged ligands) and whether this is basically ‘good enough’ or if future developments in OpenMM could make this approach obsolete.

cc: @Steboss

**Comment by jchodera** [comment]
We have implemented a workaround in [`AbsoluteAlchemicalFactory`](http://openmmtools.readthedocs.io/en/latest/api/generated/openmmtools.alchemy.AbsoluteAlchemicalFactory.html#openmmtools.alchemy.AbsoluteAlchemicalFactory) as @jmichel80 describes, but this has proven to not be a good solution for every system, so we had to implement an exact mode too which incurs a great deal of overhead when updating all the charges in the system via `NonbondedForce.updateParametersInContext()`.

We have a PR open to discuss a proposed solution here: https://github.com/pandegroup/openmm/issues/1702
