### ISSUE TITLE
Constraints-AllBonds leads to freezing

### ISSUE THREAD

**Issue by ljmartin** [openmm/openmm#2015]
Hi,
I've used constraints=AllBonds before with no issues using the CHARMM forcefield in OpenMM, and now with the same system in AMBER I can only run with constraints=HBonds. In this case, constraints=AllBonds freezes. Top tells me that the process is still using 100% of a CPU, but the GPU never fires up and the statedatareporter never shows a step. I can only guess it occurs in this case, because I'm passing a ParmEd topology to start a Simulation object. 

I've attached the system I'm using with code to reproduce - ~150,000 atom, protein, lipid and water

Possibly relevant info: GPU is Titan XP, CUDA 9.0, OpenMM installed by conda with python 3, amber parameters were generated by ParmEd Chamber with command below
[amber_constraints.tar.gz](https://github.com/pandegroup/openmm/files/1805734/amber_constraints.tar.gz)

chamber -top top_all36_lipid.rtf -top top_all36_prot.rtf -param par_all36_prot.prm -param par_all36_lipid.prm -str toppar_water_ions.str -psf ionized.psf -crd ionized.pdb
parmout test.prmtop

Any info is appreciated. 
Cheers

**Comment by ljmartin** [comment]
Forgot to mention that it seems the freezing occurs upon invoking a Simulation object: 

`sim = Simulation(parm.topology, system, integrator, platform, prop)`

**Comment by peastman** [comment]
As far as I can tell, it isn't actually frozen but it will take a *very* long time to start up the simulation.  It's stuck in the matrix inversion code, trying to invert a 57594 x 57594 sparse matrix.  I can't detect any sign that anything has actually gone wrong, although I don't claim to understand how the sparse matrix library works.  It's just taking a long time.

OpenMM has several different algorithms for handling constraints.  Water molecules get handled with SETTLE, which is really fast.  Small clusters of a few hydrogens bonded to a single heavy atom also get handled as a special case.  But when you constrain all bonds, you end up with one giant interconnected network of constraints that all have to be handled as a unit.  The algorithm needs to build and invert a NxN matrix as part of context initialization, where N is the number of interconnected constraints.  In this case, it's 57,594.  And the cost of matrix inversion scales as O(N^3).

**Comment by ljmartin** [comment]
As always peter - thanks for your time. 
By _very_ long time to initialize, do you mean a few hours or a day, which I could do, or something like months/years?

Btw, this is only the case with Amber input by parmed. The same system runs using constraints=AllBonds via Charmm input.

**Comment by peastman** [comment]
So if you don't use the ParmEd loader it works correctly?  That indicates there must be something different in how the bonds are being defined in the two cases.  I wonder if it's somehow creating extra bonds?  If so, that could make the constraint matrix both larger and denser.

As a simple check, try creating the system both ways and then print out `system.getNumConstraints()` for each one.  If the number is different, there's something odd going on.

**Comment by ljmartin** [comment]
I haven't figured out how to convert my pdb to an amber-readable format yet. OpenMM doesn't take chamber-style converted prmtops, so I may have to build it from the beginning but then it won't be equilibrated so that complicates things. 

I just note that the OpenMM benchmarks use AMBER (without ParmEd) with a larger system and constraints=AllBonds. 
I use the same system with CHARMM and constraints=AllBonds and that also works. So I assumed the difference is ParmEd

**Comment by ljmartin** [comment]
If its still applicable:
Amber via ParmEd and the CHARMM via CharmmPsfFile systems both have the same number of constraints, whether it be HBonds or AllBonds
