### ISSUE TITLE
Does CustomIntegrator have a way to compute sums across the (x,y,z) coordinates for each particle?

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#2029]
I've been fiddling with the [FIRE minimizer](https://journals.aps.org/prl/pdf/10.1103/PhysRevLett.97.170201) ideas again, but I realize I think we need a way to compute the sum of a per-dof variable across the (x,y,z) components of individual particles, an dI don't think we have a way to do that. Is there a clever workaround that doesn't involve bringing back the per-dof vectors from the GPU?

**Comment by peastman** [comment]
Nothing I can think of.  It doesn't have any feature for combining values across the components of each particle.

**Comment by peastman** [comment]
This is possible with the vector functions added in 7.3.
