### ISSUE TITLE
Travis build failing

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#2034]
It looks like one of the [travis builds](https://travis-ci.org/pandegroup/openmm/jobs/360891353) is failing:
```
Searching for pytest
Reading https://pypi.python.org/simple/pytest/
Couldn't find index page for 'pytest' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
No local packages or download links found for pytest
error: Could not find suitable distribution for Requirement.parse('pytest')
```
Looks like [this line in `.travis.yml`](https://github.com/pandegroup/openmm/blob/master/.travis.yml#L113) is the culprit:
```bash
      sudo easy_install pytest;
```
Would it be reasonable to switch this over to use `miniconda`, or even just `pip install`?

**Comment by peastman** [comment]
Did something change to cause this to start failing?  It might just be an intermittent network problem.

**Comment by jchodera** [comment]
The last time `master` passed was 19 days ago:
![image](https://user-images.githubusercontent.com/3656088/38178120-ea6dd786-35d9-11e8-9f27-0ac60316eea0.png)

**Comment by jchodera** [comment]
Can you enable [nightly Travis builds](https://docs.travis-ci.com/user/cron-jobs/), @peastman? That would help us catch upstream problems immediately.
