### ISSUE TITLE
Building from source on windows 10 visual studio 2015

### ISSUE THREAD

**Issue by kelnv** [openmm/openmm#2056]
Hi Peter,

I'm stuck by a simple problem. I followed the installation guide trying to build from source, however, there's always an error in the cwrapper building, causing the rest of building process fail. I've tried VS2012, 2013, 2015, all same issue. Do you have any idea of this? Thanks.

1>  Generating XML output...
1>  Generating XML output for class OpenMM::AndersenThermostat
1>  Generating XML outpu
**1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code -1073741819.**
2>------ Build started: Project: OpenMM, Configuration: Release x64 ------
**2>  OpenMMCWrapper.cpp
2>c1xx : fatal error C1083: Cannot open source file: 'D:\codes\openmm-build\wrappers\OpenMMCWrapper.cpp': No such file or directory
2>  OpenMMFortranWrapper.cpp
2>c1xx : fatal error C1083: Cannot open source file: 'D:\codes\openmm-build\wrappers\OpenMMFortranWrapper.cpp': No such file or directory**
2>  Generating Code...
3>------ Build started: Project: OpenMMCPU, Configuration: Release x64 ------

**Comment by dextorious** [comment]
I had the same issue in VS2017, getting rid of the wrappers as @peastman suggested got rid of the issue. I didn't try to fix the wrappers' paths.
