### ISSUE TITLE
AllBonds causing immediate explosion

### ISSUE THREAD

**Issue by ljmartin** [openmm/openmm#2067]
Hi all, 
I've tried to figure out if this is a basic input error, but I don't think so. 

A test system I have runs fine using constraints=HBonds. As soon as it is run with AllBonds, all atoms rocket away, as evidenced by their velocity. 
Would anyone be so kind as to take a look to explain if this is my error or a bug? 

Serialized system before integration:
```
        <Energies KineticEnergy="114039.12951960799" PotentialEnergy="-241764.3296012667"/>
...
                <Position x="6.1012" y="2.1842" z="5.184000000000001"/>
                <Position x="6.074400000000001" y="2.2541" z="5.2561"/>
...
                <Velocity x=".6684451985722746" y=".34034633497583117" z="-.34146084276205946"/>
                <Velocity x=".8194847690508252" y="-.5618211624290455" z=".589320968020529"/>
...
```
after integrating one small step (dt = 0.000001*picoseconds)
```
        <Energies KineticEnergy="-NaN" PotentialEnergy="-NaN"/>
...
                <Position x="6.10041323958793" y="2.185015597363285" z="5.1807050695109265"/>
                <Position x="6.074791991924844" y="2.2530791719085412" z="5.2550482029417225"/>
...
                <Velocity x="-786.7604120708194" y="815.5973632848479" z="-3294.930489074588"/>
                <Velocity x="391.99192484318246" y="-1020.8280914589807" z="-1051.797058277515"/>
...
```

Minimal input:
[minimum-script.tar.gz](https://github.com/pandegroup/openmm/files/1994248/minimum-script.tar.gz)
It uses CHARMM parameters, triclinic cell, Reference platform, is replicated on two quite different computers, and consists of the transmembrane domain of a GABA receptor in lipid. Runs fine in NAMD or in openmm with HBonds. HAngles will not get past the `createSystem` stage

**Comment by peastman** [comment]
It looks like something is causing the constraint matrix to be singular.  I'm not sure what though.  Let me see if I can figure out.
