### ISSUE TITLE
Behavior of CustomCVForce when alchemical parameters are changed

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#2069]
We think we've figured out a better way to interpolate energies between two sets of charges where we can still use PME to treat electrostatics: By creating a `CustomCVForce` that takes two `NonbondedForce`s with only charges (but no LJ) defined, we should be able to define an energy expression
```
(1-lambda_electrostatics)*cv1 + lambda_electrostatics*cv2
```
which would linearly interpolate between PME energies.

In our current alchemical applications, we would need to evaluate this many times for the same configuration with different values of `lambda_electrostatics`. In the current implementation, if the inner context has no global context parameters that are changing and the positions do not change, will `CustomCVForce` cache the values of the CVs? If not, is there some way to easily implement this optimization within OpenMM? (We could do this outside of OpenMM, but it adds a great deal of further complexity and other applications would not benefit from this under-the-hood optimization.)

**Comment by peastman** [comment]
Currently it doesn't make any attempt to cache them.  It would be possible, though there could be a bit of a performance cost.  I don't think there's a robust way for a force to tell when positions have changed, so on every force evaluation it would have to start by scanning through all positions and checking if any had changed.

**Comment by jchodera** [comment]
The integrator uses a system like this to keep track of when positions or context parameters are changed, e.g.:
```python
void ContextImpl::setPositions(const std::vector<Vec3>& positions) {
    hasSetPositions = true;
    updateStateDataKernel.getAs<UpdateStateDataKernel>().setPositions(*this, positions);
    integrator.stateChanged(State::Positions);
}
```
I wonder if the `Context` could instead (or in addition) keep track of changes that might affect energies and forces, such as
* have the positions changed?
* have context parameters changed, and if so, which forces are affected?

That might be easier than having CV forces have to cache and compare positions, since they could just be invalidated if something has happened to invalidate them.

**Comment by peastman** [comment]
That isn't for tracking changes to positions.  That's just to make sure you call `setPositions()` before starting your simulation, so it can throw an exception if you forget.

The difficulty of a system like that is that it's very hard to do robustly, and it's really easy to make mistakes.  There are lots of places where positions and parameters can change, and most of them aren't centralized.  So for example, it would require the cooperation of every integrator to inform it when positions had been modified.  Integrators don't go through the context to change positions.  They just directly modify the memory locations that hold positions.

**Comment by jchodera** [comment]
Would it be fast to compute some sort of checksum to see if the positions have changed? If this only needs to be called when `Context.getState(getEnergy=True)` is called, it might be OK to incur a bit of overhead for the context to tell forces that the positions haven't changed if this might save a lot of recomputation for many forces.

**Comment by peastman** [comment]
Directly comparing the positions will be as fast as computing any kind of checksum.  The main challenge is that the result of that comparison needs to be communicated back the CPU, and we need to try to do that without creating stalls on the GPU.
