### ISSUE TITLE
MB-pol Electrostatics in OpenMM

### ISSUE THREAD

**Issue by chemphys** [openmm/openmm#2078]
Hello! I am Marc, a grad student at the [Paesani Lab](http://paesanigroup.ucsd.edu/). We are interested in add an efficient implementation of [MB-pol](https://aip.scitation.org/doi/full/10.1063/1.4967719)/[MB-nrg](https://pubs.acs.org/doi/abs/10.1021/acs.jctc.6b00302) in OpenMM, in Periodic Boundary Conditions(PBC). For now, we have a C++ package that is able to compute energy and gradients by itself only for gas phase systems, when PBC are not taken into account. We built an OpenMM plugin to use that energy function that seems to work. However, we are facing some issues with the PBC implementation.

We currently have a [plugin](https://github.com/paesanilab/mbpol_openmm_plugin) that allows the user to use MB-pol in PBC, but the scaling is very bad and about 10 to 100 times slower than the actual AMOEBA forcefield implementation. The main problem is in the electrostatics force. Although the AMOEBA electrostatics and MB-pol/MB-nrg electrostatics are very similar (polarizable through thole-type-model (TTM)), we had to rewrite a big part of the electrostatics routine to add the following features:
- Intramolecular polarization. MB-pol and MB-nrg have intramolecular polarization. They exclude interactions of bonded atoms with different thole dampings as a function of the bonding distance (1, 2, or 3 bonds) and the monomer type (e.g., water and CO2 have different intramolecular dampings)
- TTM4. AMOEBA uses a TTM3 scheme, while MB-pol uses a TTM4 scheme.
- The MB-pol water has site dependent positions, and as a consequence, gradients associated with them. 
- In the MB scheme, we don't use quadrupole interactions

My question is if it would be of your interest to try to work on this implementation. I definitely cannot  do this alone and keep the efficiency of AMOEBA. I went through the AmoebaElectrostaticsForce classes, and there are several things that need to be added to base classes. Do you think it would be too challenging to do? Please let me know if you want more concrete information, and I will do my best to provide it.

Thanks a lot for your time,

Marc

**Comment by chemphys** [comment]
Hey @peastman ,

Thanks for your reply. Let me expand it a little bit.

1. *MB-pol and MB-nrg have intramolecular polarization*. When the permanent electric field is computed, all the excluded pairs at different distances (from now, excluded 1-2 is a bond distances, excluded 1-3 is two bond distances, and excluded 1-4 is three bond distances) are not taken into account. Basically, all the permanent electrostatic interactions of a pair of atoms are neglected if they are excluded of any type. However, during the calculation of the induced dipoles, these atoms (or sites, from now on) induce a dipole on their excluded neighbors. As an example, in a water molecule, the O will induce a dipole in the two H sites, with a given damping that is predefined for O-H intramolecular dipole-dipole interactions (excluded 1-2 pair), and the H atoms will polarize each other with another given damping for water and 1-3 distances. This requires:
    1. Keep track of the monomer identity, since different monomer types have different dampings for the different 1-2, 1-3 or 1-4 distances. 
    2. Be able to obtain, given a monomer, the different thole dampings for the different distances.
    3. Keep track of, for a given monomer, the atoms that belong to each one of the excluded pair types. This will be an external function that we will add, but the electrostatics routine should be able to call it. Something like `get_thole(string monomer, int atom1, int atom2)` to put an example.

2. *AMOEBA uses a TTM3 scheme, while MB-pol uses a TTM4 scheme*. This is basically how the different electrostatic interactions are calculated. A very nice reference is the [paper by Masia *et. al.*](https://aip.scitation.org/doi/10.1063/1.3511713), which details all the development for TTM3. Sumarizing it, the electrostatics contribution can be decomposed as:
![image](https://user-images.githubusercontent.com/10054173/40396347-6494d670-5de1-11e8-86d8-ae2e5e8a819e.png)
Where the electrostatic tensors T are defined as:
![image](https://user-images.githubusercontent.com/10054173/40396383-a12978b6-5de1-11e8-93ef-58400eaaa36f.png)
The forces can also be obtained from the electrostatic tensors as:
![image](https://user-images.githubusercontent.com/10054173/40396470-1b68c0aa-5de2-11e8-9679-0f1cfdd12f01.png)
Each screening function s<sub>i</sub> can be obtained from s<sub>i-1</sub> by the relation:
![image](https://user-images.githubusercontent.com/10054173/40396437-ed75dc78-5de1-11e8-9b2e-7e1b00c45a14.png)
Up to here, MB-nrg and AMOEBA are the same. The difference between them is the definition of these screening functions. For AMOEBA, they are defined as:
![image](https://user-images.githubusercontent.com/10054173/40396489-2ba87dd4-5de2-11e8-99b9-34cfd5648658.png)
While for MB-nrg (and MB-pol) they are defined as:
![image](https://user-images.githubusercontent.com/10054173/40396507-3eaeab38-5de2-11e8-9fd3-73fa48434f36.png)
This step should be "simple", since only this definition needs to be modified. But again, this screening functions depend on *a*, which is this thole damping that depends on the monomer and the bond distance.

3. *The MB-pol water has site dependent positions*. Sorry for that, I meant to say site dependent charges. This means that depending on the coordinates of water, the charge on the different atoms will change. This has associated gradients that will need to be taken into account. These gradients will depend on the field, so it also needs to be stored.

4. *In the MB scheme, we don't use quadrupole interactions*. If cuda ifdefs that part, we will have no problem there.

I hope I answered all your questions and probably opens new ones. Do you think you guys can help with this? [What we did a few years ago](https://github.com/paesanilab/mbpol_openmm_plugin) is probably a bad approach, but we wanted something that was working. However, we would like something that works and is efficient and usable. And it will be even better if is a part of the core repo of OpenMM.

Thanks for reading this!

**Comment by peastman** [comment]
I'm happy to provide advice on how to implement this, but I probably can't contribute to it directly.

The first thing I'd suggest is to check out #2063.  We're having a discussion there right now which is closely related to this, about ways of generalizing the multipole interactions.  I'm not sure if the ideas being discussed would be directly useful to you, but possibly we could create a single plugin that serves the needs of both.
