### ISSUE TITLE
why does pdbstructure.py warn about non-unique HETATM name?

### ISSUE THREAD

**Issue by nitroamos** [openmm/openmm#2086]
I'm looking at some structures and I'm getting this warning: `simtk/openmm/app/internal/pdbstructure.py:536: UserWarning: WARNING: duplicate atom`
in some of my ligands (and the warning has really stacktrace-esque ugly formatting).

Based on some googling in wwpdb.org and reading where I’d expect it:
https://www.wwpdb.org/documentation/file-format-content/format33/sect9.html#HETATM
it doesn't say whether they need to be unique or not (implying they do not). I do see random comments on various websites where they claim atom names should be unique:
https://www.cgl.ucsf.edu/chimera/docs/UsersGuide/tutorials/pdbintro.html
The new PDBx format says _atom_site.label_atom_id must be unique, but _atom_site.auth_atom_id doesn’t appear to be required to be unique:
http://mmcif.wwpdb.org/docs/tutorials/content/atomic-description.html

Why do you display this warning? Does OpenMM require them to be unique? Maybe this is personal opinion, but I prefer to avoid crying wolf unless there's a problem.

**Comment by peastman** [comment]
Pretty much all programs that process PDB files expect the atom names to be unique within each residue.  I'm not sure whether they explicitly state that requirement in the spec, but any file that has nonunique names will lead to a lot of problems.  Also, if you look through the chemical components dictionary, you'll see that standard PDB atom names are always unique.  For example, in a water, the two hydrogrens have unique names H1 and H2, even though they're chemically equivalent.

**Comment by nitroamos** [comment]
I agree from a best practices point of view and I was surprised to discover this problem... but my use case involves proprietary structures that curators are reluctant to modify. Apparently tools my colleagues use don't rely on unique atom names (or maybe individuals are fixing it by hand if they need to).
