### ISSUE TITLE
middle-of-chain TER records

### ISSUE THREAD

**Issue by nitroamos** [openmm/openmm#2087]
In many structures I'm testing against, chain breaks are represented by capping ends with NME/ACE and with TER records. For example:

```
ATOM  25766  HZ  PHE K 960      37.587  17.427 -15.914  0.00200.00           H
HETATM25767  N   NME K 960A     35.674  17.332 -21.228  0.00200.00           N
HETATM25768  HN  NME K 960A     34.953  16.709 -20.888  0.00200.00           H
HETATM25769  C   NME K 960A     36.916  16.739 -21.696  0.00200.00           C
HETATM25770 1H   NME K 960A     36.803  15.657 -21.744  0.00200.00           H
HETATM25771 2H   NME K 960A     37.180  17.114 -22.685  0.00200.00           H
HETATM25772 3H   NME K 960A     37.715  16.982 -20.996  0.00200.00           H
TER
HETATM25773  CA  ACE K 966A     33.132  34.824 -26.048  0.00200.00           C
HETATM25774 1HA  ACE K 966A     32.693  34.687 -27.037  0.00200.00           H
HETATM25775 2HA  ACE K 966A     32.374  35.225 -25.377  0.00200.00           H
HETATM25776 3HA  ACE K 966A     33.961  35.529 -26.116  0.00200.00           H
HETATM25777  C   ACE K 966A     33.644  33.491 -25.518  0.00200.00           C
HETATM25778  O   ACE K 966A     33.400  33.154 -24.356  0.00200.00           O
ATOM  25779  N   ASP K 967      34.337  32.745 -26.387  1.00 30.00           N
```

As far as I can tell, this is a violation of the PDB standard:
https://www.wwpdb.org/documentation/file-format-content/format33/sect9.html#TER
however, I'm told this is a "popular" house rule useful for representing a molecule fragment. I don't quite understand the reason why, but it might be to help getting around the 1 character limit in a chain ID if you have numerous ligands or perhaps an easy way to place multiple disconnected peptides in the same chain.

The impact to me is that PDBFixer is creating a separate Chain for each TER but it is only looking at the first one when looking for missing residues. Or at least this is the first issue I'm encountering, there may be others.

I haven't decided how I want to address this and I'm looking for advice. The easiest approach is to strip the TER records out (i.e., text parsing) before reading them in OpenMM. However, I'm wondering if there's a more elegant solution. Digging in OpenMM code, what if you made this clause optional somehow (I wouldn't expect to recover the TER records when the topology is written out)? 

```
> diff -C4 pdbstructure.py pdbstructure.py.orig 
*** pdbstructure.py	2018-05-30 16:15:22.680107762 -0400
--- pdbstructure.py.orig	2018-05-30 16:15:05.370028925 -0400
***************
*** 343,351 ****
          # Create a new chain if the chain id has changed
          if self._current_chain.chain_id != atom.chain_id:
              self._add_chain(Chain(atom.chain_id))
          # Create a new chain after TER record, even if ID is the same
!         elif self._current_chain.has_ter_record and False:
              self._add_chain(Chain(atom.chain_id))
          self._current_chain._add_atom(atom)
  
      def _add_chain(self, chain):
--- 343,351 ----
          # Create a new chain if the chain id has changed
          if self._current_chain.chain_id != atom.chain_id:
              self._add_chain(Chain(atom.chain_id))
          # Create a new chain after TER record, even if ID is the same
!         elif self._current_chain.has_ter_record:
              self._add_chain(Chain(atom.chain_id))
          self._current_chain._add_atom(atom)
  
      def _add_chain(self, chain):
```

and I assume it would use the same logic for determining if the residues should be connected as if the TER wasn't there to begin with.

Making this change seemed to fix my specific test case in PDBFixer.

**Comment by peastman** [comment]
Officially every new chain is supposed to be marked in two ways: there's a TER record, and the chain ID changes.  But in practice, it's really common for people to just include the TER record without changing the chain ID.  As you say, that's to work around the limit of only one character for the ID.  That's why we start a new chain at every TER record, whether the ID changes or not.

> The impact to me is that PDBFixer is creating a separate Chain for each TER but it is only looking at the first one when looking for missing residues.

Is that the real problem you're describing?  It should be looking at all chains, not just the first one.  Can you provide an example file that shows the problem?

**Comment by nitroamos** [comment]
PDBFixer is the only actual problem I've encountered, but I haven't carefully scrutinized all my test cases yet. I don't know of a reason why I'd care whether OpenMM stores my chain ID across multiple Chains or not although I am curious about how OpenMM infers the presence of peptide bonds. It looks like I could prevent printing of TER separately by setting `c.has_ter_record = False`.

Sure, here's a test case created by replacing some residues with a TER. See attached where I deleted A34-A44 from 1pga. It creates 3 chains (2 for chain A, 1 for water). PDBFixer sees residues 34 to 56 as missing even though 45-56 are present.


[1pga_extraTER.pdb.gz](https://github.com/pandegroup/openmm/files/2058510/1pga_extraTER.pdb.gz)

**Comment by peastman** [comment]
I'm confused about what you want.  You replaced residues 34-44 by a TER recording, indicating the start of a new chain.  But according to the SEQRES records, it should all be one chain.  So your file is internally inconsistent.  Which one do you want?  Is it one chain with some missing residues, or is it two different chains?

PDBFixer identifies missing residues by matching up the sequence described in the SEQRES records to the one described in the ATOM records.  If those are inconsistent with each other, it won't be able to match them up.

**Comment by nitroamos** [comment]
It's a single chain ID but it has unresolved residues. If we don't do loop modeling, it looks like our accession workflow is to cap the ends with NME/ACE and put a TER (a feature you might consider adding to PDBFixer to offer instead of filling missing residues). In this case, I'm looking for a way to start from a structure with these TER records and fill them in with explicit residues instead based on SEQRES.

**Comment by peastman** [comment]
Take a look at the PDBFixer manual: http://htmlpreview.github.io/?https://raw.github.com/pandegroup/pdbfixer/master/Manual.html.  It gives an example of altering the residues that get added.  When you call `findMissingResidues()`, it fills in the `missingResidues` field based on the SEQRES records.  You can modify that field to have it insert different residues instead.

**Comment by nitroamos** [comment]
Ok, that looks interesting, I'll check it out, thanks! However, whether I want caps or a loop, I'd still need them to be in the same `topology.Chain`, which requires either the TER records to be removed/ignored or for `findMissingResidues` to be aware that multiple Chains may be contiguous.

**Comment by peastman** [comment]
Multiple chains are *not* contiguous.  That's the definition of a chain!  If you want a series of residues to all be bonded to each other, they need to be in one chain.  If you want a break between them, they need to be in different chains.  That's what a "chain" means.

**Comment by nitroamos** [comment]
I'm distinguishing between a PDB chain and a `topology.Chain`. I'm getting multiple `topology.Chain` objects (which I'm referring to as contiguous) from a single PDB chain because of the TER records and I'm looking for the best way to get a single `topology.Chain`.

**Comment by peastman** [comment]
They're the same thing.  If you insert a TER record, that means it's the end of the chain.  Here is how the spec (http://www.wwpdb.org/documentation/file-format-content/format33/sect9.html#TER) defines a TER record:

> The TER record indicates the end of a list of ATOM/HETATM records for a chain.

**Comment by nitroamos** [comment]
Right, I already acknowledged that this approach is a violation of the PDB standard even though I'm told it's a common thing to do. However, I can't control workflows upstream from me so this is a problem I have to solve one way or another. It sounds like you're uninterested in addressing this -- would you accept a PR?

**Comment by peastman** [comment]
> even though I'm told it's a common thing to do.

Nope, it's not a common thing to do.  It's a totally incorrect thing to do, and whoever told you it's common has no clue what they're doing.  If you want a break between chains, insert a TER record.  If you don't want a break, don't insert one.  But including a TER recording and then expecting it not to be interpreted as a chain break simply makes no sense at all.  The *entire purpose* of the TER record is to indicate breaks between chains.

**Comment by nitroamos** [comment]
I went looking for a 4th opinion in OpenEye. They store an entire PDB in a class called `OEGraphMol`, a misleading name in this context but I'm guessing preserved for backwards compatibility reasons. However, they provide a class called `OEHierView` which can be [traversed](https://docs.eyesopen.com/toolkits/python/oechemtk/biopolymers.html#a-hierarchy-view) revealing how they would have users interact with structures. They distinguish between `OEHierChain` and `OEHierFragment`, and it looks like the difference is implicitly described [here](https://docs.eyesopen.com/toolkits/python/oechemtk/OEBioClasses/OEHierFragment.html#OEBio::OEHierFragment::GetFragmentNumber) where they say:

> While reading a PDB file, fragment numbers are incremented every time a TER record is encountered or a new ChainID is encountered. 

and they explain a bit more [here](https://docs.eyesopen.com/toolkits/python/oechemtk/OEChemClasses/OEResidue.html#OEChem::OEResidue::GetFragmentNumber):

> Similarly, when writing a PDB file, a TER record is written between any consecutive pair of atoms with different fragment numbers. 


To take a step back, you said:
> But including a TER recording and then expecting it not to be interpreted as a chain break simply makes no sense at all.

What's happening here is, I think, someone resolved the structure, put a TER in each gap instead of a loop model, and then stored it in a database. My project now is to enable people to do some loop modeling on those gaps. Maybe you still don't agree and/or don't want to support this but hopefully at least I've convinced you this use case is not ridiculous! :-P

**Comment by peastman** [comment]
It sounds like the problem is in how they converted the database records into a PDB file.  PDB doesn't explicitly refer to fragments, just chains.  But implicitly they're still there: they're indicated by a jump in the residue numbers, and possibly by a SEQRES record that lists what residues were skipped.  Someone incorrectly made the converter output a TER record at the end of every fragment instead of at the end of every chain.

**Comment by peastman** [comment]
Unfortunately the REMARK sections are just free text.  They provide information to the reader but they aren't designed to be machine readable.

**Comment by nitroamos** [comment]
For what it's worth, I've found that both Gromacs and Amber support/require middle-of-chain TER records:

- [Gromacs pdb2gmx](http://manual.gromacs.org/documentation/current/onlinehelp/gmx-pdb2gmx.html#options) has it in their option `-chainsep` where TER is the only way to leave a gap in a PDB without changing the chain ID.
- The [Amber manual](http://ambermd.org/doc12/Amber18.pdf) says "Similarly, if residues are missing (e.g., not detected in x-ray, or cut by the user), the gap should also be separated by a "TER" record." in their Section 12.3.

In my case, I've written code to remove these TER records before PDBFixer reads them and I'm also working on code to edit the pdbs after PDBFixer writes them out to insert TER records.
