### ISSUE TITLE
Preserve implicit bond orders in .pdb files?

### ISSUE THREAD

**Issue by nitroamos** [openmm/openmm#2088]
My feature request is for OpenMM to write out all the same CONECT records that it reads from my pdb file (i.e., I'm not referring to pdbx files). The use case is that our structures will repeat CONECT records in order to represent different bond orders in a ligand which I'm told is a pseudo-industry-standard. I think our structures are singly-linked in order to enable this because otherwise it looks like there could be some ambiguity. Implementing this goes a little bit beyond simply preserving all CONECT records because OpenMM writes doubly-linked lists.

Doing some looking around, I see that OpenMM nominally supports Single, Double, Triple, Aromatic, Amide, and None bonds following a lengthy discussion in #1443. While that might be nice, I'm not looking to use those directly.

I've attached an example using a made up ligand "E2O" where I've intended to represent one of the bonds as a double bond:
```
HETATM  774  C1  E2O A  66      15.702   0.904  12.771  1.00 17.90           C  
HETATM  775  C2  E2O A  66      14.823  -0.159  13.271  0.70 13.49           C  
HETATM  776  O   E2O A  66      15.029   2.134  12.501  0.70  7.21           O                                                              
CONECT  774  775  776 776
CONECT  775  774                                                                
CONECT  776  774                                                                
CONECT  776  774  
```
where the list is doubly-linked, but this singly linked list is I think what our structures do:
```
CONECT  774  775  776
CONECT  774  776                                                                
```

[1cbn_bondOrder.pdb.gz](https://github.com/pandegroup/openmm/files/2058686/1cbn_bondOrder.pdb.gz)

**Comment by peastman** [comment]
> which I'm told is a pseudo-industry-standard.

Whoever told you that is making things up! :)  I've never heard of anyone doing that.  This is definitely not a supported features of the PDB format.

**Comment by nitroamos** [comment]
Not that I'm an expert, but I hadn't heard of it either! However, it looks like OEChem [supports](https://docs.eyesopen.com/toolkits/cpp/oechemtk/OEChemConstants/OEOFlavor.html#OEChem::OEOFlavor::PDB::ORDERS) this but Rosetta does not. I'm not sure how important it is for me to support this, I'll have to check in with my users. If it's important, probably what I'd need to do is save the bond orders at the beginning of my workflow somehow and then add them back in at the end. It looks like I could accomplish this with OEChem if you're not interested in supporting it although maybe you'd accept a PR?
