### ISSUE TITLE
Problem in writing velocities file

### ISSUE THREAD

**Issue by snpreddy** [openmm/openmm#2089]
Hi,
I have couple of problems

1) Velocities are not writing in the NETCDF binary file, even having ParmEd Python package. Could you please let me know whether we need to link it some where?

2) Same python code giving different results in different run:
A test job, NVT followed by NVE gave log files and PDB file. When I run the same job again, the log files and PDB files are not same as older run and varying a lot. How is it possible?

You can find the files in the below link.
https://gist.github.com/snpreddy/081f23cdefd14074e1045a28777185bd

Thanks
Naga

**Comment by peastman** [comment]
> Velocities are not writing in the NETCDF binary file, even having ParmEd Python package.

I'm not sure what you mean.  Your script doesn't write any NetCDF files.  Instead you're writing to a PDB file:

```python
simulation.reporters.append(app.PDBReporter('run2_nvt.pdb', 5))
```

> Same python code giving different results in different run:

By default, LangevinIntegrator uses a different random number seed for every run.  You can set the seed value to make it use the same value every time.

```python
integrator.setRandomNumberSeed(1)
```

If you do that there's a good chance you'll get the same results every time, at least if you run on identical hardware.  It still isn't guaranteed though.  See the documentation at http://docs.openmm.org/latest/api-python/generated/simtk.openmm.openmm.LangevinIntegrator.html#simtk.openmm.openmm.LangevinIntegrator.setRandomNumberSeed.  It states:

> The precise meaning of this parameter is undefined, and is left up to each Platform to interpret in an appropriate way. It is guaranteed that if two simulations are run with different random number seeds, the sequence of random forces will be different. On the other hand, no guarantees are made about the behavior of simulations that use the same seed. In particular, Platforms are permitted to use non-deterministic algorithms which produce different results on successive runs, even if those runs were initialized identically.

**Comment by peastman** [comment]
The easiest way of doing it is to call `simulation.saveState()` to write out the current state to disk.  Then you can use `loadState()` to load it back in whenever you want.  See http://docs.openmm.org/latest/api-python/generated/simtk.openmm.app.simulation.Simulation.html#simtk.openmm.app.simulation.Simulation.saveState.

**Comment by snpreddy** [comment]
I have tried the integrator.setRandomNumberSeed(1) option and again the data is not same and varying a lot.

Simulation.savestate(), saves only last step data, and I am not looking for this. Tried the simulation.saveCheckpoint('file') option and didn't succeed to restart from a certain point. What I am looking is, I ran a simulation up to 5ns, with NVT ensebmle, and I want to branch out NVE, from the point of 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9 and 5 ns of NVT trajectory. Could you please suggest an example related to my problem.

Thank you
Naga

**Comment by peastman** [comment]
You can call `saveState()` or `saveCheckpoint()` whenever you want, as many times as you want.  Call it once after 4.2 ns, then again after 4.3 ns, and so on.  Save each to a different file.  You can then load any one of those files to resume from any point.

**Comment by snpreddy** [comment]
I have saved the checkpoint files in NVT, when I start an NVE with the load option, the trajectory is always identical. When I want to continue the same NVT trajectory, the trajectory is not identical with the old one. Here copied the lines related to the Checkpoint load for the continuation. Could you please let me know if something is missing. 

simulation.loadCheckpoint('nvt9.chk')
final_nvt_state = simulation.context.getState(getVelocities=True, getPositions=True)
positions = final_nvt_state.getPositions()
velocities = final_nvt_state.getVelocities()
simulation.context.setPositions(positions)
simulation.context.computeVirtualSites()
simulation.context.setVelocities(velocities)

Thank you
Naga

**Comment by peastman** [comment]
Did you set the random number seed as I described above?
