### ISSUE TITLE
NaN issue for alchemical free energy calculation

### ISSUE THREAD

**Issue by kcui7** [openmm/openmm#2092]
Hello, I'm using the MBAR method to calculate the free energy change of gas dissolved in ionic liquid, on a  Tesla M2070 GPU, using openmm version 7.1.1. I got the MBAR code from [http://openmm.org/tutorials/alchemical-free-energy/](url) it works for systems using only `NonbondedForce`.
However, I used the OPLS force field for ionic liquids, because the combination rule of the LJ sites in OPLS FF is `sigma=sqrt(sigma1*sigma2)`, I have to create a `CustomNonbondedForce` to apply this combination rule. But the energy then goes to NaN if the couple parameter `lambda` is near 0.0

I've first tried the following things:
1, Set `'CudaDisablePmeStream'='true'`
2, Set `'UseCpuPme'='true'`
3, Use OpenCL platform and set `'OpenCLDisablePmeStream'='true'`
4, Disable the `MonteCarloBarostat`
5, Apply some constraints.

None of above fixed the issue. 

Here's the test code for water dissolves in water, it has the same NaN issue, but runs faster for testing.
[alchemy_water.zip](https://github.com/pandegroup/openmm/files/2069771/alchemy_water.zip)

In the code, I used energy function
`energy_function = 'solv*4*epsilon*((sigma/r)^12-(sigma/r)^6) + (1.0-solv)*lambda*4*epsilon*x*(x-1.0);
x = (sigma/reff_sterics)^6; reff_sterics = sigma*(0.5*(1.0-lambda) + (r/sigma)^6)^(1/6);
sigma = sqrt(sigma1*sigma2); epsilon = sqrt(epsilon1*epsilon2); solv = (solv1*solv2);`

the parameter `solv` was used to distinguish solute-solute and solute-solvent interaction from solvent-solvent interaction. For atoms in a solute molecule, `solv=0`, for atoms in a solvent molecule, `solv=1`. So for solvent-solvent interaction, `solv=1*1=1` and the interaction energy is normal LJ interaction `4*epsilon*((sigma/r)^12-(sigma/r)^6)`. for solute-solute and solute-solvent interaction, `solv=0*1 or 1*1 =1` and the interaction energy is the softcore potential `lambda*4*epsilon*x*(x-1.0)`

Further tests shows that the NaN issue is from the `solv*4*epsilon*((sigma/r)^12-(sigma/r)^6)`  part. If I delete this part and use normal `NonbondedForce` for solvent-solvent interation, I won't see the NaN. It also seems that the issue can be fixed on a CPU platform, but CPU is just too slow for ionic liquids in practice.

**Comment by peastman** [comment]
I've been working on this, but haven't figured out yet what's going on.  I verified that if I don't multiply the first term by `solv`, the error goes away.  So this is somehow related to disabling the interactions with the alchemical particles.  I also had it write out data at every time step, and found that the temperature jumps on the very last step before it fails:

```
85287,-20073.893080783382,3723.7961597830117,298.8783470724458,15.031327408928943,0.9950932264494949
85288,-20055.67563292857,3706.9698397639404,297.5278374046704,15.031327408928943,0.9950932264494949
85289,-20047.522427389413,10050791260882.492,806693962270.4231,15.031327408928943,0.9950932264494949
```

Anyway, I wanted you to know I'm not ignoring it.  I'll report back when I have more information.

**Comment by jchodera** [comment]
When `lambda` is close to 0.0, the solute can overlap with solvent since the interactions are alchemically eliminated. 

@peastman: When solute and solvent atoms are overlapping, the unmodified Lennard-Jones part, `4*epsilon*((sigma/r)^12-(sigma/r)^6)`, becomes large or `NaN`; is multiplying this by `solv=0` enough to prevent large or `NaN` forces/energies?

@kcui7 : I'd suggest an alternative form of this expression where you don't have both unmodified and softcore LJ computed separately and then added. Instead, maybe
```
energy_function = '((1-is_alchemical) + lambda*is_alchemical)*4*epsilon*x*(x-1.0); x = (sigma/reff_sterics)^6; reff_sterics = sigma*(0.5*(1.0-lambda)*is_alchemical + (r/sigma)^6)^(1/6); sigma = sqrt(sigma1*sigma2); epsilon = sqrt(epsilon1*epsilon2); is_alchemical = 1 - (solv1*solv2);
```
Here, if the interaction is between solute-solute or solute-solvent atoms, the softcore form is always used and the unmodified Lennard-Jones energy/forces (which can be huge) are never computed.

**Comment by kcui7** [comment]
Thank you both for the comments. I ran two other tests on CPU platform and they can finish without NaN. Also, If I save a check point on GPU and start with that file it ran into NaN immediately every time. But if I use `saveState` after loading the check point, and restart from the saved state, the simulation can continue on both CPU and GPU. 

I'm currently trying to use another `energy_function`, as @jchodera suggested.

**Comment by peastman** [comment]
As long as the LJ part is finite, multiplying by 0 will produce 0.  But if it becomes NaN or Inf, multiplying by 0 will give NaN.

**Comment by kcui7** [comment]
I used another energy function to set lambda as a `PerParticleParameter`

```
energy_function = '(lambda*4*epsilon*X*(X-1.0));'
energy_function += 'X = (sigma/reff_sterics)^6; reff_sterics = sigma*(0.5*(1.0-lambda) + (r/sigma)^6)^(1/6);'
energy_function += 'sigma = sqrt(sigma1*sigma2); epsilon = sqrt(epsilon1*epsilon2); lambda = (lambda1*lambda2);'
```

For solvent lambda = 1 and for solute lambda = the coupling parameter, and now the simulation works.

**Comment by jchodera** [comment]
Hooray!

**Comment by peastman** [comment]
Closing this since the issue was solved.
