### ISSUE TITLE
Apple deprecating OpenCL

### ISSUE THREAD

**Issue by peastman** [openmm/openmm#2093]
Apple has announced that in the next version of macOS, they're deprecating both OpenGL and OpenCL.  They'll continue to work, but they're pushing everyone to use Metal (their proprietary API) instead.

I don't know what this really means.  Given the huge number of applications that rely on OpenGL, plus the fact that it's the basis of WebGL, it's hard to imagine them dropping support for it in the foreseeable future.  OpenCL might be easier though.

There isn't much we can do about this.  I certainly don't plan to port OpenMM to Metal.  It's just something we need to be aware of and keep an eye on.

**Comment by jchodera** [comment]
Apple hasn't produced any hardware that was serious about GPU computing in years, so essentially nobody will notice.

**Comment by bb30994** [comment]
From the F@H perspective, we have two classes of work -- "serious about GPU computing" and "suitable for CPU computing."  (The latter presently works with Gromacs.) Intel & other iGPU suppliers do produce hardware with an intermediate capability that might become a useful third classification of assignments.

A small number of Apple Donors have upgraded their systems with NVidia GPUs, but I agree: Do not port to METAL.
