### ISSUE TITLE
PCI-e lane performance

### ISSUE THREAD

**Issue by jmichel80** [openmm/openmm#2095]
Hi, 

I am in the process of ordering a bunch of quad-GTX GPU workstations that will run a lot of OpenMM based code. @peastman does the number of  PCI-e lanes has a a significant effect on OpenMM benchmarks? I'm comparing a solution with a 28 PCI-e lane based processor that could give a x8, x8, x8 , x4 setup vs a 44 PCI-e lane solution (x16, x16, x8, x4).

Best wishes,

Julien

**Comment by peastman** [comment]
That depends on your simulations.  As much as possible, we try to do everything on the GPU, so the speed of communicating with the host isn't that important.  On the other hand, if you're doing something that involves frequent communication (querying forces, setting particle positions, modifying particle parameters, etc.), that makes it more important.

**Comment by informatorius** [comment]
For folding@home OpenCL app we recommend pcie 3.0 x4 as minimum speed for fast GPUs on Windows and x8 for best performance. On Linux it doesn't matter much but x1 risers still reduce speed a little.
