### ISSUE TITLE
energy from NonbondedForce gives nan for dummy atoms when they overlap

### ISSUE THREAD

**Issue by scychon** [openmm/openmm#2113]
I'm trying to simulate some system with dummy atoms, but when I generate a fictitious atom which has zero nonbonded interaction parameters (q=0, sigma=1*nm, eps=0) the system gives nan for the potential energy term.
This must be related to the fix #1511 , but I'm not using Drude particles. I think there might be another issue behind the scene, since I need to have some particles to overlap even when they have non-zero nonbonded interaction parameters. Their cross interaction would be always zero, but one particle may have only LJ interactions and the other may have only Coulomb interactions. Is there an easy fix for this problem?

**Comment by Lnaden** [comment]
Is this a system made up purely of dummy atoms, or are there dummy atoms mixed in? Do you happen to have a simple case to reproduce this error?

I can make a minimal system of 2 particles on top of each other, one with charge, one with LJ epsilon, and the context does not crash, so I would guess something else is happening. But this is a non-periodic system and 2 particles only with no other interactions.

Another couple of questions I can think of:
* Are there other non-dummy particles in the system that carry a charge only (e.g. TIP3P water hydrogens)
* What platform is this on?
* Is this during integrator propagation or energy minimization? (asked based on the issue you linked to)

**Comment by scychon** [comment]
I made a system of two particles, both of them having zero mass, one has LJ parameters but 0 charge and the other has 0 charge and epsilon and still see the system has nan potential energy. The one with LJ parameter has element carbon, the other has element None.
I've created the system with PME periodic system, CUDA platform and before any step, if I just assign their positions and get the state, it gives nan potential energy. 
Below I added the script that you can reproduce the problem.
--------
from simtk.openmm.app import *
from simtk.openmm import *
from simtk.unit import *

system = System()
system.addParticle(0*dalton)
system.addParticle(0*dalton)

nbforce = NonbondedForce()
nbforce.addParticle(0*elementary_charge,1*nanometer,1*kilojoule_per_mole)
nbforce.addParticle(0*elementary_charge,1*nanometer,0*kilojoule_per_mole)
system.addForce(nbforce)


newTopology = Topology()
newChain = newTopology.addChain()
newResidue = newTopology.addResidue('IM', newChain)
newAtom = newTopology.addAtom('IM', None, newResidue)
newResidue = newTopology.addResidue('IM', newChain)
newAtom = newTopology.addAtom('IM', None, newResidue)

positions = []*nanometer
positions.append((0,0,0)*nanometer)
positions.append((0,0,0)*nanometer)

temperature = 300*kelvin
timestep = 1.*femtosecond
freq = 1/picosecond
cutoff = 1.2*nanometer

#####################
# Integrators for non-polarizable system
#####################
integ_eq = LangevinIntegrator(temperature, freq, timestep)
platform = Platform.getPlatformByName('CUDA')
properties = {'CudaPrecision': 'mixed'}

simeq = Simulation(newTopology, system, integ_eq, platform, properties)
simeq.context.setPositions(positions)
state = simeq.context.getState(getEnergy=True,getForces=True,getPositions=True)
print(str(state.getPotentialEnergy()))

**Comment by peastman** [comment]
This happens because the two particles are at exactly the same position.  This causes their interaction to get computed as 0/0.  If they were merely overlapping (i.e. close together) that wouldn't happen.  It's only because the distance between them is exactly 0.

Since the particles don't move (their mass is 0), you know which pairs are on top of each other.  How about adding exceptions to the NonbondedForce to exclude those pairs?
