### ISSUE TITLE
Charge in CudaContext

### ISSUE THREAD

**Issue by ymwangg** [openmm/openmm#2137]
`CudaContext` has a `getPosq()` function that returns a `CudaArray` that stores xyz coordinates and charges. There are multiple non-bonded forces in OpenMM such as `NonbondedForce` and `GBSAOBCForce`  that uses `addParticle(double charge, double sigma, double epsilon)` to add particles. 
If I understand OpenMM correctly, all force objects share the same `CudaContext` on a single GPU. Then, what does the charge from `getPosq()` correspond to? Does OpenMM require the charges of particles of all force object to be the same?

**Comment by peastman** [comment]
> Does OpenMM require the charges of particles of all force object to be the same?

Until a couple of months ago that was the case.  It was fixed in #2085, so having different forces with different charges now works correctly.

**Comment by ymwangg** [comment]
I'm debugging the lambda dynamics utility in CHARMM-OpenMM interface. It seems that CHARMM built a new force object `CustomForce` that modifies `posq.w` where `CudaArray& posq = cu.getPosq()` every time of integration since modifying the charges of `NonbondedForce` is not allowed through public API.
If now OpenMM allows different forces with different charges. Does this mean changing `posq.w` in `CustomForce` no longer affect the charge in `NonbondedForce`?

**Comment by peastman** [comment]
That was never a valid thing to do.  You should only ever change the charges by using a public API.  If you change the charges directly on the GPU, that's very likely to produce subtle errors in the calculation.

There are two ways of changing charges.  One is to call setParticleParameters() on the NonbondedForce, followed by updateParametersInContext().  That's a bit expensive, so you probably don't want to call it every time step.  But it's expensive for good reasons.  The code for computing nonbonded forces makes certain assumptions about the charges, and those assumptions have to be revalidated every time a charge changes.

An alternative mechanism was just added recently (#2105) that might work better for you.  NonbondedForce now lets you define global parameters, then use those parameters to modify particles.  This is much less expensive.  See https://github.com/pandegroup/openmm/blob/master/openmmapi/include/openmm/NonbondedForce.h#L80-L105.

**Comment by ymwangg** [comment]
Thank you so much! This is very helpful, I’ll talk about this with the developer.

**Comment by ymwangg** [comment]
@peastman Could you explain a little bit why changing the charges on the GPU is likely to produce subtle errors in the calculation?

I noticed the integrator uses the following code to modify the positions.
```
real4 pos = posq[index];
#endif
mixed4 delta = posDelta[index];
pos.x += delta.x;
pos.y += delta.y;
pos.z += delta.z;
```
Why doing the same on charge by using `pox.w = newCharge` does not change the charge of `NonbondedForce` correctly?

Thank you very much!

**Comment by peastman** [comment]
The most important reason has to do with how it computes nonbonded interactions.  The computation is most efficient if atoms are ordered in a spatially coherent way, so successive atoms are close together in space.  To achieve that, it reorders the atoms internally and periodically updates the order.

So the first thing I would worry about is that you'll modify the wrong atom.  If you want to modify the charge of atom 519, you don't modify element 519 of the array.  You need to modify whatever element corresponds to that atom in the current ordering.

You said that you have multiple nonbonded forces (such as a NonbondedForce and a GBSAOBCForce).  Only one of them now uses the fourth field in the posq vector.  The other has its own array for storing changes.  So the two of them will get out of sync.

Another issue is that there are other quantities that get precalculated based on the charges, such as the Ewald self energy.  When you change a charge, that needs to be updated too.
