### ISSUE TITLE
Have Context automatically fall back from CUDA to OpenCL if driver version too old?

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#2146]
@peastman : We briefly discussed this issue at the last OpenMM call, and I wanted to describe it in more detail.

If you have OpenMM installed compiled against a CUDA toolkit version for which the libraries are available, OpenMM will think the CUDA platform is available and try to use it. However, if the NVIDIA drivers are too old to support that version of CUDA, then an exception of some kind will be thrown. To run on that GPU, you will need to manually select OpenCL.

Here's a concrete example: I have a machine with NVIDIA driver 352.93 (supports CUDA 7.5 and earlier), and have installed [`cudatoolkit==9.0`](https://anaconda.org/anaconda/cudatoolkit/files) and the OpenMM 7.3 `dev` version compiled against CUDA 9.0 with
```bash
conda config --add channels omnia --add channels conda-forge
conda install --yes cudatoolkit
conda install --yes -c omnia/label/cuda90 openmm
```
When importing OpenMM, it thinks all four platforms are available:
```
>>> import simtk.openmm
>>> print(simtk.openmm.Platform.getNumPlatforms())
4
```
However, attempting to use the CUDA platform results in an exception
```bash
choderalab@csk:~/jdc/miniconda/share/openmm/examples$ python benchmark.py --platform=CUDA --seconds=60 --test=pme
Platform: CUDA
Precision: single

Test: pme (cutoff=0.9)
Step Size: 2 fs
Traceback (most recent call last):
  File "benchmark.py", line 161, in <module>
    runOneTest(options.test, options)
  File "benchmark.py", line 111, in runOneTest
    context = mm.Context(system, integ, platform, properties)
  File "/home/choderalab/jdc/miniconda/lib/python3.6/site-packages/simtk/openmm/openmm.py", line 12231, in __init__
    this = _openmm.new_Context(*args)
Exception: Error initializing FFT: 11
```
If this situation could be detected at the C++ level and `Context` could automatically fall back to OpenCL in these cases (presuming a `Platform` was not specifically specified), then this would be more robust to these driver-toolkit mismatch scenarios. 

I'm especially thinking about the case where we would like to distribute a specific set of toolkit libraries with the OpenMM FAH core and, should we encounter old drivers, if OpenMM could gracefully fall back to OpenCL in these instances, it would greatly simplify our need to detect driver versions.

**Comment by peastman** [comment]
> Exception: Error initializing FFT: 11

That's an interesting error message for it to get.  That suggests it successfully created the CUDA context and got through much of the work of initializing it.  It got all the way to the point where it tried to use the FFT library before it failed.  Actually that makes sense, because I believe the main CUDA library is bundled with the driver.  That indicates that if your system didn't use PME, it would have worked.

Anyway, we could potentially have it try to initialize the cufft library when the platform library is first loaded.  If it failed, it wouldn't register the CUDA platform.  But that wouldn't affect F@H, because it links the platform libraries statically and registers them itself.  So I think you really want to put this logic into the core.

**Comment by jchodera** [comment]
> Anyway, we could potentially have it try to initialize the cufft library when the platform library is first loaded. If it failed, it wouldn't register the CUDA platform. But that wouldn't affect F@H, because it links the platform libraries statically and registers them itself. So I think you really want to put this logic into the core.

Hm. It's still not clear that the older drivers would actually *work* at that point, even if the library is statically linked. I can try testing a statically-compiled core compiled with CUDA 9.2 on this older driver to find out what happens.

I think the general concept here is "shouldn't OpenMM ensure that, if it decides to register a platform plugin, it can actually *run* that platform?"

**Comment by peastman** [comment]
> It's still not clear that the older drivers would actually work at that point, even if the library is statically linked.

That's not what I mean.  OpenMM could decide whether to register the platform when it loads the plugin library.  But F@H doesn't rely on OpenMM to load plugin libraries or register platforms.  It statically links the plugins and directly registers the platforms itself.  It circumvents the standard OpenMM code for doing that.  So if we want to change the logic, it will be up to the core to do it.

**Comment by jchodera** [comment]
Got it---thanks for the clarification!
