### ISSUE TITLE
OpenMM 7.3 changelog?

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#2161]
@peastman: Do you have a complete changelog or summary of new features and bugfixes between 7.2.2 and 7.3.0?

**Comment by peastman** [comment]
There's a summary of the new features in https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=161&t=9433&p=0&start=0.  I haven't put together a full change log yet.  You can check the list of pull requests merged since the last release.

**Comment by jchodera** [comment]
I'm primarily concerned about bugs we know exist in 7.2.2 but left to 7.3.0 to address. It would be great to highlight those so that a user can easily tell if they should *definitely* upgrade to 7.3.0 (because the bug would affect them) or if they can stay at 7.2.2.

**Comment by jchodera** [comment]
Did we ever put together a full changelog for the release?
