### ISSUE TITLE
Creating conda-installable tests package for 7.3.0 beta 

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#2164]
I'm working on creating a separate conda-installable package to install all the platform unit tests (and a small driver script) for OpenMM 7.3.0 beta to facilitate testing.

The conda recipe I'm building can be found [here](https://github.com/omnia-md/conda-dev-recipes/tree/master/openmmtests).

So far, I have the tests building and installing into `$MINICONDA/bin`, but the plugin libraries are not automatically located when run:
```
[chodera@lilac:chodera]$ miniconda/bin/TestCudaNonbondedForce 
miniconda/bin/TestCudaNonbondedForce: error while loading shared libraries: libOpenMMCUDA.so: cannot open shared object file: No such file or directory
```
Here are the linked libraries:
```
$ lld TestCudaNonbondedForce 
-bash: lld: command not found
[chodera@lilac:bin]$ ldd TestCudaNonbondedForce 
	linux-vdso.so.1 =>  (0x00007ffdc1fe3000)
	librt.so.1 => /lib64/librt.so.1 (0x00007fca9c6db000)
	libOpenMMCUDA.so => not found
	libOpenMM.so => /lila/home/chodera/miniconda-test/bin/./../lib/libOpenMM.so (0x00007fca9be33000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fca9bc2f000)
	libcuda.so.1 => /usr/lib64/nvidia/libcuda.so.1 (0x00007fca9acae000)
	libcufft.so.9.2 => /usr/local/cuda-9.2/lib64/libcufft.so.9.2 (0x00007fca95654000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fca95438000)
	libstdc++.so.6 => /lila/home/chodera/miniconda-test/bin/./../lib/libstdc++.so.6 (0x00007fca950fd000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fca94dfb000)
	libgcc_s.so.1 => /lila/home/chodera/miniconda-test/bin/./../lib/libgcc_s.so.1 (0x00007fca94be9000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fca94827000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fca9c8fd000)
	libnvidia-fatbinaryloader.so.396.26 => /usr/lib64/nvidia/libnvidia-fatbinaryloader.so.396.26 (0x00007fca945db000)
```
Setting `OPENMM_PLUGIN_DIR` manually to include `$MINICONDA/lib/plugins` does not work, but adding that path to `$LD_LIBRARY_PATH` allows the tests to run.

I'm not sure why `conda-build` isn't translating the dynamic library paths for the plugins like it does for other libraries. 

This may be related to the issues in #2162.

Any ideas?

**Comment by peastman** [comment]
The tests directly link against the plugin libraries instead of loading them dynamically from `lib/plugins`.  That's so you can run them before you've done `make install`.  Adding them to `LD_LIBRARY_PATH` is the correct thing to do.

**Comment by jchodera** [comment]
OK, that simplifies things, though it would be great to figure out how to make this work automatically with conda.

I've attached the output of a complete set of tests on a `GTX-1080` with `linux` and the `396.26` drivers. The only exceptions were stochastic test failures:
```
exception: Assertion failure at TestAndersenThermostat.h:136.  Expected 6.65161, found 7.58384 (This test is stochastic and may occasionally fail)
exception: Assertion failure at TestOpenCLRpmd.cpp:357.  Expected 2020.43, found 2040.87 (This test is stochastic and may occasionally fail)
```

[test-openmm.txt](https://github.com/pandegroup/openmm/files/2364795/test-openmm.txt)
