### ISSUE TITLE
Add/delete atoms from not the last residue in topology?

### ISSUE THREAD

**Issue by ivyzhang999** [openmm/openmm#2166]
My current script deletes atoms from residues (not necessarily the last residue) and then adds missing atoms to create a new residue. However, I am getting the following error when I call addAtom on my topology (after I've already deleted atoms):

<img width="411" alt="screen shot 2018-09-12 at 2 06 46 pm" src="https://user-images.githubusercontent.com/35546250/45444340-375ca180-b695-11e8-8b75-f254b11b03f1.png">

The addAtom method seems to require that atoms may only be added/deleted from the last residue in the topology. Is there a way to circumvent this error and add atoms to not the last residue (without having to copy over the whole topology)?

**Comment by peastman** [comment]
The methods of Topology are mainly for building a new topology, not for editing an existing one.  If you want to do that, you generally need to create a new Topology object, copying over elements from the existing one while making any needed changes.  Modeller provides methods to simplify this for a lot of common cases.  If you need to do something that isn't covered by the features in Modeller, you can write code to do it yourself.  For example, take a look at the code for the `delete()` function: https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/modeller.py#L137-L182.

**Comment by peastman** [comment]
Closing this since the question was answered.
