### ISSUE TITLE
Get template by residue name using public API?

### ISSUE THREAD

**Issue by zhang-ivy** [openmm/openmm#2172]
Is there a way to get a template residue given the residue name?

I would like to mimic this: 
template = self._templates[residue_name]

Without calling a private class.

**Comment by peastman** [comment]
Can you say a bit more about what you want to accomplish?  The line you showed doesn't actually look up the template by residue name.  Instead it looks it up by template name, which often is different from the residue name.  There also may be multiple templates that correspond to variants of a single residue.  For example, the Amber14 force field has a bunch of templates for different versions of a HIS residue: HID, HIE, HIP, CHID, CHIE, CHIP, NHID, NHIE, NHIP.  It does not, however, have any template called HIS.

**Comment by ivyzhang999** [comment]
I am trying to change a residue in a protein, and I want to compare the existing residue to the template of the new residue to identify differences in atoms and bonds.

Looking through the forcefield code, I found the following line of code that seems to perform the functionality I want (the only problem being it uses a private class):
template = ForceField._TemplateData(residue.name)

**Comment by peastman** [comment]
Take a look at [PDBFixer](https://github.com/pandegroup/pdbfixer).  It has an `applyMutations()` method that may do exactly what you want: https://github.com/pandegroup/pdbfixer/blob/master/pdbfixer/pdbfixer.py#L712-L744

**Comment by ivyzhang999** [comment]
So there is no way to access the template data given a residue name?
PDBFixer looks helpful but I would prefer to alter my current approach if possible

**Comment by peastman** [comment]
Correct.  Template names are arbitrary and don't always match residue names.  The actual matching of residues to templates is done topologically (based on bonds and elements).

**Comment by jchodera** [comment]
There *is* a public API call to retrieve the templates that match a specified `Topology` called [`getMatchingTemplates()`](http://docs.openmm.org/latest/api-python/generated/simtk.openmm.app.forcefield.ForceField.html#simtk.openmm.app.forcefield.ForceField.getMatchingTemplates). @ivyzhang999 : Could you use this on the `Topology` object to get the templates for each residue directly?

**Comment by jchodera** [comment]
@peastman : To give you more context here: This is for [perses](http://github.com/choderalab/perses), a tool that allows us to use NCMC to switch between different related small molecules or protein residues as part of a single simulation that is biased by free energies of binding. In this case, it is vastly preferable to make sure the residue definitions are synchronized with whatever `ForceField` has loaded since we rely upon `ForceField` to apply the parameters once we have modified the `Topology` object accordingly.

**Comment by ivyzhang999** [comment]
@jchodera : `getMatchingTemplates()` retrieves templates for the existing topology, but I want to get the template(s) for the "new" residues (aka the residues to replace with)

I've managed to get PDBFixer to work as long as we can specify the pdb file for the protein of interest...is this something I can assume we have access to?

Another implementation that I've got mostly working is creating a dictionary of residue templates read in from pdbfixer/templates (https://github.com/pandegroup/pdbfixer/tree/master/pdbfixer/templates). However, it seems like this is not an ideal solution considering different forcefields may yield different residue templates?

**Comment by peastman** [comment]
In practice, how do you want to specify residues?  For example, if you want a particular protonation state of a post-translationally modified residue, how would you specify it?  Would you hardcode the assumption that you're using a particular force field, then look through the XML file to see what name it gives to the appropriate template?  Or would you want to build a description (say, as a Residue object) of the residue you want, then ask the force field for a matching template?  (Though if you already have the description, you probably don't need the template.)

Looking up the template in `_templates` is probably ok.  I can't guarantee that will never break, but if it ever does, the fixes to your code should be simple.  But note some cases won't work with that.  For example, that leaves out patches, so it won't work with CHARMM.  It also won't work if the force field includes template generators.

**Comment by jchodera** [comment]
> In practice, how do you want to specify residues?

This is indeed a difficult question. On the one hand, we need a template in `ForceField` if we're going to be able to parameterize the new `Topology` object, so limiting ourselves to template names loaded by `ForceField` is the most straightforward approach. 

While there's no standard shorthand nomenclature for modified amino acids or their protonation state variants, there *is* an expanded somewhat standard library of residue types in the [PDB Ligand Expo](http://ligand-expo.rcsb.org/) (also known as the Chemical Component Dictionary), though I'm not even sure it has protonation state variants in it. Also, most of its contents don't have parameters in current force fields, so it wouldn't be useful to use this anyway.

If/when we later move to something like [SMIRNOFF](https://open-forcefield-toolkit.readthedocs.io/en/topology/smirnoff.html), we will probably want a different way of specifying chemical transformations based on SMIRKS, but for now, I think using `_templates` is the best compromise. 

Note that, while it won't work for generators or patches, it _will_ work for cases where the complete template is already defined as a residue template, which is the initial use case we're targeting---standard amino acids and their protonation state variants.

**Comment by peastman** [comment]
> though I'm not even sure it has protonation state variants in it

I believe it doesn't.

> Note that, while it won't work for generators or patches, it will work for cases where the complete template is already defined as a residue template

So basically it will work for Amber force fields, but not CHARMM ones.

**Comment by jchodera** [comment]
Are you specifically referring to N-terminal and C_terminal residues (which require patckes)? For other standard residues, it might be fine. Or does every residue feature a patch?

**Comment by peastman** [comment]
If you want alternate protonation states, those are done with patches.  So are disulfide bonds.  And of course any kind of post-translational modification.
