### ISSUE TITLE
GbNeck2 Protein-nucleic acid parameters

### ISSUE THREAD

**Issue by alberto99** [openmm/openmm#2173]
Hi,
I'm wondering what is the best way to incorporate parameters for GbNeck2 to handle proteins and nucleic acids in the customgbforces.py. The parameters follow Nguyen, H. et al. (2015). JCTC, 11(8), 3714–3728. 

This version maintains the original parameters for GBneck2 for protein atoms (so those simulations will remain the same. 
Additionally, we will be able to simulate some protein-DNA  complexes.

The issue is that we will have to distinguish between atom.elements belonging to protein or nucleic acid. The only way I can see to do this is checking the residue name, but this would not be sustainable when thinking about all the possible modified DNA bases.

Below is a simple thought, but it would need recompilation everytime we wanted to add a new base -- which is what I would like to avoid. Is there a way to mark residues as  nucleic or protein when reading the topology?
Thanks!

Here 
_SCREEN_PARAMETERS_DNA = { # normal, GBn, GBn2
        E.hydrogen : (0.85, 1.09085413633, 1.696538),
        E.carbon : (0.72, 0.48435382330, 1.268902),
        E.nitrogen : (0.79, 0.700147318409, 1.4259728),
        E.oxygen : (0.85, 1.06557401132, 0.1840098),
        E.fluorine : (0.88, 0.5, 0.5),
        E.phosphorus : (0.86, 0.5, 1.5450597),
        E.sulfur : (0.96, 0.602256336067, -0.703469),
        None : (0.8, 0.5, 0.5) # default
}

def _screen_parameter_DNA(atom):
    if atom.residue.name in ['DA','DT','DC','DG','DA3','DA5','DC3','DC5','DG3','DG5','DT3','DT5']:
        if atom.element in _SCREEN_PARAMETERS_DNA:
            return _SCREEN_PARAMETERS_DNA[atom.element]
    else:
        if atom.element in _SCREEN_PARAMETERS:
            return _SCREEN_PARAMETERS[atom.element]
    return _SCREEN_PARAMETERS[None]

#And for the alpha,beta,gamma parameters:

               for i, atom in enumerate(topology.atoms()):
            radii[i].append(_screen_parameter_DNA(atom)[2])
            if atom.element in (E.hydrogen, E.deuterium):
                radii[i].extend([0.788440, 0.798699, 0.437334])
            elif atom.element is E.carbon:
                radii[i].extend([0.733756, 0.506378, 0.205844])
            elif atom.element is E.nitrogen:
                radii[i].extend([0.503364, 0.316828, 0.192915])
            elif atom.element is E.oxygen:
                radii[i].extend([0.867814, 0.876635, 0.387882])
            elif atom.element is E.sulfur:
                radii[i].extend([0.867814, 0.876635, 0.387882])
            else:
                radii[i].extend([0.8, 4.85, 0.5])
            if atom.residue.name in ['DA','DT','DC','DG','DA3','DA5','DC3','DC5','DG3','DG5','DT3','DT5']:
                if atom.element in (E.hydrogen, E.deuterium):
                    radii[i].extend([0.537050, 0.362861, 0.116704])
                elif atom.element is E.carbon:
                    radii[i].extend([0.331670, 0.196842, 0.093422])
                elif atom.element is E.nitrogen:
                    radii[i].extend([0.686311, 0.463189, 0.138722])
                elif atom.element is E.oxygen: #Should be only oxygen with type OS
                    radii[i].extend([0.606344, 0.463006, 0.142262])
                elif atom.element is E.phosphorus:
                    radii[i].extend([0.418365, 0.290054, 0.1064245])

**Comment by peastman** [comment]
I think checking the residue name is the best way to identify what kind of molecule it is.  The residue names follow the PDB definitions, so you don't need to include all the variants Amber defines.  For example, you just need to check for 'DA', not 'DA3' and 'DA5'.  A residue has the same name whether it's at the end of a chain or in the middle.

**Comment by alberto99** [comment]
Thanks!
I was concerned about things like RG which would then trigger with ARG. So wanted to match the whole residue name.
Knowing that residue names are the best way forward I’ll look for an implementation.
Best,
Alberto

**Comment by peastman** [comment]
Closing this since the question was answered.

**Comment by hainm** [comment]
@alberto99  it seems like @peastman's PR help your case https://github.com/openmm/openmm/pull/2397

(I am sorry that I did not have time to work on this as promise).

**Comment by alberto99** [comment]
Fantastic! Thanks @peastman!

--------------------------------------------------
Alberto Perez 
Assistant Professor
University of Florida, Department of Chemistry
https://perez.chem.ufl.edu
