### ISSUE TITLE
openMM modeller.addHydrogens

### ISSUE THREAD

**Issue by songmenghua1994** [openmm/openmm#2183]
Hi! I have a DNA.pdb, but it doesn't have hydrogen atoms. I want to use modeller.addHydrogens() to add hydrogen atoms for DNA.pdb. However, I keep getting the same error of "No templete found for residue 1(DA5). The set of atoms is similar to DA5,but it is missing 12 hydrogen atoms."

Here are the PDB file contents:

> ATOM      1  C5' DA5 X   1       0.623  -7.000  21.055  0.00  0.00           C  
ATOM      2  O5' DA5 X   1       0.595  -8.219  20.347  0.00  0.00           O  
ATOM      3  C4' DA5 X   1       1.944  -6.275  20.815  0.00  0.00           C  
ATOM      4  O4' DA5 X   1       3.044  -7.157  20.780  0.00  0.00           O  
ATOM      5  C3' DA5 X   1       2.081  -5.356  19.605  0.00  0.00           C  
ATOM      6  O3' DA5 X   1       3.039  -4.349  19.844  0.00  0.00           O  
ATOM      7  C2' DA5 X   1       2.607  -6.382  18.605  0.00  0.00           C  
ATOM      8  C1' DA5 X   1       3.563  -7.199  19.470  0.00  0.00           C  
ATOM      9  N1  DA5 X   1       6.735 -11.197  19.825  0.00  0.00           N  
ATOM     10  C2  DA5 X   1       6.791  -9.962  20.299  0.00  0.00           C  
ATOM     11  N3  DA5 X   1       5.953  -8.953  20.113  0.00  0.00           N  
ATOM     12  C4  DA5 X   1       4.889  -9.356  19.379  0.00  0.00           C  
ATOM     13  C5  DA5 X   1       4.665 -10.576  18.799  0.00  0.00           C  
ATOM     14  C6  DA5 X   1       5.668 -11.517  19.081  0.00  0.00           C  
ATOM     15  N6  DA5 X   1       5.701 -12.736  18.525  0.00  0.00           N  
ATOM     16  N7  DA5 X   1       3.416 -10.642  18.191  0.00  0.00           N  
ATOM     17  C8  DA5 X   1       2.970  -9.425  18.338  0.00  0.00           C  
ATOM     18  N9  DA5 X   1       3.802  -8.588  19.036  0.00  0.00           N  
ATOM     19  P    DA X   2       3.443  -3.278  18.712  0.00  0.00           P  
ATOM     20  O1P  DA X   2       2.245  -3.058  17.870  0.00  0.00           O  
ATOM     21  O2P  DA X   2       3.946  -2.088  19.433  0.00  0.00           O1-
ATOM     22  C5'  DA X   2       5.905  -3.995  18.361  0.00  0.00           C  
ATOM     23  O5'  DA X   2       4.622  -3.870  17.789  0.00  0.00           O  
ATOM     24  C4'  DA X   2       6.831  -4.856  17.508  0.00  0.00           C  
ATOM     25  O4'  DA X   2       6.306  -6.161  17.416  0.00  0.00           O  

This is the error i get：

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/data/Miniconda2/lib/python2.7/site-packages/simtk/openmm/app/modeller.py", line 842, in addHydrogens
    system = forcefield.createSystem(newTopology, rigidWater=False, nonbondedMethod=CutoffNonPeriodic)
  File "/home/data/Miniconda2/lib/python2.7/site-packages/simtk/openmm/app/forcefield.py", line 1128, in createSystem
    raise ValueError('No template found for residue %d (%s).  %s' % (res.index+1, res.name, _findMatchErrors(self, res)))
ValueError: No template found for residue 1 (DA5).  The set of atoms is similar to DA5, but it is missing 12 hydrogen atoms.

This is my code, almost exactly the same as the sample code:

> from simtk.openmm.app import *
from simtk.openmm import *
from simtk.unit import *
from sys import stdout
pdb = PDBFile('DNA.pdb')
forcedield=ForceField('DNA.bsc1.xml, tip3p.xml')
modeller = Modeller (pdb.topology, pdb.positions)
modeller.addHydrogens (forcefield)

**Comment by dprada** [comment]
Do the changes in https://github.com/pandegroup/openmm/pull/2314 solve this issue?
See also https://github.com/pandegroup/openmm/issues/2313.
