### ISSUE TITLE
Updating tabulated functions in context

### ISSUE THREAD

**Issue by ljmartin** [openmm/openmm#2200]
Hello,
I am just wondering if there can be some provision for updating a tabulated function in a Custom*Force without reinitializing a context? Reinitializing the whole context takes longer than updateParametersInContext but, with the exception of CustomCVForce, updateParametersInContext does not update the energy function to reflect a change in the tabulated function values. When the tabulated function changes fairly frequently then this could be quite a time saver. 

For me, this would be used in running this implementation of metadynamics ( https://pubs.acs.org/doi/abs/10.1021/acs.jctc.8b00448 ) but I have seen at least one other use case ( https://github.com/pandegroup/openmm/issues/1980#issuecomment-370755063 ). 

While I profess to know very little about the workings behind Custom*Forces, perhaps it could be a separate argument with the default behaviour to NOT update tabulated functions. This means most of the time the speed of this operation (updateParametersInContext) is the same as it is now. 
Much appreciated,
Lewis

**Comment by peastman** [comment]
In principle it could certainly be done, though it would be a bit more complicated.  CustomCVForce has the advantage that its expression is evaluated entirely on the CPU, so updating the tabulated function just means rebuilding a host side data structure.  Other custom forces evaluate the custom expression on the GPU.  That would make the update more expensive.  But it would still be faster than reinitializing the Context, and making it dependent on a separate argument as you suggest would avoiding slowing things down when you aren't changing the function.

**Comment by jiayeguo** [comment]
Related to this issue, I am trying to run metadynamics simulations using the @peastman [openMM script](https://simtk.org/svn/pyopenmm/trunk/simtk/pyopenmm/extras/metadynamics.py) biased by a CustomCVForce.  The original code `self._force.updateParametersInContext(context)` gives `AttributeError: type object 'object' has no attribute '__getattr__'`; when I tried `context.reinitialize()`, the particle position info seems to be wiped out (`Exception: Particle positions have not been set`).  I am wondering whether there is other ways to update a tabulated function in the CustomCVForce? @jchodera

**Comment by jchodera** [comment]
Can you post your code example @jiayeguo?

**Comment by jiayeguo** [comment]
Yes here is my repo with example code: https://github.com/jiayeguo/metadynamics

**Comment by jchodera** [comment]
@jiayeguo : Is it possible you're using OpenMM 7.2.1 instead of 7.3.0? `CustomCVForce.updateParametersInContext()` was added in [this commit](https://github.com/pandegroup/openmm/commit/9e0f5f3dfa25860cff9153bf721cda97b738accf) after 7.2.1 was released but prior to the release of 7.3.0.

**Comment by jiayeguo** [comment]
I am using openmm-7.2.2-py36_1.

**Comment by jchodera** [comment]
@jiayeguo : You will need to update to 7.3.0 to use that metadynamics code. That requirement is unfortunately not currently documented anywhere in the [`metadynamics.py`](https://simtk.org/svn/pyopenmm/trunk/simtk/pyopenmm/extras/metadynamics.py) code example.

**Comment by jiayeguo** [comment]
@jchodera Thanks I will definitely try it out and it would be very helpful if we could have this heads-up in an updated version of `metadynamics.py`.

**Comment by peastman** [comment]
I've tentatively marked this for inclusion in 7.7.  I'll need to investigate to see if it can be done without adding too much cost.  We should include it on all custom forces that support tabulated functions (see https://github.com/openmm/openmm/issues/3191#issuecomment-902844558).
