### ISSUE TITLE
Best integrators to NVE run

### ISSUE THREAD

**Issue by snpreddy** [openmm/openmm#2204]
Hello all,

I am running NVT followed by NVE. In NVT I am using  Langevin therermostat, T and E are conserving well. In the production run with NVE, using Verlet integrator the conservation is not well. I think the problem is with integrators. 
1) What is the best integrators for NVE run?
2) I have seen many integrators are available (https://openmmtools.readthedocs.io/en/latest/integrators.html), how can I use them?. Suppose how to define BAOAB integrator?

here my input file:

from __future__ import print_function
from simtk.openmm import app
import simtk.openmm as mm
from simtk import unit
from sys import stdout
import mbpol

simulation_name = "w4"
pdb = app.PDBFile('w4.pdb')
temperature = float(200)*unit.kelvin
forcefield = mm.app.ForceField("/opt/conda/miniconda2/envs/openmm_env/lib/python3.6/site-packages/mbpol-1.0-py3.6-linux-x86_64.egg/mbpol.xml")
nonbonded = mm.app.CutoffNonPeriodic
ewaldErrorTolerance = 1e-8
timestep = 0.2*unit.femtoseconds
production_steps = 2500000
################################## NVE

system = forcefield.createSystem(pdb.topology, nonbondedMethod=nonbonded,
    nonbondedCutoff=0.9*unit.nanometers, ewaldErrorTolerance=ewaldErrorTolerance)
integrator = mm.VerletIntegrator(timestep)

simulation = app.Simulation(pdb.topology, system, integrator)
simulation.loadState('nvt8.xml')
final_nvt_state = simulation.context.getState(getVelocities=True, getPositions=True)
positions = final_nvt_state.getPositions()
velocities = final_nvt_state.getVelocities()
simulation.context.setPositions(positions)
simulation.context.computeVirtualSites()
simulation.context.setVelocities(velocities)

simulation.reporters.append(app.PDBReporter('restart_nve.pdb', 1))

simulation.reporters.append(app.StateDataReporter(simulation_name + "_restart_nve.log", 1, step=True,
    potentialEnergy=True, kineticEnergy=True, totalEnergy=True, temperature=True,
    progress=True, remainingTime=True, speed=True, totalSteps=production_steps,
    separator=' '))

print('Running Production...')
simulation.step(production_steps)
print('Done!')

Thanks in advance
Naga

**Comment by peastman** [comment]
Just replace

```python
 integrator = mm.VerletIntegrator(timestep)
```

with whatever integrator you want to use instead.  For example,

```python
from openmmtools.integrators import BAOABIntegrator
integrator = BAOABIntegrator(temperature, collision_rate, timestep)
```

I don't have specific advice on which integrator to use for NVE.  At least for a Verlet integrator, 2 fs is probably a bit too aggressive for the step size.  That size is commonly used for NVT simulations where it only needs to conserve energy over the equilibration time of the thermostat (usually around 10 ps or less).  When you need good energy conservation over the entire simulation, you generally need to use a small step size.

**Comment by snpreddy** [comment]
Dear Peastman,

Thanks for your reply. The timestep what I used is 0.2 fs. I hope it’s good enough.
I will try the suggested format.

Thanks
Naga

**Comment by peastman** [comment]
Sorry, I misread that.  0.2 fs is very small, so that shouldn't be the problem.

Which platform are you using?  If it's CUDA or OpenCL, those use single precision by default which may be hurting the energy conservation.  If so, using mixed precision would help.

```python
simulation = app.Simulation(pdb.topology, system, integrator, mm.Platform.getPlatformByName('CUDA'), {'Precision':'mixed'})
```

**Comment by snpreddy** [comment]
Dear Peastman,

I used the below and terminated with the error
from openmmtools.integrators import VelocityVerletIntegrator
integrator = mm.VelocityVerletIntegrator(timestep)

Error:
AttributeError: module 'simtk.openmm' has no attribute 'VelocityVerletIntegrator'

Naga

**Comment by peastman** [comment]
You need to change `mm.VelocityVerletIntegrator` to just `VelocityVerletIntegrator`.  It isn't in the `simtk.openmm` module (which you imported as `mm`).

**Comment by peastman** [comment]
The documentation page looks kind of broken.  If in doubt, just check the source code: https://github.com/choderalab/openmmtools/blob/master/openmmtools/integrators.py.  It has detailed descriptions of most classes.  Anything that's a subclass of `ThermostatedIntegrator` includes a thermostat.

It looks like most of them have thermostats.  If you want NVE, I would stick to the standard `VerletIntegrator`.

**Comment by snpreddy** [comment]
Thanks for your answer.
I got the below errors while using mixed precision using OpenCL.

simulation = app.Simulation(pdb.topology, system, integrator, mm.Platform.getPlatformByName('OpenCL'), {'Precision':'mixed'})

Traceback (most recent call last):
  File "nve.py", line 28, in <module>
    simulation = app.Simulation(pdb.topology, system, integrator, mm.Platform.getPlatformByName('OpenCL'), {'Precision':'mixed'})
  File "/opt/conda/miniconda2/envs/openmm_env/lib/python3.6/site-packages/simtk/openmm/app/simulation.py", line 105, in __init__
    self.context = mm.Context(self.system, self.integrator, platform, platformProperties)
  File "/opt/conda/miniconda2/envs/openmm_env/lib/python3.6/site-packages/simtk/openmm/openmm.py", line 11936, in __init__
    this = _openmm.new_Context(*args)
Exception: Specified a Platform for a Context which does not support all required kernels

I got the below errors while using mixed precision using CUDA.

simulation = app.Simulation(pdb.topology, system, integrator, mm.Platform.getPlatformByName('CUDA'), {'Precision':'mixed'})

Traceback (most recent call last):
  File "nve.py", line 28, in <module>
    simulation = app.Simulation(pdb.topology, system, integrator, mm.Platform.getPlatformByName('CUDA'), {'Precision':'mixed'})
  File "/opt/conda/miniconda2/envs/openmm_env/lib/python3.6/site-packages/simtk/openmm/openmm.py", line 9427, in getPlatformByName
    return _openmm.Platform_getPlatformByName(name)
Exception: There is no registered Platform called "CUDA"

Could you please let me know what's going wrong?

Thanks
Naga

**Comment by jchodera** [comment]
> The documentation page looks kind of broken. 

Whoops! Will fix.

**Comment by snpreddy** [comment]
Don't understand why the E is not conserved (find the attachment). really appreciate if some one give hint to rectify the issue.

[conserved.pdf](https://github.com/pandegroup/openmm/files/2571447/conserved.pdf)


Thanks
Naga

**Comment by jchodera** [comment]
Can you post a ZIP archive of your input files?

**Comment by jchodera** [comment]
Thanks! I think this is missing `mbpol.xml`. Could you include that?

**Comment by jchodera** [comment]
Oh, it looks like this involves installing the plugin. I'll just try this with a different force field for testing.

**Comment by jchodera** [comment]
If I switch to `tip4pew.xml`, I get completely different behavior:
![image](https://user-images.githubusercontent.com/3656088/48349132-a8afd500-e683-11e8-92c6-933aec30ea36.png)
These are very small changes compared to your plot. I worry that those jumps are due to problems with the [mbpol plugin](http://paesanigroup.ucsd.edu/software/mbpol_openmm.html) you're using.

Another possibility is that the `mm.app.CutoffNonPeriodic` periodic boundary conditions will not conserve energy well if any molecule crosses the cutoff. Also, I doubt the MBPol plugin is meant to be used with the reaction-field treatment that @peastman has included in the `CutoffNonPeriodic` electrostatics.

Velocity Verlet will never exactly conserve total energy, but if you want really small fluctuations without drift, you should minimize and thermalize prior to simulation.

**Comment by snpreddy** [comment]
Thank you @jchodera for your test runs.



> If I switch to `tip4pew.xml`, I get completely different behavior:
> ![image](https://user-images.githubusercontent.com/3656088/48349132-a8afd500-e683-11e8-92c6-933aec30ea36.png)
> These are very small changes compared to your plot. I worry that those jumps are due to problems with the [mbpol plugin](http://paesanigroup.ucsd.edu/software/mbpol_openmm.html) you're using.

If the problem is with mbpolplugin why NVT simulations are good?
> 
> Another possibility is that the `mm.app.CutoffNonPeriodic` periodic boundary conditions will not conserve energy well if any molecule crosses the cutoff. Also, I doubt the MBPol plugin is meant to be used with the reaction-field treatment that @peastman has included in the `CutoffNonPeriodic` electrostatics.
> 
I have tried by increasing the cut off up to 3.0 nm, and didn't change the behavior. 
> Velocity Verlet will never exactly conserve total energy, but if you want really small fluctuations without drift, you should minimize and thermalize prior to simulation.

Not only the problem with E conservation, but also increases T with E and the water molecule evaporates.

I am running NVT followed by NVE. In the equilibration with NVT, E and T are conserved well. In NVE only the problem occurs, one more thing to confirm that I am minimizing and equilibrating with NVT before NVE run.

**Comment by jchodera** [comment]
> If the problem is with mbpolplugin why NVT simulations are good?

It's possible the thermostat is masking the sudden jumps in energy.

> I have tried by increasing the cut off up to 3.0 nm, and didn't change the behavior.

Can you run without a cutoff, using `NoCutoff`?

> Not only the problem with E conservation, but also increases T with E and the water molecule evaporates.

You should also be able to add a weak central restraining potential with `CustomExternalForce` to keep your water droplet localized.

> I am running NVT followed by NVE. In the equilibration with NVT, E and T are conserved well. In NVE only the problem occurs, one more thing to confirm that I am minimizing and equilibrating with NVT before NVE run.

E and T are not "conserved" in simulations that produce NVT ensembles, but you should see minimal drift in their average over time. Simulations in the NVE ensemble are very sensitive to accurately computing conservative forces, so are the best way to detect problems that may not appear in NVT simulations. The same happens with reaction-field electrostatics with short cutoffs.

**Comment by snpreddy** [comment]
> > If the problem is with mbpolplugin why NVT simulations are good?
> 
> It's possible the thermostat is masking the sudden jumps in energy.
> 
> > I have tried by increasing the cut off up to 3.0 nm, and didn't change the behavior.
> 
> Can you run without a cutoff, using `NoCutoff`?
I have tried and getting Segmentation fault. I have tried with out app also and also getting error "NoCutoff not defined"
system = forcefield.createSystem(pdb.topology, nonbondedMethod=app.NoCutoff)

> 
> > Not only the problem with E conservation, but also increases T with E and the water molecule evaporates.
> 
> You should also be able to add a weak central restraining potential with `CustomExternalForce` to keep your water droplet localized.
I have searched for this and didn't understand how to add it. Could you please give details to add it?
> 
> > I am running NVT followed by NVE. In the equilibration with NVT, E and T are conserved well. In NVE only the problem occurs, one more thing to confirm that I am minimizing and equilibrating with NVT before NVE run.
> 
> E and T are not "conserved" in simulations that produce NVT ensembles, but you should see minimal drift in their average over time. Simulations in the NVE ensemble are very sensitive to accurately computing conservative forces, so are the best way to detect problems that may not appear in NVT simulations. The same happens with reaction-field electrostatics with short cutoffs.

Okay, Thank you so much @jchodera

**Comment by snpreddy** [comment]
@peastman 
As you suggested, I have checked the platform, using Reference, and it’s double precision. So the problem is not related to precision.

As suggested by @jchodera, applied external force, still E not conserved. I don’t know the problem exactly which leads large drift in E.

Could you please let me know any other options to solve it?

**Comment by jchodera** [comment]
I'm guessing the mbpol plugin is responsible since things look reasonable if you switch to TIP4P-Ew.

**Comment by snpreddy** [comment]
As a try, would like to use MTSintegrator, I have tried with 0.2 timestep with group [(0,1)]. The E conservation looks better and it falls in range of 10 kJ/mol. When I use group [(0,1), (1,2), (2,8)] again it looks worst. 

I understand that I missed to setForceGroup, and it only leads bad E conservation. If some having idea to set this, I really appreciate. 

Just replacing the integrator section:
from openmmtools.integrators import MTSIntegrator
integrator = MTSIntegrator(timestep, [(0,1), (1,2), (2,8)])
