### ISSUE TITLE
MTSIntegrator force grouping

### ISSUE THREAD

**Issue by snpreddy** [openmm/openmm#2207]
As a try, would like to use MTSintegrator, I have tried with 0.2 timestep with group [(0,1)]. The E conservation looks better and it falls in range of 10 kJ/mol. When I use group [(0,1), (1,2), (2,8)] again it looks worst.

I understand that I missed to setForceGroup, and it only leads bad E conservation. If some having idea to use setForceGroup, I really appreciate.

Just replacing the integrator section:
from openmmtools.integrators import MTSIntegrator
integrator = MTSIntegrator(timestep, [(0,1), (1,2), (2,8)])

**Comment by peastman** [comment]
> I understand that I missed to setForceGroup, and it only leads bad E conservation.

Sorry, I don't understand what you mean by that.  Could you clarify?

You've told it to use different update frequencies for force groups 0, 1, and 2.  What forces are in each of those groups?  Are there any forces in still another group (other than 0, 1, and 2)?

**Comment by snpreddy** [comment]
> > I understand that I missed to setForceGroup, and it only leads bad E conservation.
> 
> Sorry, I don't understand what you mean by that. Could you clarify?
> 
> You've told it to use different update frequencies for force groups 0, 1, and 2. What forces are in each of those groups? Are there any forces in still another group (other than 0, 1, and 2)?

Manual says "To use MISintegrator, you must first divide your forces into two or more groups (by calling setForceGroup() on them) that should be evaluated at different frequencies. When you create the integrator, you provide a tuple for each group specifying the index of the force group and the frequency (as a fraction of the outermost time step) at which to evaluate it."

Here is my input, I think I am I am missing setForceGroup command.

from __future__ import print_function
from simtk.openmm import app
import simtk.openmm as mm
#import openmmtools
#from openmmtools.integrators import VelocityVerletIntegrator
from simtk import unit
from sys import stdout
import mbpol

simulation_name = "w4"
pdb = app.PDBFile('w4.pdb')
temperature = float(250)*unit.kelvin
forcefield = mm.app.ForceField("/opt/conda/miniconda2/envs/openmm_env/lib/python3.6/site-packages/mbpol-1.0-py3.6-linux-x86_64.egg/mbp
ol.xml")
nonbonded = mm.app.CutoffNonPeriodic
ewaldErrorTolerance = 1e-8
timestep = 0.4*unit.femtoseconds
production_steps = 1250000
################################## NVE

system = forcefield.createSystem(pdb.topology, nonbondedMethod=nonbonded,
    nonbondedCutoff=0.9*unit.nanometers, ewaldErrorTolerance=ewaldErrorTolerance)
#integrator = mm.nonequilibriumlangevinintegrator(timestep) 
#integrator = mm.VelocityVerletIntegrator(timestep) 
from openmmtools.integrators import MTSIntegrator
integrator = MTSIntegrator(timestep, [(0,1), (1,2), (2,8)])

simulation = app.Simulation(pdb.topology, system, integrator)
simulation.loadState('nvt7.xml')
final_nvt_state = simulation.context.getState(getVelocities=True, getPositions=True)
positions = final_nvt_state.getPositions()
velocities = final_nvt_state.getVelocities()
simulation.context.setPositions(positions)
simulation.context.computeVirtualSites()
simulation.context.setVelocities(velocities)


simulation.reporters.append(app.PDBReporter('restart_nve.pdb', 2))

simulation.reporters.append(app.StateDataReporter(simulation_name + "_restart_nve.log", 10, step=True,
    potentialEnergy=True, kineticEnergy=True, totalEnergy=True, temperature=True,
    progress=True, remainingTime=True, speed=True, totalSteps=production_steps,
    separator=' '))

print('Running Production...')
simulation.step(production_steps)
print('Done!')

**Comment by peastman** [comment]
> I think I am I am missing setForceGroup command.

That is true, you aren't setting it.  Every force is initially in group 0.  If you want to put one in a different group, you need to call `setForceGroup()` on it.  For a `NonbondedForce`, you can also call `setReciprocalSpaceForceGroup()` to have it put the reciprocal space interactions into a different group from the direct space interactions.

You can call `system.getForces()` to get a list of all the forces in your system.

The goal of MTSIntegrator is to compute inexpensive, fast changing forces frequently, and compute expensive, slow changing forces less frequently.  I'm not familiar with the mbpol force field, so I don't know what forces it includes.
