### ISSUE TITLE
VariableVerletIntegrator with very small error tolerance (1.0E-10)

### ISSUE THREAD

**Issue by snpreddy** [openmm/openmm#2208]
I have tried the simulations with VariableVerletIntegrator, if I use small tolerance(1.0e-10 tolerance), the E conservation is good and given the plot below. I would like to know whether that much small tolerance is acceptable or not? 

![energy](https://user-images.githubusercontent.com/39238829/48670582-79391680-eb22-11e8-8ff0-d572c0b95d0b.png)

**Comment by peastman** [comment]
You can get good energy conservation with any integrator by making the step size small enough (which is what you're doing by reducing the tolerance).  But if precise energy conservation is particularly important to you, you might be better off using a fixed step size Verlet.  It's symplectic, so it will have better energy conservation at the same average step size.
