### ISSUE TITLE
Assigning GBSA parameters with new AMBER force fields

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#2209]
@dwhswenson recently ran into some issues with using GBSA parameters which let me to wonder how users are supposed to use GBSA with the new force field ffxml files. It looks like we haven't [updated our documentation](http://docs.openmm.org/latest/userguide/application.html#amber14) as to how to use GBSA with the new Amber 14 conversion.

**Comment by peastman** [comment]
We don't support GBSA with the newer files.  You would have to load a prmtop file instead.  That's why the GB files are only included in the "Older Amber Force Fields" section.
