### ISSUE TITLE
RHEL7 Cannot call openmm from OS python 2.7

### ISSUE THREAD

**Issue by foellien** [openmm/openmm#2211]
I have build OpenMM and also the PythonInstall. OpenMM has been placed in /opt/openmm and the Python modules have been written to usr/lib64/python2.7/site-packages/simtk
No issues were seen in the process.

When I now try to start an openmm command I am getting the following error:

>>> from simtk.openmm import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/simtk/openmm/__init__.py", line 19, in <module>
    from simtk.openmm.openmm import *
  File "/usr/lib64/python2.7/site-packages/simtk/openmm/openmm.py", line 18, in <module>
    _openmm = swig_import_helper()
  File "/usr/lib64/python2.7/site-packages/simtk/openmm/openmm.py", line 17, in swig_import_helper
    return importlib.import_module('_openmm')
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named _openmm

**Comment by Lnaden** [comment]
If you are building from source, you will likely have to also set the environment variables `OPENMM_INCLUDE_PATH` and `OPENMM_LIB_PATH` to tell the Python version of OpenMM where to look for the OpenMM install location.

There is more info in this block here which should give more details:
http://docs.openmm.org/7.1.0/userguide/library.html?highlight=from%20source#installing-on-linux-and-mac

**Comment by foellien** [comment]
I have set both variables, but this is not helping

running install
running build
running build_py
copying simtk/openmm/version.py -> build/lib.linux-x86_64-2.7/simtk/openmm
running build_ext
running install_lib
creating /usr/lib64/python2.7/site-packages/simtk/unit
copying build/lib.linux-x86_64-2.7/simtk/unit/__init__.py -> /usr/lib64/python2.7/site-packages/simtk/unit
copying build/lib.linux-x86_64-2.7/simtk/unit/basedimension.py -> /usr/lib64/python2.7/site-packages/simtk/unit
copying build/lib.linux-x86_64-2.7/simtk/unit/baseunit.py -> /usr/lib64/python2.7/site-packages/simtk/unit
copying build/lib.linux-x86_64-2.7/simtk/unit/constants.py -> /usr/lib64/python2.7/site-packages/simtk/unit
copying build/lib.linux-x86_64-2.7/simtk/unit/doctests.py -> /usr/lib64/python2.7/site-packages/simtk/unit
copying build/lib.linux-x86_64-2.7/simtk/unit/mymatrix.py -> /usr/lib64/python2.7/site-packages/simtk/unit
copying build/lib.linux-x86_64-2.7/simtk/unit/prefix.py -> /usr/lib64/python2.7/site-packages/simtk/unit
copying build/lib.linux-x86_64-2.7/simtk/unit/quantity.py -> /usr/lib64/python2.7/site-packages/simtk/unit
copying build/lib.linux-x86_64-2.7/simtk/unit/standard_dimensions.py -> /usr/lib64/python2.7/site-packages/simtk/unit
copying build/lib.linux-x86_64-2.7/simtk/unit/unit.py -> /usr/lib64/python2.7/site-packages/simtk/unit
copying build/lib.linux-x86_64-2.7/simtk/unit/unit_definitions.py -> /usr/lib64/python2.7/site-packages/simtk/unit
copying build/lib.linux-x86_64-2.7/simtk/unit/unit_math.py -> /usr/lib64/python2.7/site-packages/simtk/unit
copying build/lib.linux-x86_64-2.7/simtk/unit/unit_operators.py -> /usr/lib64/python2.7/site-packages/simtk/unit
copying build/lib.linux-x86_64-2.7/simtk/openmm/version.py -> /usr/lib64/python2.7/site-packages/simtk/openmm
byte-compiling /usr/lib64/python2.7/site-packages/simtk/unit/__init__.py to __init__.pyc
byte-compiling /usr/lib64/python2.7/site-packages/simtk/unit/basedimension.py to basedimension.pyc
byte-compiling /usr/lib64/python2.7/site-packages/simtk/unit/baseunit.py to baseunit.pyc
byte-compiling /usr/lib64/python2.7/site-packages/simtk/unit/constants.py to constants.pyc
byte-compiling /usr/lib64/python2.7/site-packages/simtk/unit/doctests.py to doctests.pyc
byte-compiling /usr/lib64/python2.7/site-packages/simtk/unit/mymatrix.py to mymatrix.pyc
byte-compiling /usr/lib64/python2.7/site-packages/simtk/unit/prefix.py to prefix.pyc
byte-compiling /usr/lib64/python2.7/site-packages/simtk/unit/quantity.py to quantity.pyc
byte-compiling /usr/lib64/python2.7/site-packages/simtk/unit/standard_dimensions.py to standard_dimensions.pyc
byte-compiling /usr/lib64/python2.7/site-packages/simtk/unit/unit.py to unit.pyc
byte-compiling /usr/lib64/python2.7/site-packages/simtk/unit/unit_definitions.py to unit_definitions.pyc
byte-compiling /usr/lib64/python2.7/site-packages/simtk/unit/unit_math.py to unit_math.pyc
byte-compiling /usr/lib64/python2.7/site-packages/simtk/unit/unit_operators.py to unit_operators.pyc
byte-compiling /usr/lib64/python2.7/site-packages/simtk/openmm/version.py to version.pyc
running install_egg_info
Removing /usr/lib64/python2.7/site-packages/OpenMM-7.3.0-py2.7.egg-info
Writing /usr/lib64/python2.7/site-packages/OpenMM-7.3.0-py2.7.egg-info
[root@gprde2d153071 python]# pwd
/root/tmp/openmm/build/python
[root@gprde2d153071 python]# python -m simtk.testInstallation
Failed to import OpenMM packages; OpenMM will not work.
Make sure OpenMM is installed and the library path is set correctly.

Error message: No module named _openmm

**Comment by peastman** [comment]
There's a good chance it's failing to find a library that it depends on.  You can check that with `ldd`.  First look in /usr/lib64/python2.7/site-packages/simtk/openmm.  You should find a file there whose name starts with `_openmm` and ends with `.so`.  For example, on the computer I'm looking at right now it's called `_openmm.cpython-36m-x86_64-linux-gnu.so`.  Run `ldd` on that file, and it will tell you what dependencies it has.

Perhaps you just need to add your OpenMM lib directory to `LD_LIBRARY_PATH`?
