### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by mboisson** [openmm/openmm#2221]
I am building OpenMM for a Skylake processor, using Intel 2018.3 and OpenMPI 3.1.2. The tests fail with : 

```
The following tests FAILED:
         56 - TestReferenceAmoebaExtrapolatedPolarization (Failed)
         59 - TestReferenceAmoebaMultipoleForce (Failed)
``` 
All other tests succeed.

How do I diagnoze what the problem is ?

**Comment by peastman** [comment]
If you run the tests individually, you should get an error message that gives more information.  For example,

```
./TestReferenceAmoebaMultipoleForce
```

**Comment by mboisson** [comment]
I get the following : 
```
-bash-4.2$  ./TestReferenceAmoebaMultipoleForce
TestReferenceAmoebaMultipoleForce running test...
exception: Assertion failure at TestReferenceAmoebaMultipoleForce.cpp:301.  testMultipoleWaterDirectPolarization Expected -1.23967, found -1.28064
FAIL - ERROR.  Test failed.
-bash-4.2$ ./TestReferenceAmoebaExtrapolatedPolarization
exception: Assertion failure at TestReferenceAmoebaExtrapolatedPolarization.cpp:94.  testWaterDimerTriclinicPME Expected [-131.11, -187.273, 36.9466], found [-140.29, -199.056, 44.2971]
FAIL - ERROR.  Test failed.
```

**Comment by peastman** [comment]
I'm quite confused by that result.  It's using the reference platform, so its behavior should be entirely reproducible.  Possibly the compiler is doing some overly aggressive optimizations that hurt numerical accuracy.  I suggest trying clang or gcc.  We don't test with the Intel compiler, so I have less confidence in things working with it.

**Comment by mboisson** [comment]
@bartoldeman figured out the issue. It was when enabling the AVX512 instructions. 

```I finally found a way to compile OpenMM (without needing to resort to `-no-vec -no-fma` which defeats the purpose): use `xCOMMON-AVX512'`
the common-avx512 switch disables avx512 instructions that are specific to skylake but do not exist on knights landing. There could be an Intel compiler bug but don’t really have time to investigate that.```
