### ISSUE TITLE
Temperature equilibration issue with solvents different from water

### ISSUE THREAD

**Issue by cespos** [openmm/openmm#2223]
I was running MD simulations for 18 small organic molecules in different solvents, namely water, octanol, and POPC lipid bilayer (the input files are pasted below) and while the temperature equilibrated at the set value for simulations in water, it did not for simulations in octanol or lipid bilayer. In particular, I set the temperature to 298.15 K and I obtained an average temperature of 310 K for simulations in octanol and 305 K for simulations in the lipid bilayer (see Figure below). Do you know which might be the problem? I am using the 7.3.0 version of openMM.

![181129_abc-transporters 1](https://user-images.githubusercontent.com/31316943/49583614-05d43900-f959-11e8-87a6-0b7a3eb595fc.png)

`
#------------------------
# Water and Octanol
#------------------------
platform = Platform.getPlatformByName('CPU')
system = prmtop.createSystem(nonbondedMethod=app.PME, nonbondedCutoff=1*unit.nanometer, constraints=app.AllBonds)  #check contraints Hbonds in the tutorial

thermostat = AndersenThermostat(298.15 * unit.kelvin, 1/unit.picosecond)
system.addForce(thermostat)
barostat = MonteCarloBarostat(1.013 * unit.bar, 298.15 * unit.kelvin)
system.addForce(barostat)
integrator = VerletIntegrator(0.002 * unit.picoseconds)
simulation = Simulation(prmtop.topology, system, integrator, platform)
if inpcrd.boxVectors is not None:
        simulation.context.setPeriodicBoxVectors(*inpcrd.boxVectors)
simulation.context.setPositions(inpcrd.positions)

print("Minimizing")
simulation.minimizeEnergy(tolerance=10*unit.kilojoule/unit.mole)  

print("NPT Equilibration")
simulation.reporters.append(StateDataReporter('{}_npt.cvs'.format(output_name), 500, step=True, potentialEnergy=True, temperature=True))  
simulation.step(25000)  #50 ps nvt equilibration
`

`
#------------------------
# POPC bilayer
#------------------------
system = prmtop.createSystem(nonbondedMethod=app.PME, nonbondedCutoff=1*unit.nanometer, constraints=app.AllBonds)  #check contraints Hbonds in the tutorial

thermostat = AndersenThermostat(298.15 * unit.kelvin, 1/unit.picosecond)
system.addForce(thermostat)
barostat = MonteCarloMembraneBarostat(1.013*unit.bar, 0*unit.bar*unit.nanometer, 298.15 * unit.kelvin, MonteCarloMembraneBarostat.XYIsotropic, MonteCarloMembraneBarostat.ZFree)
system.addForce(barostat)
integrator = VerletIntegrator(0.002 * unit.picoseconds)
simulation = Simulation(prmtop.topology, system, integrator, platform)
if prmtop.box_vectors is not None:
        simulation.context.setPeriodicBoxVectors(*prmtop.box_vectors)
simulation.context.setPositions(prmtop.positions)

print("Minimizing")
simulation.minimizeEnergy(tolerance=10*unit.kilojoule/unit.mole)  

print("NPT Equilibration")
simulation.reporters.append(StateDataReporter('{}_npt.cvs'.format(output_name), 500, step=True, potentialEnergy=True, temperature=True, totalEnergy=True, volume=True, density=True))  # !!!
simulation.reporters.append(NetCDFReporter('{}_npt.nc'.format(output_name), 500)) 
simulation.step(500000)  #1 ns npt equilibration
`

_Originally posted by @cespos in https://github.com/pandegroup/openmm/pull/1487#issuecomment-444852572_

**Comment by peastman** [comment]
When your temperature is coming out too high, that usually indicates some calculation isn't being done accurately enough.  Most sources of error act like an additional random force, adding heat to the system.  So you need to figure out where the error is coming from, and adjust it to be more accurate.  Usually you can just do this by adjusting things one at a time and seeing whether the results improve.  Here are some things to try.

- Reduce the time step, for example to 0.001 ps.
- Reduce the Ewald error tolerance.  Try adding the argument `ewaldErrorTolerance=1e-4` to the call to `createSystem()`.
- Reduce the tolerance for constraints.  Try calling `integrator.setConstraintTolerance(1e-6)`.
- Enable the switching function for LJ interactions.  Call `setUseSwitchingFunction(True)` and `setSwitchingDistance(0.95*unit.nanometer)` on the `NonbondedForce`.

**Comment by jchodera** [comment]
I'm not sure if the `AndersenThermostat` should not be used with the leapfrog form of `VerletIntegrator` that is in OpenMM since the positions and velocities lag each other by half a timestep. AMBER used to do this as well, which led to a systematic bias in the kinetic temperature because synchronizing the velocities with the positions after the randomization required a velocity half-kick.

You might also try eliminating `AndersenThermostat` and switching to `LangevIntegrator` with a weak collision rate, like `1.0 / unit.picoseconds`.

**Comment by cespos** [comment]
@peastman I tried the things you suggested but I did not notice any difference in the temeprature equilibtation. @jchodera There is a significant improvement using the Langevin Integrator, but there is still a drift of 2-3 degrees from the target temperature.

![181207_abc-transporters](https://user-images.githubusercontent.com/31316943/49660514-119e2900-fa47-11e8-8b79-8fb914b02f5c.png)
