### ISSUE TITLE
Loadstate for continuation

### ISSUE THREAD

**Issue by snpreddy** [openmm/openmm#2228]
Dear users and developers,

I saved few sates in the simulations, and want to continue the same calculations from the saved state. I used the loadstate() option, but the obtained data is not exactly same.

Here the input for simulations, and saved states for further usage.
https://gist.github.com/snpreddy/0e22f43dc06bcfcd30230eb506873e39

Continued simulations from the saved state, for that I checked whether it is giving the identical data or not(started from nvt9.xml, ran 5 steps), the log files are not same with earlier data.
https://gist.github.com/snpreddy/3ba4795b90a81f92066e1a225c2809a8

**Comment by peastman** [comment]
Compare [`saveState()`](http://docs.openmm.org/latest/api-python/generated/simtk.openmm.app.simulation.Simulation.html#simtk.openmm.app.simulation.Simulation.saveState) and [`saveCheckpoint()`](http://docs.openmm.org/latest/api-python/generated/simtk.openmm.app.simulation.Simulation.html#simtk.openmm.app.simulation.Simulation.saveCheckpoint).  A checkpoint records all internal state of the simulation, so you can exactly continue from that point.  The disadvantage is that checkpoints are platform and hardware specific, so you can only load it into another simulation using the same platform and identical hardware.  States are more portable, but they only record public information, not internal state, so when you reload it you may not get an identical trajectory.

**Comment by snpreddy** [comment]
Means saveCheckpoint() is able to give identical trajectory?

**Comment by peastman** [comment]
That's the goal.  It isn't guaranteed that will always be the case, but it tries.  If you're using CUDA, be sure to set "DeterministicForces" to "true" (see http://docs.openmm.org/latest/userguide/library.html#cuda-platform).  Otherwise, the trajectory will of course not be deterministic.

**Comment by peastman** [comment]
Like I said, a checkpoint usually but not always leads to an identical trajectory.  When it doesn't, that's because the trajectory wasn't deterministic to begin with.  If you ran two simulations starting from the same state, you would get different ending states.  That doesn't mean one is "right" and the other is "wrong".  Both are equally valid.  But you're simulating a chaotic system, so even the tiniest difference (such as changing the least significant bit in the force on one atom) will cause the trajectories to diverge.

**Comment by snpreddy** [comment]
Okay, Thank you @peastman 
I saved state in the xml format, and continued from that if required, I hope we can take it as continuation of earlier trajectory.

**Comment by peastman** [comment]
Closing this since it's been resolved.
