### ISSUE TITLE
reading pdbfile error on pdbfile.py

### ISSUE THREAD

**Issue by guyujun** [openmm/openmm#2234]
I m running pdbfixer1.5: but openmm return error!
return another error..:
Traceback (most recent call last):
File "./repair.py", line 107, in 
repair(pdbfile)
File "./repair.py", line 83, in repair
fixer = PDBFixer(filename=pdbfile)
File "/usr/lib/python2.7/site-packages/pdbfixer-1.5-py2.7.egg/pdbfixer/pdbfixer.py", line 277, in init
templatePdb = app.PDBFile(os.path.join(templatesPath, file))
File "/usr/lib64/python2.7/site-packages/simtk/openmm/app/pdbfile.py", line 160, in init
self.positions = self._positions[0]
IndexError: list index out of range

please help.

**Comment by awakenwu** [comment]
All fixed!!! if I install pdbfixer-1.5 from conda command！！

however，If I install pdbfixer from source. It come error: 

It is the error, when I installing pdb-fixer.
>>
removing '/usr/lib/python2.7/site-packages/pdbfixer-1.5-py2.7.egg' (and everything under it)
creating /usr/lib/python2.7/site-packages/pdbfixer-1.5-py2.7.egg
Extracting pdbfixer-1.5-py2.7.egg to /usr/lib/python2.7/site-packages
Sorry: TypeError: compile() expected string without null bytes
Sorry: TypeError: compile() expected string without null bytes
Sorry: TypeError: compile() expected string without null bytes
Sorry: TypeError: compile() expected string without null bytes
Sorry: TypeError: compile() expected string without null bytes
Sorry: TypeError: compile() expected string without null bytes
Sorry: TypeError: compile() expected string without null bytes
Sorry: TypeError: compile() expected string without null bytes
pdbfixer 1.5 is already the active version in easy-install.pth

pdbfixer is already can active by comline. but it can not read PDB ( whatever, I tried).

My env = openmm7.3 pdbfixer-1.5 SWIG Version 3.0.12(g++ compiled) cmake-3.6.2 doxygen1.8.5

Best,
Kun


> 在 2018年12月25日，00:29，John Chodera <notifications@github.com> 写道：
> 
> Can you post your driver script and input files as a ZIP archive so we can take a look at what is going wrong?

**Comment by awakenwu** [comment]
> Can you post your driver script and input files as a ZIP archive so we can take a look at what is going wrong?

SENT ALREADY PLEASE CHECK...

**Comment by peastman** [comment]
Closing this, since it's been resolved.
