### ISSUE TITLE
Replica-based restrained simulations

### ISSUE THREAD

**Issue by forcefield** [openmm/openmm#2235]
What is the easiest way to implement replica-based restrained ensemble simulations in openMM?  In the restrained ensemble simulations, _N_ replicas of the same molecular system are simulated in parallel, and the average of the observables of interest are restrained to their reference experimental values.  The equilibrium distribution of the ensemble, consisting of _N_ replicas, is given by

<img src="https://latex.codecogs.com/gif.latex?p_N(&space;\{&space;x_{i=1,2,\dots,N}&space;\})&space;\propto&space;\exp\left(&space;-\beta&space;\sum_{i=1}^N&space;E(&space;x_i)&space;-&space;\sum_{\alpha=1}^M&space;\frac{K_\alpha}{2}&space;(N^{-1}\sum_{i=1}^N&space;D_\alpha&space;(x_i)&space;-&space;D_\alpha)^2\right)" title="p_N( \{ x_{i=1,2,\dots,N} \}) \propto \exp\left( -\beta \sum_{i=1}^N E( x_i) - \sum_{\alpha=1}^M \frac{K_\alpha}{2} (N^{-1}\sum_{i=1}^N D_\alpha (x_i) - D_\alpha)^2\right)" />

The replicas interact with one another through the restraining term.  Typically there are 10s to 100s of restraining terms (i.e., _M_ is on the order of 10 to 100), and the number of replicas can range between 10 and 100 (i.e., _N_ is on the order of 10 to 100).

Should this be achieved through a new customized integrator (as in ring-polymer MD), or through a new customized force, which will be taking pointers to data from other molecular systems as arguments?

Should this be implemented for single GPU, or should this be best implemented by MPI on multiple GPUs?

Thanks!

**Comment by jchodera** [comment]
I imagine @peastman will have some good suggestions, but I'll note that you can use the correspondence between ensemble-restrained simulations and MaxEnt to instead use a single replica with linear applied fields to match experimental ensemble averages:
![codecogseqn 1](https://user-images.githubusercontent.com/3656088/50503521-6b798980-0a1c-11e9-9a24-f0b01c105d4b.gif)
though the field parameters need to be iteratively refined, though this can be done through a convex optimization process using reweighting techniques to satisfy
![codecogseqn 2](https://user-images.githubusercontent.com/3656088/50503555-8ea43900-0a1c-11e9-8979-bb0ef955aa9f.gif)
See [this paper](http://www.choderalab.org/publications/2014/4/26/on-the-use-of-experimental-observations-to-bias-simulated-ensembles?rq=pitera) and the excellent follow-up by [Roux and Weare](https://aip.scitation.org/doi/abs/10.1063/1.4792208).

**Comment by peastman** [comment]
A new integrator would probably be the most straightforward way of doing it.  At least to begin with I would put everything on one GPU.  Once that's working, if you find you need to parallelize it further and you're feeling ambitious you could try supporting multiple GPUs.

**Comment by forcefield** [comment]
Thanks to @jchodera for bringing up the maximum entropy alternative.  I am indeed exploring the similarity and the difference between the restrained ensemble simulations and the maximum entropy method, which are not equivalent for finite restraining strength and finite number of replicas.  It is straightforward for restrained ensemble simulations  to take into consideration of the measurement uncertainties associated with experimental data, whereas it is unclear how to do so in the maximum entropy method.  I just posted [a manuscript on arXiv](https://arxiv.org/abs/1812.10802) discussing this.

**Comment by jchodera** [comment]
I think there's a straightforward way to incorporate measurement uncertainty in the MaxEnt approach. I have some notes I'll email you directly.
