### ISSUE TITLE
Weird behavior of Lepton

### ISSUE THREAD

**Issue by ymwangg** [openmm/openmm#2238]
I'm recently trying to develop an OpenMM plugin using Lepton. I found there might possibly be a bug in the JIT function of Lepton.

The following is the minimal code to generate the behavior
```c++
#include "OpenMM.h"
#include "lepton/CompiledExpression.h"
#include "lepton/CustomFunction.h"
#include "lepton/ExpressionProgram.h"
#include "lepton/ExpressionTreeNode.h"
#include "lepton/Operation.h"
#include "lepton/ParsedExpression.h"
#include "lepton/Parser.h"
#include <iostream>

using namespace::std;
int main(){
    for(int i=0; i<3; ++i){
        Lepton::ParsedExpression ex = Lepton::Parser::parse("x+y^2").optimize();
        Lepton::CompiledExpression expression = ex.createCompiledExpression();
        cout<<"iteration = "<<i<<endl;
    }   
    return 0;
}
```

If I compile it with gcc4.9.4, Lepton seems to set `i` to zero every iteration and the program enters an infinite loop.
```
iteration = 0
iteration = 0
iteration = 0
iteration = 0
iteration = 0
iteration = 0
iteration = 0
iteration = 0
iteration = 0
iteration = 0
iteration = 0
iteration = 0
iteration = 0
'''
```

If I compile it with icpc18.0.1, the following exception is reported.
```
terminate called after throwing an instance of 'Lepton::Exception'
  what():  Illegal call to an initialized ParsedExpression
Aborted (core dumped)
```

However, if I use the following code.
```c++
int main(){
    for(int i=0; i<3; ++i){
        Lepton::ParsedExpression ex = Lepton::Parser::parse("x+y^2").optimize();
        Lepton::CompiledExpression expression = ex.createCompiledExpression();
        cout<<"iteration = "<<i<<endl;
        double& x = expression.getVariableReference("x");
        x = 3.0;
        double& y = expression.getVariableReference("x");
        y = 2.0;
        double value = expression.evaluate();
        cout<<"value = "<<value<<endl;
    }   
    return 0;
}
```

The code compiled by g++4.9.4 has the following output:
```
iteration = 0
value = 2
iteration = 1
value = 2
iteration = 2
value = 2
Segmentation fault (core dumped)
```

I noticed this issue was gone if I turn off the compiler flag `LEPTON_USE_JIT`. It seems that other native OpenMM classes using Lepton works without this issue.

Is this a compiler issue? 
I really appreciate it if anyone can help.

**Comment by peastman** [comment]
I was able to reproduce this (not exactly the same behavior, but an error) when compiling with gcc, but not with clang.  I'm not sure what's going on.  Running it through valgrind didn't highlight anything obviously wrong in our code.  It's possible the problem is internal to asmjit.  If so, I should check whether there's a newer version we could try updating to.

**Comment by ymwangg** [comment]
Thanks. I tried the newest asmjit, but It seems that asmjit changes their APIs and is no longer compatible with Lepton.

**Comment by peastman** [comment]
I can't reproduce this anymore with either clang or gcc.  A lot has changed since then, including a new version of asmjit and new versions of the compilers.  Something probably fixed it along the way.
