### ISSUE TITLE
Dimensionless unit.Quantity loses type on multiplication

### ISSUE THREAD

**Issue by SimonBoothroyd** [openmm/openmm#2247]
I'm experiencing what seems like unexpected behavior when multiplying a dimensionless Quantity by a scalar - the return value is a vanilla python number, instead of what I would expect to be another dimensionless Quantity.

The following is the minimal code to generate the behavior:

``` 
from simtk import unit
p = unit.Quantity(5, None)
q = p * 2
assert p < q
``` 

where q will be a python number (not a Quantity), and `p < q` will throw an exception that 'AttributeError: 'int' object has no attribute 'value_in_unit''

The same example behaves as expected with units other than dimensionless, for example:

``` 
from simtk import unit
p = unit.Quantity(5, unit.meter)
q = p * 2
assert p < q
``` 

yields `q` with a type of unit.Quantity, and `p < q` evaluates correctly. I'm running the above with openmm  version 7.3.0 pulled from omnia.

**Comment by peastman** [comment]
It never occurred to me to try to make a Quantity with no units.  What are you trying to accomplish?  Whenever the result of a calculation comes out dimensionless, it always gets returned as an ordinary number rather than a quantity.  That way it functions the way you expect in other Python code.

**Comment by SimonBoothroyd** [comment]
In the codebase I'm working in we are using unit.Quantity as a general utility to represent any value of a physical quantity (such as a density or dielectric constant) whether it comes out of openmm simulation or from some other source. Because some properties are unitless (e.g dielectric constants), I've just been wrapping them in Quantity(value, None) to keep everything internally consistent (i.e so that all values have type Quantity regardless of their unit). 

I wasn't aware that this would be an unexpected use case of Quantity (the default value of unit in the Quantity constructor is itself None) so it sounds like the above snippet I posted behaves as openmm would expect. In fact looking at the Quantity source it looks like the above behavior is the expected behavior documented in the Quantity.__mul__ docstring. So it sounds like openmm always expects dimensionless values to be just ordinary numbers? Have I understood this correctly?
