### ISSUE TITLE
Double counting of Bonded Interactions in Flexible Water models

### ISSUE THREAD

**Issue by jstoppelman** [openmm/openmm#2252]
The following simulation protocol seems to double count the number of bonds for a flexible water model:

pdb = PDBFile('spcfw.pdb')
pdb.topology('residues.xml')
pdb.topology.createStandardBonds();

This is fixed with the following:
Topology.loadBondDefinitions('residues.xml')
pdb = PDBFile('spcfw.pdb')
 (and no extra call to createStandardBonds();)

This is explained in the manual that the PDBFile object automatically calls createStandardBonds(); However, the fact that the first protocol is incorrect could easily be missed. It took us a while to determine this. Is there a more general protocol that could be used to avoid subtle errors like this in the future?

**Comment by peastman** [comment]
It's very rare that you should ever have a reason to call `createStandardBonds()`.  It exists mainly for use by the various file loaders.

**Comment by jchodera** [comment]
@peastman But it's part of the public API. If we don't intend people to use it, it should be prefixed with an understrike (`_`) to designate that it is part of the [internal API](https://www.python.org/dev/peps/pep-0008/#public-and-internal-interfaces). 

Even better---could we fix it so it does it's job correctly in all circumstances?
