### ISSUE TITLE
CUDA 10.1 is available

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#2282]
CUDA 10.1 is available now: [download](https://developer.nvidia.com/cuda-downloads) | [release notes](https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#title-new-features)

**Comment by swails** [comment]
CUDA 10.1 is now on both GPU-enabled Jenkins machines as the default CUDA installation, so it's tested with that version of the toolkit.
