### ISSUE TITLE
Bonds elongated after minimization

### ISSUE THREAD

**Issue by ajsilveira** [openmm/openmm#2288]
I am applying the addHydrogen() function of app.Modeller to a pdb obtained
using PDBFixer. After minimizing the resulting configuration, (at least) one N-C bond (between atoms 1195 and 1197) is being elongated from 1.46 A to 2.87 A. 
This is noticeable when visualizing the protein, where the secondary structure seems to be "broken". 
The pdb file from PDBFixer, together with those obtained before and after doing the minimization can be found in https://gist.github.com/ajsilveira/b1ac14c3f61a985dfd351220e34ff392
I am using openmm 7.3.1 with the following script:

```
from simtk.openmm import app
from simtk import openmm, unit

platform = openmm.Platform.getPlatformByName('CUDA')

pdb = app.PDBFile('3sy7_opm_fixed.pdb')
forcefield = app.ForceField('amber14-all.xml', 'amber14/tip3pfb.xml')
modeller = app.Modeller(pdb.topology, pdb.positions)
modeller.addHydrogens(forcefield=forcefield)

system = forcefield.createSystem(modeller.topology,
                                 nonbondedMethod=app.PME,
                                 nonbondedCutoff=1*unit.nanometer)
integrator = openmm.VerletIntegrator(0.5*unit.femtoseconds)
simulation = app.Simulation(modeller.topology, system, integrator, platform)
simulation.context.setPositions(modeller.positions)
app.PDBFile.writeFile(modeller.topology,modeller.positions,open("oprd_before_min.pdb", 'w'))
simulation.minimizeEnergy(maxIterations=0)
positions = simulation.context.getState(getPositions=True).getPositions()
app.PDBFile.writeFile(modeller.topology,positions,open("oprd_after_min.pdb", 'w'))
```

**Comment by jchodera** [comment]
@peastman: Could this be a result of recent changes to the restraining potential used for constrained bonds?

**Comment by tristanic** [comment]
I realise this thread is somewhat old, but I suspect what's going on here is that OpenMM is setting the periodic box dimensions from the CRYST1 card, and in this case the box is **far** too small. If I open the model in a symmetry-aware environment (ISOLDE, in my case), the N1195-C1197 bond is threaded through the ring of a symmetry copy of TYR415. Running a simulation with such a feature tends to lead to one of two things: an explosion, or a stable-but-very-wrong arrangement with the ring stretched around an overly-long bond.

As an aside, this loop and its neighbouring loops suffer from some very severe geometry errors (in particular a lot of _cis_ and twisted peptide bonds) that are unlikely to be self-correcting in simulation. I'd suggest doing a bit of remediation before going anywhere with this model.
