### ISSUE TITLE
CUDA 10.1 not found when running the instalation test for openMM10

### ISSUE THREAD

**Issue by Kykih001** [openmm/openmm#2292]
Hi all,
I am trying to install openMM and run it on our NVIDIA 2080 GPU. I am fairly new to Linux so any help you can give is appreciated. On our machine we have Cuda compilation tools, release 10.1, V10.1.105. CUDA is installed under the /home/labuser directory, so not in its original root. OpenMM was install in anaconda using:
conda install -c omnia -c conda-forge openmm
conda install -c omnia/label/cuda100 -c conda-forge openmm
Then the installation was checked using:
python -m simtk.testInstallation
When running this command the following message appears:
There are 3 Platforms available:

1 Reference - Successfully computed forces
2 CPU - Successfully computed forces
3 OpenCL - Successfully computed forces

Median difference in forces between platforms:

Reference vs. CPU: 6.29846e-06
Reference vs. OpenCL: 6.75426e-06
CPU vs. OpenCL: 8.07471e-07

investigating further using:
python -c "import simtk.openmm; print(simtk.openmm.Platform.getPluginLoadFailures())"

The following message appears:
('Error loading library /home/dderedge/anaconda3/envs/openMM/lib/plugins/libOpenMMCUDA.so: libcufft.so.10.0: cannot open shared object file: No such file or directory', 'Error loading library /home/dderedge/anaconda3/envs/openMM/lib/plugins/libOpenMMRPMDCUDA.so: libOpenMMCUDA.so: cannot open shared object file: No such file or directory', 'Error loading library /home/dderedge/anaconda3/envs/openMM/lib/plugins/libOpenMMDrudeCUDA.so: libOpenMMCUDA.so: cannot open shared object file: No such file or directory', 'Error loading library /home/dderedge/anaconda3/envs/openMM/lib/plugins/libOpenMMAmoebaCUDA.so: libOpenMMCUDA.so: cannot open shared object file: No such file or directory', 'Error loading library /home/dderedge/anaconda3/envs/openMM/lib/plugins/libOpenMMCudaCompiler.so: libnvrtc.so.10.0: cannot open shared object file: No such file or directory')

The /bashrc file used to activate the CUDA has these added lines:
export PATH=/home/labuser/cuda-10.1/bin:$PATH
export PATH=/home/dderedge/cuda-10.1/bin:$PATH
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/home/dderedge/anaconda3/lib/plugins

How do I get openMM to utilize and recognize our GPU.
Thank you

**Comment by jchodera** [comment]
We haven't yet build a conda package for CUDA 10.1 yet. Any chance you have CUDA 10.0 installed and could use that?

**Comment by Kykih001** [comment]
Ahh, sorry for such a simple error. That fixed it.
Thank you
