### ISSUE TITLE
Integration between OpenMM and the Open Force Field Initiative

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#2293]
This thread is for brainstorming ways in which we can find synergies between OpenMM and the Open Force Field Initiative.

cc: @j-wags @davidlmobley @andrrizzi @simonboothroyd

The [Open Force Field Initiative](https://openforcefield.org/) is getting close to a first release containing a new set of Python object models for [molecules and system topologies](https://open-forcefield-toolkit.readthedocs.io/en/topology/topology.html), at which point we're looking for feedback on how the APIs could be made more useful. Ultimately, these objects will power the [Open Force Field Toolkit](https://open-forcefield-toolkit.readthedocs.io/en/topology/) used to assign [SMIRNOFF](https://open-forcefield-toolkit.readthedocs.io/en/topology/smirnoff.html) parameters, but since they represent an open source object model that can bridge between cheminformatics toolkits like [the RDKit](http://www.rdkit.org/) and [OpenEye](https://www.eyesopen.com/) that we are committing to install via `conda`, they may also be a good candidate for support in OpenMM's Python layer.

Some thoughts:
* **Serializable objects:** One drawback of many of the objects in the `simtk.openmm.app` layer is that they are not serializable, which causes headaches for using them for distributed computing or storing them to disk. The object models developed by the OFFI are intended to be serializable.
* **Topology objects with chemical information:** OpenMM's [`Topology`](http://docs.openmm.org/latest/api-python/generated/simtk.openmm.app.topology.Topology.html#simtk.openmm.app.topology.Topology) object does not store sufficient information about small molecules to allow them to be reconstituted as chemical objects in the [RDKit](http://www.rdkit.org/) and [OpenEye](https://www.eyesopen.com/) toolkits, causing huge headaches for parameterizing small molecules. The OFFI [`Topology`](https://open-forcefield-toolkit.readthedocs.io/en/topology/api/generated/openforcefield.topology.Topology.html#openforcefield.topology.Topology) object contains one or more [`Molecule`](https://open-forcefield-toolkit.readthedocs.io/en/topology/api/generated/openforcefield.topology.Molecule.html#openforcefield.topology.Molecule) objects that preserve this information so that we can subsequently apply SMIRNOFF (or even GAFF) parameters to small molecules. We could envision a new version of the OpenMM [`ForceField`](http://docs.openmm.org/latest/api-python/generated/simtk.openmm.app.forcefield.ForceField.html#simtk.openmm.app.forcefield.ForceField) object that uses the OFFI `Topology`, or once we are able to automatically convert force fields to SMIRNOFF format, perhaps using the `openforcefield` toolkit altogether.
* **System object models:** The `openforcefield` toolkit uses the force fields specified with the [SMIRNOFF](https://open-forcefield-toolkit.readthedocs.io/en/topology/smirnoff.html) spec (which isn't necessarily tied to one format---the object model will be the focus going forward) to generate an object model of a parameterized `System` using OpenMM's `Force` objects. Essentially, the OpenMM `System` object is being used as a container object and then converted for use with other packages (currently via `parmed`) if desired. This is highly flexible, but creates some awkwardness: (1) OpenMM has some `Force` objects that don't cleanly match the notion of separating conceptually distinct potential energy terms (e.g. [`NonbondedForce`](http://docs.openmm.org/latest/api-python/generated/simtk.openmm.openmm.NonbondedForce.html#simtk.openmm.openmm.NonbondedForce)), and (2) `parmed` has an AMBER-centric view of potential energy functions, making it unsuitable for growing to support the broad variety of functional forms we would like to explore in the future. It's possible that there is significant benefit in synchronizing the OFFI concept of conceptually distinct forces with a pure Python object model of a `System` that could be rendered to an OpenMM `Context` under the hood.
* **ML force field components:** Both OpenMM and OFFI are interested in exploring ML components of force fields (such as [ANI-1](https://pubs.rsc.org/en/content/articlelanding/2017/sc/c6sc05720a#!divAbstract)-like models for representing valence terms combined with long-range dispersion and electrostatics treatments), so there may be significant benefit in synchronizing how these ML models might be represented in object models or in serialized form.
* **Standard support for next-generation potentials:** The OFFI has a long-term interest in ensuring multiple simulation packages support next-generation potential functions, such as the Lepton-like expressions (in addition to ML models), as well as standardizing how these packages accept force field parameters. There is likely mutual interest in working toward a standard convenient representation for these.

**Comment by peastman** [comment]
`System` was never designed to be an interchange format.  It was created as an endpoint, the description of precisely how to compute the forces using the features of OpenMM.  So I'd suggest having a different class to represent a parametrized system in a platform independent way.  That could be done by adapting the classes from ParmEd (which was designed to be an interchange format), or by creating a completely new representation.  That class would then have the ability to generate the appropriate representations for different simulation packages, of which OpenMM systems would be one.

The difficulty here  is how widely it can be supported.  There are so many functional forms that currently can only be used in OpenMM, not in any other simulation package.  So if you want to create force fields that aren't OpenMM-specific, you'll need to get buy-in from other packages to define a common set of features that everyone commits to support.

ML based force fields have a similar problem.  I surveyed a bunch of existing ones looking for a common architecture, but didn't find anything.  People are proposing all sorts of ideas that work in very different ways.  Until that settles down and we get a clearer idea of what works best, it's hard to propose a representation that's less general than "an arbitrary compute graph taking positions as inputs and producing forces as outputs".

**Comment by jchodera** [comment]
> System was never designed to be an interchange format. It was created as an endpoint, the description of precisely how to compute the forces using the features of OpenMM. 

`System` is an object model for representing how to compute the potential energy for a system given all the dynamical variables (positions, box vectors, etc), and OpenMM was designed to be flexible and forcefield agnostic. In that sense, it was a reasonable choice.

> So I'd suggest having a different class to represent a parametrized system in a platform independent way. That could be done by adapting the classes from ParmEd (which was designed to be an interchange format), 

ParmEd was *not* designed to be an interchange format---it was simply an object model for representing what AMBER stores in a `prmtop` file, augmented by structural information and later extended to accommodate some aspects of CHARMM and other force fields. It does not contain sufficient information to actually compute the potential given the dynamical parameters because many choices that affect the potential energy---such as nonbonded treatment---are omitted from the object model. In that sense, the OpenMM `System` object was far closer to what we needed.

> or by creating a completely new representation. That class would then have the ability to generate the appropriate representations for different simulation packages, of which OpenMM systems would be one.

This is very likely the route we'll take. The closest existing tool is [InterMol](https://github.com/shirtsgroup/InterMol), which uses an object model that is conceptually similar to OpenMM. But it's likely that we will want to agree on an intermediate object model representing a parameterized system that is conceptually close to how [SMIRNOFF](https://open-forcefield-toolkit.readthedocs.io/en/topology/smirnoff.html) distinguishes force field terms.

**Comment by jchodera** [comment]
FYI, we've just released the [Open Force Field Toolkit 0.2.0](https://openforcefield.org/news/openforcefield-toolkit-0.2-release/), which introduces these new [molecular topology objects](https://open-forcefield-toolkit.readthedocs.io/en/latest/topology.html) that could eventually be useful for OpenMM's "app" layer.

**Comment by jchodera** [comment]
Update: We've released a residue template generator that supports SMIRNOFF force fields here: http://github.com/openmm/openmm-forcefields
