### ISSUE TITLE
simtk.version.version may be incorrect

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#2295]
I've just noticed that the latest [`omnia-dev` nightly conda builds](https://anaconda.org/omnia-dev/openmm/file) have the wrong `openmm.version.version`:
```
# THIS FILE IS GENERATED FROM OPENMM SETUP.PY
short_version = '7.3.0'
version = '7.3.0'
full_version = '7.3.0.dev-a4dec7b'
git_revision = 'a4dec7b9d5161f3f597e6928468dcbd2c1baec73'
release = False
openmm_library_path = r'/opt/anaconda1anaconda2anaconda3/lib'

if not release:
    version = full_version
```
I'm not quite sure how this is happening.

The recipe is here:
https://github.com/omnia-md/conda-dev-recipes

**Comment by peastman** [comment]
The version number is set here:

https://github.com/pandegroup/openmm/blob/master/CMakeLists.txt#L159-L161

We updated the build number to 7.3.1 on the 7.3 branch, but not on the master branch.

**Comment by jchodera** [comment]
Would it be OK if we updated this to 7.4.0 for now, so that the version numbers are in sync with the conda recipe? This is just a handy bookkeeping thing to allow us to check which versions are installed.

The more worrying thing is the git revision---where does that get pulled in?

**Comment by peastman** [comment]
> Would it be OK if we updated this to 7.4.0 for now

Sure.

> The more worrying thing is the git revision---where does that get pulled in?

CMake looks it up as part of building the Python API.  https://github.com/pandegroup/openmm/blob/master/wrappers/python/CMakeLists.txt#L26-L40

**Comment by jchodera** [comment]
Can you clarify whether CMake looks up the git tag corresponding to the release label (eg 7.3.0, which would fail for 7.4.0) or the _current_ git tag checked out? If the former, is there a way we can have it use the current git tag or look up the git hash of the current master?

**Comment by peastman** [comment]
It looks up the revision that's checked out,  You can see this from the example above, which you posted on April 3.  From https://github.com/pandegroup/openmm/commits/master you can see the listed revision was in fact the current revision on that day.
