### ISSUE TITLE
OpenMM bundle for ChimeraX

### ISSUE THREAD

**Issue by tristanic** [openmm/openmm#2333]
I'd like to start building OpenMM into a bundle for the ChimeraX ToolShed (essentially a wheel repository akin to the PyPI). Mainly to make it easier to keep OpenMM up to date (currently builds from Conda are pre-baked into the ChimeraX distribution, and only intermittently updated), but hopefully to eventually enable builds specific to different Linux flavours. ChimeraX currently builds and distributes for CentOS 7 (GCC 4.9, but compatible with the 4.8 runtime), Ubuntu 16.04 (GCC 5.4), Ubuntu 18.04 (GCC 6.3) and "Generic Linux" (GCC 4.9, **not** backward-compatible to the 4.8 runtime). Since my ISOLDE code uses the C++ APIs of both ChimeraX and OpenMM (albeit not within the same compiled library... yet, at least), this would be the only way for me to support the Ubuntu builds without some horrible dual-compiler building arrangement.

I envision this as only a very lightweight wrapping around the existing build system (really just a small amount of Python code telling other bundles where to find the headers and libraries, etc.). Seems only polite to ask you if you'd like to be actively involved.

**Comment by peastman** [comment]
Thanks for asking.  I'm not familiar with ChimeraX ToolShed.  I found the website at https://cxtoolshed.rbvi.ucsf.edu/, but it doesn't actually give any information about what it is.  Could you give some background?  What exactly would you be creating, and how would it be used?

**Comment by tristanic** [comment]
Sorry, yes - I should have said. The guide to building ChimeraX plugins is at http://www.rbvi.ucsf.edu/chimerax/docs/devel/writing_bundles.html. The ToolShed itself is like ChimeraX’s own PyPI: a server where third parties can upload extensions for users to install into their local ChimeraX. When the ToolShed website is accessed from within ChimeraX, the “Download” button becomes an “Install” button if there is a bundle release matching all platform and version requirements. If a bundle lists another bundle as a dependency, the second bundle will be automatically fetched and installed as part of the installation of the first.

As for what it would be used for: I personally need it as the basis for interactive MD-based model rebuilding/refinement in ISOLDE (https://isolde.cimr.cam.ac.uk). Tom Goddard has been working on a tool for interactive creation and visualisation of the effects of point mutations in binding sites. With a little work it could also make for a nice environment for general simulation preparation and trajectory analysis.

**Comment by peastman** [comment]
Got it.  Questions of this sort come up from time to time about adding other distribution mechanisms.  My main concern is always whether the person setting it up is making a long term commitment to support and maintain it.  My concern is that you'll create this new package, but then you'll move on to other things and you won't keep updating it with new OpenMM versions.  And then several years from now people will still be using it and installing a long out of date version.

**Comment by tristanic** [comment]
I understand your concern, but I'm certainly not planning on going away any time soon! ISOLDE's my full-time baby, and I'm working very hard on turning it into a workhorse tool for the structural biology community. It's in my best interests to ensure that it's always using the newest features of OpenMM. My current position is funded through to 2022, and my aim is to find an ongoing academic position focused around further development in this space.

Once ChimeraX passes version 1.0 (probably around the end of this year), the developers have promised to maintain backward compatibility in their API from that point on. When that happens it should be really straightforward to set up automated builds on Travis, so staying up to date would no longer be a serious problem.

**Comment by peastman** [comment]
Ok.  As long as you're supporting and maintaining it, it's alright with me.

**Comment by tristanic** [comment]
OK, thanks. I'll start discussing in earnest with the ChimeraX team. A few minor framework issues to get out of the way first (in particular, the ToolShed currently only allows bundles to be installed under the 'chimerax' directory which would break all OpenMM's imports). To start with I can probably pull and repackage the conda builds from conda-dev, but longer-term it would be ideal to be running automated builds from source. Are the conda build recipes publicly available somewhere? Seems like they'd be a solid starting point.

**Comment by peastman** [comment]
They're in https://github.com/omnia-md/conda-recipes-cuda/

**Comment by tristanic** [comment]
Thanks!
