### ISSUE TITLE
Martini support in OpenMM

### ISSUE THREAD

**Issue by mrinal-shekhar** [openmm/openmm#2335]
Hello
I was wondering if there is a martini support on OpenMM and if so, is there a tutorial on how to use it 
Mrinal

**Comment by peastman** [comment]
OpenMM doesn't have built in support for it.  It's possible that if you use CHARMM-GUI to build a martini system that OpenMM will be able to read it.  I'm not sure how they handle it.

**Comment by cing** [comment]
Mrinal did you see this project by @jlmaccal? Justin, perhaps you can comment about the status of this code, https://github.com/smgusing/openmmMartini

**Comment by mrinal-shekhar** [comment]
@cing I saw this and was wondering if there are any examples on the martini usage.
