### ISSUE TITLE
Cl radius in app Generalized Born implementations

### ISSUE THREAD

**Issue by kentgorday** [openmm/openmm#2339]
In a typo that seems to be inherited from ParmEd (ParmEd/ParmEd#1053), the radius for chlorine under Bondi/mBondi/mBondi2 is neither the actual Bondi value (1.75 Å), nor the value used in leap (1.7 in unitio.c). I am not sure which would make more sense here, and whether there is any motivation for the leap value or if it is itself a typo. It would not make sense for it to have been changed for neck parameter lookup, as these are tabulated exactly for both 1.7 and 1.75.

https://github.com/pandegroup/openmm/blob/b9a1bee/wrappers/python/simtk/openmm/app/internal/customgbforces.py#L253

**Comment by peastman** [comment]
@swails what's the correct value we should use here?

**Comment by swails** [comment]
1.7 is the correct value

**Comment by peastman** [comment]
Just want to confirm before I fix this.  Looking at the values in ParmEd (https://github.com/ParmEd/ParmEd/blob/master/parmed/tools/changeradii.py) it has 1.7 for Bondi, but 1.5 for mBondi and mBondi2.  Is that correct?  Or is it really supposed to be 1.7 in all cases?

**Comment by swails** [comment]
Crap, it's supposed to be 1.7 everywhere according to tleap.

I'll fix ParmEd as well.

**Comment by peastman** [comment]
Ok, thanks!
