### ISSUE TITLE
Trouble (manually) setting up system with constrained bonds

### ISSUE THREAD

**Issue by EqualAPriori** [openmm/openmm#2370]
I've been trying to use OpenMM to run some coarse-grained simulations (coming from lammps world) with custom soft potentials, and as such have been setting up the topology manually. So far, things have been working well when I use harmonic bonds.

However, when I tried rigid bonds by adding constraints manually, the system has trouble running -- applying constraints and trying to minimize the structure before hand produces structures where the positions blow up, and not applying constraints beforehand leads to simulations that quickly become NAN. 

I'm attaching a minimal example based off of a 4-bead molecule. I've isolated the problem to the 15th molecule in the coordinates. My periodic box length is L=12.92482, so the imaged bond length is correct, but the pre-imaged bond length is not. It would seem like there's something I don't understand about the periodic imaging in openMM. What's confusing is that the same initial trajectory works when using harmonic bonds, but not for the constrained bonds.

An example nonbonded interaction is included but I've set the coefficients to zero so they don't contribute to the potential energy in this script. The coordinates are obtained by reading in coordinates using mdtraj, so please ignore the extraneous 'VS' labels in the pdb file -- those were assigned by mdtraj when it created the pdb files, and aren't used when loading. I've also checked that all the bonds were in good shape (pretty close to the specified bond constraint) in the initial structures.

Thanks again for the help!
[ConstrainedBondTestClean.zip](https://github.com/openmm/openmm/files/3503172/ConstrainedBondTestClean.zip)

**Comment by peastman** [comment]
I think there's a file missing from the zip.  It's looking for `mappedto4.pdb`, which isn't there.

**Comment by EqualAPriori** [comment]
Apologies for that! I'm attaching a modified script -- it was supposed to point to mappedto4_15mol.(lammpstrj/pdb) instead of mappedto4.(lammpstrj/pdb)

[ConstrainedBondTestClean.zip](https://github.com/openmm/openmm/files/3503607/ConstrainedBondTestClean.zip)

**Comment by peastman** [comment]
Thanks!  I can reproduce the nan energy.  Investigating...

**Comment by EqualAPriori** [comment]
Thanks for helping! In case it wasn't clear above, setting the
"runProblematicExample = False" flag will run the 14-molecule case, which
should run fine.

**Comment by peastman** [comment]
Here's your problem:

```
ATOM     71 A1     A O   1      -6.456  -3.315   2.288  1.00  0.00          VS  
ATOM     72 A1     A O   1       6.095  -3.132   1.938  1.00  0.00          VS  
ATOM     73 A1     A O   1       5.799  -3.589   1.852  1.00  0.00          VS  
ATOM     74 A      A O   1       5.205  -3.578   1.607  1.00  0.00          VS  
```

Notice the negative sign in front of the x coordinate for atom 71?  Atoms 71 and 72 are about 12A apart, which causes it to become very unhappy when it tries to enforce the constraints!  (Constraints don't consider periodic boundary conditions.  It expects all the atoms in a molecule to be kept together.)  MDTraj has a [make_molecules_whole()](http://mdtraj.org/development/api/generated/mdtraj.Trajectory.html#mdtraj.Trajectory.make_molecules_whole) function that's an easy way of fixing this.

**Comment by EqualAPriori** [comment]
Ah, thank you! MDTraj's make_molecules_whole() did the trick.

To help me understand what's under the hood: is it true that harmonic bonds
do consider periodic conditions, and hence they were able to deal with this
un-whole molecule without issue?

Many thanks, again!

**Comment by peastman** [comment]
No, bonded forces don't consider periodic boundary conditions either.  By default, anyway.  You can call `setUsesPeriodicBoundaryConditions(True)` on most bonded forces, but that's only used in unusual situations.  Probably the energy minimizer was managing to fix the stretched bond.

**Comment by EqualAPriori** [comment]
Ah, thank you very much for the insight. Closing now.
