### ISSUE TITLE
Create FAQ

### ISSUE THREAD

**Issue by peastman** [openmm/openmm#2372]
I'm thinking about creating a new FAQ page.  The closest we have right now is the (quite out of date) troubleshooting page at https://simtk.org/plugins/moinmoin/openmm/FAQApp, but I'm thinking about something much more detailed and thorough.  There are a few general classes of questions that come up a lot, so I want to write up something that will give a very complete discussion of them.  Here are the particular topics I have in mind:

- How periodic boundary conditions work.  (Questions like, "Why are water molecules diffusing away from the periodic box?" or, "Why is my protein sticking out beyond the edge of the water box?")
- Template not found errors.  (What they mean and how to diagnose them.)
- Coordinates or energy being NaN.

Any other subjects that would be good to include?

**Comment by peastman** [comment]
Here's an initial draft: https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions

**Comment by jchodera** [comment]
Great idea!

Should the FAQ be wiki-based, or within the repo, or available on the openmm.org website?

**Comment by jchodera** [comment]
This is a good start! 

Some quick comments:
* "How does OpenMM handle periodic boundary conditions?" might be a better title for the first question
* Maybe we can break it up into categories, like "OpenMM implementation details" vs "Common errors"?

Here's an idea: What if we added a GitHub issue label "FAQ" that we could use to tag issues (open or closed) that would be good candidates for inclusion the FAQ? That way, we can all pitch in to annotate things that come up over and over again that would be good ideas to include in the FAQ.

**Comment by peastman** [comment]
> Maybe we can break it up into categories, like "OpenMM implementation details" vs "Common errors"?

Since there's only three questions right now, I don't think we need to divide them into categories.  As the number of questions grows, we can add organization as necessary.  Any suggestions for other questions to add?

I'd like to add a link to this on the website, but I can't do that until https://github.com/pandegroup/openmm-org/issues/28 is fixed.  Just a reminder!
