### ISSUE TITLE
1-2 / 1-3 nonbonded interactions when creating system using PSF

### ISSUE THREAD

**Issue by charmm-gui** [openmm/openmm#2379]
Dear OpenMM developers,

I have an issue related to the 1-2 and 1-3 nonbonded interaction exclusion.
When creating system using the createSystem function in CharmmPsfFile class, nonbonded interactions for 1-2 and 1-3 are always turned off.

https://github.com/openmm/openmm/blob/b71e92d9ccef7c98cfd6b862eb34095d94fa1b05/wrappers/python/simtk/openmm/app/charmmpsffile.py#L1370-L1385

However, these interactions are needed for coarse-grained system simulation.
I may be able to turn on the 1-2 and 1-3 interactions by setting charge, sigma, and epsilon values using setExceptionParameters function, but this method cannot be applied when the system contains any NBFIX pairs.

When the system contains NBFIX pairs, every 1-2 and 1-3 nonbonded interactions are added into the exclusion list in CustomNonbondedForce class.

https://github.com/openmm/openmm/blob/b71e92d9ccef7c98cfd6b862eb34095d94fa1b05/wrappers/python/simtk/openmm/app/charmmpsffile.py#L1443-L1446

Problem is that I could not find any function can remove items in the exclusion list.
Would it be possible to implement an option to include 1-2 / 1-3 nonbonded interactions?

**Comment by peastman** [comment]
Yes, that would be a very good feature to add.  I assume the PSF file has some way of indicating whether 1-2 and 1-3 pairs should be excluded?  How is that specified?

**Comment by charmm-gui** [comment]
No, including 1-2 and 1-3 nonbonded interaction is per program feature, i.e. it is configuration option for most MD programs as I know.

**Comment by charmm-gui** [comment]
Or, I would be also good to add some removing function for Exception in NonbondedForce class and Exclusion in CustomNonbondedForce class.

**Comment by peastman** [comment]
According to the documentation at https://www.charmm.org/charmm/documentation/by-version/c42b1/params/doc/nbonds/, it's specified in the file using the NBXMod option.  Here's the relevant section.

```
By default, vdw and electrostatic interactions between two bonded
1-2 interactions) and two atoms bonded to a common atom (1-3 interactions)
atoms are excluded from the calculation of energy and forces. Also,
special vdw parameters and an electrostatic scale factor (E14FAC) can be
applied to atom pairs separated by 3 bonds (1-4 interactions). The
control of the exclusion list is by the integer variable, NBXMod.

NBXMod = 0 Preserve the existing exclusion lists
NBXMod = +/- 1 Add nothing to the exclusion list
NBXMod = +/- 2 Add only 1-2 (bond) interactions
NBXMod = +/- 3 Add 1-2 and 1-3 (bond and angle)
NBXMod = +/- 4 Add 1-2 1-3 and 1-4'S
NBXMod = +/- 5 Add 1-2 1-3 and special 1-4 interactions

A positive NBXMod value causes the explicit exclusions in the PSF (inb array)
to be added to the exclusion list. A negative value causes the use of only
the bond connectivity data to construct the exclusion list (thus, ignoring
the PSF data).
```

**Comment by charmm-gui** [comment]
NBXMod option is to read exclusion data from PSF, but not write to PSF.
But since there is an option to read exclusion data from PSF, PSF can have exclusion list?
Unfortunately, I could not find any CHARMM commend for this...

**Comment by peastman** [comment]
I don't understand what you mean by that.  That option would typically be specified as part of the force field definition.

**Comment by charmm-gui** [comment]
Let me correct something.
With NBXMod, I could see the difference in energy, which means the new exclusion list is constructed.
However, this new exclusion list is not written in PSF when I tried to generate the new PSF after applying NBXMod.

**Comment by peastman** [comment]
This has nothing to do with writing PSF files.  They don't contain an explicit list of exclusions.  This is just a single option that appears in one of the files defining the force field.  For example, `par_all36_prot.prm` contains the following.

```
NONBONDED nbxmod  5 atom cdiel fshift vatom vdistance vfswitch -
cutnb 14.0 ctofnb 12.0 ctonnb 10.0 eps 1.0 e14fac 1.0 wmin 1.5 
```

Since it says `nbxmod  5`, that means to exclude all 1-2 and 1-3 interactions, and use scaled versions of 1-4 interactions.

Currently `CharmmPsfFile.createSystem()` doesn't look for that option.  It assumes mode 5, which is used in most standard force fields.  But it would be useful to make it handle other modes properly to support other cases, such as coarse grained force fields.

**Comment by charmm-gui** [comment]
Actually, NNB in the PSF is the explicit list of exclusions, although it is always 0 in the CHARMM generated PSF file.
For NONBONDED in the parameter files, yes, you are correct.
NBXmod in parameter file is indicating the default nonbonded interaction exclusion treatment for the atom types in the file.

Actually, I was talking about "nbond" command in CHARMM, which regenerates the nonbonded list and exclusion list (with NBXmod option).

Anyway, if you want to make OpenMM to read NBXmod in the parameter files, NBXmod information should be stored for each atom type (as there is NONBONDED command in every parameter files).
In this way, OpenMM can handle complex system containing both coarse-grained and united atom model (such as PACE-CG).

Actually, what I wanted is simply adding an argument in CharmmPsfFile.createSystem() (or adding removing function), but I also like your idea.

**Comment by charmm-gui** [comment]
Sorry, not sure about this part.

> Anyway, if you want to make OpenMM to read NBXmod in the parameter files, NBXmod information should be stored for each atom type (as there is NONBONDED command in every parameter files).
In this way, OpenMM can handle complex system containing both coarse-grained and united atom model (such as PACE-CG).

CHARMM may use the NONBONDED options of the last parameter file read.

**Comment by charmm-gui** [comment]
I confirmed that CHARMM uses the NONBONDED options of the last parameter file read.
I think, you can follow the same approach.
For PACE-CG (mixing coarse-grained and united atoms), all the nonbonded interaction pairs are listed in the NBFIX.

**Comment by wonpil** [comment]
Peter, how things are going? Thanks!

**Comment by peastman** [comment]
I'm looking into implementing this.  Can you provide a test case for it?  A fairly small, simple system that uses your coarse grained force field.  I'll add a test that verifies OpenMM produces the same energy as CHARMM for it.

**Comment by peastman** [comment]
@wonpil could you explain the differences between modes -1, 0, and 1?  I'm not sure what the difference is supposed to be between "Preserve the existing exclusion lists" and "Add nothing to the exclusion list".

**Comment by wonpil** [comment]
Not clear what their differences are. For now, we can ignore them.

**Comment by peastman** [comment]
I'm trying to create some test cases myself, but I've never used CHARMM before and the documentation is a bit overwhelming.  Given that I have three files (psf, rtf, par), I want to compute the potential energy.  I assume there's a simple way to do this, but I don't know what it is.  Can someone provide a script that does it?

**Comment by charmm-gui** [comment]
Test case is attached.

[testcase.tar.gz](https://github.com/openmm/openmm/files/3576296/testcase.tar.gz)

**Comment by peastman** [comment]
Thanks!  And it looks like your `input.inp` is exactly the script I needed.

**Comment by peastman** [comment]
I still can't get it to work.  I'm trying to read in some of the standard test files we have in https://github.com/openmm/openmm/tree/master/wrappers/python/tests/systems.  Here's the script I'm using.

```
! protein topology and parameter
open read card unit 10 name charmm22.rtf
read  rtf card unit 10

open read card unit 20 name charmm22.par
read para card unit 20 flex

! read PSF and CRD
open read unit 10 card name ala_ala_ala.psf
read psf  unit 10 card

open read card unit 10 name ala_ala_ala.pdb
read coor pdb unit 10 card

NONBONDED nbxmod  5 atom cdiel shift vatom vdistance vswitch -
cutnb 14.0 ctofnb 12.0 ctonnb 10.0 eps 1.0 e14fac 1.0 wmin 1.5 
ENERGY

stop
```

It produces many pages of error messages that look similar to

```
 PARRDR> WARNING: ATOMS IN BOND NH2  CT1   240.00000   1.45500 DONT EXIST
 PARRDR> WARNING: ATOMS IN BOND CST  OST   937.96000   1.16000 DONT EXIST
 PARRDR> WARNING: ATOMS IN BOND SS   FE    250.00000   2.32000 DONT EXIST
```

then exits with a fatal error

```
At line 1708 of file /Users/peastman/charmm/build/cmake/coorio.F90
Fortran runtime error: Bad value during integer read
```

What am I doing wrong?

**Comment by peastman** [comment]
Finally managed to get it working.  Remove `flex` when loading the par file, remove `card` when reading the pdb file, and change `NONBONDED` to `NBOND`.

**Comment by charmm-gui** [comment]
Note that NONBONDED and NBOND are different thing.
NONBONDED is only allowed inside the parameter file, setting default nonbonded option for a given FF.
NBOND is CHARMM command to regenerate nonbonded list and exclusion list.

**Comment by peastman** [comment]
@charmm-gui @wonpil Could one or both of you check out #2381 and verify that I fixed the problem correctly?

**Comment by wonpil** [comment]
It works well within our tests. Thanks!

**Comment by peastman** [comment]
Thank you!
