### ISSUE TITLE
setPositions incompatible with old numpy

### ISSUE THREAD

**Issue by dwhswenson** [openmm/openmm#2385]
In OpenMM 7.4, `setPositions` does not work with numpy 1.12.1, but the conda installation allows the old version. (This is probably an issue for the repo with the conda recipe, but (1), I'm not sure which that is, and (2) if anyone else has this problem, they're more likely to find it here.) I'm guessing this is related to changes in #2305, based on a glance at recent PRs.

This issue pops up in OpenPathSampling tests running Python [2.7](https://travis-ci.org/openpathsampling/openpathsampling/jobs/583133397) and [3.6](https://travis-ci.org/openpathsampling/openpathsampling/jobs/583133398) on Travis (and on a GitLab-CI server with a miniconda docker in [2.7](https://gitlab.e-cam2020.eu/dwhswenson/ops_additional_examples/-/jobs/11296)). Travis with [3.7](https://travis-ci.org/openpathsampling/openpathsampling/jobs/583133399) is fine. (I'm not sure which of our dependencies is preferring an older version of numpy in older Pythons; that's my next thing to track down).

Here's a quick test script:

```python
from __future__ import print_function
from simtk import openmm as mm
import numpy as np
from simtk import unit as u
import openmmtools

print("OpenMM: ", mm.version.version)
print("Numpy: ", np.version.version)
print("OpenMMTools: ", openmmtools.version.version)

testsys = openmmtools.testsystems.AlanineDipeptideVacuum()
integ = mm.LangevinIntegrator(300*u.kelvin, 1.0/u.picosecond, 1.0*u.femtosecond)
sim = mm.app.Simulation(testsys.topology, testsys.system, integ)

sim.context.setPositions(testsys.positions)

print("Success!")
```

By playing with my environment, I get the following (an old `openmmtools` because this first occurred in the 2.7 GitLab, and so I made a 2.7 environment):

```
OpenMM:  7.4.0.dev-b71e92d
Numpy:  1.16.4
OpenMMTools:  0.16.0
Success!
```

```
OpenMM:  7.3.1.dev-4a269c0
Numpy:  1.12.1
OpenMMTools:  0.16.0
Success!
```

```
OpenMM:  7.4.0.dev-b71e92d
Numpy:  1.12.1
OpenMMTools:  0.16.0
Traceback (most recent call last):
  File "setpositions.py", line 15, in <module>
    sim.context.setPositions(testsys.positions)
  File "/Users/dwhs/miniconda3/envs/openmm74/lib/python2.7/site-packages/simtk/openmm/openmm.py", line 5987, in setPositions
    return _openmm.Context_setPositions(self, positions)
ValueError: in method Context_setPositions, argument 2 could not be converted to type std::vector< Vec3,std::allocator< Vec3 > > const &
```

I went ahead and tried other numpy versions; 1.13.3 fails but 1.14.6 passes.

**Comment by peastman** [comment]
Yes, I think you're right that's the reason.  Something must be different in the older version that prevents swig from doing the conversion.  It sounds like the solution would be to add a constraint in the recipe to require numpy>=1.14?

**Comment by jchodera** [comment]
Pinning `numpy >=1.14` sounds reasonable! `numpy 1.14` was released on `conda-forge` 1.5 years ago, so should be pretty stable.

**Comment by peastman** [comment]
Since you're already working on the conda-forge packages, it probably makes sense to just fix it there.

**Comment by dwhswenson** [comment]
This is what I would think is the most reasonable solution. This also fits with [under-discussion NEP29](https://numpy.org/neps/nep-0029-deprecation_policy.html), which proposes Python/NumPy version support for the NumPy user community.

The one caveat is that it will be impossible to conda-install both OpenMM 7.4 and MSMBuilder. I hoping that they'll do a new build soon. (https://github.com/msmbuilder/msmbuilder/issues/1126)

**Comment by jchodera** [comment]
> Since you're already working on the conda-forge packages, it probably makes sense to just fix it there.

Is there a reason _not_ to fix it in the official omnia release channel?

**Comment by jchodera** [comment]
You've already committed us to fully supporting the omnia release of 7.4.0 throughout its lifecycle, @peastman. I don't see how we can punt on this.

**Comment by jchodera** [comment]
> The one caveat is that it will be impossible to conda-install both OpenMM 7.4 and MSMBuilder. I hoping that they'll do a new build soon. (msmbuilder/msmbuilder#1126)

Is anyone actively supporting msmbuilder?

**Comment by dwhswenson** [comment]
> Is anyone actively supporting msmbuilder?

There have been maintenance commits, and there's some activity in issues. But I'm likely to deprecate OPS's `MSMBuilderFeaturizerCV` anyway. I don't think anyone has ever used actually used it -- from what I know, most people use `MDTrajFunctionCV`s or wrap custom functions.

**Comment by peastman** [comment]
> Is there a reason not to fix it in the official omnia release channel?

Just that it would be extra work and would likely have minimal benefit.  It remains to be seen how many people will encounter this, but it's likely to be small, and once the conda-forge package is posted the number should get even smaller.  And for anyone who does encounter it, there's an easy workaround.

**Comment by peastman** [comment]
I've been thinking about this more, and I'm starting to have doubts about this solution.  Conda should always install the most recent version of numpy unless some package explicitly requests an earlier version.  But if OpenMM requires numpy>=1.14, and you have another package that requires an earlier version, you'll get a conflict and it won't let you install OpenMM at all.  Perhaps the first thing we need to do is track down what package in your environment in making it use the old numpy version?

(Can I mention how much I've come to detest conda?  It's the most broken excuse for a package manager I've ever used.  For example, I just told it to upgrade tensorflow-gpu from 1.13 to 1.14, and it decided that meant it should uninstall rdkit, scikit-learn, and joblib at the same time.  I run into issues like this on a regular basis.  Sorry, just felt the need to complain to someone!)

**Comment by jchodera** [comment]
> I've been thinking about this more, and I'm starting to have doubts about this solution. Conda should always install the most recent version of numpy unless some package explicitly requests an earlier version. But if OpenMM requires numpy>=1.14, and you have another package that requires an earlier version, you'll get a conflict and it won't let you install OpenMM at all. Perhaps the first thing we need to do is track down what package in your environment in making it use the old numpy version?

I agree that would be optimal if conda could provide more helpful guidance as to what packages are causing the constraints to be unsatisfiable, but that's likely also a hard optimization problem to solve.

> (Can I mention how much I've come to detest conda? It's the most broken excuse for a package manager I've ever used. For example, I just told it to upgrade tensorflow-gpu from 1.13 to 1.14, and it decided that meant it should uninstall rdkit, scikit-learn, and joblib at the same time. I run into issues like this on a regular basis. Sorry, just felt the need to complain to someone!)

Is there a better choice for userspace package management?

**Comment by peastman** [comment]
> Is there a better choice for userspace package management?

For Python?  Not that I know of.  The choices are basically pip and conda.  pip is better written but more limited in what it does.  conda has more features but they're terribly implemented.

**Comment by dwhswenson** [comment]
> But if OpenMM requires numpy>=1.14, and you have another package that requires an earlier version, you'll get a conflict and it won't let you install OpenMM at all. Perhaps the first thing we need to do is track down what package in your environment in making it use the old numpy version?

In my specific case, I tracked down MSMBuilder as the source of the old numpy (sorry, that was implicit in my earlier comment, but not explicit).

Clarification on conda's behavior (where the examples use `msmbuilder` as the old package and let `numpy` 1.16 stand in for `openmm` 7.4 in the examples)

* If you try to install **`old_package` and `openmm=7.4`** you would get an error, with a reasonable error message:
    ```
    $ conda create -n conflict msmbuilder numpy=1.16
    Collecting package metadata: done
    Solving environment: failed
    
    UnsatisfiableError: The following specifications were found to be in conflict:
      - msmbuilder -> numpy=1.12
      - numpy=1.16
    Use "conda search <package> --info" to see the dependencies for each package.
    ```
* If you **had `old_package` in an environment** and then **installed `openmm`**, or if you installed both at once, I believe you'd just get the last compatible version of OpenMM, i.e., 7.3 (can't prove it in this case, since numpy=1.12 is a req for msmbuilder)
* If you **had `old_package` in an environment** and then **installed `openmm=7.4`**, conda would try to remove `old_package`:
    ```
    $ conda create -n msmbuilder -c conda-forge msmbuilder
    [...]
    $ conda activate msmbuilder
    $ conda install numpy=1.16
    [...]
    The following packages will be REMOVED:
    
      msmbuilder-3.8.0-np111py36_0
    
    The following packages will be UPDATED:
    
      numpy                            1.11.3-py36hdf140aa_1207 --> 1.16.4-py36h6b0580a_0
    ```
    Conda assumes that you really *desperately* want whatever you've just requested.

The first case would have caught my problem without me making this issue, and is what I would expect as a user. The second case is annoying for me as a dev (I want my Travis tests to run the latest and greatest OpenMM, not to hold the version back because of MSMBuilder), but seems very reasonable from a user perspective. The last case is the one that I find annoying with conda. It seems that the conda devs actually expect us to *read* all the package plan before accepting it.

**Comment by peastman** [comment]
I'd find the second case pretty bad as a user also.  If you say 'install openmm', you expect to get the latest version!  The user has no idea that MSMBuilder is specifying an old version of numpy, and no idea this is causing them to be forever stuck on old versions of unrelated packages that need a newer numpy.
