### ISSUE TITLE
Update default dev build

### ISSUE THREAD

**Issue by peastman** [openmm/openmm#2389]
In the omnia-dev channel, the CUDA 9.2 build is still the default instead of the CUDA 10.1 build.  Where does that get set?

**Comment by peastman** [comment]
I made the change, but the tests are failing: https://github.com/omnia-md/conda-dev-recipes/pull/172.  The failures don't look related to this change.  AppVeyor gets the error

```
PackagesNotFoundError: The following packages are not available from current channels:
  - conda-build==2.1.17
```

And Travis gets the error

```
UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

  - conda[version='<=4.3.34'] -> python[version='2.7.*,3.4.*,>=2.7,<2.8.0a0,>=3.6,<3.7.0a0']
```

**Comment by jchodera** [comment]
Recall we had the same issue in http://github.com/omnia-md/conda-recipes-cuda. I think you managed to fix it with https://github.com/omnia-md/conda-recipes-cuda/pull/15/files --- the same fix is likely needed here.

**Comment by peastman** [comment]
But hasn't this script (aside from the trivial changes in the PR) been running successfully every night?

**Comment by jchodera** [comment]
Looks like `osx` builds broke five months ago and we didn't notice:
https://anaconda.org/omnia-dev/openmm/files
![image](https://user-images.githubusercontent.com/3656088/64885773-ecbc8f00-d632-11e9-9917-528e62633587.png)

AppVeyor is just for `win`, and we're able to build `win` packages for OpenMM automatically with this repo anyway, so it's safe to ignore AppVeyor issues.

**Comment by jchodera** [comment]
I've run into this before and think it's some sort of weird travis `osx` issue.

I actually changed the whole `osx` build infrastructure in https://github.com/omnia-md/conda-recipes-cuda after noticing the `osx` builds were way out of date and not building with CUDA properly. I think you just need to update this one file:

https://github.com/omnia-md/conda-recipes-cuda/blob/master/devtools/osx-build.sh

**Comment by peastman** [comment]
How should I update it?  I compared the versions of that file in conda-dev-recipes and conda-recipes-cuda and they're very different.  Can I just copy over the one from conda-recipes-cuda?

**Comment by jchodera** [comment]
Yes, I think you should just be able to copy it over!

More generally, the software entropy of maintaining all of these separate build frameworks is why we really need to migrate to conda-forge...

**Comment by peastman** [comment]
And here is how it's failing now.

```
+ python -m simtk.testInstallation

OpenMM Version: 7.4
Git Revision: e26294768fcd85cfdd4939bf002d82ec3770e2cb

There are 3 Platforms available:

1 Reference - Successfully computed forces
2 CPU - Successfully computed forces
python(89066,0x7fff8b58f340) malloc: *** error for object 0x7f8a1fd92598: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
3 OpenCL /Users/travis/anaconda/conda-bld/openmm_1568681613372/test_tmp/run_test.sh: line 3: 89066 Abort trap: 6           python -m simtk.testInstallation
TESTS FAILED: openmm-7.4.0-py27_cuda100_1
ERROR: File does not exist: /Users/travis/anaconda/conda-bld/osx-64/openmm-7.4.0-py27_cuda100_1.tar.bz2
```

**Comment by jchodera** [comment]
Interesting! Could that be a real error? Travis CI on `osx` across multiple projects seems to be reporting that: https://travis-ci.org/choderalab/openmmtools/jobs/585946330#L599

**Comment by peastman** [comment]
I can't reproduce it on my Mac, and https://travis-ci.org/openmm/openmm?branch=master isn't reporting any errors.

**Comment by peastman** [comment]
Thought the Mac travis build for OpenMM doesn't build OpenCL, so that may not be significant.

**Comment by jchodera** [comment]
> Thought the Mac travis build for OpenMM doesn't build OpenCL, so that may not be significant.

Excellent point! Can we try adding that?

**Comment by peastman** [comment]
We could try.  I don't know what will happen.  It depends whether the VM provides access to any kind of GPU that the tests can run on.  If it doesn't, it will try to use Apple's CPU OpenCL, which is too limited to actually run much of anything.

**Comment by jchodera** [comment]
Since this is just a nightly dev build, what if we skip this test and just let it push the nightly build packages?

**Comment by peastman** [comment]
Ok, I'll try that.  And I'll see what happens if I enable OpenCL for the regular Mac travis builds.

**Comment by peastman** [comment]
See https://github.com/openmm/openmm/pull/2394.  I suspect the problem is just that the Travis VM doesn't provide access to any GPU that OpenCL could run on.

**Comment by peastman** [comment]
Actually, I think I know exactly what was causing that error.  There's a bug in SWIG on Mac so that when the C++ code throws an exception, SWIG crashes instead of correctly translating it into a Python exception.  In this case, the C++ code was throwing an exception saying no device was available.

**Comment by peastman** [comment]
Could you take a look at https://github.com/omnia-md/conda-dev-recipes/pull/172 and see if you think it's ok to merge?  It lists all the Mac builds as failing, but I think it's just that they timed out.  We could probably remove the Python 2.7 dev builds at this point, which would make it faster.  The end of life date for Python 2.7 is in just a few months, so presumably we won't be supporting it in future releases.

**Comment by jchodera** [comment]
Thanks so much! I'll just reverse the order of builds (3.7, 3.6, 2.7) so that the newer ones have priority, and then merge.

**Comment by jchodera** [comment]
Whoops, it's in your fork, so I'll merge, then switch.

**Comment by jchodera** [comment]
Whoops again---we should have also bumped this to OpenMM 7.5.0 so that we don't accidentally bring down this version and think it's 7.4.0!

**Comment by jchodera** [comment]
@peastman : Once the 7.5.0 dev builds have been pushed to the `omnia-dev` channel, are you OK with me cleaning up the earlier versions?
https://anaconda.org/omnia-dev/openmm/files

**Comment by peastman** [comment]
Ok.

**Comment by peastman** [comment]
This was fixed in https://github.com/omnia-md/conda-dev-recipes/pull/172.
