### ISSUE TITLE
OpenMM 7.4.0 crashes when using the Drude-2013 forcefield

### ISSUE THREAD

**Issue by eldernah** [openmm/openmm#2392]
I recently downloaded OpenMM 7.4.0 and tried a simulation using the Drude-2013 forcefield. Right at the beginning of the simulation it crashed: `Exception: Particle coordinate is nan`. When I tried the exact same system with OpenMM 7.3.1 everything went smoothly. 

I also checked whether the used platform makes any difference. Here is what I found:

- Version 7.3.1
All four platforms (Reference, CPU, CUDA, and OpenCL) worked.

- Version 7.4.0
Reference: `Segmentation fault`
CPU: `Exception: Particle coordinate is nan`
CUDA and OpenCL: `ValueError: Energy is NaN`

I hope this helps.

**Comment by peastman** [comment]
Can you post a self contained test case I can use to reproduce this?

**Comment by eldernah** [comment]
There you go:

[drude.tar.gz](https://github.com/openmm/openmm/files/3631511/drude.tar.gz)

Let me know if you need anything else.

**Comment by peastman** [comment]
Thanks!  I can reproduce the problem.  I'm investigating now.

**Comment by peastman** [comment]
@jing-huang could you take a look at this?  I think it's related to your changes in #2317.

I've tracked the problem to incorrect virtual sites being added for lone pairs.  For example, the psf file lists atom 9 as being a lone pair.  But then particles 9 and 10 both get marked as virtual sites with identical parameters, causing them to get put right on top of each other.

**Comment by jing-huang** [comment]
Sure. I'll take a look.

**Comment by peastman** [comment]
@jing-huang have you had a chance to look at this?  I'd like to do a 7.4.1 patch release pretty soon, and the fix for this should be included in it.

**Comment by peastman** [comment]
The fix is in #2429, if you want to try it out.
