### ISSUE TITLE
Troubleshooting CUDA __shfl_xor issue

### ISSUE THREAD

**Issue by EqualAPriori** [openmm/openmm#2393]
Hi all, I've been running some alchemical calculations following the example (last comment) from this [openmmtools thread](https://github.com/choderalab/openmmtools/issues/376).

On one of my machines it runs fine, but on another it gives me a Error launching CUDA compiler message: `error: identifier "__shfl_xor`. I installed openMM with conda and am running CUDA-9.2 on both the machine that works and the machine that doesn't.

I've only been able to localize the culprit to the alchemical code (openmm runs fine on the problem machine if I remove all the alchemical stuff, i.e. just running a vanilla simulation), but don't know precisely where something might have gone wrong. 

I was wondering if you guys would have an idea of places to look. Sorry I haven't been able to come up with a minimal example yet! And thanks for the insight.

**Comment by peastman** [comment]
What kind of GPU do you have?  We only use `__shfl_xor` when running on Volta or later GPUs, and those aren't supported on CUDA 9.x.

**Comment by EqualAPriori** [comment]
Ah, this is on V100's. The odd thing is that openMM did run on our V100's
using CUDA 9.x, as long as I wasn't using the alchemical transformation
code I linked to.

Does your comment mean that openMM shouldn't have run at all?

**Comment by peastman** [comment]
Interesting.  I'm not sure exactly what combinations of driver, compiler, and toolkit will work.  In any case, if you use a newer version of CUDA it should work correctly.

**Comment by EqualAPriori** [comment]
Got it, thanks. To double check, will using a newer version of CUDA require
that I re-install openmm via:
 conda install -c omnia/label/cuda92 -c conda-forge openmm ?

Or is linking to the new cuda library sufficient? Right now I'm using
openmm 7.3.0, and the build is py37_cuda92_rc_1

Thanks!

**Comment by peastman** [comment]
If it's currently working, you should be in good shape.  If they were incompatible, you'd be getting a linker error and it wouldn't load the CUDA platform.  If in doubt, you can run `python -m simtk.testInstallation` to check.

**Comment by EqualAPriori** [comment]
Thanks for the tip -- I tried linking to cuda 10.1 and it no longer
recognized the CUDA platform. Does this mean I should over-write my openmm
install with:
conda install -c omnia/label/cuda101 -c conda-forge openmm   ?

Thank you for bearing with the details!

**Comment by peastman** [comment]
Exactly.  You don't actually need the `/label/cuda101`, since in OpenMM 7.4 CUDA 10.1 is now the default version.
