### ISSUE TITLE
SWIG problem when compling OpenMM

### ISSUE THREAD

**Issue by WangXinyan940** [openmm/openmm#2395]
When compiling OpenMM source code, I found a problem like this:

------------------------------------------------------------------------------------

> [ 97%] Creating OpenMM Python swig input files...
> cd /home/xinyan/openmm/build/python/src/swig_doxygen && /home/xinyan/miniconda3/envs/dualNose/bin/python /home/xinyan/openmm/build/python/src/swig_doxygen/swigInputBuilder.py -i /home/xinyan/openmm/build/wrappers/python/src/swig_doxygen/doxygen/xml -c swigInputConfig.py -d OpenMM_docstring.i -o OpenMMSwigHeaders.i -a swig_lib/python/pythonprepend.i -z swig_lib/python/pythonappend.i -v 4.0.1
> [ 97%] Creating OpenMM Python module sources with swig...
> cd /home/xinyan/openmm/build/python/src/swig_doxygen && /home/xinyan/swig/bin/swig -python -c++ -outdir /home/xinyan/openmm/build/python/simtk/openmm -o OpenMMSwig.cxx OpenMM.i
> ./swig_lib/python/extend.i:360: Warning 303: %extend defined for an undeclared class OpenMM::Force.
> ./swig_lib/python/extend.i:513: Warning 303: %extend defined for an undeclared class OpenMM::State.
> ./swig_lib/python/extend.i:398: Warning 303: %extend defined for an undeclared class OpenMM::TabulatedFunction.
> ./swig_lib/python/extend.i:227: Warning 303: %extend defined for an undeclared class OpenMM::System.
> ./swig_lib/python/extend.i:206: Warning 303: %extend defined for an undeclared class OpenMM::NonbondedForce.
> ./swig_lib/python/extend.i:107: Warning 303: %extend defined for an undeclared class OpenMM::Context.
> ./swig_lib/python/extend.i:181: Warning 303: %extend defined for an undeclared class OpenMM::RPMDIntegrator.
> ./swig_lib/python/extend.i:341: Warning 303: %extend defined for an undeclared class OpenMM::CustomIntegrator.
> ./swig_lib/python/extend.i:379: Warning 303: %extend defined for an undeclared class OpenMM::Integrator.
> OpenMMSwigHeaders.i:12: Error: Bad $descriptor() macro.
> OpenMMSwigHeaders.i:14: Error: Bad $descriptor() macro.
> OpenMMSwigHeaders.i:16: Error: Bad $descriptor() macro.
> OpenMMSwigHeaders.i:18: Error: Bad $descriptor() macro.
> OpenMMSwigHeaders.i:20: Error: Bad $descriptor() macro.
> OpenMMSwigHeaders.i:22: Error: Bad $descriptor() macro.
> OpenMMSwigHeaders.i:24: Error: Bad $descriptor() macro.
> OpenMMSwigHeaders.i:26: Error: Bad $descriptor() macro.
> OpenMMSwigHeaders.i:28: Error: Bad $descriptor() macro.
> OpenMMSwigHeaders.i:30: Error: Bad $descriptor() macro.
> OpenMMSwigHeaders.i:72: Warning 453: Can't apply (ContextImpl &OUTPUT). No typemaps are defined.
> OpenMMSwigHeaders.i:73: Warning 453: Can't apply (ContextImpl &OUTPUT). No typemaps are defined.
> OpenMMSwigHeaders.i:117: Warning 453: Can't apply (OpenMM::SerializationNode &OUTPUT). No typemaps are defined.
> make[2]: *** [python/src/swig_doxygen/OpenMMSwig.cxx] Error 10
> wrappers/python/CMakeFiles/BuildModule.dir/build.make:1356: recipe for target 'python/src/swig_doxygen/OpenMMSwig.cxx' failed
> make[2]: Leaving directory '/home/xinyan/openmm/build'
> make[1]: *** [wrappers/python/CMakeFiles/BuildModule.dir/all] Error 2
> CMakeFiles/Makefile2:1455: recipe for target 'wrappers/python/CMakeFiles/BuildModule.dir/all' failed
> make[1]: Leaving directory '/home/xinyan/openmm/build'
> make: *** [all] Error 2
> Makefile:143: recipe for target 'all' failed

------------------------------------------------------------------------------------

It seems to be a SWIG problem, and I have no idea to overcome it. I've checked OpenMMSwigHeaders.i and found that it is much shorter than it should be. My problematic file is also attached.
[OpenMMSwigHeaders.zip](https://github.com/openmm/openmm/files/3625500/OpenMMSwigHeaders.zip)

I'm using GCC 7.3.0, SWIG 4.0.1 and DOXYGEN 1.8.16.

Looking forward to your help.

**Comment by peastman** [comment]
We use SWIG 3 for all our builds.  Possibly something changed in SWIG 4 that broke it?  Does it work if you switch to an earlier version?

**Comment by WangXinyan940** [comment]
I switched to SWIG 3.0.12. The compile can be finished, but the wrapper is still problematic. When I used "make PythonInstall" to install python wrapper, I recieved error like this:

---------------------------------------
> running build_ext
> building 'simtk.openmm._openmm' extension
> creating build/temp.linux-x86_64-3.6
> creating build/temp.linux-x86_64-3.6/src
> creating build/temp.linux-x86_64-3.6/src/swig_doxygen
> gcc -pthread -B /home/xinyan/miniconda3/envs/dualNose/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DMAJOR_VERSION=7 -DMINOR_VERSION=4 -I/home/xinyan/openmm/openmm/./include -I/home/xinyan/openmm/openmm/./include/openmm -I/home/xinyan/openmm/openmm/./include/openmm/internal -I/home/xinyan/openmm/openmm/openmmapi/include -I/home/xinyan/openmm/openmm/openmmapi/include/openmm -I/home/xinyan/openmm/openmm/openmmapi/include/openmm/internal -I/home/xinyan/openmm/openmm/olla/include -I/home/xinyan/openmm/openmm/olla/include/openmm -I/home/xinyan/openmm/openmm/olla/include/openmm/internal -I/home/xinyan/openmm/openmm/serialization/include -I/home/xinyan/openmm/openmm/serialization/include/openmm -I/home/xinyan/openmm/openmm/serialization/include/openmm/internal -I/home/xinyan/openmm/openmm/plugins/amoeba/openmmapi/include -I/home/xinyan/openmm/openmm/plugins/amoeba/openmmapi/include/openmm -I/home/xinyan/openmm/openmm/plugins/amoeba/openmmapi/include/openmm/internal -I/home/xinyan/openmm/openmm/plugins/rpmd/openmmapi/include -I/home/xinyan/openmm/openmm/plugins/rpmd/openmmapi/include/openmm -I/home/xinyan/openmm/openmm/plugins/rpmd/openmmapi/include/openmm/internal -I/home/xinyan/openmm/openmm/plugins/drude/openmmapi/include -I/home/xinyan/openmm/openmm/plugins/drude/openmmapi/include/openmm -I/home/xinyan/openmm/openmm/plugins/drude/openmmapi/include/openmm/internal -I/home/xinyan/miniconda3/envs/dualNose/lib/python3.6/site-packages/numpy/core/include -I/home/xinyan/miniconda3/envs/dualNose/include/python3.6m -c src/swig_doxygen/OpenMMSwig.cxx -o build/temp.linux-x86_64-3.6/src/swig_doxygen/OpenMMSwig.o
> cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
> In file included from /home/xinyan/miniconda3/envs/dualNose/lib/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1824:0,
>                  from /home/xinyan/miniconda3/envs/dualNose/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
>                  from /home/xinyan/miniconda3/envs/dualNose/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4,
>                  from src/swig_doxygen/OpenMMSwig.cxx:6757:
> /home/xinyan/miniconda3/envs/dualNose/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
>  #warning "Using deprecated NumPy API, disable it with " \
>   ^~~~~~~
> In file included from /home/xinyan/openmm/openmm/openmmapi/include/OpenMM.h:53:0,
>                  from src/swig_doxygen/OpenMMSwig.cxx:6743:
> /home/xinyan/openmm/openmm/openmmapi/include/openmm/GayBerneForce.h: In constructor ‘OpenMM::GayBerneForce::ParticleInfo::ParticleInfo(double, double, int, int, double, double, double, double, double, double)’:
> /home/xinyan/openmm/openmm/openmmapi/include/openmm/GayBerneForce.h:286:19: warning: ‘OpenMM::GayBerneForce::ParticleInfo::epsilon’ will be initialized after [-Wreorder]
>      double sigma, epsilon, sx, sy, sz, ex, ey, ez;
>                    ^~~~~~~
> /home/xinyan/openmm/openmm/openmmapi/include/openmm/GayBerneForce.h:285:9: warning:   ‘int OpenMM::GayBerneForce::ParticleInfo::xparticle’ [-Wreorder]
>      int xparticle, yparticle;
>          ^~~~~~~~~
> /home/xinyan/openmm/openmm/openmmapi/include/openmm/GayBerneForce.h:291:5: warning:   when initialized here [-Wreorder]
>      ParticleInfo(double sigma, double epsilon, int xparticle, int yparticle, double sx, double sy, double sz, double ex, double ey, double ez) :
>      ^~~~~~~~~~~~
> In file included from /home/xinyan/openmm/openmm/openmmapi/include/OpenMM.h:63:0,
>                  from src/swig_doxygen/OpenMMSwig.cxx:6743:
> /home/xinyan/openmm/openmm/openmmapi/include/openmm/NonbondedForce.h: In constructor ‘OpenMM::NonbondedForce::ParticleOffsetInfo::ParticleOffsetInfo(int, int, double, double, double)’:
> /home/xinyan/openmm/openmm/openmmapi/include/openmm/NonbondedForce.h:645:19: warning: ‘OpenMM::NonbondedForce::ParticleOffsetInfo::parameter’ will be initialized after [-Wreorder]
>      int particle, parameter;
>                    ^~~~~~~~~
> /home/xinyan/openmm/openmm/openmmapi/include/openmm/NonbondedForce.h:645:9: warning:   ‘int OpenMM::NonbondedForce::ParticleOffsetInfo::particle’ [-Wreorder]
>      int particle, parameter;
>          ^~~~~~~~
> /home/xinyan/openmm/openmm/openmmapi/include/openmm/NonbondedForce.h:651:5: warning:   when initialized here [-Wreorder]
>      ParticleOffsetInfo(int parameter, int particle, double chargeScale, double sigmaScale, double epsilonScale) :
>      ^~~~~~~~~~~~~~~~~~
> /home/xinyan/openmm/openmm/openmmapi/include/openmm/NonbondedForce.h: In constructor ‘OpenMM::NonbondedForce::ExceptionOffsetInfo::ExceptionOffsetInfo(int, int, double, double, double)’:
> /home/xinyan/openmm/openmm/openmmapi/include/openmm/NonbondedForce.h:662:20: warning: ‘OpenMM::NonbondedForce::ExceptionOffsetInfo::parameter’ will be initialized after [-Wreorder]
>      int exception, parameter;
>                     ^~~~~~~~~
> /home/xinyan/openmm/openmm/openmmapi/include/openmm/NonbondedForce.h:662:9: warning:   ‘int OpenMM::NonbondedForce::ExceptionOffsetInfo::exception’ [-Wreorder]
>      int exception, parameter;
>          ^~~~~~~~~
> /home/xinyan/openmm/openmm/openmmapi/include/openmm/NonbondedForce.h:668:5: warning:   when initialized here [-Wreorder]
>      ExceptionOffsetInfo(int parameter, int exception, double chargeProdScale, double sigmaScale, double epsilonScale) :
>      ^~~~~~~~~~~~~~~~~~~
> In file included from /home/xinyan/openmm/openmm/plugins/amoeba/openmmapi/include/OpenMMAmoeba.h:46:0,
>                  from src/swig_doxygen/OpenMMSwig.cxx:6744:
> /home/xinyan/openmm/openmm/plugins/amoeba/openmmapi/include/openmm/HippoNonbondedForce.h: In constructor ‘OpenMM::HippoNonbondedForce::ParticleInfo::ParticleInfo(double, const std::vector<double, std::allocator<double> >&, const std::vector<double, std::allocator<double> >&, double, double, double, double, double, double, double, double, double, int, int, int, int)’:
> /home/xinyan/openmm/openmm/plugins/amoeba/openmmapi/include/openmm/HippoNonbondedForce.h:407:33: warning: ‘OpenMM::HippoNonbondedForce::ParticleInfo::quadrupole’ will be initialized after [-Wreorder]
>      std::vector<double> dipole, quadrupole;
>                                  ^~~~~~~~~~
> /home/xinyan/openmm/openmm/plugins/amoeba/openmmapi/include/openmm/HippoNonbondedForce.h:406:20: warning:   ‘double OpenMM::HippoNonbondedForce::ParticleInfo::coreCharge’ [-Wreorder]
>      double charge, coreCharge, alpha, epsilon, damping, c6, pauliK, pauliQ, pauliAlpha, polarizability;
>                     ^~~~~~~~~~
> /home/xinyan/openmm/openmm/plugins/amoeba/openmmapi/include/openmm/HippoNonbondedForce.h:414:5: warning:   when initialized here [-Wreorder]
>      ParticleInfo(double charge, const std::vector<double>& dipole, const std::vector<double>& quadrupole, double coreCharge,
>      ^~~~~~~~~~~~
> /home/xinyan/openmm/openmm/plugins/amoeba/openmmapi/include/openmm/HippoNonbondedForce.h:406:89: warning: ‘OpenMM::HippoNonbondedForce::ParticleInfo::polarizability’ will be initialized after [-Wreorder]
>      double charge, coreCharge, alpha, epsilon, damping, c6, pauliK, pauliQ, pauliAlpha, polarizability;
>                                                                                          ^~~~~~~~~~~~~~
> /home/xinyan/openmm/openmm/plugins/amoeba/openmmapi/include/openmm/HippoNonbondedForce.h:405:9: warning:   ‘int OpenMM::HippoNonbondedForce::ParticleInfo::axisType’ [-Wreorder]
>      int axisType, multipoleAtomZ, multipoleAtomX, multipoleAtomY;
>          ^~~~~~~~
> /home/xinyan/openmm/openmm/plugins/amoeba/openmmapi/include/openmm/HippoNonbondedForce.h:414:5: warning:   when initialized here [-Wreorder]
>      ParticleInfo(double charge, const std::vector<double>& dipole, const std::vector<double>& quadrupole, double coreCharge,
>      ^~~~~~~~~~~~
> src/swig_doxygen/OpenMMSwig.cxx: In function ‘PyObject* _wrap_XmlSerializer__deserializeForce(PyObject*, PyObject*)’:
> src/swig_doxygen/OpenMMSwig.cxx:32041:216: error: expected primary-expression before ‘%’ token
>      /*@SWIG:/home/xinyan/miniconda3/envs/dualNose/share/swig/3.0.12/typemaps/swigmacros.swg,200,%formacro@*//*@SWIG:/home/xinyan/miniconda3/envs/dualNose/share/swig/3.0.12/typemaps/swigmacros.swg,192,%_formacro_1@*/%_factory_dispatch
>                                                                                                                                                                                                                         ^
> src/swig_doxygen/OpenMMSwig.cxx:32041:217: error: ‘_factory_dispatch’ was not declared in this scope
>      /*@SWIG:/home/xinyan/miniconda3/envs/dualNose/share/swig/3.0.12/typemaps/swigmacros.swg,200,%formacro@*//*@SWIG:/home/xinyan/miniconda3/envs/dualNose/share/swig/3.0.12/typemaps/swigmacros.swg,192,%_formacro_1@*/%_factory_dispatch
>                                                                                                                                                                                                                          ^~~~~~~~~~~~~~~~~
> src/swig_doxygen/OpenMMSwig.cxx:32040:9: warning: unused variable ‘dcast’ [-Wunused-variable]
>      int dcast = 0;
>          ^~~~~
> src/swig_doxygen/OpenMMSwig.cxx: In function ‘PyObject* _wrap_XmlSerializer__deserializeIntegrator(PyObject*, PyObject*)’:
> src/swig_doxygen/OpenMMSwig.cxx:32112:216: error: expected primary-expression before ‘%’ token
>      /*@SWIG:/home/xinyan/miniconda3/envs/dualNose/share/swig/3.0.12/typemaps/swigmacros.swg,200,%formacro@*//*@SWIG:/home/xinyan/miniconda3/envs/dualNose/share/swig/3.0.12/typemaps/swigmacros.swg,192,%_formacro_1@*/%_factory_dispatch
>                                                                                                                                                                                                                         ^
> src/swig_doxygen/OpenMMSwig.cxx:32112:217: error: ‘_factory_dispatch’ was not declared in this scope
>      /*@SWIG:/home/xinyan/miniconda3/envs/dualNose/share/swig/3.0.12/typemaps/swigmacros.swg,200,%formacro@*//*@SWIG:/home/xinyan/miniconda3/envs/dualNose/share/swig/3.0.12/typemaps/swigmacros.swg,192,%_formacro_1@*/%_factory_dispatch
>                                                                                                                                                                                                                          ^~~~~~~~~~~~~~~~~
> src/swig_doxygen/OpenMMSwig.cxx:32111:9: warning: unused variable ‘dcast’ [-Wunused-variable]
>      int dcast = 0;
>          ^~~~~
> src/swig_doxygen/OpenMMSwig.cxx: In function ‘PyObject* _wrap_XmlSerializer__deserializeTabulatedFunction(PyObject*, PyObject*)’:
> src/swig_doxygen/OpenMMSwig.cxx:32183:216: error: expected primary-expression before ‘%’ token
>      /*@SWIG:/home/xinyan/miniconda3/envs/dualNose/share/swig/3.0.12/typemaps/swigmacros.swg,200,%formacro@*//*@SWIG:/home/xinyan/miniconda3/envs/dualNose/share/swig/3.0.12/typemaps/swigmacros.swg,192,%_formacro_1@*/%_factory_dispatch
>                                                                                                                                                                                                                         ^
> src/swig_doxygen/OpenMMSwig.cxx:32183:217: error: ‘_factory_dispatch’ was not declared in this scope
>      /*@SWIG:/home/xinyan/miniconda3/envs/dualNose/share/swig/3.0.12/typemaps/swigmacros.swg,200,%formacro@*//*@SWIG:/home/xinyan/miniconda3/envs/dualNose/share/swig/3.0.12/typemaps/swigmacros.swg,192,%_formacro_1@*/%_factory_dispatch
>                                                                                                                                                                                                                          ^~~~~~~~~~~~~~~~~
> src/swig_doxygen/OpenMMSwig.cxx:32182:9: warning: unused variable ‘dcast’ [-Wunused-variable]
>      int dcast = 0;
>          ^~~~~
> In file included from /home/xinyan/openmm/openmm/openmmapi/include/openmm/State.h:35:0,
>                  from /home/xinyan/openmm/openmm/openmmapi/include/openmm/Integrator.h:35,
>                  from /home/xinyan/openmm/openmm/openmmapi/include/openmm/BrownianIntegrator.h:35,
>                  from /home/xinyan/openmm/openmm/openmmapi/include/OpenMM.h:36,
>                  from src/swig_doxygen/OpenMMSwig.cxx:6743:
> /home/xinyan/openmm/openmm/openmmapi/include/openmm/Vec3.h: At global scope:
> /home/xinyan/openmm/openmm/openmmapi/include/openmm/Vec3.h:160:13: warning: ‘OpenMM::Vec3 OpenMM::operator*(double, OpenMM::Vec3)’ defined but not used [-Wunused-function]
>  static Vec3 operator*(double lhs, Vec3 rhs) {
>              ^~~~~~~~
> /home/xinyan/miniconda3/envs/dualNose/lib/python3.6/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/xinyan/openmm/build/python/simtk/openmm/app/internal/compiled.pyx
>   tree = Parsing.p_module(s, pxd, full_module_name)
> error: command 'gcc' failed with exit status 1
---------------------------------------

And the OpenMMSwigHeaders.i file from SWIG 3 is as short as from SWIG 4, losting lots of functions.

 It seems that the OpenMMSwigHeaders.i is automaticly generated by your script. Is it possible that some args of the script are wrong and then cause the broken SWIG input file?

**Comment by WangXinyan940** [comment]
OK. I found the solution. 

In the Doxyfile from OpenMM source code, the key "FILE_PATTERNS" is like

> # If the value of the INPUT tag contains directories, you can use the 
> # FILE_PATTERNS tag to specify one or more wildcard pattern (like *.cpp 
> # and *.h) to filter out the source-files in the directories. If left 
> # blank the following patterns are tested: 
> # *.c *.cc *.cxx *.cpp *.c++ *.java *.ii *.ixx *.ipp *.i++ *.inl *.h *.hh *.hxx 
> # *.hpp *.h++ *.idl *.odl *.cs *.php *.php3 *.inc *.m *.mm *.py *.f90
> 
> FILE_PATTERNS          =

Since it's empty, my doxygen can patch and generate nothing. After I changed it to be  "FILE_PATTERNS          =    *.h", everything goes normal. 

Maybe it's because we used different version of Doxygen... I don't know.

**Comment by peastman** [comment]
That shouldn't have anything to do with it.  The comment you quoted says, "If left blank the following patterns are tested," and `*.h` is one of the ones it lists.  I suspect you just had some files left in your build directory from when you were building with the SWIG 4, and they were causing problems.
