### ISSUE TITLE
forcefield import missing 

### ISSUE THREAD

**Issue by Olllom** [openmm/openmm#2399]
In `simtk.openmm.app.__init__py`, forcefield seems to be referenced before assignment.

This causes problems in `mdtraj.Topology.from_openmm()`

OpenMM version 7.4
MDTraj version 1.9.3

**Comment by Olllom** [comment]
Oops, that seems to have been in the code for quite a while.

https://github.com/openmm/openmm/blame/master/wrappers/python/simtk/openmm/app/__init__.py

What am I missing here???

**Comment by peastman** [comment]
All submodules contained in a package are automatically imported into the package.  You don't need to import them one at a time.

**Comment by Olllom** [comment]
I don't think this is 100% true. `__init__.py` is the first file of a package that gets parsed by the interpreter and at that point the submodule names are not loaded.

The present code only works because of the relative imports

`from .forcefield import ForceField`
...
`from .topology import Topology`

which implicitly set the names `forcefield` and `topology` (you can see that by printing `dir()` before and after these imports). You are right that `__init__.py` behaves special in that it sets the names `foo` and `bar` when calling `from .foo import bar`. In contrast, the same command in a normal python file would only set the name `bar`.

I was getting some funky behavior though when playing around with importlib stuff similar to `mdtraj.utils.delay_import`. I did not get to the bottom of it, yet - this stuff does not seem to be well documented in the Python docs.

Anyway, in my opinion a cleaner way would be to import the enumerated values as

```
# Enumerated values 

from .forcefield import ( 
    NoCutoff, 
    CutoffNonPeriodic, 
    CutoffPeriodic, 
    Ewald, 
    PME, 
    LJPME, 
    HBonds, 
    AllBonds, 
    HAngles 
) 
 
from .topology import ( 
    Single, 
    Double, 
    Triple, 
    Aromatic, 
    Amide 
) 
```
