### ISSUE TITLE
More Unmatched Residues After Registering Templates For Missing

### ISSUE THREAD

**Issue by Astrovicis** [openmm/openmm#2402]
Hello! I somehow have more unmatched residues _after_ registering templates than before and I am quite confused. The following is an abbreviation of the code I am running. tmp.pdb contains the structure for 2LYZ from RCSB.

```
self.__forcefield = ForceField('amber14-all.xml', 'amber14/tip3pfb.xml')
fixer = PDBFixer(filename="tmp.pdb")
fixer.findMissingResidues()
fixer.findNonstandardResidues()
fixer.replaceNonstandardResidues()
fixer.findMissingAtoms()
fixer.addMissingAtoms()
fixer.removeHeterogens(False)
fixer.addMissingHydrogens(7.0)
with open('tmp2.pdb', 'w') as pdb_file:
    PDBFile.writeFile(fixer.topology, fixer.positions, pdb_file)

topology = fixer.topology
topology.setPeriodicBoxVectors(computePeriodicBoxVectors(49.163, 45.981, 38.869, 90.00, 90.00, 90.00))
        unmatched_residues = self.__forcefield.getUnmatchedResidues(topology)
        print("unmatched residues:", [unmatched_residue.name for unmatched_residue in unmatched_residues], "(MDSimulationProcess::165)")
        [templates, residues] = self.__forcefield.generateTemplatesForUnmatchedResidues(topology)
# reduce residues to uniquely named
residues = list(dict.values({r.name : r for r in residues}))
templates = { t.name : t for t in templates }
for residue in residues:
    print("creating template for residue", residue.name, "(MDSimulationProcess::172)")
    template = templates[residue.name]
    count = 0
    for atom in template.atoms:
        atom.type = self.__forcefield._atomTypes["protein-"+atom.name[0].upper()]
    template.bonds = []
    for bond in residue.internal_bonds():
        count += 1
        template.addBondByName(bond.atom1.name, bond.atom2.name)
        # print("registered bond between %s and %s to template %s" % (bond.atom1.name, bond.atom2.name, template.name))
    for bond in residue.external_bonds():
        atom_internal = bond.atom1 if bond.atom1 in residue.atoms() else bond.atom2
        template.addExternalBondByName(atom_internal.name)
    print("residue %s bond count is %s (MDSimulationProcess::185)" % (residue.name, count))

    print("registering template... (MDSimulationProcess187)")
    template.overrideLevel = 9001
    self.__forcefield.registerResidueTemplate(template)

print("creating system...")
system = self.__forcefield.createSystem(topology, nonbondedMethod = NoCutoff, nonbondedCutoff = 1 * nanometer, constraints = HBonds)
print("created.")
```

The above outputs the below:
```
unmatched residues: ['ARG', 'ARG', 'ARG', 'ASP', 'ALA', 'TRP', 'ARG'] (MDSimulationProcess::165)
creating template for residue ARG (MDSimulationProcess::172)
residue ARG bond count is 46 (MDSimulationProcess::185)
registering template... (MDSimulationProcess187)
creating template for residue ASP (MDSimulationProcess::172)
residue ASP bond count is 22 (MDSimulationProcess::185)
registering template... (MDSimulationProcess187)
creating template for residue ALA (MDSimulationProcess::172)
residue ALA bond count is 17 (MDSimulationProcess::185)
registering template... (MDSimulationProcess187)
creating template for residue TRP (MDSimulationProcess::172)
residue TRP bond count is 50 (MDSimulationProcess::185)
registering template... (MDSimulationProcess187)
creating system...
number of unmatched residues: 36
['ARG', 'ALA', 'ALA', 'ALA', 'ARG', 'ASP', 'ARG', 'TRP', 'ALA', 'ALA', 'ALA', 'ARG', 'ASP', 'ASP', 'ARG', 'TRP', 'TRP', 'ASP', 'ARG', 'ARG', 'ALA', 'ASP', 'ALA', 'ALA', 'ASP', 'ALA', 'TRP', 'ALA', 'TRP', 'ARG', 'ARG', 'ASP', 'ALA', 'TRP', 'ARG', 'ARG']
template atoms (26) > best match atoms(25)
template atoms (31) > best match atoms(25)
template atoms (32) > best match atoms(25)
template atoms (32) > best match atoms(25)
template atoms (33) > best match atoms(25)
Error: Got an error 1 times, aborting simulation:
Error: Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\Nanome\plugin-molecular-dynamics\nanome_molecular_dynamics\MDSimulation.py", line 204, in __run_simulation
    self.__simulation.init_simulation(complex_list)
  File "C:\Users\Admin\Desktop\Nanome\plugin-molecular-dynamics\nanome_molecular_dynamics\MDSimulationProcess.py", line 192, in init_simulation
    system = self.__forcefield.createSystem(topology, nonbondedMethod = NoCutoff, nonbondedCutoff = 1 * nanometer, constraints = HBonds)
  File "C:\Users\Admin\Anaconda3\lib\site-packages\simtk\openmm\app\forcefield.py", line 1147, in createSystem
    raise ValueError('No template found for residue %d (%s).  %s' % (res.index+1, res.name, _findMatchErrors(self, res)))
ValueError: No template found for residue 5 (ARG).  The set of atoms matches ARG, but the bonds are different.
```

As you can see, there were 7 unmatched residues before assigning the new templates. Now there are 36. What am I doing wrong? Any help would be greatly appreciated.

Thanks!

P.S. As an fyi for troubleshooting-time optimization: I've already tried removing the loops that create internal and external bonds for each template and the result is the same: 7 before, 36 after.

**Comment by peastman** [comment]
I'm not certain exactly what you're trying to do, but there definitely are several problems with the way you're doing it!  Starting with this line:

```python
template = templates[residue.name]
```

You're assuming that template names will match residue names.  That isn't the case.  Template names are arbitrary identifiers, and often differ from the names of the residues they correspond to.  For example, Amber has nine different templates for different versions of HIS, none of which is called "HIS".

Second, you should not be modifying existing templates.  Those came with the forcefield and they're already exactly what they should be.  Modifying them will break the force field.

The first thing you need to do is figure out why you have unmatched residues.  The information at https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template might be helpful.  Until you know what the problem is, it's impossible to say what the correct fix is.  But what you're doing here is almost certainly not it.

**Comment by Astrovicis** [comment]
![template](https://user-images.githubusercontent.com/9327220/65541595-818c7b80-dec2-11e9-9115-9985d079ab61.png)
![residue](https://user-images.githubusercontent.com/9327220/65541597-82251200-dec2-11e9-9ecf-e893e25de1a6.png)

I've graphed a residue and the template it should match; the problem seems to be a missing bond. How should I go about updating the templates?

**Comment by Astrovicis** [comment]
Oh, okay. Alright, I won't go about overriding templates then haha. That's interesting though. So the templates returned by the sample code [here (Section 7.2.3)](http://docs.openmm.org/7.0.0/userguide/application.html#7.2.3) all have names such that if they were registered to the forcefield again, would need to override ones that already exist. 
```
pdb = PDBFile('input.pdb')
forcefield = ForceField('amber99sb.xml', 'tip3p.xml')
[templates, residues] = forcefield.generateTemplatesForUnmatchedResidues(topology)
# Se the atom types
for template in templates:
    for atom in template.atoms:
        atom.type = ... # set the atom types here
    # Register the template with the forcefield.
    forcefield.registerResidueTemplate(template)
```

I guess I assumed using this code was the correct approach, but seeing as there are fewer residues unmatched than residues of their type in the protein, the problem is likely with those 7 residues. I'll investigate further.

**Comment by Astrovicis** [comment]
So I've added templates for each of the missing residues using _createResidueTemplate(residue) as follows:
```
for i, residue in enumerate(residues):
            residue.name += str(i)
            template = self.createResidueTemplate(residue)
            self.__forcefield.registerResidueTemplate(template)
```

This is probably not an optimal solution to recognize these templates but it should be working, correct?

**Comment by peastman** [comment]
Maybe or maybe not.  Again, the first step is to figure out why those residues aren't being matched.  Is it because they're nonstandard residues?  Or because something is wrong with your Topology?  Or something else?  Until you know what the problem is, it's impossible to say how to solve it correctly.

**Comment by Astrovicis** [comment]
Ok, so I think I've found the culprit. It seems that a previous call to PDBFixer.addMissingHydrogens is messing up a select few residues' bonds. Suggestions?

**Comment by peastman** [comment]
Can you be more specific?  In what way is it messing them up?  Please provide as much detail as possible.

**Comment by Astrovicis** [comment]
Apologies for the delay. After some digging and adding some code to provide more helpful error messages, I've discovered that there are some bonds present in some of the residues that are not present in the templates:

```
ValueError: No template found for residue 7 (CYS).  The set of atoms matches CYM, but the bonds are different.
The residue has the following unique bonds: {'Chain:0|Residue:6|Atom:SG<-->Chain:1|Residue:27|Atom:CB', 'Chain:0|Residue:6|Atom:SG<-->Chain:1|Residue:27|Atom:SG'}
The template has the following unique bonds: set()
```

```
ValueError: No template found for residue 119 (ASP).  The set of atoms matches ASP, but the bonds are different.
The residue has the following unique bonds: {'Chain:0|Residue:118|Atom:OD2<-->Chain:0|Residue:124|Atom:NH2'}
The template has the following unique bonds: set()
```

What should I do about this? I think for all practical purposes, I'm fine with using the templates being found.

**Comment by peastman** [comment]
Next you need to figure out where those extra bonds are coming from.  For example, what's the source of the bond `Chain:0|Residue:6|Atom:SG<-->Chain:1|Residue:27|Atom:CB`?  That certainly isn't something that's supposed to exist.  Perhaps there's an incorrect CONECT record in your PDB file?
