### ISSUE TITLE
Need help for compiling OpenMM on ARM CPU

### ISSUE THREAD

**Issue by NKUCodingCat** [openmm/openmm#2404]
Hey, I'm trying to compile OpenMM on ARMv8 CPU and I found that there would be a NEON support for such cases. However I have no idea about how to turn it on. Does anyone knows about it? Thanks

**Comment by peastman** [comment]
What OS are you using?

In theory this should "just work".  The CMake script should detect the processor type and automatically enable the NEON code.  In practice, we've never tested compiling for ARM on any platform other than Android, and even that not in a long time.  So I won't be surprised if you run into problems.  But hopefully we'll be able to fix them.

**Comment by jaimergp** [comment]
Oh, we should be able to build this on `conda-forge`  _eventually_!
