### ISSUE TITLE
CustomExternalForce doesn't affect the force

### ISSUE THREAD

**Issue by XiaojuanHu** [openmm/openmm#2405]
Hi,

I introduced a CustomExternalForce to FF recently. 
Dipoles and Es are vectors. I don't know how to do vector calculations in openmm, so I calculate the product as: dipole0 * E0 + dipole1 * E1 + dipole2 * E2. The code is as following:

`
			pol_force = openmm.CustomExternalForce(' -0.5 * 96.485309 * ( dipole0 * E0 + dipole1 * E1 + dipole2 * E2) ')      
			
			pol_force.addPerParticleParameter("dipole0")
			pol_force.addPerParticleParameter("dipole1")
			pol_force.addPerParticleParameter("dipole2")
			pol_force.addPerParticleParameter("E0")
			pol_force.addPerParticleParameter("E1")
			pol_force.addPerParticleParameter("E2")

			n_atom__dipole, n_atom__E0 = get_induced_dipole(n_atom__xyz, n_atom__alpha0eff, n_atom__charge)
			
			for index in n_atom:
				pol_force.addParticle( index, [ n_atom__dipole[index][0], n_atom__dipole[index][1], n_atom__dipole[index][2], n_atom__E0[index][0], n_atom__E0[index][1], n_atom__E0[index][2] ] )
				
			system.addForce(pol_force)	
`
With this code, we can see the effects on energies after the adding of CustomExternalForce. But we didn't see the changes of atomic forces. I don't know if I did something wrong or the effects of CustomExternalForce on atomic forces are too slight?

By the way, I'm curious about how openmm calculate the atomic forces. Can you give me a clue? Thank you very much!

**Comment by jchodera** [comment]
I think the problem here is that the `CustomExternalForce` energy expression does not depend on any spatial coordinates (`x`, `y`, `z`), so the gradient of the energy with respect to all spatial coordinates---and hence the force---is zero.

Are the dipoles supposed to change with time, or are they always fixed in direction and magnitude? And is the electric field supposed to be uniform and constant everywhere?

**Comment by XiaojuanHu** [comment]
Dipoles and electric field all change with time. Dipole is calculated by solving a set of coupled equations until self-consistency is reached. Ei = sum[ (q_j * **r_ij**) / r_ij **3]. Then how should I introduce spatial coordinates?

**Comment by peastman** [comment]
That can't be done with CustomExternalForce.  It only knows about the expression you give it.  Solving for dipole moments requires a much more complicated calculation than it supports.

What about using AmoebaMultipoleForce?  It supports induced dipoles (among other features), and solves for them self consistently.

**Comment by XiaojuanHu** [comment]
Thank you! I'll take a look at AmoebaMultipoleForce.

So, I use a function 'get_induced_dipole', which is related to the atomic coordinates, to calculate induced dipoles. When I'm doing MD simulations, It's not like, for every step, 'get_induced_dipole' will be called and update the induced dipoles, right?

**Comment by peastman** [comment]
That's only for when you want to query them.  Most of the time you just call `step()` on the integrator.  That does everything necessary to take a time step, including solving for the dipoles and computing forces based on them.

**Comment by XiaojuanHu** [comment]
When I'm doing MD simulation, If it's possible that in each step, I call a own-defined function to update some parameters in system, like dipole, charge?

**Comment by peastman** [comment]
You can just write a loop like this:

```python
for i in range(steps):
  simulation.step(1)
  # Do whatever you want here
```

You can modify many things that way, but there are limits.  Generally speaking, properties stored in the Context (like box vectors or global parameters) are fast to update.  Parameters stored in the System or its Forces (such as charges) are much slower to update.  You first modify the Force object, then call `updateParametersInContext()` on it.  This is an expensive operation, so you don't want to do it every step.  And some properties, such as the number of particles in the System, can only be changed by reinitializing the Context, which is very expensive.
