### ISSUE TITLE
Increment version number?

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#2408]
Now that we've released 7.4.0, should we increment the [version number](https://github.com/openmm/openmm/blob/43f619bcf4f3a02a77ba413d42fc59ecb6c47ec3/CMakeLists.txt#L159-L161) that is being built into the development version?

The version number assigned externally to the conda dev package is 7.5.0, so this might be a convenient placeholder.

**Comment by peastman** [comment]
Sure, that would be fine.
