### ISSUE TITLE
Box Dimensions in PDBReporter

### ISSUE THREAD

**Issue by Olllom** [openmm/openmm#2410]
I find it quite counterintuitive that the `PDBReporter` gets its box dimensions from the topology rather than the state. The primary use case for the reporter is probably to write single snapshots rather than whole trajectories. Why not get the crystal information from the first snapshot?

**Comment by peastman** [comment]
The primary use case for the reporter is to write trajectories, not single snapshots.  That's what reporters do: they periodically write output while a simulation is running.  If you want to write a single snapshot, call PDBFile.writeFile().

**Comment by Olllom** [comment]
Fair enough. Thanks!
