### ISSUE TITLE
Possible Ewald energy drift

### ISSUE THREAD

**Issue by marleysamways** [openmm/openmm#2417]
Hi,

A project student of mine has noticed that as the Ewald error tolerance is decreased (via `NonbondedForce.setEwaldErrorTolerance()`), this seems to have a strange effect on the system energy, causing it to gradually decrease over time when running NVE. It seems that the tighter the tolerance, the more of an effect this has - the graph below shows the results for several values, with and without constraints on the hydrogens.

![energy-test](https://user-images.githubusercontent.com/13021497/66118146-94dbcd00-e5cd-11e9-9cf5-9acff1ece41e.png)

I'm not sure if this is a might be a bug or if there's an issue with our script that we haven't spotted? I've attached the code below (but can't seem to attach a PDB file to this post?).

Many thanks,

Marley

```
from simtk.openmm import *
from simtk.openmm.app import *
from simtk.unit import *


pdb = PDBFile('bpti-equil.pdb')
forcefield = ForceField('amber14-all.xml','amber14/tip3p.xml')

system = forcefield.createSystem(pdb.topology, nonbondedMethod=PME, nonbondedCutoff=1.2*nanometer,
                                 constraints=HBonds, switchDistance=1.0*nanometer)

for f in range(system.getNumForces()):
    force = system.getForce(f)
    if force.__class__.__name__ == 'NonbondedForce':
        nb_force = force

nb_force.setEwaldErrorTolerance(0.00005)

platform = Platform.getPlatformByName('CUDA')
platform.setPropertyDefaultValue('Precision', 'double')

temp = 300 * kelvin
timestep = 0.002 * picosecond

integrator = CustomIntegrator(timestep)
integrator.addPerDofVariable("x1", 0)
integrator.addUpdateContextState()
integrator.addComputePerDof("v", "v+0.5*dt*f/m")
integrator.addComputePerDof("x", "x+dt*v")
integrator.addComputePerDof("x1", "x")
integrator.addConstrainPositions()
integrator.addComputePerDof("v", "v+0.5*dt*f/m+(x-x1)/dt")
integrator.addConstrainVelocities()

simulation = Simulation(pdb.topology, system, integrator, platform)
simulation.context.setPositions(pdb.positions)
simulation.context.setVelocitiesToTemperature(temp)

with open('energies.dat', 'w') as f:
    f.write('Total energy\n')

for i in range(1000000):
    simulation.step(1)
    state = simulation.context.getState(getEnergy=True)
    total_energy = state.getPotentialEnergy() + state.getKineticEnergy()
    with open('energies.dat', 'a') as f:
        f.write('{}\n'.format(total_energy))
```

**Comment by peastman** [comment]
I think you just need to decrease the constraint tolerance.  Generally speaking, inaccuracies in computing forces cause the energy to increase and ones applying constraints cause it to decrease.

Look at the simulations without constraints.  With the largest Ewald tolerance there's a gradual increase in energy over the simulation.  As you decrease the tolerance the energy drift also decreases, and with the smallest tolerance it has disappeared.  Then compare the ones with constraints.  The pattern is exactly the same, except all the curves are pushed downward.  That's what's causing the energy to go down.

**Comment by marleysamways** [comment]
Ah, okay. I re-ran with the constraints set to 1e-6 and the drift disappeared.

Thank you for your help.
