### ISSUE TITLE
simtk.unit is missing hartree as unit of energy

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#2419]
It appears that `simtk.unit` is [missing `hartree` as a unit of energy](https://github.com/openmm/openmm/blob/master/wrappers/python/simtk/unit/unit_definitions.py#L234) commonly used by [quantum chemical codes](https://en.wikipedia.org/wiki/Hartree). Would it be OK to add this?

**Comment by peastman** [comment]
Yes, go for it.

**Comment by jchodera** [comment]
Fixed by #2421
