### ISSUE TITLE
How to control numThreads in CPU platform?

### ISSUE THREAD

**Issue by kyleabeauchamp** [openmm/openmm#242]
So from what I've looked at, the CPU platform always uses the maximum number of threads as determined by `getNumProcessors` in hardware.h.  Is this correct?

If so, would it be possible to let an environment variable override this behavior?  

My use case for this would be in Yank where we run replica exchange with multiple simulations on a single CPU.  I suspect that I would achieve better performance by running `n` independent simulations than by running 1 simulation on `n` threads.  

Thoughts?

**Comment by ostrokach** [comment]
For the benefit of people arriving here from google, the environent variable for controlling the number of threads started per cpu is: `OPENMM_CPU_THREADS`.

For more info, see the [CPU Platform](http://docs.openmm.org/7.1.0/userguide/library.html#cpu-platform) section in the docs.

Is there a reason why the more traditional `OMP_NUM_THREADS` was not used?

**Comment by peastman** [comment]
`OMP_NUM_THREADS` isn't traditional.  It's specific to OpenMP.  We don't use OpenMP.
