### ISSUE TITLE
problem building OpenMM 7.4

### ISSUE THREAD

**Issue by afarnudi** [openmm/openmm#2420]
Hi,

I use OpenMM as the MD engine in my C++ code (PhD research). I built omm 7.1, 7.3 from the source code without any problems (MacOS 10.14) and I have been using it for 3 months now. 

I tried to build the 7.4 but came across a building issue. I decided to write this issue after the hpc center came across the same building problem and asked me for help. I hope this isn't a previously closed issue, I tried to search pretty thoroughly. 

[build_log.txt](https://github.com/openmm/openmm/files/3693003/build_log.txt)

Also here is the log file the hpc centre sent me:
[install_openmm.txt](https://github.com/openmm/openmm/files/3693005/install_openmm.txt)
[build_log.txt](https://github.com/openmm/openmm/files/3693006/build_log.txt)

As I understand we are having the same issue.
I should also note that I went back and built openmm 7.3 and the build stopped at the same place.

**Comment by peastman** [comment]
I notice the location you're building in is /share/apps/install/OpenMM/openmm-7.3.1/build.  Based on that I'd guess you previously built 7.3.1 there, then updated the source to 7.4 and tried to build in the same place?  I think it's getting confused by files left over from building the earlier version.  I suggest creating a new build directory for the new version.

**Comment by kentgorday** [comment]
I'm getting similar issues, first with a few gcc versions up to 9.1.0, and also when I retried with clang built from github yesterday. There are no previous versions of OpenMM in the build directory and no OpenMM headers or libraries in environment variables. I'd appreciate if you have any ideas. I'm trying to build with GLIBCXX_USE_CXX11_ABI=0 to agree with a version of openmm-plumed, but the error is identical without.

[ccmake flags](https://github.com/openmm/openmm/files/3833843/ccmake.txt)
[make log](https://github.com/openmm/openmm/files/3833844/clang_error.log)

Thank you for your time!

**Comment by peastman** [comment]
I think you're running into a problem that was introduced by a recent update to Doxygen.  Try using 1.8.14.  I recently implemented a fix for it, so the latest code from the master branch should build correctly with 1.8.16.  See #2460.

**Comment by kentgorday** [comment]
Thanks, built from 6024e7c without issue.

**Comment by peastman** [comment]
This is fixed in #2460, so I'm closing it.

**Comment by afarnudi** [comment]
Thanks! This solved it for me as well.
