### ISSUE TITLE
There doesn't appear to be a way to solvate CHARMM systems

### ISSUE THREAD

**Issue by thesketh** [openmm/openmm#2426]
Hi there,

I'm fairly new to using OpenMM, so this may be an oversight on my part, but I can't seem to solvate a CHARMM system using Modeller.getSolvate in 7.3.1.dev-4a269c0. I'm using the Python interface (installed via conda), but I think this is probably a general issue. 

I've had a good look throught the last full version of the Python API (for version 6.3.0, so slightly behind the version I'm using, but I couldn't find a more up to date version: [http://docs.openmm.org/6.3.0/api-python/namespacesimtk_1_1openmm.html](http://docs.openmm.org/6.3.0/api-python/namespacesimtk_1_1openmm.html)) and I can't see anything obvious.

Modeller.getSolvate requires a ForceField instance to obtain the Van der Waals radii for the atoms in the system. I think this should be able to accept a CharmmParameterSet, but I hit an error as this doesn't have a toSystem method.

This is a toy example I'm working with:

```python
from simtk.openmm import app
from simtk import openmm as mm

# Parameters - the forcefield
psf_path = "/users/travis/psf_file.psf" 
charmm_folder = "/users/travis/.charmm/"
rtf_file = charmm_folder + "top_all36_prot.rtf"
param_file = charmm_folder + "par_all36_prot.prm"
water_stream = charmm_folder + "toppar_water_ions.str"
param_set = app.CharmmParameterSet(rtf_file, param_file, water_stream)

# The system and coordinates.
psf = app.CharmmPsfFile(psf_path)
topology = psf.topology
# I'm building coordinates using openbabel, but they could be loaded from pdb
coordinates = np.array()  # A numpy array containing molecular coordinates
coordinates = unit.quantity.Quantity(coordinate_array.tolist(), unit=unit.angstrom)

modeller = app.Modeller(topology, coordinates)
padding = 7.5 * unit.angstrom
# I think this should work.
modeller.addSolvent(param_set, padding=padding)
```

But I receive an AttributeError:

```AttributeError: 'CharmmParameterSet' object has no attribute 'createSystem'```

This is perhaps as expected, as the typical method of creating CHARMM systems is to initialise a CharmmPsfFile and use CharmmPsfFile.createSystem. 

Are there any workarounds to this problem? For instance, is it possible to obtain a ForceField from a Simulation or System?

Thank you for your time.

**Comment by peastman** [comment]
Since your system uses CHARMM36, you can create an appropriate force field like this:

```python
forcefield = ForceField('charmm36.xml', 'charmm36/water.xml')
```

**Comment by thesketh** [comment]
Thanks for your quick response! I didn't realise the CHARMM XML definitions were in the OpenMM distribution. I have already tried the set from [https://github.com/choderalab/openmm-forcefields/](https://github.com/choderalab/openmm-forcefields/), but unfortunately I just run into the following error for my system of interest:

```
Exception: Multiple matching templates found for residue 1 (HSE): HSD-NTER-HS2, HSE-NTER.
```

This occurs even when the Modeller is initialised with the topology from a CONECT-record equipped PDB file. The PSF/PDB files I'm working with already have the standard C and N termini patches applied. Is this the same issue as #2047?

**Comment by peastman** [comment]
It looks like your topology has a residue that isn't supported by the force field.  There are various workarounds I can suggest, but they're all somewhat cumbersome.  So before going into those let me ask: why not just solvate it with CHARMM?  Since you're starting from a psf file, that implies you're already using the CHARMM setup tools to build your system.  Why not add the water box at that stage?

**Comment by thesketh** [comment]
I'm unsure why I'm having issues with it - it's just a standard N-terminal histidine residue (the HSE variant used in the CHARMM forcefield, neutral with protonated N). I've tried relabelling the residue to HIS to no avail. The individual histidine amino acid is also unrecognised:

```
COMPND    H
ATOM      1  N   HSE     1A   -2.670    -0.476   0.475  1.00  0.00           N1+
ATOM      2  HT1 HSE     1A   -2.645    -1.336   1.036  1.00  0.00           H
ATOM      3  HT2 HSE     1A   -2.859    -0.751  -0.532  1.00  0.00           H
ATOM      4  HT3 HSE     1A   -3.415     0.201   0.731  1.00  0.00           H
ATOM      5  CA  HSE     1A   -1.347     0.163   0.471  1.00  0.00           C
ATOM      6  HA  HSE     1A   -1.111     0.506   1.479  1.00  0.00           H
ATOM      7  CB  HSE     1A   -0.352    -0.857  -0.040  1.00  0.00           C
ATOM      8  HB1 HSE     1A   -0.360    -1.741   0.636  1.00  0.00           H
ATOM      9  HB2 HSE     1A   -0.640    -1.175  -1.046  1.00  0.00           H
ATOM     10  CG  HSE     1A    1.003    -0.275  -0.063  1.00  0.00           C
ATOM     11  CD2 HSE     1A    2.143    -0.931  -0.476  1.00  0.00           C
ATOM     12  HD2 HSE     1A    2.217    -1.952  -0.840  1.00  0.00           H
ATOM     13  NE2 HSE     1A    3.137    -0.024  -0.328  1.00  0.00           N
ATOM     14  HE2 HSE     1A    4.132    -0.238  -0.565  1.00  0.00           H
ATOM     15  CE1 HSE     1A    2.649     1.130   0.150  1.00  0.00           C
ATOM     16  HE1 HSE     1A    3.233     2.020   0.360  1.00  0.00           H
ATOM     17  ND1 HSE     1A    1.323     0.973   0.314  1.00  0.00           N
ATOM     18  C   HSE     1A   -1.465     1.282  -0.497  1.00  0.00           C
ATOM     19  OT1 HSE     1A   -2.108     2.309  -0.180  1.00  0.00           O
ATOM     20  OT2 HSE     1A   -0.864     1.172  -1.737  1.00  0.00           O1-
MASTER        0    0    0    0    0    0    0    0   20    0    0    0
END
```

Giving `ValueError: No template found for residue 1 (HSE).  The set of atoms is similar to TCYT, but it is missing 4 atoms` if the residue is labelled as "HSE" and `Exception: Multiple matching templates found for residue 1 (HIS): HSD-NTER-CTER-HS2, HSE-NTER-CTER.` if it's labelled as "HIS".

I'm not particularly tied into the CHARMM ecosystem: I'm working with short peptides, so I'm generating the initial structures using OpenBabel and have a custom script to build the PSF files. I have been using VMD for solvation (via subprocess.call, messy and slow), but I'm in the process of converting workflows from VMD+NAMD to OpenMM and I'm trying to cut out firing up such a big application for something relatively simple. 

I could always write a script to add the molecule to an existing water box and calculate/remove the clashes, but it would obviously be nicer to use something more standard if possible.

**Comment by peastman** [comment]
I think I understand.  The force field has two ways of producing identical templates: by using the HSE template, or by starting from the HSD template and applying the HS2 patch to it.  Usually that isn't a problem.  It first looks for a template that matches directly, and if it finds one, it doesn't even consider patches.  So it would always select HSE.  But this is a terminal residue, so it always needs patches.

After looking through the patch, I *think* the patched HSD-HS2 is identical to HSE (all parameters the same).  Assuming that's true, a solution would be to make it more forgiving.  If it comes up with two templates that match, but they assign identical parameters to all atoms, it would not report an error.

**Comment by peastman** [comment]
I just merged the fix.

**Comment by thesketh** [comment]
That should do it. Thanks for your help!
