### ISSUE TITLE
Create 7.4.1 release

### ISSUE THREAD

**Issue by peastman** [openmm/openmm#2430]
There've been enough bug fixes since 7.4 that I think it would make sense to do a 7.4.1 patch.  Here are the changes I'd suggest including.

#2397: Use correct parameters for nucleic acids with GBn2
#2400: Barostats use checkpointed random number generator
#2411: Add ability to enforce units on input arguments
#2413: Make sure correct CUDA context is current
#2416 and #2418: Fixed error building neighbor list with triclinic box
#2423: Fixes writing PDBx/mmCIF files with blank residue insertion codes.
#2425: Fixes addMembrane for large(r) systems

**Comment by jchodera** [comment]
How 'bout we also toss in

#2421: Added missing hartree unit (useful for OpenMM integration into [QCEngine](https://github.com/MolSSI/QCEngine/pull/151))

Otherwise, looks good to me!

**Comment by peastman** [comment]
Sure.  It isn't really a bug fix, but it's a very small change so I'm ok with including it.

**Comment by jchodera** [comment]
Considering this was an accidental omission of an important unit despite the inclusion of its friends, it's not a stretch to consider it a "bugfix".

**Comment by JoaoRodrigues** [comment]
I think there might be a bug in the way ions are added to membrane systems via `addMembrane`. When I refactored the neutralization code into the `_addIons` function I missed that since I am excluding some waters from the pool of replaceable molecules, I am effectively underestimating the number of waters in the box and therefore the final ion concentration is _less_ than expected. I don't expect the effect to be really big since the layer of 'protected' waters is thin, but nevertheless ... This problem was never caught because the solvation/neutralization tests never check for membrane systems.

I'm working on a fix and on improving the tests, but if you don't mind, I'd rather have this shipped in 7.4.1! Sorry for introducing a bug ...

**Comment by peastman** [comment]
Could you clarify what you mean?  What waters are being excluded?

**Comment by JoaoRodrigues** [comment]
See [here](https://github.com/openmm/openmm/blob/master/wrappers/python/simtk/openmm/app/modeller.py#L1562). When `_addIons` is called, it gets `waterPos`as the pool of water molecules that will be replaced by ions. Now look [here](https://github.com/openmm/openmm/blob/master/wrappers/python/simtk/openmm/app/modeller.py#L329). For the membrane case, because there are some water molecules that are excluded from the replaceable pool (too close to the membrane), the `numIons` calculation is slightly wrong, leading to an effectively lower concentration of ions in the final box.

**Comment by jchodera** [comment]
@JoaoRodrigues Should this be a separate issue?

**Comment by JoaoRodrigues** [comment]
Took me quite a while to find the problem, but #2439 ...

**Comment by jchodera** [comment]
@peastman This is getting complex enough that it would benefit us to have this on a [Project Board](https://github.com/openmm/openmm/projects) to keep track of what makes it into 7.4.1. Would you mind if I set one up?

It would also be great to start a project board for 7.5.0, the next feature release, so we can have something of a roadmap for near-term features!

**Comment by peastman** [comment]
I'd rather not.  That becomes just one more thing I have to keep track of. :)  Let's continue to just post bug numbers in this thread.  I don't expect it to get very long.

**Comment by jchodera** [comment]
> I'd rather not. That becomes just one more thing I have to keep track of. :) Let's continue to just post bug numbers in this thread. I don't expect it to get very long.

Everything is cross-referenced, and it's really easy to drag things around and add/remove issues in a Project Board.

We're currently suffering from the lack of any sort of transparent roadmap to where we are going beyond the infrequent "let's do a release, what should go in it?" issue posts. I think this is an area where we can do much better, and the fact that Project Boards are so well-integrated with GitHub issues makes it the logical choice.

We don't have to do it for this point bugfix release, but we really, really should have something to track requests for bugfixes, new features, documentation improvements, and API-breaking changes  on some sort of roadmap so our users can have an expectation for what is coming and roughly when.

**Comment by jchodera** [comment]
This was also one of the concrete criteria in which we scored badly for the [CZI Essential Open Source Software for Science RFA](https://chanzuckerberg.com/rfa/essential-open-source-software-for-science/):
![image](https://user-images.githubusercontent.com/3656088/67431472-346ef880-f599-11e9-9734-68588a9cf56c.png)

**Comment by peastman** [comment]
Here are a few other fixes to include:

#2429: Fixed range error when adding lone pairs from PSF file
#2437: Added L-BFGS to licenses file
#2440: Fixes _addIons behavior for membrane systems.
#2441 and #2445: Do not register OpenCL platform if no implementations are available

Shall I get started on it?

**Comment by jchodera** [comment]
Do we have the whole list together somewhere?

I believe it's 

#2397: Use correct parameters for nucleic acids with GBn2
#2400: Barostats use checkpointed random number generator
#2411: Add ability to enforce units on input arguments
#2413: Make sure correct CUDA context is current
#2416 and #2418: Fixed error building neighbor list with triclinic box
#2423: Fixes writing PDBx/mmCIF files with blank residue insertion codes.
#2425: Fixes addMembrane for large(r) systems
#2421: Added missing hartree unit (useful for OpenMM integration into QCEngine)
#2429: Fixed range error when adding lone pairs from PSF file
#2437: Added L-BFGS to licenses file
#2440: Fixes _addIons behavior for membrane systems.
#2441 and #2445: Do not register OpenCL platform if no implementations are available

(but it's silly to keep copy-and-pasting)

**Comment by jchodera** [comment]
Also, should we deploy this release on conda-forge? Seems like we're essentially ready to go there.

**Comment by peastman** [comment]
Everything listed above in this thread.  No need to keep copying them.  That just adds clutter to the thread.

> Also, should we deploy this release on conda-forge? Seems like we're essentially ready to go there.

Let's give it a try.

**Comment by JoaoRodrigues** [comment]
Why not update the first post for a list of all the changes? Easier to find in the future.

Thanks a lot for managing this and for the comments on my stuff, both of you.

**Comment by peastman** [comment]
This has been held up for over two weeks waiting for conda-forge issues to be resolved, and it doesn't look to me like they're going to get resolved any time soon.  I suggest we go ahead and create this release on omnia.  I don't want to keep delaying it indefinitely.

**Comment by jchodera** [comment]
Go for it if you can get it to work.

**Comment by peastman** [comment]
Packages are built and the announcement is posted at https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=161&t=11237&p=0&start=0&view=.

**Comment by jchodera** [comment]
@peastman : You still need to cut a `7.4.1rc1` release on GitHub:
https://github.com/openmm/openmm/releases

We really need to stick to a [release checklist](https://github.com/openmm/openmm/issues/2390), or else we will inevitably forget a step of this process every time.

**Comment by peastman** [comment]
We only create github releases for actual releases.  See https://github.com/openmm/openmm/wiki/Release-Candidates.  For betas and release candidates we just add tags.  I'll add the tag for this one.

**Comment by jchodera** [comment]
Thanks! Apologies for mixing up tags and releases here. Yes, a tag would be important!

**Comment by peastman** [comment]
It's been a week and a half, and there have been no reports of problems.  It's been downloaded 14 times, so at least a few people have been trying it, but not very many.  Waiting longer isn't likely to produce many more though.  Shall we call it an official release?

**Comment by jchodera** [comment]
That's a pretty disappointing showing, but I guess we also don't really have a strong distribution channel for advertising new releases or release candidates. 

I'm not even sure if we regularly test against release candidates in travis tests on our end, though we generally test against nightly dev builds.

What if we go ahead and release, but open a thread to come up with a strategy to have more people test release candidates more thoroughly? There's no point in waiting a week or two on a release candidate if nobody is going to test it. We should either skip the RC step or get serious about finding an effective way to test it broadly.

**Comment by peastman** [comment]
Sounds like a good plan.

For major releases we usually get a lot more people testing them.  Patches are less interesting to test.

**Comment by peastman** [comment]
And it's released!  The announcement is at https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=161&t=11284&p=0&start=0&view=.

**Comment by peastman** [comment]
I'm closing this since the release is out.
