### ISSUE TITLE
Add LBFGS license to Licenses.txt

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#2434]
It looks like we neglected to include the [LBFGS license](https://github.com/openmm/openmm/blob/ecae836ce9ce279ed99e8297fdb0c8b342f144ad/libraries/lbfgs/include/lbfgs.h#L4-L25) in https://github.com/openmm/openmm/blob/master/docs-source/licenses/Licenses.txt with all the other component licenses.

cc: https://github.com/conda-forge/openmm-feedstock/pull/10#issuecomment-544312327

**Comment by isuruf** [comment]
lepton license text is missing too

**Comment by peastman** [comment]
Lepton is part of OpenMM.  It's covered by the same license as the rest of OpenMM.  I just gave it its own folder to make it easier for people who want to use it separately.
