### ISSUE TITLE
MembraneBarostat question

### ISSUE THREAD

**Issue by EqualAPriori** [openmm/openmm#2438]
Hi all, thank you again for the excellent work on openmm!

I've recently begun exploring the MembraneBarostat, and eventually I want to perform constant-tension simulations of surfactants at interfaces. To help me get started, I tried doing MembraneBarostat simulations of simply an alkane-water interface (Lipid14/OPC4 water). When I don't apply a tension, the surface area contracts as expected. However, when I apply a tension far in excess of the measured alkane-water interface (from a NPnAT simulation), my simulations still see the surface area contract instead of expand.

I wanted to check if I could be applying the barostat incorrectly:
`XYmode = mm.MonteCarloMembraneBarostat.XYIsotropic`

`Zmode = mm.MonteCarloMembraneBarostat.ZFree`

`barostat = mm.MonteCarloMembraneBarostat(args.pressure*u.bar, args.tension*u.bar*u.nanometer, args.temperature*u.kelvin, XYmode, Zmode, args.nbarostat)`

For reference, I've measured my alkane/water surface tension to be ~54.5mN/m (experimental ~50.4), or 545bar * nm. I apply a surface tension of 2000bar*nm, which is more than twice the measured surface tension (to account for the two interfaces).

Thank you for any advice, and let me know if there's other information that might help!

**Comment by peastman** [comment]
I bet you're running into #2406.  Can you try installing the latest nightly build and see if it works correctly?

```
conda install -c omnia-dev openmm
```

The fix will be in 7.4.1.

**Comment by EqualAPriori** [comment]
I tried the nightly build but haven't been able to get it to work yet -- it
gives *nan* for the energies now, so for some reason the way I'm setting up
my simulation (with openmm 7.3.1) is incompatible with the nightly build,
I'll have to explore a bit more to understand what's going on.

In the meantime, I tried the work-around, where I don't explicitly include
u.bar*u.nanometer, and the simulation now seems to give reasonable/physical
results -- confirming that I was running into the units problem.

**Comment by EqualAPriori** [comment]
Closing issue -- thanks for the help!
