### ISSUE TITLE
Should ForceField.createSystem also change water hydrogen masses?

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#2442]
Currently, the `hydrogenMass` flag for `ForceField.createSystem()` affects [_all_ hydrogens bonded to heavy atoms](https://github.com/openmm/openmm/blob/master/wrappers/python/simtk/openmm/app/forcefield.py#L1170-L1179), including waters. 

Should we allow this to only be restricted to non-water hydrogens that will not be rigidly constrained by SETTLE?

cc: https://github.com/choderalab/perses/issues/587

**Comment by peastman** [comment]
Sounds reasonable to have an option for that.

**Comment by peastman** [comment]
I'm looking into this now.  I have a few questions.

1. Should this be an option or just a change in the behavior?  Are there cases where you want it to change the masses of the water hydrogens, or should it never do that?

2. Assuming it's an option, what should the default be?

3. Alternatively, should it be linked to the `rigidWater` option?  If you're making water rigid that means not to do HMR in the waters?

**Comment by jchodera** [comment]
> Alternatively, should it be linked to the rigidWater option? If you're making water rigid that means not to do HMR in the waters?

I think this is the right call! If water is rigid, there is no need to repartition masses, I don't think.

In principle, we could test if this has an impact on the maximum stable BAOAB timestep, but I think it's conceptually simplest to not repartition waters if `rigidWater=True`.

**Comment by peastman** [comment]
I ran the ApoA1 benchmark ten times with no errors.  That's just one data point, but at least in that case the same timestep still seems to be stable.
