### ISSUE TITLE
extended Lagrangian in customCVForce

### ISSUE THREAD

**Issue by fhh2626** [openmm/openmm#2454]
Dear OpenMM developers,

I wonder if it is possible to run an extended Lagrangian-based simulation with customCVForce, as the former is needed by extended ABF or extended metadynamics. 

Currently, the only way I can acheive this is to change customCVForce every step and "mimic" an extended degree of freedom, which is obviously slow.

Thanks for your help,

SIncerely,
Haohao

**Comment by peastman** [comment]
It may be possible with a CustomIntegrator, depending on exactly what you want to do.  It can define extra degrees of freedom and integrate them.  How does the force need to depend on the extra degrees of freedom?

**Comment by fhh2626** [comment]
Thanks for your reply. The extended DOF has its own mass and is couple with the collective variable, z, through a spring [U=1/2k(z-z0)^2]. The biases from ABF or MtD are added on the extended DOF rather than the real system.

**Comment by peastman** [comment]
How does the extra DOF come into it?  `z` is a collective variable, so a function of the particle coordinates.  And you said the spring has energy `(1/2)*k*(z-z0)^2`.  Are `k` and `z0` just constants, or is one of those the extra DOF that's supposed to get integrated?  If they're just constants, how does the energy depend on the extra DOF?

**Comment by fhh2626** [comment]
Sorry for my inadequate explanation. k is a constant. z0 is the real CV, while z is the extended CV. The extended DOF and the real CV are coupled through the spring.

**Comment by peastman** [comment]
Ok, I think I understand.  `z0` is computed based on the particle positions, and `z` should be integrated, right?

It's possible to do this with a CustomIntegrator.  First you do the following when creating the CustomCVForce:

```python
cvforce.addGlobalParameter('z', 0) # Second arg is whatever you want the initial value to be
cvforce.addEnergyParameterDerivative('z')
```

This tells it that `z` is a global parameter whose value will be stored in the Context, and also instructs it to compute the derivative of the energy dE/dz at each time step.

Now write a CustomIntegrator to implement the integration algorithm.  There are some examples you can use as a starting point at http://docs.openmm.org/latest/api-c++/generated/OpenMM.CustomIntegrator.html#_CPPv2N6OpenMM16CustomIntegratorE, and many more at https://github.com/choderalab/openmmtools/blob/master/openmmtools/integrators.py.  Now you need to modify it to also integrate the value of `z` using whatever method you want.  CustomIntegrator can directly access all Context parameters, so you can just refer to it directly, and you can use the function `deriv(energy, z)`, which will return dE/dz.

**Comment by fhh2626** [comment]
Thanks for your very kind explanation. I think I understand.
