### ISSUE TITLE
Speed of simulated tempering's _attemptTemperatureChange

### ISSUE THREAD

**Issue by ljmartin** [openmm/openmm#2458]
Hi all,
Is this a legitimate way to speed up `_attemptTemperatureChange`? For my system, this step takes ~80ms. If `tempChangeInterval` is 25 steps, then that's 3.2 seconds per 1000 steps. Half of this time was taken up by this line:
`velocities = [v*scale for v in state.getVelocities().value_in_unit(unit.nanometers/unit.picoseconds)]`

In particular, `state.getVelocities().value_in_unit(unit.nanometers/unit.picoseconds)` which took 40ms. 

This is 10,000X faster:
`velocities = [v*scale for v in state.getVelocities(asNumpy=True)/unit.nanometer*unit.picosecond]` 

however loss of precision might be a problem. For example, numpy version:
`state.getVelocities(asNumpy=True)[0]/nanometer*picosecond` --> `array([ 0.71486157,  0.34841982, -1.24401581])`
vs value_in_unit:
`state.getVelocities().value_in_unit(nanometers/picoseconds)[0]` --> `Vec3(x=0.7148615717887878, y=0.34841981530189514, z=-1.2440158128738403)`

Any advice on whether or not to use this, or if there's another way to speed things up, will be greatly appreciated. 
Cheers!

**Comment by ljmartin** [comment]
I see now the precision thing was just a funny print option in numpy. From what I can see the above are equivalent except for speed, and that the fast option uses numpy which may have been avoided for some reason.

**Comment by peastman** [comment]
Yes, that's absolutely a legitimate way to speed it up, and an excellent change.  The one slight wrinkle is that OpenMM doesn't actually require numpy to be installed.  I know, we're strange that way, but I try to keep the required dependencies as close to zero as possible!  Anyway, just add this to the imports at the top of the file:

```python
try:
    import numpy
    have_numpy = True
except:
    have_numpy = False
```

And then you can make it `asNumpy=have_numpy`.  A PR with this change would be great!

**Comment by ljmartin** [comment]
Sure thing. I'm not experienced with github so I'll figure that out first and then submit. 
Thanks!

**Comment by tristanic** [comment]
If you use `asNumpy=True` then you can do away with the list comprehension entirely, which should make things faster still:

`velocities = scale *  state.getVelocities(asNumpy=True)  / unit.nanometer * unit.picosecond`

**Comment by peastman** [comment]
Good point.  This would be slightly cleaner:

```
velocities = scale*state.getVelocities(asNumpy=True).value_in_unit(unit.nanometers/unit.picoseconds)
```

**Comment by ljmartin** [comment]
PR at: https://github.com/openmm/openmm/pull/2466
