### ISSUE TITLE
Uniform pulling force problem

### ISSUE THREAD

**Issue by lenhsherr** [openmm/openmm#2478]
Hi!

I’m trying to implement a custom force in OpenMM of a uniform pulling force in a direction, very much like an uniform electric field applied to only a subset of atoms. The force would to be applied to the center of mass of ligand atoms, so I’ve opted to use the CustomCentroidBondForce with only one group. Here is the section of the code:

```python
pullforce = CustomCentroidBondForce(1,  "pull_force_constant * (x1*fx + y1*fy + z1*fz)")
pullforce.addGlobalParameter('pull_force_constant',
                                         pull_force_constant)
pullforce.addGlobalParameter('fx', fx)
pullforce.addGlobalParameter('fy', fy)
pullforce.addGlobalParameter('fz', fz)
pullforce.addGroup(lig_atom_index)
omm_simulation.system.addForce(pullforce)
omm_simulation.context.reinitialize()
omm_simulation.context.setPositions(positions)
```

The problem is, when running the simulation, the ligand would not move at all compared to setting the pull force constant to 0.0, while the same implementation works if I change the potential to harmonic instead of linear. 

Does anyone have experience implementig linear pulling force in OpenMM? I will upload self contained test script and PDB file shortly as currently it is written for Orion. 

Thanks a lot!

**Comment by jchodera** [comment]
I think I can reproduce this. Here's a complete example that should drag an alanine dipeptide in vacuum in the positive x direction, but fails to do so:
```python
from simtk import openmm, unit
from openmmtools.testsystems import AlanineDipeptideVacuum

# Create alanine dipeptide in vacuum
testsystem = AlanineDipeptideVacuum()
system = testsystem.system
positions = testsystem.positions

# Compute centroid
initial_centroid = (positions / unit.angstroms).mean(0)

# Add the pulling force
pull_force_constant = 10.0 * unit.kilocalories_per_mole / 1.0 * unit.angstroms
lig_atom_index = [ index for index in range(system.getNumParticles()) ]
fx = -1.0 # pull in x
fy = fz = 0.0 # not in y or z

pullforce = openmm.CustomCentroidBondForce(1,  "pull_force_constant * (x1*fx + y1*fy + z1*fz)")
pullforce.addGlobalParameter('pull_force_constant',
                                         pull_force_constant)
pullforce.addGlobalParameter('fx', fx)
#pullforce.addEnergyParameterDerivative('fx')
pullforce.addGlobalParameter('fy', fy)
pullforce.addGlobalParameter('fz', fz)
pullforce.addGroup(lig_atom_index)
system.addForce(pullforce)

# Create an integrator
integrator = openmm.VerletIntegrator(1.0*unit.femtoseconds)

# Create the context
context = openmm.Context(system, integrator)
context.setPositions(positions)

# Integrate
for step in range(50):
    integrator.step(100)
    positions = context.getState(getPositions=True).getPositions(asNumpy=True)
    current_centroid = (positions / unit.angstroms).mean(0)
    displacement = current_centroid - initial_centroid
    print(step, displacement)

del context, integrator
```

**Comment by lenhsherr** [comment]
Thank you @jchodera ! This is great, I think we can work off this script instead of me uploading my huge system in xml. My initial hypothesis was this has to do with the PBC as the uniform potential wouldn't be continues at boundaries, but looks like it failed too for the alanine dipeptide. Maybe a bug?

**Comment by jchodera** [comment]
@peastman: Any thoughts about what might be going on here? Is our syntax wrong, or could there be some sort of bug here?

**Comment by peastman** [comment]
You're missing one line:

```python
pullforce.addBond([0])
```

`addGroup()` defines groups whose centroids the force can depend on.  Then you need to add one or more bonds whose energy depends on those groups.

**Comment by lenhsherr** [comment]
Adding the `pullforce.addBond([0])` line now gives me this error:

```
Exception: CustomCentroidBondForce requires a device that supports 64 bit atomic operations
```
Looks like this issue was because OSX default to 32 bit OpenCL and it fails. This issue was addressed in Yank by using CPU platform. Is OpenMM able to use 64 bit OpenCL on OSX?

**Comment by peastman** [comment]
This isn't about the OpenCL, it's about the particular device (GPU) you're running on.  Low end embedded GPUs often don't support 64 bit atomic operations.  We try to work around that limitation, but there are a few forces (like CustomCentroidBondForce) where it's really hard.  You can use the CPU platform instead.

**Comment by lenhsherr** [comment]
Sounds good, thanks! Closing issue.

**Comment by CayetanaZF** [comment]
Hey guys, 
Is there a way to visualize the result of the x direction pulling like in VMD?

Best Regards, 
Cayetana

**Comment by peastman** [comment]
I'm not sure what you mean?  The result of the pulling is that the atoms you're pulling on should move.  That should be reflected in the trajectory when you view it with VMD.

**Comment by CayetanaZF** [comment]
Peastman, 

Sorry for my brief question, I meant to a command to export the results of the simulation into a .pdb file like when you're using PDBReporter as argument of the simulation.reporters.append() class, but with the openmm.Context() class (I'm new using OpenMM by the way).

**Comment by peastman** [comment]
Use Simulation instead of Context.  Simulation is just a thin wrapper around a Context that adds a few extra features, such as reporters.

**Comment by PowersPope** [comment]
Hi @peastman from your recommendation in #4738 , I am trying to implement the `CustomCentroidBondForce`. I am trying to apply a similar constant pulling force to my peptide (bound to a target). However, I am not seeing any movement or influence by the force. I wondered if I am implementing it wrong or the interaction was just strong. To combat this I decided to implement the control highlighted above. I made very slight changes, so that I could implement simulation reporters for tracking the trajecctory in PyMOL. Though when I do that I do not see any movement in the x direction of the alanine dipeptide. 

My assumption is that since it is in a vacuum I am not seeing the displacement visually. Therefore in PyMOL i made the trajectory and then loaded in the `init-alanine-test.pdb` as a reference, but the trajectory didn't move still. Am I missing something here?

```
import openmm
import openmm.app as openmm_app
import openmm.unit as unit
from openmmtools.testsystems import AlanineDipeptideVacuum
import numpy as np

# Create alanine dipeptide in vacuum
testsystem = AlanineDipeptideVacuum()
system = testsystem.system
positions = testsystem.positions

# Compute centroid
initial_centroid = (positions / unit.angstroms).mean(0)

# Add the pulling force
pull_force_constant = 10.0 * unit.kilocalories_per_mole / 1.0 * unit.angstroms
lig_atom_index = [ index for index in range(system.getNumParticles()) ]
fy = -1.0 # pull in x
fx = fz = 0.0 # not in y or z

pullforce = openmm.CustomCentroidBondForce(1,  "pull_force_constant * (x1*fx + y1*fy + z1*fz)")
pullforce.addGlobalParameter('pull_force_constant',
                                         pull_force_constant)
pullforce.addGlobalParameter('fx', fx)
#pullforce.addEnergyParameterDerivative('fx')
pullforce.addGlobalParameter('fy', fy)
pullforce.addGlobalParameter('fz', fz)
pullforce.addGroup(lig_atom_index)
pullforce.addBond([0])
system.addForce(pullforce)

# Create an integrator
integrator = openmm.VerletIntegrator(1.0*unit.femtoseconds)

simulation = openmm_app.Simulation(
    testsystem.topology,
    system,
    integrator,
    openmm.Platform.getPlatformByName('CUDA'),
)

simulation.context.setPositions(positions)

positions = simulation.context.getState(getPositions=True).getPositions()
with open('init-alanine-test.pdb', 'w') as f:
    openmm_app.PDBFile.writeFile(simulation.topology, positions, f)

simulation.reporters = []
simulation.reporters.append(openmm_app.DCDReporter("traj-alanine-test.dcd", 10))

# Integrate
for step in range(50):
    simulation.step(100)
    positions = simulation.context.getState(getPositions=True).getPositions(asNumpy=True)
    current_centroid = (positions / unit.angstroms).mean(0)
    displacement = current_centroid - initial_centroid
    print(step, np.sqrt(np.sum(np.power(displacement,2))))

del simulation
```

Also, here is the output from the print statement while it is taking steps:
```
0 0.06516831384420206
1 0.05744342146007802
2 0.060057302088031894
3 0.14524218298001615
4 0.19618681578847252
5 0.17176492293821904
6 0.10883363779379537
7 0.041905519895909626
8 0.04928513081635963
9 0.040961055526144395
10 0.07645100197962312
11 0.02243684127928902
12 0.050768876526875305
13 0.1008512481958411
14 0.1159598216889536
15 0.168720479251235
16 0.0929479065125773
17 0.06758437443408788
18 0.04642050468030835
19 0.042517613736409214
20 0.08530271552661225
21 0.03754784213804966
22 0.02860503778285564
23 0.08916870236841319
24 0.13034652718018783
25 0.19110469684184572
26 0.15702321779284184
27 0.09874851642175049
28 0.07001499724080186
29 0.03239963439876495
30 0.07490594797196767
31 0.054645085004398304
32 0.05541633903860592
33 0.050169510108197576
34 0.13290636125520913
35 0.20502913613062299
36 0.21680172106723275
37 0.1729597322947366
38 0.07865729677453467
39 0.04553633899572638
40 0.06606914400375821
41 0.02507468016711369
42 0.03984797597222536
43 0.07637595660848501
44 0.05252731798191396
45 0.1221674918020565
46 0.18797518167571212
47 0.17554618421477514
48 0.08781757646406428
49 0.05553141476068326
```

**Comment by peastman** [comment]
Please open a new issue.  This one was closed many years ago.
