### ISSUE TITLE
PBC

### ISSUE THREAD

**Issue by maicol93** [openmm/openmm#2479]
Dear OpenMM team,
I downloaded and followed the tutorial "histone methyltransferase with structural Zn2 + ions". Visualizing the trajectory produced by OpenMM through the vmd software I noticed a strange behavior of the PBC. As shown in the image, in fact, there appears to be empty regions of space between one periodic image of the box and another. Is it an artifact, or an error in the simulation setting?
Thanks
![Screenshot from 2019-11-23 15-51-18](https://user-images.githubusercontent.com/46623532/69480843-53b4ac00-0e0b-11ea-938c-ea4a3854a4cf.png)

**Comment by peastman** [comment]
Since you closed this issue, I assume you figured it out?
