### ISSUE TITLE
PDBFile

### ISSUE THREAD

**Issue by stephanmg** [openmm/openmm#248]
Dear all,

is PDBFile only Python-specific wrapping of C++/C API functionality of OpenMM?

In particular I'm interested if there is the possibility (OOTB) to read in a PDB file with OpenMM with the C/C++ API like HelloReadPDBFile.cpp for example.

Best,
Stephan

**Comment by prlw1** [comment]
This bug is closed, yet it seems that the original question is:

Is there a C++ class which will read a PDB file into an OpenMM system structure?

AFAICT the answer is no, so is this a "feature request"?

**Comment by swails** [comment]
> On Jul 25, 2016, at 12:14 PM, prlw1 <notifications@github.com> wrote:
> 
> This bug is closed, yet it seems that the original question is:
> 
> Is there a C++ class which will read a PDB file into an OpenMM system structure?
> 
> AFAICT the answer is no, so is this a "feature request"?
> 

This feature doesn't make much sense. A PDB file contains very little of the information required to create a System. It has no parameters (which is basically all that a System is). 

There is no "Topology" class in the C++ layer, and it does not make much sense there. 

The way to use a PDB file in C++ is to prepare a xml file from it (with a force field) using a script written in Python). 

Also keep in mind that the C++ layer does not have the ability to write trajectories or output files with thermodynamic observables. All of that functionality lives exclusively within the python layer.
