### ISSUE TITLE
Coulomb correction for system not periodic in z direction

### ISSUE THREAD

**Issue by z-gong** [openmm/openmm#2480]
Hello, I'm simulating an electrified solid surface with `nonbondedMethod=PME`. This system is only periodic in `xy` plane. In order to correctly calculate the long-range electrostatics, a correction term should be applied to eliminate the interactions between periodic slabs in `z` direction. The correction is straightforward based on the dipole of the system ([Ballenegger, Arnold, Cerdà. JCP 2009.](https://doi.org/10.1063/1.3216473)). I was trying to apply this correction with `CustomExternalForce`. However, the system dipole should be evaluated at every step. I'm wondering is it doable with other kinds of CustomForces? Thank you for your ideas.

![ewald-3dc](https://user-images.githubusercontent.com/379616/69486980-951c7a00-0e52-11ea-89db-903c7a7b19e4.PNG)

**Comment by peastman** [comment]
I think this could be done with a CustomCVForce.  Use three CustomExternalForces to define the three CVs, and then the energy is a simple function of them.

**Comment by peastman** [comment]
Actually, you don't need a CV for Q because it doesn't depend on any coordinates.  You can either hardcode its value into the CustomCVForce, or make it a global parameter if you want to be able to change it.

**Comment by z-gong** [comment]
> I think this could be done with a CustomCVForce. Use three CustomExternalForces to define the three CVs, and then the energy is a simple function of them.

Thank you. It works with CustomExternalForce and CustomCVForce. After applying the correction, the simulation results are almost identical to the one produced by GROMACS. In case someone has the similar requirement, I leave the code snippt here
```
def slab_correction(system: mm.System):
    # assume charge neutral system. sum(q) = 0
    muz = mm.CustomExternalForce('q*z')
    muz.addPerParticleParameter('q')
    nbforce = [system.getForce(i) for i in range(system.getNumForces())
               if system.getForce(i).__class__ == mm.NonbondedForce][0]
    for i in range(nbforce.getNumParticles()):
        q = nbforce.getParticleParameters(i)[0].value_in_unit(elementary_charge)
        muz.addParticle(i, [q])
    box = system.getDefaultPeriodicBoxVectors()
    vol = (box[0][0] * box[1][1] * box[2][2]).value_in_unit(nanometer ** 3)  # assume rectangular box
    cvforce = mm.CustomCVForce('k*muz*muz')
    _conv = (1.602E-19) ** 2 / 1E-9 / (4 * 3.1415926) / 8.854E-12 * 6.022E23 / 1000  # convert from e^2/nm to kJ/mol
    cvforce.addGlobalParameter('k', 2 * 3.1415926 / vol * _conv)
    cvforce.addCollectiveVariable('muz', muz)
    system.addForce(cvforce)
```

**Comment by peastman** [comment]
Great!  Is it ok if we close this issue?

**Comment by rowanwalker96** [comment]
Any idea how you'd implement this for an AMOEBA system? I presume you'd need to take into account the effect of induced and permanent dipoles and not just the monopole component as above...

You can get the total system dipole z component for an AMOEBA system in debyes with something like: 
`multipole_force = [ f for f in system.getForces() if isinstance(f, AmoebaMultipoleForce)][0]`
`np.array(multipole_force.getSystemMultipoleMoments(simulation.context))[3])`

However if you wanted to use custom external force you'd need to make a dependence on the z coordinate in order for the force to be calculated via the derivative?

I guess the above implementation posted by z-gong would still be a good approximation, I can try and check how well it recovers the correct value of the electric field.

**Comment by peastman** [comment]
Taking the fixed and induced dipoles into account would make it a lot more complicated.  I suspect though that they have very little effect on the dipole moment of the system as a whole.  Let us know what you find.
