### ISSUE TITLE
Multi-step integrator

### ISSUE THREAD

**Issue by raimis** [openmm/openmm#2483]
@peastman @jchodera

We would like to implement a multi-step integrator, which is loosely based on https://arxiv.org/pdf/physics/0502064.pdf:

1. Compute `fastForces` and `slowForces`
2. Propagate the state with `fastForces + 2*slowForces`
3. Compute `fastForces`
4. Propagate the state with `fastForces`

where `slowForces` is the reciprocal term of PME, and `fastForces` is everything else.

We are aware of https://openmmtools.readthedocs.io/en/latest/api/generated/openmmtools.integrators.MTSIntegrator.html#openmmtools.integrators.MTSIntegrator, but we need an implementation in C++ API.

Currently, we have an OpenMM-based implementation in ACEMD (https://software.acellera.com/docs/latest/acemd3/index.html), which achieves 10-20% increase in speed while maintaining the energy conservation.

**Comment by peastman** [comment]
MTSIntegrator is based on CustomIntegrator, so it would be very simple to convert to C++.  Take a look at the implementation in https://github.com/openmm/openmm/blob/master/wrappers/python/simtk/openmm/mtsintegrator.py.  There's only about 30 lines of code in the whole thing.

**Comment by raimis** [comment]
@peastman 

I looked at `MTSIntegrator`, as mentioned above, and tried to re-implement with `CustomIntegrator` at C++ level, as you suggested, but the performance was worse than with `LangevinIntegrator`. `CustomIntegrator` launches a lot of kernels which create a bit of overhead.

We have an implementation which is actually faster.

**Comment by peastman** [comment]
Can you post links to both versions?  The overhead from using CustomIntegrator should be minimal.  Any time you find it isn't, that usually means the two versions are actually doing different calculations.

**Comment by raimis** [comment]
To clarify, the algorithm we are talking isn't the same as implemented in `MTSIntegrator` (RESPA).

Now I'm working on an example to show what we want and what is the problem with `CustomIntegrator`.

**Comment by peastman** [comment]
Thanks, that sounds great.

**Comment by raimis** [comment]
@peastman 

I have made a  PR (https://github.com/openmm/openmm/pull/2501) with a draft implementation of `MultiStepVerletIntegrator` and `MultiStepLangevinIntegrator`. And a test script to demonstrate the issue (`examples/multi_step_integrator.py`).

For reference, I run a simulation with `VerletIntegrator` and its re-implementation `VerletIntegrator2` with `CustomIntegrator`. For simplicity, I ignore restraints and use 0.5 fs time step.
```
$ python multi_step_integrator.py v1
#"Step","Potential Energy (kJ/mole)","Speed (ns/day)"
1000,-37325.87595838946,0
2000,-37470.62595838946,211
3000,-37610.76658338946,219
4000,-37533.48533338946,219
5000,-37418.01658338946,222
6000,-37593.54783338946,223
7000,-37620.54783338946,225
8000,-37524.87595838946,225
9000,-37543.46970838946,226
10000,-37555.48533338946,227
$ python multi_step_integrator.py v2
#"Step","Potential Energy (kJ/mole)","Speed (ns/day)"
1000,-37400.68845838946,0
2000,-37502.34470838946,229
3000,-37619.21970838946,228
4000,-37545.37595838946,227
5000,-37449.17283338946,227
6000,-37609.09470838946,227
7000,-37561.75095838946,227
8000,-37528.25095838946,226
9000,-37642.27439588946,226
10000,-37664.90720838946,226
```
The trajectories are similar, but not identical, even with `properties = {'DeterministicForces': 'true', 'Precision': 'double'}`. However, this isn't the main issue.

Second, I run the simulation with `MultiStepVerletIntegrator` and its re-implementation `MultiStepVerletIntegrator2` with `CustomIntegrator`. And  the period of slow forces is 1, so effectively, it is identical to `VerletIntegrator` and `VerletIntegrator2`. 
```
$ python multi_step_integrator.py l1
#"Step","Potential Energy (kJ/mole)","Speed (ns/day)"
1000,-37325.84470838946,0
2000,-37470.56345838946,220
3000,-37610.53220838946,235
4000,-37533.10252088946,231
5000,-37418.19627088946,230
6000,-37591.95408338946,229
7000,-37617.18845838946,229
8000,-37521.71189588946,229
9000,-37539.73533338946,229
10000,-37591.83689588946,229
$ python multi_step_integrator.py l2
#"Step","Potential Energy (kJ/mole)","Speed (ns/day)"
1000,-37400.71189588946,0
2000,-37502.13377088946,187
3000,-37619.29783338946,172
4000,-37545.31345838946,172
5000,-37449.03220838946,174
6000,-37613.96970838946,177
7000,-37568.38377088946,179
8000,-37531.43845838946,178
9000,-37629.24314588946,180
10000,-37654.98533338946,179
```
The trajectories are similar to the corresponding single-step integrators, but `MultiStepVerletIntegrator2` is slower than `VerletIntegrator2`.

Finally, I run the simulation with the same integrators, but the period of slow forces is 2. For simplicity, I don't scale any forces, so effectively, the reciprocal term of PME is computed every second step.
```
$ python multi_step_integrator.py m1
#"Step","Potential Energy (kJ/mole)","Speed (ns/day)"
1000,-37333.07908338946,0
2000,-37454.36033338946,323
3000,-37448.26658338946,329
4000,-37430.39158338946,333
5000,-37543.50095838946,338
6000,-37450.50095838946,340
7000,-37520.04002088946,343
8000,-37648.16502088946,345
9000,-37538.63377088946,346
10000,-37626.89158338946,347
$ python multi_step_integrator.py m2
#"Step","Potential Energy (kJ/mole)","Speed (ns/day)"
1000,-37409.36033338946,0
2000,-37482.90720838946,185
3000,-37452.71970838946,182
4000,-37445.98533338946,181
5000,-37545.24314588946,181
6000,-37437.92283338946,180
7000,-37598.11033338946,180
8000,-37592.90720838946,180
9000,-37591.04002088946,181
10000,-37468.43845838946,180
```
As expected, `MultiStepVerletIntegrator` is faster than `VerletIntegrator`, but `MultiStepVerletIntegrator2` is slower than `VerletIntegrator2`.

**Issue:** Is a way to implement `MultiStepVerletIntegrator2` with `CustomIntegrator` efficiently? Bare in mind, I will need to scale the slow force (`f1`), so adding `f0 + f1` by just using `f` isn't an option.

**Comment by peastman** [comment]
You've written the CustomIntegrator in a way that makes it slower than it needs to be.  Take a look at MTSIntegrator (https://github.com/openmm/openmm/blob/master/wrappers/python/simtk/openmm/mtsintegrator.py), which is written in a more efficient way.  Each time you call `step()` it runs through a complete multi-step sequence, that is, one full outermost time step.  The fast inner steps are written out explicitly.

This leads to fewer kernel launches.  CustomIntegrator tries to be smart about merging multiple steps together into a single kernel launch.  But all the "if" blocks in your version prevent it from doing that, so you get lots of small kernels.

The two versions of your integrator also evaluate the forces differently.  Your CustomIntegrator uses two separate force evaluations for the fast and slow forces:

```python
integrator.addComputePerDof('fe', 'f0')
integrator.beginIfBlock('slowStep = 0')
integrator.addComputePerDof('fe', 'fe + f1')
integrator.endBlock()
```

It's more efficient to compute them together.  That is, just write `f0` in the fast steps and `f` in the slow steps.  You did say

> I will need to scale the slow force (f1), so adding f0 + f1 by just using f isn't an option.

However, that isn't what your MultiStepVerletIntegrator does.  It uses a single force evaluation for all needed groups at once:

```c++
context->calcForcesAndEnergy(true, false, getGroups());
```

If you're actually going to need to scale the groups differently you'll need to change that, which will make it slower.

Also note that your current implementation is dangerous, because it allows someone to stop midway through a complete "step".  When using a MTS integrator, you should only ever perform complete outer steps.  The positions and velocities at intermediate points aren't meaningful.  They don't correspond to points on the true trajectory.

**Comment by raimis** [comment]
@peastman 

Thanks for your comments.

>You've written the CustomIntegrator in a way that makes it slower than it needs to be. Take a look at MTSIntegrator (https://github.com/openmm/openmm/blob/master/wrappers/python/simtk/openmm/mtsintegrator.py), which is written in a more efficient way. Each time you call step() it runs through a complete multi-step sequence, that is, one full outermost time step. The fast inner steps are written out explicitly.

I have written an alternative implementation with the complete multi-step, as you suggested.
`MultiStepVerletIntegrator3` (8287e417bc26d256988b86083857f91d70fc0c1a):
```
$ python multi_step_integrator.py m3
#"Step","Potential Energy (kJ/mole)","Speed (ns/day)"
1000,-37454.27439588946,0
2000,-37430.61033338946,327
3000,-37449.25095838946,331
4000,-37646.29002088946,334
5000,-37603.81345838946,341
6000,-37580.00877088946,344
7000,-37623.19627088946,346
8000,-37670.65720838946,341
9000,-37625.24314588946,339
10000,-37599.47752088946,338
```
`MultiStepVerletIntegrator4` based on `CustomIntegrator` (d38c5f3b54578c203aa71c151ba418987ffca5b8):
```
$ python multi_step_integrator.py m4
#"Step","Potential Energy (kJ/mole)","Speed (ns/day)"
1000,-37404.87595838946,0
2000,-37492.38377088946,191
3000,-37492.03220838946,191
4000,-37634.03220838946,192
5000,-37555.21970838946,192
6000,-37638.68845838946,192
7000,-37577.98533338946,192
8000,-37599.25095838946,192
9000,-37637.12595838946,193
10000,-37627.37595838946,192
```
So `MultiStepVerletIntegrator4` is just marginally faster than `MultiStepVerletIntegrator2`.

>The two versions of your integrator also evaluate the forces differently. Your CustomIntegrator uses two separate force evaluations for the fast and slow forces:

I would like this, but it doesn't work!
```python
integrator.addComputePerDof('fe', 'f0 + 2*f1')
```
What should be easier/more logical to implement:
- speed up this:
```python
integrator.addComputePerDof('fe', 'f0')
integrator.addComputePerDof('fe', 'fe + 2 * f1')
```
- do the scaling here:
```c++
context->calcForcesAndEnergy(true, false, getGroups());
```

> It's more efficient to compute them together. That is, just write f0 in the fast steps and f in the slow steps.

For the force evaluation has to alternate between: `fastForces + 2*slowForces` and `fastForces`. If `f = fastForces + 2*slowForces` and `f0 = fastForces`, the integration part will work. The problem is that the physical forces (and energies) is `fastForces + slowForces`. So the barostat would work incorrectly and the logs would be wrong.

Currently, we have the hacked implementation in ACEMD, which uses two `NonbondedForce` objects, where one is scaled by multiplying charges by `sqrt(2)`. After setting the groups properly, I can compute all 3 energies and forces: `fastForces`, `fastForces + slowForces`, and `fastForces + 2*slowForces`.

Thus we are looking, how can such integrator be implemented in OpenMM (could be just a plugin), that it runs fast and doesn't need hacking the barostat and logging?

**Comment by raimis** [comment]
@peastman Do you have any suggestions how this can be solved?

**Comment by peastman** [comment]
The code you have that computes `f0` and `f1` separately is fine.  Yes, it's a bit slower to compute them separately than to compute them at the same time, but that's just the nature of the calculation.  It's true whether or not you use a CustomIntegrator.  Your C++ version would have exactly the same issue.

Assuming the "fast" forces really are much faster than the "slow" ones, the speed difference should be fairly small.  If that's not the case, you may want to reconsider how you split the forces.  What splitting are you using?

**Comment by raimis** [comment]
@peastman 

> The code you have that computes f0 and f1 separately is fine. Yes, it's a bit slower to compute them separately than to compute them at the same time, but that's just the nature of the calculation. It's true whether or not you use a CustomIntegrator. Your C++ version would have exactly the same issue.

I wrote an example 8f38b262357aa527cf5a7ef046c97c3658939c4c,  which uses two `NonbondedForce` objects, where one of them is scaled by 2 (charges are scaled by `sqrt(2)`). One `NonbondedForce` is used for the van der Waals interactions and the direct term of PME, while the other (scaled) is used for the reciprocal tern of PME. So I can achieve intended force scaling and fast execution. 
```bash
$ python multi_step_integrator.py m5
#"Step","Potential Energy (kJ/mole)","Speed (ns/day)"
1000,-129657.86890266498,0
2000,-131299.83765266498,357
3000,-130619.27515266498,364
4000,-131085.52515266498,353
5000,-130834.90015266498,346
6000,-131063.52515266498,344
7000,-131013.21265266498,349
8000,-131407.71265266498,349
9000,-130917.90015266498,352
10000,-130890.27515266498,354
```
The problem is that the total potential energy is incorrect, so  the barostat will work incorrectly and the logs will be wrong.

> Assuming the "fast" forces really are much faster than the "slow" ones, the speed difference should be fairly small. If that's not the case, you may want to reconsider how you split the forces. What splitting are you using?

As mentioned above, the `slowForces` is the reciprocal term of PME, and `fastForces` is everything else. So `fastForces` are fast varying, but not fast computable. Changing the splinting of the forces is not an option.

### Possible solution

Currently, the default to compute the physical system forces (and energy) is to use all force groups:
```c++
double ContextImpl::calcForcesAndEnergy(bool includeForces, bool includeEnergy, int groups=0xFFFFFFFF);
```
Maybe it would be possible to redefine that default, rather then use a hard-coded value.
```c++
double ContextImpl::setDefaultForceGroups(int groups);
```
Would this make sense?

**Comment by peastman** [comment]
If you just implement everything in the straightforward way and call `setReciprocalSpaceForceGroup(1)` on the NonbondedForce, how much speed difference is there between computing all forces at once with `f` versus computing `f0` and `f1` separately?

> Maybe it would be possible to redefine that default, rather then use a hard-coded value.

What problem would that solve?

**Comment by raimis** [comment]
> If you just implement everything in the straightforward way and call setReciprocalSpaceForceGroup(1) on the NonbondedForce, how much speed difference is there between computing all forces at once with f versus computing f0 and f1 separately?

As already showed in https://github.com/openmm/openmm/issues/2483#issuecomment-564663821:

#### The force computed separately 
```
$ python multi_step_integrator.py m4
#"Step","Potential Energy (kJ/mole)","Speed (ns/day)"
1000,-37404.87595838946,0
2000,-37492.38377088946,191
3000,-37492.03220838946,191
4000,-37634.03220838946,192
5000,-37555.21970838946,192
6000,-37638.68845838946,192
7000,-37577.98533338946,192
8000,-37599.25095838946,192
9000,-37637.12595838946,193
10000,-37627.37595838946,192
```
### The forces computed at once:
```
$ python multi_step_integrator.py m3
#"Step","Potential Energy (kJ/mole)","Speed (ns/day)"
1000,-37454.27439588946,0
2000,-37430.61033338946,327
3000,-37449.25095838946,331
4000,-37646.29002088946,334
5000,-37603.81345838946,341
6000,-37580.00877088946,344
7000,-37623.19627088946,346
8000,-37670.65720838946,341
9000,-37625.24314588946,339
10000,-37599.47752088946,338
```

> What problem would that solve?

It is possible to compute the physical energy and forces (`fastForces + slowForces`), while still having an extra `NonbondedForce` object corresponding to `2 * slowForces`

I have implemented `Context::setDefaultForceGroups` (f16027439f7c60ccc544911eb8a75330ef0c0acb). In the example bellow (66a31bfe7608590a5c8a83e0ffaafb4748c1be53), after setting the force groups properly, the integrator can compute ``fastForces` and `fastForces + 2 * slowForces` efficiently (at once), while `StateDataReporter` gets the physical energies (`fastForces + slowForces`):
```
$ python multi_step_integrator.py m6
#"Step","Potential Energy (kJ/mole)","Speed (ns/day)"
1000,-37470.68064588946,0
2000,-37533.25877088946,345
3000,-37589.07908338946,348
4000,-37538.05564588946,335
5000,-37577.29783338946,337
6000,-37680.90720838946,338
7000,-37621.59470838946,339
8000,-37624.71189588946,341
9000,-37693.14158338946,342
10000,-37628.75877088946,343
```
So, with such API extension, it is possible to implement the proposed integrator efficiently. Would it be admissible to OpenMM? I can split it into a separate PR for further refinement.

**Comment by raimis** [comment]
@peastman How could we proceed?

**Comment by peastman** [comment]
Sorry for going silent on this.  I've been out on vacation the last two weeks.  Let's see if we can get this figured out.

I'm still confused about the results you're reporting.  For one thing, the extra overhead from evaluating the force groups separately should be quite small, nothing anywhere close to what you describe.  The only way I can see that happening is if you're simulating a tiny system.  In that case, the amount of computation in each kernel is minimal and the time is just dominated by the kernel launch overhead.  But in that case, you should probably be using the CPU or Reference platform instead.

How big is the system you're simulating (number of atoms and box dimensions), and what GPU are you using?

The other thing that's confusing me is that normally, reciprocal space calculations account for less than 50% of the total computation time.  So with the splitting you're using that just skips the reciprocal calculation on every other time step, the maximum speedup you should possibly be able to get is about 25%, and probably less.  But you're reporting a much larger speedup, which again just doesn't make sense.  Unless, again, you're simulating a very small number of atoms in a relatively large box, in which case reciprocal space would dominate the computation.

**Comment by raimis** [comment]
Thanks for your comments! I'll try to do more benchmarks with more realistic systems to sort out what is going on.
