### ISSUE TITLE
does openMM support local pair?

### ISSUE THREAD

**Issue by carlcaiwin** [openmm/openmm#2485]
I've been trying to use a kind of multiscale force field called PACE with openMM, but the PACE force field include a local pair parameter, that means the nonbonded interaction parameters between i residue and i+3 residue and  the nonbonded interaction parameters between i residue and i+6,7,8.. residue are different. there is some specific parameter to correct the local conformation, mainly i - i+3 or 4.
      In GROMACS, this kind of parameters can be insert in [ pairs ] and [ exclusion ] part easily, but how can I use the PACE force field in openMM, does openMM support this kind of local pair? 
      can someone help me with this issue?

**Comment by Lnaden** [comment]
I can think of a way OpenMM may be able to do this, but can you clarify a few things first so we can make sure we give you the best advice we can?

* By "residue" do you mean particle/atom, or do you mean actual adjacent residues on a protein?
* Assuming you mean particles/atoms, for which set of parameters to modify, are you needing to change only the Nonbonded interactions between particles i/i+3, i/i+4, i/i+5... etc? i.e. Bonded, angle, and torsion terms remain unchanged.
* Assuming you want to change interactions beyond i/i>4, how far out does that expansion in the FF go? 

Thanks!

**Comment by peastman** [comment]
You can exclude particular pairs from nonbonded interactions by calling `addException()` on a NonbondedForce, or `addExclusion()` on a CustomNonbondedForce.  If necessary, you can then use a bonded force to compute those interactions in an appropriate way.

**Comment by carlcaiwin** [comment]
> I can think of a way OpenMM may be able to do this, but can you clarify a few things first so we can make sure we give you the best advice we can?
> 
> * By "residue" do you mean particle/atom, or do you mean actual adjacent residues on a protein?
> * Assuming you mean particles/atoms, for which set of parameters to modify, are you needing to change only the Nonbonded interactions between particles i/i+3, i/i+4, i/i+5... etc? i.e. Bonded, angle, and torsion terms remain unchanged.
> * Assuming you want to change interactions beyond i/i>4, how far out does that expansion in the FF go?
> 
> Thanks!

       Thanks for your reply! The residue means the amino acid in protein, the interactions between residue i and i+3 means the interactions between the certain atom/particle of i aminoacid and the certain atom/particle of i+3 aminoacid. so the interactions are among particles, but the i/i+3,i/i+4 are residue number/ aminoacid number, and the particles belong to that certain residue, such as interactions between alpha carbon in residue ID 1(i) and beta carbon in residue ID 4(i+3). I am sorry to mislead you.
         as for the expansion, the PACE force field has cutoff of 1.2nm, in some cases, such as beta sheet, the i+17 residue maybe close to the i residue, so the interactions between particles of the i+17 residue and  particles of the i residue should be calculated, but these parameters are different from the i/i+3, even though they are same atom type, but this local pair is begin from i/i+1 residue and end to i/i+5 residue, I don't know if I have expressed clearly！
          many thanks!

**Comment by carlcaiwin** [comment]
> You can exclude particular pairs from nonbonded interactions by calling `addException()` on a NonbondedForce, or `addExclusion()` on a CustomNonbondedForce. If necessary, you can then use a bonded force to compute those interactions in an appropriate way.

        Thanks for your reply! the local pairs and nonbonded interactions has the different parameters, but they are both LJ potential, not the bonded potential, just the different epsilon and different sigma, if I remove the old parameters of particular pairs, how can I add the new parameters of these particular pairs, is there any function to add LJ potential in particular pairs?
        many thanks!

**Comment by peastman** [comment]
When you call `addException()` on the NonbondedForce, you can tell it what parameters to use for each pair.  See http://docs.openmm.org/latest/api-python/generated/simtk.openmm.openmm.NonbondedForce.html#simtk.openmm.openmm.NonbondedForce.addException.
