### ISSUE TITLE
Current and Future OSX Nvidia support 

### ISSUE THREAD

**Issue by Lnaden** [openmm/openmm#2486]
@peastman So Nvidia stopped supporting their driver deployment for OSX 10.14 and greater earlier this year. Since I am working on reconfiguring the Omnia builds anyways, I wanted to ask how important is CUDA support for OSX at this point? Would you be willing to stop OSX CUDA builds for OpenMM since NVIDIA does not allow its drivers to be installed on the updated OS?

I wanted to establish this answer before I spend too much time getting the OSX builds against CUDA to work in the updated Omnia platform. Given this also impacts OpenMM CUDA + OSX support, I wanted to ask it here on the official OpenMM github instead of an omnia one.

For context, the CUDA 10+ installers for OSX technically come with a driver on them, but OSX > 10.13 is explcitly blocked in the dmg's `manifest.xml` file:

```xml
<package>
  <file>cuda_mac_installer_drv.tar.gz</file>
  <manifest>cuda_mac_installer_drv.manifest</manifest>
  <md5>9e7d82e65377913e36fd9cbfdb925b0e</md5>
  <name>CUDA Driver</name>
  <id>cuda-driver</id>
  <disable_os_greater_than>10.13</disable_os_greater_than>
</package>
```

**Comment by peastman** [comment]
I think it's reasonable if our prebuilt packages don't have CUDA on MacOS.  There aren't a lot of Macs out there with NVIDIA GPUs anyway, and if they no longer support the latest OS version, that's another argument for it.  Users who have CUDA capable Macs can always build from source.

**Comment by Lnaden** [comment]
Awesome, I will not add in CUDA OSX support to the builds anymore. It makes the builds much easier since the only way it looked like to install it was through the `.dmg` which forces a GUI element to open for "reasons." Now I don't have to do that! Thanks.
