### ISSUE TITLE
CharmmPSFWarning: ... Resetting molecularity

### ISSUE THREAD

**Issue by des2037** [openmm/openmm#2491]
Hi everyone, 

I'm noticed an odd difference between openMM 7.4 (b71e92d) and openMM 7.4 beta (b9a1bee): specifically, when running a pretty vanilla MD simulation, with openMM 7.4 beta, I see this:

`
../python3.7/site-packages/simtk/openmm/app/charmmpsffile.py:363: `
`CharmmPSFWarning: Detected PSF molecule section that is WRONG. Resetting molecularity.
`

However, for the exact same simulation setup, that message disappears when using the official 7.4 release. Regardless, for both the official and beta release, outputted .pdbs have re-numbered atoms and residues, chain names have been introduced, and segment IDs are dropped. While it's mildly inconvenient to have residue #s changed, it's not a huge problem. Reported energies seem reasonable, and visual inspection of the trajectories reveal nothing unusual. 

> Note: input .psf/.pdb were generated with CHARMM GUI. Also, this behavior has been observed for multiple, unrelated systems.

**A couple of questions:**
1) Should we be worried about this `Warning` for calculations that were run with the beta version?

2) Did something about how the .psf is parsed change between the beta and the official release, or is the warning just muted in the official release?   

3) For calculations that were initiated with the beta release, can we seamlessly switch to the official release when continuing/restarting these simulations, or are the beta/official releases too different to allow for such a transition? 

Many thanks as always,
Derek

**Comment by peastman** [comment]
> Should we be worried about this Warning for calculations that were run with the beta version?

That was usually a spurious warning that didn't indicate any actual problem, so we just got rid of it.  See #2353.  You shouldn't worry about it.

> For calculations that were initiated with the beta release, can we seamlessly switch to the official release when continuing/restarting these simulations, or are the beta/official releases too different to allow for such a transition?

Generally speaking, I don't recommend using betas for production simulations.  They tend to have known bugs, or at least haven't been tested thoroughly, which is why they're betas!  If you were to continue the simulations where you left off, there's a good chance everything would be fine.  But if you're concerned about correct results, you should use the latest release.

**Comment by des2037** [comment]
Hi @peastman , thanks a lot for the information; very glad the warning is spurious! I agree with your comments on betas, and we are definitely switching to the latest openMM release (7.4). 🙂

**Comment by peastman** [comment]
Even better, 7.4.1 has just been released!

**Comment by des2037** [comment]
True! I saw the announcement; very exciting!!! 🙂
