### ISSUE TITLE
no switchDistance option for GromacsTopFile.createSystem?

### ISSUE THREAD

**Issue by ruixingw** [openmm/openmm#2492]
```
gro = GromacsGroFile('geom.gro')
top = GromacsTopFile(
    'topol.top',
    periodicBoxVectors=gro.getPeriodicBoxVectors(),
    includeDir='/home/ruixingw/apps/gromacs2019.3/share/gromacs/top')

system = top.createSystem(
                         nonbondedMethod=PME,
                         nonbondedCutoff=1.2 * nanometer,
                         constraints=HBonds,
                         switchDistance=1.0 * nanometer
                         )
```
This results in _TypeError: createSystem() got an unexpected keyword argument 'switchDistance'_, so there's no option "switchDistance" for GromacsTopFile.createSystem. Is there a reason or simply wasn't implemented?

btw, I currently use the following as a workaround:
`nonbon = system.getForce(0)
nonbon.setUseSwitchingFunction(True)
nonbon.setSwitchingDistance(1.0*nanometer)`

**Comment by peastman** [comment]
It just hasn't been implemented.  If you'd like to send a PR implementing it, that would be welcome!
