### ISSUE TITLE
OpenMM subversion compatibility? 

### ISSUE THREAD

**Issue by des2037** [openmm/openmm#2495]
Hi everyone, 

It's really terrific and exciting to see openMM constantly improve, in everything from performance improvements, bug fixes, new features, new platform support, etc.; as a user, I'm very grateful that this open-source effort is so active and supportive!

However, new releases introduce an interesting question: what is the compatibility (if any) of MD trajectories acquired from different versions (or subversions) of openMM? For example, say I have 5 replica simulations of a given system run with v7.3, and 5 more replicas of the same system run with v7.4.1 (other than openMM version number, the simulations are exactly the same). 

**In analysis, can I treat these replicas as belonging to the same ensemble, as if they had been run with a single version of openMM?** And, if there are cases where this is possible, are there any thoughts as the the range of version numbers where this is okay (e.g. within a set of subversion #s, 7.4.0 and 7.4.1, but not 7.3.1)? 

Best,
Derek

**Comment by peastman** [comment]
That's an interesting question.  In principle all simulations should be comparable, but in practice there can be subtle differences that could introduce artifacts into your results.  Here's my advice.

- If it's reasonable to do so, running all simulations that will be analyzed together with the same version is the safest thing.

- Usually it's ok to combine simulations from different patch versions (updates to the third digit).  To be sure, you need to look over the list of fixes in each patch and make sure none of them affects your simulations.  But if none of them affects your simulation, there's no harm in sticking with the earlier version.  So again, that's safest.

- I would definitely not combine trajectories generated with different major versions.

**Comment by des2037** [comment]
Thanks @peastman , this seems totally reasonable to me. I hadn't thought about it that way: if the code has functionally changed (with regard to your use), then different versions are possibly inconsistent, if not, what's the point in changing versions. 🙂
