### ISSUE TITLE
PowerPC & ARM fixes

### ISSUE THREAD

**Issue by jaimergp** [openmm/openmm#2499]
(Comes from https://github.com/conda-forge/openmm-feedstock/pull/16#issuecomment-562988195).

Trying to build OpenMM for PPC & ARM on CF has uncovered some platform code that must be fixed. For details, check the link above. I am just leaving this here as the reference issue for a potential PR.

**Comment by jchodera** [comment]
From @peastman:
> For the PPC intrinsics error, possibly we just need to upgrade to the latest version of cl.hpp. I see it no longer imports the Intel intrinsics. https://github.com/KhronosGroup/OpenCL-CLHPP/blob/master/include/CL/cl.hpp

Sounds like it would be an easy thing to tackle this now and see if that fixes the `ppc64le` issue?

**Comment by jaimergp** [comment]
I will submit a PR here, but also will try to patch it at the recipe level first to see if that works, because I don't think the CI in this repo tackles `ppc64le`, right?

**Comment by peastman** [comment]
Correct.

**Comment by peastman** [comment]
I believe this has all been fixed, and it works correctly on both PPC and ARM.  If there are still any outstanding issues, feel free to reopen this.
