### ISSUE TITLE
Crazy segmentation fault on python import

### ISSUE THREAD

**Issue by kyleabeauchamp** [openmm/openmm#250]
So this code causes a segmentation fault on my machine:

```
import simtk.openmm as mm
import scipy.optimize.minpack2
```

Interestingly, if I import in the _opposite_ order there is no segfault.

I'm not sure what the issue is, although I presume there's some funny incompatibility going on with my SO files.  

Here are some system details:

Intel(R) Xeon(R) CPU E5-4640 0 @ 2.40GHz

```
-bash-4.1$ uname -a
Linux mskcc-ln1.local 2.6.32-279.14.1.el6.x86_64 #1 SMP Tue Nov 6 23:43:09 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux
-bash-4.1$ cat /etc/redhat-release 
CentOS release 6.4 (Final)

-bash-4.1$ python --version
Python 2.7.5 :: Anaconda 1.8.0 (64-bit)

-bash-4.1$ g++ --version
g++ (GCC) 4.8.1
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```

Anyone have any ideas here?

Here is a link to my GDB backtrace:

https://gist.github.com/kyleabeauchamp/b5bcecbd62a49f9a92a2

**Comment by frogeyedpeas** [comment]
> I generated a core dump from one of the segfaults and extracted a traceback:
> 
> ```
> #0  0x00007fb013d76e00 in PyArray_API () from /usr/lib64/python2.7/site-packages/numpy/core/multiarray.so
> #1  0x00007fb007b5a2b2 in _import_array () from /usr/lib64/python2.7/site-packages/scipy/optimize/minpack2.so
> #2  0x00007fb007b5b950 in initminpack2 () from /usr/lib64/python2.7/site-packages/scipy/optimize/minpack2.so
> #3  0x00007fb0168a37b1 in _PyImport_LoadDynamicModule () from /usr/lib64/libpython2.7.so.1.0
> ```
> 
> The numpy source code--especially with regards to the numpy array API---appears to be dynamically generated at build time, which is about as far as I had time to take my investigation.
> 
> A workaround is to just import simtk.openmm last, I suppose...

how did you generate this core dump? I'm trying to debug a totally different issue that also involves a python library segfaulting and I want to create a core dump that I can use/feed to gdb. I'm on MAC OS Big Sur
