### ISSUE TITLE
CharmmParameterSet Parsing

### ISSUE THREAD

**Issue by Olllom** [openmm/openmm#2502]
Just hit this bug:
The CharmmParameterSet parser for .prm files expects section titles (like "ANGLES", "BONDS") as full words and plural, while CHARMM parses only the first four letters. 
This means, e.g., that "ANGL" is a valid section title in CHARMM but not in OpenMM.

**Comment by peastman** [comment]
Thanks!  I've marked this as a bug.  A PR would be welcome.

**Comment by jchodera** [comment]
Would be good to coordinate this with @swails and http://github.com/parmed/parmed since they share (duplicate) some of this infrastructure.

**Comment by peastman** [comment]
Looking at the documentation at https://www.charmm.org/charmm/documentation/by-version/c40b1/params/doc/io/, I see they list multiple names for some sections.  For example,

```
ANGLe or THETA
 atom atom atom force_constant theta_min UB_force_constant UB_rmin

DIHE or PHI
 atom atom atom atom force_constant periodicity phase

IMPRoper or IMPHI
 atom atom atom atom force_constant periodicity phase
```

Are those intended to be synonyms?  For example, where we currently look for a line starting with `ANGLES`, should we accept either `ANGL` or `THETA`?

**Comment by jchodera** [comment]
I think they are intended to be synonyms, with `ANGL`, `ANGLE`, and `THETA` all valid angles, for example.

**Comment by swails** [comment]
> Are those intended to be synonyms? For example, where we currently look for a line starting with `ANGLES`, should we accept either `ANGL` or `THETA`?

I believe so.  The parsers should treat these as synonyms if they don't currently.

**Comment by Olllom** [comment]
yes, I just checked: see links and discussion in #2596
