### ISSUE TITLE
Tensorflow Force Field in OPENMM

### ISSUE THREAD

**Issue by moradza** [openmm/openmm#2505]
Hi, 
I want to pass force field 2-, 3-, and 4-body to a single bead system, for 2body what I have in mind is like this,
force = CustomNonbondedForce("""model.predict(norm(r))*r/norm(r); model""")
model is a TensorFlow Neural network, which can be analytically be written, however, it is the norm of force in the e_r direction. I don't want to analytically write the force field, instead, I want to pass the model for evaluation in the openmm.

Is there any solution for this approach?
------------------------------------------
import tensorflow as tf
import numpy as np

model = tf.keras.models.Sequential([
  tf.keras.layers.Dense(4, activation='tanh'),
  tf.keras.layers.Dense(2, activation='tanh'),
  tf.keras.layers.Dense(1, activation=None)])
------------------------------------------
for three-body I have following command in my mind (similar to SW potential)
model(r1, r2, r3) is a vector of dimension 4,
force = CustomManyParticleForce(3,
     "model(r1, r2, r3)*[e_r1, e_r2, e_r1, e_r2];"
     "r1=distance(p1,p2); r2=distance(p1,p3); r3=distance(p2,p3)");
 force->setPermutationMode(CustomManyParticleForce::SinglePermutation)

**Comment by peastman** [comment]
Have you seen https://github.com/pandegroup/openmm-nn?  It lets you define forces with TensorFlow graphs.

**Comment by moradza** [comment]
I tried both openmm-nn and openmm-torch to install NN force field however, after I made the installation I get an ImportError: /usr/local/openmm/lib/libOpenMMNN.so: undefined symbol: _ZNK6OpenMM8Platform12createKernelERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIceEERNS_11ContextImplE.
Any solution for this?

**Comment by peastman** [comment]
Is this still unresolved, or have you figured it out?  You also opened an issue on the openmm-nn github, so I wasn't sure whether this was a separate issue or the same as that one.

**Comment by moradza** [comment]
I figured out a way to use LAMMPS as the MD engine, and I stopped trying openmm.

**Comment by peastman** [comment]
I'm going to close this then.  Feel free to reopen if you come back to it in the future.
