### ISSUE TITLE
Discrepancies between NpT and NVT simulation with iAmoeba force field

### ISSUE THREAD

**Issue by marcpezz** [openmm/openmm#2506]
Hello everyone,

I am encountering an unexpected behavior while performing simulations with the iAmoeba Force Field. The _g_(_r_) obtained with NVT differs from the one obtaiend by performing  NpT simulations, even though we use the averaged volume from NpT simulations for the NVT simulations. Performing simulations with tinker does not lead to any discrepancy.

Do you have any idea why this would be the case? 

I am attaching here the files used during the simulations inside the iamoebaomm.zip: 
imaoeba.xml = Force Field  
run_sim_nvt.py = input NVT
run_sim_npt.py = input NpT
water512.pdb  = pdb file 
gor.nvt.dat and gor
.npt.dat  = datafiles 

[iamoebaomm.zip](https://github.com/openmm/openmm/files/3979054/iamoebaomm.zip)

Thanks!

**Comment by jchodera** [comment]
> Performing simulations with tinker does not lead to any discrepancy.

Can you give us details about the simulations you ran in Tinker? Were these simulations run with Berendsen volume control, or with a barostat that is guaranteed to sample the correct NpT ensemble?

Previously, I had run into two issues with pressure control in Tinker:
1. The Berendsen volume control algorithm coupled to the atomic virial gives very different distributions than a true barostat (like a molecular-scaling Monte Carlo barostat) causing large average density defects
2. The stiff valence degrees of freedom in AMOEBA/iAMOEBA water gave rise to large timestep-dependent effects when using poor integrators (e.g. integrators except [BAOAB](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4893190/)).

Both effects could be conspiring here, or there could be something simpler going on. 

The first thing I notice is that you are using `constraints=app.AllBond` in the OpenMM version. My undertanding (from being a coauthor of the iAMOEBA paper) is that AMOEBA and iAMOEBA water are both intended for use _without_ constraints of any kind, and that Tinker's default behavior is to not impose constraints. I wonder if this could also contribute, along with the loose constraint tolerance you are using:
```
integrator.setConstraintTolerance(0.00001)
```
Could you also share your Tinker input files?

**Comment by peastman** [comment]
To get flexible water, specify both `constraints=None` and `rigidWater=False`.  Since most water models are designed to be rigid, it makes water rigid by default if you have no constraints in the solute.  This will definitely change the distribution.

**Comment by peastman** [comment]
Has this been resolved or are you still experiencing the problem?

**Comment by marcpezz** [comment]
> To get flexible water, specify both `constraints=None` and `rigidWater=False`. Since most water models are designed to be rigid, it makes water rigid by default if you have no constraints in the solute. This will definitely change the distribution.

Dear peastman, 

Following yours  and Chodera's suggestions I was able to recover the correct distribution.

Thank you so much for your help!

**Comment by peastman** [comment]
Great!

**Comment by peastman** [comment]
I just made some code changes to help avoid problems like this in the future: #2529.
