### ISSUE TITLE
Linker issues on OSX x86_64 platform

### ISSUE THREAD

**Issue by hannesvdc** [openmm/openmm#2510]
Hi all, I'trying to compile the following piece of code that uses the OpenMM library:

`#include "OpenMM.h"
using namespace OpenMM;
using namespace std;

int main(){
	System system;
	return 0;
}`

However, I get the following error, for both g++ and c++:

`Undefined symbols for architecture x86_64:
  "OpenMM::System::System()", referenced from:
      _main in three_atom_hmc-1f6e03.o
  "OpenMM::System::~System()", referenced from:
      _main in three_atom_hmc-1f6e03.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

I compiled the OpenMM code on OSX (version 10.14.6) by following the instructions on http://docs.openmm.org/7.1.0/userguide/library.html, and I compile the code above with

`c++ -std=c++11 -I/usr/local/openmm/include three_atom_hmc.cpp`.

The OpenMM header files are indeed present at '/usr/local/openmm/include' and the .dylib files are located at '/usr/local/openmm/lib'.

Somehow, linking my source file to the OpenMM libraries seems to fail. Does anyone have an idea on where I should look?

My regards, 

Hannes Vandecasteele

(My apologies for the bad formatting of the code above.)

**Comment by peastman** [comment]
The instructions you're following are for an old version of the code (7.1.0).  The instructions for the current version are at http://docs.openmm.org/latest/userguide/library.html.  That may not make any difference, but it's the first thing to check.

What if you use the prebuilt version instead of building it yourself?  Does the linking work then?

**Comment by hannesvdc** [comment]
Thanks for your reply. The newest installation instructions do not make any difference in the linking step. 

I'm not sure where to find the prebuilt openmm version, but I tried installing with anaconda and locate the c++ header and dynamic library files from there, but the same linker issues remain. However, I can actually use the openmm source from Python (with the conda installation), but just not with C++.

Hannes

**Comment by peastman** [comment]
Try compiling with this command line:

```
c++ -std=c++11 -stdlib=libc++ -I/usr/local/openmm/include -L/usr/local/openmm/lib -lOpenMM three_atom_hmc.cpp
```

**Comment by hannesvdc** [comment]
With this command the linking error is gone, thank you! Now, when I run the code above, an error is thrown that the .dylib file libOpenMM.dylib is not loaded, which is strange because we explicitly included it in the compiler options.

`dyld: Library not loaded: @rpath/libOpenMM.dylib`

Hannes

**Comment by peastman** [comment]
That means libOpenMM.dylib isn't in any location that's in your library search path.  The simplest solution is

```
export DYLD_LIBRARY_PATH=/usr/local/openmm/lib
```

That will work fine if you just need to run it yourself, though there are better ways of doing it for code you plan to distribute.

**Comment by hannesvdc** [comment]
That does the trick indeed, thank you! Case closed.

**Comment by peastman** [comment]
Great!
