### ISSUE TITLE
Drude Stability

### ISSUE THREAD

**Issue by Olllom** [openmm/openmm#2513]
After trying the new `DrudeNoseHooverIntegrator` and also the `DrudeLangevinIntegrator` on a few practical systems, I want to just summarize some stability issues that we encountered in the process for future reference. I currently don't have time to implement this but I think that these things need to be fixed to make Drude easy to use in OpenMM.

Tagging @andysim @jing-huang  in case I misspeak.

### Temperature Reporting
The temperature from the `StateDataReporter` does not distinguish between real atoms and Drude particles so that the reported temperatures are usually ~30% low. Of course, this does not directly affect stability but it makes the monitoring and detection of problems unnecessarily hard.

### Velocity Generation
`Context.setVelocitiesToTemperature` does not distinguish between Drude and real particles. If the initial Drude temperature is around 300 K, equilibrating the system becomes a challenge. This might have been the problem in  https://github.com/openmm/openmm/issues/1968 

### Drude Masses
As mentioned in https://github.com/openmm/openmm/issues/1766, Drude particle masses are initialized to zero if the parameter files don't explicitly specify a nonzero mass. The CHARMM PSF parser should at least have a keyword `drudeMass`. It should also print a warning if a massless Drude particle is encountered and `drudeMass is None`. (Most people use the extended Lagrangian integrators.)

### Sensible Defaults
It would make sense to provide defaults for the Drude collision frequency and temperature in the Drude integrators so people don't have to guess. Also, the hard wall constraint is switched off by default. It could be useful to set the default to 0.025. 

### How to Implement
The implementation of some of these things would formally belong into the `Context` rather than the integrators, but this is a bit complicated due to Drude being a plugin.

Instead, why not implement an empty `AbstractDrudeForce` in the main API, from which only `DrudeForce` derives. The `Context` could then implement something called `hasDrudeForce` and at least raise warnings, when something like `Context.setVelocitiesToTemperature` is called.

The Drude specific code could then go into a central place in the plugin, either a Drude integrator base class or a utility class, like 
```
class DrudeUtils {
    ...
    void setVelocitiesToTemperature(Context& context, double temperature, double drudeTemperature=1);
    void optimizeDrudeParticlePositions(Context& context, tolerance);
    double computeTemperature(Context& context);
    double computeDrudeTemperature(Context& context);
}
```
see also https://github.com/openmm/openmm/issues/905

**Comment by peastman** [comment]
Thanks for the summary.  Here are some thoughts on them.

- Adding a `drudeMass` option to both ForceField and CharmPsfFile sounds like a good idea.
- StateDataReporter could potentially check for a DrudeForce in the system and compute the temperature only of the center of mass coordinates.  We need to be careful not to add too much overhead though.  This requires it to retrieve the velocities from the GPU, then compute the kinetic energy itself.  If this turns out to be too slow, it might be better to add this computation as a function in the Drude integrators.
- Agreed about defaults.
- For initializing velocities, how about moving the implementation into the Integrator?  `Context.setVelocitiesToTemperature()` would just call an internal method on the Integrator.  The default implementation would be identical to the current behavior.  Drude integrators could override it to provide an appropriate implementation.

**Comment by andysim** [comment]
I agree with what's been stated above.  Given that DrudeForce lives in a plugin, do you think it's safe to check for its presence?  Would it make more sense to promote DrudeForce to be a first class member of OpenMM itself, at the risk of introducing more maintenance?

**Comment by peastman** [comment]
It's ok to do it in Python code.  The Python wrappers already require the Drude plugin.  We shouldn't do it in C++ code, but none of the above changes require that.

**Comment by peastman** [comment]
Two parts of this have already been implemented (the `drudeMass` option and velocity initialization).  I'm now looking into the remaining two parts.

Providing default values for the Drude temperature and friction seems reasonable, but there's a problem.  All arguments with default values must come after all arguments without default values.  Those two arguments come before the step size, which I don't think we can reasonably provide a default value for.  We could reorder the arguments, but that would break backward compatibility, which shouldn't be done without a very good reason.

Regarding temperature reporting, I originally thought that could be done by StateDataReporter.  But aside from the inefficiency of doing it in Python, I realized it just wouldn't work.  When computing kinetic energy, many integrators first perform a half step update to the velocities.  We can't compute kinetic energy from the velocities that were returned in the State.  So instead I'm thinking about adding a `computeSystemTemperature()` method to DrudeIntegrator.  It would do the proper offsetting and compute the temperature of the system, ignoring the internal motion of each atom-drude pair.

**Comment by swails** [comment]
> Providing default values for the Drude temperature and friction seems reasonable, but there's a problem. All arguments with default values must come after all arguments without default values. Those two arguments come before the step size, which I don't think we can reasonably provide a default value for. We could reorder the arguments, but that would break backward compatibility, which shouldn't be done without a very good reason.

I *think* this can be done with [singledispatch](https://docs.python.org/3/library/functools.html#functools.singledispatch) (with some extra dressing added to the SWIG wrappers for this class).  Something like the following may work:

```python
class DrudeLangevinIntegrator:
    @singledispatch
    def __init__(self, temperature: float, frictionCoeff: float, drudeTemperature: float, drudeFrictionCoeff: float, stepSize: float):
        ...

    @__init__.register
    def _(self, temperature: float, frictionCoeff: float, stepSize: float):
        return self.__init__(temperature, frictionCoeff, <sensible_default>, <sensible_default>, stepSize)
```

That might get you backwards compatibility and sensible defaults.

**Comment by peastman** [comment]
The improved temperature reporting is implement in #3486.

**Comment by peastman** [comment]
`@singledispatch` chooses the implementation based on the type of the first argument.  Since both versions have the same type for their first argument, I don't think that would work?

**Comment by andysim** [comment]
[This paper](https://dx.doi.org/10.1021%2Fjp402860e) suggests 0.03, but it looks like [NAMD has a default](https://www.ks.uiuc.edu/Research/namd/2.14/ug/node27.html) of 0.025.  To make things even more confusing, [this more recent review](https://pubs.acs.org/doi/10.1021/acs.chemrev.5b00505) from the Drude devs suggests 0.02.  If I remember correctly, the hard wall distance should hardly ever be reached with appropriate polarizability parameters, and frequent visits to the hard wall distance are a sign that parameters need to be tweaked.  Assuming I remembered that correctly, erring on the side of a longer cutoff seems reasonable to me.

**Comment by peastman** [comment]
That first paper is unclear.  In the main text it says 0.3 A, but in the appendix where it gives more details about the hard wall constraint, it says 0.2 A.  According to [this paper](https://onlinelibrary.wiley.com/doi/10.1002/jcc.26795), CHARMM GUI also sets it to 0.2 A.  The [CHARMM documentation](https://academiccharmm.org/documentation/version/c45b2/drude) doesn't specifically recommend a value, but 0.2 A is the value it uses in the example.  I'm thinking that seems like the best value to use a default?

**Comment by swails** [comment]
> `@singledispatch` chooses the implementation based on the type of the first argument. Since both versions have the same type for their first argument, I don't think that would work?

That's true, I tested it and it won't work.  However, the [multipledispatch](https://github.com/mrocklin/multipledispatch/) project does work, and requires only `six`.

```python
>>> from multipledispatch import dispatch
>>> @dispatch(float, float)
... def func(a: float, b: float) -> bool:
...     print("Called the 2-arg version")
...     return False
... 
>>> @dispatch(float, float, float)
... def func(a, b, c):
...     print("Called the 3-arg version")
...     return True
... 
>>> func(1.0, 2.0, 3.0)
Called the 3-arg version
True
>>> func(1.0, 2.0)
Called the 2-arg version
False
```

**Comment by jing-huang** [comment]
> 

Yes I would like to confirm that 0.02 nm would be most appropriate for being the default value. We also try to consistently mention this in Drude development papers.

**Comment by peastman** [comment]
Thanks!  I'll make that the default.

**Comment by peastman** [comment]
A correction: DrudeNoseHooverIntegrator isn't actually a subclass of DrudeIntegrator.  That's why it needs to provide the accessors itself.  But it still doesn't seem to actually use the value you set.

**Comment by Olllom** [comment]
The `DrudeNoseHooverIntegrator` uses the hard wall constraint but it is disabled by default (the value 0.0 corresponds to not using a hard wall). This behavior is tested [here](https://github.com/openmm/openmm/blob/a76c2de14b5a1ab604e95a5c4197e5a586e3000d/plugins/drude/tests/TestDrudeNoseHoover.h#L303).

I think the confusion comes from the fact that the regular `NoseHooverIntegrator` from the core API already provides Drude-like relative thermostating. It also implements a hard-wall constraint defined by `maxPairDistance`. 

The `DrudeNoseHooverIntegrator` from the plugin is just a thin wrapper that initializes the corresponding Nose-Hoover chains that should be used in the base class. To mimic the interface of the `DrudeLangevinIntegrator`, we defined `MaxDrudeDistance` accessors. If I recall correctly, they should just behave as aliases for `MaxPairDistance`.

**Comment by peastman** [comment]
Thanks for the clarification!  Since DrudeNoseHooverIntegrator doesn't subclass DrudeIntegrator, and since DrudeSCFIntegrator ignores the max distance, I'm thinking it would make sense to move the get/set methods from DrudeIntegrator to DrudeLangevinIntegrator?  Alternatively we could keep them where they are, but have DrudeSCFIntegrator throw an exception if you enable it.

Ideally DrudeSCFIntegrator probably should also enforce the max distance?  That would be complicated to implement, since I don't think the L-BFGS library supports constraints of that sort.  And really we probably should eventually replace using the generic optimizer with one specifically written for this purpose.  That would probably be a lot faster, as well as making it easier to implement this constraint.  But that's a big project, and I don't think DrudeSCFIntegrator gets used very much, which makes it a low priority.

**Comment by peastman** [comment]
The change to the default is in #3508.

**Comment by peastman** [comment]
Everything described above has now been added except for default values on the `drudeTemperature` and `drudeFrictionCoeff` arguments.  I think that one may be more trouble than it's worth, especially if it requires adding a new dependency.

Shall we close this issue?

**Comment by Olllom** [comment]
This is great!
I played around with it a bit and it all looks good to me. Everything works very smoothly.

The only feature that I was missing was a simple way to monitor the Drude temperature (see #3512).
From my end, this issue can be closed.
