### ISSUE TITLE
Using GAFF and SMIRNOFF small molecule force fields in OpenMM

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#2515]
I've finally finished up an updated AMBER biopolymer force field conversion (based on AmberTools 10.9) and new residue template generators for small molecules that supports GAFF 1.x and 2.x and the Open Force Field Initiative [SMIRNOFF force fields](http://openforcefield.org). Check it out and see what you think:

https://github.com/choderalab/openmm-forcefields

I'd be happy to move this to the `openmm` github org if we think this would be useful!

**Comment by peastman** [comment]
Very nice!  It's up to you, whichever org you think is most appropriate.

**Comment by jchodera** [comment]
I'd love to consolidate OpenMM tools and plugins into the http://github.com/openmm org. I'll transfer it then!

**Comment by jchodera** [comment]
It's been transferred: https://github.com/openmm/openmm-forcefields

I'll need to do a bit of work to get all of the CI paths etc. updated.
