### ISSUE TITLE
Intel icpc compiler reports unsupported -R flag

### ISSUE THREAD

**Issue by frank-stonybrook** [openmm/openmm#2519]
Dear OpenMM developers,

I am trying to compile OpenMM (7.4.1) using intel/19.0.5 compile and python3.7. During the **Make PythonInstall** process, it reported a error:
<img width="1280" alt="Screen Shot 2020-01-11 at 14 20 40" src="https://user-images.githubusercontent.com/10855977/72209569-e96ccf00-347d-11ea-9f13-df7d045031c3.png">

Best,
Cong

**Comment by frank-stonybrook** [comment]
When I ran **python -c "import simtk.openmm as mm"**, it gives the error "_ZNK6OpenMM16CustomHbondForce17getEnergyFunctionB5cxx11Ev undefined".

**Comment by peastman** [comment]
I haven't used the Intel compiler, but I'm going to guess this is related to the GCC dual ABI: https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html  The symbol it's looking for contains the substring `cxx11`, which indicates the new ABI.  Did the Intel compiler use the old ABI for compiling libOpenMM.so?

If that's not the issue, try using `nm` to list the symbols in libOpenMM.so.  Perhaps it's using a different name mangling or something like that?

**Comment by frank-stonybrook** [comment]
Sorry, Peter. I am lost... I had no experience with ABI/intel compiler. I have to ask for very detail instructions. 
> The symbol it's looking for contains the substring cxx11, which indicates the new ABI.

Which symbol? Which file should I looking for?

> Did the Intel compiler use the old ABI for compiling libOpenMM.so?

How should I check the version of ABI the compiler use when compiler libOpenMM.so? 
I just ran ldd on it. Here is the output:
<img width="834" alt="Screen Shot 2020-01-13 at 16 59 13" src="https://user-images.githubusercontent.com/10855977/72295750-2bd11000-3626-11ea-947e-6e4b14b0ef05.png">

Thanks for you help.

**Comment by peastman** [comment]
Try this command:

```
nm -D libOpenMM.so
```

Search the output for a line containing the strings "CustomHbondForce" and "getEnergyFunction".  The Python wrapper expects to find a symbol `_ZNK6OpenMM16CustomHbondForce17getEnergyFunctionB5cxx11Ev`.  But perhaps the library was compiled with a different ABI, in which case there will be a symbol similar to that but not identical.

GCC 5.1 introduced a new ABI, which changed how it generates symbol names for C++ methods.  If the library was compiled with the old naming system, but the Python wrapper uses the new one, you'll get a linking error.

**Comment by frank-stonybrook** [comment]
Hi Peter, 

I think you are right. When I ran the following command on libOpenMM.so:
`nm  -D libOpenMM.so|grep -i CustomHbondForce|grep -i getEnergy`
I got something like this:

> 00000000002b4f20 T openmm_customhbondforce_getenergyfunction_
00000000002a5150 T OpenMM_CustomHbondForce_getEnergyFunction
00000000002b4f90 T OPENMM_CUSTOMHBONDFORCE_GETENERGYFUNCTION
**000000000010ae20 T _ZNK6OpenMM16CustomHbondForce17getEnergyFunctionEv**

When I check the make file, the CXX compiler is a different one:
<img width="513" alt="Screen Shot 2020-01-13 at 17 26 42" src="https://user-images.githubusercontent.com/10855977/72297491-0a722300-362a-11ea-985a-e519c6a958ba.png">

And its version is 4.8.5

**Comment by peastman** [comment]
So you were actually compiling with an old GCC, not with ICC?  You can change`CMAKE_CXX_COMPILER` to point to the compiler you want to use.  Unless there's a reason you really need to use ICC, I would install the latest version of Clang or GCC.

**Comment by frank-stonybrook** [comment]
Right, I am also confused. It seems that the "make PythonInstall" and the "make" choose different compilers (icc and c++ respectively). If I understood correctly, change `CMAKE_CXX_COMPILER` will fix the compiler used for compiling the c++ code. But what about the compiler used when running "make PythonInstall"? Is there any variable to fix that? Thanks!

**Comment by peastman** [comment]
When you type `make PythonInstall`, that's really just a shortcut for setting a few environment variables and then running setup.py.  The choice of compiler for the Python module is all handled by distutils.  I believe you can customize that by setting the environment variable `CC`.

**Comment by frank-stonybrook** [comment]
Good to know, Thanks! I will try the way you suggested.

**Comment by frank-stonybrook** [comment]
Finally able to compile OpenMM by using icc and icpc compiler. Thanks for your help and you can close this ticket now.
