### ISSUE TITLE
Exception: updateParametersInContext: The number of non-excluded exceptions has changed

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#252]
@pgrinaway and I are working on the constant-pH methodology again over in https://github.com/choderalab/openmm-constph

We are running into an issue where it seems that setting the `chargeprod` or `epsilon` parameters (we're not sure which yet) in a `System` object to/from 0.0 via `updateParametersInContext` causes the following error:

```
Exception: updateParametersInContext: The number of non-excluded exceptions has changed
```

This is presumably because OpenMM is internally determining _exclusions_ via `chargeprod` or `epsilon` parameters set identically to 0.0, and we are trying to change the _number_ of such 0.0 parameters via `updateParametersInContext`, which is currently not allowed.

For us, it would be better if this _was_ allowed, if there is some easy way to manage this.

For now, setting parameters to a small number instead of zero---such as `sys.float_info.epsilon`---seems to work, but I would consider this an "ugly hack" awaiting a more permanent solution.

**Comment by aizvorski** [comment]
@peastman I think I ran into the same issue with latest openmm=7.7

> Once you've created the Context, you can then change the parameters for that exception to whatever you want, either zero or nonzero.

It seems that changing nonzero->zero exception parameters causes an error as well

Minimum reproducible example:

```
import openmm as mm
from openmm import app
from openmm import unit

print(mm.__version__)
# 7.7

forcefield = app.ForceField("amber14-all.xml", "amber14/tip3pfb.xml")
pdb = app.PDBFile('alanine-dipeptide-implicit.pdb')
system = forcefield.createSystem(pdb.topology, nonbondedMethod=app.NoCutoff)
positions = pdb.getPositions(asNumpy=True)

nonbonded_force = [force for force in system.getForces() if isinstance(force, mm.NonbondedForce)][0]

integrator = mm.LangevinMiddleIntegrator(300*unit.kelvin, 1.0/unit.picoseconds, 4.0*unit.femtoseconds)
context = mm.Context(system, integrator)
context.setPositions(positions)

# get exception that happens to be nonzero in nonbonded force as created by forcefield
idx = 10
p1, p2, chargeprod, sigma, epsilon = nonbonded_force.getExceptionParameters(idx)
print(p1, p2, chargeprod, sigma, epsilon)
# 0 5 -0.053145975 e**2 0.2804727344449416 nm 0.12012161257658839 kJ/mol

# change the values to other nonzero values - this works
nonbonded_force.setExceptionParameters(idx, p1, p2, 0.5*chargeprod, sigma, 0.5*epsilon)
nonbonded_force.updateParametersInContext(context)

# change the values to zero values - this fails
nonbonded_force.setExceptionParameters(idx, p1, p2, 0, sigma, 0)
nonbonded_force.updateParametersInContext(context)
# OpenMMException: updateParametersInContext: The number of non-excluded exceptions has changed
```

**Comment by peastman** [comment]
I posted that in 2013.  I'm not surprised if the behavior has changed since then.  A lot of internals have changed in that time.  Let's not resurrect long closed issues.

**Comment by aizvorski** [comment]
@peastman Wow, that was a long time ago - just came up from googling.

Is this a thing that should be a new issue, or expected behavior?  If expected, how would one change the exception parameters in this case - does it require creating a new context or is there a way to avoid that?

**Comment by peastman** [comment]
This is expected behavior.  You would have to call `reinitialize(True)` on the Context.  It's just as slow as creating a new Context, but at least it keeps your code simpler.
