### ISSUE TITLE
Slow OpenCL performance on MacBook Pro (Vega 20 GPU)

### ISSUE THREAD

**Issue by tristanic** [openmm/openmm#2525]
A colleague using ISOLDE on his 2018 MacBook Pro reports glacially slow MD performance. Currently, ISOLDE just relies on OpenMM (currently 7.4.0.dev-b71e92d) to pick the fastest available GPU, but I suspect this might be misfiring here. From his description the speed is about the same as what I get on my MacBook Air, so the most likely explanation is that it's choosing to run on the onboard Intel GPU rather than the Radeon...

Unfortunately I don't have easy access to a high-end MacBook Pro to test on (but will ask around). Any advice? My first thought is to do a custom build with the constructor for `OpenCLContext` reporting its decision-making process to stdout, and ask him to run it.

**Comment by tristanic** [comment]
Well, I went ahead and added some logging, and found a colleague with a 2016-model 15" MacBook Pro (Radeon Pro 455 2 GB, Intel HD Graphics 530 1536 MB). From the results, it seems like one (or both) of these cards is mis-reporting its capabilities:

```
Using single precision...
Querying devices for platform vendor: Apple
Checking device Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
Checking device Intel(R) HD Graphics 530
Maximum work item size: 256
Maximum compute units: 24
Clock frequency: 1050
Device speed: 201600
Checking device AMD Radeon Pro 455 Compute Engine
Maximum work item size: 256
Maximum compute units: 12
Clock frequency: 300
Device speed: 28800
Chose platform: Apple
Chose device: Intel(R) HD Graphics 530
Using single precision...
Querying devices for platform vendor: Apple
Checking device Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
Checking device Intel(R) HD Graphics 530
Maximum work item size: 256
Maximum compute units: 24
Clock frequency: 1050
Device speed: 201600
Checking device AMD Radeon Pro 455 Compute Engine
Maximum work item size: 256
Maximum compute units: 12
Clock frequency: 300
Device speed: 28800
Chose platform: Apple
Chose device: Intel(R) HD Graphics 530
```

Also, this output suggests that the constructor is being called twice for one simulation. Is that expected behaviour? 

[OpenCLContext.cpp.zip](https://github.com/openmm/openmm/files/4065096/OpenCLContext.cpp.zip)

**Comment by tristanic** [comment]
I note that none of the code branches setting `processingElementsPerComputeUnit` are getting run, so it's defaulting to 8 (the Radeon has 64 SIMD processors per compute unit). The Radeon also seems to be under-reporting its clock frequency (300, should be 855). Thought this might be due to running on battery, but I checked and it was definitely plugged into power.

**Comment by peastman** [comment]
You can select the device to use by setting `DeviceIndex` when you create the Context, so try out the different devices and see how fast they are.  I have a 2015 Macbook Pro with both integrated Intel and discrete AMD GPUs.  It defaults to the Intel GPU, which at first I thought must be wrong.  But when I tested it I found it wasn't: for OpenCL, it really is faster than the discrete GPU!  The difference isn't very large though, and neither of them is all that much faster than the CPU platform.

**Comment by tristanic** [comment]
Interesting regarding the 2015 model! But according to the benchmark rankings at https://browser.geekbench.com/opencl-benchmarks, the Radeon Vega 20 (found in the 2018 model) should manage a bit over half the speed of the GTX 1070 (which does somewhere between 500-1000 timesteps per second on my standard test scenario, updating the model display every 50 timesteps) - GeekBench scores 25951 vs 45693. GeekBench score for the 2018-model onboard Intel GPU (UHD Graphics 630) is 4996 - not much different from the one in my 2015 MacBook Air (3996). So looks like things have changed a bit since 2015 - the Mac discrete GPUs are still a bit on the weak side, but they've moved forward substantially compared to the one in the 2015 MacBook Pro (the Radeon R9 M370X, GeekBench score 10352). 

ISOLDE does look for an optional environment variable (ISOLDE_DEVICE_INDEX) for people that want to specify a particular GPU. I haven't really documented it - mainly because my understanding is that the order in which any given system will list GPUs is undefined, so I'd prefer to add a proper GUI "choose-your-GPU" interface. Anyway, I've asked my colleague to try that - but he's in California and I'm in the UK, so I don't expect to hear back immediately.

**Comment by tristanic** [comment]
Well, I heard from another colleague with a 2017 MacBook Pro (which would be using the Radeon Pro 555). Seems on that model it's still as you said: performance on the Radeon is still much the same as on the Intel GPU. Rather a sad state of affairs, considering the price tag on those things.

**Comment by tristanic** [comment]
For what it's worth, though: for my systems (MDFF plus a handful of other custom forces), on my MacBook Air the OpenCL platform is around 50 times faster than CPU using 4 threads (1-2 coordinate updates per second vs 1 every 30 seconds, with 50 timesteps between coordinate updates).

**Comment by tristanic** [comment]
I think there may be a problem in the block at https://github.com/openmm/openmm/blob/1097780040d575e989578ab117ee527fadd2161e/platforms/opencl/src/OpenCLContext.cpp#L210-L251. Like the code for choosing the GPU at https://github.com/openmm/openmm/blob/1097780040d575e989578ab117ee527fadd2161e/platforms/opencl/src/OpenCLContext.cpp#L132-L153 this relies on the presence of the AMD APP SDK, which isn't provided by Apple. The upshot is that `numThreadBlocksPerComputeUnit` falls back to the default (6), but these newer cards all seem to have 4 SIMDs per compute unit so it should probably be 24.

**Comment by peastman** [comment]
For what it's worth, I find that even high end AMD cards are slower than Nvidia ones for compute.  If you compare two GPUs that are supposed to be equivalent according to graphics benchmarks, OpenMM runs only about half as fast on the AMD one.  I don't know why.

> on my MacBook Air the OpenCL platform is around 50 times faster than CPU

That sounds like your system must use some force that isn't optimized for CPU?  For typical systems the difference shouldn't be nearly that big.

> The upshot is that numThreadBlocksPerComputeUnit falls back to the default (6)

You could try experimenting with larger values.  I'd be surprised if it made that big a difference though.

**Comment by tristanic** [comment]
That's what I was finding a bit weird: the GeekBench numbers I cited above (which are supposed to be linear with respect to speed) are aggregate scores across a range of compute-specific benchmarks (particle physics, FFTs, face detection, etc. - see https://www.geekbench.com/doc/geekbench5-compute-workloads.pdf). But it turns out that if you search for specific results you can break down the score into different components - and the older Radeons perform terribly for OpenCL particle-physics simulations (see https://browser.geekbench.com/v5/compute/434954 for the Radeon Pro 555, compared to a GTX 1050 Ti - https://browser.geekbench.com/v5/compute/435191). Interestingly, using Metal the same benchmark on th 555 is *much* faster: https://browser.geekbench.com/v5/compute/435155.

The possibly-good news is that the Vega 20 (in the 2019 MacBook Pro) seems to have caught up in a big way: https://browser.geekbench.com/v5/compute/434672. That one's almost twice as fast using Metal, too: https://browser.geekbench.com/v5/compute/434500.

With regard to CPU vs GPU, my standard list of forces is below. CPU-vs-GPU performance isn't all that important to me, though - given that my application's all about interactivity, the GPU is pretty much a necessity. 
```
[<simtk.openmm.openmm.HarmonicBondForce; proxy of <Swig Object of type 'OpenMM::HarmonicBondForce *' at 0x7f3b44cf1bd0> >,
 <simtk.openmm.openmm.HarmonicAngleForce; proxy of <Swig Object of type 'OpenMM::HarmonicAngleForce *' at 0x7f3b44cf1570> >,
 <simtk.openmm.openmm.PeriodicTorsionForce; proxy of <Swig Object of type 'OpenMM::PeriodicTorsionForce *' at 0x7f3b44cf1db0> >,
 <simtk.openmm.openmm.NonbondedForce; proxy of <Swig Object of type 'OpenMM::NonbondedForce *' at 0x7f3b44cf1210> >,
 <simtk.openmm.openmm.CMAPTorsionForce; proxy of <Swig Object of type 'OpenMM::CMAPTorsionForce *' at 0x7f3ac0580570> >,
 <simtk.openmm.openmm.CustomExternalForce; proxy of <Swig Object of type 'OpenMM::CustomExternalForce *' at 0x7f3ac0580f00> >,
 <simtk.openmm.openmm.CustomExternalForce; proxy of <Swig Object of type 'OpenMM::CustomExternalForce *' at 0x7f3ac0580ea0> >,
 <simtk.openmm.openmm.CustomBondForce; proxy of <Swig Object of type 'OpenMM::CustomBondForce *' at 0x7f3ac0580150> >,
 <simtk.openmm.openmm.CustomBondForce; proxy of <Swig Object of type 'OpenMM::CustomBondForce *' at 0x7f3ac0580fc0> >,
 <simtk.openmm.openmm.CustomTorsionForce; proxy of <Swig Object of type 'OpenMM::CustomTorsionForce *' at 0x7f3ac05803c0> >,
 <simtk.openmm.openmm.CustomTorsionForce; proxy of <Swig Object of type 'OpenMM::CustomTorsionForce *' at 0x7f3ac05800c0> >,
 <simtk.openmm.openmm.CustomCompoundBondForce; proxy of <Swig Object of type 'OpenMM::CustomCompoundBondForce *' at 0x7f3ac0580d20> >,
 <simtk.openmm.openmm.CustomGBForce; proxy of <Swig Object of type 'OpenMM::CustomGBForce *' at 0x7f3ac05801b0> >]
```

**Comment by peastman** [comment]
> Interestingly, using Metal the same benchmark on th 555 is much faster: 

That's interesting.  I suspected the difference might have more to do with AMD's compiler than with the hardware.  It sounds like that's the case.

**Comment by askusay** [comment]
I tried benchmark.py script on the new MacBook Pro with Radeon 5500M graphics which is around 20% faster than vega 20 https://browser.geekbench.com/v5/compute/482949, results below:

```
Platform: OpenCL
Precision: single
Device: 2

Test: gbsa
Step Size: 2 fs
Integrated 30076 steps in 59.4133 seconds
87.4742 ns/day

Test: rf
Step Size: 2 fs
Integrated 17467 steps in 59.6756 seconds
50.5784 ns/day

Test: pme (cutoff=0.9)
Step Size: 2 fs
Integrated 12501 steps in 60.1949 seconds
35.8863 ns/day

Test: apoa1rf
Step Size: 2 fs
Integrated 5094 steps in 61.1917 seconds
14.385 ns/day

Test: apoa1pme
Step Size: 2 fs
Integrated 2870 steps in 54.7476 seconds
9.05859 ns/day

Test: apoa1ljpme
Step Size: 2 fs
Integrated 2383 steps in 57.0785 seconds
7.21432 ns/day
```

I have also attached the Intel CPU and OpenCL performance for comparison, in brief CPU is faster than intel OpenCL for most tests, but the 5500M OpenCL is around 2-4 times faster than either. (The amoeba test did not run in OpenCL and for CPU it only used 1 CPU core)

Given that the 5500M gets just [under half](https://browser.geekbench.com/v5/compute/482747) the OpenCL performance of a 1080 Ti, I would expect it to be much faster... I may try to install OpenMM windows on this laptop to see if this is a Mac specific issue.

Let me know if there are any tests you would like me to try
[MBP_16_Intel_Core i9-9880H_CPU.txt](https://github.com/openmm/openmm/files/4142064/MBP_16_Intel_Core.i9-9880H_CPU.txt)
[MBP_16_Intel_Core i9-9880H_OpenCL.txt](https://github.com/openmm/openmm/files/4142065/MBP_16_Intel_Core.i9-9880H_OpenCL.txt)

**Comment by peastman** [comment]
Closing this issue since it didn't lead to any action items.

**Comment by philipturner** [comment]
Citing https://github.com/openmm/openmm/issues/2525#issuecomment-575139121:

That is probably tanking performance (on both AMD and M1), and I've made a workaround in my Metal fork. We need to detect that GCN has 4x16 SIMDs and RDNA has 2x32 SIMDs. Metal seems to treat both as 1x64 SIMDs, such I just scanned the device's name for:

```cpp
std::string rdnaGPUs = {
    "5300", "5500", "5600", "5700", "5800",
    "6300", "6400", "6500", "6600", "6700", "6800", "6900",
    "6350", "6450", "6550", "6650", "6750", "6850", "6950",
    "7300", "7400", "7500", "7600", "7700", "7800", "7900",
    "7350", "7450", "7550", "7650", "7750", "7850", "7950",
};
```
I still haven't tested this works, but perhaps we could re-open this issue?
