### ISSUE TITLE
Setup Ligand-protein complex on NTP esemble production 

### ISSUE THREAD

**Issue by geo25** [openmm/openmm#2536]
i have set system (protein-ligand + solvent + ions complex) on gromacs,
and want run following setup md:

1. NVT esemble heating temperature from 0 to 310 K during 5 ns using
harmonic restraint (5 Kcal/mol energy) to backbone protein and heavy
atoms from ligand.

2. NPT esemble relaxed  restrainst from 5 Kcal/mol to 0 during 10 ns
using barostat a 1 atm.

Please help me, for set this. my question is if rRESPA is same
integrator used in NAMD package? and if can use for integration only
production.

my python script is:
--------------------------------------------------------------------------------------
#!/usr/bin/env python
from __future__ import division, print_function

import sys

# OpenMM Imports
import simtk.openmm as mm
import simtk.openmm.app as app

# ParmEd Imports
from parmed import load_file
from parmed.openmm.reporters import NetCDFReporter
from parmed import unit as u

# Load the Gromacs files
print('Loading Gromacs files...')
top = load_file('topol.top')
gro = load_file('solv_ions.gro')

# Transfer the unit cell information from the GRO file to the top object
top.box = gro.box[:]

# Create the OpenMM system
print('Creating OpenMM System')
system = top.createSystem(nonbondedMethod=app.PME,
                          nonbondedCutoff=8.0*u.angstroms,
                          constraints=app.HBonds, rigidWater=True, ewaldErrorTolerance=0.0005
)

##; Harmonic restraind 
#force = mm.CustomExternalForce("k*((x-x0)^2+(y-y0)^2+(z-z0)^2)")
#force.addGlobalParameter("k", 5.0*kilocalories_per_mole/angstroms**2)
#force.addPerParticleParameter("x0")
#force.addPerParticleParameter("y0")
#force.addPerParticleParameter("z0")
#for i, atom_crd in enumerate(parm.positions):
#    if parm.atoms[i].name in ('CA', 'C', 'N'):
#        force.addParticle(i, atom_crd.value_in_unit(u.nanometers))
#system.addForce(force)

# Create the integrator to do Langevin dynamics
integrator = mm.LangevinIntegrator(
                        300*u.kelvin,       # Temperature of heat bath
                        1.0/u.picoseconds,  # Friction coefficient
                        2.0*u.femtoseconds, # Time step
)
integrator.setConstraintTolerance(0.00001)

# Define the platform to use; CUDA, OpenCL, CPU, or Reference. Or do not specify
# the platform to use the default (fastest) platform
platform = mm.Platform.getPlatformByName('CUDA')
prop = dict(CudaPrecision='double') # Use mixed single/double precision

# Create the Simulation object
sim = app.Simulation(top.topology, system, integrator, platform, prop)

# Set the particle positions
sim.context.setPositions(gro.positions)

# Minimize the energy
print('Minimizing energy')
sim.minimizeEnergy(maxIterations=5000)

##; Equlibration
sim.context.setVelocitiesToTemperature(300*u.kelvin)
print('Equilibrating... in NVT')
simulation.step(100)

print ('Equilibrating... in NpT')
barostat = mm.MonteCarloBarostat(1.0*u.bar, 300.0*u.kelvin, 50)
system.addForce(barostat)
simulation.step(500)

# Set up the reporters to report energies and coordinates every 100 steps
sim.reporters.append(
        app.StateDataReporter(sys.stdout, 100, step=True, potentialEnergy=True,
                              kineticEnergy=True, temperature=True, 
                              totalSteps=1000000, separator='\t'))

sim.reporters.append(app.DCDReporter('lyz_jz4.dcd', 1000))

# Run dynamics
print('Running dynamics')
sim.step(1000000)

**Comment by peastman** [comment]
> my question is if rRESPA is same integrator used in NAMD package?

I haven't used NAMD, but if they offer a rRESPA integrator that should be the same thing.

The following lines in your script won't work correctly:

```python
system.addForce(barostat)
simulation.step(500)
```

When you create a Context, it copies out all information it needs from the System.  After that, making changes to the System has no effect on the existing Context.  You can force it to rebuild its internal data structures and pick up the changes with this line:

```python
sim.context.reinitialize(preserveState=True)
```

**Comment by geo25** [comment]
How can  increasing temperature from 50 k to 30
10k in intervals of 5k during 5 ns?

How can set restraints harmonics for backbone and heavy atoms of ligand
using 5 kcal/mol. Into nvt ese ble and decrement 5 kcal/mol to 0 during 10
ns using npt esemble.

Please help me.

**Comment by peastman** [comment]
> How can  increasing temperature from 50 k to 30 10k in intervals of 5k during 5 ns?

Call `setTemperature()` on the integrator.  See http://docs.openmm.org/latest/userguide/application.html#simulated-annealing for an example that's very similar to that.

> How can set restraints harmonics for backbone and heavy atoms of ligand
using 5 kcal/mol. Into nvt ese ble and decrement 5 kcal/mol to 0 during 10
ns using npt esemble.

Since your CustomExternalForce uses a global parameter to set the strength of the restraints, you can set that parameter:

```python
sim.context.setParameter('k', value_of_k)
```

By the way, instead of writing your force as

```python
force = mm.CustomExternalForce("k*((x-x0)^2+(y-y0)^2+(z-z0)^2)")
```

it's better to write it as

```python
force = mm.CustomExternalForce("k*periodicdistance(x, y, z, x0, y0, z0)^2")
```

See the discussion of this at http://docs.openmm.org/latest/api-c++/generated/OpenMM.CustomExternalForce.html#_CPPv2N6OpenMM19CustomExternalForceE.
