### ISSUE TITLE
Velocity distribution of Drude lone pairs

### ISSUE THREAD

**Issue by JavaAmyDeng** [openmm/openmm#2537]
Hi!

When I ran Drude simulation in OpenMM, the velocity distribution of lone pairs seems to be incorrect.

![The velocity distribution of drude lone pairs](https://user-images.githubusercontent.com/18480932/73232307-ccf4b600-4150-11ea-98a4-f11d362d2e43.png)

Is this distribution supposed to be Gaussian? Any suggestions/comments are greatly appreciated!

**Comment by peastman** [comment]
Are you talking about Drude particles or lone pairs (which are typically represented as virtual sites)?

Assuming you really mean Drude particles, are you using the DrudeLangevinIntegrator?  The distribution could be a little odd.  The Drude particles (or more precisely, the relative coordinate of each atom-Drude pair) are kept in contact with a heat bath at low temperature, typically around 1K.  But they also interact with the rest of the system, which is at a much higher temperature.  So there's a constant flow of energy from the high temperature thermostat, to the atoms, to the Drude coordinates, and out into the low temperature thermostat.

What is shown in your graph?  Is that the absolute velocity of Drude particles?  Or their relative velocity with respect to their parent atoms?  Or then again, is that actually showing virtual sites?

**Comment by JavaAmyDeng** [comment]
Thanks for your reply! The graph shows the velocity distribution of lone pairs along x, y, and z axises. I saved the velocity using `simulation.context.getState(getVelocities=True)` from a simulation so it should be absolute velocity. I just checked the source code of `CharmmPsfFile()` and indeed all lone pairs are set to be virtual sites.

I am using `DrudeLangevinIntegrator()` in which drude particles are at 1 K and non-drude particles are at 303.15 K.

**Comment by peastman** [comment]
In equilibrium, you expect the kinetic energy of each independent degree of freedom to follow a Boltzmann distribution.  That means different degrees of freedom will have different velocities.  A light particle will move faster than a heavy one.

Virtual sites are not independent degrees of freedom.  They have zero mass (and therefore zero kinetic energy).  Their velocities are (possibly nonlinear) functions of the massive particles they're computed from.  So the velocity of any virtual site depends both on the mass of the particles it's computed from, and on the function used to compute it.

And of course, if you aren't looking at the system in equilibrium, you could get any kind of distribution at all.  It looks from the graph like the system was undergoing center of mass motion: most of the z velocities were negative.  If you collect data long enough to be sampling the equilibrium distribution, the average center of mass velocity should be zero.

**Comment by JavaAmyDeng** [comment]
Thanks for the clear explanation. I actually didn't find how OpenMM calculate the velocity of the virtual sites but I assume that the velocity of virtual sites should have more reasonable distribution than my result, right?

The data on the graph comes from a 90ns simulation. The system has ~23k atoms, including water, counterions, a short peptide, drude particles, and lone pairs. The velocity distributions of both drude and nondrude particles are as follows:
![velocity_dist_drudeparticles](https://user-images.githubusercontent.com/18480932/73308462-54dccd80-41ee-11ea-8b0c-0e0712f6975d.png)

![velocity_dist_nondrudeparticles](https://user-images.githubusercontent.com/18480932/73308475-5dcd9f00-41ee-11ea-9292-31e3aec63d24.png)

I think they look pretty normal but just cannot figure out what's going on with lone pairs.

**Comment by peastman** [comment]
> I actually didn't find how OpenMM calculate the velocity of the virtual sites

I don't think it does.  The integrator totally ignores any particle whose mass is zero, so whatever its velocity is set to, the integrator doesn't change it.  Those velocities are probably just left over from however you initialized your system.

**Comment by peastman** [comment]
I don't know what you mean by "dimension".  The integrator doesn't change the velocities of virtual sites.  You can set them to whatever values you want.  They won't affect the simulation, and they'll still be the same at the end.

**Comment by JavaAmyDeng** [comment]
by 'dimension', I mean x, y, z axises. Sorry for confusion.

If I understand your comments correctly, it would be less useful to look at the distribution of virtual sites velocities. The purpose of this test simulation is to make sure my set-up for Drude simulation is correct. If the velocity of virtual sites doesn't affect the simulation, could I just ignore the seemingly abnormal velocities? Or what else could I look at to ensure that the lone pairs behave correctly?

**Comment by peastman** [comment]
> If I understand your comments correctly, it would be less useful to look at the distribution of virtual sites velocities.

Not just less useful.  They're totally meaningless.  They have no connection to anything happening in the simulation.  Those values are just whatever values you happened to initialize them to at the start.

> Or what else could I look at to ensure that the lone pairs behave correctly?

They aren't real degrees of freedom.  Their positions are just calculated at each step based on the positions of a set of other atoms.  They can't really "behave" correctly or incorrectly, because they have no behavior of their own.  Instead, you want to look at the real particles.

**Comment by JavaAmyDeng** [comment]
It makes sense to me. Thanks a lot!
