### ISSUE TITLE
Project board for 7.5

### ISSUE THREAD

**Issue by peastman** [openmm/openmm#2540]
I've created a project board to track changes for OpenMM 7.5.  https://github.com/openmm/openmm/projects/1.  Let me know if there are other features or bug fixes you think we should target for 7.5.

**Comment by jchodera** [comment]
How quickly could we cut a new release with the SMORNOFF trefoil impropers support? Would that be 7.4.2 or 7.5?

**Comment by peastman** [comment]
That's a new feature, so it would be 7.5.  I don't think any severe bugs have come up since 7.4.1 that would require another patch.  If you're anxious to get that feature out soon, we could start the push to finish up 7.5.

**Comment by jchodera** [comment]
A push to get 7.5 out soon would be superb.

**Comment by jchodera** [comment]
@peastman: I've added https://github.com/openmm/openmm/pull/2511 to the 7.5 project board, where it is awaiting triage (which just means you need to add it to the "Done" column).

**Comment by jchodera** [comment]
It also occurs to me that we should probably be using [release milestones](https://help.github.com/en/github/managing-your-work-on-github/about-milestones) for upcoming releases and [project boards](https://help.github.com/en/github/managing-your-work-on-github/about-project-boards) for upcoming major features or papers. Maybe we can switch after 7.5?

**Comment by peastman** [comment]
I'm looking at the project board right now, and #2511 isn't there anywhere?

**Comment by peastman** [comment]
Ok, found it.
