### ISSUE TITLE
OpenCL fails in newer Fedora distros

### ISSUE THREAD

**Issue by tristanic** [openmm/openmm#2541]
Just updated my laptop (with GTX 1070) to Fedora 31 (since 29 is already EOL - sigh...) and ran into trouble starting simulations on the OpenCL platform (also had the same issue when I upgraded to 29, for the record):

```
  File "/opt/UCSF/ChimeraX-daily/lib/python3.7/site-packages/simtk/openmm/app/simulation.py", line 105, in __init__
    self.context = mm.Context(self.system, self.integrator, platform, platformProperties)
  File "/opt/UCSF/ChimeraX-daily/lib/python3.7/site-packages/simtk/openmm/openmm.py", line 11125, in __init__
    this = _openmm.new_Context(*args)
Exception: Error initializing context: clGetDeviceIDs (-1)

Exception: Error initializing context: clGetDeviceIDs (-1)
```
Turns out the problem is that these newer distros all seem to have mesa-libOpenCL installed by default - uninstalling it fixes the issue. But I'm wondering if your OpenCL code could catch the error and simply step on to the next platform (which in my case would have been the correct CUDA one)?

**Comment by peastman** [comment]
Sounds like a good idea.  Error -1 is `CL_DEVICE_NOT_FOUND`.  According to the docs, `clGetDeviceIDs()` returns that if no devices were found, which seems like a strange behavior rather than just returning 0 for the number of devices.  But yes, we should handle that correctly.
