### ISSUE TITLE
Isometric vs anisometric truncated octahedron box

### ISSUE THREAD

**Issue by gitkol** [openmm/openmm#2543]
Hi,

The newly released version 7.4.1 fixed a bug that prevented me from using truncated octahedron simulation boxes. Now that I am trying to use them routinely, a problem arose. I am preparing my simulation boxes with Amber, and Amber allows me to generate isometric or anisometric boxes. It seems that I can use OpenMM with isometric truncated octahedron boxes, but not with anisometric ones. In some cases the latter would be advantageous, because it can work with much fewer atoms. I attached the input files and a simple script to run both systems. The isometric system works fine, but the anisometric system gives an error message that I gather basically means that the box could not be converted to a triclinic box because the angle gamma=0. I wonder if this is because (some) anisometric truncated octahedron cannot be converted to triclinc, or it might be a bug. I tried many anisometric systems, but the error message was always the same.

```
$ python run-openmm-amber-input.py
Building system...
[Quantity(value=Vec3(x=8.08003909, y=0.0, z=0.0), unit=nanometer), Quantity(value=Vec3(x=-2.6933461460146724, y=7.617933987222253, z=0.0), unit=nanometer), Quantity(value=Vec3(x=-2.6933461460146724, y=-3.808966532608644, z=6.597324623447236), unit=nanometer)]
Done

$ python run-openmm-amber-input.py
Traceback (most recent call last):
  File "run-openmm-amber-input.py", line 8, in <module>
    prmtop = AmberPrmtopFile('1W50-trunc-octa-aniso.parm7')
  File "/home/istvan/anaconda3/lib/python3.7/site-packages/simtk/openmm/app/amberprmtopfile.py", line 156, in __init__
    top.setPeriodicBoxVectors(computePeriodicBoxVectors(*(box[1:4] + box[0:1]*3)))
  File "/home/istvan/anaconda3/lib/python3.7/site-packages/simtk/openmm/app/internal/unitcell.py", line 59, in computePeriodicBoxVectors
    cy = c_length*(math.cos(alpha)-math.cos(beta)*math.cos(gamma))/math.sin(gamma)
ZeroDivisionError: float division by zero

```
If the anisometric truncated octahedron box can be used, is there a good way to prevent the protein from rotating?

Thank you very much for your help,

   Istvan

[aniso.tar.gz](https://github.com/openmm/openmm/files/4124852/aniso.tar.gz)

**Comment by peastman** [comment]
The box has to be isometric.  See http://docs.openmm.org/latest/userguide/theory.html#periodic-boundary-conditions for details on how triclinic periodic boxes are represented.  Do keep in mind this isn't a fundamental limitation: it's always possible to rotate your system to make the first vector lie along the x axis, and the second vector lie in the xy plane.

**Comment by gitkol** [comment]
OK, understood. Thanks
