### ISSUE TITLE
OpenCL Crash on Windows machine with hybrid Intel/NVIDIA GPU architecture

### ISSUE THREAD

**Issue by tristanic** [openmm/openmm#2546]
This was reported to me a while back, and appears identical to the discussion at https://www.daz3d.com/forums/discussion/243216/getting-a-fatal-error-on-launch-solved - the Intel OpenCL driver seems quite broken, appears in the queue in front of the Nvidia driver, and crashes with an access violation. Easiest solution is to just uninstall the Intel driver, but if there's a way to work around it, it might be worthwhile to do so.

[chimera_crash.evtx.zip](https://github.com/openmm/openmm/files/4133730/chimera_crash.evtx.zip)

**Comment by peastman** [comment]
How very irritating!
