### ISSUE TITLE
Illegal property name when using Platform.setPropertyValue, but getPropertyValue works

### ISSUE THREAD

**Issue by thesketh** [openmm/openmm#2547]
Hi all,

I ran into an issue trying to set the number of CPU threads used by a Simulation after it's been created. OpenMM Version is the CUDA 9.0 version installed from conda:

```python
>>> version.version
'7.4.1.dev-068f120'
```

Properties can be read using `platform.GetPropertyValue`, but can't be set using `platform.SetPropertyValue`. Trying to set property values raises `Exception: setPropertyValue: Illegal property name`, even though the property names are valid.

```python
>>> mm_platform = mm.Platform.getPlatformByName('CPU')
>>> sim = app.Simulation(topology, system, integrator, mm_platform)
>>> mm_platform.getPropertyValue(sim.context, 'Threads')
'80'
>>> mm_platform.setPropertyValue(sim.context, 'Threads', '20')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/users/travis/.modules/python/3.7/lib/python3.7/site-packages/simtk/openmm/openmm.py", line 18039, in setPropertyValue
    return _openmm.Platform_setPropertyValue(self, context, property, value)
Exception: setPropertyValue: Illegal property name
```

A workaround for this problem is to use `platform.SetPropertyDefaultValue` before creating the Simulation. As expected, this doesn't work after the simulation has been created

```python
>>> mm_platform = mm.Platform.getPlatformByName('CPU')
>>> mm_platform.setPropertyDefaultValue('Threads', '20')
>>> sim = app.Simulation(topology, system, integrator, mm_platform)
>>> sim.context.getPlatform().getPropertyValue(sim.context, 'Threads')
'20'
>>> sim.context.getPlatform().setPropertyDefaultValue('Threads', '40')
>>> sim.context.getPlatform().getPropertyValue(sim.context, 'Threads')
'20'
```

**Comment by peastman** [comment]
That is correct.  The number of threads has to be set before the simulation is created.  Once it's created, the number of threads is a read-only property.

An alternative to `setPropertyDefaultValue()` is to specify it directly when you create the simulation:

```python
sim = app.Simulation(topology, system, integrator, mm_platform, {'Threads':'20'})
```

**Comment by thesketh** [comment]
Thanks for your quick response, I suppose that makes sense. I initially tried using `mm_platform.setPropertyValue('Threads', '20')`, and the requirement for a Context is what led me to creating the simulation first. I'll probably use the property dict going forwards
