### ISSUE TITLE
Developer docs are not rendering to docs.openmm.org correctly

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#2559]
I just noticed that the new `BAOABLangevinIntegrator` is missing from the [developer docs](http://docs.openmm.org/development/api-python/library.html#integrators) accessed at the bottom of the http://docs.openmm.org webpage. Any idea why these aren't being pushed?

**Comment by peastman** [comment]
I'm working on it.  See https://github.com/rmcgibbo/sphinxcontrib-autodoc_doxygen/issues/18 and https://github.com/rmcgibbo/sphinxcontrib-autodoc_doxygen/pull/19.
