### ISSUE TITLE
The atom order in CudaIntegrateDrudeLangevinStepKernel

### ISSUE THREAD

**Issue by z-gong** [openmm/openmm#2562]
I'm trying to understand CudaIntegrateDrudeLangevinStepKernel, and I'm get confused about the order of atoms.
```
for (int i = blockIdx.x*blockDim.x+threadIdx.x; i < NUM_NORMAL_PARTICLES; i += blockDim.x*gridDim.x) {
        int index = normalParticles[i];
        mixed4 velocity = velm[index];
        if (velocity.w != 0) {
            mixed sqrtInvMass = SQRT(velocity.w);
            float4 rand = random[randomIndex+index];
            velocity.x = vscale*velocity.x + fscale*velocity.w*force[index] + noisescale*sqrtInvMass*rand.x;
            ...
        }
    }
```
There is an array `normalParticles`, which records the particle ids (based on the topology) of non-polarizable particles. But the atom order in CudaArray `velm` or `force` are not the same with the atom order in topology. So the `velm[index]` is not the velocity of index_th atom, is this correct? If so, how this kernel correctly distinguish non-polarizable particles and Drude pairs?

**Comment by peastman** [comment]
Take a look at http://docs.openmm.org/latest/developerguide/developer.html#reordering-of-particles.  It's talking about the OpenCL platform, but CUDA works the same way.  `velm` and `force` reflect the internal order after reordering the particles to improve spatial continuity.

The mapping between the two orderings is maintained by the CudaContext.  You can call `getAtomIndex()` to get a host array of the order, or `getAtomIndexArray()` to get a device array.

For example, here's the code used to retrieve velocities to return them to the user.

https://github.com/openmm/openmm/blob/484e6b99eddc47d66fa724f073b6dd2130313f7c/platforms/cuda/src/CudaKernels.cpp#L316-L327

It calls `getAtomIndex()` to retrieve the sorted indices and uses them to convert back to the original ordering.

**Comment by z-gong** [comment]
That's why I'm confused. I would expect the code to be like this. There is an `invAtomOrder` to convert the host index to device index, so that the correct atoms are reached
```
for (int i = blockIdx.x*blockDim.x+threadIdx.x; i < NUM_NORMAL_PARTICLES; i += blockDim.x*gridDim.x) {
        int indexHost = normalParticles[i];
        int indexDevice = invAtomOrder[indexHost];
        mixed4 velocity = velm[indexDevice];
        ......
}
```

**Comment by peastman** [comment]
It only reorders atoms in ways that don't affect those data structures.  DrudeForce makes sure of that.  So it will only swap a normal particle with another normal particle, and it will only swap a Drude particle with another identical Drude particle.

**Comment by z-gong** [comment]
If I understand correctly, during the reordering, only molecules with exactly the same topology and FF parameters will be swapped. So for a system made of one single polymer, the reorder will not happen?

**Comment by peastman** [comment]
Correct.  Reordering is mainly important for water molecules.

**Comment by z-gong** [comment]
Okay. Thanks!
