### ISSUE TITLE
Force to restrain the center of geometry to a fixed point in space

### ISSUE THREAD

**Issue by SimoneCnt** [openmm/openmm#2568]
I would like to have a force acting on the center of geometry of a group of atoms to restraint it to a fixed point in space (in this case the center of geometry of a reference structure). I'm using the `CustomCentroidBondForce` and it is working, but the problem is how to compute the distance using periodic boundary conditions.

```python
def AbsoluteCenterForce(reference_positions, restrained_atom_indices, force_constant, boxsize):
    comx, comy, comz = np.average(np.array(reference_positions.value_in_unit_system(unit.md_unit_system))[restrained_atom_indices], axis=0)
    #energy_expression = '(K/2)*((x1-xavg)^2+(y1-yavg)^2+(z1-zavg)^2);  ## Does not consider PBC
    #energy_expression = '(K/2)*(periodicdistance(x1, y1, z1, xavg, yavg, zavg)^2)';  ## periodicdistance not recognized
    energy_expression  = '(K/2) * (dx^2 + dy^2 + dz^2);'
    energy_expression += 'dx = abs(x1-xavg)-L*step(abs(x1-xavg)-L/2);'
    energy_expression += 'dy = abs(y1-yavg)-L*step(abs(y1-yavg)-L/2);'
    energy_expression += 'dz = abs(z1-zavg)-L*step(abs(z1-zavg)-L/2);'
    energy_expression += 'K = %f;' % force_constant.value_in_unit_system(unit.md_unit_system)
    energy_expression += 'xavg = %f;' % comx
    energy_expression += 'yavg = %f;' % comy
    energy_expression += 'zavg = %f;' % comz
    energy_expression += 'L = %f;' % boxsize.value_in_unit_system(unit.md_unit_system)
    restraint_force = openmm.CustomCentroidBondForce(1, energy_expression)
    restraint_force.addGroup(restrained_atom_indices, [1.0]*len(restrained_atom_indices))
    restraint_force.addBond([0])
    return restraint_force
```

I tried the `periodicdistance` from `CustomExternalForce`, but it looks like it is not available in `CustomCentroidBondForce`. So I did the trick with the `abs` and `step` functions, which is working fine, but the size of the box must be set beforehand and must be kept fixed (no barostat).

Is there a better way to compute the distance with PBC properly?

**Comment by peastman** [comment]
If you call `setUsesPeriodicBoundaryConditions(True)` on the CustomCentroidBondForce, the `distance()` function will take periodic boundary conditions into account.  It computes the distance between two groups, whereas you want the distance between one group and a fixed point in space.  But that's alright: just put a dummy particle at the fixed location.  Set its charge and epsilon to 0 so it won't interact with anything, and its mass to 0 to ensure it won't move.

**Comment by SimoneCnt** [comment]
This is also working, but it is far from an optimal solution.
I am creating the topology and system using charmm functions (`CharmmPsfFile`, `CharmmCrdFile`, `CharmmParameterSet`, `psf.createSystem`)
Then to add the dummy atom I have to: add the particle to the system; retrive the non-bonded force group and add the particle there; add a dummy chain, residue and atom to the topology; and finally add the coordinates of the dummy particle to the coordinates array. 
It is doable, but quite messy... The code to add the restraint is not anymore limited to the "add forces" section of my script, but I have to modify how to create the system and the simulation objects which are in different parts of the code. Let's call it a "semantic" problem.
Moreover, all outputs will contain the dummy particle, which makes analysis a bit more complicated since I need to have different topologies for different restraints. It will become worse if I need to add more restraints and more dummy particles. 
I think everything would be much easier if a function like `periodicdistance` would be available.

**Comment by peastman** [comment]
Agreed, that would certainly make things simpler in your case.  I'll mark this as a feature request.  We'll need to think about the design a bit.  How does it relate to the `distance()` function and to `setUsesPeriodicBoundaryConditions()`?  If the latter is set to false but your function uses `periodicdistance()`, is it actually periodic?  What does `getUsesPeriodicBoundaryConditions()` return?  There are opportunities for confusion that we'll need to be careful to avoid.

**Comment by peastman** [comment]
This is much easier in 7.6.  You can now use the `pointdistance()` function to compute the distance to a fixed point without needing to add a dummy atom.  @simonecnt is it ok to close this issue?

**Comment by peastman** [comment]
Great, thanks!  I'll go ahead and close this.

> Do I have to set setUsesPeriodicBoundaryConditions or not?

If you want it to use PBC when computing the distance then yes.

> Also, are the units correct? [x,y,z]avg and K are in "md_unit_system", not sure about x1,y1,z1.

That's correct.
