### ISSUE TITLE
performence drop when there are a lot of nonbonded exceptions

### ISSUE THREAD

**Issue by z-gong** [openmm/openmm#2571]
I had a similar problem as this issue #2113. In my system, there are a large number of massless particles. Their positions are updated with my own integrator. There's a possibility that some massless particles overlap with normal particles during the simulation, which causes the energy to be NaN although there is no interaction between them (The massless particles have epsilon equal to 0, and the overlapped particles have 0 charge).

Following the suggestion in that issue, I added exception and exclusion for nonbonded interactions between massless particles and those normal particles.
```
for force in system.getForces():
    if force.__class__.__name__ == 'CustomNonbondedForce':
        for i in range(1440):
            for j in range(11060, 20680):
                force.addExclusion(i, j)
    if force.__class__.__name__ == 'NonbondedForce':
        for i in range(1440):
            for j in range(11060,  20680):
                force.addException(i, j, 0, 0, 0)
```
However, the performance dropped significantly, from around 120 ns/day to 20 ns/day.

I'm wondering whether there is a more efficient way to prevent the energy to be NaN, considering that overlap is inevitable?

**Comment by peastman** [comment]
I've been thinking about this, but I haven't come up with any great solutions.  The best thing, of course, is if you can just make sure you never have two particles at exactly the same position.  But that may not be possible for you.

We could add an explicit check for this situation in the nonbonded code, but that would add overhead to every interaction, so I wouldn't want to do it as a general thing.  But you could do it with CustomNonbondedForce:

```
select(delta(r), 0, energy); energy=...
```

If `r` is exactly 0 that will set the interaction energy to 0.

**Comment by z-gong** [comment]
I use `CustomNonbondedForce` to handle LJ-12-6 and `NonbondedForce` to handle Coulomb interactions.

For the `CustomNonbondedForce`, I tried the `select` function, and it doesn't work. It still gives nan when particles overlap, is it possible that when r is very close to zero, the r^6 or r^12 is calculated to be zero because of precision? However, I could use `addInteractionGroup()` to eliminate the interactions between massless and normal particles without performance penalty.

For the `NonbondedForce` it is more confusing. At some step of the simulation, the `customNonbedForce` gives energy of nan, but `NonbondedForce` gives correct energy.

For now, I use `addInteractionGroup()` for `CustomNonbondedForce`, the simulation runs smoothly even without `addExcepion()` for `NonbondedForce`, which is weird...

I'll try to find a snapshot that `CustomNonbondedForce` fail but `NonbondedForce` does not.

**Comment by frank-stonybrook** [comment]
I also had a related question: given two sets of particles(~3000 atoms and ~100 atoms), what will be the best way in terms of performance concern to exclude the nonbonded interactions between these two set of atoms? After reading the OpenMM documents, it seems to me that `NonbondedForce.addException` and `CustomNonbondedForce.addExclusion`  can achieve it. 
Moreover, if I use `CustomNonbondedForce.addExclusion`, does it gonna overwrite the existing Coulomb and Lennard-Jones forces defined by the force field?
Thanks.

**Comment by jchodera** [comment]
@frank-stonybrook : You can use the [`CustomNonbondedForce`](http://docs.openmm.org/latest/api-python/generated/simtk.openmm.openmm.CustomNonbondedForce.html#simtk.openmm.openmm.CustomNonbondedForce) instead and use [`addInteractionGroup()`](http://docs.openmm.org/latest/api-python/generated/simtk.openmm.openmm.CustomNonbondedForce.html#simtk.openmm.openmm.CustomNonbondedForce.addInteractionGroup) to specify which particle sets you want to interact with each other.

**Comment by frank-stonybrook** [comment]
@jchodera Thanks for your response! I still had a hard time to scratch out the code. I assume that the proper way to turn off the nonbonded interactions between ligand and other solute is by subtracting the corresponding short and long-range terms from the system via CustomNonbondedForce, right? 
Following this idea, I outlined the following code:
``` python
if turn_off_ligand_solute_interaction:
    # Force group 1 (ligand and non-ligand solute short-range interactions): 
    # 0<=r <=cut_off_distance, default cut_off is 0.9 nm.
    ### substract off the following short-range term to effectively turn off it.
    expression = -1*(4*epsilon*((sigma/r)^12 - (sigma/r)^6) + ONE_4PI_EPS0*chargeprod/r);
    expression += "chargeprod = charge1*charge2;"
    expression += 'epsilon = sqrt(epsilon1*epsilon2);'
    expression += 'sigma = 0.5*(sigma1+sigma2);'
    expression += 'ONE_4PI_EPS0 = %.16e;' % (ONE_4PI_EPS0)
    force = openmm.CustomNonbondedForce(expression)
    force.addPerParticleParameter("charge")
    force.addPerParticleParameter("sigma")
    force.addPerParticleParameter("epsilon")
    force.setNonbondedMethod(openmm.CustomNonbondedForce.CutoffPeriodic)
    force.setCutoffDistance(cutoff_distance)
    force.setUseLongRangeCorrection(False)
    ### Magic happens which allow us to select nonbonded forces that ligand atoms involved.
    ligand_solute_nonbondedforce = some_select_function(system.getForces())

    for index in range(ligand_solute_nonbondedforce.getNumParticles()):
        [charge,sigma,epsilon] = ligand_solute_nonbondedforce.getParticleParameters(index)
        force.addParticle([charge,sigma,epsilon])
    force.addInteractionGroup(ligand_atoms,non_ligand_solute_atoms)
    system.addForce(force)
    
    # Force group 2 (ligand and non-ligand solute long-range interactions)
    # r >= cut_off_distance
    ### Substract off the following long-range terms to effectively turn off it.
    expression = ...
    force = openmm.CustomNonbondedForce(expression)
    force.setNonbondedMethod(openmm.NonbondedForce.PME)
    for index in range(ligand_solute_nonbondedforce.getNumParticles()):
        [charge,sigma,epsilon] = ligand_solute_nonbondedforce.getParticleParameters(index)
        force.addParticle([charge,sigma,epsilon])
    force.addInteractionGroup(ligand_atoms,non_ligand_solute_atoms)
    system.addForce(force)
```

I have some naive questions:

1. What is the expression for computing long-range interactions in OpenMM?
2. What will the proper way (aka. `some_select_function`) to select only ligand-solute `NonbondedForce` from the system?

Thanks!

**Comment by z-gong** [comment]
@frank-stonybrook 
1. There's no simple expression for computing long-range interactions between two groups. With PME, long-range interactions are not pairwise. It's calculated from the charges and positions of all the particles together in the system. Therefore, PME interactions can not be switched off between two specific groups.
2. The LJ and Coulomb forces between all pairs are handled by a single NonbondedForce. You can get it with `nbforce = next(force for force in system.getForces() if type(force) == openmm.NonbondedForce)`

**Comment by frank-stonybrook** [comment]
@z-gong Thanks for your comments! Just to clarify,

> ... Therefore, PME interactions can not be switched off between two specific groups
So, does it mean that there is no way to switched off the long-range interactions between two subgroups of the system in explicit solvent simulation when using PME method? What about using `addException` method, how does it works?

**Comment by z-gong** [comment]
@frank-stonybrook True. `addException` is usually applied for atoms that are very close to each other (separated by less than three bonds). When you call `addException(i,j,0,0,0)`, it actually creates an extra bond force to subtracts out the LJ and Coulomb force between `i` and `j` (their periodic images are not included) that have been counted by NonbondedForce. But the long range forces between `i` and `j`'s periodic images are not affected.

**Comment by frank-stonybrook** [comment]
That's interesting! I am wondering for switching off PME whether it is possible to launch two separate kernels: one compute everything, another one just compute the long-range part between two subset of atoms in the system using PME. Then subtract the forces and energy from the first kernel using the second one. It shouldn't pose too much overhead for the simulation.

**Comment by z-gong** [comment]
By the way, this document describes how LAMMPS calculate PME forces between groups of atoms
https://lammps.sandia.gov/doc/PDF/kspace.pdf

**Comment by frank-stonybrook** [comment]
Thanks!

**Comment by peastman** [comment]
> one compute everything, another one just compute the long-range part between two subset of atoms in the system using PME.

The closest thing I can think of is to create a separate NonbonedForce that sets the charges for all other particles to 0.  You could put the direct space and reciprocal space parts in different force groups and use a custom integrator that computes the right combination of forces.  I'm not sure if it really does exactly what you want though.

You also might consider using `CutoffPeriodic` instead of PME.  That uses reaction field, which doesn't have these problems and turns out to be surprisingly accurate for many simulations.

**Comment by frank-stonybrook** [comment]
> The closest thing I can think of is to create a separate NonbonedForce that sets the charges for all other particles to 0. You could put the direct space and reciprocal space parts in different force groups and use a custom integrator that computes the right combination of forces

Yes, this solution can probably achieve the same goal. 

> You also might consider using CutoffPeriodic instead of PME

Thanks! I will take a look at the reaction field theory.
