### ISSUE TITLE
Extreme slow down using Amber parm7

### ISSUE THREAD

**Issue by gitkol** [openmm/openmm#2574]
Hi, I am struggling with performance issues. I have a protein complex that I solvated with PDBFixer and ran a simulation with these relevant settings:
```
pdb = PDBFile('system.pdb')
forcefield = ForceField('amber14-all.xml', 'amber14/tip3pfb.xml')
nonbondedMethod = PME
nonbondedCutoff = 0.9*nanometers
ewaldErrorTolerance = 5e-4
constraints = HBonds
rigidWater = True
constraintTolerance = 1e-5
platform = Platform.getPlatformByName('CUDA')
platformProperties = {'Precision': 'mixed'}
topology = pdb.topology
positions = pdb.positions
system = forcefield.createSystem(topology, nonbondedMethod=nonbondedMethod, nonbondedCutoff=nonbondedCutoff,
    constraints=constraints, rigidWater=rigidWater, ewaldErrorTolerance=ewaldErrorTolerance, hydrogenMass=3.024*amu)
```
This system has ~150,000 atoms and runs at ~90 ns/day on the GTX 1080 Ti. Then, I created a new system with the exact same protein complex plus an organic ligand. I parameterized the ligand externally and used tleap to build the system. The relevant lines in my OpenMM script are as follows:
```
prmtop = AmberPrmtopFile('system-HMR.parm7')
inpcrd = AmberInpcrdFile('system.rst7')
nonbondedMethod = PME
nonbondedCutoff = 0.9*nanometers
ewaldErrorTolerance = 5e-4
constraints = HBonds
rigidWater = True
constraintTolerance = 1e-5
platform = Platform.getPlatformByName('CUDA')
platformProperties = {'Precision': 'mixed'}
topology = prmtop.topology
positions = inpcrd.positions
system = prmtop.createSystem(nonbondedMethod=nonbondedMethod, nonbondedCutoff=nonbondedCutoff,
    constraints=constraints, rigidWater=rigidWater, ewaldErrorTolerance=ewaldErrorTolerance)
```
This system has ~170,000 atoms, so I can see a 10-15% slow down, but the Amber based system runs 3-times slower, ~30 ns/day on the same hardware and same OpenMM software. This particular test was run using version 7.41 `conda install -c omnia/label/cuda100 -c conda-forge openmm`, but I saw the exact same performance degradation using OpenMM 7.3.1 that I compiled from source.

Is anything wrong with my settings? Thanks for any suggestion.

   Istvan

**Comment by peastman** [comment]
As far as I can tell, everything looks reasonable.  Is it possible for you to post your files so I can try profiling it and see where it's spending its time?

Have you tried looking at the output trajectory?  Aside from being slow, does it look like everything is behaving reasonably?

**Comment by peastman** [comment]
Testing on a Titan V, I don't see the slowdown you describe.  For the smaller system I get 86 ns/day.  On the larger one I get 75 ns/day.  Those seem reasonable given the differences in size.

Could you try running it in nvprof?  You can do it like this:

```
/usr/local/cuda/bin/nvprof python myscript.py
```

Post the output, and I can look for differences compared to what I'm seeing.

**Comment by gitkol** [comment]
Attached the nvprof results for both runs.
[fast-nvprof.log](https://github.com/openmm/openmm/files/4251615/fast-nvprof.log)
[slow-nvprof.log](https://github.com/openmm/openmm/files/4251616/slow-nvprof.log)

**Comment by gitkol** [comment]
Just posted the profiling results.

**Comment by peastman** [comment]
Overall the two profiles are very similar.  The ranking of kernels and API calls, and the times per call for each one, aren't too different.  The big difference I see is that the slow one did many more evaluations: 49,158 compared to only 12,330 for the fast one.  Possibly that just means it needed a lot more steps for energy minimization.  You might try writing out the minimized coordinates to a PDB file.  Then you can profile it just loading them in directly without having to minimize again.  That way we'll be comparing exactly the same number of time steps for each one.

I also notice there are fewer evaluations of the PME reciprocal space forces than of direct space forces.  Are you using some kind of multiple time step integrator?

**Comment by gitkol** [comment]
Yes, I am using multiple time step integration. I already have the minimized coords in PDB files, I'll rerun the profiling doing only MD steps.

**Comment by gitkol** [comment]
Wow, it turns out the whole Amber vs. not Amber setup was a red herring. I did what you suggested and there is indeed no difference, other than the ~10% slow down due to system size. However, the 3-fold slow down is still puzzling, I didn't notice that the "fast" run had a `barostatInterval = 25` and the "slow" run had `barostatInterval = 1`. Not sure where the 25 comes from, but I can confirm that the `barostatInterval` setting is responsible for the slow down. Does that make sense?

**Comment by peastman** [comment]
Yes, that makes perfect sense!  A barostat step involves two energy evaluations, so it's about as expensive as two time steps.  Doing it every 25 steps (which is the default) has only a very small effect on speed.  Doing it every step will produce a 3x slowdown.

**Comment by gitkol** [comment]
Lesson learned. Thanks, Peter.
