### ISSUE TITLE
Remaining changes for Nose-Hoover

### ISSUE THREAD

**Issue by peastman** [openmm/openmm#2578]
There are some changes that still need to be made to NoseHooverIntegrator before we can release 7.5:

- Finish up #2527 to convert it to the common framework.
- Finish up #2518 to change how temperature initialization is done.
- Convert it to the LFMiddle discretization, which allows much larger timesteps.  This is what we now use in LangevinMiddleIntegrator.  Also see http://dx.doi.org/10.1021/acs.jpca.9b02771, which has details about using this discretization with Nose-Hoover.
- Write the documentation for it in the user guide.  In particlular,
  - Add a brief description of it in section 3.6.7.
  - Add a sentence or two in chapter 16 to add it to the list of integrators for Drude particles.
  - Add a detailed description in chapter 20.

cc @andysim @Olllom

**Comment by z-gong** [comment]
I've noticed that some logic in the velocityVerlet integrator can be simplified. Herein, when integrating a drude pair, the velocity and force are transformed to center of mass and relative motions, on which the velocities are integrated, and then transformed back to real atoms and drude particles. This is not really necessary. The forces can operate directly on the real and drude particles to integrate their velocity.
https://github.com/openmm/openmm/blob/a9223eea076bf54cc5028064d664b2951be94579/platforms/reference/src/SimTKReference/ReferenceVelocityVerletDynamics.cpp#L103-L139

**Comment by andysim** [comment]
I think the temperature initialization stuff is good to go already - I'll take a look at what Travis is unhappy about in a bit, but I don't think it's related to my changes.  I think the only difficult task remaining is the conversion to the common platform.  The integrator itself is working, but I'm getting strange memory errors in the thermostat.  I'll dig around more today and try to resolve them.

**Comment by andysim** [comment]
I think the temperature initialization stuff is good to go already - I'll take a look at what Travis is unhappy about in a bit, but I don't think it's related to my changes.  I think the only difficult task remaining is the conversion to the common platform.  The integrator itself is working, but I'm getting strange memory errors in the thermostat.  I'll dig around more today and try to resolve them.

**Comment by peastman** [comment]
Are you planning to do the conversion to LFMiddle or should I start on that?

**Comment by andysim** [comment]
Sorry for the delay - crazy times over here!  I'm working on it right now while social distancing responsibly.  Feel free to chime in on #2600 if you think my approach is bad.

**Comment by peastman** [comment]
Once #2651 is merged, we can also clean up a lot of code.  There was no good mechanism for integrators to write data to checkpoints.  That required it to be hacked in at a low level, which in turn complicated other code, requiring the integrator's internal data to be stored by the context.  We now have a much cleaner mechanism for handling this.  I would have made the changes to Nose Hoover at the same time, but I didn't want to create conflicts with #2600.  I can do that once it's merged.

**Comment by peastman** [comment]
I believe everything in this issue has now been done, so I'll close it.
