### ISSUE TITLE
Describe the use of openmmforcefields for small molecule parameters in Users Guide?

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#2583]
Would it make sense to include some examples for how to use [`openmmforcefields`](https://github.com/openmm/openmmforcefields) to access small molecule parameters for protein:ligand systems in the Users Guide? If so, this might be a good candidate to include in the 7.5.0 release.

**Comment by peastman** [comment]
Sure.  Do you want to add a small molecule example in the Advanced Simulation Examples chapter?

**Comment by jchodera** [comment]
Sounds good---I've added it to the "To do" column and will tackle it soon!

**Comment by peastman** [comment]
@jchodera do you want to do this for 7.5?  It would be a great addition.

**Comment by jchodera** [comment]
Yes! PR incoming.

**Comment by jchodera** [comment]
Still working on reformatting the docs for a new section of the User Guide. Hope to have the PR opened today.

**Comment by peastman** [comment]
In what way are you reformatting them?  I was figuring this would just be another section in the Advanced Simulation Examples chapter.

**Comment by jchodera** [comment]
The documentation here is all in Markdown:
https://github.com/openmm/openmmforcefields/blob/master/README.md

No matter what, this needs to be converted into Sphinx reST.

There are really three distinct sections in the docs there:
* How to install it
* How to use the template generators with `ForceField`
* How to use the `SystemGenerator` to automate force field management, which is a distinct system from `ForceField`

For simplicity, the current plan is this
* Create a new `openforcefields.rst` that essentially ingests the whole documentation (but converted to reST)
* Insert this in the manual as "Advanced Force Field Usage: The `openmmtools` package
* Slot it into `index.rst` after `application` but before `library`

We can do fancier integration into the manual later.

**Comment by peastman** [comment]
We don't need to do all of that.  Just give a link to the openmmforcefield documentation online.  Here we just need to let users know that it exists, and give a brief example of how to use it.  In the same way, the manual doesn't give full documentation for OpenMM-Setup, it just tells users that it exists and links to the webpage for that project.

**Comment by jchodera** [comment]
@peastman: #2820 contains what you request, rather than what I proposed above.

**Comment by peastman** [comment]
Fixed by #2820.
