### ISSUE TITLE
AMBER18 format TIP3P water not recognised by OpenMM!

### ISSUE THREAD

**Issue by apbhati1** [openmm/openmm#2584]
Hi,

I am trying to load a protein PDB file and the corresponding AMBER format topology file to setup a system to be simulated using OpenMM. The topology file has been generated using AmberTools19 using `leaprc.protein.ff14SBonlysc` and `leaprc.water.tip3p`. However, I get an error message where it appears that OpenMM does not recognise the water residues in my system. I'm not sure what's wrong here. It seems as if there is some inconsistency in the parameters for TIP3P water model in AMBER forcefields and the `amber14/tip3p.xml` file of OpenMM. Can anyone suggest anything here?

Following are the relevant files:

OpenMM input script:
```from simtk.openmm.app import *
from simtk.openmm import *
from simtk.unit import *

pdb = PDBFile('../rec.pdb')
prmtop = AmberPrmtopFile('../rec.top')
forcefield = ForceField('amber14-all.xml', 'amber14/tip3p.xml')
system = forcefield.createSystem(prmtop.topology, nonbondedMethod=PME, nonbondedCutoff=1*nanometer, constraints=HBonds)
integrator = LangevinIntegrator(300*kelvin, 1/picosecond, 0.002*picoseconds)
platform = Platform.getPlatformByName('CUDA')
properties = {'Precision': 'double'}
simulation = Simulation(prmtop.topology, system, integrator, platform, properties)
simulation.context.setPositions(pdb.positions)
simulation.minimizeEnergy()
simulation.reporters.append(DCDReporter('traj.dcd', 100000))
simulation.reporters.append(StateDataReporter('sim.log', 50000, step=True, potentialEnergy=True, temperature=True))
simulation.step(500000)
```

Error message by OpenMM:
```Traceback (most recent call last):
  File "../sim.py", line 8, in <module>
    system = forcefield.createSystem(prmtop.topology, nonbondedMethod=PME, nonbondedCutoff=1*nanometer, constraints=HBonds)
  File "/gpfs/alpine/scratch/apbhati/chm155/miniconda/envs/openmm/lib/python3.7/site-packages/simtk/openmm/app/forcefield.py", line 1144, in createSystem
    raise ValueError('No template found for residue %d (%s).  %s' % (res.index+1, res.name, _findMatchErrors(self, res)))
ValueError: No template found for residue 275 (HOH).  The set of atoms matches HOH, but the bonds are different.
```

I am performing this simulation on Summit.

Best,
Agastya

**Comment by jchodera** [comment]
Can you post a ZIP file containing your PDB file and prmtop?

**Comment by apbhati1** [comment]
Attached.
[input.zip](https://github.com/openmm/openmm/files/4272175/input.zip)
Thanks!

**Comment by jchodera** [comment]
Change this line
```python
simulation = Simulation(prmtop.topology, system, integrator, platform, properties)
```
to
```python
simulation = Simulation(pdb.topology, system, integrator, platform, properties)
```
and it should work!

`PDBFile` uses the PDB specification to define standard residues that do not need `CONECT` records to define standard bonds, and OpenMM's `ForceField` uses these standard residue definitions to match residues to force field residue templates. 

On the other hand, AMBER appears to define a different set of bonds (perhaps including the `H-H` bond?) within the `prmtop` file, so `prmtop.topology` was not consistent with what OpenMM's force field definitions expected.

**Comment by apbhati1** [comment]
Thanks for the clarification. It does work with the way you suggested. But since I wanted to specifically use my AMBER topology file, I imported coordinates from the AMBER format coordinate file (`rec.crd`) instead of the pdb file and that works well too.
