### ISSUE TITLE
Update CHARMM polarizable force field

### ISSUE THREAD

**Issue by peastman** [openmm/openmm#2585]
We have only the original 2013 version of the CHARMM polarizable force field.  There have been a couple of updates to it since then.  We should add the latest version from http://mackerell.umaryland.edu/charmm_drude_ff.shtml.  They've also added a lot more molecule types including nucleic acids, lipids, and carbohydrates, so we should include as many of those as possible.

**Comment by jchodera** [comment]
Feel free to open an issue in http://github.com/openmm/openmmforcefields, but if I recall correctly, the blocking issue here was that someone needs to add support for polarizable force fields and lone pairs to ParmEd, and we haven't had the bandwidth to do that.

**Comment by peastman** [comment]
I was planning to just use the [existing script](https://github.com/openmm/openmm/blob/master/devtools/forcefield-scripts/processCharmmForceField.py) we used for the 2013 version.  It's not very fancy, but it does the job.

**Comment by jchodera** [comment]
If that doesn't work, it would be useful to see if we could do the more general thing and integrate those capabilities into ParmEd, since we could then easily support CGenFF small molecule parameterization (presuming the user has the CGenFF tool installed).

**Comment by peastman** [comment]
That would certainly be useful.  It also would produce a more robust conversion of the force field, given the support for automatically handling patches.  The carbohydrates especially involve a ton of patches.  Do you know what would be involved in adding those features?  I haven't worked with the ParmEd source code.

**Comment by jchodera** [comment]
I can't recall the specifics of what would be needed, but I think it involved
* Extending the internal representation of polarizable sites in [residues](https://github.com/ParmEd/ParmEd/blob/master/parmed/residue.py) and [parameter sets](https://github.com/ParmEd/ParmEd/blob/master/parmed/parameters.py) if they are not already defined. Note that the object models for both are AMBER-centric, so anything that isn't from the AMBER world is just kind of shoe-horned in there.
* Extending the [CHARMM readers](https://github.com/ParmEd/ParmEd/tree/master/parmed/charmm) to populate this object model
* Extending the [OpenMM object model and writers](https://github.com/ParmEd/ParmEd/blob/master/parmed/openmm/parameters.py) to handle polarizable sites

The best approach might be to [open an issue](https://github.com/ParmEd/ParmEd/issues) and get advice from @swails on the best path forward.

**Comment by peastman** [comment]
I'm running into problems related to how we use atom types.  For example, the ASN residue definition specifies

```
ANISOTROPY OD1 CG LPDA LPDB A11 0.88  A22 1.32 
```

That says the OD1 atom is anisotropically polarizable, and its coordinate frame is based on the CG, LPDA, and LPDB atoms.  When I converted the original version of the force field, I had it create a unique atom type for every atom of every residue template.  Atom OD1 of residue ASN was type 105, so I could uniquely specify that in the `<DrudeForce>` tag:

```xml
<Particle type1="851" type2="105" type3="104" type4="109" type5="110" charge="-1.63253" polarizability="0.000885" thole="1.227" aniso12="0.88" aniso34="1.32"/>
```

But ParmEd just uses a one-to-one correspondence between CHARMM atom types and OpenMM atom types, with each one having the same string for both `type` and `class`.  Unfortunately, those aren't fine grained enough.  In ASN, for example, OD1 and O both have the same atom type, OD2C1A, so we can't make one anisotropic without doing it for the other one as well.

Would it be reasonable to add an option so that it will instead create unique types for every residue/atom pair?  All other force field terms would use `class` instead of `type` to specify values, and those would be the CHARMM types.

**Comment by jchodera** [comment]
That seems like a reasonable solution for this.

**Comment by swails** [comment]
Would it break anything to do make that the standard behavior (i.e., don't add an option, just always create unique types for residue/atom pairs)?  If yes, then your proposal makes sense.  If things would continue to work by just making that change and not exposing the option, I'd elect for making the change everywhere.

**Comment by jchodera** [comment]
The only important thing here from my end is that we have to be a bit careful about synchronizing the releases of `ParmEd` within `ambertools`, `OpenMM`, and `openmmforcefields` if we want everything to keep working together nicely.

**Comment by peastman** [comment]
It might work to always do it that way.  I'm just not certain of it.  I remember we had long involved discussions in coming up with the current system, and I don't remember all the issues that were discussed at the time.

**Comment by jchodera** [comment]
I don't see an issue with doing it this way for the CHARMM force field conversion, but am still concerned about keeping all behavior consistent. 

In particular, I'd be very concerned about making this the standard behavior in ParmEd, rather than optional. It sounds like that could break pretty much everything we use ParmEd for due to subtle reasons.

What if we
* Add this as an optional behavior to ParmEd
* Try it out in `openmmforcefields` to see if the conversion actually works
* If it works, cut a new release of ParmEd and get it into a point release of AmberTools19
* Rebuild the conda-forge package
* Regenerate all the OpenMM force fields with openmmforcefields
* Cut a new release of OpenMM and openmmforcefields at the same time.

Given the timescale for this coordination, what if we tried to get OpenMM 7.5.0 out first and then added this into 7.6.0?

**Comment by peastman** [comment]
That sounds plausible.  Anyway, for the moment I'll keep it as an option.  That will let me get the polarizable force field working, and we can evaluate other force fields later.

**Comment by peastman** [comment]
I'm getting problems from the way ParmEd generates the patch definitions.  For each patch, it arbitrarily picks a single residue to apply it to.

https://github.com/ParmEd/ParmEd/blob/aa15556ab201b53f99cf36394470c341526b69ed/parmed/openmm/parameters.py#L688-L691

In the case of the NTER patch, the one it happens to pick is ALAD (alanine dipeptide).  Since that's a self contained molecule, not part of a chain, it concludes the patch doesn't affect external bonds and omits the `<RemoveExternalBond>` instruction.  That prevents it from being applied to actual N-terminal residues.

@jchodera you originally wrote this code.  Do you have any suggestions about the best way of handling this?

**Comment by moradza** [comment]
Any tutorial is available for the polarizable water model with openmm? I would appreciate getting the link.
