### ISSUE TITLE
Segfault in getting reference platform with python 3.6.8

### ISSUE THREAD

**Issue by wpm216** [openmm/openmm#2586]
Hi, 

When running the `python -m simk.testInstallation` command, I'm getting a segmentation fault before any platforms are loaded. The machine I'm running on doesn't have any GPUs, nor does it have CUDA.

```
$ python -m simtk.testInstallation

OpenMM Version: 7.4.1
Git Revision: 068f120206160d5151c9af0baf810384bba8d052

There are 2 Platforms available:

Segmentation fault
```

Here are outputs from two other commands that might be useful, given similar issues that have been opened on this project:
```
$ python -c "import simtk.openmm; print([simtk.openmm.Platform.getPlatform(index).getName() for index in range(simtk.openmm.Platform.getNumPlatforms())])"
['Reference', 'CPU']

$ python -c "import simtk.openmm; print(simtk.openmm.Platform.getPluginLoadFailures())"
('Error loading library /home/users/wpm216/psi4conda/envs/openmm/lib/plugins/libOpenMMCUDA.so: libcuda.so.1: cannot open shared object file: No such file or directory', 'Error loading library /home/users/wpm216/psi4conda/envs/openmm/lib/plugins/libOpenMMRPMDCUDA.so: libOpenMMCUDA.so: cannot open shared object file: No such file or directory', 'Error loading library /home/users/wpm216/psi4conda/envs/openmm/lib/plugins/libOpenMMDrudeCUDA.so: libOpenMMCUDA.so: cannot open shared object file: No such file or directory', 'Error loading library /home/users/wpm216/psi4conda/envs/openmm/lib/plugins/libOpenMMAmoebaCUDA.so: libOpenMMCUDA.so: cannot open shared object file: No such file or directory', 'Error loading library /home/users/wpm216/psi4conda/envs/openmm/lib/plugins/libOpenMMCudaCompiler.so: libnvrtc.so.10.1: cannot open shared object file: No such file or directory')
```

I suspect the issue is arising from the lack of the `libcuda.so.1` library in the conda environment. From the OpenMM documentation, it seems that I should be able to run the code without a GPU/CUDA. I didn't see any Omnia Anaconda channels suggestive of CUDA-independent builds, however. Was hoping y'all could shed some light on this. Thanks!

-Wes

**Comment by peastman** [comment]
Not having CUDA is fine.  That just means the CUDA platform doesn't get loaded.

Can you try running it inside gdb?

```
gdb python
```

and then at the gdb prompt,

```
run -m simtk.testInstallation
```

Let it run until it segfaults, then type

```
bt
```

That will give a stack trace that hopefully will provide more information.

**Comment by wpm216** [comment]
Thanks for the quick reply! Here's the output:

```
(gdb) run -m simtk.testInstallation
Starting program: /home/users/wpm216/psi4conda/bin/python -m simtk.testInstallation
warning: Unable to open "librpm.so.3" (/share/software/user/open/xz/5.2.3/lib/liblzma.so.5: version `XZ_5.1.2alpha' not found (required by /lib64/librpmio.so.3)), missing debuginfos notifications will not be displayed
Missing separate debuginfo for /lib64/ld-linux-x86-64.so.2
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/a5/27fe72908703c5972ae384e78d1850d1881ee7.debug
Missing separate debuginfo for /lib64/libpthread.so.0
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/96/900cb0ff25b26f2bbdf247de1408242e4773d8.debug
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Missing separate debuginfo for /lib64/libc.so.6
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/42/6a04647352308628f2091a30d347edeeded787.debug
Missing separate debuginfo for /lib64/libdl.so.2
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/35/7693c8f1f49d93010c4e31529c07cdd2bd3d08.debug
Missing separate debuginfo for /lib64/libutil.so.1
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/bf/b22a176189006bbf996a7664ccc6bdb2eb9bd9.debug
Missing separate debuginfo for /lib64/librt.so.1
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/ef/de2029c9a4a20be5b8d8ae7e6551ff9b5755d2.debug
Missing separate debuginfo for /lib64/libm.so.6
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/5b/14be4d749631673523a61074c10959d50f5455.debug
/home/users/wpm216/psi4conda/bin/python: Error while finding module specification for 'simtk.testInstallation' (ModuleNotFoundError: No module named 'simtk')
[Inferior 1 (process 24961) exited with code 01]
```

-Wes

**Comment by peastman** [comment]
That looks to me like some sort of a library incompatibility.  It's crashing inside `PyObject_IsInstance()`, which is part of the Python C API.  How did you install OpenMM?  Is this a conda package, or did you build it from source?  What OS are you on, and what Python version?

**Comment by wpm216** [comment]
Ah, found the issue!

The environment which produced the above errors was:
- CentOS Linux 7
- python 3.6.8
- conda package (`conda install -c omnia openmm` in a fresh environment)

Creating a new environment with python 3.7.6 solved the problem:

```
$ python -m simtk.testInstallation

OpenMM Version: 7.4.1
Git Revision: 068f120206160d5151c9af0baf810384bba8d052

There are 2 Platforms available:

1 Reference - Successfully computed forces
2 CPU - Successfully computed forces

Median difference in forces between platforms:

Reference vs. CPU: 6.30239e-06

All differences are within tolerance.
```

Silly mistake on my part, my apologies. If you'd like to investigate the error any further, I'd be happy to provide more information as needed.

-Wes

**Comment by peastman** [comment]
Glad you've got it working!  But what was the mistake?  It ought to work fine on Python 3.6.

**Comment by wpm216** [comment]
Me too! Yea, I'm not 100% sure what the issue is.

I made a clean conda environment just now, with python 3.6.8, and got the same error as before. Here are the outputs of `conda list` for the [python 3.6.8](https://github.com/openmm/openmm/files/4289394/py3.6_list.txt) and [python 3.7.6](https://github.com/openmm/openmm/files/4289395/py3.7_list.txt) environments.

The 3.6 environment is missing the `ld_impl_linux-64` package compared to the 3.7 one, but installing it did not fix the problem. The only other differences arise from the builds of some packages - including cython - so perhaps some small incompatibility is hiding in there somewhere.

-Wes

**Comment by wpm216** [comment]
Huh, that is strange. I'll leave it up to you as to whether this issue should be closed or not. Thanks again for all the prompt support!
