### ISSUE TITLE
Last master fails in omnia-dev

### ISSUE THREAD

**Issue by jaimergp** [openmm/openmm#2588]
I am seeing errors since last night:

* Windows can only see the Reference platform now. It used to be able to see CPU too. The CPU library gets compiled, but it can't register it during the tests:

```
$ python -m simtk.testInstallation 

OpenMM Version: 7.5
Git Revision: ca4c03c362446abaf66b832ddd500ec049b2ec60

There are 1 Platforms available:

1 Reference - Successfully computed forces

All differences are within tolerance.

$ python benchmark.py --test=rf --seconds=10 --platform=CPU
usage: benchmark.py [-h] [--platform {Reference}]
                    [--test {gbsa,rf,pme,apoa1rf,apoa1pme,apoa1ljpme,amoebagk,amoebapme}]
                    [--pme-cutoff CUTOFF] [--seconds SECONDS]
                    [--polarization {direct,extrapolated,mutual}]
                    [--mutual-epsilon EPSILON] [--heavy-hydrogens]
                    [--device DEVICE] [--precision {single,mixed,double}]
benchmark.py: error: argument --platform: invalid choice: 'CPU' (choose from 'Reference')
```

* MacOS has problems with CPU too:

```
There are 3 Platforms available:

1 Reference - Successfully computed forces
2 CPU - Error computing forces with CPU platform
3 OpenCL - Error computing forces with OpenCL platform

CPU platform error: std::bad_cast

OpenCL platform error: No compatible OpenCL platform is available
```

Ignore the OpenCL problems, those are expected. However, a short MD can indeed run, but only in some cases (2/3). The other one reports `4263 Illegal instruction: 4`.

* Linux seems unaffected.

All logs can be checked [here](https://dev.azure.com/OmniaMD/conda-dev-recipes/_build/results?buildId=138&view=results). Any recent changes in `master` that might be related or should I start digging in versions/libraries/conda nightmares?

**Comment by peastman** [comment]
I can't think of anything that would have caused this.  Did it just start happening?  There has only been one PR merged in the last week, and that one only changed code that doesn't get run on Windows.

Does `Platform.getPluginLoadFailures()` report any errors?

**Comment by jaimergp** [comment]
[Nein](https://dev.azure.com/OmniaMD/conda-dev-recipes/_build/results?buildId=141&view=logs&j=4a0dadba-b014-54f8-0bf6-a2ee97567f21&t=cbd75aa9-293f-5b7c-cd16-a969ecb7fb06&l=5614) :(

```
$> python -c "import simtk.openmm as mm; print(mm.Platform.getPluginLoadFailures())" 
()
```

**Comment by jaimergp** [comment]
More info:

* Builds were successful last Wednesday ([logs](https://dev.azure.com/OmniaMD/conda-dev-recipes/_build/results?buildId=133&view=logs&j=ba2b5d57-60df-516b-f4c1-c984f77075b0&t=4c4c1dbd-4afe-5b03-5781-f09f85b0c3f6)).
* They started failing on Thursday ([logs](https://dev.azure.com/OmniaMD/conda-dev-recipes/_build/results?buildId=134&view=logs&j=ba2b5d57-60df-516b-f4c1-c984f77075b0&t=4c4c1dbd-4afe-5b03-5781-f09f85b0c3f6&l=5738)).

Wednesday used this commit:

```
commit a9223eea076bf54cc5028064d664b2951be94579
Merge: bdc250cc3 ec28e11aa
Author: peastman <peastman@stanford.edu>
Date:   Wed Feb 26 14:10:27 2020 -0800

    Merge pull request #2580 from peastman/platformindex
    
    Improved error checking when specifying an OpenCL device

7.4.0-243-ga9223eea0
```

Thursday used:

```
commit ca4c03c362446abaf66b832ddd500ec049b2ec60
Merge: d169badca 2270a28ad
Author: peastman <peastman@stanford.edu>
Date:   Wed Mar 4 12:03:16 2020 -0800

    Merge pull request #2527 from andysim/nhcommon
    
    Convert Nose Hoover integrator to Common plaform

7.4.0-253-gca4c03c36
```

[That's 10 commits in between](https://github.com/openmm/openmm/compare/a9223eea076bf54cc5028064d664b2951be94579...ca4c03c362446abaf66b832ddd500ec049b2ec60). Tbh, I don't see how this can impact the CPU platform :/

**Comment by jaimergp** [comment]
Hm, `conda-forge` has also bumped the Python build:

* Wednesday: `3.8.2-h5fd99cc_1_cpython`
* Thursday: `3.8.2-h5fd99cc_3_cpython `

(that also applies to Python 3.6 and 3.7).

This change only concerns how they constrain Python as a package, because they recently added the notion of different Python implementations (cpython, pypy, etc). The hash itself is the same, so it shouldn't make a difference... but just in case I am going to run the CI with the previous commit to make sure.

**Comment by jaimergp** [comment]
Huh... It seems like we are facing two issues at the same time!

If I revert to the previous commit a9223eea076bf54cc5028064d664b2951be94579, MacOS builds are successful: CPU platform shows no errors and we don't see that `CPU platform error: std::bad_cast` message.

However, the problem with Windows is still there regardless the commit.

**Comment by peastman** [comment]
@tristanic the Mac error seems to be a consequence of #2587.  Most of the CPU platform is defined in one plugin library, but the reciprocal space PME calculation is defined in another plugin.   When the CPU nonbonded force (defined in one library) tries to cast the reciprocal space kernel (created by another library) to a `CalcPmeReciprocalForceKernel`, it gets a `bad_cast`.

https://github.com/openmm/openmm/blob/ca4c03c362446abaf66b832ddd500ec049b2ec60/platforms/cpu/src/CpuKernels.cpp#L649

Any suggestions on how to fix it?

**Comment by tristanic** [comment]
Hmm... how about only using RTLD_LOCAL when compiling with GCC? I guess clang does things differently, and I doubt that RTLD_GLOBAL is likely to cause issues on the Mac anyway since as far as I’m aware the stdc++ library is never statically linked there.

**Comment by peastman** [comment]
> how about only using RTLD_LOCAL when compiling with GCC?

I wonder is it a gcc issue or a Mac issue?  I verified the `bad_cast` doesn't happen with a Linux build compiled with gcc.  I'll try compiling on Linux with clang and see what happens.

> $> python -c "import simtk.openmm as mm; print(mm.Platform.getPluginLoadFailures())" 
> ()

Ok, I'm puzzled by that!  I just downloaded the latest Windows dev package and verified that OpenMMCPU.dll is present in the plugins folder.  So if the plugin is present, and there were no errors loading it, why isn't the platform available?  The one other thing that would prevent it is if `CpuPlatform::isProcessorSupported()` returns false, but why would that have changed?  Anyway, that's easy to check:

```python
from simtk.openmm import *
print(pluginLoadedLibNames)
```

Is OpenMMCPU.dll listed?  That will tell us whether the plugin got loaded.

One other odd thing I noticed.  Looking at the list of builds at https://anaconda.org/omnia-dev/openmm/files, I see there are Mac and Linux builds from last night, but the most recent Windows builds are from three days ago.  That might be connected.

**Comment by peastman** [comment]
Compiling with clang on Linux also works.  So it looks like we want to use `RTLD_LOCAL` on Linux and `RTLD_GLOBAL` on Mac.  Thanks!

**Comment by jaimergp** [comment]
Thanks for looking into this! 

I am away for the weekend, so I will add new tests on Monday. Missing Windows builds are expected because only those that pass the tests are uploaded to Anaconda. Specific MacOS builds might be missing too.

**Comment by jaimergp** [comment]
I pinned Python in Windows to the previous build just to make sure it's not part of the problem and it doesn't make a difference. Maybe Azure has changed the way they provision their CPUs? It would be such a coincidence this happened on the day as we changed commits, but rolling it back doesn't change it either. We will know next week!

**Comment by jaimergp** [comment]
Conda-forge has fixed Python over the weekend (so it was indeed broken in Windows), so that shouldn't be a problem now.

I added more debugging statements to the build and, interestingly, they return nothing:

```
>python -c "import simtk.openmm as mm; print(*mm.pluginLoadedLibNames, *mm.Platform.getPluginLoadFailures(), sep='\n')" 


```

I am going to try to debug this locally in my Windows machine now.

**Comment by jaimergp** [comment]
I have been able to build `openmm` locally and reproduce the error. I will attach the `tar.bz2` in case somebody wants to help debug in a Windows machine.

* [Free Windows VM ISOs provided by Microsoft](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/)
* [openmm-7.5.0-py38_nocuda_0.tar.bz2.zip](https://github.com/openmm/openmm/files/4307812/openmm-7.5.0-py38_nocuda_0.tar.bz2.zip) (rename to remove the `.zip` extension! otherwise GH won't let me upload)

```
> conda create -n openmm-issue-2588 path/to/openmm-7.5.0-py38_nocuda_0.tar.bz2.zip
> conda activate openmm-issue-2588
> conda update --all`
> python -m simtk.testInstallation
OpenMM Version: 7.5
Git Revision: a9223eea076bf54cc5028064d664b2951be94579

There are 1 Platforms available:

1 Reference - Successfully computed forces

All differences are within tolerance.
```

Take into account that this build is built from a previously successful commit! So the problem is not with OpenMM but the `conda` environment?

**Comment by peastman** [comment]
On your local build, can you verify the following?

- Is OpenMMCPU.dll present in the plugins folder?
- Is it listed in `pluginLoadedLibNames`?
- Does `Platform.getPluginLoadFailures()` report anything?

That should let us narrow down where the failure is happening, and then we can debug if from there.

**Comment by jaimergp** [comment]
Yes, I tried all of that and I get the same results as in the Azure builds:

```
> python -c "import simtk.openmm as mm; print(*mm.pluginLoadedLibNames, *mm.Platform.getPluginLoadFailures(), sep='\n')" 

(nothing)
```

The DLLs are there too.

**Comment by peastman** [comment]
Strange.  So the plugin doesn't get loaded, but there also isn't any error trying to load it?  That implies it isn't even trying to load it.  Perhaps it's looking in the wrong directory?  What are the values of the following?

- `version.openmm_library_path`
- `Platform.getDefaultPluginsDirectory()`
- The `OPENMM_PLUGIN_DIR` environment variable

You can also try instrumenting the code to print debugging information.  `Platform::loadPluginsFromDirectory()` gets called to load the plugins, so you can print out the directory it's looking in.  That loops over all the files in the directory that match the pattern `*.dll`, so you can print out the names of all of them.

**Comment by jaimergp** [comment]
That is familiar:

```
Type "help", "copyright", "credits" or "license" for more information.
>>> import simtk.openmm as mm
>>> mm.version.openmm_library_path
'C:/Users/Jaime/Miniconda3/conda-bld/openmm_1583769605472/_h_env/Library/lib'
>>> mm.Platform.getDefaultPluginsDirectory()
'C:\\Program Files\\OpenMM\\lib\\plugins'
>>> import os
>>> os.environ.get("OPENMM_PLUGIN_DIR")
```

I have seen this already, and reported the underlying problem [here](https://github.com/conda-forge/ripgrep-feedstock/issues/8). It was a `ripgrep` issue, which should find the `$PREFIX` files and fix them for later installation (here `C:/Users/Jaime/Miniconda3/conda-bld/openmm_1583769605472/_h_env`). I had added  checks for this in the CF repo (see [here](https://github.com/conda-forge/openmm-feedstock/blob/master/recipe/meta.yaml#L74)), but apparently thought we wouldn't need them here because it was already fixed (it was initially only a problem with AppVeyor, not Azure)... I'll readd the checks now and in the meantime I'll try to confirm my hypothesis locally.

Thanks for the hint!

**Comment by jaimergp** [comment]
This time is not `ripgrep` though, `conda-build` jumped from `3.8.11` to `3.8.12` and then we saw our errors. That's just unlucky :( 

[Last successful build (conda-build 3.8.11)](https://dev.azure.com/OmniaMD/conda-dev-recipes/_build/results?buildId=133&view=logs&j=7e620df2-09e4-5028-9c7b-4ca852e4dd9b&t=fa7ac119-13fe-5a08-6ee4-c13a5beda24f&l=5641):

```
Detected hard-coded path in text file Lib/site-packages/simtk/openmm/version.py
```

[Failing builds](https://dev.azure.com/OmniaMD/conda-dev-recipes/_build/results?buildId=134&view=logs&j=4bc7ef66-8a59-503f-fa7a-b9533d6853d5&t=b74f07a8-2579-5bef-51a5-f754ce19a846&l=5644)

```
INFO :: Time taken to mark (prefix)
        0 replacements in 0 files was 0.41 seconds
```

I am going to pin `conda-build` to 3.8.11 (hopefully this fixes it!) for now and report to the Anaconda guys.

**Comment by jaimergp** [comment]
Closing this since the original issue was solved here in OpenMM, and the second one was fixed (and reappeared, and refixed) in `conda-dev-recipes`. Thanks again!
