### ISSUE TITLE
Error creating system from solvated PDB with > 100,000 atoms

### ISSUE THREAD

**Issue by zhang-ivy** [openmm/openmm#2591]
@rafwiewiora  and I are trying to run 2 rounds of equilibration on a complex before running on Folding@Home: 1) at 2 fs with 2 amu hydrogen mass and then 2) at 5 fs with 4 amu hydrogen mass. Since the hydrogen mass changes across these equilibrations, in the second equilibration, I load in the pdb from the first equilibration and create a system from it. 

Script for 2nd equilibration and PDB from first equilibration:
[openmm_water_issue.zip](https://github.com/openmm/openmm/files/4300229/openmm_water_issue.zip)

However, I get the following error when creating the system:

```
Traceback (most recent call last):
  File "simulate_4amu_5fs.py", line 49, in <module>

  File "/Users/ivy/miniconda3/envs/py36/lib/python3.6/site-packages/simtk/openmm/app/forcefield.py", line 1145, in createSystem
    raise ValueError('No template found for residue %d (%s).  %s' % (res.index+1, res.name, _findMatchErrors(self, res)))
ValueError: No template found for residue 31562 (HOH).  The set of atoms matches HOH, but the bonds are different.
```

And when I run the following code to look at the atoms in residue 31562:

```
from simtk.openmm import app
pdb = app.PDBFile("equilibrated.pdb")
residues = [residue for residue in pdb.topology.residues()]
for atom in residues[31562].atoms():
    print(atom)
```
I get the following output:
```<Atom 99998 (O) of chain 3 residue 31562 (HOH)>
<Atom 99999 (H1) of chain 3 residue 31562 (HOH)>
<Atom 100000 (H2) of chain 3 residue 31562 (HOH)>
```

It seems like there is an issue when the atom index exceeds 100,000?

**Comment by peastman** [comment]
Strange, I'm getting a different result:

```python
>>> pdb = PDBFile('/Users/peastman/Downloads/openmm_water_issue/equilibrated.pdb')
>>> residues = list(pdb.topology.residues())
>>> list(residues[31562].atoms())
[<Atom 99998 (O) of chain 3 residue 31562 (HOH)>, <Atom 99999 (H1) of chain 3 residue 31562 (HOH)>, <Atom 100000 (H2) of chain 3 residue 31562 (HOH)>]
```

I'm getting a complete water molecule with the oxygen included.  It's also interesting that's actually the residue *after* the point where the ids wrap around:

```python
>>> [a.id for a in residues[31562].atoms()]
['2', '3', '4']
```

The wrapping happens in the middle of the previous one:

```python
>>> [a.id for a in residues[31561].atoms()]
['99999', '0', '1']
```

Very odd.  What version of OpenMM are you using?  I'm working with the latest code from the repository.  Though there've been very few changes to this code for quite a while.

**Comment by zhang-ivy** [comment]
Sorry, I think I miscopied the output in the original post. I am getting a complete water molecule as well: 
```
[<Atom 99998 (O) of chain 3 residue 31562 (HOH)>, <Atom 99999 (H1) of chain 3 residue 31562 (HOH)>, <Atom 100000 (H2) of chain 3 residue 31562 (HOH)>]
```
I'm using OpenMM 7.4.1. Definitely strange that it's the residue before that contains the atom ids wrapping around.

**Comment by jchodera** [comment]
@zhang-ivy : @peastman is working with the latest master from the repo, which is built nightly---you can try it out easily with
```bash
conda install --yes -c omnia-dev/label/cudaXY openmm
```
where `cudaXY` matches the CUDA X.Y version you are using (e.g. `cuda101`).

Can you see if that fixes the problem? If so, we can rush out a bugfix!

If not, you can revert with
```bash
conda install --yes -c omnia/label/cudaXY openmm
```

**Comment by zhang-ivy** [comment]
Ok, I ran the first command John sent, so now I am using:
```
openmm                    7.5.0            py36_cuda101_1    omnia-dev/label/cuda101
```

I am still getting the following output when I run simulate_4amu_5fs.py:
```Loading equilibrated.pdb
Loading forcefield: ['amber14/protein.ff14SB.xml', 'amber14/tip3p.xml']
Creating OpenMM System...
Traceback (most recent call last):
  File "simulate_4amu_5fs.py", line 48, in <module>
    system = forcefield.createSystem(pdb.topology, nonbondedMethod=app.PME, constraints=app.HBonds, removeCMMotion=False, hydrogenMass=hydrogen_mass)
  File "/Users/ivy/miniconda3/envs/py36/lib/python3.6/site-packages/simtk/openmm/app/forcefield.py", line 1145, in createSystem
    raise ValueError('No template found for residue %d (%s).  %s' % (res.index+1, res.name, _findMatchErrors(self, res)))
ValueError: No template found for residue 31562 (HOH).  The set of atoms matches HOH, but the bonds are different.
```

**Comment by peastman** [comment]
I see the problem.  I had it print out the bonds in that residue:

```python
for a1,a2 in pdb.topology.bonds():
    if 31562 in [a1.residue.index, a2.residue.index]:
        print(a1, a2)
```

And here's the result:

```
<Atom 99999 (H1) of chain 3 residue 31562 (HOH)> <Atom 99998 (O) of chain 3 residue 31562 (HOH)>
<Atom 100000 (H2) of chain 3 residue 31562 (HOH)> <Atom 99998 (O) of chain 3 residue 31562 (HOH)>
<Atom 99997 (H2) of chain 3 residue 31561 (HOH)> <Atom 99998 (O) of chain 3 residue 31562 (HOH)>
<Atom 99997 (H2) of chain 3 residue 31561 (HOH)> <Atom 100000 (H2) of chain 3 residue 31562 (HOH)>
<Atom 99998 (O) of chain 3 residue 31562 (HOH)> <Atom 100003 (H2) of chain 3 residue 31563 (HOH)>
```

Where did those extra bonds come from?  Answer: the CONECT records in the file:

```
CONECT    1    2    4    5    6
CONECT    2    1    3    7
CONECT    3    2
CONECT    4    1
CONECT    5    1
CONECT    6    1
CONECT    7    2
```

Because it runs out of columns for atom numbers and they have to start wrapping, that means there are actually two different atoms called "atom 1", and so it dutifully adds bonds to the water molecules.

The simplest solution is probably to just save in PDBx/mmCIF format instead of PDB.  It doesn't have this problem.

**Comment by rafwiewiora** [comment]
Oooh. The PDBx saving will be ok for most cases, but if want to do something to the equilibrated structure with MDTraj later, which doesn't have a PDBx reader (still doesn't right?) we have a problem -- guess could save both PDB and PDBx.

**Comment by peastman** [comment]
It doesn't?  Wow, we need to fix that!  As a workaround, you can load the file with OpenMM then use the `Topology.from_openmm()` method in MDTraj to convert the topology.

**Comment by rafwiewiora** [comment]
They've kept having these feature requests for years but no one had time to port it: https://github.com/mdtraj/mdtraj/issues/652
