### ISSUE TITLE
test simTK on new AMD: seems to be infinite loop

### ISSUE THREAD

**Issue by asedova** [openmm/openmm#2597]
Hi all,

I'm trying to test openMM on an OLCF test AMD system, x86 and Mi60 GPUs. I have the miniconda3 package installed and openmm seemed to install correctly. Running the test
python -m simtk.testInstallation
seems to put me in an infinite loop:
-bash-4.2$ python -m simtk.testInstallation

OpenMM Version: 7.4.1
Git Revision: 068f120206160d5151c9af0baf810384bba8d052

There are 3 Platforms available:

1 Reference - Successfully computed forces
2 CPU - Successfully computed forces

...and then it gets stuck indefinitely; I can't control D or control C out, I have to kill the terminal. 

Any ideas?

**Comment by peastman** [comment]
Not a lot of ideas.  I've never tested on that hardware.  Is it possible for you to monitor it when it's hung?  Is it still using CPU?  GPU?  Can you still interrupt the process with ctrl-Z?  If so that suggests something at the application level, and with a bit of work we can hopefully debug it.  If you can't, that suggests something at a much lower level (kernel, driver, etc.) which will be very difficult to debug.

It is possible for you to build OpenMM from source?  That will be important for debugging.

**Comment by asedova** [comment]
ctrl-Z works. I could build from source but not this week. I will definitely want to keep working on this.

**Comment by asedova** [comment]
Looks like it actually can finish, it just takes a really long time. I will keep testing.

**Comment by peastman** [comment]
If you're up for debugging, I'm definitely willing to help in tracking it down.  Once you're able to build from source, the first thing will be to try running some of the C++ test cases, like TestOpenCLHarmonicBondForce and TestOpenCLNonbondedForce.  See if you're able to reproduce it with any of those.  If you try a few and they run successfully, you can try `make test` to run all of them.

Assuming you can reproduce the problem with one of the test cases, the next thing would be to try running it in gcc.  Let it run until you're sure it has hung, then press ctrl-c and type `bt` to get a stack trace.  That should provide information about where it is.

**Comment by peastman** [comment]
Ok, that's interesting.  How long does it take?  And can you monitor the CPU and GPU usage while it's running?

**Comment by asedova** [comment]
I'm getting a "Memory access fault by GPU node-4 (Agent handle: 0x5566809ea150) on address 0x7f1d6121b000". It's a test system so anything could be the problem. I did manage to build and run gromacs with openCL with no issues at all, but this was a while ago and the system has had a number of changes since then. I don't seem to have access for ssh-ing into the work node right now to run top. But I will try to build from source and run the gdb next week.

**Comment by asedova** [comment]
It's most likely on my end with this system, I was just checking that you don't have any reason to think that using an Mi60 would be a problem.

**Comment by peastman** [comment]
I don't know of any particular reason it would be a problem.  I've never tested that card, but it does work on other Vega GPUs.

**Comment by asedova** [comment]
Ok, I'll try to figure this out and get back.
