### ISSUE TITLE
Does OpenMM make any use of the tensor cores in Volta and Turing NVIDIA GPUs?

### ISSUE THREAD

**Issue by rjfnobre** [openmm/openmm#2601]
Does OpenMM make any use of the tensor cores in Volta and Turing NVIDIA GPUs?

If not, then do you think some considerable portion of the OpenMM main calculations could be mapped to the tensor cores?

**Comment by peastman** [comment]
No, it doesn't use them at all.  We haven't come up with anything they'd be useful for in MD.  The tensor cores perform a very specific operation: multiply half precision matrices to produce a single precision result.  Half precision isn't accurate enough for most calculations in an MD simulation, and most of the bottleneck calculations don't resemble matrix multiplies.

**Comment by rjfnobre** [comment]
Thanks for the explanation.
I was wondering if there would be a way to rewrite the bootleneck calculations in OpenMM that would allow to make efficient use of the tensor cores, circunventing the intrinsic loss of precision at at the level of each individual matrix multiply operation.

I am not familiar with the OpenMM code (in fact not even with the type of algorithms used in OpenMM).
Can you point me to the type of calculations that are the bootleneck in OpenMM so that I can think about it algorithmically?
