### ISSUE TITLE
Zn Ions in OPenMM

### ISSUE THREAD

**Issue by MDcanSomehowBeFrustrating** [openmm/openmm#2603]
Dear all,

I try to simulate a protein with structural Zn2+ Ions. I replaced the Ions with dummy atoms.
The pdb, and xml looks fine but i still get this error: _**ValueError: No template found for residue 235 (ZNB).  This might mean your input topology is missing some atoms or b                                                onds, or possibly that you are using the wrong force field.**_

PDB and xml see below. Any help is appriciated.
Thanks for the effort.

ATOM      1  ZN  ZNB   246      13.775 -16.129  -7.046  1.00  0.00      Z    ZN  
ATOM      2  D1  ZNB   246      13.475 -15.280  -7.046  1.00  0.00      Z    Dy  
ATOM      3  D2  ZNB   246      14.675 -16.129  -7.046  1.00  0.00      Z    Dy  
ATOM      4  D3  ZNB   246      13.475 -16.554  -7.780  1.00  0.00      Z    Dy  
ATOM      5  D4  ZNB   246      13.475 -16.552  -6.310  1.00  0.00      Z    Dy  
ATOM      6  ZN  ZNB   247      10.621 -16.942  -5.177  1.00  0.00      Z    ZN  
ATOM      7  D1  ZNB   247      10.321 -16.093  -5.177  1.00  0.00      Z    Dy  
ATOM      8  D2  ZNB   247      11.521 -16.942  -5.177  1.00  0.00      Z    Dy  
ATOM      9  D3  ZNB   247      10.321 -17.367  -5.911  1.00  0.00      Z    Dy  
ATOM     10  D4  ZNB   247      10.321 -17.365  -4.441  1.00  0.00      Z    Dy  
ATOM     11  ZN  ZNB   248       3.392  19.798   2.221  1.00  0.00      Z    ZN  
ATOM     12  D1  ZNB   248       3.092  20.647   2.221  1.00  0.00      Z    Dy  
ATOM     13  D2  ZNB   248       4.292  19.798   2.221  1.00  0.00      Z    Dy  
ATOM     14  D3  ZNB   248       3.092  19.373   1.487  1.00  0.00      Z    Dy  
ATOM     15  D4  ZNB   248       3.092  19.375   2.957  1.00  0.00      Z    Dy
CONECT    1    2    3    4    5
CONECT    2    1
CONECT    3    1
CONECT    4    1
CONECT    5    1
CONECT    6    7    8    9    10
CONECT    7    6
CONECT    8    6
CONECT    9    6
CONECT    10   6
CONECT    11   12   13   14   15
CONECT    12   11
CONECT    13   11
CONECT    14   11
CONECT    15   11
END

<ForceField>
  <Info>
    <DateGenerated>2020-03-17</DateGenerated>
  </Info>
  <AtomTypes>
    <Type class="ZN" element="ZN" mass="53.380" name="ZN"/>
    <Type class="D" element="Dy" mass="3" name="DZ"/>
  </AtomTypes>
  <Residues>
    <Residue name="ZNB">
      <Atom name="ZN" type="ZN" charge="0.0"/>
      <Atom name="D1" type="DZ" charge="0.5"/>
      <Atom name="D2" type="DZ" charge="0.5"/>
      <Atom name="D3" type="DZ" charge="0.5"/>
      <Atom name="D4" type="DZ" charge="0.5"/>
      <Bond atomName1="ZN" atomName2="D1"/>
      <Bond atomName1="ZN" atomName2="D2"/>
      <Bond atomName1="ZN" atomName2="D3"/>
      <Bond atomName1="ZN" atomName2="D4"/>
    </Residue>
  </Residues>
  <PeriodicTorsionForce>
    <Improper type1="ZN" type2="DZ" type3="DZ" type4="DZ" periodicity1="2" phase1="0.616101225954" k1="0"/>
    <Improper type1="DZ" type2="ZN" type3="DZ" type4="DZ" periodicity1="2" phase1="2.0943951023932" k1="0"/>
    <Improper type1="DZ" type2="DZ" type3="DZ" type4="DZ" periodicity1="2" phase1="1.230457122656" k1="0"/>
  </PeriodicTorsionForce>
</ForceField>

**Comment by MDcanSomehowBeFrustrating** [comment]
<ForceField>
  <Info>
    <DateGenerated>2020-03-17</DateGenerated>
  </Info>
  <AtomTypes>
    <Type class="ZN" element="ZN" mass="53.380" name="ZN"/>
    <Type class="D" element="Dy" mass="3" name="DZ"/>
  </AtomTypes>
  <Residues>
    <Residue name="ZNB">
      <Atom name="ZN" type="ZN" charge="0.0"/>
      <Atom name="D1" type="DZ" charge="0.5"/>
      <Atom name="D2" type="DZ" charge="0.5"/>
      <Atom name="D3" type="DZ" charge="0.5"/>
      <Atom name="D4" type="DZ" charge="0.5"/>
      <Bond atomName1="ZN" atomName2="D1"/>
      <Bond atomName1="ZN" atomName2="D2"/>
      <Bond atomName1="ZN" atomName2="D3"/>
      <Bond atomName1="ZN" atomName2="D4"/>
    </Residue>
  </Residues>
  <PeriodicTorsionForce>
    <Improper type1="ZN" type2="DZ" type3="DZ" type4="DZ" periodicity1="2" phase1="0.616101225954" k1="0"/>
    <Improper type1="DZ" type2="ZN" type3="DZ" type4="DZ" periodicity1="2" phase1="2.0943951023932" k1="0"/>
    <Improper type1="DZ" type2="DZ" type3="DZ" type4="DZ" periodicity1="2" phase1="1.230457122656" k1="0"/>
  </PeriodicTorsionForce>
</ForceField>

**Comment by peastman** [comment]
What force field are you using?  It looks like you're using a complex ion model, where each physical atom is represented by five "atoms" all bonded to each other.  You'll need to provide your own force field parameters for that model.  The built in force fields don't support it.

**Comment by MDcanSomehowBeFrustrating** [comment]
The orce field is amber 14-all.
sorry, I forgot to attach the xml:

ForceField>
  <Info>
    <DateGenerated>2020-03-17</DateGenerated>
  </Info>
  <AtomTypes>
    <Type class="ZN" element="ZN" mass="53.380" name="ZN"/>
    <Type class="D" element="Dy" mass="3" name="DZ"/>
  </AtomTypes>
  <Residues>
    <Residue name="ZNB">
      <Atom name="ZN" type="ZN" charge="0.0"/>
      <Atom name="D1" type="DZ" charge="0.5"/>
      <Atom name="D2" type="DZ" charge="0.5"/>
      <Atom name="D3" type="DZ" charge="0.5"/>
      <Atom name="D4" type="DZ" charge="0.5"/>
      <Bond atomName1="ZN" atomName2="D1"/>
      <Bond atomName1="ZN" atomName2="D2"/>
      <Bond atomName1="ZN" atomName2="D3"/>
      <Bond atomName1="ZN" atomName2="D4"/>
    </Residue>
  </Residues>
  <PeriodicTorsionForce>
    <Improper type1="ZN" type2="DZ" type3="DZ" type4="DZ" periodicity1="2" phase1="0.616101225954" k1="0"/>
    <Improper type1="DZ" type2="ZN" type3="DZ" type4="DZ" periodicity1="2" phase1="2.0943951023932" k1="0"/>
    <Improper type1="DZ" type2="DZ" type3="DZ" type4="DZ" periodicity1="2" phase1="1.230457122656" k1="0"/>
  </PeriodicTorsionForce>
</ForceField>

This should define my force field right?

What might be an issue are non-nonded Force. Do you know where I can ifind the parameters for nonbonded forces of  Zn2+ ?

**Comment by MDcanSomehowBeFrustrating** [comment]
The force field is amber 14-all.
sorry, I forgot to attach the xml:

<ForceField>
  <Info>
    <DateGenerated>2020-03-17</DateGenerated>
  </Info>
  <AtomTypes>
    <Type class="ZN" element="ZN" mass="53.380" name="ZN"/>
    <Type class="D" element="Dy" mass="3" name="DZ"/>
  </AtomTypes>
  <Residues>
    <Residue name="ZNB">
      <Atom name="ZN" type="ZN" charge="0.0"/>
      <Atom name="D1" type="DZ" charge="0.5"/>
      <Atom name="D2" type="DZ" charge="0.5"/>
      <Atom name="D3" type="DZ" charge="0.5"/>
      <Atom name="D4" type="DZ" charge="0.5"/>
      <Bond atomName1="ZN" atomName2="D1"/>
      <Bond atomName1="ZN" atomName2="D2"/>
      <Bond atomName1="ZN" atomName2="D3"/>
      <Bond atomName1="ZN" atomName2="D4"/>
    </Residue>
  </Residues>
  <PeriodicTorsionForce>
    <Improper type1="ZN" type2="DZ" type3="DZ" type4="DZ" periodicity1="2" phase1="0.616101225954" k1="0"/>
    <Improper type1="DZ" type2="ZN" type3="DZ" type4="DZ" periodicity1="2" phase1="2.0943951023932" k1="0"/>
    <Improper type1="DZ" type2="DZ" type3="DZ" type4="DZ" periodicity1="2" phase1="1.230457122656" k1="0"/>
  </PeriodicTorsionForce>
  <NonbondedForce coulomb14scale="0.8333333333333334" lj14scale="0.5">
    <UseAttributeFromResidue name="charge"/>
    <Atom epsilon="0.00621311448" sigma="0.21702292773898668" class="UM"/>
    <Atom epsilon="0.0" sigma="0.0" class="DU1"/>
  </NonbondedForce>
</ForceField>


This should define my force field right?

What might be an issue are non-nonded Force. Do you know where I can ifind the parameters for nonbonded forces of Zn2+ ?

**Comment by MDcanSomehowBeFrustrating** [comment]
The force field is amber 14-all.
sorry, I forgot to attach the xml:

`<ForceField>
  <Info>
    <DateGenerated>2020-03-17</DateGenerated>
  </Info>
  <AtomTypes>
    <Type class="ZN" element="ZN" mass="53.380" name="ZN"/>
    <Type class="D" element="Dy" mass="3" name="DZ"/>
  </AtomTypes>
  <Residues>
    <Residue name="ZNB">
      <Atom name="ZN" type="ZN" charge="0.0"/>
      <Atom name="D1" type="DZ" charge="0.5"/>
      <Atom name="D2" type="DZ" charge="0.5"/>
      <Atom name="D3" type="DZ" charge="0.5"/>
      <Atom name="D4" type="DZ" charge="0.5"/>
      <Bond atomName1="ZN" atomName2="D1"/>
      <Bond atomName1="ZN" atomName2="D2"/>
      <Bond atomName1="ZN" atomName2="D3"/>
      <Bond atomName1="ZN" atomName2="D4"/>
    </Residue>
  </Residues>
  <PeriodicTorsionForce>
    <Improper type1="ZN" type2="DZ" type3="DZ" type4="DZ" periodicity1="2" phase1="0.616101225954" k1="0"/>
    <Improper type1="DZ" type2="ZN" type3="DZ" type4="DZ" periodicity1="2" phase1="2.0943951023932" k1="0"/>
    <Improper type1="DZ" type2="DZ" type3="DZ" type4="DZ" periodicity1="2" phase1="1.230457122656" k1="0"/>
  </PeriodicTorsionForce>
  <NonbondedForce coulomb14scale="0.8333333333333334" lj14scale="0.5">
    <UseAttributeFromResidue name="charge"/>
    <Atom epsilon="0.00621311448" sigma="0.21702292773898668" class="UM"/>
    <Atom epsilon="0.0" sigma="0.0" class="DU1"/>
  </NonbondedForce>
</ForceField>`

This should define my force field right?

What might be an issue are non-nonded Force. Do you know where I can ifind the parameters for nonbonded forces of Zn2+ ?

**Comment by MDcanSomehowBeFrustrating** [comment]
[code.txt](https://github.com/openmm/openmm/files/4360532/code.txt)

**Comment by peastman** [comment]
Amber14 puts its ion parameters in the file with the water model, since different water models use different parameters for them.  In all cases, it represents Zn with just a single atom.  For example,

```xml
    <Residue name="ZN">
      <Atom charge="2.0" name="ZN" type="tip3p_standard-Zn2+"/>
    </Residue>
```

That template won't match your five atom Zn model.  You need to create another XML file defining the force field parameters for it.  Documentation on how to do that is at http://docs.openmm.org/latest/userguide/application.html#creating-force-fields.

**Comment by jchodera** [comment]
@rafwiewiora : Did you ever create multisite ion models for OpenMM?

**Comment by MDcanSomehowBeFrustrating** [comment]
@peastman  I really appreciate your effort! Let me just confirm, if I got this correct. The Amber14-all/tip3p water model I am currently using, represents the Zn ions as one single atom. Since I am using a Zn2+ model with one Zn atom and 4 dummy atoms, openMM gets confused as there are too many bond/atoms. Therefore i have to create an additional xml file, where the forcefield parameters for my Zn2+ model are defined. Right?

On last question: how to I tell OpenMM then to used this additional forcefield file?

Thanks for your help.

**Comment by MDcanSomehowBeFrustrating** [comment]
@peastman like this
`<ForceField>
  <Info>
    <DateGenerated>2020-03-17</DateGenerated>
  </Info>
  <AtomTypes>
    <Type class="ZN" element="ZN" mass="53.380" name="ZN"/>
    <Type class="D" element="Dy" mass="3" name="Dy"/>
  </AtomTypes>
  <Residues>
    <Residue name="ZNB">
      <Atom name="ZN1" type="ZN" charge="0.0"/>
	  <Atom name="ZN2" type="ZN" charge="0.0"/>
	  <Atom name="ZN3" type="ZN" charge="0.0"/>
      <Atom name="D1" type="Dy" charge="0.5"/>
      <Atom name="D2" type="Dy" charge="0.5"/>
      <Atom name="D3" type="Dy" charge="0.5"/>
      <Atom name="D4" type="Dy" charge="0.5"/>
      <Atom name="D5" type="Dy" charge="0.5"/>
      <Atom name="D6" type="Dy" charge="0.5"/>
      <Atom name="D7" type="Dy" charge="0.5"/>
      <Atom name="D8" type="Dy" charge="0.5"/>
      <Atom name="D9" type="Dy" charge="0.5"/>
      <Atom name="D10" type="Dy" charge="0.5"/>
      <Atom name="D11" type="Dy" charge="0.5"/>
      <Atom name="D12" type="Dy" charge="0.5"/>
      <Bond atomName1="ZN1" atomName2="D1"/>
      <Bond atomName1="ZN1" atomName2="D2"/>
      <Bond atomName1="ZN1" atomName2="D3"/>
      <Bond atomName1="ZN1" atomName2="D4"/>
	  <Bond atomName1="ZN2" atomName2="D5"/>
      <Bond atomName1="ZN2" atomName2="D6"/>
      <Bond atomName1="ZN2" atomName2="D7"/>
      <Bond atomName1="ZN2" atomName2="D8"/>
	  <Bond atomName1="ZN3" atomName2="D9"/>
      <Bond atomName1="ZN3" atomName2="D10"/>
      <Bond atomName1="ZN3" atomName2="D11"/>
      <Bond atomName1="ZN3" atomName2="D12"/>
    </Residue>
  </Residues>
  <PeriodicTorsionForce>
    <Improper type1="ZN" type2="Dy" type3="Dy" type4="Dy" periodicity1="2" phase1="0.616101225954" k1="0"/>
    <Improper type1="Dy" type2="ZN" type3="Dy" type4="Dy" periodicity1="2" phase1="2.0943951023932" k1="0"/>
    <Improper type1="Dy" type2="Dy" type3="Dy" type4="Dy" periodicity1="2" phase1="1.230457122656" k1="0"/>
  </PeriodicTorsionForce>
  <NonbondedForce coulomb14scale="0.8333333333333334" lj14scale="0.5">
    <UseAttributeFromResidue name="charge"/>
    <Atom epsilon="4.184e-06" sigma="0.5523572052470104" class="ZN"/>
    <Atom epsilon="0.0" sigma="1.0" class="D"/>
  </NonbondedForce>
</ForceField>`

**Comment by peastman** [comment]
When you create a ForceField object, you pass a list of files to its constructor.  Just add your new file to the list.
