### ISSUE TITLE
OpenCL sortShortList error

### ISSUE THREAD

**Issue by bdenhollander** [openmm/openmm#2608]
The following error has been observed by various [FAH](https://foldingforum.org/viewtopic.php?f=74&t=32991) owners of AMD RX 460/470/480/570/580/590 GPUs.
`Error invoking kernel sortShortList: clEnqueueNDRangeKernel (-5)`

Using TestOpenCLSort.cpp and then adjusting it use the same `SortTrait` as OpenCLNonbondedUtilites.cpp, I've reproduced the problem when sorting arrays of `mm_float2` with between 4096 and 8192 elements on an RX 460.

Snippet from OpenCLSort.cpp
```
int maxLocalBuffer = (maxSharedMem/trait->getDataSize())/2;
unsigned int maxShortList = min(8192, max(maxLocalBuffer, (int) OpenCLContext::ThreadBlockSize*context.getNumThreadBlocks()));
```
The `/2` looked odd. I traced it back to this [https://github.com/openmm/openmm/blame/dd352ee536a429bfccd4aeda5258adafba8e0d84/platforms/opencl/src/OpenCLSort.h](commit). The name of the type was passed as a string so the `/2` might have accounted for scenarios like `mm_float2` with x and y.

Stepping through the test code with the debugger `maxShortList = min(8192, max(2048, 64*224))` evaluates to 8192. Testing with `mm_float2` arrays <= 4096 and >8192 elements finishes without throwing an exception. Between 4096 and 8192 should be using the long sort but the algorithm thinks it will fit in memory.

I would like to propose the following change but do not have access to a wide variety of hardware to confirm it doesn't introduce new problems.
```
int maxLocalBuffer = (maxSharedMem/trait->getDataSize());
unsigned int maxShortList = min(maxLocalBuffer, (int)OpenCLContext::ThreadBlockSize*context.getNumThreadBlocks());
```
The fix and modified test case are attached.
[sortShortList.zip](https://github.com/openmm/openmm/files/4372576/sortShortList.zip)

**Comment by peastman** [comment]
Here's the code that's most relevant to the problem:

https://github.com/openmm/openmm/blob/a752d258db6bc20fe5fb0ac6fe95f133b43a9732/platforms/opencl/src/OpenCLSort.cpp#L67-L71

OpenCL provides a way to check the maximum allowed size for the kernel.  Unfortunately, AMD's implementation of it is broken and returns the wrong value, leaving us to guess. :(

**Comment by bdenhollander** [comment]
The second snippet of code fixes the bug for my GPU. I would like some input from others before creating a pull request.

**Comment by peastman** [comment]
I think there's a better solution.  That change just makes a lower guess about what the maximum size will be.  It happens to fix the problem on this particular GPU, but there's no guarantee it won't fail on some other GPU in the future.  And it will hurt performance on GPUs that really could handle the larger number of threads.

So here's my idea.  Go ahead and try to use the short list, but catch the `cl::Error` if it fails.  In that case, set `isShortList` to false so we'll know the next time through, then go ahead and execute the regular kernels.

**Comment by bdenhollander** [comment]
I share the concern that this could negatively affect another GPU but I think this would be accurate. `CL_DEVICE_LOCAL_MEM_SIZE` divided by the size of the element to be sorted should give the max number of elements.

To me it looks like the current code limits the maximum short list to 8192 elements. If `CL_DEVICE_LOCAL_MEM_SIZE` was 48KB and it was sorting `vector<float>` it should be able to fit 12288 values `(48*1024/4)`.  Being able to use the short sort for longer lists should improve performance.

Catching the error would work as long as it's done every sort rather than globally because element size should affect `maxShortList`. The [test case](https://github.com/openmm/openmm/blob/a752d258db6bc20fe5fb0ac6fe95f133b43a9732/platforms/opencl/tests/TestOpenCLSort.cpp#L72) sorts `vector<float>`. [OpenCLNonbondedUtilities](https://github.com/openmm/openmm/blob/edbc8407b0361ce5152bad4bd91597080dee3b58/platforms/opencl/src/OpenCLNonbondedUtilities.cpp#L307) sorts `vector<mm_float2>` or `vector<mm_double2>` based on the `x` coordinate. When using double precision, it looks bound to throw when sorting `vector<mm_double2>` with 3072 to 8192 elements with the 48KB example. My suggestion would calculate the cutoff length as 3072 `(48 * 1024 / 8 / 2)`.

**Comment by peastman** [comment]
There are lots of factors that can limited the allowed work group size.  We don't know which one is limiting it in this case.  It might just as easily be the number of registers as the amount of local memory.

**Comment by bdenhollander** [comment]
Perhaps work group size or registers is a factor here. Can you suggest a way to test those?

Here's a walk through of the code in case it's useful.

`CL_DEVICE_LOCAL_MEM_SIZE` is 32KB on RX 460/470/480/570/580/590.
`CL_DEVICE_SIMD_PER_COMPUTE_UNIT_AMD` is 4
`CL_DEVICE_WAVEFRONT_WIDTH_AMD` is 4
```
maxLocalBuffer = (maxSharedMem/trait->getDataSize())/2;
maxLocalBuffer = (32768/sizeof(mm_float2)/2
maxLocalBuffer = (32768/8)/2
maxLocalBuffer = 2048
```
Existing code says 2048 elements should fit.
```
maxShortList = min(8192, max(maxLocalBuffer, (int) OpenCLContext::ThreadBlockSize*context.getNumThreadBlocks()));
maxShortList = min(8192, max(2048, 64*(4*4*14))) // 14 is based on the # of CUs and changes based on GPU model)
maxShortList = min(8192, max(2048, 14336))
maxShortList = min(8192, 14336)
maxShortList = 8192
```
Use 8192 as the cutoff for `isShortList`. Attempt to sort a `vector<mm_float2>` based on `x`
```
1000 = pass // short sort
4096 = pass // short sort
4097 = fail // attempts to use short sort
6000 = fail // attempts to use short sort
9000 = pass // long sort
```

**Comment by peastman** [comment]
Here's what the OpenCL spec says about that error code:

> CL_OUT_OF_RESOURCES if there is a failure to queue the execution instance of kernel on the command-queue because of insufficient resources needed to execute the kernel. For example, the explicitly specified local_work_size causes a failure to execute the kernel because of insufficient resources such as registers or local memory. Another example would be the number of read-only image args used in kernel exceed the CL_DEVICE_MAX_READ_IMAGE_ARGS value for device or the number of write-only image args used in kernel exceed the CL_DEVICE_MAX_WRITE_IMAGE_ARGS value for device or the number of samplers used in kernel exceed CL_DEVICE_MAX_SAMPLERS for device.

Notice that there's no universal list of resources it could be out of.  It cites a few examples, like registers and local memory, but that isn't an exhaustive list.  That's why I suggest just trying to execute the kernel and catching the exception if it fails.

**Comment by bdenhollander** [comment]
Alright. I'll leave this here as a suggested test case.

```
/**
 * Tests the OpenCL implementation of double precision sorting.
 * Intended for Titan X (or similar GPU with `CL_DEVICE_LOCAL_MEM_SIZE` of 48KB) with 
 * useShortList2 disabled in OpenCLSort.cpp to test the regular short path.
 */

#include "openmm/internal/AssertionUtilities.h"
#include "OpenCLArray.h"
#include "OpenCLContext.h"
#include "OpenCLSort.h"
#include "sfmt/SFMT.h"
#include "openmm/System.h"
#include <iostream>
#include <cmath>
#include <set>

using namespace OpenMM;
using namespace std;

static OpenCLPlatform platform;

class SortTrait : public OpenCLSort::SortTrait {
    int getDataSize() const {return sizeof(mm_double2);}
    int getKeySize() const {return sizeof(cl_double);}
    const char* getDataType() const {return "real2";}
    const char* getKeyType() const {return "real";}
    const char* getMinKey() const {return "-MAXFLOAT";}
    const char* getMaxKey() const {return "MAXFLOAT";}
    const char* getMaxValue() const {return "(real2) (MAXFLOAT, MAXFLOAT)";}
    const char* getSortKey() const {return "value.x";}
};

void verifySorting(vector<mm_double2> array) {
    // Sort the array.

    System system;
    system.addParticle(0.0);
    OpenCLPlatform::PlatformData platformData(system, "", "", platform.getPropertyDefaultValue("OpenCLPrecision"), "false", "false", 1, NULL);
    OpenCLContext& context = *platformData.contexts[0];
    context.initialize();
    OpenCLArray data(context, array.size(), sizeof(mm_double2), "sortData");
    data.upload(array);
    OpenCLSort sort(context, new SortTrait(), array.size());
    sort.sort(data);
    vector<mm_double2> sorted;
    data.download(sorted);

    // Verify that it is in sorted order.

    for (int i = 1; i < (int) sorted.size(); i++)
        ASSERT(sorted[i-1].x <= sorted[i].x);

}

void testShortList(int elements) {
    OpenMM_SFMT::SFMT sfmt;
    init_gen_rand(0, sfmt);
 
    vector<mm_double2> array(elements);
	for (int i = 0; i < (int)array.size(); i++) {
		array[i] = mm_double2((float)log(genrand_real2(sfmt)), (float)log(genrand_real2(sfmt)));
	}
    verifySorting(array);
}

int main(int argc, char* argv[]) {
    try {
        platform.setPropertyDefaultValue("OpenCLPrecision", "double");
        testShortList(3072);
        testShortList(3073);
    }
    catch(const exception& e) {
        cout << "exception: " << e.what() << endl;
        return 1;
    }
	cout << "Done" << endl;
    return 0;
}
```

**Comment by peastman** [comment]
The fix is in #2631.  Could you try it out and see if it fixes the problem for you?

**Comment by bdenhollander** [comment]
The exception is caught successfully and the sort continues.

I still think the isShortList logic could be improved. Could you run this enhanced test on NVIDIA hardware using `sortShortList` and see if it throws the exception?

[TestOpenCLSort.cpp.txt](https://github.com/openmm/openmm/files/4432367/TestOpenCLSort.cpp.txt)

**Comment by peastman** [comment]
Thanks!  Your test passes in all three precision modes, so I'll go ahead and merge the fix.
