### ISSUE TITLE
Principal components as the collective variables in metadynamics

### ISSUE THREAD

**Issue by AlchemistYuan** [openmm/openmm#2610]
Dear OpenMM users,

I would like to run metadynamics in OpenMM using the first principal component (PC1) as the collective variable. I had computed the PC coordinates and the reference structure based on an unbiased MD. Basically what I want to do is to align the coordinates of the protein to the reference structure based on a provided frequency (the same as the frequency of adding Gaussians). Then the dot products between the aligned coordinates and the reference structure will be computed and the result would be the CV value at this particular moment. The current CV value will be passed to/updated in a `Custom*Force()` object, which is the `force` argument in `BiasVariable()`. So in this way, within `Metadynamics`, Gaussians will be deposited along those CV values.

The problem is the alignment step. Initially, I tried the `CustomCVForce()` and passed the CV values to it. Therefore I need to align structure on my own, possibly relying on other packages. However, this approach would not work since there is no `SetCollectiveVariableValues()` method in `CustomCVForce()`. 

Could anyone suggest any alternative approaches? Thanks!

**Comment by peastman** [comment]
You don't set the value of the collective variable.  You provide a Force object that computes it.  In this case, you could do it with a CustomExternalForce:

```python
pcForce = CustomExternalForce('x*pcx + y*pcy + z*pcz')
pcForce.addPerParticleParameter('pcx')
pcForce.addPerParticleParameter('pcy')
pcForce.addPerParticleParameter('pcz')
for i, pc in enumerate(principleComponent):
  pcForce.addParticle(i, pc)
cvForce.addCollectiveVariable(pcForce, 'pc')
```

`principleComponent` is a list of Vec3s (or alternatively a 2D numpy array) containing the value of the principle component for each atom.
