### ISSUE TITLE
Running application using GPUs at ppc64le system (Longhorn@TACC)

### ISSUE THREAD

**Issue by mtitov** [openmm/openmm#2613]
Hi,

There is the application we try to run at Longhorn (TACC) using `srun` and `ibrun`, and certain parameters are set by env variables `CUDA_VISIBLE_DEVICES` (for gpus) and `OMP_NUM_THREADS` (for cpu threads).

Tried to define a particular GPU per task:
```
gpu_index = os.environ["CUDA_VISIBLE_DEVICES"]
```
(later this `gpu_index` was used as `GPU_index` here https://github.com/2019-ncovgroup/DrugWorkflows/blob/devel/workflow-2/MD_exps/MD_utils/openmm_simulation.py#L159)

Then only with `gpu_index = 0` it works, with other cases (1,2,3) it returns an error (NOTE: at Longhorn, every node has 4 GPUs):
```
Traceback (most recent call last):
  File "/home/07151/tg864504/DrugWorkflows/workflow-2/MD_exps/fs-pep/run_openmm.py", line 42, in <module>
    sim_time=float(args.length)*u.nanoseconds)
  File "/home/07151/tg864504/DrugWorkflows/workflow-2/MD_exps/MD_utils/openmm_simulation.py", line 219, in openmm_simulate_amber_fs_pep
    simulation = app.Simulation(pdb.topology, system, integrator, platform, properties)
  File "/home/07151/tg864504/.miniconda3/envs/covid-19-2/lib/python3.6/site-packages/simtk/openmm/app/simulation.py", line 105, in __init__
    self.context = mm.Context(self.system, self.integrator, platform, platformProperties)
  File "/home/07151/tg864504/.miniconda3/envs/covid-19-2/lib/python3.6/site-packages/simtk/openmm/openmm.py", line 7878, in __init__
    this = _openmm.new_Context(*args)
Exception: Illegal value for DeviceIndex: 1
srun: error: c001-005: task 0: Exited with exit code 1
```

I've found that there was a similar ticket here - https://github.com/openmm/openmm/issues/2533 - and just wonder if it could be related/connected

### Version of OpenMM ###

I've tried both following installations:

1) version 7.4.0

conda install -y openmm=7.4.0=py36_cuda101_0

2) version 7.5.0

followed these instructions https://gist.github.com/lee212/4bbfe520c8003fbb91929731b8ea8a1e
except "iv" and "v", which are:

module load cmake/3.16.1
module load gcc/7.3.0
module load cuda/10.1

conda install -y fftw3f doxygen

cmake .. \
-DCUDA_HOST_COMPILER=/opt/apps/gcc/7.3.0/bin/gcc \
-DCUDA_SDK_ROOT_DIR=/opt/apps/cuda/10.1/samples/ \
-DCUDA_TOOLKIT_ROOT_DIR=/opt/apps/cuda/10.1/ \
-DCMAKE_CXX_COMPILER=/opt/apps/gcc/7.3.0/bin/g++ \
-DCMAKE_C_COMPILER=/opt/apps/gcc/7.3.0/bin/gcc \
-DBUILD_TESTING=OFF \
-DOPENMM_BUILD_CUDA_TESTS=OFF \
-DOPENMM_GENERATE_API_DOCS=OFF \
-DCMAKE_INSTALL_PREFIX=${HOME}/openmm/

Regards, Mikhail

**Comment by peastman** [comment]
Possibly I'm misunderstanding what you're doing, but I take it you're setting `CUDA_VISIBLE_DEVICES` so that only one device is visible?  When you do that, it looks to applications like that's the only device in the machine.  Whatever devices the application can see are always numbered starting at 0.  So in OpenMM, you should set `DeviceIndex` to 0.

**Comment by mtitov** [comment]
Missed one more thing: there are 4 tasks running in parallel at one node (requirements for each task are 4 threads and 1 gpu). Corresponding shell script sets the environment (including that env variables) and launches executable (in our case it's python module `run_openmm.py`) with arguments. And in this case if not to provide a certain `index` every task will try to get `DeviceIndex=0`

example of shell script:
```bash
login2.longhorn(1098)$ cat radical.pilot.sandbox/re.session.login1.longhorn.tacc.utexas.edu.tg864504.018345.0008/pilot.0000/unit.000000/unit.000000.sh 
#!/bin/sh 
... 
export OMP_NUM_THREADS=4
export CUDA_VISIBLE_DEVICES=0
... 
module load gcc/7.3.0 
module load openmpi/3.1.2 
module load cuda/10.1 
... 
/usr/local/bin/ibrun -n 1 -o 0 /home/07151/tg864504/.miniconda3/envs/covid-19-2/bin/python "/home/07151/tg864504/DrugWorkflows/workflow-2/MD_exps/fs-pep/run_openmm.py" "--pdb_file" "/home/07151/tg864504/DrugWorkflows/workflow-2/MD_exps/fs-pep/pdb/100-fs-peptide-400K.pdb" "--length" "5" 
```

**Comment by peastman** [comment]
The way to handle this is that one script should set `CUDA_VISIBLE_DEVICES=0`, another should set `CUDA_VISIBLE_DEVICES=1`, etc.  And all four of them should set `DeviceIndex` to 0.  Each will think it's running on a computer with only one GPU and use that one.  But in fact, each of them is seeing a different GPU.

**Comment by jchodera** [comment]
We haven't used `ibrun` before, but for Torque/Moab, we use [this tool](https://github.com/choderalab/clusterutils) to automatically construct an `mpirun` configfile that appropriately specifies `CUDA_VISIBLE_DEVICES` for each launched process. The code then just uses device index 0, and each process is allocated a single GPU device. Not sure if this could be adapted to be useful here!

**Comment by mtitov** [comment]
Peter and John, thank you! It's more clear now with `DeviceIndex` and also will check that tool!

**Comment by mtitov** [comment]
Hello! We got to be able to assign tasks to GPUs, some fixes were made to `ibrun` (wrapper for `mpirun`, `srun`, etc.) directly. Thanks again!
