### ISSUE TITLE
Instructions for running performance benchmarks

### ISSUE THREAD

**Issue by dwtowner** [openmm/openmm#2617]
I think I can help optimise some of the CPU code, but I want to be able to run performance benchmarks to be able to measure the improvements. I see that various benchmark results are published (e.g., http://openmm.org/about.html#benchmarks) but how do I run those same benchmarks on my checkout of the repo? I can't find any instructions anywhere which tell me how to do that. Or if those published benchmarks are difficult to work with, and there any within the default repo which would be suitable instead?

**Comment by peastman** [comment]
That would be great!  You'll find lots more benchmarks at https://simtk.org/plugins/moinmoin/openmm/Benchmarks.  All of them are run with the benchmark.py script found in the examples folder.  Run

```
python benchmark.py --help
```

for details on how to run it.  For example, you can run a basic PME benchmark with DHFR with the command

```
python benchmark.py --platform=CPU --seconds=10 --test=pme
```

**Comment by dwtowner** [comment]
Okay, I've got the benchmarks running and have done a little playing around to get a feel for it. My expertise is around AVX optimisation, so I have been looking at the Vectorise8.h file and the places it is used. A few questions, to direct my work a bit:

- I tried a few different benchmarks and they use AVX to varying amounts and in slightly different ways. Which is the most important to you to speedup? Obviously COVID-19 is the hot topic - what would it benefit from?

- An easy speedup gain would come from compiling with AVX2 and extra instructions in AVX2 make some optimisations easier too, but the default build assumes only AVX. That is a fair assumption as it gives the widest compatibility to downloaded binaries, but performance on more recent machines won't be as good. If I added runtime selection of AVX2 as well as plain AVX, would that be acceptable as a way to get AVX2 in the binaries? If you run openmm on bigger server machines do you ever compile for the machine's native instruction set to be able to use AVX2 or beyond?

- I could add AVX-512 support if you wanted.

- Even if you don't want AVX2 or beyond I will still do a few optimisations that I've noticed that could give a bit of speedup here and there.

**Comment by peastman** [comment]
Try out the AVX2 optimizations and see how much difference they make.  If it's very small, it's probably not worth the trouble.  But if it makes a big difference, we could allow people to optionally compile with AVX2 support.

The best benchmarks to focus on are probably `pme` and `apoa1pme`.  The former simulates DHFR, which is a smallish protein.  The latter simulates a larger protein that's more typical of most simulations, but simulations of large proteins are usually done on GPUs.  So DHFR might be a better representative of things people would actually use the CPU platform for.  In any case, the bottlenecks in both will probably be identical.

**Comment by dwtowner** [comment]
I pulled out a few of the functions in the CPU NonbondedForceVec8 file into micro-benchmarks and got them to go faster, using just basic AVX, but when I run the benchmark as you suggest it makes only about 3% difference to the reported ns/day value. 

I used `perf top' to look at what was happening during a long benchmark run and it seems that the Nonbonded CPU AVX code is only running for about 20% of the time, and the remaining time is taken up running functions like fftpack, update_bsplines, and pme_grid_interpolate_force. From looking at the source code these seem to be reference functions, so I'm unsure why they are running at the same time as the benchmark. Only running for 20% of the time explains why the optimisations make little difference (so really that 3% gain is more significant than it appears).

Some other observations:
  - Test machine is a 40 core Xeon Skylake, no hyper-threading.
  - Allocating the entire machine to the benchmark gives about 40% speedup over giving it a single core (using taskset). Do you expect it to scale up with number of cores?
  - About 80 threads are spawned by the benchmark. All but a couple appear to be idle though. I'm not sure why they are being spawned.
  - Setting OPENM_CPU_THREADS to 1 improves the speed when running on a single core, but makes no difference to now many threads seem to spawn.

I suspect I'm misunderstanding something. Sorry for the questions and confusion. I hope though that the 3% gain I'm getting with that code only running 20% of the time might translate into a useful speedup.

**Comment by peastman** [comment]
That means it's using the reference implementation of PME rather than the optimized one.  Most likely this means it couldn't find FFTW.  Make sure it's in your library path.  If in doubt, check `Platform::getPluginLoadFailures()` to see if it reports an error loading libOpenMMPME.

**Comment by peastman** [comment]
One other thing to note is that I've never tried it on a machine with anything close to 40 cores.  It's likely that the fastest performance will be at some smaller number of threads.  You can set the environment variable `OPENMM_CPU_THREADS` to a lower number to limit how many threads it tries to use.  In past benchmarks, I think we generally got best performance somewhere around 16.  Improving the scaling to larger numbers of threads would be really useful.

**Comment by dwtowner** [comment]
Keeping to just AVX, I've tweaked various functions and reorganised the code somewhat and achieved about 20% speedup. I've been using C++11 features like lambdas and constexpr though. I couldn't find any coding standards for openmm though which say whether they are permitted in your code base or not, though I assume they probably are as you have C++11 enabled..

If you want the new code I can either give you one commit with all the changes, or several commits which build on each other. Which is preferable?

Adding AVX2 flags gives an additional 5%. Probably not worth specialising for that case.

All my timings were run on a single frequency-locked Skylake Xeon core with 1 openmm thread, running the pme benchmark.

I see what you mean about scaling on multi-core. 16 threads seems about the best, as you say.

**Comment by peastman** [comment]
Excellent!  Go ahead and send a PR in whatever form is best for you, one commit or multiple.  And C++11 is fine.  We already require it.

**Comment by dwtowner** [comment]
Just submitted another pull request. I've done substantial changes this time around, but logically it is one big group of related changes. I've explained the reasoning of each change below.

I noticed that there was quite a bit of duplicated code which was making it difficult to take my various optimisations and apply them equally well across all the different functions and targets. For example, the code for calculating Ewald and non-Ewald interactions was virtually the same, differing in only a few places. I have combined those functions so that a template parameter ispassed in to control which sort of interaction is being done.

My next change was based on the observation that SSE and AVX code was also virtually the same in form, but differed only in underlying SIMD type: fvec4 or fvec8. A good technique for handling this case is to create a single templated class which accepts the SIMD type to use, and then to write the algorithms within that class in terms of overloaded functions. To that end I replaced the CpuNonbondedForceVec4 and CpuNonbondedForceVec8 classes (and their headers, etc.) with a templated class I've named CpuNonbondedForceFvec, which can then be templated with the appropriate SIMD type:

   CpuNonbondedFvec<fvec4>
   CpuNonbondedFvec<fvec8>

So, the result of those two refactoring is there is now really only one copy of the force interaction code, which is then instantiated into the appropriate ewald/non-ewald (what's a better name?), and SIMD type. Any optimising changes made to that one copy of the function will then be reflected in all CPU classes and interaction types.

My third change, which is not yet fully complete, is to modify the runtime detection of CPU type, which then instantiates the appropriate CPU code. My aim behind this is to allow AVX2 code to be built as well, and then used in preference to the plain AVX code when possible. AVX2 in the new implementation gives a 13% boost over the AVX code, so I think that is worth having. I will also create a new fvec8_avx2 class which will bring further optimisations for that machine. The runtime support now has a handler which returns a plain pointer to the best SIMD implementation for the machine in question, rather than having to do queries on it (i.e., no need for isVec8Supported). Also, the optimal block size can be returned by the handler too, making it easy to add AVX-512 in future.

Performance measurements on my Skylake machine (detailed in previous conversation) for improvements show SSE speedup of 5%, AVX of 8%. In addition AVX2 is 13% faster than AVX (and 22% faster than origin/master AVX code).

Please can you review the pull request to see what you think. I'm hope you don't mind my doing such a substantial change. With these changes done I think it will be straightforward to some further optimisations, in particular specialising the code more closely to the target CPU.

Next steps:
  - Address any issues you might have in code review.
  - Finish runtime detection
  - Add better AVX2 optimisations
  - Add AVX-512 (which will be trivial now - just add an fvec16 class and instantiate). I know there are lots of spare Skylake servers available for folding where I work, so using them efficiently would be good.
  - Do a few other optimisations I've still got lined up, which used to give about 15% improvement.
