### ISSUE TITLE
ARM support and improvements

### ISSUE THREAD

**Issue by mark-mb** [openmm/openmm#2618]
I saw that the current support for Arm was a bit outdated it, so I started brushing it up.

 - What set inputs and benchmarks would you recommend to use to tweak and test improvements?
 - What would you want to see updated in the Arm part of OpenMM?

**Comment by peastman** [comment]
> What would you want to see updated in the Arm part of OpenMM?

#2499 also relates to ARM fixes.  @jaimergp may have thoughts about this.

> What set inputs and benchmarks would you recommend to use to tweak and test improvements?

You can use the benchmark.py script in the examples folder to run lots of different benchmarks.  A good default one is

```
python benchmark.py --platform=CPU --seconds=10 --test=pme
```

I'm assuming you're interested in the CPU platform.  The speed of ARM specific code is mostly irrelevant when running on a GPU.
