### ISSUE TITLE
Which Python version is supported?

### ISSUE THREAD

**Issue by RasmusWL** [openmm/openmm#2622]
I had some trouble figuring out which Python version was supported. Is there a place where this is officially stated?

I was convinced that Python 2.7 was still supported after reading this

https://github.com/openmm/openmm/blob/9e75b2261e65670ca923cfb46a5b520c2384d16f/wrappers/python/setup.py#L233-L234

However, I noticed that in https://github.com/openmm/openmm/issues/2548 @peastman says

> Now that we've dropped Python 2 support

If Python 2 is no longer supported, it would be great to update setup.py to reflect this. If Python 2 _is_ still supported (which I doubt), I think it could be great to explicitly state it somewhere (other than setup.py) :blush: 

### More info and links that I found

I also found the PR https://github.com/openmm/openmm/pull/2472 that stops Jenkins from testing on Python 2.

After looking around at quite a few documentation pages 

- http://docs.openmm.org/development/api-python/index.html
- https://anaconda.org/omnia/openmm
- http://openmm.org/
- https://github.com/openmm/openmm/issues/1912 (from 2017, couldn't see any recent update)

I finally found http://docs.openmm.org/latest/userguide/application.html#installing-openmm, that says:

> 1. Begin by installing the most recent 64 bit, Python 3.x version of either Anaconda or Miniconda.

but that doesn't actively mean that Python 2 is no longer supported, only that Python 3.x is recommended.

**Comment by peastman** [comment]
The most recent release (7.4.1) is supported on Python 2.7.  We have conda packages for 2.7, 3.6, and 3.7.

We've dropped support for 2.7 in the development code, so the next release will not support it.
