### ISSUE TITLE
Help with Cuda 10.2 Solution

### ISSUE THREAD

**Issue by hnisonoff** [openmm/openmm#2624]
If I only have access to a cuda 10.2 driver is it still possible to install openmm? I would be okay with a cpu-only solution. I could not find a way to have conda ignore my 10.2 driver. Are there plans to release a 10.2-compatible openmm? Thank you!

**Comment by hnisonoff** [comment]
Turns out I did have 10.1 installed as well and changing PATH and LD_LIBRARY_PATH variables appropriately allowed me to install to 10.1

**Comment by peastman** [comment]
Also, drivers are backward compatible.  You can use the 10.1 toolkit with the 10.2 driver, but not the other way around.
