### ISSUE TITLE
OpenMM_7.4.1 failed to compile on IBM Power9

### ISSUE THREAD

**Issue by frank-stonybrook** [openmm/openmm#2630]
Dear OpenMM developers,

I am trying to compile the OpenMM(7.4.1) on a IBM Power9 architecture machine (Frontera@TACC). The GNU complier I am using  is gcc/7.3.0.

Here is the error message:
![Screen Shot 2020-04-03 at 15 48 16](https://user-images.githubusercontent.com/10855977/78399297-a759b200-75c2-11ea-852e-7cbe440737c9.png)
 
Thanks for your help
Cong

**Comment by peastman** [comment]
It's getting errors trying to compile the C wrappers.  That might just be caused by having an out of date copy of the generated files.  Try deleting the `wrappers` subdirectory inside your build directory and see if the error goes away.

If not, you could just disable building the C wrappers by setting the CMake variable `OPENMM_BUILD_C_AND_FORTRAN_WRAPPERS` to off.

**Comment by frank-stonybrook** [comment]
Thanks Peter! The second option works. However, the following "Make PythonInstall" failed at the last step with a new error. 
![Screen Shot 2020-04-03 at 16 35 59](https://user-images.githubusercontent.com/10855977/78402954-8779bc80-75c9-11ea-814c-4ba9312b2ac5.png)
And I am using python3.8 at this system.

**Comment by peastman** [comment]
I've never seen that one before.  I'd guess it's an incompatibility between your versions of Python and SWIG.  I'd try either downgrading to Python 3.7 or updating to a newer version of SWIG.  After doing that, delete the `wrappers` and `python` directories inside your build directory before rebuilding.

**Comment by frank-stonybrook** [comment]
Okay, I will update my swig to newer version and give a try. Thanks!

**Comment by frank-stonybrook** [comment]
I tried downgrade python to 3.7 and update swig to 3.0.12, but the compilation failed with the same error. I attached the log file of command "make PythonInstall"  [out.log](https://github.com/openmm/openmm/files/4430185/out.log)

Here are the compilation parameters: cmake 
-DCUDA_CUDA_LIBRARY=/opt/apps/cuda/10.1/lib64/stubs/libcuda.so
-DCMAKE_INSTALL_PREFIX=$openmm_dir/Bin
-DCMAKE_C_COMPILER=/opt/apps/gcc/7.3.0/bin/gcc
-DCMAKE_CXX_COMPILER=/opt/apps/gcc/7.3.0/bin/g++
-DOPENMM_BUILD_C_AND_FORTRAN_WRAPPERS=OFF

Thanks

**Comment by peastman** [comment]
Very strange!  I've never seen that error, and I can't find anyone reporting it online.

I do think this is a SWIG problem.  Your error log reports an error in the following line of OpenMMSwig.cxx (which is generated by SWIG):

```c++
/*@SWIG:/home/06699/conliu/.anaconda3/envs/COVID19_py37/share/swig/3.0.12/typemaps/swigmacros.swg,200,%formacro@*//*@SWIG:/home/06699/conliu/.anaconda3/envs/COVID19_py37/share/swig/3.0.12/typemaps/swigmacros.swg,192,%_formacro_1@*/%_factory_dispatch
```

Looking at the version of that file on my computer, I notice the corresponding lines are slightly different:

```c++
/*@SWIG:/usr/local/share/swig/4.0.1/typemaps/swigmacros.swg,193,%formacro@*//*@SWIG:/usr/local/share/swig/4.0.1/typemaps/swigmacros.swg,185,%_formacro_1@*//*@SWIG:/usr/local/share/swig/4.0.1/typemaps/factory.swg,72,%_factory_dispatch@*/ 
```

If you scroll to the end of the line, you'll notice an important difference.  On my version, the entire line is commented out.  But on your version, the comment ends just before `%_factory_dispatch`.

Can you try upgrading to the latest version of SWIG?  That's 4.0.1.  Though I've certainly used 3.0.x versions in the past and haven't had this problem.

**Comment by frank-stonybrook** [comment]
Hi Peter,

I just updated `swig` to `4.0.1` and rebuild openmm from scratch. However, the "make" commands failure immediately when swig tries to generate python modules. The errors are attached below
![Screen Shot 2020-04-03 at 20 23 04](https://user-images.githubusercontent.com/10855977/78415153-ec470e00-75ed-11ea-94d0-d167427e3f5e.png)

**Comment by peastman** [comment]
No idea.  It works fine on my computer with 4.0.1.  And I can't find any reports of that error message online.  This may be something specific to that computer.  Supercomputers tend to be very nonstandard in their compilers, operating systems, etc.  It may have to be debugged directly on that computer.

**Comment by frank-stonybrook** [comment]
Okay, Thanks for your help!  I have contacted them and will keep you posted.

**Comment by peastman** [comment]
Asking the SWIG developers might also be useful.  They may have more idea what's going on with the generated code.

**Comment by frank-stonybrook** [comment]
Finally I figured the reason. I made a very stupid mistake: the old CMakeCache.txt somehow didn't get clean during my multiple compilation trials. The swig version recorded in the CMakeCach.txt file (3.0.12) doesn't match with the one (swig 4.0.1) installed in my environment. I was lucky to catch it when I revisited the out.log file:

> /home/06699/conliu/.anaconda3/envs/COVID19_py37/share/swig/3.0.12/

Once I cleaned the old cache file and recompiled it from scratch, I was able to successfully compile it.

Thanks for your help, @peastman! You can close this ticket now.

**Comment by peastman** [comment]
Sounds painful to debug!  I'm glad you figured it out.
