### ISSUE TITLE
Implementation issue in Amber OBC XML files

### ISSUE THREAD

**Issue by chuantian** [openmm/openmm#2636]
The parameters in files openmm/wrappers/python/simtk/openmm/app/data/amber*_obc.xml, are wrongly implemented I'm afraid. For instance, the amide H in backbone should have radius of 0.13 instead of 0.12. In addition, is it necessary to use three decimal places? The original OBC model doesn't seem to have that precision. Amber software only uses 2 decimal places. 
Also, can somebody make sure the partial charge are consistent across these amber*_obc.xml files? The GB-OBC parameter should be trained with the same set of partial charges.

**Comment by peastman** [comment]
The radii in that file come from Tinker.  They're slightly different from the ones used in Amber.  See http://docs.openmm.org/latest/userguide/application.html#older-amber-force-fields.
