### ISSUE TITLE
mW water (corse grained water model) in openMM

### ISSUE THREAD

**Issue by arjunwadhawan** [openmm/openmm#2637]
Dear users and developers,
I want to use mW water model for simulation in openMM. mW is based on  stillinger-weber type of forcefield and has originated from this article (https://www.ncbi.nlm.nih.gov/pubmed/18956896).

Now I have an feel that it can be implemented in openMM using CustomManyParticleForce .
The full expression of the SW potential as a function of the distances between pairs of atoms and the angles formed by triplets of atoms is given by
![image](https://user-images.githubusercontent.com/21062948/78872487-a654d480-7a49-11ea-83eb-69ec10815dd4.png)

Has anyone already implemented successfully? If so, I would be glad if you can share the working model's .xml and details 

PS: I was not sure where to ask this type of question so posting here as issue. If this is not allowed then please feel free to delete the post

**Comment by peastman** [comment]
Back when I first created CustomManyParticleForce, I wrote an implementation of mW water as an example for it.  The XML is below. This has not been thoroughly tested, so I don't guarantee it's entirely correct!  You should validate it by comparing energies to another implementation.  But hopefully it's correct, or at least fairly close.

```xml
<ForceField>
 <AtomTypes>
  <Type name="MW-O" class="OW" element="O" mass="18.015324"/>
 </AtomTypes>
 <Residues>
  <Residue name="HOH">
   <Atom name="O" type="MW-O"/>
  </Residue>
 </Residues>
 <CustomNonbondedForce bondCutoff="1" energy="A*eps*(B*sr^p-sr^q)*exp(sig/(r-a*sig)); sr=sig/r; A=7.049556277; B=0.6022245584; p=4; q=0; sig=0.23925; eps=25.894776; a=1.8">
  <Atom type="MW-O"/>
 </CustomNonbondedForce>
 <CustomManyParticleForce particlesPerSet="3" permutationMode="UniqueCentralParticle" bondCutoff="1"
        energy="L*eps*(cos(theta1)-ct0)^2*exp(sigma*gamma/(r12-a*sigma))*exp(sigma*gamma/(r13-a*sigma)); r12=distance(p1,p2); r13=distance(p1,p3); theta1=angle(p3,p1,p2); L=23.13; ct0=-1/3; sigma=0.23925; eps=25.894776; gamma=1.2; a=1.8">
  <Atom type="MW-O" filterType="0"/>
 </CustomManyParticleForce>
</ForceField>
```
