### ISSUE TITLE
Repo version (CPU only) doesn't compile on MacOS 

### ISSUE THREAD

**Issue by apallath** [openmm/openmm#2640]
I've been trying to compile OpenMM on MacOS 10.15.2 from the current source code, and `make PythonInstall` fails.

![Screen Shot 2020-04-11 at 7 06 43 PM](https://user-images.githubusercontent.com/16438875/79056786-d35ede00-7c27-11ea-8ca2-9d807e9abceb.jpg)

This doesn't happen when I compile OpenMM release 7.4.1 from source. 

However, I need to compile OpenMM from the latest source code to use OpenMM-torch, as per @peastman's response to https://github.com/openmm/openmm-torch/issues/11 (I've been facing the same issue).

**Comment by peastman** [comment]
You have an inconsistency between different code versions.  Try deleting the `wrappers` and `python` subdirectories inside your build directory, then build again.  Does that fix it?

**Comment by apallath** [comment]
I tried deleting the `wrappers` and `python` subdirectories, and also tried building from scratch again on the same machine and then on a different machine running MacOS 10.14. I get the same errors.

**Comment by apallath** [comment]
I get these warnings on `make`, (in case it helps):

![Screen Shot 2020-04-11 at 10 46 27 PM](https://user-images.githubusercontent.com/16438875/79059327-8fc79c80-7c46-11ea-9be3-48db7eeb398a.jpg)

**Comment by peastman** [comment]
That image doesn't show any errors, just warnings.  It looks like it succeeded?

**Comment by apallath** [comment]
The image above (with the warnings) is the output on running make (before running `make install` and `make PythonInstall`). When I run `make PythonInstall`, I get this (the same errors as before). Sorry if I wasn't clear before!

![Screen Shot 2020-04-11 at 11 54 23 PM](https://user-images.githubusercontent.com/16438875/79060175-d4a40100-7c4f-11ea-90f9-acace91f2f05.jpg)

**Comment by peastman** [comment]
Do you already have an old version of OpenMM installed in that Python?  If so, try removing it.  The classes it's complaining about, like LangevinMiddleIntegrator and NoseHooverIntegrator, are ones that have been added since the last release.  Somehow it's finding old copies of the headers that don't include them.

**Comment by apallath** [comment]
I had the Conda version of OpenMM installed, and although I'd removed it before trying to compile OpenMM from source, I think I didn't do it properly.
I cleaned and reinstalled anaconda, and used swig 3.0.12 instead of 4.0.1. `make PythonInstall` worked this time.
Thank you @peastman!!!

**Comment by peastman** [comment]
Glad that worked!
