### ISSUE TITLE
Python wrappers fail to build on macOS Mojave

### ISSUE THREAD

**Issue by apallath** [openmm/openmm#2643]
`make PythonInstall` or `python setup.py build` produces this output on macOS Mojave (I didn't encounter this error on Catalina):

![Screen Shot 2020-04-13 at 6 43 31 PM](https://user-images.githubusercontent.com/16438875/79168457-f4eecf80-7db7-11ea-9c39-6f7941e71d0f.jpg)

**Comment by peastman** [comment]
I don't think it's anything to do with the OS version.  I've never seen that error before.  Can you provide details on exactly how you're building?  Are you doing everything exactly as described in the manual?

**Comment by apallath** [comment]
I'm following all the instructions in the manual. I'm compiling for CPU only (no CUDA or OpenCL). I'm installing to a directory in my home folder (not in /usr/local). I have SWIG 3.0.12, Doxygen 1.8.17 and Python 3.7.6.
