### ISSUE TITLE
running multiple GPU jobs on a single GPU

### ISSUE THREAD

**Issue by AlchemistYuan** [openmm/openmm#2646]
Hi All,

I would like to ask if OpenMM allows running multiple GPU jobs on a single GPU? I guess the answer is No but just want to make sure.

Thanks!

**Comment by peastman** [comment]
You can do it, though it isn't necessarily a good idea.  GPUs don't multitask as well as CPUs.  But it can make sense sometimes, for example if you're simulating a very small system where one simulation can't generate enough work to keep the GPU busy.

**Comment by SianXiaoCHN** [comment]
> 

Hi, I'm wondering how can I do it. I have GPU with memory 80 GB, but it seems my system only used less than 10 GB (use nvidia-smi and see it's mostly empty). It's interesting to see how I can run other simulations on the same GPU.

**Comment by jchodera** [comment]
@SianXiaoCHN : If you have an NVIDIA GPU that supports [Multi-Instance GPU partitioning](https://docs.nvidia.com/datacenter/tesla/mig-user-guide/), this might be a good option.

@peastman : Modern GPUs are getting much better at multitasking (especially with the [Hopper architecture](https://developer.nvidia.com/blog/nvidia-hopper-architecture-in-depth/)). I wonder if it's worthwhile revisiting this.

**Comment by peastman** [comment]
Just launch multiple simulations, each in its own script, all using the same GPU.  If you want to do something more complex, you can write a single script that uses `multiprocessing` to launch multiple processes, one for each simulation.

**Comment by SianXiaoCHN** [comment]
@jchodera @peastman Thanks a lot for the help! I would contact my HPC staff about this.
