### ISSUE TITLE
Loading xml file in Fortran

### ISSUE THREAD

**Issue by amrhamedp** [openmm/openmm#2647]
Hello, 
I need to deserialize a system (xml file) in fortran wrapper.
I am following the example helloargoninfortran in which i am calling:
call OpenMM_XmlSerializer_deserializeSystem(xmlsystem, system) but I don't know what how to initialize xmlsystem. 
I tried to initialize xmlsystem using the path of the file but it didn't work.

**Comment by peastman** [comment]
You should read the file into memory and pass in the content of it as a string.
