### ISSUE TITLE
Provide a method getCurrentStep() for all platform?

### ISSUE THREAD

**Issue by z-gong** [openmm/openmm#2655]
When restarting from a checkpoint, it's useful to know which step it is at so that trajectories can be appended at the correct step, which is necessary for analyzing time correlation properties.

Cuda and OpenCL platform record the current step in the checkpoint file. The CudaContext and OpenCLContext have a getStepCount() method, but it's not exposed in python wrapper. For Reference and CPU platform, there's no such method, and the step is not saved in the checkpoint.

Do you think it's reasonable to provide such a method for all platforms, and also save step information in the checkpoint for Reference platform?

**Comment by z-gong** [comment]
Just realized that there's a method State.getTime(). So getCurrentStep doesn't seem necessary.
But It would be useful to save step and time information in checkpoint for Reference and CPU platform.

**Comment by peastman** [comment]
Simulation also has a `currentStep` field you can access.
