### ISSUE TITLE
Ligand-Protein Molecular Dynamic Simulation

### ISSUE THREAD

**Issue by tom13amy** [openmm/openmm#2659]
Can OpenMM do ligand-protein molecular dynamic simulation? I've tried to use OpenMM to do this, but encountered the "No template found for residue" error. I guess there is no definition for OpenMM to calculate the forcefield for the ligand. Hope someone could help me. Thanks!

**Comment by peastman** [comment]
The built in force fields only include standard molecules, so you need to use some tool to parametrize the ligand.  AmberTools is a popular option for that.  It supports the GAFF force field.  It will save the resulting system to a prmtop file, which you can load with OpenMM.  Another option is to use GHARMM.  It can model ligands with the CGenFF force field, and again will save to files that you can read with OpenMM.

**Comment by tom13amy** [comment]
> The built in force fields only include standard molecules, so you need to use some tool to parametrize the ligand. AmberTools is a popular option for that. It supports the GAFF force field. It will save the resulting system to a prmtop file, which you can load with OpenMM. Another option is to use GHARMM. It can model ligands with the CGenFF force field, and again will save to files that you can read with OpenMM.

Thank you very much! This will help me a lot!
