### ISSUE TITLE
Energy derivatives

### ISSUE THREAD

**Issue by adw62** [openmm/openmm#2663]
Hi,

I'm interested in calculating derivatives for the potential energy with respect to some alchemical parameters for thermodynamic integration.  

For the Lennard-Jones potential I can write a new Lennard-Jones potential as a   `CustomNonbondedForce` scale this by an alchemical  parameter which I add with `addGlobalParameter` and `addEnergyParameterDerivative` and then using `getEnergyParameterDerivatives` on the `context` gives the derivative.

Apologies if this is a naive question but is it possible to do the same for PME electrostatics? If it is possible would there be a large performance penalty to using a ` CustomNonbondedForce` for PME  electrostatics? 

Thanks,
Alex

**Comment by peastman** [comment]
Unfortunately no.  In principle this could be added (NonbondedForce does let you define global parameters that alter the parameters of individual atoms), though I'm not sure how difficult it would be to track all the needed derivatives through PME.

**Comment by adw62** [comment]
Thanks for the quick reply. For my own interest is there an easy way to explain this? No worries if not.

For the idea of modifying individual atoms in the `NonbondedForce`. I think the best option to do this is to use `ParticleParameterOffset`? I don't think I can use  `ParticleParameterOffset` with `getEnergyParameterDerivatives` so would I be need a numerical finite difference here?

**Comment by peastman** [comment]
Parameter offsets are the most efficient way of modifying particle parameters.  Currently NonbondedForce doesn't have a `addEnergyParameterDerivative()` function, but it might be possible to implement one.

Using a finite difference approximation is certainly an option.  It will be slower and less accurate than an analytical implementation, but it might still be fine for your purposes.  The code would look something like

```python
context.setParameter('lambda', curentLambda+delta)
e1 = context.getState(getEnergy=True).getPotentialEnergy()
context.setParameter('lambda', curentLambda-delta)
e2 = context.getState(getEnergy=True).getPotentialEnergy()
dEdLambda = (e1-e2)/(2*delta)
context.setParameter('lambda', curentLambda) # restore lambda to its original value!
````

**Comment by jchodera** [comment]
If you define the PME electrostatics energy for a set of ligand charges `S` as `U(x;\lambda) = \lambda \sum_{i \in S} q_i \phi(x_i)`, where `\phi(x)` is the electrostatic potential, then you could compute `dU/d\lambda = \sum_{i \in S} q_i \phi(x_i)` and add another `NonbondedForce` to a new force group (that normally isn't used in dynamics) where the charges in set `S` are set to zero. The difference between the force group 1 electrostatics and force group 2 electrostatics would then give you the derivative `dU/d\lambda`.

**Comment by peastman** [comment]
Doesn't that assume that when lambda is 0, all variable charges are exactly zero?  Often charges change between two different nonzero values.  Also you assumed that phi is independent of lambda, which won't be true if more than one particle is changing.

**Comment by jchodera** [comment]
Yes, both of those are correct!

Finite difference is likely better than turning all charges off, and if you're doing that already, BAR is even better than TI.

**Comment by adw62** [comment]
My aim is to try and reproduce the dual topology thermodynamic integration of NAMD such that we can use GPUs for the molecular dynamics, so I can't switch to BAR unfortunately. This also means I have more than one particle changing, so I don't think I can use the difference in electrostatics between force groups here. 

Reading some more it seems the problem is that PME is not pairwise decomposable so I can't just scale by lambda. Which might be why NAMD TI does not work with GPUs to start with.

Thank you both for the suggestions. I will first try using the finite difference and hope that the accuracy is sufficient.

Best,
Alex

**Comment by peastman** [comment]
If you aren't already, I recommend using mixed precision mode.  It will give you more digits of precision in the energies at fairly low cost, and that will be very important for finite differences.
