### ISSUE TITLE
Freeze atoms position

### ISSUE THREAD

**Issue by moradza** [openmm/openmm#2665]
I am trying to fix and freeze the position of a group of atoms during nvt simulation, similar to freeze command in gromacs or lammps. does openmm has such functionality?

PS: I am new to the OpenMM, I was wondering if it has a user mail list.

Thanks,
Alireza

**Comment by Lnaden** [comment]
Are you trying to periodically freeze and unfreeze them during a simulation, or are you trying to hold these particular atoms at a fixed position for the duration of the simulation?

**Comment by moradza** [comment]
I fix them all the time during the simulation. And, they should not be part of the temperature calculation group. I have a confined slit with water inside and carbon sheet, I want to keep the water temperature at 300 and freeze the carbon sheet during the simulation.

**Comment by Lnaden** [comment]
Could you just set all their masses to zero? They would not have any force exerted on them but would still exert potential energy on all the other particles.

**Comment by moradza** [comment]
I will try it and let you if it works, thanks.

**Comment by peastman** [comment]
Setting mass to 0 is indeed the recommended way of freezing an atom.  They won't count toward the number of degrees of freedom for estimating temperature, so that will still be correct.

**Comment by peastman** [comment]
Can this issue be closed?

**Comment by dspoel** [comment]
It also works when doing minimizations, by the way.

**Comment by smiles724** [comment]
> Could you just set all their masses to zero? They would not have any force exerted on them but would still exert potential energy on all the other particles.

Thanks for your information! It helps.
