### ISSUE TITLE
Distinguish between OpenMMExceptions and ctrl-C in python interface

### ISSUE THREAD

**Issue by lvotapka** [openmm/openmm#2669]
Hi OpenMM Developers,
I tried to find an answer to this question online for a while with no luck, so sorry if you answered this elsewhere.

I'm using the OpenMM Python interface, and I'm trying to detect when there was a problem with the OpenMM simulation (NaN error for instance) vs. another type of error such as SystemExit. So for now, I'm stuck using code like the following:

```
try:
simulation.saveState(state_filename)
    simulation.step(step_chunk_size)
    current_step = current_step + step_chunk_size
except:
    print("Alert! NaN error detected. Restarting from saved state.")
    simulation.loadState(state_filename)
```

When it would be preferable to have:

```
try:
    simulation.saveState(state_filename)
    simulation.step(step_chunk_size)
    current_step = current_step + step_chunk_size
except OpenMMError:
    print("Alert! NaN error detected. Restarting from saved state.")
    simulation.loadState(state_filename)
```

Is there any way to distinguish between generic exceptions and OpenMM exceptions at this time?

**Comment by peastman** [comment]
In the C++ API, all exceptions thrown by OpenMM are instances of `OpenMMException`.  But it looks like the Python wrapper just turns them into generic exceptions.  I'll see if I can find a way to improve that.

**Comment by lvotapka** [comment]
Sounds good, thanks @peastman.
