### ISSUE TITLE
"Ghost" CustomNonBondedForce

### ISSUE THREAD

**Issue by Exarctus** [openmm/openmm#2679]
Hey,

I've been looking for a way to attach a custom non-bonded force to a set of atoms, without this force being added to the total force acting on those atoms. This force needs to be computed at every step during MD, and written to an output file.

Does anyone know if there's a clean way to do this? I was thinking this could be achieved with adding 3 per-particle parameters that get updated from the energy expression, but that doesn't seem like a clean way to go about it...

Many thanks for any help!

**Comment by craabreu** [comment]
Hi @Exarctus 
If you need to compute the energy resulting from this `CustomNonbondedForce`, a possible workaround could go like this:

```py
cvforce = openmm.CustomCVForce('0')
cvforce.addCollectiveVariable('my_energy', my_custom_nonbonded_force)
system.addForce(cvforce)
```

Then, you can extend the `StateDataReporter` class so that it becomes able to report the value of this collective variable:

```py
class MyStateDataReporter(openmm.app.StateDataReporter):
   def __init__(self, file, report_interval, cvforce, **kwargs):
        super().__init__(file, report_interval, **kwargs)
        self._cvforce = cvforce

    def _constructHeaders(self):
        return super()._constructHeaders() + ['my_energy']

    def _constructReportValues(self, simulation, state):
        my_energy = self._cvforce.getCollectiveVariableValues(simulation.context)[0]
        return super()._constructReportValues(simulation, state) + [my_energy]
```

A caveat of this approach is that `my_custom_nonbonded_force` will be internally evaluated at every time step, even if `report_interval > 1`. This can be very time-consuming. Alternatively, you could define a `CustomIntegrator` which ignores forces of a given force group, and then use `context.getState` from time to time to evaluate the energy of this force group.

**Comment by craabreu** [comment]
> I've been looking for a way to attach a custom non-bonded force to a set of atoms, without this force being added to the total force acting on those atoms.

If this is a small set of atoms, maybe a simpler solution would be to store their positions over time and just do post-processing.

**Comment by peastman** [comment]
This question has come up a few times before.  People want to have a Force they can compute, but don't want it to affect integration.  Using a CustomIntegrator has generally been the best suggestion.  Perhaps we should add this as a feature to all the standard integrators as well?  There could be a method `setIntegrationForceGroups()` to tell it which groups should be evaluated when performing integration.

**Comment by craabreu** [comment]
> There could be a method setIntegrationForceGroups() to tell it which groups should be evaluated when performing integration.

I strongly support this type of new feature. Another possibility would be a simple active/inactive tag for each `Force`, with corresponding setter/getter methods.

**Comment by Exarctus** [comment]
> Hi @Exarctus
> If you need to compute the energy resulting from this `CustomNonbondedForce`, a possible workaround could go like this:
> 
> ```python
> cvforce = openmm.CustomCVForce('0')
> cvforce.addCollectiveVariable('my_energy', my_custom_nonbonded_force)
> system.addForce(cvforce)
> ```
> 
> Then, you can extend the `StateDataReporter` class so that it becomes able to report the value of this collective variable:
> 
> ```python
> class MyStateDataReporter(openmm.app.StateDataReporter):
>    def __init__(self, file, report_interval, cvforce, **kwargs):
>         super().__init__(file, report_interval, **kwargs)
>         self._cvforce = cvforce
> 
>     def _constructHeaders(self):
>         return super()._constructHeaders() + ['my_energy']
> 
>     def _constructReportValues(self, simulation, state):
>         my_energy = self._cvforce.getCollectiveVariableValues(simulation.context)[0]
>         return super()._constructReportValues(simulation, state) + [my_energy]
> ```
> 
> A caveat of this approach is that `my_custom_nonbonded_force` will be internally evaluated at every time step, even if `report_interval > 1`. This can be very time-consuming. Alternatively, you could define a `CustomIntegrator` which ignores forces of a given force group, and then use `context.getState` from time to time to evaluate the energy of this force group.

Many thanks for the code sample! If I do it this way, will the forces be evaluated also? These are the key objects that I need, the energy isn't super useful here.

> > I've been looking for a way to attach a custom non-bonded force to a set of atoms, without this force being added to the total force acting on those atoms.
> 
> If this is a small set of atoms, maybe a simpler solution would be to store their positions over time and just do post-processing.

These forces will be alchemical in nature, I suppose I could post-process every trajectory I generate in this way but I think it'd be cleaner/less hassle to do it on the fly.

**Comment by craabreu** [comment]
> If I do it this way, will the forces be evaluated also? 

The collective variables in a `CustomCVForce` are evaluated in a separate context, which you can access via `getInnerContext`. This is described [here](http://docs.openmm.org/latest/api-python/generated/simtk.openmm.openmm.CustomCVForce.html#simtk.openmm.openmm.CustomCVForce.getInnerContext).

**Comment by Exarctus** [comment]
Thanks @craabreu for all the help!
