### ISSUE TITLE
How can I efficiently calculate pairwise amino acid non-bonded interaction energies from MD simulation trajectories generated by OpenMM?

### ISSUE THREAD

**Issue by Bio-Otto** [openmm/openmm#2682]
I would like to calculate pairwise non-bonded interaction energies between amino acid residues in a protein over the length of MD simulation trajectories produced by the OpenMM 7.4 using the Amber96 force-field.

**Comment by peastman** [comment]
Could you give more detail about what you want to do?  Are you asking for the total energy, or the energy of particular pairs of residues, or of particular pairs of atoms?  Do you want to record them while the simulation is running, or later when analyzing a trajectory?  Do you want Coulomb, Lennard-Jones, or both?  What nonbonded method are you using?  The more detail you can give about exactly what you want the better.

**Comment by Bio-Otto** [comment]
I would like to calculate pairwise non-bonded interaction energies between amino acid residues in a protein over the length of MD simulation trajectories. Currently I use the namdenergy.tcl script for this purpose. And I want to record them while the simulation is running or later when analyzing a trajectory.

Thank you very much for your precious time and quick return.

**Comment by peastman** [comment]
Please see my questions above.  I'm not sure what you mean by "pairwise non-bonded interaction energies between amino acid residues".  That could mean a lot of different things.  Please provide as much detail as you can about exactly what you want to calculate.

**Comment by Bio-Otto** [comment]
I am interested in investigating the changes in the whole complex, therefore I need to calculate the interaction energies for all possible logical combinations of **residue pairs**. 

There may also be calculations in terms of total energy (Lennard-Jones + Coulomb). However, calculation is very important for each residue.

I want to automate the steps necessary to extract residue-residue interaction energies from user-supplied simulation trajectories or as real time while the simulation is running. I have added a sample output image below. 

This is what I mean by "pairwise non-bonded interaction energies between amino acid residues".

![image](https://user-images.githubusercontent.com/57147948/82166258-9211bc00-98c0-11ea-93ff-a3a8b0d78019.png)

**Comment by Bio-Otto** [comment]
I am interested in investigating the changes in the whole complex, therefore I need to calculate the interaction energies for all possible logical combinations of *residue pairs*. For this purpose I used nonbonded method as you see in my script below.

`from simtk.openmm.app import *
from simtk.openmm import *
from simtk.unit import *
from sys import stdout
from simtk.openmm.app.data import *

print('Loading...')
pdb = PDBFile('C:/Users/HIbrahim/Desktop/OpenMM_PerTool/examples/protein.pdb')
modeller = Modeller(pdb.topology, pdb.positions)

forcefield = ForceField('amber99sb.xml', 'tip3p.xml')
modeller.addHydrogens(forcefield)
print('Adding solvent...')
modeller.addSolvent(forcefield, model='tip3p', padding=10*angstrom)

system = forcefield.createSystem(modeller.topology, nonbondedMethod=PME,
                                 nonbondedCutoff=1.0*nanometers, constraints=None, rigidWater=False,  removeCMMotion=True)

integrator = VerletIntegrator(2.0 * femtoseconds)
platform = Platform.getPlatformByName('OpenCL')
properties = {'OpenCLPrecision': 'mixed'}

simulation = Simulation(modeller.topology, system, integrator, platform, properties)
simulation.context.setPositions(modeller.positions)

print('Minimizing...')
simulation.minimizeEnergy(maxIterations=500)

simulation.context.setVelocitiesToTemperature(310.0 * kelvin)
print('Starting')
simulation.reporters.append(DCDReporter('output.dcd', 100))

simulation.reporters.append(StateDataReporter(stdout, 100, step=True,
                                              time=True, potentialEnergy=True, kineticEnergy=True, totalEnergy=True,
                                              temperature=True, progress=True,
                                              remainingTime=True, speed=True, totalSteps=1000))

print('Running Production...')
simulation.step(1000)
print('Done')`

As far as I know, openmm calculates the potential energy of the system each frame in trajectory, but what I want is how much of each residual share in all potential energy?

There may also be calculations in terms of total energy (Lennard-Jones + Coulomb). However, calculation is very important for each residue.

I want to automate the steps necessary to extract residue-residue interaction energies from user-supplied simulation trajectories or as real time while the simulation is running. I have added a sample output image below. 

This is what I mean by "pairwise non-bonded interaction energies between amino acid residues".

**Comment by Bio-Otto** [comment]
This is actually what I want to do. https://github.com/openmm/openmm/issues/1830#issue-233880476

**Comment by peastman** [comment]
Does the solution suggested there work for you?  There's no interface for querying the energy between two arbitrary residues (to the extent that's well defined).  You could of course create a new system with only those two residues and nothing else in it, then compute the energy of that system.  That will be very slow though, especially if you want to loop over all possible residue pairs.

Also remember that you'll be leaving out all energy contributions related to solvent (e.g. hydrophobic attraction/repulsion).

**Comment by Bio-Otto** [comment]
Thank you for your answers. As you mentioned here (https://github.com/openmm/openmm/issues/1830#issuecomment-306548705), you said you can just compute q1*q2/r and leave it at that. Please give me an example of the procedure.

**Comment by peastman** [comment]
Just query the positions:

```python
state = simulation.context.getState(getPositions=True)
positions = state.getPositions(asNumpy=True).value_in_unit(nanometer)
```

Now you can directly calculate whatever distances you want.

**Comment by ahaldane** [comment]
I think the request here is for something similar to what is done by the ["gRINN" program](https://grinn.readthedocs.io/en/latest/index.html) for gromacs/namd.

It evaluates the force-field's nonbonded potential between all residues in each frame, as in [this figure](https://grinn.readthedocs.io/en/latest/tutorial.html#interaction-energy-matrix), and separates the LJ from electrostatic potential. I was just wondering whether openMM could do it more flexibly, eg so you could loop over residues and do something like `[system.evalVDW(groupA, groupB) for groupA, groupB in res_pairs]`.

Yes,  the force-field-potential is a limited measure of residue interaction since it ignores entropies, solvent dipole reaction, needs a reference energy, etc, but it can still give some qualitative sense of the nature of some of the interactions.

(PS: For me this calculation is not a priority. I found this issue out of curiosity about how hard it was to do and just wanted to add some info/links while I was looking.)

**Comment by Bio-Otto** [comment]
@ahaldane This is exactly what i want to do. Also the program ( gRINN) you mentioned above was developed by our lab. But with openmm, we want to add a feature that can do this without requiring an external program. Thank you for your support.

**Comment by Bio-Otto** [comment]
Dear Prof @peastman, 
please can you tell me how can i make it faster. 


`
import simtk.openmm.app
from simtk.openmm import *
from simtk.unit import *

from sys import stdout
import parmed as pmd
import numpy as np
import time

VELUNIT = angstrom / picosecond
RESIDUE_NAME = str


class Per_Residue_Energy_Decomposition():
    """
    This is the base class of OpenMM_MMGBSA.

    Parameters
    ----------
        system : list(openmm.Force)
            A list of OpenMM system objects.
    """

    def __init__(self, simulation, system, by_pass_bonds_index, by_pass_atoms):
        self.forces = {system.getForce(index).__class__.__name__: system.getForce(
            index) for index in range(system.getNumForces())}

        self.by_pass_bonds_index = by_pass_bonds_index
        self.simulation = simulation
        self.by_pass_atoms = by_pass_atoms

    def NonBondedForce_Decomposition(self):
        Nonbonded_F = self.forces['NonbondedForce']

        by_pass_atoms_index = []
        for i in range(len(self.by_pass_atoms)):
            by_pass_atoms_index.append(self.by_pass_atoms[i].index)

        for index in range(Nonbonded_F.getNumParticles()):
            charge, sigma, epsilon = Nonbonded_F.getParticleParameters(index)
            exclude = (index in by_pass_atoms_index)
            Nonbonded_F.setParticleParameters(index, 0 * charge if exclude else charge, sigma,
                                              0 * epsilon if exclude else epsilon)

        for index in range(Nonbonded_F.getNumExceptions()):
            [particle1, particle2, chargeProd, sigma, epsilon] = Nonbonded_F.getExceptionParameters(index)
            Nonbonded_F.setExceptionParameters(index, particle1, particle2, 0 * chargeProd if exclude else chargeProd,
                                               sigma, 0 * epsilon if exclude else epsilon)

        Nonbonded_F.updateParametersInContext(self.simulation.context)

    def HarmonicBondForce_Decomposition(self):
        Harmonic_BF = self.forces['HarmonicBondForce']

        for i in range(Harmonic_BF.getNumBonds()):
            p1, p2, length, k = Harmonic_BF.getBondParameters(i)
            exclude = (p1 in self.by_pass_bonds_index or p2 in self.by_pass_bonds_index)
            Harmonic_BF.setBondParameters(i, p1, p2, length, 0 if exclude else k)

        Harmonic_BF.updateParametersInContext(self.simulation.context)

    def HarmonicAngleForce_Decomposition(self):
        Harmonic_AF = self.forces['HarmonicAngleForce']

        for i in range(Harmonic_AF.getNumAngles()):
            p1, p2, p3, angle, k = Harmonic_AF.getAngleParameters(i)
            exclude = (
                    p1 in self.by_pass_bonds_index or p2 in self.by_pass_bonds_index or p3 in self.by_pass_bonds_index)
            Harmonic_AF.setAngleParameters(i, p1, p2, p3, angle, 0 if exclude else k)
        Harmonic_AF.updateParametersInContext(self.simulation.context)

    def PeriodicTorsionForce_Decomposition(self):
        Periodic_TF = self.forces['PeriodicTorsionForce']

        for i in range(Periodic_TF.getNumTorsions()):
            p1, p2, p3, p4, periodicity, phase, k = Periodic_TF.getTorsionParameters(i)
            exclude = (
                    p1 in self.by_pass_bonds_index or p2 in self.by_pass_bonds_index or p3 in self.by_pass_bonds_index or p4 in self.by_pass_bonds_index)
            Periodic_TF.setTorsionParameters(i, p1, p2, p3, p4, periodicity, phase, 0 if exclude else k)
        Periodic_TF.updateParametersInContext(self.simulation.context)


def get_residue_atoms(index, modeller):
    residues = [r for r in modeller.topology.residues()]  # build a list of residues
    indicated_res_atoms = residues[index].atoms()
    RESIDUE_NAME = residues[index].name
    return list(indicated_res_atoms), RESIDUE_NAME


def run_mmgbsa(pdb, res_indices_list):
    start_time = time.time()

    print('Loading...')
    pdb = simtk.openmm.app.PDBFile(pdb)
    modeller = simtk.openmm.app.Modeller(pdb.topology, pdb.positions)

    # all_residues = [r for r in modeller.topology.residues()]

    for res_num in res_indices_list:
        calculate_atoms, selected_res_name = get_residue_atoms(res_num, modeller)
        by_pass_atoms = []

        for k, i in enumerate(modeller.topology.atoms()):
            if i not in calculate_atoms:
                by_pass_atoms.append(i)

        bonds = [b for b in modeller.topology.bonds()]
        by_pass_bonds_index = list()

        for i in calculate_atoms:
            for j in bonds:
                if i.residue != j[0].residue:
                    by_pass_bonds_index.append(j[0].index)

        forcefield = simtk.openmm.app.ForceField('amber96.xml', 'spce.xml')

        system = forcefield.createSystem(modeller.topology, nonbondedMethod=app.NoCutoff,
                                         constraints=app.HBonds, rigidWater=True)

        platform = Platform.getPlatformByName('OpenCL')
        properties = {'OpenCLPrecision': 'mixed'}
        # platform = Platform.getPlatformByName('CUDA')
        # properties = {'CudaPrecision': 'mixed'}

        integrator = VerletIntegrator(2.0 * femtoseconds)
        simulation = simtk.openmm.app.Simulation(modeller.topology, system, integrator, platform, properties)
        simulation.context.setPositions(modeller.positions)

        Decomposition = Per_Residue_Energy_Decomposition(simulation, system, by_pass_bonds_index, by_pass_atoms)

        Decomposition.HarmonicBondForce_Decomposition()

        Decomposition.HarmonicAngleForce_Decomposition()

        Decomposition.NonBondedForce_Decomposition()

        Decomposition.PeriodicTorsionForce_Decomposition()

        structure = pmd.load_file('pdbid_fixed_ph7_apo.pdb')

        All_Energies = pmd.openmm.energy_decomposition_system(structure, system, nrg=kilojoules_per_mole)

        print("\n###################################################\n")
        print("RES_NUM: %s" % res_num)
        TOTAL_ENERGY = 0.0
        for i in range(0, len(All_Energies)):
            TOTAL_ENERGY += All_Energies[i][1]

            print(All_Energies[i][0], All_Energies[i][1])
        print('Total energy of %s Residue: %6.6f kilojoules_per_mole' % (selected_res_name, TOTAL_ENERGY))

        print("\n--- %s seconds ---" % (time.time() - start_time))
        print("###################################################")


if __name__ == '__main__':

    zaman_basla = time.time()

    run_mmgbsa('pdbid_fixed_ph7_apo.pdb', [0, 25])
    zaman_bitis = time.time()
    print("Toplamda %s saniye sürdü" % (zaman_bitis - zaman_basla))
`

**Comment by peastman** [comment]
I see one change that should help a lot: you're reloading all the files every time through the loop.  Move the lines

```python
        forcefield = simtk.openmm.app.ForceField('amber96.xml', 'spce.xml')
```

and

```python
        structure = pmd.load_file('pdbid_fixed_ph7_apo.pdb')
```

up to the top of the function.  That should speed things up a lot.  There also are other things that are unnecessarily being repeated each time, like most of `get_residue_atoms()`, but those may not be significant.  If it's still too slow, try running it through cProfile and see where most of the time is being spent.
