### ISSUE TITLE
problem pulling from omnia-dev

### ISSUE THREAD

**Issue by tdudgeon** [openmm/openmm#2683]
Something seems different in the conda packages in `omnia-dev`.

If I do:
```
conda install -c omnia/label/cuda101 openmm
```
All goes fine. But when I try:
```
conda install -c omnia-dev/label/cuda101 openmm
```
I get this error:
```
UnsatisfiableError: The following specifications were found to be incompatible with your CUDA driver:

  - feature:/linux-64::__cuda==10.2=0

Your installed CUDA driver is: 10.2
```

My CUDA is 10.1:
```
$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
```
though the driver claims it is at 10.2:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.64       Driver Version: 440.64       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1050    Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   48C    P3    N/A /  N/A |   1966MiB /  4042MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1053      G   /usr/lib/xorg/Xorg                           133MiB |
|    0      1608      G   /usr/lib/xorg/Xorg                           577MiB |
|    0      1848      G   /usr/bin/gnome-shell                         286MiB |
|    0      2596      G   gnome-control-center                           1MiB |
|    0      2760      G   ...AAAAAAAAAAAACAAAAAAAAAA= --shared-files   883MiB |
|    0      3680      G   ...quest-channel-token=7454732507031190068    68MiB |
+-----------------------------------------------------------------------------+
```
(see here for an explanation of that discrepancy https://stackoverflow.com/questions/53422407/different-cuda-versions-shown-by-nvcc-and-nvidia-smi).

Any ideas why the packages on `omnia-dev` are behaving badly?

**Comment by jchodera** [comment]
@jaimergp and @lnaden recently upgraded the build infrastructure https://github.com/omnia-md/conda-dev-recipes to test a build system that closely mirrors the conda-forge infrastructure. Tagging them in here, since I think they're the only ones able to figure out what is going on there.

If you want a version of OpenMM with all the recent bugfixes that also supports the openforcefields force field via https://github.com/openmm/openmmforcefields, give the OpenMM 7.4.2 release candidate a try:
```bash
conda install -c omnia/lable/rccudaXY openmm=7.4.2
```

**Comment by jaimergp** [comment]
The `omnia-dev` packages use `cudatoolkit`, which constrains with `__cuda`. This has always been the case, so I don't know why is causing trouble now...

More information on those virtual packages [here](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-virtual.html#overriding-detected-packages). Check the environment variables to debug it.

Other related issues:

* https://github.com/conda/conda/issues/9115
* https://github.com/conda/conda/issues/9897

**Comment by tdudgeon** [comment]
Unfortunately that didn't help.
I set:
```
export CONDA_OVERRIDE_CUDA=10.1
```

But install still failed with:
```
UnsatisfiableError: The following specifications were found to be incompatible with your CUDA driver:

  - feature:/linux-64::__cuda==10.1=0

Your installed CUDA driver is: 10.1
```
Strange!

**Comment by jaimergp** [comment]
I'll try to reproduce your errors and see what I find. For now, reading through those conda issues, it might be a `conda` thing itself. Have you updated recently? Maybe a slightly older version will work? Sorry for just dropping some open questions... :) I will also try!

**Comment by jaimergp** [comment]
@tdudgeon Is `conda-forge` on your channel list? You might want to try with:

```
conda install -c conda-forge -c omnia-dev/label/cuda101 openmm
```
