### ISSUE TITLE
Simple example of using SystemBuilder to simulate protein-ligand complex

### ISSUE THREAD

**Issue by tdudgeon** [openmm/openmm#2688]
I've been struggling to create a simple simulation of a protein-ligand complex.
Seems like there might be multiple ways of doing this with different combinations of extra toolkits (openmmforcefields, parmed, ...) and I found little snippets of how to do this but couldn't pull anything together that worked.

I created a simple example here:
https://github.com/tdudgeon/simple-simulate-complex

If someone could point out how to do this I'd be happy to further document this.

Really I think this should be included in the OpenMM user guide?
http://docs.openmm.org/latest/userguide/index.html

**Comment by Exarctus** [comment]
So it looks like to me you're trying to use a non-standard residue without providing template information. With openmmforcefields, you could try their GAFFTemplateGenerator example to first generate the template information for the ligand:

`from openforcefield.topology import Molecule
from openmmforcefields.generators import GAFFTemplateGenerator
from simtk.openmm.app import ForceField

molecule = Molecule.from_file('ligand.pdb')
gaff = GAFFTemplateGenerator(molecules=molecule)
forcefield = ForceField('amber/protein.ff14SB.xml', 'amber/tip3p_standard.xml')
forcefield.registerTemplateGenerator(gaff.generator)`

and after registering this template generator to your forcefield, the following should work:

`pdbfile = PDBFile('complex.pdb')
system = forcefield.createSystem(pdbfile.topology)`

**Comment by tdudgeon** [comment]
I'll give that a try, but I think my main point still stands.
SystemBuilder is supposed to hide the templating (as described here: https://github.com/openmm/openmmforcefields#automating-force-field-management-with-systemgenerator).
I think my example follows that approach, but clearly not in the right way.

**Comment by jchodera** [comment]
Apologies for the difficulties here! This is still a somewhat experimental feature, which is why we haven't yet added it to the official OpenMM docs, but hope to in time for OpenMM 7.5.0.

Thanks so much for putting together the example at 
https://github.com/tdudgeon/simple-simulate-complex

I'm working through this right now, and will contribute a PR.

**Comment by jchodera** [comment]
@tdudgeon : It looks like the root issue is [this line](https://github.com/tdudgeon/simple-simulate-complex/blob/master/simulateComplex.py#L11), which loads the chemical definition of the molecule in an incorrect way that somehow allows it to sneak past error checking for the `openforcefield` toolkit:
```python
ligand_mol = Molecule(open('ligand1.mol', 'rb'), file_format='mol')
```
If you print `ligand_mol`, you'll see that it has no hydrogens:
```python
>>> from openforcefield.topology import Molecule
>>> ligand_mol = Molecule(open('ligand1.mol', 'rb'), file_format='mol')
>>> ligand_mol
Molecule with name 'CCOC(=O)c1ccccc1' and SMILES '[C][C]OC(=O)c1[c][c][c][c][c]1'
```
If, instead, you were to provide the `ligand1.mol` filename to `Molecule.from_file()`, it would have given you a sensible error:
```python
>>> ligand_mol = Molecule.from_file('ligand1.mol', file_format='mol')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/choderaj/miniconda/envs/perses/lib/python3.7/site-packages/openforcefield/topology/molecule.py", line 2991, in from_file
    allow_undefined_stereo=allow_undefined_stereo)
  File "/Users/choderaj/miniconda/envs/perses/lib/python3.7/site-packages/openforcefield/utils/toolkits.py", line 1546, in from_file
    for rdmol in Chem.SupplierFromFilename(file_path, removeHs=False, sanitize=False, strictParsing=True):
  File "/Users/choderaj/miniconda/envs/perses/lib/python3.7/site-packages/rdkit/Chem/__init__.py", line 73, in SupplierFromFilename
    raise ValueError("unrecognized extension: %s" % ext)
ValueError: unrecognized extension: mol
```
Your `ligand1.mol` file appears to actually be an SDF file, so the following works fine:
```python
>>> ligand_mol = Molecule.from_file('ligand1.mol', file_format='sdf')
>>> print(ligand_mol)
Molecule with name 'CCOC(=O)c1ccccc1' and SMILES '[H]c1c(c(c(c(c1[H])[H])C(=O)OC([H])([H])C([H])([H])[H])[H])[H]'
```
Alternatively, simply changing `file_format` to `sdf` in your original line also works:
```python
>>> ligand_mol = Molecule(open('ligand1.mol', 'rb'), file_format='sdf')
>>> ligand_mol
Molecule with name 'CCOC(=O)c1ccccc1' and SMILES '[H]c1c(c(c(c(c1[H])[H])C(=O)OC([H])([H])C([H])([H])[H])[H])[H]'
```
@j-wags @mattwthompson: Maybe we can improve our error-checking somehow to avoid this kind of error? You can likely come up with better ideas, but it seems like we should at the very least check to see if loaded molecules are missing hydrogens if we use the `Molecule.__init__` constructor from a file stream. There may also be a way to make sure we don't accidentally try to load a file through `__init__` with the wrong format, but I'm not quite sure how.

@tdudgeon : I noticed you also had a commented-out attempt where you tried to use ParmEd `+` to combine the systems. I seem to recall this may have issues with not writing out the `CONECT` records properly. You can instead access the topology and positions from the `Modeller` object you construct directly via `modeller.topology` and `modeller.positions`.

I've opened a PR to fix the error in the least invasive way.

**Comment by tdudgeon** [comment]
@jchodera Thanks for that analysis and the PR.
I got it working!
But there is still some clunkiness present. Take a look at the notes at the bottom of the 
[README](https://github.com/tdudgeon/simple-simulate-complex/blob/master/README.md)

**Comment by tdudgeon** [comment]
I got ambitious and tried to incorporate water into the simulation and hit problems.
This is described here: https://github.com/tdudgeon/simple-simulate-complex#simulatecomplexwithsolventpy-simulation-with-explicit-solvent

**Comment by jchodera** [comment]
Huge thanks for the very clear and accessible notes and test case to debug. I'll dig into this shortly!

**Comment by jchodera** [comment]
@tdudgeon : The issue was the [line that defines a fixed solvent box size](https://github.com/tdudgeon/simple-simulate-complex/blob/master/simulateComplexWithSolvent.py#L40):
```python
box_vectors = unit.Quantity(np.diag([70, 70, 70]), unit.angstrom)
```
If you enlarge it by 10A on each side, the simulation runs fine:
```python
box_vectors = unit.Quantity(np.diag([80, 80, 80]), unit.angstrom)
```

```
Starting simulation
#"Step","Potential Energy (kJ/mole)","Temperature (K)"
1000,-650469.4139285805,252.8124731778625
2000,-619420.4139285805,287.4232434156706
3000,-611196.6639285805,297.20667034951856
4000,-608192.4139285805,297.3482900407921
5000,-607544.1639285805,297.1608534588128
6000,-608487.4139285805,301.74436796974663
7000,-608768.9139285805,302.1717104054274
8000,-607676.4139285805,302.07739618565336
9000,-607818.4139285805,297.86202154070946
10000,-608433.9139285805,298.61350928715547
Done
```
Presumably, there was some sort of interaction between the protein and its image that ended up causing instabilities.

We usually set a _buffer_ size to make sure the distance from the protein to its image is at least twice the periodic cutoff, changing
```python
box_vectors = unit.Quantity(np.diag([80, 80, 80]), unit.angstrom)
modeller.topology.setPeriodicBoxVectors(box_vectors)

# Solvate
print('Adding solvent...')
modeller.addSolvent(system_generator.forcefield, model='tip3p')#, padding=5.0*unit.angstroms)
print('System has %d atoms' % modeller.topology.getNumAtoms())
```
to this
```python
# Solvate
print('Adding solvent...')
modeller.addSolvent(system_generator.forcefield, model='tip3p', padding=10.0*unit.angstroms)
print('System has %d atoms' % modeller.topology.getNumAtoms())
```
This also succeeds:
```
Starting simulation
#"Step","Potential Energy (kJ/mole)","Temperature (K)"
1000,-788373.4934380297,250.8911177791746
2000,-752031.9934380297,286.62286255461726
3000,-740963.7434380297,297.06810812392047
4000,-737276.9934380297,298.5850330653336
5000,-734855.7434380297,297.696532914219
6000,-736538.9934380297,300.6500363397974
...
```
```

**Comment by tdudgeon** [comment]
@jchodera I'm afraid it's not working for me.
I increased the box to 90A and its still blowing up during minimisation.
Could it be because I'm using OpenMM 7.4.1?

**Comment by jchodera** [comment]
Hm, that's odd. Are you running on a GPU? With CUDA or OpenCL?
I just tested on my laptop locally, but can try to replicate the hardware you're running on.

One obvious CPU -> GPU issue is that my CPU runs in `mixed` precision by default. 
On a GPU, you may need the extra precision (only used for the integrator) to get more accuracy:
```
from simtk.openmm import Platform
platform = Platform.getPlatformByName('CUDA') # or 'OpenCL'
platrom.setPropertyDefaultValue('Precision', 'mixed')

# then later, when creating the Context, specify the platform explicitly
from simtk.openmm import Context
context = Context(system, integrator, platform)
```

**Comment by tdudgeon** [comment]
I'm using GPU and CUDA.
But that suggestion didn't help.
I didn't do it in exactly the way you suggested but I think the effect is the same.
https://github.com/tdudgeon/simple-simulate-complex/commit/d0a6733dacc107ea35f4fc453bc46107a1d0443d

**Comment by jchodera** [comment]
That's so odd---your latest version runs fine on GTX 1080 Ti:
```
Minimising
Starting simulation
#"Step","Potential Energy (kJ/mole)","Temperature (K)"
1000,-1346681.3430479812,248.74689936811745
2000,-1281251.5705092503,284.53530123855114
3000,-1262775.550211926,296.0491469128247
4000,-1254252.4358516214,298.37139055782245
5000,-1254830.7468916876,301.1838318278298
6000,-1253010.3479534304,301.8590924915269
7000,-1253113.8590562167,300.2523761777469
8000,-1253978.0338109285,301.81069349495993
9000,-1252703.937386346,300.3935724404845
10000,-1254737.1307977596,302.53046199557343
Done
```
Can you send me the output of `nvidia-smi`, and let me know which CUDA Toolkit you have installed?

**Comment by tdudgeon** [comment]
It runs for me, but the system blows up.
Have you viewed the `minimised1.pdb` file and compared it to `complex1.pdb`?

Here's my output (with the noisy start bit removed):
```
Uses Periodic box: True
Default Periodic box: [Quantity(value=Vec3(x=10.0, y=0.0, z=0.0), unit=nanometer), Quantity(value=Vec3(x=0.0, y=10.0, z=0.0), unit=nanometer), Quantity(value=Vec3(x=0.0, y=0.0, z=10.0), unit=nanometer)]
Minimising
Starting simulation
#"Step","Potential Energy (kJ/mole)","Temperature (K)"
1000,-1347449.786667807,247.80139644403056
2000,-1284383.612528365,284.55610664437364
3000,-1264641.9177559242,294.13100463699215
4000,-1256701.1197716743,297.7444994202598
5000,-1255226.0122099873,300.4386181191114
6000,-1253348.9512492586,301.7886686028118
7000,-1253602.9202398472,300.1416441067959
8000,-1253489.0041978676,299.0720471408149
9000,-1255762.7251976877,301.40615334235423
10000,-1254892.8203491438,299.71393621574856
Done
```

Here's the relevant bit of the `nvidia-smi` output:

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.64       Driver Version: 440.64       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1050    Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   63C    P0    N/A /  N/A |   2986MiB /  4042MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
```

Note that the CUDA version installed is 10.1 even though nvidia-smi reports 10.2.
This is supposedly because nvidia-smi is reporting the version the driver supports, not the version of the toolkit that is installed. This is explained somewhat here: https://stackoverflow.com/questions/53422407/different-cuda-versions-shown-by-nvcc-and-nvidia-smi

**Comment by jchodera** [comment]
> It runs for me, but the system blows up.

I'm confused---the potential energies look just fine. Normally, "blowing up" means the energies quickly become "Nan" as the system becomes unstable.

The trajectory produced looks just fine too. Here's frame 10/10:
![image](https://user-images.githubusercontent.com/3656088/82587008-550e2980-9b4d-11ea-9837-ebfe09e6da02.png)
Can you clarify what you mean bu "blowing up"?

> Note that the CUDA version installed is 10.1 even though nvidia-smi reports 10.2. This is supposedly because nvidia-smi is reporting the version the driver supports, not the version of the toolkit that is installed. 

Indeed! OpenMM can use either the toolkit `nvcc` or the driver's compiler library. You can control which one is used by setting `CUDA_HOST_COMPILER` to `1` (use `nvcc` from toolkit) or `0` (use driver).

**Comment by tdudgeon** [comment]
For the complex (complex1.pdb) that is created before minimisation the protein is in the middle of the solvent box and the ligand is in the active site of the protein.
After minimisation (minimised1.pdb) the ligand has moved a long way from the protein and the protein is no longer in the middle of the box (as in your screenshot).

**Comment by peastman** [comment]
I think you're getting misled by the periodic boundary conditions.  See https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#periodic.  This is a very common source of confusion.

**Comment by jchodera** [comment]
We do not re-image the coordinates to be centered on the protein, and unless you ask `context.getState()` to image the molecules into a single box, it will appear that water molecules can drift outside the box. Otherwise, you could not compute properties like diffusion constants.

If you simply center and re-image the molecules as you wish, you'll find all should be well!

**Comment by tdudgeon** [comment]
@jchodera 

> If you simply center and re-image the molecules as you wish, you'll find all should be well!

Not sure how to do that?

**Comment by peastman** [comment]
See the FAQ entry I linked above.

**Comment by tdudgeon** [comment]
> See the FAQ entry I linked above.

I did (and I'd already seem that). But there's no code example of what's needed and it's not obvious from the API docs.

**Comment by tdudgeon** [comment]
So I finally manage to track this down. The simulation was OK, but the problem was in the way the results were being generated. When writing the minimised PDB file or using the `PDBReporter` for the trajectory it's necessary to specify to write all components as if they were in the same periodic box.

For instance the `enforcePeriodicBox=False` bit here:
```
PDBFile.writeFile(complex_pdb.topology, simulation.context.getState(getPositions=True, enforcePeriodicBox=False).getPositions(), file=outfile, keepIds=True)
```

The examples are updated: https://github.com/tdudgeon/simple-simulate-complex

Note that there are some aspects I still see as being a bit clunky that are listed there.

@peastman @jchodera Thanks for your help with this.

**Comment by jchodera** [comment]
@tdudgeon : Sorry about this! Suggestions for streamlined improvements are always welcomed!

Though it's no longer actively supported, [`mdtraj`](http://mdtraj.org/) is conda-installable and provides a simple way to image trajectories or single snapshots in an intelligent way using the [`image_molecules()`](http://mdtraj.org/1.9.3/api/generated/mdtraj.Trajectory.html#mdtraj.Trajectory.image_molecules) method. For a PDB file, this is as easy as
```python
import mdtraj as md
trajectory = md.load('unimaged.pdb')
trajectory.image_molecules(inplace=True)
trajectory.save('imaged.pdb')
```
The `Trajectory` object can also be created from an OpenMM set of objects:
```python
import mdtraj as md
mdtraj_topology = md.Topology.from_openmm(openmm_topology)
trajectory = md.Trajectory(state.getPositions(asNumpy=True)/unit.nanometers, mdtraj_topology)
```
MDTraj also provides more useful [OpenMM reporters](http://mdtraj.org/1.9.3/api/reporters.html).

We're hoping to eventually pick up some funding for OpenMM so that we can potentially help support more tools in the OpenMM ecosystem beyond the core library.

@peastman : Should we add an option to the `PDBReporter` to enforce periodic boundary conditions, or have this be the default?

> Note that there are some aspects I still see as being a bit clunky that are listed there.

@tdudgeon: If you have suggestions on how we could add helper objects or further refine the API without breaking backwards-compatibility to provide a more streamlined experience, we'd love to hear about them! I have a feeling that simply having more examples to copy-and-paste from (like yours!) will be incredibly helpful too.

**Comment by peastman** [comment]
> @peastman : Should we add an option to the PDBReporter to enforce periodic boundary conditions, or have this be the default?

It already does!

https://github.com/openmm/openmm/blob/bd333a1b1875f80215b84addd34c226cd4ccc1ab/wrappers/python/simtk/openmm/app/pdbreporter.py#L53-L57

DCDReporter also has that option.

**Comment by tdudgeon** [comment]
@peastman @jchodera Yes, that's the "fix" I used by changing the PDBReporter to not enforce the periodic box. Please tell me if that's not the right solution.

@jchodera I'll try to summarise  my findings/suggestions here tomorrow. Currently they are mostly  embedded in the code examples.

**Comment by jchodera** [comment]
Should we consider changing the default in the next major release? We seem to get this question a lot, and the computation of diffusion constants (where periodic imaging would be detrimental) seems like more of a minor use case.

**Comment by peastman** [comment]
The default is to enforce periodic boundary conditions if your system is periodic, or don't enforce them if it isn't.  What are you proposing changing it to?

**Comment by jchodera** [comment]
Oh! Wow, then I guess I'm not understanding why this wasn't auromatic for @tdudgeon.

**Comment by peastman** [comment]
I think the input file must have had coordinates in the range (-width/2, width/2), but OpenMM wrapped them to the range (0, width).  `image_molecules()` is a good fix for that situation.

**Comment by tdudgeon** [comment]
Here is a summary of my findings where I believe things could be improved

1. The ligand has to be read twice, once as SDF so that Amber can parameterise it, once as PDB so that if can be combined into the complex. It should be possible to read the molecule just once in any common format (e.g. molfile, SDF, PDB, MOL2, RDKit RWMol object ...).
2. When reading the ligand PDB a shed load of WARNING: duplicate atom warnings are issued. And again when reading the complex. Clearly these warnings are incorrect. The atoms are clearly not duplicates. See the [README](https://github.com/tdudgeon/simple-simulate-complex) for details.
3. Amber seems to issue this warning Warning: `In AmberToolsToolkitwrapper.compute_partial_charges_am1bcc: Molecule 'CCOC(=O)c1ccccc1' has more than one conformer, but this function will only generate charges for the first one. when reading the ligand`. Clearly it is wrong. There is only one conformer present. Probably nothing OpenMM can do about this.
4. Ability to write ligands to molfile or sdf formats would be useful
5. Does not appear to be possible to add hydrogens to ligands. Other toolkits need to be used to do this.

**Comment by jchodera** [comment]
@tdudgeon : Thanks so much! 

We do have fixes for many of these issues in the works already, but some of them are larger issues that arise from a lack of open community toolkits.

1. We're adding support for biopolymer force fields to the [`openforcefield` toolkit](http://github.com/openforcefield/openforcefield) right now, so you'll be able to do everything with that ligand you've loaded once. In the longer term, once we have a format that is capable of representing the entire system _along_ with chemical identities (PDB, for example, does not include bond order or formal charge information necessary for identifying the unique chemical species present), you won't even need to load separate protein and ligand.

2. We believe the duplicate atom warnings are correct---while the [PDB spec](http://www.wwpdb.org/documentation/file-format-content/format33/sect9.html#HETATM) does not strictly state that atom names should be unique, it references the nomenclature specification for the [Chemical Components Dictionary](http://www.wwpdb.org/data/ccd), which ensures all atoms receive unique names. Unique atom names are also important for multiple simulation packages, which require unique atom names to assign parameters correctly---we end up assigning unique atom names before conversion.

3. This warning reflects the fact that you would receive multiconformer charges if you used the OpenEye toolkit backend, but RDKit is not able to do this. We're likely moving to a new graph convolutional network based charging scheme soon, which will be conformer-independent, os that should fix this.

4. By `molfile`, do you mean [MDL molfile](https://en.wikipedia.org/wiki/Chemical_table_file#Molfile) or some other format? And when you say "write ligands to molfile or sdf formats"---we currently support reading/writing of `Molecule` objects via SDF---is there something else you mean by "write ligands"---such as write their parameters?

5. Our toolkit asks you to know exactly what molecule you mean---by having explicit protons already---before you begin, for two reasons: (1) we want to make sure you specify the exact protonation/tautomeric state, and (2) we are assigning parameters to a system that may have been set up with another package (including ions and solvent), and if the number of atoms changes by adding protons, things can get very messy.

However, it's absolutely the case that we'd like to streamline the use case here, so if we can come up with cleaner, easier examples of how to do this, it would be enormously valuable to many!

cc: @j-wags : This excellent feedback on improving the user experience with using `openmtools` and OpenMM to build protein-ligand systems will be helpful!

**Comment by tdudgeon** [comment]
@jchodera Thanks for those comments and sorry for the slow response.
Understood on points 1-3.

On point 4 yes I was meaning MDL molfile or sdfile. I'll try the `Molecule.to_file() method for writing as SDF. That's all I was wanting here.

On point 5 it's now clear why you require a fully prepared ligand. Probable using `Molecule.to_rdkit()` and then doing the dirty work in RDKit and then reading it back using `Molecule.from_rdkit()` is the way to go here?

One other strange thing I note is that you can't create a `Molecule` from a PDB file. I get this error:
```
No toolkits in registry can read file <_io.BufferedReader name='complex1.pdb'> (format PDB). Supported formats in the provided ToolkitRegistry are {'The RDKit': ['SDF', 'MOL', 'SMI'], 'AmberTools': []}
```
RDKit does have some support for PDB format and I'm assuming AmberTools would too?

**Comment by tdudgeon** [comment]
After quite a bit of experimentation I managed to process the ligand using RDKit by just reading it from a molfile (no need for a second .pdb file). Just for the record here are the details. An example is here: https://github.com/tdudgeon/simple-simulate-complex/blob/master/simulateComplex.py#L12-L30

The basic code involved is:

```
# read the ligand and add Hs
rdkitmol = Chem.MolFromMolFile('ligand.mol')
rdkitmolh = Chem.AddHs(rdkitmol, addCoords=True)
ligand = Molecule(rdkitmolh)

# read the protein
protein = PDBFile('protein.pdb')

# Use Modeller to combine the protein and ligand into a complex
modeller = Modeller(protein.topology, protein.positions)
modeller.add(ligand.to_topology().to_openmm(), ligand.conformers[0])
```

**Comment by jchodera** [comment]
> One other strange thing I note is that you can't create a Molecule from a PDB file. I get this error:
> `RDKit does have some support for PDB format and I'm assuming AmberTools would too?`

The reason for this is that PDB files do not contain sufficient information to uniquely reconstruct the chemical species (unless the other fields required by the PDB spec, such as [`HETNAM` and `FORMUL` are also specified](https://www.wwpdb.org/documentation/file-format-content/format33/sect4.html) though this is infrequently the case). You're right that toolkits like OpenEye and RDKit have heuristics that _attempt_ to perceive the missing chemical information (such as bond order and formal charge) from the geometry, but this process is _highly_ error prone and differs from package to package. There is simply no guarantee you'll end up with the species that you want.

If you do need to go through PDB fils and guess what molecule you actually want, the right way to do it is indeed to read it in RDKit or OpenEye and then take the molecule object that contains chemical information into the openforcefield toolkit. 

Many of our choices with the toolkit design were to try to make it hard to do the wrong thing by accident. We make some conscious choices that make it hard to bring in molecules where there is ambiguity about what exactly you want to do. While that leads to frustration sometimes---especially for batch processing, which we're trying to make friendlier---it eliminates the potential for the most egregious types of modeling errors.

> After quite a bit of experimentation I managed to process the ligand using RDKit by just reading it from a molfile (no need for a second .pdb file).

Using `Modeller` to combine the two OpenMM `Topology` objects is a great idea! I'll add an example of that to `openmmtools`! Thanks!

**Comment by CoryKornowicz** [comment]
> After quite a bit of experimentation I managed to process the ligand using RDKit by just reading it from a molfile (no need for a second .pdb file). Just for the record here are the details. An example is here: https://github.com/tdudgeon/simple-simulate-complex/blob/master/simulateComplex.py#L12-L30
> 
> The basic code involved is:
> 
> ```
> # read the ligand and add Hs
> rdkitmol = Chem.MolFromMolFile('ligand.mol')
> rdkitmolh = Chem.AddHs(rdkitmol, addCoords=True)
> ligand = Molecule(rdkitmolh)
> 
> # read the protein
> protein = PDBFile('protein.pdb')
> 
> # Use Modeller to combine the protein and ligand into a complex
> modeller = Modeller(protein.topology, protein.positions)
> modeller.add(ligand.to_topology().to_openmm(), ligand.conformers[0])
> ```

I was just wondering how to solve this problem myself, and I was thinking, how do you position the the ligand in the pocket of the protein or anywhere really. Or is this one of those scenarios where it is moved into place first ( how do I do that as well ) and then it is separated to be processed again?

**Comment by tdudgeon** [comment]
@CoryKornowicz Those scripts assume that the ligand is already in position.
You will need to use docking or some other approach to achieve this.
