### ISSUE TITLE
Robust method of determining library version number

### ISSUE THREAD

**Issue by jcwomack** [openmm/openmm#2691]
I am working on a C++ application (an electronic structure code) which calls OpenMM via the C++ API. Our application builds with CMake and uses a [CMake find module](https://cmake.org/cmake/help/latest/manual/cmake-developer.7.html#find-modules) to search for the OpenMM library and set relevant build variables.

I would like to be able to have CMake check the version of any OpenMM libraries found so the build can link to OpenMM only if it is above a particular version number. The only way I can find to do this is via OpenMM API calls (`Platform.getOpenMMVersion()` in Python or `Platform::getOpenMMVersion()` in C++).

Is there a version number that can be robustly extracted in text file distributed with the library? For other libraries we have typically been able to extract this information from header files using CMake commands (`file()`, `string()`).

Running a short Python script when CMake is run to get the version string would be possible, but is not necessarily robust as OpenMM could have been built without Python wrappers.

**Comment by peastman** [comment]
The version number is set in the top level CMakeLists.txt.  Everywhere else that it appears gets propagated from there:

https://github.com/openmm/openmm/blob/15d95f7ab2e8c33632a891118fee2c71b48397fc/CMakeLists.txt#L163-L165
