### ISSUE TITLE
OpenMM cant find "LangevinMiddleIntegrator"

### ISSUE THREAD

**Issue by cadalyjr** [openmm/openmm#2697]
I have recently installed OpenMM via conda and everything seems to be running correctly. Here is the output from my running the test script:

```
(openmm) clydedaly@Clydes-MacBook-Pro examples % python -m simtk.testInstallation
OpenMM Version: 7.4.1
Git Revision: 068f120206160d5151c9af0baf810384bba8d052
There are 3 Platforms available:
1 Reference - Successfully computed forces
2 CPU - Successfully computed forces
3 OpenCL - Successfully computed forces
Median difference in forces between platforms:
Reference vs. CPU: 6.29566e-06
Reference vs. OpenCL: 6.72489e-06
CPU vs. OpenCL: 8.92848e-07
All differences are within tolerance.
```

All good! Now, I went to run the examples noted in Chapter 2.3 of the [user guide](http://docs.openmm.org/latest/userguide/application.html). I cloned a forked copy of the OpenMM git repository to my computer and ran:

```
(openmm) clydedaly@Clydes-MacBook-Pro examples % python simulatePdb.py 
Traceback (most recent call last):
  File "simulatePdb.py", line 9, in <module>
    integrator = openmm.LangevinMiddleIntegrator(300*kelvin, 1/picosecond, 0.004*picoseconds)
AttributeError: module 'simtk.openmm.openmm' has no attribute 'LangevinMiddleIntegrator'
```

When I change the line in simulatePdb.py
```
integrator = openmm.LangevinMiddleIntegrator(300*kelvin, 1/picosecond, 0.004*picoseconds)
```
to 
```
integrator = openmm.LangevinIntegrator(300*kelvin, 1/picosecond, 0.004*picoseconds)
```

The code runs perfectly fine. Should the openmm.LangevinMiddleIntegrator() be accessible?

**Comment by peastman** [comment]
LangevinMiddleIntegrator was added since the last release.  It will be a new feature in OpenMM 7.5.  In the user guide page you linked to, you'll see the examples use LangevinIntegrator, not LangevinMiddleIntegrator.

**Comment by cadalyjr** [comment]
Thanks!

**Comment by peastman** [comment]
By the way, you should reduce the step size to 0.002*picoseconds.  LangevinMiddleIntegrator uses a different discretization of the Langevin equation that lets you take bigger time steps.  Starting in 7.5 it will be our recommended integrator for most simulations.  With LangevinIntegrator you need to take smaller steps to avoid having very large error.
