### ISSUE TITLE
Issue with Hydration Free Energies with OpenMM

### ISSUE THREAD

**Issue by Exarctus** [openmm/openmm#2703]
Hey guys,

I've been trying to use openmmtools' alchemy.py code to compute solvation free energies of an ethanol molecule in water. The main issue is that the dV/dl curves that alchemy.py is producing are significantly different from those in the literature, and the resulting free energies are incorrect. They're also not particularly smooth, either (see figure 1 on the github page).

I've created a repository with all of my code + a workflow of the issues I've encountered here:

https://github.com/Exarctus/OpenMMSolvation/tree/master/OpenMMSolvation

Some additional points/notes:

1) I think that adding lambda-dependent energy derivatives should be automatically included in alchemy.py when addGlobalParameter is called in the force creation function, makes codes a little cleaner since you'll typically be interested in dU/dl values - does this add significant overhead?

2) Since solvation free energies are one of the most common benchmarks with classical MD, would it be worth adding a simple tutorial to the openmm website? If I can get this code working I'd be happy to help.

**Comment by jchodera** [comment]
@Exarctus : Thanks so much for the super clear example! Could you post this issue in https://github.com/choderalab/openmmtools/issues, since the issue is with code there? We can get a few more eyeballs on it this way.

**Comment by Exarctus** [comment]
thanks @jchodera will do that now!
