### ISSUE TITLE
ARM builds are timing out on travis

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#2705]
OpenMM builds on ARM are [timing out on travis](https://travis-ci.org/github/openmm/openmm).

Any idea why [this step](https://travis-ci.org/github/openmm/openmm/jobs/692697328#L7108-L7113) would cause them to get stuck?

**Comment by peastman** [comment]
They'd been working fine, and then a little while ago they stopped.  I haven't investigated yet to figure out why.

**Comment by peastman** [comment]
Closing this since we plan to migrate away from travis anyway.
