### ISSUE TITLE
Out-of-bounds access in CpuBondForce

### ISSUE THREAD

**Issue by thtrummer** [openmm/openmm#2707]
[This line](https://github.com/openmm/openmm/blob/6b39ec7ec0285e1584531efa8d56fc571e0d0c9f/platforms/cpu/src/CpuBondForce.cpp#L44) creates an out-of-bounds exception when the vector is empty. This can be reproduced by running `TestCpuCheckpoints`.

**Comment by peastman** [comment]
I think we can change it to `bondAtoms.data()`.

**Comment by thtrummer** [comment]
Since `std::vector::data()` isn't guaranteed to return a `nullptr` when the vector is empty, would you object to something along the lines of: `this->bondAtoms = bondAtoms.empty() ? nullptr : bondAtoms.data();`

**Comment by peastman** [comment]
That would be fine, although I don't think it's necessary.  All accesses to `bondAtoms` are inside loops over bonds, so if `numBonds` is 0 it will never be accessed.

**Comment by thtrummer** [comment]
The idea is to be defensive against future changes.

**Comment by peastman** [comment]
Ok, sounds reasonable.

**Comment by thtrummer** [comment]
Fixed by #2714.
