### ISSUE TITLE
Support for Vulkan API

### ISSUE THREAD

**Issue by arehtykitna** [openmm/openmm#2710]
I understand there's core development work underway to support CUDA better but I have searched the forum and cannot find any reference to Vulkan API which can also be used for compute tasks, therefore possibly leveraged for expanding the list of F@H supported devices.

Specifically please look into this: "For example, the open source clspv compiler and clvk API translator enable OpenCL applications to be run over a Vulkan run-time. This gives OpenCL developers significant flexibility on where and how they can deploy their OpenCL applications." - https://www.khronos.org/opencl/

> "Initial specifications stated that Vulkan will work on hardware that currently supports OpenGL ES 3.1 or OpenGL 4.x and up.[175] As Vulkan support requires new graphics drivers, this does not necessarily imply that every existing device that supports OpenGL ES 3.1 or OpenGL 4.x will have Vulkan drivers available.
> 
> Vulkan 1.1 with higher efforts is supported by the newer lines in Hardware like Intel Skylake and higher, AMD GCN 3rd and higher, Nvidia Kepler and higher. AMD, Arm, Imagination Technologies, Intel, Nvidia and Qualcomm supports actual hardware since second half of 2018 Vulkan 1.1 with own drivers. Mesa 18.1 supports with RADV and ANVIL driver AMD and Intel hardware. Actual state in Mesa 3D of RADV and ANVIL see Mesamatrix.[176]
> 
> Android 7.0 Nougat supports Vulkan 1.0.[177] The software was released in August 2016.[178] Vulkan 1.1 is supported in Android 9.0 Pie.[179] Vulkan 1.1 support is mandatory for 64-bit devices running Android 10.[180]
> 
> Vulkan support for iOS and macOS has not been announced by Apple, but an open-source library exists which provides a Vulkan implementation that runs on top of Metal on iOS and macOS devices.[25]"

Source: https://en.wikipedia.org/wiki/Vulkan_(API)#Compatibility

Current release is Vulkan 1.2:
Full information and SDK - https://www.khronos.org/vulkan/

**Comment by peastman** [comment]
At present we have no plans to use Vulkan.  OpenCL is already available on all devices and platforms that support Vulkan, and also on some that don't (MacOS, iOS), so adding Vulkan wouldn't do anything to expand what we can run on.

**Comment by arehtykitna** [comment]
I opened this issue at the request of John Chodera, so feel free to discuss the merits further with him. As for platform support, do you already support ARM and Qualcomm then? If not this is the opportunity to do so easily. More and more computers are being made using ARM and Qualcomm chips now instead of Intel Atom.
https://foldingforum.org/viewtopic.php?f=16&t=35408&p=336032#p335993

**Comment by peastman** [comment]
Yes, we support ARM.  Also, using the Vulkan API has nothing to do with what CPU architecture it runs on.

**Comment by arehtykitna** [comment]
I'm not on about CPU architecture or folding either but thanks for the clarification that openmm already supports ARM.

**Comment by jchodera** [comment]
@arehtykitna Thanks for opening this issue! I think we're just trying to understand whether Vulkan support would expand the platforms that OpenMM is currently able to support with the CUDA and OpenCL platforms. From our conversations with various vendors, I don't think we've identified platforms that would benefit from this at the current time, but we're always looking to see what might be useful to support!

**Comment by arehtykitna** [comment]
Thanks for a sensible and respectful answer. If I find anything else in future that may be of use I will open an issue here rather than wasting time on the forum again

**Comment by jchodera** [comment]
Thanks so much, @arehtykitna. And no worries about "wasting time" either in the forum or here---we're always open to anything that might be useful for the OpenMM user community and to Folding@home, and these discussions are always illuminating!

**Comment by Daasin** [comment]
Were there not plans for convergence or even mergers between OpenCL + Vulkan Compute? 

Having it as an option atleast could yield some benefits for places it can be used surely? Could be picked automatically in an ideal config preset 🧐😕

**Comment by peastman** [comment]
> Were there not plans for convergence or even mergers between OpenCL + Vulkan Compute?

At one point there was talk about that, but they've now gone in an different direction.  OpenCL 3.0 made large parts of the spec optional, including support for SPIR-V, the IR used by Vulkan.
