### ISSUE TITLE
OpenCL tests for Drude and RPMD plugins don't support platform/device selection

### ISSUE THREAD

**Issue by thtrummer** [openmm/openmm#2718]
[This line](https://github.com/openmm/openmm/blob/945067fe1bfdb45e832575fd24a6aa5a9b77dce3/plugins/drude/platforms/opencl/tests/CMakeLists.txt#L20) should probably be something like this:

`ADD_TEST(${TEST_ROOT}Single ${EXECUTABLE_OUTPUT_PATH}/${TEST_ROOT} single ${OPENCL_TEST_PLATFORM_INDEX} ${OPENCL_TEST_DEVICE_INDEX})`

**Comment by peastman** [comment]
Agreed!
