### ISSUE TITLE
XmlSerializer is fragile to extra `\r` characters

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#2721]
Opening an XML file in a manner that adds extra `\r` characters causes the [XML serialization handler](https://github.com/openmm/openmm/blob/master/serialization/src/SerializationNode.cpp) to break with 
```
ERROR:exception: Unknown property 'type' in node ''
```
It would be useful if we could be resilient to this mode of failure just in case.

cc: https://github.com/FoldingAtHome/openmm-core/pull/254

**Comment by peastman** [comment]
Can you provide an example file that doesn't load correctly?

**Comment by jchodera** [comment]
Note I've also filed an issue in the [cbang](https://github.com/CauldronDevelopmentLLC/cbang/issues/57) issue tracker to fix the root cause.

Hare are two examples:
[examples.zip](https://github.com/openmm/openmm/files/4726729/examples.zip)

The C++ code used [`cb::SystemUtilities::iopen` with the `autoCompression=True` flag]()
```C++
  bool autoCompression = true;
  auto in = SystemUtilities::iopen(filename, autoCompression);
  System *system = XmlSerializer::deserialize<System>(*in);
```
If you print out the contents, they look fine but cannot be deserialized:
```C++
  bool autoCompression = true;
  auto in = SystemUtilities::iopen(sysFile_, autoCompression);
  std::stringstream contents;
  cb::SystemUtilities::cp(*in, contents);
  cout << contents << endl;
  // This throws the exception
  System *system = XmlSerializer::deserialize<System>(contents);
```
But if you strip out the `\r` characters, deserialization proceeds normally:
```C++
  bool autoCompression = true;
  auto in = SystemUtilities::iopen(sysFile_, autoCompression);
  std::stringstream contents;
  cb::SystemUtilities::cp(*in, contents);
  std::string s(contents.str());
  s.erase( std::remove(s.begin(), s.end(), '\r'), s.end() );
  contents.str(s);
  // This succeeds.
  System *sys = XmlSerializer::deserialize<System>(contents);
```

**Comment by thtrummer** [comment]
Code block 1: 
Your problem here is that you provide a stream that is not seekable which results in the XML parser having no data to work with.

Code block 2: 
This actually shouldn't compile. Assuming it does it's likely that the `cout` line has "used up" all data and the XML parser again has not data to work with.

Code block 3: 
I'm betting this would still work if you comment out `s.erase(...)`.

**Comment by jchodera** [comment]
> Code block 3:
> I'm betting this would still work if you comment out the s.erase(...) line.

Ha! You're right---thanks so much!
