### ISSUE TITLE
Error handling in C API?

### ISSUE THREAD

**Issue by tristanic** [openmm/openmm#2729]
I'm looking into switching my C++ code to use OpenMM's C API, to remove the need for matching compilers between ChimeraX and OpenMM. One thing I can't find in the documentation nor in the code examples: what is the process for handling of exceptions via this API? Is there one?

**Comment by jchodera** [comment]
Is this only a consideration in using conda packages for OpenMM? I wonder if we could help by preparing alternative packages with different compilers under different channel labels.

**Comment by tristanic** [comment]
> Is this only a consideration in using conda packages for OpenMM?

Essentially, yes. But alternative packages aren't really an option: ChimeraX 1.0 will be out in the next fortnight, and the Linux builds will be GCC 4.8 (primarily to maintain compatibility with the OpenMM 7.4.1 that I've been working with). Since the newer OpenMM builds will require GCC > 5, that's a major stumbling block. The ChimeraX team's plan is to revisit the Linux compiler version for version 1.1 (probably in 6 months to a year), but until then I'll be locked to the existing OpenMM version.

**Comment by peastman** [comment]
The C API doesn't make any attempt to handle exceptions.  They just propagate straight through it.

**Comment by jchodera** [comment]
Don't we still use the same `gcc` for OpenMM 7.4.2 as for 7.4.1? We're using the [same docker container](https://github.com/omnia-md/conda-recipes-cuda/blob/master/.travis.yml#L49) and [compiler toolchain](https://github.com/omnia-md/conda-recipes-cuda/blob/master/openmm/build.sh#L37), from what I understand. Unless somehow the `conda-forge` compiler tools were silently updated?

**Comment by tristanic** [comment]
At what point does the new common compute API come in? I believe that was the point of no return.
Anyway, by the sound of it the C API isn't going to be the best way for me to go here. Right now OpenMM is "baked in" to the ChimeraX release, so it won't be possible to update in 1.0 (and they're in their code-freeze period now, so 7.4.1 it is). The plan for 1.1 is to move it into a plugin bundle so it can be updated independently - I was originally going to take this one, but the ChimeraX team have decided they'd prefer to manage it. Having precompiled versions made using your pipeline and matching their compiler would make you very popular with them - one of the reasons this hasn't happened so far is that they really haven't wanted to take on the responsibility of maintaining their own OpenMM build environment.

**Comment by jchodera** [comment]
@tristanic : Maybe you could have them connect up via our issue tracker here and we can figure out the best way forward?

**Comment by tristanic** [comment]
@jchodera Good idea! I've just dropped a message to them to suggest it.
