### ISSUE TITLE
topology.addBond(atom1, atom2): type of atom object?

### ISSUE THREAD

**Issue by nope-sto** [openmm/openmm#2731]
In principle my goal was to create a new bond between substrate and protein. As proposed in the documentations, I've created a HarmonicBondForce object:

`class HarmonicBondForce(object):
    def makeBond(self, atom1, atom2, length_bond, force_constant, system):  
        self.makeBond =system.addForce(mm.openmm.HarmonicBondForce.addBond(self,atom1, atom2, length_bond, force_constant))`

with: 
`#adding protein ligand bond - specification of respective particle atoms and parameters  
particle1= 'protein and index 1542'
particle2='resname LIG name C1'
length_bond = 0.12247
force_constant = 521242.71999999986
bond_selection_reference_topology = mdt.Topology().from_openmm(protein_mod.topology)   
particle1_indices = bond_selection_reference_topology.select(particle1)
for index in particle1_indices:
    atom1=int(index)
particle2_indices = bond_selection_reference_topology.select(particle2)
for index in particle2_indices:
    atom2=int(index)`

I suppose that I've succeeded in adding this Force in this way:
`system = forcefield.createSystem(solvated_model.topology, nonbondedMethod=app.PME, nonbondedCutoff=1.0*unit.nanometers, constraints=app.AllBonds, ewaldErrorTolerance=0.0005, rigidWater=True)
if connected_sub == True:
    HarmonicBondForce.makeBond
#next simulation steps`

The code ran through, but it seems as no bond was formed.

Therefore I assumed, that I need to include the bond into the topology. I've used the modeller object with already inserted ligand (protein_mod):

`top_protein_mod=protein_mod.getTopology()
pos_protein_mod=protein_mod.getPositions()
top_protein_mod.addBond(atom1, atom2)
protein_mod = app.Modeller(top_protein_mod, pos_protein_mod)`

I ended up with this error: 

>  solvated_model.addExtraParticles(forcefield)
  File "/home/usr/anaconda3/envs/sim/lib/python3.7/site-packages/simtk/openmm/app/modeller.py", line 1056, in addExtraParticles
    bondedToAtom[atom1.index].add(atom2.index) AttributeError: 'int' object has no attribute 'index'

I am aware, that there is a problem with the type 'int', but I can not find a specification in the documentations.

Please correct me if I am completely on the wrong way ^^

Thanks in advance!

**Comment by peastman** [comment]
It expects Atom objects.  You're passing it ints instead.

You don't need to add a bond to the Topology.  A Topology represents the chemical structure of a model.  Bonds should only be added for actual covalent bonds.  In contrast, a System is a description of the mathematical model to simulate.  A bond in a HarmonicBondForce just indicates a certain potential term, with nothing implied about what physical entity (if any) it's being used to represent.

I don't understand this code at all:

```python
self.makeBond =system.addForce(mm.openmm.HarmonicBondForce.addBond(self,atom1, atom2, length_bond, force_constant))
```

There are a bunch of problems with it:

1. `addBond()` is not a static method.  You have to call it on an instance of HarmonicBondForce.

2. `addBond()` doesn't return a Force object, so you can't pass the return value to `addForce()`.

3. Why do you overwrite `self.makeBond`???

I believe the code you actually want is something like this:

```python
force = HarmonicBondForce()
force.addBond(atom1, atom2, length_bond, force_constant)
system.addForce(force)
```

**Comment by nope-sto** [comment]
Ok everything works that was too easy. Python newbie just got afraid by the phrase "create object" in the documentation and messed it up.
Thank you very much for your fast reply. Nice tool, nice support. I'll stay with openmm.
