### ISSUE TITLE
QUESTION: How do I apply a constant external force to an atom?

### ISSUE THREAD

**Issue by KirillShmilovich** [openmm/openmm#2732]
Hello!

I'm a new user to OpenMM and would like to perform a simulation where one atom of a molecule is held fixed, for example using:

```
force = mm.CustomExternalForce("k_0*periodicdistance(x, y, z, 0.1, 0.1, 0.1)^2")
force.addGlobalParameter('k_0', 0)
force.addParticle(idx_0, [])
```

Then, I'd like to apply a **constant** external force on another atom along a coordinate, say the z-coordinate. What should be the form of the external force to apply this constant force to an atom?

I've tried something like this so far, but doesn't seem to work:

```
constantForce = mm.CustomExternalForce('k_1*step(100-periodicdistance(x, y, z, x, y, 100))')
constantForce.addGlobalParameter('k_1', 0)
constantForce.addParticle(idx_1, [])
```

Any guidance or references here would be much appreciated. Thank you!!

**Comment by z-gong** [comment]
It should be just like this
```
constantForce = mm.CustomExternalForce('-k_1*z')
```
k1 is the magnitude of the constant force `-dU/dz=k_1`

The function you are using will not work because the derivative is always zero.

**Comment by peastman** [comment]
If you want the first atom to remain truly fixed in place rather than just restrained to stay close to a particular spot, there's an even easier way.  Just set its mass to 0.  That tells the integrator not to update it so it will never move.
