### ISSUE TITLE
No template found for residue

### ISSUE THREAD

**Issue by JGaed** [openmm/openmm#2733]
Hello,

sorry if this is a simple question, but I'm going to switch from LAMMPS to OpenMM for better GPU support. I have just rewritten parts of a adjusted CP&P Forcefield for an ionic liquid into the .xml format. I quiet like the automated bond setting system. Anyway, now I got an error with  "No template found for residue 1 (BUP)" Its my first time to use the .pdb file etc. I tried to figure out why he cant find the residue in the .xml files. Maybe you can give it a litte overlook. I have attached the files because if I insert them as a code the line breaks are gone somehow.

However I hope you will give it a look, thank you very much in advance.
[OpenMM_Files.zip](https://github.com/openmm/openmm/files/4747204/OpenMM_Files.zip)

**Comment by peastman** [comment]
Take a look at https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template and see if it answers your question.  If not, we can dig into it further and see what's going on.

**Comment by JGaed** [comment]
Thank you, it helped me a lot. One question, if I have a non standard residue defined in my forcefield file named BUP and its also labeled BUP in my .pdb file. Do I have to specifiy all bonds in the .pdb file with the "CONECT" label aswell? And I have to use the "HETATM" label if its not a standard residue instead of the "ATOM" label right?

**Comment by jchodera** [comment]
The PDB reader can only assign bonds for standard residues as defined in the [PDB Specification](https://www.rcsb.org/pdb/static.do?p=file_formats/pdb/index.html), so you'll have to specify the `CONECT` records for any nonstandard residues. In principle, the nonstandard residues should be named `HETATM`, but I don't think that OpenMM makes this distinction.

**Comment by Gareth-elliott** [comment]
Hi Everyone, 

Hopefully I'm not hijacking this thread, but I have a similar issue I think. I'm trying to run simulations with different ions in water using amoeba2013. I have been able to run water with no ions, and then with Na+, Li+ and K+ paired with Cl- however I was trying to run simulations with Cs+ and Rb+ as well, and these failed with the error:

"No template found for residue 4168 (CS).  This might mean your input topology is missing some atoms or bonds, or possibly that you are using the wrong force field."

I have the following lines as part of my job script:

# read in pdb file:
pdb = PDBFile(pdbFile)

# instantiate the ForceField Object:
forcefield = ForceField('amoeba2013.xml')

# create the system, specify the topology and the nonbonded stuff:
# note the constraints and rigidWater tags:
system = forcefield.createSystem(pdb.topology, nonbondedMethod=PME,
        nonbondedCutoff=14*angstrom, constraints=None, rigidWater=False,
        polarization='mutual', mutualInducedTargetEpsilon=0.00001)

....

# Instantiate the Simulation object:
simulation = Simulation(pdb.topology, system, integrator)

# print the platform to stdout:
print('Running on Platform: ' + str(simulation.context.getPlatform().getName()))

# Set up the positions and forces:
simulation.context.setPositions(pdb.positions)

The setup for the simulations that worked and for those that failed is identical apart from the atom/residue tags

I looked at the amoeba2013.xml file (at /wrappers/python/simtk/openmm/app/data/amoeba2013.xml), and both CS and RB are listed as atoms and as residues (same for LI, Cl, K, NA). I also checked to see if there was a standard code for these ions in the pdb format, and at least according to PubMed they are correct.

I double checked that the pdb file has the right formatting, and it seems so (here are some sample lines):

ATOM  12499  O   HOH A4167      14.466  36.689  35.986  1.00  0.00
ATOM  12500  H1  HOH A4167      14.035  35.835  35.953  1.00  0.00
ATOM  12501  H2  HOH A4167      14.723  36.864  35.081  1.00  0.00
ATOM  12502  CS  CS  B   1       1.961   2.223   1.931  1.00  0.00
ATOM  12503  Cl  Cl  C   1      50.000   2.000  50.000  1.00  0.00

I'm not sure what other steps I can do to debug this, or if there is a different way of setting up the topology?

Hopefully this makes sense and thanks in advance :)

Thanks,

Gareth

**Comment by peastman** [comment]
Your PDB file is missing elements.  See http://www.wwpdb.org/documentation/file-format-content/format33/sect9.html#ATOM.  The element symbol is supposed to go in columns 77-78.  Without that, it has to try to guess the element based on the atom name, and it will guess that an atom named CS is carbon.

**Comment by Gareth-elliott** [comment]
Thanks @peastman - that was a rather easy fix!

For the simulations that have run using other ions (Li+, Na+, K+, Cl-) is it safe to assume that without the element tags that they ran with the correct parameters (i.e. is there any functionality within the python interface that would allow me to check?)

I hadn't realised that when it reads in the pdb file it looks for those element tags, and I based my pdb file off that (I'm using Packmol to generate the initial box, so I just made templates for water and individual ions) given as an example (/examples/input.pdb) and also at (/wrappers/python/simtk/openmm/app/data) - and none of the ones I looked at had the atom tags (I did just look at all of the pdb files in the second location and realised that the ones that have been generated with OpenMM (e.g. DOPC.pdb) have them - can I suggest it might be helpful for people not particularly familiar with using .pdb files that it be explicitly mentioned in the user manual and/or amend the example pdb files so they have them?

Thanks again for getting to this so quickly :)

**Comment by peastman** [comment]
If in doubt, the best way to check is to have OpenMM reload those PDB files and and see what element it set for the atom.

```python
atoms = list(pdb.topology.atoms())
print(atoms[index].element)
```

Alternatively you could have it write out a new PDB file and see whether it records the correct elements:

```python
with open('output.pdb', 'w') as f:
    PDBFile.writeFile(pdb.topology, pdb.positions, f)
```

**Comment by Gareth-elliott** [comment]
Thanks @peastman - thankfully they had, so no need for me to run them again :)

**Comment by peastman** [comment]
I'm glad! 😀

Can this issue be closed, or are the still open questions on it?

**Comment by Gareth-elliott** [comment]
I'm happy if you want to close it, assuming @JGaed  also has their issue fixed :)

**Comment by JGaed** [comment]
Yes of course, thank you very much! I just forgot the element labels and didnt know that the bonds should be listed for all non standard pdb residues. It works like a charm now. In the next step I have to figure out how to use .pdbx for systems containing > 99999 Atoms.
