### ISSUE TITLE
Simulations die after running for some time, due to CUDA: Error deleting array bondParams

### ISSUE THREAD

**Issue by des2037** [openmm/openmm#2735]
Hi everyone, 

I've been running a long simulation for a system of ~560K atoms, using OpenMM 7.4.0 on Summit (ORNL, POWER9, V100s, CUDA 10.1.168). We've run the simulations for ~228 ns, over many restarts (using xml statefiles). However, the simulations have recently started dying after exactly 280,000 steps. I don't think this is related to the system entering a bad state because I've tried restarting from earlier xmls (that have previously worked), but encounter the same problem. Here's the error message:

```
  File "/ccs/proj/bip109/anaconda_2019_10/envs/openmm_7.4.2_cuda_10.1.243/lib/python3.7/site-packages/simtk/openmm/app/simulation.py", line 132, in step
    self._simulate(endStep=self.currentStep+steps)
  File "/ccs/proj/bip109/anaconda_2019_10/envs/openmm_7.4.2_cuda_10.1.243/lib/python3.7/site-packages/simtk/openmm/app/simulation.py", line 197, in _simulate
    self.integrator.step(10) # Only take 10 steps at a time, to give Python more chances to respond to a control-c.
  File "/ccs/proj/bip109/anaconda_2019_10/envs/openmm_7.4.2_cuda_10.1.243/lib/python3.7/site-packages/simtk/openmm/openmm.py", line 15576, in step
    return _openmm.LangevinIntegrator_step(self, steps)
Exception: Error synchronizing on event for CCMA: CUDA_ERROR_UNKNOWN (999) at /ccs/proj/bip109/openmm_7.4.2/platforms/cuda/src/CudaIntegrationUtilities.cpp:631
terminate called after throwing an instance of 'OpenMM::OpenMMException'
  what():  Error deleting array bondParams: CUDA_ERROR_UNKNOWN (999)
```

I thought maybe this could be caused if Summit updated their NVIDIA drivers (just a guess), so I (re)compiled both v7.4.0 and v7.4.2 from source, using CUDA 10.1.243. Nevertheless, in both cases I still get the same error. 

Any ideas as to what might be going on, or how to troubleshoot this? 

Thanks as always!

**Comment by peastman** [comment]
Not much idea.  `CUDA_ERROR_UNKNOWN` is about as uninformative as it sounds.  The documentation just says, "This indicates that an unknown internal error has occurred."  I've only found a small number of other reports of people encountering that error, mostly in TensorFlow.  They mostly seem to indicate some sort of driver installation problem.  See for example https://github.com/tensorflow/tensorflow/issues/394.  But those are when initializing CUDA, not after it's been successfully running for a long time.

Is it possible the drivers on the computer have gotten updated?

**Comment by des2037** [comment]
That's a good question, but I would guess the crash happens between step 280,000 (the last checkpoint written) and 290,000 (which it doesn't get to before failing). I'm basing this on the fact I see good GPU utilization after 280,000 is written to the log file--that is the openMM process doesn't instantly die after writing step 280,000 (so it's probably not really crashing exactly at step 280,000). 

Given this currently seems limited to a specific system (and somehow related to the environment provided by the queuing system), I think I'm going to see how this calculation does on another cluster. I'll report back if I observe anything noteworthy. 🙂

**Comment by jchodera** [comment]
Would it be possible to post a ZIP archive of the serialized `System`, `State`, and `Integrator` XML files?

I wonder if the system isn't re-imaged into the box---OpenMM doesn't do this by default---and some molecules have just drifted to very large magnitude Cartesian coordinates.

**Comment by peastman** [comment]
> I wonder if the system isn't re-imaged into the box---OpenMM doesn't do this by default---and some molecules have just drifted to very large magnitude Cartesian coordinates.

Internally it actually does do that to maintain accuracy.  It keeps track of the integral number of box vectors it has translated by in each dimension so it can put them back to the "correct" positions on output.

Does this simulation use periodic boundary conditions?

**Comment by des2037** [comment]
Hi @peastman @jchodera ,

Yes, the calculation does use PBC. 

**Update:** this exact same calculation runs perfectly fine on another cluster. In addition, it runs without error on the Summit submit node. So what this means is that there is something about the environment that Summit's job scheduler (LSF) provides that openMM doesn't like. This is extremely weird because things my LSF setup was running fine (for this exact calculation) until recently (maybe the setup was dependent on a non-obvious default that has been changed). On the other hand, this possible environment weirdness only impacts this specific system (other systems are currently unaffected)! 

Regardless, I don't want to burden your time on what seems to be a system and data-center related problem. If this becomes more systemic, I'll reopen the issue. 

Thanks very much for your thoughts! 🙂
