### ISSUE TITLE
Error initializing FFT:2

### ISSUE THREAD

**Issue by VincenzoChen** [openmm/openmm#2739]
Hi everyone, I am new to openmm. When I use it to run molecular simulations in drude force field, it ouput such error.Why does this error occur and how can I resolve it?
```Traceback (most recent call last):
  File "run_Drude.py", line 154, in <module>
    simulation = app.Simulation(psf.topology, system, integrator, platform)
  File "/home/chenzhao/anaconda3/envs/chemtool/lib/python3.7/site-packages/simtk/openmm/app/simulation.py", line 103, in __init__
    self.context = mm.Context(self.system, self.integrator, platform)
  File "/home/chenzhao/anaconda3/envs/chemtool/lib/python3.7/site-packages/simtk/openmm/openmm.py", line 18608, in __init__
    this = _openmm.new_Context(*args)
Exception: Error initializing FFT: 2```

**Comment by peastman** [comment]
Error code 2 is `CUFFT_ALLOC_FAILED`, which the documentation describes as, "cuFFT failed to allocate GPU or CPU memory."  The most likely reason for that is that you were trying to use a huge grid for PME.  What are the dimensions of your periodic box?  And did you modify any settings related to PME, such as the error tolerance or the grid dimensions?  If so, what did you set them to?

**Comment by VincenzoChen** [comment]
`system = psf.createSystem(params, nonbondedMethod=ff.PME, nonbondedCutoff=1.20, switchDistance=1.00, ewaldErrorTolerance=0.0001, constraints=ff.HBonds)`
I use this sentence to create a system which is related to PME.
What's more ,I define my periodic box as follow:
```
box1=np.array([86 A,0.00,0.00])
box2=np.array([0.00,86 A,0.00])
box3=np.array([0.00,0.00,86 A])
simulation.context.setPeriodicBoxVectors(box1,box2,box3)
```

**Comment by VincenzoChen** [comment]
When I reduce the ewaldErrorTolerance, this error didn't occur.But another problem was produced.
```Exception: Error launching CUDA compiler: 256
/tmp/openmmTempKernel0x559874044b90_4956.cu(1002): error: calling a constexpr __host__ function("fmin") from a __global__ function("computeBondedForces") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/tmp/openmmTempKernel0x559874044b90_4956.cu(1003): error: calling a constexpr __host__ function("fmin") from a __global__ function("computeBondedForces") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

2 errors detected in the compilation of "/tmp/tmpxft_000013a6_00000000-6_openmmTempKernel0x559874044b90_4956.cpp1.ii".```

**Comment by peastman** [comment]
> box1=np.array([86 A,0.00,0.00])

That doesn't look like valid Python syntax.  Do you mean `86*angstroms`?  Make sure it really knows you mean angstroms.  If you've set the box width to 86 nanometers that would certainly explain it running out of memory!

What version of OpenMM are you using?  The compiler error message you posted looks a little (but not exactly) like one we were getting for a while in the development code before we fixed it, but it shouldn't happen in any released version.  Also what OS and CUDA version do you have?

**Comment by VincenzoChen** [comment]
Yeah, the 86 A means 86*angstroms. So the openmm can't deal with the system which is too large? If so, which size is the cutoff?     
The version of my OpenMM is 7.4.2, and my OS is centos 8. My cuda is V10.2.89. It seems that the cuda version is too high.

**Comment by VincenzoChen** [comment]
I use openmm7.4.2 in lower cuda version which is 9.2 and it said the cuda module can't be loaded.
```
Exception: Error loading CUDA module: CUDA_ERROR_ILLEGAL_ADDRESS (700)
terminate called after throwing an instance of 'OpenMM::OpenMMException'
  what():  Error deleting array bondParams: CUDA_ERROR_ILLEGAL_ADDRESS (700)
Aborted
```

**Comment by peastman** [comment]
Can you post the full script plus input files so I can try to reproduce this?  It's hard to guess what the problem might be.

**Comment by VincenzoChen** [comment]
I have solved the problem with cuda because the system is too large. No I did energy minimization and when I wanted to do equilibrium with the ouput pdb from energy minimization, It ouput such error:
```ValueError: Energy is NaN```
My scripts and pdb file are here:[drude.tar.gz](https://github.com/openmm/openmm/files/4798430/drude.tar.gz)
(just enter the folder and then use command `python ***.py -i input.inp` to run them)

**Comment by peastman** [comment]
Take a look at https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#nan.  It discusses the common sources of that error.

**Comment by VincenzoChen** [comment]
I try all the parameters showed by this documents, but it still didn't work. When I used CHARMM to run drude MD with this system, it worked well. What's more, I have compared the structure of protein before energy minimization and after. And I found that the two structures were same. It seemed that the energy minimization have not worked on the system. But the ouput of energy was indeed smaller.

**Comment by peastman** [comment]
> And I found that the two structures were same. It seemed that the energy minimization have not worked on the system. But the ouput of energy was indeed smaller.

I don't think I understand.  The minimizer searches for a new structure with lower energy.  If the energy went down, then structure can't have been the same?
