### ISSUE TITLE
CudaUpdateStateDataKernel::setPositions may read uninitialized data from the device

### ISSUE THREAD

**Issue by thtrummer** [openmm/openmm#2740]
Is [this line](https://github.com/openmm/openmm/blob/e4c1f73c6875452c7d00b0922419806333a4518c/platforms/cuda/src/CudaKernels.cpp#L212) strictly necessary (especially compared to the mixed precision case)? If yes, then there is a problem where this line reads uninitialized data from the device (for `TestCudaVirtualSites`).

**Comment by peastman** [comment]
We need to download it first to avoid overwriting the `w` component of each vector, which may be used to hold atomic charges.  It's possible the content of that array is uninitialized, but if so we immediately overwrite all of it except the `w` component.  Those in turn get initialized by NonbondedForce, while leaving the other three components unchanged.

So basically, the different components get initialized at different times, but they're all guaranteed to be initialized before any code relies on them.

**Comment by thtrummer** [comment]
Thanks for the explanation.
