### ISSUE TITLE
"two constraints between the same atoms" error by only OpenMM 7.5

### ISSUE THREAD

**Issue by fhh2626** [openmm/openmm#2742]
Dear all,

[test.zip](https://github.com/openmm/openmm/files/4776297/test.zip)

When trying to run the above files using OpenMM 7.5 beta (Cuda 10.2), I got an error "Exception: The System has two constraints between the same atoms.  This will produce a singular constraint matrix". However, everything seems good when using OpenMM 7.4 (Cuda 10.1) or other MD engine like NAMD.
I guess there is some major change in OpenMM 7.5 when parsing CHARMM psf files?

Thanks,
Haohao

**Comment by z-gong** [comment]
This issue comes from the explicit H-H bonds in the psf file. It should have already been fixed in the master branch by #2615.

**Comment by fhh2626** [comment]
> This issue comes from the explicit H-H bonds in the psf file. It should have already been fixed in the master branch by #2615.

Thanks for your reply!
