### ISSUE TITLE
Amber ff19SB and OPC water model?

### ISSUE THREAD

**Issue by ltchong** [openmm/openmm#2743]
Hi! What is the status of porting Amber ff19SB (and the OPC water model) to OpenMM? We would love to use it when it is ready.

**Comment by jchodera** [comment]
AMBER ff19SB uses CMAP torsional potentials. While OpenMM fully supports these, ParmEd does not yet support the conversion of CMAP into OpenMM format. It would be easy to add, and @chuantian thought he might have time to add it, but the OpenMM devs don't have the bandwidth to maintain ParmEd. See this thread: https://github.com/openmm/openmmforcefields/issues/75

OPC water could be easily added, though! Can you suggest which `leaprc` files should be converted, or which page of the AmberTools 20 manual describes the recommended `leaprc` files?

**Comment by chuantian** [comment]
The leaprc file to OPC water model is located at: $AMBERHOME/dat/leap/cmd/leaprc.water.opc. I used that in tleap to build up all OPC simulations in Amber.

**Comment by jchodera** [comment]
@chuantian : Does that include all the relevant ions, or do they have to be bundled together from different `leaprc` files?

**Comment by chuantian** [comment]
This leaprc file kind of acts as "bash" script to read from multiple library/parm files that have water, ions parameters, etc. This leaprc file, together with 2 lib files and 3 frcmod files will be relevant and required for OPC model.   In addition, if within amber tleap, in practice, users would just "source leaprc.water.opc" and everything will be read in.

**Comment by jchodera** [comment]
Great! I'll add this to `openmmforcefields`.

**Comment by peastman** [comment]
> ParmEd does not yet support the conversion of CMAP into OpenMM format.

Are you sure of that?  It's fine with converting CMAPs from CHARMM files.  Maybe it doesn't work with Amber input files.

**Comment by jchodera** [comment]
> See this thread: openmm/openmmforcefields#75

That points to the issue, which is that ParmEd doesn't support _exporting_ CMAP to OpenMM: https://github.com/ParmEd/ParmEd/issues/1066

**Comment by peastman** [comment]
When translating a CHARMM force field to OpenMM, it has no problem exporting the CMAPs.

**Comment by jchodera** [comment]
Whoops, you're right---please see https://github.com/ParmEd/ParmEd/issues/1066#issue-514416452

I've just checked this with the latest `ambertools 20` and the issue is still there.

**Comment by tuckerburgin** [comment]
Sorry to comment in a closed issue. I can't find a clear answer -- now that ParmEd can handle Amber CMAP terms, does OpenMM currently support importing Amber topology files that use ff19SB?

I am getting some weird behavior with OpenMM minimization on an ff19SB + OPC system, though the same code was working fine with ff14SB + TIP3P. Trying to figure out if it's something on my end or if OpenMM just doesn't support it yet.

**Comment by peastman** [comment]
Not yet.  We're looking into adding support.

**Comment by sreyoshi09** [comment]
Sorry to comment on this closed issue. But I also ran a minimization and an equilibration run for OPC water and RNA OL3 system and the system was acting very weird. Since my OpenMM code did not give any error initially I thought my system was running ok. If OPC is not supported it would be really helpful if we could at least get a warning or an error message.

**Comment by peastman** [comment]
I assume you did that by loading a prmtop file?  That should work correctly.  This issue is about providing a converted force field so you can use it without going through AmberTools.
