### ISSUE TITLE
Python Bindings Issue

### ISSUE THREAD

**Issue by Exarctus** [openmm/openmm#2746]
Hey all,

I've recently compiled openMM from source. I need the version that's currently on github as it contains #2701 but this doesn't seem pushed to the omnia repository (conda search openmm gives 7.4.2 as the latest).

OpenMM builds fine, all tests work great and building python bindings seems to have been fine on first look, however, when I try to do the following:

```python
from simtk import openmm
```
the following error is produced:

```
Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from simtk import openmm
Traceback (most recent call last):
  File "/home/nick/anaconda3/lib/python3.7/site-packages/simtk/openmm/openmm.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'simtk.openmm._openmm'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nick/anaconda3/lib/python3.7/site-packages/simtk/openmm/__init__.py", line 19, in <module>
    from simtk.openmm.openmm import *
  File "/home/nick/anaconda3/lib/python3.7/site-packages/simtk/openmm/openmm.py", line 17, in <module>
    _openmm = swig_import_helper()
  File "/home/nick/anaconda3/lib/python3.7/site-packages/simtk/openmm/openmm.py", line 16, in swig_import_helper
    return importlib.import_module('_openmm')
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_openmm' 
```

If anyone could provide any insight would be much appreciated.

**Comment by peastman** [comment]
Take a look in `/home/nick/anaconda3/lib/python3.7/site-packages/simtk/openmm`.  Is there a file there whose name starts with `_openmm.`?  If not, something has gone wrong with the installation.

If the file is there, it's possible it isn't able to load due to an unresolved dependency on some other library.  Try running `ldd` on that file.  What is the output?

**Comment by Exarctus** [comment]
@peastman 

Thanks for the reply! The file exists and ldd all linked libraries seem to exist...

```
ldd _openmm.cpython-37m-x86_64-linux-gnu.so
	linux-vdso.so.1 (0x00007fffb31a1000)
	libOpenMM.so => /home/nick/anaconda3/lib/libOpenMM.so (0x00007f09051a3000)
	libOpenMMAmoeba.so => /home/nick/anaconda3/lib/libOpenMMAmoeba.so (0x00007f0904f17000)
	libOpenMMRPMD.so => /home/nick/anaconda3/lib/libOpenMMRPMD.so (0x00007f0904d09000)
	libOpenMMDrude.so => /home/nick/anaconda3/lib/libOpenMMDrude.so (0x00007f0904af7000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f090476e000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f09043d0000)
	libgcc_s.so.1 => /home/nick/anaconda3/lib/libgcc_s.so.1 (0x00007f0905db4000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f09041b1000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f0903dc0000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f0903bb8000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f09039b4000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f0905bce000)
```
Should note that a few of the tests failed but they don't seem significant/related:

```99% tests passed, 3 tests failed out of 465

Total Test time (real) = 2512.55 sec

The following tests FAILED:
	186 - TestOpenCLCheckpointsMixed (Failed)
	187 - TestOpenCLCheckpointsDouble (Failed)
	416 - TestCudaDrudeNoseHooverMixed (Failed)
```

**Comment by Exarctus** [comment]
I seem to have found a workaround:

I had some pre-existing libraries in /home/nick/anaconda3/lib/libOpenMM* from a previous openMM installation, which were installed via conda a while ago. Calling conda remove openmm didn't seem to remove these as well.

When I built openmm, it installed these libraries into the default /usr/local/openmm/lib/* location, but didn't seem to use these for building the python bindings while using the anaconda python3 interpretter. I copied over all openMM libraries from /usr/local/openmm/lib/* into /home/nick/anaconda3/lib/ and this seems to have fixed the problem.

**Comment by peastman** [comment]
It sounds like Python was getting confused by having multiple copies of OpenMM around.  Possibly the new version of the Python module was trying to link to the old version of the libraries?  If you just completely remove the libraries from `/home/nick/anaconda3/lib/` does it work?

Anyway, glad you managed to get it working!
