### ISSUE TITLE
NonbondedForceImpl  evalIntegral

### ISSUE THREAD

**Issue by TobiasWilming** [openmm/openmm#2747]
Hi I took a look into https://github.com/openmm/openmm/blob/3fef456d8290ece8e78d332a79ab1d7920b86983/openmmapi/src/NonbondedForceImpl.cpp#L198. I tried to optimised it a little bit I have not tested it yet because I have not set up the project on my free time on my pc. Is it woth to take a deeper look into this? This is what I came up with in a short amount of time.

`double NonbondedForceImpl::evalIntegral(double r, double rs, double rc, double sigma) {
    // Compute the indefinite integral of the LJ interaction multiplied by the switching function.
    // This is a large and somewhat horrifying expression, though it does grow on you if you look
    // at it long enough.  Perhaps it could be simplified further, but I got tired of working on it.
    
    double A = 1/(rc-rs);
    double A2 = A*A;
    double A3 = A2*A;
    double sig2 = sigma*sigma;
    double sig6 = sig2*sig2*sig2;
    double rs2 = rs*rs;
    double rs3 = rs*rs2;
    double r2 = r*r;
    double r3 = r*r2;
    double r4 = r*r3;
    double r5 = r*r4;
    double r6 = r*r5;
    double r9 = r3*r6;
    double rsA = rs*A;
    double rs2A2 = rs2*A2;
    double rs2A26 = 6*rs2A2;
    double f = (2*rs*A2 + A);
    double g = (rs2A26 + 6*rsA + 1);
    double h = rs3*(rs2A26 + 15*rsA + 10);
    double i = r*rs2*(rs2A2 + 2*rsA + 1);
    double j = r2*rs*(2*rs2A2 + 3*rsA + 1);
    return sig6*A3*((
        sig6*(
            + 28*h
            - 945*i
            + 1080*j
            - r3*420*g
            + r4*756*f
            - r5*378*A2)
        -r6*(
            + 84*h
            - 3780*i
            + 7560*j)
        )/(252*r9)
     - log(r)*10*g
     + r*15*f
     - r2*3*A2
    );
}`

**Comment by peastman** [comment]
Thanks!  I wouldn't worry about this routine too much.  It's unlikely to ever be a significant performance bottleneck.  Also, compilers are pretty good at doing common subexpression elimination, so if you see the same subexpression more than once, you don't need to manually define a variable for it.  The compiler is smart enough to do that automatically.
