### ISSUE TITLE
CHARMM Drude NBThole implementation

### ISSUE THREAD

**Issue by aakognole** [openmm/openmm#2750]
There is a difference in charmm and openmm energies for drude systems. 
```
Software | Version | Energy (kcal/mol)
         |         | FULL      | Only DNA | Only WATER | Only IONS
Charmm   | c44b2   | -99876.39 | -3054.58 |  -84250.37 | -93.45
OpenMM   | 7.4.2   | -98798.26 | -2245.06 |  -83989.81 | -85.04
``` 
The difference appears to be coming from this modification to add exception parameters into NBThole by @jing-huang

[https://github.com/openmm/openmm/commit/31f7f3559990caa924560118dfdf7f8be835d6fe](url)

Energies after commenting this part are acceptable. However there is a difference in water energy and ions which is another issue to solve.
```
Software | Version | Energy (kcal/mol)
         |         | FULL      | Only DNA | Only WATER | Only IONS
Charmm   | c44b2   | -99876.39 | -3054.58 |  -84250.37 | -93.45
OpenMM   | 7.4.2   | -98798.26 | -2245.06 |  -83989.81 | -85.04
OpenMM   | mod     | -99597.54 | -3044.19 |  -83989.92 | -85.04
``` 
Thanks.

**Comment by jing-huang** [comment]
The modification is to get NBThole handled in a consistent way. Which particular NBThole pair is involved in your DNA system?

**Comment by aakognole** [comment]
There are two NBThole parameters that we are using that are specific to nucleic acids. One of them has been there since Drude-2018 and now we have added new one specific to pair between phosphate anionic O and C3' as well. I was able to confirm that the energy difference comes from these two parameters.

However they are both 1-4 separated. 

```
! nucleic acid specific
CD32C  OD2C2B  1.45000 ! phosphate anionic O to C5' -- special 1,4 term
CD315B OD2C2B  1.45000 ! phosphate anionic O to C3' -- special 1,4 term
```

**Comment by jing-huang** [comment]
Thanks. I think it is because the current NBThole implementation marks these 1-4 interactions to be non-bonded so their electrostatics and vdw interactions are computed and added to the total energy. Let me work out a fix.

**Comment by peastman** [comment]
@jing-huang do you have any update on this?

**Comment by jing-huang** [comment]
A postdoc in my group just fixed this. He will commit the fix soon.
