### ISSUE TITLE
How to do NVT equilibrium on system using drude force field

### ISSUE THREAD

**Issue by VincenzoChen** [openmm/openmm#2752]
@jing-huang Dear Mr.Huang, since I have read your article "Molecular Dynamics Simulations Using the Drude Polarizable Force Field on GPUs with OpenMM: Implementation, Validation, and Benchmarks", I was wondering that how did you do NVT equilibrium on a system using drude force field. I have not seen the relative part in the script that you offerred in you supplementary material. And I also can't find the relative manual on the web. So would you please to show me an example about doing NVT equilibrium on system using drude force field?

**Comment by jing-huang** [comment]
NVT simulations can be carried out as long as the MonteCarloBarostat is switched off. Typically we first perform some equilibrium simulations using CHARMM additive force fields, and then switch to Drude simulation. You could take a look at the scripts in CHARMM-GUI (http://charmm-gui.org/?doc=input/drude) for reference.

**Comment by VincenzoChen** [comment]
Thank you very much! It is really helpful to my problem.

**Comment by VincenzoChen** [comment]
@jing-huang  Mr.Huang, I have one more question that when I use DrudeLangevinIntegrator in my script, I set the temperature equal to 298.15k. But when I check the output of StateDataReporter,  the temperature always doesn't converge at a temperature far away from 298.15k. Maybe you know something about such bias?

**Comment by VincenzoChen** [comment]
Temperature (K)
188.74302940794016
183.85888451794972 
187.97175771225116 
192.60808407155298
here is an example of output of temperature in different time.

**Comment by peastman** [comment]
That's actually correct.  DrudeLangevinIntegrator tries to keep different parts of the system at different temperatures.  The center of mass of each atom (including its Drude particle if it has one) is at 298.15, but the relative motion of the Drude particle relative to the atom is at a much lower temperature, typically around 1K.  StateDataReporter is reporting the overall temperature of the whole system, that is, the mean kinetic energy of all degrees of freedom.  That should be somewhere in between the two temperatures.
