### ISSUE TITLE
How to delete residues with Modeller

### ISSUE THREAD

**Issue by atbogetti** [openmm/openmm#2753]
Hello,  I have a modeller object in openmm and I would like to delete a certain residue (say, residue 300).  It's an NO3 molecule, so it will not interrupt connectivity with the rest of the molecule.  How can I do this?  I see I can use the Modeller.delete() function but how do I specify the residue?  And more generally, how do I select/specify residues, atoms etc with openmm topologies?

**Comment by peastman** [comment]
The argument to `delete()` is the list of objects to delete: atoms, residues, chains, or bonds.  For example, if you want to delete every NO3 residue you could write

```python
toDelete = [r for r in topology.residues() if r.name == 'NO3']
modeller.delete(toDelete)
```

Of course, you can write whatever logic you want for selecting what to delete.  See http://docs.openmm.org/latest/api-python/generated/simtk.openmm.app.modeller.Modeller.html#simtk.openmm.app.modeller.Modeller.delete.

**Comment by atbogetti** [comment]
Thanks!  This worked for me.

**Comment by pguillem** [comment]
Hi @peastman 
I tried to delete a chain from a modeller instance, like this:

```
chains = [r for r in topology.chains()]
chains 
 [<Chain 0>, <Chain 1>]
modeller.delete([chains[0]])

```
Command succeeds, but no chains are deleted.
using chains[0] alone is not irterable.

Also tried to delete all residues below 100 as in your example above:

```
toDelete = [r for r in topology.residues() if int(r.id) < 100]
modeller.delete(toDelete)

```
Cmd succeeds, but no residues are deleted from the modeller instance. 
Am I doing something wrong?

Best
Pedro

**Comment by peastman** [comment]
Can you show the complete code?  I can't tell from just those two lines what you're doing wrong.  Remember that `delete()` doesn't modify the existing Topology.  It creates a new Topology.  After the call, `modeller.topology` will be a new object without the deleted elements.

**Comment by pguillem** [comment]
Thanks @peastman

It makes much more sense now. 
Are these topologies still in memory after each function call? if so, are they accesible/iterable?

**Comment by peastman** [comment]
Modeller doesn't keep around references to previous Topologies, but you can store a reference to `modeller.topology` after each call if you want to keep it.

**Comment by pguillem** [comment]
Excellent.
Thanks!

**Comment by mdatif3909** [comment]
hello @peastman , i am too late here for discussion . i have generated the topology file for MnO2 8 by 9 in x y direction but i want it to be periodic in 7 by 7 x y direction for that i need to delete some extra residues and all the necessary information related to that residue . how can i do that ?? Pls ask if any extra information u need to get the things clear

**Comment by peastman** [comment]
Use [`modeller.delete()`](http://docs.openmm.org/latest/api-python/generated/openmm.app.modeller.Modeller.html#openmm.app.modeller.Modeller.delete).  Pass it a list of the residues you want it to delete.  See above for more details.

**Comment by mdatif3909** [comment]
Glad to see you are here , please tell me what is the first step to do the above task effectively as new learner so i am not getting the things clearly beacuse i have  total 72 residues in my topology file , how many residues i have to delete like 9,18,27,--- till 72 ?? and what we will do with residue 8,16,24---- becuase it also comes beyond boundary limits . Pls provide me a detail , i will sincerely comsider your help .

**Comment by peastman** [comment]
You need to figure out which residues you want to delete.  I can't answer that for you.  It depends on how you generated the topology, and how the residues are arranged, and what arrangement you want to end up with.  It sounds like you might want to do it by looking at the x and y coordinates for them?

**Comment by mdatif3909** [comment]
Yes i want to do it with x y coordinate since my single unit cell size is around 5 Angstrom in both directions and I have replicated my .pdb file in x direction 8 times and in y direction 9 times to make a large sheet and generated the topology file and i want my actual size 7 times in both directions for that i need to delete some residues from my topology file .
