### ISSUE TITLE
"CUDA" platform can not be registered due to failure of loading 'libcuda.so.1' and 'libnvrtc.so.10.1'

### ISSUE THREAD

**Issue by frank-stonybrook** [openmm/openmm#2760]
Dear OpenMM developers,

I compiled OpenMM (**7.4.2**) with **CUDA/10.1**. The installation seems successfully as the 
``` 
python -m simtk.testInstallation
``` 
output reasonable results for three platforms (CPU, Reference, CUDA) on the login node. 

While running OpenMM simulations on the compute node using GPU will throw exception of no registered CUDA platform.  I did some self-check using these commands on the compute node:
```python
from simtk.openmm import *
print(pluginLoadedLibNames)
print(Platform.getPluginLoadFailures())
```
It complains of 'libcuda.so.1' and 'libnvrtc.so.10.1' can not be loaded. CUDA version reported by `nvidia-smi` is **10.2**  while the `nvcc` is **10.1**. 
Could it be the version mismatch causes the problem?

Thanks

**Comment by peastman** [comment]
The first thing to check is that the libraries are actually present and in your library path.  Do you need to execute some sort of `module load` command or something similar?  Are those libraries present, and if so where are they?

**Comment by frank-stonybrook** [comment]
You are right! I was trying to use a premature cluster. The system admin put CUDA at /usr/local/cuda at the login node while the same directory doesn't exist on the computing node! No Module utility support. I will notify them to properly configure the computing nodes. Lessons learned: never use premature cluster....

**Comment by peastman** [comment]
Glad it was that simple!
