### ISSUE TITLE
Virtual Sites Implementation

### ISSUE THREAD

**Issue by SofiaBariami** [openmm/openmm#2761]
Hello, I have a question about the implementation of Local Coordinates Virtual sites. I'm modifying the source code of [Sire](http://siremol.org) to support v-sites and I'm testing my implementation using a pyridine pdb/xml with one virtual site. However, the energy that I'm getting using an OpenMM script does not match the energy from Sire (the difference is ~ 0.12 kcal/mol). In summary, here are the steps that I have followed: 
1. Read the xml and store the parameters (the parameters are read correctly)
2. Add a particle of zero mass and define the v-site:
```
system_openmm->addParticle(0.0); 
OpenMM::LocalCoordinatesSite * vsite = new OpenMM::LocalCoordinatesSite(atom1, atom2, atom3, OpenMM::Vec3(wo1, wo2, wo3), OpenMM::Vec3(wx1, wx2, wx3) , OpenMM::Vec3(wy1, wy2, wy3), OpenMM::Vec3(pos1, pos2, pos3));
```
(debugging output to make sure that everything is set correctly):
```
NUMBER OF PARTICLES BEFORE V-SITE:  11
positions std::vector(-0.046, -0.075, 0)  o_weights  std::vector(1, 0, 0)  x_weights  std::vector(-1, 1, 0)  y_weights  std::vector(-1, 0, 1) parent atoms std::vector(3, 2, 4)
vsite SYSTEM INDEX:   11  VSITE:  0x564c0bfd26d0
IS VSITE? :   true THE MASS IS:  0
NUMBER OF PARTICLES AFTER V-SITE :   12
```
3. Added the nonbonded parameters: 
```
nonbond_openmm->addParticle(charge_vs, sigma_vs * OpenMM::NmPerAngstrom, epsilon_vs * OpenMM::KJPerKcal);
```
4. Add a custom forcefield for free energy calculations. `custom_non_bonded_params_vs` contains the initial and final charges and LJ parameters of the v-site (here it's not perturbed):
```
custom_force_field->addParticle(custom_non_bonded_params_vs);
```
5. Find the 1-4 pairs of the v-site and add them to the `custom14pairs` list because we are using the OPLSAA scaling factors (0.5, 0.5) that are not the default ones. 
 
6. Make a bond with the parent atom and use `createExeptionsFromBonds`: 
```
bondPairs.push_back(std::make_pair(system_index, parent_index));
nonbond_openmm->createExceptionsFromBonds(bondPairs, Coulomb14Scale, LennardJones14Scale); 
```

Am I missing something here?
One thing I noticed is that by changing the index of the parent atoms and/or the local coordinates the energy remains the same. However, this shouldn't happen as a change like this would change the distance between the v-site and the other atoms, and consequently the electrostatic interactions, right? So is there a mistake at the way that I have initially defined the virtual site? 

Any help with this would be much appreciated. You can find the input files that I'm using and the openMM script [here](https://uoe-my.sharepoint.com/:f:/g/personal/s1786388_ed_ac_uk/Elw-QEEWXO9PlbG396pLZWAB9ses5gZIDCTP8wdjffyRww?e=dgnhiz). Thank you very much!

**Comment by peastman** [comment]
In between the call to `setPositions()` and the call to `getState()` add this line:

```python
simulation.context.computeVirtualSites()
```

When you call `setPositions()`, it sets all the particles to exactly the positions you specify, even if some of those are "incorrect" according to the constraints and virtual site rules.  You need to tell it to fix them either by calling `computeVirtualSites()` or by calling `applyConstraints()`, which also fixes the virtual sites.  Normally you don't need to think about this because that's done automatically in each time step.  But because you aren't doing any integration, you need to tell it to do it.

**Comment by SofiaBariami** [comment]
@peastman this worked! Thank you very much. 
I'll close the issue now
