### ISSUE TITLE
Center of mass/coordinates calculations in CustomNonbondedForce

### ISSUE THREAD

**Issue by jeff231li** [openmm/openmm#2763]
Hi,

I want to experiment with a nonbonded potential that involves a transformation of coordinates before calculating the pairwise distance interaction. The transformation requires the center of mass/coordinates of the molecule of interest. The center of mass calculation is implemented in `CustomCentroidBondForce` where you add particles with `addGroup` and the center of mass is referenced as `x1,y1,z1,...,xn,yn,zn` in the string energy expression. How hard will it be to implement this feature in `CustomNonbondedForce`?

Cheers,
Jeff

**Comment by peastman** [comment]
Could you describe your interaction?  How many groups are there that you're computing COM for?  How many particles are in each one?  Does every group interact with every other group?  What is the functional form of the interaction between groups?

**Comment by jeff231li** [comment]
The interaction uses the same functional form as most FF (Coulomb and LJ12-6) but I want to scale the pairwise distance. The coordinates are transformed with `x'=((1-l)*xcom - l*x)` (where `l` is the scaling factor) before the pairwise distances are calculated. This will only be applied to the intermolecular interactions but the intramolecular interactions stay the same. So, the molecule of interest will interact with the rest of the environment with scaled pairwise distances but atoms within the molecule will use the nontransformed distances (Looking at the document I think I need to specify two interaction groups in `CustomNonbondedForce`). Right now I'm only looking at adding one group representing a small molecule but I guess this could be generalized to multiple groups.

**Comment by peastman** [comment]
So all interactions between particles are computed with a standard pairwise form, but they're based on altered positions for the particles?  I don't think that can be done with a custom force.  You'll need to write a plugin instead.  AmoebaVdwForce does something very similar, where hydrogens interact through "reduced" positions that are moved slightly toward their parent atoms.

**Comment by jeff231li** [comment]
I see. I thought `CustomNonbondedForce` can be used because `openmmtools/alchemy.py` implements a decoupling feature for alchemical calculations with custom forces, which defines separate interaction groups and only perturbing the intermolecular interactions. I'm trying to do something similar to the decoupling feature but instead of scaling the energies directly, I'm scaling the pairwise distances. I'll take a look at the process of writing a plugin for OpenMM to see if it's worth the effort.
