### ISSUE TITLE
NPT Simulation - write CRYST1 information in .pdb file at each step

### ISSUE THREAD

**Issue by Gareth-elliott** [openmm/openmm#2767]
Hi OpenMM developers,

I have recently been running some simulations and was outputting to a .pdb format as I use TRAVIS (http://www.travis-analyzer.de) to analyse the trajectories. It seems as though OpenMM only prints the CRYST1 (i.e. box dimensions) in the header of the trajectory file, even for an NPT run where the box size is changing - is there a way to make it dump it at every step?

Thanks, 
Gareth

**Comment by peastman** [comment]
This is inherent in the PDB format.  It only allows a single set of box vectors for the whole file, not one per frame.  I recommend using DCDReporter instead, which does allow saving a separate box size for each frame.  It's also a much better trajectory format for other reasons.  The files are much smaller, and it stores the coordinates to higher accuracy.

**Comment by Gareth-elliott** [comment]
Hi @peastman - ah ok thanks, I might check out the DCDReporter - however I don't think it can be read by TRAVIS, so I might have to try use something like MDAnalysis.
