### ISSUE TITLE
Do protein-ligand simulation in drude force field

### ISSUE THREAD

**Issue by VincenzoChen** [openmm/openmm#2770]
I want to run protein-ligand simulation in drude force field by using openmm. I get the parameters of protein and ligand in different ways so they are seperated. Is there any way to construct protein-ligand system by using openmm?

**Comment by jchodera** [comment]
You might want to investigate using [ParmEd](http://parmed.github.io/ParmEd/html/index.html), which has capabilities for [combining parts of parameterized systems](http://parmed.github.io/ParmEd/html/structure.html#structure-combining) and [converting to OpenMM](http://parmed.github.io/ParmEd/html/openmm.html).

**Comment by VincenzoChen** [comment]
Thank you! I have tried the ParmEd but it can't read the .psf file of protein and ligand which are used in Drude.

**Comment by jchodera** [comment]
Have you raised an issue there?
https://github.com/parmed/parmed/issues

Which specific files do you have and how did you generate them?

**Comment by VincenzoChen** [comment]
Yeah I have raised an issue.
I generate the .psf file of protein by charmm-gui and ligand by ffparam. The difference between the .psf file in drude and classic force fields is that in drude the file has special parameters shown as follow:
```
         5        20 !NUMLP NUMLPH
         3         1   F  -0.300000    180.000    180.000 
         3         5   F  -0.350000    110.000     90.000 
         3         9   F  -0.350000    110.000    270.000 
         3        13   F  -0.350000    110.000     90.000 
         3        17   F  -0.350000    110.000    270.000 
```
These parameters can't be recognized by parmed.

**Comment by VincenzoChen** [comment]
I have solved this problem by producing the complex .psf file directly by CHARMM. Thanks.
