### ISSUE TITLE
Possible inconsistencies between charmm36.xml and residues.xml

### ISSUE THREAD

**Issue by craabreu** [openmm/openmm#2777]
It seems that the connectivity of nucleic acid residues implied in `residues.xml` is inconsistent with the topologies in `charmm36.xml`. For instance, in the `ADE` residue the atoms `H2'` and `H2''` are linked to `O2'` and `C2'`, respectively, as we can see in the graph below (taken from the original `top_all36_na.rtf`file). This is correctly reproduced in `charmm36.xml`.

```
RESI ADE         -1.00  !             H61  H62!
ATOM P    P       1.50  !               \  /
ATOM O1P  ON3    -0.78  !                N6
ATOM O2P  ON3    -0.78  !                |
ATOM O5'  ON2    -0.57  !                C6
ATOM C5'  CN8B   -0.08  !              //  \
ATOM H5'  HN8     0.09  !              N1   C5--N7\\
ATOM H5'' HN8     0.09  !              |    ||     C8-H8
GROUP                   !              C2   C4--N9/
ATOM C4'  CN7     0.16  !             / \\ /     \
ATOM H4'  HN7     0.09  !           H2   N3       \
ATOM O4'  ON6B   -0.50  !                          \
ATOM C1'  CN7B    0.16  !                           \
ATOM H1'  HN7     0.09  !                            \
GROUP                   !        O1P    H5' H4'  O4'  \
ATOM N9   NN2    -0.05  !         |      |    \ /   \  \
ATOM C5   CN5     0.28  !        -P-O5'-C5'---C4'    C1'
ATOM N7   NN4    -0.71  !         |      |     \     / \
ATOM C8   CN4     0.34  !        O2P    H5''   C3'--C2' H1'
ATOM H8   HN3     0.12  !                     / \   / \
ATOM N1   NN3A   -0.74  !                  O3' H3' O2' H2''
ATOM C2   CN4     0.50  !                   |       |
ATOM H2   HN3     0.13  !                          H2'
```

```
BOND C2'  C3'       C2'  O2'       O2'  H2'       C3'  O3'       O3'  +P
BOND C1'  H1'       C2'  H2''      C3'  H3'       C4'  H4'       C5'  H5'
```

However, the file `residue.xml` contains the following information about residue `A`:

https://github.com/openmm/openmm/blob/ac5a8f7127656c1ca1679a8842dd93d64628699c/wrappers/python/simtk/openmm/app/data/residues.xml#L12

https://github.com/openmm/openmm/blob/ac5a8f7127656c1ca1679a8842dd93d64628699c/wrappers/python/simtk/openmm/app/data/residues.xml#L35

These aliases defined in `pdbNames.xml` do not seem to be able to solve the inconsistency:

https://github.com/openmm/openmm/blob/ac5a8f7127656c1ca1679a8842dd93d64628699c/wrappers/python/simtk/openmm/app/data/pdbNames.xml#L29

https://github.com/openmm/openmm/blob/ac5a8f7127656c1ca1679a8842dd93d64628699c/wrappers/python/simtk/openmm/app/data/pdbNames.xml#L34

Similar issues occur for other nucleic acid residues.

**Comment by craabreu** [comment]
I seize the opportunity to ask a related question. In the following patch (`DEOX`), the two bonds in `C2'--O2'--H2'` are removed, as well as the `O2'` atom. A new bond `C2'--H2'` should then be added. Why is this not explicitly stated in the patch?

```xml
    <Patch name="DEOX">
      <ChangeAtom charge="1.5" name="P" type="P2"/>
      <ChangeAtom charge="0.16" name="C4'" type="CN7"/>
      <ChangeAtom charge="0.09" name="H4'" type="HN7"/>
      <ChangeAtom charge="-0.5" name="O4'" type="ON6"/>
      <ChangeAtom charge="0.16" name="C1'" type="CN7B"/>
      <ChangeAtom charge="0.09" name="H1'" type="HN7"/>
      <ChangeAtom charge="-0.18" name="C2'" type="CN8"/>
      <ChangeAtom charge="0.09" name="H2'" type="HN8"/>
      <ChangeAtom charge="0.09" name="H2''" type="HN8"/>
      <RemoveAtom name="O2'"/>
      <RemoveBond atomName1="C2'" atomName2="O2'"/>
      <RemoveBond atomName1="O2'" atomName2="H2'"/>
    </Patch>
```

**Comment by peastman** [comment]
> or instance, in the ADE residue the atoms H2' and H2'' are linked to O2' and C2'

I think this is just a difference is the names of atoms.  residues.xml was generated from the PDB chemical components dictionary, so it's following the standard names.  You can see this by looking at ftp://ftp.wwpdb.org/pub/pdb/data/monomers/A:

```
CONECT      H2'    1 C2' 
CONECT      HO2'   1 O2' 
```

CHARMM is using nonstandard names, but that doesn't matter.  When looking for a template that matches a residue, all it cares about is the element of each atom and the bonds between them.  Atom names in the XML file are just for information.

**Comment by craabreu** [comment]
Thank you, @peastman.

FYI, I'm writing a code in [Julia](https://julialang.org/) to assign atom types based on graph isomorphism, for which I use the [Nauty](http://users.cecs.anu.edu.au/~bdm/nauty/) library and OpenMM's XML files. Basically, the code rearranges the residue templates in their canonical forms (seeing them as graphs with colored vertices, each chemical element being a different color). The same is done for the residues of a molecule retrieved from a PDB file. When two canonical forms match, I simply transfer the atom types from one to the other. This is quite simple. The method works fine with AMBER and also with CHARMM for proteins, but I'm struggling to correctly generate the templates and connect the atoms in nucleic acid molecules.

**Comment by peastman** [comment]
Was the second part of your question answered?  It's not clear to me either why that bond isn't added in the patch.
