### ISSUE TITLE
Problem with OpenCL when building from source

### ISSUE THREAD

**Issue by btamiller** [openmm/openmm#2785]
I'm building OpenMM version 7.4.2 from source in a Singularity container to be used with a CHARMM install in the same container. I need to have both the CUDA and OpenCL platforms available since CHARMM seems to want OpenCL available. However, although both platforms appear to build, only the CUDA platform is available at runtime within the container.

First here are the commands from the container definition file that I'm using to build:

```  
   cd /usr/src
   git clone https://github.com/openmm/openmm.git   
   cd openmm
   git checkout 7.4.2
   cd ..
   mkdir omm_build
   cd omm_build
   cmake -DOPENMM_BUILD_CUDA_LIB=ON -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda \
      -DCUDA_CUDART_LIBRARY=/usr/local/cuda/lib64/libcudart.so \
      -DCUDA_NVCC_EXECUTABLE=/usr/local/cuda/bin/nvcc \
      -DCUDA_INCLUDE_DIRS=/usr/local/cuda/include \
      -DCMAKE_LIBRARY_PATH=/usr/local/cuda/lib64/stubs \
      -DOPENMM_BUILD_OPENCL_LIB=ON \
      -DOPENCL_LIBRARY=/usr/local/cuda/lib64/libOpenCL.so \
      -DPYTHON_EXECUTABLE=/opt/conda/envs/openmm/bin/python /usr/src/openmm
   make -j4
   make install
```

These commands all complete successfully AFAICT, and looking at /usr/local/openmm/lib/plugins in the container, I see OpenCL plugin libraries:

```
Singularity> ls /usr/local/openmm/lib/plugins/
libOpenMMAmoebaCUDA.so       libOpenMMCUDA.so          libOpenMMDrudeOpenCL.so     libOpenMMPME.so         libOpenMMRPMDReference.so
libOpenMMAmoebaReference.so  libOpenMMCudaCompiler.so  libOpenMMDrudeReference.so  libOpenMMRPMDCUDA.so
libOpenMMCPU.so              libOpenMMDrudeCUDA.so     libOpenMMOpenCL.so          libOpenMMRPMDOpenCL.so
```

However, only the CUDA platform is detected:

```
Singularity> python -m simtk.testInstallation

OpenMM Version: 7.4.2
Git Revision: dc9d188939ad630d240e89806b185061f7cd661a

There are 3 Platforms available:

1 Reference - Successfully computed forces
2 CPU - Successfully computed forces
3 CUDA - Successfully computed forces

Median difference in forces between platforms:

Reference vs. CPU: 6.29961e-06
Reference vs. CUDA: 6.74647e-06
CPU vs. CUDA: 7.34369e-07

All differences are within tolerance.
```

I've looked at what plugins OpenMM finds and if it had an errors loading them, but nothing obvious strikes me:

```
Singularity> python -c "import simtk.openmm; print(simtk.openmm.Platform.getPluginLoadFailures())"
()
Singularity> python
Python 3.7.7 (default, May  7 2020, 21:25:33)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from simtk.openmm import *
>>> print(Platform.getDefaultPluginsDirectory())
/usr/local/openmm/lib/plugins
>>> print(version.openmm_library_path)
/usr/local/openmm/lib
>>> print(pluginLoadedLibNames)
('/usr/local/openmm/lib/plugins/libOpenMMCPU.so', '/usr/local/openmm/lib/plugins/libOpenMMPME.so', '/usr/local/openmm/lib/plugins/libOpenMMCUDA.so', '/usr/local/openmm/lib/plugins/libOpenMMOpenCL.so', '/usr/local/openmm/lib/plugins/libOpenMMRPMDCUDA.so', '/usr/local/openmm/lib/plugins/libOpenMMDrudeCUDA.so', '/usr/local/openmm/lib/plugins/libOpenMMAmoebaCUDA.so', '/usr/local/openmm/lib/plugins/libOpenMMRPMDOpenCL.so', '/usr/local/openmm/lib/plugins/libOpenMMDrudeOpenCL.so', '/usr/local/openmm/lib/plugins/libOpenMMCudaCompiler.so', '/usr/local/openmm/lib/plugins/libOpenMMRPMDReference.so', '/usr/local/openmm/lib/plugins/libOpenMMDrudeReference.so', '/usr/local/openmm/lib/plugins/libOpenMMAmoebaReference.so')
```

So, it looks to me like the OpenCL plugin is there and loaded correctly, but OpenMM cannot use it for some reason. I'm a bit of a newbie to OpenMM, but I couldn't find anything about this in the documentation. If there's something obvious that I'm missing, my apologies. I thought that perhaps the CUDA and OpenMM plugins might conflict, but I could not find anything about this in t he user level build documents. Again, if I missed something, my apologies and please point me in the right direction.

**Comment by peastman** [comment]
Most likely this means that OpenCL isn't available in the container.  OpenCL is based around a plugin architecture, just as OpenMM is.  Programs link to the library libOpenCL.so, but that's just a plugin loader.  Different vendors can install different implementations of OpenCL (called "platforms", not to be confused with OpenMM platforms).  At runtime, a program that uses OpenCL can look through the list of available platforms and select which one to use.

When OpenMM starts up and loads its OpenCL platform (in the OpenMM sense), it checks to see if any OpenCL platform is available (yes, the overlapping terminology gets confusing!).  If none is available, then it doesn't register the (OpenMM) OpenCL platform.

Take a look in `/etc/OpenCL/vendors`.  Are any files there?  If not then you don't have any OpenCL implementation installed.

**Comment by btamiller** [comment]
Aha - looks like I pulled the wrong docker container from Nvidia that does not have the correct OpenCL bits and pieces installed. I'll go ahead and fix this. Thanks very much for the insight - clearly thisis my first time dealing with OpenCL ... many thanks :-).

**Comment by peastman** [comment]
Glad it was that easy!
