### ISSUE TITLE
simulation.context.reinitialize problem

### ISSUE THREAD

**Issue by gitkol** [openmm/openmm#2787]
Hi,

I am having a problem with an OpenMM-PLUMED script that has always worked but after the OS on the cluster compute node had been upgraded from Ubuntu 16.04 to 18.04 it no longer works. Specifically, the problem is with this part of the code.
```
simulation.context.setVelocitiesToTemperature(10, randomSeed)
simulation.currentStep = 0
print('Equilibrating...')
simulation.step(steps1)
print('Done')

# inject DRR force
plumed_force_index = system.addForce(PlumedForce(plumed_force))
plumed = system.getForce(plumed_force_index)
plumed.setForceGroup(2)
simulation.context.reinitialize(preserveState=True)

print('Simulating...')
simulation.step(steps2)
print('Done')
```
The initial energy minimization and equilibration completes (everything is running fine on the GPU) but when I inject the PLUMED forces, which requires `simulation.context.reinitialize(preserveState=True)`, the simulation crashes as shown below.
```
Building system...
Performing flexible energy minimization...
Initial potential energy = -631235.0675860839 kJ/mol
Final potential energy   = -1175042.0822805255 kJ/mol
Time elapsed: 64.277045 seconds
Done
Building system...
[Quantity(value=Vec3(x=8.8029858, y=0.0, z=0.0), unit=nanometer), Quantity(value=Vec3(x=0.0, y=9.7951153, z=0.0), unit=nanometer), Quantity(value=Vec3(x=0.0, y=0.0, z=9.3774393), unit=nanometer)]
PME parameters used [2.9202898720871846, 80, 90, 84]
Equilibrating...
#"Step","Time (ps)","Potential Energy (kJ/mole)","Kinetic Energy (kJ/mole)","Temperature (K)","Speed (ns/day)","Elapsed Time (s)"
1000,8.000000000000005,-884394.4287517434,157103.72076580708,270.68759307319294,0,0.0005574226379394531
Done
Traceback (most recent call last):
  File "run-meta-eABF-path-CV.py", line 194, in <module>
    simulation.context.reinitialize(State=True)
  File "/home/istvan/anaconda3/lib/python3.7/site-packages/simtk/openmm/openmm.py", line 18471, in reinitialize
    return _openmm.Context_reinitialize(self, preserveState)
Exception: Specified a Platform for a Context which does not support all required kernels
Segmentation fault (core dumped)
```
Since this script has always worked before, I have no idea where to start debugging this. I am using the conda install of OpenMM 7.4.1 with CUDA 10.0. Do you have a suggestion where to look?

Thank you very much for your kinds assistance,

   Istvan

**Comment by peastman** [comment]
Most likely this means a plugin isn't getting loaded, and most likely that's because of a library linking error.  Try printing out `Platform.getPluginLoadFailures()`.  That will report any plugins that failed to load, and hopefully a useful error message for each one.  If you identify a particular plugin that isn't loading, you also can try running `ldd` on it to see if it depends on any libraries that couldn't be found.

**Comment by gitkol** [comment]
Thanks Peter, this is very helpful. It seems that

libboost_serialization.so.1.58.0

is missing, I'll ask the admin to install it.

Thanks again,

   Istvan

**Comment by peastman** [comment]
Closing this since the issue has been resolved.
