### ISSUE TITLE
openmmtorch `TorchForce` as `CustomForce` object

### ISSUE THREAD

**Issue by dominicrufa** [openmm/openmm#2788]
could the pytorch plugin force for openmm be reconfigured such that it can take global variables like the other `CustomForce` objects? (specifically, so the `forward` function in the `nn.Module` subclass can take a global variable).

similarly, would it be possible to create a `TorchForce` that isn't strictly loadable from a '.pt' file? (i.e. create a `nn.Module` subclass and load it directly in to a `TorchForce` without saving to disk? ) i ask this because i would like to be able to change some model parameters of the torch force between integration steps. i suppose this would require also making the `nn.Module` subclass _extractable_ from the `TorchForce`.

**Comment by peastman** [comment]
The first one should be straightforward.  Does the following sound like what you have in mind?

- You can define global parameters by calling `addGlobalParameter()`, just as you would with other custom forces.
- The values of the parameters are passed to `forward()` as additional arguments.
- This would only support real scalar values, not tensors.
- The values of parameters can be changed at any time by calling `setParameter()` on the Context, just as with other custom forces.

The second one sounds a lot more complicated.  To begin with it requires passing objects directly from Python to C++.  And then, if I understand correctly, you want to be able to modify the model midway through a simulation?  Leaving aside the C++ issues, is it even possible to modify a model that has been compiled to TorchScript?

**Comment by jchodera** [comment]
We've also been discussing creating an `ANIForce`, but should probably discuss that in a separate issue. Which scheme would be most useful to you first, @dominicrufa ?

**Comment by dominicrufa** [comment]
i think resolving the first three points you mentioned would be more than sufficient for what i had in mind! i suggested (and might have gone overboard with) the last point (4) because it would allow for a _lot_ of flexibility with the openmm torch plugin that we (I) want to pursue in the future. ultimately, i think that supporting a tensor (of real values) to modify the `nn.Module` subclass in place would be the ultimate goal, but i don't really have a grasp on the level of code manipulation involved in making that last bit doable.

**Comment by peastman** [comment]
We have a lot of existing infrastructure for dealing with scalars as global variables.  For example, they can be stored in a Context.  They can be saved and restored with States and Checkpoints.  They can be shared between Forces.  They can be modified by a CustomIntegrator.  If we use the existing mechanism, you get all of that for free.  But there's no corresponding infrastructure for tensors.  So either we would have to make major changes to the core library, or else you wouldn't get any of those features.

**Comment by dominicrufa** [comment]
i think that supporting scalars as global vars for the torch plugin would be great and allow for a lot of flexibility. if this is doable in the shorter term, i think we could get a lot of mileage out of it.

**Comment by peastman** [comment]
@dominicrufa this is implemented in https://github.com/openmm/openmm-torch/pull/18.  Can you try it out and see if it works for you?

**Comment by dominicrufa** [comment]
@peastman , i can give it a go. is there a code snippet somewhere that demonstrates how i can create a torch force object and scale it by a global parameter?

**Comment by peastman** [comment]
The PR includes additions to the README that explain how to do it.

**Comment by dominicrufa** [comment]
ah, this is very well-explained; however, I am having some trouble with the installation. i am able to install libtorch with its associated instructions, but i'm having some problems with the cmake gui steps and configuring variables appropriately to generate. (i am using ccmake, by the way)
once i try `make install`, i see.

```
Scanning dependencies of target OpenMMTorch
[  7%] Building CXX object CMakeFiles/OpenMMTorch.dir/openmmapi/src/TorchForce.cpp.o
In file included from /mnt/c/Users/domin/github/openmm-torch/openmmapi/src/TorchForce.cpp:32:0:
/mnt/c/Users/domin/github/openmm-torch/openmmapi/include/TorchForce.h:35:10: fatal error: openmm/Context.h: No such file or directory
 #include "openmm/Context.h"
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/OpenMMTorch.dir/build.make:62: recipe for target 'CMakeFiles/OpenMMTorch.dir/openmmapi/src/TorchForce.cpp.o' failed
make[2]: *** [CMakeFiles/OpenMMTorch.dir/openmmapi/src/TorchForce.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/OpenMMTorch.dir/all' failed
make[1]: *** [CMakeFiles/OpenMMTorch.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
```
i figure there is something obvious that i am doing wrong, but i can't figure out what. is it possible that you could walk me through the installation?

**Comment by peastman** [comment]
That suggests you have `OPENMM_DIR` set incorrectly.  It needs to point to the directory where OpenMM is installed.  On my computer that's /usr/local/openmm, but you might have installed it somewhere different.  The directory will have `include` and `lib` subdirectories containing the headers and libraries.

**Comment by dominicrufa** [comment]
if i conda-forge installed openmm, where would that path be? in my `anaconda3/lib/python3.6/site-packages/simtk/openmm` dir, there aren't any `include` or `lib` subdirs

**Comment by jchodera** [comment]
@peastman @jaimergp : We should definitely make it easier to build plugins by packaging everything needed to build them in the `openmm` conda package if we're not doing that already.

**Comment by peastman** [comment]
Execute this code.

```python
from simtk.openmm import *
print(version.openmm_library_path)
```

That prints out the location of the lib directory.  Its parent directory is what `OPENMM_DIR` should point to.

(I should add this to the documentation!)

**Comment by jaimergp** [comment]
> @peastman @jaimergp : We should definitely make it easier to build plugins by packaging everything needed to build them in the `openmm` conda package if we're not doing that already.

It's usually `$CONDA_PREFIX` (the root of the conda env). The `lib` and `include` directories are there.

**Comment by jaimergp** [comment]
Btw, `pytorch` is now on `conda-forge` too (with GPU), so there's a chance we can build the plugin there, provided the libraries needed are packaged too. If they aren't, we can ask for them to be included as well, hopefully in a ABI-compatible way.

**Comment by jchodera** [comment]
> Btw, pytorch is now on conda-forge too (with GPU)

Awesome!

**Comment by peastman** [comment]
Have you had a chance to try it out?  I'd like to get it merged.

**Comment by dominicrufa** [comment]
i dont want to be the blocking here. i can try it this weekend, but since @jaimergp has an artifact, it might be safe to merge and we can test the artifact?

**Comment by peastman** [comment]
Can you look over the API first and make sure at least that looks OK for your purposes?

**Comment by dominicrufa** [comment]
it looks great! this may be a bell (or whistle), but would it be possible to take the derivative w.r.t. the scale factor that is passed to the torch force? as in [here](http://docs.openmm.org/7.1.0/api-python/generated/simtk.openmm.openmm.CustomNonbondedForce.html#simtk.openmm.openmm.CustomNonbondedForce.addEnergyParameterDerivative)?

**Comment by peastman** [comment]
I think so.  How high a priority is that?

I'll merge the PR, but keep this issue open for adding the derivatives.

**Comment by dominicrufa** [comment]
not a high priority right now. thanks!

**Comment by jchodera** [comment]
This was implemented in https://github.com/openmm/openmm-torch/pull/29
