### ISSUE TITLE
Setting periodic box origin (trouble wrapping)

### ISSUE THREAD

**Issue by ajasja** [openmm/openmm#2791]
Is it possible to set the periodic box origin?

I have made a solvated box using [this script](https://gist.github.com/ajasja/a7e3d6498e5471f430ab7428b30f4e3a).

The periodic box vectors are
`(Vec3(x=13.765799999999999, y=0.0, z=0.0), Vec3(x=0.0, y=13.0535, z=0.0), Vec3(x=0.0, y=0.0, z=6.126)) nm`
and the box looks OK.

![image](https://user-images.githubusercontent.com/19926/88852512-39ee1480-d1a3-11ea-8592-4999c569a3a0.png)
However as soon as I started the minimization/equilibration the box wrapped. 

![image](https://user-images.githubusercontent.com/19926/88852587-5722e300-d1a3-11ea-98f9-9ce1dfdbb10e.png)

What is the best way to handle this? 
In NAMD I would just move the origin of the periodic box. I guess I could move all the other atoms in the system instead.

Script used to run
```python
    topology = pdb.topology
    print(topology.getPeriodicBoxVectors())
    print(topology.getUnitCellDimensions()) 
    system = forcefield.createSystem(topology, nonbondedMethod=nonbondedMethod, nonbondedCutoff=nonbondedCutoff,
        constraints=constraints, rigidWater=rigidWater, ewaldErrorTolerance=ewaldErrorTolerance, switchDistance=0.8*nanometer)
    system.addForce(MonteCarloBarostat(pressure, temperature, barostatInterval))
    integrator = LangevinIntegrator(temperature, friction, dt)
    integrator.setConstraintTolerance(constraintTolerance)
    simulation = Simulation(topology, system, integrator, platform=platform, platformProperties=platformProperties)
    #simulation = Simulation(topology, system, integrator, platform, platformProperties)
    simulation.context.setPositions(positions)
```

**Comment by peastman** [comment]
Take a look at https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#periodic.  It discusses how periodic boundary conditions work and what's going on here.  This is just a visualization issue and doesn't affect the simulation.  You can use tools like MDTraj and Cpptraj to put the output into a form that's more convenient for visualization.

**Comment by ajasja** [comment]
Thanks, super useful FAQ! It did not come up in any of the google searches I tried (`OpenMM periodic box`, `OpenMM wrapping trajectory`, etc../).

I'll try the recommended [image_molecules].(http://mdtraj.org/development/api/generated/mdtraj.Trajectory.html#mdtraj.Trajectory.image_molecules)
I know it's just an visualization issue, but visual images are important:)
