### ISSUE TITLE
Slow implicit solvent (GB) performance when building from parmtop files

### ISSUE THREAD

**Issue by ajasja** [openmm/openmm#2796]
For a system with about 16000 atoms I get about 91 ns/day on a GTX1080Ti with a 2fs timestep.
I construct the system using

```python
        pdb = PDBFile(input_pdb)
        forcefield = ForceField('amber99sb.xml', 'amber99_obc.xml')
```

If however I make the file using tleap and then try the GBn2 implicit forcefield I get about 7 ns/day.

```python
            amberSys    = AmberPrmtopFile(input_top)
            topology    = amberSys.topology
            positions   = PDBFile(input_pdb).positions

            system = amberSys.createSystem(nonbondedMethod=nonbondedMethod, nonbondedCutoff=nonbondedCutoff,
                constraints=constraints, rigidWater=True,  implicitSolvent=solv_map[args.solvent], implicitSolventSaltConc=args.salt*moles/liter)      
```
Is this expected? If not I guess making minimal running example is the next step.

**Comment by peastman** [comment]
An example would be great.  You're comparing two different solvent models (OBC and GBn2), so some speed difference is expected, but not nearly that much.  Make sure everything else is the same, for example that you aren't using a cutoff on one but not the other, or that you aren't using CUDA for one and CPU for the other.

**Comment by ajasja** [comment]
Here are the results (and the attached min example)

**The OBC gives**
```bash
$ python 01_test_obc.py 
Building system...
Using 16290 atoms.
Done in 5.40 s.

Equilibrating for 5000 steps...
Done in 10.00 s.

Running 86.38 ns/day
```

**The Gbn2 gives**
```bash
$ python 02_test_gbn2.py 
Building system...
Using 16290 atoms.
Done in 2.75 s.

Equilibrating for 5000 steps...
Done in 12.53 s.

Running 68.94 ns/day
```
I guess this is really good news!

I must be missing something in my "production" code. Will investigate and close this tomorrow if I don't find anything.

**Comment by ajasja** [comment]
`dcdReporter = DCDReporter(f'{out_base}__{suffix}_{part_num:02d}.dcd', runSteps//1000)`

It was the reporters! I set the interval to runSteps//1000, since I wanted a 1000 frames for 100ns. But when benchmarking I only ran for 5000 steps, so it was writing every five steps.

**Comment by peastman** [comment]
That would do it!
