### ISSUE TITLE
ARM builds are timing out

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#2797]
See https://travis-ci.org/github/openmm/openmm/jobs/713399757

Specifically, timeout messages like [this one](https://travis-ci.org/github/openmm/openmm/jobs/713399757#L7097-L7102):
```
TestDesmondDMSFile.py::TestDesmondDMSFile::test_RemoveCMMotion PASSED    [ 33%]
TestElement.py::TestElement:
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
The build has been terminated
```

**Comment by peastman** [comment]
About half the time it passes and half the time it times out.  Possibly the thing to do is just turn off running the Python tests on ARM.

**Comment by jchodera** [comment]
Is it that the operation that is running is just silent for a long time? If so, could we have it output more debug output?

If something is getting stuck, that is a concern that there is some sort of race condition, isn't it?

**Comment by peastman** [comment]
> Is it that the operation that is running is just silent for a long time? If so, could we have it output more debug output?

My impression is that the output is getting buffered.  It goes for a while without anything appearing, and then a bunch of lines of output appear all at once.

**Comment by jchodera** [comment]
Ah! There's a simple solution for that then---turn off buffering and don't capture output.
Example: https://github.com/pytest-dev/pytest/issues/1886#issuecomment-549145520

**Comment by peastman** [comment]
Closing since we're moving away from travis.
