### ISSUE TITLE
CUDA platform error

### ISSUE THREAD

**Issue by mrinal-shekhar** [openmm/openmm#2798]
Hi 
I had installed OpenMM 7.4.2 on my workstation using Conda. Upon running the following command: python -m simtk.testInstallation, it recognizes all 4 platforms. However i get the following error: 

OpenMM Version: 7.4.2
Git Revision: dc9d188939ad630d240e89806b185061f7cd661a

There are 4 Platforms available:

1 Reference - Successfully computed forces
2 CPU - Successfully computed forces
3 CUDA - Error computing forces with CUDA platform
4 OpenCL - Error computing forces with OpenCL platform

CUDA platform error: No compatible CUDA device is available

OpenCL platform error: Error initializing context: clCreateContext (-33)

Median difference in forces between platforms:

Reference vs. CPU: 6.29793e-06

Upon doing nvidia-smi, i can see my gpus and i have CUDA 10.2 installed.
Please help
Mrinal

**Comment by peastman** [comment]
What version of CUDA do you have?

What GPU do you have?

What OS are you running?

Can you post the output of both `nvidia-smi` and `clinfo`?

**Comment by mrinal-shekhar** [comment]
Hi Peter
My workstation uses CUDA 10.2, GPU is GeForce GTX 1080 Ti  and OS is Ubuntu 18.04.4 LTS. 
I am attaching the output of nvidia-smi
![nvidia](https://user-images.githubusercontent.com/40069534/89585278-925c8c00-d80b-11ea-8a73-cb0098de52bf.png)

**Comment by mrinal-shekhar** [comment]
I am also attaching the output from clinfo
![clinfo1](https://user-images.githubusercontent.com/40069534/89585837-950bb100-d80c-11ea-859a-abaa050f938e.png)
![clinfo2](https://user-images.githubusercontent.com/40069534/89585840-95a44780-d80c-11ea-99b6-ed640dd52e88.png)
![clinfo3](https://user-images.githubusercontent.com/40069534/89585843-963cde00-d80c-11ea-9f8b-c0f5492d0a49.png)
![clinfo4](https://user-images.githubusercontent.com/40069534/89585844-963cde00-d80c-11ea-89bc-a04c191061c8.png)
![clinfo5](https://user-images.githubusercontent.com/40069534/89585846-96d57480-d80c-11ea-8e56-8397706a401f.png)
![clinfo6](https://user-images.githubusercontent.com/40069534/89585849-976e0b00-d80c-11ea-8014-866ff6675571.png)
![clinfo7](https://user-images.githubusercontent.com/40069534/89585850-9806a180-d80c-11ea-8f56-a49a9c13018d.png)

**Comment by peastman** [comment]
Try quitting VMD.  You can see from nvidia-smi that the GPUs are all in "exclusive process" mode.  That means that only one process is allowed to create a CUDA context on each one at a time.  You can also see that VMD already has processes using all four of them for compute (type "C").  While it's running, no other process can use them.

**Comment by mrinal-shekhar** [comment]
Thanks this seemed to work. 
Mrinal

**Comment by peastman** [comment]
Great!
