### ISSUE TITLE
Typo in forcefield.py: 2DFunction used instead of 3DFunction

### ISSUE THREAD

**Issue by Dann239** [openmm/openmm#2799]
There is a typo in forcefield.py:
https://github.com/openmm/openmm/blob/cc3c4b54305fd53b535ddf26df15d9e1bb903e47/wrappers/python/simtk/openmm/app/forcefield.py#L117-L128
Should be `Continuous3DFunction`, not `Continuous2DFunction`

Same thing a few lines later:
https://github.com/openmm/openmm/blob/cc3c4b54305fd53b535ddf26df15d9e1bb903e47/wrappers/python/simtk/openmm/app/forcefield.py#L133-L134
Should be `Discrete3DFunction`, not `Discrete2DFunction`

**Comment by Dann239** [comment]
Created a pull request: #2800

**Comment by peastman** [comment]
Fixed by #2800.
