### ISSUE TITLE
Problem with Platform_getPlatformByName

### ISSUE THREAD

**Issue by dacase** [openmm/openmm#2808]
I've installed openmm via the conda package.  On some machines with GPUs everything "just works", including the following:
```
(openmm) pop-os% python
Python 3.7.8 | packaged by conda-forge | (default, Jul 31 2020, 02:25:08) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from simtk import openmm
>>> openmm.Platform.getPlatformByName('CUDA')
<simtk.openmm.openmm.Platform; proxy of <Swig Object of type 'OpenMM::Platform *' at 0x7fdf8c78f750> >
```

But on other machines, the same call fails to find a registered Platform:
```
>>> openmm.Platform.getPlatformByName('CUDA')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/case/miniconda/envs/openmm/lib/python3.7/site-packages/simtk/openmm/openmm.py", line 17865, in getPlatformByName
    return _openmm.Platform_getPlatformByName(name)
Exception: There is no registered Platform called "CUDA"
```

I didn't do anything (that I'm aware of) on the first machine to register the platform.  One difference is that the first machine (that works) has only a single GPU, whereas the second has several -- could that be making a difference?

I see methods like `findPlatform` and `registerPlatform`, but am hoping for a good pointer to how I should use them, or to do whatever is needed.

...thanks!....dave case

**Comment by peastman** [comment]
The platform automatically gets registered when the CUDA plugin gets loaded.  If that doesn't happen, it suggests the plugin isn't able to get loaded.  Try printing out `Platform.getPluginLoadFailures()`.  It lists any plugins that couldn't get loaded and, with luck, a helpful error message about why.

Most often this indicates a problem linking to another library.  Do you have the CUDA toolkit's `lib64` directory in your library path?

**Comment by dacase** [comment]
Thanks for your quick reply.  Knowing about `getPluginLoadFailures()` was actually quite helpful.  But I have egg on my face -- my CUDA SDK version was not in sync with my openmm version.  So it was all just user error; but the loadFailures made that pretty obvious, so thanks again.

**Comment by jchodera** [comment]
@dacase: We are pretty close to being able to distribute OpenMM via conda-forge where it will automatically grab the right cudatoolkit for you! Hopefully this will eliminate this issue---I know I've been burned by it many times myself!
