### ISSUE TITLE
convert the force field (get from openmm) and topology into lammps.data?

### ISSUE THREAD

**Issue by lifewadwdv** [openmm/openmm#2810]
After get the force parameters, i want to convert the force coeffs and topology into the input files of **LAMMPS**(data files), does the openmm package have this function now?
```python
pdb = PDBFile('input.pdb')
forcefield = ForceField('charmm/ffxml/charmm36.xml')
system = forcefield.createSystem(pdb.topology)
```

**Comment by peastman** [comment]
No, OpenMM doesn't write LAMMPS files.  Sorry!
