### ISSUE TITLE
ImportError for  import openmm

### ISSUE THREAD

**Issue by RobinEllison** [openmm/openmm#2811]
I compile OpenMM (commit:cdc0789) from Source Code, recommended by the guide in "Chapter 8 Compiling OpenMM from Source Code"[http://docs.openmm.org/latest/userguide/library.html#compiling-openmm-from-source-code](url). 
`from simtk.openmm import *`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zhangcw/app/anaconda3/envs/dna/lib/python3.7/site-packages/simtk/openmm/__init__.py", line 19, in <module>
    from simtk.openmm.openmm import *
  File "/home/zhangcw/app/anaconda3/envs/dna/lib/python3.7/site-packages/simtk/openmm/openmm.py", line 28, in <module>
    _openmm = swig_import_helper()
  File "/home/zhangcw/app/anaconda3/envs/dna/lib/python3.7/site-packages/simtk/openmm/openmm.py", line 24, in swig_import_helper
    _mod = imp.load_module('_openmm', fp, pathname, description)
  File "/home/zhangcw/app/anaconda3/envs/dna/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/zhangcw/app/anaconda3/envs/dna/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /home/zhangcw/app/anaconda3/envs/dna/lib/python3.7/site-packages/simtk/openmm/_openmm.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZTIN6OpenMM15DrudeIntegratorE

I don't know why i get this error.  
Info about my os
python 3.7
gcc 5.4
cuda  release 10.1, V10.1.105

**Comment by peastman** [comment]
What location did you install OpenMM to?  Make sure you added the `lib` directory to your library path.

If that doesn't fix it, could you post the output of this command?

```
ldd /home/zhangcw/app/anaconda3/envs/dna/lib/python3.7/site-packages/simtk/openmm/_openmm.cpython-37m-x86_64-linux-gnu.so
```

**Comment by RobinEllison** [comment]
OpenMM was installed to /usr/local/openmm.
Following your suggestion:
First
`echo $LD_LIBRARY_PATH`
"/usr/local/openmm/lib:/usr/local/cuda-10.1/lib64:/usr/local/lib/vmd"

Next
`ldd /home/zhangcw/app/anaconda3/envs/dna/lib/python3.7/site-packages/simtk/openmm/_openmm.cpython-37m-x86_64-linux-gnu.so`
"	linux-vdso.so.1 =>  (0x00007fffe0948000)
	libOpenMM.so => /home/zhangcw/app/anaconda3/envs/dna/lib/libOpenMM.so (0x00007fd3331b6000)
	libOpenMMAmoeba.so => /home/zhangcw/app/anaconda3/envs/dna/lib/libOpenMMAmoeba.so (0x00007fd332f2a000)
	libOpenMMRPMD.so => /home/zhangcw/app/anaconda3/envs/dna/lib/libOpenMMRPMD.so (0x00007fd332d1c000)
	libOpenMMDrude.so => /home/zhangcw/app/anaconda3/envs/dna/lib/libOpenMMDrude.so (0x00007fd332b0a000)
	libstdc++.so.6 => /home/zhangcw/app/anaconda3/envs/dna/lib/libstdc++.so.6 (0x00007fd333a9d000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fd332801000)
	libgcc_s.so.1 => /home/zhangcw/app/anaconda3/envs/dna/lib/libgcc_s.so.1 (0x00007fd333a63000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fd3325e4000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd33221a000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fd332012000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fd331e0e000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fd3339ee000)
"

**Comment by peastman** [comment]
Did you ever resolve this issue?

Looking at the output above, it looks like there's some inconsistency between paths.  The libraries are all in `/home/zhangcw/app/anaconda3/envs/dna/lib`, but you instead added `/usr/local/openmm/lib` to `LD_LIBRARY_PATH`.

**Comment by RobinEllison** [comment]
@peastman  I am sorry for replying lately. I mixed the environment of OS/Conda. I resolved this issue by reinstalling OpenMM under my Conda environment.

**Comment by peastman** [comment]
Glad you figured it out!
