### ISSUE TITLE
Tiny error when parse psf files.

### ISSUE THREAD

**Issue by RobinEllison** [openmm/openmm#2815]
I found a tiny error when use app.CharmmPsfFile() to parse psf files
for example:
```
from simtk.openmm import app
psf = app.CharmmPsfFile('example.psf')
print(len(psf.residue_list))
print(len(psf.atom_list))
```
output the same number

` elif (lr.resname != resname or lr.idx != resname or` (line 535 in simtk/openmm/app/internal/charmm/topologyobjects.py) 
replaced by
` elif (lr.resname != resname or lr.idx != resnum or`
May fix this problem

**Comment by peastman** [comment]
Thanks!
