### ISSUE TITLE
OpenCL platform breaks on AMD GPUs

### ISSUE THREAD

**Issue by Dann239** [openmm/openmm#2817]
This issue is the continuation of #2805. I'm going to recap what happened there. The initial topic of that issue was overflows on high amounts of atoms, but later another bug has been found, which i'm going to describe here.

I've made a simple C++ program that generates a simple configuration of atoms, applies `NonbondedForce` and computes forces and energy using two different platforms and counts ones whose difference is more than `eps` and uses binary search to pinpoint where such errors are happening:
```cpp
#include <vector>
#include <iostream>
#include <cstdio>
#include <cmath>
#include <map>
#include <string>
#include "OpenMM.h"

double len(const OpenMM::Vec3& v) {
    return sqrt(v.dot(v));
}
double gen_rand(double max) {
    return rand() * max / RAND_MAX;
}
std::map<std::string, std::string> get_properties(std::string platform) {
    if(platform == "CUDA")
        return {{"Precision", "double"}, {"DeterministicForces", "true"}};
    else if(platform == "OpenCL")
        return {{"Precision", "double"}, {"OpenCLPlatformIndex", "0"}};
    else
        return {};
}
int lj(int amount, std::string platform1, std::string platform2, double eps) {
    double size = cbrt(amount) + 2;

    std::vector<OpenMM::Vec3> pos(amount);

    // this generates some configuration of particles. what exactly happens here is ultimately unimportant
    int grid_dim = size;
    std::vector<std::vector<std::vector<int>>> grid(grid_dim,
        std::vector<std::vector<int>>(grid_dim,
        std::vector<int>(grid_dim, 0)));
    srand(0);
    for(auto& p : pos) {
        int* occ = nullptr;
        do {
            int grid_pos[3] = {
                rand() % grid_dim,
                rand() % grid_dim,
                rand() % grid_dim};
            p = {
                static_cast<double>(grid_pos[0]) + gen_rand(0.1),
                static_cast<double>(grid_pos[1]) + gen_rand(0.1),
                static_cast<double>(grid_pos[2]) + gen_rand(0.1)
            };
            occ = &grid[grid_pos[0]][grid_pos[1]][grid_pos[2]];
        } while(*occ);
        *occ = 1;
    }
    // end of the unimportant part

    OpenMM::System sys;
    sys.setDefaultPeriodicBoxVectors(
        {size, 0, 0},
        {0, size, 0},
        {0, 0, size}
    );

    // i create a simple nonbondedforce. lj units are used here for convenience
    auto lj = new OpenMM::NonbondedForce();
    lj->setNonbondedMethod(OpenMM::NonbondedForce::CutoffPeriodic);
    lj->setUseSwitchingFunction(true);
    lj->setSwitchingDistance(2);
    lj->setCutoffDistance(4);
    for(int i = 0; i < amount; i++) {
        lj->addParticle(0, 1, 1);
        sys.addParticle(1);
    }
    sys.addForce(lj);

    //compute forces
    OpenMM::VerletIntegrator verlet1(0.01);
    auto context1 = new OpenMM::Context(sys, verlet1, OpenMM::Platform::getPlatformByName(platform1), get_properties(platform1));
    context1->setPositions(pos);
    context1->setVelocitiesToTemperature(1, 0);
    double energy1 = context1->getState(OpenMM::State::Energy).getPotentialEnergy();
    auto forces1 = context1->getState(OpenMM::State::Forces).getForces();
    delete context1;

    // compute forces in the exact same system a different platform
    OpenMM::VerletIntegrator verlet2(0.01);
    auto context2 = new OpenMM::Context(sys, verlet2, OpenMM::Platform::getPlatformByName(platform2), get_properties(platform2));
    context2->setPositions(pos);
    context2->setVelocitiesToTemperature(1, 0);
    double energy2 = context2->getState(OpenMM::State::Energy).getPotentialEnergy();
    auto forces2 = context2->getState(OpenMM::State::Forces).getForces();
    delete context2;

    //count how many forces differ
    int energy_badness = abs(energy1 - energy2) > eps;
    int badness = 0;
    for(int i = 0; i < amount; i++)
        if(len(forces1[i] - forces2[i]) > eps)
            badness++;

    std::cout << std::defaultfloat << platform1 << " VS " << platform2 << ": eps = " << eps << ", " << amount << " atoms: " << badness << " errors";
    std::cout << ". energy is " << (energy_badness ? "bad" : "good");
    std::cout << std::endl;

    return badness + energy_badness;
}

int main(int argc, char* argv[]) { // args: amount, platform1, platform2, eps
    std::string plugins_dir = OpenMM::Platform::getDefaultPluginsDirectory();
    OpenMM::Platform::loadPluginsFromDirectory(plugins_dir);


    if(argc > 4) {
        lj(std::stoi(argv[1]), argv[2], argv[3], std::stod(argv[4]));
        return 0;
    }
    double eps = 1e-6;
    std::string p1 = "OpenCL", p2 = "Reference";
    int l = 0, r = 3000000;
    while(r - l > 1) {
        int m = (l + r) / 2;
        int b = lj(m, p1, p2, eps);
        if(b == 0)
            l = m;
        else
            r = m;
    }
    lj(l, p1, p2, eps);
    lj(r, p1, p2, eps);
}
```
Unless specified otherwise, double precision was used for testing:
```
Specs:
  CUDA: TITAN V
  OpenCL: Radeon gfx906 Vega 20
  OS: Ubuntu 18.04.2
  Driver: ROCm 3.3

OpenCL VS CUDA: eps = 1e-08, 1000000 atoms: 0 errors
OpenCL VS CUDA: eps = 1e-08, 2000000 atoms: 0 errors
OpenCL VS CUDA: eps = 1e-08, 3000000 atoms: 1050777 errors
OpenCL VS CUDA: eps = 1e-08, 4000000 atoms: 2060981 errors
OpenCL VS CUDA: eps = 1e-08, 5000000 atoms: 3102126 errors
OpenCL VS CUDA: eps = 1e-08, 6000000 atoms: 4150716 errors
OpenCL VS CUDA: eps = 1e-08, 7000000 atoms: 5169910 errors
OpenCL VS CUDA: eps = 1e-08, 8000000 atoms: 6158807 errors
OpenCL VS CUDA: eps = 1e-08, 9000000 atoms: 7179812 errors
OpenCL VS CUDA: eps = 1e-08, 10000000 atoms: 8180822 errors
OpenCL VS CUDA: eps = 1e-08, 11000000 atoms: 9188662 errors
OpenCL VS CUDA: eps = 1e-08, 12000000 atoms: 10191756 errors
OpenCL VS CUDA: eps = 1e-08, 13000000 atoms: 11204010 errors
OpenCL VS CUDA: eps = 1e-08, 14000000 atoms: 12198030 errors
OpenCL VS CUDA: eps = 1e-08, 15000000 atoms: 13197902 errors
```
I'm testing against CUDA here because it replicates Reference with sufficient precision but works a few orders of magnitude faster.

After employing binary search, i've narrowed down the issue to about 2^21 atoms. However, weird behavior always starts slightly before the number reaches exactly 2097152.
```
Specs:
  CUDA: TITAN V
  OpenCL: Radeon gfx906 Vega 20
  OS: Ubuntu 18.04.2
  Driver: ROCm 3.3

OpenCL VS CUDA: eps = 1e-06, 2097500 atoms: 2472 errors. energy is bad
OpenCL VS CUDA: eps = 1e-06, 2097250 atoms: 1035 errors. energy is bad
OpenCL VS CUDA: eps = 1e-06, 2097125 atoms: 0 errors. energy is good
OpenCL VS CUDA: eps = 1e-06, 2097187 atoms: 935 errors. energy is bad
OpenCL VS CUDA: eps = 1e-06, 2097156 atoms: 362 errors. energy is bad
OpenCL VS CUDA: eps = 1e-06, 2097140 atoms: 0 errors. energy is good
OpenCL VS CUDA: eps = 1e-06, 2097148 atoms: 7 errors. energy is good
OpenCL VS CUDA: eps = 1e-06, 2097144 atoms: 214 errors. energy is bad
OpenCL VS CUDA: eps = 1e-06, 2097142 atoms: 0 errors. energy is good
OpenCL VS CUDA: eps = 1e-06, 2097143 atoms: 135 errors. energy is bad
OpenCL VS CUDA: eps = 1e-06, 2097142 atoms: 117 errors. energy is bad
OpenCL VS CUDA: eps = 1e-06, 2097143 atoms: 0 errors. energy is good
```

I also reproduced it on a different device
```
Specs:
  OpenCL: AMD FirePro S9150
  OS: SLES11
  Driver: AMDGPU-PRO

OpenCL VS Reference: eps = 1e-08, 2097500 atoms: 2521 errors. energy is good
OpenCL VS Reference: eps = 1e-08, 2097250 atoms: 1353 errors. energy is good
OpenCL VS Reference: eps = 1e-08, 2097125 atoms: 0 errors. energy is good
OpenCL VS Reference: eps = 1e-08, 2097187 atoms: 248 errors. energy is bad
OpenCL VS Reference: eps = 1e-08, 2097156 atoms: 696 errors. energy is bad
OpenCL VS Reference: eps = 1e-08, 2097140 atoms: 0 errors. energy is good
OpenCL VS Reference: eps = 1e-08, 2097148 atoms: 155 errors. energy is bad
OpenCL VS Reference: eps = 1e-08, 2097144 atoms: 246 errors. energy is bad
OpenCL VS Reference: eps = 1e-08, 2097142 atoms: 0 errors. energy is good
OpenCL VS Reference: eps = 1e-08, 2097143 atoms: 0 errors. energy is good
OpenCL VS Reference: eps = 1e-08, 2097143 atoms: 0 errors. energy is good
OpenCL VS Reference: eps = 1e-08, 2097144 atoms: 0 errors. energy is good
```

I also (as per @peastman's suggestion) printed out some of the forces that disagree.
Here are some examples at `eps = 1e-08, 2100000 atoms`:
```
(52.51402703; -20.36511698; 19.77343340) vs (61.50966446; -24.43923722; 31.88184289)
(69.96141767; -61.16939664; -11.47831811) vs (71.62729306; -59.26220552; -11.16672110)
(10.81719569; 26.03645921; -15.18058281) vs (10.83498777; 26.01710816; -15.18422344)
(88.88560223; -25.37994582; -1.70660083) vs (88.88548036; -25.38000594; -1.70678536)
(10.29704808; 97.82318720; 16.34285352) vs (13.50166716; 110.81853326; 15.61235474)
```
Forces don't exceed 100 and differ in about 1st to 6th significant digit. However, at `eps = 1, 15000000 atoms` forces don't agree at all:
```
(-18.48210491; -7.41743184; 7.23708934) vs (13.62239267; -11.50955888; -2.16335091)
(32.67631737; 8.55291197; 47.86459162) vs (5.41072362; 24.17102462; 47.45160939)
(30.15783009; -0.77365225; -35.74712786) vs (39.00532932; 41.62868227; 9.48238771)
(30.38392845; -0.84360602; -7.18454449) vs (51.47966417; -8.27215748; -13.66138324)
(-42.78379957; -72.16406250; 4.84289926) vs (-60.73544200; 2.56207385; 5.57435739)
```

The problem doesn't appear on this AMD GPU though
```
Specs:
  OpenCL: AMD Radeon RX 5700 XT
  GPU DRIVER: AMDGPU-PRO
  OS: Mint 20 (Ubuntu 20.04)

OpenCL VS Reference: eps = 1e-08, 9000000 atoms: 0 errors. energy is good
OpenCL VS Reference: eps = 1e-08, 12500000 atoms: 0 errors. energy is good
OpenCL VS Reference: eps = 1e-08, 14250000 atoms: 0 errors. energy is good
OpenCL VS Reference: eps = 1e-08, 15125000 atoms: 0 errors. energy is good
OpenCL VS Reference: eps = 1e-08, 15562500 atoms: 0 errors. energy is good
OpenCL VS Reference: eps = 1e-08, 15781250 atoms: 0 errors. energy is good
```

The possible reason for this might be that AMD Radeon RX 5700 XT has a wavefront size of 32.
```
$ clinfo | grep -i wave
  Wavefront width (AMD)                           32
```
And AMD Radeon gfx906 Vega 20 has a wavefront size of 64.
```cpp
hipDeviceProp_t chars;
hipGetDeviceProperties(&chars, 0);
printf("warpSize: %d\n", chars.warpSize);
/*
Output:
warpSize: 64
*/
```
However there's not enough evidence to say this for sure, as @peastman remarked:
> That might be related, or it might be something else. There are a lot of other differences, since they're different generations with different architectures.
> 
> If you're up for trying to debug this, here are the next steps. First an important question: are the errors deterministic? Try running it a second time. Are the incorrect forces exactly the same, or are some of the values different? If they're different, this is most likely a race condition. If they're deterministic, it's probably something else.
> 
> Another easy thing to check is to try switching the nonbonded method to NoCutoff. It will be really slow computing the forces for such a big system with no cutoff (use CPU instead of Reference or you'll be waiting for hours!), but that eliminates everything related to the neighbor list. Do the forces still disagree?

Lastly, errors appear to be deterministic. Forces disagree the same way (it seems to me after looking at them), two consecutive binary search runs produce same results, OpenCL vs OpenCL produces no errors.
```
OpenCL VS OpenCL: eps = 1e-08, 10000000 atoms: 0 errors. energy is good
```

NoCutoff doesn't work on such big systems. OpenCL crashes:
```
Memory access fault by GPU node-4 (Agent handle: 0x56246b7c7f30) on address 0x7faad0da7000. Reason: Page not present or supervisor privilege.
Aborted (core dumped)
```
CUDA crashes too:
```
terminate called after throwing an instance of 'OpenMM::OpenMMException'
  what():  Error downloading array force: CUDA_ERROR_ILLEGAL_ADDRESS (700)
Aborted (core dumped)
```

@peastman, probably, this needs to be labeled 'bug' too

**Comment by peastman** [comment]
Unfortunately I don't have access to a GPU I can reproduce this on.  I don't know how much effort you're willing to put in to try to debug it, but if you're up for it, I can describe the approach I'd take.

I would start by identifying a single atom that has a significantly different force on it between OpenCL and CUDA.  Then I would add print statements into the code that computes nonbonded interactions so it would print out every individual interaction involving that atom.  Once you have those, you can paste the output into a spreadsheet, sort each one by atom number, and compare.  You should find one of three things:

1. There are some interactions that are incorrectly getting missed.
2. There are some interactions that are incorrectly getting added.
3. The set of interactions is correct, but the two platforms are computing different forces for them.

Whichever one it is, that tells us where to dig further.

One complication is that these platforms reorder the atoms to improve spatial locality.  That means that, for example, atom 131 as seen by the kernel is different from atom 131 as seen by the public API.  You can get the reordered indices by calling `getAtomIndex()` on the OpenCLContext or CudaContext.  `getAtomIndex()[i]` is the index (as seen by the public API) of atom `i` (as seen by the kernel).

Then again, since the majority of atoms have errors once the system gets big enough, you probably don't need to worry about this.  Any atom you pick at random has a good chance of having an error.

The code for computing nonbonded interactions is found in `nonbonded.cl` (for OpenCL) and `nonbonded.cu` (for CUDA).  You'll see that each of them includes several appearances of `COMPUTE_INTERACTION`.  Each place that appears, the full content of `coulombLennardJones.cl` or `coulombLennardJones.cu` gets inserted.  You can add the print statements either within `coulombLennardJones` or just after each of the places it gets inserted.  The latter might ultimately be necessary, if we need to identify where the disagreement is appearing, but the former is probably fine to start with.  Something like this, assuming you want to print interactions involving atom 12345:

```c++
if ((atom1 == 12345 || atom2 == 12345) && !isExcluded)
  printf("%d %d %g %g %g\n", atom1, atom2, dEdR.x, dEdR.y, dEdR.z);
```

**Comment by Dann239** [comment]
Sorry if i'm missing something obvious, but as i understand, `OpenCLContext` and `CudaContext` are from OpenMM Low Level API. How can i access them? The only way i could come up with is to make `getImpl()` public for `Context` and then accessing the `ComputeContext` from `PlatformData`
```cpp
auto data1 = (OpenMM::CudaPlatform::PlatformData*)context1->getImpl().getPlatformData();
auto compute_context1 = (OpenMM::ComputeContext*) data1->contexts.back();
auto api_indecies1 = compute_context1->getAtomIndex();
std::vector<int> kernel_indecies1(amount);
for(int i = 0; i < amount; i++) kernel_indecies1[api_indecies1[i]] = i;
```
Is there a less hacky way to do it? Because figuring it out took quite some time and it feels like i'm missing some easy way.

**Comment by Dann239** [comment]
I did what you suggested. I added the following
```cpp
if((atom1 == 1387 || atom2 == 1387) && !isExcluded && dEdR != 0)
    printf("CUDA: %d %d %g\n", atom1, atom2, dEdR);
```
to `coulombLennardJones.cu` and a similar thing to `coulombLennardJones.cl`. The particle 1387 has following total forces:
```
k_ind1=1387; k_ind2=1387
f1 = ( -40.17229549; 5.80100008; -12.86519120 )
f2 = ( -81.15372478; 13.91615578; -3.26848061 )

CUDA VS OpenCL: eps = 1e-08, 2100000 atoms: 8260 errors. energy is bad
```
I then sorted the output lines and juxtaposed identical (in terms of atom numbers) lines from CUDA and OpenCL to make anomalies stand out.

It looks like OpenCL 'invokes' COMPUTE_INTERACTION twice as much on certain particles. Take a look yourself.

Here are results that were produced and a sorted version of them: [cuda_vs_ocl.zip](https://github.com/openmm/openmm/files/5131703/cuda_vs_ocl.zip)

**Comment by peastman** [comment]
This would require compiling OpenMM from source and adding diagnostic code directly inside the GPU kernels.  I don't think there's any way to get the necessary level of insight from "outside" the code.

**Comment by Dann239** [comment]
That's not exactly what i was asking. I understand that recompiling the source is a requirement for adding debug output into kernels  (which i did), i was just asking if there was an easier way of invoking `getAtomIndex()` on contexts. But i guess my 'hacky' way works just fine.

**Comment by peastman** [comment]
Excellent!  You're exactly right.  For example, the interaction between atoms  1294 and 1387 is listed three times for CUDA (I assume because forces got computed three times?) but six times for OpenCL.

Let's focus on that particular pair and figure out why it's getting computed more often.  There are four different places in nonbonded.cl where COMPUTE_INTERACTION gets inserted, so let's start by figuring out which of those it's getting computed in.  I have a super sophisticated, patented technique I use for doing that.  Right after the first one add the line

```c++
if (!isExcluded && ((atom1 == 1294 && atom2 == 1387) || (atom1 == 1387 && atom2 == 1294)))
    printf("a %d %d\n", atom1, atom2);
```

Then after the second one I add the same thing but have it print "b", and so on.

I *think* it's going to end up being computed in the third or fourth blocks.  Those are the second loop, where it computes interactions from the neighbor list.  Assuming that's true, let's also check the size of the neighbor list.  Assuming that's correct, let's find out if the neighbor list is the same size for both CUDA and OpenCL.  You can check that by adding this at the very end of the kernel:

```c++
if (warp == 0 && tgx == 0)
    printf("%d tiles\n", numTiles);
```

**Comment by Dann239** [comment]
Apparently, forces are computed three times because each kernel is launched three times. After i commented out those lines:
```cpp
context1->setVelocitiesToTemperature(1, 0);
double energy1 = context1->getState(OpenMM::State::Energy).getPotentialEnergy();
```
There was only one invocation per platform. Here's the output:
```
CUDA: 1387 1294 c
CUDA: 976993 tiles
OpenCL: 1294 1387 c
OpenCL: 975809 tiles
OpenCL: 1387 1294 c

k_ind1=1387; k_ind2=1387
f1 = ( -40.17229549; 5.80100008; -12.86519120 )
f2 = ( -81.15372478; 13.91615578; -3.26848061 )


k_ind1=1294; k_ind2=1294
f1 = ( 25.59796891; 74.72335395; 27.71143236 )
f2 = ( 27.90261103; 158.96257428; -7.87470192 )

CUDA VS OpenCL: eps = 1e-08, 2100000 atoms: 8260 errors
```

**Comment by peastman** [comment]
I have a hypothesis about this.  Could you try an experiment?  Line 78 of findInteractingBlocks.cl is

```c++
#if SIMD_WIDTH <= 32
```

Try changing that to `<= 64`.  Does the error go away?

**Comment by Dann239** [comment]
```
CUDA: 1387 1294 c
CUDA: 976993 tiles; 0 sth else
OpenCL: 1387 1294 c
OpenCL: 976993 tiles; 0 sth else

k_ind1=1387; k_ind2=1387
f1 = ( -40.17229549; 5.80100008; -12.86519120 )
f2 = ( -40.17229549; 5.80100008; -12.86519120 )


k_ind1=1294; k_ind2=1294
f1 = ( 25.59796891; 74.72335395; 27.71143236 )
f2 = ( 25.59796891; 74.72335395; 27.71143236 )

CUDA VS OpenCL: eps = 1e-08, 2100000 atoms: 0 errors
```
I does seem to fix the problem. However, this still bothers me:
https://github.com/openmm/openmm/blob/cdc0789a1b4d82266419d469c951470ef78fd1d0/platforms/opencl/src/kernels/findInteractingBlocks.cl#L92-L105
Why 32 everywhere? Aren't we losing 50% of performance by this if we do this fix? And what if `SIMD_WIDTH` were 16 or 8?

**Comment by peastman** [comment]
Great!  That helps a lot to narrow down where the problem is.  I don't intend this as a fix.  It could serve as a workaround if absolutely necessary, but it would hurt performance on older AMD GPUs, so I'd like to fix it properly.

The 32s are because we operate on blocks of 32 atoms.  If the SIMD width happens to be exactly 32, that's very efficient.  If it's less than 32 it still works pretty well, but we have to add in occasional synchronization to ensure correct behavior.  (You'll find `SYNC_WARPS` lines scattered through the kernel.  That maps to a barrier if the SIMD width is <32, and nothing otherwise.)  If the width is >32, this still works correctly but leads to thread divergence that hurts performance.  That's why we have an alternate implementation for that case.

**Comment by Dann239** [comment]
I see. I'm glad i've been able to help, i'm willing to help you with testing whatever solution you implement or perform further debugging if this is still not enough to identify the exact issue.

**Comment by peastman** [comment]
I just posted a PR that I believe should fix this.  Can you try the code in #2829 and see if it now works for you?

**Comment by Dann239** [comment]
This is excellent! The problem doesn't appear on my GPUs anymore. Thank you for the fix.

**Comment by peastman** [comment]
Great!  Thanks so much for your help in tracking this down!
