### ISSUE TITLE
Possibly incorrect comparison in CudaContext.cpp

### ISSUE THREAD

**Issue by anand-bhat** [openmm/openmm#2821]
I was curious to know if the issue that was fixed in https://github.com/openmm/openmm/pull/2819 could have been caught using static code analysis. I tried running this through [Cppcheck](http://cppcheck.sourceforge.net/) and while it didn't flag this, it did raise some other things, one of which caught my eye.

![image](https://user-images.githubusercontent.com/7332442/91578170-2ba33c00-e98d-11ea-848c-1f31254af6eb.png)

I'm not a C++ developer so I could very well be reading this wrong. There are also a number of false positives raised by Cppcheck but to my untrained eye, this looks legit as the variable `res` that is set in the `#ifdef` masks the one defined outside and will never have a value set when [checked](https://github.com/openmm/openmm/blob/cea03eea70ed71f248dbeb6ea447e83053e5c6af/platforms/cuda/src/CudaContext.cpp#L610) outside to write into the error log.

Context: Checked [CudaContext.cpp](https://github.com/openmm/openmm/blob/cea03eea70ed71f248dbeb6ea447e83053e5c6af/platforms/cuda/src/CudaContext.cpp) from openmm:master at commit cea03eea70ed71f248dbeb6ea447e83053e5c6af using Cppcheck 2.1 on Win10.

I haven't run the program (and probably wouldn't know how to) so my apologies if this is an invalid issue.

**Comment by peastman** [comment]
You're right, line 603 shouldn't be defining a new variable.  Thanks!
