### ISSUE TITLE
Move website

### ISSUE THREAD

**Issue by peastman** [openmm/openmm#2824]
The OpenMM website is currently hosted on Vijay's AWS account.  He wants to shut down the account, so we need to move to somewhere else.  Any suggestions?  The simplest solution would probably be to just migrate to a different AWS account, but we could also consider other options that might be easier to maintain.  It's a very simple static website.

**Comment by jchodera** [comment]
We should be able to use GitHub Pages to host the static site:
https://pages.github.com/

The more complicated thing is getting the domain name transferred if we haven't done that already.

**Comment by peastman** [comment]
I enabled Github Pages on the openmm-org repository, and to an amazing extent it "just worked".  You can browse the site at https://openmm.github.io/openmm-org/.

Along with the domain name, the other thing we need to figure out a solution for is the documentation.  Currently that's hosted on a separate bucket in AWS.  It includes documentation for lots of past releases, as well as the current development documentation that gets automatically rebuilt with every PR.  Trying to store that on Github would be way too inefficient.

**Comment by jchodera** [comment]
I'm happy to set up a bucket for that and transfer everything over. I think I already have access to the current bucket so let me see if I can just copy everything over and update the URL.

**Comment by peastman** [comment]
That would be great, thanks!

**Comment by peastman** [comment]
The docs seem to have gotten broken in the process.  Going to http://docs.openmm.org/latest/userguide/index.html produces a "403 Forbidden" error.

**Comment by jchodera** [comment]
Unpaid bills:
![Uploading image.png…]()

**Comment by jchodera** [comment]
Update: There was an issue with the Stanford contact which has now been resolved. The account should be paid in a few days. Until then, the docs will be down.

@peastman : How do you want to proceed? I think it's probably going to be much simpler if I simply assume ownership of the AWS account after the PO expires at the end of 2020. We won't have to change or copy anything at that point, and I can help continue to spin down the other services.

**Comment by peastman** [comment]
Ok.

**Comment by rmcgibbo** [comment]
@jchodera: If the account comes up over the weekend, I'll copy the mdtraj content off into my personal AWS account.

**Comment by rmcgibbo** [comment]
I'm actually not sure who owns the mdtraj.org domain name itself, so that's another headache...

**Comment by jchodera** [comment]
Looks like---I'd email him to get it migrated.

The DNS seems to be configured from AWS. Do you have a moment to work together on that once AWS comes back up?
Might take a few days for Stanford to process paperwork.

**Comment by rmcgibbo** [comment]
Yeah, IIRC DNS is from Route53. We can work together on migrating those, since we both have to do the same thing (you for openmm, me for mdtraj). I'll email Vijay to set up the mdtraj godaddy migration.

**Comment by peastman** [comment]
What's the status of this?  Are we still planning to switch to Github Pages?

**Comment by jchodera** [comment]
If it isn't broken, I don't think we need to fix it. My new plan is simply to take over paying for the pandelab AWS account when Stanford stops paying at the end of the year. That way, we don't need to migrate anything.

The only expensive item that still needs to be shut down is a DeepChem discourse server running on EC2 at 13.52.177.231. Is that still actively used?

**Comment by peastman** [comment]
Fair enough.  I don't think the discourse is being used, but check with Bharath to be sure.  Shall I close this issue?
