### ISSUE TITLE
Potential "invalid __shared__ read of size 4" in CUDA findBlocksWithInteractions?

### ISSUE THREAD

**Issue by zhi-wang** [openmm/openmm#2825]
Hello,

I've seen unwanted memory access reported by `cuda-memcheck`. Since I don't know exactly which line caused it, I can only guess it was from this [line](https://github.com/openmm/openmm/blob/master/platforms/cuda/src/kernels/findInteractingBlocks.cu#L347) in `findBlocksWithInteractions()`. Here is my thought process, and please correct me if I am wrong.

Suppose the `buffer` was fill with 256 atoms, `tilesToStore=8`, array index `indexInWarp+TILE_SIZE*tilesToStore` would exceed its capacity `BUFFER_SIZE` (256). If this warp also happened to be the last warp of the working threads, this line would cause out-of-bound memory access.

Even though accessing out-of-bound memory is undefined behavior, it would probably be okay if the program doesn't try to write to unwanted memory location. I wish I could get away from the `cuda-memcheck` report, and I understand it, if this is an intentional design decision.

Regards,
Zhi Wang

**Comment by peastman** [comment]
It's possible that's the problem.  Try prefixing that line with

```c++
if (indexInWarp+TILE_SIZE*tilesToStore < BUFFER_SIZE)
```

Does that make the error go away?

**Comment by zhi-wang** [comment]
I have tried this line and it seemed to have fixed the problem.
```C
if (tilesToStore < BUFFER_SIZE/TILE_SIZE)
```

Since the invalid memory only happened when the buffer was full, I believe your proposed fix and the following line would both fix it too.
```C
if (neighborsInBuffer == BUFFER_SIZE)
```

Thanks.

**Comment by peastman** [comment]
Great!  I'll make that change.  Thanks!
