### ISSUE TITLE
About constant one_4pi_eps

### ISSUE THREAD

**Issue by ChunshuWu** [openmm/openmm#2826]
Does it stand for Coulomb's constant? This constant is defined as ~139, I wonder why it is different from the value of Coulomb's constant. Is it combined with some other constant or is it just a matter of unit? Thanks.

**Comment by peastman** [comment]
> Does it stand for Coulomb's constant?

That's correct.  The value depends on the units.  In the latest version of the code we compute it from other constants rather than specifying the value directly:

```c++
#define E_CHARGE     (1.602176634e-19)
...
#define AVOGADRO     (6.02214076e23)          
...
#define EPSILON0     (1e-6*8.8541878128e-12/(E_CHARGE*E_CHARGE*AVOGADRO)) /* (e^2 Na/(kJ nm)) == (e^2/(kJ mol nm)) */ 
...
#define ONE_4PI_EPS0      (1/(4*M_PI*EPSILON0))
```

**Comment by ChunshuWu** [comment]
Many thanks for the clarification
