### ISSUE TITLE
Possible bug in OpenCLKernels

### ISSUE THREAD

**Issue by ThWuensche** [openmm/openmm#2828]
In OpenCLKernels.h: OpenCLCalcNonbondedForceKernel private variable paramValues is defined as 
std::vector\<double\> paramValues;
but in OpenCLKernels.cpp we have:
 ```
   globalParams.initialize(cl, max((int) paramValues.size(), 1), cl.getUseDoublePrecision() ? sizeof(double) : sizeof(float), "globalParams");
    if (paramValues.size() > 0)
        globalParams.upload(paramValues, true);

```
If cl.getUseDoublePrecision evaluates to false, the initialization will have a different size than the uploaded paramValues and it will throw an exception

**Comment by peastman** [comment]
Passing `true` as the second argument tells it to automatically convert the values if necessary:

https://github.com/openmm/openmm/blob/c879fdbe5e48420651f13fa8fee467b142b067b5/platforms/common/include/openmm/common/ArrayInterface.h#L90-L98

**Comment by ThWuensche** [comment]
I came across that as the memory initialization bugfix on the backport to F@H throws the exception

**Comment by peastman** [comment]
I see, it's because F@H is using an older version of OpenMM.  The signature was different in that version:

```c++
void upload(const std::vector<T>& data, bool blocking = true, bool convert = false)
```

So we need to change `globalParams.upload(paramValues, true);` to `globalParams.upload(paramValues, true, true);`.

**Comment by ThWuensche** [comment]
Ok, thanks, will you propagate that to the F@H code base and tell John, or should I do so? You probably have the higher authority :)

**Comment by ThWuensche** [comment]
Is there a performance drawback on the automatic conversion?

**Comment by peastman** [comment]
Already merged the change!  https://github.com/FoldingAtHome/openmm/pull/29

> Is there a performance drawback on the automatic conversion?

It makes no difference here.  This is a one time upload of a very small array.

**Comment by ThWuensche** [comment]
Thanks, I made the change locally and it is working.

**Comment by jchodera** [comment]
Thanks, @ThWuensche and @peastman!
