### ISSUE TITLE
Accept Numpy ints for int arguments

### ISSUE THREAD

**Issue by Hong-Rui** [openmm/openmm#2831]
Hi, 

I recently jump into a problem with custom external force setups.
This is the same problem with #2607 

My codes are something like 
```
from simtk.unit import *
from simtk.openmm import *
from simtk.openmm.app import *
import MDAnalysis as mda
import parmed as pmd

def add_harmonic_restraints(structure, system, selection_string='protein or resname MOL and not name H*', spring_const_name='spring_const'):
    universe = mda.Universe(structure)
    restrained_atoms = universe.select_atoms(selection_string)
    atom_coordinates = restrained_atoms.positions * angstrom
    atom_coordinates = atom_coordinates.value_in_unit(nanometer)
    atom_indices = restrained_atoms.indices

    restraint_force = CustomExternalForce('{k}*periodicdistance(x,y,z,x0,y0,z0)^2'.format(k=spring_const_name))
    restraint_force.addGlobalParameter(spring_const_name, 0.0)
    restraint_force.addPerParticleParameter('x0')
    restraint_force.addPerParticleParameter('y0')
    restraint_force.addPerParticleParameter('z0')

    for current_idx, current_coor in enumerate(atom_coordinates):
        restraint_force.addParticle(atom_indices[current_idx], [current_coor[0], current_coor[1], current_coor[2]])

    system.addForce(restraint_force)
    return restraint_force


structure = pmd.load_file('system_solvated.prmtop', xyz='system_solvated.inpcrd')
system = structure.createSystem(nonbondedMethod=LJPME,
                                nonbondedCutoff=1.2 * nanometer,
                                constraints=HBonds,
                                hydrogenMass=3.024)

restraint_force = add_harmonic_restraints(structure, system)
```

This produces the following error:

```
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-4-116c5d7a2906> in <module>
----> 1 restraint_force = add_harmonic_restraints(structure, system)

<ipython-input-1-7afa6cee77eb> in add_harmonic_restraints(structure, system, selection_string, spring_const_name)
     22 
     23     for current_idx, current_coor in enumerate(atom_coordinates):
---> 24         restraint_force.addParticle(atom_indices[current_idx], Vec3(current_coor[0], current_coor[1], current_coor[2]))
     25 
     26     system.addForce(restraint_force)

~/Modules/miniconda3/envs/Drug_Design_Frontend/lib/python3.7/site-packages/simtk/openmm/openmm.py in addParticle(self, *args)
   3556             the index of the particle term that was added
   3557         """
-> 3558         return _openmm.CustomExternalForce_addParticle(self, args[0], args[1])
   3559 
   3560 

NotImplementedError: Wrong number or type of arguments for overloaded function 'CustomExternalForce_addParticle'.
  Possible C/C++ prototypes are:
    OpenMM::CustomExternalForce::addParticle(int,std::vector< double,std::allocator< double > > const &)
    OpenMM::CustomExternalForce::addParticle(int)
```

Same as in #2607 , I tried with Vec3(), list, tuple, of the particle coords, and none of them work.
I've also printed out the input values in the ```openmm.py ``` ```addParticle()``` function, and verified that the passing values were correct.

I'm using Ubuntu 20.04 with python 3.7 and openmm=7.4.2.
I also tried to downgrade the OpenMM version to 7.4.1, 7.3.1, and none of them worked.

However, if I switched to another python 2.7 environment, the above codes worked, and produce the desired results. (verified)
I also tried to directly modify the some inputs in ```openmm.py ``` ```addParticle()``` , and doesn't seem to work.
So I believe there's something going on in the C++ shared libraries, ```_openmm.cpython-37m-x86_64-linux-gnu.so```.

In my python 3.7 env, the ```numpy``` version is the newest 1.19.1, while in the python 2.7 env it is 1.16.5.

Since we're developing some distributed software, and we really need a py37 env to work ASAP.
Could you please have a look on this issue? @peastman 
Really thanks a lot !

**Comment by Hong-Rui** [comment]
#2607

**Comment by Hong-Rui** [comment]
btw, I also tried with OpenMM 7.5.0 beta, and still doesn't work.
The only difference is that the ```NotImplementedError``` now changes to a ```TypeError```, but printed with exactly the same error message.

**Comment by tristanic** [comment]
This sounds like it might be due to a really annoying idiosyncrasy of Numpy when working with wrapped C++ methods taking integer arguments (happens for SWIG and boost.python, but PyBind11 seems to be smart enough to sort it out): Numpy integer scalars are not the same type as Python `int`, so fail type-checking when passed to the wrapper. Try replacing:

```
        restraint_force.addParticle(atom_indices[current_idx], [current_coor[0], current_coor[1], current_coor[2]])
```
with
```
        restraint_force.addParticle(int(atom_indices[current_idx]), [current_coor[0], current_coor[1], current_coor[2]])
```
... and see if that works.

**Comment by tristanic** [comment]
:)

Believe me, that caused a *lot* of head-scratching when I first encountered it.

**Comment by Hong-Rui** [comment]
Me too!
I've been stucked with these codes and debugging for one afternoon and still not figuring out what's happening before posting this...

**Comment by peastman** [comment]
We should see if we can make this work automatically.  This looks relevant: https://stackoverflow.com/questions/58528367/passing-numpy-array-element-int-to-c-int-using-swig

**Comment by peastman** [comment]
I edited the title to reflect what the actual problem is.
