### ISSUE TITLE
LangevinMiddleIntegrator docs incomplete

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#2832]
The `LangevinMiddleIntegrator` docs seem to represent a nonexistent paper about "the LFMiddle discretization" (and an online search turns up empty). They also make no mention of BAOAB. Can we fix this?
http://docs.openmm.org/development/api-python/generated/simtk.openmm.openmm.LangevinMiddleIntegrator.html#simtk.openmm.openmm.LangevinMiddleIntegrator
![image](https://user-images.githubusercontent.com/3656088/92204423-56334000-ee38-11ea-9453-7b521f142b2c.png)

**Comment by jchodera** [comment]
We use Sphinx to render the C++ API docs, which I believe interprets this as [restructuredText (rst)](https://www.sphinx-doc.org/en/master/usage/restructuredtext/index.html). I believe we just need to use the syntax for [hyperlinks](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#hyperlinks) here.

Can we also mention that this is equivalent to BAOAB in the leapfrog discretization (and cite the Matthews and Leimkuhler paper) if we decided that they were equivalent, and note why we did this instead of offering BAOAB?

**Comment by mattwthompson** [comment]
I noticed some similar rendering issues in [this](http://docs.openmm.org/latest/api-python/library.html#core-objects) page (`J. Phys. ...` is cut off at `J.`):

<img width="952" alt="image" src="https://user-images.githubusercontent.com/7935382/185012954-1750f1bb-4c35-4cec-8c95-c343809b3249.png">

although following the link to the [documentation for each class](http://docs.openmm.org/latest/api-python/generated/openmm.openmm.LangevinMiddleIntegrator.html#openmm.openmm.LangevinMiddleIntegrator) renders fine:

<img width="913" alt="image" src="https://user-images.githubusercontent.com/7935382/185013165-fa4d567e-358b-4ba9-872c-440bfe19dc4c.png">

there might be a few instances of this, and it doesn't really matter, but I thought I'd report somewhere.

**Comment by peastman** [comment]
The summary table includes the first sentence of the description for each class.  Sphinx sees the period after the J and cleverly concludes that it's the end of the sentence.
