### ISSUE TITLE
Implicit membrane model?

### ISSUE THREAD

**Issue by aizvorski** [openmm/openmm#2836]
I'd like to use an implicit membrane model in OpenMM.  I don't have a preference for a particular model; GBSW or HDGB look good.

I did a search and there doesn't seem to be any examples of that online. https://github.com/choderalab/openmm-validation mentions "Construct a CustomGBForce for an implicit membrane model..." but I couldn't find any code for that.  CHARMM-GUI has an implicit membrane builder http://www.charmm-gui.org/?doc=input/implicit but that seems to be CHARMM-only.  I don't know if loading the resulting .psf file in OpenMM would be expected to just work; maybe not, there seems to be some setup in the .inp file.

Is this possible?  Where do I get started?

**Comment by peastman** [comment]
We do have a test case that involves an implicit membrane model:

https://github.com/openmm/openmm/blob/c4b9505a610f3c59c55de2a685b7258bcabcd1a4/tests/TestCustomGBForce.h#L194-L214

I believe it's adapted from https://pubs.acs.org/doi/abs/10.1021/jp020674r.  Be aware this hasn't been extensively validated though.  It could serve as a starting point for you, but I can't make any guarantees either about the quality of the model or the correctness of the implementation.

**Comment by c00jsw00** [comment]
Dear all,
I wrote a simple   implicit membrane model  code (https://github.com/c00jsw00/openmm-IMGB/tree/main). Could u helpe me the check it is ok ?
