### ISSUE TITLE
Appropriate naming for debug libs

### ISSUE THREAD

**Issue by samuelflores** [openmm/openmm#2845]
guys, 

I am trying to compile my code in debug mode, which requires openmm to also be in debug mode. However it is only creating libOpenMM.so , whereas I am expecting libOpenMM_d.so:

/usr/bin/ld: cannot find -lOpenMM_d

I checked and confirmed that openmm is only writing libOpenMM.so:

 CMAKE_BUILD_TYPE                 Debug                                                                    
make install
...
-- Up-to-date: /usr/local/openmm/lib/libOpenMM.so
...

Can someone clarify?

many thanks

sam

**Comment by peastman** [comment]
The file name is always the same.  Changing the build type doesn't affect the name.

**Comment by samuelflores** [comment]
OK, good to know officially. I'm used to appending _d to the debug libs so I thought it was a standard. 

thanks
