### ISSUE TITLE
Unrecognised atom types in charmm files

### ISSUE THREAD

**Issue by sarahmapplebeck** [openmm/openmm#2846]
Hi 

I have the below function to get an xml file using charmm files for a protein in implicit solvent:

from simtk.openmm.app import *
from simtk.openmm import *
from simtk.unit import *
import xml.etree.ElementTree as ET
from sys import stdout, exit, stderr

def get_openmm_charmm(psf_file,crd_file,out_xml):
    psf = CharmmPsfFile(psf_file)
    crd = CharmmCrdFile(crd_file)
    params = CharmmParameterSet('/Users/cm14sjm/Downloads/charmm-gui-0035490319/toppar/par_all36m_prot.prm',
                                '/Users/cm14sjm/Downloads/charmm-gui-0035490319/toppar/top_all36_prot.rtf',
                                '/Users/cm14sjm/Downloads/charmm-gui-0035490319/toppar/toppar_water_ions.str')
    system = psf.createSystem(params,nonbondedMethod=NoCutoff,nonbondedCutoff=1*nanometer, constraints=None, implicitSolvent=None )
    integrator = LangevinIntegrator(300*kelvin, 1/picosecond, 0.002*picosecond)
    simulation = Simulation(psf.topology, system,integrator)
    simulation.context.setPositions(crd.positions)
    simulation.minimizeEnergy()
    simulation.step(10000)
    serialized_system = XmlSerializer.serialize(system)
    out_file = open(out_xml, 'w')
    out_file.write(serialized_system)
    pdb_file = open('tit.pdb', 'w')
    PDBFile.writeFile(simulation.topology, crd.positions, pdb_file)

Which is called using: 

get_openmm_charmm('/Users/cm14sjm/Downloads/charmm-gui-0035490319/step1_pdbreader.psf',
                  '/Users/cm14sjm/Downloads/charmm-gui-0035490319/step1_pdbreader.crd',
                  '/Users/cm14sjm/PycharmProjects/ChemDyME_working/tit_out.xml')

But, when using these files i always get this error:

MissingParameter: Could not find atom type for CH1E

I think it relates to my psf file (attached) as this has this contains this atom type and the function works with another psf file I have for the same protein but in explicit solvent which doesn't contain this atom type.

Any help on how to fix this would much appreciated.

Thanks
Sarah

[step1_pdbreader_psf.txt](https://github.com/openmm/openmm/files/5246635/step1_pdbreader_psf.txt)

**Comment by peastman** [comment]
I think there's something wrong with your files.  I can't find any atom type called CH1E in CHARMM36.  Here is how top_all36_prot.rtf defines the atoms in LEU:

```
ATOM N    NH1    -0.47  !     |        HD11 HD12
ATOM HN   H       0.31  !  HN-N          | /
ATOM CA   CT1     0.07  !     |   HB1   CD1--HD13
ATOM HA   HB1     0.09  !     |   |    /
GROUP                   !  HA-CA--CB--CG-HG
ATOM CB   CT2    -0.18  !     |   |    \ 
ATOM HB1  HA2     0.09  !     |   HB2   CD2--HD23
ATOM HB2  HA2     0.09  !   O=C          | \
GROUP                   !     |        HD21 HD22
ATOM CG   CT1    -0.09
ATOM HG   HA1     0.09
GROUP   
ATOM CD1  CT3    -0.27
ATOM HD11 HA3     0.09
ATOM HD12 HA3     0.09
ATOM HD13 HA3     0.09
GROUP   
ATOM CD2  CT3    -0.27
ATOM HD21 HA3     0.09
ATOM HD22 HA3     0.09
ATOM HD23 HA3     0.09
GROUP   
ATOM C    C       0.51
ATOM O    O      -0.51
```

And here is how your PSF file define it:

```
       1 PROA 1    LEU  HT1  HC     0.300000       1.00800           0   0.00000     -0.301140E-02
       2 PROA 1    LEU  HT2  HC     0.300000       1.00800           0   0.00000     -0.301140E-02
       3 PROA 1    LEU  N    NH3   -0.900000       14.0067           0   0.00000     -0.301140E-02
       4 PROA 1    LEU  HT3  HC     0.300000       1.00800           0   0.00000     -0.301140E-02
       5 PROA 1    LEU  CA   CH1E    0.00000       13.0190           0   0.00000     -0.301140E-02
       6 PROA 1    LEU  CB   CH2E    0.00000       14.0270           0   0.00000     -0.301140E-02
       7 PROA 1    LEU  CG   CH1E    0.00000       13.0190           0   0.00000     -0.301140E-02
       8 PROA 1    LEU  CD1  CH3E    0.00000       15.0350           0   0.00000     -0.301140E-02
       9 PROA 1    LEU  CD2  CH3E    0.00000       15.0350           0   0.00000     -0.301140E-02
      10 PROA 1    LEU  C    C      0.550000       12.0110           0   0.00000     -0.301140E-02
      11 PROA 1    LEU  O    O     -0.550000       15.9994           0   0.00000     -0.301140E-02
```

The atom types are completely different.
