### ISSUE TITLE
ANI implementations in OpenMM

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#2850]
I'm creating this thread to discuss how we might support the [ANI](https://pubs.rsc.org/en/content/articlelanding/2017/sc/c6sc05720a) (especially [ANI-2x](https://chemrxiv.org/articles/Extending_the_Applicability_of_the_ANI_Deep_Learning_Molecular_Potential_to_Sulfur_and_Halogens/11819268/1)) in OpenMM.

There are a number of implementations of this, including [TorchANI](https://github.com/aiqm/torchani), and now an implementation in [RDKit](https://github.com/rdkit/rdkit/pull/3408).

The developers of ANI have now also established an [ANI Model Zoo](https://github.com/aiqm/ani-model-zoo) for organizing deployed releases of ANI potentials.

We're currently considering a few possibilities, including:
* Support via the [openmm-torch](https://github.com/openmm/openmm-torch) plugin
* Support via a low-level `ANIForce` that would use a community-driven open source [neural network potential kernel library](https://github.com/peastman/NNPOps) that would provide efficient implementations of GPU kernels for common ML potential featurization schemes, also available as custom Ops for ML frameworks like PyTorch, TensorFlow, and JAX

This thread is intended to collect some feedback from the community and help us plan for upcoming feature roadmaps.

**Comment by peastman** [comment]
I think we've settled on an approach for this.  We managed to [speed up TorchANI](https://github.com/openmm/NNPOps/pull/13) quite a bit, partly through improvements to the PyTorch model and partly by using the optimized GPU kernel.  The plan is to use that through the PyTorch plugin.
