### ISSUE TITLE
CUDA - Error computing forces with CUDA platform

### ISSUE THREAD

**Issue by VicCruces** [openmm/openmm#2851]
Hello,

I am an ArchLinux user, and I am trying to install OPENMM,
I was following the conda instructions of the main webpage:
http://docs.openmm.org/latest/userguide/application.html

The only difference that I did is the following command:
conda install -c omnia/label/cuda101 -c conda-forge openmm

It seems that it is already installed (at least for CPU), but once I run
the verification command:
python -m simtk.testInstallation

I get the message:

> 
> OpenMM Version: 7.4.2
> Git Revision: dc9d188939ad630d240e89806b185061f7cd661a
> 
> There are 4 Platforms available:
> 
> 1 Reference - Successfully computed forces
> 2 CPU - Successfully computed forces
> 3 CUDA - Error computing forces with CUDA platform
> 4 OpenCL - Successfully computed forces
> 
> CUDA platform error: Error launching CUDA compiler: 32512
> sh: /usr/local/cuda/bin/nvcc: No such file or directory
> 
> 
> Median difference in forces between platforms:
> 
> Reference vs. CPU: 6.32688e-06
> Reference vs. OpenCL: 6.75312e-06
> CPU vs. OpenCL: 7.8229e-07
> 

The problem seems to be that for default OPENMM is looking for
"/usr/local/cuda/bin/nvcc". 

And, the CUDA-10.1 nvcc on ArchLinux is located in the path 
"/opt/cuda-10.1/nvcc". 

Could you help me to solve this problem?

Best,
Victor

**Comment by peastman** [comment]
You can fix it with

```
export OPENMM_CUDA_COMPILER=/opt/cuda-10.1/nvcc
```

**Comment by VicCruces** [comment]
Thanks a lot. It is working perfectly!

Have a nice day

**Comment by phisanti** [comment]
Hi @peastman, I have the same problem so I was wondering where I should put the` export OPENMM_CUDA_COMPILER=/opt/cuda-10.1/nvcc command` that you recommend. Should it be within the `.bashrc` file?

**Comment by peastman** [comment]
Anywhere you want.  It just needs to be executed before you run a program that uses OpenMM.
