### ISSUE TITLE
Dodecahedron box together with padding?

### ISSUE THREAD

**Issue by tbengtsen** [openmm/openmm#2852]
Hi, 
I don't seem to be able to find out how to combine the padding option for a box and setting the box to be dodecahedron or  truncated octahedron. Is there a way to do this? So that it can be automated for efficient simulations over many proteins?  It seems it would be in the addSolvent, but I can't find out how to do it. 
best

**Comment by peastman** [comment]
I don't understand your question.  Are you using OpenMM-Setup?  The choices for box shape and padding distance are independent.  Or if you're setting the box vectors by hand in a script, you can set them however you want.

**Comment by tbengtsen** [comment]
Thanks for the quick answer.
 I tried OpenMM-setup, yes, and there I can specify both padding and a dodecahedron box. But OpenMM-setup does not seem to be efficient for automating setup and simulations of many proteins. So my question goes, is there some commands I can input in a OpenMM script, that does this similar to OpenMM-setup? I can see that `addSolvent(forcefield,padding=1.0*nanometers)` does the trick with padding, but it defaults in a cubic box. How can I change it to a dodecahedron box? Since it has to be automated, setting box vectors by hand, does not work.

**Comment by peastman** [comment]
Use the `boxVectors` argument to `addSolvent()`.  You can set it to whatever size and shape you want.

See https://doi.org/10.1002/(SICI)1096-987X(19971130)18:15%3C1930::AID-JCC8%3E3.0.CO;2-P for a description of how to set the box vectors to get boxes of different shapes.  Here is the code in OpenMM-Setup that calculates box vectors:

https://github.com/openmm/openmm-setup/blob/e6930a0cc47b2b98de98a157f89c9a3ea75d5a57/openmmsetup/openmmsetup.py#L245-L256

**Comment by tbengtsen** [comment]
okay, thanks a lot, that should work!
