### ISSUE TITLE
Possible bug in metadynamics.py

### ISSUE THREAD

**Issue by JVZY** [openmm/openmm#2853]
Hi, 
I am using metadynamics and I find for some values of **_simulation.currentStep_** and **_self.frequency_**, the bias potential will not change.

I think the reason is that the 167 line in metadynamics.py doesn't work as expected.

>                 nextSteps = min(nextSteps, simulation.currentStep % self.frequency)

For example, if the frequency is 3 and I run two 10 steps simulations , the second simulation starts with **_simulation.currentStep = 10_**. 

I expect **_nextSteps = 2_** but the 167 line gives **_nextSteps = 1_**. I think this line should be something like

>                 nextSteps = min(nextSteps, self.frequency - simulation.currentStep % self.frequency)

Thanks!

**Comment by peastman** [comment]
I believe you're correct.  I'll fix it.  Thanks!
