### ISSUE TITLE
Issue in temperature calculation for polarizable model

### ISSUE THREAD

**Issue by MMW1** [openmm/openmm#2854]
Hi,

I'm looking at a polarizable system with 1000 ions that are described by 1000 cores and 1000 shells,
and I'm using the DrudeSCFIntegrator. For obtaining say 300 K in my simulation I have to specify 600 K in the script.
I have noticed that the kinetic energy is then also correct (as compared to my system in Gromacs).

For example, using 600 K for my system with 1000 ions, the kinetic energy was 3520 kJ/mole at one time step. 
With E_kin = 3/2 * R * T, we get 282 K, which is also the value given in the log-file.

If I specify 300 K in my script instead, then the temperature is around 150 K in the log-file.

**Comment by MMW1** [comment]
Now I tested to use the DrudeLangevinIntegrator with the same system as mentioned above (1000 ions, represented by 1000 cores and 1000 shells). 

Using a temperature of 300 K (for the cores), the log-file reports at one time step e.g. E_kin = 3565 kJ/mole and T = 143 K (according to the equation E_kin = 3/2 * R * T, it should read 286 K). 

With the DrudeLangevinIntegrator the kinetic energy seems to be correct (in contrast to the DrudeSCFIntegrator), but the temperature is also in this case by a factor of 2 off (i.e. the same as for the DrudeSCFIntegrator).

**Comment by peastman** [comment]
DrudeLangevinIntegrator couples different parts of the system to thermostats at different temperatures.  The center of mass of each atom/Drude pair is at one temperature (300 K in your case), and the motion of each Drude particle relative to its parent atom is at a much lower temperature (usually around 1 K).  If you calculate an instantaneous temperature based on the total kinetic energy, you'll get a weighted average of those two temperatures.  Since you have equal numbers of atoms and Drude particles, it will just be the mean of the two temperatures: 150.5 K.

**Comment by MMW1** [comment]
Thank you, I see. And what about the DrudeSCFIntegrator?

**Comment by peastman** [comment]
That's a constant energy integrator, not a constant temperature one.

**Comment by MMW1** [comment]
I understand. But is it not possible to run the DrudeSCFIntegrator in combination with the AndersenThermostat that should take care of the constant temperature?

**Comment by peastman** [comment]
I don't think that would be a good idea.  AndersenThermostat isn't designed to work with Drude particles.  If you want constant temperature, use DrudeLangevinIntegrator.

**Comment by MMW1** [comment]
Ok, I see. In my test the AndersenThermostat worked in combination with the DrudeSCFIntegrator in principle, i.e. the temperature was kept constant, but it was too low by a factor of 2. 

So there is no thermostat implemented that would work with DrudeSCFIntegrator, which is to my understanding the more accurate integrator for drude particles in comparison to the DrudeLangevinIntegrator? 

Also, is it possible to use the MonteCarloBarostat with a drude model, or are there similar restrictions as for the AndersenThermostat?

**Comment by peastman** [comment]
I wouldn't say that either integrator is more accurate.  They just simulate different physical systems.

I believe MonteCarloBarostat should be fine with Drude particles.

**Comment by MMW1** [comment]
So to summarize:

* Using DrudeSCFIntegrator it is **not** possible to run constant temperature simulations.
* Using DrudeLangevinIntegrator it is possible to run constant temperature simulations.

* Both DrudeIntegretors should not be run in combination with the AndersenThermostat, but can be run in combination with the MonteCarloBarostat.

For the DrudeLangevinIntegrator: 
Is it possible to read out the temperature (and the kinetic energy) for the center of mass of each atom/drude pair, and not to get a weighted average of the two temperatures (and kinetic energies) for the drude particle and its parent atom?

**Comment by peastman** [comment]
There's no routine to calculate it, but you could query the velocities and calculate it yourself.

**Comment by MMW1** [comment]
Ok. Thank you very much for all your answers.

**Comment by peastman** [comment]
I'm closing this since I think everything has been resolved.  Feel free to reopen it if I missed something.
