### ISSUE TITLE
SyntaxWarnings in desmonddmsfile.py, "is" used where == is needed.

### ISSUE THREAD

**Issue by tomgoddard** [openmm/openmm#2856]
OpenMM 7.5.0 on macOS 10.15.6, Sept 22, 2020 version from omnia-dev is giving syntax warnings about incorrect usage of "is" instead of "=="

https://anaconda.org/omnia-dev/openmm/files?version=7.5.0&page=1

/Users/goddard/ucsf/chimerax/ChimeraX.app/Contents/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/simtk/openmm/app/desmonddmsfile.py:411: SyntaxWarning: "is" with a literal. Did you mean "=="?
if implicitSolvent is 'AGBNP3':
/Users/goddard/ucsf/chimerax/ChimeraX.app/Contents/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/simtk/openmm/app/desmonddmsfile.py:433: SyntaxWarning: "is" with a literal. Did you mean "=="?
if implicitSolvent is 'GVolSA':
/Users/goddard/ucsf/chimerax/ChimeraX.app/Contents/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/simtk/openmm/app/desmonddmsfile.py:440: SyntaxWarning: "is" with a literal. Did you mean "=="?
if implicitSolvent is 'AGBNP':

**Comment by peastman** [comment]
Thanks!  Fixed in #2859.
