### ISSUE TITLE
AWS_Cloud_OpenMM

### ISSUE THREAD

**Issue by sharavdesai** [openmm/openmm#2857]
how to run openMM simulation on the AWS cloud.  I have tried for the same but the code of the minimization step is stuck for hours and not moving toward simulations.

**Comment by peastman** [comment]
I doubt that has anything to do with it being on AWS.  More likely it's due to a problem in your system or initial conformation that the minimizer can't resolve.  If you post more details, or better a reproducible test case, I might be able to say more.

**Comment by asgharrazavi** [comment]
I am also having trouble using AWS GPUs.
This is the output of `nvidia-smi` on AWS:
<pre>
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.64.00    Driver Version: 440.64.00    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  On   | 00000000:00:1E.0 Off |                    0 |
| N/A   37C    P0    26W / 300W |      0MiB / 16160MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

</pre>

This is the output from running `python -m simtk.testInstallation`:

<pre>
OpenMM Version: 7.4.2
Git Revision: dc9d188939ad630d240e89806b185061f7cd661a

There are 4 Platforms available:

1 Reference - Successfully computed forces
2 CPU - Successfully computed forces
3 CUDA - Error computing forces with CUDA platform
4 OpenCL - Error computing forces with OpenCL platform

CUDA platform error: No compatible CUDA device is available

OpenCL platform error: Error initializing context: clCreateContext (-33)

Median difference in forces between platforms:

Reference vs. CPU: 6.30396e-06

All differences are within tolerance.
</pre>

**Comment by frank-stonybrook** [comment]
@asgharrazavi What's the output of `echo $OPENMM_CUDA_COMPILER` if you run it in command line?

**Comment by asgharrazavi** [comment]
No output:

<pre>
echo $OPENMM_CUDA_COMPILER 

</pre>

**Comment by frank-stonybrook** [comment]
Then you point it to the CUDA compiler in your environment. Try the following and rerun the python command
```bash
OPENMM_CUDA_COMPILER=`which nvcc`
```

**Comment by asgharrazavi** [comment]
Still not working but error is different: Looks like can't find the nvcc.

<pre>
python -m simtk.testInstallation

OpenMM Version: 7.4.2
Git Revision: dc9d188939ad630d240e89806b185061f7cd661a

There are 4 Platforms available:

1 Reference - Successfully computed forces
2 CPU - Successfully computed forces
3 CUDA - Error computing forces with CUDA platform
4 OpenCL - Error computing forces with OpenCL platform

CUDA platform error: Error launching CUDA compiler: 32512
sh: /usr/local/cuda/bin/nvcc: No such file or directory


OpenCL platform error: Error initializing context: clCreateContext (-33)

Median difference in forces between platforms:

Reference vs. CPU: 6.31255e-06

All differences are within tolerance.
 
$ echo $OPENMM_CUDA_COMPILER 
/home/asghar/programs/cuda_tools/bin/nvcc
</pre>

**Comment by frank-stonybrook** [comment]
You probably want to contact the AWS and figure out the exact path of the CUDA compiler. Also the CUDA compiler path output by OPENMM_CUDA_COMPILER variable seems different than the one OpenMM tries to load. I don't know what's happening there. Other people may have more experience with AWS.

**Comment by peastman** [comment]
The CUDA and OpenCL platforms are both reporting they can't access the device.  That's likely related to the fact that it's in exclusive process mode.  At the time you ran `nvidia-smi` there was nothing else using it, but is it possible something else was using it when you ran `testInstallation`?

**Comment by asgharrazavi** [comment]
I don't think so, I checked before running `testInstallation` and after, no other job is running.  
Why OpenMM is trying to find nvcc here: `/usr/local/cuda/bin/nvcc` instead of where I am pointing it to: `/home/asghar/programs/cuda_tools/bin/nvcc`?

**Comment by peastman** [comment]
`OPENMM_CUDA_COMPILER` is the correct environment variable to point to the compiler.  Could something be preventing that variable from getting propagated to the Python process?

Even if the compiler can't be found, it should just switch over to using the runtime compiler.  Can you run `ldd` on the `libOpenMMCudaCompiler.so` plugin found in the `openmm/lib/plugins` directory?  Does it show any unresolved dependencies?

**Comment by asgharrazavi** [comment]
Here is the output, there are some "not found":
<pre>
ldd /home/asghar/miniconda3/lib/plugins/libOpenMMCudaCompiler.so
	linux-vdso.so.1 =>  (0x00007ffcea7f5000)
	librt.so.1 => /lib64/librt.so.1 (0x00007fd63eedf000)
	libnvrtc.so.10.1 => not found
	libOpenMMCUDA.so => not found
	libOpenMM.so => /home/asghar/miniconda3/lib/plugins/../libOpenMM.so (0x00007fd63e983000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fd63e77f000)
	libcuda.so.1 => not found
	libcufft.so.10 => /home/asghar/miniconda3/lib/plugins/../libcufft.so.10 (0x00007fd6352dd000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fd6350c1000)
	libstdc++.so.6 => /home/asghar/miniconda3/lib/plugins/../libstdc++.so.6 (0x00007fd63f38a000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fd634dbf000)
	libgcc_s.so.1 => /home/asghar/miniconda3/lib/plugins/../libgcc_s.so.1 (0x00007fd63f375000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fd6349f2000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fd63f2ef000)
</pre>


Also, I have several `libOpenMMCudaCompiler.so`:

<pre>
/home/asghar/anaconda3/lib/plugins/libOpenMMCudaCompiler.so
/home/asghar/miniconda3/pkgs/openmm-7.4.0-py37_cuda101_rc_1/lib/plugins/libOpenMMCudaCompiler.so
/home/asghar/miniconda3/pkgs/openmm-7.4.2-py37_cuda101_rc_1/lib/plugins/libOpenMMCudaCompiler.so
/home/asghar/miniconda3/lib/plugins/libOpenMMCudaCompiler.so
</pre>

**Comment by peastman** [comment]
Do you have a CUDA compatible driver installed on this computer?  It isn't finding `libcuda.so`, which comes with the driver.

**Comment by asgharrazavi** [comment]
Yes, I have one here:

<pre>
/home/asghar/programs/cuda_tools/targets/x86_64-linux/lib/stubs/libcuda.so
</pre>

Should I copy it to `miniconda3/lib/` or someplace similar?

**Comment by peastman** [comment]
That's just a stub.  You can use it to compile against, but it can't execute CUDA programs.

**Comment by asgharrazavi** [comment]
Do I need to install OpenMM from source code then?

**Comment by peastman** [comment]
No, this is about CUDA, not OpenMM.  Since this instance has a GPU, it presumably already has a CUDA compatible driver installed.  You need to figure out where the actual libcuda.so is installed.  Perhaps Amazon documents that somewhere?

**Comment by asgharrazavi** [comment]
I am trying to have aws account managers to take a look into this. Meanwhile, I found a `libcuda.so` in `/usr/lib/`. I tried to set up `OPENMM_CUDA_COMPILER ` to `/usr/lib/` but no luck:

<pre>
$ ls /usr/lib/libcuda.so*
/usr/lib/libcuda.so  /usr/lib/libcuda.so.1  /usr/lib/libcuda.so.440.64.00

$ export OPENMM_CUDA_COMPILER=/usr/lib/

$ python -m simtk.testInstallation

OpenMM Version: 7.4.2
Git Revision: dc9d188939ad630d240e89806b185061f7cd661a

There are 4 Platforms available:

1 Reference - Successfully computed forces
2 CPU - Successfully computed forces
3 CUDA - Error computing forces with CUDA platform
4 OpenCL - Error computing forces with OpenCL platform

CUDA platform error: Error launching CUDA compiler: 32256
sh: /usr/lib/: Is a directory


OpenCL platform error: Error initializing context: clCreateContext (-33)

Median difference in forces between platforms:

Reference vs. CPU: 6.31653e-06

All differences are within tolerance.
</pre>

**Comment by peastman** [comment]
`libcuda.so` is not the compiler.  It's a runtime library.  It shouldn't have anything to do with the value of `OPENMM_CUDA_COMPILER`.

The output above shows that `libnvrtc` isn't being found.  That should be in the same directory with the rest of the toolkit libraries (like `libcufft`).  Is it not there?

**Comment by asgharrazavi** [comment]
I removed my OpenMM installation on `minicona`, installed `anaconda3`, created a `python3.7` environment, installed OpenMM using `conda install -c omnia/label/cuda101 -c conda-forge openmm`. Now, it can recognize OpenCl but not CUDA:
<pre>
python -m simtk.testInstallation

OpenMM Version: 7.4.2
Git Revision: dc9d188939ad630d240e89806b185061f7cd661a

There are 3 Platforms available:

1 Reference - Successfully computed forces
2 CPU - Successfully computed forces
3 OpenCL - Successfully computed forces

Median difference in forces between platforms:

Reference vs. CPU: 6.30703e-06
Reference vs. OpenCL: 6.75312e-06
CPU vs. OpenCL: 8.14522e-07

All differences are within tolerance.

</pre>

This is the output of `ldd` on `libOpenMMCudaCompiler.so`: 

<pre>
ldd /home/asghar/anaconda3/envs/py3.7/lib/plugins/libOpenMMCudaCompiler.so
	linux-vdso.so.1 =>  (0x00007ffffb1c2000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f5eb025f000)
	libnvrtc.so.10.1 => not found
	libOpenMMCUDA.so => /home/asghar/anaconda3/envs/py3.7/lib/plugins/libOpenMMCUDA.so (0x00007f5eafdef000)
	libOpenMM.so => /home/asghar/anaconda3/envs/py3.7/lib/plugins/../libOpenMM.so (0x00007f5eaf893000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f5eaf68f000)
	libcuda.so.1 => /lib64/libcuda.so.1 (0x00007f5eae489000)
	libcufft.so.10 => not found
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f5eae26d000)
	libstdc++.so.6 => /home/asghar/anaconda3/envs/py3.7/lib/plugins/../libstdc++.so.6 (0x00007f5eb0708000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f5eadf6b000)
	libgcc_s.so.1 => /home/asghar/anaconda3/envs/py3.7/lib/plugins/../libgcc_s.so.1 (0x00007f5eb06f3000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f5eadb9e000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f5eb066f000)
	libcufft.so.10 => not found
</pre>

If I do ```export OPENMM_CUDA_COMPILER=`which nvcc` ```  I get the same results as above when testing OpenMM.

**Comment by peastman** [comment]
That's good progress.  If OpenCL is now working, that suggests it's now finding all files it needs from the driver.  The remaining ones, like nvrtc and cufft, come from the toolkit.  Since you installed the CUDA 10.1 version of OpenMM, you want to install a 10.1 compatible toolkit.  There are a couple of ways you can get that.  One is to download it from NVIDIA at https://developer.nvidia.com/cuda-toolkit-archive.  The installer will typically put it into `/user/local/cuda`.  Another option is to install it with conda.  The command should be something like `conda install cudatoolkit=10.1`.  That will put it somewhere inside your conda directory.  Either way, you then need to add the directory containing the toolkit's libraries to your LD_LIBRARY_PATH.  For example,

```
export LD_LIBRARY_PATH=/usr/local/cuda/lib64
```

With the next version of OpenMM this should all get simpler.  When you install it with conda, it will automatically download an appropriate toolkit as well.

**Comment by asgharrazavi** [comment]
The  `conda install cudatoolkit=10.1`  worked and now OpenMM can use CUDA as well :)
<pre>
python -m simtk.testInstallation

OpenMM Version: 7.4.2
Git Revision: dc9d188939ad630d240e89806b185061f7cd661a

There are 4 Platforms available:

1 Reference - Successfully computed forces
2 CPU - Successfully computed forces
3 CUDA - Successfully computed forces
4 OpenCL - Successfully computed forces

Median difference in forces between platforms:

Reference vs. CPU: 6.30576e-06
Reference vs. CUDA: 6.73574e-06
CPU vs. CUDA: 7.76155e-07
Reference vs. OpenCL: 6.75312e-06
CPU vs. OpenCL: 8.16099e-07
CUDA vs. OpenCL: 2.1727e-07

All differences are within tolerance.
</pre>

Libraries are all found:

<pre>
 ldd /home/asghar/anaconda3/envs/py3.7/lib/plugins/libOpenMMCudaCompiler.so
	linux-vdso.so.1 =>  (0x00007ffd95daf000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f5902a0c000)
	libnvrtc.so.10.1 => /home/asghar/anaconda3/envs/py3.7/lib/plugins/../libnvrtc.so.10.1 (0x00007f590129b000)
	libOpenMMCUDA.so => /home/asghar/anaconda3/envs/py3.7/lib/plugins/libOpenMMCUDA.so (0x00007f5900e2b000)
	libOpenMM.so => /home/asghar/anaconda3/envs/py3.7/lib/plugins/../libOpenMM.so (0x00007f59008cf000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f59006cb000)
	libcuda.so.1 => /lib64/libcuda.so.1 (0x00007f58ff4c5000)
	libcufft.so.10 => /home/asghar/anaconda3/envs/py3.7/lib/plugins/../libcufft.so.10 (0x00007f58f6e89000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f58f6c6d000)
	libstdc++.so.6 => /home/asghar/anaconda3/envs/py3.7/lib/plugins/../libstdc++.so.6 (0x00007f5902eb5000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f58f696b000)
	libgcc_s.so.1 => /home/asghar/anaconda3/envs/py3.7/lib/plugins/../libgcc_s.so.1 (0x00007f5902ea0000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f58f659e000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f5902e1c000)
</pre>


Thank you for the great software and the great support.

**Comment by peastman** [comment]
Yay!!!
