### ISSUE TITLE
Applying Damping Cofficient To Langevin 

### ISSUE THREAD

**Issue by Bio-Otto** [openmm/openmm#2860]
I want to use **langevinIntegrator** in my system but I could not find how to specify "_damping coefficient_".

Also, is it possible to update the "**nonbonded pair list**" on-demand? For example, every 10 steps.

**Comment by peastman** [comment]
The friction coefficient is one of the arguments you pass to the LangevinIntegrator's constructor.

Neighbor lists are part of the internal implementation.  You don't need to do anything about them.  It automatically figures out how to do the calculation in an optimal way while ensuring no interactions are ever missed.

**Comment by Bio-Otto** [comment]
@peastman thank you so much for clarity and for your quick response.
