### ISSUE TITLE
Energy conservation depends on initial conditions

### ISSUE THREAD

**Issue by VickyLu001** [openmm/openmm#2862]
Hi,

Thanks for the amazing software. I encountered an issue for energy conservation recently. I set a toy system, where I have two chains of beads, and beads in the same chain are connected with nearest neighbors via a harmonic bond. That is:

Chain 1: 0-2-4-6,
Chain 2: 1-3-5-7.

Numbers represent beads and '-' represents harmonic bonds here. I used the VerletIntegrator, which should conserve energy. My codes are below(the units are a mess since I'm trying to use reduced units, but I guess that's not what causes the problem.)
```
from simtk.openmm.app import *
from simtk.openmm import *
from simtk.unit import *
import numpy as np
def ho_force(k = 3513, r0 = 2, nAtom = 8):
    ho = CustomBondForce("0.5*k_con*(r-r0)^2")
    ho.addGlobalParameter("k_con", k)
    ho.addGlobalParameter("r0", r0)
    for i in range(nAtom-2):
        ho.addBond(i,i+2)
    return ho

steps = 10**8
frequency = 10**4
platform = Platform.getPlatformByName("CUDA")
pdb_filename = "eightBeads.pdb"
xml_filename = "HO.xml"
precision = "mixed"
velocity = # see discussion below

pdb = PDBFile(pdb_filename)
forcefield = ForceField(xml_filename)
system = forcefield.createSystem(pdb.topology)
nAtom = pdb.topology.getNumAtoms()

system.addForce(ho_force(nAtom = nAtom))
integrator = VerletIntegrator(0.2*0.001/2.75*picoseconds)
simulation = Simulation(pdb.topology, system, integrator, platform, {'Precision':precision})

class ForceReporter(object):
    def __init__(self, file, reportInterval):
        self._out = open(file, 'w')
        self._reportInterval = reportInterval
    def __del__(self):
        self._out.close()
    def describeNextReport(self, simulation):
        steps = self._reportInterval - simulation.currentStep%self._reportInterval
        return (steps, False, False, True, False)
    def report(self, simulation, state):
        forces = state.getForces(True).value_in_unit(kilojoules/mole/nanometer)
        for index,f in enumerate(forces):
            self._out.write('%d %d %.15f %.15f %.15f\n' % (simulation.currentStep, index, f[0], f[1], f[2]))

class PositionReporter(object):
    def __init__(self, file, reportInterval):
        self._out = open(file, 'w')
        self._reportInterval = reportInterval
    def __del__(self):
        self._out.close()
    def describeNextReport(self, simulation):
        steps = self._reportInterval - simulation.currentStep%self._reportInterval
        return (steps, True, False, False, False)
    def report(self, simulation, state):
        positions = state.getPositions(True).value_in_unit(nanometer)
        for index,p in enumerate(positions):
            self._out.write('%d %d %.15f %.15f %.15f\n' % (simulation.currentStep, index, p[0], p[1], p[2]))

positions = np.array(pdb.positions)
simulation.context.setPositions(positions)
simulation.context.setVelocities(velocity)
#simulation.minimizeEnergy()
simulation.reporters.append(PDBReporter('output.pdb', frequency))
simulation.reporters.append(ForceReporter('force.out',frequency))
simulation.reporters.append(PositionReporter('position.out',frequency))
simulation.reporters.append(StateDataReporter("StateDataReporter.out", frequency, step=True,
         potentialEnergy=True, kineticEnergy = True, totalEnergy = True, temperature=True))
simulation.step(steps)
```

When you assigned random velocity to each bead, say
```
velocity = [Vec3(x=0.4568040858446034, y=-0.9844556465043288, z=-0.7170264464330172), Vec3(x=-1.0994917118360785, y=0.3468974309184162, z=-0.9469091464756022), Vec3(x=1.4965325266476333, y=0.46764260898927623, z=-1.7144691870401831), Vec3(x=1.0161916441780974, y=0.7254643970052022, z=1.2483130108752158), Vec3(x=-0.42879183914243163, y=0.052331472142714164, z=-1.2856063651707252), Vec3(x=-0.6127192957747496, y=-0.1608138877896948, z=1.2962055433769788), Vec3(x=0.9892034552519253, y=-0.7927516532684038, z=0.43176758956020783), Vec3(x=-1.8177292873349946, y=0.34568518164611517, z=1.687725342145787)]
```
The total energy won't conserve and it's already obvious at 1e8 steps as shown in the figure below. If you run it longer it will further explore.
![f1](https://github.com/VickyLu001/image/blob/master/f1.png)
And I calculated the force based on the distance between the beads and that reported by openmm. Surprisingly, the length of the **(calculated force vector minus reported force vector) is also increasing with time**. However, the force calculation should only depend on the current positions, right?
![f2](https://github.com/VickyLu001/image/blob/master/f2.png)
Besides, if you assign the same velocity for both chains, say
```
velocity = [Vec3(x=0.4568040858446034, y=-0.9844556465043288, z=-0.7170264464330172), Vec3(x=0.4568040858446034, y=-0.9844556465043288, z=-0.7170264464330172), Vec3(x=1.4965325266476333, y=0.46764260898927623, z=-1.7144691870401831), Vec3(x=1.4965325266476333, y=0.46764260898927623, z=-1.7144691870401831), Vec3(x=-0.42879183914243163, y=0.052331472142714164, z=-1.2856063651707252), Vec3(x=-0.42879183914243163, y=0.052331472142714164, z=-1.2856063651707252), Vec3(x=0.9892034552519253, y=-0.7927516532684038, z=0.43176758956020783), Vec3(x=0.9892034552519253, y=-0.7927516532684038, z=0.43176758956020783),]
```
The energy is conserved,
![f3](https://github.com/VickyLu001/image/blob/master/f3.png)
and the force difference is not increasing.
![f4](https://github.com/VickyLu001/image/blob/master/f4.png)

My HO.xml file is
```
<ForceField>
 <!-- Specify atom types -->
 <AtomTypes>
  <Type name="I" class="I" element="N" mass="1"/>
 </AtomTypes>
 <!-- Setup residue templates -->
 <Residues>
  <Residue name="BEAD">
   <Atom name="I" type="I"/>
  </Residue>
 </Residues>
</ForceField>
```
and my eightBeads.pdb is
```
ATOM      1  I   BEADA   1       0.0     0.0    20.0    1.00  0.00      SYST N
ATOM      2  I   BEADA   2      10.0     0.0    20.0    1.00  0.00      SYST N
ATOM      3  I   BEADA   3       0.0     0.0    40.0    1.00  0.00      SYST N
ATOM      4  I   BEADA   4      10.0     0.0    40.0    1.00  0.00      SYST N
ATOM      5  I   BEADA   5       0.0     0.0    60.0    1.00  0.00      SYST N
ATOM      6  I   BEADA   6      10.0     0.0    60.0    1.00  0.00      SYST N
ATOM      7  I   BEADA   7       0.0     0.0    80.0    1.00  0.00      SYST N
ATOM      8  I   BEADA   8      10.0     0.0    80.0    1.00  0.00      SYST N
```

**Comment by peastman** [comment]
Is the system gradually migrating away from the origin?  You specified mixed precision, which means the forces are calculated in single precision.  As the particles move away from the origin, calculating distances between them becomes less precise.

By default ForceField includes a CMMotionRemover which will *mostly* prevent the center of mass from moving.  But it isn't a strict constraint.  It sets the overall center of mass momentum to zero at each step, and that's only correct up to the limits of numerical precision.  And 10^8 steps is a lot, so tiny errors will add up.

**Comment by VickyLu001** [comment]
> Is the system gradually migrating away from the origin? You specified mixed precision, which means the forces are calculated in single precision. As the particles move away from the origin, calculating distances between them becomes less precise.
> 
> By default ForceField includes a CMMotionRemover which will _mostly_ prevent the center of mass from moving. But it isn't a strict constraint. It sets the overall center of mass momentum to zero at each step, and that's only correct up to the limits of numerical precision. And 10^8 steps is a lot, so tiny errors will add up.

Thanks for the quick reply. Yes, double precision does solve the problem. However, I'm still confused.  I tried the system with periodic boundary conditions at mixed precision using code below, which should prevent the chains migrating too far but the energy is still exploding.

Also, I'm reporting positions at %.15f with my custom PositionReporter so my calculation on force based on bond length shouldn't be affected. When you mentioned "As the particles move away from the origin, calculating distances between them becomes less precise." do you mean that happens when openmm calculates the distances? I thought for mixed precision, the integration is done in double precision so the distance shouldn't be a problem in my system

```
def ho_force(k = 3513, r0 = 2, nAtom = 8):
    ho = CustomBondForce("0.5*k_con*(r-r0)^2")
    ho.addGlobalParameter("k_con", k)
    ho.addGlobalParameter("r0", r0)
    for i in range(nAtom-2):
        ho.addBond(i,i+2)
    ho.setUsesPeriodicBoundaryConditions(periodic = True)#This line set periodic boundary condition
    return ho
```

**Comment by peastman** [comment]
> do you mean that happens when openmm calculates the distances?

Correct.

> I thought for mixed precision, the integration is done in double precision so the distance shouldn't be a problem in my system

Integration is done in double precision, but forces are calculated in single precision.  That means the atom positions are all truncated to single precision before being passed to the routines that calculate forces.  If you add a large constant to all of the positions, the precision of each one (and hence the precision of differences between them) decreases.

>  I tried the system with periodic boundary conditions at mixed precision using code below, which should prevent the chains migrating too far but the energy is still exploding.

That surprised me a bit at first: normally when using periodic boundary conditions, it stores the positions internally as an integral number of box widths plus a position modulo the box width.  That avoids loss of precision, no matter how far it drifts.  But I just looked at the code, and I see that only happens if you use periodic boundary conditions for *nonbonded* interactions.  Since you don't have any nonbonded interactions, that code doesn't get activated and the positions just get stored as a single float.

**Comment by peastman** [comment]
By the way, a simple workaround for this problem would be to periodically calculate the centroid of the particle coordinates and shift them all back to the origin.  It wouldn't need to be done very often, so the effect on performance would be negligible.

**Comment by VickyLu001** [comment]
Thanks for your explanation. This makes sense to me. 

Besides, I have one more question: the force at step 1 is not 0. My beads are placed at balanced positions(as shown in my eightBeads.pdb) so at step 1 there shouldn't be a force. Only after it moves a little bit due to initial velocities, at step 2 there should be non-zero forces. Initially, I thought that's because I used the leap-frog verlet integrator, so I write a custom integrator, but I still get non-zero forces at step 1.
```
class CustomVerletIntegrator(openmm.CustomIntegrator):
    def __init__(self, timestep=1.0 * unit.femtoseconds):
        super(CustomVerletIntegrator, self).__init__(timestep)
        self.addUpdateContextState()
        self.addComputePerDof("v", "v+dt*f/m")
        self.addComputePerDof("x", "x+dt*v")
```

The force on the 8 beads reported at step 1 with my custom integrator is ( step, bead, fx, fy, fz)
```
1 0 -0.000009634764865 -0.000013455981389 -0.254822726594284
1 1 0.000043147243559 0.000007720431313 0.560880786506459
1 2 0.000001962529495 0.000011801021174 0.364411300281063
1 3 -0.000043872743845 -0.000008115079254 -0.548628705553710
1 4 0.000030295923352 -0.000011828029528 0.329197527840734
1 5 -0.000003657769412 0.000002237036824 0.087785606505349
1 6 -0.000022623687983 0.000013482989743 -0.438786101527512
1 7 0.000004383269697 -0.000001842388883 -0.100037687458098
```

**Comment by peastman** [comment]
Reporters get called at the end of the step, so it's already taken one step at that point.  Try calling `simulation.context.getState(getForces=True).getForces()` before taking the first step.  Are the forces zero?
