### ISSUE TITLE
benchmark.py tests occasionally fail

### ISSUE THREAD

**Issue by ncf0003** [openmm/openmm#2864]
@peastman 

Just in case this is at all helpful I ran the script ten times to see which test it failed on:

Test: pme (cutoff=0.9)
Test: apoa1pme
Finished
Test: apoa1rf
Finished
Test: apoa1rf
Test: apoa1rf
Test: apoa1pme
Test: apoa1rf
Test: apoa1rf

**Comment by ncf0003** [comment]
Suppose I'm now also sorta concerned with the compilation (#2840) is because the systems I was running on the opencl from the conda install were working without fail and now on the compiled CUDA they don't seem to run more than two minutes.

**Comment by peastman** [comment]
What version were you using before, and what version are you using now?

**Comment by ncf0003** [comment]
Openmm from conda is version 7.4.1, build py37_cuda101_rc_1 from channel omnia. 

And according to git reflog this is the commit I compiled on our HPC.
817fd3b HEAD@{1}: clone: from https://github.com/openmm/openmm.git

**Comment by peastman** [comment]
Here's what I've found so far.

The benchmark failures don't seem to be an equilibration problem.  If I run more equilibration and use the resulting structure to start the benchmark, it doesn't help.  Also, the longer I run the benchmark the higher the chance of it failing, which isn't what you'd expect if it were just a problem in the starting structure.

This may be related to us switching our standard benchmark from LangevinIntegrator with 2 fs step to LangevinMiddleIntegrator with 4 fs step.  The current settings seem to be pushing the edge of stability.  If I reduce the step size from 4 fs to 3.5 fs, it becomes much more stable.

To test whether this is a bug in LangevinMiddleIntegrator, I tried using BAOABIntegrator from openmmtools, but the results are exactly the same.  It also fails regularly.

@jchodera you've been running lots of simulations with BAOAB and 4 fs, right?  Have you encountered any cases where this is unstable?  Could you take a look at the settings in benchmark.py to see if they look reasonable?  Have you been using 7.4.2, 7.5, or both?  Have you noticed any difference in stability between them?

**Comment by peastman** [comment]
@jchodera any insight on this?

**Comment by peastman** [comment]
I've been looking into this more, and I think it may involve some kind of resonance in the ApoA1 system.  For a variety of step sizes I ran the benchmark ten times, each time for 60 seconds, and recorded how many of the ten runs failed.  Here are the results.

3.5: 0
3.6: 0
3.7: 10
3.8: 10
3.9: 1
4.0: 7
4.1: 10

As you increase the step size, it abruptly goes from passing every time to failing every time.  Then you increase it further and it gets better again!  Furthermore, turning on a small amount of HMR (hydrogen mass 1.5 amu) makes the errors go away.  Constraining bond lengths, on the other hand, doesn't seem to help.  This seems like some sort of a resonance effect when the step size lines up with a resonant frequency.  Another argument for that is that I only see it happen with ApoA1, not DHFR.  Perhaps something in the lipids?
