### ISSUE TITLE
OpenCL 2.0 Device kernel enqueue

### ISSUE THREAD

**Issue by bdenhollander** [openmm/openmm#2867]
OpenCL 2.0 added the ability for an executing kernel to enqueue a kernel on the same device. Would this feature be useful in OpenMM to reduce repeated launches of small kernels or make recursion easier? 

[enqueue_kernel](https://www.khronos.org/registry/OpenCL/specs/2.2/html/OpenCL_C.html#enqueuing-kernels) in OpenCL documentation

Intel has a [QuickSort](https://software.intel.com/content/www/us/en/develop/articles/gpu-quicksort-in-opencl-20-using-nested-parallelism-and-work-group-scan-functions.html) tutorial and performance comparisons on [slides 25-26](https://www.iwocl.org/wp-content/uploads/iwocl-2015-talk-Robert-Ioffe-Intel.pdf).

**Comment by peastman** [comment]
Since neither NVIDIA nor Apple supports OpenCL 2.0, it's unfortunately not an option for us.

**Comment by informatorius** [comment]
But AMD supports it so maybe that could be an option to compile for AMD OpenCl 2.0 with that performance option enabled?

**Comment by peastman** [comment]
Not without major restructuring and complex workarounds to make it still compile on the older version.  Also, there's nothing we want it for.  We don't use this feature on CUDA either.
