### ISSUE TITLE
NVIDIA 3080/3090 FP32 Units

### ISSUE THREAD

**Issue by bdenhollander** [openmm/openmm#2868]
> In the Turing generation, each of the four SM processing blocks (also called partitions) had two primary datapaths, but only one of the two could process FP32 operations. The other datapath was limited to integer operations. GA10X includes FP32 processing on both datapaths, doubling the peak processing rate for FP32 operations. One datapath in each partition consists of 16 FP32 CUDA Cores capable of executing 16 FP32 operations per clock. Another datapath consists of both 16 FP32 CUDA Cores and 16 INT32 Cores, and is capable of executing either 16 FP32 operations OR 16 INT32 operations per clock. As a result of this new design, each GA10x SM partition is capable of executing either 32 FP32 operations per clock, or 16 FP32 and 16 INT32 operations per clock. All four SM partitions combined can execute 128 FP32 operations per clock, which is double the FP32 rate of the Turing SM, or 64 FP32 and 64 INT32 operations per clock.

Source: [NVIDIA AMPERE GA102 GPU ARCHITECTURE](https://www.nvidia.com/content/dam/en-zz/Solutions/geforce/ampere/pdf/NVIDIA-ampere-GA102-GPU-Architecture-Whitepaper-V1.pdf)

Does OpenMM need any adjustments to be aware of the extra FP32 units in order to schedule enough work to fill the GPU? [Here](https://github.com/openmm/openmm/blob/fd667c743a65bdabe62ccc1b9f9b02b7e120db18/platforms/cuda/src/CudaContext.cpp#L213) and [here](https://github.com/openmm/openmm/blob/fd667c743a65bdabe62ccc1b9f9b02b7e120db18/platforms/cuda/src/CudaContext.cpp#L250) look like good starting points for investigation.

**Comment by peastman** [comment]
This is completely invisible to the program.  It just means the instruction scheduler has more options in how it executes your code.

**Comment by bdenhollander** [comment]
3080 vs. 2080 Ti in #2865 seems a bit lacklustre considering the jump from [13.45](https://www.techpowerup.com/gpu-specs/geforce-rtx-2080-ti.c3305) to [29.77](https://www.techpowerup.com/gpu-specs/geforce-rtx-3080.c3621) FP32 max TFLOPS. If OpenMM is splitting work into chunks assuming half of the 8704 shaders exist based on previous architectures, that might explain why there isn't a 50%+ performance increase.

Part of the fixes for Navi in #2367 was increasing the number of threads per compute unit.

**Comment by peastman** [comment]
Don't put too much weight on specs like that.  They're largely marketing numbers with limited connection to real world performance, which is a complex mix of integer, floating point, memory latency, memory bandwidth, cache performance, etc.  Also keep in mind that the numbers in that issue are for DHFR, which is a pretty small protein.  Even 2080 Ti is already too wide for that system to keep it busy.  There's no benefit to adding more compute units when you aren't even fully utilizing the ones you already have.  You'll see better performance on large systems.

I've been working on optimizing for Ampere and I've managed to speed it up a little bit relative to those numbers, but nothing dramatic.

**Comment by jchodera** [comment]
The DHFR system is very small, and may not effectively utilize "wide" GPUs like the 2080 and 3080. Here's a benchmark for the SARS-CoV-2 spike protein (448,584 atoms). Note the much larger difference between the 3080 and 2080 (15 -> 24 ns/day, or a 60% increase):
![image](https://user-images.githubusercontent.com/3656088/94352599-f6394f00-001b-11eb-8455-b374323727e1.png)

**Comment by bdenhollander** [comment]
2080 -> A100 speedup makes sense. A100 has 2x max FP32 FLOPS and 3x memory bandwidth.
2080 -> 3080 seems low. 3080 has almost 3x max FP32 FLOPS and 1.7x memory bandwidth.

A100 does have the advantage of 25% higher TDP than 3080 so it would be more likely to reach it's max FLOPS rating.

**Comment by peastman** [comment]
That sounds like memory makes more difference in this benchmark than FLOPS.
