### ISSUE TITLE
CUDA vs OpenCL pcie bus bandwidth on Windows

### ISSUE THREAD

**Issue by informatorius** [openmm/openmm#2873]
FAH cuda core shows much less pcie bandwidth usage on Windows than with FAH OpenCL core. And cuda core has 25% better performance than opencl core. That may be a hint for opencl implementation of OpenMM that the pcie bandwidth usage is not optimized yet on Windows? And maybe fixing that may also increase OpenCL performance?

**Comment by peastman** [comment]
PCIe bandwidth should be minimal in all cases.  We try as much as possible to do everything on the GPU, rarely bringing any data back to the CPU.  If PCIe bandwidth is having a significant effect on performance, something is wrong.

**Comment by peastman** [comment]
The difference in speed comes from the kernels executing faster.

**Comment by informatorius** [comment]
![FAH_P13426_CUDA_vs_OpenCL](https://user-images.githubusercontent.com/6989214/94842329-8e1faa00-041b-11eb-9537-96e8717374ab.png)

**Comment by informatorius** [comment]
clEnqueueMapBuffer / clEnqueueUnmapMemObject I did not find in OpenMM code?
https://forum.byte-welt.net/t/how-to-use-clenqueuemapbuffer-and-clenqueueunmapmemobject/6228
