### ISSUE TITLE
Energy decomposition of a charged species wrt the rest of system

### ISSUE THREAD

**Issue by frank-stonybrook** [openmm/openmm#2874]
I am interested in quantifying the potential energy contribution of a charge species with respect to the rest of the system  simulated in the explicit solvent environment. To make the thing simple, let say a **Na+** ion with the rest protein and water molecules in a water box. After looking through some of the posts here (like #2682 ), a possible solution will be to 'mask' the ion by changing the nb parameters to zero.  The potential energy difference between original and masked system will be the contribution from this ion. 

While I have two questions:

1. Simply disappearing the **Na+** ion will cause the net charge of the box to be non neutral, therefore the electrostatic interaction computed using PME in the masked system is not valid, right? I assume that there must be something complicated than that. The **CPPTRAJ** in AmberTools has [a function](https://amber-md.github.io/cpptraj/CPPTRAJ.xhtml#toc-Subsection-11.30) that can do it pretty easily, but I don't know what's happening there under the hood. 

1. Is there a way to output amber topology from OpenMM's simulation object? The reason for this is that I am also interested in some immediate states along the transition path where the ion might 'partially exist' in the system and our existing codebase which build around OpenMM can easily perform this transition. In the worst case, I would like to extract an amber topology and use cpptraj to perform the calculation if the easy solution outline above not working.  Parmed has a feature that can take OpenMM topology and parse it:
```python
parmed.openmm.load_topology(aOpenMMSimulationObject.topology)
```
but I got warning the topology not parametrized. Atom types and bond types information are all missing after parsing by parmed. I just want to know whether this is a supported/recommended feature to extract topology from OpenMM simulation.

Any comment or suggestion are appreciated!

**Comment by peastman** [comment]
PME implicitly forces the system to be neutral by ignoring the zero frequency contribution in the reciprocal space calculation.  This is equivalent to assuming that all of space is filled with a uniform charge density just right to neutralize the system.

I haven't tried using ParmEd to convert a topology from OpenMM to Amber, but that seems like the approach to take.

**Comment by frank-stonybrook** [comment]
> PME implicitly forces the system to be neutral by ignoring the zero frequency contribution in the reciprocal space calculation. This is equivalent to assuming that all of space is filled with a uniform charge density just right to neutralize the system.

Thanks for your clarification @peastman! Once the PME algorithm adds a uniformly distributed charge density to the perturbed system, which the Na+ ion has beed disappeared, then technically this system is not the same one as in the original system, right? Therefore, the relative potential energy difference between perturbed system and the original one will not be exactly equal to the ion's contribution?

> I haven't tried using ParmEd to convert a topology from OpenMM to Amber, but that seems like the approach to take.

Okay. I will take a look of Parmed documentation and see whether I miss anything. But I am curious whether the `OpenMMSimulationObject.topology` still contains the atom type and bond type information.

**Comment by peastman** [comment]
> Once the PME algorithm adds a uniformly distributed charge density to the perturbed system, which the Na+ ion has beed disappeared, then technically this system is not the same one as in the original system, right?

Correct.  "The ion's contribution to the energy" is not a well defined concept.  You really mean the difference in energy between two systems, one that includes the ion and one that doesn't.  But if one of those systems is charged and the other isn't, that makes them very different.  You should consider exactly what the scientific question is that you're trying to answer, then try to work out a simulation protocol that you can rigorously show will answer that question.

**Comment by frank-stonybrook** [comment]
Thanks! I will take a look how other people formulate this question.

**Comment by frank-stonybrook** [comment]
I reopen this issue regarding the uniform charge neutralization approach. I read in some references saying that neutralize the system by ignoring the zero frequency contribution would require accounting the self-energy of this background charge as well as its interaction with each point charge in the system. Since in the derivation I don't see these two terms dedicated for the background charge, I would like to know how these two parts are handled.

**Comment by peastman** [comment]
I see this question was never answered.  Ignoring the zero frequency contribution is equivalent to a neutralizing plasma in that they produce identical forces.  You're correct that the energies are different, since the latter would involve a self energy term.  But that's just a constant offset.

**Comment by frank-stonybrook** [comment]
Thanks for answering the follow-up question! It clarifies my doubts.
