### ISSUE TITLE
Competitable Anaconda distrubution and CUDA version for Running OpenMM smoothly? 

### ISSUE THREAD

**Issue by rijuaxt** [openmm/openmm#2879]
Hello,

I was trying to install OpenMM on latest anacodna distribution using the code as given in openmm installation guide under documentation panel. It failed and showed that python 3.8 is not supported for OpenMM. Apart from that, it showed an error with CUDA version.  I have had latest 11.0 CUDA installed with my RTX 2080 Ti GPU. 

I was wondering if anyone could suggest me which distribution of anaconda and version of CUDA have to be installed on Windows for running the latest OpenMM or stable release of it?

**Comment by mattwthompson** [comment]
Try Python 3.7 and CUDA 10.1

**Comment by jchodera** [comment]
We're working on the migration to conda-forge for the release of OpenMM 7.5.0, which will allow us to automatically distribute the appropriate `cudatoolkit` from anaconda cloud. For now, you can try the preview builds here, which support Python 3.8 and CUDA 11.0:

https://anaconda.org/omnia-dev/openmm/files

```bash
conda install -c omnia-dev/label/cuda110 openm
```

**Comment by rijuaxt** [comment]
Thanks . The problem has been solved
