### ISSUE TITLE
Simulating protein-ligand complex from minimization to production within the same file

### ISSUE THREAD

**Issue by divya938** [openmm/openmm#2881]
I am new to openmm. I have created amber format input files that is prmtop and incrpdb file using ambertools.

- Initially, I want to minimize the protein-ligand complex and save the coordinates every 1000 steps of the minimization process.

- The coordinates from the minimization step will be the starting coordinates from simulated annealing starting from 0 K to 300 K in NPT ensemble.

- The coordinates from the previous step will feed to the equilibrium simulations at 300 K temperature and 1 bar pressure.

- Finally the priduction run.

Here it is the piece of code:

#This file takes input files created from ambertools
#................USAGE...............#
#python openmmamber_minimize.py  .prmtopfile_name .inpcrdfile_name
#................USAGE...............#
from __future__ import print_function
from simtk.openmm.app import *
from simtk.openmm import *
from simtk.unit import *
from sys import stdout

platform = Platform.getPlatformByName('CUDA')
properties = {'DeviceIndex': '0,1', 'Precision': 'mixed'}

# Reading Amber topology and coordinates 

topo_file=sys.argv[1]
coor_file=sys.argv[2]

#prmtop = AmberPrmtopFile('input.prmtop')
#inpcrd = AmberInpcrdFile('input.inpcrd')

# Loading Amber topology and coordinates
prmtop = AmberPrmtopFile(topo_file)
inpcrd = AmberInpcrdFile(coor_file)

# Select simulation parameters
print ('Creating System')

system = prmtop.createSystem(nonbondedMethod=PME, nonbondedCutoff=1*nanometer,
        constraints=HBonds)
integrator = VerletIntegrator(1*femtosecond)
simulation = Simulation(prmtop.topology, system, integrator,platform, properties)

#Setting initial condition
print('Setting initial condition')
simulation.context.setPositions(inpcrd.positions)

if inpcrd.boxVectors is not None:
    simulation.context.setPeriodicBoxVectors(*inpcrd.boxVectors)

# output files
simulation.minimizeEnergy(maxIterations=10000)
logperiod = 1000
dcdperiod = 1000
simulation.reporters.append(DCDReporter('complex_minimize.dcd', dcdperiod))
simulation.reporters.append(StateDataReporter('minimize.log', logperiod, step=True,
       time=True, potentialEnergy=True, kineticEnergy=True, totalEnergy=True,
       temperature=True, volume=True, density=True, separator='\t'))
print ('Geometry optimization done!!!')

minpositions = simulation.context.getState(getPositions=True,enforcePeriodicBox=False).getPositions()
PDBFile.writeFile(prmtop.topology, minpositions, open('final_minimize.pdb', 'w'))

# Run the MD simulation to perform NPT simulation and anneal it from 0 K to 300 K.
print('Running MD')

mdsteps = 5000
pdb = PDBFile('final_minimize.pdb')
simulation.context.setPositions(pdb.positions)

for i in range(0, 300, 10):
     check_name = 'heat'+str(i)+'K.chk'
     simulation.context.setVelocitiesToTemperature(i*kelvin)
     system = prmtop.createSystem(nonbondedMethod=PME, nonbondedCutoff=1*nanometer,
        constraints=HBonds)
     integrator = LangevinIntegrator(i*kelvin, 1/picosecond, 1.0*femtosecond)
     system.addForce(MonteCarloBarostat(1*bar, i*kelvin))
     simulation = Simulation(prmtop.topology, system, integrator, platform, properties)
     simulation.step(mdsteps)
     simulation.reporters.append(CheckpointReporter(check_name,500))
     simulation.reporters.append(DCDReporter('heat.dcd', dcdperiod))
     simulation.reporters.append(StateDataReporter('heat.log', logperiod, step=True,
       time=True, potentialEnergy=True, kineticEnergy=True, totalEnergy=True,
       temperature=True, volume=True, density=True, separator='\t'))
     finalpositions = simulation.context.getState(getPositions=True).getPositions()
     outfile = 'heat'+str(i)+'k.pdb'
     PDBFile.writeFile(prmtop.topology, finalpositions, open(outfile, 'w'))
     pdb = PDBFile(outfile)
     simulation.context.setPositions(pdb.positions)

# setting up equilibrium simulations at 300 K temperature

mdsteps        = 25000000 ; # 2.5 ns
dcdsteps       = 1000
logsteps       = 1000
Eq_temperature = 300*kelvin
outfile        = complex_eq

system = prmtop.createSystem(nonbondedMethod=PME, nonbondedCutoff=1*nanometer,
        constraints=HBonds)
integrator = LangevinIntegrator(Eq_temperature, 1/picosecond, 1.0*femtosecond)
system.addForce(MonteCarloBarostat(1*bar, Eq_temperature))
simulation = Simulation(prmtop.topology, system, integrator, platform, properties)
simulation.step(mdsteps)
simulation.reporters.append(CheckpointReporter('complex_eq.chk',500))
simulation.reporters.append(DCDReporter('complex_eq.dcd', dcdperiod))
simulation.reporters.append(StateDataReporter('complex_eq.log', logperiod, step=True,
       time=True, potentialEnergy=True, kineticEnergy=True, totalEnergy=True,
       temperature=True, volume=True, density=True, separator='\t'))
finalpositions = simulation.context.getState(getPositions=True).getPositions()
PDBFile.writeFile(prmtop.topology, finalpositions, open(outfile+'.pdb', 'w'))
pdb = PDBFile(outfile+'.pdb')
simulation.context.setPositions(pdb.positions)

# setting up production simulations at 300 K temperature

mdsteps        = 2000000 ; # 4.0 ns
dcdsteps       = 500
logsteps       = 500
Eq_temperature = 300*kelvin
outfile        = complex_prod

system = prmtop.createSystem(nonbondedMethod=PME, nonbondedCutoff=1*nanometer,
        constraints=HBonds)
integrator = LangevinIntegrator(Eq_temperature, 1/picosecond, 2.0*femtosecond)
simulation = Simulation(prmtop.topology, system, integrator, platform, properties)
simulation.step(mdsteps)
simulation.reporters.append(CheckpointReporter('complex_prod.chk',500))
simulation.reporters.append(DCDReporter('complex_prod.dcd', dcdperiod))
simulation.reporters.append(StateDataReporter('complex_prod.log', logperiod, step=True,
       time=True, potentialEnergy=True, kineticEnergy=True, totalEnergy=True,
       temperature=True, volume=True, density=True, separator='\t'))
finalpositions = simulation.context.getState(getPositions=True).getPositions()
PDBFile.writeFile(prmtop.topology, finalpositions, open(outfile+'.pdb', 'w'))

print('Starting simulation with', num_steps, 'steps ...')
t0 = time.time()
simulation.step(num_steps)
t1 = time.time()
print('Simulation complete in', t1 - t0, 'seconds at', temperature)

**Comment by peastman** [comment]
Do you have particular questions?

Github is rendering your script as markdown, which makes it hard to read.  If you edit your post and add a line

\`\`\`

before and after the code, it will display correctly.

**Comment by divya938** [comment]
Hi,
I tried to run this code, the minimization step is fine, I have extracted the final coordinates from the minimization using this commands

**minpositions = simulation.context.getState(getPositions=True,enforcePeriodicBox=False).getPositions()
PDBFile.writeFile(prmtop.topology, minpositions, open('final_minimize.pdb', 'w'))**

The extracted .pdb file which is final_minimize.pdb fed as initial coordinates for simulated annealing 

**pdb = PDBFile('final_minimize.pdb')
simulation.context.setPositions(pdb.positions)**

The simulated annealing done using the following code

**for i in range(0, 300, 10):
        check_name = 'heat'+str(i)+'K.chk'
        simulation.context.setVelocitiesToTemperature(ikelvin)
        system = prmtop.createSystem(nonbondedMethod=PME, nonbondedCutoff=1nanometer,
        constraints=HBonds)
        integrator = LangevinIntegrator(ikelvin, 1/picosecond, 1.0femtosecond)
        system.addForce(MonteCarloBarostat(1bar, ikelvin))
        simulation = Simulation(prmtop.topology, system, integrator, platform, properties)
        simulation.step(mdsteps)
        simulation.reporters.append(CheckpointReporter(check_name,500))
        simulation.reporters.append(DCDReporter('heat.dcd', dcdperiod))
        simulation.reporters.append(StateDataReporter('heat.log', logperiod, step=True,
        time=True, potentialEnergy=True, kineticEnergy=True, totalEnergy=True,
        temperature=True, volume=True, density=True, separator='\t'))
        finalpositions = simulation.context.getState(getPositions=True).getPositions()
        outfile = 'heat'+str(i)+'k.pdb'
        PDBFile.writeFile(prmtop.topology, finalpositions, open(outfile, 'w'))
        pdb = PDBFile(outfile)
        simulation.context.setPositions(pdb.positions)**

At simulation.step(mdsteps): It is giving me the error as

File "openmmamber_minimize.py", line 67, in <module>
    simulation.step(mdsteps)
  File "/home2/divya.korlepara/softwares/anaconda3/lib/python3.7/site-packages/simtk/openmm/app/simulation.py", line 132, in step
    self._simulate(endStep=self.currentStep+steps)
  File "/home2/divya.korlepara/softwares/anaconda3/lib/python3.7/site-packages/simtk/openmm/app/simulation.py", line 197, in _simulate
    self.integrator.step(10) # Only take 10 steps at a time, to give Python more chances to respond to a control-c.
  File "/home2/divya.korlepara/softwares/anaconda3/lib/python3.7/site-packages/simtk/openmm/openmm.py", line 19017, in step
    return _openmm.LangevinIntegrator_step(self, steps)
Exception: Particle positions have not been set

I want to know how to get rid of this error?

**Comment by divya938** [comment]
For information, I used indentation inside for loop.

**Comment by divya938** [comment]
Hi could solve the issue using this piece of code for simulation annealing in NPT.

But the last line of the code which is used to save final PDB of the simulation. Which is not saving pdb with updated box dimensions. How to do that?

mdsteps   = 10000
dcdperiod = 1000
logperiod = 1000

for i in range(0, 300, 5):
     print('i',i,'PDB_file',pdb)
     check_name = 'heat'+str(i)+'K.chk'
    # prefix = 'heat'+str(i)
     simulation.context.reinitialize(preserveState=False)
     system = prmtop.createSystem(nonbondedMethod=PME, nonbondedCutoff=1*nanometer,
        constraints=HBonds)
     integrator = LangevinIntegrator(i*kelvin, 1/picosecond, 1.0*femtosecond)
     system.addForce(MonteCarloBarostat(1*bar, i*kelvin))
     simulation = Simulation(prmtop.topology, system, integrator, platform, properties)
     simulation.context.setPositions(pdb.positions)
     simulation.context.setVelocitiesToTemperature(i*kelvin)

     simulation.reporters.append(CheckpointReporter(check_name,500))
     #simulation.reporters.append(DCDReporter('heat.dcd', dcdperiod, append=True))
     #simulation.reporters.append(StateDataReporter('heat.log', logperiod, step=True,
     #  time=True, potentialEnergy=True, kineticEnergy=True, totalEnergy=True,
     #  temperature=True, volume=True, density=True, separator='\t', append=True))
     simulation.reporters.append(DCDReporter('heat'+str(i)+'K.dcd', dcdperiod))
     simulation.reporters.append(StateDataReporter('heat'+str(i)+'K.log', logperiod, step=True,
       time=True, potentialEnergy=True, kineticEnergy=True, totalEnergy=True,
       temperature=True, volume=True, density=True, separator='\t'))
     simulation.step(mdsteps)

     finalpositions = simulation.context.getState(getPositions=True, enforcePeriodicBox=True).getPositions()
     outfile = 'heat'+str(i)+'k.pdb'
     PDBFile.writeFile(prmtop.topology, finalpositions, open(outfile, 'w'))
     pdb = PDBFile(outfile)

**Comment by divya938** [comment]
> Do you have particular questions?
> 
> Github is rendering your script as markdown, which makes it hard to read. If you edit your post and add a line
> 
> ```
> 
> before and after the code, it will display correctly.

I am doing NPT simulations with simulated annealing for that I am using the following lines of code. The code I working fine but the stored trajectroy in pdb form has same box dimension though the density is changed during the course of simulation.

`for i in range(0, 300, 5):
        print('i',i,'PDB_file',pdb)
        check_name = 'heat'+str(i)+'K.chk'
        # prefix = 'heat'+str(i)
        simulation.context.reinitialize(preserveState=False)
        system = prmtop.createSystem(nonbondedMethod=PME, nonbondedCutoff=1nanometer,
        constraints=HBonds)
        integrator = LangevinIntegrator(i*kelvin, 1/*picosecond, 1.0*femtosecond)
       system.addForce(MonteCarloBarostat(1*bar, i*kelvin))
       simulation = Simulation(prmtop.topology, system, integrator, platform, properties)
       simulation.context.setPositions(pdb.positions)
       simulation.context.setVelocitiesToTemperature(i*kelvin)
       simulation.reporters.append(CheckpointReporter(check_name,500))
       simulation.reporters.append(DCDReporter('heat'+str(i)+'K.dcd', dcdperiod))
       simulation.reporters.append(StateDataReporter('heat'+str(i)+'K.log', logperiod, step=True,
                  time=True, potentialEnergy=True, kineticEnergy=True, totalEnergy=True,
                  temperature=True, volume=True, density=True, separator='\t'))
       simulation.step(mdsteps)

      finalpositions = simulation.context.getState(getPositions=True, enforcePeriodicBox=True).getPositions()
      outfile = 'heat'+str(i)+'k.pdb'
      PDBFile.writeFile(prmtop.topology, finalpositions, open(outfile, 'w'))
      pdb = PDBFile(outfile)`
       
      

- The generated PDB  does not have updated the box dimensions  

-  [Please help me how to do the simulation with updated box dimensions]

**Comment by peastman** [comment]
Once again, please edit your posts to mark the code correctly.  Otherwise it's very difficult to read.

>  Exception: Particle positions have not been set

You need to set the initial positions.  You're creating a Simulation and then immediately trying to take a step without ever telling it the initial positions of the particles:

```python
simulation = Simulation(prmtop.topology, system, integrator, platform, properties)
simulation.step(mdsteps)
```

You need to call `simulation.context.setPositions()` first.  See http://docs.openmm.org/latest/userguide/application.html#a-first-example.

> The code I working fine but the stored trajectroy in pdb form has same box dimension though the density is changed during the course of simulation.

That's an intrinsic problem in the PDB format: it only stores one set of box vectors at the very start, and can't reflect how they change over a simulation.  The DCD file should have correct box vectors in it, because that format does allow the box vectors to change over a simulation.

If you only want to save a single frame to a PDB file, a workaround is to first copy the box vectors from the most recent State over to the Topology.  That's where PDBFile gets them from.

```python
topology.setPeriodicBoxVectors(state.getPeriodicBoxVectors())
```

**Comment by divya938** [comment]
I tried these lines as you suggested.

```
state = simulation.context.getState(getPositions=True, getVelocities=True, enforcePeriodicBox=True)
Topology.setPeriodicBoxVectors(vectors=state.getPeriodicBoxVectors())
```


I got similar error.

**Traceback (most recent call last):
  File "openmmamber_minimize.py", line 51, in <module>
    Topology.setPeriodicBoxVectors(vectors=state.getPeriodicBoxVectors())
TypeError: setPeriodicBoxVectors() missing 1 required positional argument: 'self'**

**Comment by peastman** [comment]
`Topology` is the name of a class.  You need to call it on a specific Topology object.  In your case that would be `prmtop.topology`.
