### ISSUE TITLE
CudaCMAPTorsionForce: Tests all fail

### ISSUE THREAD

**Issue by ca-taylor** [openmm/openmm#2882]
After building OpenMM under CUDA 11.1.0 and running on an DGX A100 GPU, the following test all failed. 
------------------------------------------------------------------------------------------
48/288 Test  #48: TestCudaCMAPTorsionForceSingle .................***Failed    1.42 sec
        Start  49: TestCudaCMAPTorsionForceMixed
 49/288 Test  #49: TestCudaCMAPTorsionForceMixed ..................***Failed    1.74 sec
        Start  50: TestCudaCMAPTorsionForceDouble
 50/288 Test  #50: TestCudaCMAPTorsionForceDouble .................***Failed    2.09 sec

        Start  85: TestCudaCustomIntegratorMixed
 85/288 Test  #85: TestCudaCustomIntegratorMixed ..................***Failed   27.98 sec
-------------------------------------------------------------------------------------------

Sample Error Message...
[chasman@c47a-s3 build]$ ./TestCudaCMAPTorsionForce 
exception: Error launching CUDA compiler: 256
/scratch/local/59720226/openmmTempKernel0x275dba0_86665.cu(735): error: calling a constexpr __host__ function("fmin") from a __global__ function("computeBondedForces") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/scratch/local/59720226/openmmTempKernel0x275dba0_86665.cu(736): error: calling a constexpr __host__ function("fmin") from a __global__ function("computeBondedForces") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

2 errors detected in the compilation of "/scratch/local/59720226/openmmTempKernel0x275dba0_86665.cu".

**Comment by peastman** [comment]
Thanks!  This is a known issue that has already been fixed in the development code.  See #2694.  The fix will be in 7.5.
