### ISSUE TITLE
getState() got an unexpected keyword argument 'getPeriodicBoxVectors'

### ISSUE THREAD

**Issue by divya938** [openmm/openmm#2883]
I am trying to do simulation annealing from 0 to 300 K temperature? Here is the piece of code I am using.

<
from __future__ import print_function
from simtk.openmm.app import *
from simtk.openmm import *
from simtk.unit import *
from sys import *
import time

topo_file=sys.argv[1]
coor_file=sys.argv[2]

prmtop = AmberPrmtopFile(topo_file)
inpcrd = AmberInpcrdFile(coor_file)

print ('Creating System')

system = prmtop.createSystem(nonbondedMethod=PME, nonbondedCutoff=1*nanometer,
        constraints=HBonds)
integrator = LangevinIntegrator(0*kelvin, 1/picosecond, 1.0*femtosecond)
system.addForce(MonteCarloBarostat(1*bar, 0*kelvin))
simulation = Simulation(prmtop.topology, system, integrator, platform, properties)

#Setting initial condition
print('Setting initial condition')
simulation.context.setPositions(inpcrd.positions)

simulation.context.setPeriodicBoxVectors(*inpcrd.boxVectors)

simulation.minimizeEnergy()
simulation.step(1000)
 
state = simulation.context.getState(getPeriodicBoxVectors=True, getPositions=True, getVelocities=True, enforcePeriodicBox=True)
>

This is giving me error as follows:

**TypeError: getState() got an unexpected keyword argument 'getPeriodicBoxVectors'**

**Comment by Bio-Otto** [comment]
What is the version of openmm that you use?

**Comment by divya938** [comment]
I am using openmm 7.4.2

**Comment by frank-stonybrook** [comment]
According to definition [here](https://github.com/openmm/openmm/blob/cc3c4b54305fd53b535ddf26df15d9e1bb903e47/wrappers/python/src/swig_doxygen/swig_lib/python/extend.i#L143), `getPeriodicBoxVectors` is not a valid argument. If your system is in an explicit solvent, you should get the box vector information upon call the `getPosition` method.

**Comment by peastman** [comment]
States always include periodic box vectors.  You don't need an argument to tell it to include them.

**Comment by divya938** [comment]
@frank-stonybrook Whatever you said is true. Even I tried doing simulation with out `getPeriodicBoxVectors`, the simulation is working fine but after sometime it is giving me the error as

**Exception: Particle coordinate is nan**

I thought it could be due to the box dimensions.

 I tried to print the final positions in pdb format. I opened them, the box dimensions were not changed even though I am running NPT simulations.

The NPT simulation is working fine, which I checked from the log file, where the density is changing over time. That is why I am trying to assign box dimensions explicitly. 

So the main problem I am facing here is 

**Exception: Particle coordinate is nan**

Please help to figure out this.

**Comment by frank-stonybrook** [comment]
@divya938 To inspect box dimensions, you can call the `getPeriodicBoxVectors()` method on the OpenMM `state` object. It will extract the box vector. As for the Particle coordinate is nan, please refer to this excellent [Q&A article](https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions).
