### ISSUE TITLE
How to add an HbondedCustomForce in openmm? I am struggling to add donor-accetor. If I have 4 particles then how should I implement the Hbonded force? Please help.

### ISSUE THREAD

**Issue by LipikaBaidya** [openmm/openmm#2884]

**Comment by peastman** [comment]
Do you mean the donor or acceptor individually has four particles?  CustomHbondForce only allows a donor or acceptor to involve three particles.  Sorry.

**Comment by LipikaBaidya** [comment]
No, I don't mean that four particles.

**Comment by LipikaBaidya** [comment]
In the forcefield, there are r, theta,phi  value.  Now how should I implement it?How should I provide the values of r, theta,phi? Can you please give an example ? How to incorporate in force?

**Comment by peastman** [comment]
You need to look up how the force field defines those parameters.  Presumably they are distances and angles defined by particular sets of atoms. CustomHbondForce can compute whatever distances and angles you need, but it's up to you to tell it which ones to compute.  See http://docs.openmm.org/latest/api-c++/generated/OpenMM.CustomHbondForce.html#_CPPv2N6OpenMM16CustomHbondForceE.

**Comment by LipikaBaidya** [comment]
In the documentation:
CustomHbondForce* force = new CustomHbondForce("k*(distance(a1,d1)-r0)^2*(angle(a1,d1,d2)-theta0)^2");
how to provide the values a1,d1 or d2? In my system, there are many Hbonds present.

**Comment by peastman** [comment]
The expression is evaluated for each pair of interacting donors and acceptors.  The names "a1", "d1", etc. refer to particular particles in the donor and acceptor.  When you call `addDonor()` or `addAcceptor()`, you specify which particles they correspond to for that donor or acceptor.

**Comment by LipikaBaidya** [comment]
Thank you for the help.
