### ISSUE TITLE
Algorithms for calculating nonbonded forces

### ISSUE THREAD

**Issue by ThWuensche** [openmm/openmm#2890]
The current algorithm for calculating nonbonded forces is highly optimized, but needs a relevant amount of computing time for the preparations to the actual calculation. The following trace (for FAH banchmark RUN11) shows preparations to take more time than the actual calculation of nonbonded forces: 

![grafik](https://user-images.githubusercontent.com/70173377/96298462-c239c400-0ff2-11eb-91ca-09cfe6e4b3f6.png)

The nonbonded forces in turn dominate the total processing time. That situation seems to make it worthwhile to repeatedly consider alternative solutions. However of course openMM has a long history and I do not know what has been discussed or tried before.

One idea would be to divide a box containing the system into geometrically defined boxes with regular structure, so that it is easily visible what could be interacting neighbours without searching through the whole system.

Concept would be as such: A main box including the whole system is divided into smaller boxes of identical size, two in each dimension, so 8 sub-boxes in total. Sub-boxes exceeding a number of atoms would again be divided in a treelike structure in further 8 sub-boxes, two along each dimension. And so on, unless the subboxes are small enough to include only a manageable amount of atoms for processing nonbonded forces, probably smaller than the cutoff distance. For the calculation of interactions of atoms in each sub-box the neighbouring boxes to be included into the calculation would be identified by the geometric relation, such avoiding expensive searches. When atoms move out of a box and into another one, that should also be easy to calculate based on the fixed geometric structure.

Please let me know whether the idea is worthwhile to follow, simple nonsense or has been sorted out as unusable before.

**Comment by ThWuensche** [comment]
Needs to consider that the above trace results apply for AMD GCN and findBlocksWithInteractions has different implementations for GPUs with 32 or less threads per warp and the 64 threads per wavefront on AMD GCN. So before making any decision it would be required to analyze the share of preparation work compared to the actual calculation of nonbonded forces also for other architectures (NVidia), as maybe on other architectures that share is much lower. If that's the case the solution might also lie in a more efficient solution of that kernel for architectures with 64 threads per wavefront. Nicholas Curtis? That might have big effect on efficiency of openMM on AMD GCN, the runtime of that kernel makes up for 15% of total compute time in that test case.

**Comment by peastman** [comment]
There's a huge literature on methods of building neighbor lists.  All sorts of different approaches have been tried.  The closest thing to a "canonical" approach is to uniformly divide space into voxels whose width equals the cutoff distance.  For each atom you search through the 3x3x3 cube of boxes centered on the box that contains it.  OpenMM's CPU platform uses a variation on that approach, except we only subdivide along two dimensions, leaving long thin boxes spanning the width of the box along the third dimension.  Within each box we sort the atoms along that third dimension and check each atom against a range of atoms in the sorted sequence.  That requires checking fewer atoms than a simple subdivision would.

Hierarchical spatial subdivisions are mainly useful when dealing with things that are very non-uniformly distributed.  In typical MD simulations with water, the density of atoms is very uniform throughout the box, so a uniform subdivision ends up being more efficient.

**Comment by ThWuensche** [comment]
Thanks, I was not sure whether all simulations include water or other liquids filling the space, thus the hierarchical approach, which of course results in a uniform distribution (hierarchically accessed) in case of more-or-less even distribution of atoms. In vacuum or gases the hierarchical division probably would need less memory.

As you mention on CPU platform that approach is used, but not on GPUs, probably it turns out less effective on GPUs due to the SIMD structure, which will in an implementation divided by space, not atom count, leave some threads unused? Or was there another reason for the current GPU implementation, with the preparation effort being probably higher than in uniform cells in space?

I'm currently trying to optimize findBlockBounds. As currently each thread handles a complete tile, the total amount of threads even in relatively large systems will not fill all available threads. I'm trying to have one thread handle eight atoms and then unite the results, hoping for performance improvement. But just learning how to deal with that kind of parallelization, breaking my head. Will let you know of results.

**Comment by ThWuensche** [comment]
Seems my modified implementation of findBlockBounds cuts down execution time of the kernel to less then 1/2 for FAH benchmark RUN9 (~4000 atoms). It is still working without increase of the number of threads. I can't guarantee that it is correct, but at least does not generate NaNs. Here is the trace output, may be compared to that in the sortShortList issue:
![run9_mit_mod_findBlock](https://user-images.githubusercontent.com/70173377/96441372-b4aa5700-1209-11eb-938c-08be86c2bb99.png)

**Comment by ThWuensche** [comment]
I'm testing with different system sizes. While for low system sizes there is a small overall improvement, for larger system sizes the performance seems to drop. What makes me wonder is that the number of threads started equals the number of atoms (filled to tile size, observed on small system), while as far as I understand in the standard implementation one thread is needed for each tile, in above implementation 4 threads per tile. Could start of a high number of threads, which might not have work, actually have negative impact on performance? Or are all of them needed and I just don't understand how?

**Comment by ThWuensche** [comment]
The time savings for that kernel on a system with 60000 atoms is around 20%, so benefit for small systems (50% at 4071 atoms) is higher. But there seems to still be an error in calculation, the reduced overall performance is caused by longer execution times for computeNonbonded and sortBuckets, which lets me assume to still be caused by a bug in the code for findBlockBounds.

**Comment by peastman** [comment]
`findBlockBounds()` is a very minor kernel.  Your profile above for the unoptimized version shows it taking much less than 1% of the total time.  It isn't worth spending a lot of effort on it, and also not worth making the code more complicated for something that at best can only be a negligible speedup.

> As you mention on CPU platform that approach is used, but not on GPUs, probably it turns out less effective on GPUs due to the SIMD structure, which will in an implementation divided by space, not atom count, leave some threads unused?

The GPU uses what is essentially a full O(N^2) search, except it's really (N/32)^2, and in a way that parallelizes extremely well.  For a sufficiently large system that will become inefficient, but for the typical system sizes we work with it's very fast.

**Comment by ThWuensche** [comment]
I agree it is minor, overall (whole simulation) gains seem to be about 0.7% on very small (4000 atom) systems and 0.3% on middle (60000 atom) systems. For larger systems the - as you mention quadratic - effort for findBlocksWithInteractions gets more and more dominating. Of course it is much better to have higher gains, but considering the overall compute power in FAH to my understanding still makes 0.x% a relevant amount of compute time. In German there is a word "Kleinvieh mach auch Mist" or translated "Also small animals make manure" :).

But it's your decision, if you think it's not helpful I will not spend more time on that.

What do you think about the number of threads started (atom count threads started, but only atom count / 32 threads needed)? Could starting less threads save energy? Again only minor due to low share of that kernels runtime, but on FAH still would add up.

**Comment by ThWuensche** [comment]
> `findBlockBounds()` is a very minor kernel. Your profile above for the unoptimized version shows it taking much less than 1% of the total time. It isn't worth spending a lot of effort on it, and also not worth making the code more complicated for something that at best can only be a negligible speedup.
> 
> > As you mention on CPU platform that approach is used, but not on GPUs, probably it turns out less effective on GPUs due to the SIMD structure, which will in an implementation divided by space, not atom count, leave some threads unused?
> 
> The GPU uses what is essentially a full O(N^2) search, except it's really (N/32)^2, and in a way that parallelizes extremely well. For a sufficiently large system that will become inefficient, but for the typical system sizes we work with it's very fast.

**Comment by ThWuensche** [comment]
Ok, it seems to be working. The runtime of the kernel has been cut down to less than 1/2 for a small project (FAH RUN9, 4071 atoms) from 18us to 8us, which results in a calculated gain of ~1.2% for the whole project. On a big project the kernel seems memory limited, not calculation limited. At first I had seen no improvements, however by reducing the thread count in a workgroup to 16 improvement of the kernel runtime on my hardware is about 20% (FAH RUN11, 448584 atoms), which however results in a very small calculated overall improvement for the project of 0.1%.

What makes me wonder are observations I made during analysis why the big project in the beginning gave NaNs after a number of steps. That stopped after chosing the first atom of the tile as center, which is for sure not ideal, but may do. I'm observing bounding boxes with very large size, close to the size of the periodic box. That might indicate that the adaption due to USE_PERIODIC may work different for different atoms in the tile - frankly speaking I don't fully understand what's happening there.

When I tried that with the standard implementation, I also get a number of large bounding boxes. Might that be related to the fact that for the first atom the USE_PERIODIC handling just takes the position of the first atom, but later on the center of the bounding box is taken, which changes with addition of further atoms? Could that extend the bounding box over the full size of the (periodic) box, while atoms are much closer in reality? Or should we assume the bounding box is really that big? Erronously to big bounding boxes would probably result in to many boxes considered to be neighbors, such resulting in unnecessary calculations. But then to big bounding boxes probably should not result in NaNs, since they provide only a preselection for the calculation and should not make the force calculation itself invalid (to small bounding boxes could probably result in some atoms falsely not taken into account for nonbonded forces).

So the questions are whether the big bounding boxes also in the standard implementation could indicate a problem with the algorithm, which creates some % of unnessesary calculations and whether the NaNs could indicate some other problem, which otherwise is not visible. If my description is not clear, please let me know.

```
#define NUM_SECTIONS 4
#define BLOCKSIZE 16
__kernel void findBlockBounds(int numAtoms, real4 periodicBoxSize, real4 invPeriodicBoxSize, real4 periodicBoxVecX, real4 periodicBoxVecY, real4 periodicBoxVecZ,
        __global const real4* restrict posq, __global real4* restrict blockCenter, __global real4* restrict blockBoundingBox, __global int* restrict rebuildNeighborList,
        __global real2* restrict sortedBlocks) {
    unsigned index = get_global_id(0);		// Index of thread handling TILE_SIZE/NUM_SECTIONS atoms
    unsigned tile = index/NUM_SECTIONS;
    unsigned base = tile*TILE_SIZE;	// Index of first atom in the tile
    unsigned section = index%NUM_SECTIONS; 
    unsigned sectionBase = base + section*(TILE_SIZE/NUM_SECTIONS);	
    unsigned subWarp = (get_local_id(0)/NUM_SECTIONS);			// Assuming that stays constant during the loop below??
    __local real4 minPosSeg[NUM_SECTIONS*(BLOCKSIZE/NUM_SECTIONS)];	// Each thread in the CU needs a place to store data for calculating overall tile data
    __local real4 maxPosSeg[NUM_SECTIONS*(BLOCKSIZE/NUM_SECTIONS)];
    __local real4 centerWSeg[NUM_SECTIONS*(BLOCKSIZE/NUM_SECTIONS)];
    __local unsigned activeThread[NUM_SECTIONS*(BLOCKSIZE/NUM_SECTIONS)];    //Initialize that
    activeThread[get_local_id(0)] = 0;
//printf("numAtoms %x, index %x, base %x, section %d, sectionBase %x\n",numAtoms,index,base,section,sectionBase);
//if (get_global_id(0) == 0) printf("numAtoms %d, numThreads %ld, numItemsInWg %d\n",numAtoms,get_global_size(0),get_local_size(0));
//if (get_global_id(0) == 0) printf("BoxSize %f %f %f\n",periodicBoxSize.x,periodicBoxSize.y,periodicBoxSize.z);

    while (sectionBase < numAtoms) {
//printf("numAtoms %x, global_size %x, index %x, base %x, section %d, sectionBase %x\n",numAtoms,get_global_size(0),index,base,section,sectionBase);
//if (tile >= (numAtoms+TILE_SIZE-1)/TILE_SIZE) printf("!!!Writing beyond tile index\n");


	real4 tilecenter = posq[base];
        real4 pos = posq[sectionBase];
#ifdef USE_PERIODIC
//if (get_global_id(0) == 0) printf("Using periodic\n");
        APPLY_PERIODIC_TO_POS_WITH_CENTER(pos, tilecenter)
#endif
	real4 minPos = pos;
	real4 maxPos = pos;
        int last = min(sectionBase+TILE_SIZE/NUM_SECTIONS, (unsigned)numAtoms);
        for (unsigned i = sectionBase+1; i < last; i++) {
//printf("i %d, last %d\n",i,last);
            pos = posq[i];
#ifdef USE_PERIODIC
//            real4 center = 0.5f*(maxPos+minPos);
            APPLY_PERIODIC_TO_POS_WITH_CENTER(pos, tilecenter)
//            APPLY_PERIODIC_TO_POS(pos)
#endif
            minPos = min(minPos, pos);
            maxPos = max(maxPos, pos);
        }
        minPosSeg[section+subWarp*NUM_SECTIONS] = minPos;
	maxPosSeg[section+subWarp*NUM_SECTIONS] = maxPos;
	activeThread[section+subWarp*NUM_SECTIONS] = 1;
	barrier(CLK_LOCAL_MEM_FENCE);

	minPos = minPosSeg[0+subWarp*NUM_SECTIONS];
	maxPos = maxPosSeg[0+subWarp*NUM_SECTIONS];
	for (int j=1;j<NUM_SECTIONS;j++)
	    if (activeThread[j+subWarp*NUM_SECTIONS]){
		minPos = min(minPos,minPosSeg[j+subWarp*NUM_SECTIONS]);
		maxPos = max(maxPos,maxPosSeg[j+subWarp*NUM_SECTIONS]);
	    }
	barrier(CLK_LOCAL_MEM_FENCE);
        real4 blockSize = 0.5f*(maxPos-minPos);
        real4 center = 0.5f*(maxPos+minPos);
        center.w = 0;
        for (unsigned i = sectionBase; i < last; i++) {
            pos = posq[i];
            real4 delta = posq[i]-center;
#ifdef USE_PERIODIC
            APPLY_PERIODIC_TO_DELTA(delta)
#endif
            center.w = max(center.w, delta.x*delta.x+delta.y*delta.y+delta.z*delta.z);
        }
	centerWSeg[section+subWarp*NUM_SECTIONS] = center.w;
	barrier(CLK_LOCAL_MEM_FENCE);

	if (section == 0){
	    center.w = centerWSeg[0+subWarp*NUM_SECTIONS].w;
	    for (int j=1;j<NUM_SECTIONS;j++)
	        if (activeThread[j+subWarp*NUM_SECTIONS]){
		    center.w = max(center.w,centerWSeg[j+subWarp*NUM_SECTIONS].w);
	        }
            center.w = sqrt(center.w);
//if (center.w > 10) printf("tile %d, centerW %f\n",tile,center.w);
            blockBoundingBox[tile] = blockSize;
            blockCenter[tile] = center;
            sortedBlocks[tile] = (real2) (blockSize.x+blockSize.y+blockSize.z, tile);
//printf("subwarp %d, BlockSize %f, tile %f\n",subWarp,sortedBlocks[index/NUM_SECTIONS].x,sortedBlocks[index/NUM_SECTIONS].y);
	}
	barrier(CLK_LOCAL_MEM_FENCE);
        index += get_global_size(0);
	tile = index/NUM_SECTIONS;
    	base = tile*TILE_SIZE;	// Index of first atom in the tile
    	section = index%NUM_SECTIONS; 
    	sectionBase = base + section*(TILE_SIZE/NUM_SECTIONS);
	activeThread[section+subWarp*NUM_SECTIONS] = 0;
    }
    if (get_global_id(0) == 0){
        rebuildNeighborList[0] = 0;
//	printf("Leave findBlockBounds\n");
    }
}
```

Drawback of the implementation is the fixed BLOCKSIZE (threads on workgroup), the calling code also has to specify the correct (or lower) workgroup size. BLOCKSIZE bigger than the workgroup size in the calling code however probably should not hurt, just allocate unnecessary memory.

**Comment by peastman** [comment]
How many blocks do you see having large bounding boxes?  We expect there to be a few, but not many.  This is due to the way we [reorder particles](http://docs.openmm.org/latest/developerguide/developer.html#reordering-of-particles).  Most blocks contain a small, mostly contiguous piece of the protein, or a few waters that are all close together.  But at the end of the protein there will be a block that contains both protein and water, which may be very large.  A block containing ions will also be big, since aren't many of them and reordering can't do a lot to bring them together.

**Comment by ThWuensche** [comment]
I will tomorrow travel to Ukraine, analyse further in a few days. Where is the reordering into blocks done, I could not find it? What happens if an atom moves across the border of the (periodic) box, will it be inserted again on the other side of the box? That would obviously make the bounding box of the tile very large, until some resorting happens.

Side note: Upgrade of Linux kernel on my machines to 5.8 seems to bring about 5% increase in performance.

**Comment by peastman** [comment]
The reordering happens in `ComputeContext::reorderAtomsImpl()`.

When computing the bounding boxes, it takes periodic boundary conditions into account:

https://github.com/openmm/openmm/blob/2c36e9b34d046f09be4887ff60e7fdac02cf3cdb/platforms/opencl/src/kernels/findInteractingBlocks.cl#L22-L27

Out of all possible periodic positions for each atom, it takes the one closest to the center of the box (with the center being determined based on the atoms it has looped over so far).

**Comment by peastman** [comment]
Closing this old issue, since I think everything in it has been addressed.  Feel free to reopen it if you still have questions.
