### ISSUE TITLE
CHARMM parameter loading logic does not match the code

### ISSUE THREAD

**Issue by yaoyic** [openmm/openmm#2895]
Recently I met with a situation where the input CHARMM parameter file contains multiple DIHEDRAL entries with the same set of atoms and multiplicities but different energy coefficient as well as different equilibrium dihedral angle. According to the warning message, the original dihedral entry should be overwritten by the new entry, but actually the code did not do anything and the original dihedral entry just remains unchanged.

Corresponding code is here:
In [L388 of app/charmmparameterset.py](https://github.com/openmm/openmm/blob/418855e640d30f72110d339c509cd3aa25faa6b8/wrappers/python/simtk/openmm/app/charmmparameterset.py#L388), the warning says "Replacing dihedral (old) with (new)". But then in [L390 of app/charmmparameterset.py](https://github.com/openmm/openmm/blob/418855e640d30f72110d339c509cd3aa25faa6b8/wrappers/python/simtk/openmm/app/charmmparameterset.py#L390), nothing was changed. In my opinion, L390 should be changed to `self.dihedral_types[key][i] = dihedral` in order to match what was warned above.

Although I don't know how in the original CHARMM program they handle this behavior, the current implementation seems not self-consistent.

**Comment by qiuzy** [comment]
Jing Huang have told me this issue. I have run some tests and will fix this issue in tomorrow.

**Comment by qiuzy** [comment]
Thanks for reporing this bug!!

In Charmm, if flex key word is added when reading parameters, then parameter repeat checking will be triggered. This part code can be found in parmio.F90 in Charmm source code.

I already fix this issue as you suggested.

**Comment by qiuzy** [comment]
I have fixed this bug in #2952 which is already merged into openmm-master. Please Check and test it. Thx!

**Comment by yaoyic** [comment]
Thanks for the bug fix! It looks good.
