### ISSUE TITLE
Omnia link at website broken

### ISSUE THREAD

**Issue by birbilis** [openmm/openmm#2896]
the http://openmm.org/ website says
"Part of the Omnia suite of tools for predictive biomolecular simulation"
but the Omnia link there gives TOO MANY REDIRECTS error when clicked with Edge-Chromium

**Comment by peastman** [comment]
Anyone know who's maintaining omnia.md?

**Comment by jchodera** [comment]
> Anyone know who's maintaining omnia.md?

@peastman : I'm paying for the squarespace site now, but we haven't been able to locate whoever owns the omnia.md domain. Given its current registration, I imagine that someone neglected to pay the bill, it reverted to being available again, and someone else bought it. 

We could buy a new domain, or we could just finish the conversion to conda-forge.

**Comment by birbilis** [comment]
Guess for the time being could change that link to https://omniamd.squarespace.com/ since it's at the frontpage and many people may click it

if it's being "captured" directing people there could be a potential security hazard for them

**Comment by peastman** [comment]
Fixed by https://github.com/openmm/openmm-org/pull/42.
