### ISSUE TITLE
Why GPU is not utilized properly? 

### ISSUE THREAD

**Issue by rijuaxt** [openmm/openmm#2902]
Hi, 

I am an openmm user. I am facing problems while running simulation on CUDA. My gpu card is Nvidia RTX 2080 Ti 11 GB cuda enabled,  and i installed cuda 10.1 to comply with openmm.
After successful installation,  i found gpu is utilized only 15  % during simulation. I was wondering if anyone could help me out of it?

**Comment by peastman** [comment]
There could be lots of reasons.  It depends on what you're doing.  One possibility is that your code is spending most of its time doing something other than simulating.  For example, if you have it writing output or doing analysis very frequently, that will take up most of the time.  Another possibility is that you're simulating a very small system.  Your GPU has a *lot* of compute units, and it takes a lot of work to keep all of them busy.  If you're simulating a small system (perhaps only a few thousand atoms), it just won't have enough to do and most of the compute units will sit idle.

**Comment by rijuaxt** [comment]
I was simulating only 40 thousands atoms. I wrote  my code to give output and write report after 1000 steps. I don’t know why it takes 3 hours to complete 1 ns.

**Comment by peastman** [comment]
Are you sure it's actually using the CUDA platform, not CPU?

If you post your code I might be able to say more.  Otherwise all I can do is speculate.

**Comment by rijuaxt** [comment]
# This script was generated by OpenMM-Setup on 2020-10-19.

from simtk.openmm import *
from simtk.openmm.app import *
from simtk.unit import *

# Input Files

prmtop = AmberPrmtopFile('input.prmtop')
inpcrd = AmberInpcrdFile('input.inpcrd')

# System Configuration

nonbondedMethod = PME
nonbondedCutoff = 1.0*nanometers
ewaldErrorTolerance = 0.0005
constraints = HBonds
rigidWater = True
constraintTolerance = 0.000001

# Integration Options

dt = 0.002*picoseconds
temperature = 310*kelvin
friction = 1.0/picosecond
pressure = 1.0*atmospheres
barostatInterval = 25

# Simulation Options

steps = 250000000
equilibrationSteps = 1000
platform = Platform.getPlatformByName('CUDA')
platformProperties = {'Precision': 'mixed'}
dcdReporter = DCDReporter('trajectory.dcd', 10000)
dataReporter = StateDataReporter('log.txt', 1000, totalSteps=steps,
    step=True, time=True, speed=True, progress=True, elapsedTime=True, remainingTime=True, potentialEnergy=True, kineticEnergy=True, totalEnergy=True, temperature=True, separator='\t')

# Prepare the Simulation

print('Building system...')
topology = prmtop.topology
positions = inpcrd.positions
system = prmtop.createSystem(nonbondedMethod=nonbondedMethod, nonbondedCutoff=nonbondedCutoff,
    constraints=constraints, rigidWater=rigidWater, ewaldErrorTolerance=ewaldErrorTolerance)
system.addForce(MonteCarloBarostat(pressure, temperature, barostatInterval))
integrator = LangevinIntegrator(temperature, friction, dt)
integrator.setConstraintTolerance(constraintTolerance)
simulation = Simulation(topology, system, integrator, platform, platformProperties)
simulation.context.setPositions(positions)
if inpcrd.boxVectors is not None:
    simulation.context.setPeriodicBoxVectors(*inpcrd.boxVectors)

# Minimize and Equilibrate

print('Performing energy minimization...')
simulation.minimizeEnergy()
print('Equilibrating...')
simulation.context.setVelocitiesToTemperature(temperature)
simulation.step(equilibrationSteps)

# Simulate

print('Simulating...')
simulation.reporters.append(dcdReporter)
simulation.reporters.append(dataReporter)
simulation.currentStep = 0
simulation.step(steps)

**Comment by rijuaxt** [comment]
the above script was applied for my work

**Comment by peastman** [comment]
The settings in your script all look reasonable.  Simulating 40,000 atoms on a 2080 Ti, you should be getting hundreds of ns per day.  And the GPU usage should be much higher than 15%.

Is it possible something else running on your computer is monopolizing the CPU, keeping the script from getting much time and starving the GPU?  Try watching `top` while the script is running.  How much CPU time is the script using?  Is the CPU very busy overall, or are some cores mostly idle?  (Wait until after it finishes energy minimization and prints the message, "Simulating...")

If the script is using lots of CPU but not much GPU, the next thing to do is figure out what it's doing on the CPU.  A first step for that is to run it in the Python profiler.

```
python -m cProfile -s cumtime <scriptname>
```

The output will give information about where time is being spent.
