### ISSUE TITLE
Major enhancement to binding free energy calculation? 

### ISSUE THREAD

**Issue by rijuaxt** [openmm/openmm#2903]
Hello, 

I've seen that openmm has no feature regarding binding free energy calculation Between protein and ligand either from its single complex or trajectory. I think it would be great  to include feature like that. 

Calculating binding free energy by mm/gbsa or pbsa from single complex or trajectory could be the great feature of openmm

**Comment by rijuaxt** [comment]
@peastman @jchodera

**Comment by peastman** [comment]
Have you looked at [Yank](http://getyank.org/latest/)?

**Comment by jchodera** [comment]
We've been working on adding support for a variety of alchemical free energy calculations (both relative and absolute) through [openmmtools](http://openmmtools.readthedocs.org), a set of higher-level tools that build on OpenMM, and the end-point applications [yank](http://getyank.org) and [perses](http://github.com/choderalab/perses). These are still very much experimental, but we're hoping that both will be ready for larger-scale use by the end of the year.

**Comment by peastman** [comment]
Closing this issue since the feature is being added in separate packages.
