### ISSUE TITLE
Defining CustomCompoundBondForce in force field .xml file

### ISSUE THREAD

**Issue by Eli-VDB** [openmm/openmm#2906]
Dear developers, 

I am trying to construct a .xml forcefield file to use in combination with the openMM software.
To this end I want to define a CustomCompoundBondForce at a forcefield level and hence not at a system level. 
To be more precise, I am trying to convert a yaff-forcefield (https://github.com/molmod/yaff) to an openmm forcefield for a polymeric system.

At the moment, when my xml file is read and a system is generated 

```
pdb = PDBFile('polymerize/pentamer/pentamer.pdb')
forcefield = ForceField('polymerize/pentamer/ff-qff_pentamer.xml') 
system = forcefield.createSystem(pdb.topology)
```
All forces apart from the CustomCompoundBondForce are generated: 

```
for force in system.getForces():
        print(force)
```
<simtk.openmm.openmm.HarmonicBondForce; proxy of <Swig Object of type 'OpenMM::HarmonicBondForce *' at 0x7fb679e87780> >
<simtk.openmm.openmm.HarmonicAngleForce; proxy of <Swig Object of type 'OpenMM::HarmonicAngleForce *' at 0x7fb679902c90> >
<simtk.openmm.openmm.CustomTorsionForce; proxy of <Swig Object of type 'OpenMM::CustomTorsionForce *' at 0x7fb679902a20> >
<simtk.openmm.openmm.CMMotionRemover; proxy of <Swig Object of type 'OpenMM::CMMotionRemover *' at 0x7fb679902cf0> >

It is possible to manually add this force to the system once created. For example by Serializing the generated system, adding the CustomComboundBondForce manually and deserialize it again with a resulting system 'recognizing' all forces.( An alternative approach could be to add it to the system object.)

What i would however like to do is to use the newly created forcefield.xml file (here, ff-qff_pentamer.xml)  with the system generator from Openmmforcefields (to combine this system with the Parsley forcefield of openforcefield) without making any manual adjustments during or afterwards as I want to automate the process and for the ease of use (obviously). 

At the moment the API supports the definition of various CustomForces , which are relatively analogue to the CustomCompoundBondForce, but seems to be unable to define CustomCompoundBondForces. 

For completeness the following lines illustrate a CustomCompoundBond force in the  forcefield xml input and the system xml input (which I can manually add to the serialized system, with afterwards successful recognizion)

force field xml:
```xml
<CustomCompoundBondForce energy="0.5 * K * (distance(p2, p4) * cos(2 * atan(1.0000) - angle(p4, p2, p3)) * sin(dihedral(p1, p2, p3, p4)) - D0)^2">
        <PerBondParameter name="K"/>
        <PerBondParameter name="D0"/>
        <Bond class1="O2" class2="N3" class3="C5" class4="C6" K="123449.10043" D0=".0015419174698999998" />
</CustomCompoundBondForce>
```
system xml:
```xml
                <Force energy="0.5 * K * (distance(p2, p4) * cos(2 * atan(1.0000) - angle(p4, p2, p3)) * sin(dihedral(p1, p2, p3, p4)) - D0)^2" forceGroup="0" particles="4" type="CustomCompoundBondForce" usesPeriodic="1" version="3">
                        <PerBondParameters>
                                <Parameter name="K"/>
                                <Parameter name="D0"/>
                        </PerBondParameters>
                        <GlobalParameters/>
                        <EnergyParameterDerivatives/>
                        <Bonds>
                                <Bond p1="4" p2="5" p3="7" p4="8" param1="123449.10043" param2=".0015419174698999998"/>
                                <Bond p1="20" p2="21" p3="23" p4="24" param1="123449.10043" param2=".0015419174698999998"/>
                                <Bond p1="36" p2="37" p3="39" p4="40" param1="123449.10043" param2=".0015419174698999998"/>
                                <Bond p1="52" p2="53" p3="55" p4="56" param1="123449.10043" param2=".0015419174698999998"/>
                                <Bond p1="68" p2="69" p3="71" p4="72" param1="123449.10043" param2=".0015419174698999998"/>
                        </Bonds>
                        <Functions/>
                </Force>
```

If it's implemented, could you provide me with an example?
Is there a way around this if it's not implemented? 
Or am I making a mistake in the definition of the force field term?

Hopefully everything is clear, feel free to contact me for more information.

Kind regards,
Elias

**Comment by peastman** [comment]
The reason it doesn't support a `<CustomCompoundBondForce>` tag is that it doesn't know what pattern of atoms and bonds to match against.  All the other forces deal with specific patterns.  For example, a HarmonicBondForce gets matched against pairs of atoms that are directly bonded to each other.  A CustomTorsionForce specifies proper torsions, which get matched to four atoms bonded in a line, and improper torsions, which get matched to three atoms all bonded to the same central atom.  But with CustomCompoundBondForce, it doesn't know what pattern to match against.

There is a workaround you can use for this.  The XML file can include a `<Script>` tag containing python code that gets executed after the rest of the System is built.  You can use it to add other forces that aren't supported in any other way.  See https://raw.githubusercontent.com/openmm/openmm/master/wrappers/python/simtk/openmm/app/data/charmm_polar_2013.xml for an example of a force field that does that.

**Comment by Eli-VDB** [comment]
@peastman 
Thank you for the swift reply.

I understand now, thanks for the help.
Might indeed be worth having a look at the <Script> tag.
You can close this issue.

**Comment by peastman** [comment]
Let me know if you have any questions about how to use it.
