### ISSUE TITLE
OpenCLContext int numThreadBlocksPerComputeUnit = 6; hardcoded for Nvidia seems wrong

### ISSUE THREAD

**Issue by informatorius** [openmm/openmm#2907]
In OpenCLContext the` int numThreadBlocksPerComputeUnit = 6;` hardcoded for Nvidia seems wrong. 
e.g. a gtx 1080ti has 28 SM/ComputeUnits with 4 Blocks with 32 cores each = 128 cores per SM/CU = 3582 cores total
https://wccftech.com/nvidia-geforce-gtx-1080-ti-final-specs-pcb-leak/

And indeed when I run a FAHbench with numThreadBlocksPerComputeUnit = 4 instead of 6 then I get a slight speedup from 90ns/day to 91 ns/day for a FAH work unit.

**Comment by peastman** [comment]
It has nothing to do with the number of compute units.  This determines how many workgroups we launch, each containing many work units.

There isn't a single number that's guaranteed to be best in all cases.  It depends on the GPU, the size of the system being simulated, and the details of the system.  6 was chosen after a lot of testing, as a number that is often optimal and never much worse than the optimal number.
