### ISSUE TITLE
Printing Pressure/Stress Tensors for CMD Simulation

### ISSUE THREAD

**Issue by jmt0518** [openmm/openmm#2915]
Hello,

Our research team is conducting molecular dynamics simulations of various molten salts through openmm. Right now we are working with a LiF mixture and are wanting to calculate the viscosity using Green-Kubo equilibrium methods. However, this requires integration of the pressure or stress tensors on the (off) diagonals components. I have looked through and have not found whether or not openmm has this options available for implementation anywhere. 

Any help would be appreciated!

Thanks,
Jared

**Comment by proteneer** [comment]
OpenMM does not compute the virial.
