### ISSUE TITLE
Dummy atom Positional restraint in openmm

### ISSUE THREAD

**Issue by sghosh123** [openmm/openmm#2917]
I am trying to fix a protein molecule in my simulation box, so that it does not roam around.

So I wanted to have some positional restraints on 7/8 atoms. I took help from your previous code from #2262  :

    #Add some restraints.

    restraint = HarmonicBondForce()
    restraint.setUsesPeriodicBoundaryConditions(True)
    system.addForce(restraint)
    nonbonded = [f for f in system.getForces() if isinstance(f, NonbondedForce)][0]
    atomsToRestrain=[0,1000,10000]
    dummyIndex = []
    positions = pdb.positions
    for i in atomsToRestrain:
        j = system.addParticle(0)
        nonbonded.addParticle(0, 1, 0)
        nonbonded.addException(i, j, 0, 1, 0)
        restraint.addBond(i, j, 0nanometers, 100kilojoules_per_mole/nanometer**2)
        dummyIndex.append(j)
        positions.append(positions[i])

I was using this piece of code to add dummy atoms for position restraint , but got an error:
Exception: CustomNonbondedForce must have exactly as many particles as the System it belongs to.

Can you help me out on this? @peastman @jchodera

**Comment by peastman** [comment]
I replied to this question at https://github.com/openmm/openmm/issues/2262#issuecomment-724803044.
