### ISSUE TITLE
Changes in Travis CI pricing model

### ISSUE THREAD

**Issue by jaimergp** [openmm/openmm#2919]
See https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

OSX will be a paid feature after 1000 mins, and Linux will be deprioritized. I don't think this is an urgent change, but we should think of moving them to Azure?

**Comment by peastman** [comment]
Thanks for bringing this up.  It's actually much worse, though they try hard to obscure it.  The blog post starts by talking a lot about how they're making all these changes just to help you.  Then they bring up the more obscure cases, like building on Macs or running more than 10 concurrent builds.  Then they finally get to the main point, which is written in an intentionally confusing way: they're getting rid of free support for open source projects.  If you have an open source project that is currently using travis for free, they will "upgrade" you to a trial plan that gives only a very small amount of build time.  Once you've used that up, you need to "consider which of our plans will meet your needs."

I don't think Azure supports either ARM or PPC, so we need to figure out what to do with them.

**Comment by jaimergp** [comment]
Azure can provide ARM / PPC through emulation, as conda-forge does. It's way slower but hopefully it still runs within 6h. I think it requires some Docker trickery but it's definitely doable.

**Comment by jaimergp** [comment]
I might give it a try in the next weeks. Would you be ok with having all the CI running on GH Actions? I know Windows is running on Azure now, but I am more comfortable with GHA (and has a faster dev cycle, less auth/login issues), and I can migrate Windows to GHA if you want!

**Comment by peastman** [comment]
Github Actions would be fine too.  We used to run Windows CI on Appveyor, but it was really slow, so we eventually switched to Azure.  Whatever works and is easiest to maintain.

**Comment by jchodera** [comment]
Now that we are moving toward conda-forge, do we want OpenMM's CI infrastructure to more closely resemble a conda package build/deploy? I'm just wondering if there's a way to reduce the entropy of the different bits we have to maintain.

**Comment by jaimergp** [comment]
At least one of the things I'd do is to get rid of `omnia-dev` and have nightlies built and uploaded using `openmm/openmm-feedstock`. The CI pipelines are not really covered by the conda-forge infrastructure, but since we are going to use GHA, we can delegate the fragile parts to established _actions_ (e.g. installing Miniconda with `conda-incubator/setup-miniconda`).

**Comment by swails** [comment]
I could also add a Raspberry Pi 4 to the Jenkins setup 😆

**Comment by peastman** [comment]
If you have a Raspberry Pi sitting around. 😀  At the moment we aren't actively supporting any ARM based platforms, but supporting ARM based Macs will probably become important quite soon.

**Comment by jaimergp** [comment]
See #2964 for the new GHA-based CI!
