### ISSUE TITLE
How to get position of atoms for a given atom types ?

### ISSUE THREAD

**Issue by DanielWicz** [openmm/openmm#2920]
Hello, I'm struggling with getting atom positions for a given atom selection. The thing what I want to get is the position of atoms after calling the `simulation.step()` method. 

Here is an example:
```
from simtk.openmm.app import *
from simtk.openmm import *
from simtk.unit import *
from openmmtools.testsystems import AlanineDipeptideVacuum
import numpy as np

```

```
testsystem = AlanineDipeptideVacuum()
system = testsystem.system
integrator = LangevinIntegrator(300*kelvin, 1/picosecond, 2*femtoseconds)
simulation = Simulation(testsystem.topology, system, integrator)
simulation.context.setPositions(testsystem.positions)
simulation.minimizeEnergy()
```

```
for i in range(10):
    simulation.step(1000)
    state = simulation.context.getState(getPositions=True)
    # hypothetical method
    state.getPositionsByAtomNames(selection='type CA or N')

```
I have tried to tackle the problem, with an assumption, that "atom ids correspond to the positions in the positions' matrix".

```
def get_numbers_of_atoms(topology=None, selection=['N', 'CA', 'O', 'CB']):
"""outputs all atom ids for a given selection from the systems topology.
"""
    list_of_atom_id = []
    for atom in topology.atoms():
        if atom.name in selection:
            list_of_atom_id.append(int(atom.id))
    return np.array(list_of_atom_id)

```
So then, with the assumption I can extract atom positions in a such way:

```
for i in range(100):
    simulation.step(1000)
    state = simulation.context.getState(getPositions=True)
    positions = state.getPositions(asNumpy=True)
    # -1 because ids start from 1 not 0
    selected_positions = positions[atom_ids-1]

```

The questions then comes down to these two points:
**1. The assumption is always true (e.g. atom ids correspond to positions in the positions' matrix) ?
2. There's a better way to do this ?**

**Comment by aizvorski** [comment]
@DanielWicz That appears correct to me.  The enumeration of atoms in `topology.atoms() ` should be the same as the order of positions in `state.getPositions()`.

You could avoid the `atom_ids-1` hack by doing something like this:

```
    for i, atom in enumerate(topology.atoms()):
        if atom.name in selection:
            list_of_indexes.append(i)
```

and then use `positions[list_of_indexes]` directly.

I've mostly used `mdtraj.Topology` for this, as follows:

```
import mdtraj.Topology
mdtop = mdtraj.Topology.from_openmm(topology)
indexes = mdtop.select('protein and name == "CA"')
```

**Comment by peastman** [comment]
>  1. The assumption is always true (e.g. atom ids correspond to positions in the positions' matrix) ?

The field you should use is `atom.index`.  That is the index in the topology.  `atom.id` is an arbitrary string which might or might not have any connection to atom order.

As for whether the order of atoms in the System and Topology match, that depends on how you create them.  If you create the System by passing a Topology to a ForceField's `createSystem()` method, that will be true.  Likewise if the System and Topology were both created by the same AmberPrmtopFile, CharmmPsfFile, etc. it should be true.  If you create them in some other way, it depends on exactly how you do it.

>  2. There's a better way to do this ?

Using MDTraj as suggested above is a good approach.  It has a flexible atom selection language.
