### ISSUE TITLE
modeller.addMembrane - possible improvement

### ISSUE THREAD

**Issue by DNA2RNA** [openmm/openmm#2921]
Hi,

I found the addMembrane method of modeller to fail on larger proteins. I kept getting particle coords = NaN errors. It appears the sensitive step is the iterative protein scaling.

To get around this, I made a small tweak to how the protein scaling and membrane relaxing. Instead of having a one size fits all approach, I used the size of the protein to be embedded into the membrane to adjust the number of scaling cycles and membrane relax steps. That way larger proteins will be scaled up more slowly and have more relaxation steps for each cycle.

This code is by no means perfect, but the concept seems to have improved membrane embedding reliability in my hands (100% success so far!). The downside is that it can be a bit slower.

Here is the code:

```

# Run a simulation while slowly scaling up the protein so the membrane can relax.
        integrator = LangevinIntegrator(300.0, 50.0, 0.00001)
        integrator.setConstraintTolerance(0.00001)

        context = Context(system, integrator)
        context.setPositions(mergedPositions)
        LocalEnergyMinimizer.minimize(context, 10, 0)

        try:
            import numpy as np
            hasNumpy = True
            proteinPosArray = np.array(proteinPos)
            scaledProteinPosArray = np.array(scaledProteinPos)
        except:
            hasNumpy = False

        # THIS IS THE ORIGINAL METHOD WITH 50 CYCLES OF SCALING AND 50 MINIMIZE STEPS
        # try:
        #     for i in range(50):
        #         weight1 = i/49.0
        #         weight2 = 1.0-weight1
        #         mergedPositions = context.getState(getPositions=True).getPositions(asNumpy=hasNumpy).value_in_unit(nanometer)
        #         if hasNumpy:
        #             mergedPositions[numMembraneParticles:] = weight1*proteinPosArray + weight2*scaledProteinPosArray
        #         else:
        #             for j in range(len(proteinPos)):
        #                 mergedPositions[j+numMembraneParticles] = (weight1*proteinPos[j] + weight2*scaledProteinPos[j])
        #         context.setPositions(mergedPositions)
        #         integrator.step(50)

        membrane_insertion_iterations =  int((numProteinParticles//1000)*3)
        membrane_insertion_iter_wt_1  =  membrane_insertion_iterations-1
        membrane_relax_steps          =  int((numProteinParticles//1000)*3)

        for i in range(membrane_insertion_iterations):
            weight1 = i/membrane_insertion_iter_wt_1
            weight2 = 1.0-weight1
            mergedPositions = context.getState(getPositions=True).getPositions(asNumpy=hasNumpy).value_in_unit(nanometer)
            if hasNumpy:
                mergedPositions[numMembraneParticles:] = weight1*proteinPosArray + weight2*scaledProteinPosArray
            else:
                for j in range(len(proteinPos)):
                    mergedPositions[j+numMembraneParticles] = (weight1*proteinPos[j] + weight2*scaledProteinPos[j])
            context.setPositions(mergedPositions)
            integrator.step(membrane_relax_steps)

        # Add the membrane to the protein.

        modeller = Modeller(self.topology, self.positions)
        modeller.add(membraneTopology, context.getState(getPositions=True).getPositions()[:numMembraneParticles])
        modeller.topology.setPeriodicBoxVectors(membraneTopology.getPeriodicBoxVectors())
        del context
        del system
        del integrator
```

Hopefully this is helpful!

**Comment by peastman** [comment]
Good idea!  I'll mark this as a feature request.  We should experiment with different ways of selecting the number of iterations to find a good balance between speed and robustness.

**Comment by peastman** [comment]
I have a candidate fix for this in #3230.  I implemented logic that seemed reasonable to me, and it worked for a couple of proteins I tested.  Could you try it out on your proteins and see how it works?

**Comment by peastman** [comment]
I went ahead and merged #3230.  If you have a chance to test it on your proteins at some point, that would be a great help.

**Comment by DNA2RNA** [comment]
Sorry for the delay - my wife and I recently welcomed a child into the world and I just started to dig my way out of a little work backlog! I will attempt to test, but I may be on the slow side for the next months as I acclimatize to sleep deprivation. Thank you and apologies!

PS: Responded to wrong thread. Deleted and moved response here.

**Comment by peastman** [comment]
Congratulations!  Perhaps you could let your child help with this testing?  It's never too early to start building up those important skills in computational biology!
