### ISSUE TITLE
How to add custom electrostatic force?

### ISSUE THREAD

**Issue by aizvorski** [openmm/openmm#2922]
I'd like to simulate a system in an external electric field.  What is the best way to do that?

It seems like a CustomExternalForce would do the job, but how to get the charges for each particle?

Is it possible to simply add a global offset to the calculated long-range electrostatics before applying to each particle, and would that be a better way to do this?

**Comment by peastman** [comment]
You can copy the charges from the system's NonbondedForce.  Assuming that `nonbonded` is the NonbondedForce, `custom` is the CustomExternalForce, and it has a single per-particle parameter for the charge, the code would look something like this.

```python
for i in range(nonbonded.getNumParticles()):
    charge, sigma, epsilon = nonbonded.getParticleParameters(i)
    custom.addParticle(i, [charge])
```
