### ISSUE TITLE
CUDA platform giving incorrect answers for CustomNonBonedForce compare with CPU

### ISSUE THREAD

**Issue by KuangYu** [openmm/openmm#2923]
Dear all, 

I am trying to implement some kind of GCMC/MD algorithm in OpenMM, that requires me to run ghost molecules without any interactions within a system. But I found while the code runs okay on CPU platform, it crashes in the CUDA platform. I have narrowed down the issue to the CustomNonBondedForce, which generates insane forces (but correct energy!) when the ghost atom is too close to each other. Here is a simple test code (two close ghost atoms interacting with each other):

```python
#!/usr/bin/env python
import sys
import numpy as np
from simtk.openmm.app import *
from simtk.openmm import *
from simtk.unit import *

system = System()
top = Topology()
nbforce = CustomNonbondedForce('A1*A2/r^12-C1*C2/r^6')
# nbforce = CustomNonbondedForce('A1*A2/r^6/r^6-C1*C2/r^6')
nbforce.addPerParticleParameter('C')
nbforce.addPerParticleParameter('A')
system.addForce(nbforce)


# add two particles that are very close to each other, but without interactions
system.addParticle(1.0*dalton)
# nbforce.addParticle((0.010042285379363657, 0.00014232416903160687))
nbforce.addParticle((0.0, 0.0))
chain = top.addChain()
res = top.addResidue('res0', chain)
top.addAtom('h0', element.Element.getBySymbol('H'), res)
# ---
system.addParticle(1.0*dalton)
nbforce.addParticle((0.0, 0.0))
chain = top.addChain()
res = top.addResidue('res1', chain)
top.addAtom('h1', element.Element.getBySymbol('H'), res)

pos = np.array( \
        [[0.543458878993988, 1.4864429235458374, 3.6463305950164795], \
        [0.5418841242790222,1.4875054359436035, 3.6207005977630615]])
pos = np.array(pos) * nanometer
box = np.eye(3) * 4 * nanometers


# define the simulation
platform_name = 'CUDA'
platform = Platform.getPlatformByName(platform_name)
if platform_name == 'CPU':
    properties = {}
else:
    properties = {'CudaPrecision': 'mixed'}
integrator = LangevinIntegrator(300*kelvin, 1.0/picosecond, 1.0*femtosecond)
simulation = Simulation(top, system, integrator, platform, properties)

simulation.context.setPeriodicBoxVectors(box[0], box[1], box[2])
simulation.context.setPositions(pos)

# checkout the energy and force
state = simulation.context.getState(getEnergy=True, getForces=True)
print(state.getPotentialEnergy())
for f in state.getForces():
    print(f)
```

On CPU platform, it generates:
```
0.0 kJ/mol
Vec3(x=0.0, y=0.0, z=0.0) kJ/(nm mol)
Vec3(x=0.0, y=0.0, z=0.0) kJ/(nm mol)
```
But on CUDA platform, it generates:
```
0.0 kJ/mol
Vec3(x=-2147483648.0, y=-2147483648.0, z=-2147483648.0) kJ/(nm mol)
Vec3(x=-2147483648.0, y=-2147483648.0, z=-2147483648.0) kJ/(nm mol)
```
Furthermore, I found if I change the functional form from `'A1*A2/r^12-C1*C2/r^6'` to `'A1*A2/r^6/r^6-C1*C2/r^6'`, the problem disappears.

I am not sure if this has been reported before, and help is appreciated! Is this a bug in OpenMM? Also, is that fix (rewriting the functional form) actually working correctly?

BTW, I am testing the code with OpenMM 7.4.1

Thank you very much!

Kuang

**Comment by peastman** [comment]
This is happening because the two particles are almost exactly on top of each other.  When you raise the distance to a sufficiently high power, you end up with a number that's too small to represent in single precision, so the calculation comes out as 0/0 = NaN.  If you switch to double precision the result comes out correct.  But generally this just never comes up.  The repulsive term ensures particles never come close enough for it to be a problem.

If you really need to handle distances that small, you can modify your expression so the potential is flat below a certain distance.  For example,

```python
nbforce = CustomNonbondedForce('A1*A2/rc^12-C1*C2/rc^6; rc=max(r, 0.1)')
```

**Comment by KuangYu** [comment]
Thanks for the reply, that's very helpful. My problem is solved by implementing a softcore potential.
