### ISSUE TITLE
Using DCDReporter for a system with dummy atoms used for position restraints

### ISSUE THREAD

**Issue by lohedges** [openmm/openmm#2927]
I would like to monitor a trajectory for a simulation where position restraints are implemented using zero-mass dummy atoms, as described [here](https://github.com/openmm/openmm/issues/2262#issuecomment-464157489). In this situation the use of a [DCDReporter](http://docs.openmm.org/development/api-python/generated/simtk.openmm.app.dcdreporter.DCDReporter.html) doesn't work because there is a mismatch between the number of atoms in the system topology and the number of positions, e.g.:

```python
...

# Create the simulation.
simulation = Simulation(pdb.topology, system, integrator)

# Set the atomic positions. Here 'positions' contains those from 'pdb.topology'
# plus those of the additional dummy atoms.
simulation.context.setPositions(positions)

# Add the DCD trajectory reporter.
simulation.reporters.append(DCDReporter('output.dcd', 1000))

...
```

When running the script I get the following error:

```sh
File "/home/lester/sire.app/lib/python3.7/site-packages/simtk/openmm/app/dcdfile.py", line 121, in writeModel
    raise ValueError('The number of positions must match the number of atoms')
ValueError: The number of positions must match the number of atoms
```

This can be solved by editing `dcdfile.py` so that we only write the positions corresponding to the atoms in the original topology, i.e. we exclude the positions of the dummy atoms that are used as restraints.

```python
if len(list(self._topology.atoms())) != len(positions):
    positions = positions[:len(list(self._topology.atoms()))]
```
Obviously this isn't a generally valid approach, since we can't always be sure that a mismatch in the atom number is sane. (In this case the ordering of atoms is the same and the additional dummy atoms that we can ignore come at the end of the positions list.)

Is there an easier way to do this that I've missed?

Cheers.

**Comment by peastman** [comment]
Add the dummy atoms to the topology as well.  In the call to `topology.addAtom()`, specify `None` for the element.

**Comment by lohedges** [comment]
Ah, thanks. Not sure how I missed that. In my case I ended up monkey-patching `DCDFile.writeModel` so that the dummy atoms are excluded from the trajectory file. This means that I don't need to delete the dummies from the systems that I load from the trajectory elsewhere in my pipeline, which is slower. In case it's useful to anyone I simply did the following:

```python
from simtk.openmm.app import *

# Store the original writeModel method.
_writeModel = DCDFile.writeModel

# Create a monkey-patch where we slice the positions list to match the
# number of atoms in the topology, then pass this through to the original
# writeModel method.
def foo(self, positions, unitCellDimensions=None, periodicBoxVectors=None):
    positions = positions[:len(list(self._topology.atoms()))]
    _writeModel(self,
                positions,
                unitCellDimensions=unitCellDimensions,
                periodicBoxVectors=periodicBoxVectors)

# Replace the writeModel method with the monkey-patch.
DCDFile.writeModel = foo
```
