### ISSUE TITLE
Integration slows down 2 times with additional force

### ISSUE THREAD

**Issue by deadsummer** [openmm/openmm#2928]
Dear all,

I try to run a simulation with a constant additional force acting on the layer of atoms (the bottom layer is frozen to prevent a shift of the whole system). I use custom force field for atomic interaction (my system is a solid state) and CustomExternalForce method to add a constant force. I noticed that adding an external force slows down the integration two - three times. However this is not such a complicated thing to take so much resources. Maybe I do something wrong or there is a faster way to implement it?

Here is a simple script (the key strings in ### ADDITIONAL FORCES ###)  :
````
from simtk.openmm import app
import simtk.openmm as mm
import openmmtools as mmtools
from simtk import unit
from sys import stdout
#import read as rd
import pandas as pd
import  subprocess
import sys

################################# CONSTANTS ####################################################

CUTOFF_DISTANCE = 0.619610 * unit.nanometers     #!!! IMPORTANT!!!
FILE_FORCE_FIELD = "

[pdb_and_forcefield.zip](https://github.com/openmm/openmm/files/5559827/pdb_and_forcefield.zip)

UMo.xml"
DEFAULT_PARTICLE_TYPES = ["Mo","Xe"]

timestepint = 1 * unit.femtoseconds
mass_thres = 100.0 * unit.dalton
k1_0 =  100

DevInd = str(sys.argv[1])
FILE_INPUT = str(sys.argv[2])
T = int(sys.argv[3])
f0 = float(sys.argv[4])

runSteps = 200000000
stepsPDBTrj = 500000
stepsForParams = 5000

f = f0 * 96.5251 * unit.kilojoule_per_mole / unit.angstrom
k1 = k1_0 * 96.5251  * unit.kilojoule_per_mole / unit.angstrom**2
pathToSave = './'
#nameToRead = 'data.UO2-5x5x5'
nameToSaveTrj = 'force_bubble_trj_'+str(T)+"_"+str(f0)
nameToSaveParams = 'params'+str(T)+"_"+str(f0)
saveCheckPoint = 'final_state'+str(T)+"_"+str(f0)
file_output=open("output_"+str(T)+"_"+str(f0), 'w')
platform = mm.Platform.getPlatformByName('OpenCL')
properties = {'DeviceIndex': DevInd, 'Precision': 'mixed'}

################################# IMPORT ####################################################
print("Importing system from " + FILE_INPUT)
pdb = app.PDBFile(FILE_INPUT)
modeller = app.Modeller(pdb.topology, pdb.positions)

################################# XML IMPORT & Forces & APPLICATION ########################################
print("Importing force field from " + FILE_FORCE_FIELD)
force_field = app.ForceField(FILE_FORCE_FIELD)
print("Force field imported")

################################  APPLICATION1 ########################################
print("Creating system..")
system = force_field.createSystem(modeller.topology, nonbondedMethod=app.CutoffPeriodic, nonbondedCutoff=CUTOFF_DISTANCE, rigidWater=False, ewaldErrorTolerence=1e-5,removeCMMotion=False)

integrator = mm.VerletIntegrator(timestepint)

################################ ADDITIONAL FORCES ##########################################################
low_border = 5*unit.angstrom
high_border = 98*unit.angstrom

n1=0
for i in range(system.getNumParticles()):
	if system.getParticleMass(i) < mass_thres and (pdb.positions[i][2] < low_border or pdb.positions[i][2] > high_border) :
		system.setParticleMass(i, 0.0)
		n1+=1
print(n1) 
       
n2=0
force2 = mm.CustomExternalForce(" f*(z-z0) " );
force2.addGlobalParameter("f", f);
force2.addPerParticleParameter("z0");
system.addForce(force2)
for i in range(system.getNumParticles()):
    if system.getParticleMass(i) < mass_thres and (pdb.positions[i][2] > low_border and pdb.positions[i][2] < high_border) :
        force2.addParticle(i, [pdb.positions[i][2]])
        n2+=1
print(n2)      

################################  APPLICATION2 ########################################
print("Setting up simulation..")
simulation = app.Simulation(
    modeller.topology,
    system,
    integrator,
    platform,
    properties)
print("Setting positions..")
simulation.context.setPositions(pdb.positions)
print("Setting velocities..")
simulation.context.setVelocitiesToTemperature(T*unit.kelvin)
# now the simulation is ready to go
print("Simulation set up")  

####################################  SIMULATION ##############################################################
print("Simulation 1 ...")
simulation.reporters.append(app.StateDataReporter(file_output, stepsForParams, step=True, kineticEnergy=True, potentialEnergy=True, totalEnergy=True, volume=False, density=True, temperature=True, time=False, speed=True, separator=' | '))
simulation.reporters.append(app.PDBReporter(nameToSaveTrj, stepsPDBTrj))
simulation.step(runSteps)
simulation.saveState(saveCheckPoint)
`````
[pdb_and_forcefield.zip](https://github.com/openmm/openmm/files/5560168/pdb_and_forcefield.zip)

I also attach a start pdb file and xml force-field file.

**Comment by peastman** [comment]
Your code looks reasonable.  The CustomExternalForce should have minimal impact on speed.  Is it possible this isn't from the force itself, but from the way the force affects the system?  An extreme example would be if you're applying such a large force that it causes the simulation to blow up.

What values do you use for T and f0?

**Comment by deadsummer** [comment]
Thank you for your attention. Unfortunately it is namely the force method itself because the speed does not depend on the force value. I use 0.001 eV/A in calculations but the slow down effect is the same with 0.00000001 eV/A. If comment 
`        force2.addParticle(i, [pdb.positions[i][2]])`
everything becomes normal.

Output with commented force:
![image](https://user-images.githubusercontent.com/8791445/99676068-1704aa80-2a89-11eb-867e-eedbb41846b9.png)
Output with force 0.00000001 eV/A :
![image](https://user-images.githubusercontent.com/8791445/99677091-613a5b80-2a8a-11eb-97b6-f792b0fed40e.png)

Here the speed ratio 40/25 is not so great, but with bigger cells it is bigger.

**Comment by peastman** [comment]
This is really curious.  I can reproduce that adding the force makes the simulation slower.  It's unrelated to what calculation it does.  Even if I give it a constant expression for the energy so it applies no force at all, I still get the slowdown.  It also depends on how many particles I add to the force.  More particles means a bigger slowdown.  That seems as if the force calculation were taking a long time.  But it isn't!  When I run it in the profiler, the kernel for that force only takes 0.4% of the GPU time, totally negligible.  Instead, the difference comes from the other kernels running more slowly!

One possible clue: if I keep the CustomExternalForce but don't add the per-particle parameter to it, the slowdown goes away.  Perhaps this is related to memory use?  By forcing the compute units to load the data for the CustomExternalForce, that causes data for the CustomGBForce to get purged from the caches?

**Comment by peastman** [comment]
@dmclark17 do you have any idea what could be causing this?  I'm really confused by it.  Adding the CustomExternalForce only runs one extra kernel which takes a negligible amount of time, but it causes lots of other kernels to run much slower.

**Comment by dmclark17** [comment]
That does seem weird—I will look into it as well. Does it happen with both the OpenCL and CUDA platforms? Are you reproducing it with the master branch or a released version?

**Comment by peastman** [comment]
It happens in both platforms with the master branch.

**Comment by peastman** [comment]
Here's the nvprof output for a couple of short runs of the script.  I set `runSteps` to 1000 and ran it with the command

```
nvprof python test.py 0 Mo_R12_2200_24x24x32_xe150.pdb 300 0.001
```

First without the CustomExternalForce:

```
            Type  Time(%)      Time     Calls       Avg       Min       Max  Name
 GPU activities:   46.04%  365.55ms      1002  364.82us  264.80us  422.63us  computeN2Energy
                   23.72%  188.31ms      1002  187.93us  176.23us  214.21us  computeNonbonded
                   19.24%  152.73ms      1002  152.43us  144.67us  175.65us  computeN2Value
                    3.63%  28.815ms      1002  28.757us  28.224us  32.384us  sortShortList2
                    1.61%  12.790ms      1002  12.764us  12.256us  15.137us  findBlockBounds
                    1.15%  9.1147ms      1002  9.0960us  1.5680us  195.84us  findBlocksWithInteractions
                    1.08%  8.5718ms      1000  8.5710us  8.0000us  31.008us  integrateVerletPart1
                    0.79%  6.2903ms      1000  6.2900us  5.8240us  7.6160us  integrateVerletPart2
                    0.61%  4.8465ms      1002  4.8360us  4.4480us  5.7280us  computePerParticleEnergy
                    0.48%  3.8058ms      1023  3.7200us  1.1200us  178.95us  [CUDA memcpy DtoH]
                    0.45%  3.5470ms      1002  3.5390us  3.2320us  5.7280us  sortBoxData
                    0.41%  3.2912ms      1002  3.2840us  2.9120us  5.7920us  clearFourBuffers
                    0.35%  2.8115ms        35  80.328us  1.0240us  211.30us  [CUDA memcpy HtoD]
                    0.26%  2.0557ms      1002  2.0510us  1.9840us  3.5200us  computePerParticleValues
                    0.17%  1.3371ms      1004  1.3310us  1.2480us  9.5690us  [CUDA memcpy DtoD]
                    0.00%  36.064us         1  36.064us  36.064us  36.064us  reduceEnergy
                    0.00%  4.7040us         1  4.7040us  4.7040us  4.7040us  timeShiftVelocities
```

And then with:

```
            Type  Time(%)      Time     Calls       Avg       Min       Max  Name
 GPU activities:   42.56%  443.72ms      1002  442.83us  343.62us  461.10us  computeN2Energy
                   25.44%  265.21ms      1002  264.68us  234.53us  291.91us  computeNonbonded
                   22.30%  232.50ms      1002  232.03us  203.30us  246.60us  computeN2Value
                    2.80%  29.220ms      1002  29.161us  28.544us  32.544us  sortShortList2
                    1.72%  17.901ms      1002  17.865us  1.5680us  417.10us  findBlocksWithInteractions
                    1.22%  12.689ms      1002  12.663us  12.160us  14.784us  findBlockBounds
                    0.87%  9.0566ms      1000  9.0560us  8.5120us  10.336us  integrateVerletPart1
                    0.64%  6.7071ms      1000  6.7070us  6.2080us  7.7760us  integrateVerletPart2
                    0.51%  5.2910ms      1002  5.2800us  4.9280us  6.1120us  computePerParticleEnergy
                    0.37%  3.8085ms      1023  3.7220us  1.0880us  178.72us  [CUDA memcpy DtoH]
                    0.33%  3.4399ms      1002  3.4320us  3.2320us  4.2560us  computeBondedForces
                    0.32%  3.3704ms      1002  3.3630us  3.1040us  6.0160us  sortBoxData
                    0.31%  3.2104ms      1002  3.2030us  2.8480us  5.6640us  clearFourBuffers
                    0.27%  2.8575ms        38  75.198us     992ns  210.98us  [CUDA memcpy HtoD]
                    0.20%  2.0971ms      1002  2.0920us  2.0160us  2.7530us  computePerParticleValues
                    0.13%  1.3476ms      1004  1.3420us  1.2800us  8.5120us  [CUDA memcpy DtoD]
                    0.00%  36.352us         1  36.352us  36.352us  36.352us  reduceEnergy
                    0.00%  5.0560us         1  5.0560us  5.0560us  5.0560us  timeShiftVelocities
```

It only adds one extra kernel, `computeBondedForces`, which takes a negligible amount of time.  But unrelated kernels like `computeN2Energy`, `computeNonbonded`, and `computeN2Value` take much longer.

**Comment by dmclark17** [comment]
I took a look at the `computeNonbonded` kernel for both cases, and, while the generated source code matches, the inclusion of the custom force increases the number of instructions executed by `computeNonbonded` by about 80%. I found that the `numTiles` variable is going from ~5.7k to ~12k when the force is added—is this increase expected?

**Comment by peastman** [comment]
Of course!  Now I feel silly for not having spotted that and realized what was going on right at the start.  Thank you for pointing out the obvious thing I was missing. :)

The calculation of nonbonded forces in OpenMM relies on being able to reorder particles for maximum efficiency.  See http://docs.openmm.org/latest/developerguide/developer.html#reordering-of-particles for more information.  It can only reorder particles that are considered to be identical.  Since the CustomExternalForce defines a per-particle parameter with a different value for every particle, reordering becomes impossible.

**Comment by jchodera** [comment]
> Since the CustomExternalForce defines a per-particle parameter with a different value for every particle, reordering becomes impossible.

Why shouldn't they still be identical in that case as far as nonbonded forces are concerned? `CustomExternalForce` is only O(N) and can be computed independently for each particle, so it puzzles me why it wold impact nonbonded (pairwise) computations.

**Comment by peastman** [comment]
See the link above.  We only exchange particles if *every* force considers them identical.  That way we don't need to rebuild the data structures associated with forces.

**Comment by jchodera** [comment]
Is that just done for simplicity? Wouldn't adding an extra particle index lookup for O(N) force calculations not impact performance measurably?

**Comment by peastman** [comment]
Partly simplicity, and partly a question of what case you optimize for.  This script is doing something unusual, adding a per-particle parameter with a different value for every particle.  That isn't the case in normal simulations, so it isn't the case the code is optimized for.  I'm always looking for different ways of structuring it, and I've tried a few other methods, but so far they ended up being slower on the typical cases.

**Comment by deadsummer** [comment]
Thank you very much for your answers!
