### ISSUE TITLE
VerletIntegrator Too Slow after state file loading

### ISSUE THREAD

**Issue by Bio-Otto** [openmm/openmm#2929]
I'm doing aproximately 1 ns langevin dynamics at 2 fs time steps and 1 atm of pressure. Then, with the "state.xml" file, I continue the NVE simulation using 1 fs time steps and VerletIntegrator as I have stated in the script below. However, while the speed was about 7 ns / day in the langevin stage, it was 0.09 ns / day in the Verlet stage. Is this possible? @peastman 

## LANGEVIN
![image](https://user-images.githubusercontent.com/57147948/99664990-11539880-2a7a-11eb-8e50-a3dba5397ab4.png)

## VERLET
![image](https://user-images.githubusercontent.com/57147948/99665806-2d0b6e80-2a7b-11eb-85dc-e3704962a6f8.png)

Also in the zip file there is "state.xml" and "last_structure.pdb" file that I got at the end of the langevin stage.

[run_verlet.zip](https://github.com/openmm/openmm/files/5566518/run_verlet.zip)

```python
from simtk.openmm import app
import simtk.openmm as mm
from simtk import unit
from sys import stdout
from simtk.unit import *
from simtk.openmm import *
from simtk.openmm.app import *


pdb = app.PDBFile('last_structure.pdb')
topology = pdb.topology

print('Forcefield parameters loading to the simulation system ...')
forcefield = app.ForceField('charmm36.xml', 'charmm36/tip5p.xml')

print('Constructing an OpenMM System')
system = forcefield.createSystem(topology, nonbondedMethod=app.PME,
                                 nonbondedCutoff=12.0 * unit.angstroms, constraints=None,
                                 rigidWater=True,
                                 ewaldErrorTolerance=5e-5)

nonbonded = [f for f in system.getForces() if isinstance(f, NonbondedForce)][0]
nonbonded.setUseSwitchingFunction(use=True)
nonbonded.setSwitchingDistance(10.0 * unit.angstroms)

state = mm.XmlSerializer.deserialize(open('state.xml').read())
integrator = VerletIntegrator(1.0 * unit.femtoseconds)

platform = mm.Platform.getPlatformByName('OpenCL')
properties = {'OpenCLPrecision': 'mixed'}

simulation = app.Simulation(topology, system, integrator, platform, properties)
simulation.context.setState(state)
simulation.context.setTime(0)

simulation.context.computeVirtualSites()

simulation.reporters.append(
    app.StateDataReporter(stdout, 1, step=True, time=True, potentialEnergy=True,
                          kineticEnergy=True, totalEnergy=True, temperature=True, progress=True, volume=True,
                          density=True, remainingTime=True, speed=True, totalSteps=2000,
                          separator='\t'))

simulation.reporters.append(app.DCDReporter('referenceDCD.dcd', 1))

simulation.step(2000)
```

**Comment by peastman** [comment]
You're writing out a frame to the DCD file every step.  That takes up almost all the time.  More typical values would be to have the StateDataReporter produce a report every 1000 steps and the DCDReporter write a frame every 10,000 steps.  With those values, I get almost 10 ns/day with your script.
