### ISSUE TITLE
Support ARM based Macs

### ISSUE THREAD

**Issue by peastman** [openmm/openmm#2939]
Now that the first ARM based Macs have been released, we should look into supporting them.  Hopefully our existing packages will "just work" under emulation, but we need to test that.  A natively compiled version would probably be faster, although if most of the work is being done on the GPU, there might not be that much difference.  The ARM Macs do still support OpenCL, which is something I'd been worried about, so that's good.  Information about building conda packages for them is at https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/.

**Comment by jaimergp** [comment]
I think this was closed by #2978
