### ISSUE TITLE
Confusing with covalent bonds through periodic boundary conditions

### ISSUE THREAD

**Issue by RobinEllison** [openmm/openmm#2941]
Hello,
I'm running a simulation where a molecule is covalently bonded to itself through  periodic box condition. So i do a simple test.
```
import numpy as np
import simtk.openmm as mm
from simtk.unit import *
from simtk.openmm.app.internal.unitcell import computePeriodicBoxVectors

# save to pdb 
def add(st, n):
    if len(st) > n:
        return st[:n]
    else:
        return st + " " * (n - len(st))


def save_pdb(coor):
    coor = np.asarray(coor)
    record = ""
    for i in np.arange(coor.shape[0]):
        ret = ""
        atomNum = i
        segmentNum = i
        line = coor[i]
        ret = add("ATOM", 6)
        ret = add(ret + "{:5d}".format(atomNum), 11)
        ret = ret + " "
        ret = add(ret + "CA", 17)
        ret = add(ret + "ALA", 21)
        ret = add(ret + "A", 22)
        ret = add(ret + str(atomNum), 26)
        ret = add(ret + "         ", 30)
        # ret = add(ret + "%i" % (atomNum), 30)
        ret = add(ret + ("%8.3f" % line[0]), 38)
        ret = add(ret + ("%8.3f" % line[1]), 46)
        ret = add(ret + ("%8.3f" % line[2]), 54)
        ret = add(ret + (" 1.00"), 61)
        ret = add(ret + str(float(i % 8 > 4)), 67)
        ret = add(ret, 73)
        ret = add(ret + str(segmentNum), 77)
        record += ret + "\n"
    return record

system = mm.System()
pbc = computePeriodicBoxVectors(10,10,10,90,90,90)
system.setDefaultPeriodicBoxVectors(*pbc)

# add two particle
system.addParticle(1)
system.addParticle(1)
# add bond force
force = mm.HarmonicBondForce()
force.setForceGroup(1)
force.addBond(0,1,2.7,100)
# covalent bond linked through PBC
force.setUsesPeriodicBoundaryConditions(True)
system.addForce(force)
#create integrator
integrator = mm.VerletIntegrator(0.001*picoseconds)
#create context
context = mm.Context(system,integrator)
coor = [mm.Vec3(0,4,1),mm.Vec3(0,6,9)] 
context.setPositions(coor)
for i in range(1000):
    integrator.step(10)
    state = context.getState(getPositions=True)
    positions = state.getPositions().value_in_unit(angstroms)
    print("MODEL     %4d\n"%(i+1))
    print(save_pdb(positions))
    print("ENDMDL\n")
```
I am confused with the  results.
a) Just as the Figure A shows,The movement direction (arrow around the black sphere representing the atom)  of  atoms in simulation are confusing. I don't know why atoms follow the direction, and  atoms should follow the direction draw in Figure B intuitively,  because of the image of the atom 2 ( atom 2' in image).
b) Initial x coordinates of both atoms are 0. It should  always  be 0 during the simulation, while the x coordinates of both atom change slightly in real simulation.
Thanks in advance！

![Presentation1](https://user-images.githubusercontent.com/23442084/100954019-b9736200-354e-11eb-8f73-0e240502d83c.png)

**Comment by frank-stonybrook** [comment]
Based on my limit knowledge about the code, OpenMM will not wrap individual atoms that are covalently bonded since that might violate the topology. Instead it will try to wrap the molecule (atom 1 and 2 together) as a whole and put its center to the box center.

**Comment by RobinEllison** [comment]
Thanks for suggestion. 
I check the coordinates of both atom. It seems that the OpenMM neither wraps individual atom nor recenter the center of mass of the system. If the recenter occurs, it is also confusing why the atom has that movement direction. @frank-stonybrook

**Comment by peastman** [comment]
>  pbc = computePeriodicBoxVectors(10,10,10,90,90,90)

If you don't specify units, the angles are interpreted as radians and the lengths as nanometers.  90 radians is not what you intended!

By the way, if you add \``` above and below your code, it will be a lot easier to read.  It's getting rendered as markdown.

**Comment by peastman** [comment]
> I check the coordinates of both atom. It seems that the OpenMM neither wraps individual atom nor recenter the center of mass of the system.

See https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#periodic for an explanation of this.

**Comment by RobinEllison** [comment]
@peastman You are right. I made a mistake.```computePeriodicBoxVectors(10,10,10,90,90,90)``` should be replaced by ```computePeriodicBoxVectors(10,10,10,90*degrees,90*degrees,90*degrees)```.
All things work properly.
So grateful for your  response.

**Comment by peastman** [comment]
Glad it was that easy!
