### ISSUE TITLE
Is it possible to use more than 1 cpu core with cuda version of openmm?

### ISSUE THREAD

**Issue by divya938** [openmm/openmm#2942]
I have installed openmm using the following command.
`
 conda install -c omnia/label/betacuda92 openmm` 

The openmm installation is successful. I checked using the following command.

`python -m simtk.TestInstallation`

```
OpenMM Version: 7.4.2
Git Revision: dc9d188939ad630d240e89806b185061f7cd661a

There are 4 Platforms available:

1 Reference - Successfully computed forces
2 CPU - Successfully computed forces
3 CUDA - Successfully computed forces
4 OpenCL - Successfully computed forces

Median difference in forces between platforms:

Reference vs. CPU: 6.29063e-06
Reference vs. CUDA: 6.73921e-06
CPU vs. CUDA: 7.51039e-07
Reference vs. OpenCL: 6.75312e-06
CPU vs. OpenCL: 8.1321e-07
CUDA vs. OpenCL: 2.67308e-07

All differences are within tolerance.

```

The above installation worked when I am using only 1 cpu core. If I increase the number of cpu cores, then it is taking long time to finish up.

Please help me to figure out this.

**Comment by peastman** [comment]
What do you mean by "using only 1 cpu core"?  If you're using CUDA it runs on the GPU, not the CPU.  And how are you specifying a number of CPU cores?

**Comment by divya938** [comment]
using mpirun -np $ncores python simulation.py

**Comment by peastman** [comment]
OpenMM doesn't use MPI.

**Comment by divya938** [comment]
Thank you.

**Comment by divya938** [comment]
How to increase the number of cpu cores?

**Comment by peastman** [comment]
There's nothing to increase.  It's doing almost everything on the GPU, not the CPU.

**Comment by divya938** [comment]
Thank you for the clarification!!!
