### ISSUE TITLE
Minor CUDA Changes

### ISSUE THREAD

**Issue by dmclark17** [openmm/openmm#2943]
I have some minor changes to submit, which address some changes in an upcoming version of CUDA. 

1. Changing NVRTC Program name to `NULL`

https://github.com/openmm/openmm/blob/b49b82efb5a253a7c891ca084b3370e181de2ea3/plugins/cudacompiler/src/CudaCompilerKernels.cpp#L67

Right now the name of the NVRTC program is `""`, however, `NULL` can be passed as the argument to give the program a default name.

2. Adding launch bounds to `findBlocksWithInteractions`

I'd like to add a `__launch_bounds__(256,1)` to this line:

https://github.com/openmm/openmm/blob/b49b82efb5a253a7c891ca084b3370e181de2ea3/platforms/cuda/src/kernels/findInteractingBlocks.cu#L179

In the upcoming version of CUDA, I found this slightly improved performance for some benchmarks—I understand if you'd like to wait for its release to test out for yourself.

If these sound reasonable, I can submit a pull request with the changes. Thanks!

**Comment by peastman** [comment]
A PR would be great!  findInteractingBlocks defines a constant for the block size, so you can specify the bounds as `__launch_bounds__(GROUP_SIZE,1)`.

**Comment by peastman** [comment]
Fixed in #2947.
