### ISSUE TITLE
Simulation from checkpoint is always exactly the same, even if a new integrator seed is set. 

### ISSUE THREAD

**Issue by MagnusPetersen** [openmm/openmm#2945]
Hi!

I have to create many small simulation runs from the same starting configuration. My plan was to load the starting configuration checkpoint, set a new seed collect my data and then reset to the checkpoint and do the same again for a new seed. However all results are identical, as if the seed had not been changed.

`pdb = PDBFile('cloud_center/cloud'+str(0)+'.pdb')
modeller = Modeller(pdb.topology, pdb.positions)
forcefield = ForceField('amberfb15.xml', 'tip3p.xml')
modeller.addSolvent(forcefield, numAdded=593)
system = forcefield.createSystem(modeller.topology, nonbondedMethod = CutoffPeriodic, nonbondedCutoff=1.0*nanometer,
constraints=HBonds)
integrator = LangevinIntegrator(300*kelvin, 1/picosecond, 0.002*picoseconds)
simulation = Simulation(modeller.topology, system, integrator)
simulation.reporters.append(HDF5Reporter('cloud_center/clouds/cloudtraj.h5', 10, atomSubset = atom_indices))
simulation.reporters.append(StateDataReporter("report.txt", 10, step=True, potentialEnergy=True, kineticEnergy = True,
totalEnergy = True, temperature=True))
for i in range(0, cloud_num):
    pdb = PDBFile('cloud_center/cloud'+str(i)+'.pdb')
    modeller = Modeller(pdb.topology, pdb.positions)
    modeller.addSolvent(forcefield, numAdded=593)
    system = forcefield.createSystem(modeller.topology, nonbondedMethod = CutoffPeriodic, nonbondedCutoff=1.0*nanometer, 
    constraints=HBonds)
    simulation.context.setPositions(modeller.positions)
    simulation.minimizeEnergy(maxIterations=25)
    simulation.step(5000)
    #The relevant part: 
    simulation.saveCheckpoint('checkpoint.txt')
    for j in range(cloud_size):
        simulation.loadCheckpoint('checkpoint.txt')
        simulation.integrator.setRandomNumberSeed(random.randint(0, 10000))
        integrator.setRandomNumberSeed(random.randint(0, 10000))

        simulation.step(5000)`

I tried to change the seed both with  'simulation.integrator.setRandomNumberSeed(random.randint(0, 10000))' and 'integrator.setRandomNumberSeed(random.randint(0, 10000))' however the results are always exactly identical. How can I truly change the seed, to produce non identical results?

Thank you for your help.

**Comment by peastman** [comment]
Use `saveState()` instead of `saveCheckpoint()`.  A checkpoint records the complete state of the simulation, including the random number generator.  So whatever seed you used to initialize it, that gets overwritten when you load the checkpoint.  A State only records the visible parameters, like positions and velocities, but not internal ones like the random number generator.

**Comment by MagnusPetersen** [comment]
Thank you very much! That solved it.
