### ISSUE TITLE
Conda doesn't auto-detect an installed CUDA Toolkit

### ISSUE THREAD

**Issue by Dann239** [openmm/openmm#2948]
Hello!
I'm currently trying out the new conda-forge method of installation. I've already got CUDA installed on my laptop:
```
(test) palych@palych-laptop: /home/palych$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Apr_24_19:10:27_PDT_2019
Cuda compilation tools, release 10.1, V10.1.168
```
And yet if i try to install OpenMM, conda tries to download its own CUDA Toolkit:
```
(test) palych@palych-laptop: /home/palych$ conda install -c conda-forge openmm
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/palych/miniconda3/envs/test

  added / updated specs:
    - openmm


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2020.12.5  |       ha878542_0         137 KB  conda-forge
    certifi-2020.12.5          |   py39hf3d152e_0         143 KB  conda-forge
    cudatoolkit-11.0.3         |       h15472ef_6       952.1 MB  conda-forge
    fftw-3.3.8                 |nompi_h8cb7ab2_1114         6.4 MB  conda-forge
    ld_impl_linux-64-2.35.1    |       hed1e6ac_0         617 KB  conda-forge
    libblas-3.9.0              |       3_openblas          11 KB  conda-forge
    libcblas-3.9.0             |       3_openblas          11 KB  conda-forge
    libffi-3.3                 |       h58526e2_2          51 KB  conda-forge
    libgcc-ng-9.3.0            |      h5dbcf3e_17         7.8 MB  conda-forge
    libgfortran-ng-9.3.0       |      he4bcb1c_17          22 KB  conda-forge
    libgfortran5-9.3.0         |      he4bcb1c_17         2.0 MB  conda-forge
    libgomp-9.3.0              |      h5dbcf3e_17         378 KB  conda-forge
    liblapack-3.9.0            |       3_openblas          11 KB  conda-forge
    libopenblas-0.3.12         |pthreads_h4812303_1         8.9 MB  conda-forge
    libstdcxx-ng-9.3.0         |      h2ae2ef3_17         4.0 MB  conda-forge
    ncurses-6.2                |       h58526e2_4         985 KB  conda-forge
    numpy-1.19.4               |   py39h57d35e7_1         5.2 MB  conda-forge
    ocl-icd-2.2.13             |    h36c2ea0_1006         105 KB  conda-forge
    ocl-icd-system-1.0.0       |                1           4 KB  conda-forge
    openmm-7.5.0               |   py39h23e55b3_4        10.9 MB  conda-forge
    pip-20.3.1                 |     pyhd8ed1ab_0         1.1 MB  conda-forge
    python-3.9.1               |hffdb5ce_1_cpython        27.4 MB  conda-forge
    python_abi-3.9             |           1_cp39           4 KB  conda-forge
    setuptools-49.6.0          |   py39h079e4ff_2         953 KB  conda-forge
    sqlite-3.34.0              |       h74cdb3f_0         1.4 MB  conda-forge
    tk-8.6.10                  |       hed695b0_1         3.2 MB  conda-forge
    tzdata-2020d               |       h516909a_0         120 KB  conda-forge
    wheel-0.36.1               |     pyhd3deb0d_0          30 KB  conda-forge
    zlib-1.2.11                |    h516909a_1010         106 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        1.01 GB

```
Is this supposed to happen? Cudatoolkit makes up up 95% of the downloaded data. Is there a way to force it to use the installed version? Sorry for not trying this out earlier, when it wasn't already pushed to main.

**Comment by j-wags** [comment]
As I understand it, the excessive size of the first-gen CUDA toolkit packages on conda-forge is a known problem. I'd expect this to get cut down substantially, but the timeline is unclear since it may be more of a legal issue than a technical issue. 

In case this is breaking containers/CI builds, a short-term patch would be to keep omnia on the channels list and force a downgrade to 7.4

`conda create -n temp -c conda-forge -c omnia "openmm<7.5"`

Aside: One thing I notice is that running the build in a linux docker container on my macbook (no dedicated GPU -- Intel Iris Plus Graphics 640) still tried to pull `cudatoolkit        conda-forge/linux-64::cudatoolkit-10.2.89-h8f6ccaa_6`. I wonder if CUDA needs to be required for _all_ linux builds.

**Comment by peastman** [comment]
It's definitely not ideal.  We discussed approaches to avoid the download, but they added a lot of complexity and created opportunities for people to end up with incomplete installations.  In the end we decided it was best to just accept the extra download.  Hopefully they can reduce the size of the toolkit packages in the future.

**Comment by Dann239** [comment]
I see. Will the omnia-dev channel still be maintained after the transition to conda-forge? In case i want to use the old-school way of installing.

**Comment by peastman** [comment]
We'll keep doing dev builds every night, but you shouldn't use them for production purposes.  We don't plan to maintain a separate set of release builds.  The other option is to build from source.

**Comment by Dann239** [comment]
Thank you both for quick answers! I think i've no more questions about this topic.

**Comment by jchodera** [comment]
@jaimergp : Is there a way we could build conda package variants without the CUDA toolkit as a runtime requirement (but only a build requirement)? Has conda-forge added `cuda` metapackages or feature variants so you can tell it you already have the toolkit installed?

**Comment by jaimergp** [comment]
In short, I don't see an easy solution with the same guarantees we are offering right now.

What `conda` does is to keep track of the _maximum_ CUDA version supported by your drivers, via the `__cuda` virtual package. AFAIK, it doesn't detect whether you installed CUDA or which version it's present at the system level. 

If people want to avoid a download (e.g. in CI scenarios), this is something to be handled at the `cudatoolkit` package level. I guess we still need to track the pinned `cudatoolkit` for ABI reasons, but that can be fulfilled with a metapackage that distributes no files, only the pinnings. Some activation script magic could point to the installation location in the same way `nvcc` does.

Choosing between the real package or the empty one would be something like 

```
# full download
conda install -c conda-forge openmm cudatoolkit=10.0  
# empty download, just metadata
conda install -c conda-forge openmm cudatoolkit=10.0=*system*
```

There are some caveats to guarantee the version matches and solving that probably involves changes in `conda` itself. 

The best bet towards this goal is to raise an issue at https://github.com/conda-forge/cudatoolkit-feedstock.

---

If people want to build OpenMM themselves, starting from the conda-forge recipe and then removing the cudatoolkit runtime dependency should work. I can add more instructions in this direction once I am back from vacations and we have more experience in this new setup!
