### ISSUE TITLE
Error in NVCC path in tests?

### ISSUE THREAD

**Issue by lvotapka** [openmm/openmm#2954]
Hello,

I tried to install OpenMM from source, and when I get to the ccmake step, I entered the following variable:

CUDA_NVCC_EXECUTABLE             /software/repo/cuda/cuda-10.1/bin/nvcc

This is the correct path to my local NVCC executable.

However, several steps later, when I attempt to run: "make test", all the CUDA tests fail. When I look at the output of the tests specifically (such as TestCudaLangevinIntegrator), I see the following output:

$ ./TestCudaLangevinIntegrator 
exception: Error launching CUDA compiler: 32512
sh: 1: /usr/local/cuda/bin/nvcc: not found

Interestingly, even though the tests fail, the Cuda utilities in OpenMM, such as LangevinIntegrator, appear to work anyways.

Perhaps this path to NVCC was hard-coded into the tests somewhere?...

**Comment by frank-stonybrook** [comment]
Have you set the OPENMM_CUDA_COMPILER variable in your bashrc?

**Comment by lvotapka** [comment]
Hey thanks @frank-stonybrook, when I defined that variable and then recompiled OpenMM, the CUDA tests worked.

I hope all is going well Cong. Have a nice holiday season.

**Comment by peastman** [comment]
That variable isn't used for anything.  It's set automatically by CMake's FindCUDA script, but OpenMM does all its compilation of CUDA kernels at runtime, not at compile time.  See http://docs.openmm.org/latest/userguide/library.html#cuda-platform for information on how to set the location.  But normally you shouldn't need it.  As long as the CUDA libraries are in your LD_LIBRARY_PATH, it can use the runtime compiler instead.

**Comment by frank-stonybrook** [comment]
> Hey thanks @frank-stonybrook, when I defined that variable and then recompiled OpenMM, the CUDA tests worked.
> 
> I hope all is going well Cong. Have a nice holiday season.

Thanks. Same for you, Lane!

**Comment by lvotapka** [comment]
Thanks for the info, everyone. I had been focusing on the wrong environmental variable.
