### ISSUE TITLE
Support for CUDA 11?

### ISSUE THREAD

**Issue by tengjieksee** [openmm/openmm#2957]
Hi everyone, 

Sorry to disturb but I just wanna ask if OpenMM supports the latest CUDA version 11?
We have trouble running it with CUDA 11 so far..

Thanks in advance!

**Comment by Bio-Otto** [comment]
Openmm 7.5 supports cuda 11. Just type `conda install - c conda-forge/label/test - c conda-forge openmm`

**Comment by peastman** [comment]
7.5 is released now, so the command to install it is just

```
conda install -c conda-forge openmm
```

**Comment by tengjieksee** [comment]
Thanks for the help! Everything works now! :)
