### ISSUE TITLE
Error in simtk.unit conversion

### ISSUE THREAD

**Issue by dwhswenson** [openmm/openmm#2966]
There seems to be an error when calculating conversion factors in `simtk.unit`:

```python
from simtk import unit
J_per_mol = unit.joules / unit.mole
J_per_mol.conversion_factor_to(unit.kilojoules_per_mole)
# 0.0009999999999999998
```

Small difference, but this does cause real problems for reproducibility, since the value you get depends (slightly) on which unit system you used. See test failures in OpenMMTools: https://github.com/choderalab/openmmtools/issues/490. The workaround I proposed there is hideous, so an upstream fix would be better.

(Tested in macOS, Python 3.7, OpenMM 7.5.0)

**Comment by dwhswenson** [comment]
A little more detail: this appears to be a result of rounding errors in floating point math when dealing with multiplying large floats, as used to adjust between SI prefixes. The issues are already present in `BaseUnit._conversion_factor_to_by_name` after import.

```python
from simtk import unit
base_unit = list(list(unit.nanometer._top_base_units.values())[0].keys())[0]
base_unit
# BaseUnit(base_dim=BaseDimension("length"), name="nanometer", symbol="nm")

base_unit._conversion_factor_to_by_name
# {'nanometer': 1.0,
# 'meter': 1e-09,
# 'yottometer': 1000000000000000.1,
# 'zeptometer': 1000000000000.0002,
# 'attometer': 999999999.9999999,
# 'femtometer': 999999.9999999999,
# ... 
#  'millimeter': 1.0000000000000002e-06, ... }
```

The conversion for, e.g., nm to mm is being calculated something like this:

```python
# mm / nm = 1e-9 m / nm * 1e3 mm / m
1e-9 * 1e3
# 1.0000000000000002e-06
```

Issues with associativity/commutativity also show up here: 

```python
(1.0  # J/mol = kg * m**2 / s**2 / mol; convert to g * nm**2 / ps**2 / mol
 * 1e3  # g / kg
 * (1e9)**2  # nm**2 / m**2
 * (1e-12)**2  # s**2 / ps**2
)
# 0.001

# but:
1.0  * 1e3 * (1e-12)**2 * (1e9)**2
# 0.0009999999999999998

# while:
1.0  * 1e3 * ((1e-12)**2 * (1e9)**2)
# 0.001
```

I'm not sure that there's an easy fix for this: it seems to me that the best approach is to explicitly carry around the SI prefixes as integers and work out the correct exponent last -- essentially do an internal exponent/mantissa split in `simtk.unit`. But that's a major rewrite. Maybe there are some reordering tricks that can minimize the problems?

**Comment by jchodera** [comment]
`simtk.unit` was developed long before there were other standard unit systems available in Python. In particular, it is incapable of performing any kind of dimensionality checking, which is another major source of silent errors.

In addition, the Python API was developed in a C++-as-Python style, rather than a Pythonic style that complies with PEP8.

We should likely create a new first-class Python API at some point that also fixes these unit shortcomings by using a standard unit library like [pint](https://pint.readthedocs.io/en/stable/) or [unyt](https://unyt.readthedocs.io/en/stable/).

**Comment by peastman** [comment]
This is one of those unfortunate things about floating point math.  It happens whenever you're dealing with value that can't be exactly represented.  I'll see if I can figure out a way of improving the behavior.

> In particular, it is incapable of performing any kind of dimensionality checking, which is another major source of silent errors.

What do you mean?

```
>>> (1*picoseconds).value_in_unit(nanometers)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/peastman/miniconda3/lib/python3.7/site-packages/simtk/unit/quantity.py", line 621, in value_in_unit
    val = self.in_units_of(unit)
  File "/Users/peastman/miniconda3/lib/python3.7/site-packages/simtk/unit/quantity.py", line 657, in in_units_of
    raise TypeError('Unit "%s" is not compatible with Unit "%s".' % (self.unit, other_unit))
TypeError: Unit "picosecond" is not compatible with Unit "nanometer".
```

**Comment by peastman** [comment]
Try out #2968.  It should significantly improve this.  For example, your code above now gives

```python
>>> from simtk import unit
>>> J_per_mol = unit.joules / unit.mole
>>> J_per_mol.conversion_factor_to(unit.kilojoules_per_mole)
0.001
```

**Comment by peastman** [comment]
@dwhswenson have you had a chance to try #2968?

**Comment by dwhswenson** [comment]
Sorry for going AWOL on this... I didn't test it, but if the specific example I gave works, then in fixes the specific problem I was trying to fix (OpenMMTools was failing tests), which hopefully will in turn fix the thing that was blocking (OpenMMTools might now release on conda-forge), which might then fix the thing that's actually directly relevant to me (OpenPathSampling is stuck on Python 3.7 for our testing, which includes testing OpenMMTools integration.) This was a long trip upstream to try to unblock a minor issue of mine -- thanks for fixing it!
