### ISSUE TITLE
No template is found for ASP 597 ?

### ISSUE THREAD

**Issue by rijuaxt** [openmm/openmm#2969]
Can anyone help me by solving this ?

![image](https://user-images.githubusercontent.com/72547976/103341021-dcdaef80-4aaf-11eb-819d-6a0a3ef605e7.png)

**Comment by rijuaxt** [comment]
ATOM   9232  N   ASP A 597      -1.579   6.039 -42.420  1.00 61.42           N  
ATOM   9233  CA  ASP A 597      -0.896   4.956 -43.106  1.00 61.46           C  
ATOM   9234  C   ASP A 597      -1.885   4.095 -43.887  1.00 62.10           C  
ATOM   9235  O   ASP A 597      -1.650   3.784 -45.058  1.00 67.61           O  
ATOM   9236  CB  ASP A 597      -0.102   4.126 -42.097  1.00 59.08           C  
ATOM   9237  CG  ASP A 597       0.614   2.963 -42.751  1.00 76.08           C  
ATOM   9238  OD1 ASP A 597      -0.001   1.881 -42.879  1.00 83.91           O  
ATOM   9239  OD2 ASP A 597       1.775   3.142 -43.174  1.00 75.14           O1-
ATOM   9240  H   ASP A 597      -1.650   6.032 -41.413  1.00  0.00           H  
ATOM   9241  HA  ASP A 597      -0.193   5.393 -43.815  1.00  0.00           H  
ATOM   9242  HB3 ASP A 597      -0.776   3.750 -41.327  1.00  0.00           H

**Comment by jchodera** [comment]
Can you post the whole PDB file you're trying to set up?

If the above is the entire ASP 597 part of the PDB file, it appears to be missing several protons. Were you intending for openmm-setup to add all protons? Does your input file only contain some protons?

**Comment by rijuaxt** [comment]
Solved
