### ISSUE TITLE
A100, V100 and multi-gpu benchmarks

### ISSUE THREAD

**Issue by aizvorski** [openmm/openmm#2971]
Here is a set of benchmarks using A100, V100, and T4 GPUs from AWS, and including results for 1, 2, 4 and 8 GPUs:

https://gist.github.com/aizvorski/d506677cee5282ba696872ab8f225329

This is using a completely stock openmm=7.5.0 from conda-forge, except that the Amber benchmarks (JAC, FactorIX, Cellulose and STMV) were run using this code: https://github.com/openmm/openmm/pull/2970/commits/b6afae988c2409abca40bdf0cdaf3d88ff7498ff .  Identical OS/driver/CUDA etc for all.  Some results appear more than once (multiple independent runs).

With one GPU, it looks like this (all numbers in ns/day):

```
GPU                            T4    V100    A100
Test                                             
-------------------------------------------------
gbsa                       1323.0  2154.6  1836.7
rf                          663.5  1260.2  1281.5
pme (cutoff=0.9)            554.6   915.3   978.0
apoa1rf                     171.5   471.9   567.4
apoa1pme                    114.9   293.6   394.7
apoa1ljpme                   96.1   229.1   312.5
amoebagk (epsilon=1e-05)      4.3    12.8    15.9
amoebapme (epsilon=1e-05)    10.2    19.3    22.4
JAC                         593.9   971.0  1044.2
FactorIX                    137.8   359.7   458.7
Cellulose                    21.2    58.6   110.2
STMV                          6.4    19.2    33.9
```

With different numbers of GPUs on the STMV test only:
```
GPU               T4  V100  A100
Device                          
--------------------------------
0                6.4  19.2  33.9
0,1              9.1  29.0  51.6
0,1,2,3          6.6  33.6  65.2
0,1,2,3,4,5,6,7  3.5  11.5  65.9
```

My motivation was mainly to figure out how to speed up very large to huge systems, or at least figure out what performance to expect: after I saw my system running at 0.4 ns/day I got into benchmarking :)  The performance for large systems on single GPUs here is scaling almost linearly with memory bandwidth (T4 = 320 GB/s, V100 = 900 GB/s and A100 = 1,555 GB/s).  For the STMV (~1M atoms) on A100, each step takes 0.01 seconds, which is enough to read 15 GB of data from memory (assuming perfect efficiency), but the total state of the system seems to be only on the order of ~tens of megabytes.  How many times per step does the state need to be read from memory?

I'm also curious what limits the ability to split a large system over multiple GPUs (on the same node or different).  If the system is divided into blocks (eg cubes) handled by different GPUs, most atoms would only have short-range interacting neighbors in the same block; the atoms which have neighbors in different blocks would be a small fraction.  Each block can also calculate the charges for its own part of the PME grid.  How is work split between GPUs now?  (Apologies if this is a very basic question)

**Comment by peastman** [comment]
The multi-GPU support doesn't do any sort of domain decomposition.  It just splits up the force evaluation.  The process is

1. Broadcast the atom positions to all GPUs.
2. Compute forces in parallel.
3. Send the forces from each GPU back to a single GPU.
4. That single GPU sums all of them and does integration.

This works alright for small numbers of GPUs but doesn't scale very far.  Implementing domain decomposition would let it scale better, but it would be a major project and that's never been a priority for us.  For most applications we're interested in, total aggregate sampling is what matters, so it's more efficient to just run multiple independent simulations.

The multi-GPU performance is also affected by the bus connecting the GPUs.  Did this use PCIe or NVLink?  If PCIe, what was the topology?  Did all the GPUs have the ability to use peer-to-peer data transfers, or did it have to route the data through the host?

**Comment by jchodera** [comment]
@aizvorski : Other packages like NAMD and gromacs have focused on multi-node and multi-GPU performance. It would be a significant undertaking to incorporate the same kinds of domain decomposition schemes into one of the OpenMM GPU platforms, but would in principle be possible. 

It would be useful to check out @peastman's suggestions to see if any of these easy fixes might deliver the performance you're looking for, but if you absolutely need that, we can certainly discuss what it would take to get there!

Another question is whether you would need atomistic models to treat systems of the size you're interested in. For OpenMM 8, we've been focusing on tight integration with machine learning models, enabling models like ANI and SchNet to run at near-MM speeds. With new methods like [CGSchNet](https://aip.scitation.org/doi/10.1063/5.0026133) offering the potential to build coarse-grained SchNet-based models from short MM simulations, it may be possible that OpenMM could offer a different path to the scales you're interested in.

**Comment by jchodera** [comment]
Also, huge thanks for running these benchmarks! They're clearly going to be of widespread interest!

@peastman: What do you think of integrating these into the [benchmarks page](http://openmm.org/about.html#benchmarks)? These benchmarks are going to be much more useful to folks that have access to cloud computing than some of the benchmarks we have up (e.g. Titan V). We could even make a separate "cloud benchmarks" table, where we might be able to figure out how to also report ns/$ each time the website is rebuilt using the [AWS EC2 JSON pricing tables](http://forecastcloudy.net/2012/04/02/amazon-web-services-aws-ec2-pricing-data/).

**Comment by aizvorski** [comment]
@peastman Thank you, I understand the multi-GPU method better now.  

Are the forces that are sent back forces between pairs of particles, or partial sums of forces acting on each particle?  

If it's partial sums, then the total broadcast is N*3*4 bytes worth of positions (assuming single precision), and the data received back is the same size of forces = 2*N*3*4 bytes per step?  That's only 2.4 Gbyte/s for the STMV system at 100 steps/second - doesn't seem like the overall speed would be limited by the interconnects (latency might be important though).

> The multi-GPU performance is also affected by the bus connecting the GPUs. Did this use PCIe or NVLink? If PCIe, what was the topology? Did all the GPUs have the ability to use peer-to-peer data transfers, or did it have to route the data through the host?

The A100s and V100s both have NVLink (A100 should have NVSwitch as well) and should have fast peer-to-peer.  T4s were PCIe and go through the host.

**Comment by aizvorski** [comment]
@jchodera Thanks, good advice!  I mainly wanted to understand where the ceiling is, and what determines it.  It's so tempting to try to solve problems by throwing hardware at them, but it doesn't always work :)

Coarse-graining is a very good call!  I thought about Martini but wasn't sure the OpenMM Martini is ready to use (and I really like the OpenMM custom forces...)

ANI at near-MM speeds, heck yes :)  Where is OpenMM 8 at - planning stage or private branch or something like that?

> @aizvorski : Other packages like NAMD and gromacs have focused on multi-node and multi-GPU performance. It would be a significant undertaking to incorporate the same kinds of domain decomposition schemes into one of the OpenMM GPU platforms, but would in principle be possible.
> 
> It would be useful to check out @peastman's suggestions to see if any of these easy fixes might deliver the performance you're looking for, but if you absolutely need that, we can certainly discuss what it would take to get there!
> 
> Another question is whether you would need atomistic models to treat systems of the size you're interested in. For OpenMM 8, we've been focusing on tight integration with machine learning models, enabling models like ANI and SchNet to run at near-MM speeds. With new methods like [CGSchNet](https://aip.scitation.org/doi/10.1063/5.0026133) offering the potential to build coarse-grained SchNet-based models from short MM simulations, it may be possible that OpenMM could offer a different path to the scales you're interested in.

**Comment by peastman** [comment]
> If it's partial sums, then the total broadcast is `N*3*4` bytes worth of positions (assuming single precision)

Correct.  The communication is all linear in the system size.

> ANI at near-MM speeds, heck yes :)

"Near" for a very loose definition of near.  Only a few orders of magnitude slower. :)  See https://github.com/openmm/NNPOps/pull/19.  With our most recent code, it takes 0.4 ms to compute forces and energy for a system of 46 atoms.

**Comment by giadefa** [comment]
Check https://arxiv.org/abs/2012.12106 and corresponding github.com repo
for coarse graining. We are going to soon use acemd and opennMM for running
these coarse gained simulations.

Best. Gianni

**Comment by peastman** [comment]
> What do you think of integrating these into the benchmarks page?

This might be a good time to consider an overhaul of our benchmarks.  What systems do we want to report benchmarks for, what hardware should we benchmark them on, and how do we ensure the data is collected in a controlled, reproducible way?

**Comment by aizvorski** [comment]
@peastman In a cloud environment, I think T4 for best price performance, V100 and A100 for speed; other available GPUs are slower and/or more expensive than T4 so unlikely to be used in production.  I can help automate this; it seems very consistent from run to run, and I haven't noticed any difference between AWS and GCP.

**Comment by aizvorski** [comment]
> Check https://arxiv.org/abs/2012.12106 and corresponding github.com repo for coarse graining. We are going to soon use acemd and opennMM for running these coarse gained simulations. Best. Gianni

Thanks Gianni, great paper!   How do you see the main application - are you trying to learn good coarse grained force fields with ML?  or use actual ML force fields?

**Comment by giadefa** [comment]
it will serve the three cases, learning QM potentials, learning
coarse-grained potentials, end-to-end learning. I suggested it because of
the coarse-grained part which would be great for large systems. Note that
we produce a coarse-grained model which preserves the energetics of the
all-atom system in the remaining degrees of fredom. Which is what
coarse-graining should be about.

For just runnnig  ML potentials, whether generated with torchmd-net or
others, I would suggest OpenMM or ACEMD with the Tensorflow or PyTorch
backend because you don't need an end-to-end differentiable simulator for
that. However, torchmd is simple enough that it might be a nice choice if
you don't care of performance but want to modify the code for research.
Soon we will be facilitating running torchmd coarse-grained models using
openMM.

g

**Comment by jchodera** [comment]
Tagging in @mikemhenry to consider whether this could be automated with GitHub Actions and AWS at some point in the nebulous future.

**Comment by mpvenkatesh** [comment]
Alex, could you share your set-up, protocol and command-line for the multi-GPU STMV runs? I'd like to reproduce them here within NVIDIA on A100, thanks.

**Comment by aizvorski** [comment]
@mpvenkatesh Certainly, I will try although it's been a little while.  It went something like this:

* Launch new VM with the `Deep Learning AMI (Amazon Linux 2) Version 38.0` machine image
* Log in and install openmm with `conda install -c conda-forge openmm=7.5.0`
* Check out [this commit](https://github.com/openmm/openmm/commit/b6afae988c2409abca40bdf0cdaf3d88ff7498ff) of openmm
* Run `python openmm/examples/benchmark.py --test=STMV --device=0,1,2,3` (or whatever list of devices you want to use)

I didn't do anything to install drivers or CUDA, just used the standard that already came with the AMI (which I assume may be optimized by Amazon).

Let me know if that works for you!   Best, -A.

> Alex, could you share your set-up, protocol and command-line for the multi-GPU STMV runs? I'd like to reproduce them here within NVIDIA on A100, thanks.

**Comment by mpvenkatesh** [comment]
Thanks Alex! My openmm-7.5.1 pull did not have the STMV system but I was able to reproduce some of your V100 numbers, and test a few on multi-GPU set-ups. I will share final benchmarking results (V100 vs A100, single vs. multi-GPU) after completion of other associated tests. I am trying to expand into multi-GPU systems that use the multistate module of openmm-tools (or other ways of running replica exchange on OpenMM); let me know if you have any scripts that could be handy.

**Comment by aizvorski** [comment]
@mpvenkatesh I'm sorry for the confusion, I probably didn't explain that well enough.  To run STMV exactly the way I did, you need openmm=7.5.0 installed from conda-forge, but then actually run the benchmark.py script from commit `b6afae9`; don't run the benchmark.py from 7.5.0, and don't install b6afae9 in conda.  Alternately, if you use the latest code (master), you should be able to run with `benchmark.py --test=amber20-stmv` (which is very similar in effect, but not identical to what I did)

I don't know about the multistate module, but one thing that's worth mentioning is that multi-GPU scaling in practice is a lot worse than it has to be from theory, which was the main result I wanted to share originally.  The data that needs to move between GPUs is relatively small (total traffic is approx (K+1)*N*3*4 bytes per step where K=number of GPUs and N=number of atoms), which works out to only a few GB/s in the case of the STMV simulation on A100s running at 200-400 steps/s; but the available bandwidth with NVLink/NVSwitch is ~two orders of magnitude greater.  This could be a latency issue, or something else.  I'm pretty sure the multi-GPU code doesn't use NCCL yet. What are your thoughts on optimizing the scaling? (separately from multistate)

**Comment by peastman** [comment]
I'm not sure what's limiting the scaling in that case.  I've never profiled it on a system with NVLink.  Communication overhead should be quite low in that case.  Some parts of the calculation don't get parallelized, but they only represent a small fraction of computation time, so that shouldn't prevent a much larger speedup than what you see.  And of course, communicating between GPUs requires synchronization points that mean flushing the queue.  But you pay that cost as soon as you add a second GPU.  In principle, that cost doesn't need to increase much as you add a third or fourth one.

It would be interesting to profile it and figure out what is really going on.

**Comment by aizvorski** [comment]
@peastman Looking at multi-GPU scaling again - could you let me know how you'd profile something like this?  If you could tell me how to do it, I'd be happy to collect some profiling info.

Would it help to have access to a multi-A100 machine for a bit?

**Comment by aizvorski** [comment]
The multi-GPU scaling was significantly improved in #3333, and there is some more follow-on work tracked in #3457 and #3389, so the original purpose of this benchmark is probably completed - closing.

**Comment by sjkoelle** [comment]
I ended up in this thread due to curiosity about gpu benchmarks for non-openmm training types.  I found https://lambdalabs.com/gpu-benchmarks to be a useful comparison as well.
