### ISSUE TITLE
Calcutate pressure tensor in OpenMM

### ISSUE THREAD

**Issue by WangXinyan940** [openmm/openmm#2980]
Hello,

I am trying to calculate viscosity and find there was no good way to get pressure tensor in OpenMM in recent years. I wonder if we have any new way for pressure tensor in OpenMM now, or I'd better use non-equilibrium molecular dynamics for viscosity?

**Comment by proteneer** [comment]
We currently do not compute the virial in OpenMM.

**Comment by peastman** [comment]
Computing the virial is trivial.  It's basically just the sum over force\*position for all particles.  See https://en.wikipedia.org/wiki/Virial_theorem.

The thing we don't compute is the gradient of the virial with respect to the box vectors.  That's needed for some types of barostats.  But for your purposes, that might not be a problem?

**Comment by WangXinyan940** [comment]
I remember the virial in PBC system is not simply force*position, in which Ewald sum and pairwise interactions also need to be considered as the followed papers did:
https://aip.scitation.org/doi/full/10.1063/1.3245303
https://aip.scitation.org/doi/abs/10.1063/1.476834

Since virial is not included in the code, maybe I'd better write a force to do non-equilibrium MD. Many thanks for replying.
