### ISSUE TITLE
SaveState Parameter Issue

### ISSUE THREAD

**Issue by Teohoho** [openmm/openmm#2981]
I ran a restrained minimization protocol, by adding a CustomExternalForce object (which describes a harmonic potential, using a spring constant, which I named "springConstant") to atoms found in secondary structures. After all minimization protocols were finished, I wanted to save the positions of the atoms, using the saveState function, into an XML file.
In the following simulation, I do not want to restrain any atoms, so I do not create any custom force object. However, when attempting to LoadState, there is an error regarding the assignment of the parameter "springConstant". 
I toyed around with the loadState and the force objects and found that the same error comes up if I remove the MonteCarloBarostat from the second simulation, the change being the name of the errant parameter. My issue is: is there a way to select which parameters to save when using the saveState function? In lieu of this, is there a way to remove a parameter from a context before saving? 
Note: I did try removing the force from the system, reinitializing the context and saving, but the parameter was still saved in the XML file. So far, the only workaround I could find is manually deleting the offending parameter from the XML.

**Comment by peastman** [comment]
A state file is designed to record the complete state of the simulation, not just coordinates, so that won't work well in this case.  How about saving to a different type of file?  For example,

```python
state = simulation.context.getState(getPositions=True)
simulation.topology.setPeriodicBoxVectors(state.getPeriodicBoxVectors())
with open('minimized.pdbx', 'w') as output:
    PDBxFile.writeFile(simulation.topology, state.getPositions(), output)
```

And then to reload them,

```python
pdbx = PDBxFile('minimized.pdbx')
simulation.context.setPositions(pdbx.positions)
simulation.context.setPeriodicBoxVectors(pdbx.topology.getPeriodicBoxVectors())
```

**Comment by Teohoho** [comment]
I see. Yes, that is also going to work! Thank you for your quick response!
