### ISSUE TITLE
Gromacs .top to OpenMM .xml

### ISSUE THREAD

**Issue by bkpgh** [openmm/openmm#2985]
Warning: parmed newbie question.

I've seen a few similar questions, but I can't figure out how to read in a .top file and write out a .xml file. For example if I do:
top = gromacs.GromacsTopologyFile('my.top')

what do I follow this with in order to produce an OpenMM .xml? I'm not sure of the role or use of parameterset methods or ff objects or ...

Thanks.

**Comment by peastman** [comment]
Did you intend to post this on the ParmEd repo?  Although you probably don't need ParmEd in this case.  OpenMM can read the .top file directly.  http://docs.openmm.org/latest/userguide/application.html#using-gromacs-files
