### ISSUE TITLE
Confusion about handling the forceGroup in CUDA plugin

### ISSUE THREAD

**Issue by frank-stonybrook** [openmm/openmm#2990]
Dear OpenMM developers,

We're trying to extend the MELD plugin to support the (force) group flag when calling the `getState` on a context to retrieve maybe some subsets of MELD restraints' energy during simulation. 

To that end, we have implemented `setForceGroup` and `getForceGroup` in `MeldForce`. I can verify that the `calcForceAndEnergy` function in `MeldForceImpl` is properly controlled. However, the `getState` called on a context is still reporting the total potential energy. 

To me, the problem seems that the bonded interaction energy coming from MELD restraints are computed and accumulated by the `finishComputation` in `CudaKernels` regardless of the force group flag.

I don't understand how to pass the forceGroup flag from our MeldForce context to the bonded-interaction evaluation context. It seems that we should call the [`getBondedUtilities().addInteraction`](https://github.com/openmm/openmm/blob/9008050c9e6ccb477442d0db1fee6e53782f4cbf/platforms/common/src/CommonKernels.cpp#L289) to pass it, but  I still don't know how to properly do it.

Thanks for your help!

**Comment by peastman** [comment]
Are you using BondedUtilities to compute the forces?  It automates most of the work for you.  All you have to do is provide the small bit of code to calculate a single interaction, and it does everything else.  In that case, the force group is just a single extra argument you pass to it.  For example,

https://github.com/openmm/openmm/blob/9008050c9e6ccb477442d0db1fee6e53782f4cbf/platforms/common/src/CommonKernels.cpp#L148

If you aren't using it, then it's up to you to make sure you only compute the correct force groups.  But it sounds like you must be using it, or they wouldn't be getting computed in `finishComputation()`.

**Comment by frank-stonybrook** [comment]
Thanks for your quick reply!

I guess the answer is No. Compare with the `execute` function in the `CommonKernels` you pointed out, the [one](https://github.com/maccallumlab/meld/blob/3f2893e6728a8eac172de7f5ce37cf1c6d99d22a/plugin/platforms/cuda/src/MeldCudaKernels.cpp#L935) in our `MeldCudaKernels` does not only upload parameters but also execute various kernels. To me that is a sign that the computation of force and energy is done on our side. @jlmaccal might confirm it. 

Speak of the energy reported by the `finishComputation()`, I am also puzzled. I thought the only place to invoke the `execute` is inside the **`calcForceAndEnergy`** which is properly controlled. So why this function will still be called?

**Comment by peastman** [comment]
There are two ways to add a contribution to the energy.  One is to return it from `execute()`.  Since you're doing the calculations on the GPU, that would be inefficient.  It would require `execute()` to block until the kernels had all finished, then transfer the energy back to the host.  So instead it uses the second method, which is to add the energy to the `energies` array on the GPU.  That array gets summed and transferred back to the host in `finishComputation()`.

Your code looks fine as far as I can tell.  You check the force group before executing any kernels:

https://github.com/maccallumlab/meld/blob/3f2893e6728a8eac172de7f5ce37cf1c6d99d22a/plugin/openmmapi/src/MeldForceImpl.cpp#L28-L32

Can you verify that your kernels really aren't getting executed?  If they don't, there's no way any energy they didn't compute could end up getting computed.

**Comment by frank-stonybrook** [comment]
Thanks for taking a look of our codebase! Sure, I did this following tests by adding a MELD force and setting it to be group 7 (`force->setForceGroup(7)`, the expected energy is 1) :

- Test1: getState(State::Energy, true, 1<<3);
- Test2: getState(State::Energy, true, 1<<7);
- Print out Energy from OpenMM's `ContextImpl` and `CudaKernels` as well as round the if loop in `MeldForceImpl`;

Here are the results:
**Test1**
![Screen Shot 2021-01-22 at 14 32 19](https://user-images.githubusercontent.com/10855977/105536622-a400f580-5cbe-11eb-90a8-b1dc81b4f7d2.png)



**Test2**:  
![Screen Shot 2021-01-22 at 14 30 55](https://user-images.githubusercontent.com/10855977/105536491-72882a00-5cbe-11eb-886b-9868a5647b9f.png)



Based the output, the MELD kernel is only being executed in the second test which is what we expected. The mysterious potential seems cause by [this line of code](https://github.com/openmm/openmm/blob/9008050c9e6ccb477442d0db1fee6e53782f4cbf/platforms/cuda/src/CudaKernels.cpp#L119)

**Comment by peastman** [comment]
That line computes interactions that have been added to the BondedUtilities.  MeldForce doesn't use BondedUtilities.  Therefore, the potential must be coming from some other force, not the MeldForce.

**Comment by frank-stonybrook** [comment]
I figured it out that the mysterious potential comes from a stupid debug I did in my test script!!
I am now able to leverage the `group` flag in the `getState` function and correctly retrieve potential energy from a subset of system.
Thanks for your help!
