### ISSUE TITLE
API for ML potentials

### ISSUE THREAD

**Issue by peastman** [openmm/openmm#2991]
This is a followup to #2940.  Now that we have a plan for what use cases we want to support, it's time to consider the design and implementation.  Here are some initial suggestions.

For the case where you want to model the entire system with the ML potential, we can have a simple `createSystem()` function similar to the ones in ForceField, AmberPrmtopFile, etc.  It takes a Topology and returns a System.

For the case where you want to model only one piece with the ML potential, I suggest a `createSystem()` function that takes 1) a Topology, 2) an existing System that models everything with the classical potential, and 3) a list of which atoms you want to model with ML.  It would clone the System, removing all internal interactions between pairs of atoms that are both modelled with ML, and add the ML force.

The first of these would need specific support for each ML model.  Given that support, I think the second one could be implemented in a generic way.

Ideally, supporting a new ML potential would just involve adding a new data file, the same way we do for ForceField, but I don't think that will be practical.  In general, each ML model will involve both code and data.  It may involve calling other libraries like TorchANI or SchNetPack.  So I think the best approach is a plugin based one, where pieces of code register themselves.  The user code might look something like this.

```python
potential = NeuralNetworkPotential('ani2x')
system = potential.createSystem(topology)
```

It would look up the code that had been registered for the name "ani2x" and execute it to create the system.  We could include a collection of supported potentials, and other separately installed packages could add other potentials.

I suggest putting all of this into a new package.  I don't want it to be in the core OpenMM package, because that would make PyTorch into a dependency of OpenMM.  It also doesn't belong in the openmm-torch package, because it may eventually support models based on other frameworks like TensorFlow and TensorRT.  And I want to keep NNPOps as a lower level package that doesn't have OpenMM specific code.  Possibly we can reuse the name `openmm-nn` for this package.

**Comment by jchodera** [comment]
Thanks for getting this conversation started!

A few observations:

**Best practices:** If we're going to create new packages, we should [adhere to software best practices](https://molssi.org/education/best-practices/) and use [PEP8](https://www.python.org/dev/peps/pep-0008/). Ideally, we would harmonize best practices for Python projects with the [Open Force Field Initiative](http://openforcefield.org).

**Use cases:** The most important initial use case is QML/MM---was the thought that this pure QML potential is perhaps easier to initially support?

**Namespace:** We should think carefully about what namespace we want to use. Should we stick with `simtk.openmm.*`? Do we want `openmm` as a top-level namespace?

**Naming:** I don't think we should use `NeuralNetworkPotential` because some of these might not be neural network potentials. They might be based on GPs, or Clebsch-Gordan nets, or more general concepts or have more important ideas than "neural nets". What they share is that they use some sort of machine learning potential. Perhaps `MLPotential`?

**Package name:** I also don't think `openmm-nn` is a good name for this package. Perhaps `openmm-mlpotential` or `openmm-qml`?

**Comment by peastman** [comment]
> The most important initial use case is QML/MM---was the thought that this pure QML potential is perhaps easier to initially support?

I'm not sure what you mean?  The proposal above includes both.

> Should we stick with simtk.openmm.*? Do we want openmm as a top-level namespace?

The proposal above is that it would be its own package.  You would `import openmmnn` just like you `import openmmtorch` or `import openmmtools`.

> I don't think we should use NeuralNetworkPotential because some of these might not be neural network potentials. They might be based on GPs, or Clebsch-Gordan nets

Those *are* neural networks.  "Neural network potential" is the standard term used in the field for these models.  That's why most of them have "net" in their names: SchNet, PhysNet, Tensor Field Networks, E(3) Equivariant Neural Networks, Clebsch-Gordon Nets, etc.  ANI is short for ANIKIN-ME, which is a painful acronym for "Accurate NeurAl networK engINe for Molecular Energies".  CORMORANT is an equally painful acronym for "COvaRiant MOleculaR Artificial Neural neTwork".  (Ouch!)

> Perhaps openmm-mlpotential or openmm-qml?

Same as above.  Also, there's nothing inherently quantum about these models.  For example, one of the major use cases is training coarse grained models to reproduce classical all-atom models.

**Comment by giadefa** [comment]
I think that mlpotential is the best choice. Actually most of the models
used by QM people are kernel models, not NN.

**Comment by jchodera** [comment]
> I'm not sure what you mean? The proposal above includes both.

Can you write out the example use case in code? The example you show does not include this use case.

I proposed a specific example here: https://github.com/openmm/openmm/issues/2940#issuecomment-736925719

#2940 contains a whole list of use cases with proposed example code.

> The proposal above is that it would be its own package. You would import openmmnn just like you import openmmtorch or import openmmtools.

You can install multiple conda packages that put modules into the same namespace. The Open Force Field Initiative recently [moved to this model](https://github.com/openforcefield/openff-toolkit/issues/804), where installing `openff-toolkit` provides `openff.toolkit` while installing `openff-evaluator` provides `openff.evaluator`. We could potentially start to populate a base-level `openmm` namespace, install within the `simtk.openmm` namespace, or keep all packages at the top-level namespace (`openmmnn`). I find the first two options to be tidier than to keep coming up with new top-level namespaces for each package.

> Those are neural networks. "Neural network potential" is the standard term used in the field for these models. That's why most of them have "net" in their names: SchNet, PhysNet, Tensor Field Networks, E(3) Equivariant Neural Networks, Clebsch-Gordon Nets, etc. ANI is short for ANIKIN-ME, which is a painful acronym for "Accurate NeurAl networK engINe for Molecular Energies". CORMORANT is an equally painful acronym for "COvaRiant MOleculaR Artificial Neural neTwork". (Ouch!)

The unifying concept is that they are machine learning potentials, not that they are neural networks. There are other methods not based on neural networks we will likely want to support. See [this review by Anatole von Lilienfeld](https://doi.org/10.1002/anie.201709686), which also uses the *quantum machine learning* (QML) terminology that I have argued we should adopt.

As @giadefa points out, most of the models in use today are not neural networks, but kernel-based methods. Calling them neural networks is inappropriate (unless NNs are used to define the latent space embedding).

> Same as above. Also, there's nothing inherently quantum about these models. For example, one of the major use cases is training coarse grained models to reproduce classical all-atom models.

True! They need not be derived from quantum chemical data. We can drop the "quantum" and just call them ML potentials.

**Comment by peastman** [comment]
> Can you write out the example use case in code?

Something like this.

```python
mm_system = forcefield.createSystem(topology, nonbondedMethod=PME, ...)
ml_system = potential.createHybridSystem(topology, mm_system, ml_atoms)
```

`ml_atoms` would be a list of the indices of atoms that should be modeled with the neural network.  It would clone `mm_system`, remove all interactions between pairs of atoms that are both in `ml_atoms`, and add the TorchForce (or whatever else it needed) to model them.

> We could potentially start to populate a base-level openmm namespace

I've thought for a long time it would be nice to get rid of the `simtk` prefix, which is there for historical reasons, and have `openmm` be the top level package.  Is there a way we could do that while still having the old package be recognized for backward compatibility?  If so, then having all the other packages be sub-packages inside `openmm` would be a good design.

**Comment by jchodera** [comment]
Thanks for the concrete example! Let's iterate this into a complete example to poke at.

First, we need to recognize that `forcefield.createSystem()` doesn't work with small molecule ligands unless we handcrafted ffxml files, or we have registered a residue template generator. To use `openmmforcefields` for this, we would have something like:
```python
# Create an OpenFF Molecule object for the ligand
from openff.toolkit.topology import Molecule
molecule = Molecule.from_file('ligand.sdf')
# Create the GAFF template generator for ForceField
from openmmforcefields.generators import GAFFTemplateGenerator
gaff = GAFFTemplateGenerator(molecules=molecule)
# Create an OpenMM ForceField object with AMBER ff14SB and TIP3P with compatible ions
from simtk.openmm.app import ForceField
forcefield = ForceField('amber/protein.ff14SB.xml', 'amber/tip3p_standard.xml', 'amber/tip3p_HFE_multivalent.xml')
# Register the GAFF template generator with ForceField
forcefield.registerTemplateGenerator(gaff.generator)
# Create a system from a PDB file containing the protein, ligand, and water molecules
from simtk.openmm.app import PDBFile
pdbfile = PDBFile('complex.pdb')
system = forcefield.createSystem(pdbfile.topology, constraints=None, rigidWater=True, removeCMMotion=False, hydrogenMass=2*unit.amu)
# Find the ligand atoms
# This is hard to do right now without something like mdtraj; can we make this easier?
import mdtraj as md
mdpdb = md.load('complex.pdb')
ligand_atoms = md.select('resn MOL')
# Now convert it to a QML/MM hybrid system where the ligand atoms are replaced
# Note that we want to likely put this in a different package and use PEP8 instead
from simtk.openmm.ml import MLPotential
ml_potential = MLPotential('ANI2x')
hybrid_system = ml_potential.createHybridSystem(pdbfile.topology, ml_potential, ligand_atoms)
```
This has a number of things we would like to fix to reduce the barriers to use:
* Parameterizing the ligand is still a bit of a pain
* It's going to be perilous if the user can easily mess up things in `ForceField.createSystem()` that won't work or aren't recommended for the QML/MM (such as bond length constraints)
* We need something like MDTraj to find the ligand using a sensible selection DSL
* There is ambiguity in the meaning of "hybrid" system---sometimes we want to subtract the vacuum potential of an atom subset and add back QML, while other times we want to add ML `Force` objects for short-range and leave physical `Force` objects for long-range
* We want to simplify the top-level namespace
* We likely want to adopt PEP8 and other best practices in naming

It would be great if we can identify ways to chip away at each of these things.

I've implemented a `SystemGenerator` in `openmmforcefields` that considerably simplifies the ligand parameterization aspect.
Rewriting with this saves some code and offers more flexibility in small molecule force field:
```python
# Create an OpenFF Molecule object for the ligand
from openff.toolkit.topology import Molecule
molecule = Molecule.from_file('ligand.sdf')
# Initialize a SystemGenerator using the Open Force Field Initiative "Parsley" force field for small molecules
# GAFF can easily be substituted by specifying 'gaff-2.11' or other variants instead of 'openff-1.3.0'
from openmmforcefields.generators import SystemGenerator
forcefield_kwargs = { 'constraints' : None, 'rigidWater' : True, 'removeCMMotion' : False, 'hydrogenMass' : 2*unit.amu }
system_generator = SystemGenerator(forcefields=['amber/ff14SB.xml', 'amber/tip3p_standard.xml'], small_molecule_forcefield='openff-1.3.0', forcefield_kwargs=forcefield_kwargs)
# Create a system from a PDB file containing the protein, ligand, and water molecules
from simtk.openmm.app import PDBFile
pdbfile = PDBFile('complex.pdb')
system = forcefield.createSystem(pdbfile.topology)
# Find the ligand atoms
# This is hard to do right now without something like mdtraj; can we make this easier?
import mdtraj as md
mdpdb = md.load('complex.pdb')
ligand_atoms = md.select('resn MOL')
# Now convert it to a QML/MM hybrid system where the ligand atoms are replaced
# Note that we want to likely put this in a different package and use PEP8 instead
from simtk.openmm.ml import MLPotential
ml_potential = MLPotential('ANI2x')
hybrid_system = ml_potential.createHybridSystem(pdbfile.topology, ml_potential, ligand_atoms)
```
Any ideas for streamlining the rest?

> I've thought for a long time it would be nice to get rid of the simtk prefix, which is there for historical reasons, and have openmm be the top level package. Is there a way we could do that while still having the old package be recognized for backward compatibility? If so, then having all the other packages be sub-packages inside openmm would be a good design.

We can likely do whatever we want here. We could either freeze the old `simtk.openmm.*` and note it will be deprecated soon, or we could find some way to support (or mimic) both the "old-style API" and create a new API within the `openmm.*` namespace implemented in a PEP8 compliant manner.

**Comment by peastman** [comment]
> Parameterizing the ligand is still a bit of a pain

That's an issue regardless.  At the very least, you need charges and vdw parameters for the ligand, if you plan for it to interact with the rest of the system using a classical potential.  The only way to avoid that is to use ML for everything.

> It's going to be perilous if the user can easily mess up things in ForceField.createSystem() that won't work or aren't recommended for the QML/MM (such as bond length constraints)

I see a few options:

1. The ML potential could remove internal constraints in the ligand, just like it removes internal interactions.
2. It could print a warning about them.
3. This could also be controlled by an optional argument, e.g. `removeConstraints=True`.

> We need something like MDTraj to find the ligand using a sensible selection DSL

Agreed.

> There is ambiguity in the meaning of "hybrid" system

In https://github.com/openmm/openmm/issues/2940#issuecomment-754184367 I distinguished two different cases:

1. You have a potential function that uses classical terms for some parts (e.g. Coulomb) and a neural network for other parts (e.g. bonded interactions).  Together they form a single potential function.  The pieces are parametrized to work together.  I refer to this as a "hybrid potential".
2. You're modelling most of the system with a classical potential, and using the ML potential only for the internal energy of the ligand.  This is *not* a hybrid potential.  It has two completely different potentials, one conventional and one ML.  You can freely mix and match different potentials (e.g. Amber and ANI), even though they weren't parametrized together.

The `createHybridSystem()` function above is for the second case.  (Maybe we should change the name, if the difference between "hybrid system" and "hybrid potential" is confusing.)

> We likely want to adopt PEP8 and other best practices in naming

Maintaining consistency with the rest of OpenMM is much more important.  In fact, PEP8 [specifically recommends that](https://www.python.org/dev/peps/pep-0008/#a-foolish-consistency-is-the-hobgoblin-of-little-minds).  "Consistency with this style guide is important. Consistency within a project is more important. Consistency within one module or function is the most important."

**Comment by raimis** [comment]
For ACEMD, we would need access via C++ API.

Of course, it would be impractical to use PyTorch form C++. So, at least, there should be an option to save the model and later load it via C++ API:
```python
ml_potential = MLPotential('ANI2x')
hybrid_system = ml_potential.createHybridSystem(pdbfile.topology, ml_potential, ligand_atoms)
hybrid_system.saveMLModel('model.mlp')
```
`model.mlp` should contain a model what can be passed to OpenMM-Torch and NNP atom indices at least.

**Comment by peastman** [comment]
The System it returns will just be an ordinary System, nothing special about it.  So you can save it with the regular serialization mechanism.

```python
with open('system.xml', 'w') as output:
  output.write(XmlSerializer.serialize(system))
```

Then you can load it back in with C++.

```c++
ifstream systemStream("system.xml");
System* system = XmlSerializer::deserialize<System>(systemStream);
```

**Comment by giadefa** [comment]
I don't think that we use system at all

**Comment by peastman** [comment]
You do.  It's one of the core classes involved in every simulation.

**Comment by mattwthompson** [comment]
In lines like these,

```python3
hybrid_system = ml_potential.createHybridSystem(pdbfile.topology, ml_potential, ligand_atoms)
```

where is the "classical" MM potential? Or are `system` (from `forcefield.createSystem(pdbfile.topology)
`) and `hybrid_system` passed to other machinery as separate objects?

**Comment by peastman** [comment]
He probably just mistyped that.  There would be no need to pass `ml_potential` as an argument, since that's the object you're calling the method on.  The example I gave was

```python
ml_system = potential.createHybridSystem(topology, mm_system, ml_atoms)
```

**Comment by peastman** [comment]
I have an initial implementation of this API ready for review: https://github.com/openmm/openmm-ml/pull/1.  Comments welcome!

**Comment by peastman** [comment]
I updated the PR to include support for creating Systems that mix ML potentials with conventional force fields.

**Comment by peastman** [comment]
Closing this since the first version of the API has been implemented.
