### ISSUE TITLE
Wishlist for 7.5.1

### ISSUE THREAD

**Issue by jaimergp** [openmm/openmm#2993]
Writing down what I'd need to for the conda-forge packaging:

- #2978
- #2992 
- #2998

**Comment by jchodera** [comment]
@peastman @jaimergp : How about we use the "Milestone" tagging feature to tag the issues listed above for the "7.5.1" release milestone? That will make it very easy to read off what we expect to go into 7.5.1 from the [Milestone dashboard])https://github.com/openmm/openmm/milestones).

**Comment by jchodera** [comment]
It's on the right-hand side of issues and PRs:
![Uploading image.png…]()

**Comment by peastman** [comment]
The above issues can basically be summarized as

- Support ARM based Macs
- Support Pypy
- Support PPC

I'm not too worried about the PPC support.  We've had people using it for a while, and the fix was just to deal with a bug in a particular compiler.  The Pypy issue wasn't even a bug, just making a test less sensitive to a subtle difference in behavior.  It would be good if all of us spent a little while trying out Pypy for our day to day work to see if any real problems turn up.

For ARM based Macs, it would be good if at least one person had spent a while doing regular work on one.  Any update on when your new computer is going to come?

**Comment by jchodera** [comment]
> For ARM based Macs, it would be good if at least one person had spent a while doing regular work on one. Any update on when your new computer is going to come?

Another couple of months, according to MSK.

**Comment by peastman** [comment]
Anyone else on here have an ARM based Mac?

**Comment by jaimergp** [comment]
If it helps, these are current downloads for `osx-arm64` packages. Not too many:

![image](https://user-images.githubusercontent.com/2559438/109388422-29537780-7907-11eb-881f-6b9db789cb0b.png)

**Comment by jchodera** [comment]
@peastman : This may have been missed:
> How about we use the "Milestone" tagging feature to tag the issues listed above for the "7.5.1" release milestone? That will make it very easy to read off what we expect to go into 7.5.1 from the Milestone dashboard.

Can we do this? Is there a good reason not to?

**Comment by peastman** [comment]
It's fine with me.  First we need to make sure there's agreement about what changes should be included in it.

**Comment by peastman** [comment]
Check the [list of changes](https://github.com/openmm/openmm/milestone/2?closed=1) currently marked for 7.5.1.  Do all of those look ok?  Anything else we should add?

**Comment by jaimergp** [comment]
My particular wishlist, as you summed it up before in the thread:

> The above issues can basically be summarized as
> 
> * Support ARM based Macs
> * Support Pypy
> * Support PPC

is there, so I am happy! :)

**Comment by jchodera** [comment]
This process would be much easier if we consistently labeled issues and PRs with what they address (bug, feature, documentation, testing, deployment) and the severity (low severity, critical, introduced recently).

It's not too late to start marking issues and PRs as such now. We can then easily sort for critical bugs and just go through that list for this bugfix release.

**Comment by peastman** [comment]
I made the changes.  Shall we build a release candidate from the head of `7.5_branch`?

**Comment by jchodera** [comment]
@peastman: Can you share the draft release notes as well?

**Comment by jchodera** [comment]
@peastman : @jaimergp will be transitioning to a new role in the next couple of months, so this is a good time for you to tackle the conda-forge updates yourself under his supervision.

**Comment by jaimergp** [comment]
We've never built RCs on `conda-forge` so I'd say I should do this one (involves creating a new branch), but I will document it. If we release a RC2, @peastman can tackle that one.

**Comment by jchodera** [comment]
@peastman @jaimergp Are we *sure* we want to build explicit RCs on `conda-forge`? 

I believe the standard conda-forge process is different, and involves using standard release numbers, and then pull the release manually if there is an issue.

**Comment by jaimergp** [comment]
Pre-releases are documented here: https://github.com/conda-forge/cfep/blob/master/cfep-05.md

Example with Jupyter Lab 3: https://github.com/conda-forge/jupyterlab-feedstock/pull/247

Note how they merge to `rc` not `master`

**Comment by jchodera** [comment]
Fantastic! OK, that's what we want then, it seems.

**Comment by jaimergp** [comment]
Is the head of `7.5_branch` ready for a RC1, @peastman?

**Comment by peastman** [comment]
Go for it!

**Comment by peastman** [comment]
Here's a draft of the release notes.

> This is a patch release.  It contains a small number of bug fixes, as well as changes to enable two significant additions to the supported platforms.
>
> First, this release provides preliminary support for ARM based Macs.  The support has not been extensively tested and should be treated as beta quality.  Please try it out and let us know if you encounter any bugs while using it.
>
> Second, we are now providing conda packages for use with Pypy.  This is an alternate Python interpreter that uses just-in-time compilation to provide much faster execution than CPython.  You can create a conda environment that uses Pypy with the command
>
>     conda create -c conda-forge --name pypy pypy
>
> Here is the full list of changes in this release.
>
> #2978: Initial fixes for Apple silicon
> #2992: Made ordering of impropers more deterministic
> #2998: Workaround for bug in GCC 9 on PPC
> #3057: Fixed rare error related to single pairs
> #3058: Fix compilation error in test
> #3060: Correctly use the force group for the metadynamics force
> #3061: Release GIL when calling getState()

**Comment by jaimergp** [comment]
> conda create -c conda-forge --name pypy pypy

Maybe we can make this command include openmm too? Like this:

```
conda create -n openmm-pypy -c conda-forge openmm pypy
```

**Comment by jaimergp** [comment]
7.5.1 RC1 builds are available now, including `pypy` variants:

```
conda create -n openmm-rc -c conda-forge/label/openmm_rc -c conda-forge openmm
conda activate openmm-rc
python -m simtk.testInstallation
```

With pypy:

```
conda create -n openmm-rc-pypy -c conda-forge/label/openmm_rc -c conda-forge openmm pypy
conda activate openmm-rc-pypy
pypy -m simtk.testInstallation
```

**Comment by peastman** [comment]
Thanks!  Let's test this out.  Then once we figure out what's going on with #3085 and get that merged, you can walk me through creating RC2.

**Comment by peastman** [comment]
#3087 is merged, so we're ready to create RC2.

**Comment by jchodera** [comment]
@peastman : I believe you were going to lead that process, check in with @jaimergp as you need to?

**Comment by peastman** [comment]
The plan is for him to walk me through the process.  I don't know how it works.

**Comment by jchodera** [comment]
OK, let's have you make an RC3 on your own then after this. It's essential that we have the expertise fully in-house.

**Comment by jchodera** [comment]
> I don't know how it works.

And that's precisely what this process is supposed to solve! We should build a checklist.

**Comment by peastman** [comment]
An RC3 isn't necessary.  @jaimergp will walk me through creating RC2.  Then I'll do the release with (hopefully) minimal assistance.

> We should build a checklist.

Yes, please do!  Having everything written down will be important.

**Comment by jaimergp** [comment]
I led the process by releasing RC1, which required some initial setup. Now I will document it so Peter can follow the checklist and create the PR for RC2.

**Comment by peastman** [comment]
The announcement is at https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=161&t=13286&p=0&start=0&view=.

**Comment by peastman** [comment]
Shall we move ahead with the official release?

**Comment by peastman** [comment]
Anyone?  If no one objects, I want to go ahead and create the release.

**Comment by jchodera** [comment]
I count a total of 16 downloads. Presumably, we either want to skip the rc next time, or persuade more people (or automated nightlies) to test?

**Comment by peastman** [comment]
Finding more people to test future releases would be good.  I would never do a release with a release candidate first.  16 people testing it is a lot better than 0.

I'll create the release today.

**Comment by jchodera** [comment]
> Finding more people to test future releases would be good. 

Would be great to brainstorm how to do this. One option, for example, is to configure some of our nightly builds from the lab to test against an RC if one is available. We'd have to figure out how to do this in a way that only tests unreleased or recent RCs, but this would allow us to automatically test on a diverse number of platforms with a diverse set of applications.

@mikemhenry might be able to help us figure that out, perhaps with suggestions from @jaimergp.

> I would never do a release with a release candidate first. 16 people testing it is a lot better than 0.
> I'll create the release today.

OK!

**Comment by peastman** [comment]
@jaimergp I see there are a lot of changes to openmm-feedstock between the `master` and `rc` branches.  Which one should I base the PR on?

**Comment by mikemhenry** [comment]
I'll follow up with @peastman via email but just some quick thoughts.

For more tightly coupled downstream projects (e.g. `perses`), we can ensure that our automated CI tests release candidates -- probably by running github actions via their cron syntax so we run them even if we don't have code changes but are just checking to see if anything breaks. We test the nightly as part of our CI:
`conda install --quiet -c omnia-dev openmm`   
~but don't have anything setup yet for release candidates.~
Actually we do! It is just commented out in our CI :) 
```
           #rc) # We can uncomment this case when we have this label on conda-forge
             #echo "Using OpenMM rc" 
             #conda install --quiet -c conda-forge/label/openmm_rc openmm;;

```
I've created a PR that will add testing of the release candidate now every 24 hours.

https://github.com/choderalab/perses/pull/787


It would be really nice if this worked:

https://github.com/openmm/openmm/network/dependents

which would help us find what major packages are using openmm that we could ask if they want to help us test.

Do we have any sort of community mailing list? My guess is we have people that would want to help us test but they don't know how.

**Comment by jchodera** [comment]
@peastman @jaimergp @mikemhenry : Is there a way in which we can only test the RC for a package version until the package is released? Otherwise, we'll be testing stale RCs. Do/can we move the RC to the main channel and remove any old RCs? Or do we have to do some sort of complicated package name comparison to see if a package with the same version is also on the main channel?

Sadly the [dependency page only supports `pip` dependencies for python](https://docs.github.com/en/code-security/supply-chain-security/about-the-dependency-graph#supported-package-ecosystems).

**Comment by jaimergp** [comment]
@peastman I have created a [draft PR](https://github.com/conda-forge/openmm-feedstock/pull/53) to show what you should get. The process should be:

1. Branch off the most recently updated branch in the feedstock. In this case, `rc`.
2. Since this is a final release, make sure `channel_targets` is set to `- conda-forge main` in `conda_build_config.yaml`. (See note below)
3. In `meta.yaml`, update `version` and `git_rev` accordingly. Ensure `build.number` is 0.
4. Push to your fork and open PR targetting `master`.
5. Ask the bot for a re-render.
6. Wait for green!

Note: There's a small fix to be made in `conda_build_config.yaml` that I realized while contributing to `nvcc-feedstock`. The RCs used GCC9 on Linux64 but they should use GCC7. For now, just copy the file in my PR to yours. In normal releases, you should only worry about `channel_targets`.

***

@jchodera @mikemhenry For downstream RCs, the easiest way would be to check `-c conda-forge/label/openmm_rc` for recent uploads (let's say 7 or 14 days). And if that's the case, install the RC from there and run CI. If not, ignore the rest of the pipeline. We shouldn't (and technically can't unless we submit a request) move packages from label to label, which would alter provenance.

This command will list the packages with timestamps in JSON. We can compare the timestamps and then ask conda to install openmm from there if necessary.

```
% conda search --json --info --override-channels -c conda-forge/label/openmm_rc openmm
{
  "openmm": [
    {
      "arch": "x86_64",
      "build": "py36h0d20474_0",
      "build_number": 0,
      "channel": "https://conda.anaconda.org/conda-forge/label/openmm_rc/linux-64",
      "constrains": [],
      "depends": [
        "cudatoolkit 10.1|10.1.*",
        "fftw >=3.3.9,<4.0a0",
        "libgcc-ng >=9.3.0",
        "libstdcxx-ng >=9.3.0",
        "numpy",
        "ocl-icd >=2.3.0,<3.0a0",
        "ocl-icd-system",
        "python >=3.6,<3.7.0a0",
        "python_abi 3.6.* *_cp36m"
      ],
      "fn": "openmm-7.5.1rc1-py36h0d20474_0.tar.bz2",
      "license": "LGPL-3.0-or-later",
      "license_family": "LGPL",
      "md5": "f48c258645ef79c826eafa7c369c2d05",
      "name": "openmm",
      "platform": "linux",
      "size": 11416388,
      "subdir": "linux-64",
      "timestamp": 1617547743033,
      "url": "https://conda.anaconda.org/conda-forge/label/openmm_rc/linux-64/openmm-7.5.1rc1-py36h0d20474_0.tar.bz2",
      "version": "7.5.1rc1"
    },
    {
      "arch": "x86_64",
      "build": "py36h1803ea8_0",
      "build_number": 0,
      "channel": "https://conda.anaconda.org/conda-forge/label/openmm_rc/linux-64",
      "constrains": [],
      "depends": [
....
```

**Comment by jchodera** [comment]
Thanks so much, @jaimergp!

@peastman: How should we ensure you are able to do this on your own next time?

**Comment by peastman** [comment]
Thanks!

I'm a bit confused about how branches are being used, in particular

> Branch off the most recently updated branch in the feedstock. In this case, rc.

Normally I would expect all major changes to be made in the master branch, and the rc branch to contain only changes specific to a release candidate.  I'd also expect the rc branch to be specific to one particular release candidate.  That is, for each new version we would create an entirely new branch off of the master branch to build that release candidate.  We would either delete it once we were done, or else give it a unique name like `rc751`.  I take it that isn't how branches are being used?  Can you explain what the actual branching pattern is, and the reasons for it?

**Comment by peastman** [comment]
My PR is at https://github.com/conda-forge/openmm-feedstock/pull/54.

**Comment by jaimergp** [comment]
The principles are detailed [here](https://github.com/conda-forge/cfep/blob/master/cfep-05.md).

Conda Forge will trigger the CI (with upload permissions) from _any_ branch in the feedstock. That's why we need to use forks to open PRs, otherwise each attempt could end up with wrongly uploaded packages to Anaconda.org.

In principle, `master` hosts the stable releases, and `rc` the release candidates (if applicable); `dev` would be for alphas. Technically, we don't need to use different branches either, but it helps keep everything conceptually separated (with respect to the value of `channel_targets`). Some feedstocks use multiple branches, like [`jupyterlab`](https://github.com/conda-forge/jupyterlab-feedstock). I don't have a strong opinion on one method or another.


> Branch off the most recently updated branch in the feedstock. In this case, rc.

We needed to update `master` with the contents of `rc` because during the transition from 7.5.0 to 7.5.1 several things happened:

* We received an automated PR for PyPy builds, which only 7.5.1 would support. 
* The PR initially failed due to some shortcomings in the recipe. I used this PR to improve the recipe with unit tests and other checks we would consider beneficial in the future. 
* This PR ended up being the first 7.5.1rc, merged to `rc`.
* Thus, `rc` ended up with some improvements the stable builds could use too. That's why we branched off `rc` for the final release.

Branches are not meant to be deleted. They are supposed to be there for provenance and backported updates, if needed. In the future, you can choose to create a new `rcXYZ` branch, or merge to `rc` again. The key difference is that `channel_targets` will point to a different label.

With time, we will hopefully stop being one of the most experimental feedstocks, with bleeding edge CUDA support, and things would stabilize so "improvements" are not needed as often. 

Let me know if further clarification is needed!

***

> My PR is at conda-forge/openmm-feedstock#54.

Awesome! Check my last comment to include the Windows fix there.

**Comment by giadefa** [comment]
Jaime any news on the PPC version?

g

**Comment by jaimergp** [comment]
The Conda Forge team has to decide what to do with CUDA 11+ on PPC, which requires CentOS 8's glibc, which is not yet packaged as a sysroot on CF. We can technically deploy support for CUDA 10.2 already (because it uses CentOS 7), but the discussion is now focused on the organizational details. You can follow the discussion [here](https://github.com/conda-forge/nvcc-feedstock/pull/66).

**Comment by giadefa** [comment]
The discussion there on CentOS is probably not so useful in my view. CentOS
is dead. They just need to guarantee compatibility with RedHat X.X.

g

**Comment by peastman** [comment]
So it's impossible to make changes to the repository on any branch without creating a new release?  There's no way to split your changes across multiple PRs, merge them separately, but only do a release when all the changes are complete?

**Comment by jaimergp** [comment]
I am afraid that's not part of the workflow. I guess you could intentionally merge a broken build so the upload doesn't happen; or manually change the value of the `upload_packages` variable in the pipelines. Most packages work fine with the one PR = one release assumption. Other workflows would need to be discussed with the CF team.

**Comment by mikemhenry** [comment]
> So it's impossible to make changes to the repository on any branch without creating a new release? There's no way to split your changes across multiple PRs, merge them separately, but only do a release when all the changes are complete?

I think this is a good workflow from a software engineering perspective, but I get the impression that CF wants that workflow to happen on the repo for the package, and the PR to the feedstock should only be for packaging. Or are the changes you are talking about for the feedstock recipe?

**Comment by peastman** [comment]
I'm talking about changes to the recipe.  A good example of this is the change mentioned in https://github.com/conda-forge/openmm-feedstock/pull/54#issuecomment-829016880.  Something (probably an upstream change to some other package?) caused the Windows tests to start failing.  Jaime discovered it while building the release candidate, and he had to make a change to the test script to fix it.  That change wasn't specific to any particular release, and it's needed for all future builds.  So it would have been cleanest to fix it on the main branch in its own PR.  But apparently we can't do that.  There's no way to tell conda-forge, "This PR fixes a bug for future releases, but it isn't itself a new release."

**Comment by mikemhenry** [comment]
Yikes now I see what you mean, that is annoying.

**Comment by peastman** [comment]
The 7.5.1 builds are now up, so we can close this!
