### ISSUE TITLE
Expand API to include addParticleParameterScaling()

### ISSUE THREAD

**Issue by zhang-ivy** [openmm/openmm#2999]
@jchodera, @dominicrufa and I are actively developing [perses](https://github.com/choderalab/perses), our relative free energy calculation software, and have found that it is very difficult to control the scaling of the same particle with two different lambdas.

In our existing implementation of perses, we change a WT residue (lambda = 0) to a mutant residue (lambda = 1). To handle electrostatics, we use `addParticleParameterOffset()` in the `NonbondedForce`. However, we also would like to be able to add a temperature scaling lambda (or any other scaling factor) which scales the temperature of the system at the same time as the alchemical transformation, but this is difficult to handle given the way that offsets work:
```
charge = baseCharge + param*chargeScale
sigma = baseSigma + param*sigmaScale
epsilon = baseEpsilon + param*epsilonScale
```
Would it be possible to expand the API to include something like `addParticleParameterScaling()`  to the `NonbondedForce()` (that cannot be used as the same time as `addParticleParameterOffset()`)? 
We envision that `addParticleParameterScaling()` would work like this:
```
charge = baseCharge*(param)
sigma = baseSigma*(param)
epsilon = baseEpsilon*(param)
```
And if two of them are added to the same particle, the original term would be multiplied by both scalings (e.g. `charge = baseCharge*param1*param2`)

**Comment by peastman** [comment]
I think this is just equivalent to adding two offset parameters and setting the base value to 0?

```
charge = 0 + chargeScale1*param1 + chargeScale2*param2
```

By choosing appropriate values for the two scales and parameters, you should be able to do exactly what you described.  Is there a case I'm missing?

**Comment by jchodera** [comment]
@dominicrufa @zhang-ivy : Would this extension still be helpful to you folks?

**Comment by dominicrufa** [comment]
Yes, I think this would be incredibly helpful. I think that there are
benefits to having multiplicative parameters because and/or logic in
standard nonbondeds could be coded up much more easily this way. In
implementing REST-like enhanced sampling, I’ve encountered this several
times.

**Comment by jchodera** [comment]
So is the proposal that adding
```python
particle_index = nbforce.addParticle(charge, sigma, epsilon)
nbforce.addParticleParameterScaling(parameter1, particle_index, charge1, sigma1, epsilon1)
nbforce.addParticleParameterOffset(parameter2, particle_index, charge2, sigma2, epsilon2)
```
would yield new parameters like
```
new_charge = charge*parameter1*charge1 + parameter2*charge2
```
?

I think @peastman is right that, provided the parameters can be additive, this can just be done with two calls to `addParticleParameterOffset`:
```python
particle_index = nbforce.addParticle(0, 0, 0)
nbforce.addParticleParameterScaling(parameter1, particle_index, charge1, sigma1, epsilon1)
nbforce.addParticleParameterOffset(parameter2, particle_index, charge2, sigma2, epsilon2)
```
Is there really a complexity reduction in the Python code that you'd write using this? Perhaps you could give an example of how this could simplify things?

**Comment by dominicrufa** [comment]
Ah, I guess I didn’t give this too much thought. I think peter is right,
too. We can probably close this issue.
