### ISSUE TITLE
read the psf file that includes the drude particles

### ISSUE THREAD

**Issue by ahmedo047** [openmm/openmm#3007]
Hi,

I am trying to run a simulation using OpenMM-7.4.2 with CHARMM Drude FF (`charmm_polar_2019.xml`) but I get the below error:
```
...
    self.psf = CharmmPsfFile(psffile)
NameError: name 'CharmmPsfFile' is not defined
```
My questions are:
-how can I fix the above error?
-My `psf` file includes the drude particles as well. Does the `CharmmPsfFile `read the drude particles from the `psf` file?

**Comment by peastman** [comment]
It looks like you probably haven't imported the class.  You need to first do something like

```python
from simtk.openmm.app import *
```

> Does the CharmmPsfFile read the drude particles from the psf file?

Yes.
