### ISSUE TITLE
OpenMM constraint algorithms

### ISSUE THREAD

**Issue by balazsfabian** [openmm/openmm#3013]
The [manual](http://docs.openmm.org/latest/userguide/application.html#constraints) only specifies the possible values, but not the algorithm. I found Lincs, CCMA and SETTLE in openmm/platforms/reference/src/SimTKReference/. Naively, I tried to add some std::cerr statements to see which one gets called through the python wrapper, but nothing printed.

* Could you tell me what kind of constraint algorithms are implemented in OpenMM? And is there a way to choose between them?
* How can I "debug" OpenMM functions that are called through the python wrapper?

Thank you!

**Comment by peastman** [comment]
It depends on the details of your system and on the platform.  Generally it will use a mix of different algorithms for different parts of the system.

- All platforms use SETTLE for water molecules.
- The CUDA and OpenCL platforms use SHAKE for isolated clusters of one heavy atom with up to three hydrogens bonded to it.
- CCMA is used for anything not handled by one of the above algorithms.
