### ISSUE TITLE
ChecksumMismatchError

### ISSUE THREAD

**Issue by mikemhenry** [openmm/openmm#3021]
Working on troubleshooting an issue I have with a nightly build/dev version of openmm.
I thought I just had some interment HTTP issues but I consistently get this error, even when using docker to try and stay isolated from any other environmental weirdness.
This command: 

`docker run --rm -it continuumio/miniconda3:4.9.2 conda create -y -n openmm-debug -c omnia-dev openmm python=3.8`

Gives me this error:

```
ChecksumMismatchError: Conda detected a mismatch between the expected content and downloaded content
for url 'https://conda.anaconda.org/omnia-dev/linux-64/openmm-7.4.1-py38_cuda102_0.tar.bz2'.
  download saved to: /opt/conda/pkgs/openmm-7.4.1-py38_cuda102_0.tar.bz2
  expected md5: da5a9cc43a68852896dda8514d0fe5ba
  actual md5: 19481cbdcf3d2e5f037536a891fbeebc
```

**Comment by jchodera** [comment]
@mikemhenry : That's odd.
Note that we are still using the `omnia-dev` channel for nightly test builds, but the latest version is now 7.5.1:
https://anaconda.org/omnia-dev/openmm/files

The releases are now through the `conda-forge` channel.

**Comment by jaimergp** [comment]
@mikemhenry let's book an hour so we sync on some of the CI/build infrastructure details of OpenMM! You might have needed `-c conda-forge` on that command line too, but there are other things to take into account. Reach me on Slack!

**Comment by mikemhenry** [comment]
7.4.1 is being pulled in due to the  conflict between the python, numpy, and openmm version:

```
➜ docker run --rm -it continuumio/miniconda3:4.9.2 conda create -y -n openmm-debug -c omnia-dev openmm=7.5.1 python=3.8
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed 

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package python conflicts for:
openmm=7.5.1 -> numpy -> python[version='>=2.7,<2.8.0a0|>=3.9,<3.10.0a0|>=3.5,<3.6.0a0']
openmm=7.5.1 -> python[version='>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0']
python=3.8
```

This is a separate issue, but looks like it will cause problems for people trying to do python 3.8 and omnia 7.5.1 (at least when using only the `omnia-dev` channel and the defaults)

Adding `-c conda-forge` makes this error go away.
