### ISSUE TITLE
Namespace Change is Not Backwards Compatible [NIGHTLY]

### ISSUE THREAD

**Issue by mikemhenry** [openmm/openmm#3022]
In an environment with openmm nightly, this correctly gives the deprecation warning:

``` python
>>> import simtk.openmm
Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
```

But this does not:

``` python
>>> from simtk.openmm.app.element import Element
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'simtk.openmm.app.element'
```

I've discussed the issue with @jaimergp and I have a plan to fix this with a PR.

**Comment by jaimergp** [comment]
To clarify, `7.5.1` is the placeholder version for the latest nightlies at `omnia-dev`.

I guess the deprecation warnings would be part of the _real_ 7.5.1, discussed at #2993

**Comment by peastman** [comment]
The name change isn't in any release yet.  That's why we have nightlies: to catch things like this before they get released. :)

**Comment by peastman** [comment]
Could you describe your plan before sending the PR?

**Comment by mikemhenry** [comment]
Sorry for the confusion! I was going off of the version number in the dev channel, I've edited the post to make this more clear for future readers.

My plan is to ensure `python -m simtk.testInstallation` works by chaninging `simtk/testInstallation/__main__.py` to 

``` python
from openmm.testInstallation import main; if __name__ == "__main__": main()
```
 and fix the other imports with `simtk/__init__.py`

``` python
import openmm
from openmm import unit
```

I've got a few test cases to ensure it works.

I have never contributed to openmm before so it will take me a bit of time to get my development env setup.

**Comment by peastman** [comment]
What's your plan for fixing `from simtk.openmm.app.element import Element`?

Note that `from simtk.openmm.app import Element` does work correctly.  The problem only appears if people include the name of the individual `.py` file as part of the module path.

**Comment by mikemhenry** [comment]
I was going to create the file structure of the old namespace but then use the correct imports for the new namespace. 

I'm not sure what I am doing wrong but `from simtk.openmm.app import Element` does not work correctly for me.

```python
>>> import simtk.openmm
Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
>>> from simtk.openmm.app.element import Element
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'simtk.openmm.app.element'
>>> 
```
```
$ conda list
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
brotlipy                  0.7.0           py38h8df0ef7_1001    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.17.1               h36c2ea0_0    conda-forge
ca-certificates           2020.12.5            ha878542_0    conda-forge
certifi                   2020.12.5        py38h578d9bd_1    conda-forge
cffi                      1.14.4           py38ha65f79e_1    conda-forge
chardet                   4.0.0            py38h578d9bd_0    conda-forge
conda                     4.9.2            py38h578d9bd_0    conda-forge
conda-package-handling    1.7.2            py38h8df0ef7_0    conda-forge
cryptography              3.3.1            py38h2b97feb_0    conda-forge
fftw                      3.3.9           nompi_hcdd671c_100    conda-forge
icu                       68.1                 h58526e2_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
krb5                      1.17.2               h926e7f8_0    conda-forge
ld_impl_linux-64          2.35.1               hea4e1c9_1    conda-forge
libarchive                3.3.3             hddc7a2b_1008    conda-forge
libblas                   3.9.0                8_openblas    conda-forge
libcblas                  3.9.0                8_openblas    conda-forge
libcurl                   7.71.1               hcdd3856_8    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc-ng                 9.3.0               h5dbcf3e_17    conda-forge
libgfortran-ng            9.3.0               hff62375_18    conda-forge
libgfortran5              9.3.0               hff62375_18    conda-forge
libgomp                   9.3.0               h5dbcf3e_17    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblapack                 3.9.0                8_openblas    conda-forge
libnghttp2                1.41.0               h8cfc5f6_2    conda-forge
libopenblas               0.3.12          pthreads_h4812303_1    conda-forge
libsolv                   0.7.16               h8b12597_0    conda-forge
libssh2                   1.9.0                hab1572f_5    conda-forge
libstdcxx-ng              9.3.0               h2ae2ef3_17    conda-forge
libxml2                   2.9.10               h72842e0_3    conda-forge
lz4-c                     1.9.2                he1b5a44_3    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
mamba                     0.7.6            py38h4c9354d_0    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
numpy                     1.20.1           py38h18fd61f_0    conda-forge
openmm                    7.5.1            py38_cuda102_1    omnia-dev
openssl                   1.1.1i               h7f98852_0    conda-forge
pip                       20.3.3             pyhd8ed1ab_0    conda-forge
pycosat                   0.6.3           py38h8df0ef7_1005    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1            py38h924ce5b_2    conda-forge
python                    3.8.6           hffdb5ce_4_cpython    conda-forge
python_abi                3.8                      1_cp38    conda-forge
readline                  8.0                  he28a2e2_2    conda-forge
reproc                    14.2.1               h36c2ea0_0    conda-forge
reproc-cpp                14.2.1               h58526e2_0    conda-forge
requests                  2.25.1             pyhd3deb0d_0    conda-forge
ruamel_yaml               0.15.80         py38h8df0ef7_1003    conda-forge
setuptools                49.6.0           py38h924ce5b_2    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.34.0               h74cdb3f_0    conda-forge
tk                        8.6.10               h21135ba_1    conda-forge
tqdm                      4.55.0             pyhd8ed1ab_0    conda-forge
urllib3                   1.26.2             pyhd8ed1ab_0    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
zstd                      1.4.5                h6597ccf_2    conda-forge
```

**Comment by peastman** [comment]
That depends how easy it is.  Our examples have always imported from `simtk.openmm.app`, never adding an additional module name beyond that, so hopefully that's what most people are doing.  So I don't think it's critical, but if we can easily do it that would be good.

**Comment by jaimergp** [comment]
Github searches are too good to be true! This is what you can find in the wild wrt to the imports:

* [`from simtk.openmm.app.element import Element`](https://github.com/search?q=from+simtk.openmm.app.element+import+Element&type=code): 283 results
* [`from simtk.openmm.app import Element`](https://github.com/search?q=from+simtk.openmm.app+import+Element&type=code): 876 results

Definitely not as popular, but also not negligible...

**Comment by peastman** [comment]
You need to put the search term in quotes.  Otherwise it finds a lot of approximate matches that are actually different.  Here are those same searches with quotes, plus one other variation.

- ["from simtk.openmm.app.element import Element"](https://github.com/search?q=%22from+simtk.openmm.app.element+import+Element%22&type=code): 17 results
- ["from simtk.openmm.app import Element"](https://github.com/search?q=%22from+simtk.openmm.app+import+Element%22&type=code): 60 results, but there's no way to make the search case sensitive.  Some of the matches are importing `Element` (the class), while others are actually importing `element` (the submodule).
- ["simtk.openmm.app.element.Element"](https://github.com/search?q=simtk.openmm.app.element.Element&type=code): 44 results, but only one is in Python.  Most are in automatically generated docs files.

Looking through the matches, I further see that a lot of them are actually just in forks of OpenMM, which will get fixed automatically when/if the owners update to a version with the package name change.  For example, of the 17 matches for "from simtk.openmm.app.element import Element", 11 are in copies of charmmparameterset.py.

**Comment by mikemhenry** [comment]
I don't have an openmm development system setup to test and play with this yet--when will a release with this change be cut? 

I'd like to add backwards compatible support for importing like `from simtk.openmm.app.element import Element` _unless_ there is some PEP or openmm doc that discourages importing that way. Not having an example isn't quite enough (most of the time users copy and paste so I'm guessing the history of this is someone wrote this in one place and it has been copied). When a public API breaks, I just like being able to point to something and say "here it said it was a bad idea and now you know why"

**Comment by peastman** [comment]
You can install the latest nightly build with conda.  We don't have a release scheduled anytime soon, and we certainly won't make a release containing this change until *after* we're happy with the behavior!

**Comment by mikemhenry** [comment]
Sorry I was asking about the timeline since I wanted to work on this issue but wanted to know if a release was happening really soon. It doesn't sound like one is so I'll have some time to play with this to see if I can come up with a solution that keeps things as backwards compatible as possible.

**Comment by jchodera** [comment]
@peastman: It this a `wontfix` then? How should we label it and move on?

**Comment by peastman** [comment]
I'd be ok with that if everyone else is.

**Comment by mikemhenry** [comment]
I think changing our imports in openmmtools and other packages is the right fix. I don't really have the openMM dev setup to iterate on different ways to make it even more backwards comptable. I expect we will get some users who will complain when `from simtk.openmm.app.element import Element` breaks but we can just tell them to change their import -- should be a low friction fix.
