### ISSUE TITLE
Performance on embedded nvidia GPUs

### ISSUE THREAD

**Issue by pgrinaway** [openmm/openmm#3024]
Hi,

I have a quick if unusual question: does anyone know what kind of performance (in terms of ns/day on standard benchmarks) one could get using an embedded nvidia GPU such as the Jetson AGX Xavier? Obviously it would be interesting to have numbers, but since nobody has likely tried using these GPUs, is there a good way for me to guesstimate the performance using specs such as CUDA cores, etc?

Thanks for the help--happy to provide extra info if that would assist.

**Comment by peastman** [comment]
There are benchmarks for a lot of different GPUs at https://github.com/openmm/openmm/issues/2865#issuecomment-699063714.  I would start by looking for the most similar GPU on that list.  Find one that's the same generation, and as close as possible in number of cores and clock rate.  If it isn't exactly the same, assume performance will scale linearly in cores and clock rate.  That isn't exactly true, but it will give you a reasonable estimate.

**Comment by pgrinaway** [comment]
Ok, thanks!
