### ISSUE TITLE
Specific custom external force

### ISSUE THREAD

**Issue by kolotinsky1998** [openmm/openmm#3026]
Hello, dear community!

My question concerns the possibility to use a non-string parameter for the CustomExternalForce class. I want to solve a system of coupled equations: Newton's for particle motion and Poisson's to calculate self-consistent electrostatic potential in which these charged particles advance. I need to solve Poisson's equation every time step particles advance. I have an idea to implement it by rewriting CustomExternalForce class. However, for that purpose, I need somehow reload the CustomExternalForce class methods. Could you give me any advice on how can I do it?

Daniil

**Comment by peastman** [comment]
You'll definitely need to write a plugin to do that.  Can you describe in more detail what you want to do?  I don't really understand what you mean by "use a non-string parameter" or "reload the CustomExternalForce class methods."  The more detail you can provide, the better.

**Comment by kolotinsky1998** [comment]
The simulation I want to conduct is the following:

1. Charged particles are distributed in the 3D computational domain
2. Calculate charge density according to the particle space distribution
3. Interpolate 3d charge density to obtain continuous space function (scipy library)
4. Solve Poisson's equation for that interpolated density function (hear I want to use FeniCS Finite Element Library with python interface)
5. Calculate electrical field taking the gradient of computed potential
6. Calculate forces acting on each charged particle from the electrical field
7. Advance particle
8. Do the 1st-7th steps again while a number of steps < N_steps

I thought about the possibility to make 2nd-6th stages inside  CustomExternalForce class

**Comment by peastman** [comment]
CustomExternalForce just evaluates a single expression, nothing more.  It doesn't solve Poisson's equation, and it doesn't invoke Python libraries!

You can perhaps achieve what you want by using a CustomExternalForce that just applies a constant force to each particle:

```python
force = CustomExternalForce('-fx*x-fy*y-fz*z')
force.addPerParticleParameter('fx')
force.addPerParticleParameter('fy')
force.addPerParticleParameter('fz')
```

At each time step do the following.

1. Run all your calculations to compute the force you want to apply to each particle.
2. For each particle, call `force.setParticleParameters(i, i, force[i])` to set the force you want applied to it.
3. Call `force.updateParametersInContext(context)` to copy them over to the context.

This has overhead, but compared to all the calculations you're doing it shouldn't be significant.

**Comment by kolotinsky1998** [comment]
Thank you very much, I will definitely try this approach!
