### ISSUE TITLE
How to deal with periodic box condition in CustomCentroidBondForce

### ISSUE THREAD

**Issue by VincenzoChen** [openmm/openmm#3027]
I want to add a distance restraint between mass centers of two groups in a system to keep these two groups in a reasonable distance. Here I follow the code stated as following:
```
CustomCentroidBondForce* force = new CustomCentroidBondForce(2, "0.5*k*distance(g1,g2)^2");
force->addPerBondParameter("k");
force->addGroup(particles1);
force->addGroup(particles2);
vector<int> bondGroups;
bondGroups.push_back(0);
bondGroups.push_back(1);
vector<double> bondParameters;
bondParameters.push_back(k);
force->addBond(bondGroups, bondParameters);
```
I wonder that whether the function distance(g1,g2) will take the periodic box condition into consideration and return the minimal distance between mass centers of two groups? If not, how can I deal with periodic box condition when I calculate distance?
Another question is class CustomCentroidBondForce support user give the coordinates of mass center. If I want to use x1, y1, z1, x2, y2, z2 calculated by myself which is the coordinates of mass center of two groups in this code line:```CustomCentroidBondForce* force = new CustomCentroidBondForce(2, "0.5*k*((x1-x2)^2+(y1-y2)^2+(z1-z2)^2)")```, how does the force apply to the corresponding groups because it seems that I have not assigned groups?

**Comment by peastman** [comment]
You can tell it whether or not to use periodic boundary conditions.  Call `force->setUsesPeriodicBoundaryConditions(true)`.

I don't understand your second question.  You don't calculate the center of mass coordinates yourself.  The force calculates them.  If that isn't what you want, then CustomCentroidBondForce isn't the right tool to use.  Can you describe what you're trying to accomplish?

**Comment by VincenzoChen** [comment]
For the second question I follow the manual of CustomCenteroidBondForce [here](http://docs.openmm.org/7.0.0/api-c++/generated/OpenMM.CustomCentroidBondForce.html#_CPPv2N6OpenMM23CustomCentroidBondForce7addBondERKNSt6vectorIiEERKNSt6vectorIdEE) and it said:
```
CustomCentroidBondForce() evaluates a user supplied algebraic expression to determine the interaction energy. The expression may depend on the following variables and functions:

- x1, y1, z1, x2, y2, z2, etc.: The x, y, and z coordinates of the centers of the groups. For example, x1 is the x coordinate of the center of group g1, and y3 is the y coordinate of the center of group g3.
- distance(g1, g2): the distance between the centers of groups g1 and g2 (where “g1” and “g2” may be replaced by the names of whichever groups you want to calculate the distance between).
- angle(g1, g2, g3): the angle formed by the centers of the three specified groups.
- dihedral(g1, g2, g3, g4): the dihedral angle formed by the centers of the four specified groups.
```
It seems that the CustomCentroidBondForce can take use of the x1,y1,z1,x2,y2,z2 we give. So here comes the question that if we give the coordinates directly to calculate the force, how does it know which two groups will the force add to because we just give center mass coodinates of groups but not expilicity assign the groups just like that by function distance(g1,g2)?

**Comment by peastman** [comment]
The group number is part of the variable name.  From the documentation you quoted above:

> For example, x1 is the x coordinate of the center of group g1, and y3 is the y coordinate of the center of group g3.

**Comment by VincenzoChen** [comment]
That's help a lot. Thank you very much!

**Comment by VincenzoChen** [comment]
Another question is that does the unit of distance(g1,g2) measured in nm in code ```CustomCentroidBondForce* force = new CustomCentroidBondForce(2, "0.5*k*distance(g1,g2)^2")```? For example, if I want to add force between mass centers of two groups when their distance is more than 1nm but keep this force equal to zero if their distance is less than 1 nm, I specify the energy function like this:
```posres = CustomCentroidBondForce(2,"fc_pos*(step(distance(g1,g2)-1)*distance(g1,g2))^2")```
I wonder whether it is correct or not?

**Comment by peastman** [comment]
Correct.  However, you probably don't want to use that expression, because it has a discontinuity when the distance is 1 nm.  A better option would be something like `"fc_pos*max(0, distance(g1,g2)-1)^2"`.

**Comment by VincenzoChen** [comment]
Yeah, you are right. I have not considered the discontinuity when the distance is 1 nm ever before. Thank you very much!
