### ISSUE TITLE
what():  Error initializing FFT: 5？

### ISSUE THREAD

**Issue by hongxiahao91** [openmm/openmm#3028]
Hi all,
I'm trying to run openmm, but encountered the error

 Platform CUDA :  Setting Precision to MIXED via CUDA-PRECISION
terminate called after throwing an instance of 'OpenMM::OpenMMException'
  what():  Error initializing FFT: 5

Program received signal SIGABRT: Process abort signal.

Does anyone have clues about what this means and how to solve the problem?

**Comment by peastman** [comment]
Error code 5 is `CUFFT_INTERNAL_ERROR`.  The documentation describes it as, "Driver or internal cuFFT library error."

That sounds like something may be messed up on your computer.  Could you provide **all** of the following?

- The operating system you're using
- The GPU you're using
- The CUDA version you're using
- How you installed CUDA (an installer from NVIDIA's website, with conda, etc.)
- The driver version you're using
- How you installed the driver
- Whether other programs that use CUDA work on your computer

**Comment by hongxiahao91** [comment]
Thank you very much for the help. I compiled it on the university cluster. It indeed turns out that something went wrong with the system. And now after two days, I rerun the job, they are working well now. Thanks!

**Comment by peastman** [comment]
Glad it's working now!
