### ISSUE TITLE
Build for CUDA 10.1

### ISSUE THREAD

**Issue by mkrompiec** [openmm/openmm#3030]
Hi, I can't find a build for linux-64, python 3.7 (or 3.8) and CUDA 10.1 on the conda-forge channel. It seems that all three builds are for CUDA 11.0/11.1/11.2.  It would be great if you provided a build for CUDA 10.1 as well. Upgrading CUDA drivers on a managed HPC is not something we want to do too often...

**Comment by peastman** [comment]
We have builds for CUDA 9.2, 10.0, 10.1, 10.2, 11.0, 11.1, and 11.2.

**Comment by jchodera** [comment]
@mkrompiec : Following the [installation docs](http://docs.openmm.org/latest/userguide/application.html#installing-openmm), you should be able to install 10.1 with
```bash
conda install -c conda-forge openmm cudatoolkit=10.1
```
If that doesn't work for you, can you send the error message you receive?

**Comment by mkrompiec** [comment]
Our cluster can't connect to external Internet sites so I have to manually download packages and install with conda install  --offline. On https://anaconda.org/conda-forge/openmm/files?version=7.5.0 there are 3 packages for linux-64 and Python 3.7. I checked their dependencies and it appears that they are for, respectively, cudatoolkit 11.0, 11.1 and 11.2. Same situation for Python 3.8. Or am I looking in the wrong place?

**Comment by mkrompiec** [comment]
I checked again and was able to find the right package. Not sure what had happened previously...

**Comment by Bio-Otto** [comment]
You can check with @jchodera argument with typing `conda install -c conda-forge openmm cudatoolkit=10.1 --download-only`.

**Comment by jchodera** [comment]
> Our cluster can't connect to external Internet sites so I have to manually download packages and install with conda install --offline

Oh my! That sounds horribly inconvenient.

For the [Open Force Field Initiative](http://openforcefield.org), we've had good luck building standalone installers with [this tool](https://github.com/openforcefield/toolkit-installer-constructor). You can use it to build a miniconda-like installer distribution with the desired conda environment packages and dependencies baked in!
