### ISSUE TITLE
Modify PDB for simulation

### ISSUE THREAD

**Issue by phisanti** [openmm/openmm#3035]
First of all, sorry if this is not the place for this question. I have built a system for a simulation with charmm-gui. The test went alright, but I got an issue that I would like to optimise. The system follows this tutorial: 
https://www.youtube.com/watch?v=KNEhbHbCYGM

Now, I have noticed that the simulation contains lots of water in the bottom layer that probably can be ignored. Therefore, I was wondering if I could use the "Modeller" within openMM to remove the water below z <10. The idea would be to do something reverse to this:

```python
pdb = PDBFile('input.pdb')
modeller = Modeller(pdb.topology, pdb.positions)
modeller.addHydrogen(forcefield, pH=7.0) 
modeller.addSolvent(forcefield, padding=1.0*nanometers, model='tip3p’) # Instead of adding water, I want to remove water below z < 10
modeller.addSolvent(forcefield, boxSize=Vec3(5.0, 3.5, 3.5)*nanometers)  # Then I suppose I have to adapt box size.

```
adapted from: https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwjS2ZWKrIfvAhUiQkEAHWY-CmoQFjAAegQIARAD&url=https%3A%2F%2Fsimtk.org%2Fdocman%2Fview.php%2F161%2F1748%2FPresentation3_IntroSimulationExercises.pdf&usg=AOvVaw01kLIsI2BxUMzA6t3GZ_QG

Another way to deal with this could be to use an implicit model because I am not sure if the water, despite being present, is interacting with the protein at all. Using the model as it comes, I expect it to at least from some H---O---H bridges between protein and water.  However, I am quite new in the MD world, so I am not sure if that is happening.

Once again, sorry if the question doesn't belong here, and thank you for the help in advance.

**Comment by peastman** [comment]
That's easy to do, but first make sure you really want to do it.  Is it possible the protein could rotate over the course of the simulation?  For a membrane simulation that isn't generally a problem, but for a globular protein in water the protein can freely rotate.  Make sure the box is large enough in all directions so the protein won't collide with itself however it rotates.

Assuming that isn't a problem for you, something like the following will remove all waters with z<10.  (I haven't tested this code, but hopefully I'm not making too many mistakes typing it into the browser.)

```python
delete = []
for residue in modeller.topology.residues():
  if residue.name == 'HOH':  # This is a water
    oxygen = [atom for atom in residue.atoms() if atom.element == element.oxygen][0]  # Find the oxygen atom
    if modeller.positions[oxygen.index][2] < 10:
      delete.append(residue)
modeller.delete(delete)  # Delete all the residues we found above
```

**Comment by phisanti** [comment]
That looks like a very clever solution! However, once I have removed all the waters below the position z<10, should not there be a command to reduce the "box size"? Would the simulation take empty space as a vacuum?

Regarding the rotation, I have done some small simulation test and I see some lateral (XY axis) movement, but up or down movement. Does it mean I am safe?

**Comment by peastman** [comment]
I just realized I forgot to do that!  Yes, you can call `modeller.topology.setUnitCellDimensions()` to tell it the new shape.  After doing all of this, you should also do a local energy minimization, then equilibrate for a while with a barostat so the box size can adjust to the exact amount of water you have left.

> Does it mean I am safe?

Not necessarily.  You may not see any significant rotation in a short simulation, but that doesn't mean it won't happen in a longer one.  It may just take more time.
