### ISSUE TITLE
AmberPrmtopFile support is broken for ff19SB

### ISSUE THREAD

**Issue by swails** [openmm/openmm#3040]
The new generation of Amber force fields have adopted CMAP terms.  OpenMM doesn't parse these sections, but also doesn't fail if they're present, meaning that any Amber topology file that has CMAP terms is silently and non-obviously doing the wrong thing.

**Comment by peastman** [comment]
#3041 adds an error message.  We should add proper support for CMAPs in prmtop files.

**Comment by peastman** [comment]
This was implemented in #3143.
