### ISSUE TITLE
Options for a clean implementation of a hybrid meta-Force?

### ISSUE THREAD

**Issue by egallicc** [openmm/openmm#3045]
We have this approach called [Alchemical Transfer](https://arxiv.org/abs/2101.07894) for alchemical calculations based on displacing molecules around. It is implemented in the [SDM 2 plugin](https://github.com/rajatkrpal/openmm_sdm_plugin) and it appears to work surprisingly well for both absolute and relative binding free energy calculations.

The approach is based on a hybrid potential energy function that basically looks like:

     U(x, lambda) = lambda * U(x + displacement) + (1-lambda) * U(x)

where U(x) is the OpenMM potential energy function with whatever set of forces are added to the system (any kind of force works, including many-body potentials as far as we can tell).

Currently, we are evaluating U(x, lambda) inside a modified Langevin integrator by, essentially, calling calcForcesAndEnergy() before and after the displacement.

My question is: is there a way to implement this meta-force so that it would appear to OpenMM as the regular set of forces invoked by calcForcesAndEnergy()? This could hypothetically enable the method for any integrator/barostat combination, it would allow the retrieval of the alchemical potential energy by standard means such as getState(), etc. 

Maybe there are other clever options. Any feedback is greatly appreciated!

**Comment by peastman** [comment]
One option would be to copy the approach used by CustomCVForce.  Internally it creates its own System and Context and uses them to evaluate forces.  This would actually be simpler than CustomCVForce.  It uses the forces and energies to evaluate a new energy expression, whereas you could just pass them on unmodified.

**Comment by egallicc** [comment]
Thank you @peastman. We'll look at CustomCVForce. It sounds very promising.

**Comment by jchodera** [comment]
I'll second that the proposed feature would be incredibly useful, especially since this kind of simple linear combination of potentials works very well with machine learning potentials like ANI.

**Comment by egallicc** [comment]
Yes, John, it is a very exciting use case. If you can point us in the right direction, we can start testing with the existing code while we work on the cleaner solution proposed by Peter.

**Comment by jchodera** [comment]
@egallicc : I think we should consider having @peastman spec out (and implement, if sensible) a new OpenMM feature to do what you suggest. 

In the meantime, your current approach---using the integrator to compute this hybrid potential---is probably the best approach (though slower since it triggers the pairlist recalculation every step).

Is your displacement always a constant, out of curiosity? Or does the magnitude and/or direction change during the simulation, or depend on other things?

**Comment by egallicc** [comment]
@peastman's help in any form would be more than welcome if available!

I am not sure how the recalculation of the neighbor list can be avoided unless two neighbor lists are maintained, one for the pre- and another for the post-displacement states. An alternative we envisioned was to somehow assign the ligand to multiple voxels corresponding to the regions occupied by the ligand in the receptor and in the solvent bulk. 

We have measured a rather moderate 15% slow-down when recalculating the neighbor list at every step for host-guest systems. We should benchmark protein systems. Anyway, it does not look like a  show-stopper, for testing at least.

Yes,  the displacement vector is fixed. For absolute binding free energy calculations, we like to set it so that the ligand occupies one of the corners of the box when this is centered on the CM of the receptor. For relative binding free energies, the two ligands are displaced in opposite directions to swap their positions. (Their relative orientations are optionally restrained to keep them aligned. Also, the plugin supports arbitrary displacement maps, but these two are the only setups we have tried so far.)

**Comment by peastman** [comment]
Using the CustomCVForce approach, each of the two contexts (the main context where you're running the simulation, and the one created by the force) has its own neighbor list.  Each of them will get recalculated when an atom has moved far enough to require it.  Since the displacement remains fixed, that means both contexts will recalculate the respective neighbor lists at the same time.

**Comment by egallicc** [comment]
I see. Nice. It is good for the synchronization of the two contexts. I guess it would be the same for unitary affine transformations since they are distance-preserving? These could be useful for connecting alternative binding modes. 

What about the communication of coordinates and the merging of forces between the contexts? Would it slow-down the GPU platforms?

Also, could displaced virtual particles play a role? The neighbor list of the virtual displaced ligand would be taken care of. Then it would be a matter of turning on and off the real or the virtual particles to compute the components of the hybrid potential. Probably a virtual particles approach would not be relevant for a multi-context/multi-neighbor list approach, but maybe it could be a stepping stone to address the neighbor list issue of the current single-context prototype.

**Comment by peastman** [comment]
> What about the communication of coordinates and the merging of forces between the contexts? Would it slow-down the GPU platforms?

The communication itself should only have small overhead.  Both contexts are on the same GPU, so copying data between them is fast.  Some slowdown is unavoidable, since you're doing extra work.  But it shouldn't be a major issue.

> Also, could displaced virtual particles play a role?

If I've correctly understood what you're doing, it shouldn't make any difference whether a particle is virtual or not.  You're never going to be computing virtual particle locations in the inner context.  You'll just take the positions from the outer context, however they were calculated, and apply a fixed displacement to a subset of them.

**Comment by egallicc** [comment]
Sorry, I was not very clear regarding the question about virtual particles. The atoms of the ligand in the displaced position could conceivably be represented as virtual particles at positions (x + displacement) relative to the positions (x) of the atoms in the original positions. If feasible, in this representation, particle positions are not changed and the transformation would be implemented by turning their interactions on and off. And the neighbor list would not have to be recalculated at each step because the neighbors of each particle (virtual or otherwise) would be tracked in the usual way. Right?

Anyway, this virtual particle representation is probably not useful for a multi-context implementation.

**Comment by egallicc** [comment]
Regarding the GPU performance: it is great that the communication overhead is not significant on a single GPU. Additionally, because the calculation of energy and forces for the original and displaced states is embarrassingly parallel, there is maybe the opportunity of boosting performance for very large systems by distributing the load on two GPUs.

Does the scheme implemented in CustomCVForce allow for spawning a context on a different GPU?

**Comment by peastman** [comment]
Yes, that would be another way of implementing it.  If the number of particles you're displacing is small, that would be efficient.  You could use a parameter offset to turn interactions on and off with a global parameter.  That might well be the best way of doing it.

You might need to create a new virtual particle class to handle this.  That isn't difficult though.

> Does the scheme implemented in CustomCVForce allow for spawning a context on a different GPU?

In theory you could write it to do that.  It would take more work, and add communication overhead.

**Comment by egallicc** [comment]
> You could use a parameter offset to turn interactions on and off with a global parameter. That might well be the best way of doing it

Right. But how would the global parameter trickle down to each individual Force to tell it to ignore one or the other image of a particle? And can it be accomplished without modifying the implementation of each Force?

.

**Comment by peastman** [comment]
The only force you need to consider is the NonbondedForce.  You're translating the entire ligand by the same amount, so the bonded forces are the same in both versions.  The only difference between the two versions is whether the nonbonded interactions are computed based on the real particles or virtual particles.

**Comment by egallicc** [comment]
Yes, true ... for now. The idea is to support constant affine transformations to, for example, connect two binding modes of the ligand differing in one or more torsional angles. We could also explore breaking chemical bonds eventually, such as moving protons around. 

So it could be prudent to assume from the start that the displacement perturbation affects all energy terms. This of course can be accomplished by displacing particle coordinates since each Force is based on them. 

(While general, I do find displacing coordinates a bit unsatisfactory somehow. That is why I raised the possibility of alternatives, such as virtual particles.)

**Comment by peastman** [comment]
An alternative approach would be to just create two copies of every Force, one that uses the real particles and one that uses the virtual particles.  You would assign them to different force groups, so you could easily query either one.

**Comment by egallicc** [comment]
Interesting. Can the selection of the "active" particles be accomplished without code modifications of the Force implementations?

**Comment by peastman** [comment]
That would be baked into the definitions of the forces.  For example, one PeriodicTorsionForce would have torsions that involved real particles, and the other would have torsions that involved virtual particles.  One NonbondedForce would set charge and epsilon to 0 for the virtual particles, and the other would set them to 0 for the real particles.

**Comment by egallicc** [comment]
I see. That is probably a significant amount of work and probably specific to the API of each Force. It would also be a maintenance challenge to support new Force types that may be coming down the pipe in the future.

So I think I am voting for the first solution based on multiple contexts proposed by Peter. 

If I understand it correctly it consists of:

1. Creating and maintaining two identical contexts except for the coordinate of the particles
2. At each call of calcForcesAndEnergy(): 
(a) Each Force of the first (main) context is evaluated. 
(b) The displaced coordinates of the first context are copied to the second context 
(c) Each Force of the second context is evaluated
(d) Energies and gradients of the two contexts are retrieved and hybridized according to the alchemical function and stored in the first (main) context 

The advantage of the approach above is that it works out of the box for most if not all of the existing and future Force implementations. It also takes care of the non-bonded neighbor list recalculation issue automatically.

Assuming we go this way, my lab is available to tackle the implementation of this alchemical ATM meta-Force. But expect lots of requests for assistance. The implementation details are not so clear to us. Any help is welcome. Thank you in advance!

Also, we do have a working prototype (with the [SDM 2 plugin](https://github.com/rajatkrpal/openmm_sdm_plugin)) ready for production under mild limitations (NVT with the Langevin thermostat and only ~15% lower performance). I recommend that people interested in the technology test or help us test applications (for example binding free energies with ANI and polarizable potentials) with the prototype before we invest resources in the full implementation of the meta-Force.

**Comment by peastman** [comment]
I'll be glad to answer any questions that come up.  A good place to start is looking over the implementation of CustomCVForce.

**Comment by jchodera** [comment]
@peastman Wouldn't it make sense to carefully design the API and capabilities so we could support this feature in the main OpenMM branch? This would have utility far beyond this specific use case, especially considering the utility for QML-based free energy calculations.

**Comment by peastman** [comment]
What other use cases do you have in mind?  What is the more general feature?

**Comment by egallicc** [comment]
The user-level API is very simple:

```
atmforce = mm.AlchemicalTransferForce()
atmforce.addParticle(p, dx, dy, dz)
atmforce.setLambda(lambda_value)
```
where `p` is each particle being displaced, `dx,dy,dz` is the displacement applied to the particle, and `lambda_value` is the value of lambda, 0 <= lambda <= 1.

There a few more optional settings having to do with the softplus alchemical perturbation function, but that's about it.

**Comment by peastman** [comment]
So the idea is that it would internally compute forces for both the original and displaced coordinates and output their weighted average?  That makes sense.  Presumably it would internally contain two different contexts, one for the original coordinates and one for the displaced coordinates?  Alternatively it could compute both with a single context, but then it would have to rebuild neighbor lists more often.

One change I'd make is that lambda should be a global parameter stored in the context.  That way it will be recorded properly in states and checkpoints.  You would set it with

```python
context.setParameter("lambda", lambda_value)
```

**Comment by egallicc** [comment]
> So the idea is that it would internally compute forces for both the original and displaced coordinates and output their weighted average?

Yes, although in general is a bit more complex than a simple weighted average. To improve convergence, the hybridization often involves a non-linear bridging function that depends on the perturbation energy. Something like:
```
u(x) =  U(x + displacement) - U(x)
U(x,lambda) = U(x) + W(u, lambda)
```
where `W(u,lambda)` is any function such that `W(u,0)=0` and `W(u,1)=u`. In our recent work, we have used a generalized softplus bridging function (basically the function one gets by integrating Fermi's function).  `W(u,lambda) = lambda * u` is a special case that corresponds to the simple weighted average. 

Anyway, these details make very little difference for the implementation. Computing the gradients of `U(x,lambda)` from the gradients of the potential energy function is fast and straightforward. But we would need an API to set not only lambda but a few more parameters that depend on it (I think there are 6 of them) that define how `W(u,lambda)` depends on lambda. (This also makes me think of ways that we could generalize the specification of a meta-Force of this kind. I'll try to explain my thoughts in the next message in this thread.)

> Presumably it would internally contain two different contexts, one for the original coordinates and one for the displaced coordinates?

That is the plan, right? The details are not so clear to me, however. For example, I assume the user will create this meta-Force as any other Force. But then internally the meta-Force would have to take over all of the other Forces so that only the meta-Force is executed when calcForcesAndEnergy() is called? How would that work?

> Alternatively it could compute both with a single context, but then it would have to rebuild neighbor lists more often.

Yes, that would be the disadvantage of doing it within a single context.

> One change I'd make is that lambda should be a global parameter stored in the context.

That makes sense. But I am not sure that it would be pretty to create a global parameter for each additional parameter of the perturbation function. Maybe the meta-Force can have a specific API to tell it how each additional parameter depends on lambda so that it can figure them out on the fly. An alternative would be to have as a global parameter some index into a table that specifies the alchemical state and the parameters that go with it (@jchodera could advise).

**Comment by egallicc** [comment]
Our specific alchemical thing is just a specific realization of the general idea of mixing potential functions of different kinds to construct a new potential function. It is an old idea that must have come up before among OpenMM users. 

The typical example is a QM/MM feature based on merging energy and forces from a quantum package with those from a MM package. People have been doing these things with MPI and in more rudimental ways.

Anyway, I wonder if it would make sense, if there is a general interest, to brainstorm around a general feature to support meta Forces of this kind in OpenMM?

For example, something that would look like:

mymetaforce = mm.MetaForce("lambda * force1 + (1-lambda) * force2")
force1 = mm.HarmonicBondForce(...)
force2 = mm.PeriodicTorsionForce(...)
...
mymetaforce.addForce(force1)
mymetaforce.addForce(force2)

I would not know where to begin to implement a feature such as this. But it would be nice. And useful.

**Comment by peastman** [comment]
> But then internally the meta-Force would have to take over all of the other Forces so that only the meta-Force is executed when calcForcesAndEnergy() is called? How would that work?

You would add them to the meta-force rather than adding them directly to the System.  Look at CustomCVForce.  You call `addCollectiveVariable()` on it to add a Force object that is used to compute a collective variable.  Internally it creates a System, adds all the Forces to it for the collective variables, and creates a Context in which to calculate them.

> But I am not sure that it would be pretty to create a global parameter for each additional parameter of the perturbation function.

Anything the user will be changing frequently, and that should be considered as part of the state, should be a context parameter.  Anything that's calculated rather than being set by the user probably shouldn't be.

> mymetaforce = mm.MetaForce("lambda * force1 + (1-lambda) * force2")

That's exactly what CustomCVForce does!  Change `addForce()` to `addCollectiveVariable()` and you'll have working code.  But it doesn't apply displacements to coordinates.

**Comment by egallicc** [comment]
Ah! That piece of enlightenment had not reached my neurons!

Then it should be fairly easy to build the alchemical force based on customCVForce.

So all of the forces added to customCVForce get stored in the "inner" context?

**Comment by peastman** [comment]
Exactly.  Here's the relevant code.

https://github.com/openmm/openmm/blob/1e42b8befa174bf3b4c7d19a4128d9456ebe6390/openmmapi/src/CustomCVForceImpl.cpp#L53-L74

The code that sets force groups is needed so it can evaluate each force individually.  You won't need to do that, since you just care about the sum of all forces.  Now that I think about it, the code that sets the default periodic box vectors probably isn't needed either.  It copies over the current box vectors at each time step, which is what really matters.

Also notice that it creates the Context with `createLinkedContext()`.  That allows it to copy data between the contexts more efficiently.

**Comment by egallicc** [comment]
Thank you. I understand it much better now.

**Comment by jchodera** [comment]
> What other use cases do you have in mind? What is the more general feature?

Apologies for being out of the loop for a few days! 

I think this is on the right track to being a very useful general feature, especially if we can also support the use case of zero displacement. 

The use cases I'm thinking of, beyond the @egallicc use cases (presumably both alchemical transfer and BEDAM), are:
* absolute and relative relative free energy calculations with quantum machine learning potentials, where all we need to do is linearly interpolate the two potentials (presuming one or more potentials contains non-interacting dummy atoms)
* another way to implement accelerated molecular dynamics
* solute tempering style calculations, where two systems (with and without solute-solvent interactions) are interpolated
* simple lambda dynamics calculations, where multiple ligands are interpolated between
* orthogonal space random walk calculations, where biasing potentials are added to dU/dlambda, which for linear interpolation has dU/dlambda = (U1 - U0)

So if we can make this a bit general, there are a number of complex algorithms it can easily enable.

**Comment by peastman** [comment]
Can't those things be done with CustomCVForce?  The only thing it's missing that @egallicc needs is the atom displacements.

**Comment by jchodera** [comment]
Indeed, I had forgotten the "easy MM -> QML" free energy calculation interpolations as well!

> Can't those things be done with CustomCVForce? The only thing it's missing that @egallicc needs is the atom displacements.

This feature would make those use cases just a few (three?) lines of code, whereas `CustomCVForce` can make it rather complex to do this. Having this as an alternative would be very valuable.

**Comment by peastman** [comment]
> This feature would make those use cases just a few (three?) lines of code, whereas CustomCVForce can make it rather complex to do this. Having this as an alternative would be very valuable.

I don't understand what you mean.  Could you give an example?  This appears to me basically identical to CustomCVForce, except with the addition of displacements.

```python
cv = CustomCVForce('lambda*force1 + (1-lambda)*force2')
cv.addCollectiveVariable('force1', force1)
cv.addCollectiveVariable('force2', force2)
cv.addGlobalParameter('lambda', 0)
```

**Comment by egallicc** [comment]
In the alchemical displacement approach, force1 and force2 would be the same force (just "displaced" internally). So it could be a bit of a simplification if it could be entered once. Presumably,  it is possible to add the same Force to two Systems. If so, we can attempt to design the API so that each Force managed by the meta Force is entered once.

But again, the current prototype already recalculates all of the relevant forces automatically. It would be reassuring to test it with a QML potential, or something equivalent in terms of complexity, to test feasibility before investing resources on the full implementation.

**Comment by peastman** [comment]
It seems to me there are two different cases here.  In the applications @jchodera listed you have multiple potential functions, all evaluated for the same coordinates.  In the application @egallicc is working on you have a single potential function that gets evaluated for multiple sets of coordinates.  Conceptually, the applications may be similar, but mechanistically, changing the potential function is very different from changing the coordinates.

So it isn't clear to me how you would support both cases with a single, general feature.  I'm happy hear to suggestions though.

**Comment by egallicc** [comment]
I agree. It is not obvious how to unify the cases mentioned. 

One way would be to introduce a new feature that adds a coordinate transformation to a Force. Something like: 

force.setCoordinateTransformation("f(x)")

where f(x) is some expression that performs the coordinate transformation. The Force will apply the transformation before evaluating the actual force and it propagates the gradients accordingly.

With this feature, I think the alchemical transfer displacement idea could be implemented with CustomCVForce() directly.

I am not sure if it is worth the effort. Just putting it out there ...

**Comment by peastman** [comment]
In principle it would be straightforward to make a Force that wraps other Forces (in the same way CustomCVForce) does.  It would apply the coordinate transformation, compute the contained Forces, and apply the inverse transform to the result.

That is exactly what your proposed class would do, but only for the very limited case of a constant offset.  The question is how much more general it should be.  Should it allow nonlinear transformations?  What can the new position for a particle depend on?  It's current position?  The positions of other particles?

**Comment by egallicc** [comment]
I guess one would start with constant unitary affine transformations: translation + rotation for a fixed translation, rotation axis, and rotation angle. The gradients would then just be rotated accordingly.

Then maybe move to displacements between two atoms for translations, and the vector going through two atoms for the rotation axis. With quaternion algebra is probably not very hard to implement gradients for these limited cases.

**Comment by egallicc** [comment]
In any case, I agree that it is too premature to implement a general feature such as this. That's what plugins are for. We can come back to it if the idea proves useful and there is enough interest for it.

**Comment by egallicc** [comment]
I have started to play around with the idea of an inner system/context to skip recalculation of the neighbor list, initially within the modified [Langevin integrator plugin](https://github.com/rajatkrpal/openmm_sdm_plugin) we have been using. I got stuck in the initialization of the inner context:

I have added an inner context, system, and integrator to the plugin class:

```
    OpenMM::System *innerSystem;
    OpenMM::VerletIntegrator *innerIntegrator;
    OpenMM::Context* innerContext;
```
which are created in the class constructor
```
    innerSystem = new OpenMM::System;
    innerIntegrator = new OpenMM::VerletIntegrator(1.0);
```
Then I initialize them in the initialize() method of the integrator using the customCVForce code above as a template:
```
void LangevinIntegratorSDM::initialize(ContextImpl& contextRef) {
    if (owner != NULL && &contextRef.getOwner() != owner)
        throw OpenMMException("This Integrator is already bound to a context");
    context = &contextRef;
    [...]
    for (int i = 0; i < system.getNumParticles(); i++) 
      innerSystem->addParticle(system.getParticleMass(i)); 
    for (int i=0; i<numforces; i++){
      const Force &force = system.getForce(i);
      int group = force.getForceGroup();
      if(group == 2){//non-bonded
	Force* newnbforce = XmlSerializer::clone<Force>(force);
	newnbforce->setForceGroup(group);
	NonbondedForce* nonbonded = dynamic_cast<NonbondedForce*>(newnbforce);
        if (nonbonded != NULL)
            nonbonded->setReciprocalSpaceForceGroup(-1);
	innerSystem->addForce(newnbforce);
      }
    }
    innerContext = contextRef.createLinkedContext(*innerSystem, *innerIntegrator); 
    vector<Vec3> positions(system.getNumParticles(), Vec3()); 
    innerContext->setPositions(positions);
    [...]
```
However, it fails at runtime at `innerContext->setPositions(positions)` with a SEGV fault. This is with the Reference platform. 

I poked around a bit and confirmed that `posData` in `ReferenceUpdateStateDataKernel::setPositions()` is sized correctly. The debugger appears to strangely blame the last assignment of `posData`. The memory corruption is likely elsewhere.

Any idea of where to go to investigate further? Thanks!

**Comment by peastman** [comment]
Can you run it in a debugger to see where the segfault is happening?

**Comment by egallicc** [comment]
Here:

https://github.com/openmm/openmm/blob/59b8afb1b0f01fbdd85d050e093f4e4d62c93daf/platforms/reference/src/ReferenceKernels.cpp#L228

Apparently when updating the last of the 230 particles in the system (i=229).

**Comment by peastman** [comment]
I notice that in your code, `innerSystem` and `innerIntegator` are both pointers.  That's different from CustomCVForce, where they're objects.  Are you sure they point to valid objects?

**Comment by egallicc** [comment]
Yes, this was very strange. Initially, I had objects in the class definition just like in customCVForce()

```
OpenMM::System innerSystem;
OpenMM::VerletIntegrator innerIntegrator;
```
which were initialized by the class constructor
```
LangevinIntegratorSDM::LangevinIntegratorSDM(double temperature, double frictionCoeff, double stepSize, int nParticles_t): innerIntegrator(1.0), innerContext(NULL)
```
again as in customCVForce(). I was getting however runtime segfaults when initializing unrelated class variables. 

By trial and error, I realized that it was the presence of the System object that caused the errors. Suspecting some odd incompatibility between the automatic System constructor and the plugin, I changed the System variable to a pointer and created the System object with `new` (see above). The errors went away.

But I guess, this was probably the symptom of something more serious that is now causing memory corruption elsewhere.

Let me know if you think that the creation of an inner System/Context could be fundamentally incompatible with an Integrator plugin and call off the experiment.

**Comment by peastman** [comment]
I can't think of any reason they would be incompatible.  That does suggest the problem is somewhere else, and changing to pointers just changed when you happened to run across the memory corruption (or whatever it is).

**Comment by egallicc** [comment]
I suspect Swig-related issues. There might be some magic in the class interface file to address them. But I think we have enough now to attempt the Force plugin directly based on CustomCVForce. We will template the Swig interface file on one of our working Force plugins.

**Comment by peastman** [comment]
In #3073 I converted CustomCVForce to the common compute platform.  That means a single implementation can serve for both CUDA and OpenCL.  Since you're modelling your class after it, you might want to take a look.

**Comment by egallicc** [comment]
Yes, thank you, we will definitively take advantage of the Common platform. 

We are working on a reference implementation. It looks good so far.

**Comment by egallicc** [comment]
In addition to returning the hybridized potential energy and updating the gradients, this force also needs to return the perturbation energy

    u = U(x+displacement) - U(x)

which is used for the free energy calculation in post-processing.

In our current integrator-based implementation, we record the perturbation energy in the integrator itself and we use get/set methods. The set method is called by the computational kernel to set the perturbation energy and the get method is generally called from python to retrieve and store the perturbation energy.

Is there a cleaner/more standard way to do this? Ideally, I guess, we would want to get it from getState(), with units and such.

**Comment by peastman** [comment]
This is a quantity that you get automatically while computing the energy, right?  One option would be to store it in a Context parameter.  Then you could query it whenever you want using `context.getParameter()`.  One thing to be careful of, which I don't think is an issue for you, is that no other force should depend on the value of that parameter.  That's because there are no guarantees about the order forces will be evaluated in.  But I don't think that's something you would want to do anyway.

Another option would be to store it in a field of the ForceImpl or its Kernel.  The Force object could provide a `getPerturbationEnergy(context)` method to retrieve it.

An issue with either of those is that it could produce unexpected results, since it would return the value computed in the most recent force evaluation rather than the current value.  If you called `setPositions()` and then `getPerturbationEnergy()`, the returned value would not reflect the newly set positions.  And if you called it after `step()`, the returned value would reflect whatever positions the forces were last evaluated for, rather than those at the end of the step.  So it might be better to recalculate the energy.  That increases the cost, but if you're only going to be calling it occasionally that shouldn't be a problem.

**Comment by egallicc** [comment]
Thank you. I was actually trying to do the latter (store the perturbation energy in the implementation class). But I got stuck because I don't know how to access the implementation class from the corresponding Force class. Do you have an example?

The other issue, which is less pressing, is how to design the swig interface of this method so that it returns the perturbation energy with units. So that if the get function is defined in the ATMMetaForce class as:

      double getPerturbationEnergy(void);

the python call:

      perturbation_energy = atmmetaforce.getPerturbationEnergy()

returns `perturbation_energy` as a Quantity in kJ/mol.

Yes, the perturbation energy is calculated together with the energy. Yes, I understand that the perturbation energy would not be automatically invalidated if the coordinates or other energy parameters are changed. Finally, yes, we simply collect and store the perturbation energy at regular (long) intervals during MD.

**Comment by peastman** [comment]
Force has a protected method `getImplInContext()`.  For example,

https://github.com/openmm/openmm/blob/98d817304cf97c78d19b7b54304fb0b1ecb90566/openmmapi/src/NonbondedForce.cpp#L133-L135

For units, you can use a `%pythonappend` block in the SWIG interface definition to add units to the return value.  (I assume your plugin uses a handwritten interface definition, rather than programmatically generating it like the core library?)  For example,

```python
%pythonappend OpenMM::State::getPotentialEnergy() const %{
   val=unit.Quantity(val, unit.kilojoules_per_mole)
%}
```

For the core library, those blocks are generated automatically based on the units specified in swigInputConfig.py.

**Comment by egallicc** [comment]
Thank you. It works. 

It might not be obvious to the user why getting the perturbation energy requires the context: 

       pertE = atmforce.getPerturbationEnergy(simulation.context))

I see, yes, I added the %pythonappend incantation by hand.

**Comment by egallicc** [comment]
I have an initial implementation: [openmm-atmmetaforce-plugin](https://github.com/Gallicchio-Lab/openmm-atmmetaforce-plugin)

It has been tested with OpenMM 7.5.0 for a small example of a host molecule in vacuum with two guests. See `example/test.py`.

In this example, the covalent and restraint Forces are in group 1, the non-bonded Force (the one that changes upon ligand displacement) is placed in group 2, and the ATM MetaForce is in group 3. The MD integration is carried out with groups 1 and 3, while the ATM MetaForce knows to duplicate and manage the Forces in group 2 (hard-coded for now).

The plugin uses two inner contexts to evaluate the non-bonded force before and after the two ligands are displaced.

Issues/To do:

1. The test example is in vacuum with a very large cutoff so the neighbor list etc. is not an issue. I see listeners(?) in the OpenCL implementation of CustomCVForce in 7.5.0 that appear to sync maps related to the sorting of molecules. Do I have to worry about those?
2. Yes, I chickened out from the Common platform. I worked only on the Reference and OpenCL implementations. This is mainly because I do not know how to set up a plugin with the Common platform. I suggest maybe porting the openmmexampleplugin to the Common platform? It could be useful. We could take it from there.
3. The ATM MetaForce should I guess have an API to set the Force groups to manage. Something like: `atmforce.setAlchemicalForceGroups({2})`. This can be easily implemented if the present approach based on Force groups is deemed suitable. 

Feedback is much appreciated.

**Comment by peastman** [comment]
> I see listeners(?) in the OpenCL implementation of CustomCVForce in 7.5.0 that appear to sync maps related to the sorting of molecules.

If you don't use a cutoff then atoms will never be reordered.  But if you do use a cutoff, even a very large one, then those listeners are essential.

> I suggest maybe porting the openmmexampleplugin to the Common platform?

Yes, I definitely plan to do that!

> The ATM MetaForce should I guess have an API to set the Force groups to manage.

This is different from what I had in mind.  I assumed you would add the forces to the ATMMetaForce, the same way you do with CustomCVForce, rather than adding them to the System and pulling them out based on force groups.

**Comment by egallicc** [comment]
> If you don't use a cutoff then atoms will never be reordered. But if you do use a cutoff, even a very large one, then those listeners are essential.

The plugin calls the non-bonded force indirectly by calling calcForcesAndEnergy() on the Context. Is there a chance that the Context's machinery takes care of the reordering automatically?

Can you tell us where we can learn more about the principles of the reordering feature and how to use/manage it? I assume that we are not talking about changing the indexes of the particles, but only somehow their assignment to voxels? I wrote a GPU implementation of a non-bonded force (AGBNP) without encountering this aspect ... but maybe we never used it with cutoffs ... 

> This is different from what I had in mind. I assumed you would add the forces to the ATMMetaForce, the same way you do with CustomCVForce, rather than adding them to the System and pulling them out based on force groups.

Yes. Well, this is a first stab at the implementation. We can switch to another approach if this one is not feasible. Do you think there is a fundamental obstacle to this approach? It has the advantage of requiring only very minor adjustments to the setup of the molecular system. Users add arbitrary Forces to the System as usual. The MetaForce simply picks out the "alchemical" ones based on their group assignment.

One of the primary goals of this project is the simplification of free energy estimation tools. This approach, we claim, easily adds free energy estimation capabilities to MD packages without requiring modifications of their low-level energy routines and their system setup procedures. So the idea of minimal disruptions and assumptions goes to the core of the effort.

**Comment by peastman** [comment]
See http://docs.openmm.org/latest/developerguide/developer.html#reordering-of-particles.  Reordering happens automatically when evaluating forces.  The inner and outer contexts may order the particles in different ways, and the ordering can change at any time.  The force needs to take it into account when copying positions and forces between the contexts.  That's why it needs to get notified whenever the ordering of either context changes.

**Comment by egallicc** [comment]
I see. Thank you. Clearly, we do need to worry about reordering. We will follow the way that coordinates and forces are exchanged in CustomCVForce.

Is the definition of OpenCLCalcCustomCVForceKernel::ForceInfo a suitable one for a Force, such as the Meta-Force in question, that does not directly involve a distance cutoff?

**Comment by peastman** [comment]
You should be able to copy the implementation directly from CustomCVForce, though if you use the design you described it may not be necessary.  It's designed to make sure any reordering in the outer context respects the forces in the inner context.  But since those forces are *also* present in the outer context in your design, it will already respect them.  Still, it shouldn't hurt.

**Comment by egallicc** [comment]
We are running into some issues with the atom reordering/listeners.

One odd thing we noticed is that the ordering of the inner contexts (`cl1.getAtomIndex()`) never changes, even though we expect them to track closely the ordering of the outer context. Is there something we should do to "turn on" ordering of the inner contexts?  We probably missed something from the CustomCVForce implementation that we are following as a template.

**Comment by peastman** [comment]
I think I see the problem.  The integrator calls `reorderAtoms()` on each time step:

https://github.com/openmm/openmm/blob/0607d41c18ee1b52efe872b7b951e097f670ad4e/platforms/common/src/CommonKernels.cpp#L5490

That only reorders the main context, not the inner one, which means nonbonded forces inside a CustomCVForce get computed in an inefficient way.  That probably isn't much of a problem in practice, because when does anyone use the nonbonded energy as a CV?  But for you it's a big problem.

A simple solution might be to reorder both contexts at the same time.  Instead of adding ReorderListeners to both contexts, only add one to the outer context.  When it gets called, it can invoke `reorderAtoms()` on the inner context, then update the arrays for both contexts.

**Comment by egallicc** [comment]
Yes, thank you, it makes sense. We will try it.

**Comment by egallicc** [comment]
It took a bit of tinkering but it looks like reordering is working now based on the approach outlined by @peastman.

I am tentatively closing this issue. If more questions/issues come up we can discuss them on the issue page of the [openmm-atmmetaforce-plugin repository](https://github.com/Gallicchio-Lab/openmm-atmmetaforce-plugin).

Thank you for the help! Let us know if there is an interest to try the plugin to compute free energies with polarizable and ANI potentials.

**Comment by peastman** [comment]
Great!  I look forward to seeing your results.

**Comment by jchodera** [comment]
Awesome! Would be great if we could pull this feature into the main OpenMM---it sounds super useful!

**Comment by egallicc** [comment]
> Would be great if we could pull this feature into the main OpenMM---it sounds super useful!

Yes, thank you, that would be great. 

Maybe we should stress-test the plugin thoroughly before considering incorporation? Only the alchemical transformation of the non-bonded Force has been (sparsely) tested so far.

Also, to be generally useful, I think at a minimum one should be able to change the analytical expression of the alchemical hybridization function (currently only the softplus function is hard-coded). I don't know how to do that. But it's probably straightforward with Lepton.

Let's continue the discussion on the [github page](https://github.com/Gallicchio-Lab/openmm-atmmetaforce-plugin) of the plugin?

**Comment by jchodera** [comment]
@peastman : What do you think about being able to pull this feature into OpenMM proper? I worry that it will be difficult for the @egallicc lab folks to maintain, and especially deliver via a conda package, but could be easy for us to support within the main repo (and very useful!).

**Comment by peastman** [comment]
I don't think that would be appropriate right now.  We haven't come up with any sort of general feature that would make sense to include in OpenMM.  This is a specialized class to support a new algorithm @egallicc is developing.

**Comment by jchodera** [comment]
We would definitely be users of the alchemical transfer force feature, and it's an elegant solution for a general problem (alchemical free energies) that avoids many of the challenges of more complex solutions. From what I understand, we could support even more general transformations in addition to displacements, enabling this to be a flexible addition to the custom force family.

**Comment by egallicc** [comment]
Thank you for the interest and support @jchodera and thank you again @peastman for helping us put together the ATMMetaForce plugin. We are open to all options to contribute a solid facility for alchemical calculations in OpenMM and to make it widely available to the community. 

The method and the software are very new and there is a lot we still don't know about large-scale deployments, especially for protein-ligand systems. It is true that our resources are quite limited (especially so now during final exams week!). I will be on sabbatical for the next academic year so things are expected to pick up quickly starting this Summer.

We are committed to the long-term development and maintenance of the ATMMetaForce as a plugin or as part of OpenMM. However, as @jchodera points out, we are not likely to be able to support effectively the conda binary distribution and the variety of setup and simulation workflows that people are likely to want to deploy in conjunction with the ATMMetaForce. For example, our setup workflows are based on Maestro/Desmond files from our Schrodinger day and we are actually not very knowledgeable of the ways that most users set up their systems for OpenMM.

Again, we are open to whatever options are deemed most effective to deliver a solid facility to as many OpenMM users as possible.

**Comment by jchodera** [comment]
Thanks so much, @egallicc! 

> we are not likely to be able to support effectively the conda binary distribution

This is the main aspect I'm worried about, to be honest: The userbase will be _much_ smaller (by an order of magnitude?) if we can't easily deploy your plugin for folks via conda.

@peastman : Maybe we could brainstorm a bit more about whether this could be generalized sufficiently to make it worth your while to bring it in as a first-class CustomForce?

**Comment by peastman** [comment]
Or we could help with building conda packages for it.
