### ISSUE TITLE
Question about covalent md .

### ISSUE THREAD

**Issue by ZeroDesigner** [openmm/openmm#3050]
I am recently doing a covalent MD with openmm. 
Could u tell me where I can find the turtorial teaching me how to do that?

**Comment by peastman** [comment]
I don't understand the question.  What do you mean by "covalent MD"?

**Comment by luskyqi1995** [comment]
> I don't understand the question. What do you mean by "covalent MD"?

Sorry, maybe I didn't describe my question clearly.
You can see the pdb 7BE7
> http://www.rcsb.org/structure/7BE7
> Crystal structure of MG-132 covalently bound to the main protease (3CLpro/Mpro) of SARS-CoV-2.
As you can see , the MG-132 bound to Mpro covalently. 
So how can i do such an MD like this?
Is there any tutorial ?
<img width="561" alt="Screen Shot 2021-03-08 at 12 41 31 PM" src="https://user-images.githubusercontent.com/32703906/110275316-c56a3680-800b-11eb-83ca-9323620189ee.png">

**Comment by Bio-Otto** [comment]
Which type of energy calculation you want to do? If you want to perform end-point free energy calculations like mmgbsa or mmpbsa type calculations you can check openmmtools.

**Comment by jchodera** [comment]
We don't yet have any tools that make it easy to parameterize a covalently-bound inhibitor fully within OpenMM. You can always go through the other ecosystems we provide importers for, such as CHARMM, AMBER, or gromacs.

I also believe [CHARMM-GUI](charmm-gui.org) provides automated tools for this and [outputs OpenMM input files](https://pubs.acs.org/doi/10.1021/acs.jctc.5b00935).

**Comment by luskyqi1995** [comment]
> We don't yet have any tools that make it easy to parameterize a covalently-bound inhibitor fully within OpenMM. You can always go through the other ecosystems we provide importers for, such as CHARMM, AMBER, or gromacs.
> 
> I also believe [CHARMM-GUI](charmm-gui.org) provides automated tools for this and [outputs OpenMM input files](https://pubs.acs.org/doi/10.1021/acs.jctc.5b00935).

Thanks for your reply. I will try it.

**Comment by jchodera** [comment]
@ZeroDesigner Did this solve your problem? If so, can we close the issue?

**Comment by ZeroDesigner** [comment]
> @ZeroDesigner Did this solve your problem? If so, can we close the issue?

yes,thank you
