### ISSUE TITLE
Syncing does not update CustomCVForce in Metadynamics

### ISSUE THREAD

**Issue by JIMonroe** [openmm/openmm#3051]
From what I can tell, creating a new `Metadynamics` instance and pointing it to a directory that already has biases written (bias_*_*.npy files) does not update `_table`, which controls the `CustomCVForce` applied as a biasing potential.  It only updates `_totalBiases` during initialization through `_syncWithDisk`.  This means that the simulation is run without biases until `_addGaussian` gets called, which I think is not the intended behavior?  We'd rather pull in bias information from the get-go and then add to it?  The simple fix seems to be to just move `_syncWithDisk` higher up in init, probably right after defining `_loadedBiases`.

**Comment by peastman** [comment]
That looks reasonable to me.  A PR would be welcome!

**Comment by JIMonroe** [comment]
I just submitted PR #3052.  Unfortunately, it will take me a little time to build the code from source to test this.  Since it's such a simple change, I just went ahead and submitted the PR now and will send an update once I've tested it out.

**Comment by peastman** [comment]
Thanks!

**Comment by JIMonroe** [comment]
Alright, managed to build and install on my Mac and it seems to be working - granted, I only have the one test case I was working with.  If you need a minimal working example, I'm happy to help put that together.  Essentially, create the `Metadynamics` object and a simulation, run with metadynamics for a bit, then re-run the script up to the point of running MD and instead print out the forces.

**Comment by peastman** [comment]
The PR is merged.  Thanks for the fix!
