### ISSUE TITLE
ValueError: No template found for residue 264 (LEU).  The set of atoms matches LEU, but the bonds are different.

### ISSUE THREAD

**Issue by tesla-cat** [openmm/openmm#3062]

**Comment by peastman** [comment]
Take a look at https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template, which discusses reasons for this error.  I suspect the real problem is the following residue.  Your PDB file is probably missing CONECT records for it, so you don't have the bond connecting it to the LEU, which is why it says the bonds for that residue are incorrect.  But it also won't find a match for CQ1, because that isn't a standard residue that Amber14 has parameters for.

**Comment by tesla-cat** [comment]
- @peastman   You are right, the next residue `CQ1` is nonstandard. It is a GFP chromophore.
- I have a physics background, new to MD, and little knowledge with proteins, may I ask how can I add `CONECT` record myself? Are there any tools for this?

**Comment by tesla-cat** [comment]
@peastman 

- I added `CONECT` records using `PyMol`
- but now the error became: 

> ValueError: No template found for residue 265 (CQ1).  This might mean your input topology is missing some atoms or bonds, or possibly that you are using the wrong force field.

- I checked the structure with `PyMol`, and **I think this file is faulty, am I right?**
    - we can clearly see the discontinuities around the chromophore
    - and the chromophore is not connected to anything!
    
## this PDB file is from a postdoc in Stanford, thus I am not confident to say it is faulty, what do you think?

![image](https://user-images.githubusercontent.com/28215638/110978276-2001ea80-839e-11eb-9852-243e40186c24.png)

![image](https://user-images.githubusercontent.com/28215638/110978293-26906200-839e-11eb-9b52-08d6a591007f.png)

**Comment by peastman** [comment]
Force fields like Amber14 provide parameters only for a limited set of molecule types, like standard amino acids and nucleotides.  If your system contains any other sort of molecule, they won't know what to do with it.  There are tools you can use to parametrize small molecules.  I'll let other people make recommendations about that.

**Comment by peastman** [comment]
Force fields like Amber14 provide parameters only for a limited set of molecule types, like standard amino acids and nucleotides.  If your system contains any other sort of molecule, they won't know what to do with it.  There are tools you can use to parametrize small molecules.  I'll let other people make recommendations about that.

**Comment by tesla-cat** [comment]
@peastman  

- actually I have deleted the question you are answering above.
- the new question is **whether you think the PDB file is faulty based on the above images?**.
- I know this is not related to openmm directly anymore, but I'd really appreciate if you can help me with this! Thank you very much!

**Comment by jchodera** [comment]
@tesla-cat Can you upload a ZIP file of the whole PDB file? We can't diagnose the exact issue with just the images.

**Comment by jchodera** [comment]
BTW, have you tried out [CHARMM-GUI](http://www.charmm-gui.org/)? If you're new to MD and just want to prepare a protein structure from a given PDB ID, the tools there (especially the [Solution Build](http://www.charmm-gui.org/?doc=input/solution)) is a great way to build something you can simulate right away. It even generates input files for OpenMM, though OpenMM can also run files you prepare for CHARMM or AMBER with it.

**Comment by tesla-cat** [comment]
@jchodera @peastman 

- Thank you for the help!
- It turns out that the PDB file is correct and I simply had to change some settings in PyMol.
- Unfortunately I don't think I am allowed to share the PDB file to public, but since it is correct we don't have to worry about it.

## The issue now is 

- I am still getting this error **after manually adding CONECT record to connect the nonstandard residue with its neighbors**:
```python
ValueError: No template found for residue 265 (CQ1).  This might mean your input topology is missing some atoms or bonds, or possibly that you are using the wrong force field.
```
- from the FAQ @peastman asked me to read, it mentioned that the problem is caused by nonstandard residue, but didn't saying anything about how to solve it!

> You have a nonstandard residue. Standard force fields like Amber and CHARMM cover a variety of standard molecules, like proteins and nucleic acids. But if your Topology also includes a ligand or other small molecule, the force field will probably not have parameters (and hence no template) for it.

- How should one actually solve this problem? In my case my nonstandard residue is actually a **standard GFP chromophore**

![](https://lh3.googleusercontent.com/proxy/okISVGtXI11A9IlcNqqPQD7ZPcn6_16j9A2jenWqt-0vNd1B-v2LBXE7iiR9XXnO8-1EZ6PtOgB7oJw0ewS8f_Vj1rJCJk8nCsj66xBboE9z-xD4_wmuDGlrm0AJSrTAl5rLhlF-LcfG7sO2)

**Comment by tesla-cat** [comment]
@jchodera 

- Thanks!
- I encountered the following error when trying to use CHARMM-GUI

![image](https://user-images.githubusercontent.com/28215638/111111827-04fbca00-859a-11eb-8cc7-f33f4f8a2427.png)

- unfortunately I don't think I am allowed to share the full PDB files with public, but the atoms for engineered residues are
  - **CQ1**: [**a standard GFP chromophore**](https://lh3.googleusercontent.com/proxy/okISVGtXI11A9IlcNqqPQD7ZPcn6_16j9A2jenWqt-0vNd1B-v2LBXE7iiR9XXnO8-1EZ6PtOgB7oJw0ewS8f_Vj1rJCJk8nCsj66xBboE9z-xD4_wmuDGlrm0AJSrTAl5rLhlF-LcfG7sO2)
  ```python
  ATOM   2041  H1  CQ1 X 265       2.945 -15.451 123.116  1.00155.27           H
  ATOM   2042  O1  CQ1 X 265       1.795 -15.285 122.502  1.00155.27           O
  ATOM   2043  CZ  CQ1 X 265       1.565 -16.035 121.354  1.00155.27           C
  ATOM   2044  CE1 CQ1 X 265       2.575 -16.545 120.511  1.00155.27           C
  ATOM   2045  CD1 CQ1 X 265       2.215 -17.246 119.355  1.00155.27           C
  ATOM   2046  CE2 CQ1 X 265       0.264 -16.196 121.008  1.00155.27           C
  ATOM   2047  CD2 CQ1 X 265      -0.083 -16.901 119.917  1.00155.27           C
  ATOM   2048  CG2 CQ1 X 265       0.852 -17.478 119.106  1.00155.27           C
  ATOM   2049  CB2 CQ1 X 265       0.300 -18.165 117.912  1.00155.27           C
  ATOM   2050  CA2 CQ1 X 265       1.062 -18.633 116.776  1.00155.27           C
  ATOM   2051  N2  CQ1 X 265       2.394 -18.796 116.804  1.00155.27           N
  ATOM   2052  C2  CQ1 X 265       0.541 -19.337 115.678  1.00155.27           C
  ATOM   2053  O2  CQ1 X 265      -0.717 -19.260 115.329  1.00155.27           O
  ATOM   2054  N3  CQ1 X 265       1.507 -19.643 114.853  1.00155.27           N
  ATOM   2055  CA3 CQ1 X 265       1.405 -20.149 113.477  1.00155.27           C
  ATOM   2056  C3  CQ1 X 265       0.970 -21.587 113.444  1.00155.27           C
  ATOM   2057  O3  CQ1 X 265       0.634 -22.026 112.288  1.00155.27           O
  ATOM   2058  C1  CQ1 X 265       2.687 -19.371 115.558  1.00155.27           C
  ATOM   2059  CA1 CQ1 X 265       4.014 -19.707 115.046  1.00155.27           C
  ATOM   2060  N1  CQ1 X 265       4.417 -18.602 114.176  1.00155.27           N
  ATOM   2061  CB1 CQ1 X 265       5.042 -19.847 116.164  1.00155.27           C
  ATOM   2062  CG1 CQ1 X 265       6.314 -20.345 115.587  1.00155.27           C
  ATOM   2063  OG1 CQ1 X 265       5.306 -18.544 116.803  1.00155.27           O
  ```
  - **HOH**
  ```python
  ATOM   2998  O   HOH X 379       4.125 -15.630 123.710  1.00155.27           O
  ```

**Comment by jchodera** [comment]
Info on help for CHARMM-GUI is here: http://www.charmm-gui.org/?doc=contact

Now that I understand that the chromophore is part of the amino acid chain, OpenMM definitely does not have tools to make its parameterization easy at this time, though we hope the [Open Force Field Initiative](http://openforcefield.org) will eventually change that. I know CHARMM-GUI definitely has some common chromophores defined, so it may be your best bet to see if their ecosystem can help you easily assign parameters. Hopefully they've built these parameters for you, since it's not an easy task to derive them on your own!
