### ISSUE TITLE
[question] Is OpenMM supporting multiple-node computations, e.g. through MPI or something

### ISSUE THREAD

**Issue by DanielWicz** [openmm/openmm#3063]
As far as I can see, it is not mentioned in the library's documentation. Furthermore, there's no indication of MPI (or anything else like this) in the available `Platform` objects. So the answer is no at the moment or it's available through some external package (like @jchodera 's openmmtools ?).

**Comment by peastman** [comment]
Correct, a Context only runs on a single node.  With openmmtools you can run a replica exchange simulation with MPI, each replica running on a different node.

**Comment by DanielWicz** [comment]
> Correct, a Context only runs on a single node. With openmmtools you can run a replica exchange simulation with MPI, each replica running on a different node.

Thanks, that answers my question. Thus I close.
