### ISSUE TITLE
conda openmm install

### ISSUE THREAD

**Issue by abazabaaa** [openmm/openmm#3067]
Specifying cudatoolkit==10.0 or 10.1 for conda install -c conda-forge openmm fails to work for me. It says that not such version exists. I tried various other cuda toolkit version and had the same issues.

Conda installs cuda v11.x version of openmm.. my system runs 10.1. 

Any suggestions on how to force the install and specify cuda version?

**Comment by peastman** [comment]
I see CUDA 10.1 builds at https://anaconda.org/conda-forge/cudatoolkit/files for both Linux x64 and Windows.  Linux PPC only seems to include 10.2 and up.  What OS and processor type do you have?

When you say your "system runs 10.1", what does that mean?  Are you saying you have a very old driver than can't support any version newer than that?  If so, can you upgrade your driver?

**Comment by abazabaaa** [comment]
No, we cannot change cuda. This is a centos7 machine that mimics our cluster as a local testenv. The cluster is not going to upgrade.. they are cautious about deploying clusterwide CUDA changes.

failed install on fresh conda env with python = 3.7

(testenv) [schrogpu@schrogpu1 ~]$ conda install -c conda-forge openmm cudatoolkit==10.0
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - cudatoolkit==10.0

Current channels:

  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.


conda info:
   active environment : testenv
    active env location : /home/schrogpu/miniconda3/envs/testenv
            shell level : 2
       user config file : /home/schrogpu/.condarc
 populated config files : /home/schrogpu/.condarc
          conda version : 4.9.2
    conda-build version : not installed
         python version : 3.8.5.final.0
       virtual packages : __cuda=10.1=0
                          __glibc=2.17=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/schrogpu/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/schrogpu/miniconda3/pkgs
                          /home/schrogpu/.conda/pkgs
       envs directories : /home/schrogpu/miniconda3/envs
                          /home/schrogpu/.conda/envs
               platform : linux-64
             user-agent : conda/4.9.2 requests/2.24.0 CPython/3.8.5 Linux/3.10.0-1127.19.1.el7.x86_64 centos/7.8.2003 glibc/2.17
                UID:GID : 1001:1001
             netrc file : None
           offline mode : False

64 cpu machine:
processor	: 60
vendor_id	: GenuineIntel
cpu family	: 6
model		: 85
model name	: Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz
stepping	: 7
microcode	: 0x5002f01
cpu MHz		: 800.189
cache size	: 22528 KB
physical id	: 1
siblings	: 32
core id		: 12
cpu cores	: 16
apicid		: 57
initial apicid	: 57
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes

nvidia-smi:

| NVIDIA-SMI 418.87.00    Driver Version: 418.87.00    CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro RTX 5000     On   | 00000000:18:00.0 Off |                  Off |
| 35%   27C    P8    12W / 230W |     11MiB / 16095MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   1  Quadro RTX 5000     On   | 00000000:3B:00.0 Off |                  Off |
| 35%   28C    P8    12W / 230W |     11MiB / 16095MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   2  Quadro P620         On   | 00000000:5E:00.0  On |                  N/A |
| 34%   44C    P0    N/A /  N/A |   1486MiB /  2000MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+

**Comment by jchodera** [comment]
The available `cudatoolkit` versions are 10.0.130 and 10.1.243, but the use of the `==`operator specifies the _exact_ version (according to the [conda cheat sheet](https://docs.conda.io/projects/conda/en/4.6.0/_downloads/52a95608c49671267e40c689e0bc00ca/conda-cheatsheet.pdf)). Can you try using the `=` fuzzy match instead?
```bash
conda install -c conda-forge openmm cudatoolkit=10.0
```

**Comment by abazabaaa** [comment]
@jchodera @peastman success.. This solved the problem. Thanks so much for the prompt response.. openmm is awesome. Really appreciate the dedication you guys put into it.

You may want to update this in the userguide, as it says to use "=="

http://docs.openmm.org/latest/userguide/application.html#installing-openmm

**Comment by peastman** [comment]
Thanks!  I'll fix that.
