### ISSUE TITLE
Does OpenMM's neighbor list is the same as LAMMPS's neighbor list?

### ISSUE THREAD

**Issue by dingye18** [openmm/openmm#3074]
I'm developing a plugin for OpenMM, and it needs the neighbor list as the input. So I used the neighbor list algorithm from [ReferenceNeighborList.cpp](https://github.com/openmm/openmm/blob/72c70cfe5c22531ece4512f2fc3190d26e48b6f5/platforms/reference/src/SimTKReference/ReferenceNeighborList.cpp#L221)
But for the benchmark of my plugin, I found the neighbor list generated by above function is different with LAMMPS's neighbor list. Which is very confusing......

**Comment by peastman** [comment]
Different in what way?  Do you mean it contained different atoms?  Or was returned in a different format?  I'm not familiar with the LAMMPS code.

The more information you can provide about what you're doing, the more likely we'll be able to help.

**Comment by dingye18** [comment]
It contained different atoms. I'm trying to reproduce this problem. I will let you know when I finished the testing code.

**Comment by swails** [comment]
Containing different atoms isn't in itself a problem. The only requirement for correctness is that each atom within the cutoff of another is found in the pairlist. Order does not matter, nor does it matter if atoms *outside* the cutoff are included in the pairlist (this is done intentionally to prevent the pairlist from needing to be rebuilt every step). 

There are lots of reasons the pairlists may differ between codes (they are merely an implementation detail of implementing non bonded interactions with a cutoff efficiently in direct space).

**Comment by jchodera** [comment]
@dingye18: Do you have any updates on this, or can we close the issue?
