### ISSUE TITLE
Unable to use MonteCarloAnisotropicBarostat 

### ISSUE THREAD

**Issue by RobinEllison** [openmm/openmm#3075]
```
from simtk import openmm as mm
from simtk.unit import *
print(mm.version.full_version)
mm.MonteCarloAnisotropicBarostat(1*bar, 200*kelvin,scaleX=False,scaleY=False,ScaleZ=True)
```
output:
```
7.5.0.dev-b49b82e
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    mm.MonteCarloAnisotropicBarostat(1*bar, 20*kelvin,scaleX=False,scaleY=False,ScaleZ=True)
TypeError: __init__() got an unexpected keyword argument 'scaleX'
```
Any help would be much appreciated.

**Comment by peastman** [comment]
Specifying arguments by name doesn't always work with SWIG generated wrappers.  Most methods support them, but not overloaded ones.  The C++ class has two constructors (the standard constructor and a copy constructor).  But Python doesn't support overloading.  SWIG falls back on a different style of wrapper that can recognize both sets of arguments, but can't handle keyword arguments.

There's a second problem in your code: MonteCarloAnisotropicBarostat expects the pressure to be a three component vector, not a scalar.  The following works:

```python
MonteCarloAnisotropicBarostat([1, 1, 1]*bar, 200*kelvin, False, False, True)
```

**Comment by RobinEllison** [comment]
Thanks so much. It worked. Maybe we should add what you mentioned in the document to make it friendly and easy to use.

**Comment by peastman** [comment]
Great!  Glad that worked.
