### ISSUE TITLE
Support for MDI standard to enable QM/MM calculations?

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#3076]
It looks like MolSSI (specifically, @taylor-a-barnes) has developed a standardized QM/MM interface that OpenMM might consider adding support for: [[paper]](https://www.sciencedirect.com/science/article/abs/pii/S0010465520303386) [[GitHub]](https://github.com/MolSSI-MDI/MDI_Library)

**Comment by peastman** [comment]
Do you mean to use OpenMM as a driver for it?  They already have support for using it as an engine.

**Comment by jchodera** [comment]
Oh! I was just thinking of engine support---no need to make OpenMM a driver.
