### ISSUE TITLE
Steered MD in z direction

### ISSUE THREAD

**Issue by EDKots** [openmm/openmm#3080]
Hi!

I would like to perform a steered MD for an ion in a putative channel. However, there are two possibilities for the channel's location, thus I was thinking of applying a weak external harmonic force only to z-coordinate so that the ion would not be constrained in x and y directions. I would like to ask for your advice on the matter: do you think this is the right way to do it?

Gratefully yours,
Katya

**Comment by peastman** [comment]
That's an easy thing to do, but I can't comment on whether it's a good simulation protocol.  Perhaps someone else with experience in simulating ion channels can provide advice.

**Comment by EDKots** [comment]
Sorry, I think I need to clarify :) I was wondering if this is a right application of the CustomExternalForce? Could it be applied to only one direction?

**Comment by peastman** [comment]
Yes, very easily.

```python
force = CustomExternalForce("k*periodicdistance(0, 0, z, 0, 0, z0)^2")
```

**Comment by EDKots** [comment]
Thank you!
