### ISSUE TITLE
Spherical computational domain

### ISSUE THREAD

**Issue by kolotinsky1998** [openmm/openmm#3090]
Hi, dear community!

I would like to use spherical computational domain for my openMM simulation. The boundary conditions I want to use are the following. When a particle leaves the domain a new particle is reinjected at the random position of the spherical boundary with a random velocity.

As I understand that I can implement it checking every time step of openMM integrator whether a particle leave a spherical domain or not and change it coordinate and velocity. My question is how to make it work efficiently not loosing performance?

Thank you in advance
Daniil Kolotinskii

**Comment by peastman** [comment]
To do that efficiently, you'll want to write a plugin.  That's especially important for CUDA and OpenCL, so you can update the positions and velocities directly on the GPU without having to transfer any data back to the CPU.  See the [Developer Guide](http://docs.openmm.org/latest/developerguide/index.html) for information on how to write plugins.  Also see the [example plugin](https://github.com/openmm/openmmexampleplugin).  (Note that it currently uses separate implementations for CUDA and OpenCL, but I plan to update it shortly to use the common compute framework so a single implementation can serve for both platforms.)

In terms of the mechanism, you'll create a new Force subclass.  You'll implement `updateContextState()` to check for particles outside the sphere and modify their positions and velocities.  Take a look at MonteCarloBarostat for an example of a Force that does something similar, modifying positions in `updateContextState()`.

If you have questions as you work through it, feel free to ask.

**Comment by jchodera** [comment]
@peastman : As an alternative to writing a plugin, which is still somewhat complex, do you think it might be efficient to extend the [openmm-torch plugin](https://github.com/openmm/openmm-torch) to also provide an `Integrator` and/or a positions/velocities modifying `Force` that is defined by a Torch compute graph? This might make it very simply to implement integrators or forces like this in a few lines of Python.

**Comment by peastman** [comment]
Actually, I realized you can do this with a CustomIntegrator.  It's a little bit awkward, but far easier than writing a plugin.  First set a per-DOF variable to 1 for particles that are outside the sphere and 0 for particles that are inside it:

```c++
integrator.addComputePerDof("outside", "step(dot(x,x)-radiusSquared)")
```

Now compute a random velocity and a random point on the sphere for each particle.  The velocity is easy:

```c++
integrator.addComputePerDof("newv", "sqrt(kT/m)*gaussian")
```

The position is a bit more complicated.  There are [various methods](https://mathworld.wolfram.com/SpherePointPicking.html) for picking a uniformly distributed point on the surface of a sphere.  Equation 16 on that site works well for our purposes.  The following line relies on the fact that random numbers only get evaluated once per step, so when the variable `gaussian` appears three times in a single expression, it's the same random number in all three places.

```c++
integrator.addComputePerDof("newx", "radius*gaussian/sqrt(dot(gaussian, gaussian))")
```

Finally we set the position and velocity to either the old or new value, depending on `outside`.

```c++
integrator.addComputePerDof("v", "select(outside, newv, v)")
integrator.addComputePerDof("x", "select(outside, newx, x)")
```

Hopefully I haven't made too many mistakes in that code!

Now you need to combine this with a standard integration method to do the actual integration.  You could copy [one of the integrators](https://github.com/choderalab/openmmtools/blob/master/openmmtools/integrators.py) from openmmtools.  Alternatively, you could use a CompoundIntegrator to combine the above CustomIntegrator (setting its step size to 0, so it doesn't change time) with a standard integrator.  You would alternate taking steps with them.  To take a single step, you would call

```c++
compoundIntegrator.setCurrentIntegrator(0)
compoundIntegrator.step(1)
compoundIntegrator.setCurrentIntegrator(1)
compoundIntegrator.step(1)
```

**Comment by kolotinsky1998** [comment]
@peastman, thank you for the extensive respond!

I have not mentioned earlier that for generation new positions and velocities of particles escaping the computational domain I use rather complex cumulative distribution function ([equations (8-11)](https://iopscience.iop.org/article/10.1088/0741-3335/44/9/313/pdf)). And I am not sure if it is possible to define it through a string expression in a `integrator.addComputePerDof` line.

At the moment, I am using the following algorithm for accounting boundary conditions in my openmm script. 

```python
#1. (takes not so much time )
simulation.step(1) 
#2. (takes a lot of time)
state = simulation.context.getState(True,True) 
position_array = state.getPositions(True)         
velocity_array = state.getVelocities(True)      
#3. (takes not so much time)
'''
some operations with position and velocity arrays to take into account boundary conditions
'''   
#4. (takes a lot of time)
simulation.context.setPositions(position_array)
simulation.context.setVelocities(velocity_array)
```

Steps 2. and 4. where data are transfered from GPU to CPU and vice versa indeed take the most part of computational time. 

However, the number of particles which leaving the computational domain at the given integration step are much less than the total number of particles. May be,  if I could transfer data between GPU and CPU only for those particles which are leaving computational domain at the current step it would make the simulation much more efficient. Is there any way to do it within openmm Python API? May be I can use somehow `getPerDofVariable` and ` setPerDofVariable` methods of `CustomIntegrator` class?

**Comment by peastman** [comment]
In that case, writing a plugin in probably the way to go.  The really big problem in the current implementation is that it creates a bubble in the execution queue.  GPUs work best if you queue up lots of work so that as soon as one kernel finishes running, the next one is ready to start.  When you call `getState()`, it has to wait until all pending kernels have finished running.  Then it transfers the data back to the CPU, then keeps waiting while you do your computations on the positions and velocities, then transfers the data back to the GPU.  Then it can finally launch new kernels, which involves yet more latency and data transfer.  This leads to a big block of time when the GPU is sitting idle.

**Comment by kolotinsky1998** [comment]
I think that I have found the way to implement boundary conditions I need with the custom integrator class.For do that I need each time step calculate different uniformly distributed quantities for all atoms in my system but not for all degrees of freedom. Is it possible? Something between global "uniform" and perDoF "uniform".

**Comment by peastman** [comment]
You want a random number for each atom, shared between its degrees of freedom?  `_x(uniform)` will do that.  You can think of `uniform` as being a three component vector, and `_x()` pulls out the x component of that vector.

**Comment by kolotinsky1998** [comment]
Oh, thank you very much for!

**Comment by kolotinsky1998** [comment]
I want to summarise all that state above, may be it will be useful for somebody else. My task was to implement open boundary conditions for atoms at a spherical domain. There is a flow through this domain of atoms which have shifted maxwellian distribution. Finally I got these working code for that purpose:

```python
'''define custom integrator object'''
integrator = mm.CustomIntegrator(openmm_units.dt)
'''define some variables I will use bellow'''
integrator.addPerDofVariable("outside_domain",0)
integrator.addPerDofVariable("newv",0)
integrator.addPerDofVariable("newx",0)
integrator.addGlobalVariable("r", 0)
'''define flow velocity directed to z-axis for all atoms'''
v_fl_array = []
for i in range(N):
    v_fl_array.append(mm.Vec3(0, 0, openmm_units.v_fl))
integrator.addPerDofVariable("v_fl",0.0)
integrator.setPerDofVariableByName("v_fl", v_fl_array)
integrator.addGlobalVariable("v_T", openmm_units.v_T)
'''This is the internal radius of boundary domain and external radius of main computational domain'''
integrator.addGlobalVariable("R", openmm_units.R)
'''This is the external radius of boundary domain'''
integrator.addGlobalVariable("R_boundary_conditions", openmm_units.R_boundary_conditions)
'''velocity Verlet integration scheme'''
integrator.addComputePerDof("v", "v+0.5*dt*f/m")
integrator.addComputePerDof("x", "x+dt*v")
integrator.addComputePerDof("v", "v+0.5*dt*f/m")
'''define particles which are out of computational domain'''
integrator.addComputePerDof("outside_domain", "step(dot(x,x)-R^2)")
'''random radius to distribute particles at the boundary domain'''
integrator.addComputeGlobal("r","(R^3+uniform*(R_boundary_conditions^3-R^3))^(1/3)")
'''velocity with shifted maxwellian distribution'''
integrator.addComputePerDof("newv", "v_T*gaussian + v_fl")
'''distribute particles uniformly in boundary domain'''
integrator.addComputePerDof("newx", "(R^3+_x(uniform)*(R_boundary_conditions^3-R^3))^(1/3)*gaussian/sqrt(dot(gaussian, gaussian))")
'''compute new velocities and positions for particles which are out of computational domain'''
integrator.addComputePerDof("v", "select(outside_domain, newv, v)")
integrator.addComputePerDof("x", "select(outside_domain, newx, x)")
```

**Comment by jchodera** [comment]
This is super cool! Thanks for sharing your solution, @kolotinsky1998!
