### ISSUE TITLE
Cannot install OpenMM 7.5 with conda on Ubuntu 20.04

### ISSUE THREAD

**Issue by gitkol** [openmm/openmm#3093]
Hi,

Sorry if this is a trivial thing, but I don't seem to be able to do the vanilla installation of OpenMM 7.5 on Ubuntu 20.04. I installed the latest anaconda3 package Anaconda3-2020.11-Linux-x86_64.sh (I also tried it with 2020.07, 2020.02, and 2019.10) and then tried installing OpenMM via 'conda install -c conda-forge openmm', however, conda finds a huge number of conflicts that it tries to resolve for about an hour but eventually gives up. Could this be a 20.04 issue? As far as I can tell, I am doing everything by the book, and I have installed OpenMM via conda before without any issues, granted that was in the omnia channel. Do you have any suggestion? It looks like it has to be some trivial issue with my setup.

Thank you very much for your kind assistance.

Best regards,

   Istvan Kolossvary

**Comment by jchodera** [comment]
@gitkol : Apologies for the issues here!

We're trying to improve the [installation instructions](http://docs.openmm.org/latest/userguide/application.html#installing-openmm) to make it easier to install OpenMM without running into issues like this. 

First, it might make sense to try the minimal [`miniconda` installation](https://docs.conda.io/en/latest/miniconda.html) instead of the full-blown Anaconda package. This should only take a minute or so to install, and should present minimal conflicts when installing OpenMM.

Next, installing OpenMM with 
```bash
conda install -c conda-forge openmm
```
*should* produce the latest install of OpenMM. If you see any conflicts or error messages, can you paste the whole output you see here?

I personally haven't tried to install from full-blown Anaconda3 in a while, so we should probably test the same procedure locally using the [latest `anaconda3` install](https://repo.anaconda.com/archive/Anaconda3-2020.11-Linux-x86_64.sh). Maybe @peastman or @jaimergp could give that a try to see if they run into similar issues?

**Comment by j-wags** [comment]
Hi @gitkol,

The Anaconda conda installer pre-installs a large number of packages in its `base` environment, which can make adding an additional package like openmm quite complex. If you install it into a new environment, you will likely have an easier time:

```
conda create -n openmm-env -c conda-forge openmm
conda activate openmm-env
```

**Comment by gitkol** [comment]
Hi Jeff @j-wags,

Thanks for the env suggestion, it worked much better, but now I still have a spurious CUDA error.
```
istvan@istvan-G464:~$ conda activate openmm-env
(openmm-env) istvan@istvan-G464:~$ python -m simtk.testInstallation

OpenMM Version: 7.5
Git Revision: b49b82efb5a253a7c891ca084b3370e181de2ea3

There are 3 Platforms available:

1 Reference - Successfully computed forces
2 CPU - Successfully computed forces
3 CUDA - Error computing forces with CUDA platform

CUDA platform error: Error initializing CUDA: CUDA_ERROR_COMPAT_NOT_SUPPORTED_ON_DEVICE (804) at /home/conda/feedstock_root/build_artifacts/openmm_1613569779229/work/platforms/cuda/src/CudaContext.cpp:138

Median difference in forces between platforms:

Reference vs. CPU: 6.30092e-06

All differences are within tolerance.

```
John @jchodera the installer installed cudatoolkit 11.2. I guess, I could try Miniconda as you suggested, but I don't think it would make a difference with regards to CUDA. The driver is NVIDIA-Linux-x86_64-460.73.01.run and the card is the 2080 Ti.

Thank you both for your kind help.

Best,

   Istvan

**Comment by gitkol** [comment]
Hey. I think I figured this out. It looks like it was a bad idea to install the Nvidia driver directly from the Nvidia repository as suggested in the Install Guide. I removed that installation and restored the original Ubuntu-Nvidia driver, and now OpenMM works just fine. :)
```
(openmm-env) istvan@istvan-G464:~$ python -m simtk.testInstallation

OpenMM Version: 7.5
Git Revision: b49b82efb5a253a7c891ca084b3370e181de2ea3

There are 4 Platforms available:

1 Reference - Successfully computed forces
2 CPU - Successfully computed forces
3 CUDA - Successfully computed forces
4 OpenCL - Successfully computed forces

Median difference in forces between platforms:

Reference vs. CPU: 6.30621e-06
Reference vs. CUDA: 6.73249e-06
CPU vs. CUDA: 7.06673e-07
Reference vs. OpenCL: 6.75475e-06
CPU vs. OpenCL: 7.75014e-07
CUDA vs. OpenCL: 2.67603e-07

All differences are within tolerance.
```
Thanks,

   Istvan

**Comment by peastman** [comment]
Here's what the CUDA documentation says about that error.

> This error indicates that the system was upgraded to run with forward compatibility but the visible hardware detected by CUDA does not support this configuration. Refer to the compatibility documentation for the supported hardware matrix or ensure that only supported hardware is visible during initialization via the CUDA_VISIBLE_DEVICES environment variable. 

That sounds like some sort of a driver/hardware incompatibility, though I'm not sure exactly what it means.

**Comment by gitkol** [comment]
Thanks, Peter. Yes, it seems that Ubuntu 20.04 is quite particular about using its own Nvidia driver and not the one from the Nvidia repository. As I indicated above reverting to Ubuntu via `sudo apt install nvidia-driver-460`, it installs a slightly different version 460.56 as opposed to 460.73, and that seems to have sold the problem.

   Istvan

**Comment by chemlove** [comment]
Will the omnia channel be updated again in the future? It seems the channel "Last upload: 1 year and 2 months ago".
