### ISSUE TITLE
bug with NBFIX in python wrapper openmm/app/charmmpsffile.py

### ISSUE THREAD

**Issue by feiglab** [openmm/openmm#3094]
The python wrapper app/charmmpsffile.py does not correctly handle a scenario where two different atom types have the same exact LJ parameters, but where the second atom type (in order of occurrence in the atom list) has NBFIX terms. 

Specifically the following piece of code only checks the first atom type for NBFIX:

                ljtype = (atom.rmin, atom.epsilon)
                lj_type_list.append(atom)
                lj_radii.append(atom.rmin)
                lj_depths.append(atom.epsilon)
                for j in range(i+1, len(self.atom_list)):
                    atom2 = self.atom_list[j].type
                    if lj_idx_list[j] > 0: continue # already assigned
                    if atom2 is atom:
                        lj_idx_list[j] = num_lj_types
                    elif not atom.nbfix and not atom.nbthole:
                        # Only non-NBFIXed and non-NBTholed atom types can be compressed
                        ljtype2 = (atom2.rmin, atom2.epsilon)
                        if ljtype == ljtype2:
                            lj_idx_list[j] = num_lj_types

As a result, NBFIXes for the second atom type are being ignored. 

The fix is to check for the second atom type as well:

                    if atom2 is atom:
                        lj_idx_list[j] = num_lj_types
                    elif not atom.nbfix and not atom.nbthole **and not atom2.nbfix**:

Probably there should also be a check for atom2.nbthole.

If it isn't clear, I can provide a test case that fails without the fix and works with the modification.

**Comment by swails** [comment]
The test case would be very useful since then we could turn it into a unit test.

**Comment by feiglab** [comment]
Here is a test case.  It uses 'openmm' scripts from CHARMM-GUI but I am sure you can adapt it.

[nbfix_tst.feiglab.tar.gz](https://github.com/openmm/openmm/files/6365869/nbfix_tst.feiglab.tar.gz)

Again, the issue is that atom types CT, PE, BS all have the same exact default LJ parameters but there is an NBFIX for the BS-PE interaction to keep them together like a pseudo-bond. Without the bug fix, the NBFIX is not effective because LJ types are merged. The 'CLG' particle then breaks up (see output in test case). This is corrected with the bug fix given above. 

Yes, there are other ways to make this work, but that's not the point here.

**Comment by qiuzy** [comment]
Hi, feiglab! Thanks for reporting this issue. We also find this bug which causes zero LJ energy for some pairs with NBFix parameter. Have you commit or would you like to do this? If you don't have time, I can push a commit to fix this bug.

**Comment by feiglab** [comment]
Since we are not regular openMM developers and this is a very minor fix, it may be easier if one of the 'regular' developers could commit the change. Thank you.
