### ISSUE TITLE
LJ and Coulomb calculation.

### ISSUE THREAD

**Issue by davidRFB** [openmm/openmm#3095]
Hi! I am new  using  openMM but I was wondering if there is a fast way to calculate a matrix[n_atoms][n_atoms] that contain the Coulomb and LJ interaction of the pair of atoms i,j. I am performing some test based on some tutorials and it is like this: 
```
from __future__ import print_function
from simtk.openmm import app
import simtk.openmm as mm
from simtk import unit
from sys import stdout

# load in input PDB file and force field XML files
pdb = app.PDBFile('1o9s_fixed.pdb')
forcefield = app.ForceField('amber99sbildn.xml', 'tip3p.xml')

# use app.Modeller to add hydrogens and solvent
modeller = app.Modeller(pdb.topology, pdb.positions)
modeller.addHydrogens(forcefield)
app.PDBFile.writeFile(modeller.topology, modeller.positions, open('1o9s_modeller.pdb', 'w'))

system = forcefield.createSystem(modeller.topology, nonbondedMethod=app.PME,
    nonbondedCutoff=1.0*unit.nanometers, constraints=app.HBonds, rigidWater=True,
    ewaldErrorTolerance=0.0005)

forces = { force.__class__.__name__ : force for force in system.getForces() }
nbforce = forces['NonbondedForce']

N_atoms = modeller.topology.getNumAtoms()


import numpy as np 
LJMatrix = np.zeros((N_atoms,N_atoms))
for i in range(N_atoms):
    charge_1=nbforce.getParticleParameters(i)[0].value_in_unit(unit.elementary_charge)
    sigma_1 = nbforce.getParticleParameters(i)[1].value_in_unit(unit.nanometer)
    epsilon_1 = nbforce.getParticleParameters(i)[2].value_in_unit(unit.kilojoule_per_mole)
    for j in range(i+1,N_atoms):
        charge_1=nbforce.getParticleParameters(j)[0].value_in_unit(unit.elementary_charge)
        sigma_1 = nbforce.getParticleParameters(j)[1].value_in_unit(unit.nanometer)
        epsilon_1 = nbforce.getParticleParameters(j)[2].value_in_unit(unit.kilojoule_per_mole)
        if(Distance(i,j)<Cutoff):
            LJMatrix[i][j]=CoulombInt(i,j)+LJInte(i,j)
```
However I do not know if there a function distance that helps me to evaluate better the evaulation of the interaction. In addition I was wondering if openMM already have functions that calculates the Coulomb and LJ interactions and how fast they are. Maybe a cython implementation could be faster ? 

thank you very much for your time and contributions. 
Best Regards,
David

**Comment by peastman** [comment]
There's no function to compute just a single interaction.  The functional forms are all described in http://docs.openmm.org/latest/userguide/theory.html#nonbondedforce, so you can write the code to evaluate one interaction based on the parameters.  For LJ that's easy.  For Coulomb it's much more complicated since you're using PME.  That means each "interaction" isn't really just two particles.  It's two infinite grids of particles interacting with each other.  Computing that separately for each pair of particles is going to be really slow.

**Comment by davidRFB** [comment]
@peastman  Thank you very much for your answer. Regarding the distance, it is possible to calculate the distance between both atoms using the modeller.positions, or the system of openmm contain this information in a more accessible way?

**Comment by peastman** [comment]
Yes, you can easily calculate the distance from it.  Something like this should work.

```python
pos = modeller.positions.value_in_unit(nanometers)
...
delta = pos[i]-pos[j]
distance = np.sqrt(np.dot(delta, delta))
```

Removing units from the positions before starting the loop will make it faster.

**Comment by davidRFB** [comment]
Thank you very much for your help !!
