### ISSUE TITLE
Different behavior with (CUDA or OpenCL) vs. CPU [1 particle + NonbondedForce + CustomExternalForce]

### ISSUE THREAD

**Issue by dprada** [openmm/openmm#3101]
Please, could anyone tell me if this is reproducible?

I have reduced the problem I was having in my simulations to the following scenario.

The system:
-  A one-particle system
-  LJ parameters defined in a non-bonded force (sigma=3.4 A, epsilon=0.24 kcal/mol, and charge = 0): cut off periodic (distance = 4 * sigma), switching distance (3.0 * sigma) and dispersion correction.
-  A 1D harmonic external force in Z (k=1.0 kcal/mol * 1/nm**2)
-  A big PBC cubic box (~150*sigma) 

The simulation:
- Langevin dynamics ( temperature = 300 K,  collisions_rate = 1.0 1/ps, integration timestep = 2 fs)
- Initial conditions: all set to zero.

The problem:
- Running with CPU everything seems reasonable, but not with CUDA or OpenCL.
- When running with CUDA or OpenCL, the particle shows a sudden increment of energy in the dimension restrained by the harmonic potential [energies_CUDA.pdf](https://github.com/openmm/openmm/files/6416512/energies_CUDA.pdf). The particle jumps to the neighbor PBC box and thanks to the Langevin damping it relaxes to the new equilibrium position -until the next jump- [z_CUDA.pdf](https://github.com/openmm/openmm/files/6416514/z_CUDA.pdf). Apparently, the particle always 'diffuses' to the box below (not 100% sure).
- When the non-bonded force is not defined, CPU, CUDA, and OpenCL have the same result. They all look good.
- When the harmonic potential is not defined, CPU, CUDA, and OpenCL have the same result. They all look good.
- If the harmonic potential is extended to other dimensions, the same behavior is observed in the new restrained dimensions.
- If the spring constant increases, the number of jumps increases in the same period of time.

I have reproduced this in three different machines (with three different GPUs) with OpenMM 7.5.1 and 7.4.2, with simple, mixed, and double precision (if I remember well), always with cudatoolkit=10.2.

A script to run the dynamics is attached to this post 
[1_LJ_particle_with_harmonic_1Dpot.zip](https://github.com/openmm/openmm/files/6416519/1_LJ_particle_with_harmonic_1Dpot.zip). It can be run by choosing the platform from the command line:

```bash
python 1_LJ_particle_with_harmonic_1Dpot.py CUDA
```
or
```bash
python 1_LJ_particle_with_harmonic_1Dpot.py CPU
```

The output is a set of three plots: energies vs time, z vs time and vz vs time.

Is this reproducible? Is there anything wrong -I don't see- in the script?

Many, many thanks in advance.

**Comment by peastman** [comment]
You need to change the definition of the CustomExternalForce from

```python
force = mm.CustomExternalForce('A*(z^2)')
```

to

```python
force = mm.CustomExternalForce('A*periodicdistance(0, 0, z, 0, 0, 0)^2')
```

See the discussion of `periodicdistance()` at http://docs.openmm.org/latest/api-c++/generated/OpenMM.CustomExternalForce.html.  You also might find https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#periodic helpful.

**Comment by dprada** [comment]
Oh! Thanks. I see. You are right. It works now. Thanks for your help.

Before closing the issue. Why with CPU looked always good? Was it just luck?

**Comment by dprada** [comment]
I'm going to close it. Thanks @peastman for your help with this.
It was simple and I was not detecting it.
Thank you.

**Comment by peastman** [comment]
The CUDA and OpenCL platforms internally translate every molecule into a single periodic cell, keeping track of how many box widths they have been translated by so they can be translated back on output.  This is done for accuracy.  Those platforms use single precision by default.  Keeping all the positions as small as possible maximizes their accuracy.  The Referenece and CPU platforms don't do that.  They store the coordinates in double precision, so accuracy isn't an issue.

That's why the documentation says there's no guarantee about which periodic copy will get passed to the CustomExternalForce.  It can vary between platforms, and may change from one time step to the next.
