### ISSUE TITLE
AMBER14 or CHARMM36 force field with implicit water model?

### ISSUE THREAD

**Issue by nowozin** [openmm/openmm#3104]
I have successfully done MD simulations with both AMBER14 and CHARMM36 force fields using the explicit water models (`amber14/tip3pfb.xml` and `charmm36/water.xml`, respectively).

However, from reading the documentation and examples I have been unable to use AMBER14 or CHARMM36 force fields with implicit water models.

For AMBER99 I can successfully use an implicit water model as

```python
   forcefield = mm.app.ForceField("amber99sbildn.xml", "amber99_obc.xml")
```

Please could you let me know how I would use an implicit water model with AMBER14 or CHARMM36?  There does not seem to be an implicit water model XML file in the respective directories.

**Comment by jchodera** [comment]
We do not currently support GB models with the newer force field conversions. 

@peastman: In principle, we can do this using `openmm.app.internal.customgbforces.CustomAmberGBForceBase.getStandardParameters(toplogy)`, where `CustomAmberGBForceBase` is replaced with the appropriate GB model. Would it make sense to provide an example or facility for doing this? I'm not sure exactly how it would work, but it would be something like
```python
from openmm import app
# Load PDB topology and positions
pdbfile = app.PDBFile('filename.pdb')
# Create vacuum system
forcefield = app.ForceField('amber14sb.xml')
system = forcefield.createSystem(pdbfile.topology, nonbondedMethod=app.NoCutoff)
# Add GB forces
from app.internal.customgbforces import GBSAOBC2Force
params = GBSAOBC2Force.getParameters(pdbfile.topology)
gbforce = GBSAOBC2Force.addParticles(params)
system.addForce(gbforce)
```

**Comment by peastman** [comment]
This could be a good thing to support.  We need to be a bit careful to make sure it's correct.  For example, when using implicit solvent you need to modify the NonbondedForce to set the reaction field dielectric to 1.  The best approach might be an XML file that you include in your ForceField, just like the old Amber versions.  It would have a `<Script>` tag that does roughly what you show above.

**Comment by jchodera** [comment]
> This could be a good thing to support. We need to be a bit careful to make sure it's correct. For example, when using implicit solvent you need to modify the NonbondedForce to set the reaction field dielectric to 1. 

To my understanding, these implicit solvents are not recommended for use with cutoffs---they should be used with `NoCutoff`, which should not require the dielectric to be set.

> The best approach might be an XML file that you include in your ForceField, just like the old Amber versions. It would have a <Script> tag that does roughly what you show above.

That's a great idea!

**Comment by peastman** [comment]
In practice, implicit solvent is frequently used with a cutoff.  You do need to use a somewhat longer cutoff though.  Around 20 A is usually reasonable.

**Comment by nowozin** [comment]
Thank you for the swift and informative reply.  I will use AMBER99 for now and look forward to future support of AMBER14 or CHARM36 implicit solvent models.
