### ISSUE TITLE
Multi-walker metadynamics blows up due to updating _selfBias

### ISSUE THREAD

**Issue by scychon** [openmm/openmm#3105]
I'm trying to run a multi-walker metadynamics simulation but was facing blow-up issues continuously, while single metadynamics run was fine.
I found in the openmm/app/metadynamics.py file, the self._totalBias was memory-copying self._selfBias so adding biases from other walkers updated selfbias. Thus the biases were increasing exponentially !!

```ruby
    def _syncWithDisk(self):
...
        if fileLoaded:
            self._totalBias = self._selfBias
```

A simple fix is to change the memory-copy to np.copy() function of the numpy, such that
```ruby
    def _syncWithDisk(self):
...
        if fileLoaded:
            self._totalBias = np.copy(self._selfBias)
```

I saw there's another pull request for metadynamics.py file, so am not sure how you want to proceed with this bug.
I'm running my simulation with the bug fixed on my side but would be nice to see this fixed in the main repository as well.

**Comment by dlukauskis** [comment]
My pull request solves the same issue but in a bit more roundabout way. I think your solution is more elegant, but mine makes each walker write out the total bias into the bias file. When reconstructing the full FES, do you just sum all the bias together?

**Comment by scychon** [comment]
Sorry for the belated respond. Yes when reconstructing the full FES, just summing over all the bias together and multiplying the scaling factor due to well-tempered bias would give the total FES. I think along with this, writing a separate HILSS file similar to what PLUMED does would help tracking the actual bias history and restarting multi-walker version of metadynamics simulation. I'll post a new pull request with this added functionality.
