### ISSUE TITLE
ValueError: No template found for residue 37 (TYR).  The set of atoms is similar to TTHY, but it is missing 2 atoms.

### ISSUE THREAD

**Issue by nataliaszulc** [openmm/openmm#3108]
Hi everyone, I am new to openmm. When I use it to run molecular simulations, there is problem with the last residue in the peptide, which is amidated, the 37 TYR (see: https://www.rcsb.org/structure/2L86):

 File "/home/ebam/niedziel1p/Desktop/insert_openmm/openmm_run.py", line 41, in <module>
    hydrogenMass=4*amu, patches=patches)
  File "/home/ebam/niedziel1p/miniconda3/envs/openmm/lib/python3.6/site-packages/simtk/openmm/app/forcefield.py", line 1179, in createSystem
    templateForResidue = self._matchAllResiduesToTemplates(data, topology, residueTemplates, ignoreExternalBonds)
  File "/home/ebam/niedziel1p/miniconda3/envs/openmm/lib/python3.6/site-packages/simtk/openmm/app/forcefield.py", line 1393, in _matchAllResiduesToTemplates
    raise ValueError('No template found for residue %d (%s).  %s' % (res.index+1, res.name, _findMatchErrors(self, res)))
ValueError: No template found for residue 37 (TYR).  The set of atoms is similar to TTHY, but it is missing 2 atoms.

I would be grateful for help.

**Comment by peastman** [comment]
Take a look at https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template and see if it answers your question.

**Comment by nataliaszulc** [comment]
> 
> 
> Take a look at https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template and see if it answers your question.

> A chain is terminated incorrectly. Proteins, and nucleic acids to an even greater extent, can be terminated in different ways. The residues at the ends of the chain are different from those in the middle and require different templates. Often a force field will only support one or two ways of terminating each chain. If your Topology has them terminated in a different way, they will not match.

Does it mean that I can't use the amidated terminal amino acid in openmm with CHARMM36?

**Comment by nataliaszulc** [comment]
It was generated by using CHARMM-GUI, where terminal group patching is CT2.
According to the documentation:
![charmm_gui](https://user-images.githubusercontent.com/48363461/117722374-42b75080-b1e1-11eb-8f73-d3164594874f.jpg)

**Comment by peastman** [comment]
It's possible CHARMM-GUI has just set up the PDB file incorrectly.  CHARMM works differently from most other force fields.  In most force fields, the NME group at the end is considered a separate residue.  That's also how the original PDB file describes it: it's residue 38.  But CHARMM instead treats it as a modification to residue 37, which means the extra atoms need to be marked as being part of residue 37.  Otherwise, it won't match the template.

**Comment by jchodera** [comment]
@nataliaszulc Could you attach a ZIP file containing the problematic protein PDB? We can take a look at what is causing this error specifically.

**Comment by nataliaszulc** [comment]
Of course, the sturcture below:
[files_amylin.zip](https://github.com/openmm/openmm/files/6572203/files_amylin.zip)

**Comment by jchodera** [comment]
Residue 37 seems to be a standard TYR with carboxylate C-terminus:
![image](https://user-images.githubusercontent.com/3656088/120245783-5718c700-c23c-11eb-88dd-feeeedcf6557.png)
The corresponding PSF file seems to match this.

When I attempt to create a `System` object with `ForceField` using `charmm36.xml`, I instead run into the issue that the PDB is missing `CONECT` records [required by the PDB format specification](https://www.wwpdb.org/documentation/file-format-content/format33/sect10.html) for molecules like `POPC`:
```python
>>> from simtk.openmm import app
>>> ff = app.ForceField('charmm36.xml')
>>> pdbfile = app.PDBFile('step5_input.pdb')
>>> system = ff.createSystem(pdbfile.topology)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/choderaj/miniconda/envs/perses-fah-0.9.0/lib/python3.7/site-packages/simtk/openmm/app/forcefield.py", line 1174, in createSystem
    raise ValueError('No template found for residue %d (%s).  %s' % (res.index+1, res.name, _findMatchErrors(self, res)))
ValueError: No template found for residue 38 (POPC).  The set of atoms matches POPC, but the bonds are different.  Perhaps the chain is missing a terminal group?
```
Were you using a different scheme to load the structure and apply parameters?

**Comment by nataliaszulc** [comment]
Yes, sorry, I sent the wrong setup without amidation on the C-terminus, below the correct one: 
[amylin_amidation.zip](https://github.com/openmm/openmm/files/6639654/amylin_amidation.zip)

**Comment by DanielWicz** [comment]
I have the same problem without any lipid membrane. The file is a NMR PDB formated by CHARMM PDB reader (through CHARMM-GUI) with CT2 cap included. I add the file here:
[2L86.zip](https://github.com/openmm/openmm/files/6982690/2L86.zip)

**Comment by Silki600** [comment]
ValueError: No template found for residue 1 (GLY).  The set of atoms matches GLY, but the bonds are different.  Perhaps the chain is missing a terminal group?  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template
