### ISSUE TITLE
Particle at the origin causes large force in a spherical-container potential

### ISSUE THREAD

**Issue by naotohori** [openmm/openmm#3111]
Hello, I am trying to build some simulations of coarse-grained particles and encounter the following issue. I appreciate any comments on what could be the underlying cause. I'm new to OpenMM, so sorry if I am making some elementary mistakes.

In summary, when a particle is placed at the origin (0.0, 0.0, 0.0), a spherical-container potential causes a huge force, resulting in NaN coordinate in minimization, even though the particle is safely inside the sphere. The strange thing is that the problem occurs only when the particle coordinate is the exact origin; it does not happen for instance (10, 10, 10) or even slightly off (0.0001, 0.0001, 0.0001).

The following is a minimal code with sample XML and PDB to reproduce the issue.  In this code, there is only one particle loaded from a PDB, and only a spherical-container potential is set following an example in the manual (the radius of the sphere is 5.0 nm). http://docs.openmm.org/latest/userguide/application.html?highlight=customexternalforce#applying-an-external-force-to-particles-a-spherical-container

```python
from simtk.openmm import app
import simtk.openmm as omm
from simtk import unit

forcefield = app.ForceField('sample.xml')

# Load PDB
pdb = app.PDBFile('sample.pdb')
topology = pdb.getTopology()
positions = pdb.getPositions()

#positions = [omm.Vec3(0.0001, 0.0001, 0.0001)*unit.angstrom,]

system = forcefield.createSystem(topology)

# spherical constraint
constraint_force = omm.CustomExternalForce('const_k*max(0, r-const_r)^2; r=sqrt(x*x+y*y+z*z)')
constraint_force.addGlobalParameter('const_k', 1.0 * unit.kilocalorie_per_mole/unit.angstrom**2)
constraint_force.addGlobalParameter('const_r', 50.0 * unit.angstrom)

for i in range(system.getNumParticles()):
    constraint_force.addParticle(i, [])

system.addForce(constraint_force)

integrator = omm.LangevinIntegrator(300.0*unit.kelvin, 0.5/unit.picosecond, 50*unit.femtoseconds)
simulation = app.Simulation(topology, system, integrator)

simulation.context.setPositions(positions)
print("Positions:")
for p in positions:
    print(p)

print('Potential energy before minimization:', simulation.context.getState(getEnergy=True).getPotentialEnergy())

# Debug
print('Check force before minimization')
forces = simulation.context.getState(getForces=True).getForces()
for i, f in enumerate(forces):
    print(i, f.in_units_of(unit.kilocalorie_per_mole/unit.angstrom))

print('Minimizing ...')
simulation.minimizeEnergy(tolerance=1*unit.kilocalorie_per_mole, maxIterations=100000)

print('Potential energy after minimization:', simulation.context.getState(getEnergy=True).getPotentialEnergy())
```

sample.xml  
```xml:sample.xml
<ForceField>
  <AtomTypes>
    <Type name="0" class="Ar" element="Ar" mass="100.0"/>
  </AtomTypes>
  <Residues>
    <Residue name="ARG">
      <Atom name="Ar" type="0"/>
    </Residue>
  </Residues>
</ForceField>
```

sample.pdb  
```:sample.pdb
ATOM      1  Ar  ARG 0   1       0.000   0.000   0.000  1.00  0.00          Ar
TER
END
```

By running the above code, I get output like this.

```
Positions:
Vec3(x=0.0, y=0.0, z=0.0) nm
Potential energy before minimization: 0.0 kJ/mol
Check force before minimization
0 Vec3(x=-51326091.01338432, y=-51326091.01338432, z=-51326091.01338432) kcal/(A mol)
Minimizing ...
Traceback (most recent call last):
  File "./debug.py", line 48, in <module>
    simulation.minimizeEnergy(tolerance=1*unit.kilocalorie_per_mole, maxIterations=100000)
  File "/home/hori/anaconda3/envs/openmm/lib/python3.8/site-packages/simtk/openmm/app/simulation.py", line 128, in minimizeEnergy
    mm.LocalEnergyMinimizer.minimize(self.context, tolerance, maxIterations)
  File "/home/hori/anaconda3/envs/openmm/lib/python3.8/site-packages/simtk/openmm/openmm.py", line 14161, in minimize
    return _openmm.LocalEnergyMinimizer_minimize(context, tolerance, maxIterations)
simtk.openmm.OpenMMException: Particle coordinate is nan
```

If I replace the coordinate in the PDB to `10.0  10.0  10.0`, or alternatively I overwrite the coordinate by the following line,
```
positions = [omm.Vec3(0.0001, 0.0001, 0.0001)*unit.angstrom,]
```
then this does not occur, and the output is like this:

```
Positions:
Vec3(x=0.0001, y=0.0001, z=0.0001) A
Potential energy before minimization: 0.0 kJ/mol
Check force before minimization
0 Vec3(x=0.0, y=0.0, z=0.0) kcal/(A mol)
Minimizing ...
Potential energy after minimization: 0.0 kJ/mol
```

**Comment by naotohori** [comment]
That solved the issue!  So in this case, the `max` function is not enough to guarantee that the potential is totally flat inside the sphere. 

Thank you very much for your prompt reply!

**Comment by peastman** [comment]
I think we could actually improve this.  Here is how the derivative of `max()` is implemented.

https://github.com/openmm/openmm/blob/d8ef57fed6554ec95684e53768188e1f666405c9/libraries/lepton/src/Operation.cpp#L402-L409

It uses `step()` to determine which argument is greater, than adds together the derivatives of both arguments, multiplying one by 1 and the other by 0.  In this case, though, one of the derivatives is NaN, and 0*NaN=NaN.  We should change the implementation to use `select()`.

I'm going to reopen this and mark it as an enhancement request.
