### ISSUE TITLE
ppc64 conda openmm build

### ISSUE THREAD

**Issue by vipinsachdeva** [openmm/openmm#3116]
Hi, Is there a conda channel I can use for OpenMM ppc64 conda build ? Thanks.

**Comment by peastman** [comment]
We're working at it.  The problem is that there aren't yet CUDA toolkit packages for PPC.  Once those are available, we can make OpenMM packages.

**Comment by raimis** [comment]
A relevant conda-forge issue: https://github.com/conda-forge/openmm-feedstock/issues/8

**Comment by vipinsachdeva** [comment]
I got it running following directions on Summit at https://github.com/inspiremd/conda-recipes-summit

**Comment by jaimergp** [comment]
PPC packages for CUDA 10.2 should be available now at conda-forge @vipinsachdeva! This can be closed @peastman.

**Comment by peastman** [comment]
Thanks!
