### ISSUE TITLE
Segfault when using  'UseCpuPme': 'true'

### ISSUE THREAD

**Issue by DanielWicz** [openmm/openmm#3118]
When I use UseCpuPme: true as below: 

`properties = {'Precision': 'mixed', 'DeviceIndex': '0,1,2,3', 'UseCpuPme': 'true', 'UseBlockingSync': 'false'}`

I get fallowing error: 
`/var/spool/slurm/job392105/slurm_script: line 20:  3333 Segmentation fault      python $WORKDIR/openmm_run.py`
When I set UseCpuPme to false, everything works perfectly fine. 

Details:
code: this tutorial: http://openmm.org/tutorials/b2ar_membrane/
with properties and platform changed.

Software:
OpenMM version: 7.5.0
CUDA version: 10.1.243
FFTW version: 3.3.9
Driver: 440.44

I think segfault shouldn't be the case, even if something is missing. The segfault happens immediately after running the script.

**Comment by peastman** [comment]
Can you run the script inside `gdb`?  That will hopefully provide some information about where the segfault is happening.  Let it run until it reaches the segfault, then type `bt` to get a stack trace for where it happened.

**Comment by DanielWicz** [comment]
> Can you run the script inside `gdb`? That will hopefully provide some information about where the segfault is happening. Let it run until it reaches the segfault, then type `bt` to get a stack trace for where it happened.

I think, I'm doing something wrong with gdb. Do you know how to properly run a Python package through it ? I get something like this:
![image](https://user-images.githubusercontent.com/37775482/118368433-588e9200-b5a2-11eb-8c63-a042a083756f.png)

**Comment by peastman** [comment]
Thanks!  That led me right to the problem.  Add this to the properties: `'DisablePmeStream': 'true'`.  The error is coming from an intersection of two different features that weren't intended to be used together: running PME on the CPU, and running PME on a separate GPU stream.  I'll fix the code so it automatically disables the PME stream when using the CPU implementation.

**Comment by DanielWicz** [comment]
> 'DisablePmeStream': 'true'

Thanks for help. Nevertheless it shows a weird behavior now. I could use 4-5fs timestep with mixed precision, middle langevin integrator. And now it gives me "nans" even with timestep of 1fs (I didn't test less than that).
