### ISSUE TITLE
OpenMM only 1 platform available 

### ISSUE THREAD

**Issue by namyh** [openmm/openmm#3119]
Hi 
I'm trying to install OpenMM without conda in linux.
At first I've got 3 platforms(reference, CPU, OpenCl) and removed it and installed again 
However, I've tried several versions of OpenMM but only 1 platform(reference) was printed with python -m simtk.testInstallation code 
I'm wondering is this problem relate in installing process or is there any other ways to activate other platforms??
The environment that I have CUDA 11.2 
and I tried 6.3.1~7.1.1 versions of the OpenMM

**Comment by peastman** [comment]
That probably means it's failing to load the plugins.  How exactly did you install?  Did you build from source?

Try executing these commands:

```python
from simtk.openmm import *
print(version.openmm_library_path)
```

That will tell you where it *thinks* it's installed.

**Comment by namyh** [comment]
I compiled with Pre-compiled Binaries Linux version with compilers 
I checked the plugins and the path with your advice , and they are matched

**Comment by namyh** [comment]
I compiled from source code and I figured out that i have low version of "Swig"
Is this critical for running OpenMM? 
I saw this Swig error several times when I compiled with precompiled binaries codes

**Comment by peastman** [comment]
I don't understand what you mean by "compiled with precompiled binaries".  Did you compile it from source, or did you use pre-compiled binaries?  Either way, describe exactly what you did.  If you compiled from source, give the exact sequence of commands you executed to compile and install.  If you used pre-compiled binaries, where did you get them from?

**Comment by namyh** [comment]
> I don't understand what you mean by "compiled with precompiled binaries". Did you compile it from source, or did you use pre-compiled binaries? Either way, describe exactly what you did. If you compiled from source, give the exact sequence of commands you executed to compile and install. If you used pre-compiled binaries, where did you get them from?

I used pre-compiled binaries(from simTK: openMM download links).
I downloaded pre-compiled binaries(OpenMM-7.1.1-Linux.zip) from https://simtk.org/frs/index.php?group_id=161.
I unziped this in my computer, then I ran install.sh file in this folder.
I changed the default install location and the python path for my environment. 
After installation I added CUDA libraries in my library path 





--------------the below is the installation instructions that i used ----------------
3.3. Installing on Linux
1. Download the pre-compiled binary of OpenMM for Linux from https://simtk.org/project/xml/downloads.xml?group_id=161, then double click the .zip file to expand it.

2. Make sure you have Python 2.6 or higher (earlier versions will not work) and a C++ compiler (typically gcc or clang) installed on your computer. You can check what version of Python is installed by typing python --version into a console window.

(Optional) If you want to run OpenMM on a GPU, install CUDA and/or OpenCL.
If you have an Nvidia GPU, download CUDA 7.5 from https://developer.nvidia.com/cuda-downloads. Be sure to install both the drivers and toolkit. OpenCL is included with the CUDA drivers.
If you have an AMD GPU, download the latest version of the Catalyst driver from http://support.amd.com.
4. (Optional) If you plan to use the CPU platform, it is recommended that you install FFTW. It is probably available through your system’s package manager such as yum or apt-get. Alternatively, you can download it from http://www.fftw.org. When configuring it, be sure to specify single precision and multiple threads (the --enable-float and --enable-threads options). OpenMM will still work without FFTW, but the performance of particle mesh Ewald (PME) will be much worse.

5. In a console window, change to the OpenMM directory by typing

cd <openmm_directory>
where <openmm_directory> is the path to the OpenMM folder. Then run the install script by typing

sudo ./install.sh
It will prompt you for an install location and the path to the python executable. Unless you are certain you know what you are doing, accept the defaults for both options.

6. (Optional) To use the CUDA platform on an Nvidia GPU, you must add the CUDA libraries to your library path so your computer knows where to find them. You can do this by typing

export LD_LIBRARY_PATH=/usr/local/cuda/lib
This will affect only the particular console window you type it into. If you want to run OpenMM in another console window, you must type the above command in the new window.

7. Verify your installation by typing the following command:

python -m simtk.testInstallation
This command confirms that OpenMM is installed, checks whether GPU acceleration is available (via the OpenCL and/or CUDA platforms), and verifies that all platforms produce consistent results.

**Comment by jchodera** [comment]
@namyh : Could you give us more information about your use case for needing to install OpenMM without conda? We'd love to understand this better, since we've attempted to standardize on conda distribution as being the easiest way to get started running OpenMM.

Also, did you happen to find the [instructions on compiling the latest OpenMM release (7.5) from source](http://docs.openmm.org/latest/userguide/library.html#compiling-openmm-from-source-code)? If not, could you let us know what led you to [the SimTK page you mention](https://simtk.org/frs/index.php?group_id=161), so we can help revise the documentation and pointers to better lead folks to the latest info?

cc: @Yoshanuikabundi

**Comment by namyh** [comment]
> Could you give us more information about your use case for needing to install OpenMM without conda? We'd love to understand this better, since we've attempted to standardize on conda distribution as being the easiest way to get started running OpenMM.
> 
> Also, did you happen to find the [instructions on compiling the latest OpenMM release (7.5) from source](http://docs.openmm.org/latest/userguide/library.html#compiling-openmm-from-source-code)? If not, could you let us know what led you to [the SimTK page you mention](https://simtk.org/frs/index.php?group_id=161), so we can help revise the documentation and pointers to better lead folks to the latest info?


I'm using super computers in my university and the manager told me that these computers are not allowed to install any packages with conda because of the security problem.(when I try conda install, there is HTTP error).
I read this page http://docs.openmm.org/7.0.0/userguide/application.html and followed the 3.3 installing on linux because i'm on CentOS7 at first. 
But it didn't work as i thought, so I was trying with instructions of compiling from source code that you mentioned

**Comment by jchodera** [comment]
> I'm using super computers in my university and the manager told me that these computers are not allowed to install any packages with conda because of the security problem.(when I try conda install, there is HTTP error).

Thanks for pointing this out! There is a way we can package OpenMM, its dependencies, and the [miniforge](https://github.com/conda-forge/miniforge) minimal Python for userspace installation as a monolithic ZIP installer. Would that be helpful to you? You'd just unpack it, set your path, and go.

(@peastman: We would use a modified version of the [OpenFF installer constructor](https://github.com/openforcefield/toolkit-installer-constructor) to do this!)

If that could be useful to you, would you be able to let us know what architecture your supercomputer is? Is this x86 linux?

The compiling-from-source page you note is from OpenMM 7.0.0, which may be out of date. The [latest compiling from source instructions](http://docs.openmm.org/latest/userguide/library.html#compiling-openmm-from-source-code) should be up to date for the 7.5 releases, which are [hosted at GitHub](https://github.com/openmm/openmm/releases). 

Can you recall how you ended up at the 7.0.0 version of the docs? We should fix that so folks find the latest docs in future!

**Comment by peastman** [comment]
>  I downloaded pre-compiled binaries(OpenMM-7.1.1-Linux.zip) from https://simtk.org/frs/index.php?group_id=161.

That's a very old version.  The current release is 7.5.1.  If you can't use conda, compiling from source is the supported alternative.

**Comment by jchodera** [comment]
@namyh Did using a more recent version of OpenMM installed from conda solve your problem? If so, can we close this issue?

**Comment by namyh** [comment]
> @namyh Did using a more recent version of OpenMM installed from conda solve your problem? If so, can we close this issue?

Thank you for your kindness
I'm still in process andI'm having another problem now so you can close this issue

**Comment by jchodera** [comment]
Let us know if there are other specific issues we can help with!
