### ISSUE TITLE
can amoeba force field describe interactoins of small organic molecules

### ISSUE THREAD

**Issue by zhengcheng233** [openmm/openmm#3122]
Recently, I try to use openmm to study a small organic molecules with amoeba2013 force field. However, I notice that in amoeba2013.xml, it only has some standard amoino residues, so the residue in the origanic molecue which i tried to learn can not be founded. Is there any method to solve this issue?

**Comment by jchodera** [comment]
You'd have to contact the developers of the AMOEBA force field regarding any tools they might have for automatically assigning parameters for arbitrary small organic molecules. We've only provided minimal support for force field parameters for templated residues provided as part of the [Tinker modeling package](https://dasher.wustl.edu/tinker/) that could be easily converted into OpenMM force field XML files.

If you do find that they've provided an open source, conda-installable tool for generating AMOEBA force field parameters, we could potentially support it within the [openmmforcefields](https://github.com/openmm/openmmforcefields) package, which currently supports [AmberTools GAFF](http://ambermd.org/antechamber/gaff.html) (via antechamber) and [the Open Force Field force fields](http://openforcefield.org).

**Comment by zhengcheng233** [comment]
Get it. Thank you
