### ISSUE TITLE
Documentation build instructions are incorrect

### ISSUE THREAD

**Issue by Yoshanuikabundi** [openmm/openmm#3126]
Following the guide on [building the docs](http://docs.openmm.org/latest/userguide/library.html#building-the-documentation-optional) leads to a crash rather than correctly built docs. Several additional steps are required (as used in [CI](https://github.com/openmm/openmm/blob/master/.github/workflows/CI.yml#L499-L588)):

1. Sphinx must be pinned to version 2.3.1. Simply installing sphinx through PIP or Conda provides 4.0.2 which includes backwards-incompatible changes. The error message is cryptic and does not suggest downgrading.
2. The Python wrapper must be built with `make PythonInstall` so that Sphinx can find the appropriate docstrings

In addition, in [CI](https://github.com/openmm/openmm/blob/master/devtools/ci/gh-actions/conda-envs/docs.yml) `sphinxcontrib-bibtex` is pinned to any version before 2.0.0. I haven't tested without this pin but I imagine it is also necessary.

The instructions for using [CCMake](http://docs.openmm.org/latest/userguide/library.html#starting-cmake) are also incomplete. Current versions do not provide the `-i` switch, which seems to be unnecessary.

**Comment by peastman** [comment]
> Sphinx must be pinned to version 2.3.1.

Has a sphinx update broken the build again?  (This happens a *lot*.)  We should figure out why and get it working with the latest version.

**Comment by peastman** [comment]
> The Python wrapper must be built with make PythonInstall so that Sphinx can find the appropriate docstrings

This shouldn't be something the user needs to do manually.  The build script is supposed to recognize it as a dependency and do it automatically if needed.  I take it that isn't happening for you?

**Comment by Yoshanuikabundi** [comment]
Yeah, I discovered this stuff trying to figure out how to build the docs myself. I ended up having to duplicate the steps in CI rather than in the documentation. I figured these were known issues since the CI works, and just no one had updated the docs. 

> Has a sphinx update broken the build again?

The most recent version gave an error about something missing some particular attribute. Sorry, I didn't write down the exact error. I didn't investigate any further once I found the pin in CI.

>  We should figure out why and get it working with the latest version.

I agree! 

> This shouldn't be something the user needs to do manually. The build script is supposed to recognize it as a dependency and do it automatically if needed. I take it that isn't happening for you?

Didn't work for me, and CI manually makes PythonInstall too so I don't think its just me.

Guess I'm learning how to write cmake files this week!

**Comment by peastman** [comment]
Ok, I'll look into those problems and see if I can figure them out.

> Guess I'm learning how to write cmake files this week!

I'm sorry!  (Not a fate I would wish on anyone.)

**Comment by peastman** [comment]
I'm working on getting it working with Sphinx 4.0.2.  See https://github.com/rmcgibbo/sphinxcontrib-lunrsearch/pull/3 and https://github.com/rmcgibbo/sphinxcontrib-autodoc_doxygen/pull/22.

#3129 fixed the second item above, so you don't need to `make PythonInstall` anymore.

**Comment by Yoshanuikabundi** [comment]
@peastman Ok. I have managed to build the user guide, dev guide, and even the C++ API docs, but the Python API docs still have me stumped.

In a clean clone of `master` using a conda environment generated from `devtools/ci/gh-actions/conda-envs/docs.yml` with no changes, running the following commands:

```shell
mkdir build
cd build
cmake .. -DOPENMM_GENERATE_API_DOCS=ON -DCMAKE_INSTALL_PREFIX=${CONDA_PREFIX} -DCMAKE_PREFIX_PATH=${CONDA_PREFIX} -DOPENMM_BUILD_PYTHON_WRAPPERS=ON
make PythonApiDocs
```

Gives the following error (cmake completes successfully, though it skips the compiler checks):

```
[ 96%] Built target PythonInstall
[100%] CMake-copying file /home/joshm/Documents/openmm/openmm/docs-source/api-python/_templates/class.rst to /home/joshm/Documents/openmm/openmm/build/docs-source/api-python/_templates/class.rst
[100%] CMake-copying file /home/joshm/Documents/openmm/openmm/docs-source/api-python/conf.py to /home/joshm/Documents/openmm/openmm/build/docs-source/api-python/conf.py
[100%] CMake-copying file /home/joshm/Documents/openmm/openmm/docs-source/api-python/process-docstring.py to /home/joshm/Documents/openmm/openmm/build/docs-source/api-python/process-docstring.py
[100%] CMake-copying file /home/joshm/Documents/openmm/openmm/docs-source/api-python/render.py to /home/joshm/Documents/openmm/openmm/build/docs-source/api-python/render.py
[100%] CMake-copying file /home/joshm/Documents/openmm/openmm/docs-source/api-python/app.rst.jinja2 to /home/joshm/Documents/openmm/openmm/build/docs-source/api-python/app.rst.jinja2
[100%] CMake-copying file /home/joshm/Documents/openmm/openmm/docs-source/api-python/library.rst.jinja2 to /home/joshm/Documents/openmm/openmm/build/docs-source/api-python/library.rst.jinja2
[100%] Generating app.rst, library.rst
Traceback (most recent call last):
  File "/home/joshm/Documents/openmm/openmm/build/docs-source/api-python/render.py", line 11, in <module>
    import openmm
ModuleNotFoundError: No module named 'openmm'
make[3]: *** [docs-source/api-python/CMakeFiles/PythonApiDocs.dir/build.make:93: docs-source/api-python/app.rst] Error 1
make[2]: *** [CMakeFiles/Makefile2:6830: docs-source/api-python/CMakeFiles/PythonApiDocs.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:6837: docs-source/api-python/CMakeFiles/PythonApiDocs.dir/rule] Error 2
make: *** [Makefile:2974: PythonApiDocs] Error 2
```

Removing the prefix definitions in the cmake command in a fresh build directory doesn't help. Ok, fine, so the script can't find the OpenMM install, I'll just `make install PythonInstall` first as happens in CI (btw, I think this means that #3129 is insufficient to fix that dependency bug, and this will actually be a big problem if I have to reinstall openmm every time I want to view a change I make to the API docs). That gives me this:

```
[ 96%] Built target PythonInstall
[ 96%] Generating app.rst, library.rst
Traceback (most recent call last):
  File "/home/joshm/Documents/openmm/openmm/build/docs-source/api-python/render.py", line 11, in <module>
    import openmm
  File "/home/joshm/conda/envs/ommdev/lib/python3.9/site-packages/openmm/__init__.py", line 19, in <module>
    from openmm.openmm import *
  File "/home/joshm/conda/envs/ommdev/lib/python3.9/site-packages/openmm/openmm.py", line 13, in <module>
    from . import _openmm
ImportError: /home/joshm/conda/envs/ommdev/lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/joshm/conda/envs/ommdev/lib/libOpenMM.so.7.5)
make[3]: *** [docs-source/api-python/CMakeFiles/PythonApiDocs.dir/build.make:93: docs-source/api-python/app.rst] Error 1
make[2]: *** [CMakeFiles/Makefile2:6830: docs-source/api-python/CMakeFiles/PythonApiDocs.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:6837: docs-source/api-python/CMakeFiles/PythonApiDocs.dir/rule] Error 2
make: *** [Makefile:2974: PythonApiDocs] Error 2
```

Importing the Python package in a Python interpreter gives the same error. It looks like a configuration issue on my machine, which is mystifying as it's in the same shell session as I ran `cmake`, so surely it should be finding the same clib? I made sure to run cmake only after activating the conda environment and with a fresh build directory. ` /home/joshm/conda/envs/ommdev/lib/libstdc++.so.6` seems to be the right conda environment. Do you have any insight?

**Comment by peastman** [comment]
I'm not quite certain, but I *think* this is what is happening.  libOpenMM is compiled against libstdc++.  Since you compiled from source, it probably compiled against the version built into your OS.  But conda has installed its own copy into your environment, and it's incompatible with the one you compiled OpenMM against (it requires a different version of GLIBCXX).

This isn't a situation I've encountered, so I'm not certain what the solution is.  Can you have conda uninstall its version of libstdc++ so the one from the OS will be used instead?  Or alternatively can you get it to compile OpenMM against the one installed by conda?

**Comment by Yoshanuikabundi** [comment]
Solved this by installing a C++ compiler in the Conda environment and letting Conda manage all the dependencies. Documented in e3fb262

**Comment by peastman** [comment]
I believe the instructions in the manual are now up to date and work correctly.  Is it ok to close this?
