### ISSUE TITLE
Improve navigation of User's and Developer's Guides

### ISSUE THREAD

**Issue by Yoshanuikabundi** [openmm/openmm#3133]
At the moment, the User's and Developer's Guides both have intended layouts that do not match their layouts in source or on the web page. The intended layout as far as I can tell is:

- Documentation
    - User's Guide
        - Introduction
        - Part I: Application layer
             - Chapters 2-6
        - Part II:  Library layer
            - Chapters 7-16
        - Part III: Theory
            - Chapters 17-22
        - Bibliography
    - Dev's Guide
        - Chapters 1-8
    - Python API ref
    - C++ API ref

This matches the layout of files on disk, with single files associated with each part of the user's guide. It does not match the semantics of the source or the built documentation itself, which looks more like this: 

- User's Guide
    - Chapters 1-23
- Dev's Guide
    - Chapters 1-8
- Python API ref
- C++ API ref

Note that the chapters in the User's Guide are flat, and are not delineated into parts. As Sphinx builds the table of contents and navigation by looking at the semantics of the source, but builds the actual HTML files based on the files in the source, this makes navigation very confusing as the user is unsure whether clicking a link will take them to a new page or not.

In addition, pages are extremely long, as entire parts of 5+ chapters are compiled into single web pages. This makes navigation frustrating as the user must scroll to the top of the page to find the navigation menu on the left hand side.

The following changes to the source would very quickly and easily make a massive improvement to the navigability of the User's Guide in particular, but also the developer's guide:

 - Insert new section levels corresponding to parts. This will clearly separate out which chapters belong to which parts and make it easier for the user to find themselves in the navigation tree.
 - Break the source files up so that each chapter appears in its own source file, and therefore its own web page. This will help users to find the navigation menu with minimum scrolling.

The following changes to the template would facilitate the above:

- "Next Chapter" and "Previous Chapter" links should be added to the template at the top and bottom of every page.
- Parts should have a distinct visual design in the navigation menu.
- The navigation menu on the left should not go deeper than the chapter level, except for the current chapter where it should go to the subsection level (this is actually the current behaviour, but it will be much more usable with pages-as-chapters)
- A search function should be added to make up for the loss of ctrl+F (which is already compromised by breaking the pages up into parts)

**Comment by peastman** [comment]
> The following changes to the template would facilitate the above:

Note that these things are generally managed by the Sphinx theme you choose.  (Perhaps that's what you meant by "template"?) They provide a variety of styles of navigation menus, often include "next" and "previous" links, etc.  We could also consider switching to a different theme, if we find one we like better.

**Comment by Yoshanuikabundi** [comment]
Yep, the theme is exactly what I mean!
