### ISSUE TITLE
‘is_trivially_copyable’ is not a member of ‘std’

### ISSUE THREAD

**Issue by namyh** [openmm/openmm#3135]
Hi, 

I posted an installation issue few days ago and I got a lot of thankful advices.

I'm trying to install openmm with source code(the latest version : http://docs.openmm.org/latest/userguide/library.html#compiling-openmm-from-source-code )

there is a problem during 'make' process 

I'm using gcc 10.2.0 

Is there any recommended gcc version?

**Comment by jmkoral** [comment]
Has this issue been addressed? I am having the same issue.
[ 29%] Building CXX object platforms/cuda/sharedTarget/CMakeFiles/OpenMMCUDA.dir/__/src/CudaArray.cpp.o
In file included from /cm/shared/apps/openmm/platforms/cuda/../common/include/openmm/common/ComputeProgram.h:30:0,
                 from /cm/shared/apps/openmm/platforms/cuda/../common/include/openmm/common/ComputeContext.h:38,
                 from /cm/shared/apps/openmm/platforms/cuda/../common/include/openmm/common/ExpressionUtilities.h:30,
                 from /cm/shared/apps/openmm/platforms/cuda/./include/CudaExpressionUtilities.h:30,
                 from /cm/shared/apps/openmm/platforms/cuda/./include/CudaContext.h:45,
                 from /cm/shared/apps/openmm/platforms/cuda/src/CudaArray.cpp:28:
/cm/shared/apps/openmm/platforms/cuda/../common/include/openmm/common/ComputeKernel.h:63:29: error: ‘is_trivially_copyable’ is not a member of ‘std’
     typename std::enable_if<std::is_trivially_copyable<T>::value, void>::type addArg(const T& value) {
                             ^
/cm/shared/apps/openmm/platforms/cuda/../common/include/openmm/common/ComputeKernel.h:63:29: error: ‘is_trivially_copyable’ is not a member of ‘std’
/cm/shared/apps/openmm/platforms/cuda/../common/include/openmm/common/ComputeKernel.h:63:57: error: template argument 1 is invalid
     typename std::enable_if<std::is_trivially_copyable<T>::value, void>::type addArg(const T& value) {
                                                         ^
/cm/shared/apps/openmm/platforms/cuda/../common/include/openmm/common/ComputeKernel.h:63:58: error: expected identifier before ‘::’ token
     typename std::enable_if<std::is_trivially_copyable<T>::value, void>::type addArg(const T& value) {
                                                          ^
/cm/shared/apps/openmm/platforms/cuda/../common/include/openmm/common/ComputeKernel.h:63:65: error: invalid type in declaration before ‘,’ token
     typename std::enable_if<std::is_trivially_copyable<T>::value, void>::type addArg(const T& value) {
                                                                 ^
/cm/shared/apps/openmm/platforms/cuda/../common/include/openmm/common/ComputeKernel.h:63:65: error: invalid use of ‘::’
/cm/shared/apps/openmm/platforms/cuda/../common/include/openmm/common/ComputeKernel.h:88:29: error: ‘is_trivially_copyable’ is not a member of ‘std’
     typename std::enable_if<std::is_trivially_copyable<T>::value, void>::type setArg(int index, const T& value) {
                             ^
/cm/shared/apps/openmm/platforms/cuda/../common/include/openmm/common/ComputeKernel.h:88:29: error: ‘is_trivially_copyable’ is not a member of ‘std’
/cm/shared/apps/openmm/platforms/cuda/../common/include/openmm/common/ComputeKernel.h:88:57: error: template argument 1 is invalid
     typename std::enable_if<std::is_trivially_copyable<T>::value, void>::type setArg(int index, const T& value) {
                                                         ^
/cm/shared/apps/openmm/platforms/cuda/../common/include/openmm/common/ComputeKernel.h:88:58: error: expected identifier before ‘::’ token
     typename std::enable_if<std::is_trivially_copyable<T>::value, void>::type setArg(int index, const T& value) {
                                                          ^
/cm/shared/apps/openmm/platforms/cuda/../common/include/openmm/common/ComputeKernel.h:88:65: error: invalid type in declaration before ‘,’ token
     typename std::enable_if<std::is_trivially_copyable<T>::value, void>::type setArg(int index, const T& value) {
                                                                 ^
/cm/shared/apps/openmm/platforms/cuda/../common/include/openmm/common/ComputeKernel.h:88:65: error: invalid use of ‘::’
make[2]: *** [platforms/cuda/sharedTarget/CMakeFiles/OpenMMCUDA.dir/__/src/CudaArray.cpp.o] Error 1
make[1]: *** [platforms/cuda/sharedTarget/CMakeFiles/OpenMMCUDA.dir/all] Error 2
make: *** [all] Error 2

**Comment by peastman** [comment]
You need to use a modern compiler.  `is_trivially_copyable` is part of the C++11 standard.  Very old compilers don't support it.
