### ISSUE TITLE
Question about the SHAKE implementation

### ISSUE THREAD

**Issue by asilveirastx** [openmm/openmm#3137]
If I understood the SHAKE implementation correctly, it is based on Equation 5.6 of the paper (https://www.sciencedirect.com/science/article/pii/0021999177900985), which is solved only to first order. LAMMPS, for example, solves the quadratic equation for the Lagrange multiplier (https://github.com/lammps/lammps/blob/92e995d3a2bdd7f2614446d511ebd2295a03df38/src/RIGID/fix_shake.cpp#L1724).
Could you please provide more details regarding the choice of solving to first order?
Thanks!

**Comment by peastman** [comment]
OpenMM uses a mix of algorithms to enforce constraints.  SHAKE and CCMA are both iterative algorithms.  They are iterated until the distances converge to within the required tolerance.  SETTLE is an analytical algorithm that solves for the required distances in a single step, accurate to the limits of numerical precision.  An algorithm that was only accurate to first order wouldn't be useful for most purposes.

**Comment by asilveirastx** [comment]
Sorry, by first order I meant that, as the paper suggests, the quadratic term in g is neglected
![Screen Shot 2021-06-03 at 11 55 45 AM](https://user-images.githubusercontent.com/72212636/120674974-a3dde700-c462-11eb-8993-6c068bcee183.png)
LAMMPS solves the quadratic equation.

**Comment by peastman** [comment]
That's how all quasi-Newton methods work.  No idea what algorithm LAMMPS uses, but if they're solving to quadratic order, its something different from SHAKE.  But the choice of algorithm doesn't affect the result.  The constraint equations have a unique solution, and any algorithm will converge to it.
