### ISSUE TITLE
Replace unmaintained documentation dependencies 

### ISSUE THREAD

**Issue by Yoshanuikabundi** [openmm/openmm#3149]
We should replace `sphinxcontrib-lunrsearch` and `sphinxcontrib-autodoc_doxygen` with modern, actively maintained alternatives. The latter should be possible to replace with [`breathe`](https://breathe.readthedocs.io/en/latest/), and we may be able to replace the former with Sphinx's built in search functionality.

How committed are we to the search-as-you-type feature? As I've discussed in #3132, I think its idiosyncratic at best, and at the very least needs to be augmented with full page search on pressing enter. I'd be in favour of removing the search-as-you-type functionality altogether and sticking with the built in search, especially if it lets us remove an unmaintained dependency.

Are we aware of any other unmaintained dependencies?

**Comment by peastman** [comment]
I'm not at all attached to the particular search implementation.  Anything that works reasonably well is fine with me.
