### ISSUE TITLE
problem with getPlatformByName("CUDA") 

### ISSUE THREAD

**Issue by AhmetGG** [openmm/openmm#3153]
Hi,

I am Phd student who is newly starting using OpenMM. Normally when I don`t add getPlatformByName("CUDA") on a simulation, there is no problem of running.However whenever I put this platform on it I get a mistake that it is written that "This Integrator is already bound to a context". What can I do to solve?  Also even if I don`t write this, Does it means that the simulation already run on GPU? I would greatly appreciate your kind help.Thanks.

**Comment by peastman** [comment]
Could you post your code?  That error has nothing to do with looking up a platform.

**Comment by AhmetGG** [comment]
Thank you so much for replying. I found my mistake. After simulation was again run from first line, there  was no problem.
