### ISSUE TITLE
issue with system creation with the OBC implicit solvent 

### ISSUE THREAD

**Issue by eguarnera** [openmm/openmm#3155]
Hi,

I'm having an issue when calling OBC1 or OBC2 implicit solvent models from Amber pmrtop file.

Here's an example of the command I'm using 

system = prmtop.createSystem(constraints=HBonds,
                             implicitSolvent=OBC2,
                             soluteDielectric=1.0, 
                             solventDielectric=80.0,implicitSolventSaltConc=0.020*moles/liter)

Here's the output with error message. However, if instead I use GBn2 I don't have problem in creating the system and performing the simulation. Any suggestion?
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-18-661ad0dc94dd> in <module>
      3                              implicitSolvent=OBC2,
      4                              soluteDielectric=1.0,
----> 5                              solventDielectric=80.0,implicitSolventSaltConc=0.020*moles/liter)

~/anaconda3/envs/merck/lib/python3.7/site-packages/simtk/openmm/app/amberprmtopfile.py in createSystem(self, nonbondedMethod, nonbondedCutoff, constraints, rigidWater, implicitSolvent, implicitSolventSaltConc, implicitSolventKappa, temperature, soluteDielectric, solventDielectric, removeCMMotion, hydrogenMass, ewaldErrorTolerance, switchDistance, gbsaModel)
    279                         flexibleConstraints=False, gbmodel=implicitString, soluteDielectric=soluteDielectric,
    280                         solventDielectric=solventDielectric, implicitSolventKappa=implicitSolventKappa,
--> 281                         rigidWater=rigidWater, elements=self.elements, gbsaModel=gbsaModel)
    282 
    283         if hydrogenMass is not None:

~/anaconda3/envs/merck/lib/python3.7/site-packages/simtk/openmm/app/internal/amber_file_parser.py in readAmberSystem(topology, prmtop_filename, prmtop_loader, shake, gbmodel, soluteDielectric, solventDielectric, implicitSolventKappa, nonbondedCutoff, nonbondedMethod, scee, scnb, mm, verbose, EwaldErrorTolerance, flexibleConstraints, rigidWater, elements, gbsaModel)
   1008         # the prmtop screen factors from LEaP in sander and pmemd
   1009         if gbmodel in ('HCT', 'OBC1', 'OBC2'):
-> 1010             screen = [float(s) for s in prmtop._raw_data['SCREEN']]
   1011         else:
   1012             screen = [gb_parm[1] for gb_parm in gb_parms]

KeyError: 'SCREEN'

---------------------------------------------------------------------------

**Comment by peastman** [comment]
It looks like your prmtop file wasn't created for use with OBC?  It's missing the screening parameters.

**Comment by eguarnera** [comment]
Oh I see, you are right, the pmrtop was created using MOE, which currently doesn't allow to set the screening parameters for implicit solvent simulations. I guess I will have to revert to the usual Amber's workflow or edit the pmrtop?

Thanks for the feedback!

**Comment by peastman** [comment]
That would explain it!
