### ISSUE TITLE
Error using gromacs files

### ISSUE THREAD

**Issue by gabriela-correa** [openmm/openmm#3157]
Hi,

I'm trying to write a script that uses openmm functions to calculate free energy differences. When I use amber or pdb files with xml files as input, my code runs correctly. However, when I try to use gromacs files as input, I get the following error:
```
    simulation.minimizeEnergy()
  File "/home/gabriela/anaconda3/lib/python3.8/site-packages/simtk/openmm/app/simulation.py", line 128, in minimizeEnergy
    mm.LocalEnergyMinimizer.minimize(self.context, tolerance, maxIterations)
  File "/home/gabriela/anaconda3/lib/python3.8/site-packages/simtk/openmm/openmm.py", line 18992, in minimize
    return _openmm.LocalEnergyMinimizer_minimize(context, tolerance, maxIterations)
simtk.openmm.OpenMMException: Particle coordinate is nan
```
I saw it's a general error. This error is very strange to me. That's because I can run the code with amber files, but I can't run it with gromacs files that were converted by ParmEd through amber files. I'm trying to debug this error. The error occurs at the start of minimization. Before minimization, I am calculating the potential and kinetic energies of the system as -5233.012604193971 kJ / mol and **nan kJ / mol** respectively. Therefore, the problem seems to occur in the calculation of kinetic energy.

Can anyone help me with this problem?

Thank you very much.

[code.zip](https://github.com/openmm/openmm/files/6720644/code.zip)

**Comment by gabriela-correa** [comment]
I think I know what's going on. When using gromacs files as input, the format of the CustomNonbondedForce function seems to be the reason for the error in kinetic energy. For example, if I set the function format as

potential = 'in_out_vdw*4.0*lambda_vdw*epsilon*(x^2 - x)'
potential += '; x = 1/((r/sigma)^6)'

or 

potential = 'in_out_vdw*4.0*lambda_vdw*epsilon*(x^2 - x)'
potential += '; x = (r/sigma)^(-6)'

the error Kinetic energy = nan occurs. But if I set

potential = 'in_out_vdw*4.0*lambda_vdw*epsilon*(x^2 - x)'
potential += '; x = (sigma/r)^6'

the Kinetic Energy is calculated correctly. So, it seems to be a bug in OpenMM when we use gromacs files as input. I don't know if anyone has ever reported it. 

[new code.zip](https://github.com/openmm/openmm/files/6721747/new.code.zip)

**Comment by peastman** [comment]
Thanks for the excellent test case!  This is happening because some atoms have sigma set to 0.  That causes r/sigma to be nan.  It's getting this directly from the .top file, which sets sigma to 0 for atom type "ho".  How did you create this file?

**Comment by gabriela-correa** [comment]
Thanks for your answer! I created Amber's .inpcrd and .prmtop files with tleap. So I used ParmEd to convert these files to .top and .gro formats.

Inserting this in the code

for force in system.getForces():
    if isinstance(force, openmm.NonbondedForce):
        for index in range(force.getNumParticles()):
            charge, sigma, epsilon = force.getParticleParameters(index)
            if sigma/sigma.unit == 0.0:
                force.setParticleParameters(index, charge, 1.0, epsilon)

I solved the problem.

This error is strange because the potential energy is calculated correctly. It only affects the kinetic energy. Do you know why?

**Comment by gabriela-correa** [comment]
I have just confirmed that the Amber files don't specify any sigma as 0. So there must be a problem with ParmEd.
Thanks a lot for the help!

**Comment by peastman** [comment]
Great!
