### ISSUE TITLE
applying the position restraint on  a specific atom...

### ISSUE THREAD

**Issue by AhmetGG** [openmm/openmm#3158]
Hello,

I would like to apply position restraint on only  "CA" atom. The following script I wrote gave mistake. I could not find any example of how to do position restraint on specific atoms. Could you help me?  

# adding restraint on heavy atoms...

restraint= CustomExternalForce("k*periodicdistance(x,y,z,x0,y0,z0)^2")

restraint.addGlobalParameter("k",2.0*kilocalories_per_mole/angstroms**2)
restraint.addPerParticleParameter("x0")
restraint.addPerParticleParameter("y0")
restraint.addPerParticleParameter("z0")

calphaIndex = []
for i,atom in enumerate(modeller.topology.atoms()):
    if atom.name =="CA":
        calphaIndex.append(i)

atom_positions = State.getPositions(modeller.topology, asNumpy = True)

restraint.addParticle(calphaIndex, atom_positions)
        
        
system.addForce(restraint)

**Comment by peastman** [comment]
You need to call `addParticle()` once for each particle.  Something like this should work:

```python
for i,atom in enumerate(modeller.topology.atoms()):
  if atom.name =="CA":
    restraint.addParticle(i, atom_positions[i])
```

**Comment by AhmetGG** [comment]
Thank you so much for your reply.I applied your suggestion on all heavy atom in my simulation. I did not get any mistake but I got confused whether I applied on position restrain for all heavy atoms in the correct way. Also does is matter where the part of applying restraint in any simulation of OpenMM is written? The following code is written:

# adding restraint on heavy atoms...

restraint= CustomExternalForce("k*periodicdistance(x,y,z,x0,y0,z0)^2")

restraint.addGlobalParameter("k",2.0*kilocalories_per_mole/angstroms**2)
restraint.addPerParticleParameter("x0")
restraint.addPerParticleParameter("y0")
restraint.addPerParticleParameter("z0")

atom_positions = modeller.positions

for i,atom in enumerate (modeller.topology.atoms()):
    if atom.name == "CA":
        restraint.addParticle(i,atom_positions[i])
    

for i,atom in enumerate (modeller.topology.atoms()):
    if atom.name == "N":
        restraint.addParticle(i,atom_positions[i])
        

for i,atom in enumerate (modeller.topology.atoms()):
    if atom.name == "C":
        restraint.addParticle(i,atom_positions[i])
        
system.addForce(restraint)

**Comment by peastman** [comment]
You're applying the restraint only to backbone heavy atoms, not to all heavy atoms.  But I assume that's what you intended?

You could combine all of those into a single loop:

```python
for i, atom in enumerate(modeller.topology.atoms()):
  if atom.name in ['CA', 'N', 'C']:
    restraint.addParticle(i, atom_positions[i])
```

The only important rule about where to put the code is that it needs to be *before* you create the Simulation/Context.  Once you create a Context, it won't see any further changes made to the System.

**Comment by AhmetGG** [comment]
Yes, I am trying to apply only backbone atoms. I did in this way. Thanks for your informative suggestion.

**Comment by peastman** [comment]
I believe all the questions have been answered, so I'm going to close this issue.  Feel free to reopen it if I missed something.
