### ISSUE TITLE
[Question] How to add tetrahedral restrain to a protein

### ISSUE THREAD

**Issue by nataliaszulc** [openmm/openmm#3160]
I have a set of indices for my protein system.  The indices represent atoms, that form the tetrahedral angle. My question is how to add restrains to selected indices in OpenMM framework. As far as I know from the documentation, there's  `CustomTorsionForce`. 

1. How do I define the force potential, If I want to restraint the angles e.g. with a force of 200 kJ/nm ? 
2. Do I add separate `CustomTorsionForce` for every set of 4 indices or not ?
3. There're any examples, that I could use to learn ?

**Comment by jchodera** [comment]
Hi @nataliaszulc!

If you simply need to add angular restraints with a force constant of 200 kJ/nm to the ideal tetrahedral angle of 109.5 degrees, you can do this with a [`HarmonicAngleForce`](http://docs.openmm.org/latest/api-python/generated/simtk.openmm.openmm.HarmonicAngleForce.html#simtk.openmm.openmm.HarmonicAngleForce):
```python
# Create the force
from simtk.openmm import HarmonicAngleForce
force = HarmonicAngleForce()
# Add the particles involved in each angle
# Here, we assume the four atom indices involved in the tetrahedron are atoms[0] as central atom, and atoms[1:4] are the substituents
from simtk import unit
tetrahedral_angle = 109.5*unit.degrees
force_constant = 200*unit.kilojoules_per_mole / unit.nanometers
atom2 = atoms[0] # central atom
from itertools import combinations
for atom1, atom3 in combinations(atoms[2:4], 2):
    force.addAngle(atom1, atom2, atom3, tetrahedral_angle, force_constant)
# Now add the force to the system
system.addForce(force)
```
There are other ways you could do this as well:
* You could use [`CustomAngleForce`](http://docs.openmm.org/latest/api-python/generated/simtk.openmm.openmm.CustomAngleForce.html#simtk.openmm.openmm.CustomAngleForce) if you wanted to control the spring constant or angle during the simulation with global variables
* You could use [`CustomCompoundBondForce`](http://docs.openmm.org/latest/api-python/generated/simtk.openmm.openmm.CustomCompoundBondForce.html#simtk.openmm.openmm.CustomCompoundBondForce) if you wanted to simply specify the four atoms and use a more complex energy expression to add all the angular restraints in one go

Let us know if we could be of more help!

**Comment by nataliaszulc** [comment]
Hi @jchodera, thanks for quick reply!

>```# Add the particles involved in each angle
># Here, we assume the four atom indices involved in the tetrahedron are atoms[0] as central atom, 
># and atoms[1:4] are the substituent atoms that should be restrained to tetrahedral geometry```

So I read angles from the initial structure, and then add them to my simulation ? Because I want to restraint backbone of my protein with respect to the initial structure.

**Comment by jchodera** [comment]
> So I read angles from the initial structure, and then add them to my simulation ? Because I want to restraint backbone of my protein with respect to the initial structure.

Oh! Could you elaborate on this a little more? Do you want to restrain them to stay close to a fixed point in Cartesian space (given by their initial positions), or do you want to allow the whole protein to rotate but just restrain some atoms close to their initial angles?

**Comment by nataliaszulc** [comment]
> 
> 
> > So I read angles from the initial structure, and then add them to my simulation ? Because I want to restraint backbone of my protein with respect to the initial structure.
> 
> Oh! Could you elaborate on this a little more? Do you want to restrain them to stay close to a fixed point in Cartesian space (given by their initial positions), or do you want to allow the whole protein to rotate but just restrain some atoms close to their initial angles?

I want to restrain tetrahedral angles with respect to the initial tetrahedral angles of the protein's backbone. But I also want the protein to be able to move in the x,y,z space freely. So the second option I think. 
The problem is, that my protein is embedded in the lipid membrane, and at the beginning of the simulation it unfolds, if its backbone is not restraint.

**Comment by peastman** [comment]
When you say a "tetrahedral" restraint, do you mean a restraint on the dihedral angle formed by four atoms (but not affect any other of their degrees of freedom)?  Or do you mean that you want to restrain them to a particular tetrahedral geometry (which would restrain multiple degrees of freedom)?

**Comment by nataliaszulc** [comment]
@peastman 
I think I'd like to have the first, like in GROMACS. I attach definition of restrains from GROMACS's doc. 
![obraz](https://user-images.githubusercontent.com/48363461/123821554-cb0dc400-d8fb-11eb-9598-fc69913ce172.png)

**Comment by peastman** [comment]
Ok, CustomTorsionForce is what you want then.  The documentation at http://docs.openmm.org/latest/api-c++/generated/OpenMM.CustomTorsionForce.html#_CPPv4N6OpenMM18CustomTorsionForceE gives an example of a harmonic restraint, including showing how to deal with the discontinuity in the domain when the angle jumps by 2*pi.

You only need to add a single CustomTorsionForce.  You call `addTorsion()` on it once for each set of four atoms you want to restrain.

**Comment by nataliaszulc** [comment]
> You only need to add a single CustomTorsionForce. You call `addTorsion()` on it once for each set of four atoms you want to restrain.

But if the reference angle is different for every 4-tuple of atoms, then also I need to use only one force ? Because If want to restrain every dihedral angle in the protein, then I will restrain it to the initial angle from my initial structure.

**Comment by peastman** [comment]
You specify the reference angle with a per-torsion parameter.  This is done in the example linked above.

**Comment by nataliaszulc** [comment]
@peastman 
So after I define my force object, I do:
```
initial_angle = 2.
forceobj.addTorsion(1, 6, 8, 14, initial_angle)
```
and I do it for every set of 4 atoms, yes ?

**Comment by peastman** [comment]
Make that

```python
forceobj.addTorsion(1, 6, 8, 14, [initial_angle])
```

The final argument is a list of parameter values, which in your case has length 1.  But aside from that minor detail, yes, that's correct.

**Comment by nataliaszulc** [comment]
@peastman Thank you, I'll let you back if it works for me
