### ISSUE TITLE
Link to docs 404s

### ISSUE THREAD

**Issue by mikemhenry** [openmm/openmm#3163]
The `README.md` links to http://docs.openmm.org/ which redirects to https://openmm.org/documentation.html which then 404s.
I'm guessing this happened after the website rework where the docs pages are a tab instead of a separate page.

**Comment by peastman** [comment]
cc @raimis.  This is closely related to https://github.com/openmm/openmm-org/issues/55.

**Comment by jchodera** [comment]
I've been thinking that we were a bit too hasty in moving away from the previous structure to use tabs instead. It's possible this generated a ton of broken links.

**Comment by jchodera** [comment]
http://docs.openmm.org works again thanks to @raimis!
