### ISSUE TITLE
addHydrogens() fails to add hydrogens to topology with glycam residues

### ISSUE THREAD

**Issue by zhang-ivy** [openmm/openmm#3175]
I am trying to call `modeller.addHydrogens()` on a topology that has glycam residues, however, it fails to add hydrogens to to glycam residues. I think this is because [hydrogens.xml](https://github.com/openmm/openmm/blob/master/wrappers/python/openmm/app/data/hydrogens.xml) does not include glycam residues. 

How was hydrogens.xml generated? If there's existing code that takes a forcefield and generates a hydrogens.xml file, could you point me to it? 

Tagging @peastman  for feedback!

**Comment by peastman** [comment]
It's been many years since I created it.  Whatever script I wrote for it, I have no idea where it is now.  I believe the process was only partly automated.  If I recall, it parsed the monomer PDB files from https://www.wwpdb.org/data/ccd to generate the list of hydrogens and the heavy atom each was bonded to.  But those files don't indicate which hydrogens are only present in terminal residues, so I had to add that information by hand.

If you create your own file with additional hydrogen definitions, you can call [`loadHydrogenDefinitions()`](http://docs.openmm.org/latest/api-python/generated/simtk.openmm.app.modeller.Modeller.html#simtk.openmm.app.modeller.Modeller.loadHydrogenDefinitions) to load it.

**Comment by zhang-ivy** [comment]
Thanks! I'll work on generating a hydrogens.xml for glycam residues over the next couple days.

> But those files don't indicate which hydrogens are only present in terminal residues, so I had to add that information by hand.

How did you know which hydrogens should be present in terminal residues? For example, from glancing at hydrogens.xml, it seems that for all standard amino acids, you've added 
```xml
  <H name="H2" parent="N" terminal="N"/>
  <H name="H3" parent="N" terminal="N"/>
```
How did you know that this is the right hydrogen naming scheme? I don't see `H2` or `H3` present in [ff14SB](https://github.com/openmm/openmmforcefields/blob/master/amber/ffxml/protein.ff14SB.xml)

**Comment by zhang-ivy** [comment]
When I look up [the bonds for `ASN` in the CCD](https://www.ebi.ac.uk/pdbe-srv/pdbechem/bond/list/ASN), I see N-H2 but not N-H3: 
<img width="1167" alt="Screen Shot 2021-07-26 at 3 46 24 PM" src="https://user-images.githubusercontent.com/35546250/127049398-b0a85917-367c-4511-8bf1-d9adab2c4c45.png">

**Comment by peastman** [comment]
If in doubt, look at the template definitions.  Amber defines three versions of each amino acid.  For example, ALA is an ALA residue in the middle of a chain, NALA is an N-terminal one, and CALA is a C-terminal one.  You can compare them to see what atoms and bonds are different.

**Comment by zhang-ivy** [comment]
Ok I'm looking at [the template for NALA in ff14SB](https://github.com/openmm/openmmforcefields/blob/master/amber/ffxml/protein.ff14SB.xml#L1936) and it seems to indicate that when ALA is an n-terminal residue, the hydrogens bonded to N are H1, H2, H3. However, hydrogens.xml indicates it would be H, H2, and H3: https://github.com/openmm/openmm/blob/master/wrappers/python/openmm/app/data/hydrogens.xml#L35-L37
Do you remember the rationale for writing ALA in hydrogens.xml like this? 

Also, a more general question -- why did you introduce the `terminal` attribute in hydrogens.xml instead of just having separate Residue elements for NALA and CALA in hydrogens.xml?

**Comment by peastman** [comment]
The names that appear in force field definitions are arbitrary.  They're just labels.  For the Amber force fields, we copied the names used in the original Amber files.  Templates are matched to residues based on elements and bonds.  It doesn't matter what names they have.

The names in hydrogens.xml are not arbitrary.  They should match the CCD.  The PDB uses the same name for an ALA residue wherever it appears in a chain.

In general there may be multiple templates corresponding to different versions of a single residue.  Terminal and non-terminal versions are one example of that.  CYS residues can also have different templates depending on whether they form disulfide bonds.

**Comment by zhang-ivy** [comment]
>The names that appear in force field definitions are arbitrary. They're just labels. For the Amber force fields, we copied the names used in the original Amber files. Templates are matched to residues based on elements and bonds. It doesn't matter what names they have.

Got it, thanks. For glycam residues, this is no longer true, as we match residues based on names and not topology.

> The names in hydrogens.xml are not arbitrary. They should match the CCD. The PDB uses the same name for an ALA residue wherever it appears in a chain.

Thanks for the clarification. I've decided to generate a hydrogens.xml for glycam residues by: 
1) Reading in the converted GLYCAM_06j-1.xml to generate a dictionary of key: residue name, value: list of tuples containing hydrogens and their parent atoms
2)  Using the dictionary to create a hydrogens.xml in the same format as the current one in OpenMM.

Note that this deviates from the hydrogens.xml currently in OpenMM in that the glycan residue names in the input PDB file will need to be amber based, not CCD based. The reason for this choice is that CCD based residue names do not account for differences in glycan connectivity. 
Here are two examples:
- NLN is the amber residue name for ASNs that are missing a hydrogen to allow it to bond to a glycan residue. However, CCD doesn't have a different name for ASNs that are bound to a glycan residue, the name is ASN regardless. 
- CCD does not distinguish between amber residues UYB and 4YB, which contain different numbers of hydrogens -- both of these are called NAG in CCD. 

Attached is an example of a PDB with amber glycam names (amber.pdb) and the same PDB with CCD glycam names (ccd.pdb).

To circumvent problems like the aforementioned ones, I could introduce a bunch of attributes that distinguish between the different residue templates, but I think for now, it's easiest if I just require the user to input a PDB file with amber glycam residue names. If someone else has time to generate a hydrogens.xml for glycan residues with CCD names in the future, they can do so themselves.

@peastman: Please let me know if all this sounds reasonable to you. I'm attaching the hydrogens.xml I generated for glycam residues here in case you have time to review.

Finally -- should we consider including the hydrogens.xml for glycam residues as part of the OpenMM repo so that anyone interested in calling addHydrogens() to a topology with glycans can do so?

[hydrogen_xml_files.zip](https://github.com/openmm/openmm/files/6881550/hydrogen_xml_files.zip)

**Comment by peastman** [comment]
That seems reasonable.  It's an ugly hack, but given the design of glycam, it's probably the best of various bad options.  The big disadvantage is that it won't work for standard PDB files.  It will only work for ones that have been modified to use glycam's nonstandard names in place of the standard ones.

**Comment by jchodera** [comment]
Will adding GLYCAM hydrogen definition files _break_ handling of PDB files because the names don't correspond to standard names? If it won't break things, it may be safe to include. 

If it's not safe, we can add a section to the user guide showing users how to call the [`Modeller.loadHydrogenDefinitions()`](http://docs.openmm.org/latest/api-python/generated/simtk.openmm.app.modeller.Modeller.html#simtk.openmm.app.modeller.Modeller.loadHydrogenDefinitions) to add this file (which we can still distribute) before processing a GLYCAM PDB file.

Again, the long-term solution here is really something like [Open Force Field](https://openforcefield.org/) or [espaloma](https://github.com/choderalab/espaloma). I keep thinking we should train an "official" OpenMM version of espaloma for parameter assignment just to streamline handling of systems where "close enough" is good enough.

**Comment by peastman** [comment]
It might be ok, but probably it's safest if we tell people to load the file themselves.

> Again, the long-term solution here is really something like Open Force Field or espaloma.

How would that help?  This is about adding missing hydrogens to your structure, which comes before parameter assignment.  Are you suggesting creating a SMIRKS based method for identifying what hydrogens need to be added?

**Comment by jchodera** [comment]
> How would that help? This is about adding missing hydrogens to your structure, which comes before parameter assignment. Are you suggesting creating a SMIRKS based method for identifying what hydrogens need to be added?

No, but that's a good idea! 

The comment was more directed toward this:

> The big disadvantage is that it won't work for standard PDB files. It will only work for ones that have been modified to use glycam's nonstandard names in place of the standard ones.

OpenFF ignores the definitions of both residues and residue names / atom names in assigning parameters.

**Comment by zhang-ivy** [comment]
>It might be ok, but probably it's safest if we tell people to load the file themselves.

@peastman : Do you want to open a PR that 1) updates the docs to tell people to load my hydrogens.xml for glycam residues and 2) includes my glycam hydrogens.xml in `openmm/app/data/`? 
I can do this if you prefer, just let me know which file I need to update in order add to the docs.

We may also want to include the converted GLYCAM_06j-1.xml in `openmm/app/data/amber14/`, right?

**Comment by peastman** [comment]
Sure, I can do that.  I'm going to wait until we have 7.6 out, which will probably be about two weeks.
