### ISSUE TITLE
single group center of mass restraint

### ISSUE THREAD

**Issue by namyh** [openmm/openmm#3189]
Hi,

I'm trying to give restraint force to an enzyme in my system to prevent enzyme drifting issue.

Is CustomCentroidBondForce good choice to hold this single group to it's original coordinate?

After few ns MD simulation with this command, enzyme didn't move toward pbc box but rotated in that position

can you help for this problem?

thank you

**Comment by peastman** [comment]
I assume you want to prevent the enzyme from either rotating or translating, not just translating?  What else is in the system?  Do you want it to be completely fixed in place, or have a limited amount of motion allowed?

What expression did you use for the CustomCentroidBondForce?

The more detail you can give about exactly what you want to happen, the more we'll be able to help.

**Comment by namyh** [comment]
I want no translation or rotation of the enzyme itself, I want only the movements of amino acids(backbone, and functional groups). I calculate RMSD  through trajectories, and translation and rotation of enzyme are not favorable to have converged RMSD. my system contains box full water, an enzyme and a ligand.

proa = []
for i in range(0,5746) :
    proa.append(i)
proa_coor = [pdb.positions[index]/nanometer for index in proa]
force = CustomCentroidBondForce(1, "0.5*k*((x1-0)^2+(y1-0)^2+(z1-0)^2)")
force.addGlobalParameter("k", 100.0*kilocalories_per_mole/nanometer**2)
force.addGroup(proa)
system = psf.createSystem(params, nonbondedMethod = PME, nonbondedCutoff=1.6*nanometer)

<<< these are my codes

**Comment by namyh** [comment]
I changed lines to

proa = []
for i in range(0,5746) :
    proa.append(i)
proa_coor = [pdb.positions[index]/nanometer for index in proa]
avg = np.mean(np.asarray(proa_coor), axis=0)
print(avg)
xavg = avg[0]
yavg = avg[1]
zavg = avg[2]

**_force = CustomCentroidBondForce(1, "0.5*k*((x1-xavg)^2+(y1-yavg)^2+(z1-zavg)^2)")_**
instead of **_force = CustomCentroidBondForce(1, "0.5k((x1-0)^2+(y1-0)^2+(z1-0)^2)")_**

and the enzyme maintained its position and the RMSD result seems to converge after few ns MD simulation

thank you!

**Comment by peastman** [comment]
You're applying a single restraint to the position of the enzyme's centroid.  That will prevent it from translating but not from rotating.  It sounds like that's good enough for your purposes though.  It also isn't clear to me why you need this restraint at all.  Neither translations nor rotations affect RMSD.  What is the goal of the restraint?

By the way, this code

```python
proa = []
for i in range(0,5746) :
  proa.append(i)
```

can be simplified to just

```python
proa = list(range(5746))
```

**Comment by namyh** [comment]
I saw a paper of protein-ligand complex MD simulation and they fixed the center of mass of the protein to prevent the enzyme drift to the box. So I thought that I need to prevent the rotation and translation too. But, I figured out that I was doing wrong RMSD calculation and realized that  I don't need any restraint to my system..!!
I'm so grateful to your kind advice
thank you so much

**Comment by peastman** [comment]
Ok, great!
