### ISSUE TITLE
Building openmm 7.5.1 with intel compiler fails TestVectorizeAvx (but not TestVectorizeAvx2)

### ISSUE THREAD

**Issue by Gareth-elliott** [openmm/openmm#3192]
Hi OpenMM Developers,

I have been trying to build openmm 7.5.1 with intel compilers, however TestVectorizeAvx keeps failing (but not TestVectorizeAvx2).

I have built it already with gnu compilers, but was looking to see if I could get some extra performance.  If this test fails but Avx2 passes, is OpenMM ok to use anyway? (i.e. if avx2 instructions are available, they will get used instead of avx instead?)

I'm using the intel compiler version 19.0.4.243

    Start 450: TestVectorizeAvx
1/1 Test #450: TestVectorizeAvx .................***Failed    0.01 sec
exception: Assertion failure at TestVectorizeGeneric.h:400.  Error during test for type 5fvec8
Values differ. 1, 1, 1, 1, 1, 1, 1, 1,  and 2, 2, 2, 2, 2, 2, 2, 2,

**Comment by peastman** [comment]
If a test case is failing, that indicates a potential problem.  You would need to debug the test and figure out what is going wrong.

We don't support the Intel compiler.  Several years ago we did try compiling with it, but we found it produced slower code than either clang or gcc, so there was no reason to try to support it.

**Comment by Gareth-elliott** [comment]
Thanks for the quick reply as usual @peastman 👍 
I haven't had any experience debugging code before, and if you and the other developers found that it wasn't faster anyway, then I'll just stick with the gnu compiled version. 
Just for reference, building with only the -g flag passes the test, however the TestVectorizeAvx appears to fail for any of the O[1,2,3] optimisation flags.
Thanks again for your quick reply :-)
Feel free to close the issue.

**Comment by peastman** [comment]
That sounds suspiciously like a compiler bug.  Optimizations aren't supposed to change the behavior.  Anyway, I'll go ahead and close this.
