### ISSUE TITLE
Implementing targeted MD in openMM

### ISSUE THREAD

**Issue by asgharrazavi** [openmm/openmm#3195]
Is there a guide on how to implement RMSD-based targeted MD (an example [here](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.0020134)) using openmm? I was able to use `CustomExternalForce` to force atoms to move toward a reference structure but I don't how to update target values (x0, y0, z0) during simulation:
```
chains = [chain for chain in pdb.topology.chains()]
listt = [str(i) for i in range(675,750)]
pull_index = [atom.index for atom in chains[0].atoms() if atom.residue.id in listt and atom.name=='CA']
pull_force = CustomExternalForce("k*periodicdistance(x, y, z, x0, y0, z0)^2")
pull_force.addGlobalParameter("k", 20)
pull_force.addPerParticleParameter('x0')
pull_force.addPerParticleParameter('y0')
pull_force.addPerParticleParameter('z0')
ref_xyz = np.loadtxt('ref_xyz.dat')  * 0.1   # these are the target structure CA coordinates in angstrom
xyz = pdb.positions
for i,j in zip(pull_index,ref_xyz.T):
    x0, y0, z0 = j[0], j[1], j[2] 
    pull_force.addParticle(i,[x0, y0, z0])
system.addForce(pull_force)
```

**Comment by peastman** [comment]
You can update them like this:

```python
for i, pos in enumerate(newPositions):
  pull_force.setParticleParameters(i, i, pos)
pull_force.updateParametersInContext(context)
```

This would make a good example for the cookbook (#3140).  It's almost the same as https://gist.github.com/peastman/ad8cda653242d731d75e18c836b2a3a5, just with the addition of changing the target positions.

**Comment by asgharrazavi** [comment]
Since I am applying forces to only a subset of atoms, shouldn't the code be like this:
```python 
for i, pos in zip(pull_index,newPositions):
  pull_force.setParticleParameters(i, i, pos)
pull_force.updateParametersInContext(context)
```

Also, how can I do the updating while the simulation is running? For example, I am running simulation for 10000 steps: `simulation.step(10000)` , and I want to update new positions every 1000 steps.

**Comment by peastman** [comment]
For a subset of atoms, you probably want this:

```python
for i in range(len(pull_index)):
  pull_force.setParticleParameters(i, pull_index[i], newPositions[i])
```

To update the parameters every 1000 steps, just change your code to

```python
for i in range(10):
  simulation.step(1000)
  # update parameters for the next 1000 steps
```

**Comment by peastman** [comment]
Closing this since the question was answered.
