### ISSUE TITLE
specifying pair-wise CustomNonbondedForce parameter

### ISSUE THREAD

**Issue by anseongpark** [openmm/openmm#3197]
Dear developers,

I've recently started learning 'openMM', and struggling with modifying ` CustomNonbondedForce ` interaction term. So far, I've modified .xml file to implement `CustomNonbondedForce` interaction

    <CustomNonbondedForce energy = ~ />
      <PerParticleParameter name = ~ />
        <Atom type = ~ />
        <Atom type = ~ />
I know that we can use user-specified combining rule to calculate nonbonded interaction parameters, and so far everything works good. However, my concern is some of my nonbonded interaction pair parameters are from reference parameters, not from combining rule. In this case, my  I ask is there a way to assign pair-wise parameters that I want to the `CustomNonbondedForce` ?

Thanks,

Anseong

**Comment by peastman** [comment]
You can assign an integer "atom type" to each particle, then look up the interaction parameters in a table.  That's how we implement the `<LennardJonesForce>` tag, which allows you to override the combining rules for certain pairs of types.

https://github.com/openmm/openmm/blob/473069f07ecbf6267db2fc558dc8443a8d01d4e8/wrappers/python/openmm/app/forcefield.py#L2597-L2600

**Comment by anseongpark** [comment]
Thank you very much for the help.
It is working now and I am closing this issue.

**Comment by anseongpark** [comment]
Sorry for reopening the question. Code run successfully, however the result was not really representing the `customnonbondedforce` that i wanted. I tried to figure out by myself, but couldn't find out why it happens. Below code is the Buckingham potential that I've currently working on.
First, I read fixed inter-atomic buckingham potential parameter (A, B, and C) and saved it to `ff_params`. I have 9 unique atomtypes in the system and each inter-atomic interaction accompanies 3 nonbondedforce parameters, so the shape of `ff_params` matrix is [9 x 9 x 3].  After defining `ff_params`, I've tried to follow what you've advised to do.
```
numTypes = len(mergedTypes)
acoef = [0]*(numTypes*numTypes)
bcoef = [0]*(numTypes*numTypes)  
ccoef = [0]*(numTypes*numTypes)  
for m in range(numTypes):
	for n in range(numTypes):
		num = m+numTypes*n; ffm=mergedTypes[m]-1; ffn=mergedTypes[n]-1
		acoef[num] = ff_params[ffm,ffn,0] 
		bcoef[num] = ff_params[ffm,ffn,1]   
		ccoef[num] = ff_params[ffm,ffn,2]  
		continue 
cbForce = CustomNonbondedForce('A(type1,type2)*exp(-r*B(type1,type2))-C(type1,type2)/r^6+4.184*0.00005*(12/(B(type1,type2)*r))^12;')
A = 1.0*kilojoules_per_mole
B = 1.0*nanometer**(-1)
C = 1.0*kilojoules_per_mole*nanometer**(6)
cbForce.addTabulatedFunction('A', Discrete2DFunction(numTypes,numTypes,acoef))
cbForce.addTabulatedFunction('B', Discrete2DFunction(numTypes,numTypes,bcoef))
cbForce.addTabulatedFunction('C', Discrete2DFunction(numTypes,numTypes,ccoef))
cbForce.addPerParticleParameter('type')
cbForce.setNonbondedMethod(CustomNonbondedForce.CutoffPeriodic)
cbForce.setCutoffDistance(cutoff)
for idx, pos in enumerate(pdb.positions):
	cbForce.addParticle((mergedTypes[idx],))
```
Parameters such as `mergedTypes`, `acoef`, `bcoef`, `ccoef` were saved without problem. After running the simulation, the results showed that the strength of `customNonbondedForce` was weak that some atoms were close as much as a covalent bond.

Previously, I've performed simulation that includes `customNonbondForce` in .xml file using modified Waldman-Hagler rule and the result was fine. However, problem happens when I tried to include fixed-nonbonded parameters in python code the way I mentioned above. Could you tell me what the problem is??

I really appreciate your help.

**Comment by peastman** [comment]
I don't see anything obviously wrong with the code as far as it goes, except for the three lines defining `A`, `B`, and `C` which never get used.  Make sure your units are correct.  If in doubt, create a system with just two particles.  Compute the energy a few times while changing the distance between them and make sure it matches what you expect.

**Comment by peastman** [comment]
Did you figure this out?  If so, can the issue be closed?

**Comment by anseongpark** [comment]
unfortunately, I couldn't solve the problem. So, I rather used other force-field that did not need any custom-nonbonded force parameter. Nevertheless, thank you for your advice. I think this issue can be closed.
