### ISSUE TITLE
A parallel simulation on multiple CPU 

### ISSUE THREAD

**Issue by AhmetGG** [openmm/openmm#3200]
Hi, I want to run my simulation as parallel simulation so I would like to use 4 CPU and 1 GPU on it. When I write CUDA platform, the only CPU and GPU. If I wrote CPU. I guess, GPU is not working. How can I do that?

**Comment by peastman** [comment]
We don't attempt to split work between CPUs and GPUs.  A good GPU is so much faster than most CPUs, there just isn't anything to gain.  The overhead of transferring data back and forth and having to synchronize them ends up making it slower than if you just keep everything on the GPU.

**Comment by AhmetGG** [comment]
As far as I understand, there is no gain when I run on multiple CPU cores. Thank you so much...
