### ISSUE TITLE
Modeller.addHydrogens and hydrogens.xml with metals

### ISSUE THREAD

**Issue by MauriceKarrenbrock** [openmm/openmm#3206]
Hi,

I have two correlated questions about adding hydrogens in case of residues complexing a metal

1) I noticed that CYM is not defined in hydrogens.xml , is there a reason or could it be added?
I guess it could be done like:
```
<Residue name="CYS">
  <Variant name="CYS"/>
  <Variant name="CYX"/>
  <Variant name="CYM"/>
  <H name="H" parent="N"/>
  <H name="H2" parent="N" terminal="N"/>
  <H name="H3" parent="N" terminal="N"/>
  <H name="HA" parent="CA"/>
  <H name="HB2" parent="CB"/>
  <H name="HB3" parent="CB"/>
  <H name="HG" parent="SG" maxph="8.5" variant="CYS"/>
 </Residue>
```

2) I have seen that Modeller.addHydrogens checks for possible hydrogen bonds to decide where to put the hydrogen in histidines (HIS -> HIE, HID), but by looking at the code it looks like it only takes in consideration distance and angles but not the atom type, does it mean that there is the risk it will generate an hydrogen pointing towards a positively charged metallic ion?

Thank you very much in advance and have a nice day

**Comment by peastman** [comment]
> I noticed that CYM is not defined in hydrogens.xml , is there a reason or could it be added?

I don't think I understand.  You haven't made any atoms depend on that variant.  Are you just asking for it to accept "CYM" as a synonym for "CYX"?  Why?

> does it mean that there is the risk it will generate an hydrogen pointing towards a positively charged metallic ion?

The only elements it considers for hydrogen bond acceptors are oxygen and nitrogen:

https://github.com/openmm/openmm/blob/ae2fe2fd7db2aae4c5c39fadcee328c6d5bc607d/wrappers/python/openmm/app/modeller.py#L792

**Comment by MauriceKarrenbrock** [comment]
> Are you just asking for it to accept "CYM" as a synonym for "CYX"

Yes that's what I meant as it is (at least in amber FF) the name of cysteines complexing a metal and it has to be deprotonated exacly as CYX, so it looked like the easiest way to do it.
In any case if you think it's not a good idea don't worry, in case I would find a way around it.

>  The only elements it considers for hydrogen bond acceptors are oxygen and nitrogen

I guess I missed that line, that's exactly what I was looking for!

Thank you very much!

**Comment by peastman** [comment]
Amber has a lot of nonstandard names it uses for different kinds of residues.  Those names are completely specific to Amber.  They aren't used by other codes or other force fields.
