### ISSUE TITLE
modeller.addSolvent() requires Vec3 objects to return solvated protein in center of the box

### ISSUE THREAD

**Issue by zhang-ivy** [openmm/openmm#3213]
I recently noticed that if I feed modeller.addSolvent() positions in numpy format (not Vec3), the outputted protein positions are not centered with respect to the solvent box: 
<img width="434" alt="Screen Shot 2021-08-16 at 2 02 22 PM" src="https://user-images.githubusercontent.com/35546250/129608880-2d71f314-9c09-4b2c-9e80-844902501ee4.png">

If I convert the positions to Vec3 objects, the protein 
positions are centered correctly:
<img width="403" alt="Screen Shot 2021-08-16 at 2 03 15 PM" src="https://user-images.githubusercontent.com/35546250/129608981-d3498d64-75d5-4f7b-832e-a969203c3f87.png">

@jchodera mentioned that `addSolvent` should not be sensitive to the type of the input positions, which is why I'm raising this issue. Tagging @peastman so we can discuss what the right expected behavior here is.

Attached are the files necessary to reproduce this.
[debug_vec3_issue.zip](https://github.com/openmm/openmm/files/6995020/debug_vec3_issue.zip)

**Comment by peastman** [comment]
Are you sure the difference is really the input format, not the input coordinates?  `addSolvent()` should leave the positions of all existing atoms unchanged, whatever format they're in.  Try taking the list of Vec3s and wrap it in a call to `np.array()`.  Does that change the behavior?

**Comment by zhang-ivy** [comment]
Yes, it's the input format. The only difference in the code used to generate the positions in the first screenshot and the second screenshot is that the second screenshot takes the numpy positions and generates
```python
# Convert positions back to openmm vec3 objects
complex_positions_vec3 = []
for position in complex_positions:
    complex_positions_vec3.append(openmm.Vec3(*position.value_in_unit_system(unit.md_unit_system)))
complex_positions_vec3 = unit.Quantity(value=complex_positions_vec3, unit=unit.nanometer)
```
> Try taking the list of Vec3s and wrap it in a call to np.array(). Does that change the behavior?
I double checked this and when I wrap the Vec3s in a np.array(), the positions now match the first screenshot (wrong behavior).

**Comment by peastman** [comment]
Found the problem!  It's in the constructor of Modeller's internal `_CellList` class.  It uses `[:]` to make a copy of the positions before applying periodic boundary conditions to them:

https://github.com/openmm/openmm/blob/ad113a0cb37991a2de67a08026cf3b91616bafbe/wrappers/python/openmm/app/modeller.py#L1540

That works for standard Python collections like lists and tuples, but for numpy arrays it just creates a view pointing to the same data.

The fix is very easy: just use `deepcopy()` instead of `[:]` to make the copy.

**Comment by zhang-ivy** [comment]
Ah great!

**Comment by jchodera** [comment]
Would this bug have actually generated problematic inputs, or did it just result in translated or odd-looking initial snapshots?

**Comment by peastman** [comment]
As far as I can tell, it's just translated.  The protein still looks fine.  It's just not centered in the water box.
