### ISSUE TITLE
OpenMM 7.6 rc1: `app.internal` not in legacy `simtk` namespace

### ISSUE THREAD

**Issue by dwhswenson** [openmm/openmm#3218]
Namespaces other than `unit`, `openmm`, and `openmm.app` were not included in the legacy support for imports from the `simtk` namespace in #3000. OpenPathSampling uses `openmm.app.internal.unitcell.reducePeriodicBoxVectors`, and `simtk.openmm.app.internal` is no longer a valid import.

I think it's completely reasonable to say "these are internal APIs; you're using them at your own risk" (and I already have a fix for this for OPS in https://github.com/openpathsampling/openpathsampling/pull/1051). But I figured it was worth raising the issue in case you want to provide backward compatibility for these namespaces as well.

Aside: The good news is that [the GitHub action I wrote](https://github.com/marketplace/actions/check-conda-for-release-candidates) to test against OpenMM release candidates works as hoped -- tests ran against the RC without me needing to do anything.

**Comment by peastman** [comment]
I knew I must have called that package `internal` for a reason. :)

**Comment by peastman** [comment]
Closing this, since we decided not to support the legacy name for `internal`.
