### ISSUE TITLE
wwPDB running out of 3-character residue IDs

### ISSUE THREAD

**Issue by tristanic** [openmm/openmm#3219]
The discussion in #3217 reminded me... I can't recall exactly where I heard this (I think a presentation by a wwPDB member?), but the set of available 3-character residue ID codes is expected to run out in the next year or two. That's expected to mark the official end of life for the venerable PDB format - the new solution will be mmCIF only. Just flagging for future-proofing purposes.

**Comment by peastman** [comment]
I'm closing this, since I don't think there's really anything for us to do about it (except keep encouraging people to move to PDBx/mmCIF, of course!).  If there's something more specific you think we should do, feel free to reopen it.
