### ISSUE TITLE
amber water/ion force fields do not load compromise (CM) parameter set 

### ISSUE THREAD

**Issue by PatschD** [openmm/openmm#3224]
I am trying to model some zinc ions using the 12-6 LJ Nonbonded Model, however, when i create a system using:
pdb file i am using is 4V2Y

pdb = PDBFile('input')
forcefield = ForceField('amber14/protein.ff14SB.xml', 'amber14/spce.xml',)

system = forcefield.createSystem(pdb.topology, nonbondedMethod=PME, rigidWater=False)
integrator = LangevinMiddleIntegrator(300*kelvin, 1/picosecond, 0.004*picoseconds)
simulation = Simulation(pdb.topology, system, integrator)

and check out the details (using parmed), i get an empty string for type and no charge/Lj parameters for the ions. is this a bug or do i have to create custom XML files for this? i thought this information is included in the space water fields

**Comment by peastman** [comment]
The reason for this is that Amber defines two different versions of the template with different charges: `FE` for Fe3+ and `FE2` for Fe2+.  ForceField doesn't know which one you want.  You can tell it which to use by including the `residueTemplates` argument in the call to `createSystem()`.  For example, you can specify something like

```python
residueTemplates=dict((res, 'FE2') for res in topology.residues() if res.name == 'FE')
```

depending on which template you want to use, and what name the residues have.  See http://docs.openmm.org/latest/api-python/generated/openmm.app.forcefield.ForceField.html#openmm.app.forcefield.ForceField.createSystem for more details.
