### ISSUE TITLE
DrudeSCFIntegrator Energy Drift?

### ISSUE THREAD

**Issue by jstoppelman** [openmm/openmm#3233]
Hello, I've run into the need to use the DrudeSCFIntegrator instead of the DrudeLangevinIntegrator as I would normally use. When testing energy conservation of my system, I've noticed a pretty severe energy drift in the total energy (kinetic + potential) of -50 kJ/mol/ps  for a unitcell containing 110 acetonitrile molecules. I see a similar effect when running a simulation of a unitcell containing 300 water molecules using the SWM4-NDP water model. Is an energy drift of this magnitude expected? I would be happy to provide a directory containing my tests with input files and OpenMM run scripts if this would be helpful.

**Comment by peastman** [comment]
Here are a few things to check.

- What do you have the minimization error tolerance set to?  (Call `getMinimizationErrorTolerance()` on the integrator to check.)  In general the smaller the tolerance, the better the energy conservation.
- What step size are you using?  Constant energy simulations generally need a smaller step size than constant temperature ones.
- If you're using CUDA or OpenCL, which precision mode are you using?  If you're using single precision, try switching to mixed precision.

**Comment by jstoppelman** [comment]
Thank you for the response!

- For these simulations, I used `setMinimizationErrorTolerance(1e-3)` Do you recommend I move to a smaller value?
- I used a 0.5 fs timestep. I believe that is standard for Drude particles using the SCF treatment, but I can try a smaller timestep i.e. 0.25 fs.
- I used OpenCL, with the precision set to double for these simulations.

**Comment by jstoppelman** [comment]
- I've tried changing the minimization tolerance down to 1e-5 while keeping the time step at 0.5 fs, and the drift is approximately the same
- Oddly, I've changed the step size to 0.1 fs while keeping the tolerance at 1e-3, and I still see a similar magnitude of drift. 
- I have no constraints in my simulation.

**Comment by swails** [comment]
Another idea is to change the platform (CPU or Reference - although the latter can be *really* slow for some custom forces).

**Comment by peastman** [comment]
If you're running in double precision, CUDA should be very precise.  More precise than CPU, in fact.

I'm puzzled.  Those are all the standard things I would expect to affect energy conservation, but it seems none of them is the cause.  I can't rule out the possibility of a bug in DrudeSCFIntegrator.  It's a rarely used class, so it hasn't received as much attention as most other integrators.  Can you post a test case?

**Comment by jstoppelman** [comment]
Thank you for taking a look. This zip file contains an OpenMM run script and input files for the acetonitrile system I was looking at, and also an input file and run script for SWM4-NDP water, which I also saw exhibit similar drift as the acetonitrile system.
[drudescf_test.zip](https://github.com/openmm/openmm/files/7101732/drudescf_test.zip)

**Comment by peastman** [comment]
The main source of energy drift is errors in computing the nonbonded interactions.  Add these arguments in the call to `createSystem()`: `nonbondedMethod=PME, ewaldErrorTolerance=5e-5, switchDistance=0.9*nanometer`.  Reducing the Ewald error tolerance causes it to compute Coulomb interactions more accurately.  The `switchDistance` argument causes it to apply a switching function to the Lennard-Jones interactions.  Otherwise it applies a sharp cutoff.  At 1 nm, those interactions are tiny enough that the discontinuity is insignificant in a constant temperature simulation.  But for constant energy, all those tiny errors every time a particle crosses over it add up and lead to energy drift.

Adding those arguments makes the energy drift several times smaller.  If you want to reduce it further, you can experiment to see what is the remaining dominant source of error.

**Comment by jstoppelman** [comment]
Ok thanks, I've noticed some improved performance. I'll try to see if there are any settings that can help.

**Comment by selimsami** [comment]
Just bumped into this post from long ago while trying to set up a SWN4 system myself and I noticed an important problem with the setup, which I thought my be useful to mention in case someone bumps into here as well:

`forcefield.createSystem ` by default assigns a mass to Drude particles of 0.4 amu, which is incompatible with DrudeSCF.
Setting forcefield.createSystem(..., drudeMass=0) should make a big difference to the above results (no idea if it will fix the drift issue though)
