### ISSUE TITLE
Python package does not install cleanly in an empty virtualenv

### ISSUE THREAD

**Issue by ecederstrand** [openmm/openmm#3237]
https://github.com/openmm/openmm/blob/master/wrappers/python/setup.py contains a top-level import of numpy and Cython which means that you cannot install the OpenMM Python package cleanly in an empty virtualenv.

```python
$ python3 -m venv .env
$ source .env/bin/activate
$ python3 setup.py build_ext bdist_wheel
Traceback (most recent call last):
  File "setup.py", line 9, in <module>
    import numpy
```
The solution is to create a custom build extension in setup.py and add a `setup_requires=["Cython", "numpy"]` argument to `setup()`. See example in e.g. https://github.com/scikit-garden/scikit-garden/pull/86

**Comment by peastman** [comment]
You need to follow the instructions at http://docs.openmm.org/latest/userguide/library/02_compiling.html.  Building the OpenMM Python layer is much more complicated than just executing setup.py.  Large parts of it first need to be generated by SWIG, based on interface definition files that in turn need to get programmatically generated.  The CMake build scripts automate all of this.

**Comment by pippo1990** [comment]
meaning changing this 

Set the variable CMAKE_INSTALL_PREFIX to the location where you want to install OpenMM.

Set the variable PYTHON_EXECUTABLE to the Python interpreter you plan to use OpenMM with. Usually this will be detected automatically.

???? or something else ?
