### ISSUE TITLE
Allow barostat temperature to be set via Context parameter, like pressure is

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#324]
If one wants to change the temperature and pressure of a simulation involving a `System` object with a `MonteCarloBarostat`, we can change the `pressure` on the fly via

``` python
parameter_name = barostat.Pressure() 
context.setParameter(parameter_name, pressure)
```

but the temperature used by the barostat must be changed via 

``` python
barostat.setTemperature(thermodynamic_state.temperature)
```

which changes the serialized representation of the `System` object.

It would be useful if both temperature and pressure can be set via Contex global parameters.

See OpenMM feature tracker:
https://simtk.org/tracker/index.php?func=detail&aid=1979&group_id=161&atid=436

**Comment by jchodera** [comment]
This would still be useful!

**Comment by jchodera** [comment]
cc: #1440

**Comment by peastman** [comment]
We now support this.
