### ISSUE TITLE
Alchemical/Relative free energy calculation for Protein-ligand interaction

### ISSUE THREAD

**Issue by Oulfin** [openmm/openmm#3243]
Dear OpenMM team,

I would like to run free energy simulation with protein-ligand interaction with your MD engine, but I could not find a proper tutorial or information related to that.

Could you provide any information where one can find a recent tutorial or information? It can also be a paper showing which tools can be used in OpenMM to perform these kind of simulations.

Great job with OpenMM! Thanks for all the effort.

**Comment by egallicc** [comment]
Look at [Yank](http://getyank.org/) and [Siremol](https://www.siremol.org/tutorials/ligandswap/), which are based on OpenMM. The [ATMMetaForce OpenMM plugin](https://github.com/Gallicchio-Lab/openmm-atmmetaforce-plugin)  is also available for both absolute and relative alchemical binding free energy calculations.

**Comment by peastman** [comment]
Closing this since the question was answered.
