### ISSUE TITLE
Restarting and PDB 'CONECT' records

### ISSUE THREAD

**Issue by Dan-Burns** [openmm/openmm#3245]
Hello,

Sorry if this has been addressed somewhere already.

When I initially made my system, I had to modeller.add() the separate structures (thank you, John).

I am restarting my simulation now from a serialized system.  At the end of the first part of the simulation I wrote out a PDB file to use as my input topology and positions for the restart.

This PDB written by openmm has incorrect CONECT records so I am unable to use it to generate a topology.  I have to create the topology again by running all the modeller.add() lines.

I'm wondering why are the CONECT records needed if the forcefield defines all the bonds?

Also despite having a serialized system and a checkpoint file that contains the positions, I still have to make the topology from a structure file because I can't create a Simulation() without it to use for simulation.loadCheckpoint().

Is there some way of having the entire simulation saved with topology and positions to make restarting easier? 

Thank you,

Dan

**Comment by peastman** [comment]
> This PDB written by openmm has incorrect CONECT records

In what way are they incorrect?

> I'm wondering why are the CONECT records needed if the forcefield defines all the bonds?

The topology and force field both need to define the bonds.  That's part of how it figures out what force field parameters to use for each residue.  See http://docs.openmm.org/latest/userguide/application/05_creating_ffs.html#basic-concepts for an explanation.

> Is there some way of having the entire simulation saved with topology and positions to make restarting easier?

We have a feature request to make Topology and other Python objects serializable.  https://github.com/openmm/openmm/issues/1543.  In the mean time, pickle is probably your best bet.  It's far from an ideal serialization mechanism.  For example, it isn't compatible between different Python versions.  But for your purpose of saving and restarting simulations, it would probably be fine.

**Comment by Dan-Burns** [comment]
The modeller object that is created from the separate PDBs and then solvated has fewer bonds than the PDB file that it is written out by Openmm.

I will try the pickle route, thank you.

**Comment by Dan-Burns** [comment]
I realize that I can't properly view my trajectory unless I write out a pdb with the correct bonds.  Do you have any idea what the reason could be for this issue.  

I have a nucleotide that I added lines to the forcfield in order to include a methylation.  I also have a ligand that was parameterized with openmm's gaff template generator.  Neither molecule appears correctly when I try to visualize the pdb that openmm writes out.

**Comment by peastman** [comment]
I don't understand what you're saying.  You first said it doesn't appear correctly when you visualize it (you didn't say with what program), but then you said it does appear correctly in PyMol.  You said you don't need the CONECT lines, but then said they're required.  I don't understand!  Please describe *exactly* what you're doing, step by step, *exactly* what happens when you do it, and how that differs from what you expect to happen.

**Comment by Dan-Burns** [comment]
I create a modeller object from three separate pdb files with modeller.add.  
One contains DNA with a modified nucleotide, one contains a small molecule, and once contains a protein.
I solvate this object and 
`modeller.topology`
returns
`Topology; 6 chains, 34126 residues, 108348 atoms, 74807 bonds`

If I save this as a pdb file and then load it back in:
`test = PDBFile('init.pdb')
test.topology`
I get:
`Topology; 6 chains, 34126 residues, 108348 atoms, 74755 bonds`

I have 52 fewer bonds in this example.  

I think they need to match if I want to use this pdb file for simulation restarts.  

Bonds appear to only be written out for my DNA chain and gaff parameterized small molecule.  Since they don't display correctly if I load the pdb into pymol or nglview, I'm assuming there's something wrong with the CONECT records.

**Comment by peastman** [comment]
I can make a guess about what's happening.  Am I correct that the missing bonds are for the modified nucleotide?  Does the modified nucleotide have a different name to indicate that it's modified, or did you name it as if it were a standard nucleotide?

The PDB spec says that CONECT records should be omitted for standard amino acids, nucleotides, and water.  When writing files, we identify standard residues by name:

https://github.com/openmm/openmm/blob/779400a1e3fdc988e84fa7aed760ac95d81c179c/wrappers/python/openmm/app/pdbfile.py#L407-L409

If my guess is correct, the solution is to change the name of that residue.  Standard residue names should only be used for standard residues.

**Comment by Dan-Burns** [comment]
It has a unique residue name.  It looks like the issue was just that it was labeled as a HETATM instead of ATOM.

Thank you,

Dan

**Comment by peastman** [comment]
The PDB reader in OpenMM doesn't care whether it's labeled as HETATM or ATOM.  It treats it the same either way.

**Comment by peastman** [comment]
Are there any outstanding questions with this issue, or can it be closed?

**Comment by peastman** [comment]
Sorry for not replying sooner.  What exactly do you want me to look at?  Looking at gg-m6a-ct_aligned.pdb, I see lots of CONECT records for residues that are labeled as being standard residues.  See my explanation above (https://github.com/openmm/openmm/issues/3245#issuecomment-923153686).

**Comment by Dan-Burns** [comment]
The issue is when I write out a PDB file from openmm of the complete system and then load it back in as a new system, the number of bonds do not match with the original, correct system.

**Comment by peastman** [comment]
Yes, I explained above why that can happen.
