### ISSUE TITLE
CHARMM-GUI to OpenMM to PDB file to PyMol fails to load correct topology 

### ISSUE THREAD

**Issue by apayne97** [openmm/openmm#3250]
Related to #3245 and #3152 (and perhaps #1543).
I have generated a system using CHARMM-GUI. It's an homodimeric ion channel containing residues 30-476 embedded in POPE and POPG lipids, 150mM KCl, ~30,000 water atoms. ~150,000 atoms total.

When I load the `step5_input.pdb` into PyMol, it looks fine: 
![image](https://user-images.githubusercontent.com/31800806/133689697-b69a1235-245c-4f51-b4bf-30a652f0e34e.png)

But when I use this code to load the system into PyMol, and then write out the PDBFile...
```
filePath = 'testing-saving-topology/'
psf = CharmmPsfFile(filePath + 'step5_input.psf')
pdb = PDBFile(filePath + 'step5_input.pdb')

param_filenames = ['par_all36m_prot.prm', 'top_all36_prot.rtf',
                       'par_all36_lipid.prm', 'top_all36_lipid.rtf',
                       'toppar_water_ions.str']
param_paths = [os.path.join(filePath, file) for file in param_filenames]
params = CharmmParameterSet(*param_paths)

output_path = 'testing-saving-topology/'
pdb_path = output_path + 'before_creating_system.pdb'
print(f"Writing system to {pdb_path}")
with open(pdb_path, "w") as outfile:
    PDBFile.writeFile(
        pdb.topology,
        pdb.positions,
        file=outfile,
        keepIds=True
[input-files.zip](https://github.com/openmm/openmm/files/7181191/input-files.zip)
    )
```

One of the chains disappears, I think because there are no Chain IDs:
![image](https://user-images.githubusercontent.com/31800806/133690349-a2d172e5-2139-4728-9b72-3d4fd1b93e4e.png)

Which makes sense because the topology info in the CHARMM-GUI PDB file alone is insufficient. So, when I generate a system using this code and save the pdb...
```
psf.setBox(12.1, 12.1, 11.1)
## Setting system parameters we will use later
nonbonded_method = app.PME
constraints = app.HBonds
hydrogen_mass = hydrogenMass=4.0 * unit.amu
temperature = 303.15*unit.kelvin
friction = 1/unit.picosecond
time_step = 0.004*unit.picoseconds
pressure = 1*unit.bar
surface_tension = 200*unit.bar*unit.nanometer

## Setting up the system using the psf file
system = psf.createSystem(params, 
                          nonbondedMethod=nonbonded_method, 
                          constraints=constraints,
                          removeCMMotion=False,
                          hydrogenMass=hydrogen_mass
                         )
## Setting the integrator and barostat

integrator = LangevinMiddleIntegrator(temperature,  
                                     friction,
                                     time_step)

barostat = mm.MonteCarloMembraneBarostat(pressure,
                                         surface_tension, 
                                         temperature,
                                         mm.MonteCarloMembraneBarostat.XYIsotropic, 
                                         mm.MonteCarloMembraneBarostat.ZFree
                                        )
barostat.setFrequency(50)    ## for some reason the __init__ won't accept it as an argument, but this works
                            ## the default is 25 timesteps, i've set it for 50
system.addForce(barostat)

simulation = app.Simulation(psf.topology, system, integrator)
simulation.context.setPositions(pdb.positions)
# Save after making system
output_path = 'testing-saving-topology/'
pdb_path = output_path + 'after_creating_system.pdb'


## With Id's
print("Saving %s" % pdb_path)
with open(pdb_path, "wt") as outfile:
    PDBFile.writeFile(
        simulation.topology,
        simulation.context.getState(
            getPositions=True,
            enforcePeriodicBox=True).getPositions(),
            file=outfile,
            keepIds=True
    )
```

The protein topology is recovered but the lipid and water topology is completely out of wack:
![image](https://user-images.githubusercontent.com/31800806/133690768-383f0b9e-7c6b-4fee-92cb-5dc6242b766a.png)

@zhang-ivy has suggested that this is caused by the HETATM ids looping over ID numbers. but @sukritsingh says that he has simulations running that are at least this size without this problem. So what's going on?

Thanks,
Alex

P.S. Input files are provided below

[input-files.zip](https://github.com/openmm/openmm/files/7181204/input-files.zip)

**Comment by peastman** [comment]
When I run the first script above, it produces a file called `before_creating_system.pdb` that looks totally normal as far as I can tell.  Here's a render of it in Chimera.  No chains are missing.

![image](https://user-images.githubusercontent.com/4379786/135177967-92bfab05-7474-41e1-b9a5-8a7bd7a5b3f3.png)

Is there something else I need to do to reproduce the problem?

**Comment by apayne97** [comment]
Ah, well the atoms are there but since there is no chain information contained in the pDB file I think PyMol doesn't know what to do. This doesn't seem to bother Chimera. 

```
REMARK   1 CREATED WITH OPENMM 7.5.1, 2021-09-29
ATOM      1  N   ALA    30      46.026  51.730  32.814  1.00  0.00           N  
ATOM      2  H   ALA    30      46.952  51.776  32.353  1.00  0.00           H  
ATOM      3  H2  ALA    30      45.436  50.994  32.369  1.00  0.00           H  
ATOM      4  H3  ALA    30      46.158  51.508  33.825  1.00  0.00           H  
ATOM      5  CA  ALA    30      45.362  53.052  32.671  1.00  0.00           C  
ATOM      6  HA  ALA    30      45.228  53.251  31.620  1.00  0.00           H  
ATOM      7  CB  ALA    30      44.018  53.023  33.397  1.00  0.00           C  
```

**Comment by apayne97** [comment]
In any case, the main problem follows next. This is what `after_creating_system.pdb` looks like when I open it in Chimera:
![image](https://user-images.githubusercontent.com/31800806/135298610-724d7e5f-c04e-43ad-97c4-5876f474c614.png)

**Comment by peastman** [comment]
If you remove the argument `keepIds=True` when writing the file, OpenMM will assign proper chain ids.

**Comment by peastman** [comment]
I think your PDB and PSF files don't match each other?  Either that, or something is causing it to produces a messed up Topology from the PSF file.  `after_creating_system.pdb` looks messed up for me too.  But if I pass `pdb.topology` instead of `psf.topology` to the Simulation constructor, then it looks fine.

**Comment by apayne97** [comment]
Yes, that works!! Wow. If I pass `pdb.topology` and then save with `keepIds=True` the system looks good!
Then i can serialize as before and reload like so:
```
## Load System from XML Files
output_prefix = 'output/'
integrator_xml_filename = "minimized-integrator.xml"
state_xml_filename = "minimized-state.xml"
system_xml_filename = "minimized-system.xml"

pdb = PDBFile(output_prefix + 'minimized.pdb')
systemFile = output_prefix+system_xml_filename
intFile = output_prefix+integrator_xml_filename
stateFile = output_prefix+state_xml_filename

sim = app.Simulation(pdb.topology, 
                     system=systemFile, 
                     integrator=intFile,
                     state=stateFile
                     )

# Save serialized system
output_path = 'output/'
file_name = 'after_serializing_system'
pdb_path = output_path + file_name + '.pdb'


print("Saving %s" % pdb_path)
with open(pdb_path, "wt") as outfile:
    PDBFile.writeFile(
        sim.topology,
        sim.context.getState(
            getPositions=True,
            enforcePeriodicBox=True).getPositions(),
            file=outfile,
            keepIds=True
    )
```
![image](https://user-images.githubusercontent.com/31800806/135310523-fa1646f0-18bd-4234-b157-9135e365c039.png)

**Comment by apayne97** [comment]
So for some reason using the PDB topology but not the psf topology works. Thank you so much!

**Comment by peastman** [comment]
I think I understand what's going on.  Paradoxically, the Topology from the PSF file is really the correct one.

`step5_input.pdb` contains no CONECT records.  That makes it incorrect, since you need to specify the bonds within the lipids.  Without that, you don't know which atoms are bonded to each other.  But most visualizers will automatically infer bonds based on distances, so it still looks correct when you load it into Chimera.

The Topology created from the PSF file does contain bonds, and when you write it to a PDB file CONECT records get written for them.  At that point, you run into the problem that @zhang-ivy pointed out: the IDs wrap around.  The PDB spec doesn't permit a single file to have more than 99,999 atoms.  Since your file does, you end up with multiple atoms that have the same ID, and that makes the bonds ambiguous.  For example, it includes the line

```
CONECT1423214231
```

That's a bond between atoms 14232 and 14231.  Those atoms are part of a lipid:

```
HETATM14231  N   POP C   1      21.635  73.984  76.003  1.00  0.00           N  
HETATM14232  HN1 POP C   1      22.280  74.322  75.266  1.00  0.00           H  
```

But there also are two atoms with the same IDs that are part of water molecules:

```
HETATM14231  H2  HOH D7604     119.121  62.873   5.656  1.00  0.00           H  
HETATM14232  O   HOH D7605     116.502  63.127  13.374  1.00  0.00           O  
```

The visualizer doesn't know which one of those you meant, so it has to guess, or maybe include bonds between both.  That's why you get a messed up visualization.  The simulation is still run correctly though.  The problem is only the interpretation of the output file.  The best solution is probably to write a PDBx/mmCIF file instead of a PDB file.  It doesn't have the limitation on number of atoms.

**Comment by apayne97** [comment]
I was just exploring this as well and discovered part of what you did - that the psf actually has the correct info.
If I load the simulation using a pdb vs the psf topology, the number of bonds is drastically different:
```
simpsf.topology
<Topology; 5 chains, 31578 residues, 151884 atoms, 121378 bonds>

simpdb.topology
<Topology; 5 chains, 31578 residues, 151884 atoms, 74566 bonds>
```

I think this is because it is missing all of the lipid bonds (chainId 2)
```
pdb, psf = allchains[2]
pdbresidues = [residue for residue in pdb.residues()]
psfresidues = [residue for residue in psf.residues()]

psfresidues[300]
<Residue 1194 (POPG) of chain 2>

pdbresidues[300]
<Residue 1194 (POP) of chain 2>

pdbbonds = [bond for bond in pdbresidues[300].bonds()]   ## This is a POPG
psfbonds = [bond for bond in psfresidues[300].bonds()]


pdbbonds
[]

psfbonds
[Bond(<Atom 51880 (HO3) of chain 2 residue 1194 (POPG)>, <Atom 51879 (OC3) of chain 2 residue 1194 (POPG)>),
 Bond(<Atom 51879 (OC3) of chain 2 residue 1194 (POPG)>, <Atom 51876 (C13) of chain 2 residue 1194 (POPG)>),
 Bond(<Atom 51876 (C13) of chain 2 residue 1194 (POPG)>, <Atom 51877 (H13A) of chain 2 residue 1194 (POPG)>),
...]
```

So I will try loading using the PSF file and save as a PDBx/mmCIF file.

**Comment by apayne97** [comment]
A problem with this is that while OpenMM can read and write mmCIF files, it looks like MDAnalysis and MDTraj cannot. I'm not sure what to do about that. I suppose that I could write out the protein, membrane, ion, and solvent coordinates to separate PDB files, load them, and then combine them?

**Comment by peastman** [comment]
You could load the file with OpenMM and then use `Topology.from_openmm()` to convert it to a MDTraj topology.  I don't know if MDAnalysis has something similar.

**Comment by apayne97** [comment]
You're a legend. thank you!

**Comment by apayne97** [comment]
For posterity:

```
traj_path = "../../complete-open-models/20210913-system04/output/equil_and_prod_combined.dcd"
top_path = "input/step5_input.psf"
t = md.load_dcd(traj_path, top=top_path)

pdb_path = 'output/after_serializing_system.cif'
pdb = PDBxFile(pdb_path)

psfbonds = [bond for bond in t.topology.bonds]
pdbbonds = [bond for bond in pdb.topology.bonds()]

print(f'PSF: {len(psfbonds)} \t PDB: {len(pdbbonds)}')
          PSF: 151458 	 PDB: 121378
```

Here, the `PDB` number is correct, or at least is the number of bonds that openmm gets from the psf file.

To fix the topology for MDTraj
```
new_top = oldt.topology.from_openmm(pdb.topology)
t.topology = new_top

ibonds = [bond for bond in t.topology.bonds]
print(f'MDTRAJ Bonds: {len(ibonds)} OpenMM Bonds: {len(pdbbonds)}')
MDTRAJ Bonds: 121378 OpenMM Bonds: 121378
```

Thanks for all your help!

**Comment by peastman** [comment]
Glad that worked so easily!

**Comment by apayne97** [comment]
Linking @rafwiewiora's issue for MDTraj since it is relevant: https://github.com/mdtraj/mdtraj/issues/652
