### ISSUE TITLE
applying multiple energy minimization for protein-protein interaction 

### ISSUE THREAD

**Issue by AhmetGG** [openmm/openmm#3254]
Hi,I would like to employ multiple energy minimization, such as steepest-decent minimization for 500 steps and  Newton-Raphson minimization for 1000 steps in one simulation. Since most protein-protein interaction protocols are did multiple minimizations. But in openmm, only I have only one chance to minimize. How can I do this energy minimization in openMM. Is ıt enough to write 'simulation.minimizeEnergy(1500)'. I know opemm employs a different algorithm for energy minimization.

**Comment by peastman** [comment]
Can you describe what you're trying to accomplish?  OpenMM uses L-BFGS, which is a pretty efficient algorithm.  You give it a tolerance, and it will continue to minimize until the magnitude of the force drops below that tolerance.  Unless you have a special reason for needing something different, you can just call `minimizeEnergy()` once.

**Comment by AhmetGG** [comment]
Thank you so much for replying. I mean I am working on a refinement of protein-protein interaction. Most of the existing protocol has been employed different energy minimization in series, in different simulation programs. I wonder for openmm, is it enough to apply only minimization command for such a protocol.

**Comment by peastman** [comment]
`minimizeEnergy()` finds a local minimum (it doesn't guarantee which one it will find) and localizes it to the specified accuracy.  If that's what you want, then yes it's sufficient.  If that isn't what you want, then can you describe what you do want?
