### ISSUE TITLE
Incorrect non-bonded energy with CHARMM FF

### ISSUE THREAD

**Issue by charmm-gui** [openmm/openmm#3257]
I conducted a single point energy comparison between CHARMM and OpenMM with a simple test system containing a single cholesterol molecule ([test_chl1.tar.gz](https://github.com/openmm/openmm/files/7220567/test_chl1.tar.gz)).

(unit: kcal/mol)  | CHARMM | OpenMM
-- | -- | --
Bond | 3.4090 | 3.4089
Angle | 16.2683 | 16.2683
Urey-Bradly | 2.3382 | 2.3382
Dihedral | 16.8157 | 16.8156
Improper | 0.0000 | 0.0000
vdW 1-4 | 6.5306 | 6.1477
vdW | -3.4140 | -3.4140
vdW Total | 3.1166 | 2.7337
Elec. 1-4 | -44.0315 | -
Elec. | -15.1082 | -
Elec. Total | -59.1397 | -46.7842

As shown above, while bonded energies are identical between CHARMM and OpenMM, non-bonded energies are different.
The energy difference in vdW 1-4 came from the NBFIX, i.e. if NBFIX parameter is available for a certain 1-4 atom type pair, the corresponding NBFIX parameter should be used.
However, this doesn't seem to be implemented in `createSystem` function in `CharmmPsfFile` class.

https://github.com/openmm/openmm/blob/779400a1e3fdc988e84fa7aed760ac95d81c179c/wrappers/python/openmm/app/charmmpsffile.py#L1383-L1390

For electrostatic interaction, I have no idea what is causing the difference.

Could you please check this case?

For non-bonded interaction, I used the hard-truncation with 12 Å cut-off without PBC (CutoffNonPeriodic).

**Comment by peastman** [comment]
I think you're correct about vdw: it isn't using the NBFIX rules when computing 1-4 pairs.

For electrostatics, I don't think the two cases are using the same functional form.  The documentation at https://hpc.nih.gov/apps/charmm/c42b2html/nbonds.html isn't very clear, but I think your settings correspond to a sharp cutoff at 12A?  Whereas OpenMM is using reaction field to smoothly cut it off.

**Comment by charmm-gui** [comment]
Is there any way to use hard truncation (sharp cutoff) for electrostatic in OpenMM?

**Comment by peastman** [comment]
Not with NonbondedForce.  You could implement it with CustomNonbondedForce if you really wanted it.  (But you really shouldn't.  Sharp cutoffs on Coulomb produce huge errors.)

**Comment by charmm-gui** [comment]
I wanted the hard-truncation just for energy comparison purpose, not for actual simulation.
Each program uses different algorithm / implementation, so the hard truncation makes it easier to check the non-bonded energy as the implementation of hard-truncation will be the same throughout the simulation programs.
I will try to compare the electrostatic energy with different cutoff method.

**Comment by jchodera** [comment]
@peastman: Doesn't `NonbondedForce` do hard-truncation when `nonbondedMethod=CutoffPeriodic` and the reaction field dielectric is set to 1?

**Comment by charmm-gui** [comment]
I tried `setReactionFieldDielectric(1.0)` but it still gives different energy.
CHARMM: -59.1397
OpenMM: -50.45485223

I also tried NoCutoff, which still gives slightly different energy:
CHARMM: -58.89917
OpenMM: -58.89777654

**Comment by jchodera** [comment]
Ah---OpenMM still subtracts off the energy at the cutoff for `CutoffPeriodic`, I think. I don't think there's a way to override that (as @peastman suggests). 

The energy discrepancy with `NoCutoff` is somewhat small (but not as small as we might hope). Is this with the `Reference` platform, which uses double precision?

**Comment by peastman** [comment]
NoCutoff is a good one to focus one, since there's not much ambiguity in that case.  A first thing I would check is whether they're using different values for physical constants, particularly epsilon_0.  The values used by OpenMM are defined in https://github.com/openmm/openmm/blob/master/platforms/reference/include/SimTKOpenMMRealType.h.

**Comment by charmm-gui** [comment]
@jchodera Yes, I used `Reference` platform.

As far as I know, CHARMM uses 332.0716 for 1/(4\*pi\*e0).
For OpenMM, I got 332.0637133 for 1/(4\*pi\*e0) from the values in https://github.com/openmm/openmm/blob/master/platforms/reference/include/SimTKOpenMMRealType.h,

So, calculated sum of q<sub>i</sub>q<sub>j</sub>/r<sub>ij</sub> are:
CHARMM: -58.89117 / 332.0716 = -0.177368886710
OpenMM: -58.89777654 / 332.0637133 = -0.177368902958

It still shows a slight difference, but I guess, it is acceptable range?

**Comment by peastman** [comment]
The relative difference between those is about 1e-7, which is just barely larger than machine epsilon in single precision.  If any part of the calculation in either program is being done in single precision, that's as good agreement as you could ask for.

**Comment by charmm-gui** [comment]
OK. Thank you for your help!
Please let me know once you fixed the vdW 1-4 issue.

**Comment by swails** [comment]
Is this also an issue with ParmEd's CHARMM system generator?

**Comment by charmm-gui** [comment]
I haven't tried ParmEd, but it does seem like this issue exists also in ParmEd.
In CHARMM FF, there could be two NBFIX parameters: one for general non-bonded interaction and the other for 1-4 specific.
https://academiccharmm.org/documentation/latest/parmfile

For example,
NBFIX
      H    O   -0.30  1.50   -0.15  1.50

First two parameters are epsilon and Rmin for NBFIX of atom type pair H and O.
Remaining two parameters are epsilon and Rmin for NBFIX of 1-4 pair interaction.
However, in most cases, NBFIX parameters omit the second parameter set.

NBFIX
      H    O   -0.30  1.50

In such a case, the first NBFIX parameter set is being used for 1-4 interaction.

ParmEd appears to try to use second parameter set for 1-4 interaction, but it doesn't attempt to use the first parameter set if second set is omitted.
https://github.com/ParmEd/ParmEd/blob/0f733a4a690533bf949643bfb67ecff9ff65ff9f/parmed/structure.py#L2608-L2617

**Comment by peastman** [comment]
Thanks for clarifying that.  I hadn't realized it could define separate parameters for 1-4.  How does that interact with `E14FAC`?  The documentation doesn't mention.  Should I assume the following?

- If there is only one set of parameters, use those values and multiply by `E14FAC`.
- If there are two sets of parameters, use the second set and do *not* multiply by `E14FAC`.

**Comment by charmm-gui** [comment]
E14FAC is for electrostatic interaction, it does not related to NBFIX.

**Comment by peastman** [comment]
Does that mean CHARMM never applies any scaling to 1-4 LJ interactions?

**Comment by charmm-gui** [comment]
Correct. Instead, it has atom type specific 1-4 parameter.

**Comment by peastman** [comment]
Ok, thanks.

**Comment by swails** [comment]
I think ParmEd does the correct thing, then.  If the second set isn't specified, it is just copied from the first set:

https://github.com/ParmEd/ParmEd/blob/0f733a4a690533bf949643bfb67ecff9ff65ff9f/parmed/topologyobjects.py#L5081-L5083

**Comment by charmm-gui** [comment]
Oh, I missed that part.
Yes, it does seem to do correct thing.

**Comment by peastman** [comment]
The fix is in #3324.
