### ISSUE TITLE
Low cpu usage 

### ISSUE THREAD

**Issue by diallobakary4** [openmm/openmm#3267]
I'm running openmm on a 324 residues protein. The 32 CPUs (Intel(R) Xeon(R) CPU @ 2.30GHz) don't seem to be used efficiently. The rarely attend 50% utilization. I'm running on CPU platform. The performance is about 50ns/day. 
 
![image](https://user-images.githubusercontent.com/13533717/136006979-fff9a2fb-b2df-4a7b-bb04-262188d76d49.png)

Here is sample code of the system creation.
```
system = forcefield.createSystem(pdb.topology,  hydrogenMass=4*amu,  nonbondedMethod=PME, =1*nanometer,
                                            constraints=AllBonds)
integrator = LangevinIntegrator(300*kelvin, 1/picosecond, 0.005*picoseconds)
```
Can the small system size cause parallelization issues?

**Comment by peastman** [comment]
The CPU platform in OpenMM doesn't scale very well to large numbers of cores.  In fact, beyond about 16 cores it can sometimes get slower when adding more threads.  I would try limiting the number of threads (by setting the `OPENMM_CPU_THREADS` environment variable) and see what gives the best performance.
