### ISSUE TITLE
How to ideal residue "HEM" of complicated  hemoglobin when MD??

### ISSUE THREAD

**Issue by ABChh26** [openmm/openmm#3271]
When I do molecular dynamics simulation of heme protein in openmm, It always remind me of the lack of hydrogen atoms, but 
HEM exist in the form of deprotonation，after PDBFixer is also useless!
Here is the wrong message:
ValueError: No template found for residue 496 (HEM).  The set of atoms is similar to HEME, but it is missing 30 hydrogen atoms.

**Comment by peastman** [comment]
The cookbook entry is had been added.
