### ISSUE TITLE
How to reproduce standard nonbonded force as a custom nonbonded force?

### ISSUE THREAD

**Issue by aizvorski** [openmm/openmm#3281]
I'd like to make a CustomNonbondedForce which exactly reproduces the standard NonbondedForce.  

Here's my attempt so far:

```
import openmm as mm
import openmm.app as app
import openmm.unit as unit

ff = app.ForceField('amber99sb.xml', 'tip3p.xml')
pdb = app.PDBFile(d+'5dfr_solv-cube_equil.pdb')
method = app.CutoffNonPeriodic
cutoff = 1*unit.nanometers
dt = 4*unit.femtosecond
constraints = app.HBonds
hydrogenMass = 1.5*unit.amu
temperature = 300*unit.kelvin
friction = 1/unit.picoseconds
integrator = mm.LangevinMiddleIntegrator(temperature, friction, dt)
system = ff.createSystem(pdb.topology, 
                         nonbondedMethod=method, 
                         nonbondedCutoff=cutoff, 
                         constraints=constraints, 
                         hydrogenMass=hydrogenMass)    

for force in system.getForces():
    if isinstance(force, mm.NonbondedForce):
        original_nonbonded_force = force

ONE_4PI_EPS0 = 138.935456
energy_expression  = "4*epsilon*((sigma/r)^12 - (sigma/r)^6) + ONE_4PI_EPS0*chargeprod/r;"
energy_expression += "epsilon = sqrt(epsilon1*epsilon2);"
energy_expression += "sigma = 0.5*(sigma1+sigma2);"
energy_expression += "chargeprod = charge1*charge2;"
energy_expression += "ONE_4PI_EPS0 = {:f};".format(ONE_4PI_EPS0)

custom_nonbonded_force = mm.CustomNonbondedForce(energy_expression)
custom_nonbonded_force.addPerParticleParameter('charge')
custom_nonbonded_force.addPerParticleParameter('sigma')
custom_nonbonded_force.addPerParticleParameter('epsilon')
custom_nonbonded_force.setNonbondedMethod(mm.CustomNonbondedForce.CutoffNonPeriodic)
custom_nonbonded_force.setCutoffDistance(cutoff)

for index in range(original_nonbonded_force.getNumParticles()):
    charge, sigma, epsilon = original_nonbonded_force.getParticleParameters(index)
    custom_nonbonded_force.addParticle([charge, sigma, epsilon])
    
for index in range(original_nonbonded_force.getNumExceptions()):
    j, k, chargeprod, sigma, epsilon = original_nonbonded_force.getExceptionParameters(index)
    custom_nonbonded_force.addExclusion(j, k)

energy_expression = "4*epsilon*((sigma/r)^12 - (sigma/r)^6) + ONE_4PI_EPS0*chargeprod/r;"
energy_expression += "ONE_4PI_EPS0 = {:f};".format(ONE_4PI_EPS0)
custom_bond_force = mm.CustomBondForce(energy_expression)
custom_bond_force.addPerBondParameter('chargeprod')
custom_bond_force.addPerBondParameter('sigma')
custom_bond_force.addPerBondParameter('epsilon')

for index in range(original_nonbonded_force.getNumExceptions()):
    j, k, chargeprod, sigma, epsilon = original_nonbonded_force.getExceptionParameters(index)
    custom_bond_force.addBond(j, k, [chargeprod, sigma, epsilon])

system.addForce(custom_nonbonded_force)
system.addForce(custom_bond_force)

original_nonbonded_force.setForceGroup(1)
custom_nonbonded_force.setForceGroup(2)
custom_bond_force.setForceGroup(2)

platform = mm.Platform.getPlatformByName('CPU')
properties = {}
simulation = app.Simulation(pdb.topology, system, integrator, platform, properties)
simulation.context.setPositions(pdb.positions)

energy1 = simulation.context.getState(getEnergy=True, groups=1<<1).getPotentialEnergy()
energy2 = simulation.context.getState(getEnergy=True, groups=1<<2).getPotentialEnergy()

print(energy1)
print(energy2)
```

With CutoffPeriodic, this produces -290114.0585404039 kJ/mol and -312236.9729349502 kJ/mol.  With CutoffNonPeriodic, it produces -245596.8761436086 kJ/mol and -269899.32464117865 kJ/mol.

What accounts for the remaining difference?

Some other questions:
- Is using a CustomBondForce to replicate the exceptions in NonbondedForce the way I have it above correct?  (and/or is this the best way to do it?)
- Is there no way to use PME in a CustomNonbondedForce?
- If there was a system using a NonbondedForce with PME (and a few particles which are made non-interacting as far as that is concerned) plus a CustomNonbondedForce for just those few particles - is there an approximate nonbonded method that can be mixed with PME?  (maybe CutoffPeriodic with some additional settings?)

**Comment by peastman** [comment]
The exact formulas used by NonbondedForce are described in http://docs.openmm.org/latest/userguide/theory/02_standard_forces.html#nonbondedforce.  I believe the main difference in your code is that your CustomNonbondedForce applies a sharp cutoff, while NonbondedForce uses reaction field.

> Is there no way to use PME in a CustomNonbondedForce?

There's no way to implement a custom version of the reciprocal space calculation.  If you're satisfied with the standard version for the reciprocal space calculation, you can use a NonbondedForce, call `setIncludeDirectSpace(false)` on it to disable the direct space part, and use a CustomNonbondedForce to provide a customized implementation.  See #3269 for an ongoing discussion about doing that.

> is there an approximate nonbonded method that can be mixed with PME?

Maybe?  You certainly could do what you described, and it probably would be fine.  I'm just not sure of all the theoretical implications.  You would need to think carefully about exactly what Hamiltonian your potential corresponds to, and convince yourself it's a physically reasonable approximation.

**Comment by aizvorski** [comment]
@peastman Thanks!  

Okay, second try, adding reaction field:

```
eps_solvent = original_nonbonded_force.getReactionFieldDielectric()
krf = (1/ (cutoff**3)) * (eps_solvent - 1) / (2*eps_solvent + 1)
crf = (1/ cutoff) * (3* eps_solvent) / (2*eps_solvent + 1)
original_nonbonded_force.setUseDispersionCorrection(False)
...
energy_expression  = "4*epsilon*((sigma/r)^12 - (sigma/r)^6) + ONE_4PI_EPS0*chargeprod*(1/r + krf*r*r - crf);"
energy_expression += "krf = {:f};".format(krf.value_in_unit(unit.nanometer**-3))
energy_expression += "crf = {:f};".format(crf.value_in_unit(unit.nanometer**-1))
...
```

With CutoffPeriodic, this is near exact: -288540.8713446002 kJ/mol and -288540.90938102454 kJ/mol.    (Also the original version was near exact with NoCutoff).

To get it to match, in addition to reaction field, I also had to add `original_nonbonded_force.setUseDispersionCorrection(False)` otherwise there was still a pretty large difference.  I could try reproducing that term in the custom force as well.  Is the dispersion correction calculated as an average over particles closer than the cutoff only?  (the theory section says "represents an average over all pairs of particles in the system")

Thanks for the pointer to `setIncludeDirectSpace(false)`, that's super useful. 

One last clarification - is it possible to turn the reaction field term off in the original nonbonded force?  It seems from the formulas that setReactionFieldDielectric(1) would make krf = 0 but it still leaves crf = 1/cutoff.  I assume PME + reaction field doesn't make sense, so is reaction field turned off somehow when PME is on?

**Comment by peastman** [comment]
> If it is over all particles, how often is it recalculated?

It's an analytic approximation.  It just adds a fixed energy equal to a coefficient divided by the box volume.  Calculating the coefficient is expensive, since it involves integrals over all pairs of atom types in the system.  That's done when you create the context.  After that, it's negligible work on each step.

>  How would one turn off RF in the normal nonbonded force without using PME?

By using a CustomNonbondedForce instead?  No one should ever use a sharp cutoff for Coulomb, so NonbondedForce doesn't give you the option.
