### ISSUE TITLE
the theory and mathematical equation behind getPotentialEnergy()

### ISSUE THREAD

**Issue by baoxingsong** [openmm/openmm#3282]
I guess this is a stupid question since I am new to this field.
I tried to read through the online document and played with it with python code.
But I did not understand how is getPotentialEnergy() calculated. The Part III of the online document gives a lot of theories and I did not find the exact equation clearly saying this one is used to calculate Potential Energy.

Could you share anything for me to learn about the theory about Potential Energy, please?

**Comment by peastman** [comment]
That depends on your System, and what Force objects it contains.  Each Force object adds a contribution to the potential energy.  Those are described in the documentation.  [This section](http://docs.openmm.org/latest/userguide/library/01_introduction.html#the-openmm-public-api) in particular might help.

**Comment by baoxingsong** [comment]
Thanks so much for the quick reply.

I am looking into the AlphaFold2 code:


```
  force_field = openmm_app.ForceField("amber99sb.xml")
  constraints = openmm_app.HBonds
  system = force_field.createSystem(
      pdb.topology, constraints=constraints)
  if stiffness > 0 * ENERGY / (LENGTH**2):
    _add_restraints(system, pdb, stiffness, restraint_set, exclude_residues)

  integrator = openmm.LangevinIntegrator(0, 0.01, 0.0)
  platform = openmm.Platform.getPlatformByName("CPU")
  simulation = openmm_app.Simulation(
      pdb.topology, system, integrator, platform)
  simulation.context.setPositions(pdb.positions)

  ret = {}
  state = simulation.context.getState(getEnergy=True, getPositions=True)

```

Following this, I also looked into the amber force fields equation. But as far as I could understand the amber equation always generate positive values. While openmm gives negative values.

So I think I am must understanding something incorrectly.

**Comment by baoxingsong** [comment]
Thanks for the patient explanation, I think I got the point.
Thanks again.
