### ISSUE TITLE
How to track energy balance with thermostats/barostats?

### ISSUE THREAD

**Issue by aizvorski** [openmm/openmm#3285]
I'd like to track the net energy going to/from the thermostat (eg LangevinIntegator) and barostat (eg MonteCarloBarostat) in a system.  Is there any way using the current API to accomplish this?  If not, where's the best place to patch that in?

I think at least the barostat part of that may be of general interest - perhaps the API could add functions to query the most recent move's delta-E, delta-V and whether the move was accepted or rejected.  I'm not sure how to do the equivalent with a thermostat (esp thermostat built into an integrator).

**Comment by peastman** [comment]
If all the forces in your system are conservative, then any change in energy must be due to the thermostat and barostat.  Check the total energy, then check it again at some later time.  The difference gives you the energy added or removed by the thermostat and barostat.  Do you need something more than that?  If so, could you explain in more detail what you want to do?

**Comment by peastman** [comment]
You should be able to do it efficiently with CustomIntegrator.  The [API docs](http://docs.openmm.org/latest/api-c++/generated/CustomIntegrator.html) give code for a CustomIntegrator that implements the same algorithm as LangevinMiddleIntegrator.  You should be able to modify it to add the tracking.  Remember that variables like `f` and `x` represent the forces and positions *at that particular point*.  Any operation that can change the positions (including `addConstrainPositions()` and `updateContextState()`) will cause the value of `f` to change.  You might want to copy the forces into a separate variable to be sure you use a single value throughout the step.

Notice that the algorithm involves two half step updates to the positions.  Velocity randomization happens in between, so they use slightly different velocities.

> work += np.sum(np.norm(np.dot(forces, velocities)))

Work is force\*distance, not force\*velocity.

**Comment by aizvorski** [comment]
@peastman That's a great pointer, thanks - I didn't know how to write a custom integrator.

Would something like this work for an energy-tracking LangevinMiddleIntegrator?

```
integrator.addGlobalVariable("energy_flow", 0) # not sure if this needs to be added for a compute sum
...
integrator.addComputePerDof("x", "x + 0.5*dt*v")
integrator.addComputePerDof("v_previous", "v")
integrator.addComputePerDof("v", "a*v + b*sqrt(kT/m)*gaussian")
integrator.addComputeSum("energy_change", "m*(v*v*2 - v_previous*v_previous*2)/2")
integrator.addComputePerDof("x", "x + 0.5*dt*v")
...
while True:
    integrator.step()
    energy_change = integrator.getGlobalVariableByName("energy_change")
```

**Comment by aizvorski** [comment]
Thanks @peastman !
