### ISSUE TITLE
Openmm installation on cluster

### ISSUE THREAD

**Issue by synjon-symthe** [openmm/openmm#3287]
I am trying to install openmm on our cluster using instructions on 
http://docs.openmm.org/latest/userguide/application/01_getting_started.html#installing-openmm
After I run 
conda install -c conda-forge openmm

I tried 
python -m openmm.testInstallation

I get cannot Import name error.

I see the following files in /home/synjon/miniconda3

./include/openmm
./pkgs/openmm-7.6.0-py39h9717219_0/include/openmm
./pkgs/openmm-7.6.0-py39h9717219_0/lib/python3.9/site-packages/simtk/openmm
./pkgs/openmm-7.6.0-py39h9717219_0/lib/python3.9/site-packages/openmm
./pkgs/openmm-7.6.0-py39h9717219_0/share/openmm
./lib/python3.9/site-packages/simtk/openmm
./lib/python3.9/site-packages/openmm
./share/openmm

Do I have set some path based on these files or does the installation test check have to done in some specific directory?

It would help to have some of these comments/notes on the installation page.

Thanks
synjon

**Comment by peastman** [comment]
Could you try running the following two commands and post the output?

```
which python
python -c "import openmm"
```

**Comment by j-wags** [comment]
Hi @synjon-symthe,

It looks like the environment for your terminal session may be getting some paths from your locally installed conda at `/home/synjon/miniconda3`, but some other paths from the system-wide conda install in ` /gpfs/anaconda3/`. 

You may be able to fix this by running `source /home/synjon/miniconda3/etc/profile.d/conda.sh` and then `conda activate base`. The first command should fix your conda paths to use only things from the locally installed conda in `/home/synjon/miniconda3`, and the second will put you into the `base` conda environment where you probably installed openmm. 

It's possible that, if you weren't doing this before, the openmm install could be wrong, so you may need to reinstall openmm to make it work. Also, if the above two steps work, you will need to run those at the beginning of each new terminal session where you want to use your locally-installed conda.

**Comment by peastman** [comment]
It looks like you successfully installed OpenMM in the Python at /gpfs/anaconda3/2020.11/bin/python.  The command `import openmm` ran without an error.  The question is which Python you want to be using.

**Comment by peastman** [comment]
Did you figure it out?
