### ISSUE TITLE
Running Amber20 benchmarks

### ISSUE THREAD

**Issue by synjon-symthe** [openmm/openmm#3291]
After downloading the benchmark tar file from
https://ambermd.org/GPUPerformance.php

If one wants to run the single core cpu cases, should one do
./runBenchmarks.sh  -NGPU 0, -NCORE 0

Are there any notes on how to run just one set of the DHRF case shown on 
https://openmm.org/benchmarks
say the Implicit 2fs case?
Thanks
synjon

**Comment by peastman** [comment]
Those benchmarks are generated with the benchmark.py script found in the examples directory.  To get a full description of the options, run

```
python benchmark.py --help
```

To run a single DHFR benchmark, you might run

```
python benchmark.py --platform=CUDA --test=pme --seconds=30
```

**Comment by jchodera** [comment]
@synjon-symthe : Are you asking how you can manually convert then input files within the Amber20 benchmarks suite---meant to be run with the Amber20 `pmemd` executable---with OpenMM, a completely separate MD engine? If so, you'll need to do quite a bit of conversion:
1. The `runBenchmarks.sh` script would need to be rewritten, likely in Python, to load in the appropriate files, interpret the Amber Fortran namelist mdin files into equivalent configurations for OpenMM, and run and benchmark calculations
2. While the prmtop files provided are all readable by `simtk.openmm.app.AmberPrmtopFile`, the input coordinates are in Amber NetCDF format, which I don't believe OpenMM supports yet. You'd need to use one of the AmberTools tools to convert these into either old-style text Amber `inpcrd` or PDB files for input.

**Comment by synjon-symthe** [comment]
Thanks Peter and John.
I want to run the DHFR case shown in https://openmm.org/benchmarks - just to see what kind of speedup i can get on a GPU compared to a CPU.  I thought I would have to download the required files from Joint Amber/Charmm link and then run those benchmarks.
From reading Peter's comments it looks like it is much simpler to do and can be accomplished by running something like 
python benchmark.py --platform=CUDA --test=pme --seconds=30 
in the examples folder.

I will give it a try.  Thank you very much for your prompt responses.
This file is in miniconda3/share/openmm/examples directory

**Comment by aizvorski** [comment]
@synjon-symthe Amber benchmarks can already be used automatically from openmm's examples/benchmark.py script, just run it like this:

```python benchmark.py --test=amber20-dhfr```

This automatically downloads and unpacks the benchmark suite from Amber's website, please have a look at `downloadAmberSuite()` in benchmark.py.  All the available amber-* tests are listed with `python benchmark.py --help`

I may be misunderstanding the question, but it seems that the thing you're asking about is already available and automated in the standard benchmark script.  If you're trying to do something other than that, could you please explain what you're trying to do?

**Comment by peastman** [comment]
I'm closing this since I think all questions have been answered.
