### ISSUE TITLE
Why should we care about potential energy, but not entropy?

### ISSUE THREAD

**Issue by baoxingsong** [openmm/openmm#3294]
Hi, I am thinking to integrate the protein structure analysis with quantitative genetics analysis. To do that, I am trying to understand folding energy better.

May I ask another stupid question, please?

When using the openmm, we use the minimizeEnergy() function to "perform a local energy minimization". I guess that is local **potential** energy minimization, as far as I could understand.
I am wondering why we should care about **potential** energy but not **free** energy here, please? 
In another word, for protein structure energy analysis, for what kind of analysis should we care about potential energy? And when should we care about free energy.
Are there any functions implemented in openmm to calculate entropy, please?

Any reference paper or book could help me to understand this better, please?

**Comment by DanielWicz** [comment]
> Thanks so much for the reply. I have been reading books and related papers, but still could not understand those concepts/equations very well. I could not understand why in openmm, the energy is called potential energy? And why in the Rosetta, they call their energy free energy? I did not see a fundamental difference between the rosseta equations and AMBER equations. Rosetta does have an entropy term in its equation.
> 
> I am looking for an approximation for the protein activities of plant natural population alleles, via the protein folding approach. And I would like to associate this protein activity approximation with plant traits. Looks the protein stability is a good approximation for protein activity.
> 
> There might be multiple amino acid mutations and even indel variants among plant protein natural alleles. Foldx, DynaMut etc only deal with amino acid alternatives but not indels, so they would do not work.
> 
> The AlphaFold2 is calling the openmm library to output the final structure prediction, so I read the openmm documents and the AMBER99SB carefully.
> 
> I guess I need to compare the free energy between the unfold state and fold states to calculate delta G for each allele. And compare the delta Gs among those alleles. Do you have any suggestions for how to do that, please?
> 
> Do you have any suggestions/comments on how to perform protein stability comparison, please?

I think OpenMM's github is more for the technical problem of the OpenMM than general question about nature of the protein folding and MD simulations. OpenMM as it, is a framework to perform MD simulation and accelerate it (OpenMMTools from @jchodera). 
For more general questions regarding science in general I'd recommend you to use ResearchGate and OpenMM leave as a building block for your computational experiments.

**Comment by apayne97** [comment]
@baoxingsong so can we close this issue?
