### ISSUE TITLE
nvcc compiler in PATH not found

### ISSUE THREAD

**Issue by ijpulidos** [openmm/openmm#3302]
I recently stumbled upon the following error when using the nightly `conda-forge` build of `openmm`.

```bash
  File "simple_nan_test.py", line 11, in <module>
    context = Context(system, integrator, platform)
  File "/home/user/miniconda3/envs/openmm-dev/lib/python3.8/site-packages/openmm/openmm.py", line 13130, in __init__
    _openmm.Context_swiginit(self, _openmm.new_Context(*args))
openmm.OpenMMException: Error launching CUDA compiler: 32512
```
Even though `nvcc` is  in the `PATH`. This is only happening with the nightly version, previous versions (7.5.1 and 7.6.0) do not have the issue.

**Comment by raimis** [comment]
I don't set `OPENMM_CUDA_COMPILER`, but I get that `CudaCompiler` is set by default:
```python
import openmm
from openmm import Platform

print(openmm.__version__)

p = Platform.getPlatformByName('CUDA')
print(p.getPropertyDefaultValue('CudaCompiler'))
```
```
7.6
/usr/local/cuda/bin/nvcc
```
I would expect to see:
```
7.6
None
```

**Comment by peastman** [comment]
That behavior is correct.  That's the default location it will try if it can't load the runtime compiler.  It will still try to use the runtime compiler first.

**Comment by raimis** [comment]
How to set `CudaCompiler`, if I want to disable `nvcc` completely?

**Comment by peastman** [comment]
How do you mean?  It only uses nvcc if you tell it to, or if it can't load nvrtc.

**Comment by raimis** [comment]
In OpenMM 7.5, it was possible to set `CudaCompiler` to `''` (empty string) and that guaranteed that the default `nvcc` won't be used.

OpenMM 7.6 doesn't allow to set `CudaCompiler` to `''`.

**Comment by peastman** [comment]
That's because it used to default to nvcc, but now it defaults to nvrtc.  You could call `setPropertyDefaultValue("CudaCompiler", "")`.  That will guarantee that if it tries to fall back to nvcc it will fail.

**Comment by jchodera** [comment]
Did we get this issue fully resolved? It would be useful to have a way to robustly avoid the experience of having users run into `openmm.OpenMMException: Error launching CUDA compiler: 32512` for slight CUDA misconfigurations.

**Comment by ijpulidos** [comment]
I don't really know if this is the expected behavior, but while trying to test my locally build Openmm (7.6 release from source) I am getting the following error for all of the Cuda tests (example is just one of them)
```bash
❯ ./TestCudaVerletIntegrator
exception: Error launching CUDA compiler: 32512
sh: line 1: /usr/local/cuda/bin/nvcc: No such file or directory
```
Of course if I set up `OPENMM_CUDA_COMPILER` to point to my local nvcc it works. But I wonder why this isn't using `nvrtc` and why something like testing the installation from the python API works, as follows (without having to define any env variable)
```
❯ python -m openmm.testInstallation

OpenMM Version: 7.6
Git Revision: fd1cfdd60ccc883d4b811da96b823cb403182635

There are 3 Platforms available:

1 Reference - Successfully computed forces
2 CPU - Successfully computed forces
reordering took 0.000566959 seconds
3 CUDA - Successfully computed forces

Median difference in forces between platforms:

Reference vs. CPU: 6.29773e-06
Reference vs. CUDA: 6.73048e-06
CPU vs. CUDA: 7.34129e-07

All differences are within tolerance.
```
What is the way to tell it to use `nvrtc` and why it seems to be used through the python API but not in `make test`?

**Comment by peastman** [comment]
This has to do with how the test cases get built.  You're supposed to be able to run the tests *before* installing, which means they can't rely on dynamically loading libraries from the `plugins` directory.  So instead they get directly linked to the CUDA plugin and initialize it manually.  But they don't get linked to the runtime compiler plugin, so they instead need to be able to use nvcc.

**Comment by jchodera** [comment]
@peastman : Is this a behavior we should change (i.e. dynamically link the tests to the NVIDIA runtime compiler, which seems safe?), or is this impossible to fix due to a design decision? 

If it's something we should eventually fix, should we change the issue name and label it as an enhancement to remind us to tackle it at some point?

**Comment by ijpulidos** [comment]
I think there is still something to be discussed here, and maybe it is relevant for next release. As far as I understand there are advantages in performance with using NVRTC. So, I guess the question to answer here is how to force `nvrtc` to be used? As far as I can see it, `nvrtc` is the default now and it falls back to `nvcc` if it fails, but I _guess_ there are probably use cases where you want to avoid using `nvcc` at all and expect the simulation to error when you cannot use `nvrtc`. Is this something that should be considered for next release (7.7)?

For some reason the nightly build needs `nvcc`, that is, it ends up not using `nvrtc` (I'm guessing it needs it for debugging? Since that's how nightly is compiled, is that correct?)

**Comment by peastman** [comment]
Closing this since OpenMM 8.1 no longer supports using nvcc.
