### ISSUE TITLE
Is it possible to parse OpenMM System to create subsystems to calculate energies?

### ISSUE THREAD

**Issue by Bio-Otto** [openmm/openmm#3309]
After a classical simulation in OpenMM, is it possible to create a subsystem with topology, positions, and other necessary parameters and calculate energy?

For example, taking only 2 residues from a system of 100 residues and calculating them. I would also like to ask if such a thing makes sense. If possible how can I do it? Thanks:)

**Comment by swails** [comment]
ParmEd will let you do this for all systems that use a supported (and recognizable) force field:

```python
import parmed as pmd
from openmm.app import NoCutoff

structure = pmd.openmm.load_topology(topology, system)

# Take residues 9 and 10
substructure = structure[8:10]

# Create a new system
subsystem = substructure.createSystem(nonbondedMethod=NoCutoff)

energy_decomp = pmd.openmm.energy_decomposition_system(substructure, subsystem)
print(energy_decomp)
```

You'll need to fill in the code to provide the `topology` and `system` objects, and want to change the arguments given to `createSystem`, but this should give you an idea of how it can be done (it's important to understand exactly what this quantity *means*, though, as the unnaturally cut bonds with no capping atoms or residues will yield a physically unrealistic system.

**Comment by peastman** [comment]
Can you describe the scientific question you're trying to answer?  There are various ways you might define the "energy" of just two residues in a much larger protein.  Depending on how you define it, the answer you get might not match the question you were trying to ask.

**Comment by peastman** [comment]
Is this still an open question?  If so, please see the questions above.  Otherwise, is it ok to close it?

**Comment by Bio-Otto** [comment]
Sorry for my late reply. I went on a short trip because I lost my grandmother. I think @swails 's answer is exactly what I want. Thank you so much for your kindness.
