### ISSUE TITLE
Barostat is not changing box volume

### ISSUE THREAD

**Issue by orioncohen** [openmm/openmm#3312]
Preface: this is probably an error on my part

I am trying to use the barostat to change the volume of a simulation box.

I am generating initial coordinates with Packmol by packing my molecules inside a 4nm x 4nm x 4nm box and setting the system positions manually. 

```python
# generate topology from Parmed and system from OpenFF
integrator = LangevinMiddleIntegrator(300 * kelvin, 1 / picosecond, 0.001 * picoseconds)
coordinates = coordinates_from_packmol(smiles, counts, box_size) # my code
simulation = Simulation(topology, system, integrator)
simulation.context.setPositions(coordinates)
```

I then add a reporter to check the volume and a barostat to run at constant pressure.

```python
simulation.reporters.append(StateDataReporter(stdout, 100, step=True, volume=True))
system.addForce(MonteCarloBarostat(1*atmosphere, 300*kelvin, 10))
simulation.step(10000)
```

Despite adding a barostat, the volume remains at 8 nm^3 over the course of the simulation. This is (a) not the expected volume of 64 nm^3 that Packmol generates and (b) not changing.

I suspect that I am doing something wrong by not specifying the periodic box vectors, but I am not sure what to change.

Any help appreciated.

**Comment by peastman** [comment]
You need to add the barostat before you create the Simulation.  Once a Simulation is created, it won't see any further changes to System (unless you call `reinitialize()` to make it pick up the changes).

**Comment by orioncohen** [comment]
Thanks so much @peastman! That helps but it raises another issue, apparently my system is not periodic and I am now getting the error: `openmm.OpenMMException: A barostat cannot be used with a non-periodic system`. 

I tried setting periodic box vectors on the system and on the topology, but neither helped. Is there any way to force the system to be periodic? I am creating my system with the openff.ForceField.create_openmm_system() method. 

Also, if there is a better place to solicit this kind of help, please let me know.

**Comment by peastman** [comment]
A system is considered to be periodic if it contains any force that applies periodic boundary conditions.  Usually that's a NonbondedForce.  If you were using a standard OpenMM ForceField, you would specify a method such as `nonbondedMethod=CutoffPeriodic` or `nonbondedMethod=PME` when you call `createSystem()`.  It looks like OpenFF Toolkit works differently.  Hopefully someone with more experience using OpenFF can describe how to do it.

**Comment by apayne97** [comment]
> I tried setting periodic box vectors on the system and on the topology, but neither helped. Is there any way to force the system to be periodic? I am creating my system with the openff.ForceField.create_openmm_system() method.
can you send your complete system setup code? i have had related struggles. when do you add the periodic box vectors?

**Comment by orioncohen** [comment]
Thank's @peastman, very helpful. I'll inquire in the OpenFF issues. Since the Parsley ForceField has non-bonded forces built in, I expect that it should automatically be characterized as a periodic system, but that does not appear to be what is happening. 

@apayne97, well since you asked for the [complete setup code....](https://github.com/orioncohen/openmm-testing/blob/bcc92ccd0564318602e9bcad7234fa6ac64c92ba/setup/setup_functions.py#L82). Though I agree that `create_openmm_system` SHOULD create a peroidic system, it does not :/. Instead, I've been laundering the system through ParmEd to add the `nonbondedMethod` parameters, that allows me to add the barostat without issue. Maybe I don't need to do that if I add the periodic box vectors earlier?

**Comment by peastman** [comment]
Nonbonded forces don't necessarily imply a periodic system.  It depends whether you're simulating a molecule in vacuum (non-periodic), implicit solvent (also non-periodic), or explicit solvent (periodic).

**Comment by j-wags** [comment]
Hi @orioncohen,

@apayne97 is right -- The OpenFF toolkit's `create_openmm_system` method will only produce a periodic system if the OpenFF topology has `box_vectors` set. A quick example of doing this in your code looks like:

```diff
def _smiles_to_simulation(
    smiles, counts, box_size, integrator=None, platform_properties=None, **sys_kwargs
):
    if integrator is None:
        integrator = LangevinMiddleIntegrator(
            300 * kelvin, 1 / picosecond, 0.001 * picoseconds
        )
    # if not platform_properties:
    #     platform_properties = {}
    topology = _smiles_to_topology(smiles, counts)
    coordinates = _smiles_to_coordinates(smiles, counts, box_size)
    openff_mols = [
        openff.toolkit.topology.Molecule.from_smiles(smile) for smile in smiles
    ]
    openff_forcefield = smirnoff.ForceField("openff_unconstrained-2.0.0.offxml")
    openff_topology = openff.toolkit.topology.Topology.from_openmm(
        topology, openff_mols
    )
+   # Quick hack! Assumes a single side length for box size
+   openff_topology.box_vectors = [box_size, box_size, box_size] * angstrom  
    system = openff_forcefield.create_openmm_system(openff_topology)
    structure = parmed.openmm.load_topology(topology, system)
    structure.box = make_box_list(box_size, 'openmm')
    system = structure.createSystem(nonbondedMethod=PME, nonbondedCutoff=1 * nanometer)
    # system.addForce(MonteCarloBarostat(1 * atmosphere, 300 * kelvin, 10))
    platform = Platform.getPlatformByName('OpenCL')
    #properties = {"DeviceIndex": "0,1"}
    simulation = Simulation(topology, system, integrator, platform)#, properties)
    simulation.context.setPositions(coordinates)
    simulation.context.setPeriodicBoxVectors((4, 0, 0), (0, 4, 0), (0, 0, 4))
    return simulation
```

then

```
sim = _smiles_to_simulation(['CCO'], [4], 20 )
nbf = [force for force in sim.system.getForces() if "Nonbonded" in str(force)][0]
print(nbf.usesPeriodicBoundaryConditions())
```
> True

**Comment by apayne97** [comment]
> Though I agree that `create_openmm_system` SHOULD create a peroidic system, it does not

to be clear, what I meant is that your `openff_topology` needs to have periodic box vectors or else the system created by `create_openmm_system` will not be periodic! (what @j-wags is demonstrating)

the extra jump through parmed should be unnecessary.

**Comment by orioncohen** [comment]
Thank you so much @j-wags, @apayne97! Y'all have been incredibly helpful in getting through my OpenFF and OpenMM growing pains. The fix above solved my problem without jumping through `ParmEd`.

I'll close this Issue in couple days, barring other input.
