### ISSUE TITLE
How to set a initial velocity for the simulation of droplet impacting on the soild surface?

### ISSUE THREAD

**Issue by Dropletsimuli** [openmm/openmm#3316]
Dear all,
I want to run a simulation about droplet impacting on the soild surface in openMM. But I don't know how to set a initial velocity on Z axis for the droplet group in openMM. Is there anyway or trick to solve this problem?

**Comment by peastman** [comment]
You can call `setVelocities()` on the Context.  The API is exactly like `setPositions()`, except of course that the values you provide are velocities instead of positions.

**Comment by Dropletsimuli** [comment]
I will try it. Thanks!
