### ISSUE TITLE
Optimizing code by using C++ or creating Java wrapper

### ISSUE THREAD

**Issue by lukeczapla** [openmm/openmm#3318]
Hi everyone. this is for anyone with extensive knowledge of OpenMM.

So I have an interesting problem here that I began in the OpenMM Python language interface/wrapper, where I need to save the aMD "boost energy" deltaV and 12 collective variables at every 10 timesteps (to factor out all the noise in Boltzmann weighting each configuration with exp(beta*deltaV) where deltaV jumps a ton, for generating PMFs and true averages for these observables).  Originally with no measurements of the variables or deltaV, performance was much better, but suggestions to do this less often (every 50 timesteps) barely improved anything and the point was to get the most data as possible anyway.

So Python in some ways works like a "black box".  In any other programming language, something like this:

```
dV = [0]*500                 # create fixed list buffers of length 500,   [None]*500 works as well.
colvars = [(0,0,0,0,0,0,0,0,0,0,0,0)]*500
for j in range(int(inputs.nstep/5000)):
   for i in range(500):
      simulation.step(10)
      dV[i] = integrator.getGlobalVariable(7)
      colvars[i] = cvforce.getCollectiveVariableValues(simulation.context)
   print(....) # print the buffers to file that stdout is redirected to
```

would always outperform something like this:

```
for j in range(int(inputs.nstep/5000)):
   dV = []           # empty out list buffers
   colvars = []    # empty out list buffers
   for i in range(500):
      simulation.step(10)
      dV.append(integrator.getGlobalVariable(7))
      colvars.append(cvforce.getCollectiveVariableValues(simulation.context))
   print(...) # print the buffers
```

But the opposite is true in testing both - the bottom one works faster, even though it is constantly creating new empty lists, growing them with appends, and totally clearing them.  The fixed buffer should always do better because of less operations (just create the right size list once in the whole 10+ ns run, and every time the 500-size buffers are totally replaced, output them), at least if they were simple arrays like in other languages.  The dV list is just floats and the colvars list is tuples of 12 floats, to avoid wrapping these into objects with using stuff from openmm.unit package in the latest builds.  So on one local machine (OpenCL on AMD RX580, before transferring to HPC) the performance drop is huge, it goes from 21-22 ns/day without any reporting besides every 5000 steps with StateDataReporter, to 14 ns/day with the better of the two codes up top (the 2nd one) in that loop.

So I looked at /lib/python3.8/site-packages/openmm/app/simulation.py (because a couple times back when I was debugging it crashed in here) and it looks like it's doing things in steps of 10 anyway (changing this to 50 and the -= 10 blocks below it to -= 50, etc., did not improve anything, and I really think ideally recording every 10 steps is most reasonable.), but in a normal run without recording, CPU utilization (on a 12 hyperthreaded core system where usage can be as high as 1200%) the usage was only 9%, and then jumped to around 40% with the bottom code above with the loop.   So because of the Python global interpretor lock (GIL), it appears it's just completely idling as it defers to the GPU code that's likely called from the C++ libOpenMM.so library.

So recalling watching some of these older simulation packages, I'd see on a machine with 32 hyperthreaded cores and 1-2 GPUs that the GPU would be working away and the CPUs would also be near full utilization of 3200% of 1 core, which would only be possible inside invoked C++ libraries with a single threaded interpretor.  So now I don't think C++ is for everyone, in fact over the 25 years or so working with it, it has seen great improvements but also has become quite convoluted - but quite a few other C++ programmers like me have seen similar but more elegant languages like Java becoming a language of choice that have many of these same benefits.  Since the amount of memory these OpenMM jobs take up is trivial nowadays (especially compared to processing large batches of text documents, where the RAM usage might be 20 GB to optimize it by loading everything, and cluster nodes have over 512 GB anyway) there isn't much loss adopting the JVM and in fact the Java "parallelStream()" syntax can outperform "#pragma omp" OpenMP blocks that C++ often relies on, getting nearly to 1600% utilization on a 16 hyperthreaded core machine (e.g., 1510% utilization) when just asked to do intensive calculations like calculate numbers or process regex's.   There is a javacpp implementation sort of like the old JNI but way simpler ( https://github.com/bytedeco/javacpp ) that would allow prototyping of functions and objects in Java but actually calling the C++ elegantly, we'd used it in an open source product called deeplearning4j, invoking C code like libBLAS and LAPACK).

So it might be really useful to make an OpenMM Java wrapper, because with Python the CPU is generally idling and already losing efficiency, whereas C++ and Java can both just run this on only 1 thread and have access to all of the CPU cores whilst things are being deferred to the GPU for calculations.  Then my "loop" could be hypothetically something that's processing at the same time and notices when values change.

Does anyone have some suggestions on how moving to C++ might help remove this performance bottleneck or if alternatives exist?  That would be the simplest start, but I think that a Java wrapper could also be a good compromise (for me) between C++ and Python in bringing a simpler syntax (no & or * references/pointers etc., automatic memory management from GC, etc.) to the thing while really invoking the libOpenMM C++ routines natively with Java prototyping.
 
Thank you!
Luke

**Comment by peastman** [comment]
The first thing to do is figure out where the time is really being spent.  I would be really surprised to see any speed difference between the two versions.  Setting list elements or appending to lists should both take negligible time.  Writing output to a file is potentially more expensive, but it depends on the amount of output and the device you're writing to.  The call to `getCollectiveVariableValues()` is also potentially expensive, since it requires computing the values.  Exactly how expensive depends on what the CVs are and which platform you're using.

Running the code through a profiler is the place to start.  That will tell you more about what's really going on.  And remember that if you're running the simulation on a GPU, the CPU *should* be idle most of the time.  If you're using the CPU platform, though, all the cores should be busy most of the time.  Also, OpenMM releases the GIL while it's inside a call to `step()`, so it doesn't block other Python threads.

There's a Java wrapper for OpenMM at https://github.com/SchniedersLab/jopenmm.  I haven't tried it, so I can't say how well it works.  That might be something to try.  But first figure out what's really going on with the Python code, because I don't think the time is being spent where you think it is.

**Comment by lukeczapla** [comment]
The biggest bottleneck may be either this BAOAB Langevin Integrator or the CustomCVForce, this actually has dropped performance more than anything, with the standard Langevin integrator and no collective variables I have more like 21 ns day (as mentioned above, yes I am running on CUDA/HPC but this is locally with OpenCL on AMD RX580 GPU where there's more flexibility in removing lines and rerunning), but adding those back I'm down to 14 ns/day, so it might be more measuring the colvars, they are just simple distances "r" and diihedral angle "theta" measurements (the dihedrals are phi/psi/chi1/chi2 angles from the proteins).  Is there any more efficient way to obtain these than the CustomCVForce?

**Comment by peastman** [comment]
Are you using the BAOAB integrator from OpenMMTools?  It's written in a very inefficient way.  It applies constraints many more times than is necessary.  I recommend using LangevinMiddleIntegrator instead.

Try each of the following:

- Omit the collective variables from the System.
- Include them in the system, but don't call `getCollectiveVariableValues()`.
- Do call that method, but don't output the results to disk.

How fast is it in each of those cases?

**Comment by lukeczapla** [comment]
this CustomCVForce has the greater effect though, it's about 21 ns/day with no CustomCVForce or OpenMMTools BAOAB integrator, 15.5 ns/day without BOAB but including CustomCVForce, and 14 ns/day including both of them.  So I'd agree maybe it's not super efficient but that CustomCVForce is really slowing it down.  My code:

```
from openmm.unit import *
from openmm import *
from openmm.app import *

def CreateCVForce(system):

    cvforce = CustomCVForce("0")
    system.addForce(cvforce)
    D1 = CustomBondForce("r")
    D1.addBond(929, 2444)
    print(D1.getNumGlobalParameters())
    #D1.addGlobalParameter("dist", "r")
    D2 = CustomBondForce("r")
    D2.addBond(620, 2444)
    #D2.addGlobalParameter("dist", "r")
    X_Phi = CustomTorsionForce("theta")
    X_Phi.addTorsion(2407,2409,2411,2417)
    X_Psi = CustomTorsionForce("theta")
    X_Psi.addTorsion(2409,2411,2417,2419)
    D_Phi = CustomTorsionForce("theta")
    D_Phi.addTorsion(2417,2419,2421,2430)
    D_Psi = CustomTorsionForce("theta")
    D_Psi.addTorsion(2419,2421,2430,2432)
    F_Phi = CustomTorsionForce("theta")
    F_Phi.addTorsion(2430,2432,2434,2450)
    F_Psi = CustomTorsionForce("theta")
    F_Psi.addTorsion(2432,2434,2450,2452)
    D_Chi1 = CustomTorsionForce("theta")
    D_Chi1.addTorsion(2419,2421,2423,2426)
    D_Chi2 = CustomTorsionForce("theta")
    D_Chi2.addTorsion(2421,2423,2426,2428)
    F_Chi1 = CustomTorsionForce("theta")
    F_Chi1.addTorsion(2432,2434,2436,2439)
    F_Chi2 = CustomTorsionForce("theta")
    F_Chi2.addTorsion(2434,2436,2439,2440)
    cvforce.addCollectiveVariable("D1", D1)
    cvforce.addCollectiveVariable("D2", D2)
    cvforce.addCollectiveVariable("X_Phi", X_Phi)
    cvforce.addCollectiveVariable("X_Psi", X_Psi)
    cvforce.addCollectiveVariable("D_Phi", D_Phi)
    cvforce.addCollectiveVariable("D_Psi", D_Psi)
    cvforce.addCollectiveVariable("F_Phi", F_Phi)
    cvforce.addCollectiveVariable("F_Psi", F_Psi)
    cvforce.addCollectiveVariable("D_Chi1", D_Chi1)
    cvforce.addCollectiveVariable("D_Chi2", D_Chi2)
    cvforce.addCollectiveVariable("F_Chi1", F_Chi1)
    cvforce.addCollectiveVariable("F_Chi2", F_Chi2)
    return cvforce
```

**Comment by peastman** [comment]
Which part causes the slowdown?  Is it including the CustomCVForce in the System, querying the CVs, or writing them to a file?

It looks like you aren't actually using the CustomCVForce in the normal way.  The energy doesn't depend on the CVs.

```python
    cvforce = CustomCVForce("0")
```

Are you just using it as a way to query those angles?  If so, it would probably be faster to query the positions and compute them yourself.  That way you only add cost every 500 steps instead of every step.  Alternatively, you could move the CustomCVForce into a different force group that isn't included during integration.

```python
cvforce.setForceGroup(31)
integrator.setIntegrationForceGroups(range(31)) # includes all values from 0 to 30, but not 31
```

**Comment by lukeczapla** [comment]
Yes, I wasn't sure how to poll/query the 2 distances and the 10 dihedrals so I just asked someone familiar with this and they suggested CustomCVForce to do it, but it seemed counterintuitive with the documentation. I modified that BAOAB Langevin class and called it LangevinAMDForceGroupIntegrator so I could use single group boost (dihedral) aMD with that BAOAB integrator and ditch AndersenThermostat and the kinda leapfrog-like AMDForceGroupIntegrator, that's how the boost potential (which I call dV or deltaV to agree with the original notation) ended up being getGlobalVariable(7).   So yes, it's purely to measure distances and angles.  I will try the two lines suggested there, and I still want their values every 10 steps to make the Boltzmann weighted PMF data from aMD less noisy, my histograms show you can miss sampling 4 points that ended up in a bin and have nothing to estimate the PMF with 500 steps..

**Comment by lukeczapla** [comment]
It won't accept integrator.setIntegrationForceGroups(range(31)) and says it's an error but this worked (using the force bit idea):

integrator.setIntegrationForceGroups({0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15})

I think that's all I need for the total but I suppose I can go up to 30 too

**Comment by everyday847** [comment]
Immaterial to the scientific question at hand, but as to python syntax, I strongly suspect the error you faced was that `range(31)` is a range object and python 3 complains if you use a range object where a list (or potentially a set) is expected, so if you pass `list(range(31))` (or _perhaps_ `set(range(31))` since that's the exact object you successfully passed) you'll be fine.

**Comment by peastman** [comment]
Sorry, typo on my part.  That should have been

```python
integrator.setIntegrationForceGroups(set(range(31)))
```

**Comment by lukeczapla** [comment]
so now it improved with removing this CustomCVForce group from the integration forces, but still using BAOAB and recording deltaV and these CVs every 10 time steps it's getting 17 ns/day (better than 14 ns/day!!).  Turning off BAOAB and using standard Langevin dynamics (no BAOAB) but still using the CustomCVForce (without including in integration) gets 19.5 ns/s, and lastly turning off the recording of the collective variables gets back to the 21 ns/day I had with everything standard.  So it's a bit like a number of things slowing it down along the process but now excluding the CustomCVForce from integration groups, that is not slowing it down.  It's only the recording CVs and deltaV every 10 timesteps and using this openmmtools Langevin BAOAB integrator that are each slowing down and together drop me from 21 ns/day to now 17 ns/day, so there was some improvement over the 14 ns/day drop!

**Comment by peastman** [comment]
That makes sense.  You could try instead querying the positions and computing the collective variables yourself.  That might or might not be faster.

If you need to write a custom integrator, I suggest basing it on the code at http://docs.openmm.org/latest/api-c++/generated/CustomIntegrator.html.  It gives examples of custom integrators whose algorithms are identical to VerletIntegrator and LangevinMiddleIntegrator.  Those are more efficient than the one in OpenMMTools.

**Comment by lukeczapla** [comment]
One last note here, the benchmarks on the HPC can be horribly unreliable (and I have to hit up HPC to figure out why two systems with the same GPU are now giving wildly different ns/day, but it's likely other jobs on the machines since I don't benefit from 2xGPU or 4xGPUs, and maybe it'll go back up on the weekend) while on the desktop where the only thing running is the X11 system and window system and maybe a single browser tab, the benchmarks are super stable.  So I think the desktop test platform (OpenCL + AMD RX580 GPU) is much better for getting reliable benchmarks than an overloaded HPC system.  For that, I might have to think about stacking my jobs together on one machine with HPC assistance, since my CPU usage is practically zero and then I'll know better what the other GPUs are doing.

**Comment by lukeczapla** [comment]
Okay, so I have a LangevinRVOVRAMDForceGroupIntegrator.py that's rewritten from just CustomIntegrator to just specifically do my job, and the performance from saving the data every 10 timesteps isn't bad at all now.  I got up from 17 ns/day to 18.5 ns/day and the baseline with just default MD was 21 ns/day on the dinky workstation testbed with OpenCL + AMD RX580 GPU.  I don't see a need to try to rewrite CustomCVForce right now, it's pretty well organized at the moment, and I can put this code up here at the end if anyone wants to see (maybe make a repo later for all of the stuff)

It seemed this integrator did a better job of removing bias and exploring phase space of useful configurations in tests ( https://doi.org/10.3390/e20050318 ), so that was the original reason it was in there, to see what's up with that and hopefully get some extra from it.  So the cheaper one will hopefully get the job done, and I have HPC issues to work out.

```Python

from openmm.openmm import CustomIntegrator
from openmm.unit import *
import numpy as np

kB = BOLTZMANN_CONSTANT_kB * AVOGADRO_CONSTANT_NA
class LangevinVRORVAMDForceGroupIntegrator(CustomIntegrator):
    def __init__(self, alphaGroup, EGroup, group=2, temperature = 310*kelvin,
                  collision_rate=1.0/picoseconds, timestep=2.0*femtoseconds):
        gamma = collision_rate*picoseconds    # stupid "SWIG" thing with numpy
        super(LangevinVRORVAMDForceGroupIntegrator, self).__init__(timestep)
        self.addPerDofVariable("sigma", 0)
        self.addGlobalVariable('kT', kB * temperature)
        self.addGlobalVariable("a", np.exp(-gamma))
        self.addGlobalVariable("b", np.sqrt(1 - np.exp(-2 * gamma)))
        self.addPerDofVariable("x1", 0) # before position restraints
        
        # Set aMD boost parameters
        self.addGlobalVariable("alphaGroup", alphaGroup)
        self.addGlobalVariable("EGroup", EGroup)
        self.addGlobalVariable("groupEnergy", 0)
        self.addGlobalVariable("deltaV", 0)
        self.addPerDofVariable("fg", 0)
        
        self.addUpdateContextState()
        # Compute thermal properties, kT doesn't change here
        self.addComputePerDof("sigma", "sqrt(kT/m)")
        # V step
        self.addComputeGlobal("groupEnergy", "energy"+str(group))
        self.addComputeGlobal("deltaV", "modify*(EGroup-groupEnergy)^2/(alphaGroup+EGroup-groupEnergy); modify=step(EGroup-groupEnergy)")
        self.addComputePerDof("fg", "f"+str(group))
        self.addComputePerDof("v", "v + (dt / 2) * fprime / m; fprime=fother+fg*((1-modify) + modify*(alphaGroup/(alphaGroup+EGroup-groupEnergy))^2); fother=f-fg; modify=step(EGroup-groupEnergy)")
        #self.addConstrainVelocities()
        # R Step
        self.addComputePerDof("x", "x + (dt / 2)*v")
        self.addComputePerDof("x1", "x")  # save pre-constraint positions in x1
        self.addConstrainPositions()      # x is now constrained
        self.addComputePerDof("v", "v + (x - x1)/(dt / 2)")
        #self.addConstrainVelocities()        
        # O Step
        self.addComputePerDof("v", "(a * v) + (b * sigma * gaussian)")
        #self.addConstrainVelocities()
        # R Step
        self.addComputePerDof("x", "x + (dt / 2)*v")
        self.addComputePerDof("x1", "x")  # save pre-constraint positions in x1
        self.addConstrainPositions()      # x is now constrained
        self.addComputePerDof("v", "v + (x - x1) / (dt / 2)")
        #self.addConstrainVelocities()
        # V step
        self.addComputeGlobal("groupEnergy", "energy"+str(group))
        self.addComputeGlobal("deltaV", "modify*(EGroup-groupEnergy)^2/(alphaGroup+EGroup-groupEnergy); modify=step(EGroup-groupEnergy)")
        self.addComputePerDof("fg", "f"+str(group))
        self.addComputePerDof("v", "v + (dt / 2) * fprime / m; fprime=fother+fg*((1-modify) + modify*(alphaGroup/(alphaGroup+EGroup-groupEnergy))^2); fother=f-fg; modify=step(EGroup-groupEnergy)")
        self.addConstrainVelocities()

```
