### ISSUE TITLE
NonbondedForce parameter offsets: Negative scale factors should be allowed

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#3319]
#3286 added a number of helpful checks for valid parameter values, but it also appears to have [restricted `sigmaScale` and `epsilonScale` `NonbondedForce` parameter offset scaling factors to be nonnegative](https://github.com/peastman/openmm/blob/44d10d6608639193c0acc44bded0abfe28841bba/openmmapi/src/NonbondedForceImpl.cpp#L112-L115). This does not appear to be necessary, since it should be perfectly reasonable to reduce the initial parameter values (provided the final value doesn't end up negative, but this cannot be checked ahead of time). We in fact use this in perses, since this is necessary for relative alchemical free energy calculations. (cc https://github.com/choderalab/perses/issues/890).

**Comment by peastman** [comment]
Good catch.  I'll fix that.
