### ISSUE TITLE
How to fully backup simulation state?

### ISSUE THREAD

**Issue by orioncohen** [openmm/openmm#3322]
I am trying to save a simulation to be reloaded later. I may need to change platforms so `Checkpoint` isn't an option.

Instantiating a Simulation requires (at least) a `System`, `Topology`, and `Integrator`, but from what I can tell,  `Simulation.saveState()` only saves the positions and velocities, which is not enough to restore the system.

The `Integrator` is relatively easy to specify and I can save the `Topology` by adding a PDB reporter but I have no idea how to save a `System`. When I am setting up, I am using the OpenFF toolkit to parameterize the system with the Sage Force Field. I could load a topology and re-parameterize, but I would prefer to load directly from a file. 

Is there a straightforward way to save the whole state of a `Simulation` or just to save a `System`?

**Comment by peastman** [comment]
Saving a System is very easy.

```python
with open('system.xml', 'w') as output:
  output.write(XmlSerializer.serialize(system)
```

And then to load it back in,

```python
with open('system.xml') as input:
  system = XmlSerializer.deserialize(input.read())
```

**Comment by orioncohen** [comment]
Thank you! Is there any list of what OpenMM objects can be serialized like this?

**Comment by peastman** [comment]
Anything for which [a serialization proxy is registered](https://github.com/openmm/openmm/blob/master/serialization/src/SerializationProxyRegistration.cpp).  That includes System, State, and non-abstract subclasses of Integrator, Force, and TabulatedFunction.

**Comment by orioncohen** [comment]
Awesome, thank you. Closing now.
