### ISSUE TITLE
Set rigidWater attribute to True for TIPnP ffxml variants

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#3323]
I just discovered that the `ForceField` class can use an [ffxml template residue's default `rigidWater` behavior](https://github.com/openmm/openmm/blob/master/wrappers/python/openmm/app/forcefield.py#L1162-L1165) if `rigidWater` is not specified as an argument (or set to `None`). Currently, this is only used to [ensure iAmoeba water remains flexible](https://github.com/openmm/openmm/blob/be19e0222ddf66f612016a3c1f687161a53c2396/wrappers/python/openmm/app/data/iamoeba.xml#L7), but we should definitely use this to ensure that all TIPnP models are rigid by default to avoid issues.

We just experienced one of these issues internally today, where we discovered it is easy to accidentally specify constrained bonds to hydrogen but omit `rigidWater=True` in setting simulations that then have a higher tendency to explode when using 4fs timesteps.

**Comment by peastman** [comment]
If a template doesn't include the `rigidWater` attribute, it defaults to true.  You can add the attribute setting it to true just for clarity, but it doesn't affect the behavior.  Something different must have been the problem in your case.

Perhaps the water molecules in your topology had a nonstandard name?  It identifies water based on the name "HOH".

**Comment by zhang-ivy** [comment]
If `rigidWater=True`, should there be 3 constraints for each water?

**Comment by zhang-ivy** [comment]
If not, is there a way to check a system.xml and ascertain whether rigidWaters was used to generate the system?

**Comment by zhang-ivy** [comment]
It seems like there should be 3 constraints for each water, as angles in rigid waters will be marked as constrained [here](https://github.com/openmm/openmm/blob/d83c2724a40131be77f6ed2b29acfa9b3e0c7af5/wrappers/python/openmm/app/forcefield.py#L1342-L1343), and then [a constraint is added](https://github.com/openmm/openmm/blob/d83c2724a40131be77f6ed2b29acfa9b3e0c7af5/wrappers/python/openmm/app/forcefield.py#L2075-L2095) when the angle force is created.

However, when I run:
```python
import openmmtools
from simtk.openmm import app

atp = openmmtools.testsystems.AlanineDipeptideVacuum()
forcefield_files = ['amber14/protein.ff14SB.xml', 'amber14/tip3p.xml']
forcefield = app.ForceField(*forcefield_files)
modeller = app.Modeller(atp.topology, atp.positions)
modeller.addSolvent(forcefield, model='tip3p', padding=9*unit.angstroms, ionicStrength=0.15*unit.molar)

system = forcefield.createSystem(modeller.topology, 
                                 nonbondedMethod=app.PME, 
                                 constraints=app.HBonds, 
                                 rigidWater=True, 
                                 removeCMMotion=False, 
                                 hydrogenMass=4*unit.amu)
```
and check the constraints, I'm seeing the following constraints for waters:
```
[22, 23, Quantity(value=0.09572, unit=nanometer)]
[22, 24, Quantity(value=0.09572, unit=nanometer)]
[25, 26, Quantity(value=0.09572, unit=nanometer)]
[25, 27, Quantity(value=0.09572, unit=nanometer)]
...
```

**Comment by peastman** [comment]
The constraints are all there, just not in the order you're expecting.  All constraints for bonds come before all constraints for angles.  Try this:

```python
for i in range(system.getNumConstraints()):
  p1, p2, length = system.getConstraintParameters(i)
  if p1 in (22, 23, 24):
    print(p1, p2, length)
```

Here's the output I get.

```
22 23 0.09572 nm
22 24 0.09572 nm
23 24 0.15139006545247014 nm
```

**Comment by jchodera** [comment]
Ah! Thanks for pointing this out. I hadn't realized it defaults to `true`!
