### ISSUE TITLE
Error using pointdistance with CustomCentroidBondForce

### ISSUE THREAD

**Issue by gabriela-correa** [openmm/openmm#3327]
I'm having trouble using CustomCentroidBondForce. I would like to use the pointdistance function to calculate the distance between the z coordinates of two groups of particles. But when I run the code, an error indicates that pointdistance is an unknown function. Can someone help me? 

The error:
```
Traceback (most recent call last):
  File "simulation_PMF.py", line 89, in <module>
    simulation = app.Simulation(prmtop.topology, system, integrator, platform)
  File "/home/gabriela/anaconda3/lib/python3.8/site-packages/simtk/openmm/app/simulation.py", line 103, in __init__
    self.context = mm.Context(self.system, self.integrator, platform)
  File "/home/gabriela/anaconda3/lib/python3.8/site-packages/simtk/openmm/openmm.py", line 4948, in __init__
    _openmm.Context_swiginit(self, _openmm.new_Context(*args))
simtk.openmm.OpenMMException: Parse error in expression "0.5*k*(r - r0)^2;r = pointdistance(z1, z2);": unknown function: pointdistance
```

A piece of the code:
```py
#bias potential
energy_function = '0.5*k*(r - r0)^2;'
energy_function += 'r = pointdistance(z1, z2);'
bias = openmm.CustomCentroidBondForce(2, energy_function)
bias.addPerBondParameter('k')
bias.addPerBondParameter('r0')
particles1 = [atom.index for atom in prmtop.topology.atoms() if atom.residue.name == res_name_solute]
particles2 = [atom.index for atom in prmtop.topology.atoms() if atom.residue.name == res_name_water]
bias.addGroup(particles1)
bias.addGroup(particles2)
bondGroups = [0, 1]
bondParameters = [100.0, 0.1]
bias.addBond(bondGroups, bondParameters)
system.addForce(bias)
```

**Comment by peastman** [comment]
Which version of OpenMM are you using?  It was added in 7.6.

By the way, that function expects six arguments.  You can write it as `pointdistance(0, 0, z1, 0, 0, z2)`.  That is, pass 0 for the x and y coordinates of the two points.

**Comment by gabriela-correa** [comment]
I am using version 7.5. Probably it is the problem.
When I install with
```
conda install -c conda-forge openmm
```
I get the version 7.5. How can I get the version 7.6? Just installing directly from github?

**Comment by peastman** [comment]
That indicates something else in your conda environment is preventing it from installing 7.6.  Try creating a new environment, for example with

```
conda create --name openmm openmm
```

That will create a new environment called `openmm` and install OpenMM into it.

**Comment by gabriela-correa** [comment]
I used  ``` conda install -c conda-forge openmm=7.6 ``` and it worked without creating a new conda environment.
Thank you very much for your attention!

**Comment by peastman** [comment]
Strange, I wonder why it was installing an older version?  Anyway, I'm glad it was that easy to fix.
