### ISSUE TITLE
PDBFile - topology is not working in Openmm 7.7.0beta?

### ISSUE THREAD

**Issue by Eli-VDB** [openmm/openmm#3331]
I am trying to explore a new functionality implemented in version 7.7.0beta (MonteCarloFlexibleBarostat) but I've encountered an issue with the dcd reporter in version 7.7.0beta. 

Perhaps this problem is already resolved, but if not please have a look.
I am able to reproduce the issue with a freshly installed conda environment.

With
```bash
 conda install -c conda-forge/label/openmm_rc openmm=7.7.0beta
```
 I get the following error message (only showing the relevant part):
```bash
  File " miniconda3/envs/openmm-test/lib/python3.9/site-packages/openmm/app/simulation.py", line 263, in _generate_reports
    reporter.report(self, state)
  File "miniconda3/envs/openmm-test/lib/python3.9/site-packages/openmm/app/dcdreporter.py", line 107, in report
    self._dcd.writeModel(state.getPositions(), periodicBoxVectors=state.getPeriodicBoxVectors())
  File "miniconda3/envs/openmm-test/lib/python3.9/site-packages/openmm/app/dcdfile.py", line 121, in writeModel
    raise ValueError('The number of positions must match the number of atoms')
ValueError: The number of positions must match the number of atoms
```
When commenting this command in the simulation script:
simulation.reporters.append(app.DCDReporter(f'xxx.dcd', data_freq))
then no error occurs.

When openmm is installed via:
```bash 
conda install openmm
```
(Hence Openmm 7.6.0):

No error occurs, simulation and reporting runs fine.

Apart from the versioning I am not changing anything on the python script, Hence the problem can be attributed solely to a bug in the new version (7.7.0) I believe. Could you verify this and/or solve this? 

Evidently I am using a version of 10 days ago as this is the last version uploaded to conda, so maybe this problem is outdated already,
in that case feel free to ignore this :).

Thank you in advance for resolving this issue!

**Comment by peastman** [comment]
That error indicates that the number of particles in your System doesn't match the number of atoms in your Topology.  You can easily check that:

```python
print(system.getNumParticles(), topology.getNumAtoms())
```

where `system` and `topology` are the objects you pass to the Simulation's constructor.  Are the two numbers different?

**Comment by Eli-VDB** [comment]
@peastman Thanks for the swift response,

I indeed identified the error incorrectly, the bug is not residing within the DCDreporter, but rather with PDBFile() (or the derivation of the topology from the file, I'll rename the issue).

Nonetheless, changing the version of openmm is sufficient to solve the problem.
After checking what is going on with the amount of particles in each version, I can see that the number of atoms recognized in the topology file in no longer correct in version 7.7.0beta.

For example:
In version 3.6.0:
print(system.getNumParticles(), topology.getNumAtoms()) results in 40780 40780.
while with version 3.7.0beta I get:
print(system.getNumParticles(), topology.getNumAtoms()) results in 40780 26500.
where topology = PDBFile('compressed_output.pdb').topology

Not sure what's going on here but perhaps this information can help in pinpointing the problem with 7.7.0beta?
Thanks in advance.

**Comment by peastman** [comment]
Ok, that helps to narrow things down.  Can you post your code, including all input files necessary to run it?  There's clearly something strange here.  The number of atoms in the topology (which you read from a PDB file?) changed, which could be caused by various things.  But the number of atoms didn't change, which indicates you aren't creating the system based on the topology?  If I can see exactly what you're doing it should be clearer.

**Comment by Eli-VDB** [comment]
Unfortunately, sharing my data is not allowed (yet) due to confidentiality concerns.

However, below you can find the python script I use, I am loading a system.xml file to initiate the system (as it is a continuation of a previous simulation and the parameterization procedure is non-trivial atm) after which I load the topology though this didn't cause any problems before:
```python 
from openmm.app import *
from openmm import *
from openmm.openmm import *
from openmm.unit import *
from sys import stdout
import time
import argparse
import numpy as np


parser = argparse.ArgumentParser()
parser.add_argument('-x','--xml',type=str,help='system.xml input filename, generated with the notebook, packmol, Openyaff ,...')

#parser.add_argument('-d', '--dimension',type=float)
args = parser.parse_args()

n_api = 476
n_chains = 15
n_chain = 15
cid = 35802
R = 8.31446261815324 * 10**-3 #kjmol/K/mol
n_atoms = 35*n_api + 1608*n_chain
T=298 #K

systems_dir = '/data/gent/vo/000/gvo00003/vsc41963/Project_ASD/Equilibration/Systems/'

def forcegroupify(system):
    forcegroups = {}
    for i in range(system.getNumForces()):
        force = system.getForce(i)
        force.setForceGroup(i)
        forcegroups[force] = i
    return forcegroups

def getEnergyDecomposition(context, forcegroups):
    energies = {}
    for f, i in forcegroups.items():
        energies[f] = context.getState(getEnergy=True, groups=2**i).getPotentialEnergy()
    return energies


def Perform_npt_run(pdb_box,system,integrator,simulation_steps,pressure,temperature,timecon):
    
    #barostat = MonteCarloFlexibleBarostat(pressure, temperature,timecon)
    barostat = MonteCarloBarostat(pressure, temperature,timecon)
    forceIndex = system.addForce(barostat)
    data_freq = 10# for test purposes otherwise: 10000 i.e. 10 ps
#    platform = Platform.getPlatformByName('CUDA')
#    properties = {}
#    properties["DeviceIndex"]='0'
#    properties["Precision"]='mixed'
    print(system.getNumParticles(),pdb_box.topology.getNumAtoms())
    assert system.getNumParticles() == pdb_box.topology.getNumAtoms()
    simulation = app.Simulation(pdb_box.topology, system, integrator)#,platform,platformProperties=properties)
    #box_positions = pdb_box.getPositions()
    simulation.loadState('compressed_output.xml') #production_state_output.xml')
    #simulation.context.setPositions(box_positions)
    ## Reporters

    simulation.reporters = []
    simulation.reporters.append(app.DCDReporter(f'traj_nptflex.dcd', data_freq))
    simulation.reporters.append(app.StateDataReporter('nptflex_stdout.log', data_freq, step=True,temperature=True, elapsedTime=True))
    simulation.reporters.append(app.StateDataReporter(f"scalars_nptflex.csv", data_freq, time=True,potentialEnergy=True, totalEnergy=True, temperature=True,volume=True,density=True))
    

    #Simulation 
    print("Starting simulation")
    print(len(pdb_box.getPositions()),pdb_box.topology.getNumAtoms())
    start = time.process_time()
    simulation.step(simulation_steps)
    end = time.process_time()
    print("Elapsed time %.2f seconds" % (end-start))
    print("Done!")
    system.removeForce(forceIndex)
    
    #Saving  
    print('Saving ...')
    simulation.saveCheckpoint('nptflex_output.pdb.chk')
    simulation.saveState('nptflex_output.xml')
    positions = simulation.context.getState(getPositions=True).getPositions()
    print('Simulation output dimensions')
    print(simulation.context.getState(getPositions=True).getPeriodicBoxVectors())
    print(simulation.topology.getPeriodicBoxVectors())
    simulation.topology.setPeriodicBoxVectors(simulation.context.getState(getPositions=True).getPeriodicBoxVectors())
    print(simulation.topology.getPeriodicBoxVectors())
    PDBFile.writeFile(simulation.topology, positions, open('nptflex_output.pdb', 'w'))
    
    print('... Saving Succeeded')
    return

    
    return

def main():
    # MD settings
    timestep = 1*femtoseconds #in femtoseconds
    temperature_1 = 298*kelvin
    temperatureEqProtocol = 600*kelvin
    pressure = 1*bar #in bar, for an isobaric simulation
    frequency = 25 # steps
    timecon = 10 # frequency for montecarlo barostat in npt_flex
    
    ## Create the System object
    xml_file = open(args.xml).read()
    off_box_system = XmlSerializer.deserializeSystem(xml_file)
    if off_box_system.usesPeriodicBoundaryConditions():
        print('This system is defined with PBC')
    forcegroups = forcegroupify(off_box_system)
    ForceIndex=None
    for idx,force in enumerate(forcegroups):
        if isinstance(force,MonteCarloBarostat):
           ForceIndex=idx
    if ForceIndex:
        off_box_system.removeForce(ForceIndex=idx)
        print('Barostat removed')
	
    # Thermostat, nose hoover to be able to extract dynamic properties
    # integrator_NVT = NoseHooverIntegrator(temperature_1, 1/picosecond, timestep)
    integrator = LangevinIntegrator(temperature_1, 1/picosecond, timestep)
    
    pdb_box_compressed  = PDBFile('compressed_output.pdb')

    off_box_system.setDefaultPeriodicBoxVectors(pdb_box_compressed.topology.getPeriodicBoxVectors()[0],pdb_box_compressed.topology.getPeriodicBoxVectors()[1],pdb_box_compressed.topology.getPeriodicBoxVectors()[2])
    
    print(pdb_box_compressed.topology.getUnitCellDimensions())
    if not pdb_box_compressed.topology.getUnitCellDimensions():
        print('box dimensions of previous step are needed.')

    print("Performing production run")    
    steps_nptflex = int((12*nanoseconds)/(timestep))
    Perform_npt_run(pdb_box_compressed,off_box_system,integrator,steps_nptflex,pressure,temperature_1,timecon)
    
        
    return

main()    
```

If you need input files as well, then I'll have to check up with my experimental patners and supervisors whether I can share it, sorry for this inconvenience.

**Comment by peastman** [comment]
Without the files to reproduce the problem, I can only offer very limited help.  It appears that the PDB file is getting loaded differently in the two versions.  Can you identify which atoms are included in the topology in 7.6 but not 7.7, then see if there's any obvious pattern to them?

If you can get permission to send me the PDB file, that would makes this a lot easier.

**Comment by Eli-VDB** [comment]
I got permission to share it. I've shared a private github repo with the system.xml, state.xml and the .pdb file.
If you need extra information, or if you want me to send you the data in another way, feel free to ask.

Thanks in advance!

**Comment by peastman** [comment]
Perfect, thanks!

When I load the file, it prints thousands of warning messages like this:

```
/Users/peastman/miniconda3/envs/openmm/lib/python3.9/site-packages/openmm/app/internal/pdbstructure.py:538: UserWarning: WARNING: duplicate atom (HETATM24124  O   UNL B   1      71.422  26.189  39.395  1.00  0.00           O  , HETATM24123  O   UNL B   1      67.778  24.221  30.672  1.00  0.00           O  )
```

That's telling you exactly what the problem is: atom names are required to be unique within a residue.  When it encounters multiple atoms with the same name, it doesn't know how to interpret them.  Are they supposed to be different atoms, and you incorrectly gave them the same name?  Or are they supposed to be alternate locations for the same atom, and you incorrectly left off the alternate location identifier?  OpenMM used to assume the former, but a side effect of #3270 is that it now assumes the latter.  But either way, the file is incorrect and it's printing out warnings to tell you that.

**Comment by Eli-VDB** [comment]
Super, thanks for figuring out the source of my error.

Well, they are indeed supposed to be different atoms, however the atoms the warning is referring to belong to the residues UNL, which are all parameterized at the beginning of the investigation using openforcefield (hence not requiring any types, just connectivity data). Afterwards I work with the system.xml and .pdb files to perform the simulations and hence circumvent the need to perform typing, as it works indexed based (of course there is a reason why I take this approach).

Can I circumvent the crashes for now, by reverting the PDBFile function to the version of 3.6.0 in my local environment? In future work, I'll make sure that for this purpose I also ensure unique atom names for residues which I plan to parameterize with OpenFF.

Thanks for all the help!

**Comment by peastman** [comment]
> Can I circumvent the crashes for now, by reverting the PDBFile function to the version of 3.6.0 in my local environment?

You could, but you'll be removing an important bug fix.  A much better solution would be to fix the atom names in the file.  You should be able to do that with a short script.  Read in the lines of the file and write them to another file.  If a line starts with HETATM, check whether the atom name and residue index both match the previous line.  If so, modify the atom name column to give it a different name.

**Comment by Eli-VDB** [comment]
Super, will do the latter!

Thanks again!
