### ISSUE TITLE
Bug in using implicit solvent together with GROMACS topology file

### ISSUE THREAD

**Issue by WangXinyan940** [openmm/openmm#3334]
See https://github.com/openmm/openmm/blob/f477b106fc946c4cb3b4ae7d61da43889e568c9e/wrappers/python/openmm/app/gromacstopfile.py#L937

`

                for fields in moleculeType.atoms:
                    if implicitSolvent is OBC2:
                        if fields[1] not in self._implicitTypes:
                            raise ValueError('No implicit solvent parameters specified for atom type: '+fields[1])
                        gbparams = self._implicitTypes[fields[1]]
                        gb.addParticle(q, float(gbparams[4]), float(gbparams[5]))
`

The atomic charge **q** is not loaded while adding particles to GBSAOBCForce. The code now uses the charge of the last particle for all the atoms. Removing line 937 will fix it.

**Comment by peastman** [comment]
Thanks!
