### ISSUE TITLE
Did somebody eat GBVIForce.h?

### ISSUE THREAD

**Issue by lukeczapla** [openmm/openmm#3341]
Hi guys, I've been hacking ye old 2013 code that I now call Excalibur (a C++ implementation of OpenMM mixed with other routines) and I noticed GBVIForce was missing entirely but now it's totally up to date for 2021.

So was it just bunk to begin with or just not the hassle or something?  I liked it a bunch but if it was buggy that would be one reason to throw it into the trash.  Any comments?  I just got started again doing this stuff maybe a month ago and wanted to really compare for myself a C++ implementation vs. a Python implementation where I knew exactly how to optimize it with straight "C" or even GPU routines (are there any good examples of invoking those directly that I can view in source code?).   We needed to up our game regardless and I am just not a huge fan of Python and I bet someone can always come along and help wrap it up in Python with me.

Thanks guys!

**Comment by peastman** [comment]
It was removed years ago.  It was an interesting functional form, but no one ever got around to parametrizing it, which meant it wasn't really useful.  Plus we only ever had a reference implementation, not any kind of optimized version that would be practical for real simulations.  And if I recall, it was a function that could be implemented with CustomGBForce, so there really was no reason to have a custom implementation of it.

**Comment by lukeczapla** [comment]
Ok rad, yes I suppose it's all about parameterization and I had some preliminaries in the new github repo but I really didn't do a great job there either, in a sense it's a big project but I did want to keep it alive in terms of the theory behind it, it seemed like an excellent way to go.  We have a CHARMM developers license at Rutgers and I guess in 2012-2013 I was trying to do this for the CHARMM-OpenMM interfaces - any updates on that thing if it is such a thing nowadays?  Because why shouldn't it have a CustomGBForce implementation and sort of be in my github repo to play around with for kicks?

**Comment by lukeczapla** [comment]
so if you have an old GBVIForce.h laying around, definitely you could email it or paste it here and I'll see what I had.

**Comment by lukeczapla** [comment]
probably might need the C++ code .cpp file too because most of my stuff is both too

**Comment by peastman** [comment]
The code is all in the git history.  Here's the commit where it was deleted: https://github.com/openmm/openmm/commit/14e78600334aa2e49fe39d983fd6431f948a2bb9

**Comment by lukeczapla** [comment]
great, thanks so much! I'll see what I can do with it, I really have a ton of junk here where I truly believe you just integrate the old C++ code with the OpenMM acceleration and we got something awesome, so now that I'm getting some more info from the benchmarks and everything I might want to revive that with a set of generic parameters for a coarse-grained model of DNA that rebuilds into an all-atom picture of everything but the sugar right now.  So I'm happy to go digging along and seeing what the story was and if it should be trashed and redone entirely and we have people here and other places to go ask for advice.

**Comment by peastman** [comment]
If you're interested in using that solvent model, I recommend implementing it with CustomGBForce.  It's much easier than writing C++ code, and you'll get GPU acceleration.

**Comment by lukeczapla** [comment]
I still have a CustomGBForce based GBSAOBCForce GBN2Force and OBC2Force - seems some worked with some Bondi2 radii - it has some huge parameter sets as vector<double> but otherwise it's using the GPUs with addComputedValue(s) and I suppose I didn't need a GBVIForce unless we exhaust that list there but I liked the properties - I was looking at general variations on the theme for combining the implicit solvent MD with particle insertions (grand-canonical MC moves) and an MD integrator to kick it all around - maybe even docking a drug quickly with some clever tricks.  Those could be a lot closer to your examples, from the examples in my older code from circa 2013 - I can barely remember the details about some of these but they are here in my revived repo, and they were running in C++.

**Comment by peastman** [comment]
We have CustomGBForce implementations of a lot of standard models, including OBC and GBn2 among others, at https://github.com/openmm/openmm/blob/master/wrappers/python/openmm/app/internal/customgbforces.py.

**Comment by lukeczapla** [comment]
yep, those were the ones I had in the C++ so I'll check mine against those Python guys but yes I probably got em from you!

**Comment by lukeczapla** [comment]
I will try to run the C++ benchmarks too because there's always a difference between what is generalized (Python and C++ are about the same, CUDA always beats OpenCL on NVIDIA) and what you might see if you try it out.

**Comment by lukeczapla** [comment]
it wasn't super faster and they definitely had a CustomNonbondedForce in Python whereas I just used the built-in switching at 10 å and cutoff at 12å with the same PME grid spacing... 23 ns/day in C++ vs. 21 ns/day on the Python implementation.  The Python version throws a couple weird warnings about some duplicate improper dihedrals though (I could send them and I doubt they were severe), whereas my code for reading the CHARMM PSFs seemed to be fine loading in the entire files and assigning everything.
