### ISSUE TITLE
weird openmm warnings in miniconda3/lib/python3.8/site-packages/openmm/app/charmmparameterset.py

### ISSUE THREAD

**Issue by lukeczapla** [openmm/openmm#3348]
**Let me just paste this annoying thing below and somebody who cares please tell me if it's valid or somebody goofed up this charmmparameterset.py thing and I should just throw away a garbage simulation I'd run for like weeks on end because people do not even answer basic other questions about weird stuff like VRORV integrators and it's just some warnings but when I put it through my C++ and run it's totally legit with nothing weird - "tangentially related" (because me' own waterbox+1 silly cases do this too, not just Abl1 kinase) - I'm looking at what looks like a stupid simulation (VRORV integrator gives < T > ~= 307.5 not T = 310 K with both the basic and more simplified implementations) so if all this isn't addressed I would just wanna run something more solid.  Maybe some intelligence could scale that so you run it at approximately T = 312K or something and there's an exact formula (in which case, yes let's just put this dumb formula in there so people can specify 310 K and get what they mean)  that means that yields the < T > = 310 K but I do not study such things and we might have better experts to address this, totally bizarre to set it at T = 310 K and observe something else but I would fix it up like that if this is just like,that's what you get!!!  might as well just say something useful here so nobody else steals it or something, you learn a lot just by staring at the outputs**

/home/luke/miniconda3/lib/python3.8/site-packages/openmm/app/charmmparameterset.py:390: UserWarning: Replacing dihedral <DihedralType: k=0.5; phase=0.0; per=3> with <DihedralType: k=0.0; phase=180.0; per=3>
  warnings.warn('Replacing dihedral %r with %r' %
/home/luke/miniconda3/lib/python3.8/site-packages/openmm/app/charmmparameterset.py:390: UserWarning: Replacing dihedral <DihedralType: k=1.6; phase=180.0; per=1> with <DihedralType: k=0.6; phase=180.0; per=1>
  warnings.warn('Replacing dihedral %r with %r' %
/home/luke/miniconda3/lib/python3.8/site-packages/openmm/app/charmmparameterset.py:390: UserWarning: Replacing dihedral <DihedralType: k=0.6; phase=180.0; per=2> with <DihedralType: k=1.5; phase=0.0; per=2>
  warnings.warn('Replacing dihedral %r with %r' %
/home/luke/miniconda3/lib/python3.8/site-packages/openmm/app/charmmparameterset.py:390: UserWarning: Replacing dihedral <DihedralType: k=1.1; phase=180.0; per=1> with <DihedralType: k=2.5; phase=180.0; per=1>
  warnings.warn('Replacing dihedral %r with %r' %
/home/luke/miniconda3/lib/python3.8/site-packages/openmm/app/charmmparameterset.py:390: UserWarning: Replacing dihedral <DihedralType: k=0.3; phase=180.0; per=3> with <DihedralType: k=0.2; phase=0.0; per=3>
  warnings.warn('Replacing dihedral %r with %r' %
/home/luke/miniconda3/lib/python3.8/site-packages/openmm/app/charmmparameterset.py:390: UserWarning: Replacing dihedral <DihedralType: k=0.48; phase=0.0; per=3> with <DihedralType: k=0.16; phase=0.0; per=3>
  warnings.warn('Replacing dihedral %r with %r' %
/home/luke/miniconda3/lib/python3.8/site-packages/openmm/app/charmmparameterset.py:390: UserWarning: Replacing dihedral <DihedralType: k=0.4; phase=0.0; per=3> with <DihedralType: k=0.0; phase=180.0; per=3>
  warnings.warn('Replacing dihedral %r with %r' %
/home/luke/miniconda3/lib/python3.8/site-packages/openmm/app/charmmparameterset.py:390: UserWarning: Replacing dihedral <DihedralType: k=0.26; phase=0.0; per=3> with <DihedralType: k=0.2; phase=0.0; per=3>
  warnings.warn('Replacing dihedral %r with %r' %
/home/luke/miniconda3/lib/python3.8/site-packages/openmm/app/charmmparameterset.py:390: UserWarning: Replacing dihedral <DihedralType: k=0.77; phase=0.0; per=3> with <DihedralType: k=0.74; phase=0.0; per=3>
  warnings.warn('Replacing dihedral %r with %r' %
/home/luke/miniconda3/lib/python3.8/site-packages/openmm/app/charmmparameterset.py:390: UserWarning: Replacing dihedral <DihedralType: k=0.54; phase=0.0; per=2> with <DihedralType: k=1.4; phase=0.0; per=2>
  warnings.warn('Replacing dihedral %r with %r' %
/home/luke/miniconda3/lib/python3.8/site-packages/openmm/app/charmmparameterset.py:390: UserWarning: Replacing dihedral <DihedralType: k=1.08; phase=0.0; per=1> with <DihedralType: k=2.1; phase=0.0; per=1>
  warnings.warn('Replacing dihedral %r with %r' %
/home/luke/miniconda3/lib/python3.8/site-packages/openmm/app/charmmparameterset.py:390: UserWarning: Replacing dihedral <DihedralType: k=0.85; phase=180.0; per=2> with <DihedralType: k=0.55; phase=180.0; per=2>
  warnings.warn('Replacing dihedral %r with %r' %
/home/luke/miniconda3/lib/python3.8/site-packages/openmm/app/charmmparameterset.py:390: UserWarning: Replacing dihedral <DihedralType: k=0.1; phase=0.0; per=6> with <DihedralType: k=0.05; phase=180.0; per=6>
  warnings.warn('Replacing dihedral %r with %r' %
/home/luke/miniconda3/lib/python3.8/site-packages/openmm/app/charmmparameterset.py:390: UserWarning: Replacing dihedral <DihedralType: k=0.4; phase=0.0; per=3> with <DihedralType: k=0.01; phase=180.0; per=3>
  warnings.warn('Replacing dihedral %r with %r' %
/home/luke/miniconda3/lib/python3.8/site-packages/openmm/app/charmmparameterset.py:390: UserWarning: Replacing dihedral <DihedralType: k=0.3; phase=180.0; per=2> with <DihedralType: k=0.37; phase=0.0; per=2>
  warnings.warn('Replacing dihedral %r with %r' %
/home/luke/miniconda3/lib/python3.8/site-packages/openmm/app/charmmparameterset.py:390: UserWarning: Replacing dihedral <DihedralType: k=0.3; phase=0.0; per=1> with <DihedralType: k=0.35; phase=0.0; per=1>
  warnings.warn('Replacing dihedral %r with %r' %
/home/luke/miniconda3/lib/python3.8/site-packages/openmm/app/charmmparameterset.py:390: UserWarning: Replacing dihedral <DihedralType: k=0.38; phase=180.0; per=2> with <DihedralType: k=0.37; phase=0.0; per=2>
  warnings.warn('Replacing dihedral %r with %r' %
/home/luke/miniconda3/lib/python3.8/site-packages/openmm/app/charmmparameterset.py:390: UserWarning: Replacing dihedral <DihedralType: k=0.85; phase=180.0; per=1> with <DihedralType: k=0.35; phase=0.0; per=1>
  warnings.warn('Replacing dihedral %r with %r' %
/home/luke/miniconda3/lib/python3.8/site-packages/openmm/app/charmmparameterset.py:390: UserWarning: Replacing dihedral <DihedralType: k=0.35; phase=0.0; per=3> with <DihedralType: k=0.01; phase=180.0; per=3>
  warnings.warn('Replacing dihedral %r with %r' %
/home/luke/miniconda3/lib/python3.8/site-packages/openmm/app/charmmparameterset.py:390: UserWarning: Replacing dihedral <DihedralType: k=0.23; phase=180.0; per=3> with <DihedralType: k=0.19; phase=0.0; per=3>
  warnings.warn('Replacing dihedral %r with %r' %
/home/luke/miniconda3/lib/python3.8/site-packages/openmm/app/charmmparameterset.py:390: UserWarning: Replacing dihedral <DihedralType: k=0.55; phase=180.0; per=2> with <DihedralType: k=0.0; phase=0.0; per=2>
  warnings.warn('Replacing dihedral %r with %r' %
/home/luke/miniconda3/lib/python3.8/site-packages/openmm/app/charmmparameterset.py:390: UserWarning: Replacing dihedral <DihedralType: k=0.7; phase=180.0; per=2> with <DihedralType: k=0.0; phase=0.0; per=2>
  warnings.warn('Replacing dihedral %r with %r' %
/home/luke/miniconda3/lib/python3.8/site-packages/openmm/app/charmmparameterset.py:430: UserWarning: Repeat improper dihedral found ('CG2O3', 'OG2D2', 'OG2D2', 'CG311') and New param. k: 96.000000  ,thetaq: 0.000000 will use
  warnings.warn('Repeat improper dihedral found %r and New param. k: %f  ,thetaq: %f will use' %
/home/luke/miniconda3/lib/python3.8/site-packages/openmm/app/charmmparameterset.py:430: UserWarning: Repeat improper dihedral found ('CG2O3', 'OG2D2', 'OG2D2', 'CG301') and New param. k: 96.000000  ,thetaq: 0.000000 will use
  warnings.warn('Repeat improper dihedral found %r and New param. k: %f  ,thetaq: %f will use' %
/home/luke/miniconda3/lib/python3.8/site-packages/openmm/app/charmmparameterset.py:390: UserWarning: Replacing dihedral <DihedralType: k=0.5; phase=180.0; per=3> with <DihedralType: k=1.3; phase=180.0; per=3>
  warnings.warn('Replacing dihedral %r with %r' %
/home/luke/miniconda3/lib/python3.8/site-packages/openmm/app/charmmparameterset.py:390: UserWarning: Replacing dihedral <DihedralType: k=0.2; phase=0.0; per=3> with <DihedralType: k=0.14; phase=0.0; per=3>
  warnings.warn('Replacing dihedral %r with %r' %
/home/luke/miniconda3/lib/python3.8/site-packages/openmm/app/charmmparameterset.py:430: UserWarning: Repeat improper dihedral found ('CL', 'X', 'X', 'OBL') and New param. k: 100.000000  ,thetaq: 0.000000 will use
  warnings.warn('Repeat improper dihedral found %r and New param. k: %f  ,thetaq: %f will use' %
/home/luke/miniconda3/lib/python3.8/site-packages/openmm/app/charmmparameterset.py:390: UserWarning: Replacing dihedral <DihedralType: k=1.0; phase=0.0; per=2> with <DihedralType: k=8.5; phase=180.0; per=2>
  warnings.warn('Replacing dihedral %r with %r' %
/home/luke/miniconda3/lib/python3.8/site-packages/openmm/app/charmmparameterset.py:390: UserWarning: Replacing dihedral <DihedralType: k=0.2; phase=0.0; per=3> with <DihedralType: k=0.73; phase=180.0; per=3>
  warnings.warn('Replacing dihedral %r with %r' %
/home/luke/miniconda3/lib/python3.8/site-packages/openmm/app/charmmparameterset.py:390: UserWarning: Replacing dihedral <DihedralType: k=1.1; phase=180.0; per=2> with <DihedralType: k=1.0; phase=180.0; per=2>
  warnings.warn('Replacing dihedral %r with %r' %
/home/luke/miniconda3/lib/python3.8/site-packages/openmm/app/charmmparameterset.py:390: UserWarning: Replacing dihedral <DihedralType: k=1.0; phase=180.0; per=2> with <DihedralType: k=2.5; phase=180.0; per=2>
  warnings.warn('Replacing dihedral %r with %r' %
/home/luke/miniconda3/lib/python3.8/site-packages/openmm/app/charmmparameterset.py:430: UserWarning: Repeat improper dihedral found ('CG2O1', 'CG2R51', 'NG2S1', 'OG2D1') and New param. k: 120.000000  ,thetaq: 0.000000 will use
  warnings.warn('Repeat improper dihedral found %r and New param. k: %f  ,thetaq: %f will use' %

**Comment by peastman** [comment]
The warnings mean that you're providing parameter files that contain conflicting definitions for the same atom types.  For example, it found multiple definitions for dihedrals with the types ('CG2O1', 'CG2R51', 'NG2S1', 'OG2D1').  Take a look at your parameter files to figure out where the duplicates are coming from.  In some cases the parameters are quite different, so this likely indicates a problem.

Regarding the temperature, this is inherent in the VRORV algorithm.  The velocities it produces don't accurately reflect the Boltzmann distribution.  On the other hand, LangevinMiddleIntegrator (which uses the leapfrog version of the same algorithm) produces a very accurate distribution.  You might think that means it's more accurate, but in fact they produce identical trajectories.  I've never found a good explanation for why the half-step velocities follow the correct distribution and the on-step velocities don't.    See https://pubs.acs.org/doi/abs/10.1021/acs.jpca.9b02771 for more information about this.

**Comment by lukeczapla** [comment]
Thank you looking into this.  So I did see ('CG2O1', 'CG2R51', 'NG2S1', 'OG2D1') and I just wanted to clarify if all errors pertained to that group and nothing else until any other mentions? so it's nothing to me, silly streaming toppar.par when in my C++ I carefully feed the required stuff.

BUT, the other thing about these integrators.. wow

So yes, but if was as simple as VRORV doesn't **accurately reflect the Boltzmann distribution** yes I may have to throw it away entirely for my aMD work because I'm just trying to explain this to others the same way you would a Monte Carlo simulation distribution, everything is statistics, PMFs, the integrator just helps with sampling and the histogram reweighting.  you want rare events, milliseconds aint giving you much, stop trying so hard with conventional MD when 3 microseconds seems 3 days on A100 or what not.

So in the sense, yes in some other metrics, nobody would look at 307.5 K and 310 K and pick em apart.    you can come up with tons of maths that might not reveal much either too .  Thanks for showing me other options!!

**Comment by giacomofiorin** [comment]
@peastman Pretty much at the same time as the paper that you linked, Niels Grœnbech-Jensen also derived an unbiased definition of the discrete-step velocity:
https://doi.org/10.1080/00268976.2019.1570369
His derivation is focused on his own Langevin scheme (just like Liu works with his method), but is applicable to other Langevin schemes as well. The following paper fleshes out better the equivalency (with mathematical identities and numerical tests) with other schemes:
https://doi.org/10.1063/5.0066008

Following that framework, the issue is related to how the discretization errors are accommodated when deriving the Langevin scheme. For correct statistics, you impose conditions describing from the partition function and diffusivity of the free-particle and harmonic oscillator at the given temperature. But then you end up mathematically unable to also enforce an additional condition on the discrete-step velocities. If you choose instead to measure velocities halfway through a step in a leap-frog manner, that condition becomes enforceable and all statistics finally check out.

**Comment by peastman** [comment]
Thanks!  I'll take a look at those papers.

> but if was as simple as VRORV doesn't accurately reflect the Boltzmann distribution yes I may have to throw it away entirely for my aMD work

I don't think that's the case.  The positions do reflect a Boltzmann distribution.  And so do the half-step velocities.  It's only the on-step velocities that don't.

**Comment by lukeczapla** [comment]
> The positions do reflect a Boltzmann distribution. And so do the half-step velocities. It's only the on-step velocities that don't.

So my head may blow up on all these statements, the sampling of states (yes positions) NEEDS to follow a Boltzmann distribution, or I'm going to have to email people who suggested this and recommend rereading graduate texts like Frenkel and Smit's "Understanding Molecular Simulation". So now it's like a simulation at 307.5 K when 310 K was the specified target, are the positions obeying the Boltzmann distribution for T = 307.5K or 310K? I don't care about velocities at all but all of this is very confusing and that Middle step integrator sounds promising but I guess if it's all goofy I can use the A100 on AWS for about $30/day and be done in 6 days instead of 46 days. Nothing even seemed wrong with LangevinIntegrator (exactly mean T = 310K when specifying 310) or using Leap frog/Verlet with Andersen Thermostat.  Oy vey!

I appreciate your comment here though because it has to seem odd to anyone here, I just need the basic correct sampling for configurational part of Z (positions) for the target temperature like in MC.

**Comment by jchodera** [comment]
@lukeczapla : [This paper](https://www.choderalab.org/publications/2018/2/16/quantifying-configuration-sampling-error-in-langevin-simulations-of-complex-molecular-systems) sheds more light on what happens to the velocity distributions with Langevin integrators at various points throughout the integrator cycle. It also explains why the issues with velocity distributions having greater error for VRORV are irrelevant if accurate configurational sampling is desired. Be sure to check out Figs 1 and 3!

This figure didn't make it into the paper, but shows what happens at different points in the integrator cycle:
![image](https://user-images.githubusercontent.com/3656088/143619938-9dd893d1-5854-4feb-8bd0-982966e5c5e1.png)

**Comment by lukeczapla** [comment]
So big V smaller V.   Very complicated but as long as it is actually reproducing a Boltzmann distribution of positions it is totally fine with me.   The pseudo-time trajectory of an aMD is not ENTIRELY meaningless (it's interesting though), but floppy dihedrals tend to get knocked around easier and as long as the histogram reweighting is done correctly, you're still sampling the rare states with the absolute correct weights for their contribution to the configurational portion of that partition function.   So yes, of course it's cheating time, but a MC simulation doesn't have time at all, it's just too inefficient for most dense particle systems (perfect for implicit solvent to mix with MD though) but I do know one guy Mihaly Mezei at Mt. Sinai who showed me some techniques to counter that too (moves for dense water systems), but it's very unusual and creative work to make it happen.

**Comment by peastman** [comment]
The first of the two papers @giacomofiorin cited does a good job of explaining an essential point: the "velocity" that appears in the Verlet algorithm isn't really the velocity of the particles.  It's just an internal parameter that corresponds to a low order approximation.  For many purposes you can treat it as velocity, but it's always less accurate than the positions.

**Comment by lukeczapla** [comment]
Thanks, yes if I spend too much time in this thread I'll be developing Accelerated Monte Carlo!  But thank you for these explanations - I really like John's paper, very well done, but I'm going to wager a common sense guess here that the integrator ain't going to get you all THAT much here - K-L divergences are interesting and we're sitting on a manuscript with these for DNA tetramers at the moment and it's kinda interesting but not really "down to earth" that people would really be reading if not for their interest in mathematics, so the pictures and figures are enough for me.  seems we have to start writing a second manuscript to even get anything reasonable done and I think this Pasi et. al. paper made a mistake and reported the twist of parmbsc0 DNA simulation libraries as 32.5 degrees when it should've been 35.3 degrees, and nobody but me checked one of those guys' work.

**Comment by lukeczapla** [comment]
Mezei certainly found it hilarious when I emailed him and spent like 4 hours just chilling out with him over there at Mt. Sinai for no good reason but to learn, it's good that someone thinks you're a "rock star" but in the Monte Carlo world I was totally impressed and with an NVIDIA A100 benchmarks start to become a joke, let's get something new out there, right?  Just impractical compared to other things that would assist in this endeavor for something novel.
