### ISSUE TITLE
examples folder for developer's guide?

### ISSUE THREAD

**Issue by lukeczapla** [openmm/openmm#3349]
it's not much of a developer's guide without something to cross reference so like for example - I want to just do some trivial stuff like use some GPU buffers in OpenCL for a use case I described in some detail where it improves mathematics/statistics/etc.  storing these cool things we define like CustomCVForce junk (you might not even want a force but if you do it helps you too!!!) in buffers so you can specify the exact reporting time and poll your output.  very basic problem where obscuring code by just writing a "Developer's Guide" to someone who is just on Github (and maybe not in some fancy group at Stanford where everyone's too cool) would've been smarter from the start.  GPU memory is super cheap these days and we need to ask for specific things beyond just scaling to handle extra devices, that's actually not the worst problem in the world from my experience with other packages too. 

So that is my request - just copy something into a folder, call it example - because it does not need to be plural! just CPU/OpenCL and if you really want CUDA too it would be fine, that's some annoying thing with the stupid nvcc where if you just want my OpenCL matrix multiplication benchmarks and all that linear algebra nonsense I'll post a new "joke repo" for you too to try to give something back here because you're likely just invoking LAPACK and other stuff like DL4j and a few other things for some of that.  All of this is worth putting out and studying, not just giving people Makefiles with the (c) 2009 which is old enough so I updated something for you at least in my adventures.  CUDA is literally just another stupid wasteful layer so I'll drop my opencl repo if anyone wants to talk like super basic kernels that are not tied to the format of the C++ routines you need for OpenMM plugins and stare at straight gcc code (i dont want a nvcc, I'll show you a gcc solution first), no gimmicks.

**Comment by lukeczapla** [comment]
If you unpack all of the things I just brought up (I don't know who's even a programmer here like this, just Eastman?) and have something intelligent to contribute on these issues, let me know.  If that sounds like dribble, you aren't the person to answer my question.

**Comment by peastman** [comment]
I think this may be what you're looking for?

https://github.com/openmm/openmmexampleplugin

> you guys took the $$ and swallowed the CUDA poison

Comments like this really aren't appropriate.  Please keep the discussion professional and respectful to everyone involved.

**Comment by lukeczapla** [comment]
oh that's awesome too, it would've been a lot easier to just provide that but I'm looking at #3351  and also this and a developers guide with no mention of even a Lepton expression is not very helpful - yes it's a great enhancement but are you talking to yourself there?

**Comment by lukeczapla** [comment]
So let's keep this simple, here was an old example and I came up with a better way than what you might google for getting it on the Mac too where playing with the device # would be lots of fun (your latest might not even permit copying into /System/Frameworks).  We do need definitions of a few things not even mentioned in Developer's Guides - so let's store stuff and do more than run a silly test.  Makefile was fine on Linux (I can write the sudo apt-get versions for Debian/Ubuntu and the slickest one on Docker right now is Bullseye!) but ./buildmac shows you it's still not a convoluted vendor-dependent game.

https://github.com/lukeczapla/opencl

**Comment by jchodera** [comment]
@lukeczapla : Some comments in this thread are clearly in violation of the OpenMM [Code of Conduct](https://github.com/openmm/openmm/blob/master/CODE_OF_CONDUCT.md). Please make sure to keep the discussion focused on constructive comments regarding how we can better serve the molecular simulation community.

Also, it helps to focus on a single issue or technical question at a time in a thread. It's hard for me to follow specifically what the concrete questions our suggestions are in a number of these threads.

**Comment by lukeczapla** [comment]
ok, tried to edit some stuff out/remove and all - I can certainly play with the suggested repo https://github.com/openmm/openmmexampleplugin when getting documentation could take a lot more work, the request is here and yes when things are not in developer's guides at all it's tough, where does one begin to comprehend some of these thoughts about Lepton(s), I can only spin up and spin down with a whole integer and obviously it's about the technology and not my joke so maybe I even get a little info as hints and collect them.  there was a good suggestion about the VRORV in another one too in #3348 , might be time to think of other options too.
