### ISSUE TITLE
Vectorize Lepton expressions

### ISSUE THREAD

**Issue by peastman** [openmm/openmm#3351]
With the OpenCL and CUDA platforms, there's little difference in speed between standard forces and equivalent custom forces.  On the CPU platform, there can be a much bigger difference.  That's especially true for CustomNonbondedForce.

The main reason for this is that Lepton expressions don't get vectorized.  NonbondedForce uses the vector unit to evaluate 4 or 8 interactions at once, but CustomNonbondedForce needs to evaluate them one at a time.  Implementing vectorization of expressions would make CustomNonbondedForce a lot faster on the CPU platform.

This also could help with #3229, since vectorization would allow the numeric integrals to be computed much more quickly.

**Comment by lukeczapla** [comment]
@peastman Are the Lepton expressions those strings with formulas that everyone's using?  It's a bit like an old scripting language but with very powerful math syntax for derivatives and integration and all.  Here is what I am trying to write:

saveGlobalVariable(1, 5000);   // it would mean to save value once every timestep and copy to main RAM every 5000 steps
                                                    // if your platform is a GPU or "interesting" OpenCL device
So now would that be a plugin or also just a new feature too?  I know I need one for each platform and the Reference would be easy, is the only difference between Reference and CPU is that CPU can take advantage of say, 72 cores on a fancy HPC server?   Global variables are always type "real" (i.e., single/double) or could they be integers too?

>  With the OpenCL and CUDA platforms, there's little difference in speed between standard forces and equivalent custom forces. On the CPU platform, there can be a much bigger difference. 

This is true, I wrote my C++ code to use the standard forces (SwitchingDistance + Cutoffs) to approximate the force-switching used by some CHARMM CustomNonbondedForce from Im's lab, and it was barely any different in ns/day between the custom and built in variants with everything else (PME spacings and all factors).   23 ns/d vs. 21.5 ns/d - now looking at the difference between the Python and C++ one to see if anything comes out, meaning running both on the same basic GPU.

> The main reason for this is that Lepton expressions don't get vectorized

So if we write a ComputePerDof variable for example, you want to arrange the data linearly or linearly packed for things like SIMD GPU routines?  Even with 3D data (bins in space) I had a problem like 15 years ago and could do something like linearly packing it and getting the most out of, e.g., the 2-4 GB of CPU RAM at the time.  The GPUs now have even more than that.

Which .cpp files in the code should I look for to get a heads up on this whole system, like are there parsing routines or anything for the lepton expressions or is in an existing library?  I always found that stuff interesting, in my youth forever ago I was writing this little scripting language so you could define a few variables and do things like program text to go up and down (across, diagonal) and do tricks on a connecting modem's VGA display with ANSI, certainly didn't have any integration or differentiation parts though!

**Comment by peastman** [comment]
This would only affect the CPU platform.  As far as the code is concerned it would be a new feature, but from the user perspective there would be no visible changes.  It would just run faster.

The code is in `libraries/lepton`.  See especially the Parser and CompiledExpression classes.

>  Here is what I am trying to write:

That's unrelated to this feature.  If you want to ask how to do something, please open a separate issue for it.  Adding unrelated discussion to issues makes the issue tracker much less useful for everyone.

**Comment by lukeczapla** [comment]
> This would only affect the CPU platform. As far as the code is concerned it would be a new feature, but from the user perspective there would be no visible changes. It would just run faster.
> 
> The code is in `libraries/lepton`. See especially the Parser and CompiledExpression classes.

Thanks, so on that other note above, those OMP # pragma optimizations seem not so great compared to other parallelization routines I've seen for other languages, so on this CPU platform what kinds of options best help the issue.

Is it so specific that now with the Mac M1 ARM and also so many x86_64 that it has to be one for both?  Because different chips might have different CPU SIMD features.. at least they'd all support those existing optimizations

**Comment by peastman** [comment]
Yes, the compilation is specific to a particle architecture.  See #3350.
