### ISSUE TITLE
No module named simtk.testInstallation

### ISSUE THREAD

**Issue by AngeloRaymondRossi** [openmm/openmm#3356]
Hello,

I installed miniconda and used it to install OpenMM:

conda install -c conda-forge opem,

I also installed opemmtools.

It seems as if everything is installed in /home/rossi/miniconda3

AmberTools/  LICENSE.txt            amber.sh*         conda-meta/  dat/   include/  licenses/  pymbar/  shell/  x86_64-conda-linux-gnu/
GNU_LGPL_v3  amber-interactive.sh*  bin/              condabin/    envs/  lib/      man/       sbin/    ssl/    x86_64-conda_cos6-linux-gnu/
LICENSE      amber.csh*             compiler_compat/  config.h     etc/   libexec/  pkgs/      share/   test/

(base) Mon Nov 29 16:53:08 [rossi@debian OpenMM]$    python3 -m simtk.testInstallation
/home/rossi/miniconda3/bin/python3: No module named simtk.testInstallation

(base) Mon Nov 29 17:13:08 [rossi@debian OpenMM]$conda list | grep openmm
openmm                    7.6.0            py39h33ab577_0    conda-forge
openmmtools               0.20.0           py39h3811e60_1    conda-forge

Can you please help me with this?  Thanks so much.

Regards,

Angelo

**Comment by peastman** [comment]
It was renamed to `openmm.testInstallation`.  Is there somewhere in the documentation that still gives the old name?

**Comment by AngeloRaymondRossi** [comment]
Thanks so much for the quick reply.

 http://docs.openmm.org/7.0.0/userguide/application.html
Scroll down to 3.1 Installing with Conda; Go to step 4:
4. Verify your installation by typing the following command:

python -m simtk.testInstallation

**Comment by AngeloRaymondRossi** [comment]
Hooray!!!  It worked.

(base) Mon Nov 29 17:13:15 ***@***.*** OpenMM]$    python3 -m
openmm.testInstallation

OpenMM Version: 7.6
Git Revision: ad113a0cb37991a2de67a08026cf3b91616bafbe

There are 2 Platforms available:

1 Reference - Successfully computed forces
2 CPU - Successfully computed forces

Median difference in forces between platforms:

Reference vs. CPU: 6.29449e-06

All differences are within tolerance.
(base) Mon Nov 29 17:43:15 ***@***.*** OpenMM]$

**Comment by peastman** [comment]
>  http://docs.openmm.org/7.0.0/userguide/application.html

That's the documentation for version 7.0.  Instead try http://docs.openmm.org/latest/userguide/application.html.
