### ISSUE TITLE
Optimizing sorting when building neighbor list

### ISSUE THREAD

**Issue by peastman** [openmm/openmm#3357]
This is a followup to the discussion that started in #3347.  I'm moving it here so it won't get lost in the discussion for a merged PR.

When running the amber20-stmv benchmark parallelized across four A100s, @dmclark17 found `sortBuckets()` was taking a significant amount of time.  In contrast, when I run the same benchmark on a single Titan V that kernel takes very little time.  We want to figure out why that's happening and what we can do about it.

He observed that some blocks had very large numbers of elements, forcing it to use the slower code path that doesn't use shared memory.  It chooses the number of buckets so that the average number of elements in each bucket will be no more than half the maximum it can fit in shared memory.

https://github.com/openmm/openmm/blob/0c82c2647de98da5c6dab7bf7a7b8b19705aadc0/platforms/cuda/src/CudaSort.cpp#L71-L72

That ensures most buckets can be sorted with the fast path.  If the data is uniformly distributed, all of them will.  But if the distribution is very nonuniform, there could be some that require the slow path.

One solution is to increase the number of buckets further.  That would impact speed in several ways.

- It would reduce the number of buckets requiring the slow path.
- It would make each bucket faster to sort, since the bitonic merge sort scales as O(n*(log(n))^2).
- It would add some overhead in `computeRange()` and `computeBucketPositions()`.
- It could lead to some buckets having very few elements, which would mean some threads being left idle in `sortBuckets()`.

Another possible optimization is to try to skip the sort on steps when the neighbor list doesn't need to be rebuilt.  Here is how the code currently works.

1. `findBlockBounds()` clears the flag for whether a rebuild is needed.
2. We sort the blocks by the size of their bounding boxes.
3. `sortBoxData()` checks all atoms to see how far they have moved and sets a flag if any has moved far enough to require rebuilding.

Those operations don't have to be done in those particular kernels.  They were just convenient places to put them.  In principle we could do the check in `findBlockBounds()` instead, which would allow us to skip the sort if it isn't needed.  That would require the flag to get cleared at some earlier point, and also require the result to be sent back to the host.

**Comment by dmclark17** [comment]
I looked into the distribution of bounding box sizes for STMV for a single timestep, and it seems to be somewhat normally distributed. Additionally, 99.7% of the data is less than 3; however, the maximum value is 22.9. Because of the large range in sizes, I think we'd need about 4.5k buckets to avoid the global memory code path with the current thread-block size. CUB has some block-level sorting functions that allow for multiple items per thread; [here is the documentation](https://nvlabs.github.io/cub/classcub_1_1_block_radix_sort.html). This would allow for the buckets to be larger before going to the global memory version.

Another option would be to apply a transformation to the bounding box sizes to make the distribution more uniform. I did some experiments with `erf`, and the results look promising. For a single GPU, I am seeing 35.7ns/day vs ~33ns/day. However, I am a little worried that I am saturating `erf` for the large bounding boxes—what would happen if the bounding boxes weren't perfectly sorted?

**Comment by peastman** [comment]
> what would happen if the bounding boxes weren't perfectly sorted?

Results would still be correct, but performance might suffer a bit.  The neighbor list consists of blocks of 32 contiguous atoms interacting with arbitrary sets of 32 atoms.  The algorithm to build it is basically

```
for block1 in 0 to numBlocks
  for block2 in block1+1 to numBlocks
    for each atom in block2
      if the distance from block1's bounding box to the atom < cutoff, add it to the list
```

By sorting the blocks, we ensure it's always comparing the smaller bounding box to individual atoms from the larger one, which leads to fewer interactions being included.

**Comment by dmclark17** [comment]
I found that the bounding box transformation gave about a 10% improvement for 4 and 8 GPUs. The change was smaller for 1 and 2 GPUs. Specifically, I used the normal distribution's CDF to do the transformation in the `findBlockBounds` kernel—the overhead to the kernel was minimal. Given the range of the data and how fast `erf` goes to 1, I am fairly confident that the largest bounding boxes were not being sorted correctly as all of their sizes mapped to 1.0. I am currently hard coding the mean and variance of the distribution, so I'm not sure if this will be as effective for other systems—I'm not sure how much bounding box size distributions change over time either.

How do you feel about this method of optimization? While it does work for STMV, it makes assumptions about the distribution of bounding box sizes. 

Here is a screenshot of the new timeline for 4xA100—it seems like the load balancing will be a promising place to look next!

![image](https://user-images.githubusercontent.com/30421289/144544608-f004aa58-c9e9-4260-8170-7090c58c3870.png)

**Comment by peastman** [comment]
> I found that the bounding box transformation gave about a 10% improvement for 4 and 8 GPUs.

Do you mean the overall speed was 10% faster, or just that sorting was 10% faster?

> I am currently hard coding the mean and variance of the distribution, so I'm not sure if this will be as effective for other systems—I'm not sure how much bounding box size distributions change over time either.

The distribution does vary between systems.  For example, the boxes tend to be smallest for water, a bit larger for proteins (because it can't reorder the atoms for compactness), and even larger for lipids (the long chains aren't very compact).  If you use a four or five point water model, that means more particles in the same space, so the boxes are smaller.  Or if you use a coarse grained model, that makes them larger.

**Comment by peastman** [comment]
It looks like the problem is really a matter of outliers.  Most box sizes are in the same general range.  The distribution isn't necessarily uniform, but they do follow a reasonable distribution.  Then there are a handful of outliers with much larger or smaller boxes.  They skew the range and force most data into just a few buckets.

With DHFR and ApoA1, this doesn't come up.  In those cases, the number of boxes is small enough that it uses the short list kernel instead.  It only becomes an issue on the larger systems.

**Comment by peastman** [comment]
One solution would be to make the sorting code better at handling outliers.  `computeRange()` scans the data to find the minimum and maximum values.  It could also compute the mean and standard deviation at the same time and limit the range based on them.  I'm trying to think of any situations where that would cause problems.  So far I haven't thought of any.

**Comment by dmclark17** [comment]
I agree that the outliers are the source of the problem. Are you thinking that the outliers could be placed in a separate bucket? i.e. have a special bucket from the limited upper range to infinity?

**Comment by peastman** [comment]
I tried to implement this.  I don't quite understand the results.  Here is my modified version of `computeRange()`.

```c++
__global__ void computeRange(const DATA_TYPE* __restrict__ data, unsigned int length, KEY_TYPE* __restrict__ range,
        unsigned int numBuckets, unsigned int* __restrict__ bucketOffset) {
    extern __shared__ KEY_TYPE minBuffer[];
    KEY_TYPE* maxBuffer = minBuffer+blockDim.x;
    KEY_TYPE minimum = MAX_KEY;
    KEY_TYPE maximum = MIN_KEY;
    float sum = 0;
    float sum2 = 0;
    float* sumBuffer = (float*) (maxBuffer+blockDim.x);
    float* sum2Buffer = sumBuffer+blockDim.x;

    // Each thread calculates the range of a subset of values.

    for (unsigned int index = threadIdx.x; index < length; index += blockDim.x) {
        KEY_TYPE value = getValue(data[index]);
        minimum = min(minimum, value);
        maximum = max(maximum, value);
        float v = value;
        sum += v;
        sum2 += v*v;
    }

    // Now reduce them.

    minBuffer[threadIdx.x] = minimum;
    maxBuffer[threadIdx.x] = maximum;
    sumBuffer[threadIdx.x] = sum;
    sum2Buffer[threadIdx.x] = sum2;
    __syncthreads();
    for (unsigned int step = 1; step < blockDim.x; step *= 2) {
        if (threadIdx.x+step < blockDim.x && threadIdx.x%(2*step) == 0) {
            minBuffer[threadIdx.x] = min(minBuffer[threadIdx.x], minBuffer[threadIdx.x+step]);
            maxBuffer[threadIdx.x] = max(maxBuffer[threadIdx.x], maxBuffer[threadIdx.x+step]);
            sumBuffer[threadIdx.x] += sumBuffer[threadIdx.x+step];
            sum2Buffer[threadIdx.x] += sum2Buffer[threadIdx.x+step];
        }
        __syncthreads();
    }
    if (threadIdx.x == 0) {
        sum = sumBuffer[0];
        sum2 = sum2Buffer[0];
        float mean = sum/length;
        float std = sqrtf(sum2/length-mean*mean);
        minimum = max(minBuffer[0], (KEY_TYPE) (mean-4*std));
        maximum = min(maxBuffer[0], (KEY_TYPE) (mean+4*std));
        range[0] = minimum;
        range[1] = maximum;
    }
    
    // Clear the bucket counters in preparation for the next kernel.

    for (unsigned int index = threadIdx.x; index < numBuckets; index += blockDim.x)
        bucketOffset[index] = 0;
}
```

On amber20-cellulose it produces a small but significant speedup.  The overall ns/day increases from 49.8 to 52.9.  Looking at it in nvprof, `computeRange()` gets a little slower (average time increases from 94.5 to 113.5 us), but `sortBuckets()` gets a lot faster (average time decreases from 322.1 to 106.5 us).

But on amber20-stmv, it actually gets slower.  `sortBuckets()` increases from 595.8 to 899.4 us, and the overall ns/day decreases from 15.10 to 14.99.

Here is a graph of the number of elements in each bucket for STMV.  The change makes the distribution a lot more even, though it's still far from being uniform.  For some reason, that makes it slower.

![image](https://user-images.githubusercontent.com/4379786/145268395-e5a6242d-a4da-4283-a6d9-73b18dc85143.png)

**Comment by peastman** [comment]
Other ideas for possible optimizations.

- We could do a more sophisticated transformation of the values to make them have a uniform distribution.  For example, randomly sample 64 elements from the array, sort them, take them as defining the distribution, and assign buckets accordingly.
- We could do something more sophisticated in `sortBuckets()` when a bucket can't fit in shared memory.  For example, use a quicksort that recursively subdivides it until we reach a number of elements that can fit in shared memory, then use the bitonic merge sort.
- Possibly there's a totally different sorting algorithm (something different from bucket sort followed by bitonic merge sort) that would be faster.  Do you have any advice on the current state of the art for GPU sorting algorithms?

**Comment by dmclark17** [comment]
I am not too familiar with state of the art GPU sorting algorithms, but I can look into it more. [CUB](https://github.com/NVIDIA/cub) has very well optimized sorting routines, and it is open-source and included in recent versions of CUDA. I experimented with the [`cub::DeviceRadixSort::SortKeys`](https://nvlabs.github.io/cub/structcub_1_1_device_radix_sort.html#aac3b51925d55aa4504a29cb1379ae42e) function to sort data from STMV and found that it took about 200us on a Titan V. It doesn't support vector types out of the box, but we can limit the bits used for key comparison to get the desired behavior.

Since this function is called from the host, I don't think we could do runtime compilations easily. Would it be possible to add some non-JIT CUDA components to OpenMM?

**Comment by peastman** [comment]
Interesting, I'll have to look at CUB to see how they apply radix sort to floating point values.

> Would it be possible to add some non-JIT CUDA components to OpenMM?

I'd prefer not to.  It would make our build process a lot more complicated.

**Comment by peastman** [comment]
Looks like they use a very simple transformation:

https://github.com/NVIDIA/cub/blob/703b10a92ad5e21c65446108696d4e3d428d5f04/cub/device/device_radix_sort.cuh#L84-L90

```
 * To convert the input values into a radix-sortable bitwise representation,
 * the following transformations take place prior to sorting:
 *
 * - For unsigned integral values, the keys are used directly.
 * - For signed integral values, the sign bit is inverted.
 * - For positive floating point values, the sign bit is inverted.
 * - For negative floating point values, the full key is inverted.
```

That's simple enough.

**Comment by peastman** [comment]
@dmclark17 can you post the code you used to sort the data with CUB?  I'd like to try it out.  Since it's bundled with CUDA 11.0 and later, one option would be to write code to use it guarded by `#if CUDA_VERSION >= 11000`.

**Comment by peastman** [comment]
I'm very confused.  I spent the last day writing a much more sophisticated version of the bucket assignment code.  It collects samples, maps out the distribution, and uses it to assign them in a much more uniform way.  Here is the result.

![image](https://user-images.githubusercontent.com/4379786/145475680-6ace17b2-e609-44ce-8b62-54510a06377f.png)

You can see it's now doing a much better job of distributing the elements between buckets.  The result?  The average time for `sortBuckets()` increased dramatically, from 582 us to 8078 us.

I think we may have misunderstood what the actual cause of the slowness is.

**Comment by peastman** [comment]
Sorry, the labels "original" and "modified" are swapped in the graph.  The blue curve is the modified one.

**Comment by dmclark17** [comment]
To clarify, I ran the host API CUB sorting outside of OpenMM—I just saved the (bucket size, index) data and benchmarked sorting them offline. I wasn't sure how to use the host API within OpenMM. Are you still interested in the code? 

Could we record how many thread-blocks take the global memory code path? The threshold is 256 elements in the bucket, correct? Based on the graph, it seems like there are a lot of buckets very close to the threshold.

**Comment by peastman** [comment]
> Are you still interested in the code?

Sure, that could still be helpful.

> Could we record how many thread-blocks take the global memory code path?

It varies quite a bit.  It can be as low as about 10 or as high as about 50.  That's out of 260 buckets total.

**Comment by dmclark17** [comment]
Is that for the original or modified distribution?

If you'd like to test it, here is the transformation I did to the block size in `findBlockBounds`

https://github.com/openmm/openmm/blob/92c6dbb35c63af86bce0d9436e677acfcdc8aa20/platforms/cuda/src/kernels/findInteractingBlocks.cu#L43

```
        const double mean = 1.73465118;
        const double std  = 1.0 / (0.57397992 * sqrt(2.0));
        const double block_size = blockSize.x+blockSize.y+blockSize.z;
        const double sort_val = erf((block_size - mean) * std);
        sortedBlocks[index] = make_real2((real) sort_val, index);
```

It is definitely a less robust method, but it may be an interesting data point.

**Comment by peastman** [comment]
It looks like CUB is defined entirely by header files.  There's no library.  Which I guess means you can't use it if you aren't compiling your host code with nvcc?

**Comment by dmclark17** [comment]
That is my understanding as well—NVRTC doesn't support host code, so I think we'd have to use nvcc. 

I think we could do system calls to `nvcc` at runtime to create a shared library and then load it with `dlopen`.

**Comment by peastman** [comment]
I tried an experiment to better understand what's going on.  I first sorted the data on the CPU so I could freely divide it up between buckets however I wanted without changing the correctness of the results.  Then I made it evenly divide the samples between N buckets, leaving the remaining buckets (out of 260 total) empty.  Here is the execution time of `sortBuckets()` on a Titan V as a function of the number of non-empty buckets.

| Buckets | Time (us) |
| --- | --- |
1 | 4754.7
2 | 3412.7
3 | 2949.5
5 | 973.64
10 | 343.95
15 | 683.66
20 | 915.43
25 | 242.24
30 | 209.85
50 | 168.72
80 | 166.09
129 | 174.77
130 | 157.32
131 | 149.71
200 | 134.20
260 | 154.80

Not surprisingly, putting all the data into a single bucket is very slow.  That means a single thread block does a bitonic merge sort of the entire list.  Dividing it between more buckets improves the speed.  But then something weird happens and it gets slower again.  Why is 20 buckets much slower than 10???  I repeated the test to make sure it was reproducible.  After peaking somewhere around 20 buckets it gets faster again.

At 129 buckets, each one of them has at least 257 elements and therefore uses the slow path.  At 131 buckets, every one of them has 256 or fewer elements and therefore uses the fast path.  That makes it a little faster, but the difference isn't that big.  Which path it takes in the kernel clearly isn't the main factor determining speed.  Also notice that even with only 50 blocks, it's already getting close to optimal speed.  The GPU has 80 SMs, so 30 of them are left sitting idle.  But increasing the number of blocks from 50 to 80 doesn't make a significant difference.

**Comment by peastman** [comment]
The numbers above are a bit misleading.  CudaSort gets used in two places, during building the neighbor list and also during PME charge spreading.  My changes to redistribute the elements between buckets only affected the first one, but the timings for `sortBuckets()` were averaged over both.  The list that gets sorted in PME is actually much larger, but the elements are uniformly distributed, so it doesn't have the same problems.

I switched off PME so I could get timings for only the calls to `sortBuckets()` we care about here.  Here are the results.

| Buckets | Time (us) |
| --- | --- |
1 | 5458.2
10 | 332.74
20 | 137.60
50 | 63.895
80 | 40.501
129 | 37.359
131 | 15.476
200 | 15.510
260 | 15.694

That makes a lot more sense now.  The time decreases steadily with increasing buckets up to about 80.  At that point all SMs have something to do, and there is little change until we reach the point where it switches over to the fast path.  There's an abrupt 2x speedup there, and then no further improvement with more buckets.

**Comment by peastman** [comment]
With PME turned off, I now see a clear benefit from the optimization I described in https://github.com/openmm/openmm/issues/3357#issuecomment-990320345.  `sortBuckets()` is much faster, from 419 us down to 146 us.  Although `assignElementsToBuckets()` is now more complicated, its runtime is basically unchanged at 16 us, indicating its speed is limited by memory instead of compute.  And as a bonus, it eliminates the need for `computeRange()`, which takes about 20 us.  So overall it's a big speedup.

The reason I didn't see that before is that the change was also being applied during charge spreading, which sorts a much larger but uniformly distributed list.  My change ended up making that sort much less balanced, not more balanced.

**Comment by dmclark17** [comment]
Nice! Good to hear the change worked! Do you think it would make sense to have different code paths for the PME sorting and nonbonded sorting?

**Comment by peastman** [comment]
Exactly.  I'm working on a PR with the changes.  I've added an optional `uniform` argument to the constructor so you can tell it whether you expect the data to be uniformly distributed.

**Comment by aizvorski** [comment]
@peastman @dmclark17 Just saw this - very exciting!

I have some very basic questions about what the sort we're doing here is for.  I assume this is related to building a list of blocks over which to compute nonbonded interactions?  

Is there a description somewhere in the docs of how the block-list-building algorithm works?  I've seen this http://docs.openmm.org/latest/developerguide/06_opencl_platform.html#reordering-of-particles but I probably don't completely understand it, as it seems only identical molecules are reordered.  Does that mean that within (eg) a protein the atoms stay in the original order, and the blocks are just every consecutive 32 atoms - so there would be lots of blocks in which only a couple of atoms are close enough to interact?  How often are the blocks and block-pairs list recalculated?  Also - what data structure is the block-pairs list stored in, and is there a good place in the openmm code to dump a list of the block-pairs for which nonbonded interactions would be calculated at each step?

I've been thinking about how to divide a system into efficient blocks (essentially: based on space filling curves) and I have some ideas but I'd like to understand how things work now and see what the blocks used in practice are before I try the stuff I'm thinking of.  Thanks!

**Comment by peastman** [comment]
It starts by dividing the atoms into "blocks".  A block consists of 32 consecutive atoms.

The neighbor list is made of "tiles".  Each tile contains 1024 interactions: 32 atoms interacting with a different set of 32 atoms.  The first set is a consecutive atom block.  The second set can be any 32 atoms, not necessarily consecutive.

Here's a description of the algorithm used to build the neighbor list.

https://github.com/openmm/openmm/blob/130124a3f9277b054ec40927360a6ad20c8f5fa6/platforms/cuda/src/kernels/findInteractingBlocks.cu#L132-L151

For this neighbor list to be efficient, we need blocks of 32 consecutive atoms to be spatially compact.  Two methods are used to ensure that.  The first is reordering of molecules, as described in the developer guide.  If you want to see exactly how it's done, take a look at `ComputeContext::reorderAtomsImpl()`.  The second method is to ensure that while we're building the neighbor list, we always prefer compact blocks.  When it's comparing two blocks as described above, the more compact one should be block X (the one that gets used as a contiguous block).  The less compact one should be used as block Y (the one from which we select individual atoms).

Before invoking `findBlocksWithInteractions()`, we therefore first sort the list of blocks by spatial size.  That's the sort I just optimized.  The list isn't that big (# atoms/32), but block sizes tend to follow a very nonuniform distribution, which was making the bucket sort not very effective.

**Comment by aizvorski** [comment]
Hi @peastman - Thanks!  This is a very nice explanation.  I incorrectly had assumed the tile was 32 consecutive x 32 consecutive.  

So, does that mean that if an atom y from the second set is within the cutoff from any atom in the fist set (consecutive block X), there will be a tile that contains all y-X pairs? (where not all of those are within the cutoff)  What happens to pairs outside the cutoff - they are skipped but those threads have to wait for the ones that are calculating the interactions?  Do you have any stats on the fraction of pairs within the cutoff for typical systems? (ie "tile utilization efficiency")

Also, in terms of memory reads, if the second sets are arbitrary, is the number of memory reads (from global memory) proportional to the number of pairwise interactions evaluated?  (since the access of atom parameters from the second sets is essentially random access)

**Comment by jchodera** [comment]
I [recently came across this paper](https://onlinelibrary.wiley.com/doi/10.1002/jcc.20071) on efficient pairlist construction using grid cells and mask arrays. Presumably, our current algorithm offers considerable advantages over this on GPUs?

**Comment by peastman** [comment]
> Do you have any stats on the fraction of pairs within the cutoff for typical systems?

I've looked at that in the past, but it's been a long time so I don't remember the exact numbers.  It's a significant fraction that end up being beyond the cutoff and getting skipped.

> is the number of memory reads (from global memory) proportional to the number of pairwise interactions evaluated?

No, it only loads the data for each atom once.  The memory access is less efficient since it can't be completely coalesced, but it isn't completely random either.  Due to the algorithm used to build the list, the atoms still tend to be close together in sequence.

Setting the tile size to 32x32 is a tradeoff between compute and memory.  Reducing it to 16x16 would mean fewer extra interactions that are beyond the cutoff, so it would save computing time.  But it also would double the amount of memory access (load 32 atoms to compute 256 interactions, rather than load 64 atoms to compute 1024 interactions).

**Comment by aizvorski** [comment]
> I [recently came across this paper](https://onlinelibrary.wiley.com/doi/10.1002/jcc.20071) on efficient pairlist construction using grid cells and mask arrays. Presumably, our current algorithm offers considerable advantages over this on GPUs?

@jchodera Thanks for the paper! I only did a quick read but it doesn't seem to address building a tilelist, only a pairlist.  The same idea (mask array) can probably be adapted for tilelist just by using larger cells but they didn't try that.

Re: GPU, I think openmm is entirely memory-bound, so anything that either reduces memory accesses or makes memory access more efficient (eg by coalescing reads) would be a win.  This basically has to be some kind of tiling scheme, but what exact kind is the trick :)

The tilelist building itself can be amortized over a fairly large number of steps, so that probably doesn't limit speed - building a more efficient tilelist slower would probably still be better.  The measure of tilelist efficiency is something along the lines of "total data read from global memory per step" in combination with total number of separate (non-coalesced) reads and maybe some more subtle things about the access pattern.

**Comment by peastman** [comment]
> I think openmm is entirely memory-bound

Are you talking about building the neighbor list?  That might be.  But computing interactions is balanced between compute and memory.  Both are significant.  If they weren't, I would have already changed the tile size.

> The tilelist building itself can be amortized over a fairly large number of steps

It used to typically rebuild the neighbor list every 4-5 steps.  Then we introduced LangevinMiddleIntegrator, which let us increase the step size in most simulations from 2 to 4 fs.  Now it usually rebuilds the neighbor list every other step.  We can control that, of course, by changing the amount of padding added when building the list.  The current value has been tuned to give near optimal performance in most simulations.

**Comment by aizvorski** [comment]
> I've looked at that in the past, but it's been a long time so I don't remember the exact numbers.

@peastman I'm really curious about that - is there a way to patch openmm so it dumps the exact tilelist that would be used before calling the computeNonbonded kernel so we can get some real-life numbers?

> No, it only loads the data for each atom once. 

Hmm - it loads the data for each atom once per tile, not once per step, right?  

(Back of the envelope, in a water box there are 140 molecules within a 1nm cutoff, so each atom would be within the cutoff of `3*140` other atoms, so each atom would be in at least `3*140/32 = ~13` tiles, assuming perfect tiling efficiency.   That is not quite one memory read per interacting pair, but it is one memory read per interacting pair*efficiency/32, so total memory reads seem to be proportional to the number of pairs)

**Comment by peastman** [comment]
One other detail.  It actually maintains a separate list of single interacting pairs, that get computed in their own loop.  Remember that it has identified which atoms of block Y are within the cutoff distance of any atom of block X.  If the number is less than some cutoff, it puts them into the single pairs list instead.

https://github.com/openmm/openmm/blob/130124a3f9277b054ec40927360a6ad20c8f5fa6/platforms/cuda/src/kernels/findInteractingBlocks.cu#L100-L107

`MAX_BITS_FOR_PAIRS` depends on the architecture: 4 on Ampere, 2 on earlier architectures.  These interactions get computed in a memory-inefficient way, loading two atoms for a single interaction.  But that's still more efficient than having an entire warp compute 32 interactions when 31 of them are beyond the cutoff.

Anyway, if you want to know what fraction of interactions are actually computed, the easiest approach would probably be to add debugging code to `nonbonded.cu`.  There are several different blocks that compute different sets of interactions, but here is the point you care about:

https://github.com/openmm/openmm/blob/130124a3f9277b054ec40927360a6ad20c8f5fa6/platforms/cuda/src/kernels/nonbonded.cu#L444-L446

Immediately after that, check whether `r2 < CUTOFF_SQUARED`.  Have each thread keep track of how many interactions it computes and what fraction are outside the cutoff, then print out the result at the end of the kernel.

Note that there are two reasons an interaction might be beyond the cutoff.  1) We included that atom because it's within the cutoff distance of some other atom.  2) It's within the padding distance we added to the cutoff so we wouldn't need to rebuild the neighbor list every step.

**Comment by aizvorski** [comment]
@peastman Thanks!  I'll try to collect the tilelist and single pairlist info when I have a chance.  

I collected some data on overall memory access/utilization with nsight-compute, see new issue #3389 - we can continue there.

**Comment by ex-rzr** [comment]
That's interesting. I also noticed this issue during our work on HIP support. I came to this solution for "faster" distribution:
https://github.com/openmm/openmm/pull/3338/commits/34a986e1dab2e74202cb06434db125bea9f523ca

**Comment by jchodera** [comment]
> The current value has been tuned to give near optimal performance in most simulations.

Can that tuning be done on the fly to squeeze out some system-dependent performance gains?

**Comment by peastman** [comment]
In principle, yes.  In practice, it's unlikely to make a big difference.  The speed isn't that sensitive to the exact value, and the optimal value doesn't vary a lot between systems.  See https://github.com/openmm/openmm/pull/2989#issuecomment-768790704.
