### ISSUE TITLE
Extract dihedral energy

### ISSUE THREAD

**Issue by ccccclw** [openmm/openmm#3365]
Hi, 
I was trying to extract dihedral energy with `context.getOwner().getState(State::Energy,false,8).getPotentialEnergy();` but returns 0. Is there any example to extract energy terms from c++ interface?
Thanks!

**Comment by peastman** [comment]
Where are you putting this code?  `getOwner()` is a method of `ContextImpl`, which isn't part of the public API.  It's only used internally.

Given a Context object, you can get the energy of group `i` with

```c++
context.getState(State::Energy, false, 1<<i).getPotentialEnergy()
```

**Comment by ccccclw** [comment]
Thanks for the advice. I was trying to utilize the dihedral energies for calculation of other forces in a plugin: https://github.com/maccallumlab/meld/blob/95d50d49102fd95459a69675f52acbfde4733385/plugin/platforms/cuda/src/MeldCudaKernels.cpp#L1005, but haven't figured out how to correctly call the energy values.

**Comment by peastman** [comment]
That function computes forces and energies for the MeldForce.  If you ask the Context to do an energy evaluation when it's right in the middle of another energy evaluation, that's not going to work correctly!

Can you describe the big picture of what you're trying to do?  What sort of an algorithm are you trying to implement?  If I understand what you want to accomplish, I can maybe suggest ways of doing it.

**Comment by ccccclw** [comment]
I see! I want to implement boost force based on energy values calculated from force field there (basically the gaussian accelerated MD) so that we can combine this boost force and existed features in the plugin. Perhaps I should write this feature separately?

**Comment by peastman** [comment]
There's a built in implementation of the original aMD algorithm: see the API docs for [AMDIntegrator](http://docs.openmm.org/latest/api-python/generated/openmm.amd.AMDIntegrator.html#openmm.amd.AMDIntegrator), [AMDForceGroupIntegrator](http://docs.openmm.org/latest/api-python/generated/openmm.amd.AMDForceGroupIntegrator.html#openmm.amd.AMDForceGroupIntegrator), and [DualAMDIntegrator](http://docs.openmm.org/latest/api-python/generated/openmm.amd.DualAMDIntegrator.html#openmm.amd.DualAMDIntegrator).  And there's an implementation of GaMD at https://github.com/MiaoLab20/GaMD-OpenMM.

**Comment by ccccclw** [comment]
Thanks! I'll check them.
