### ISSUE TITLE
Does implementate for gromos force field in openmm?

### ISSUE THREAD

**Issue by Byun-jinyoung** [openmm/openmm#3369]
As I know, openmm supports the GROMACS input file such as .gro and .top file.
My question is whether openmm also supports the gromos54a7 united-atom force field formatted GROMACS input file format (.gro and .top file format).

Thank you :)

**Comment by peastman** [comment]
I don't know about that particular force field.  OpenMM's readers for Gromacs files support a subset of the features allowed in those files.  If you try to load a file, and it includes a feature that isn't supported, it should throw an exception.

**Comment by Byun-jinyoung** [comment]
I'll try it. Thank you :)
