### ISSUE TITLE
Writing PDBFile without ter lines

### ISSUE THREAD

**Issue by IkramMHD** [openmm/openmm#3372]
Hello, 

I'm writing a pdb file using openmm, howeever i do't want to write the ter lines beteweens chains, 

Is there any options in openmm PDBFile that allow the user to not write thoose lines?
Thank's

**Comment by IkramMHD** [comment]
Hello, 
Thank's you i'm using openmm to rename chain in order to get them merged into a unique chain, however the ter lines are separating beteween two chains which are actually the same one

Thank's you,

**Comment by peastman** [comment]
You can just delete the line by hand.

**Comment by peastman** [comment]
Closing this since the question was answered.
