### ISSUE TITLE
Using a force expression instead of an energy expression for CustomNonbondedForce

### ISSUE THREAD

**Issue by ansingh1214** [openmm/openmm#3375]
Hi, I'm interested in using a force that depends on the effective density around a particle (sum over all particles within some neighbor list, with a factor of exp(-r^2/(2*sigma^2)). The first issue is that the Custom force only takes in the energy expression and takes the derivative automatically, which makes it hard to implement such a force (a workaround for this is by using custom many body force). The second issue that I face (when using custom many body force) is that the jacobian makes the force nonpositive, giving the wrong forces.
I was wondering if there's a way to implement this in a minimal way. Going over the source code, I found that the ReferenceKernels.cpp has the following line:

https://github.com/openmm/openmm/blob/92c6dbb35c63af86bce0d9436e677acfcdc8aa20/platforms/reference/src/ReferenceKernels.cpp#L426-L428

and in the  ComputeKernels.cpp: 

https://github.com/openmm/openmm/blob/92c6dbb35c63af86bce0d9436e677acfcdc8aa20/platforms/common/src/CommonKernels.cpp#L1929-L1930

I was wondering if I simply change these files such that forceExpression = energyExpression, would the form I put in act as a force, instead of the energy? Or would I need to make some other major modifications?

**Comment by peastman** [comment]
Can you describe exactly what you want to do?  What are you trying to model with this force?  What is the exact functional form you want?

It sounds like CustomGBForce might be the best choice for you.  It can perform a sum over the neighborhood of each particle, then compute the energy as a function of that sum.  But I can't be sure without knowing more details.

**Comment by jchodera** [comment]
[`CustomGBForce`](http://docs.openmm.org/latest/api-python/generated/openmm.openmm.CustomGBForce.html#openmm.openmm.CustomGBForce) would indeed be a good choice for implementing a potential based on particle density! As an example, you could compute the density around each particle with this:
```python
# Create a CustomGB force
from openmm import CustomGBForce
force = CustomGBForce()
# Create a global parameter for the sigma parameter used to compute local particle densities
force.addGlobalParameter('sigma', sigma)
# Define the function computed for each particle pair to estimate the total number of particles in the neighborhood
force.addComputedValue('number', 'exp(-r^2 / (2*sigma^2)', CustomGBForce.ParticlePairNoExclusions)
# Now define a function to compute the density in terms of the total 'number' around each particle
force.addComputedValue('density', 'number/volume;'
      'volume = sqrt(2*pi*sigma^3);'
      'pi=3.1415926536;', CustomGBForce.SingleParticle)
# Now define a potential energy contribution in terms of the density
# This is just an example; you can also use per-particle 
# Note that you can also define and use per-particle parameters here!
force.addEnergyTerm('(K/2) * (density - density0)^2;'
     'K = 1.0;' # you might want to define these as global parameters
     'density0 = 1.0;', # you might want to define these as global parameters
      CustomGBForce::SingleParticle)
```
@peastman: I realize the [API documentation](http://docs.openmm.org/latest/api-python/generated/openmm.openmm.CustomGBForce.html#openmm.openmm.CustomGBForce) is a little vague on which quantities are summed across particles. Even in the example, the quantity `I` is defined for particle pairs, but then used in computing the per-particle value `B`, without ever stating whether `I` is first summed over all interacting particles or whether `B` is summed over all interacting particles. Perhaps we could clarify this a bit and add another example?

**Comment by peastman** [comment]
> Even in the example, the quantity I is defined for particle pairs, but then used in computing the per-particle value B, without ever stating whether I is first summed over all interacting particles or whether B is summed over all interacting particles.

The documentation says,

> A computed value is a scalar value that is computed for each particle in the system.

So `I` is a scalar value for each particle.  In the description of particle pair computations it says,

> In the case of a computed value, the value for a particular particle is calculated by pairing it with every other particle in the system, evaluating the expression for each pair, and summing them.

That seems to already be pretty clear.  What would make it easier to understand?

**Comment by ansingh1214** [comment]
Thanks a lot for the prompt response!!
CustomGBForce is indeed a great way to implement a force that adds on to the density, but I again face the issue of not being able to manually put in the forces myself (instead its done through an automatic derivative).
The problem with this is, for instance, when I implement @jchodera 's code, in a minimal way:
```
sig    = 2
lamb   = CustomGBForce()
lamb.addComputedValue('N', 'exp(-r^2 / (2*{:.3f}^2)) / (2*{:.5f}*{:.2f}^2)'.
                      format(sig,np.pi,sig), CustomGBForce.ParticlePairNoExclusions)
lamb.addComputedValue('rho', 'N', CustomGBForce.SingleParticle)
lamb.addEnergyTerm('rho', CustomGBForce.SingleParticle)          
for i in range(N):
    lamb.addParticle([])
lamb.setForceGroup(1)
lamb.setNonbondedMethod(CustomGBForce.CutoffPeriodic)
lamb.setCutoffDistance(1.5*sig) 
system.addForce(lamb)

```
a derivative of the density w.r.t the particle's coordinates is taken, which is not what I want - I want to use the the density as a constant along with some expression (something like rho*(x-5)^2). This is why I was wondering if there's a way to forgo the differentiation and implement the forces directly.

Also, another quick question, is there a simple way to include time-dependence within the custom force? I have been running some non-equilibrium simulations, and the only way I've been able to include time dependence is by defining a new global variable in a custom integrator.

**Comment by peastman** [comment]
You still haven't explained what you're trying to do.  What are you trying to model?  What is the exact functional form of the force you want?  Without knowing that, we're just trying to guess at an appropriate way to implement it.

All custom forces take an expression for the energy, not the force.  However, if you know the force you want, you can easily write an energy designed to have exactly that force as its gradient, e.g. `-fx*x-fy*y-fz*z`.

**Comment by ansingh1214** [comment]
I'm interested in implementing a force that takes the form:
f = (density - density0) * (x-x0, y-y0, z-z0)
where f is the force vector (fx,fy,fz), and (density - density0) is a constant, with density being defined as @jchodera defined it in his code. The idea is to force a bunch of particles to form a cluster around x0,y0 and z0.
The issue with the implementation with CustomGBForce, is that it is differentiating the density w.r.t. to x,y & z which is giving the wrong estimate of the density (it should be purely positive, but that's not the case).

**Comment by peastman** [comment]
That force isn't conservative.  If you ignore the derivatives of density with position, your simulation won't conserve energy and won't reproduce any kind of thermodynamic distribution.  Are you sure you really want to do that?

If you set the energy expression to `0.5*(density-density0)*((x-x0)^2+(y-y0)^2+(z-z0)^2)`, you'll get a force that has more or less the behavior of what you described above, except correctly taking all derivatives into account.

**Comment by ansingh1214** [comment]
The simulation that I'm running is not in equilibrium, and the goal is to use variational force (this specific form of force, ideally) to minimize the action, which is why I'm interested in implementing non-conservative (time-dependent) forces.
This is why I was wondering if changing 
`forceExpression = expression.differentiate("r").createCompiledExpression(); ` 
to 
`forceExpression = expression.createCompiledExpression(); ; ` 
would do the trick

**Comment by jchodera** [comment]
If all you need is a _single_ density, without any modifications, you could 
* compute the scalar `density` you need in a `CustomGBForce.addEnergyTerm()` expression
* move the `CustomGBForce` into a specific force group
* write your own [`CustomIntegrator`](http://docs.openmm.org/latest/api-python/generated/openmm.openmm.CustomIntegrator.html#openmm.openmm.CustomIntegrator) that computes your non-conservative force and uses the density (via the energy from the force group) it in the integration, in a possibly time-dependent nonequilibrium manner

There's certainly merit in the more general feature request of enabling `Custom*Force` groups to specify non-conservative forces directly instead of integrators, but I'm not sure how that would work with OpenMM's overall structure, since everything in OpenMM is essentially predicated on simulating a conservative force-field. I suppose we would just assume the energy contributions to be zero if non-conservative forces are used.

@peastman : Good point about the documentation---it does make sense once I carefully re-read the documentation prior to the example. If there's time, I think I'd like to suggest some clarifications to the example and its explanation below the example code to make those steps clearer and more explicit.

**Comment by peastman** [comment]
Trying to modify the code for a custom force isn't going to give the result you want.  I think your best bet is to write a plugin to implement your particular force.  Do you only need the reference and CPU platforms?  If so, it's pretty easy.  Supporting GPUs is more work.

**Comment by ansingh1214** [comment]
What I need is not a single density, but the a density array that stores the density around all particles. The goal is to exert a force on particles, proportional to the density around them.
I guess, developing a plugin is what I'm going to do. I would like to implement it in CUDA as there's a 3 order of magnitude speed up when I switch from CPU to GPUs.

**Comment by peastman** [comment]
Take a look at the [developer guide](http://docs.openmm.org/latest/developerguide/), which describes how to write plugins.  Also see the [example plugin](https://github.com/openmm/openmmexampleplugin), which can serve as a helpful starting point.  Feel free to ask if you have questions as you go along.

Even if you plan to support CUDA, I would start by writing the reference/CPU version first.  It's a lot easier, and then you can use it as a reference for correct results when writing the GPU version.

**Comment by ansingh1214** [comment]
Thanks a lot for the help, I'll start working on coding up a plugin.
One more thing (I'm not sure if I need to make another post on this), I'm facing an error when I install openmm from source in Catalina OSX (silicon).
The issue I'm getting is:
```
[ 51%] Linking CXX shared library ../../../../libOpenMMAmoebaOpenCL.dylib
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
ld: library not found for -lstdc++
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [plugins/amoeba/platforms/opencl/CMakeFiles/OpenMMAmoebaOpenCL.dir/build.make:151: libOpenMMAmoebaOpenCL.dylib] Error 1
make[1]: *** [CMakeFiles/Makefile2:5384: plugins/amoeba/platforms/opencl/CMakeFiles/OpenMMAmoebaOpenCL.dir/all] Error 2
make: *** [Makefile:160: all] Error 2
```
Any idea why this is failing? I'm using clang as the C-compiler. If I switch to a brew installed gcc (12.0.0), the compilation fails right away with a similar error. I can make a new post if required.

**Comment by jchodera** [comment]
@peastman : Could this be a use case for [openmm-torch](https://github.com/openmm/openmm-torch), where the [`backward()`](https://pytorch.org/docs/stable/notes/extending.html) method is manually called to compute the negative forces that are desired? This might be considerably easier than a plugin.

**Comment by peastman** [comment]
Yes, this would be a good application of it.  It doesn't currently support that feature, but we have an open feature request for it: https://github.com/openmm/openmm-torch/issues/48.  It would be a lot easier than writing a plugin, although it could be challenging to compute the densities efficiently in PyTorch.

I'm not sure what's causing that error.  On MacOS, the CMake script specifies the flag `-stdlib=libc++`.

https://github.com/openmm/openmm/blob/92c6dbb35c63af86bce0d9436e677acfcdc8aa20/CMakeLists.txt#L129

So why is it trying to use libstdc++ instead?

**Comment by ansingh1214** [comment]
The issue had to do something with installation of OpenMMAmoebaOpenCL library.
Setting OPENMM_BUILD_AMOEBA_OPENCL_LIB=OFF fixed the issue
