### ISSUE TITLE
Missing forces in system setup

### ISSUE THREAD

**Issue by Gareth-elliott** [openmm/openmm#3376]
Hi OpenMM Developers,

I have been trying to convert parameters for DMSO from the amoeba09 parameter set (i.e. from amoeba09.prm shipped with tinker).  After a bunch of troubleshooting I have (finally...) figured out why it wasn't working. It seems as though angle bending and stretch bending forces aren't being assigned when the system is built. I can't figure out where I have gone wrong, as far as I can tell the syntax is correct in the .xml file. Attached are files (see below) to replicate the test (I got the code from the python tests).  The output should be:

AmoebaBond = 0.15070207374291236
PeriodicTorsionForce = 0.14169368202790666
AmoebaVdwForce = 0.7631602726562148
AmoebaMultipoleForce = -7.326956329367588
CMMotionRemover = 0.0

Which shows that there are no entries for:
AmoebaAngleForce
AmoebaStretchBend

Your help would be much appreciated.

[computeEnergies.py.txt](https://github.com/openmm/openmm/files/7703204/computeEnergies.py.txt)
[dmso.pdb.txt](https://github.com/openmm/openmm/files/7703205/dmso.pdb.txt)
[dmso.xml.txt](https://github.com/openmm/openmm/files/7703206/dmso.xml.txt)

G

**Comment by peastman** [comment]
Due to a quirk of how AMOEBA is implemented, you also have to add an AmoebaOutOfPlaneBendForce or else the other two don't get added correctly.  It's because of the way the different forces share parameters with each other.  Add the following to your XML file.

```xml
 <AmoebaOutOfPlaneBendForce type="ALLINGER" opbend-cubic="-0.014" opbend-quartic="5.6e-05" opbend-pentic="-7e-07" opbend-sextic="2.2e-08">
 </AmoebaOutOfPlaneBendForce>
```

Sorry for the confusion.  We should add a check for this case.

**Comment by Gareth-elliott** [comment]
Thanks a lot @peastman! :-) Its working now.

**Comment by peastman** [comment]
I marked this as a bug, since it really should catch that case and handle it properly.
