### ISSUE TITLE
Tabulated function for CustomExternalForce

### ISSUE THREAD

**Issue by kolotinsky1998** [openmm/openmm#3384]
Dear community,

I would like to know if is it possible to set CustomExternalForce using tabulated function for potential energy?

Sincerely,
Daniil Kolotinskii

**Comment by peastman** [comment]
CustomExternalForce doesn't support tabulated functions, but CustomCompoundBondForce does, and it can be used for nearly all of the same purposes.  Just set the number of particles per bond to 1.

**Comment by kolotinsky1998** [comment]
Thank You, Peter!

Below I have placed an example. May be it will be useful for somebody. 

`x_array = np.linspace(xmin, xmax, xsize)`
`values = 0.1*x_array**2`
`potential_energy = mm.Continuous1DFunction(values, xmin, xmax)`
`force = mm.CustomCompoundBondForce(1,"f_domain(sqrt(x1^2+y1^2))")`
`force.addTabulatedFunction("f_domain", potential_energy)`
