### ISSUE TITLE
how to get the velocity of each atom from each step

### ISSUE THREAD

**Issue by csu1505110121** [openmm/openmm#3388]
Hello, everyone,

Here, in my research, I want to analyze the velocity autocorrelation so as to get more information. Is there a convenient way to get the information I need? @Lnaden

**Comment by peastman** [comment]
You can get the velocities like this:

```python
velocities = simulation.context.getState(getVelocities=True).getVelocities(asNumpy=True)
```

**Comment by csu1505110121** [comment]
> You can get the velocities like this:
> 
> ```python
> velocities = simulation.context.getState(getVelocities=True).getVelocities(asNumpy=True)
> ```

Thank you for your replying, I have tried this method but this command could only get the current velocities

**Comment by peastman** [comment]
The current velocities are the only ones it knows about.  You can query them at each step (or whatever interval you need) and write them to a file.

Most standard file formats for saving trajectories don't include velocities.  But MDTraj has an OpenMM reporter that can save to [a custom HDF5 based format](https://www.mdtraj.org/1.9.5/api/generated/mdtraj.reporters.HDF5Reporter.html#mdtraj.reporters.HDF5Reporter) that does allow them.

**Comment by csu1505110121** [comment]
> The current velocities are the only ones it knows about. You can query them at each step (or whatever interval you need) and write them to a file.
> 
> Most standard file formats for saving trajectories don't include velocities. But MDTraj has an OpenMM reporter that can save to [a custom HDF5 based format](https://www.mdtraj.org/1.9.5/api/generated/mdtraj.reporters.HDF5Reporter.html#mdtraj.reporters.HDF5Reporter) that does allow them.

Sounds great, and it works! Thanks

**Comment by csu1505110121** [comment]
Sorry to bother again, another problem raised! 
I could save the coordinate, velocities and potentials in a custom HDF5 based format with the help of `mdtraj`. However, the information could not be derived from the `h5` file directly! Is there some good ways to get it?

Now, a method I utilized was attached here:
```
with h5py.File(params_SAMPL6['dir']+str(smiles[0])+'/output.traj.h5', "r")as f:
    print(f.keys())
    data = list(f['velocities'])
    #print(np.array(data))

data = np.array(data)
data.shape
```
But, this method needs another package, `h5py`, when I install it, some package was updated, and then    OpenMM was broken.

**Comment by peastman** [comment]
Make sure you install it from the conda-forge channel.  Packages from different channels sometimes aren't binary compatible with each other.

> some package was updated, and then OpenMM was broken.

What package was updated, and how was OpenMM broken?

**Comment by csu1505110121** [comment]
> Make sure you install it from the conda-forge channel. Packages from different channels sometimes aren't binary compatible with each other.
> 
> > some package was updated, and then OpenMM was broken.
> 
> What package was updated, and how was OpenMM broken?

Sorry for not stating it clearly, and thank you for your suggestion, I will try installing it from the conda-forge channel.
The error I mentioned above could not be accessed now as I rebuilt a new environment.

**Comment by peastman** [comment]
Is this still an open issue?  Did you get it to work?
