### ISSUE TITLE
amber20-factorix benchmark fails with "PeriodicTorsionForce: periodicity must be positive"

### ISSUE THREAD

**Issue by ex-rzr** [openmm/openmm#3391]
It fails in this check (recently added): 
https://github.com/openmm/openmm/blame/610e92fa5f79fbc8cc48ea96d221b0583f817839/openmmapi/src/PeriodicTorsionForceImpl.cpp#L61

**Comment by jchodera** [comment]
The `Amber20_Benchmark_Suite/PME/Topologies/FactorIX.prmtop` file indeed contains negative periodicities in this block:
```
%FLAG DIHEDRAL_PERIODICITY
%FORMAT(5E16.8)
  2.00000000E+00  2.00000000E+00  2.00000000E+00  2.00000000E+00  2.00000000E+00
  2.00000000E+00  2.00000000E+00  3.00000000E+00  2.00000000E+00  3.00000000E+00
  3.00000000E+00  2.00000000E+00  3.00000000E+00  3.00000000E+00  2.00000000E+00
  2.00000000E+00  2.00000000E+00  2.00000000E+00  2.00000000E+00  2.00000000E+00
  2.00000000E+00  2.00000000E+00  2.00000000E+00  2.00000000E+00  2.00000000E+00
  2.00000000E+00  2.00000000E+00  2.00000000E+00  2.00000000E+00  2.00000000E+00
 -4.00000000E+00 -4.00000000E+00 -4.00000000E+00 -2.00000000E+00 -2.00000000E+00
  1.00000000E+00  1.00000000E+00  1.00000000E+00  2.00000000E+00  2.00000000E+00
  2.00000000E+00  2.00000000E+00  2.00000000E+00  2.00000000E+00  2.00000000E+00
  2.00000000E+00  2.00000000E+00  2.00000000E+00  2.00000000E+00  2.00000000E+00
  2.00000000E+00  2.00000000E+00  2.00000000E+00  2.00000000E+00
```
The [`prmtop` file specification](https://ambermd.org/FileFormats.php#topology) describes this block as:
```
%FLAG DIHEDRAL_PERIODICITY
%FORMAT(5E16.8)  (PN(i), i=1,NPTRA)
  PN     : periodicity of the dihedral of a given type
```
Unless I'm missing something, this seems like an error in building the prmtop file. 

The force field definition file uses negative periodicities (`PN`) to indicate there are multiple torsions applied to the same quartet of atoms, and the absolute value is used for simulations:
```
         PN         The periodicity of the torsional barrier.
                    NOTE: If PN .lt. 0.0 then the torsional potential
                          is assumed to have more than one term, and the
                          values of the rest of the terms are read from the
                          next cards until a positive PN is encountered.  The
                          negative value of pn is used only for identifying
                          the existence of the next term and only the
                          absolute value of PN is kept.
```
but the block of negative periodicities have repeated values, which does not make any sense---if these were preserved from the force field definition, the repeated terms would have different periodicities:
```
 -4.00000000E+00 -4.00000000E+00 -4.00000000E+00 -2.00000000E+00 -2.00000000E+00
```
@swails: As the resident Amber expert, any idea why there might be negative periodicities in a prmtop file? 
Is this permissible in Amber prmtop files? Is it equivalent to using the absolute value of the periodicity?

For reference, none of the test `prmtop` files in the `amber20_src/AmberTools/test/` directory of the AmberTools distribution have negative periodicities.

**Comment by dacase** [comment]
The factor_ix benchmark prmtop file is indeed ancient: it was originally
an "old-style" topology, which means that it was created before 2000,
certainly using force fields that are no longer relevant.

SO: please let us know if your sanity checks find other examples of negative
dihedral periodicities.  I have a (very vague) recollection of seeing this
problem before, and fixing the underlying force field files.

About the factor_IX benchmark: the first simple task (volunteers, please!)
would be to manually change the five negative entries to be positive, and see
if the results change.  If we are lucky, we can just update the prmtop file.

**Comment by swails** [comment]
Sorry for missing this!  I need to fix my email notifications for these GH notifications 😬

**Comment by jchodera** [comment]
I passed this question to the AMBER mailing list. Here's the thread:
http://archive.ambermd.org/202201/0195.html

It seems that `sander` has some weird behavior where [negative phases produce different energies than just taking the absolute value of the phase](http://archive.ambermd.org/202201/0224.html), and OpenMM does not implement this weird behavior, so it's best to fail in this case rather than generate results that disagree with AMBER.

**Comment by jchodera** [comment]
Thanks again to @dacase and the AMBER community for diving into this! I think we can safely close this for now.

**Comment by peastman** [comment]
Ok, thanks for looking into it!

**Comment by bdenhollander** [comment]
Running benchmark.py with `--test --verbose` will log this error. Removing `amber20-factorix` from the default list of `TESTS` would avoid the false alarm.
