### ISSUE TITLE
OpenMM on Windows 10/11 WSL2

### ISSUE THREAD

**Issue by gitkol** [openmm/openmm#3400]
Hi,
Does a conda-install version of OpenMM exist that can be run on the Windows Subsystem for Linux? With the latest Windows build and WSL2 one can install a CUDA driver that allows native Linux programs running on the WSL side use the Nvidia GPU.
```
(openmm-env) istvan@MSI:~$ ls -l /usr/lib/wsl/lib
total 73632
-r-xr-xr-x 1 root root   141464 Aug 24 03:24 libcuda.so
-r-xr-xr-x 1 root root   141464 Aug 24 03:24 libcuda.so.1
-r-xr-xr-x 1 root root   141464 Aug 24 03:24 libcuda.so.1.1
-r-xr-xr-x 3 root root   785608 Jun  5  2021 libd3d12.so
-r-xr-xr-x 2 root root  5398848 Jan  3 20:28 libd3d12core.so
-r-xr-xr-x 2 root root   827904 Jun  5  2021 libdxcore.so
-r-xr-xr-x 1 root root  5962912 Dec 15 07:16 libnvcuvid.so
-r-xr-xr-x 1 root root  5962912 Aug 24 03:24 libnvcuvid.so.1
-r-xr-xr-x 1 root root   424400 Dec 15 07:16 libnvidia-encode.so
-r-xr-xr-x 1 root root   424400 Aug 24 03:24 libnvidia-encode.so.1
-r-xr-xr-x 1 root root   197752 Aug 24 03:24 libnvidia-ml.so.1
-r-xr-xr-x 1 root root   354768 Dec 15 07:16 libnvidia-opticalflow.so
-r-xr-xr-x 1 root root   354768 Aug 24 03:24 libnvidia-opticalflow.so.1
-r-xr-xr-x 1 root root 53568104 Aug 24 03:24 libnvwgf2umx.so
-r-xr-xr-x 1 root root   682552 Aug 24 03:24 nvidia-smi
```
I can install OpenMM on the WSL with conda, but the test fails on the GPU indicating some incompatibility, see attached screen shot. nvidia-smi does seem to see the GPU, though.
Many thanks for any suggestion,
   Istvan
![CUDA_error](https://user-images.githubusercontent.com/42390762/148161675-022578fa-61ba-41d4-a2dd-d5a04de4c7e8.png)
![GPU_visible](https://user-images.githubusercontent.com/42390762/148161697-3ebefe08-2a0d-4847-9682-bd953df6ad3a.png)

**Comment by peastman** [comment]
Do you have prerelease software from NVIDIA installed?  It claims you have CUDA 11.6, but according to https://developer.nvidia.com/cuda-downloads the most recent release is 11.5 update 1.  And it claims your driver is 510.06, but the most recent version I can find on NVIDIA's website is 497.29.

Anyway, that error message normally means that your toolkit is newer than your driver, such that the compiler is producing output that the driver can't load.  But in this case, it seems like something else is causing the incompatibility.

**Comment by gitkol** [comment]
The 510.06 driver comes from this source https://developer.nvidia.com/cuda/wsl, the 497.29 driver is a pure Windows driver. If I am not mistaken the conda install of OpenMM 7.7 comes with CUDA Toolkit 11.6, maybe nvidia-smi refers to that?

**Comment by peastman** [comment]
The most recent CUDA toolkit listed at https://anaconda.org/conda-forge/cudatoolkit is 11.5.0.  I don't think you're getting 11.6 from conda.

Perhaps the CUDA toolkit from conda-forge is incompatible with WSL?  Try deleting it with

```
conda remove --force cudatoolkit
```

Then run with the toolkit you got from NVIDIA, adding it to your LD_LIBRARY_PATH.

**Comment by gitkol** [comment]
I tried but it didn't work. If I delete cudatoolkit, OpenMM wouldn't find the GPU platform even after setting LD_LIBRARY_PATH as well as CUDA_HOME to point to where the WSL cuda libraries are located.

**Comment by peastman** [comment]
Try `ldd libOpenMMCUDA.so` (at whatever location it's installed inside your conda directory).  That should tell you what libraries it's not finding.

**Comment by gitkol** [comment]
Wow, this is actually working after reverting back to the 497.29 driver and installing it through the Microsoft Insider program rather than through Nvidia. :) The OpenMM test finished flawlessly on the WSL on all 3 platforms including CUDA.

**Comment by peastman** [comment]
Excellent!

**Comment by gitkol** [comment]
WSL, another great platform where OpenMM runs out of the box!

Thanks,

   Istvan
