### ISSUE TITLE
Analyze the particle energy to investigate 'particle coordinate is nan'

### ISSUE THREAD

**Issue by pschnee1** [openmm/openmm#3401]
Greeting everyone,

I am simulating a system consisting of a protein (dark and light blue), DNA (orange) and a cofactor (yellow), all complexed with each other (see picture). 
![DNMT3A](https://user-images.githubusercontent.com/97196949/148292180-81ea3e9b-5912-4e28-86a1-733977d9f35b.png)
Minimization, multiple equilibration rounds (with restrained DNA, cofactor, 1ns each), run all smoothly. However, about 10ns in the simulation, the system crashes because of too much energy at certain position ('particle coordinate is nan').
To overcome this, I narrowed the step size from 2fs to 1fs, which resulted in a 15ns simulation, but eventually still crashing. - I am pretty sure, the DNA is somewhere entangled, which then creates huge forces.

Making a long story short: How can I investigate which particle or residue is causing the system to crash?
I will point out my steps to approach this questions - 
I read a bit and stumbled across: 

```
class ForceReporter(object):
    def __init__(self, file, reportInterval):
        self._out = open(file, 'w')
        self._reportInterval = reportInterval

    def __del__(self):
        self._out.close()

    def describeNextReport(self, simulation):
        steps = self._reportInterval - simulation.currentStep%self._reportInterval
        # return (steps, positions, velocities, forces, energies)
        return (steps, False, False, True, False)

    def report(self, simulation, state):
        forces = state.getForces().value_in_unit(kilojoules/mole/nanometer)
        for f in forces:
            self._out.write('%g %g %g\n' % (f[0], f[1], f[2])) #0->HarmonicBondForce, 1->HarmonicAngleForce, 2->PeriodicTorsionForce,

Force_Reporter = ForceReporter(traj_folder + '/' + 'forces.txt', 10000)
```
This works perfectly fine, but I was still struggling with the question:
Firstly, am I right with the assumption of the forces? (#0->HarmonicBondForce, 1->HarmonicAngleForce, 2->PeriodicTorsionForce)

The file i get looks like this:

193.54 87.4012 -674.86
211.406 24.7029 39.2503
-329.522 757.185 -292.679
71.1205 -151.688 6.36102

Which imo are the forces for each particle in one line, each time I report (the number of rows fits the number of particles I have in the system* number of reportings). 
This already gives me a lot of information! However I want to narrow this down an only get the forces for the protein or the DNA residues and not for every particle in the system. Is there a way to call this class without the ```state```? Maybe like with MDTraj: 
```
selection = 'protein or chainid 4 or chainid 5 resname SAA or resname SAB'
forces = selection.getForces().value_in_unit(kilojoules/mole/nanometer)
```
And if this would work, how would the numbering in the output file (forces.txt) would be? 

first row -> first residue of protein
second row -> second residue of protein
.
.
.
then chainid 4 ?

Sorry for the long question, thanks for the effort!

Best regards,
pschnee1

**Comment by jchodera** [comment]
I've often seen this behavior in AMBER force fields where some hydrogens have partial charges but no LJ sites, relying on the heavy atom they are attached to instead to "shield" them from charges of unlike sign getting too close together.

Can you share a ZIP of the serialized `System` and `State` objects?
```python
def serialize(obj, filename):
    from openmm import XmlSerializer
    with open(filename, 'wt') as outfile:
        outfile.write(XmlSerializer.serialize(obj))

serialize(system, 'system.xml')
serialize(state, 'state.xml')
```
That would help us inspect what might be going on.

Another possibility: Are you using `mixed` precision in CUDA/OpenCL? By default, OpenMM uses `single` precision, which may be insufficient for integrator constraint handling.

**Comment by pschnee1** [comment]
Thanks for the quick reply! 
I checked the FAQs prior of asking here, that's how i came up with the step size from 2fs to 1fs, which unfortunately did not work out. 

> I've often seen this behavior in AMBER force fields where some hydrogens have partial charges but no LJ sites, relying on the heavy atom they are attached to instead to "shield" them from charges of unlike sign getting too close together.
> 
> Can you share a ZIP of the serialized `System` and `State` objects?

@jchodera I serialized the system and provided the code and PDBs. The system and state was serialized after the NPT equilibration. Let me know, if you see/find anything suspicious. 
[Git.zip](https://github.com/openmm/openmm/files/7825122/Git.zip)


> Another possibility: Are you using `mixed` precision in CUDA/OpenCL? By default, OpenMM uses `single` precision, which may be insufficient for integrator constraint handling.

I usually run on 'single' precision on a Nvidia RTX 3090 with 2 AMD Ryzen Threadripper 1900X 8-Core Processor, 16 GB RAM.
I restarted the system with `mixed`, still the system keeps crashing at about 60% in the simulation. 

@peastman For the assessment of the forces on each atom, I now have this:

```
Energy_Analysis_molecules = 'protein or chainid 4 or chainid 5 or resname SMA or resname SMB' 
Energy_Analysis_indices = selection_reference_topology.select(Energy_Analysis_molecules)

class ForceReporter(object):
    def __init__(self, file, reportInterval):
        self._out = open(file, 'w')
        self._reportInterval = reportInterval

    def __del__(self):
        self._out.close()

    def describeNextReport(self, simulation):
        steps = self._reportInterval - simulation.currentStep%self._reportInterval
        # return (steps, positions, velocities, forces, energies)
        return (steps, False, False, True, False)

    def report(self, simulation, state):
        forces = state.getForces().value_in_unit(kilojoules/mole/nanometer)
        for i in Energy_Analysis_indices:
            f = forces[i]
            self._out.write('%d %g %g %g\n' % (i, f[0], f[1], f[2]))

Force_Reporter = ForceReporter(traj_folder + '/' + 'forces.txt', 10000)
```

This gives me exactly what I want from it: The forces on x, y, z for each atom I had in the selection list, as seen below:

0 -245.737 -123.529 71.0282
1 434.386 -81.1122 -80.9795
2 107.411 -423.033 -129.758
3 -147.56 264.273 375.878
.
.
.

To investigate where (at which residue or atom) in my system I have large force changes, I would proceed as follows:

1. report the forces for each selected atom at 'step 1' in the production run and keep the force values.
2. report the forces at 'step 2' and compare them to the forces from 'step 1'.
3. If a drastic change occurs (don't know what this could be, maybe 100% increase or decrease of a force in x, y, or z direction) 
-> report this and write in a dataframe with the according atom number and step.

That way I should be able to monitor and identify large force changes in the system (_these steps are not included in the code yet_).
I don't know if this is the best way to do this or if this even works. What do you think about it?

Thanks a lot for your help,

pschnee1

**Comment by peastman** [comment]
How consistent is the point where it crashes?  Is it always at about 60% of the way, or does it vary?  I've sometimes seen people have problems like that when something was systematically changing over the simulation.  For example, they gradually increased the temperature, and when it got too high the simulation became unstable.  Perhaps something like that is happening?

You aren't looking for large changes in the force on a particular atom.  That happens all the time, like when two atoms collide with each other.  Instead, I would look for any atom that has a force larger than some fixed amount.  10000 kJ/mol/nm is usually a good value.  That's about the largest force that should ever come up in typical situations.

**Comment by jchodera** [comment]
Thanks for sharing the `system.xml`!

I'm suspicious of entries like this, where there is no LJ site on a partial charge:
```
                                <Particle eps="0" q=".4102" sig="1"/
```
You might try a quick test of making these nonzero to see if this eliminates the instability?
```python
from openmm import unit
forces = { force : force.getName() for force in system.getForces() }
force = forces['NonbondedForce']
for particle_index in range(force.getNumParticles()):
    charge, sigma, epsilon = force.getParticleParameters(particle_index)
    if epsilon / unit.kilojoules_per_mole == 0.0:
        force.setParticleParameters(charge_index, charge, 0.1*unit.nanometers, 0.001*unit.kilojoules_per_mole)
```

**Comment by peastman** [comment]
Is this still an open issue?  Did you figure out what the problem was?

**Comment by pschnee1** [comment]
Yes and No. The problem was solved for my particular problem during the last week. However, not in a sophisticated way.
I will shortly describe what I did to overcome this problem in a pragmatic way, knowing, that this might not be the most elegant way.

The problem was, that I had multiple elements (cofactor, DNA, 4 protein subunits ) in my system which kept crashing in 90% of all cases after sometimes 20%, 50% or 90% of the simulation time. I did not know, which of the elements caused the issue. So I successively took them out and found out, that the DNA was the element, which caused the issue.
What was lacking for me to fix the issue was where the problem in the DNA was exactly located. Which nucleotide of the DNA or which atoms created the large forces responsible for the system to collapse. - Answer: I still don't know.

The pragmatic solution I came up with was as follows: I took a trajectory, which went trough (or one could use a trajectory which is about 90% finished) and analyzed the whole trajectory for the potential energy (code below). I extracted the frame with the lowest potential energy and used this as the new starting structure. The system now runs smoothly for up to 100 ns (maximum I tried).

A problem for this strategy could be that sampling takes only place in a certain energy minimum (the frame, which was selected as the new starting position). So maybe multiple starting positions for this are a good quality check.

Certainly this is a pragmatic way, but maybe it helps people reading this. As soon as I finish the script which tells you which atom(s) give large forces and maybe therefore cause the system to crash, I will update this issue.

```
f = h5py.File('traj.h5', 'r')
 
# get potential energey from h5 file
P_energy = f['potentialEnergy']

# make list
list_P_energy = list(P_energy)
 
#shorten it
short_P_energy = list_P_energy[0::10]
 
#put in pandas
df_P = pd.DataFrame(short_P_energy)
df_P_ges = pd.concat([df_P_ges,df_P], axis = 1)

#convert to excel
df_P_ges.columns = ['Rep1','Rep2','Rep3','Rep4','Rep5','Rep6','Rep7','Rep8','Rep9','Rep10']
df_P_ges.to_excel('potentialEnergy_{}.xlsx'.format(NHT))
```
