### ISSUE TITLE
'Nan' appears on single-precision CUDA and OpenCL platforms while double-precision one normally runs

### ISSUE THREAD

**Issue by Dropletsimuli** [openmm/openmm#3404]
Hi,
I want to use Martini 2.0 with polarizable water model ( doi:10.1371/journal.pcbi.1000810 ) on OpenMM-7.6.0.  However, when I tested the system consisting of 5000 water beads on  single-precision CUDA platform, there was an error:
```
Building system...
Performing energy minimization...
Simulating...
Traceback (most recent call last):
  File "/home/zzx/PycharmProjects/openmm/drop/vesicle2/prebuilt_vesicle_polarwater/pw_test/2/error/pw_mix.py", line 74, in <module>
    simulation.step(steps)
  File "/home/zzx/research/tools/miniconda3/envs/openmm/lib/python3.7/site-packages/openmm/app/simulation.py", line 134, in step
    self._simulate(endStep=self.currentStep+steps)
  File "/home/zzx/research/tools/miniconda3/envs/openmm/lib/python3.7/site-packages/openmm/app/simulation.py", line 199, in _simulate
    self.integrator.step(10) # Only take 10 steps at a time, to give Python more chances to respond to a control-c.
  File "/home/zzx/research/tools/miniconda3/envs/openmm/lib/python3.7/site-packages/openmm/openmm.py", line 9599, in step
    return _openmm.LangevinMiddleIntegrator_step(self, steps)
openmm.OpenMMException: Particle coordinate is nan

Process finished with exit code 1
```
Here is the input file:
[pw_mix_test.zip](https://github.com/openmm/openmm/files/7827397/pw_mix_test.zip)

Nan appeared on single-precision CUDA  platform, but double-precision one can run normally. I also tested it on other platforms, the result is following: 
![image](https://user-images.githubusercontent.com/78062613/148510696-0d090add-55bb-42dc-863e-d9a73eb88293.png)
I want to run the simulation on CUDA platform with single precision for faster speed, but I am weird about the above results and don't know how to modify it.
Thank you in advance for resolving this issue!

Best regards,
Drep

**Comment by peastman** [comment]
Is this the martini implementation you're using?  https://github.com/maccallumlab/martini_openmm

**Comment by jchodera** [comment]
From what I can tell by serializing the `System` object (attached):
* You're using 25 fs timesteps with 1/ps collision rate
* The water model has the O-H bonds constrained, but H-O-H is treated by a flexible angle
* Only the O site (`POL` type) has a LJ site---the H sites (`D`) have partial charges

[system.zip](https://github.com/openmm/openmm/files/7830905/system.zip)

I'm honestly surprised this is stable in double precision with a 25 fs timestep. It seems like the CPU platform (mixed precision) is stable too, so perhaps this indicates it's some kind of integrator constraints stability issue?

**Comment by Dropletsimuli** [comment]
> Is this the martini implementation you're using? https://github.com/maccallumlab/martini_openmm

Yes, I use it for running MARTINI model. But this python script dosen't support the polarizable water model of MARTINI currently,  I want to modified the script for running this water model.

**Comment by Dropletsimuli** [comment]
This polarizable CG water consists of three particles instead of one in the standard MARTINI force field (Fig. B): 

1. The central particle W (POL) is neutral and interacts with other particles in the system by means of the Lennard-Jones interactions. 
2. The additional particles WP (D) and WM (D) are bound to the central particle and carry a positive and negative charge of +q and −q, respectively. They interact with other particles via a Coulomb function only, and lack any LJ interactions. 
3. The bonds W-WP and W-WM are constrained to a distance l. 
4. The interactions between WP and WM particles inside the same CG water bead are excluded. 
5. 20 - 40 fs timestep is recommended in MARTINI model

(https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1000810)

![image](https://user-images.githubusercontent.com/78062613/148666888-6d96ec2d-400b-4d4f-af56-05db4df84aed.png)

**Comment by Dropletsimuli** [comment]
> From what I can tell by serializing the `System` object (attached):
> 
> * You're using 25 fs timesteps with 1/ps collision rate
> * The water model has the O-H bonds constrained, but H-O-H is treated by a flexible angle
> * Only the O site (`POL` type) has a LJ site---the H sites (`D`) have partial charges
> 
> [system.zip](https://github.com/openmm/openmm/files/7830905/system.zip)
> 
> I'm honestly surprised this is stable in double precision with a 25 fs timestep. It seems like the CPU platform (mixed precision) is stable too, so perhaps this indicates it's some kind of integrator constraints stability issue?

I think so. When I removed all the constraint and exclusion, it run normally under single-precision platform (CUDA or OpenCL).

**Comment by peastman** [comment]
I notice several strange things about this system.

There's a CustomNonbondedForce that implements Coulomb interactions with reaction field.  And then there's a CustomBondForce that has a similar functional form and presumably is meant to calculate the 1-4 interactions.  But if that's the intention there's a bunch of problems.

- It's missing the 1/r in the energy expression, so it actually is a totally different potential.
- It includes bonds connecting each central particle to itself???
- It includes bonds corresponding to the constrained distances.  That's going to hurt stability, since it will produce forces trying to change the lengths away from the constrained values.

There's a second CustomNonbondedForce and CustomBondForce to do the same thing for LJ interactions.  In this case, the CustomBondForce is purely wasted computation.  It sets C6 and C12 to 0 for every bond, so the energy is always zero.

**Comment by Dropletsimuli** [comment]
> I notice several strange things about this system.
> 
> There's a CustomNonbondedForce that implements Coulomb interactions with reaction field. And then there's a CustomBondForce that has a similar functional form and presumably is meant to calculate the 1-4 interactions. But if that's the intention there's a bunch of problems.
> 
> * It's missing the 1/r in the energy expression, so it actually is a totally different potential.
> * It includes bonds connecting each central particle to itself???
> * It includes bonds corresponding to the constrained distances.  That's going to hurt stability, since it will produce forces trying to change the lengths away from the constrained values.
> 
> There's a second CustomNonbondedForce and CustomBondForce to do the same thing for LJ interactions. In this case, the CustomBondForce is purely wasted computation. It sets C6 and C12 to 0 for every bond, so the energy is always zero.

Sorry for the late replay.  I check the original script(https://github.com/maccallumlab/martini_openmm/blob/master/martini_openmm/martini.py), and I found that:
```
        # custom non-bonded force to deal with martini's
        # use of epsilon_r
        es = mm.CustomNonbondedForce(
            f"step(rcut-r) * ES;"
            f"ES = (f / epsilon_r) * q1 * q2 * (1/r + krf * r^2 - crf);"
            f"crf = 1 / rcut + krf * rcut^2;"
            f"krf = 1 / (2 * rcut^3);"
            f"epsilon_r = {epsilon_r};"
            f"f = 138.935458;"
            f"rcut={nonbondedCutoff.value_in_unit(unit.nanometers)};"
        )
        es.addPerParticleParameter("q")
        es.setNonbondedMethod(mm.CustomNonbondedForce.CutoffPeriodic)
        es.setCutoffDistance(nonbondedCutoff.value_in_unit(unit.nanometer))
        sys.addForce(es)

        # custom non-bonded force to add in the electrostatic
        # terms for self and excluded interactions
        elecSelfExclForce = mm.CustomBondForce(
            f"step(rcut-r) * ES;"
            f"ES = f*qprod/epsilon_r * (krf * r^2 - crf);"
            f"crf = 1 / rcut + krf * rcut^2;"
            f"krf = 1 / (2 * rcut^3);"
            f"epsilon_r = {epsilon_r};"
            f"f = 138.935458;"
            f"rcut={nonbondedCutoff.value_in_unit(unit.nanometers)};"
        )
        elecSelfExclForce.addPerBondParameter("qprod")
        sys.addForce(elecSelfExclForce)

        # custom LJ force using a lookup table to implment
        # nbfix-like terms
        lj = mm.CustomNonbondedForce(
            "step(rcut-r)*(energy - corr);"
            "energy = (C12(type1, type2) / r^12 - C6(type1, type2) / r^6);"
            "corr = (C12(type1, type2) / rcut^12 - C6(type1, type2) / rcut^6);"
            f"rcut={nonbondedCutoff.value_in_unit(unit.nanometers)};"
        )
        lj.addPerParticleParameter("type")
        lj.setNonbondedMethod(mm.CustomNonbondedForce.CutoffPeriodic)
        lj.setCutoffDistance(nonbondedCutoff.value_in_unit(unit.nanometer))
        sys.addForce(lj)

        # custom Lbonded force to handle exceptions
        ljExceptForce = mm.CustomBondForce(
            "step(rcut-r) * (energy - corr);"
            "energy = (C12/r^12 - C6/r^6);"
            "corr = (C12/rcut^12 - C6/rcut^6);"
            f"rcut={nonbondedCutoff.value_in_unit(unit.nanometers)};"
        )
        ljExceptForce.addPerBondParameter("C12")
        ljExceptForce.addPerBondParameter("C6")
        sys.addForce(ljExceptForce)
```
What does the `CustomBondForce` work for the exceptions of Coulomb and LJ interaction? I also weird about these `CustomBondForce` ( `elecSelfExclForce` and `ljExceptForce` ).

**Comment by peastman** [comment]
I'm pretty sure the expression in that code is wrong.  @jlmaccal do you agree?  See https://github.com/openmm/openmm/issues/3404#issuecomment-1008359008 above.

**Comment by jlmaccal** [comment]
Sorry, which expression are we talking about?

We haven't done anything with polarizable water yet, but we have a fairly extensive test set validating that the energies and forces match between gromacs / OpenMM.

**Comment by jlmaccal** [comment]
I'm pretty fuzzy on the details of this, as it's been... a while since I worked on this.

The custom bonded force `lj_except_force` is meant to handle LJ exceptions. I don't remember why it had to be implemented this way, but there is a reason :) @peastman is right, that for this system, there are only exclusions and these are all zeros. I'm adding a check for this to avoid calculating interactions that are always zeros.

As far as the `es_self_excl_force` goes, I think there is a problem here, but I'm not sure exactly what it is yet. This term is meant to cover two cases: (1) self- and excluded interactions, and (2) exceptions. For (1), gromacs has a self-interaction term and there is still an energy term between excluded particles. For these cases, it is a different potential and the `1 / r` term is *not* supposed to be there. I don't fully remember the details of this, but adding in the `1 / r` term causes the forces and energies to not match for all test cases. However, in the case of an exception, it should be there. So, I probably need to split this into two different forces. That said, I don't think martini uses exceptions anywhere.

@peastman As far as your comment about duplicate bonds / constraints, the bonds are commented out, so they shouldn't be duplicated. I don't understand your comment about particles being bonded to themselves. I'm not seeing that in the topology file.

**Comment by peastman** [comment]
> As far as your comment about duplicate bonds / constraints, the bonds are commented out, so they shouldn't be duplicated. I don't understand your comment about particles being bonded to themselves.

I see them in the serialized system that was posted above in https://github.com/openmm/openmm/issues/3404#issuecomment-1007679497.  `elecSelfExclForce` has bonds like

```xml
<Bond p1="0" p2="0" param1="0"/>
```

That's a bond connecting particle 0 to itself.  And then in `ljExceptForce` there are bonds like

```xml
<Bond p1="0" p2="1" param1="0" param2="0"/>
```

That's a bond connecting particles 0 and 1, which is a constrained pair.  That would cause problems, except that in this case C6 and C12 are both set to 0, so it doesn't actually apply any force.

**Comment by jlmaccal** [comment]
Ah, gotcha. I didn't see that @jchodera had posted the serialized system.

For the first case, those "self-bonds" are intentional. They account for the self term in the reaction field correction to match gromacs. There is probably a better way to handle them, as they are simply constant factors added to the energy.

For the second case, I've added a check to avoid adding the terms where both C6 and C12 are zero.

**Comment by jlmaccal** [comment]
I've added @Dropletsimuli 's system as an additional test. On the latest `martini3` branch, the energies and forces are reproduced almost exactly.

Any remaining stability issues likely boil down to integrator settings and differences in constraint algorithms. I will note that one frequently encounters bonds that rotate more than 30 degrees during the LINCS step with gromacs.

**Comment by Dropletsimuli** [comment]
@jlmaccal Because the `lj` and `es` use `addExclusion`  in the line 1234-1235 [[martini_openmm.py](https://github.com/maccallumlab/martini_openmm/blob/master/martini_openmm/martini.py)], is there probably no need to add  `elecSelfExclForce` and `ljExceptForce` to handle the exceptions of Coulomb and LJ interaction? 
And is `elecSelfExclForce`  just a energy term for the reaction field correction for excluded interactions without any force computation?

**Comment by jlmaccal** [comment]
Let's take this over to the other repository, to keep the traffic down here.

Those two lines exclude that atom pair from the normal LJ and ES nonbonded terms. For the LJ it was adding useless computations that are always zero. This wasn't incorrect, just marginally inefficient. For the ES part, these extra terms must be added or the energies and forces won't match those from gromacs.

For self interactions, the `elecSelfExclForce` is just a constant energy term with no force on the atom. For excluded atom pairs, there is both an energy and force term between the excluded atoms. You can have a look at the [gromacs reference manual](https://manual.gromacs.org/documentation/2020-beta1/reference-manual/functions/nonbonded-interactions.html) for details.

**Comment by Dropletsimuli** [comment]
@jlmaccal Thank you for your suggestion!
