### ISSUE TITLE
OpenMM nightly dev builds are not updating

### ISSUE THREAD

**Issue by zhang-ivy** [openmm/openmm#3406]
The last time the builds were updated was 9 days ago: https://anaconda.org/omnia-dev/openmm/files

Is this because the version number needs to be bumped?

cc: @jchodera @peastman

**Comment by peastman** [comment]
Thanks!  Is this the version number that needs to be updated?

https://github.com/omnia-md/conda-dev-recipes/blob/b0e74705ef3b06888173c4fd9af53091ca4d8117/recipes/openmm/meta.yaml#L17

**Comment by jchodera** [comment]
That's it! Could you add that step to the release checklist?

**Comment by peastman** [comment]
PR is at https://github.com/omnia-md/conda-dev-recipes/pull/213.  CI is running right now, and then I can merge it.

**Comment by zhang-ivy** [comment]
Looks like the builds are now updated! I see that https://github.com/omnia-md/conda-dev-recipes/pull/213 is failing though, so I'll keep this issue open.

**Comment by peastman** [comment]
All the Windows CUDA builds are failing.  Is that expected?

**Comment by peastman** [comment]
I merged the PR, so at least Linux builds should be working again.

**Comment by jchodera** [comment]
@peastman : We discussed the failing win builds here: https://github.com/omnia-md/conda-dev-recipes/issues/207

**Comment by zhang-ivy** [comment]
@peastman @jchodera : It looks like the nightly builds are no longer updating again: https://anaconda.org/omnia-dev/openmm/files

What can I do to resolve this?
