### ISSUE TITLE
Can the MonteCarloBarostat frequency be 0?

### ISSUE THREAD

**Issue by zhang-ivy** [openmm/openmm#3408]
The docs for `MonteCarloBarostat` 's `setFrequency()` say: "Set the frequency (in time steps) at which Monte Carlo pressure changes should be attempted. If this is set to 0, the barostat is disabled."

However, if I call `setFrequency(0)`, I get this error:
```
OpenMMException: Frequency must be positive
```
which comes from [this check](https://github.com/openmm/openmm/blob/610e92fa5f79fbc8cc48ea96d221b0583f817839/openmmapi/src/MonteCarloBarostat.cpp#L53-L54). 

Are the docs wrong or should that check actually be `< 0`, not `<= 0`?

**Comment by zhang-ivy** [comment]
tagging @peastman to make sure you see this!

**Comment by peastman** [comment]
I believe you're correct.  It should be checking that it is non-negative rather than positive.  A PR would be welcome!

**Comment by zhang-ivy** [comment]
@peastman : The PR #3411 is ready for your review!
