### ISSUE TITLE
Adding swm4 water to the modeller object with charmm_polar_2019

### ISSUE THREAD

**Issue by andrewsb8** [openmm/openmm#3415]
Hello,

I am running into an issue which I can't find documented anywhere. I can't import swm4ndp.xml water file to the Forcefield object, according to the [documentation](http://docs.openmm.org/latest/userguide/application/02_running_sims.html), when using the charmm drude 2019 force field. 

`Warning
Drude polarizable sites and lone pairs are not yet supported by ParmEd and the CHARMM36 forcefields that depend on these features are not included in this port. To use the CHARMM 2019 polarizable force field[12], include the single file charmm_polar_2019.xml.`

I do see that the swm4 water in the charmm_polar_2019.xml file so that I should be able to add it. According to the [documentation](http://docs.openmm.org/latest/userguide/application/03_model_building_editing.html#adding-solvent) for adding solvent via the modeller.addSolvent command, this model is not supported:

`Allowed values for the model option are 'tip3p', 'tip3pfb', 'spce', 'tip4pew', 'tip4pfb', and 'tip5p'. Be sure to include the single quotes around the value.`

So technically this is not an option. However, choosing the option `model='tip5p'` does "work" because swm4 is a 5-point water model. The resultant atom names in the pdb of the system and definitions of the swm4 water model in the .xml file seem different so it's unclear if I'm actually using the correct water model. I am wondering if:

1. This is actually the correct method for doing this?
2. And, if it is, could a note of this be made in the documentation so it is clearer how to accomplish this? Given the process for using this force field is already different from most of the nonpolarizable force fields, it feels unclear and I had to hope that the tip5p option would be interpretted correctly.

Thanks again!

Brian

**Comment by peastman** [comment]
You're right, we should add that as an option to `addSolvent()`.  For the moment, I think the best thing to do is specify `tip3p` so it will add three point water, then call `addExtraParticles()` to add the missing virtual site and Drude particle.

**Comment by andrewsb8** [comment]
`forcefield = ForceField(ff)`
`modeller = Modeller(pdb.topology, pdb.positions)`
`modeller.addExtraParticles(forcefield) #THIS STEP IS REQUIRED FOR CHARMM DRUDE/POLARIZABLE FFs`
`modeller.addSolvent(forcefield, boxSize=Vec3(5, 5, 5)*nanometers, neutralize=True, negativeIon='Cl-', positiveIon='Na+', model='tip3p')\n`
`modeller.addExtraParticles()`

This currently throws a template error because the snw4 template expects the two virtual sites. The second `modeller.addExtraParticles()` still does not work even if `forcefield` is added as an argument. Unless you meant that `tip5p` should be the specified option for now.

**Comment by peastman** [comment]
Could you post the stack trace for the exception?

**Comment by andrewsb8** [comment]
`Traceback (most recent call last):
  File "/data/B/bandrews/OpenMM/GIG_CHARMM_Drude_2019_SWM4-NDP_water/openmm_setup.py", line 39, in <module>
    modeller.addSolvent(forcefield, boxSize=Vec3(5, 5, 5)*nanometers, neutralize=True, negativeIon='Cl-', positiveIon='Na+', model='tip3p')
  File "/home/bandrews/miniconda3/envs/openMM/lib/python3.9/site-packages/openmm/app/modeller.py", line 631, in addSolvent
    self._addIons(forcefield, numTotalWaters, waterPos, positiveIon=positiveIon, negativeIon=negativeIon, ionicStrength=ionicStrength, neutralize=neutralize)
  File "/home/bandrews/miniconda3/envs/openMM/lib/python3.9/site-packages/openmm/app/modeller.py", line 305, in _addIons
    system = forcefield.createSystem(self.topology)
  File "/home/bandrews/miniconda3/envs/openMM/lib/python3.9/site-packages/openmm/app/forcefield.py", line 1206, in createSystem
    templateForResidue = self._matchAllResiduesToTemplates(data, topology, residueTemplates, ignoreExternalBonds)
  File "/home/bandrews/miniconda3/envs/openMM/lib/python3.9/site-packages/openmm/app/forcefield.py", line 1420, in _matchAllResiduesToTemplates
    raise ValueError('No template found for residue %d (%s).  %s' % (res.index+1, res.name, _findMatchErrors(self, res)))
ValueError: No template found for residue 4 (HOH).  The set of atoms is similar to SWM4, but it is missing 2 extra particles.  You can add them with Modeller.addExtraParticles().`

This is what you need, right? Let me know if you need anything else!

**Comment by peastman** [comment]
Try this:

```python
modeller = Modeller(pdb.topology, pdb.positions)
forcefield1 = ForceField('amber14-all.xml', 'amber14/tip3pfb.xml')
modeller.addSolvent(forcefield1, boxSize=Vec3(5, 5, 5)*nanometers, neutralize=True, negativeIon='Cl-', positiveIon='Na+', model='tip3p')
forcefield2 = ForceField('charmm_polar_2019.xml')
modeller.addExtraParticles(forcefield2)

**Comment by andrewsb8** [comment]
That does work. And the atom names are as expressed in the swm4 entries of the charm_polar_2019.xml and swm4ndp.xml files. So the `model='tip5p'` method is not appropriate here. This also works with at least `charmm36.xml` and `charmm36/water.xml` in the `forcefield1` entry. You can also eliminate the `model='tip3p'` from this as the 3 point water model is specified in `forcefield1` and I tested it. But it doesn't matter if you include it either.

Sorry to ask this question again lol, but it does not seem that this forcefield supports a neutral C terminus option, only charged. Is that correct? It seems that none of these patches apply this under residue GLY:

`<AllowPatch name="GNTE"/>
      <AllowPatch name="ACE"/>
      <AllowPatch name="CTEG"/>
      <AllowPatch name="CNEG"/>
      <AllowPatch name="CT1G"/>
      <AllowPatch name="CT2G"/>
      <AllowPatch name="CT3"/>`

If so, I'll just have to live with that. Thanks again for all of your help today.

**Comment by peastman** [comment]
Are you sure?  CTEG and CNEG look like the charged and neutral versions, respectively.

**Comment by andrewsb8** [comment]
The CNEG does seem to add a hydrogen. But I'm unsure how to modify the atom between `forcefield1` and `forcefield2`. When I keep the HXT atom at the end of the pdb file as we discussed in #3413, for example, that throws a template error during the `forcefield2` step: 

`Traceback (most recent call last):
  File "/data/B/bandrews/OpenMM/GIG_CHARMM_Drude_2019_SWM4-NDP_water/openmm_setup.py", line 38, in <module>
    modeller.addExtraParticles(forcefield2)
  File "/home/bandrews/miniconda3/envs/openMM/lib/python3.9/site-packages/openmm/app/modeller.py", line 1048, in addExtraParticles
    templates = forcefield._matchAllResiduesToTemplates(ForceField._SystemData(self.topology), self.topology, {}, False, True, False)
  File "/home/bandrews/miniconda3/envs/openMM/lib/python3.9/site-packages/openmm/app/forcefield.py", line 1420, in _matchAllResiduesToTemplates
    raise ValueError('No template found for residue %d (%s).  %s' % (res.index+1, res.name, _findMatchErrors(self, res)))
ValueError: No template found for residue 3 (GLY).  The set of atoms is similar to SER, but it is missing 12 atoms.
`
For now I will run a simulation with charged termini while thinking of a way to address that issue.
