### ISSUE TITLE
Unable to access periodic box vectors in DCD file created by DCDReporter

### ISSUE THREAD

**Issue by zhang-ivy** [openmm/openmm#3418]
I ran a simulation with a `DCDReporter`, which [writes the periodic box vectors to the DCD](https://github.com/openmm/openmm/blob/be19e0222ddf66f612016a3c1f687161a53c2396/wrappers/python/openmm/app/dcdreporter.py#L107) every time the positions are written to the file.

OpenMM doesn't allow loading of DCD files, so I tried loading the DCD file using mdtraj:
```python
cif = app.PDBxFile("equilibrated_imaged.cif")
topology = md.Topology.from_openmm(cif.topology)
traj = md.load("traj.dcd", top=topology)
traj
```
I get the following output:
```
<mdtraj.Trajectory with 93 frames, 185377 atoms, 57660 residues, without unitcells at 0x2b6815daa970>
```

Note that it says `without unitcells`, meaning mdtraj isn't able to load the box vectors. Since OpenMM doesn't allow loading of DCD files, I'm not sure how to check whether the box vectors are actually being saved to the file or whether this is an mdtraj loading error. What is the best way to access the box vectors from an OpenMM-generated DCD file?

**Comment by peastman** [comment]
OpenMM writes box vectors if and only if your Topology defines box vectors (`getPeriodicBoxVectors()` doesn't return `None`).  If they're in the file, MDTraj should be reading them.

**Comment by zhang-ivy** [comment]
In [this line](https://github.com/openmm/openmm/blob/be19e0222ddf66f612016a3c1f687161a53c2396/wrappers/python/openmm/app/dcdreporter.py#L107), the `DCDReporter` retrieves the box vectors from the `state`, not the topology. If the system is periodic, `getPeriodicBoxVectors()` cannot return None, right?

**Comment by peastman** [comment]
See the API docs on [DCDFile.writeModel()](http://docs.openmm.org/latest/api-python/generated/openmm.app.dcdfile.DCDFile.html#openmm.app.dcdfile.DCDFile.writeModel).

> The periodic box can be specified either by the unit cell dimensions (for a rectangular box), or the full set of box vectors (for an arbitrary triclinic box). If neither is specified, the box vectors specified in the Topology will be used. Regardless of the value specified, no dimensions will be written if the Topology does not represent a periodic system.

If the Topology doesn't define box vectors, it won't write them to the file.

**Comment by zhang-ivy** [comment]
>If the Topology doesn't define box vectors, it won't write them to the file.
Ah, I see. So even if `state.getPeriodicBoxVectors()` is not None, if the topology does not have box vectors, it will not write them to file. Why do we need to check that the topology defines box vectors in order to write them? It seems like it would be useful to write the box vectors regardless.

**Comment by peastman** [comment]
The State always contains periodic box vectors.  Even if nothing in your system uses periodic boundary conditions, there is still always a set of box vectors defined.  The writer needs to decide whether this is actually a periodic system, which it does based on the Topology.

**Comment by zhang-ivy** [comment]
Got it. Thanks!

**Comment by jchodera** [comment]
@zhang-ivy @peastman : Can we suggest an update to the [`DCDReporter` docs](http://docs.openmm.org/latest/api-python/generated/openmm.app.dcdreporter.DCDReporter.html#openmm.app.dcdreporter.DCDReporter) to make this clearer for the next time someone has this question?
