### ISSUE TITLE
How to calculate potential energy for a selection group (e.g. protein alone)

### ISSUE THREAD

**Issue by DanielWicz** [openmm/openmm#3425]
I want to know is where the protein is on the potential energy surface at the moment (e.g. if I will do 1000 steps, if protein in step 998 has lower/higher energy than in step 999). Since the simulations are carried out in the explicit solvent, the potential energy is dominated by the solvent energy. So I want to separate/calculate alone the protein's energy just for comparison

 I've identified few solutions to this questions:

- Create separate force groups for protein and solvent. Although it's a bit questionable if I will separate both energies like that, because still the fluctuations are highly dependent on the water-protein interactions
- Approximate the potential energy using separate calculation. But may be tricky, because I'd be forced to have a separate topology just for the protein. If I use e.g. charmmgui's parameters, then it becomes difficult
- Calculate using implicit solvent, then compare. But it once again requires separate force field

Anyway I would prefer to use OpenMM to do this or some proxy package like MdTraj/Parmed. What would you propose ?

**Comment by peastman** [comment]
I have two questions.  First, how do you define the "protein energy"?  And second, why do you want to compute it?  For example, does it include the energy of the protein's interaction with the solvent?  What about the effect of solvent reorganization induced by the protein?  If you don't include those things, what would you expect to learn from only the energy of internal interactions within the protein?

**Comment by aizvorski** [comment]
@DanielWicz I've dealt with a similar problem before by creating a CustomNonbondedForce which clones the standard nonbonded force - see #3281 for more details on that.  You can then calculate the nonbonded energy for part of the system only using `custom_nonbonded_force.addInteractionGroup()` (for interactions between two arbitrary sets of atoms).  If you want to do that on the fly during a simulation (without recreating the force or system), it should also be possible to call `setInteractionGroupParameters()` to switch between part of the system and whole system (note: I haven't tried that).  The downside is that there didn't seem to be any way to do that with PME, but it works fine with CutoffPeriodic.  Hope that works for your use case too.

@peastman Would it be possible to add `addInteractionGroup()` to the standard NonbondedForce to support this kind of usage without having to clone the force?

**Comment by DanielWicz** [comment]
@aizvorski 
Thnanks for your quick asnwer.
So in general I'd create a new simulation with `CutoffPeriodic` (now I use PME), add a new InteractionGroup and calculate make a 1 step energy calculation and extract the Interaction Group ?

**Comment by DanielWicz** [comment]
@peastman 
>First, how do you define the "protein energy"?
Actually potential energy of the protein, but I see now it's a bit more trickier. Nevertheless, I'd define it as the total potential energy (call it `Ep`) minus  energy of the solvent (call it `Esol`), so `Eprotein = Ep - Esol`. But at a given time, kinetic energy can push potential energy lower, because kinetic energy gets higher, making it not that much meaningful. 

>And second, why do you want to compute it? For example, does it include the energy of the protein's interaction with the solvent? 
>What about the effect of solvent reorganization induced by the protein? If you don't include those things, what would you expect to learn from only the energy of internal interactions within the protein?
What to check if the protein does not go to crazy, very high energy regions during the simulation. With regard to the solvent - I don't know at the moment, still thinking about it. 

But I see your point in the question, to reflect a bit about the physics of the idea, thanks.

**Comment by peastman** [comment]
> if you want to run the simulation while getting this kind of energy, you'd have to figure out some way to turn off the custom nonbonded force while the simulation is running

You can just put the CustomNonbondedForce into its own force group and call `setIntegrationForceGroups()` on the Integrator to tell it not to use that group.

Do you need to compute this every step or just occasionally?  If the later, you could just create a second System and Context in which all the water has been removed, then occasionally copy the protein positions over to it and evaluate its energy.  Doing that every step would be slow, but every 100 steps would probably be fine.

**Comment by DanielWicz** [comment]
@peastman 
I do it very occasionally, e.g. every 100000 steps or even less frequent. 

>If the later, you could just create a second System and Context in which all the water has been removed, then occasionally copy the protein positions over to it and evaluate its energy.

Two things pop up in my mind then:
1. If copy the system and remove water, I do need to create a new topology, yes ? I do it by using Modeller ? But what then if I use e.g. external topology from a PSF file ?
2. To evaluate the energy I just make one step of integration, then I get the state trough context ? Or there's another way ?

**Comment by peastman** [comment]
> If copy the system and remove water, I do need to create a new topology, yes ? I do it by using Modeller ? But what then if I use e.g. external topology from a PSF file ?

Modeller is one way to do it.  If you're loading from a PSF file, it's probably easiest if you create a second PSF file in which the water is removed.  I assume AmberTools has some way to do that?

> To evaluate the energy I just make one step of integration, then I get the state trough context ? Or there's another way ?

No need to perform integration.  Just call `setPositions()` to set the new positions, then `getState()` to query the energy.

**Comment by DanielWicz** [comment]
@peastman 
I see MDTraj has method `to_openmm` in the Topology class. Do you know if OpenMM would work with MDTraj edited topology ?

**Comment by peastman** [comment]
That would work too.  The question is, how are you parametrizing the system?  If you're using an OpenMM force field, Modeller is the simplest way to edit the Topology, and then you can easily create a new System using the force field.  If you're relying on CharmmPsfFile to build the System, it will be simpler if you can create an edited version of the file.  ParmEd is also another way you could do it.

**Comment by DanielWicz** [comment]
@peastman 
In general I want to use OpenMM's objects as much as possible, because I use different formats (sometimes openmmtools test systems, sometimes charmm, sometimes gromacs). This would make my code far simpler than if I create a solution for every case scenario. I have tried to implement it fallowing my objective as fallowing: 


```
class EnergySelect:
    def __init__(self, topology, system, selection="protein"):
        self.selection = selection
        # create MDtraj topology
        topology = md.Topology.from_openmm(topology)
        
        # select atoms according to the selection
        self.sub_ind = topology.select(self.selection)
        # create a slice of topology
        sub_top = topology.subset(self.sub_ind)
        # save old topology to make a from positions
        self.old_topology = topology
        # convert sliced topology to the openmm format
        self.topology = sub_top.to_openmm()
        integrator = LangevinMiddleIntegrator(300*kelvin, 1/picosecond, 0.004*picoseconds)
        # here is the problem
        forcefield = ???? # e.g. ForceField('charmm36.xml') or preferably extract from System object
        self.system = forcefield.createSystem(self.topology, nonbondedMethod=CutoffNonPeriodic, nonbondedCutoff=2.0*nanometers)
        self.simulation = Simulation(self.topology, self.system, integrator)
        
    def calc_energy(self, positions):
        # slice trajectory
        trajectory = md.Trajectory(positions, self.old_topology)
        new_positions = trajectory.atom_slice(self.sub_ind).xyz[0]
        self.simulation.context.setPositions(new_positions)
        state = self.simulation.context.getState(getEnergy=True)
        
        return state.getPotentialEnergy()
```
The only problem and I think most difficult is to extract parameters from the `System` object and slice it according to the selection. I've tried to use Parmed here with the unsliced topology/system, `struct = prm.openmm.load_topology(topology, system)`, and then extract the protein to `struct_sliced` and create a new system with `struct_sliced.createSystem(nonbondedMethod=CutoffNonPeriodic, nonbondedCutoff=2.0*chem.unit.nanometers)` but without much success, because I get `ParameterError: Cannot find necessary parameters`.

**Comment by peastman** [comment]
The easiest way of doing it will be if you're building your System from a force field.  In that case, you can just edit the Topology and call `createSystem()` twice on the same ForceField, once for the full topology and once for the edited one.

The next easiest is if you can use ParmEd.  Editing fully parametrized systems is what it's designed for.  I don't know what's causing the error you mentioned.  You could try opening an issue on the ParmEd repo to ask about it.

If you want to edit the fully parametrized system without using ParmEd it will be a bit more work.  OpenMM doesn't include any features specifically for that, so you'll need to write the code yourself.  It shouldn't be that difficult though.  Here's the basic approach.

1. Create a new System.
2. Copy over every particle that you want to include.  In the process, build a dict mapping particle indices in the original System to ones in the new System.  You'll need that for all the other steps below.
3. Copy over every constraint that connects two particles that are both included, using your dict to translate particle indices correctly.
4. Loop over every Force in the System and add a new Force of the same type to the new System.  Loop over every particle/bond/angle/etc. contained in the Force and add it to the new Force, assuming it only contains particles that are being included.

**Comment by DanielWicz** [comment]
Okey, here is one based on your help and @swails. Maybe it will be helpful to someone else so I post it here:

```
from simtk.openmm.app import *
from simtk.openmm import *
from simtk.unit import *
from openmmtools.testsystems import SrcExplicit
from sys import stdout
import mdtraj as md
import numpy as np
import parmed as prm

class EnergySelect:
    def __init__(self, topology_openmm, system, selection_md="protein"):
        """The class allows calculating MD energy for a given selection.
            To init the class it's requires to pass openmm topology and system.
            Arguments:
            topology_openmm: Topology of the full system from the openmm
            system: System object from the OpenMM
            selection_md: Selection for the calculated energy, according to the MDTraj syntax
        """
        self.selection_md = selection_md
        # create MDtraj topology
        topology = md.Topology.from_openmm(topology_openmm)
        # select atoms according to the selection
        self.sub_ind = topology.select(self.selection_md)
        # create a slice of topology
        sub_top = topology.subset(self.sub_ind)
        # save old topology to make a from positions
        self.old_topology = topology
        # convert sliced topology to the openmm format
        self.topology = sub_top.to_openmm()
        
        # Creating system only for protein
        struct = prm.openmm.load_topology(topology_openmm, system)
        # select structure
        struct = struct[self.sub_ind]
        # if there're hbond restrains, add parameters
        new_bond_type = prm.topologyobjects.BondType(k=400, req=1.0)
        constrained_bond_type = struct.bond_types.append(new_bond_type)
        struct.bond_types.claim()

        for bond in struct.bonds:
            if bond.type is None:
                bond.type = new_bond_type
                
        # crete a new system
        new_system = struct.createSystem(nonbondedMethod=CutoffNonPeriodic, nonbondedCutoff=2.0*prm.unit.nanometers)
        self.system = new_system
        # creating simulation object
        integrator = LangevinMiddleIntegrator(300*kelvin, 1/picosecond, 0.004*picoseconds)
        self.simulation = Simulation(self.topology, self.system, integrator)
        
    def calc_energy(self, positions):
        trajectory = md.Trajectory(positions, self.old_topology)
        new_positions = trajectory.atom_slice(self.sub_ind).xyz[0]
        self.simulation.context.setPositions(new_positions)
        state = self.simulation.context.getState(getEnergy=True)
        
        return state.getPotentialEnergy()
```

To use it you create an object with selection, system and topology:
`enesel = EnergySelect(topology, system, selection_md="protein")`
and then pass the coordinates to calculate energy
`enesel.system.getNumParticles()` and voila ! We have energy
