### ISSUE TITLE
Question: how to remove atoms / bonds from a topology?

### ISSUE THREAD

**Issue by orioncohen** [openmm/openmm#3431]
What is the cleanest way to remove atoms (and their bonds) from an OpenMM topology?

If I know the index of the atoms in the topology, can I use that to remove them?

**Comment by peastman** [comment]
Use `Modeller.delete()`.

```python
modeller = Modeller(topology, positions)
modeler.delete(<list of atoms, bonds, etc.>)
topology = modeller.topology
positions = modeller.positions
```

See the [manual](http://docs.openmm.org/latest/userguide/application/03_model_building_editing.html) and [API docs](http://docs.openmm.org/latest/api-python/generated/openmm.app.modeller.Modeller.html) for more details.

**Comment by orioncohen** [comment]
Thank you @peastman. I didn't think to use `Modeller`.
