### ISSUE TITLE
Error when ForceField is instantiated with two .xml files

### ISSUE THREAD

**Issue by Gareth-elliott** [openmm/openmm#3433]
Hi OpenMM Developers,

There appears to be an error that occurs when a simulation is set up with two .xml files. It happens for me when a system uses in-plane angles. I did have a bit of a go at tracking down the issue, but I got a bit lost. I did figure out that the index error occurs for angle[3]. Here are files necessary to produce the error (the only difference between the *_works and *_error is the addition of amoeba2018.xml to the ForceField call:

[computeEnergies_works.py.txt](https://github.com/openmm/openmm/files/7949550/computeEnergies_works.py.txt)
[computeEnergies_error.py.txt](https://github.com/openmm/openmm/files/7949551/computeEnergies_error.py.txt)
[n-methylformamide.xml.txt](https://github.com/openmm/openmm/files/7949552/n-methylformamide.xml.txt)
[n-methylformamide.pdb.txt](https://github.com/openmm/openmm/files/7949553/n-methylformamide.pdb.txt)

and here is the stack trace that I'm getting:

Traceback (most recent call last):
  File "./computeEnergies_error.py", line 11, in <module>
    system = forcefield.createSystem(pdb.topology, polarization='mutual', mutualInducedTargetEpsilon=1e-4)
  File "....../forcefield.py", line 1363, in createSystem
    force.createForce(sys, data, nonbondedMethod, nonbondedCutoff, args)
  File "....../forcefield.py", line 3848, in createForce
    force.createForcePostOpBendInPlaneAngle(sys, data, nonbondedMethod, nonbondedCutoff, angles, args)
  File "....../forcefield.py", line 3623, in createForcePostOpBendInPlaneAngle
    force.addBond((angle[0], angle[1], angle[2], angle[3]), (self.angle[i][0], self.k[i]))
IndexError: list index out of range

Thanks,

Gareth

**Comment by peastman** [comment]
I figured out the problem.  The fix is in #3438.  Thanks!

**Comment by Gareth-elliott** [comment]
Thanks a lot @peastman! 👍
