### ISSUE TITLE
chargeProd not updated following updateParametersInContext() or reinitialize()

### ISSUE THREAD

**Issue by jhymel** [openmm/openmm#3436]
I seem to be running into an issue regarding what I believe to be a fairly common procedure, changing the charge on an atom during the course of a simulation. When I update the charge on an atom using <code>NonbondedForce.setParticleParameters()</code> followed by <code>NonbondedForce.updateParametersInContext(Simulation.context)</code>, the charge on the atom is updated appropriately. I run into my issue when checking the NonbondedForce exceptions. The chargeProd between the atom whose charge I changed and any atom 1-4 to it is not updated. 

Before making this post, I read through a still open issue (#3427) which prompted the addition of a new section to the [OpenMM FAQ page](https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#system). Reading through this, I realize that whether or not a particular variable gets updated by <code>updateParametersInContext()</code> depends on the Force involved. Reading the [documentation](http://docs.openmm.org/latest/api-python/generated/openmm.openmm.NonbondedForce.html#openmm.openmm.NonbondedForce.updateParametersInContext) on <code>NonbondedForce.updateParametersInContext()</code>, I interpret this to mean that the method should update the chargeProd, sigma, and epsilon values of an exception, but like I said, this does not appear to be the case. I have instead tried using the more expensive procedure, <code>reinitialize(preserveState=True)</code>, to no avail.

I have created a minimum working example which demonstrates this issue: [ethyne_test_case.tar.gz](https://github.com/openmm/openmm/files/7966976/ethyne_test_case.tar.gz)
In this example, I demonstrate this issue using ethyne where the two hydrogens (bonded 1-4 to one another) have a coulomb14scale of 0.5. The chargeProd between the two hydrogens remains the same after the charge on one is altered and updated in context.

**Comment by peastman** [comment]
If you want to update the exceptions, you need to modify them by calling `setExceptionParameters()`.  `createExceptionsFromBonds()` is just a convenience method to simplify a common case.  The exceptions it creates are no different from ones you add directly with `addException()`: you're free to modify them at any time, and they don't maintain any fixed relationship to the particles they were created from.  That's the whole point of exceptions, after all.

**Comment by peastman** [comment]
Closing this since the question was answered.  Feel free to reopen it if I missed something.
