### ISSUE TITLE
No template found for residue 24 (PHE).  The set of atoms matches PHE, but the bonds are different.

### ISSUE THREAD

**Issue by pguillem** [openmm/openmm#3439]
Hello all.

I have gone through all other similar posts and docs. I couldn't find a workaround, nor explain why _createSystem_ complains about this residue "looking like" a PHE but not having the right bonds. The PDB came straight from PyMOL. I also tried to export with Maestro/MoE, same result. I also ran it through openmm setup, pdb4amber and pdbfixer.... same outcome.

- I'm using OpenMM 7.7.0 (via anaconda)
- ForceField('amber14-all.xml', 'amber14/tip3p.xml')

Running script was generated with Openmm Setup. Fails with and without cleaning the PDB file.

Here is how that famous F24 is defined in my PDB.. i'm not entirely sure what the program es expecting.
Can anybody share some light?

```
ATOM    313  N   PHE    24      -3.189 -10.360  -9.067  1.00  0.00           N  
ATOM    314  CA  PHE    24      -3.385 -11.206  -7.893  1.00  0.00          C  
ATOM    315  C   PHE    24      -3.549 -12.654  -8.289  1.00  0.00           C  
ATOM    316  O   PHE    24      -2.565 -13.236  -8.824  1.00  0.00           O  
ATOM    317  CB  PHE    24      -4.656 -10.751  -7.114  1.00  0.00          C  
ATOM    318  CG  PHE    24      -4.628  -9.331  -6.527  1.00  0.00           C  
ATOM    319  CD1 PHE    24      -5.347  -8.308  -7.156  1.00  0.00          C  
ATOM    320  CD2 PHE    24      -3.843  -9.034  -5.410  1.00  0.00          C  
ATOM    321  CE1 PHE    24      -5.267  -7.002  -6.685  1.00  0.00          C  
ATOM    322  CE2 PHE    24      -3.772  -7.728  -4.932  1.00  0.00          C  
ATOM    323  CZ  PHE    24      -4.481  -6.712  -5.572  1.00  0.00           C  
ATOM    324  H   PHE    24      -2.341  -9.815  -9.129  1.00  0.00            H  
ATOM    325  HA  PHE    24      -2.494 -11.127  -7.242  1.00  0.00          H  
ATOM    326 2HB  PHE    24      -4.858 -11.465  -6.291  1.00  0.00         H  
ATOM    327 3HB  PHE    24      -5.548 -10.850  -7.766  1.00  0.00         H  
ATOM    328 1HD  PHE    24      -5.933  -8.520  -8.040  1.00  0.00          H  
ATOM    329 2HD  PHE    24      -3.274  -9.813  -4.921  1.00  0.00          H  
ATOM    330 1HE  PHE    24      -5.801  -6.215  -7.196  1.00  0.00          H  
ATOM    331 2HE  PHE    24      -3.158  -7.501  -4.072  1.00  0.00          H  
ATOM    332  HZ  PHE    24      -4.417  -5.697  -5.211  1.00  0.00           H  
```

**Comment by peastman** [comment]
Can you post the full PDB file?

**Comment by pguillem** [comment]
Hi @peastman, thanks in advance.
I had to rename the extension to TXT so github would allow it. Just remove the extension.

[test.pdb.txt](https://github.com/openmm/openmm/files/7985617/test.pdb.txt)

I'm also checking the source code of createSystem() and below to try tracing the exit condition.
Best
Pedro

**Comment by pguillem** [comment]
So, **_getResidueTemplateMatches()** is not matching that PHE.
I'm checking exactly where the match() is failing.

<Residue 22 (HIS) of chain 0>
<openmm.app.forcefield.ForceField._TemplateData object at 0x7fd78c486eb0>
matches [0, 2, 15, 16, 4, 7, 13, 8, 9, 11, 1, 3, 5, 6, 14, 10, 12]

**<Residue 23 (PHE) of chain 0>**
**None**

**Comment by pguillem** [comment]
Dear @peastman. 
I traced the error back to a parsing issue with the hydrogens, specially the AtomName column (third column of the PDB. Looks like the PyMol Mutagenesis Wizzard introduces the hydrogen atom number in pos 13 instead of 16. 

I have no idea if there is some flexibility (or convention) defining the position of this number, but other legacy IDEs seem to understand it.

Note the original PDB (see bold)

```
ATOM    324  H   PHE    24      -2.341  -9.815  -9.129  1.00  0.00           H  
ATOM    325  HA  PHE    24      -2.494 -11.127  -7.242  1.00  0.00           H  
ATOM    326 **2**HB  PHE    24      -4.858 -11.465  -6.291  1.00  0.00           H  
ATOM    327 **3**HB  PHE    24      -5.548 -10.850  -7.766  1.00  0.00           H  
ATOM    328 **1**HD  PHE    24      -5.933  -8.520  -8.040  1.00  0.00           H  
ATOM    329 **2**HD  PHE    24      -3.274  -9.813  -4.921  1.00  0.00           H  
ATOM    330 **1**HE  PHE    24      -5.801  -6.215  -7.196  1.00  0.00           H  
ATOM    331 **2**HE  PHE    24      -3.158  -7.501  -4.072  1.00  0.00           H  
ATOM    332  HZ  PHE    24      -4.417  -5.697  -5.211  1.00  0.00           H  
```

This is how the corrected PDB format should look like. This one worked in openMM.

```
ATOM    324  H   PHE    24      -2.341  -9.815  -9.129  1.00  0.00           H
ATOM    325  HA  PHE    24      -2.494 -11.127  -7.242  1.00  0.00           H
ATOM    326  HB**2** PHE    24      -4.858 -11.465  -6.291  1.00  0.00           H
ATOM    327  HB**3** PHE    24      -5.548 -10.850  -7.766  1.00  0.00           H
ATOM    328  HD**1** PHE    24      -5.933  -8.520  -8.040  1.00  0.00           H
ATOM    329  HD**2** PHE    24      -3.274  -9.813  -4.921  1.00  0.00           H
ATOM    330  HE**1** PHE    24      -5.801  -6.215  -7.196  1.00  0.00           H
ATOM    331  HE**2** PHE    24      -3.158  -7.501  -4.072  1.00  0.00           H
ATOM    332  HZ  PHE    24      -4.417  -5.697  -5.211  1.00  0.00           H
```

Maybe I could add a snippet to correct and account for this weird hydrogen formatting with a regexp...? I'm sure it happens to others out there.

**Comment by peastman** [comment]
Take a look at https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template.  It explains what's going on and why you encounter this error.  We can add those names to our list of recognized nonstandard names.  I also suggest filing a bug report with the PyMol developers telling them they're producing incorrect names.
