### ISSUE TITLE
OpenMM Metadynamics on Distance between two particles

### ISSUE THREAD

**Issue by phu91** [openmm/openmm#3444]
Hello, 
I want to simulation a particle in an external field. This particle is now subjected to Metadynamics simulation so it can cross high-energy barrier. 
Could anyone please show me how to define a CUSTOM CV in OpenMM? If anyone can provide an example template, that will be super helpful for future development. 

Thank you so much. 
```from sys import stdout
from turtle import distance
import numpy as np
from simtk.openmm import *
from simtk.openmm.app import *
from simtk.openmm.openmm import *
from simtk.unit import *
from sys import stdout

class Reporter(object):
    def __init__(self, file, reportInterval):
        self._out = open(file, 'w')
        self._out.write("ps\tx1\tx2\n")
        self._reportInterval = reportInterval
        
    def __del__(self):
        self._out.close()

    def describeNextReport(self, simulation):
        steps = self._reportInterval - simulation.currentStep%self._reportInterval
        return (steps, True, False, True, True, None)

    def report(self, simulation, state):
        forces = state.getForces().value_in_unit(kilojoule/mole/nanometer)
        position=state.getPositions(asNumpy=False).value_in_unit(nanometer)
        energy = state.getPotentialEnergy()._value
        time = state.getTime().value_in_unit(picosecond)
        self._out.write('%g\t%g\t%g\n' % (time,position[0][0],position[1][0]))      #position[atom index][x,y,z]
 
temperature = 298*kelvin
natom = 2
n_steps = 1000

system = System()
system.addParticle(1)   # particle 0 - mass 0 => no change in positions and velocity
system.addParticle(0)   # particle 1 

print("Adding Force ...")
g_dagger_value = 4	#kBT
energy_func = 'step(abs(x))*(step(f)*v+step(-f)*u);f=abs(x)-1/2;u=u0*g_dagger;v=v0*g_dagger;u0=-2*x^2;v0=2*(abs(x)-1)^2-1'
force = CustomExternalForce(energy_func) 
force.addGlobalParameter("g_dagger",g_dagger_value)

for i in range(natom):
    force.addParticle(i,[])
    
system.addForce(force)
 
expr = "distance(p0,p1)"
cv_defined = CustomCVForce(expr)
cv_bias = cv_defined.getCollectiveVariableValues()```

**Comment by peastman** [comment]
The easiest way to perform metadynamics is with the [Metadynamics](http://docs.openmm.org/latest/api-python/generated/openmm.app.metadynamics.Metadynamics.html) class.  To use it, you create a [BiasVariable](http://docs.openmm.org/latest/api-python/generated/openmm.app.metadynamics.BiasVariable.html) object for your CV and pass it to the Metadynamics object's constructor.  If anything in the documentation isn't clear, let me know.

**Comment by phu91** [comment]
Thank you. I found out that openmm-plumed plugin give me more flexible in designing new COLVARS. 
`from openmm-plumed import PlumedPlace`

**Comment by peastman** [comment]
Great, good to hear that works for you.  I'm going to close this, since I think the question has been answered.  Feel free to reopen it if I missed something.
