### ISSUE TITLE
Passing residueTemplates dictionary to other functions

### ISSUE THREAD

**Issue by rosemary-cresset** [openmm/openmm#3445]
ForceField.createSystem allows me to pass a dictionary of residueTemplates to specify whether I want the Fe2+ or Fe3+ template. It would be good if it was also possible to pass the residueTemplates dictionary to Modeller.addExtraParticles, ForceField.getUnmatchedResidues and Modeller.addSolvent. At the moment, all of those functions throw an error if I pass a topology that contains Fe and the only way I can get round this is convert my Fe ions into another element and then convert them back again before I call createSystem.

**Comment by peastman** [comment]
That would make sense.  I'll tag this is as a feature request.

**Comment by peastman** [comment]
This is implemented in #4211.
