### ISSUE TITLE
Changing nonbonded parameters causing system to explode in openmm 7.5.0+

### ISSUE THREAD

**Issue by olliemelling** [openmm/openmm#3447]
Hi,

I'm having an issue with the system exploding (i.e. very high potential energies resulting in `Particle coordinate is nan` errors) in OpenMM versions 7.5.0 and later when perturbing the nonbonded parameters of atoms.

Here is a simple example that takes a small water box and sets the nonbonded parameters to 0 for one of the waters before minimizing and running MD. This will run fine in openmm version 7.4.2 but the system explodes instantly during minimisation in versions 7.5.0 and later.
```
from openmmtools.integrators import BAOABIntegrator
from simtk.openmm.app import *
from simtk.openmm import *
from simtk.unit import *

pdb = PDBFile('water_box-eq.pdb')
ff = ForceField('amber14/tip3p.xml')
system = ff.createSystem(pdb.topology, nonbondedMethod=PME, constraints=HBonds, switchDistance=1.0*nanometer, nonbondedCutoff=1.2*nanometer)

integrator = BAOABIntegrator(timestep=2*femtoseconds, temperature=298*kelvin, collision_rate=1.0/picosecond)

platform = Platform.getPlatformByName("CUDA")
platform.setPropertyDefaultValue("Precision", "mixed")

simulation = Simulation(pdb.topology, system, integrator, platform)

simulation.context.setPositions(pdb.positions)
simulation.context.setVelocitiesToTemperature(298*kelvin)
simulation.context.setPeriodicBoxVectors(*pdb.topology.getPeriodicBoxVectors())

for force in system.getForces():
    if force.__class__.__name__ == "NonbondedForce":
        nb_force = force

for atom in pdb.topology.atoms():
    if atom.residue.index == 0:
        print(atom)
        nb_force.setParticleParameters(atom.index, 0*elementary_charge, 0*nanometers, 0*kilojoules_per_mole)

nb_force.updateParametersInContext(simulation.context)

simulation.minimizeEnergy()
simulation.step(1000)
```

I had a look through the change logs of the recent releases but couldn't see anything that seemed like it would be causing this. Any guidance would be much appreciated.

Thanks

**Comment by peastman** [comment]
I'm not sure what would cause that.  Here are just a few ideas that come to mind.

Try setting `sigma` to a nonzero value, like 0.1 nm.
Try using the Reference platform.
Try also setting charge and epsilon to 0 for all the exceptions involving atoms in that residue.

Does any of those make a difference?

**Comment by olliemelling** [comment]
I've looked into this further and it appears the error described above is actually only seen when using both CUDA and mixed precision. Any other combination of platform and precision (i.e. single or double precision on CUDA or any precision with OpenCL) work fine.

**Comment by olliemelling** [comment]
Making simga non-zero and setting the charge and epsilon to 0 did not have an effect. In fact it appears that it crashes if the charge, sigma and epsilon are set to any values other than their initial values defined by the forcefield - even if they are only adjusted very slightly.

If the charge and epsilon are set to 0 for all the exceptions (I assume this means all the waters in the system so everything is turned off?) then it runs without any problem. But if charge or epsilon for any one atom is set to a non-zero value then the system will crash. Basically, it seems to only runs if everything is off or everything is turned on and at its initial forcefield-defined value which seems very odd.

Using the LangevinMiddleIntegrator also had no effect - the same issues arose.

**Comment by peastman** [comment]
Can you post your input file?  I'd like to try to reproduce it.

**Comment by olliemelling** [comment]
[openmm_error.zip](https://github.com/openmm/openmm/files/8050367/openmm_error.zip)
