### ISSUE TITLE
Volume not changing with MonteCarloBarostat for NpT equilibration

### ISSUE THREAD

**Issue by bbye98** [openmm/openmm#3448]
Hello!

I am trying to run a simulation with a few NpT steps for equilibration and then switching to NVT for the production run. This is my current Python input script (without the NVT/production part):

    from openmm.app import *
    from openmm import *
    from openmm.unit import *
    from sys import stdout
    import numpy as np
    import os

    P = 1*atmosphere
    T = 300*kelvin
    FREQ = 1/picosecond
    CUTOFF = 12*angstrom
    TS = 1*femtosecond
    TS_INT = 1000
    TS_NPT = 50000
    TS_EQ = 100000
    TS_NVT = 1000000

    pdb = PDBFile('topology.pdb')
    ff = ForceField('forcefield.xml')
    system = ff.createSystem(pdb.topology, nonbondedMethod=PME, nonbondedCutoff=CUTOFF)
    integrator = LangevinIntegrator(T, FREQ, TS)
    sim = Simulation(pdb.topology, system, integrator)
    sim.context.setPositions(pdb.positions)
    sim.minimizeEnergy()
    sim.reporters.append(DCDReporter('trajectory.dcd', TS_INT))
    sim.reporters.append(
        StateDataReporter(
            stdout, TS_INT, step=True, potentialEnergy=True, kineticEnergy=True,
            temperature=True, volume=True, density=True,
            remainingTime=True, speed=True, totalSteps=TS_NPT + TS_EQ + TS_NVT
        )
    )

    mcb = MonteCarloBarostat(P, T, 25)
    system.addForce(mcb)
    V0 = sim.context.getState().getPeriodicBoxVolume()
    Vt = np.zeros(TS_NPT // TS_INT, dtype=Quantity)
    for i in range(TS_NPT // TS_INT):
        sim.step(TS_INT)
        Vt[i] = sim.context.getState().getPeriodicBoxVolume()
    # system.setDefaultPeriodicBoxVectors(...)
    system.removeForce(mcb)

I get the box volume and store it in `V0` before the NpT run, but the volumes returned in the `for` loop are the same as `V0`. This is perhaps a silly question, but am I missing something simple? Is it because I specified the initial system configuration as a `.pdb` file? According to an identical simulation run in LAMMPS, the box volume should change (shrink) as the system equilibrates. I have tried to find example OpenMM simulations with NpT runs but did not come across any that shed any light on my problem.

For reference, the `.pdb` and `.xml` files are from Avogadro/LigParGen/`fftool`/Packmol.

I would appreciate any input anyone has to offer! Thank you in advance!

**Comment by peastman** [comment]
The problem is that you don't add the barostat to the System until after you create the Simulation/Context.  Once a Context is created, any later changes made to the System (such as adding a new Force) don't affect it.  See https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#system for more information.

**Comment by bbye98** [comment]
@peastman Thank you for the information. I was not aware that `Context`s were immutable.

In this case, what would be the best solution? Would it be to complete the NpT equilibration, write out the atom positions, and then set up another NVT simulation to continue from there?

**Comment by peastman** [comment]
You can just add the barostat once you finish the equilibration and then call `reinitialize()` on the Context.  This is discussed in the FAQ entry linked above.
