### ISSUE TITLE
Can not install OpenMM successfully 

### ISSUE THREAD

**Issue by smiles724** [openmm/openmm#3449]
Hi, thanks for providing such a useful tool.

I encountered a problem when installing the package. I tried both 'conda install -c conda-forge openmm' and 'conda install -c conda-forge openmm cudatoolkit=10.0', but still could not tackle the problem. The error reports that the environment is incompatible with OpenMM. 

Can you give me some hints on how to install OpenMM more conveniently and easily?

**Comment by peastman** [comment]
That means you have something else already installed in your environment with incompatible requirements.  In that case, it's best to create a new environment for OpenMM:

```
conda create --name openmm python=3.9
conda activate openmm
conda install -c conda-forge openmm
```

**Comment by smiles724** [comment]
Thanks

**Comment by peastman** [comment]
I'm closing this, since I think the question has been answered.  Feel free to reopen it if it still isn't working.
