### ISSUE TITLE
Simulation drags protein/ligand outside of the waterbox

### ISSUE THREAD

**Issue by pguillem** [openmm/openmm#3452]
An image is worth a thousand words.

The program is moving each object to the border of the water box, instead of simulating both inside the water box. Script came straight out of openmm-setup.

INPUT SYSTEM
![MD1](https://user-images.githubusercontent.com/1541205/152809380-6c7a1399-0be1-4913-b1f9-171cd3ffeb32.png)

MD FRAME 1
![MD2](https://user-images.githubusercontent.com/1541205/152809372-18277113-a5ff-4df1-a171-f9dfad120de9.png)

Any ideas?
Pedro

**Comment by pguillem** [comment]
If both proteins were repulsive enough this would make sense, but this is not the case. Maybe the cell is too big and this is (offcourse) the best starting energy after minimization/equilibration?.

Is there an explicit way to match the cell boundary to the borders of the waterbox?. any other pointers here?

**Comment by peastman** [comment]
Take a look at https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#periodic.  It explains what is going on.

**Comment by pguillem** [comment]
Thank you. This made it a lot clearer.

Solution:
`nonbondedMethod = CutoffNonPeriodic`

**Comment by stefdoerr** [comment]
That's not really the solution. The solution is to wrap the simulation after it's completed. Disabling periodic interactions is not going to produce very good simulations (afaik)

**Comment by pguillem** [comment]
Thanks for the valuavle insight @stefdoerr, very much appreciated.

I benchmarked the output against amber20 and it seems very consistent.. might be luck, probably due to the system itself.
...however I would like to fully understand the principle here.

What exactly do you mean by "wrapping" and how should it be done?
Best, and thanks in advance.

Pedro

**Comment by stefdoerr** [comment]
https://software.acellera.com/docs/latest/htmd/tutorials/WrappingTutorial.html
Here you can see an explanation on periodic interactions. Should help clarify things with the above link by Peter

**Comment by pguillem** [comment]
Roger that.
I'll give it a good read.

Thanks!
