### ISSUE TITLE
How to save a topology that is created by openMM? 

### ISSUE THREAD

**Issue by asgharrazavi** [openmm/openmm#3453]
Is there an easy way to save topology information that is created by `simtk.openmm.app.forcefield.ForceField`?
Most other software create topology files, e.g. .top file in GROMACS, .psf file in NAMD, .parm7 in Amber. It would be great if OpenMM would offer the same convenience and save topology information in a file.

**Comment by peastman** [comment]
Do you mean a Topology or a System?  Since you said that it's created by a ForceField, I assume you mean System?  Yes, you can serialize it to an XML file:

```python
with open('system.xml', 'w') as output:
  output.write(XmlSerializer.serialize(system))
```

Then you can load it back with

```python
with open('system.xml') as input:
  system = XmlSerializer.deserialize(input.read())
```

We should add a cookbook entry for this.

**Comment by swails** [comment]
`simtk.openmm.app.forcefield.ForceField` doesn't create a topology, it creates an OpenMM `System` object when given a Topology object.  This is all you need (along with a set of starting coordinates) to launch an MD simulation.

You can save a System object as an XML file using OpenMM's XML serializer.  The System object is part of the core OpenMM API (part of the C++ implementation wrapped in Python with SWIG).

The Topology object, on the other hand, is instantiated from a PDB file (or Amber prmtop, CHARMM PSF, or GROMACS topology file) and only exists in the Python application layer.  There is no XML serializer for this object to my knowledge.  You can use Python's pickle module to do (Python-specific) serialization.

**Comment by asgharrazavi** [comment]
The solution provided by @peastman would work for me, but it would be great to have something like this for OpenMM as well:

```
# AMBER input
prmtop = AmberPrmtopFile('mol.parm7')
inpcrd = AmberInpcrdFile('mol.rst7')
system = prmtop.createSystem()
```
Meaning that to have a way of saving and loading topology created by OpenMM. PDB files don't have all the topology information, especially if there are extra custom defined bonds, angles. This will also help visualizations later on when using other software like VMD.
