### ISSUE TITLE
Do custom forces apply during energy minimization?

### ISSUE THREAD

**Issue by asgharrazavi** [openmm/openmm#3455]
I am wondering whether OpenMM keeps custom forces, e.g. additional bonds using code below, during minimization? 

```
import simtk.openmm as mm
req = 0.235  # req in nm
k = 1000  # k in kJ/mol/nm^2
bond = mm.HarmonicBondForce()
bond.addBond(id1, id2, req, k)
system.addForce(bond)
```

I noticed that the restrained atoms move somewhat during minimization but keep their position during equilibration, so, I was wondering if energy minimization function considers the additional forces?

**Comment by peastman** [comment]
Yes, all Force objects are included when minimizing.

**Comment by peastman** [comment]
I'm closing this issue, since the question has been answered.
