### ISSUE TITLE
How to keep pdb residue numbering when saving positions as a pdb file?

### ISSUE THREAD

**Issue by asgharrazavi** [openmm/openmm#3459]
I noticed that when I use the below code to write pdb files of my system, the residue numbering for each chain starts from 1. How can I ask OpenMM not to automatically renumber residues?

```
with open('system.pdb', 'w') as f:
    PDBFile.writeFile(modeller.topology, modeller.positions, f)
```

**Comment by peastman** [comment]
Add the argument `keepIds=True` in the call to `writeFile()`.

**Comment by asgharrazavi** [comment]
Thanks @peastman , that trick works perfect, this vastly simplifies comparing outputs of two simulations when each started with a different crystal structure of the same system.
In general, it might be good to set the defaults to least perturb the input information.

**Comment by peastman** [comment]
It's a hard call.  The problem is that it's really common to come across topologies that don't have valid IDs, especially for the chains.  The default is chosen to guarantee you'll get a valid output file.

**Comment by jchodera** [comment]
I agree that most users would want to _not_ lose information silently by default without warning---this violates the principle of minimum surprise in an API.

Peerhaps the default could be `keepIds=True`, and we could change the behavior of this to only try to keep the IDs if they are valid? Invalid IDs can raise an exception---which is arguably the appropriate behavior when the method is fed an invalid `Topology` argument.

We could add a third option `keepIds='force'` which would always force IDs to be written even if invalid, which would recover the old `keepIds=True` behavior. Users that want to generate a file that is renumbered (which is an uncommon use case) could use the exceptions to tell them they should use `keepIds=False`.
