### ISSUE TITLE
Periodicity error when reading AMBER parm7 file

### ISSUE THREAD

**Issue by halx** [openmm/openmm#3466]
Hi,

the code at the end results in the following error in OpenMM 7.7.0-py39h9717219_0 from conda-forge.  The code works with a previous 7.6 from the same channel. Inputs are attached.  
[inputs.tar.gz](https://github.com/openmm/openmm/files/8078753/inputs.tar.gz)

Traceback (most recent call last):
  File "/home/xyzz/torsion_error.py", line 17, in <module>
    simulation = app.Simulation(prmtop.topology, system, integrator)
  File "/appsr/miniconda3/envs/sire/lib/python3.9/site-packages/openmm/app/simulation.py", line 99, in __init__
    self.context = mm.Context(self.system, self.integrator)
  File "/apps/miniconda3/envs/sire/lib/python3.9/site-packages/openmm/openmm.py", line 16305, in __init__
    _openmm.Context_swiginit(self, _openmm.new_Context(*args))
openmm.OpenMMException: PeriodicTorsionForce: periodicity must be positive

```
import openmm.app as app
import openmm
import openmm.unit as units


prmtop = app.AmberPrmtopFile('Input.prm7')
inpcrd = app.AmberInpcrdFile('Input.rst7')

system = prmtop.createSystem(nonbondedMethod=app.PME,
                             nonbondedCutoff=10.0*units.angstrom,
                             constraints=app.HBonds)

integrator = openmm.LangevinMiddleIntegrator(300.0*units.kelvin,
                                             1.0/units.picosecond,
                                             0.004*units.picoseconds)

simulation = app.Simulation(prmtop.topology, system, integrator)
```

**Comment by swails** [comment]
I believe negative periodicities are relics of ancient force fields and prmtops.  As long as the phase shift is 0 or 180 degrees, the torsion potential is identical for positive or negative periodicities.  You can "fix" the prmtop with ParmEd using something like the following script (untested):

```python
import parmed as pmd
import math

old_parm = pmd.amber.AmberFormat("Input.prm7")

TOL = 1e-4

for i, (per, phase) in enumerate(zip(parm.parm_data["DIHEDRAL_PERIODICITY"], parm.parm_data["DIHEDRAL PHASE"])):
    if per > 0:
        continue
    if per == 0:
        raise ValueError("0-periodicity torsions have no effect on the forces and should be dropped.")
    if phase == 0 or abs(phase - math.pi) < TOL:
        parm.parm_data["DIHEDRAL_PERIODICITY"][i] = abs(per)
    else:
        raise ValueError(f"Cannot remove negative periodicities with a phase angle of {phase} rad")

old_parm.write_parm("Input_fixed.prm7")
```

This will throw up errors if there are "bad" torsions that can't be fixed.

**Comment by halx** [comment]
Many thanks.

I have to explain this in more detail.  The topology file has been created for SOMD which is Julien Michel's single topology approach on top of OpenMM.  Such topologies will have bond and angle terms defined for dummy atoms to allow clean-up through minimisation after structure construction.  All other terms are zero and so of no relevance.

As far as the periodicities go, none of them are actually negative and your script confirms that as does a quick look at the DIHEDRAL_PERIODICITY section in the parmtop.  Nevertheless, OpenMM 7.7 thinks that at least some are.  I have also checked with version 7.6 which is fine with the file and we never had a problem with earlier versions.  So something seems to have changed since 7.6.

**Comment by swails** [comment]
Can you try loading the prmtop through ParmEd instead of `AmberPrmtopFile`?

**Comment by halx** [comment]
I suppose you mean passing the parmed AmberFormat object directly to Simulation.  This results in the same error as in my original message.

**Comment by swails** [comment]
Actually, the 0-periodicity torsions *also* have a force constant of 0, meaning that the value of the periodicity is meaningless.  So you can adjust the script I attached slightly as such:

```python
import parmed as pmd
import math

old_parm = pmd.amber.AmberFormat("Input.prm7")

TOL = 1e-4

for i, (per, k) in enumerate(zip(old_parm.parm_data["DIHEDRAL_PERIODICITY"], old_parm.parm_data["DIHEDRAL_FORCE_CONSTANT"])):
    if per == 0:
        assert k == 0
        old_parm.parm_data["DIHEDRAL_PERIODICITY"][i] = 1  # value doesn't matter

old_parm.write_parm("Input_fixed.prm7")
```

Then make sure you use `Input_fixed.prm7` instead of `Input.prm7` in your simulation.

**Comment by halx** [comment]
Errm, yes.  Those parameters are zero "by design" as they involve dummy atoms.  We patch them with sensible values at a later stage.

I suppose you are saying that OpenMM in the new version 7.7 would not accept the periodicity as 0 anymore.  So I guess the solution for us at the moment is to set the periodicity to something positive and keep the force constant at zero as we need it to be.  Is there any deeper reason why this check has been introduced?

**Comment by halx** [comment]
Do you have similar plans with the torsion barrier heights?  After all the effect of a zero barrier is the same but for our purpose it is crucial that we are able to set torsions to zero.

**Comment by swails** [comment]
There are more use-cases for 0-force constants than 0-periodicities (the latter imposes a constant shift in the potential while the former does not); neither affects the forces.

Taking away k=0 would make scaling a torsion to zero a lot harder (if you want to eliminate a torsion during a simulation, you can get away with simply updating the context by setting the force constant to 0 whereas deleting the torsion completely would invalidate the context altogether and incur a large performance penalty), so I strongly doubt that will ever be disallowed in the future.

**Comment by peastman** [comment]
You can even make k negative.  I don't know whether that's a particularly useful thing to do, but it doesn't prevent it.
