### ISSUE TITLE
Exporting topology after addSolvent() succeeds using PSF format, but fails with PRMTOP format.

### ISSUE THREAD

**Issue by pguillem** [openmm/openmm#3468]
I'm loading a very sanitized PDB, without solvent/hydrogens.

- I use the modeller class to addHydrogens(), addSolvent() and addExtraParticles().
- Then I createSystem(), which succeeds.

- Then I use this 2 liner to export the topology before minimizing/equilibrating/simulating:
```
structure = topsystem.load_topology( modeller.topology, system, modeller.positions)
structure.save('input1_nowat.psf', overwrite=True)
```

This code is successful.
**However, if I change the topology extension to amber prmtop, the save process fails.** 

`structure.save('input1_nowat.prmtop', overwrite=True)`

**Here is the error:**

```
Building system...
Adding Solvent...
Done..
Traceback (most recent call last):
  File "/group/bioinfp_data/run_input1.py", line 53, in <module>
    structure.save('input1_nowat.prmtop', overwrite=True)
  File "/.local/lib/python3.9/site-packages/parmed/structure.py", line 1507, in save
    s = amber.AmberParm.from_structure(self)
  File "/.local/lib/python3.9/site-packages/parmed/amber/_amberparm.py", line 349, in from_structure
    inst.remake_parm()
  File "/.local/lib/python3.9/site-packages/parmed/amber/_amberparm.py", line 676, in remake_parm
    self._xfer_bond_info()
  File "/.local/lib/python3.9/site-packages/parmed/amber/_amberparm.py", line 1580, in _xfer_bond_info
    bond.type.used = True
**AttributeError: 'NoneType' object has no attribute 'used'**

```

If I don't add the waters with modeller, the save succeeds.

**Comment by pguillem** [comment]
Thanks  @swails .
I'm creating a system without constrains.

Also, simulations run well. The system is also being created without errors.
The error only happens if I try to save the topology to a file in "prmtop" format.

**Comment by swails** [comment]
Without having the files available to reproduce the problem, it's impossible for me to help.  If you can put together a complete example that encounters this error I can investigate.

**Comment by swails** [comment]
The values of the bond force constants aren't important if you constrain the waters (which you need to do), so you can create a new one:

```python
oh_bond_type = BondType(k=100, req=..., list=parm.bond_types)
parm.bond_types.append(oh_bond_type)
for bond in parm.bonds:
    if bond.type is None and bond.atom1.element == 8 and bond.atom2.element == 1:
        bond.type = oh_bond_type
```

Something like that should work.  You'll probably also have to add the `H-H` bond.

**Comment by pguillem** [comment]
Cool. Let's give it a try.
Thank you so much.

**Comment by swails** [comment]
Yes - but fill in the req with the actual lengths

**Comment by pguillem** [comment]
@swails, worked like a charm.
Thanks.
