### ISSUE TITLE
Coupling with arbitrary external field (?)

### ISSUE THREAD

**Issue by EqualAPriori** [openmm/openmm#3472]
Hi, I was wondering what the best way would be to apply an arbitrary external potential field (say, defined on a grid) to an OpenMM simulation. I know there's the custom force object where I can write simple 1-body potentials, but my understanding is that is only for an algebraic expression. Maybe I should be doing something like implementing the potential calculation in torch and then using [openmm-torch](https://github.com/openmm/openmm-torch)?

Thanks!

**Comment by peastman** [comment]
If your potential is defined on a grid, you can represent it with a TabulatedFunction (specifically a [Continuous3DFunction](http://docs.openmm.org/latest/api-python/generated/openmm.openmm.Continuous3DFunction.html#openmm.openmm.Continuous3DFunction)).  Then use a [CustomCompoundBondForce](http://docs.openmm.org/latest/api-python/generated/openmm.openmm.CustomCompoundBondForce.html) to implement a 1-body potential depending on it.  (CustomExternalForce is more often used for 1-body potentials, but it doesn't support tabulated functions.)

**Comment by EqualAPriori** [comment]
Ah! Yes much simpler. Does the Continuous3D function use a particular form of interpolation between tabulated points? Can that be customized (or am I misunderstanding how it works).

**Comment by peastman** [comment]
It fits a natural cubic spline to the points.  The constructor has a `periodic` argument to tell it whether the function is periodic.  If the function is periodic, the first and last points along each axis need to be identical.  Here is the [C++ API documentation](http://docs.openmm.org/latest/api-c++/generated/Continuous3DFunction.html) for it, which is more complete than the Python documentation.  A lot of the details seem to have gotten lost in the automatic translation.
