### ISSUE TITLE
how to debug a Common kernel

### ISSUE THREAD

**Issue by egallicchio** [openmm/openmm#3475]
I am porting the [ATMMetaForce plugin](https://github.com/Gallicchio-Lab/openmm-atmmetaforce-plugin) to the Common platform. I think one of the kernels does not compile correctly. The OpenCL version results in an unspecified "Error compiling kernel" message and the CUDA version gives a CUDA_ERROR_INVALID_CONTEXT error at runtime.

Assuming I am on the right track regarding a kernel compilation error, what is the best way to debug a Common kernel? Can the text of the translated program be retrieved in either OpenCL or CUDA?

**Comment by peastman** [comment]
A way of debugging it is to print out the full source of the kernel.  For OpenCL, that's in `OpenCLContext::createProgram()`:

https://github.com/openmm/openmm/blob/4142e19827fd6c9c98b4369e9908c78926f59929/platforms/opencl/src/OpenCLContext.cpp#L623-L629

You can print out `src.str()` in the catch block.  For CUDA it's in `CudaContext::createModule()`, which is a little more complicated because it can compile either with nvcc or nvrtc.  But again just print out `src.str()`.

**Comment by egallicchio** [comment]
Thank you. Interestingly, I get errors when compiling the NonBonded OpenCL kernels
```
   __kernel void findBlockBounds(...
   __kernel void sortBoxData(...
   __kernel void findBlocksWithInteractions(...
```
etc. for the inner context. The compilation of the identical OpenCL code block for the main context is okay.

Similar to the CustomCVForce, the ATMMetaForce duplicates the main Systems's Forces, including the nonbonded force, into two inner systems. However, I understand that nonbonded forces are rarely used in CustomCVForce. Has CustomCVForce been tested with nonbonded forces? Could there be issues related to translating the Common's nonbonded kernels for the inner contexts?

**Comment by peastman** [comment]
I don't know of any reason it wouldn't work.  The build log doesn't give any details about what the error is?

**Comment by egallicchio** [comment]
The build log appears to be empty ...

```
Traceback (most recent call last):
  File "abfe.py", line 114, in <module>
    state = simulation.context.getState(getEnergy = True, groups = {1,3})
  File "/home/emilio/Dropbox/devel/docker/openmm_latest/lib/python3.7/site-packages/openmm/openmm.py", line 3197, in getState
    state = _openmm.Context_getState(self, types, enforcePeriodicBox, groups_mask)
openmm.OpenMMException: Error compiling kernel: 

```
I'll keep investigating ... one clue is that the compilation error does not occur if the nonbonded Force is not added to the inner  system.

**Comment by peastman** [comment]
Can you create a minimal test case that doesn't use the plugin, just NonbondedForce?  That would tell us whether the problem is in the plugin code.

**Comment by egallicchio** [comment]
I intend to prepare a test case with customCVForce with a CV based on NonbondedForce. If it passes, it will probably give us a guide on where to go next.  Unless customCVForce + NonbondedForce combination is already included in the automated tests?

**Comment by peastman** [comment]
TestCustomCVForce.h doesn't include any tests with a NonbondedForce.  It does have one with a CustomNonbondedForce.  It doesn't use a cutoff, though, which is where those kernels would get used.  But I just tried modifying it to use a cutoff, and there were no errors.

**Comment by egallicchio** [comment]
Thank you for checking. It must be some kind of misbehavior of the plugin then ...

**Comment by peastman** [comment]
Maybe?  Let's debug it and then we'll know.  I would start from your failing test case and keep simplifying it until you find the minimum case needed to reproduce the problem.

**Comment by egallicchio** [comment]
Well, I had to trim it all the way to two particles, but in the end, I found the unmentionable silly typo in the Common kernel code. The Common implementation of the ATMMetaForce plugin seems to work fine. Thank you and sorry for the trouble.

**Comment by peastman** [comment]
Yay!  I once spent an entire week tracking down a bug that turned out to be caused by a single 0 that should have been a 1.
