### ISSUE TITLE
ZeroDivisionError after fixing particle positions with zero mass

### ISSUE THREAD

**Issue by bbye98** [openmm/openmm#3478]
Hello!

I am currently trying to simulate a coarse-grained system of charged Lennard-Jones particles constrained between two fixed HCP lattice walls. To maintain the positions of the wall particles, I set their masses to 0. However, I am getting `ZeroDivisonError: 0.0 cannot be raised to a negative power`, likely due to the zero mass.

I first set up the system:

    system = openmm.System()
    system.setDefaultPeriodicBoxVectors(
        unit.Quantity((L_X, 0 * unit.angstrom, 0 * unit.angstrom)),
        unit.Quantity((0 * unit.angstrom, L_Y, 0 * unit.angstrom)),
        unit.Quantity((0 * unit.angstrom, 0 * unit.angstrom, L_Z))
    )

Then, I define my pair potentials:

    coul = openmm.NonbondedForce()
    coul.setCutoffDistance(CUTOFF)
    coul.setEwaldErrorTolerance(1e-5)
    coul.setNonbondedMethod(openmm.NonbondedForce.PME)

    wca = openmm.CustomNonbondedForce(
        'step(2^(1/6) * sig - r) * (4 * eps * ((sig / r)^12 - (sig / r)^6) + eps);'
        f'eps = sqrt(epsilon1 * epsilon2);'
        f'sig = (sigma1 + sigma2) / 2;'
    )
    wca.addPerParticleParameter('epsilon')
    wca.addPerParticleParameter('sigma')
    wca.setCutoffDistance(CUTOFF)
    wca.setNonbondedMethod(openmm.CustomNonbondedForce.CutoffPeriodic)

For debugging purposes, I have only added the wall particles. The charged Lennard-Jones system works as intended, but I start having issues after adding the walls:

    for i in range(2 * N_WALL):
        system.addParticle(0 * unit.amu)
        coul.addParticle(0, 0, 0)
        wca.addParticle((100 * EPSILON, SIGMA))

I then added exclusions/exceptions so that the wall particles do not interact with themselves:

    for i in range(2 * N_WALL):
        for j in range(i + 1, 2 * N_WALL):
            wca.addExclusion(i, j)
            coul.addException(i, j, 0, 0, 0)

    system.addForce(coul)
    system.addForce(wca)

Finally, I set up the topology/chains, define the wall particle positions (which I calculated previously) and then initialize the simulation context:

    topology = app.Topology()
    ELEMENT_WALL = app.Element.getBySymbol('C')
    CHAIN_WALL = topology.addChain()
    for i in range(2 * N_WALL):
        residue = topology.addResidue('C', CHAIN_WALL)
        topology.addAtom('Wall', ELEMENT_WALL, residue)
    integrator = openmm.LangevinIntegrator(T, 1 / unit.picosecond, 1 * unit.femtosecond)
    simulation = app.Simulation(topology, system, integrator, plat, prop)
    simulation.context.setPositions(POS_WALL)
    simulation.minimizeEnergy()
    simulation.reporters.append(openmm.app.PDBReporter('dilute.pdb', TS_EVERY))
    simulation.reporters.append(
        openmm.app.StateDataReporter(
            sys.stdout, reportInterval=TS_EVERY, step=True, temperature=True,
            potentialEnergy=True, kineticEnergy=True, totalEnergy=True,
            remainingTime=True, speed=True, totalSteps=TS_TOTAL
        )
    )
    simulation.step(TS_TOTAL)

The `.pdb` output for the initial state looks correct, with the wall particles forming HCP lattices. However, once the NVT simulation starts, I get the `ZeroDivisionError`. Is there another method of preventing particles from moving during a NVT simulation? I originally got the idea of zeroing particle mass from [here](https://github.com/ParmEd/ParmEd/wiki/OpenMM-Tricks-and-Recipes).

Thank you!

**Comment by peastman** [comment]
Can you post the full stack trace for the exception?  ZeroDivisionError is a Python error.  It's coming from somewhere in the Python code, not the lower level simulation code.

**Comment by bbye98** [comment]
@peastman Thanks for your quick response, as always!

I add a logging function to see where the error happens (the first few lines). Here is the full stack trace:

    Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
    13:43:00  OpenMM 7.7 is using platform CUDA on host blob.
    13:43:00  Defining system parameters...
    13:43:00  Setting up initial state and force field...
    13:43:01  Adding particles to simulation system...
    13:43:01  Setting up NVT simulation...
    13:43:03  Starting NVT simulation...
    #"Step","Potential Energy (kJ/mole)","Kinetic Energy (kJ/mole)","Total Energy (kJ/mole)","Temperature (K)","Speed (ns/day)","Time Remaining"
    Traceback (most recent call last):
      File "/home/bye/testing/dilute_cgil.py", line 155, in <module>
          simulation.step(TS_TOTAL)
      File "/home/bye/miniconda3/lib/python3.9/site-packages/openmm/app/simulation.py", line 141, in step
          self._simulate(endStep=self.currentStep+steps)
      File "/home/bye/miniconda3/lib/python3.9/site-packages/openmm/app/simulation.py", line 241, in _simulate
          self._generate_reports(wrapped, True)
      File "/home/bye/miniconda3/lib/python3.9/site-packages/openmm/app/simulation.py", line 263, in _generate_reports
          reporter.report(self, state)
      File "/home/bye/miniconda3/lib/python3.9/site-packages/openmm/app/statedatareporter.py", line 209, in report
          values = self._constructReportValues(simulation, state)
      File "/home/bye/miniconda3/lib/python3.9/site-packages/openmm/app/statedatareporter.py", line 251, in _constructReportValues
          values.append((2*state.getKineticEnergy()/(self._dof*unit.MOLAR_GAS_CONSTANT_R)).value_in_unit(unit.kelvin))
      File "/home/bye/miniconda3/lib/python3.9/site-packages/openmm/unit/quantity.py", line 408, in __truediv__
          return (self/other._value) / other.unit
      File "/home/bye/miniconda3/lib/python3.9/site-packages/openmm/unit/quantity.py", line 411, in __truediv__
          return self * pow(other, -1.0)
    ZeroDivisionError: 0.0 cannot be raised to a negative power

**Comment by peastman** [comment]
> specifically the fact that I am asking it to report the kinetic energy (but the particles have no mass and are not...moving).

Computing kinetic energy isn't a problem (it's zero), but you also asked for temperature, which is proportional to kinetic energy per degree of freedom.  Your system has 0 degrees of freedom, thus the division by zero.

[The FAQ](https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#nan) has advice on debugging problems with NaNs.  In your case, you may just need to run a local energy minimization before starting the simulation.

**Comment by bbye98** [comment]
@peastman Once again, thank you. After some debugging, I ironed out all the issues and the simulation now proceeds as expected.
