### ISSUE TITLE
How to describe rotation around axis with virtual site?

### ISSUE THREAD

**Issue by aizvorski** [openmm/openmm#3479]
I'd like to use two particles to define an axis of rotation, and then create a virtual site based on rotating the location of a third particle around that axis by a fixed angle.  It seems like either OutOfPlaneSite or LocalCoordinatesSite may be able to do this, but I can't quite figure out how.

For example, supposing I wanted a virtual site produced by rotating a particle at coordinates r1 by 60 degrees around the axis given by particles at r2 and r3, how would I do that?

**Comment by peastman** [comment]
I don't think any of the virtual site types can do exactly that.  With LocalCoordinatesSite you can find the plane generated by rotating the r1-r2-r3 plane by 60 degrees around the r2-r3 axis.  But then you would have to place the virtual site at a fixed position within that plane.  It couldn't depend on the offset between r1 and r2.

**Comment by peastman** [comment]
Closing this since the question has been answered.
