### ISSUE TITLE
namespaces in custom forces and LJ when setIncludeDirectSpace(false)

### ISSUE THREAD

**Issue by halx** [openmm/openmm#3484]
Hi again,

When I use the same global parameter, and I guess the clue is in the "global", in _different_ custom forces does this mean that there is only this one parameter i.e. there is a single namespace for all custom forces?

When I use PME as NonbondedForce method and then call setIncludeDirectSpace(false) on that force does this also switch off the LJ potential i.e. do I have to make sure myself in a custom force to implement it accordingly?

Many thanks.

**Comment by Lnaden** [comment]
>  in different custom forces does this mean that there is only this one parameter

Any global parameter added through the `addGlobalParameter` method shares a namespace with any other force which also adds this same parameter name. Each force you want to use it in must still declare the parameter through the `addGlobalParameter` method though. The namespace is even shared up to any `CustomIntegrator` classes (if I remember correctly), so they can be used there as well.

> does this also switch off the LJ potential

Depends. 
If you are using only electrostatics in the PME calculation, then the direct and reciprocal spaces are for the electrostatic component only, leaving the Lennard-Jones terms to be controlled by the cutoff, switching method, and whether or not long range dispersion correction is being treated.
If you are using LJPME and Electrostatics: yes.

I haven't worked with the LJPME calculations myself, so someone who has can correct me if i'm wrong.

**Comment by peastman** [comment]
Or to state that more directly:

- If you are using LJPME, then LJ is split between direct space and reciprocal space.  `setIncludeDirectSpace(false)` turns off the direct space part but not the reciprocal space part.
- For any other method, LJ is contained entirely in the direct space calculation.  `setIncludeDirectSpace(false)` turns it off.
