### ISSUE TITLE
Possible issue in `AmberPrmTopFile.createSystem` logic

### ISSUE THREAD

**Issue by mattwthompson** [openmm/openmm#3488]
I'm on the trail of a case in which `GBSAOBCForce.setUseSwitchingDistance()` is called inside of `AmberPrmTopFile.createSystem`, which causes a crash because that force does not have that attribute. I could be totally wrong here, but by my eye the [indentation here](https://github.com/openmm/openmm/blob/7.7.0/wrappers/python/openmm/app/amberprmtopfile.py#L294-L310) doesn't match what I'd expect. The `if switchingDistance ...` logic on L300 seems like it should be inside of the `if isinstance(force, mm.NonbondedForce):` check on L295 so that it's only called when `force` is an object that  supports a switching distance. Otherwise, that block seems to be called on whatever is the last force in `sys.getForces()`, which may typically be a non-bonded force but as far as I'm aware that's not guaranteed. These lines haven't been modified since they were added (https://github.com/openmm/openmm/pull/1272) and I don't see other issues on the tracker, so I guess it normally works.

The most minimal reproduction I can come up with is something like this:

```
In [1]: from openmm import app, unit

In [2]: sys = app.AmberPrmtopFile("gbsa.tmp.prmtop").createSystem(
   ...:     nonbondedMethod=app.CutoffNonPeriodic,
   ...:     implicitSolvent=app.OBC2,
   ...:     switchDistance=0.7 * unit.nanometer,
   ...: )
/Users/mwt/miniconda3/envs/openff-interchange-env/lib/python3.8/site-packages/openmm/app/internal/amber_file_parser.py:1102: UserWarning: Non-optimal GB parameters detected for GB model OBC2
  warnings.warn(
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [2], in <module>
----> 1 sys = app.AmberPrmtopFile("gbsa.tmp.prmtop").createSystem(
      2     nonbondedMethod=app.CutoffNonPeriodic,
      3     implicitSolvent=app.OBC2,
      4     switchDistance=0.7 * unit.nanometer,
      5 )

File ~/miniconda3/envs/openff-interchange-env/lib/python3.8/site-packages/openmm/app/amberprmtopfile.py:310, in AmberPrmtopFile.createSystem(self, nonbondedMethod, nonbondedCutoff, constraints, rigidWater, implicitSolvent, implicitSolventSaltConc, implicitSolventKappa, temperature, soluteDielectric, solventDielectric, removeCMMotion, hydrogenMass, ewaldErrorTolerance, switchDistance, gbsaModel)
    307     if _strip_optunit(switchDistance, u.nanometer) < 0:
    308         # Detects negatives for both Quantity and float
    309         raise ValueError('switchDistance must be non-negative!')
--> 310     force.setUseSwitchingFunction(True)
    311     force.setSwitchingDistance(switchDistance)
    313 return sys

AttributeError: 'GBSAOBCForce' object has no attribute 'setUseSwitchingFunction'
```

Does this seem sensible?

I opened a PR that fixes this for my local configuration: #3499

This can probably be reproduced with some vanilla files but this is the one I used: [gbsa.tmp.prmtop.txt](https://github.com/openmm/openmm/files/8157442/gbsa.tmp.prmtop.txt)

**Comment by swails** [comment]
Does ParmEd have this same problem?

**Comment by mattwthompson** [comment]
I'm not so familiar with that portion of ParmEd API but I think this behavior is correct:


```python3
In [1]: from openmm import app, unit

In [2]: import parmed as pmd
Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.

In [3]: struct = pmd.load_file('gbsa.tmp.prmtop')

In [4]: sys = struct.createSystem(
   ...:     implicitSolvent=app.OBC2,
   ...:     nonbondedMethod=app.CutoffNonPeriodic,
   ...:     switchDistance=0.7 * unit.nanometer,
   ...: )

In [5]: sys.getForces()
Out[5]:
[<openmm.openmm.HarmonicBondForce; proxy of <Swig Object of type 'OpenMM::HarmonicBondForce *' at 0x7fa64b40a570> >,
 <openmm.openmm.HarmonicAngleForce; proxy of <Swig Object of type 'OpenMM::HarmonicAngleForce *' at 0x7fa64b3e7d80> >,
 <openmm.openmm.PeriodicTorsionForce; proxy of <Swig Object of type 'OpenMM::PeriodicTorsionForce *' at 0x7fa64a63e450> >,
 <openmm.openmm.NonbondedForce; proxy of <Swig Object of type 'OpenMM::NonbondedForce *' at 0x7fa64a63e4e0> >,
 <openmm.openmm.CustomGBForce; proxy of <Swig Object of type 'OpenMM::CustomGBForce *' at 0x7fa64a63e600> >,
 <openmm.openmm.CMMotionRemover; proxy of <Swig Object of type 'OpenMM::CMMotionRemover *' at 0x7fa64bbfa630> >]

In [6]: sys.getForces()[3].getSwitchingDistance()
Out[6]: Quantity(value=0.7, unit=nanometer)
```

I see similar-looking code [here](https://github.com/ParmEd/ParmEd/blob/cd763f2e83c98ba9e51676f6dbebf0eebfd5157e/parmed/structure.py#L2653-L2658), but it's in a function that appears to be scoped to only that one force, so the assumption is fine.
