### ISSUE TITLE
What distribution of random numbers does IntegrationUtilities::prepareRandomNumbers provide?

### ISSUE THREAD

**Issue by Dann239** [openmm/openmm#3498]
I have a question about `IntegrationUtilities::prepareRandomNumbers`. What distribution does it generate? I tried looking for it in the documentation and in previous issues, but i couldn't find anything. I also couldn't deduce it from the code. At first i though it generated uniformly distributed values in `[-1,1]` but putting
```cpp
printf("%f %f %f %f\n", value.x, value.y, value.z, value.w);
```
in the kernel produces values as high as `3.184038`.

Thanks in advance

**Comment by peastman** [comment]
They're Gaussian distributed.  Here is the code to generate them.  It uses a KISS generator to produce uniformly distributed values, then applies Box-Muller to transform them into normally distributed ones.

https://github.com/openmm/openmm/blob/7432ad8c1cf075be2de164aaec7aca0d630fed94/platforms/common/src/kernels/integrationUtilities.cc#L4-L69.

**Comment by Dann239** [comment]
thanks!
and what are the parameters of this distribution?

**Comment by Dann239** [comment]
a quick google search gave me the result: it's a standard distribution

thanks for pointing me in the right direction!
