### ISSUE TITLE
TIP4P waters not compatible with AllBonds?

### ISSUE THREAD

**Issue by lvotapka** [openmm/openmm#3499]
Hi All,

I'm attempting to run a system with TIP4Pew waters using the "AllBond" constraint option, but I get the following error:
```
openmm.OpenMMException: A constraint cannot involve a massless particle
```
I'm assuming this is because of the virtual site on the water molecules.

Here is the script I'm using:
```
import simtk.openmm.app as app
import simtk.openmm as mm
import simtk.unit as unit
from sys import stdout

import numpy as np

prmtop = app.AmberPrmtopFile('tryp_ben.prmtop')
inpcrd = app.AmberInpcrdFile('tryp_ben.inpcrd')
system = prmtop.createSystem(nonbondedMethod=app.PME, nonbondedCutoff=1*unit.nanometer,
        constraints=app.AllBonds)

num_steps = 10000
time_step = 0.002

input_file = "tryp_ben_new.pdb"

mypdb = app.PDBFile(input_file)

integrator = mm.LangevinIntegrator(298.15*unit.kelvin, 1/unit.picosecond, time_step*unit.picoseconds)
platform = mm.Platform.getPlatformByName('CUDA')
properties = {'CudaDeviceIndex': '0', 'CudaPrecision': 'mixed'}
simulation = app.Simulation(prmtop.topology, system, integrator, platform, properties)
simulation.context.setPositions(mypdb.positions)
simulation.context.setPeriodicBoxVectors(*inpcrd.boxVectors)
simulation.minimizeEnergy()
simulation.context.setVelocitiesToTemperature(298.15 * unit.kelvin)
```

I've attached the files one can use to recreate this error.
[tryp_ben.prmtop.zip](https://github.com/openmm/openmm/files/8181237/tryp_ben.prmtop.zip)
[tryp_ben.inpcrd.zip](https://github.com/openmm/openmm/files/8181238/tryp_ben.inpcrd.zip)

**Comment by peastman** [comment]
This is happening because in the `BONDS_WITHOUT_HYDROGEN` section, the prmtop file lists a bond between the O and the extra particle in each water molecule.  Is that normal for a prmtop file with TIP4P?  I've never seen that before.

If so, what is the correct way to identify the extra bond that should be removed?  Should we assume that any bond involving an extra particle should always be removed?

**Comment by lvotapka** [comment]
Thanks for taking a look at this, @peastman. 

I generated that .prmtop file using tleap in Ambertools18 (fairly recent version). Here's the LEAP script that I used to generate the files:

```
source leaprc.protein.ff14SB
source leaprc.gaff
source leaprc.water.tip4pew
set default PBRadii mbondi2
loadoff benz.lib
loadamberparams benz.frcmod
WAT = T4E
HOH = T4E
loadAmberParams frcmod.ionsjc_tip4pew
loadAmberParams frcmod.tip4pew
mol = loadpdb 3ptb_processed.pdb
solvateoct mol TIP4PEWBOX 8
addIons2 mol Cl- 0
saveamberparm mol tryp_ben.prmtop tryp_ben.inpcrd
savepdb mol tryp_ben.pdb
check mol
charge mol
quit
```

Notice that I'm using the "solvateoct" command to make a TIP4Pew truncated octahedron waterbox.

As for what to do about the extra bond - I imagine that you would know better than me what to do about it. I think that every simulation engine treats the extra particle in TIP4P as a virtual site. Would it make sense to remove that bond only if the rigidWater setting is set to True? I'm also not too familiar with how OpenMM handles TIP4P, though I assume that it treats that extra particle as a virtual site (and not like a true zero mass particle, because then they would never move).

**Comment by peastman** [comment]
In this case, removing the bond is clearly the right thing to do.  But I don't want to break some other case while fixing this one.  That's why I'm wondering about how to handle this in general.  Is it correct to say that any bond involving an extra particle should always be removed?

Any insight from someone with more knowledge of prmtop files would be welcome!

**Comment by lvotapka** [comment]
My experience isn't vast, but I cannot think of any other situation, aside from TIP4P and TIP5P, where extra particles would be included in a prmtop file. I've personally never encountered extra particles in protein, nucleic acid, glycan, lipid, or small molecules in the AMBER FF that have these extra, massless particles.

**Comment by peastman** [comment]
Another case is the CHARMM polarizable force field.  It uses extra particles both for Drude particles and for lone pairs.

**Comment by lvotapka** [comment]
Yes, that is true. Do the CHARMM input files draw bonds between those particles and real atoms?
