### ISSUE TITLE
How to extract metadynamics biases as a fixed force?

### ISSUE THREAD

**Issue by KirillShmilovich** [openmm/openmm#3503]
After having completed a metadynamcis simulation(s), how could one collect all deposited biases from the `bias_*_*.npy` file(s) to create a Force object that one could use to run a separate simulation with a **fixed** potential extracted from the metadynamics simulation(s)?

**Comment by peastman** [comment]
Once you're done running the metadynamics, you can just take the System and create a new simulation for it.  The biases are applied by the CustomCVForce inside the System.  If you want to save it to disk, you can [serialize it as XML](https://openmm.github.io/openmm-cookbook/dev/notebooks/cookbook/Saving%20Systems%20to%20XML%20Files.html).  You also could serialize just the CustomCVForce to reload later and add to a different System.

**Comment by KirillShmilovich** [comment]
Perfect, thank you!! Would it also be possible to recreate the metadynamics object with the specified directory where the biases live e.g.:

`meta = Metadynamics(system, [cv], 300.0, biasFactor=5.0, height=1.0, frequency=500, saveFrequency=500, biasDir='biases_dir/')`

and then simply extract the CusomCVForce from the `meta._force` attribute and then apply to another system (e.g. in the case where there are many `bias_*_*.npy` accumulated)? Or, in the case of running just a single metadynamics simulation, is it preferable to instead serialize the `meta._force` object and then reload separately when needed?

**Comment by peastman** [comment]
A Force can't belong to multiple Systems, but if you make a copy of it with `copy(meta._force)`, that should work.

**Comment by KirillShmilovich** [comment]
Great, thank you!

**Comment by KirillShmilovich** [comment]
Quick question again regarding this:

Given we've extracted the fixed meta dynamics force, either within the deserialized system or from `meta._force` object, is it possible to then modify the force object to decrease the magnitude of the force when applied to a new simulation/system? e.g. applying a prefactor of 0.1 to the force such that the strength of the fixed force is only 10% of the original metadynamics force?

**Comment by peastman** [comment]
Sure, you can call `setEnergyFunction()` on it.  Something like this:

```python
force.setEnergyFunction(f'0.1*{force.getEnergyFunction()}')
```

Or if you want to be able to change the scale factor at any time, you could add a global parameter and multiply by it.

**Comment by KirillShmilovich** [comment]
Amazing! Thanks!
