### ISSUE TITLE
BondCutoff issue in CustomHBondForce with OpenCL

### ISSUE THREAD

**Issue by jacopomoi** [openmm/openmm#3509]
I set a CustomHBondForce in amber99sbildn.xml
```
<CustomHbondForce particlesPerDonor="3" particlesPerAcceptor="2" bondCutoff="4" energy="step(0.3-distance(a1,d1))*(836*(distance(a1,d1)-0.195)^2)">

    <Donor class1="H" class2="N" class3="C" />
    <Acceptor class1="O" class2="C"/>
```

I run the simulation with OpenCL on a AMD radeon 550x, i think the device type is not important because i get the same error also on a cluster with more advanced GPU.
```
openmm.OpenMMException: CustomHbondForce: this platform does not support more than four exclusions per acceptor
```
The problem disappear when <BondCutoff =2>
Is this related to the GPU or to the OpenCL platform? Or am i missing some parameters during the initialization?
Thanks.

Anyway OpenMM is the best engine i've ever used.

**Comment by jacopomoi** [comment]
Thank you for the answer. I packed everything inside the .zip file. Inside there is the .PDB, the modified forcefield and the code. 
[issue.zip](https://github.com/openmm/openmm/files/8226118/issue.zip)

In reality my issues was an attempt to understand why the harmonic angle force tend to explode the simulation, so i thought that the CustomHBondForce was also including some groups too much closed in the backbone and probably increasing the BondCutoff it would fix this aspect. Also i noticed that the angles respect the main-chain hbond in this force are not respected at the final stage of the annealing with BondCutoff=2, i don't know if i made a mistake. I was also wondering if there is a way to serialize only the angle() from a force.

If you want i can provide the final structure in a while.
```
<CustomHbondForce particlesPerDonor="3" particlesPerAcceptor="2" bondCutoff="2" energy="step(0.3-distance(a1,d1))*(836*(distance(a1,d1)-0.195)^2)" >
<Donor class1="H" class2="N" class3="C"/>
<Acceptor class1="O" class2="C"/>
...
</CustomHbondForce>
<CustomHbondForce particlesPerDonor="3" particlesPerAcceptor="2" bondCutoff="2" energy="step(0.3-distance(a1,d1))*418*((angle(a1,d1,d2)-2.792)^2)" >
<Donor class1="H" class2="N" class3="C"/>
<Acceptor class1="O" class2="C"/>
...
</CustomHbondForce>
<CustomHbondForce particlesPerDonor="3" particlesPerAcceptor="2" bondCutoff="2" energy="step(0.3-distance(a1,d1))*418*((angle(d1,a1,a2)-2.618)^2)" >
<Donor class1="H" class2="N" class3="C"/>
<Acceptor class1="O" class2="C"/>
...
</CustomHbondForce>
```
Thank you very much for your time!

**Comment by peastman** [comment]
The zip file is missing some of the things needed to run the script and reproduce the problem.  It looks like there's also supposed to be subdirectories called `model` and `forcefield`?

What happens if you omit the hbond force?  It looks like you tried out various force fields, include CHARMM, Amber, and AMOEBA ones.  All of those are designed to correctly reproduce energies without a specific hbond force.

> I was also wondering if there is a way to serialize only the angle() from a force.

You can serialize just one force.  Is that what you mean?  For example,

```python
for force in system.getForces():
  if isinstance(force, HarmonicAngleForce):
    print(XmlSerializer.serialize(force))
```

**Comment by jacopomoi** [comment]
Whops, sorry. I'll fix that. I was wondering if there is a way to get the values of the angle() function, the one on the forcefield. Yes i know that the other forcefields have a correct description but this potential is described in a paper ( FGMD Fragment Guided Molecular Dynamics ) from Zhang. Anyway i'm from the beginning a bit suspicious about this kind of hbond statistical potential. Thank you in any case, now i know that GPU and opencl works fine!
