### ISSUE TITLE
Update User Guide build docs (and provide conda-forge development environment?) for OpenMM 8

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#3514]
We likely need to update the build docs in the User Guide for OpenMM 8 (cc: https://github.com/openmm/openmm/issues/3378#issuecomment-1066306673).

We could give people a choice of full build environments (minimal for OpenMM, OpenMM + plugins, etc).

**Comment by peastman** [comment]
Closing this since the existing documentation is correct.  The problems only occur when using conda-forge compilers, which is strongly disrecommended.
