### ISSUE TITLE
Implementing Yeh–Berkowitz correction for slab geometry with periodic boundary conditions

### ISSUE THREAD

**Issue by bbye98** [openmm/openmm#3516]
Hello!

I am planning on simulating charge-neutral electrolyte systems with slab geometries (fully periodic in x- and y-directions, but constrained by two walls in the z-direction), with and without electric fields and image charges. In LAMMPS and GROMACS, this type of simulation can still be carried out with fully periodic Ewald summation by expanding the z-size to be three times the simulation box length and then subtracting a slab correction term (Yeh & Berkowitz, DOI: 10.1063/1.479595) that accounts for any dipole moments in the system. The respective commands are [`kspace_modify slab 3.0`](https://docs.lammps.org/kspace_modify.html#description) and [`ewald_geometry = 3dc`](https://manual.gromacs.org/documentation/2018/user-guide/mdp-options.html#ewald), but there doesn't seem to be an equivalent in OpenMM.

The correction term is subtracted from the force and is given by `-4*pi*q_i*M_z/V`, where `q_i` is the charge of particle `i`, `M_z` is the instantaneous system dipole, and `V` is the system volume. I was thinking of using a `CustomExternalForce` to add this correction term, with `q_i` as a per-particle parameter and `M_z` as a global parameter. However, I am unsure how to tell OpenMM to sum all of the products of the particle positions and charges (`M_z = sum(q_i*z_i)` from `i = 1` to `i = N`, where `N` is the number of ions) in the `CustomExternalForce.addGlobalParameter()` function. Is this possible?

Thanks in advance for any hints or insights!

**Comment by peastman** [comment]
Interesting question.  There's no way to get CustomExternalForce to perform the sum.  But if you use a CustomIntegrator, you can make it compute it.  The [API docs](http://docs.openmm.org/latest/api-c++/generated/CustomIntegrator.html) include sample code for a CustomIntegrator that implements exactly the same algorithm as LangevinMiddleIntegrator.  You can start from that.  Then do the following.

1. Have the CustomExternalForce define a global parameter called `M_z`.
2. Have the CustomIntegrator define a per-DOF variable called `q`.  For each particle, set it to (0, 0, charge).
3. Add this line at the end of the integator:

```python
integrator.addComputeSum("M_z", "q*x")
```

Since the x and y components of `q` are 0, the sum only includes z components.

**Comment by bbye98** [comment]
@peastman Thanks so much--your solution makes perfect sense. Essentially, I am building a `CustomIntegrator` that uses the same algorithm as the `LangevinMiddleIntegrator` but with an additional computation, the summation of `q_i*z_i` to give me `M_z` for use in a `CustomExternalForce`.

However, how does one access the particle charges and set it to be the second column of the per-DOF variable `q`? Looking through the `CustomIntegrator` man page, it looks like `CustomIntegrator.addPerDofVariable()` only takes a variable name (`str`) and an expression (`str`) (not sure how to define a "matrix" using an expression), and the particle charges are not one of the "predefined variables". Any suggestions?

**Comment by peastman** [comment]
Once you set a variable, its value remains fixed until something changes it.  That could be you calling `setPerDofVariable()`, or it could be the integrator itself executing a step you added with `addComputePerDof()`.  If neither of those happens, it won't change.

**Comment by bbye98** [comment]
@peastman Hi, I apologize in advance for the following question, but I am still really confused about accessing/setting the particle charges, namely "step 2" in your original response.

For example, say I have 500 anions, 500 cations, and then 500 wall particles added in that order. I need to set the charges for the 1,500 particles so that `M_z = sum(q_i*z_i)` can be computed by the `CustomIntegrator`. Naturally, this means that there are 500 `-1`s, 500 `1`s, and 500 `0`s in that order if we were expressing the charges in terms of elementary charge units. To have the `M_z` sum only over `z`, this would mean that each ion has `q = (0, 0, +-1)` and each wall particle has `q = (0, 0, 0)`.

However, how do I implement this? `CustomIntegrator.addPerDofVariable("q", initialValue)` forces the `initialValue` to be a `double`/`float`, and `CustomIntegrator.setPerDofVariableByName("q", value)` requires `q` to have been initialized first and `value` to be an `Vec3` object. Is the correct approach something like the following, where the per-DOF variable `q` is first initialized with a dummy value like `0` and then set with `CustomIntegrator.setPerDofVariableByName()`, where `value` is a `list` of `Vec3` objects?


    # LanveginMiddleIntegrator
    integrator = openmm.CustomIntegrator(TS)
    integrator.addGlobalVariable("a", np.exp(-FRIC*TS))
    integrator.addGlobalVariable("b", np.sqrt(1 - np.exp(-2*FRIC*TS)))
    integrator.addGlobalVariable("kT", unit.BOLTZMANN_CONSTANT_kB*TEMP)
    integrator.addPerDofVariable("x1", 0)
    integrator.addUpdateContextState()
    integrator.addComputePerDof("v", "v + dt*f/m")
    integrator.addConstrainVelocities()
    integrator.addComputePerDof("x", "x + 0.5*dt*v")
    integrator.addComputePerDof("v", "a*v + b*sqrt(kT/m)*gaussian")
    integrator.addComputePerDof("x", "x + 0.5*dt*v")
    integrator.addComputePerDof("x1", "x")
    integrator.addConstrainPositions()
    integrator.addComputePerDof("v", "v + (x-x1)/dt")

    # initialize per-DOF variable q for charge
    integrator.addPerDofVariable("q", 0)

    # set charge for each particle
    integrator.setPerDofVariableByName("q", \
        [openmm.Vec3(0*unit.elementary_charge, 0*unit.elementary_charge, -1*unit.elementary_charge),
        openmm.Vec3(0*unit.elementary_charge, 0*unit.elementary_charge, -1*unit.elementary_charge)
        ...,
        openmm.Vec3(0*unit.elementary_charge, 0*unit.elementary_charge, 0*unit.elementary_charge)])

    # compute dipole moment
    integrator.addComputeSum("M_z", "q*x")

**Comment by peastman** [comment]
> set with CustomIntegrator.setPerDofVariableByName("q", value), where value is a list of Vec3 objects?

Exactly.

> how do I access the value of M_z?

A CustomIntegrator can change the value of a global parameter defined by a Force.  Just add a step to the integrator:

```python
integrator.addComputeSum("M_z", "q*x")
```

The next time the force is evaluated, it will see the new value of the parameter.

**Comment by bbye98** [comment]
Hi Peter, if I'm understanding your second part correctly, this means that I should add a global parameter `M_z` to my `CustomExternalForce` and just give it some dummy value like `0`. If I have added the compute sum to my `CustomIntegrator`, the next time the integrator takes a step, the value of global parameter `M_z` will be updated in my `CustomExternalForce`? If so, OpenMM is an amazingly designed piece of software.

**Comment by peastman** [comment]
> the next time the integrator takes a step, the value of global parameter M_z will be updated in my CustomExternalForce?

Exactly.

> If so, OpenMM is an amazingly designed piece of software.

Thank you!
