### ISSUE TITLE
openMM ValueError: No template found for residue

### ISSUE THREAD

**Issue by ixy90** [openmm/openmm#3519]
Hello everybody. I am new to openMM, so I am trying to run the most basic example script for the TLR8 receptor (5WYZ from pdb). unfortunately, it gives me the 

ValueError: No template found for residue 69 (VAL).  The set of atoms is similar to NVAL, but it is missing 1 hydrogen atoms.

I tried to preprocess it with PDB fixer - error still the same.
I tried to run entirely with OpenMM Setup - there are some issues with the code, but the downloaded preprocessed file gives the same error.
I tried the modeller.addhydrogens method - the function itself gives the same error.
Also I found a thread here, where the guys try to fix something similar by correcting the file by hand, but they have small molecules and I don't think thats an option for a large peptide like mine.

I am very thankful for any input!

**Comment by peastman** [comment]
Have you read the [FAQ entry](https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template) on this?  It explains the common causes of this error.

If that doesn't resolve it, can you provide all the files needed to reproduce the problem?  Include your script, input files, etc.

From the error message, it sounds like your file may have the neutral form of the terminal residue, but you're using an Amber force field that only supports the charged form.

**Comment by ixy90** [comment]
> 
Thank you for your answer!!

yes, from the FAQ entry I got the OpenMM setup idea... 

My receptor I downloaded as a pdb file from: 
https://www.rcsb.org/structure/5WYZ

And the code is the "first example" from http://docs.openmm.org/latest/userguide/application/02_running_sims.html

It goes like this:

from openmm.app import *
from openmm import *
from openmm.unit import *
from sys import stdout

pdb = PDBFile('input.pdb')
forcefield = ForceField('amber14-all.xml', 'amber14/tip3pfb.xml')
system = forcefield.createSystem(pdb.topology, nonbondedMethod=PME,
        nonbondedCutoff=1*nanometer, constraints=HBonds)
integrator = LangevinMiddleIntegrator(300*kelvin, 1/picosecond, 0.004*picoseconds)
simulation = Simulation(pdb.topology, system, integrator)
simulation.context.setPositions(pdb.positions)
simulation.minimizeEnergy()
simulation.reporters.append(PDBReporter('output.pdb', 1000))
simulation.reporters.append(StateDataReporter(stdout, 1000, step=True,
        potentialEnergy=True, temperature=True))
simulation.step(10000)

**Comment by peastman** [comment]
You didn't post your input.pdb file, so I can only guess at what the problems are in it.  Here are a couple of possibilities that come to mind.

I downloaded 5WYZ from the PDB, and I see it includes some nonstandard molecules (MAN, BMA, NAG, 7VF).  Amber force fields only contain parameters for standard molecules.  If those aren't essential for your simulation, you can remove them by selecting the option in PDBFixer to "delete heterogens except water".  If those molecules are essential for your simulation, you'll need to parametrize them.  See http://docs.openmm.org/latest/userguide/application/02_running_sims.html#small-molecule-parameters.

Another possible problem is the size of the system.  There are over 26,000 atoms just in the protein.  If you build a water box, it will probably end up with more than 100,000 atoms, which is the limit to what the PDB format allows.  There are hacks for storing more atoms than that in a PDB file, but they often lead to problems.  Instead, tell PDBFixer to save the model in PDBx/mmCIF format.  That's the successor to PDB format.  It doesn't place any limit on the number of atoms.  In the script, you can just change

```python
pdb = PDBFile('input.pdb')
```

to

```python
pdb = PDBxFile('input.cif')
```

**Comment by ixy90** [comment]
Thank you very much, this was very helpful :)
