### ISSUE TITLE
Documentation not clear

### ISSUE THREAD

**Issue by xx7Ahmed7xx** [openmm/openmm#3523]
I still Can't find any real valuable information about how to import this to python, Or an actual Python API to use?

**Comment by peastman** [comment]
See http://docs.openmm.org/latest/userguide/application/02_running_sims.html and http://docs.openmm.org/latest/api-python/.

**Comment by peastman** [comment]
I'm closing this, since the question was answered.

**Comment by xx7Ahmed7xx** [comment]
Hello Yes I checked them but Can't find the part where it makes a 3D visualization and alignment to other genomes .. Can you help ?

**Comment by peastman** [comment]
For 3D visualization, some good programs are VMD, ChimeraX, and PyMol.  Genome alignment is a completely different field.  I don't have experience with programs for that.
