### ISSUE TITLE
Is it possible to optimize the structure of small molecule in gas phase?

### ISSUE THREAD

**Issue by OkKakao** [openmm/openmm#3524]
I'm trying to optimize cucurbit[6]uril(CB6) in gas phase, so I prepared pdb file with a rough structure of single CB[6] molecule.

However, when I executed python code, it couldn't recognize the single atoms in the pdb file.

The error message was multiple lines of following texts.

/usr/local/envs/openmm/lib/python3.7/site-packages/openmm/app/internal/pdbstructure.py:537: UserWarning: WARNING: duplicate atom (HETATM    5  N           1       5.647  -0.944  -0.393  1.00  0.00           N  , HETATM    2  N           1      10.749   0.810  -2.783  1.00  0.00           N  )
warnings.warn("WARNING: duplicate atom (%s, %s)" % (atom, old_atom._pdb_string(old_atom.serial_number, atom.alternate_location_indicator)))

The used pdb file is the following.
It contains only one CB6 molecule with rough structure.
[Untitled-1.zip](https://github.com/openmm/openmm/files/8311202/Untitled-1.zip)

**Comment by peastman** [comment]
In your file, the name of each atom is just its element symbol.  That's what it's warning you about.  Atom names are supposed to be unique within a residue.  You have a single residue with many atoms all called "H", many others all called "C", etc.  You should make the names unique, for example "H1", "H2", ...

Another problem with your file is that the residue name and chain ID columns are blank.

**Comment by OkKakao** [comment]
> In your file, the name of each atom is just its element symbol. That's what it's warning you about. Atom names are supposed to be unique within a residue. You have a single residue with many atoms all called "H", many others all called "C", etc. You should make the names unique, for example "H1", "H2", ...
> 
> Another problem with your file is that the residue name and chain ID columns are blank.

Thanks for kind explanation!
I didn't know that there is pdb file format for openmm simulation.

Is there any website or document that explains about the pdb file format?
I'm really newbie in this area...

**Comment by swails** [comment]
OpenMM uses the "standard" PDB file format (found [here](https://www.wwpdb.org/documentation/file-format)).

This isn't an assumption inherent to OpenMM (that is, that all atoms in a residue have to have a unique atom name), but rather one that is essentially present in every bioinformatics application (every MD program will have the same requirement).

**Comment by OkKakao** [comment]
I used chemdraw 3D and it generated the PDB file which is not distinguish the atoms and has missing parameters. 
I think that I have to modify the file with respect to the website.
Thank you for answering my question!
