### ISSUE TITLE
Position restrains on P atoms

### ISSUE THREAD

**Issue by nataliaszulc** [openmm/openmm#3525]
Hello,
I have a problem with setting position force (position restrains) on P atoms. I tried to check how Z coordinates of each P atom change over time, however, there's no pattern on the plot; even if I set the force to vale 10 000 kcal/(molnm^2), see _Figure_. 
![obraz](https://user-images.githubusercontent.com/48363461/159230546-f03f3f30-aeee-4f11-bae0-a48ae61fdf27.png)

The input files: https://we.tl/t-RKLRxjojzm

Below the script:
"""
import simtk.openmm as omm
from simtk.openmm.app import *
import simtk.openmm.app  as omm_app
from simtk.unit import *
from sys import stdout
import mdtraj as md
# load file 
t = md.load('at_autopsf.pdb')

# calculate indices and angles
psi_ind, psi_angles = md.compute_psi(t)
phi_ind, phi_angles = md.compute_phi(t)
print(psi_angles[0][1])

psf = CharmmPsfFile('at_autopsf.psf')
pdb = PDBFile('at_autopsf.pdb')
params = CharmmParameterSet('top_all36_prot.rtf', 'par_all36_prot.prm',
                             'top_all36_lipid.rtf', 'par_all36_lipid.prm',
                             'toppar_water_ions.str')
psf.box_vectors = ((72/10, 0, 0), (0, 72/10, 0), (0, 0, 132/10))
system = psf.createSystem(params, nonbondedMethod=PME, nonbondedCutoff=1.2*nanometer, constraints=HBonds, switchDistance=1.0*nanometer,rigidWater=True)

# definition of the torsion force object
torsion_psi = omm.CustomTorsionForce("0.5*k_psi*dtheta^2; dtheta = min(tmp, 2*pi-tmp); tmp = abs(theta - psi)")
torsion_psi.addGlobalParameter("pi", math.pi)
torsion_psi.addGlobalParameter("k_psi", 1000)

# definition of the torsion force object
torsion_phi = omm.CustomTorsionForce("0.5*k_phi*dtheta^2; dtheta = min(tmp, 2*pi-tmp); tmp = abs(theta - phi)")
# variable, which not change
k=500 * kilocalories_per_mole/radians**2
torsion_phi.addGlobalParameter("pi", math.pi)
torsion_phi.addGlobalParameter("k_phi", k)
torsion_psi.addGlobalParameter("pi", math.pi)
torsion_psi.addGlobalParameter("k_psi", k)

# variables, which change
torsion_phi.addPerTorsionParameter("phi")
torsion_psi.addPerTorsionParameter("psi")

# Add per torsion parameters for each torsion value
for i, list_index in enumerate(psi_ind):
    a=int(list_index[0])
    b=int(list_index[1])
    c=int(list_index[2])
    d=int(list_index[3])
    torsion_psi.addTorsion(a,b,c,d, [psi_angles[0][i] * radians]) 
    print(a,b, c, d) 
    print([psi_angles[0][i] * radians]) 

# Add per torsion parameters for each torsion value
for i, list_index in enumerate(phi_ind):
    e=int(list_index[0])
    f=int(list_index[1])
    g=int(list_index[2])
    h=int(list_index[3])
    torsion_phi.addTorsion(e,f,g,h, [phi_angles[0][i] * radians])  
    print (e, f, g, h)
    print ([phi_angles[0][i] * radians])
system.addForce(torsion_psi)
system.addForce(torsion_phi)

#Harmonic restrains
force = omm.CustomExternalForce("k*(z-z0)^2")
force.addGlobalParameter("k",10000*kilojoule_per_mole/nanometer**2)
force.addPerParticleParameter("z0")

for atom in pdb.topology.atoms():
    if atom.name == 'P':
        force.addParticle(atom.index, [pdb.positions[atom.index][-1]])

integrator = LangevinMiddleIntegrator(300*kelvin, 1/picosecond, 0.002*picoseconds)
simulation = Simulation(pdb.topology, system, integrator)
simulation.context.setPositions(pdb.positions)
simulation.minimizeEnergy()

simulation.reporters.append(PDBReporter('output2_k10000_only_z.pdb', 5000))
simulation.reporters.append(StateDataReporter(stdout, 5000, step=True,
        potentialEnergy=True, temperature=True))

simulation.step(500* 5000)
"""

I'd like to ask for help

**Comment by swails** [comment]
Can you edit your post to replace the `"""` with back-ticks so the code gets formatted?   Even better is to format it as python:

````
```python
<paste script here>
```
````

That'll make it easier to both read and copy-paste to get a working example (note that without this formatting, all of the indentation and formatting is discarded).

**Comment by swails** [comment]
One other observation, you create a harmonic restraint force:

```python
force = omm.CustomExternalForce("k*(z-z0)^2")
force.addGlobalParameter("k",10000*kilojoule_per_mole/nanometer**2)
force.addPerParticleParameter("z0")

for atom in pdb.topology.atoms():
    if atom.name == 'P':
        force.addParticle(atom.index, [pdb.positions[atom.index][-1]])
```

but then never actually add it to the system, so the simulation never actually applies that force.

You need to add `system.addForce(force)` after you finish adding all of the particles to it (similarly to what you did for `torsion_psi` and `torsion_phi`).

**Comment by nataliaszulc** [comment]
Hello, I have still problem  with a harmonic restraint force.  I checked again how Z coordinates of each P atom change over time, however, there's no pattern on the plot; even if I set the force to vale 10 000 kcal/(molnm^2), I look even worse than without force, see Figure.
![obraz](https://user-images.githubusercontent.com/48363461/159529324-56ad2563-891d-453e-a136-b9c076bf48ed.png)
```python
<import simtk.openmm as omm
from simtk.openmm.app import *
import simtk.openmm.app as omm_app
from simtk.unit import *
from sys import stdout
import mdtraj as md

# load file 
t = md.load('at_autopsf.pdb')

# calculate indices and angles
psi_ind, psi_angles = md.compute_psi(t)
phi_ind, phi_angles = md.compute_phi(t)
print(psi_angles[0][1])

psf = CharmmPsfFile('at_autopsf.psf')
pdb = PDBFile('at_autopsf.pdb')
params = CharmmParameterSet('top_all36_prot.rtf', 'par_all36_prot.prm',
                             'top_all36_lipid.rtf', 'par_all36_lipid.prm',
                             'toppar_water_ions.str')
psf.box_vectors = ((72/10, 0, 0), (0, 72/10, 0), (0, 0, 132/10))
system = psf.createSystem(params, nonbondedMethod=PME, nonbondedCutoff=1.2*nanometer, constraints=HBonds, switchDistance=1.0*nanometer,rigidWater=True)


# definition of the torsion force object
torsion_psi = omm.CustomTorsionForce("0.5*k_psi*dtheta^2; dtheta = min(tmp, 2*pi-tmp); tmp = abs(theta - psi)")
torsion_psi.addGlobalParameter("pi", math.pi)
torsion_psi.addGlobalParameter("k_psi", 1000)

# definition of the torsion force object
torsion_phi = omm.CustomTorsionForce("0.5*k_phi*dtheta^2; dtheta = min(tmp, 2*pi-tmp); tmp = abs(theta - phi)")
# variable, which not change
k=500 * kilocalories_per_mole/radians**2
torsion_phi.addGlobalParameter("pi", math.pi)
torsion_phi.addGlobalParameter("k_phi", k)
torsion_psi.addGlobalParameter("pi", math.pi)
torsion_psi.addGlobalParameter("k_psi", k)

# variables, which change
torsion_phi.addPerTorsionParameter("phi")
torsion_psi.addPerTorsionParameter("psi")

# Add per torsion parameters for each torsion value
for i, list_index in enumerate(psi_ind):
    a=int(list_index[0])
    b=int(list_index[1])
    c=int(list_index[2])
    d=int(list_index[3])
    torsion_psi.addTorsion(a,b,c,d, [psi_angles[0][i] * radians]) 
 
# Add per torsion parameters for each torsion value
for i, list_index in enumerate(phi_ind):
    e=int(list_index[0])
    f=int(list_index[1])
    g=int(list_index[2])
    h=int(list_index[3])
    torsion_phi.addTorsion(e,f,g,h, [phi_angles[0][i] * radians])  
system.addForce(torsion_psi)
system.addForce(torsion_phi)


#Harmonic restrains
force = omm.CustomExternalForce("k*(z-z0)^2")
force.addGlobalParameter("k",1000*kilojoule_per_mole/nanometer**2)
force.addPerParticleParameter("z0")

for atom in pdb.topology.atoms():
    if atom.name == 'P':
        print(atom.index)
        force.addParticle(atom.index, [pdb.positions[atom.index][-1]])
system.addForce(force)

integrator = LangevinMiddleIntegrator(300*kelvin, 1/picosecond, 0.002*picoseconds)
simulation = Simulation(pdb.topology, system, integrator)
simulation.context.setPositions(pdb.positions)
simulation.minimizeEnergy()

simulation.reporters.append(PDBReporter('output2_k1000only_z.pdb', 5000))
simulation.reporters.append(StateDataReporter(stdout, 5000, step=True,
        potentialEnergy=True, temperature=True))

simulation.step(500* 5000>
```

**Comment by swails** [comment]
A few observations:

* Are these coordinates measured in angstroms (which is what's stored in the PDB file) or nanometers (which is what OpenMM measures lengths using)?
* It's not clear that your plotting command is in fact limiting the coordinate plots to just the restrained (P) atoms
* The force constants are not actually as big as they initially seem.  1000 kJ/mol/nm**2 and 10,000 kJ/mol/nm**2 are equal to ~2 kcal/mol/Angstrom**2 and ~20 kcal/mol/Angstrom**2, respectively.  These are pretty weak restraints, especially on an atom as heavy as phosphorus, so it wouldn't surprise me if the Z-coordinate varies over the simulation by a few angstroms (not a few nanometers, but the scale of your plots makes me think they're plotted in angstroms, not nm).
* Notice that the the scales in the two plots you showed are different -- the stronger constraints have a smaller range (6 Angstroms or nm) than the unrestrained (9 Angstroms or nm).  For the very weak restraint of 1000 kJ/mol/nm**2 that doesn't seem unreasonable.

The only way to tell for sure whether the restraint is actually working is to check that its energy and force contributions are properly computed and included.  That's a bit involved, but possible (ParmEd has some energy decomposition utilities that are useful or this application).

But there are some straightforward things you can try:

* Restrain *all* Z-coordinates (not just P)
* Use a stronger force constant (maybe 100,000 kJ/mol/nm**2)
* Make sure of the units you're using in your coordinate plots and that you're plotting the atoms you think you are (it's easy to confuse atom indices, especially when mixing schemes where indexes start at 0 or 1).

**Comment by peastman** [comment]
There's a [cookbook entry](https://openmm.github.io/openmm-cookbook/dev/notebooks/cookbook/Analyzing%20Energy%20Contributions.html) that shows how to compute individual energy contributions.

**Comment by swails** [comment]
[ParmEd's utility functions to do it](https://github.com/ParmEd/ParmEd/blob/master/parmed/openmm/utils.py) :smile:

**Comment by nataliaszulc** [comment]
Thank you very much for precious advice.

**Comment by nataliaszulc** [comment]
Are the coordinates in the nm in opemm or it depends @peastman ?

**Comment by swails** [comment]
OpenMM stores them internally in nm, but the pdb spec requires angstroms. So if you are reading the pdb files raw, the coordinates will be in Angstroms. If you're using mdtraj, the coordinates are all converted to nm I believe. Other programs like ParmEd or pytraj operate in Angstroms. 

So we'd really need to see the full code you used to make the plots to determine what the units are.

**Comment by DanielWicz** [comment]
> OpenMM stores them internally in nm, but the pdb spec requires angstroms. So if you are reading the pdb files raw, the coordinates will be in Angstroms. If you're using mdtraj, the coordinates are all converted to nm I believe. Other programs like ParmEd or pytraj operate in Angstroms. 
> 
> So we'd really need to see the full code you used to make the plots to determine what the units are. 


Isn't it always converted to nm if you use openmm ? Because she asks (she sits in the same room as me 😅) if it's in nm, because the unit for force constant is in kcal/nm^2 then

**Comment by swails** [comment]
The code posted only shows how the simulation is run, and that the coordinates are dumped via a PDB file reporter.  So even though OpenMM tracks positions in nm, it *writes* them to the PDB file in Angstroms because that's what the spec requires.

The code shown with the plot is just `plt.plot(coordinates[:, -1])`, with no context as to where `coordinates` came from.  Was it parsed from the PDB file?  If so, how?  Was it retrieved another way?  If so, how?  Where did the `coordinates` object get instantiated - what was the code that preceded the plot?  Certainly if the coordinates are parsed from the PDB using OpenMM, then the positions would be stored in nanometers, but they would also have units applied and would need to be converted into a numpy array before being plotted with `plt.plot(coordinates[:, -1])`.

If, on the other hand, you used something like ParmEd to parse the PDB file and select just the `P` atoms (code for doing so shown below), then the coordinates would be in Angstroms.  Since the OpenMM code shown above only pulls coordinates by writing to a PDB file, I'm assuming this must be where the coordinates come from to plot.  The code going from PDB file to `coordinates` is what I'm missing here and what ultimately determines what units the plot is shown in.

```python
import parmed as pmd

pdb = pmd.load_file("output2_k1000only_z.pdb")
coordinates = pdb["@P"].coordinates

# Plot the Z-coordinates of atoms named P in Angstroms
plt.plot(coordinates[:, -1])
```

**Comment by peastman** [comment]
Can this be closed, or are you still having problems with it?
