### ISSUE TITLE
RMSDForce: Only serialize/deserialize ReferencePositions of active Particles?

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#3529]
When `System` objects containing `RMSDForce` objects are serialized, current behavior is that all `ReferencePositions` are written, whether or not these are actually designated to be used in computing the RMSD or not. As a result, a serialized `system.xml` file for a solvated system can go from 7MB to 159MB!

Instead, what if we only serialized/deserialized the positions of active particles? This would save an enormous amount of storage in most circumstances.

**Comment by peastman** [comment]
That would throw out information.  Our guarantee with serialization is that the reconstructed object is bit-for-bit identical to the original one.  In the case of RMSDForce, a reasonable workflow might be to save an RMSDForce including positions for all particles, then repeatedly load it and call `setParticles()` to create versions that compute the RMSD for different sets of particles.  Also, `copy()` and `deepcopy()` are implemented through serialization.

> As a result, a serialized system.xml file for a solvated system can go from 7MB to 159MB!

That doesn't make sense.  All it stores for each particle is a single tag that looks like

```xml
<Position x="..." y="..." z="..."/>
```

The size of that tag should be similar to what NonbondedForce stores for each particle:

```xml
<Particle q="..." sig="..." eps="..."/>
```

At worst the change in size of the file should be on the order of 2x, not 20x.

**Comment by peastman** [comment]
Maybe you're compressing the files, and you're comparing the sizes after compression?  Many particles tend to have identical parameters, so that part of the file compresses very well.  If every particle has a different reference position, they won't compress well.

If that's the problem, set the reference position of any particle you don't care about to (0, 0, 0).

**Comment by jchodera** [comment]
You're right---the size change I reported was incorrect because the 7MB file was somehow truncated. A 100K atom system only grows from 1.4MB to 1.8MB on a local test.
