### ISSUE TITLE
Nightly omnia-dev builds are no longer building

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#3530]
It looks like [`omnia-dev` nightly builds](https://github.com/omnia-md/conda-dev-recipes) stopped being updated six days ago:
https://anaconda.org/omnia-dev/openmm/files
![image](https://user-images.githubusercontent.com/3656088/159838340-394f10ea-f1ea-4d6c-8244-7a35d9b6973f.png)
I'm investigating now.

**Comment by jchodera** [comment]
@peastman : It looks like the linux builds are failing with this error:
```
/home/conda/build_artifacts/openmm_1648099009272/work/libraries/asmjit/asmjit/core/cpuinfo.cpp:18:12: fatal error: sys/auxv.h: No such file or directory
   18 |   #include <sys/auxv.h>
      |            ^~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/OpenMM.dir/build.make:3044: CMakeFiles/OpenMM.dir/libraries/asmjit/asmjit/core/cpuinfo.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:694: CMakeFiles/OpenMM.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

[conda-build-all] Error: one or more packages failed to build
  openmm-7.8-py38_cuda92_debug_1: Command '['/bin/bash', '-o', 'errexit', '/home/conda/build_artifacts/openmm_1648098485015/work/conda_build.sh']' returned non-zero exit status 2.
  openmm-7.8-py38_cuda92_1: Command '['/bin/bash', '-o', 'errexit', '/home/conda/build_artifacts/openmm_1648099009272/work/conda_build.sh']' returned non-zero exit status 2.
##[error]Bash exited with code '2'.
```
The failures started ~7 days ago. 

It looks like this `#include` appears in [this file modified 7 days ago](https://github.com/openmm/openmm/blob/cc7018eac438a2a510090658e9adee35f67c9bfa/libraries/asmjit/asmjit/core/cpuinfo.cpp):
```
// Required by `getauxval()` on Linux.
#if defined(__linux__)
  #include <sys/auxv.h>
#endif
```
Is there any chance we need to upgrade the compiler or include some other dependency in our docker image in order to make this work?

**Comment by jchodera** [comment]
The CUDA 11.0 builds are now working again, but we'll need to update the docker images to get other versions to build:
https://github.com/omnia-md/conda-dev-recipes/issues/216

**Comment by zhang-ivy** [comment]
@jchodera @peastman It looks like the nighty builds are not longer updating: https://anaconda.org/omnia-dev/openmm/files

Some of them were last updated ~2 weeks ago, whereas others were last updated > 1 month ago.
