### ISSUE TITLE
OpenMM has trouble with MoE files

### ISSUE THREAD

**Issue by ixy90** [openmm/openmm#3532]
Did anybody else have troubles using files from MoE/maestro in OpenMM? I have some files which were edited with MoE, and I tried to preprocess them with pdbfixer and OpenMM, and still OpenMM wouldn’t take them. Is there an obvious reason I am not seeing, is it a common issue, or is it just my file?

Any help is very appreciated!

**Comment by peastman** [comment]
Can you provide more details?  What is the exact error message you get when you try to load the file?  If you can post the file and the code you're using to try to load it, that would help.

**Comment by ixy90** [comment]
[5wyz-processed_with_lig3.pdb.txt](https://github.com/openmm/openmm/files/8352805/5wyz-processed_with_lig3.pdb.txt)

I had to append .txt, so that github would upload the file. My code is very basic:

pdb = PDBFile('5wyz-processed_with_lig3.pdb')
forcefield = ForceField('amber99sb.xml', 'tip3p.xml')
system = forcefield.createSystem(pdb.topology, nonbondedMethod=NoCutoff,
        nonbondedCutoff=1*nanometer, constraints=HBonds)
integrator = LangevinIntegrator(300*kelvin, 1/picosecond, 0.002*picoseconds)
simulation = Simulation(pdb.topology, system, integrator)
simulation.context.setPositions(pdb.positions)
simulation.minimizeEnergy()
simulation.reporters.append(PDBReporter('output.pdb', 100))
simulation.reporters.append(StateDataReporter(stdout, 100, step=True,
        potentialEnergy=True, temperature=True))
simulation.step(1000)

and the error I am getting is:

ValueError: No template found for residue 1623 (*).  This might mean your input topology is missing some atoms or bonds, or possibly that you are using the wrong force field.

**Comment by peastman** [comment]
Your file contains a ligand that the Amber force field doesn't provide parameters for.  See https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template for more information about this issue.  The [user guide](http://docs.openmm.org/latest/userguide/application/02_running_sims.html#small-molecule-parameters) has instructions on how you can generate parameters for it.

**Comment by ixy90** [comment]
I am thinking wether it would be easier to merge the ligand to the protein in another way

**Comment by peastman** [comment]
What other way are you referring to?  One way or another, you need to parametrize the ligand.

**Comment by ixy90** [comment]
referring to not using moe, but a different approach. I am thinking about rdkit in particular.

**Comment by jchodera** [comment]
That tutorial ultimately [uses the OpenMM residue template generators for small molecules](https://github.com/openmm/openmmforcefields#using-amber-gaff-1x-and-2x-for-small-molecules) to generate parameters for the small molecule, so the same underlying approach to generate small molecule parameters will be used whether you use the template generator directly or follow this tutorial.
