### ISSUE TITLE
saving and re-using small molecule topologies

### ISSUE THREAD

**Issue by mbatgh** [openmm/openmm#3539]
I try to use openmm MD to post-process some docking output.
Here I need to parameterize several ligands, and run, for each of them multiple MD simulations each
starting with different ligand coordinates/conformations.
Since some of these ligands are rather large the AM1BCC charge calculation becomes the bottleneck,
and I'd rather do this calculation only once per molecule. I got as far as the code snippet shown below.
After that I merge the protein and the molecule, and perform an MD simulation, and, next to other output
a file gaff-molecules.json ends up in my working directory. 
Question is: how can I reuse the topology and charges saved (I assume) in gaff-molecules.json
in another simulation run so that I do not have to calculate the charges again?
thanks for any help!
Michael

molecule = Molecule.from_file('small.sdf')
molecule.compute_partial_charges_am1bcc()
gaff = GAFFTemplateGenerator(cache='gaff-molecules.json', molecules=molecule, forcefield='gaff-2.11')
forcefield = ForceField('amber14-all.xml', 'implicit/gbn2.xml')
forcefield.registerTemplateGenerator(gaff.generator)

**Comment by peastman** [comment]
After you create a System by calling `createSystem()` on the ForceField, you can save it to a file.  See this [cookbook entry](https://openmm.github.io/openmm-cookbook/dev/notebooks/cookbook/Saving%20Systems%20to%20XML%20Files.html) that shows how to do it.

**Comment by jchodera** [comment]
Try removing the `molecule.compute_partial_charges()` call. If the molecule
does not have charges, the template generator should compute AM1-BCC
charges only when they don't already exist in the JSON cache file you
specify. This should do what you're hoping to do and avoid recomputing
charges if they've already been computed.

**Comment by mbatgh** [comment]
thank you! .... so far i only tried the second solution (just leave out the compute_partial_charges line), but that works like a charm, a few brief follow up brief questions: 
1) If I register more than one molecule in a given json file, and then later re-load the json file, and try to simulate one of the molecules, openmm will figure out on its own which parameter set belongs to my chosen molecule, correct?
2) if i load a molecule for which parameters exist in the json file, but the original input file had a different atom order, the algorithm is smart enough to understand that, and assign parameters as appropriate, i.e., only based on elements and connectivity, ignoring order and/or atom names, correct?
3) there are cases when the point 2 applies, two molecules have identical elements and connectivity, but they might have different stereo-chemistry, and therefore different charges, i assume openmm considers these molecules as identical, and i have to save them in two different json files to make sure i get what i want, correct?

thanks again, and best regards,
michael

**Comment by jchodera** [comment]
> If I register more than one molecule in a given json file, and then later re-load the json file, and try to simulate one of the molecules, openmm will figure out on its own which parameter set belongs to my chosen molecule, correct?

Correct! The residue template generator will attempt to find a match for your molecule's topology (elements and connectivity) in the JSON file, and generate new parameters if they aren't found. Also, once the template has been generated, `ForceField` will already know about it and re-use the parameters for subsequent instances it encounters during the lifetime of the `ForceField` object.

> if i load a molecule for which parameters exist in the json file, but the original input file had a different atom order, the algorithm is smart enough to understand that, and assign parameters as appropriate, i.e., only based on elements and connectivity, ignoring order and/or atom names, correct?

Correct. The [residue matching code](https://github.com/openmm/openmmforcefields/blob/master/openmmforcefields/generators/template_generators.py#L126-L196) identifies a valid graph isomorphism between your molecule and the template using only the elements and connectivity.

> there are cases when the point 2 applies, two molecules have identical elements and connectivity, but they might have different stereo-chemistry, and therefore different charges, i assume openmm considers these molecules as identical, and i have to save them in two different json files to make sure i get what i want, correct?

Correct---only one set of charges can be applied in this case because we don't have a way to specify stereochemistry in the OpenMM `Topology` object, so there is no way to identify the difference between two molecules that may have two stereocenters with distinct sets of stereochemistry that would lead to distinct partial charges. You'd want to carefully keep those JSON files separate yourself, or avoid using the cache. 

The `openmmtools` residue template generator scheme is only a stopgap measure until the [Open Force Field Initiative](http://openforcefield) toolchain is mature enough to parameterize heterogeneous systems directly. Those tools should properly be able to deal with situations like these, though there is still some debate about how to robustly handle the case you highlight.

**Comment by mbatgh** [comment]
thanks for the elaborate answer - very helpful!

**Comment by mbatgh** [comment]
Hi,
thanks again, both methods suggested by John (above) and Jeff (https://github.com/openforcefield/openff-toolkit/issues/1237) work.
two more comments before I close the issue:
1) I found that, for the charges to be saved in a json file issuing the command forcefield.registerTemplateGenerator(gaff.generator) is not enough - it needs to be followed by
the creation of a Modeller object, and a call to forcefield.createSystem.
2) Jeffs solution, saving charges in an sdf file works, but only after explicitly calculating
the charges using molecule.compute_partial_charges_am1bcc() - 
If I use the GAFFTemplateGenerator, and then save an sdf file the charges (in spite of
having been calculated) do not show up in the sdf file.
cheers,
michael

**Comment by jchodera** [comment]
> sorry, one more ... talking about charges and the (lack of) speed of conventional AM1BCC for larger molecules ...
are there any plans to incorporate Graph Nets for Partial Charge Prediction (https://arxiv.org/abs/1909.07903) in openmm?

This is on the roadmap for an upcoming Open Force Field Toolkit release!

**Comment by jchodera** [comment]
> I found that, for the charges to be saved in a json file issuing the command forcefield.registerTemplateGenerator(gaff.generator) is not enough - it needs to be followed by the creation of a Modeller object, and a call to forcefield.createSystem.

You don't need a `Modeller` object, but the `forcefield.createSystem()` object does need to _encounter_ the small molecule to cause it to generate and cache the parameters in the JSON file. We try to be "lazy" in only doing the work if we need to.

If it would be useful for you to call a method in the residue template generator directly to cause the parameters to be generated and cached for one or more molecules, we could add an API for this---just [open an issue here](https://github.com/openmm/openmmforcefields/issues) to suggest what you would like to do.
