### ISSUE TITLE
Cucurbit[7]uril simulation explodes

### ISSUE THREAD

**Issue by OkKakao** [openmm/openmm#3540]
I'm new to MD simulation, somy question can be somewhat stupud.

My goal is simulating cucurbit[7]uril(CB7) in NaCl dissoved water.

At the beggining, I tried the simplest simulation which contains only one CB7 molecule. 

Since there was no xml forcefield file for CB7, I made a template for it refering to openmm user guide section 6.2.4

So it's working, but it explodes.

The code I used is the following.

```
from openmm.app import *
from openmm import *
from openmm.unit import *
from sys import stdout
pdb = PDBFile('CB7_clean3.pdb')
forcefield = ForceField('amber99sb.xml')
[templates, residues] = forcefield.generateTemplatesForUnmatchedResidues(pdb.topology)
# Set the atom types
for template in templates:
  for i, atom in enumerate(template.atoms):
    # set the atom types here
    atom.type = str(i)
  # Register the template with the forcefield.
  forcefield.registerResidueTemplate(template)
system = forcefield.createSystem(pdb.topology, nonbondedMethod=NoCutoff, nonbondedCutoff=1*nanometer, constraints=HBonds)
integrator = LangevinMiddleIntegrator(0*kelvin, 1/picosecond, 0.0005*picoseconds)
simulation = Simulation(pdb.topology, system, integrator)
simulation.context.setPositions(pdb.positions)
simulation.minimizeEnergy()
simulation.reporters.append(PDBReporter('output.pdb', 1000))
simulation.reporters.append(StateDataReporter(stdout, 1000, step=True,
        potentialEnergy=True, temperature=True))
simulation.step(10000)
```

Also, the result is the Following.

```
#"Step","Potential Energy (kJ/mole)","Temperature (K)"
1000,-528.2065489814863,3708.8827041309964
2000,-1678.2273992662508,5752.324609753581
3000,-2587.614816098203,2472.9813116496016
4000,-3562.001530840667,1341.5109864917151
5000,-3988.607068658437,695.7039660677575
6000,-4433.092435269031,456.66088447698735
7000,-4656.915828749186,259.0041147834574
8000,-4784.801297554609,203.92985158535174
9000,-4919.4551498926285,163.04881461822734
10000,-5064.190460554809,116.2632247649496
```

The temperature of the simulation ascends to the heaven and then falls to the ground.

I can't spot the problem of my simulation...
[CB7_clean3.zip](https://github.com/openmm/openmm/files/8389340/CB7_clean3.zip)
.

**Comment by jchodera** [comment]
Have you tried using the GAFF or SMIRNOFF residue template generators that are intended to produce useful parameters for small molecules? Check out the documentation here: http://docs.openmm.org/latest/userguide/application/02_running_sims.html?highlight=gaff#small-molecule-residue-template-generators

It will take a few minutes the first time, but you can specify a JSON `cache` file to store the charges and parameters so the next time you run it, parameters can simply be read back from the JSON cache.

**Comment by OkKakao** [comment]
> Have you tried using the GAFF or SMIRNOFF residue template generators that are intended to produce useful parameters for small molecules? Check out the documentation here: http://docs.openmm.org/latest/userguide/application/02_running_sims.html?highlight=gaff#small-molecule-residue-template-generators
> 
> It will take a few minutes the first time, but you can specify a JSON `cache` file to store the charges and parameters so the next time you run it, parameters can simply be read back from the JSON cache.

I coudn't try the methods since I don't have license for openeye module.
Is there any possible way to try those methods without obtaining the license?
I also requested the license from official openeye website, but they replied that it takes 2-4weeks...

**Comment by jchodera** [comment]
If you installed openmmforcefields from conda via conda-forge, it should
fall back on free tools (in this case AmberTools and RDKit) if you don't
have the OpenEye toolkit! If it isn't doing this correctly, can you paste
the error you're seeing and export a copy of your conda environment so we
can figure out what's going wrong?

**Comment by OkKakao** [comment]
I found that it was just an RDkit error. I solved the error by installing RDkit with following code.
```
import sys
import os
import requests
import subprocess
import shutil
from logging import getLogger, StreamHandler, INFO


logger = getLogger(__name__)
logger.addHandler(StreamHandler())
logger.setLevel(INFO)


def install(
        chunk_size=4096,
        file_name="Miniconda3-latest-Linux-x86_64.sh",
        url_base="https://repo.continuum.io/miniconda/",
        conda_path=os.path.expanduser(os.path.join("~", "miniconda")),
        rdkit_version='2020.03.3',
        add_python_path=True,
        force=False):
    """install rdkit from miniconda
    ```
    import rdkit_installer
    rdkit_installer.install()
    ```
    """

    python_path = os.path.join(
        conda_path,
        "lib",
        "python{0}.{1}".format(*sys.version_info),
        "site-packages",
    )

    if add_python_path and python_path not in sys.path:
        logger.info("add {} to PYTHONPATH".format(python_path))
        sys.path.append(python_path)

    if os.path.isdir(os.path.join(python_path, "rdkit")):
        logger.info("rdkit is already installed")
        if not force:
            return

        logger.info("force re-install")

    url = url_base + file_name
    python_version = "{0}.{1}.{2}".format(*sys.version_info)

    logger.info("python version: {}".format(python_version))

    if os.path.isdir(conda_path):
        logger.warning("remove current miniconda")
        shutil.rmtree(conda_path)
    elif os.path.isfile(conda_path):
        logger.warning("remove {}".format(conda_path))
        os.remove(conda_path)

    logger.info('fetching installer from {}'.format(url))
    res = requests.get(url, stream=True)
    res.raise_for_status()
    with open(file_name, 'wb') as f:
        for chunk in res.iter_content(chunk_size):
            f.write(chunk)
    logger.info('done')

    logger.info('installing miniconda to {}'.format(conda_path))
    subprocess.check_call(["bash", file_name, "-b", "-p", conda_path])
    logger.info('done')

    logger.info("installing rdkit")
    subprocess.check_call([
        os.path.join(conda_path, "bin", "conda"),
        "install",
        "--yes",
        "-c", "rdkit",
        "python==3.7.9",
        "rdkit" if rdkit_version is None else "rdkit=={}".format(rdkit_version)])
    logger.info("done")

    import rdkit
    logger.info("rdkit-{} installation finished!".format(rdkit.__version__))

install()
```
