### ISSUE TITLE
charmmpsffile.py failing to recognize case-sensitive atom types

### ISSUE THREAD

**Issue by mdpoleto** [openmm/openmm#3541]
Hi,

I recently had to run simulations using metal ions provided in **toppar_ions_won.str** and I realized that, while the .psf file built by CHARMM has a atom type "CU1P", OpenMM failed to recognize the atom type "Cu1p". When I changed my atom type in the .psf file to "Cu1p", OpenMM is able to recognize it. That problem is not observed in CHARMM since everything is read as uppercase strings.

Further inspection of the charmmpsffile.py shows (line 232 and 612-625) that atom types are read as they are written, thus failing when there is a mismatch between the atom types string cases.

**Comment by peastman** [comment]
I'm working on fixing this now.  Do you have a file I can use to test it?

**Comment by mdpoleto** [comment]
Hi @peastman 

You can use the tarball attached below. Note that the file "cu1p.psf" should fail, while "cu1p_FIX.psf" should provide the correct behavior. 

[case_sensitive_example.zip](https://github.com/openmm/openmm/files/9292942/case_sensitive_example.zip)

If I can help in any other way, please let me know.

**Comment by peastman** [comment]
Your script runs without problem using either file.  What version of OpenMM are you using?  I think this was probably fixed by #3273, which means it ought to work in 7.7.

**Comment by mdpoleto** [comment]
You are right. I am using 7.6 and I was not aware of that fix for 7.7 (searching for "case-sensitive" in closed issues did not find #3273 so I created this one). Thanks Peter.
