### ISSUE TITLE
Drop support for processors without AVX

### ISSUE THREAD

**Issue by peastman** [openmm/openmm#3544]
The first CPUs with AVX were released in 2011.  It has been standard on all x86 processors from both Intel and AMD for many years.  What do you think about dropping support for processors that don't include it?

This came up in the context of #3351.  Supporting vectorization of Lepton expressions both with and without AVX support would add a lot of complexity.  Alternatively I could make older processors still work, but they wouldn't get JIT compilation of expressions anymore, which would make custom forces on the CPU platform slower.

**Comment by jchodera** [comment]
We could do a quick Twitter poll to see if there is any need to support x86
without AVX.

Any suggestions on the wording and options?

**Comment by peastman** [comment]
You could just ask whether they're still using old x86 processors without AVX support.  Options could include "Yes", "Yes, but not for anything where CPU performance is critical", and "No".

**Comment by jchodera** [comment]
Just posted the twitter poll here:
https://twitter.com/openmm_toolkit/status/1510685264481763328

I had to tailor the options a bit since each option must be 25 characters or less.

**Comment by peastman** [comment]
I see the result are up.  40% of respondents said they're still using an older CPU, which is a lot higher than I would have expected.  Clearly we need to maintain compatibility a while longer.  A much smaller fraction (18.5%) are using the CPU platform on it, and presumably some even smaller fraction of those are using custom forces.  Also, the text you used ("use CPU") doesn't really capture the distinction I was looking for ("anything where CPU performance is critical").

As an intermediate step, what about continuing to support older CPUs, but JIT compilation of custom expressions will require AVX?  They'll still work without JIT compilation, just not as quickly.

**Comment by swails** [comment]
In my recalled experience, even single point calculations on the CPU platform were uselessly slow when using custom nonbonded potentials (like the custom GB forces which constitute the defacto implementation of all the GB models in Amber except one) on standard protein sized systems.

**Comment by swails** [comment]
65 votes are also only a small number, and probably overrepresent the old processor support requests given they would seem to have the most to lose by not responding.

So on the one hand JIT probably matters the most to the old systems that will be unusably slow without it, but the workarounds are simple:

- Use an older version of OpenMM 
- Get a newer cpu (plenty of compatible refurb options at affordable costs)
- Run on a budget CPU
- Use the OpenCL platform on the CPU (I think?)

I'd drop JIT support for pre-AVX procs, personally.

**Comment by jchodera** [comment]
Here are the poll results, for reference:
![image](https://user-images.githubusercontent.com/3656088/161669072-323b1987-a95b-48f5-9a22-5eced75215ae.png)

**Comment by jchodera** [comment]
> As an intermediate step, what about continuing to support older CPUs, but JIT compilation of custom expressions will require AVX? They'll still work without JIT compilation, just not as quickly.

This sounds reasonable.

**Comment by jchodera** [comment]
Closing this since we have now merged #3552.
