### ISSUE TITLE
Pass blocking sync option to CUDA event creation

### ISSUE THREAD

**Issue by dmclark17** [openmm/openmm#3547]
I was looking into CPU usage for the CUDA platform and did not observe a reduction in CPU usage when using the `UseBlockingSync` option for the STMV benchmark. I believe this is because the synchronization primarily happens via `cuEventSynchronize`. It's [documentation](https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__EVENT.html#group__CUDA__EVENT_1g9e520d34e51af7f5375610bca4add99c ) says:

> Waiting for an event that was created with the CU_EVENT_BLOCKING_SYNC flag will cause the calling CPU thread to block until the event has been completed by the device. If the CU_EVENT_BLOCKING_SYNC flag has not been set, then the CPU thread will busy-wait until the event has been completed by the device.

It looks like when `UseBlockingSync` is true, `CU_CTX_SCHED_BLOCKING_SYNC` is passed to the context creation; however, the events are not created with the `CU_EVENT_BLOCKING_SYNC` flag. I tried hard coding the flag into the event creation, and it seemed to reduce the CPU usage. Would it be possible to pass `CU_EVENT_BLOCKING_SYNC` to the event creation when `UseBlockingSync` is enabled? Thanks!

**Comment by peastman** [comment]
Good idea!
