### ISSUE TITLE
RDKit conformer generation failed

### ISSUE THREAD

**Issue by mbatgh** [openmm/openmm#3550]
I just tried to prepare a small molecule using the code below.
I get a fatal error, also included below. I believe that the important part of the error msg is:
"RDKit conformer generation failed". This is a fairly large molecule with many rotatable bonds - 
can it be that rdkit fails because of that?

code snippet (sdf file attached)
molecule = Molecule.from_file(sdf_filename)
molecule.compute_partial_charges_am1bcc()

[QL8-fails.sdf.gz](https://github.com/openmm/openmm/files/8421268/QL8-fails.sdf.gz)

error msg:
Traceback (most recent call last):
  File "/home/michael/work/tcp/charge-protacs/sdf2json.py", line 53, in <module>
    molecule.compute_partial_charges_am1bcc()
  File "/home/michael/miniconda3/lib/python3.9/site-packages/openff/toolkit/topology/molecule.py", line 3584, in compute_partial_charges_am1bcc
    self.assign_partial_charges(
  File "/home/michael/miniconda3/lib/python3.9/site-packages/openff/toolkit/topology/molecule.py", line 3636, in assign_partial_charges
    toolkit_registry.call(
  File "/home/michael/miniconda3/lib/python3.9/site-packages/openff/toolkit/utils/toolkit_registry.py", line 380, in call
    raise ValueError(msg)
ValueError: No registered toolkits can provide the capability "assign_partial_charges" for args "()" and kwargs "{'molecule': Molecule with name 'QL8' and SMILES '[H][O][C@@]1([H])[C]([H])([H])[N]([C](=[O])[C@@]([H])([N]([H])[C](=[O])[C]([H])([H])[C]([H])([H])[O][C]([H])([H])[C]([H])([H])[O][C]([H])([H])[C]([H])([H])[O][C]([H])([H])[C]([H])([H])[O][C]([H])([H])[C]([H])([H])[O][C]([H])([H])[C]([H])([H])[O][C]([H])([H])[C]#[C][c]2[c]([H])[c]([H])[c]([O][C]([H])([H])[C]([H])([H])[C]([H])([H])[C]3=[C]([C](=[O])[O-])[N]=[C]([N]4[C]([H])([H])[c]5[c]([C](=[O])[N]([H])[C]6=[N][c]7[c]([H])[c]([H])[c]([H])[c]([H])[c]7[S]6)[c]([H])[c]([H])[c]([H])[c]5[C]([H])([H])[C]4([H])[H])[S]3)[c]([H])[c]2[H])[C]([C]([H])([H])[H])([C]([H])([H])[H])[C]([H])([H])[H])[C@]([H])([C](=[O])[N]([H])[C]([H])([H])[c]2[c]([H])[c]([H])[c]([C]3=[C]([C]([H])([H])[H])[N]=[C]([H])[S]3)[c]([H])[c]2[H])[C]1([H])[H]', 'partial_charge_method': 'am1bcc', 'use_conformers': None, 'strict_n_conformers': False, 'normalize_partial_charges': True, '_cls': <class 'openff.toolkit.topology.molecule.Molecule'>}"
Available toolkits are: [ToolkitWrapper around The RDKit version 2021.09.5, ToolkitWrapper around AmberTools version 21.0, ToolkitWrapper around Built-in Toolkit version None]
 ToolkitWrapper around The RDKit version 2021.09.5 <class 'openff.toolkit.utils.exceptions.ChargeMethodUnavailableError'> : partial_charge_method 'am1bcc' is not available from RDKitToolkitWrapper. Available charge methods are ['mmff94'] 
 ToolkitWrapper around AmberTools version 21.0 <class 'openff.toolkit.utils.exceptions.ConformerGenerationError'> : RDKit conformer generation failed.
 ToolkitWrapper around Built-in Toolkit version None <class 'openff.toolkit.utils.exceptions.ChargeMethodUnavailableError'> : Partial charge method "am1bcc"" is not supported by the Built-in toolkit. Available charge methods are ['zeros', 'formal_charge']

**Comment by swails** [comment]
Unless I'm missing something, this question doesn't have anything to do with OpenMM.  May I recommend posting to openforcefield/openff-toolkit instead?

**Comment by j-wags** [comment]
Yeah, this is a known openFF bug - https://github.com/openforcefield/openff-toolkit/issues/822. I've bumped that on our radar to make sure it actually gets fixed.

I think this issue should be closed.
