### ISSUE TITLE
compute_partial_charges_am1bcc fails

### ISSUE THREAD

**Issue by mbatgh** [openmm/openmm#3551]
molecule = Molecule.from_file(sdf_filename)
molecule.compute_partial_charges_am1bcc()

fails with the error included below (sdf attached)
Command '['antechamber ... ']' returned non-zero exit status 1.

[neu-protac-pdb-RN3.sdf.gz](https://github.com/openmm/openmm/files/8425518/neu-protac-pdb-RN3.sdf.gz)

However, if I execute antechamber directly using:
antechamber  -i neu-protac-pdb-RN3.sdf -fi sdf -o charged.mol2 -fo mol2 -pf yes -dr 1 -c bcc -nc 0.0
this finishes gracefully, and gives me file charged.mol2.

Does one of the two commands shown in the first two lines above manipulate my molecule in any way
that can cause this?
cheers
Michael

error msg:
 
 Warning: Unable to load toolkit 'OpenEye Toolkit'. The Open Force Field Toolkit does not require the OpenEye Toolkits, and can use RDKit/AmberTools instead. However, if you have a valid license for the OpenEye Toolkits, consider installing them for faster performance and additional file format support: https://docs.eyesopen.com/toolkits/python/quickstart-python/linuxosx.html OpenEye offers free Toolkit licenses for academics: https://www.eyesopen.com/academic-licensing
ligand input file:    neu-protac-pdb-RN3.sdf
json file:            neu-protac-pdb-RN3.json
xml_filename:         neu-protac-pdb-RN3.xml
sdfout_filename:      neu-protac-pdb-RN3-and-charges.sdf
load molecule
calculate AM1BCC charges and write neu-protac-pdb-RN3-and-charges.sdf
[22:30:31] UFFTYPER: Unrecognized atom type: *_ (61)
/home/micb/miniconda3/bin/wrapped_progs/antechamber: Fatal Error!
Unrecognized case-sensitive atomic symbol (    R).
Traceback (most recent call last):
  File "/home/micb/work/charge-protacs/sdf2json.py", line 53, in <module>
    molecule.compute_partial_charges_am1bcc()
  File "/home/micb/miniconda3/lib/python3.9/site-packages/openff/toolkit/topology/molecule.py", line 3584, in compute_partial_charges_am1bcc
    self.assign_partial_charges(
  File "/home/micb/miniconda3/lib/python3.9/site-packages/openff/toolkit/topology/molecule.py", line 3636, in assign_partial_charges
    toolkit_registry.call(
  File "/home/micb/miniconda3/lib/python3.9/site-packages/openff/toolkit/utils/toolkit_registry.py", line 380, in call
    raise ValueError(msg)
ValueError: No registered toolkits can provide the capability "assign_partial_charges" for args "()" and kwargs "{'molecule': Molecule with name 'RN3' and SMILES '[*][c]1[c]([H])[c]([H])[c]([C]2=[N][C@@]([H])([C]([H])([H])[C](=[O])[O][C]([H])([H])[H])[C]3=[N][N]=[C]([C]([H])([H])[H])[N]3[C]3=[C]2[C]([C]([H])([H])[H])=[C]([C](=[O])[N]([H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[N]([H])[C](=[O])[C]([H])([H])[O][c]2[c]([H])[c]([H])[c]([H])[c]4[c]2[C](=[O])[N]([C@]2([H])[C](=[O])[N]([H])[C](=[O])[C]([H])([H])[C]2([H])[H])[C]4=[O])[S]3)[c]([H])[c]1[H]', 'partial_charge_method': 'am1bcc', 'use_conformers': None, 'strict_n_conformers': False, 'normalize_partial_charges': True, '_cls': <class 'openff.toolkit.topology.molecule.Molecule'>}"
Available toolkits are: [ToolkitWrapper around The RDKit version 2022.03.1, ToolkitWrapper around AmberTools version 21.0, ToolkitWrapper around Built-in Toolkit version None]
 ToolkitWrapper around The RDKit version 2022.03.1 <class 'openff.toolkit.utils.exceptions.ChargeMethodUnavailableError'> : partial_charge_method 'am1bcc' is not available from RDKitToolkitWrapper. Available charge methods are ['mmff94'] 
 ToolkitWrapper around AmberTools version 21.0 <class 'subprocess.CalledProcessError'> : Command '['antechamber', '-i', 'molecule.sdf', '-fi', 'sdf', '-o', 'charged.mol2', '-fo', 'mol2', '-pf', 'yes', '-dr', 'n', '-c', 'bcc', '-nc', '0.0']' returned non-zero exit status 1.
 ToolkitWrapper around Built-in Toolkit version None <class 'openff.toolkit.utils.exceptions.ChargeMethodUnavailableError'> : Partial charge method "am1bcc"" is not supported by the Built-in toolkit. Available charge methods are ['zeros', 'formal_charge']

**Comment by mattwthompson** [comment]
This looks like an OpenFF Toolkit issue - mind opening this over there?

**Comment by jchodera** [comment]
Please open an issue here: https://github.com/openforcefield/openff-toolkit/issues

**Comment by peastman** [comment]
Closing this since it's an OpenFF Toolkit issue.
