### ISSUE TITLE
Measuring protocol work in CustomIntegrator appears to differ from measuring work using Context.setParameter()

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#3553]
We have been using `CustomIntegrator`s to measure the accumulation of protocol work in which we alternate (1) computing the change in potential energy for a small perturbation to a global parameter, and (2) a step of dynamics (either deterministic or stochastic). Surprisingly, we are now noticing that there is a significant difference (almost 2x) if we accumulate the change in potential energy outside of the integrator.

Here's an example set of outputs, where the first script, `integrate-setparameter.py`, updates the parameters and computes the contribution to the protocol work outside of the integrator step, while the second script, `integrate-customintegrator.py`, accumulates the contribution to the protocol work inside the `CustomIntegrator`:
```
(restraints) [chodera@lilac:281]$ python integrate-setparameter.py
Reading 281_apo_system.xml...
Reading 281_apo_state.xml...
Creating context...
Integrating from lambda = 0 -> 1 in 5000 steps...
step          0 : time      0.000 ns | lambda   0.000000000000 | protocol_work =        0.000 | RMSD =      0.00026 nm
step       1000 : time      0.004 ns | lambda   0.200000000000 | protocol_work =       -0.898 | RMSD =      0.06538 nm
step       2000 : time      0.008 ns | lambda   0.400000000000 | protocol_work =        5.807 | RMSD =      0.07630 nm
step       3000 : time      0.012 ns | lambda   0.600000000000 | protocol_work =       12.712 | RMSD =      0.08192 nm
step       4000 : time      0.016 ns | lambda   0.800000000000 | protocol_work =       15.121 | RMSD =      0.09294 nm
(restraints) [chodera@lilac:281]$ python integrate-customintegrator.py
Reading 281_apo_system.xml...
Reading 281_apo_state.xml...
Creating context...
Integrating from lambda = 0 -> 1 in 5000 steps...
step          0 : time      0.000 ns | lambda   0.000000000000 | protocol_work =        0.000 | RMSD =      0.00026 nm
step       1000 : time      0.004 ns | lambda   0.000000000000 | protocol_work =       -6.204 | RMSD =      0.06031 nm
step       2000 : time      0.008 ns | lambda   0.000000000000 | protocol_work =        7.377 | RMSD =      0.07544 nm
step       3000 : time      0.012 ns | lambda   0.000000000000 | protocol_work =       18.932 | RMSD =      0.08940 nm
step       4000 : time      0.016 ns | lambda   0.000000000000 | protocol_work =       37.202 | RMSD =      0.09893 nm
```
I'm using the nightly dev build of OpenMM, since the `System` uses `ComputedValues` for `CustomNonbondedForce`. 

Input files and scripts are in the attached ZIP file. They both use the same LangevinMiddleIntegrator core, but I see the same behavior if I use `LangevinMiddleIntegrator` as a `CustomIntegrator` in both scripts, or even a leapfrog Verlet integrator core in both scripts.
[work-discrepancy.zip](https://github.com/openmm/openmm/files/8440277/work-discrepancy.zip)

**Comment by jchodera** [comment]
This difference in behavior seems to persist for all platforms I've tried: `CUDA` (`mixed` precision, deterministic forces), `OpenCL` (`mixed` precision), and `CPU` (`OPENMM_CPU_THREADS=16`):
$ python integrate-setparameter.py
Reading 281_apo_system.xml...
Reading 281_apo_state.xml...
Creating context...
Integrating from lambda = 0 -> 1 in 5000 steps...
step          0 : time      0.000 ns | lambda   0.000200000000 | protocol_work =       -0.242 | RMSD =      0.00000 nm     
step       1000 : time      0.004 ns | lambda   0.200200000000 | protocol_work =       -1.178 | RMSD =      0.06338 nm
step       2000 : time      0.008 ns | lambda   0.400200000000 | protocol_work =        5.913 | RMSD =      0.07766 nm
step       3000 : time      0.012 ns | lambda   0.600200000000 | protocol_work =       12.265 | RMSD =      0.08658 nm
step       4000 : time      0.016 ns | lambda   0.800200000000 | protocol_work =       15.986 | RMSD =      0.09732 nm
$ python integrate-customintegrator.py     
Reading 281_apo_system.xml...
Reading 281_apo_state.xml...
Creating context...
Integrating from lambda = 0 -> 1 in 5000 steps...
step          0 : time      0.000 ns | lambda   0.000000000000 | protocol_work =        0.000 | RMSD =      0.00000 nm
step       1000 : time      0.004 ns | lambda   0.000000000000 | protocol_work =       -3.659 | RMSD =      0.06480 nm
step       2000 : time      0.008 ns | lambda   0.000000000000 | protocol_work =       18.838 | RMSD =      0.06886 nm
step       3000 : time      0.012 ns | lambda   0.000000000000 | protocol_work =       30.972 | RMSD =      0.08069 nm
step       4000 : time      0.016 ns | lambda   0.000000000000 | protocol_work =       38.457 | RMSD =      0.08257 nm
```

**Comment by jchodera** [comment]
I was worried that the half-timestep lag between velocities and positions may be partly responsible, so I tried implementing the exact same BAOAB step kernel in a `CustomIntegrator` and just moving the protocol work accumulation inside the `CustomIntegrator` or outside via `context.getState()`, and the ~2x difference in accumulated work persists. 
[kinetic-energy-discrepancy.zip](https://github.com/openmm/openmm/files/8486108/kinetic-energy-discrepancy.zip)
(This uses the same input files as above.)

Any ideas what might be going on?
Is there a way I can inspect the `CustomIntegrator` code that is generated?

**Comment by peastman** [comment]
`integrate-customintegrator.py` prints the work in units of kJ/mol.  `integrate-setparameter.py` prints it in units of kT, which in this case equals 2.494 kJ/mol.

**Comment by peastman** [comment]
Can this be closed?

**Comment by jchodera** [comment]
Thanks for catching this!
