### ISSUE TITLE
Issues with CustomNonbondedForces, Tabulated Function

### ISSUE THREAD

**Issue by yihengwuKP** [openmm/openmm#3562]
# Summary
I found a few issues related with `CustomNonbondedForces` and tabulated function:

1. `CustomNonbondedForce` doesn't have `getTabulatedFunctionParameters` method like indicated in the [documentation](http://docs.openmm.org/latest/api-python/generated/openmm.openmm.CustomNonbondedForce.html#openmm.openmm.CustomNonbondedForce). Or maybe I understood this paragraph wrong. Now I found that the thing works is the `getFunctionParameters` which should be deprecated.

> [](http://docs.openmm.org/latest/api-python/generated/openmm.openmm.CustomNonbondedForce.html#openmm.openmm.CustomNonbondedForce.getFunctionParameters)getFunctionParameters(self, index)
Get the parameters for a tabulated function that may appear in the energy expression.
>Deprecated
>This method exists only for backward compatibility. Use getTabulatedFunctionParameters() instead. If the specified function is not a Continuous1DFunction, this throws an exception.

2. in version `7.7`, calling `getTabulatedFunction` on `CustomNonbondedForce` would return a `TabulatedFunction` object rather than the subclass object like `Continuous1DFunction`, however that's the behaviour in version `7.6`. And thus the parameters can't be get by calling `getFunctionParameters` because it's only available in the subclass.

# Minimum Code Example:
## version 7.7 behaviour
```python
import openmm as mm
print(mm.__version__)
```
7.7

```python
spline = mm.CustomNonbondedForce("U(r)")
tab = mm.Continuous1DFunction([0, 1, 2, 3], 0, 1)
print(type(tab))
spline.addTabulatedFunction("U", tab)
'getTabulatedFunctionParameters' in dir(spline)
```
openmm.openmm.Continuous1DFunction
False
```python
tab1 = spline.getTabulatedFunction(0)
type(tab1)
```
openmm.openmm.TabulatedFunction
```python
'getFunctionParameters' in dir(tab1)
```
False
```python
'getFunctionParameters' in dir(tab)
```
True

```python
import openmm as mm
print(mm.__version__)
```
7.6

```python
spline = mm.CustomNonbondedForce("U(r)")
tab = mm.Continuous1DFunction([0, 1, 2, 3], 0, 1)
print(type(tab))
spline.addTabulatedFunction("U", tab)
'getTabulatedFunctionParameters' in dir(spline)
```
openmm.openmm.Continuous1DFunction
False
```python
tab1 = spline.getTabulatedFunction(0)
type(tab1)
```
openmm.openmm.Continuous1DFunction
```python
'getFunctionParameters' in dir(tab1)
```
True
```python
'getFunctionParameters' in dir(tab)
```
True

**Comment by yihengwuKP** [comment]
Btw, forgot to mension, i noticed that @peastman added support for using updateParameterInContext for tabulated function in commit 27bcb65729dcfa4284d2170999739b3ab4d29405. Just want to say thank you, it's much faster than context reinitialization.

**Comment by peastman** [comment]
It looks like this is another thing that broke from the behavior change in Doxygen 1.9.2.  Thanks!  I'll fix it.

**Comment by yihengwuKP** [comment]
Thanks!
