### ISSUE TITLE
Excluding image charges from LennardJonesForce in ForceField

### ISSUE THREAD

**Issue by bbye98** [openmm/openmm#3563]
Hello!

I am currently using a custom Langevin integrator plugin that allows me to run MD simulations with image charges for systems with perfectly conducting boundaries. My force field (`field.xml`) and topology (`config.pdb`) were generated using `packmol` and `fftool`, and the force field uses `NonbondedForce` for the Coulomb potential and `LennardJonesForce` (`CustomNonbondedForce`) for the Lennard-Jones potential. I added parameters for a graphene sheet and let OpenMM take care of populating the `TabulatedFunction` using the Lorentz-Berthelot combining rule. The `NonbondedForce` and `LennardJonesForce` sections look like:

     <NonbondedForce coulomb14scale="0.5" lj14scale="0.5">
      <UseAttributeFromResidue name="charge" />
      <Atom class="NA" sigma="0.0" epsilon="0.0" />
      <Atom class="CR" sigma="0.0" epsilon="0.0" />
      <Atom class="CW" sigma="0.0" epsilon="0.0" />
      <Atom class="CT" sigma="0.0" epsilon="0.0" />
      <Atom class="HA" sigma="0.0" epsilon="0.0" />
      <Atom class="CT" sigma="0.0" epsilon="0.0" />
      <Atom class="HA" sigma="0.0" epsilon="0.0" />
      <Atom class="HC" sigma="0.0" epsilon="0.0" />
      <Atom class="CT" sigma="0.0" epsilon="0.0" />
      <Atom class="CT" sigma="0.0" epsilon="0.0" />
      <Atom class="HC" sigma="0.0" epsilon="0.0" />
      <Atom class="CT" sigma="0.0" epsilon="0.0" />
      <Atom class="B" sigma="0.0" epsilon="0.0" />
      <Atom class="F" sigma="0.0" epsilon="0.0" />
      <Atom class="C" sigma="0.0" epsilon="0.0" />
     </NonbondedForce>
     <LennardJonesForce lj14scale="0.5">
      <Atom class="NA" sigma="0.3250" epsilon="0.71128" />
      <Atom class="CR" sigma="0.3550" epsilon="0.29288" />
      <Atom class="CW" sigma="0.3550" epsilon="0.29288" />
      <Atom class="CT" sigma="0.3500" epsilon="0.27614" />
      <Atom class="HA" sigma="0.2420" epsilon="0.12552" />
      <Atom class="CT" sigma="0.3500" epsilon="0.27614" />
      <Atom class="HA" sigma="0.2420" epsilon="0.12552" />
      <Atom class="HC" sigma="0.2500" epsilon="0.12552" />
      <Atom class="CT" sigma="0.3500" epsilon="0.27614" />
      <Atom class="CT" sigma="0.3500" epsilon="0.27614" />
      <Atom class="HC" sigma="0.2500" epsilon="0.12552" />
      <Atom class="CT" sigma="0.3500" epsilon="0.27614" />
      <Atom class="B" sigma="0.3580" epsilon="0.39750" />
      <Atom class="F" sigma="0.3120" epsilon="0.25520" />
      
      <Atom class="C" sigma="0.337" epsilon="0.232" />
      <NBFixPair class1="NA" class2="CR" sigma="0.33966896" epsilon="0.45642051" />
      <NBFixPair class1="NA" class2="CW" sigma="0.33966896" epsilon="0.45642051" />
      <NBFixPair class1="NA" class2="CT" sigma="0.33726844" epsilon="0.44318490" />
      <NBFixPair class1="NA" class2="HA" sigma="0.28044607" epsilon="0.29879737" />
      <NBFixPair class1="NA" class2="HC" sigma="0.28504386" epsilon="0.29879737" />
      <NBFixPair class1="NA" class2="B" sigma="0.34110116" epsilon="0.53172719" />
      <NBFixPair class1="NA" class2="F" sigma="0.31843367" epsilon="0.42605006" />
      <NBFixPair class1="CR" class2="CW" sigma="0.35500000" epsilon="0.29288000" />
      <NBFixPair class1="CR" class2="CT" sigma="0.35249113" epsilon="0.28438685" />
      <NBFixPair class1="CR" class2="HA" sigma="0.29310408" epsilon="0.19173497" />
      <NBFixPair class1="CR" class2="HC" sigma="0.29790938" epsilon="0.19173497" />
      <NBFixPair class1="CR" class2="B" sigma="0.35649684" epsilon="0.34120346" />
      <NBFixPair class1="CR" class2="F" sigma="0.33280625" epsilon="0.27339162" />
      <NBFixPair class1="CW" class2="CT" sigma="0.35249113" epsilon="0.28438685" />
      <NBFixPair class1="CW" class2="HA" sigma="0.29310408" epsilon="0.19173497" />
      <NBFixPair class1="CW" class2="HC" sigma="0.29790938" epsilon="0.19173497" />
      <NBFixPair class1="CW" class2="B" sigma="0.35649684" epsilon="0.34120346" />
      <NBFixPair class1="CW" class2="F" sigma="0.33280625" epsilon="0.27339162" />
      <NBFixPair class1="CT" class2="HA" sigma="0.29103264" epsilon="0.18617490" />
      <NBFixPair class1="CT" class2="HC" sigma="0.29580399" epsilon="0.18617490" />
      <NBFixPair class1="CT" class2="B" sigma="0.35397740" epsilon="0.33130899" />
      <NBFixPair class1="CT" class2="F" sigma="0.33045423" epsilon="0.26546361" />
      <NBFixPair class1="HA" class2="HC" sigma="0.24596748" epsilon="0.12552000" />
      <NBFixPair class1="HA" class2="B" sigma="0.29433994" epsilon="0.22337010" />
      <NBFixPair class1="HA" class2="F" sigma="0.27477991" epsilon="0.17897683" />
      <NBFixPair class1="HC" class2="B" sigma="0.29916551" epsilon="0.22337010" />
      <NBFixPair class1="HC" class2="F" sigma="0.27928480" epsilon="0.17897683" />
      <NBFixPair class1="B" class2="F" sigma="0.33420952" epsilon="0.31849961" />
     </LennardJonesForce>

I have to manually add the image charges one-by-one to the `NonbondedForce`, the `LennardJonesForce`, and the topology/system. The image charges should have no excluded volume interactions, so they should all have `sigma=0` and `epsilon=0`. Only their electrostatic interactions are important. Originally, I thought to exclude them from the `LennardJonesForce` using

    coul = next(f for f in system.getForces() if type(f) == openmm.NonbondedForce)
    lj = next(f for f in system.getForces() if type(f) == openmm.CustomNonbondedForce)
    chain_ic = modeller.topology.addChain()
    residue_ic = modeller.topology.addResidue("IC", chain_ic)
    for i in range(N_ATOMS_REAL):
        modeller.topology.addAtom("IC", None, residue_ic)
        coul.addParticle(-coul.getParticleParameters(i)[0], 0, 0)
        lj.addParticle(lj.getParticleParameters(i))
        system.addParticle(0)
    for i in range(N_ATOMS_REAL, lj.getNumParticles()):
        for j in range(i + 1, lj.getNumParticles()):
            lj.addExclusion(i, j)

However, my system is quite large (16,584 atoms), so the code above amounts to over 100 million exclusions. I would have to assume that this will severely impact performance. Is there an easier way to exclude/turn off all Lennard-Jones interactions for the image charges I am adding?

(I am pretty sure I cannot combine the `NonbondedForce` with the `LennardJonesForce` due to the `NBFixPair`s. However, I do suspect that the `NBFixPair`s simply apply the Lorentz-Berthelot combining rules to the `Atom` classes, but I will have to verify first. Regardless, it would be nice to know if there is a way to exclude a whole group of identity-less particles.)

Thank you in advance for any tips or feedback!

**Comment by z-gong** [comment]
`addInteractionGroup` is probably what you need.
```
lj.addInteractionGroup(set(atoms_real), set(atoms_image))
lj.addInteractionGroup(set(atoms_real), set(atoms_real))
```

**Comment by peastman** [comment]
The CustomNonbondedForce uses a pair of lookup tables called `acoef` and `bcoef` for the two coefficients:

https://github.com/openmm/openmm/blob/6fb1c8a41edff980862750bc086f6a204eb50941/wrappers/python/openmm/app/forcefield.py#L2609-L2613

You can have a particular `type` that corresponds to image charges.  In the lookup tables, set every element in that row and column to zero.
