### ISSUE TITLE
CentroidBondForce, restraints to keep molecules from moving far apart

### ISSUE THREAD

**Issue by nataliaszulc** [openmm/openmm#3564]
Hello,
I have three peptides in the system and I want to restraint the position of them relative to each other.
I used the CentroidBondForce. However, it doesn`t help, I think my energy expression doesn`t work.
What should I do to keep their arrangement similar to initial, during the simulation? 

```python
#Select proteins for adding Bond Force
protein1, protein2, protein3 = [],[],[]
for chain in pdb.topology.chains():
    residues = [res for res in chain.residues()]
    #atoms = [res.atoms() for res in residues]
    if chain.index < 8:
        for res in residues:
            for atom in res.atoms():
                protein1.append(atom.index)
    if chain.index >=8 and chain.index < 16:
        for res in residues:
            for atom in res.atoms():
                protein2.append(atom.index)
    if chain.index >=16 and chain.index < 24:
        for res in residues:
            for atom in res.atoms():
                protein3.append(atom.index)



# Addition of  CentroidBondForce, such as restraints to keep  molecules from moving  far apart
pull_force_constant = 10.0 * unit.kilocalories_per_mole / 1.0 * unit.angstroms
fx = fy = fz = -1.0 # pull in x,y,z

pullforce = omm.CustomCentroidBondForce(3,  "pull_force_constant * (x1*fx + y1*fy + z1*fz)")
pullforce.addGlobalParameter('pull_force_constant', pull_force_constant)
pullforce.addGlobalParameter('fx', fx)
pullforce.addGlobalParameter('fy', fy)
pullforce.addGlobalParameter('fz', fz)
pullforce.addGroup(protein1)
pullforce.addGroup(protein2)
pullforce.addGroup(protein3)
system.addForce(pullforce)
```

I attached also the whole script and the files:
[Openmm.zip](https://github.com/openmm/openmm/files/8459548/Openmm.zip)

**Comment by peastman** [comment]
Your expression just applies a constant force to the entire system.  It's identical for all three proteins and doesn't depend on position.  That won't do anything to keep them together.

There are a few ways you could do it, depending on exactly what you want.  Maybe you want to keep each protein from moving too far from its initial position?  In that case, something like this would work:

```python
force = CustomCentroidBondForce(1, 'k*((x1-x0)^2+(y1-y0)^2+(z1-z0)^2)')
```

You would add three bonds (one for each group), with `x0`, `y0`, and `z0` being per-bond parameters giving the initial position of each group's centroid.

Another option (more likely what you really want) would be to apply the restraint force to the distances between pairs of centroids:

```python
force = CustomCentroidBondForce(2, 'k*(distance(g1,g2)-d0)^2')
```

In that case, `d0` is a per-bond parameter giving the initial distance between two groups.  There would be three bonds, one for each pair.

Another possibility is a one-sided restraint.  You want to prevent the groups from moving too far apart, but not apply any force as long as they remain sufficiently close together.  You could do that like this:

```python
force = CustomCentroidBondForce(2, 'k*(max(0, distance(g1,g2)-d0))^2')
```

In all cases you should call `force.setUsesPeriodicBoundaryConditions(True)` to make sure periodic boundary conditions will be handled correctly.

**Comment by nataliaszulc** [comment]
Thank you very much for complex advice, it looks like the force works.
