### ISSUE TITLE
Stuck at system generation stage for large ligand

### ISSUE THREAD

**Issue by praman-nrx** [openmm/openmm#3569]
Dear developers,

I'm trying to generate a system involving a large ligand through the Forcefield.create_openmm_system function. The ligand has 107 atoms. Reading previous posts, it seems that it gets stuck in the template matching step(?). Below is a test case that should reproduce the problem. It works for a small ligand (benzene), but fails for the large one. Thanks!

from rdkit import Chem
from rdkit.Chem import AllChem
import openmm
from openmm import unit
import openff.toolkit
from openff.toolkit.typing.engines.smirnoff import ForceField
from openff.toolkit.topology import Molecule, Topology

#small ligand
#smiles = 'c1ccccc1'
#big ligand
smiles = "Cc1c2c(sc1C(=O)NCCCCCCCCNC(=O)COc3cccc4c3C(=O)N(C4=O)[C@H]5CCC(=O)NC5=O)-n6c(nnc6[C@@H](N=C2c7ccc(cc7)Cl)CC(=O)OC)C"

m = Chem.MolFromSmiles(smiles)
m=Chem.AddHs(m)
AllChem.EmbedMolecule(m)
AllChem.MMFFOptimizeMolecule(m)
with Chem.SDWriter('input.sdf') as w:
    w.write(m)

ligand_path = "input.sdf"
ligand_off_molecule = Molecule(ligand_path)
force_field = ForceField("openff_unconstrained-2.0.0.offxml")

top = ligand_off_molecule.to_topology()
ligand_system = force_field.create_openmm_system(top)

**Comment by jchodera** [comment]
Sorry you're having trouble with this! This is an [Open Force Field Toolkit](https://github.com/openforcefield/openff-toolkit) issue---can you close this issue and open a new one there?
https://github.com/openforcefield/openff-toolkit/issues

The OpenFF toolkit devs should be able to help you!

**Comment by praman-nrx** [comment]
Thanks John. Will do
