### ISSUE TITLE
The problem on whether supports Ion parameters of Li and Merz(Lennard Jones of 12-6-4) in Amber force fields by using openMM or not

### ISSUE THREAD

**Issue by Lesile-Han** [openmm/openmm#3571]
Recently, I want to use the 12-6-4 terms(developped by Li and Merz---https://ambermd.org/AmberModels_ions.php-) to deal with the Lennard-Jones interaction between ions in openMM. However I don't know that whether openMM can use the amber force fields of  12-6-4 terms or not .

**Comment by swails** [comment]
It looks like the Amber prmtop file parser in OpenMM *does* support the 12-6-4 potential.

**Comment by peastman** [comment]
That's correct.  `AmberPrmtopFile.createSystem()` should handle it correctly.

**Comment by jchodera** [comment]
Looks like this has been addressed, so closing this issue. Please reopen if further clarification is needed!
