### ISSUE TITLE
Error: specify salt concentration in `forcefield.createSystem()` while using Amber implicit solvent model in OpenMM/7.7.0

### ISSUE THREAD

**Issue by taoliu032** [openmm/openmm#3578]
Hello,

I notice that in OpenMM/7.7.0, Amber implicit solvent models can now be used when creating a forcefield and when such a forcefield object is used to create a system, salt concentration of the implicit solvent can be specified by `implicitSolventKappa`, as shown here: http://docs.openmm.org/latest/userguide/application/02_running_sims.html#implicit-solvent

So I was trying to test the feature in 7.7.0 by following the user guide. My commands are:
```
from openmm import *
from openmm.app import *
from openmm.unit import *

pdbfile = PDBFile('1aw4_DNA_openmm.pdb')
topology = pdbfile.topology

forcefield = ForceField('amber14-all.xml', 'implicit/gbn2.xml')
system = forcefield.createSystem(topology, implicitSolventKappa=1.0/nanometer)
```
The PDB file was cleaned up by PDBFixer (the file can be found [here](https://github.com/siminegroup/E2EDNA2/blob/TL-cluster-code/1aw4_DNA_openmm.pdb)). But I received a TypeError:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/taoliu/miniconda3/envs/e2edna/lib/python3.9/site-packages/openmm/app/forcefield.py", line 1376, in createSystem
    exec(script, locals())
  File "<string>", line 29, in <module>
  File "/Users/taoliu/miniconda3/envs/e2edna/lib/python3.9/site-packages/openmm/app/internal/customgbforces.py", line 748, in finalize
    self._addEnergyTerms()
  File "/Users/taoliu/miniconda3/envs/e2edna/lib/python3.9/site-packages/openmm/app/internal/customgbforces.py", line 957, in _addEnergyTerms
    _createEnergyTerms(self, self.solventDielectric, self.soluteDielectric, self.SA, self.cutoff, self.kappa, self.OFFSET)
  File "/Users/taoliu/miniconda3/envs/e2edna/lib/python3.9/site-packages/openmm/app/internal/customgbforces.py", line 360, in _createEnergyTerms
    params = "; solventDielectric=%.16g; soluteDielectric=%.16g; kappa=%.16g; offset=%.16g" % (solventDielectric, soluteDielectric, kappa, offset)
TypeError: Quantity.__float__ returned non-float (type Quantity)
```
The TypeError is gone if I remove the `implicitSolventKappa` argument. 

I am wondering if anyone could help me with this problem? As always, thank you very much!

PS: This is an exciting feature in 7.7.0 to me because in previous OpenMM versions, it seems one can only specify salt concentration of an Amber implicit solvent model by `prmtop.createSystem()`, such as this [example](http://docs.openmm.org/7.6.0/userguide/application/02_running_sims.html#amber-implicit-solvent) I have been following in OpenMM/7.6.0 where I have to call Ambertools first to generate prmtop file.

**Comment by peastman** [comment]
Looks like it's failing to strip the units.  I'll fix that.  In the mean time, the workaround is just to leave off the units: `implicitSolventKappa=1.0`.  It will be assumed to be in inverse nanometers (following the standard OpenMM unit system).

**Comment by taoliu032** [comment]
Thank you very much. The solution you suggested worked!
