### ISSUE TITLE
Issue simulating silver in OpenMM

### ISSUE THREAD

**Issue by cadalyjr** [openmm/openmm#3581]
Hello all,

I'm trying to run a simulation of a silver slab with OpenMM and am having some difficulty. I am modeling the silver atoms as simple Lennard-Jones spheres as in CHARMM. My force field file is pretty short:

```
<ForceField>
 <AtomTypes>
  <Type name="Ag" class="Ag" element="Ag" mass="107.87000"/>
  <Type name="Agp" class="Agp" element="Ag" mass="107.87000"/>
 </AtomTypes>
 <Residues>
  <Residue name="IAG">
   <Atom charge="0.0" name="AG" type="Ag"/>
  </Residue>
  <Residue name="AGP">
   <Atom charge="1.0" name="AP" type="Agp"/>
  </Residue>
 </Residues>
 <NonbondedForce coulomb14scale="1.0" lj14scale="1.0">
   <UseAttributeFromResidue name="charge"/>	
   <Atom type="Ag" sigma="0.263261" epsilon="19.079"/>
   <Atom type="Agp" sigma="0.216364" epsilon="1.2008"/>
 </NonbondedForce>
</ForceField>
```

In my simulation there are only silver atoms, no water or any biomolecules. I keep getting the error:

`ValueError: No template found for residue 1 (IAG).  This might mean your input topology is missing some atoms or bonds, or possibly that you are using the wrong force field.`

Normally, my fix for this sort of thing is to create a residue template file which lists the bonding. It looks a bit weird, since there are no bonds:

```
<Residues>
<Residue name="IAG">
  <Atom name="AG" type="Ag"/>
</Residue>
<Residue name="AGP">
  <Atom name="AP" type="Agp"/>
</Residue>
</Residues>

```

And then include this using code like:

```
from openmm import app
import openmm as mm

app.topology.Topology.loadBondDefinitions('silver_temp.xml')

pdb = app.PDBFile('test.pdb')
forcefield = app.ForceField('silver.xml')

```

A minimal PDB structure which might work to test this would look like:

```
REMARK   1 CREATED WITH OPENMM 7.6, 2022-04-19
HETATM    1 Ag   IAG A   1     -51.075 -51.075 -14.301  1.00  0.00          EP  
HETATM    2 AG   IAG A   2     -51.075 -49.032 -12.258  1.00  0.00          EP  
HETATM    3 AG   IAG A   3     -49.032 -51.075 -12.258  1.00  0.00          EP  
HETATM    4 AG   IAG A   4     -49.032 -49.032 -14.301  1.00  0.00          EP  
HETATM    5 AG   IAG A   5     -51.075 -46.989 -14.301  1.00  0.00          EP  
HETATM    6 AG   IAG A   6     -51.075 -44.946 -12.258  1.00  0.00          EP  
HETATM    7 AG   IAG A   7     -49.032 -46.989 -12.258  1.00  0.00          EP  
HETATM    8 AG   IAG A   8     -49.032 -44.946 -14.301  1.00  0.00          EP  
HETATM    9 AG   IAG A   9     -51.075 -42.903 -14.301  1.00  0.00          EP
TER   10         IAG A9
END
```

Looking at the underlying code for the ForceField object, it seems like my residue template idea was a bad one since a lot of what the residue templates do is clarify for OpenMM which atoms are bonded to each other - if there are no bonds, there's nothing to do. But, what can I do to get my simulation to actually run? Please let me know if there's any more information I can supply, and thank you in advance for your time!

**Comment by peastman** [comment]
The problem is the `EP` in the element column of the PDB file.  That's used to indicate an "extra particle", one that doesn't correspond to a real atom.  You want to put `Ag` there instead.

The next problem you'll have is that both templates match the residues.  All it knows is that each residue consists of a single silver atom with no bonds.  Should it match the IAG template and assign atom type Ag, or match the AGP template and assign atom type Agp?  It has no way to know.  You can resolve this by using the `residueTemplates` argument to `createSystem()` to tell it which to use for each residue.

**Comment by cadalyjr** [comment]
Is there an example of using the residueTemplates argument that you can point me to? The documentation is a bit unclear, or I'm a bit dumb :D.

**Comment by peastman** [comment]
Suppose you want it to use `IAG` for every residue.  You could do this:

```python
residueTemplates = {}
for res in topology.residues():
    residueTemplates[res] = 'IAG'
```

Or maybe you're using the residue name in the PDB file to specify which template you want.  Your example above calls every residue "IAG", but maybe your real PDB file will call some of them "AGP".  In that case you could do this:

```python
residueTemplates = {}
for res in topology.residues():
    residueTemplates[res] = res.name
```

Then include `residueTemplates=residueTemplates` as an argument to `createSystem()`.

**Comment by peastman** [comment]
Can this issue be closed?

**Comment by cadalyjr** [comment]
Yes, thank you!

**Comment by SgonzalezHaverford** [comment]
Thank you for your help on our issue it was appreciated! We used the residueTemplates code you provided but there has been another error that we keep getting. 

```
Traceback (most recent call last):
  File "template.py", line 16, in <module>
    system = forcefield.createSystem(pdb.topology,
  File "/homes/sgonzalez/anaconda3/envs/openmm/lib/python3.8/site-packages/openmm/app/forcefield.py", line 1212, in createSystem
    templateForResidue = self._matchAllResiduesToTemplates(data, topology, residueTemplates, ignoreExternalBonds)
  File "/homes/sgonzalez/anaconda3/envs/openmm/lib/python3.8/site-packages/openmm/app/forcefield.py", line 1392, in _matchAllResiduesToTemplates
    raise Exception('User-supplied template %s does not match the residue %d (%s)' % (tname, res.index+1, res.name))
Exception: User-supplied template IAG does not match the residue 1 (IAG)
```

How do we get the IAG templates to match? Or what might be a reason we keep getting this error?

**Comment by SgonzalezHaverford** [comment]
I realized I forgot to insert the code I used to run the simulation. When I got the error I ran this code. 

```
`app.topology.Topology.loadBondDefinitions('silver_temp.xml')

pdb = app.PDBFile('charmm-gui-4857443827/step1_nanomaterial.pdb')
forcefield = app.ForceField('silver.xml')

residueTemplates = {}
for res in pdb.topology.residues():
    residueTemplates[res] = 'IAG'
pdb.topology.setUnitCellDimensions([100*unit.angstroms, 100*unit.angstroms, 25*unit.angstroms])
system = forcefield.createSystem(pdb.topology,
                                 nonbondedMethod=app.PME,
                                 nonbondedCutoff=1*unit.angstroms,
                                 constraints=app.HBonds,
                                 residueTemplates=residueTemplates)`
```
Could there be any issues within the code to not allow the residue templates to match?
