### ISSUE TITLE
no template found for residue/ coordinate "..." could not be represented in a width-8 field

### ISSUE THREAD

**Issue by ixy90** [openmm/openmm#3582]
Hi! I am trying to run a simulation with openMM, and I cant get it to run. The file is already preprocessed with OpenMMSetup, and then a ligand is added to it with MoE. This is the file (.txt ending is only there so that github would upload it): 
[5wyz-processed_with_lig3.pdb.txt](https://github.com/openmm/openmm/files/8550462/5wyz-processed_with_lig3.pdb.txt)

And this is my code until the error:

```
from openmm.app import *
from openmm import *
from openmm.unit import *
from sys import stdout
from openff.toolkit.topology import Molecule
from openmmforcefields.generators import SMIRNOFFTemplateGenerator
from openmm.app import ForceField

molecule = Molecule.from_smiles('FC(F)(F)c1nc(NCc2ccc(CO)cc2)nc(NCCc2ccc(CO)cc2)c1')
smirnoff = SMIRNOFFTemplateGenerator(molecules=molecule)
forcefield = ForceField('amber/protein.ff14SB.xml', 'amber/tip3p_standard.xml', 'amber/tip3p_HFE_multivalent.xml')
forcefield.registerTemplateGenerator(smirnoff.generator)
pdbfile = PDBFile('5wyz-processed_with_lig3.pdb')
system = forcefield.createSystem(pdbfile.topology)
```
The error here is:
Did not recognize residue *; did you forget to call .add_molecules() to add it?

Then, because previously I had warnings about having duplicate atoms and found something on that in issue #2103  , I tried to rename the atoms, so my new file looked like this (the altering is done to the atoms of the ligand which is to be found at the very bottom of the file):

[5wyz-processed_with_lig3_altered.pdb.txt](https://github.com/openmm/openmm/files/8550467/5wyz-processed_with_lig3_altered.pdb.txt)

With this, I got my code running for a few more lines (I know, the step size is too small, but this was just for quick trying):

```
integrator = LangevinIntegrator(300*kelvin, 1/picosecond, 0.004*picoseconds)
simulation = Simulation(pdbfile.topology, system, integrator)
simulation.context.setPositions(pdbfile.positions)
simulation.minimizeEnergy()
simulation.reporters.append(PDBReporter('output.pdb', 100))
simulation.reporters.append(StateDataReporter(stdout, 100, step=True,
        potentialEnergy=True, temperature=True))
simulation.step(1000)
```

Now, however, I get the error:

ValueError: coordinate "-1020036160.0" could not be represented in a width-8 field

My question, finally, is: what does this error mean?? I did not find anything like that with google. And, is it maybe connected to my alterations of the file?

Any thoughts and input are highly appreciated!

**Comment by peastman** [comment]
> ValueError: coordinate "-1020036160.0" could not be represented in a width-8 field

That means your simulation has blown up.  The coordinates have turned into huge values.  The [FAQ](https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#nan) describes some things that can cause simulations to blow up and gives advice on how to debug it.

One problem I notice from your code is that your time step is probably too large.  You use 4 fs.  To use that large a time step, you generally need to constrain the lengths of all bonds involving hydrogen.  Either decrease the time step, or add the argument `constraints=HBonds` to `createSystem()`.

**Comment by ixy90** [comment]
@peastman Thank you very much, that helped!!
