### ISSUE TITLE
Anisotropic diffusion

### ISSUE THREAD

**Issue by Dingel321** [openmm/openmm#3583]
Hi everybody,

I'm simulating a very very simple system in openMM. It is just a single particle in 2d with a custom external potential. 
I was wondering if it is possible to have different diffusion coefficients along the x and y directions?
For example, I had the question of whether there is a setting in the `BAOBAIntegrator` to have different diffusion coefficients for the different directions.

**Comment by Dingel321** [comment]
That's perfect! But normally I simulate multiple non-interacting particles and then I would like to set the effective masses along the x and y directions differently for each particle that is simulated. So is there a way to set new per-DOF variables differently for each particle in the system?

**Comment by peastman** [comment]
That's exactly what a per-DOF variable is.  You specify a Vec3 for each particle.  See the API docs.
