### ISSUE TITLE
Problem with box size in DCD file

### ISSUE THREAD

**Issue by nataliaszulc** [openmm/openmm#3586]
Hello,
I run simulation, and now I want to use wrap (VMD or MDanalysis)  to center protein in the box. Both programs can't read the box size from DCD file obtained from OpenMM7.7.  Is OpenMM saving this information in the DCD file?
How can I solve that problem?

Below I pasted the fragment of code:
```python
saving_frequency = 25000
dcdreporter = DCDReporter('traj'+'.dcd', saving_frequency, enforcePeriodicBox=True)
simulation.reporters.append(dcdreporter)
simulation.reporters.append(StateDataReporter(stdout, 5000, step=True,
                                              potentialEnergy=True, temperature=True))
simulation.reporters.append(StateDataReporter(dirName+'/scalarsm'+'.csv', saving_frequency, 
                                              time=True, potentialEnergy=True, temperature=True, 
                                              volume=True, density=True, speed=True))
```

I also attached full script.
[openmm_trimers_water_ions.zip](https://github.com/openmm/openmm/files/8566950/openmm_trimers_water_ions.zip)

**Comment by peastman** [comment]
This might be related to #3507?

Try using MDTraj.  I'm pretty sure it will read it correctly.

**Comment by DanielWicz** [comment]
@peastman 

I think she wanted to ask if default DCDReporter saves box information. Because neither VMD nor MDanalysis can't read box info from the Openmm's DCD trajectory

**Comment by nataliaszulc** [comment]
I can try using MDTraj, but it doesn't have **wrap** function which I need.

**Comment by peastman** [comment]
It saves box information if you're simulating a periodic system, that is, if `topology.getUnitCellDimensions()` does not return `None`.

The function you're looking for in MDTraj is `Trajectory.image_molecules()`.

**Comment by nataliaszulc** [comment]
Thanks it worked.

**Comment by peastman** [comment]
Did you intend to reopen this?

**Comment by nataliaszulc** [comment]
Yes, I want to reopen. I still have this problem with all my dcd files. Under unknown circumstances there is no PBC vectors in the dcd files. Please could you look at my script, all files.  
[trimer.zip](https://github.com/openmm/openmm/files/8589334/trimer.zip)

**Comment by DanielWicz** [comment]
> Yes, I want to reopen. I still have this problem with all my dcd files. Under unknown circumstances there is no PBC vectors in the dcd files. Please could you look at my script, all files. [trimer.zip](https://github.com/openmm/openmm/files/8589334/trimer.zip)

When I run the script and open in VMD then type `pbc unwrap` I get something like this:
![image](https://user-images.githubusercontent.com/37775482/165914906-5dff8eb0-349d-4b96-bf71-ef4e421b6fea.png)
plus VMD hangs indefinitely, which was never the case before. Nevertheless, I couldn't spot anything, which would cause the problem. 

Usually DCD trajectories from OpenMM work fine in VMD, even with `pbc unwrap`. I have like several of them and they work fine

**Comment by nataliaszulc** [comment]
So I solved the problem by changing the topology  variable into psf.topology, instead of pdb.topology in  Simulation function.
