### ISSUE TITLE
Error finding top_all36_prot.rtf with readTopologyFile

### ISSUE THREAD

**Issue by kong1-731** [openmm/openmm#3587]
I created a membrane system with the CHARMM GUI membrane builder and downloaded the associated OpenMM files. When I try to run the first equilibration step, I keep getting an error that it cannot locate the "top_all36_prot.rtf" file even though I can see it in the toppar folder inside my miniconda installation. I can't figure out where "../toppar/" is pointing to...whether it is inside the miniconda3 folder or inside the folder with my equilibration scripts. I appreciate any direction with this error.

Error message:
  
```

File "/home/name/miniconda3/envs/py37/lib/python3.7/site-packages/openmm/app/charmmparameterset.py", line 596, in readTopologyFile
    f = CharmmFile(tfile)
  File "/home/name/miniconda3/envs/py37/lib/python3.7/site-packages/openmm/app/internal/charmm/_charmmfile.py", line 64, in __init__
    raise CharmmFileError(str(e))
openmm.app.internal.charmm.exceptions.CharmmFileError: [Errno 2] No such file or directory: '../toppar/top_all36_prot.rtf'
```

**Comment by peastman** [comment]
Your script is looking for a file with the path `../toppar/top_all36_prot.rtf` relative to  your current directory.  Whatever directory you're in when you run the script, it looks up one level and expects to find a `toppar` subdirectory there.

**Comment by kong1-731** [comment]
Thank you!

**Comment by kong1-731** [comment]
I am currently trying to run OpenMM on a HPC system (Sherlock) where I don't really know exactly where the directories are inside OpenMM. Therefore, how should I fix this problem with not knowing where the toppar file is? Is there a way for me to change how read_params is working?
