### ISSUE TITLE
Github actions are broken

### ISSUE THREAD

**Issue by jlmaccal** [openmm/openmm#3591]
The github actions CI steps are broken due to nvidia updating public keys. We're facing the same issue with MELD, as we've largely copied the CI setup from openmm.

NVIDIA has posted steps to fix this issue, but they don't seem to be working. One possible issue is that there seems to be a mismatch in some packages. The `CI.yml` specifies `ubuntu-latest`, which I assume is `20.04`. However, the `install_cuda.sh` script is hard-coded to point to `18.04` repositories.

**Comment by peastman** [comment]
Thanks!  Do you have a link to NVIDIA's post?

**Comment by jlmaccal** [comment]
I think this is the announcement. You can also find a number of threads where people are having problems.

https://forums.developer.nvidia.com/t/notice-cuda-linux-repository-key-rotation/212772
