### ISSUE TITLE
Torsion issues in alchemical system

### ISSUE THREAD

**Issue by adw62** [openmm/openmm#3592]
Hello,

I have built an alchemical system which I can run with OpenMM < 7.4.2 however for more recent versions the system nans. Removing forces has shown me the torsions are causing the nan and I have committed a similar mistake in the past https://github.com/openmm/openmm/issues/2959. My solution in the previous case was to slightly shift some of my alchemical atoms to resolve the undefined torsion forces but that fix does not work here. And more confusing is the version dependence of the problem. I have attached xmls of the system from OpenMM 7.7.0 which nans and OpenMM 7.4.0 which is okay as well as a zip of the pdb and prmtop files I use:

OpenMM 7.7:
[system77.txt](https://github.com/openmm/openmm/files/8624817/system77.txt)
OpenMM 7.4
[system74.txt](https://github.com/openmm/openmm/files/8624819/system74.txt)
input files:
[build.zip](https://github.com/openmm/openmm/files/8624821/build.zip)

Any insight on what I'm doing wrong would be appreciated. I also appreciate my example might not be so clear, if a minimal example would help let me know and I'll try and make one.

Cheers,
Alex

**Comment by adw62** [comment]
Okay I think I solved it. It's the same issue I had before but a stronger version of it. There are nonphysical torsions in the input which straddle the alchemical region. In 7.4.2 I can turn these off using OpenMMTools by zeroing k for these torsions. However, In 7.7.0 this does not work and the simulation blows up. The solution is to rebuild the torsion force leaving out the nonphysical torsions then everything works fine.

Thanks,
Alex

**Comment by jchodera** [comment]
> Okay I think I solved it. It's the same issue I had before but a stronger version of it. There are nonphysical torsions in the input which straddle the alchemical region. In 7.4.2 I can turn these off using OpenMMTools by zeroing k for these torsions. However, In 7.7.0 this does not work and the simulation blows up. The solution is to rebuild the torsion force leaving out the nonphysical torsions then everything works fine.

@adw62 : Can you elaborate on the difference between 7.4.2 and 7.7.0 and why you can only turn off the torsions in 7.4.2? I'm trying to understand if there is something we can fix here in OpenMM or openmmtools to eliminate this issue.
