### ISSUE TITLE
Accessing c++ code generated while using CUDA

### ISSUE THREAD

**Issue by ansingh1214** [openmm/openmm#3597]
Is there a way to print out/access the C++ code that is compiled in real time while running a simulation on CUDA?

**Comment by peastman** [comment]
If you compile OpenMM from source, you can hack the code to print it out.  Kernels are compiled in `CudaContext::createModule()`.  The source code gets assembled in the variable `src`.  Immediately after the line

https://github.com/openmm/openmm/blob/e9b8b6a2b4c1130c06e2d7c83a9e33a0640b7e3b/platforms/cuda/src/CudaContext.cpp#L554

add this

```
print("%s\n", src.str().c_str());
```

**Comment by ansingh1214** [comment]
Thanks a lot for the prompt response! 
While printing out the file, I realized that the generated CUDA code did not contain any information about addComputeGlobal that I had added to a CustomIntegrator. Are the globals not computed at each timestep by the CUDA kernel?

**Comment by peastman** [comment]
No, global computations are done on the CPU.

https://github.com/openmm/openmm/blob/e9b8b6a2b4c1130c06e2d7c83a9e33a0640b7e3b/platforms/common/src/CommonKernels.cpp#L7360-L7365

**Comment by ansingh1214** [comment]
Ok great thanks! One final question - is there any way in which we can modify the c++ kernel that is printed out and run it ourselves? I'm planning to do path sampling that uses an external force, defined by a large basis on time and the coordinates, and doing it via the custom integrator slows down the computation by a factor of 20 (on a A100 GPU). I am assuming the slowdown arises from multiple computeGlobals and the fact that I have to sum over the basis at each step. I can send my code/paper for implementation of the method if required.

**Comment by peastman** [comment]
If you want to define your own kernels directly, you need to write a plugin.  See [the developer guide](http://docs.openmm.org/latest/developerguide/) for information about doing that.  First though, make sure you really understand the bottlenecks in your current implementation.  When you profile code, you often find out it's totally different from what you thought it was.

Can you post the code for your custom force and integrator?

**Comment by ansingh1214** [comment]
I've personally met with @jchodera about the implementation of this method. The idea is to use some nonconservative force to compute the rate of nucleation of 2D active brownian particles (https://github.com/ansingh1214/OpenMM-Active-Systems).
There are some inefficiencies Openmm(such as the constant dimensionality of positions and perDofVariables), yet the implementation seems to be the most straightforward compared to other MD packages.
The code for the integrator is given below. 
```python
#Using external forces to evaluate nucleation of 
#active brownian particles (ABP) using Variational Path Sampling.
#https://journals.aps.org/prl/pdf/10.1103/PhysRevLett.128.028005

#Each ABP has 3 degrees of freedom -
#x,y and theta
#where theta defines an 'angle of propulsion'

#To implement this, following modifications are
#applied to the position and velocity matrix:
#The z coordinate is kept invariant: pos = (x,y,0) 
#The velocity coordinate holds the x and y
#components of the propulsion: vel = (cos(theta),sin(theta),0)

#ABPs constitute one of the simplest systems
#that are intrinsically driven out of equilbirium
#Link for a simple implementation in OpenMM -
#https://github.com/ansingh1214/OpenMM-Active-Systems

#nb_t = total gaussian basis sets in time
#nb_phi= total gaussian basis sets on density
#t_m[nb_t]= centers of the gaussian basis sets on time
#phi_m[nb_phi]= centers of the gaussian basis sets on density
#c[nb_phi][nb_t] = coefficients corresponding to each basis set
#v0  = propulsion speed
#Dr  = Rotational Diffusion constant
def MIPS_VPS(nb_t,nb_phi,t_m,phi_m, c,
            temperature=1,v0=1,D=1, Dr=2.448577,timestep=1e-6,
            sigma=2,deff=1.10688,xm=81.049,ym=40.52470, tf=.4,N=4096):
    
    integrator = CustomIntegrator(timestep)
    integrator.addGlobalVariable("pi",3.14159265359)
    integrator.addGlobalVariable("D",D)
    integrator.addGlobalVariable("Dr",Dr)
    integrator.addGlobalVariable("v0",v0)
    integrator.addGlobalVariable("t",0)
    integrator.addGlobalVariable("U",0)
    integrator.addGlobalVariable("dU",0)
    integrator.addGlobalVariable("xm",xm)
    integrator.addGlobalVariable("ym",ym)
    integrator.addGlobalVariable("tf",tf)
    integrator.addGlobalVariable("n",N)
    integrator.addPerDofVariable("dxy",0)
    integrator.addPerDofVariable("rand",0)
    integrator.addPerDofVariable("phi_step",0)
    integrator.addPerDofVariable("dtheta",0)
    integrator.addPerDofVariable("randxy",0)
    integrator.addPerDofVariable("phi",0)
    integrator.addPerDofVariable("dUi",0)
    integrator.addPerDofVariable("r",0)
    integrator.addPerDofVariable("psi",0)
    integrator.addPerDofVariable("diff",0)

    #VPS Implementation

    #Time basis sets
    #Holds the name of basis sets on time
    basisStr_t   = [] 
    #Holds the expression for time basis sets
    expr_t       = "exp(-({:.6f}-t)^2/(2*0.0025))/sqrt(2*pi*0.0025)"

    #Density basis sets

    #Holds the expression for basis sets on density
    expr_phi     = "exp(-({:.3f}-phi)^2/(2*0.0036))/sqrt(2*pi*0.0036)"
    #Holds the name of basis sets
    basisStr     = []
    #Holds the name of "Mallevin weights" for each coefficient
    mwStr        = []
    #Holds the name of the change in Mallevin weights for each coefficient
    dmwStr       = []
    #Holds the name of the gradient of the reward in w.r.t. coefficients
    gradStr      = []
    #Holds the total external force
    integrator.addPerDofVariable("fsum",0)

    for i in range(nb_t):
        basisStr_t.append("bast{:d}".format(i))
        integrator.addGlobalVariable(basisStr_t[i],0)

    for i in range(nb_phi):
        basisStr.append([])
        mwStr.append([])
        dmwStr.append([])
        gradStr.append([])
        for j in range(nb_t):
            basisStr[i].append(expr_phi.format(i) + " * " + basisStr_t[j])
            mwStr[i].append("ym_{:d}_{:d}".format(i,j))
            dmwStr[i].append("dym_{:d}_{:d}".format(i,j))
            gradStr[i].append("grad_{:d}_{:d}".format(i,j))
            integrator.addGlobalVariable(mwStr[i][j],0)
            integrator.addGlobalVariable(gradStr[i][j],0)
            integrator.addGlobalVariable(dmwStr[i][j],0)

    
    #Per step computation for Active Brownian Particles in 2D
    integrator.addUpdateContextState()
    integrator.addComputePerDof("rand","gaussian")
    #Enforcing that the z-coordinates remain unchanged
    integrator.addComputePerDof("randxy","rand * vector(1,1,0)")
    
    #f1 corresponds to the gaussian approximated density around
    #each particle. This is done using a nonconservative custom
    #nonbonded force. (https://github.com/ansingh1214/openmm-nonconservative)
    #The idea is to apply a force on ABPs proportional to the 
    #density around them
    #phi corresponds to the 'packing fraction' around an ABP
    integrator.addComputePerDof("phi","(f1+1)/({:.5f} * sqrt(2*{:.5f}))^2  * {:.5f}"
                            .format(sigma, np.pi, np.pi*(deff/2)**2))
    #n is a rough estimate of the cluster size around a particle
    integrator.addComputePerDof("phi_step", "step(phi-0.55)")
    integrator.addComputeSum("n","phi_step/3")

    #Computes the angle between the propulsion vector of the particle
    #and the vector towards the particle with the highest density

    integrator.addComputePerDof("diff","atan2(ym - _y(x),xm - _x(x) ) - atan2(_y(v), _x(v))")
    integrator.addComputePerDof("diff","sin(diff)")
    integrator.addComputePerDof("r","sqrt((_x(x)-xm)^2 + (_y(x)-ym)^2)*vector(1,1,0)")

    #Compute the value of basis on t
    for i in range(nb_t):
        integrator.addComputePerDof(basisStr_t[i],expr_t.format(i))

    #Compute the total external force
    fsum = ""
    for i in range(nb_phi):
        for j in range(nb_t):
            if not(i == nb_phi - 1 and j == nb_t - 1):
                fsum += str(c[i][j]) +" * " + basisStr[i][j] + " + "
            else:
                fsum += str(c[i][j]) +" * " + basisStr[i][j]
    integrator.addComputePerDof("fsum",fsum)
    #psi*fsum is the total external force
    integrator.addComputePerDof("psi","3*Dr*step(170-n)*diff/(1+exp(20*(r-15)))")
    integrator.addComputePerDof("dtheta","_z(rand) * sqrt(2*Dr*dt) + psi*dt*fsum")
    integrator.addComputePerDof("v","vector(_x(v)*cos(_x(dtheta)) - _y(v)*sin(_x(dtheta))," + 
                                           "_y(v)*cos(_x(dtheta)) + _x(v)*sin(_x(dtheta)),0)")
    integrator.addComputePerDof("dxy","dt*(v0*v+(f0)/m) + randxy * sqrt(2*D*dt)")
    integrator.addComputePerDof("x","x+dxy")
    #U corresponds to the KL-Divergence between the driven trajectory and the
    #undriven trajectory
    integrator.addComputePerDof("dUi", "-dt*((fsum*psi)^2 - 2*(fsum*psi)*dtheta/dt)*vector(1,0,0)")
    integrator.addComputeSum("dU", "dUi/(4*Dr)")
    integrator.addComputeGlobal("U","U + dU")
    integrator.addComputeGlobal("t","t + dt")

    #Compute gradient and mallevin weights for each coefficient
    for i in range(nb_phi):
        for j in range(nb_t):
            integrator.addComputeSum(dmwStr[i][j],\
                                     "_z(rand)*sqrt(2*dt/Dr) *" +\
                                      basisStr[i][j] +\
                                      "*psi/(Dr*2)*vector(1,0,0)")
            integrator.addComputeGlobal(mwStr[i][j],mwStr[i][j] + \
                                      " + " + dmwStr[i][j])
            integrator.addComputeGlobal(gradStr[i][j], gradStr[i][j]  + \
                                      " + " + mwStr[i][j] +"*dU")
    return integrator
```
On benchmarking the code, I found that the biggest bottleneck is the last few lines of the code, where I compute the "Mallevin weights" and gradients for each coefficient. The multiple ComputeSums are slowing down the code.
I have thought about the right way to approach this for a while, and have 2 directions to proceed:

- Figure out a way to define "global arrays" like positions/velocities/forces, and then pass them to a modified CustomGB force. In this case if I could pass the random gaussian numbers and the action to the Force kernel as arguments, I could compute the Mallevin weights and gradients while computing the force.
- Modify the computeSum in a way in which I can compute all the mallevin weights and gradients in one simple loop over the particles. Perhaps, a way to do this would be to define GlobalArray (like GlobalVariables). Also, I am not sure if the computeSums are done using the CPU or CUDA - if its the latter I wonder if I could somehow modify the .cu files in the CUDA kernels.

For reference, the code for running the simulation is given below
```python
deff    = 1.10688
phi     = 0.29
N       = 4096
eps     = 100
Pe      = 100
D0      = 1
dt      = 2e-6
Dr      = 3*D0 / (deff)**2
A       = N*np.pi*(deff/2)**2 / phi
Lx      = 2*np.sqrt(A/2)
Ly      = np.sqrt(A/2)
tf      = int(4e5)
a       = np.array([Lx,0.0,0.0])
b       = np.array([0.0,Ly,0.0])
c       = np.array([0.0,0.0,100.0])
box     = np.array([Lx,Ly,10,90,90,90])
system  = System()
config  = extractConf(box)
x0      = config[:,:3]
v0      = config[:,3:]
cut     = 2**(1/6)
n0      = largestCluster(x0, box, cut)
center  = periodicCOM(x0[n0], box)
x0      = CAW(x0, center, box)
n0      = np.sum(n0)
system.setDefaultPeriodicBoxVectors(a,b,c)
for i in range(N):
    system.addParticle(1)
#WCA force
energy_expression = '4.0*{:.1f}*((1/r)^12 - (1/r)^6+1/4)'.format(eps)
force             = CustomNonbondedForce(energy_expression)
for i in range(N):
    force.addParticle([])
force.setNonbondedMethod(CustomNonbondedForce.CutoffPeriodic)
force.setCutoffDistance(cut) 
system.addForce(force)
#Nonconservative 'force' phi which computes the density around a particle
phi_expression = ('exp(-r^2 / (2*{:.5f}^2)) ').format(sigma)
lamb           = CustomNonbondedForce(phi_expression)
#setNC() was added in this modification
#https://github.com/ansingh1214/openmm-nonconservative
lamb.setNC()
lamb.setNonbondedMethod(CustomNonbondedForce.CutoffPeriodic)
lamb.setCutoffDistance(4*3)
for i in range(N):
    lamb.addParticle([])
lamb.setForceGroup(1)
system.addForce(lamb)
platform   = openmm.Platform.getPlatformByName("CUDA")
integrator = MIPS_VPS(nb_t,nb_phi,t_m,phi_m,coeffs,
	      timestep=dt,D=1,v0=Pe,Dr=Dr,
	      tf=tf*dt,sigma=sigma)
context    = Context(system,integrator,platform)
context.setPositions(x0)
context.setVelocities(v0)
integrator.step(tf)
nf = np.sum(largestCluster(np.array(state.getPositions()._value), 
box, cut))
if nf > 200:
    dat[1] = 1
for i in range(nb_t):
    dat[2+i] = integrator.getGlobalVariableByName("grad_t{:d}".format(i))\
    + dat[1]*s*integrator.getGlobalVariableByName("ym_t{:d}".format(i))
    for i in range(nb_phi):
    dat[2+nb_t+i] = integrator.getGlobalVariableByName("grad_phi{:d}".format(i))\
    + dat[1]*s*integrator.getGlobalVariableByName("ym_phi{:d}".format(i))

```

**Comment by peastman** [comment]
What are the values of `nb_t` and `nb_phi`?

I can certainly see why computing all those sums could be slow.  Each one executes a trivial kernel to compute a value for each particle.  Then it executes another kernel to sum it over all particles, and then it has to transfer the result back to the host (which flushes the execution queue and creates a bubble where the GPU is idle) before it can execute the next operation.  I would want to see a profile before definitely concluding that's the problem, but it does make sense.

I think something's missing from the code: what are the `dmwStr[i][j]`, `mwStr[i][j]`, and `gradStr[i][j]` values used for?  The integrator computes them but doesn't use them.  Neither does the custom force.  Do you just copy them out for later use?  Is it necessary to compute them every time step?

**Comment by ansingh1214** [comment]
For now I've been using 8x4 basis sets, but for actual convergence, we might need to increase it to 25x25. The interesting part is that there is a < 10% slowdown when I increase the basis sets from 8x4 to 25x25, if I just compute the forces (and comment out the computation of dmw,mw and grad). However including those compute sums reduces the performance by > 300 times (I go from 3200 iterations/s to 10 iterations/s).
I'm not sure how to profile the code properly, but I can do so if you can point to an example/code.

dmw, and mw are used to compute the gradients, and the gradients are used to update the coefficients c[i][j] for the next step of optimization. Basically we're performing gradient descent to find the lowest KL-divergence force that makes the ABPs nucleate, and the construction of the algorithm requires us to compute them at each timestep.

It'd be nice if there was a way to cheese the ComputeSums by either modifying the .cu files, modifying the runtime c++ file or by making a custom compute sums, which could take in a list of global variables and expressions and evaluate them at the same time.

**Comment by peastman** [comment]
> dmw, and mw are used to compute the gradients, and the gradients are used to update the coefficients c[i][j] for the next step of optimization.

I don't understand.  The `c[i][j]` values are hardcoded into the expression.  Once you create the integrator, they never change.

It sounds like a plugin is probably the best solution for what you want to do.  With custom kernels, you can compute all the coefficients at once and transfer them to the host with only a single copy.  Or possibly you don't need to transfer them at all, if you can do all the computations you need on the GPU.  The [developer guide](http://docs.openmm.org/latest/developerguide/) describes how to write plugins, and the [example plugin](https://github.com/openmm/openmmexampleplugin) gives a minimal working project you can start from.  It implements a force rather than an integrator, but that doesn't affect the structure.  You just write different classes.  If you look in [CommonKernels.h](https://github.com/openmm/openmm/blob/master/platforms/common/include/openmm/common/CommonKernels.h) and [CommonKernels.cpp](https://github.com/openmm/openmm/blob/master/platforms/common/src/CommonKernels.cpp), you'll find lots of examples of how integrators are implemented.

**Comment by ansingh1214** [comment]
I only included the code for running 1 simulation - in general I'm using a .sh file that runs multiple simulations in parallel, averages grad at each step over all simulations, updates c[i][j] and stores it in a file - and all of this comprises a single optimization step. The new c[i][j] are for the next step is drawn from the new file.
I have already looked at the plugin, but the main issue with it is that I need information about the gaussian random numbers that I draw, and the global variable dU. I'm not exactly sure how I can pass these variables as arguments to the force.
But indeed if there's a way to do so, it would solve all the issues.

**Comment by peastman** [comment]
Does that mean you're recreating your whole integrator and context after every timestep?  That's going to be incredibly slow.  Pretty much anything the integrator does should be negligible compared to that.

> I'm not exactly sure how I can pass these variables as arguments to the force.

What force are you talking about?  The random numbers are used in the integrator, not the force.

**Comment by ansingh1214** [comment]
I'm creating a new integrator after one simulation run, that runs for 10^6 timesteps.
And I'm sorry, did you mean that I should try constructing a plugin that implements a custom integrator for my specific algorithm? I guess that would indeed solve the problem.

**Comment by peastman** [comment]
Correct.
