### ISSUE TITLE
No template found for residue 294 (ASN)

### ISSUE THREAD

**Issue by ixy90** [openmm/openmm#3601]
Hello :)

I am trying to run an OpneMM code with a MOE generated file (preprocessed with OpenMM Setup), and I am getting the error: No template found for residue 294 (ASN).  The set of atoms is similar to CGLN, but it is missing 2 atoms.

I tried it with my own code and with the the very basic "first example" code from the OpenMM site, which I will post here for simplicity, because the error is the same with both anyways.
I looked into the file and found, that the residue that makes the problem is the very last residue of the protein (after it comes the ligand). The error says "residue 294", but it is only because there is a jump in enumeration. However I do not know what is wrong with it exactly.

Here is the code:

```
from openmm.app import *
from openmm import *
from openmm.unit import *
from sys import stdout

pdb = PDBFile('desktop/5HT2BR_ERG-processedcopy.pdb')
forcefield = ForceField('amber14-all.xml', 'amber14/tip3pfb.xml')
system = forcefield.createSystem(pdb.topology, nonbondedMethod=PME,
        nonbondedCutoff=1*nanometer, constraints=HBonds)
integrator = LangevinMiddleIntegrator(300*kelvin, 1/picosecond, 0.004*picoseconds)
simulation = Simulation(pdb.topology, system, integrator)
simulation.context.setPositions(pdb.positions)
simulation.minimizeEnergy()
simulation.reporters.append(PDBReporter('output.pdb', 1000))
simulation.reporters.append(StateDataReporter(stdout, 1000, step=True,
        potentialEnergy=True, temperature=True))
simulation.step(10000)
```

Here is a screenshot from the residue in question:

<img width="693" alt="Screenshot 2022-05-12 at 23 55 51" src="https://user-images.githubusercontent.com/77452721/168174525-9afcf243-3d34-4e0a-8acd-c2dce9f950fa.png">

And here is the whole file (with .txt ending so that github would take it)

[5HT2BR_ERG-processed.pdb.txt](https://github.com/openmm/openmm/files/8682794/5HT2BR_ERG-processed.pdb.txt)

Thank you all very much in advance!!

**Comment by peastman** [comment]
See [this FAQ entry](https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template) for lots of information about what causes this type of error.

In your case, we can compare to the template for a C terminal ASN:

https://github.com/openmm/openmm/blob/fb0360604800bba836be24cd6e8adce8b22b258a/wrappers/python/openmm/app/data/amber14/protein.ff14SB.xml#L1102-L1133

Your file has an extra atom called `HC` that isn't supposed to be there.  What is it?
