### ISSUE TITLE
Obtaining polarisation data from AMOEBA

### ISSUE THREAD

**Issue by Gareth-elliott** [openmm/openmm#3613]
Hi OpenMM Developers,

I was wondering if it is possible to obtain the polarisation data by post-processing a trajectory (or if not can it be dumped during a simulation?). I.e. can you run a "single point" calculation of each frame to get the polarisation state of all the particles in the system with respect to some (global?) reference frame? 

Thanks,

Gareth

**Comment by peastman** [comment]
Yes, see the [API documentation](http://docs.openmm.org/latest/api-python/generated/openmm.openmm.AmoebaMultipoleForce.html#openmm.openmm.AmoebaMultipoleForce) for AmoebaMultipoleForce.  There are several methods you can call to compute polarization information for the current positions stored in the Context: `getInducedDipoles()`, `getLabFramePermanentDipoles()`, `getTotalDipoles()`, and `getSystemMultipoleMoments()`.

**Comment by Gareth-elliott** [comment]
Thanks a lot @peastman :-)

Just to clarify - does the ```getInducedDipoles()``` function return the dipoles in the local frame or the global frame (i.e. lab frame?)

If I was going to post-process a trajectory, I assume I would update the context with the atom positions (similar to loading a checkpoint file), what would I have to do to run the self-consistent loop to converge the induced dipoles?

**Comment by peastman** [comment]
> does the getInducedDipoles() function return the dipoles in the local frame or the global frame (i.e. lab frame?)

The lab frame.

> what would I have to do to run the self-consistent loop to converge the induced dipoles?

Just call `getInducedDipoles()`.  The ones it returns will be correct for whatever positions are currently stored in the context.

**Comment by Gareth-elliott** [comment]
Great, thanks a lot @peastman! :-)
