### ISSUE TITLE
amide bond between protein and small molecule

### ISSUE THREAD

**Issue by tanmoy7989** [openmm/openmm#3615]
I have a system consisting of a peptide and a polymeric linker (a 3 amino acid - 16 C fatty acid conjugate), which I parameterize using a combination of amber14 protein ff and gaff-2.1 through openmmforcefield’s SystemGenerator API. 

Now, I want to add an amide bond between the N terminal N of the peptide and a carbonyl carbon of the linker. Ideally I’d also like to have angles and dihedrals around this new bond. If I simply use addBond from the Topology object, will that take care of :
1. adding the right parameters for the bond when the system is constructed?
2. adding parameters for all extra angles and dihedrals introduced by this bond?
3. Which forcefield to use for these extra interactions, peptide ff or small molecule ff?

**Comment by peastman** [comment]
@jchodera is this case supposed to work?  From looking at the force field files, I don't think it would.  The peptide would be parametrized using Amber14 types and the linker would be parametrized using GAFF types.  Then we would need parameters for a bond connecting an Amber14 atom type to a GAFF atom type.  I don't see any definitions like that.

**Comment by jchodera** [comment]
[`SystemGenerator`](https://github.com/openmm/openmmforcefields#automating-force-field-management-with-systemgenerator) is simply a wrapper around [`GAFFTemplateGenerator`](https://github.com/openmm/openmmforcefields#examples-using-gafftemplategenerator-to-generate-small-molecule-gaff-parameters), which uses AmberTools `antechamber` and `tleap` to generate small molecule parameters. That AmberTools workflow does not support covalent biopolymer/small molecule conjugates.

You would have to follow the standard approach you would use in AmberTools to manually modify the complete system topology within `tleap` and apply parameters (likely needing to craft your own `frcmod` files or modify individual parameters manually) and then export a `prmtop/inpcrd` pair you can read in OpenMM via the [Amber prmtop/inpcrd file readers](http://docs.openmm.org/latest/userguide/application/02_running_sims.html#using-amber-files).

If you want to try an experimental approach, [espaloma](http://github.com/choderalab/espaloma) can handle these conjugates, but creating the [OpenFF Toolkit `Molecule` object](https://docs.openforcefield.org/projects/toolkit/en/stable/topology.html) for the biopolymer/small molecule conjugate may still be slow until the new enhanced biopolymer support release of the OpenFF toolkit comes out.

**Comment by tanmoy7989** [comment]
I tried a version of the first approach. ie manually modifying the forcefield, albeit using openmm to add the bond, angle, torsion and improper interactions associated with forming a new amide bond, whose (gaff-2.11) params I took from: https://github.com/openmm/openmmforcefields/blob/master/amber/gaff/ffxml/gaff-2.11.xml

I'll know soon if the simulations produce valid results, so keeping this open until then.

**Comment by tanmoy7989** [comment]
@peastman @jchodera 
Still working on this and ran into another question. Esplaoma is a great tool of course, but there are reasons that I'm not going into here, for which we are stuck to gaff-based parameterization of tethered (by amide bonds) small molecules (fatty acids in this case) to protein residues. 

Based on what @jchodera suggested about manually modifying amber parameters and writing custom `frcmod` files, I wonder if it might be possible to do that in a more openmm-ish way using forcefield patches?  Eg. is the following possible?

```
from openmmforcefields.generators import SystemGenerator

ff_protein = "amber14/protein.ff14SB.xml"
ff_solvent = "amber14/spce.xml",
ff_ligand = "gaff-2.11"

ff_tether = "my_tether_ff.xml"

sysgen = SystemGenerator(
        forcefields=[ff_protein, ff_solvent, ff_tether],
        small_molecule_forcfield=ff_ligand,
        forcfield_kwargs=...,
       periodic_forcefield_kwargs=...,
       nonperiodic_forcefield_kwargs=...,
      cache="tethered_ligands.cache"
)
```

And then the `my_tether.xml` would contain something like:

```
<Patches>
  <Patch name="TetherLigand" residues="2">
    <RemoveAtom name="1:?"/>
    <RemoveAtom name="2:?"/>
    <AddBond atomName1="1:?" atomName2="2:?"/>
    <ApplyToResidue name="1:LYS"/>
    <ApplyToResidue name="2:?"/>
  </Patch>
</Patches>

<HarmonicBondForce>
 ...
</HarmonicBondForce>

<HarmonicAngleForce>
 ...
</HarmonicAngleForce>
```

Basically, just a patch containing the modification to the topology that is needed to create the protein - small molecule amide bond, and then all associated bond, angle, torsion etc terms that appear as a result. (I put question marks in the xml above, since I'm unsure about the names at this point)

For the bond, angle and torsion parameters I will probably just use the [gaff-2.11 parameters from `openmmforcefields`](https://github.com/openmm/openmmforcefields/blob/7e2c769003195089938a134c44b3c81b05aeb624/amber/gaff/ffxml/gaff-2.11.xml). 

My questions are: 
- can I get away with just defining a patch in a forcefield file, and have it automatically point to the correct atom names if I keep them consistent with the gaff-2.11 names?
-  if this works, how do I get the patch to focus in on a particular residue? Eg `<ApplyToResidue name="1:LYS"/>` would probably apply this to all LYS residues, while I only need to apply on say the 10th residue.

**Comment by peastman** [comment]
It's an interesting idea.  As things are currently implemented, I don't think it would work.  Patches get processed before template generators.  After all, patches are part of the force field definition, and template generators are only for residues that couldn't be matched with the force field (including patches).

In principle, SystemGenerator could implement logic that handles this.  It would need to somehow recognize that it needs to preemptively generate and register a template for the small molecule minus the linker, but not for the LYS.  I'm not sure how it would do that.

A simpler solution would be to define a new `<Residue>` template for the modified LYS, where one atom has been removed and replaced by an external bond.  That will allow all matching to happen normally.  I'm assuming GAFFTemplateGenerator can handle residues that are part of a larger molecule, not just small molecules.  I'm not sure if that's true.

It still leaves you the job of defining parameters.  You'll end up with a single molecule that partly has Amber14 atom types and partly GAFF atom types.  Since the force fields don't supply any definitions for bonds connecting those atoms, you'll need to supply them yourself.

**Comment by tanmoy7989** [comment]
*A simpler solution would be to define a new <Residue> template for the modified LYS, where one atom has been removed and replaced by an external bond*

I have been thinking along these lines. But would I have to make corresponding changes to the topology as well, manually? ie before using this template would I need to remove the hydrogen from the modified LYS in the pdb file beforehand?

* Since the force fields don't supply any definitions for bonds connecting those atoms, you'll need to supply them yourself.*
Yep, thats the plan.

**Comment by tanmoy7989** [comment]
@peastman 
*A simpler solution would be to define a new <Residue> template for the modified LYS, where one atom has been removed and replaced by an external bond*
This makes a lot of sense, thanks! Would I also to need to modify the LYS manually in the PDB file before this template can be applied? ie remove the hydrogen manually? 

*Since the force fields don't supply any definitions for bonds connecting those atoms, you'll need to supply them yourself*
Yep, that's the plan.

**Comment by tanmoy7989** [comment]
This worked perfectly. Thanks for the suggestions. Closing.
