### ISSUE TITLE
Ignore NonbondedForce/CustomNonbondedForce at specific regions

### ISSUE THREAD

**Issue by smlee99** [openmm/openmm#3616]
I am now simulating the solvated aqueous small peptide box with CHARMM36/TIP3P forcefield. There is a subtle and complex issue while progressing on my research. If the box z length is 10nm for instance, I'd like to ignore the `NonbondedForce` and `CustomNonbondedForce` between peptide and (water molecules located between 3nm to 5nm).(This is independent of the peptide location, pre-defined values.) Although controlling such interaction could be handled via `addInteractionGroups`, the problem here is that I need to update the group list per every step. Updating such list per every step should be insane, so I wonder if there is a way to resolve this issue.

What I've thought about this problem is to use the custom force. Selecting water molecules coordinate list at specific regions would be possible by using step function and `CustomCVForce`. Then, can I access to the pairwise `CustomNonbondedForce` values between peptide and selected water coordinate list? If that's possible, then I could add the `CustomExternalForce` to exactly cancel out the original interaction between them. Or is there any better solution to handle this problem?

**Comment by peastman** [comment]
If I understand correctly, you want water molecules to "disappear" as far as nonbonded interactions are concerned whenever they're in a particular region.  Is that really correct?  I'm trusting you have a good reason for wanting that!  Obviously your simulation won't conserve energy.

Should the filtering be done per-atom or per-molecule?  If a water is partly inside the ignored region, should the peptide interact with the atoms that are still outside it?

**Comment by smlee99** [comment]
Yes. There are some reasons to simulate such system but never thought about the energy conservation. I consider per-atom case but choose the atoms where the COM of water molecules are locating in certain z value range.(I guess this range would be nearly equal to the cutoff distance)

**Comment by peastman** [comment]
> I consider per-atom case but choose the atoms where the COM of water molecules are locating in certain z value range.

I'm not sure what you mean.  Are you saying that the filtering is always done for whole molecules based on the COM of the molecule?  Or that it's done per-atom?

If you want to do it per-atom, I believe this can be done with a CustomGBForce.  It will be a little inefficient, but not too bad.  I can give more details if that's what you want.

If it needs to be done per-molecule, the best I can suggest is to add a per-particle parameter specifying which particles should be ignored.  You would need to update it and call `updateParametersInContext()` after every step.  This would be *very* slow, though not as slow as rebuilding the context to use different interaction groups.

The other option, of course, is to write a plugin.  That's a lot of work, but it would allow you to do it efficiently.

**Comment by smlee99** [comment]
Sorry for late reply. 
>Are you saying that the filtering is always done for whole molecules based on the COM of the molecule? Or that it's done per-atom?

The former one was what I meant but now I understood that updating particle list is inevitable. I think it would be a good start to filter in per-atom case first.  Could you give me more details to implement CustomGBForce to cancel out the nonbondedforce in CHARMM36?

**Comment by peastman** [comment]
Are you really sure you want to do that?  You're going to get *very* strange results.  As each water molecule passes across the border, it will go through a series of states in which it becomes charged as different combinations of atoms get ignored.  I can't imagine how you'll get anything meaningful out of it.

**Comment by smlee99** [comment]
Yeap.. I tried some cases and found that such results were quite inadequate for any physical interpretation. Let me close this issue.
