### ISSUE TITLE
Simulation box dimensions no longer being reported in PDB files

### ISSUE THREAD

**Issue by bbye98** [openmm/openmm#3617]
Hello!

I recently noticed that a newer version of OpenMM 7.7 (from May 23, 2022) is no longer reporting the simulation box dimensions in PDB files written by `openmm.app.PDBReporter`. An older version of OpenMM 7.7 (from May 5, 2022) does.

Here are two snippets of PDB files written by the two versions:

Old:
```
REMARK   1 CREATED WITH OPENMM 7.7, 2022-05-05
CRYST1   62.900   61.834  126.319  90.00  90.00  90.00 P 1           1 
MODEL        1
HETATM    1 CAT  CAT A   1      62.353  12.836   8.692  1.00  0.00          Ar  
```

New:
```
REMARK   1 CREATED WITH OPENMM 7.7, 2022-05-23
MODEL        1
HETATM    1 CAT  CAT A   1       2.842  70.435 134.134  1.00  0.00          Ar  
```

The two runs above are from different simulations with different parameters, but they share the same "controlling" Python script (meaning that everything else is identical). 

Is there a way to force OpenMM to output the system dimensions in the PDB files? I've written several functions that parse the first two lines of the PDB file for this information, so it would be a shame to have to go back and find an alternative way of extracting the dimensions.

Thank you in advance!

**Comment by peastman** [comment]
It writes the box vectors if they're present in your Topology.  If they aren't being written, that means `topology.getPeriodicBoxVectors()` is returning `None`.

**Comment by bbye98** [comment]
Interesting. To the top of my head, I don't recall having played around that in my "controlling" Python script--but I will go back and quickly check. Thank you as always!

**Comment by bbye98** [comment]
Thank you--it turns out I accidentally moved my `topology.setUnitCellDimensions()` call inside an `if` statement so for certain cases it is not called.

A little bit off-topic, but is there a way to only include certain particles/residues in the outputted PDB file? I have a bunch of "dummy" image charges that are not relevant in my data analysis, but they add an unnecessary ~10 GB to my PDB files.

**Comment by peastman** [comment]
You could use Modeller to create an edited Topology that only has the atoms you want.  Then you can call `PDBFile.writeFile()` with that Topology and an edited list of positions for only the atoms you want.

But to answer a different question than what you asked, you really shouldn't be using PDB as your output format.  If you save trajectories in DCD format instead, they'll be much smaller and the positions will be stored more accurately.

**Comment by bbye98** [comment]
Thank you for the suggestion! I've written most of my code for PDB files, but if DCD files offer superior accuracy and smaller file sizes, it would be a no-brainer to adapt my current functions to work with DCD files as well.
