### ISSUE TITLE
Seperate XML files are not supported for AMOEBA GK forces.

### ISSUE THREAD

**Issue by WangXinyan940** [openmm/openmm#3624]
https://github.com/openmm/openmm/blob/master/wrappers/python/openmm/app/forcefield.py#L5515
&
https://github.com/openmm/openmm/blob/master/wrappers/python/openmm/app/forcefield.py#L5747

In the latest code, I found that most of the Amoeba forces finally support separate XML files by searching for existing generator from ForceField._forces in parseElement function except the upper two forces, AmoebaGeneralizedKirkwoodForce and AmoebaWcaDispersionForce. Maybe they can also be kindly fixed.

**Comment by peastman** [comment]
Thanks for catching this!  The fix is in #3625.  Can you test it and see whether it works for you?

**Comment by WangXinyan940** [comment]
> Thanks for catching this! The fix is in #3625. Can you test it and see whether it works for you?

Yes. It works well now.

**Comment by peastman** [comment]
Thanks!
