### ISSUE TITLE
Pure bilayer simulations with the AMOEBA force field

### ISSUE THREAD

**Issue by batukav** [openmm/openmm#3627]
Hello,

I am trying to create a pure POPE bilayer simulation with the AMOEBA force field. I have obtained the force field file in xml format and also created the initial structure of the bilayer using the CHARMM-GUI. The generated PDB file does not have the CONECT records.

I would like to read in the PDB file, alongside with the force field file, to run a bilayer simulation. 

When I run the below commands

`pdb = PDBFile('pop.pdb')
forcefield = ForceField('pope.xml')
system = forcefield.createSystem(pdb.topology)`

I receive the error 

`ValueError: No template found for residue 1 (POPE).  The set of atoms matches POPE, but the bonds are different.  Perhaps the chain is missing a terminal group?`

The order of the atoms in the PDB file and the xml file are the same. As my PDB file does not contain the CONECT records, do I need to manually create the bonds? In general, is there a recommended/suggested way of creating pure bilayer simulations in OpenMM starting from only a PDB file? I attach my files in case they'd be useful.

Thank you all.
[pope.zip](https://github.com/openmm/openmm/files/8832766/pope.zip)

**Comment by peastman** [comment]
If your PDB file is missing CONECT records, that will cause problems.  Some programs can attempt to infer missing bonds based on geometry.  For example, I think VMD will do it automatically.  Just load your PDB file, then save it, and the new file will hopefully have correct bonds.

It also would be good to report this to the CHARMM-GUI developers.  They need to know they're producing incorrect PDB files!
