### ISSUE TITLE
Does OpenMM automatically use CMAP corrections when using charmm36m parameter files?

### ISSUE THREAD

**Issue by moeenmeigooni** [openmm/openmm#3629]
I see that OpenMM is able to utilize CMAP tabulated energy corrections through CMAPTorsionForce. Does OpenMM automatically use these corrections during dynamics if I create my System from a parameter list that includes par_all36m_prot.prm? Or do I have to call CMAPTorsionForce for every amino acid manually? It would also be helpful to know if it's possible do a sanity check during setup to make sure the corrections are in place. Would that be done by iterating through all the forces and checking each with isinstance or is there a special system property I could try like usesCMAP?

**Comment by peastman** [comment]
Yes, it will do it automatically.

> Would that be done by iterating through all the forces and checking each with isinstance

Correct.  You can do it like this.

```python
for force in system.getForces():
  if isinstance(force, CMAPTorsionForce):
    print(force.getNumTorsions())
```

**Comment by moeenmeigooni** [comment]
Thanks!
