### ISSUE TITLE
Slowdown on multi-GPU machine vs single-GPU machine with custom forces

### ISSUE THREAD

**Issue by moeenmeigooni** [openmm/openmm#3632]
Hello,

I am running OpenMM on two different machines using the ```CUDA``` Platform. One is a workstation equipped with an NVIDIA GeForce GTX 1080. The other is an NVIDIA DGX-2, equipped with 16x NVIDIA Tesla V100 GPUs. On the single-GPU workstation, I can consistently get ~700 ns/day running once copy of my system. On the DGX-2, I get around the same ns/day if I run a single copy on a single GPU (leaving the other 15 idle). However, when I run 16 independent copies, one on each GPU, each copy only gets around 300 ns/day. Additionally, the ns/day for each copy seems to scale linearly between 300 and 700 as I vary the number of concurrent independent copies from 1 to 16.

In the system I'm simulating, I've added a harmonic restraint to the distance between two atoms using CustomCentroidBondForce. The energy expression I input is ```0.5 * k0 * (distance(g1,g2) - d0)^2```. I define k0 and d0 as global parameters, and each centroid-defining group consists of only one atom. 

I think a simple explanation for this slowdown is that my CustomCentroidBondForce is being computed on the CPU, and as I increase the number of independent simulations, the restraint forces of all the different copies must all be computed on the CPU despite the rest of the dynamics being calculated on separate GPUs, resulting in a CPU bottleneck. I am hoping you could share some advice on potential routes of addressing this slowdown.

First, does my assessment of the problem make sense? 

Second, is there a way to implement a harmonic pairwise distance potential that doesn't rely on CPU evaluation? I get that CustomCentroidBondForce is already overkill since there is only one atom in each interacting group. But I imagine that any Custom force object is still going to be evaluated on CPU, so I would guess that CustomBondForce runs into the same CPU bottleneck issue. Could HarmonicBondForce be the answer since my functional form is the same?

Lastly, is there a way to assign a CPU id or range of ids to particular GPU simulations to prevent the bottleneck? Since the DGX-2 has multiple GPUs and multiple CPUs, I'd imagine that performance could be improved by restricting each independent GPU simulation to a CPU id range for CPU-side calculations. Something like including a list of CPU ids in the same properties dictionary that specifies the GPU id? I know it's possible to specify both CPU and GPU ranges in other MD packages, so I was hoping a similar approach here might alleviate the bottleneck. Or might OpenMM do this already by checking the CPU affinity of each GPU and dividing them evenly?

I really appreciate all your help thus far, as well as any more you might be able to provide here.

**Comment by peastman** [comment]
If you specify the CUDA platform, all computation is done on the GPU.  No forces, whether custom or standard, are evaluated on the CPU.

When you say you're running independent copies, does that mean you're running 16 separate processes, each running a separate simulation on a different GPU?  That ought to scale very well, at least as long as you have roughly 2 CPU cores per GPU.  If you're doing something different, there are lots of pitfalls you could run into.  Perhaps you're running a single Python script that tries to run 16 simulations all in one process?  Python is mostly single threaded, so CPU would become a serious bottleneck in that case.  And are you sure you're really running every simulation on a different GPU, rather than several all on the same GPU?

If you can provide more details about exactly what you're doing, hopefully with code, that would help.  You also can see a lot just with `top` (to see what's going on on the CPU) and `nvidia-smi` (to see what's going on on the GPUs).  Are the GPUs all busy, or mostly idle?  What about the CPU cores?

**Comment by moeenmeigooni** [comment]
> does that mean you're running 16 separate processes, each running a separate simulation on a different GPU

Yes.

> as long as you have roughly 2 CPU cores per GPU

There are a total of 96 CPU cores, which comes out to 6 cores per GPU. The CPU affinity of each GPU can vary, however. Here is the output from running ```nvidia-smi topo -m``` if it helps:
```
	GPU0	GPU1	GPU2	GPU3	GPU4	GPU5	GPU6	GPU7	GPU8	GPU9	GPU10	GPU11	GPU12	GPU13	GPU14	GPU15	mlx5_0	mlx5_1	mlx5_2	mlx5_3	mlx5_4	mlx5_5	mlx5_6	mlx5_7	mlx5_8	mlx5_9	CPU Affinity	NUMA Affinity
GPU0	 X 	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	PIX	PXB	NODE	NODE	SYS	SYS	SYS	SYS	SYS	SYS	0-23,48-71	0
GPU1	NV6	 X 	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	PIX	PXB	NODE	NODE	SYS	SYS	SYS	SYS	SYS	SYS	0-23,48-71	0
GPU2	NV6	NV6	 X 	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	PXB	PIX	NODE	NODE	SYS	SYS	SYS	SYS	SYS	SYS	0-23,48-71	0
GPU3	NV6	NV6	NV6	 X 	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	PXB	PIX	NODE	NODE	SYS	SYS	SYS	SYS	SYS	SYS	0-23,48-71	0
GPU4	NV6	NV6	NV6	NV6	 X 	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NODE	NODE	PIX	PXB	SYS	SYS	SYS	SYS	SYS	SYS	0-23,48-71	0
GPU5	NV6	NV6	NV6	NV6	NV6	 X 	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NODE	NODE	PIX	PXB	SYS	SYS	SYS	SYS	SYS	SYS	0-23,48-71	0
GPU6	NV6	NV6	NV6	NV6	NV6	NV6	 X 	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NODE	NODE	PXB	PIX	SYS	SYS	SYS	SYS	SYS	SYS	0-23,48-71	0
GPU7	NV6	NV6	NV6	NV6	NV6	NV6	NV6	 X 	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NODE	NODE	PXB	PIX	SYS	SYS	SYS	SYS	SYS	SYS	0-23,48-71	0
GPU8	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	 X 	NV6	NV6	NV6	NV6	NV6	NV6	NV6	SYS	SYS	SYS	SYS	NODE	NODE	PIX	PXB	NODE	NODE	24-47,72-95	1
GPU9	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	 X 	NV6	NV6	NV6	NV6	NV6	NV6	SYS	SYS	SYS	SYS	NODE	NODE	PIX	PXB	NODE	NODE	24-47,72-95	1
GPU10	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	 X 	NV6	NV6	NV6	NV6	NV6	SYS	SYS	SYS	SYS	NODE	NODE	PXB	PIX	NODE	NODE	24-47,72-95	1
GPU11	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	 X 	NV6	NV6	NV6	NV6	SYS	SYS	SYS	SYS	NODE	NODE	PXB	PIX	NODE	NODE	24-47,72-95	1
GPU12	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	 X 	NV6	NV6	NV6	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	PIX	PXB	24-47,72-95	1
GPU13	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	 X 	NV6	NV6	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	PIX	PXB	24-47,72-95	1
GPU14	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	 X 	NV6	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	PXB	PIX	24-47,72-95	1
GPU15	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	NV6	 X 	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	PXB	PIX	24-47,72-95	1
mlx5_0	PIX	PIX	PXB	PXB	NODE	NODE	NODE	NODE	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	 X 	PXB	NODE	NODE	SYS	SYS	SYS	SYS	SYS	SYS		
mlx5_1	PXB	PXB	PIX	PIX	NODE	NODE	NODE	NODE	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	PXB	 X 	NODE	NODE	SYS	SYS	SYS	SYS	SYS	SYS		
mlx5_2	NODE	NODE	NODE	NODE	PIX	PIX	PXB	PXB	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	NODE	NODE	 X 	PXB	SYS	SYS	SYS	SYS	SYS	SYS		
mlx5_3	NODE	NODE	NODE	NODE	PXB	PXB	PIX	PIX	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	NODE	NODE	PXB	 X 	SYS	SYS	SYS	SYS	SYS	SYS		
mlx5_4	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	SYS	SYS	SYS	SYS	 X 	PIX	NODE	NODE	NODE	NODE		
mlx5_5	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	SYS	SYS	SYS	SYS	PIX	 X 	NODE	NODE	NODE	NODE		
mlx5_6	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	PIX	PIX	PXB	PXB	NODE	NODE	NODE	NODE	SYS	SYS	SYS	SYS	NODE	NODE	 X 	PXB	NODE	NODE		
mlx5_7	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	PXB	PXB	PIX	PIX	NODE	NODE	NODE	NODE	SYS	SYS	SYS	SYS	NODE	NODE	PXB	 X 	NODE	NODE		
mlx5_8	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	PIX	PIX	PXB	PXB	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	 X 	PXB		
mlx5_9	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	PXB	PXB	PIX	PIX	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	PXB	 X 		

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks
```
> Perhaps you're running a single Python script that tries to run 16 simulations all in one process? 

Technically I am launching all 16 runs using a single .py file, but I'm running it 16 separate times with different argument variables to specify GPU id for convenience. Python is being run from a bash script like this:
```bash
n_gpu=16
for (( i=0; i<$n_gpu; i++)); do
  python run.py --gpuid $i >& run_$i.log &
done
wait
```
The script passes the gpuid to a properties dictionary ```{'DeviceIndex': gpuid}``` which is then used to initialize the Simulation object. There should be no difference between this and 16 separate python scripts, right?

> Are the GPUs all busy, or mostly idle? 

When I use ```watch -n.1 nvidia-smi``` to see volatile GPU utilization over time, I notice some strange periodicity. The usage of any single GPU varies between 90% and 0%. For a few seconds, the usage is very high, and then for a few seconds the usage is zero. I'm working on making a graph to visualize each GPU's usage over time for a more quantitative description, but it seems like the GPUs are taking turns going to zero. At any one time, about half the GPUs are at 0%. I definitely do not see this periodic variation in usage when I run a single copy on a single GPU, leaving the other 15 idle. When I do that, the GPU usage consistently stays >95% until it's done running. 

> What about the CPU cores?

Looking at CPU usage with ```top``` shows that half the CPU processes are in the 'D' state at any given time.
```
PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND 
69341 meigoon2  20   0  0.127t 445096 190192 R  50.8  0.0  32:30.20 python                                              
69335 meigoon2  20   0  0.127t 445364 190400 R  47.5  0.0  32:40.10 python                                              
69340 meigoon2  20   0  0.127t 444376 189672 R  45.9  0.0  32:20.19 python                                              
69332 meigoon2  20   0  0.137t 510464 194672 D  42.9  0.0  32:23.93 python                                              
69329 meigoon2  20   0  0.138t 511248 195184 D  42.2  0.0  32:52.08 python                                              
69336 meigoon2  20   0  0.136t 510664 195144 R  42.2  0.0  32:46.96 python                                              
69337 meigoon2  20   0  0.127t 445092 190136 R  42.2  0.0  32:26.27 python                                              
69338 meigoon2  20   0  0.127t 444656 189952 D  41.9  0.0  32:23.74 python                                              
69328 meigoon2  20   0  0.137t 510596 194888 D  40.6  0.0  32:40.05 python                                              
69334 meigoon2  20   0  0.127t 446096 190212 D  40.6  0.0  32:19.88 python                                              
69342 meigoon2  20   0  0.127t 446112 189960 D  40.6  0.0  32:42.99 python                                              
69327 meigoon2  20   0  0.136t 511632 195272 R  33.0  0.0  32:44.15 python                                              
69331 meigoon2  20   0  0.127t 445264 190328 D  31.7  0.0  32:21.15 python                                              
69339 meigoon2  20   0  0.127t 445020 190320 R  30.4  0.0  32:35.14 python                                              
69333 meigoon2  20   0  0.127t 445476 190756 R  30.0  0.0  32:14.23 python        
```


Given all the above, does anything seem obviously wrong? If not I can organize all my code and system specs into a .zip file for you. Also, is there a more convenient way for me to communicate CPU or GPU usage over time other than by manually parsing the outputs from ```top``` and ```nvidia-smi``` commands?

**Comment by peastman** [comment]
> Technically I am launching all 16 runs using a single .py file, but I'm running it 16 separate times with different argument variables to specify GPU id for convenience.

That should be fine.  The important thing is that each is run in a different process.

> Looking at CPU usage with top shows that half the CPU processes are in the 'D' state at any given time.

That seems likely to be the problem.  "D" is "disk sleep".  It's the state a process gets put into while it's blocked waiting for an IO operation to complete.  Does your code do a lot of reading or writing while it runs?  That would explain why the problem gets worse as the number of processes increases, since they're competing for access to the same disk.

**Comment by moeenmeigooni** [comment]
> Does your code do a lot of reading or writing while it runs?

I am writing every 1000 steps with DCDReporter, StateDataReporter, and CheckpointReporter. I think I remember reading elsewhere that writing checkpoints can be slow, since it basically has to repickle the context object every N steps? 

Here's the % usage for all 16 GPUs when I write a checkpoint every 1000 steps:
![dgx-chk1000](https://user-images.githubusercontent.com/22182118/172921644-de9a260c-d7c2-4c15-8366-10d8c1b22b83.png)



I tried running without a checkpoint reporter, et voila:
![dgx-nochk](https://user-images.githubusercontent.com/22182118/172921664-a5fd8d94-5f7e-4096-a8e7-efcf66705658.png)



I'm convinced! I will have to write checkpoint files less frequently. Thanks for the help.

**Comment by peastman** [comment]
Excellent!  Checkpoints are indeed a bit expensive to write.  And there's no reason to write them all that often.  If your simulation crashes or the computer gets shut down, you want a checkpoint you can restart from.  But if you have to repeat a few minutes of work, it's not a big deal.  If you're writing a checkpoint every few seconds, that's probably way more than required.
