### ISSUE TITLE
How can I report the result of simulation.minimizeEnergy()?

### ISSUE THREAD

**Issue by OkKakao** [openmm/openmm#3635]
Hi, I'm trying structural optimization by sampling the MD simulation and subsequent local energy minimization.

I'm quite sure that MD simulation is done by following code
```simulation.step(10000)```

Also, local energy minimization is done by the following
```simulation.minimizeEnergy(tolerance=number, maxIteration=number)```

The former one is exported to PDB file with the following
```simulation.reporters.append(PDBReporter(f'{filename}.pdb', step))```

However, I couldn't find how to report the resulatant state of local energy minimization.

I also tried getstate() function or something, the only successful result was the following.
```print(simulation.context.getState(getEnergy=True).getPotentialEnergy())```

How can I report the locally optimized position, energy or other properties?

I even couldn't find how to access mapdoublestring type....

**Comment by peastman** [comment]
`getState()` is the correct way to retrieve information about the current state.  See [the API documentation](http://docs.openmm.org/latest/api-python/generated/openmm.openmm.Context.html#openmm.openmm.Context.getState) for details on all the different options.  For example, if you want positions and energy you would write

```python
state = simulation.context.getState(getPositions=True, getEnergy=True)
```

If you want to write out the coordinates to a PDB file you can do it like this:

```python
with open('filename.pdb', 'w') as output:
    PDBFile.writeFile(simulation.topology, state.getPositions(), output)
```

> I even couldn't find how to access mapdoublestring type....

You can just treat it as a `dict`.  Occasionally you'll see classes with strange names like that appearing in the Python API.  They're generated by SWIG when wrapping the C++ library.  They behave exactly like standard Python classes.

**Comment by OkKakao** [comment]
That's what I exactly wanted!!
Thank you for clear explanation!
