### ISSUE TITLE
CUDA initialization error when using GPU acceleration

### ISSUE THREAD

**Issue by OkKakao** [openmm/openmm#3638]
I executed code and it worked well, however, after several hours, I tried another execution attempt, an error raised.

The whole code is the following.
```
filename = 'glc+ser//D-glc+D-ser_3'
temps = ['OC[C@H]1O[C@@H](O)[C@H](O)[C@@H](O)[C@@H]1O', 'C([C@H](C(=O)O)N)O', 'C(O)[C@@H]1(O[C@@H](O)[C@@H](O)[C@H](O)[C@@H](O)1)']
#        D-glc                                           D-ser                 L-glc
forcefield = ForceField('amber14/tip3p.xml')
for i in temps:
    molecule = Molecule.from_smiles(i)
    espaloma = EspalomaTemplateGenerator(molecules=molecule, forcefield='espaloma-0.2.2')
    forcefield.registerTemplateGenerator(espaloma.generator)
pdb = PDBFile(f'{filename}.pdb')
platform = Platform.getPlatformByName('CUDA')
system = forcefield.createSystem(pdb.topology, nonbondedMethod=NoCutoff, constraints=HBonds)
force = CustomExternalForce('100*max(0, r-4)^2; r=sqrt(x*x+y*y+z*z)')
system.addForce(force)
for i in range(system.getNumParticles()):
    force.addParticle(i, [])
integrator = LangevinMiddleIntegrator(300*kelvin, 1/picosecond, 0.002*picoseconds)
simulation = Simulation(pdb.topology, system, integrator, platform)
simulation.context.setPositions(pdb.positions)
simulation.minimizeEnergy()
```
The error message was this
```openmm.OpenMMException: Error initializing CUDA: CUDA_ERROR_NOT_INITIALIZED (3) at /home/conda/feedstock_root/build_artifacts/openmm_1646184868775/work/platforms/cuda/src/CudaContext.cpp:139```

Also, nvidia-smi information is here

![image](https://user-images.githubusercontent.com/101975748/173187502-aff4bf3a-82c2-453c-ab35-7371c22fae3b.png)

I don't know why this code raises error since it worked well but currently raising error without any modification....

**Comment by peastman** [comment]
I don't know if it's the same problem, but I have a Linux system on which putting the computer to sleep and waking it up again sometimes (but not always) causes CUDA to become unusable.  Any attempt to run a program that uses CUDA leads to errors similar to that.  The only way I've found to fix it is to reboot.

**Comment by OkKakao** [comment]
> I don't know if it's the same problem, but I have a Linux system on which putting the computer to sleep and waking it up again sometimes (but not always) causes CUDA to become unusable. Any attempt to run a program that uses CUDA leads to errors similar to that. The only way I've found to fix it is to reboot.

I tried rebooting process and it worked.
Thanks!!
