### ISSUE TITLE
Where is the implementation code of the force expression used in Calc~ForcesKernel() such as CalcNonbondedForceKernel()

### ISSUE THREAD

**Issue by psp3dcg** [openmm/openmm#3640]
I find many force expressions in [ theory documentation](http://docs.openmm.org/6.3.0/userguide/theory.html) and want to learn from the code of expressions. According to the [core library description
](http://docs.openmm.org/latest/developerguide/02_core_library.html) and the calling relationship of the code , I guess the implementation may be in the kernels.cpp or other kernel-like files. However, I cannot find it. So could anyone please tell me the code location, thx~ :)

**Comment by peastman** [comment]
Each platform has its own implementation.  The reference platform is the easiest one to follow if you want to study the code.  [This directory](https://github.com/openmm/openmm/tree/master/platforms/reference/src/SimTKReference) contains the classes for them.

**Comment by psp3dcg** [comment]
> Each platform has its own implementation. The reference platform is the easiest one to follow if you want to study the code. [This directory](https://github.com/openmm/openmm/tree/master/platforms/reference/src/SimTKReference) contains the classes for them.

OK，thank you for the help, I will check it~
