### ISSUE TITLE
Possibility to use x, y, and z coordinates of the particle positions in CustomHbondForce

### ISSUE THREAD

**Issue by WangXinyan940** [openmm/openmm#3642]
Dear OpenMM developers,

I am trying to build potential energy to describe the interaction between two groups of atoms, in which I want to use local coordinates and need things like x1, y1, z1, x2, y2, z2,... in CustomHbondForce. Is it possible to get x, y, and z components of donor/acceptor particles in CustomHbondForce?

**Comment by AnthoniAlcaraz** [comment]
I think that is not possible since "It computes interactions between "donor" particle groups and "acceptor" particle groups"
[https://simtk.org/api_docs/openmm/api3_1/classOpenMM_1_1CustomHbondForce.html](url). But @peastman could answer it.

**Comment by peastman** [comment]
Can you describe the exact potential function you want to implement?  CustomHbondForce only supports interactions that depend on the relative geometry of the atoms involved, not on their absolute positions.  But there are other custom forces that do support that.  If you give the exact equations you want to implement, we might be able to figure out a way to implement them.
