### ISSUE TITLE
Does PDBFile store the protonation variants of amino acid residues?

### ISSUE THREAD

**Issue by ziyuanzhao2000** [openmm/openmm#3645]
So I'm trying to read in a pdf file using openmm and recording the protonation variant of the residues. I then found out that using `resid.name` only gives me the standard residue names, for example, HID will alias to HIS. Is it possible that I can access the protonation variant and get a string description, say just "HID" for a histidine variant, without comparing the residue topology against the templates for all the possible variants? Thanks!

**Comment by peastman** [comment]
PDB uses the same name for all variants.  You need to check which hydrogens are there to see which one it is.  With HIS, for example, check whether it contains the atoms HD1 and HE2.  Each combination of them corresponds to a different variant.

**Comment by ziyuanzhao2000** [comment]
Thanks for your quick response, I appreciate that! What you said makes sense given that residue names in some PDB files are ambiguously labelled. One last question: perhaps are you aware of any other python packages that can parse the residue variant information from the underlying molecular topology, or I have to write my code to do the H-atoms checking.

**Comment by peastman** [comment]
Given a Residue object, it's very easy to check for atoms.  Something like this:

```python
names = set(atom.name for atom in residue.atoms())
if 'HD1' in names:
    variant = 'HIP' if 'HE2' in names else 'HID'
else:
    variant = 'HIE' if 'HE2' in names else 'HIN'
```

**Comment by ziyuanzhao2000** [comment]
Thanks, I did something just like that. Thanks for your example!
