### ISSUE TITLE
OpenMM Not Recognizing CPU/GPU Platforms

### ISSUE THREAD

**Issue by jaketanderson** [openmm/openmm#3646]
I'm running a simulation on a GPU cluster within the Open Science Pool. `nvidia-smi` shows that I have drivers and CUDA: `Driver Version: 495.29.05    CUDA Version: 11.5`. But when I run the function getNumPlatforms and enumerate through them to find the available platforms, I see only `Reference` -- neither `CPU` nor `GPU`. When I do the same on my PC with CUDA 11.7 and driver version 500+ I see both CPU and GPU available. I'm wondering, why might OpenMM not recognize that there is a GPU (and CPU) to be used here? Maybe someone could point me in the right direction?

**Comment by jaketanderson** [comment]
#### For reference:

What I get on the login node (which has a cpu as its only compute workhorse):

	Reference
	1.0
	CPU
	10.0

What I get on my personal computer (which has a cpu and a gpu):

	Reference
	1.0
	CPU
	10.0
	CUDA
	100.0
	OpenCL
	50.0

What I get on the remote GPU node (which has a cpu and gpu):

	Reference
	1.0
	
The remote GPU node doesn't show a cpu or gpu capability which is strange.

**Comment by peastman** [comment]
This indicates the plugins aren't getting loaded.  That could mean it's looking in the wrong directory for the plugins, or it might be getting an error while trying to load them.

Try executing these lines.

```python
from openmm import *
print(Platform.getPluginLoadFailures())
```

If it's getting errors loading plugins, that will tell us and hopefully provide information about why.  If it doesn't report any errors, then more likely it's looking in the wrong place for the plugins directory.  Try

```python
print(version.openmm_library_path)
```

It expects that directory to contain a subdirectory called "plugins" with all the plugin libraries.

**Comment by jaketanderson** [comment]
Here's the output:
`()
/home/conda/feedstock_root/build_artifacts/openmm_1646184847868/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib
`

I have no clue what's happening with the `placehold`s. Is there a straightforward way to manually set the plugins file path?

**Comment by peastman** [comment]
That's really strange.  How did you install it?

You can set the environment variable `OPENMM_PLUGIN_DIR` to point to your plugins directory.

**Comment by jaketanderson** [comment]
I'm using `conda-pack` to compress my conda environment. Then I transfer the compressed file and activate the environment on the node using the following:
`mkdir $ENVDIR`
`tar -xzf $ENVNAME.tar.gz -C $ENVDIR`
`. $ENVDIR/bin/activate`

Setting `OPENMM_PLUGIN_DIR` to the path $ENVDIR/lib seemed to do the trick. Many thanks, Peter!
