### ISSUE TITLE
OpenMM version and plugins

### ISSUE THREAD

**Issue by egallicc** [openmm/openmm#3648]
Is there a way to build a plugin against multiple OpenMM API versions? (In this case to support both the 7.6 and 7.7 context selector APIs by conditionally including `ComputeContext.h` depending on the version of the OpenMM API?)

Alternatively, is there a standard way to limit the building of a plugin to the specific set of OpenMM API versions that it supports?

Thanks!

**Comment by egallicc** [comment]
Thank you. Is there a way to access macros with the OpenMM library version numbers?

**Comment by peastman** [comment]
You can access conda macros inside your build script.  For example, the OpenMM recipe conditionally sets the variable `with_test_suite`:

https://github.com/conda-forge/openmm-feedstock/blob/d68725f149ed2b6cfdf89f3e197ba5d7f99f954f/recipe/meta.yaml#L4-L5

And then build_openmm.sh sets CMake variables based on it:

https://github.com/conda-forge/openmm-feedstock/blob/d68725f149ed2b6cfdf89f3e197ba5d7f99f954f/recipe/build_openmm.sh#L7-L11

There might be a simpler way, but this is already pushing the limits of my experience with conda recipes.

**Comment by peastman** [comment]
Closing this since I believe the question has been answered.  Feel free to reopen if I missed something.
