### ISSUE TITLE
Obtaining values of custom variables added in a `CustomIntegrator` using `Reporters`

### ISSUE THREAD

**Issue by shaunak-badani** [openmm/openmm#3650]
Hello,
     I'm trying to use the `CustomIntegrator` functionality. If I add a global variable, say `s` to the `CustomIntegrator`, is there a method of getting the value of this variable throughout the simulation by the use of a custom `DataReporter`? In a nutshell : 

```
self.addGlobalVariable("s", 0)
```
Is there any way to monitor this `s` using reporters?

**Comment by shaunak-badani** [comment]
Thank you for the reply, Mr. Eastman
1. The `getGlobalVariableByName` function can be used at the end of the simulation.If I were to use this function, I could do something along the lines of 
```
for i in range(nsteps):
    simulation.step(1)
    s = integrator.getGlobalVariableByName("s")
```
But I'm assuming this is slower than : 
```
simulation.step(nsteps)
```
2. The `customReporters` can only report the following, as far as I have read : 
* `positions`
* `velocities`
* `forces`
* `energies` - `PE, KE`
* `step`, `time`, `totalEnergy` ... basically everything stated [here](http://docs.openmm.org/latest/api-python/generated/openmm.app.statedatareporter.StateDataReporter.html#openmm.app.statedatareporter.StateDataReporter)

I don't know how to get the values of the custom variables through the standard reporters, or any of the custom reporters stated in the documentation.

**Comment by craabreu** [comment]
You can also extend `StateDataReporter` to incorporate selected `CustomIntegrator` variables:

```py
from openmm import app

class MyStateDataReporter(app.StateDataReporter):
    def __init__(self, file, report_interval, integratorVariables=[], **kwargs):
        self._vars = integratorVariables
        super().__init__(file, report_interval, **kwargs)

    def _constructHeaders(self):
        return super()._constructHeaders() + self._vars

    def _constructReportValues(self, simulation, state):
        getvar = simulation.context.getIntegrator().getGlobalVariableByName
        values = list(map(getvar, self._vars))
        return super()._constructReportValues(simulation, state) + values
```

**Comment by shaunak-badani** [comment]
This worked!

I was not aware of the fact that `context` contained a `getIntegrator` function.
Thank you.

**Comment by peastman** [comment]
> But I'm assuming this is slower than :

It should make very little difference.  If you call `step(n)`, it mostly just loops `n` times and calls a function to take each step.
