### ISSUE TITLE
N- and C-terminal residues from PDBx

### ISSUE THREAD

**Issue by jgninterline** [openmm/openmm#3653]
Hi,

I'm trying to simulate a system with more than 100K atoms so I need to use a PDBx file and the PDBxFile reader to build the system. I'd like to build with the ff14SB force field. When my script tries to run createSystem, I get the error:

"ValueError: No template found for residue 1 (MET).  This might mean your input topology is missing some atoms or bonds, or possibly that you are using the wrong force field."

Which makes sense since residue  1 is actually NMET, not MET, which is included in ff14SB.xml. How do I correct the residue name in either the input file or topology? 

Thanks!
Gard

**Comment by peastman** [comment]
See https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template for information about the causes of this error.  Can you post your file, or just quote the part defining the first couple of residues?

**Comment by jgninterline** [comment]
Thanks for your help. Yeah, I saw that page and the error makes sense. Its just not clear to me how to fix it. I generated the file with pymol from an old-format PDB. Here's the first 5 residues:

ATOM   1   N N   . MET C2 . 1 ? -34.817 -8.497 -66.492 1.00  39.61 0 A 1
ATOM   2   C CA  . MET C2 . 1 ? -35.282 -7.356 -65.625 1.00  39.61 0 A 1
ATOM   3   C C   . MET C2 . 1 ? -34.505 -7.410 -64.288 1.00  39.61 0 A 1
ATOM   4   O O   . MET C2 . 1 ? -33.917 -6.393 -63.921 1.00  39.61 0 A 1
ATOM   5   C CB  . MET C2 . 1 ? -36.818 -7.307 -65.430 1.00  39.61 0 A 1
ATOM   6   C CG  . MET C2 . 1 ? -37.584 -6.827 -66.674 1.00  39.61 0 A 1
ATOM   7   S SD  . MET C2 . 1 ? -39.362 -6.616 -66.404 1.00  39.61 0 A 1
ATOM   8   C CE  . MET C2 . 1 ? -39.750 -5.522 -67.796 1.00  39.61 0 A 1
ATOM   9   PS pseudo . MET C2 . 1 ? -39.309 -6.115 -65.923 0.00   0.00 0 A 1
ATOM   10  PS pseudo . MET C2 . 1 ? -39.559 -7.209 -66.713 0.00   0.00 0 A 1
ATOM   11  H HA  . MET C2 . 1 ? -34.954 -6.472 -66.176 0.00  39.61 0 A 1
ATOM   12  H HB2 . MET C2 . 1 ? -37.203 -8.275 -65.105 0.00  39.61 0 A 1
ATOM   13  H HB3 . MET C2 . 1 ? -37.058 -6.614 -64.621 0.00  39.61 0 A 1
ATOM   14  H HG2 . MET C2 . 1 ? -37.178 -5.867 -66.994 0.00  39.61 0 A 1
ATOM   15  H HG3 . MET C2 . 1 ? -37.444 -7.519 -67.505 0.00  39.61 0 A 1
ATOM   16  H HE1 . MET C2 . 1 ? -40.818 -5.305 -67.815 0.00  39.61 0 A 1
ATOM   17  H HE2 . MET C2 . 1 ? -39.209 -4.580 -67.705 0.00  39.61 0 A 1
ATOM   18  H HE3 . MET C2 . 1 ? -39.476 -5.994 -68.740 0.00  39.61 0 A 1
ATOM   19  H H1  . MET C2 . 1 ? -35.268 -8.420 -67.393 0.00  39.61 0 A 1
ATOM   20  H H2  . MET C2 . 1 ? -33.816 -8.437 -66.615 0.00  39.61 0 A 1
ATOM   21  H H3  . MET C2 . 1 ? -35.071 -9.375 -66.064 0.00  39.61 0 A 1
ATOM   22  N N   . GLU C2 . 2 ? -34.538 -8.543 -63.557 1.00  44.32 0 A 1
ATOM   23  C CA  . GLU C2 . 2 ? -33.965 -8.686 -62.215 1.00  44.32 0 A 1
ATOM   24  C C   . GLU C2 . 2 ? -32.517 -9.218 -62.219 1.00  44.32 0 A 1
ATOM   25  O O   . GLU C2 . 2 ? -32.108 -9.906 -61.284 1.00  44.32 0 A 1
ATOM   26  C CB  . GLU C2 . 2 ? -34.955 -9.476 -61.336 1.00  44.32 0 A 1
ATOM   27  C CG  . GLU C2 . 2 ? -36.263 -8.678 -61.112 1.00  44.32 0 A 1
ATOM   28  C CD  . GLU C2 . 2 ? -37.353 -9.416 -60.324 1.00  44.32 0 A 1
ATOM   29  O OE1 . GLU C2 . 2 ? -38.069 -8.721 -59.569 1.00  44.32 0 A 1
ATOM   30  O OE2 . GLU C2 . 2 ? -37.482 -10.648 -60.500 1.00  44.32 0 A 1
ATOM   31  H H   . GLU C2 . 2 ? -35.063 -9.340 -63.885 0.00  44.32 0 A 1
ATOM   32  H HA  . GLU C2 . 2 ? -33.881 -7.698 -61.758 0.00  44.32 0 A 1
ATOM   33  H HB2 . GLU C2 . 2 ? -35.169 -10.432 -61.817 0.00  44.32 0 A 1
ATOM   34  H HB3 . GLU C2 . 2 ? -34.511 -9.712 -60.368 0.00  44.32 0 A 1
ATOM   35  H HG2 . GLU C2 . 2 ? -36.025 -7.740 -60.607 0.00  44.32 0 A 1
ATOM   36  H HG3 . GLU C2 . 2 ? -36.707 -8.400 -62.068 0.00  44.32 0 A 1
ATOM   37  N N   . GLY C2 . 3 ? -31.738 -8.794 -63.232 1.00  39.16 0 A 1
ATOM   38  C CA  . GLY C2 . 3 ? -30.274 -8.867 -63.256 1.00  39.16 0 A 1
ATOM   39  C C   . GLY C2 . 3 ? -29.641 -7.783 -62.358 1.00  39.16 0 A 1
ATOM   40  O O   . GLY C2 . 3 ? -28.423 -7.776 -62.187 1.00  39.16 0 A 1
ATOM   41  H H   . GLY C2 . 3 ? -32.164 -8.230 -63.953 0.00  39.16 0 A 1
ATOM   42  H HA2 . GLY C2 . 3 ? -29.937 -9.854 -62.934 0.00  39.16 0 A 1
ATOM   43  H HA3 . GLY C2 . 3 ? -29.929 -8.727 -64.280 0.00  39.16 0 A 1
ATOM   44  N N   . SER C2 . 4 ? -30.464 -6.905 -61.750 1.00  45.35 0 A 1
ATOM   45  C CA  . SER C2 . 4 ? -30.105 -5.948 -60.704 1.00  45.35 0 A 1
ATOM   46  C C   . SER C2 . 4 ? -29.895 -6.610 -59.319 1.00  45.35 0 A 1
ATOM   47  O O   . SER C2 . 4 ? -29.760 -5.892 -58.332 1.00  45.35 0 A 1
ATOM   48  C CB  . SER C2 . 4 ? -31.175 -4.832 -60.681 1.00  45.35 0 A 1
ATOM   49  O OG  . SER C2 . 4 ? -30.793 -3.739 -59.867 1.00  45.35 0 A 1
ATOM   50  H H   . SER C2 . 4 ? -31.452 -6.961 -61.955 0.00  45.35 0 A 1
ATOM   51  H HA  . SER C2 . 4 ? -29.153 -5.493 -60.985 0.00  45.35 0 A 1
ATOM   52  H HB2 . SER C2 . 4 ? -31.342 -4.449 -61.689 0.00  45.35 0 A 1
ATOM   53  H HB3 . SER C2 . 4 ? -32.132 -5.220 -60.330 0.00  45.35 0 A 1
ATOM   54  H HG  . SER C2 . 4 ? -30.716 -4.050 -58.961 0.00  45.35 0 A 1
ATOM   55  N N   . GLY C2 . 5 ? -29.818 -7.953 -59.254 1.00  38.57 0 A 1
ATOM   56  C CA  . GLY C2 . 5 ? -29.414 -8.704 -58.062 1.00  38.57 0 A 1
ATOM   57  C C   . GLY C2 . 5 ? -27.921 -8.505 -57.728 1.00  38.57 0 A 1
ATOM   58  O O   . GLY C2 . 5 ? -27.529 -8.733 -56.586 1.00  38.57 0 A 1
ATOM   59  H H   . GLY C2 . 5 ? -29.959 -8.490 -60.098 0.00  38.57 0 A 1
ATOM   60  H HA2 . GLY C2 . 5 ? -30.026 -8.407 -57.209 0.00  38.57 0 A 1
ATOM   61  H HA3 . GLY C2 . 5 ? -29.600 -9.764 -58.236 0.00  38.57 0 A 1

**Comment by peastman** [comment]
What are these lines meant to represent?

```
ATOM 9 PS pseudo . MET C2 . 1 ? -39.309 -6.115 -65.923 0.00 0.00 0 A 1
ATOM 10 PS pseudo . MET C2 . 1 ? -39.559 -7.209 -66.713 0.00 0.00 0 A 1
```

I think they're the cause of the problem.  They look like maybe they're meant to represent some kind of virtual site, but Amber14 doesn't use virtual sites, and the other residues don't have anything like that.

**Comment by jgninterline** [comment]
Pymol must have added the pseudos. There are two for each sulfur atom in the structure. I deleted them all and tried rerunning the simulation, but it still crashes with the same error. Here's the offending Met now:

ATOM   1   N N   . MET C2 . 1 ? -34.817 -8.497 -66.492 1.00  39.61 0 A 1
ATOM   2   C CA  . MET C2 . 1 ? -35.282 -7.356 -65.625 1.00  39.61 0 A 1
ATOM   3   C C   . MET C2 . 1 ? -34.505 -7.410 -64.288 1.00  39.61 0 A 1
ATOM   4   O O   . MET C2 . 1 ? -33.917 -6.393 -63.921 1.00  39.61 0 A 1
ATOM   5   C CB  . MET C2 . 1 ? -36.818 -7.307 -65.430 1.00  39.61 0 A 1
ATOM   6   C CG  . MET C2 . 1 ? -37.584 -6.827 -66.674 1.00  39.61 0 A 1
ATOM   7   S SD  . MET C2 . 1 ? -39.362 -6.616 -66.404 1.00  39.61 0 A 1
ATOM   8   C CE  . MET C2 . 1 ? -39.750 -5.522 -67.796 1.00  39.61 0 A 1
ATOM   11  H HA  . MET C2 . 1 ? -34.954 -6.472 -66.176 0.00  39.61 0 A 1
ATOM   12  H HB2 . MET C2 . 1 ? -37.203 -8.275 -65.105 0.00  39.61 0 A 1
ATOM   13  H HB3 . MET C2 . 1 ? -37.058 -6.614 -64.621 0.00  39.61 0 A 1
ATOM   14  H HG2 . MET C2 . 1 ? -37.178 -5.867 -66.994 0.00  39.61 0 A 1
ATOM   15  H HG3 . MET C2 . 1 ? -37.444 -7.519 -67.505 0.00  39.61 0 A 1
ATOM   16  H HE1 . MET C2 . 1 ? -40.818 -5.305 -67.815 0.00  39.61 0 A 1
ATOM   17  H HE2 . MET C2 . 1 ? -39.209 -4.580 -67.705 0.00  39.61 0 A 1
ATOM   18  H HE3 . MET C2 . 1 ? -39.476 -5.994 -68.740 0.00  39.61 0 A 1
ATOM   19  H H1  . MET C2 . 1 ? -35.268 -8.420 -67.393 0.00  39.61 0 A 1
ATOM   20  H H2  . MET C2 . 1 ? -33.816 -8.437 -66.615 0.00  39.61 0 A 1
ATOM   21  H H3  . MET C2 . 1 ? -35.071 -9.375 -66.064 0.00  39.61 0 A 1

I manually deleted Met1 from the file and reran the script. It still give me the same error, but now about a Thr way down the sequence. Unlike the Met, this Thr is not a terminal residue. I looked up both residues (NMET and THR) in ff14SB.xml and all the atom names are exactly the same. I'm stumped about why these two residues are giving errors and the other ones aren't.

**Comment by jgninterline** [comment]
Here's a similar system that was prepared in the same way and gives similar errors. And here's an excerpt from my script:

omm_forcefield = ForceField("amber/ff14SB.xml", "amber/lipid17.xml", "amber14/tip3pfb.xml")
receptor = PDBxFile(receptor_path)
modeller = Modeller(receptor.topology, receptor.positions)
modeller.addHydrogens(omm_forcefield)
system = omm_forcefield.createSystem(
                modeller.topology,
                nonbondedMethod=PME,
                nonbondedCutoff=nb_cutoff,
                constraints=HBonds,
                rigidWater=True,
                hydrogenMass=H_mass
)

Thanks!

[full.cif.zip](https://github.com/openmm/openmm/files/8960421/full.cif.zip)

**Comment by jgninterline** [comment]
Awesome, thanks!

Yeah, I assumed that since CYX, POPC, etc. are in the ff14SB and lipid17 force field files that it'd be ok to leave them in there. I can reformat that if needed, but it'd be great if PDBxFile() did it automatically. What is the proper procedure for protonated residues like Asp or non-standard protonation states of His? Again the amber FF has special residues for these but I need to be sure I'm treating them correctly in my input structure and script.

As far as the OXT goes, it looks like both chains are missing residue 238, leading to two chain breaks and the two extra OXT's. If this were my real system, I'd model residue 238 back in for sure, but as it is, that missing residue shouldn't break things, right? I have had modeller be finicky about OXT's in the past. Pretending we wanted to leave that chain break there, what would be the best way to treat this?

**Comment by peastman** [comment]
All residue and atom names should follow the PDB chemical components dictionary.  That means the name doesn't change with protonation state.  Amber has its own special names for variants (CYX instead of CYS, GLH instead of GLU, etc.), but standard file formats like PDB and PDBx/mmCIF should use the standard names regardless of which hydrogens are present.

> Pretending we wanted to leave that chain break there, what would be the best way to treat this?

The chain ID (`auth_asym_id`) should change at the start of a new chain.  That's the second to last column in your file.  It should change from `A` to `B` (or anything else).  It's good form if `label_asym_id` changes too (the seventh column in your file).

**Comment by peastman** [comment]
#3659 has the changes to automatically replace nonstandard names.
