### ISSUE TITLE
ValueError: AmoebaMultipoleForce: input cutoff method not available

### ISSUE THREAD

**Issue by ShahbazQalandar** [openmm/openmm#3657]
I am trying to use Amoeba forcefield for simulation. First I run with AMBER forcefield and there was no error. When I change the forcefield to AMOEBA I got the following error

Traceback (most recent call last):
  File "test1.py", line 39, in <module>
    modeller.addHydrogens(forcefield)
  File "/home/basit/anaconda3/lib/python3.7/site-packages/simtk/openmm/app/modeller.py", line 947, in addHydrogens
    system = forcefield.createSystem(newTopology, rigidWater=False, nonbondedMethod=CutoffNonPeriodic)
  File "/home/basit/anaconda3/lib/python3.7/site-packages/simtk/openmm/app/forcefield.py", line 1328, in createSystem
    force.createForce(sys, data, nonbondedMethod, nonbondedCutoff, args)
  File "/home/basit/anaconda3/lib/python3.7/site-packages/simtk/openmm/app/forcefield.py", line 4951, in createForce
    raise ValueError( "AmoebaMultipoleForce: input cutoff method not available." )
ValueError: AmoebaMultipoleForce: input cutoff method not available.

My inputs are as follow:

pdb = PDBFile('test.pdb')
forcefield = app.ForceField('amoeba2013.xml')
#forcefield = app.ForceField('amber99sbildn.xml', 'tip3p.xml')
modeller = Modeller(pdb.topology, pdb.positions)
modeller.addHydrogens(forcefield)
modeller.addSolvent(forcefield,padding=1.0*nanometers,ionicStrength=0.1*molar)
system = forcefield.createSystem(modeller.topology,nonbondedMethod=PME)
integrator = LangevinMiddleIntegrator(300*kelvin, 1/picosecond, 0.001*picoseconds)
barostat = MonteCarloBarostat(1.0*bar, 300.0*kelvin, 25)
system.addForce(barostat)
platform = Platform.getPlatformByName('CUDA')
properties = {'CudaPrecision': 'mixed'}

simulation = Simulation(modeller.topology, system, integrator, platform, properties)
simulation.context.setPositions(modeller.positions)

simulation.reporters.append(PDBReporter('min.pdb', 50))
simulation.reporters.append(StateDataReporter('min_data.csv', 100, time=True, kineticEnergy=True, potentialEnergy=True, temperature=True,separator='\t',))

simulation.minimizeEnergy()
positions = simulation.context.getState(getPositions=True).getPositions()
PDBFile.writeFile(simulation.topology, positions, open('minimized.pdb', 'w'))
simulation.step(100)

**Comment by peastman** [comment]
Closing this since I believe the question has been answered.  Feel free to reopen if I missed something.
