### ISSUE TITLE
OpenMM nightly dev builds are not longer updating

### ISSUE THREAD

**Issue by zhang-ivy** [openmm/openmm#3669]
The latest build was from > 2 months ago: https://anaconda.org/omnia-dev/openmm/files

**Comment by zhang-ivy** [comment]
cc: @jchodera @peastman

**Comment by peastman** [comment]
I don't know what's up with them.  We do have a new dev build getting built right now at `conda-forge/label/openmm_dev` thanks to https://github.com/conda-forge/openmm-feedstock/pull/79.

**Comment by zhang-ivy** [comment]
Ah, thanks for the pointer! For anyone else that's interested in installing the 7.7.0dev1 build from conda forge, I was able to install using: `mamba install -c conda-forge/label/openmm_dev openmm=7.7.0dev1`

I'll keep this issue open for now, since we the omnia-dev builds are still broken

**Comment by jchodera** [comment]
Looks like it might have just been some sort of azure timeout. I've tried to re-run the azure pipelines and make sure the nightlies were still scheduled. But I am hoping we can move to conda-forge `dev` builds.

**Comment by jchodera** [comment]
It looks like [nightly dev builds are being pushed now](https://anaconda.org/omnia-dev/openmm/files).

**Comment by jchodera** [comment]
I can confirm they are updating nightly now.

**Comment by zhang-ivy** [comment]
Great, thank you!!
