### ISSUE TITLE
 Unit of the CustomForce including charges in the OpenMM?

### ISSUE THREAD

**Issue by mdionic** [openmm/openmm#3672]
Hi,
I recently want to add the Tang-Toennies  function for the electrostatic interaction between some hydrogen atoms and dipoles in the drude-based polarizable force field using OpenMM. The electrostatic interactions are calculated using PEM method. I know the unit of " energy" in the OpenMM is "kJ/mol". But when using the [Coulomb interaction](http://docs.openmm.org/latest/userguide/theory/02_standard_forces.html), the "/mol"  in unit disappear, so I have some questions as follows:
1. The unit of energy in the CustomNonbondedForce is "kJ/mol"? But I find an example code in  the Peter's presentation slides (2012) like this:
```
# Create the force
force = CustomExternalForce(“10*((x-x0)^2+(y-y0)^2+(z-z0)^2)")
force.addPerParticleParameter("x0")
force.addPerParticleParameter("y0")
force.addPerParticleParameter("z0")
# Bind particle 5 to the location (0, 1, -0.5) nm
force.addParticle(5, (0, 1, -0.5)*nanometers)
```
The "/mol" in the unit also disappears. So the OpenMM will add it automatically?

2. I want to first use the PME to calculate  the electrostatic forces of all the particles, and then use the CustomNonbondedforce to modify the electrostatic forces between hydrogen atom and dipoles under the certain cut-off. Is it rational? Because the PME is under periodic boundary conditions, it considers the image particles.

**Comment by peastman** [comment]
I don't understand what you mean when you say it disappears.  The only unit that appears in the code you quoted is a distance, measured in nanometers.

Units are part of the Python API.  Custom forces are implemented in C++, so they don't know about units.  They expect all quantities to have the standard units described in [the user guide](http://docs.openmm.org/latest/userguide/theory/01_introduction.html#units).  If you pass in a quantity with units attached, it will automatically convert it to standard units.  In the code above, if you specified the position as `(0, 10, -5)*angstroms`, it would automatically divide by 10 to convert to nanometers.  But no units appear within the energy expression itself.  It assumes everything has standard units.  For example, the `10` at the start of the expression is interpreted as being 10 kJ/mol/nm^2.

For item 2, can you describe how you want to modify the force?  Each Force object is treated independently.  It computes its own contribution to the potential function, and all the contributions get added together.  The CustomNonbondedForce can't modify the energy computed by the NonbondedForce.  But you know what the form of Coulomb is, so you can write an expression for a correction that gives the result you want when added to the standard Coulomb force.

**Comment by mdionic** [comment]
@peastman  Thanks a lot! I think I understand the unit problem with your explanations. I want to modify the electrostatic interactions between some hydrogen atoms and dipoles by a short-range damping function to avoid the simulation explosion. I think it is just like the Thole damping functions in the CHARMM polariazble force field.The function is

![ ](https://latex.codecogs.com/svg.image?\frac{q_1q_2}{4r\pi\epsilon_0}(1-t(r)))
and t(r) satisfies 
![](https://latex.codecogs.com/svg.image?t(r)=e^{-br}(1&plus;br&plus;(br)^2/2&plus;(br)^3/6&plus;(br)^4/24))
**And I want to know if the CustomNonbondedForce API is suitable for this correction.** Do I need to write additional plugin to realize this? Because the standard Coulomb force  in the system can be calculated with PME (its "cutoff" is set 1.2 nm), which consider the all the periodic image particles in the calculations, but the CustomNonbondedForce uses CustomNonbondedForce.CutoffPeriodic. The CustomNonbondedForce core codes are as follows:   
```
...
ttf =openmm.CustomNonbondedForce('-1*const*q1*q2/r*c1*c2;'
                                      'c1=exp(-br);'
                                      'c2=1+br+br*br/2+br2*br/6+br2*br2/24;'
                                      'br2=br*br;'
                                      'br=b*r')
#e^2*NA/(4*PI*epsilon_0*1e-9m*1000)=138.8860506kJ/mol
ttf.addGlobalParameter('const',138.8860506*openmm.unit.kilojoule/openmm.unit.mole)
ttf.addGlobalParameter('b',45.0/nanometer)
ttf.addPerParticleParameter('q')
...
```
where NA in the comment is the Avogadro constant. 

Thanks a lot!

**Comment by peastman** [comment]
Is this intended to apply to all atoms, or just limited pairs?  DrudeForce already provides Thole damping between a restricted set of pairs.  See http://docs.openmm.org/latest/api-c++/generated/DrudeForce.html.

**Comment by mdionic** [comment]
@peastman  It's for limited pairs (some hydrogen atoms with the Drude  and its parent particles). The Thole damping function in the DrudeForce is not the same as mine. So how  do I realize it in OpenMM? Write a plugin like DrueForce? 

Thank you!

**Comment by peastman** [comment]
If it's just for a restricted set of pairs, you probably want to use CustomBondForce.  That way you can enumerate exactly which sets of particles it should be applied to.  CustomNonbondedForce involves every particle interacting with every other, which isn't what you want.

**Comment by peastman** [comment]
Closing this since I believe the question has been answered.  Feel free to reopen if I missed something.
