### ISSUE TITLE
Saving forces

### ISSUE THREAD

**Issue by kostalv** [openmm/openmm#3673]
Hi,

I would like to follow the force components on each atom during the molecular dynamics run (AMOEBA in Tinker-OpenMM). However, the keyword "save-force" appends the same values in each dynamics step. I observe this issue only using GPU via OpenMM interface. Could you please advise me how to get the forces in each step properly?

Thanks in advance!

**Comment by peastman** [comment]
I don't know how it's done in Tinker-OpenMM.  You should ask the developers at https://github.com/TinkerTools/Tinker.  When using OpenMM directly, you can save forces with the method described [here](http://docs.openmm.org/latest/userguide/application/04_advanced_sim_examples.html#extracting-and-reporting-forces-and-other-data).
