### ISSUE TITLE
Fixed specific particles during integrating system

### ISSUE THREAD

**Issue by zhenyuwei99** [openmm/openmm#3674]
Hi,
I am trying to run a simulation with several fixed charges but I am not very clear on how to achieve this. I think we only need to skip the position updating of these particles, which means it will be the job of the integrator. I am not very sure can this be achieved in the openmm

Best,

**Comment by peastman** [comment]
Set the mass of the particle to 0.  The integrator will never move it.

**Comment by peastman** [comment]
Correct.  It checks for massless particles and skips them.

**Comment by zhenyuwei99** [comment]
Cool. I think all questions has been solved.

**Comment by mdionic** [comment]
Hi,
I want to fixed the positions of atom nucleus (AN)  except the Drude particles in the polarizable force fields. I set the mass of AN and Drude particles  to zero and 0.4 amu, respectively. But the simulations are soon blow up. Is there any methods to solve this? 
@peastman

**Comment by peastman** [comment]
The FAQ has advice on ways to debug simulations blowing up: https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#nan

**Comment by mdionic** [comment]
Thank you, Peter!
