### ISSUE TITLE
Specified a Platform for a Context which does not support all required kernels

### ISSUE THREAD

**Issue by danielpert** [openmm/openmm#3677]
I am trying to run a simulation on a GPU using CUDA but am running into this error:

Traceback (most recent call last):
  File "../src/biased_simulation.py", line 277, in <module>
    run_simulation(args.force_constant)
  File "../src/biased_simulation.py", line 222, in run_simulation
    simulation = Simulation(modeller.topology, system, integrator, platform)
  File "XXXX/lib/python3.8/site-packages/simtk/openmm/app/simulation.py", line 103, in __init__
    self.context = mm.Context(self.system, self.integrator, platform)
  File "XXXX/openmm-7.5.0-jqi6xufw5yoxhm3mtam5vw3b42hx54q6/lib/python3.8/site-packages/simtk/openmm/openmm.py", line 15587, in __init__
    _openmm.Context_swiginit(self, _openmm.new_Context(*args))
**simtk.openmm.OpenMMException: Specified a Platform for a Context which does not support all required kernels**

According to this GitHub issue: https://github.com/openmm/openmm-plumed/issues/10, this is solved by using Platform.loadPluginsFromDirectory() with the directory where the OpenMMPlumed**.so files are located, but I am already doing this and loading the following plugins:

libOpenMMAmoebaCUDA.so       libOpenMMCudaCompiler.so    libOpenMMOpenCL.so        libOpenMMPlumedReference.so
libOpenMMAmoebaReference.so  libOpenMMDrudeCUDA.so       libOpenMMPME.so           libOpenMMRPMDCUDA.so
libOpenMMCPU.so              libOpenMMDrudeOpenCL.so     libOpenMMPlumedCUDA.so    libOpenMMRPMDOpenCL.so
libOpenMMCUDA.so             libOpenMMDrudeReference.so  libOpenMMPlumedOpenCL.so  libOpenMMRPMDReference.so

I checked Platform.getPluginLoadFailures() and there are no failures for the shared object files.

**Comment by peastman** [comment]
I see you opened an identical issue at https://github.com/openmm/openmm-plumed/issues/59.  Is this using the PLUMED plugin?  If so, let's close this issue and discuss it on the other one.

**Comment by danielpert** [comment]
Yes, I am using the PLUMED plugin.
