### ISSUE TITLE
Why implementing pbc with bond force is not appropriate

### ISSUE THREAD

**Issue by zhenyuwei99** [openmm/openmm#3679]
Hi, I am trying to implement a sio2 with infinite length in the x and y dimension, which means I will have several bonds go across the pbc box boundary. I initially create the system and minimize the system and found the sio2 plane shrunk to a cylinder which seems the pbc is not considered in the bond force. So I checked the doc and found:
> Set whether this force should apply periodic boundary conditions when calculating displacements. Usually, this is not appropriate for bonded forces, but there are situations when it can be useful.

It's quite strange for me as I think we always need to consider the pbc issues in almost every case suppose a molecule, water, for example, goes through the boundary. I am quiet interesting about how does openmm dealing with these condition and why this implementation is not appropriate.

Best,

**Comment by peastman** [comment]
What is a sio2?

See [the FAQ](https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#periodic) for a discussion of how periodic boundary conditions work.  I think it will clarify what's going on.

**Comment by aizvorski** [comment]
@zhenyuwei99 "always need to consider the pbc issues in almost every case" - I think this is essentially because if a molecule is not bonded to a copy of itself, then bonds don't need to know about pbc.

If you're simulating an infinite bonded structure (like I assume you're trying to do with silicon dioxide or SiO2), then you need bonds with pbc.  It would be quite interesting to have an example of that in openmm.

**Comment by zhenyuwei99** [comment]
@peastman @aizvorski Thanks for the reply. I think the reason why I think it is a bit weird for me is that I always believe in each step we will wrap the positions of each particle into a box within the volume of the center pbc images. So I will think the bond between two particles across the pbc boundary will still be the original one (wrapped during the integration) instead of the particle with an image copy. 
However, if we do this in the openmm, we never need the `enforcePeriodic` keywords in the reporter. So I am not very sure whether this physical picture matches the real implementation in the openmm.

**Comment by aizvorski** [comment]
@zhenyuwei99 "in each step we will wrap the positions of each particle into a box within the volume of the center pbc images" - Ah, I see.  pbc applies to displacements, see this section in the FAQ "Periodic boundary conditions are applied to displacements, not positions" that Peter linked above.  Whether particles are wrapped (this is also called "re-imaging" or moving from one copy of the periodic box to another) has no effect on the forces which depend on the displacement only; you can add or subtract the box vectors any number of times to any subset of particles and it doesn't change the calculated force.  Molecules (sets of particles connected with bonds) are guaranteed to be imaged into the same copy of the periodic box, whether they *fit in* that copy of the box or not.  Earlier versions of openmm (I believe pre 7.7.0) would occasionally reimage whole molecules (I think whenever any particle in the molecule crossed a box boundary) but newer versions simply don't reimage.

**Comment by peastman** [comment]
One other detail is that it may internally store the positions differently from how they're reported in the API.  To increase accuracy, it often will internally store a position as a location within a single periodic box, along with an integer number of box vectors to displace it by.  That's important for accuracy when working in single precision.  But other than numerical precision, it makes no difference to forces.  Even if it stored a position many box copies away from the origin, that would still represent the same grid of particles.

**Comment by zhenyuwei99** [comment]
@aizvorski Thanks for the detailed explanation. I think there are two paradigms for handling the pbc issues:
- We re-image the positions in each timestep and we need to treat the bond with considering the pbc issues. And in this case, the displacement between two particles will never be greater than the size of the pbc box on the corresponding dimension. And the bonded molecules will cross the pbc box as it has been re-imaged.
- We do not reimage the positions in each step and warp the displacement from any range to the range between the single pbc box range. In this case, we only need to consider the pbc for the nonbonded part as the bonded particle will always be closed to each other.
I get the first picture all the time so:
> Set whether this force should apply periodic boundary conditions when calculating displacements. Usually, this is not appropriate for bonded forces, but there are situations when it can be useful.

is a bit weird for me. But the comment will be nature for the second picture.
And I think this is really important @peastman 
> To increase accuracy, it often will internally store a position as a location within a single periodic box, along with an integer number of box vectors to displace it by.

As the displacement could be the subtraction of two very large numbers, yielding some error, when the simulation time becomes very long if we use the second picture.

**Comment by zhenyuwei99** [comment]
I am not pretty sure whether there is a performance balance between choosing which paradigm or whether it is a tradition in MD engines? I believe AMBER also uses the second picture which does not re-image in each step. 
Meanwhile, suppose we want to divide the space and construct the neighbor list or cell list, wrapped positions will be beneficial.

**Comment by peastman** [comment]
The performance difference should be minimal.  Applying periodic boundary conditions adds a few extra instructions to each bonded force calculation, but that's a tiny overhead compared to other parts of computing a time step.

**Comment by zhenyuwei99** [comment]
So it's mainly a traditional choice and the quote:

>  Usually, this is not appropriate for bonded forces, but there are situations when it can be useful.

is nature in this paradigm. That will make sense to me.

Many thanks for the detailed explanation.

**Comment by zhenyuwei99** [comment]
Sure, this will be definitely essential if we do not wrap the positions of macromolecules in a single pbc box. But I am curious if we have a diffused system (I mean the particles may distributed in different pbc boxes), how can we divide the space to construct the cell list or find particles close to each other?

**Comment by peastman** [comment]
Different platforms use different algorithms to build the neighbor list, and of course they work differently depending on whether the NonbondedForce is set to use periodic boundary conditions.  The details are a bit complicated.

But we were talking about bonded forces, which of course don't use a neighbor list.  They just loop over every bond you've specified.  And each one indicates a bond between a specific set of particles, not between a particle and periodic copies of the other one.  If you interpreted it like that, it would imply that the bond between two particles could spontaneously break and be transferred to a different pair of particles.
