### ISSUE TITLE
Pressure ramp and/or volume ramp in OpenMM

### ISSUE THREAD

**Issue by kong1-731** [openmm/openmm#3683]
Is there a way to apply a pressure ramp in OpenMM? I would like to change the pressure over the simulation. It is possible to apply a linear pressure ramp in LAMMPS using fix npt and changing the Pstart and Pstop, but I am not sure if there is something similar that could be developed/I could implement in OpenMM to accomplish the same thing.
Along the same line, is it possible to change the volume of the system over the course of the simulation similar to fix deform in LAMMPS?

**Comment by peastman** [comment]
Yes, you can do both of them.  The current pressure is stored as a parameter in the context.  Your code might look something like this.

```python
for step in range(steps):
    simulation.context.setParameter(barostat.Pressure(), pstart+(pstop-pstart)*step/(steps-1))
    simulation.step(1000)
```

Changing the box volume is similar, but instead of `setParameter()` you'll call [`setPeriodicBoxVectors()`](http://docs.openmm.org/latest/api-python/generated/openmm.openmm.Context.html#openmm.openmm.Context.setPeriodicBoxVectors).  If you want a cubic box of volume `v` (measured in nm^3), the code would be

```python
width = v**(1/3)
simulation.context.setPeriodicBoxVectors((width, 0, 0), (0, width, 0), (0, 0, width))
```

**Comment by peastman** [comment]
You can do it however you want.  In the example above I call `simulation.step(1000)` after each call to `setParameter()`.  That means it changes the pressure and then takes 1000 steps before the next pressure change.  You can change it however frequently you want.  And you can change it over the full length of the simulation, or you can take additional steps before and/or after.  It's all just Python code.  Likewise, you can calculate the value you pass to `setParameter()` however you want.  In that example it's a linear function of step index, but it can be anything you want.

**Comment by kong1-731** [comment]
Thank you; that makes sense!

**Comment by kong1-731** [comment]
I have a quick question regrading setting the volume using setPeriodicBoxVectors(). I keep getting an error that the box is blowing up (with particle coordinate nan), so I started by setting the periodic box vectors to the results of system.getDefaultPeriodicBoxVectors(), which was ~ 8.4 nm in the x direction, 8.4 in the y direction, and 10 nm in the z direction. However, I printed the volume of the box via the state reporter and noticed that the volume hovers around 514 nm^3. Since these box dimensions are incongruous with the volume, does system.getDefaultPeriodicBoxVectors() give the XYZ vectors from the restart file that I started the simulation with or from the initial pdb coordinates? I am not sure how to print out the current X, Y, and Z box lengths.

**Comment by peastman** [comment]
The default box vectors come from the PDB.  If you want to check the current box vectors, you can use `context.getState().getPeriodicBoxVectors()`.

**Comment by kong1-731** [comment]
Thank you!

**Comment by kong1-731** [comment]
When I am applying a pressure ramp, I realized that because a pressure tensor is not given as output in OpenMM, I am not sure how to verify that my pressure ramp is working properly. I noticed issue #3647 discussing the calculation of the pressure tensor, but I was wondering how OpenMM evaluates whether the pressure control function is working properly and is near the target if it does not internally calculate the pressure at all. Is there some way to access OpenMM's internal pressure check easily? Also, would it be possible to control the pressure in OpenMM along axes (or in other words specify the pressure tensor Pxx, Pyy, Pzz, etc)?

**Comment by peastman** [comment]
It doesn't have any internal check.  It implements an algorithm that's known to lead to correct results.  We do have some test cases to verify that it produces expected volumes in some known cases.  See https://github.com/openmm/openmm/blob/master/tests/TestMonteCarloBarostat.h.

To apply a different pressure along each axis, see [MonteCarloAnisotropicBarostat](http://docs.openmm.org/latest/api-c++/generated/MonteCarloAnisotropicBarostat.html).  It defines three context parameters you can set to control the three pressures.

**Comment by kong1-731** [comment]
Thank you. I see. Does OpenMM track the constraint forces and bondlengths for the SHAKE algorithm so that this information could be accessed and added to the virial term? I noticed that in LAMMPS it is mentioned that the virial terms associated with the SHAKE constraints should be added, but I am not sure if it is possible to access this information.

**Comment by peastman** [comment]
No, it doesn't record constraint forces.  In some constraint algorithms, they're never even calculated explicitly.

**Comment by kong1-731** [comment]
Oh thank you!

**Comment by kong1-731** [comment]
I have a question regarding the pressure ramp. I keep getting the following error:

```
  File "openmm_run_89.py", line 187, in <module>
    simulation.context.setParameter(barostat.Pressure(), 5)
AttributeError: 'function' object has no attribute 'Pressure'
```
with this code: 

```
system = barostat(system, inputs)
simulation.context.setParameter(barostat.Pressure(), 5).
```
where the relevant inputs are as follows:
```
p_ref       = 1.0                               # Pressure (Pref or Pxx, Pyy, Pzz; bar)
p_type      = membrane                          # MonteCarloBarostat type
p_XYMode    = XYIsotropic                       # For MonteCarloMembraneBarostat
p_ZMode     = ZFree                             # For MonteCarloMembraneBarostat
p_tens      = 0.0                               # Sulface tension for MonteCarloMembraneBarostat (dyne/cm)
p_freq      = 100                               # Pressure coupling frequency (steps)
```


I originally tried to change the pressure over time with the following code and got the same error:
```
for i in range(inputs.nstep):
            desired_sinP = p_initial+p_amplitude*sin(2*math.pi*i/p_tau)
            simulation.context.setParameter(barostat.Pressure(), desired_sinP)
            simulation.step(1)
```

`Traceback (most recent call last):
  File "openmm_sinP_88.py", line 179, in <module>
    simulation.context.setParameter(barostat.Pressure(), desired_sinP)
AttributeError: 'function' object has no attribute 'Pressure'`


Is there another way I should be instantiating the MonteCarloBarostat in order to modulate the pressure during the simulation? Thank you!

**Comment by peastman** [comment]
It appears you've defined a function called `barostat()` that adds a barostat to the system?  The error means exactly what it says: the function you've defined doesn't have any attribute called `Pressure`.  You probably mean to be calling it on the barostat object you created, not on the function you defined.

**Comment by kong1-731** [comment]
I see. Should I still instantiate the barostat object with the reference pressure and some pressure frequency and then call simulation.context.setParameter to change the pressure?

**Comment by kong1-731** [comment]
I'm not sure if it is preferable to set up the barostat with a reference pressure and then have my changing pressure for loop or just to set up the barostat inside the for loop.

Would these two methods end up with the same result?

```
for i in range(inputs.nstep):
            desired_sinP = p_initial+p_amplitude*sin(2*math.pi*i/p_tau)
            barostat = MonteCarloMembraneBarostat(desired_sinP*bar, inputs.p_tens*bar*nanometers, inputs.temp*kelvin, inputs.p_XYMode, inputs.p_ZMode, inputs.p_freq)
```

```
barostat = MonteCarloMembraneBarostat(p_ref*bar, inputs.p_tens*bar*nanometers, inputs.temp*kelvin, inputs.p_XYMode, inputs.p_ZMode, inputs.p_freq)
for i in range(inputs.nstep):
            desired_sinP = p_initial+p_amplitude*sin(2*math.pi*i/p_tau)
            simulation.context.setParameter(barostat.Pressure(), desired_sinP)
            simulation.step(1)
```

**Comment by peastman** [comment]
Neither one of those will work.  You need to add the barostat to the System or it has no connection to the simulation.  And you need to add it before you create the Simulation.  Your code should look something like this.

```python
barostat = MonteCarloMembraneBarostat(...)
system.addForce(barostat)
...
simulation = Simulation(topology, system, integrator)
...
for i in range(steps):
    pressure = ...
    simulation.context.setParameter(barostat.Pressure(), pressure)
    simulation.step(1)
```

**Comment by kong1-731** [comment]
Thank you. If I wanted to control the pressure in the X, Y, and Z directions separately and modulate them over time, would I have to do the following?

barostat = MonteCarloAnisotropicBarostat( inputs.p_ref*bar, inputs.temp*kelvin, inputs.p_scale[0], inputs.p_scale[1], inputs.p_scale[2], inputs.p_freq )
system.addForce(barostat)
...
simulation = Simulation(topology, system, integrator)
...
for i in range(steps):
    pressureX = i*...
    pressureY = i*...
    pressureZ = i*...
    simulation.context.setParameter(barostat.PressureX(), pressureX)
    simulation.context.setParameter(barostat.PressureY(), pressureY)
    simulation.context.setParameter(barostat.PressureZ(), pressureZ)
    simulation.step(1)

**Comment by peastman** [comment]
Exactly.

**Comment by UmeshRoy** [comment]
> Neither one of those will work. You need to add the barostat to the System or it has no connection to the simulation. And you need to add it before you create the Simulation. Your code should look something like this.
> 
> ```python
> barostat = MonteCarloMembraneBarostat(...)
> system.addForce(barostat)
> ...
> simulation = Simulation(topology, system, integrator)
> ...
> for i in range(steps):
>     pressure = ...
>     simulation.context.setParameter(barostat.Pressure(), pressure)
>     simulation.step(1)
> ```

I have defined pressure RAMP as follows:
**barostat = MonteCarloBarostat(1.0*bar, 298.0*kelvin, 25)**
system.addForce(barostat)
simulation = Simulation(pdb.topology, system, integrator, platform)
pstart = 1.0
pstop = 100
psteps= 10
for ps in range(psteps):
    simulation.context.setParameter(barostat.Pressure(), pstart+(pstop-pstart)*ps/(psteps-1))
    simulation.step(10000)

How would I make sure the unit of pressure here? Can you please clarify here?

Thank you.

Umesh


Thank you.

**Comment by peastman** [comment]
Correct.  See [the API docs](http://docs.openmm.org/latest/api-python/generated/openmm.openmm.MonteCarloBarostat.html#openmm.openmm.MonteCarloBarostat.Pressure).

**Comment by UmeshRoy** [comment]
Thank you. Now got it.

**Comment by gabriela-correa** [comment]
> Yes, you can do both of them. The current pressure is stored as a parameter in the context. Your code might look something like this.
> 
> ```python
> for step in range(steps):
>     simulation.context.setParameter(barostat.Pressure(), pstart+(pstop-pstart)*step/(steps-1))
>     simulation.step(1000)
> ```
> 
> Changing the box volume is similar, but instead of `setParameter()` you'll call [`setPeriodicBoxVectors()`](http://docs.openmm.org/latest/api-python/generated/openmm.openmm.Context.html#openmm.openmm.Context.setPeriodicBoxVectors). If you want a cubic box of volume `v` (measured in nm^3), the code would be
> 
> ```python
> width = v**(1/3)
> simulation.context.setPeriodicBoxVectors((width, 0, 0), (0, width, 0), (0, 0, width))
> ```

When we use fix deform in LAMMPS, a remapping of each atom in the system occurs to adjust to the new simulation box size. When we change the simulation box size with setPeriodicBoxVectors at OpenMM, do the atoms in the box remain in the same coordinates, or are they remapped according to the applied deformation?
