### ISSUE TITLE
Shockwave simulation in OpenMM

### ISSUE THREAD

**Issue by kong1-731** [openmm/openmm#3684]
I am just wondering if there is a way to implement a bound on the simulation domain on one or more of its faces with a flat wall that interacts with atoms by generating a force on the atoms (similar to fix wall/reflect in LAMMPS). Would there also be a way to bound the simulation with a moving wall that reflects particles in a specified group and drives the system with an effective infinite-mass piston (fix wall/piston in LAMMPS)?

**Comment by peastman** [comment]
I'm not a LAMMPS user so I'm not familiar with those particular options.  I can suggest a few options that might be what you want.

[This example](http://docs.openmm.org/latest/userguide/application/04_advanced_sim_examples.html#applying-an-external-force-to-particles-a-spherical-container) in the user guide shows how to create a potential to hold particles inside a spherical container.  It applies a harmonic potential that activates when they get too far away from the origin.  You could easily adapt it to a flat wall on one side, for example `100*max(0, x-3)` causes the energy to increase rapidly for x>3.

If instead you want a completely impenetrable wall that instantly reflects any particle that hits it, a [CustomIntegrator](http://docs.openmm.org/latest/api-c++/generated/CustomIntegrator.html) will be the most efficient way of implementing it.  The API docs give example code for some standard algorithms, including the ones used by LangevinMiddleIntegrator and VerletIntegrator.  You can start with one them and modify it to add in the hard wall.  Something along these lines ought to work.  (I'm just writing this in the browser, so it might not be exactly right.)

```python
integrator.addPerDofVariable('reflect', 0)
...
integrator.addComputePerDof('reflect', step(_x(x)-3))  # 1 if the x component of position >= 3, 0 otherwise
integrator.addComputePerDof('x', vector(_x(x)-reflect*2*(_x(x)-3), _y(x), _z(x)))
integrator.addComputePerDof('v', vector(_x(v)*select(reflect, -1, 1), _y(v), _z(v)))
```

In those examples I hardcoded the position of the wall at x=3.  If you want to be able to change it with time, you can add a global parameter to the CustomExternalForce or a global variable to the CustomIntegrator.

**Comment by kong1-731** [comment]
Thank you! That will point me in the right direction.
