### ISSUE TITLE
Continuing issue with CHARMM membrane GUI builder

### ISSUE THREAD

**Issue by kong1-731** [openmm/openmm#3685]
Referencing my previous question #3596, I have still not been able to resolve this because updating CUDA has not been successful after different attempts to do so. Therefore, is there some way to modify openmm_run.py or install some version of openmm that is compatible with CUDA version 10.2?

**Comment by kong1-731** [comment]
Thank you! Now I am back to my original issue where I have the fft error from the simulation setup line: simulation = Simulation(top.topology, system, integrator, platform, prop).  

---------------------------------------------------------------------------
OpenMMException                           Traceback (most recent call last)
/tmp/ipykernel_38049/1251864808.py in <module>
----> 1 simulation = Simulation(top.topology, system, integrator, platform, prop)

~/miniconda3/envs/py37/lib/python3.7/site-packages/openmm/app/simulation.py in __init__(self, topology, system, integrator, platform, platformProperties, state)
    103             self.context = mm.Context(self.system, self.integrator, platform)
    104         else:
--> 105             self.context = mm.Context(self.system, self.integrator, platform, platformProperties)
    106         if state is not None:
    107             with open(state, 'r') as f:

~/miniconda3/envs/py37/lib/python3.7/site-packages/openmm/openmm.py in __init__(self, *args)
   3949             a set of values for platform-specific properties. Keys are the property names.
   3950         """
-> 3951         _openmm.Context_swiginit(self, _openmm.new_Context(*args))
   3952 
   3953         self._system = args[0]

OpenMMException: Error initializing FFT: 11


Output of conda list: 
# packages in environment at /home/kyrstyn/miniconda3:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
brotlipy                  0.7.0           py38h8df0ef7_1001    conda-forge
ca-certificates           2022.6.15            ha878542_0    conda-forge
certifi                   2022.6.15        py38h578d9bd_0    conda-forge
cffi                      1.14.4           py38ha65f79e_1    conda-forge
chardet                   4.0.0            py38h578d9bd_0    conda-forge
conda                     4.13.0           py38h578d9bd_1    conda-forge
conda-package-handling    1.7.2            py38h8df0ef7_0    conda-forge
cryptography              3.3.1            py38h2b97feb_0    conda-forge
cudatoolkit               10.2.89              h8f6ccaa_8    conda-forge
expat                     2.2.9                he1b5a44_2    conda-forge
fftw                      3.3.9                h27cfd23_1  
fontconfig                2.13.1            h736d332_1003    conda-forge
freetype                  2.10.4               h7ca028e_0    conda-forge
giflib                    5.2.1                h36c2ea0_2    conda-forge
gnuplot                   5.0.3                         4    bioconda
gromacs                   2018.6               h6bb024c_1    bioconda
icu                       68.1                 h58526e2_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
jpeg                      9d                   h36c2ea0_0    conda-forge
ld_impl_linux-64          2.35.1               hea4e1c9_1    conda-forge
libblas                   3.9.0           11_linux64_openblas    conda-forge
libcblas                  3.9.0           11_linux64_openblas    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc                    7.2.0                h69d50b8_2    conda-forge
libgcc-ng                 11.2.0              h1d223b6_16    conda-forge
libgd                     2.3.0                h47910db_1    conda-forge
libgfortran-ng            9.3.0               he4bcb1c_17    conda-forge
libgfortran5              9.3.0               he4bcb1c_17    conda-forge
libgomp                   11.2.0              h1d223b6_16    conda-forge
libhwloc                  1.11.13              h3c4fd83_0    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblapack                 3.9.0           11_linux64_openblas    conda-forge
libopenblas               0.3.17          pthreads_h8fe5266_1    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libstdcxx-ng              9.3.0               h2ae2ef3_17    conda-forge
libtiff                   4.2.0                hdc55705_0    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libwebp                   1.1.0                h76fa15c_4    conda-forge
libwebp-base              1.1.0                h36c2ea0_3    conda-forge
libxml2                   2.9.10               h72842e0_3    conda-forge
llvm-openmp               8.0.1                hc9558a2_0    conda-forge
lz4-c                     1.9.2                he1b5a44_3    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
numpy                     1.22.2                   pypi_0    pypi
ocl-icd                   2.3.1                h7f98852_0    conda-forge
ocl-icd-system            1.0.0                         1    conda-forge
openmm                    7.6.0            py38hb15d7a2_0    conda-forge
openmp                    8.0.1                         0    conda-forge
openssl                   1.1.1o               h166bdaf_0    conda-forge
pip                       20.3.3             pyhd8ed1ab_0    conda-forge
pycosat                   0.6.3           py38h8df0ef7_1005    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pygnuplot                 0.11.16                  pypi_0    pypi
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1            py38h924ce5b_2    conda-forge
python                    3.8.5                h7579374_1  
python_abi                3.8                      1_cp38    conda-forge
readline                  8.0                  he28a2e2_2    conda-forge
requests                  2.25.1             pyhd3deb0d_0    conda-forge
ruamel_yaml               0.15.80         py38h8df0ef7_1003    conda-forge
setuptools                49.6.0           py38h924ce5b_2    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.34.0               h74cdb3f_0    conda-forge
tk                        8.6.10               h21135ba_1    conda-forge
tqdm                      4.55.0             pyhd8ed1ab_0    conda-forge
urllib3                   1.26.2             pyhd8ed1ab_0    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
zstd                      1.4.5                h6597ccf_2    conda-forge

Is my version of fftw incorrect?

**Comment by peastman** [comment]
It's unrelated to FFTW.  The error comes from cufft.  It's the same error as in #3596.

**Comment by kong1-731** [comment]
Does this mean that I can't get past the error without updating CUDA or should I reinstall OpenMM?

**Comment by kong1-731** [comment]
Thank you! I deleted the second CUDA toolkit in my path and now I have cleared the error! I appreciate your guidance with this.
