### ISSUE TITLE
Openmm Example for Protein-Ligand Complex

### ISSUE THREAD

**Issue by gundalav** [openmm/openmm#3686]
Hi, 

Thanks for making this great tool. 
Is there anywhere I can find example or tutorial for Protein-Ligand Complex modeling?
I'm thinking of something like [GROMACS tutorial of the same subject](http://www.mdtutorials.com/gmx/complex/index.html).

I'm aware of [this code](https://github.com/tdudgeon/simple-simulate-complex/blob/master/simulateComplex.py) from this [repository](https://github.com/tdudgeon/simple-simulate-complex). But it uses different (old?) library:

```
import sys, time
from openforcefield.topology import Molecule
from openmmforcefields.generators import SystemGenerator
from simtk import unit, openmm
from simtk.openmm import app, Platform, LangevinIntegrator
from simtk.openmm.app import PDBFile, Simulation, Modeller, PDBReporter, DCDReporter, StateDataReporter
from simtk.openmm.vec3 import Vec3
```

instead of `import openmm` approach, as described [here](http://docs.openmm.org/latest/userguide/application/02_running_sims.html#a-first-example).

Thanks and hope to hear from you again .

G.V.

**Comment by mattwthompson** [comment]
The `from simtk` imports are deprecated but mostly still work, see release notes here: https://github.com/openmm/openmm/releases/tag/7.6.0

Have you looked through [the docs](https://openmm.org/documentation), particularly the [user guide](http://docs.openmm.org/latest/userguide/)? There are [many examples](http://docs.openmm.org/latest/userguide/application/02_running_sims.html) scattered throughout those pages that demonstrate setting up simulations that you might be after.

**Comment by peastman** [comment]
Have you looked at [OpenMM-Setup](https://github.com/openmm/openmm-setup)?  It provides a simple UI that automates most of the steps in that tutorial.

**Comment by peastman** [comment]
Closing this since I believe the question has been answered.  Feel free to reopen if I missed something.
