### ISSUE TITLE
Adjust pair-wise parameters according to the atomic distance

### ISSUE THREAD

**Issue by XiaojuanHu** [openmm/openmm#3688]
Hi,
I'm trying to add the charge transfer effect to the classical force field.
What we want to do is get the distance between the cation ion and the surrounding atom, and if the distance is within the cutoff distance, we adjust the charge of the cation ion and the surrounding atoms. I tried to use 'state.getPositions()' to get atom positions and then calculate the distance between two atoms. But this method does not take into account the periodic condition. When the protein moves to the edge of the box, I get a distance of over 60 angstrom, while the actual distance is about 2 angstroms. What should I do to fix this problem? Or is there a nicer way to implement charge transfer with cutoff distance? Thank you very much!

**Comment by peastman** [comment]
Complicated question!  I'll answer it at a few levels.  Your most immediate question is how to compute distances through the Python API taking periodic boundary conditions into account.  You can do it like this.

```python
from openmm.app.internal import compiled
vectors = [v.value_in_unit(nanometers) for v in state.getPeriodicBoxVectors()]
periodicDistance = compiled.periodicDistance(vectors)
```

You can now use the `periodicDistance` function to compute distances between pairs of points:

```python
d = periodicDistance(p1, p2)
```

If you're analyzing a simulation after it's run this could be a reasonable approach.  But for computing forces during a simulation, don't do this!  It will be incredibly slow.  Instead you want to use custom forces, which get evaluated efficiently on the GPU.  Depending on exactly what you're doing, [CustomNonbondedForce](http://docs.openmm.org/latest/api-c++/generated/CustomNonbondedForce.html) or [CustomBondForce](http://docs.openmm.org/latest/api-c++/generated/CustomBondForce.html) are most likely to be relevant.

Taking another step back, what exactly do you mean by "charge transfer"?  Usually it is distinguished from polarization, which tends to be a more important effect.  The main methods used to model polarization are Drude particles (as in the CHARMM polarizable force field) and point dipoles (as in the AMOEBA and HIPPO force fields).  That leaves charge transfer as a secondary effect.  See for example https://pubs.acs.org/doi/10.1021/ct400704a, and the charge transfer model described in https://dasher.wustl.edu/ponder/papers/rackers-thesis.pdf.

**Comment by peastman** [comment]
Closing this since I believe the question has been answered.  Feel free to reopen if I missed something.
