### ISSUE TITLE
Profiling code and finding out what steps are inefficient for my system in OpenMM

### ISSUE THREAD

**Issue by kong1-731** [openmm/openmm#3694]
I have tried using different numbers of GPUS (varying from 1-4) for a production run of a membrane segment in OpenMM and I have noticed that using two GPUs seems to have better performance than 1 GPU. I am wondering if there is some way to check how much time is spent opening and closing the files/ fetching information versus the actual calculation in order to make sure that using more GPUs is efficient or if there is a profiler compatible or already built into OpenMM. 
Thank you!

**Comment by peastman** [comment]
[NVIDIA Nsight Systems](https://developer.nvidia.com/nsight-systems) is a good tool for that.  You can see a timeline showing exactly what each GPU is doing, when it's idle, and when data is being copied between them.

**Comment by kong1-731** [comment]
Thank you!
