### ISSUE TITLE
Question about NonbondedForce implementation

### ISSUE THREAD

**Issue by craabreu** [openmm/openmm#3697]
Why must particle parameters be updated at every step when a `NonbondedForce` contains parameter offsets? In the CUDA and OpenCL implementations, `computeParamsKernel` and `computeExclusionParamsKernel` always get executed if `hasOffset` is true, regardless of whether `paramChanged` is true or false. I'm struggling to understand why.

**Comment by peastman** [comment]
That's where the Ewald self energy gets computed.  When you aren't using offsets, it gets precomputed in `initialize()` and then `execute()` can just return it.  But with parameter offsets, it only gets computed on the GPU and we need to invoke the kernel that computes it every step.

It principle we could probably restructure the code to avoid the repeated computations.  In practice, the savings might not be enough to matter.  Those kernels are usually pretty fast.

**Comment by craabreu** [comment]
Ok. I see. It might make a difference for small systems only. Thanks for the answer.

**Comment by peastman** [comment]
There are no current plans to do that because no one ever asked for it before. :)  If you were to ask for it, though, it probably wouldn't be hard to do.

**Comment by craabreu** [comment]
Thanks, @peastman. I've just asked for it in the form of PR #3700. :)

**Comment by peastman** [comment]
Fixed by #3700.
