### ISSUE TITLE
Single dimension of `periodicdistance` in the CustomExternalForce class

### ISSUE THREAD

**Issue by zhenyuwei99** [openmm/openmm#3698]
Hi:
I am trying to implement an umbrella sampling simulation with the `CustomExternalForce`, and I found the function `periodicdistance` in the docs as:

```
CustomExternalForce* force = new CustomExternalForce("k*periodicdistance(x, y, z, x0, y0, z0)^2");
```

I am curious is there any simple version of this function for the single dimension such as `periodicdistance(x, x0)` or we should implemented it as a conditional judgement?

Best,

**Comment by peastman** [comment]
You can use `periodicdistance(x, 0, 0, x0, 0, 0)`.  It's just a function that accepts whatever arguments you want.  They don't have to be the actual position of the particle.

**Comment by zhenyuwei99** [comment]
Beautiful solution! Many thanks.
