### ISSUE TITLE
How can I add residual molecules into system?

### ISSUE THREAD

**Issue by OkKakao** [openmm/openmm#3702]
Hi

I'm trying an MD simulation, but stucked since I couldn't figure out how to add multiple residual molecule into system.

Is there any modeller function that places residual molecule into system?

Adding solvent is super easy, but adding residual molecule is quite elusive...

Besides, I want ethylenediamine molecules to be placed in the system.

Also, the following is my code.

If there is no way, I will try adding molecules manually into pdb input file..
```
from openmm.app import *
from openmm import *
from openmm.unit import *
from openff.toolkit.topology import Molecule
from openmmforcefields.generators import EspalomaTemplateGenerator
from sys import stdout
import time

start = time.time()
filename = '#file name will be placed here'
temps = [#smiles list will be placed here]
forcefield = ForceField('amber14/tip3p.xml')
espaloma = EspalomaTemplateGenerator()
forcefield.registerTemplateGenerator(espaloma.generator)
for i in temps:
    molecule = Molecule.from_smiles(i)
    espaloma.add_molecules(molecule)
pdb = PDBFile(f'{filename}.pdb')
platform = Platform.getPlatformByName('CUDA')
modeller = Modeller(pdb.topology, pdb.positions)
modeller.addSolvent(forcefield, ionicStrength=0.1*molar, positiveIon='Li+', negativeIon='I-')

system = forcefield.createSystem(modeller.topology, nonbondedMethod=PME, constraints=HBonds)
integrator = LangevinMiddleIntegrator(300*kelvin, 1/picosecond, 0.002*picoseconds)
simulation = Simulation(pdb.topology, system, integrator, platform)
simulation.context.setPositions(pdb.positions)
simulation.minimizeEnergy()
simulation.reporters.append(StateDataReporter(stdout, 100000, step=True, potentialEnergy=True, temperature=True))
simulation.step(100000000)
```

**Comment by peastman** [comment]
I noticed that no one ever replied to you about this.  Sorry about that!  I don't have a lot of experience with this sort of thing, but I'll do my best.  Are you adding just a single extra molecule?  If so, that can probably be done by hand.  If you're adding a whole lot of molecules, you probably want something to automate it.  I think programs like VMD include tools for building models, but that isn't something I've done.

**Comment by OkKakao** [comment]
I found a way to add nonstandard solvent molecules via gromacs.
The command gmx insert_molecule or gmx solvate was successfully added molecules into pdb file.
Thank you for caring for me!
