### ISSUE TITLE
Efficiency question regarding saving unwrapped atomic coordinates to separate files for a certain time interval

### ISSUE THREAD

**Issue by kong1-731** [openmm/openmm#3704]
I have been doing a deformation analysis of my MD simulation results that requires taking the unwrapped atomic coordinates for each lipid from each timepoint of a simulation and comparing the current unwrapped atomic positions to the initial positions at the start of the simulation. The unwrapped coordinate data is saved within "dump" files in LAMMPS, and I am now transitioning to using OpenMM instead of LAMMPS to increase the speed of my simulations. 
I noticed that the atomic coordinates can be saved in many different formats in OpenMM, including pdb files. In terms of efficiency, would using the PDBReporter to create a pdb trajectory and then breaking that file up later into each timepoint be a better idea than just saving the positions in their own text file at a certain time interval? Alternatively, would it be more efficient to calculate the deformation in realtime every so often during the molecular dynamics production run? I am just trying to figure out which method of saving the unwrapped atomic coordinate data along with the lipid type and number information would be closest to a LAMMPS style dump file or alternatively what would be the most efficient way to save this data in OpenMM. 
Thank you so much for any guidance on this issue!

**Comment by peastman** [comment]
I definitely would not use PDB.  It produces huge files and has limited precision for coordinates.  DCD is a better choice.  Be sure to specify `enforcePeriodicBox=False` to the DCDReporter constructor to get unwrapped coordinates.  Or you could create your own format, whatever is most convenient.

Doing the analysis in real time rather than saving coordinates is also fine.  It will save a little time from reading and writing files, but unless that's a bottleneck the total amount of time spent on simulating plus analyzing will probably be about the same either way.  Mostly it's a question of what's most convenient for you.

**Comment by kong1-731** [comment]
Thank you! One question I have with creating my own format is that how would I save atomID number corresponding to the unwrapped coordinate value? Does state.getPositions include the atomID so that I could somehow read the initial PDB and relate which atoms are in which lipid from that initial file? Also, does state.getPositions allow me to access the unwrapped coordinates, or do I have to use the DCDReporter? I am only hesitant to use the DCDReporter because I don't know how I would read in the coordinates.

**Comment by peastman** [comment]
> Does state.getPositions include the atomID so that I could somehow read the initial PDB and relate which atoms are in which lipid from that initial file?

The positions are in the same order as the particles in the System, which is the same order as the Topology it was created from.  So if you load a PDB, create a System from it, and retrieve the positions from a State, the first position will correspond to the first atom in the original PDB file.

> Also, does state.getPositions allow me to access the unwrapped coordinates

When you call `getState()`, the `enforcePeriodicBox` argument specifies whether the positions should be wrapped or not.  The default value is False, that is unwrapped.

> I am only hesitant to use the DCDReporter because I don't know how I would read in the coordinates.

You can use MDTraj to load it and get the coordinates.

**Comment by peastman** [comment]
Closing this since I believe the question has been answered.  Feel free to reopen it if I missed something.
