### ISSUE TITLE
Problem(s) building openmm from source code

### ISSUE THREAD

**Issue by k2o0r** [openmm/openmm#3707]
Hello, I have been trying to build OpenMM from source (because I want to use it with PLUMED w/ modules differing from the conda build, which, as I understand, requires building everything from source) and have encountered some issues in particular with the CUDA platform.

When I run make after ccmake .. I encounter these warning messages during the build:
<img width="1064" alt="dtoa" src="https://user-images.githubusercontent.com/67603864/180012551-6f95b8ff-5fe2-46ad-a229-4d7d33d79625.png">
<img width="929" alt="cuda" src="https://user-images.githubusercontent.com/67603864/180012598-a3449c01-0dc9-4cef-888b-06024ccb80c7.png">

The compilation does finish and I can then proceed with installation and testing, but all CUDA tests fail which I assume is related to the CUDA message linked above (all other tests pass).

Here is the output from nvidia-smi:
<img width="570" alt="smi" src="https://user-images.githubusercontent.com/67603864/180013134-ef61ff66-a5a9-4101-981e-8d2d9d28bfe1.png">

If there is any more information that may be useful in debugging this please let me know and I'll update, thanks!

**Comment by peastman** [comment]
You can ignore those warnings.  They aren't a problem.

In what way do the tests fail?  Try running one of them directly and post the output here.  For example,

```
./TestCudaHarmonicBondForce
```

**Comment by k2o0r** [comment]
Thanks for the quick reply! Here is the error I get from  ``./TestCudaHarmonicBondForce``

<img width="468" alt="Screenshot 2022-07-21 at 11 20 19" src="https://user-images.githubusercontent.com/67603864/180191256-e1418322-68e3-4c06-8b16-2182288e397e.png">

**Comment by k2o0r** [comment]
Right that error message was actually very helpful, managed to figure things out now, thanks!
