### ISSUE TITLE
Extracting Potential Energy as a GlobalParameter? 

### ISSUE THREAD

**Issue by sukritsingh** [openmm/openmm#3709]
I wanted to read out the Potential Energy of an OpenMM simulation `State` at each frame, but am not able to use a reporter (the  FAH core doesn't support `Reporter` objects yet).

One workaround I've previously used is to extract these kinds of features without a `Reporter` is attach the feature as a `GlobalParameter`(the FAH GPU core allows easy collection of all `GlobalParameters` at each frame). In the past I've done this by defining a `customIntegrator` and having the Potential Energy as a `globalParameter` inside there. 

However, in this current case I'm using the standard `LangevinIntegrator` or `LangevinMiddleIntegrator` objects, and I'm not too sure what is the best way to attach the Potential Energy as a `GlobalParameter` to my simulation. 

Are there any recommendations for how I could do this with the standard Integrators? Or would it be easiest to just write a `customIntegrator` again? 

I thought about attaching a zero-force `customForce` object to the simulation, but wasn't sure what I would attach it to so I could readout the entire simulation's Potential Energy.

**Comment by peastman** [comment]
I think it would be best to open an issue at https://github.com/FoldingAtHome/openmm-core.  This isn't really a question about OpenMM itself.  It's easy to query the energy at any time with `getState()`.  Your problem is in the limitations of what the core can do.

If you're really limited to only outputting global parameters, then a custom integrator is the way to do it.

**Comment by sukritsingh** [comment]
Yea I've previously opened an [issue](https://github.com/FoldingAtHome/openmm-core/issues/422) about this already on the OpenMM-Core repo but encountered it again recently so wanted to see if there was any chance of a quick workaround. I figured it would either be that or a core-level issue.

Thanks for clarifying!
