### ISSUE TITLE
Illegal nonbonded method for a non-periodic system

### ISSUE THREAD

**Issue by razvanmarinescu** [openmm/openmm#3715]
I'm trying to do a simulation in explicit solvent with PME, and I get the following error:
```
Traceback (most recent call last):
  File "/home/bizon/research/md/hbv/2g33_AB_explicit/run_md.py", line 16, in <module>
    system = psf.createSystem(params, nonbondedMethod=PME, nonbondedCutoff=1*nanometer, constraints=constraints, hydrogenMass=hydrogenMass)
  File "/home/bizon/anaconda3/envs/westpa-dev/lib/python3.10/site-packages/openmm/app/charmmpsffile.py", line 894, in createSystem
    raise ValueError('Illegal nonbonded method for a '
ValueError: Illegal nonbonded method for a non-periodic system
```

This is my system:
```
pdb = PDBFile('psfgen_out.pdb')
psf = CharmmPsfFile('psfgen_out.psf')
params = CharmmParameterSet('toppar_c36_jul21/top_all36_prot.rtf', 'toppar_c36_jul21/par_all36m_prot.prm', 'toppar_c36_jul21/toppar_water_ions.str')

dt = 0.004*picoseconds
constraints = HBonds
hydrogenMass = 1.5*amu

system = psf.createSystem(params, nonbondedMethod=PME, nonbondedCutoff=1*nanometer, constraints=constraints, hydrogenMass=hydrogenMass)
```

I couldn't figure out where to define the periodic boundary conditions (like the box dimensions). I thought it's defined in the force field parameters, and not in the pdb/psf files. But I couldn't figure out how to define it. Any help? Thanks

**Comment by peastman** [comment]
You can specify the periodic box size and shape using either the `periodicBoxVectors` or `unitCellDimensions` argument to the CharmmPsfFile constructure.  See http://docs.openmm.org/latest/api-python/generated/openmm.app.charmmpsffile.CharmmPsfFile.html#openmm.app.charmmpsffile.CharmmPsfFile.

**Comment by razvanmarinescu** [comment]
@peastman That worked, thank you very much!!
