### ISSUE TITLE
CUDA Out of memory error when using PME

### ISSUE THREAD

**Issue by razvanmarinescu** [openmm/openmm#3717]
Hi,

I have a system with 34k atoms (4k atoms belong to a protein, rest are TIP3 water molecules) and 4 GPUs (Nvidia A4000) of 16GB each. When I switch from `nonbondedMethod=CutoffPeriodic` to  `nonbondedMethod=PME`, I get the following error:

```
Traceback (most recent call last):
  File "/home/bizon/research/md/hbv/2g33_AB_explicit/run_md.py", line 22, in <module>
    simulation = Simulation(psf.topology, system, integrator, platform, properties)
  File "/home/bizon/anaconda3/envs/westpa-dev/lib/python3.10/site-packages/openmm/app/simulation.py", line 103, in __init__
    self.context = mm.Context(self.system, self.integrator, platform, platformProperties)
  File "/home/bizon/anaconda3/envs/westpa-dev/lib/python3.10/site-packages/openmm/openmm.py", line 12378, in __init__
    _openmm.Context_swiginit(self, _openmm.new_Context(*args))
openmm.OpenMMException: Error creating array pmeGrid1: CUDA_ERROR_OUT_OF_MEMORY (2)
```

How much GPU memory does `PME` need? I cannot get it to work even if I scale on multiple GPUs. I have a relatively small system, so I don't think there should be an issue. It otherwise works fine with `CutoffPeriodic`. 

Also, is my understanding correct that `PME` is more accurate, but slower than using 'CutoffPeriodic'? In what cases would I need a more accurate electrostatics like PME?

**Comment by razvanmarinescu** [comment]
This is the code I run:
```
pdb = PDBFile('psfgen_out.pdb')
psf = CharmmPsfFile('psfgen_out.psf', unitCellDimensions=(80,80,80) )
params = CharmmParameterSet('toppar_c36_jul21/top_all36_prot.rtf', 'toppar_c36_jul21/par_all36m_prot.prm', 'toppar_c36_jul21/toppar_water_ions.str')
print('nr of atoms:',len(pdb.positions) )

dt = 0.004*picoseconds
constraints = HBonds
hydrogenMass = 1.5*amu

system = psf.createSystem(params, nonbondedMethod=PME, nonbondedCutoff=1*nanometer, constraints=constraints, hydrogenMass=hydrogenMass)

integrator = LangevinMiddleIntegrator(300*kelvin, 1/picosecond, dt)

platform = Platform.getPlatformByName('CUDA')
properties = {'DeviceIndex': '1' }
simulation = Simulation(psf.topology, system, integrator, platform, properties)
simulation.context.setPositions(pdb.positions)
```

I also tried running two of the PME benchmarks (`pme` and `apoa1pme`), and they all work fine.

**Comment by peastman** [comment]
> `psf = CharmmPsfFile('psfgen_out.psf', unitCellDimensions=(80,80,80) )`

You don't really mean those dimensions, do you?  If you don't specify units, it assumes nm.  80 nm is a *huge* box.  You probably meant 80 A?

**Comment by razvanmarinescu** [comment]
Yes, that's right. I meant 80A, not 80nm. It now works, thank you!

**Comment by peastman** [comment]
The units API is your friend!  You can avoid all uncertainty by writing `(80, 80, 80)*angstroms`.

I'm closing this since the problem has been solved.
