### ISSUE TITLE
What is the correct usage of RMSDForce? Returning 0 energy at all times

### ISSUE THREAD

**Issue by ljmartin** [openmm/openmm#3718]
Hi all, 
I'd like to use an `RMSDForce` (ordinarily wrapped in a `CustomCVForce`) and subsequently change the reference positions. On examination, I appear to not see any force from the `RMSDForce` being applied. Is the below the correct usage?

Here's a quite minimal example, without the `CustomCVForce`. Note that the reference position is non-zero, so I expected there to be a force at timestep zero. `ref_pos` can be set to any wildly large, medium or small value, but the resulting force is always 0 kj/mol (the inverse works as well - set `ref_pos` to (0,0,0) and propagate for some steps at temperature, but the force remains zero).

```python
from openmm import app
import openmm
from openmm.openmm import unit

system = openmm.System()
system.addParticle(1)

ref_pos = [[10,0,0]]
rmsd_force = openmm.RMSDForce(ref_pos, [0])
system.addForce(rmsd_force)

integrator = openmm.LangevinIntegrator(500, 1, 0.02)
context = openmm.Context(system, integrator, openmm.Platform.getPlatformByName('CPU'))

context.setPositions([[0, 0, 0]])

print('Version', openmm.__version__)
print(context.getState(getEnergy=True).getPotentialEnergy())
``` 
output is:
```
Version 7.7
Quantity(value=0.0, unit=kilojoule/mole)
```

Thanks for your time!

<details><summary>For completeness, an example with `CustomCVForce`</summary>
<p>

```python
system = openmm.System()
system.addParticle(1)

ref_pos = [[10,0,0]]
rmsd_force = openmm.RMSDForce(ref_pos, [0])

cv_force = openmm.CustomCVForce('rmsd')
cv_force.addCollectiveVariable('rmsd', rmsd_force)
system.addForce(cv_force)

integrator = openmm.LangevinIntegrator(500, 1, 0.02)
context = openmm.Context(system, integrator, openmm.Platform.getPlatformByName('CPU'))

context.setPositions([[0, 0, 0]])

print(context.getState(getEnergy=True).getPotentialEnergy())
print(cv_force.getCollectiveVariableValues(context))
```
output:
```
0.0 kJ/mol
(0.0,)
```

</p>
</details>

**Comment by peastman** [comment]
This happens because you're applying it to only a single particle.  The RMSD calculation begins by finding a translation and rotation that optimally align the current positions to the reference positions.  A single point can always be translated to exactly align it with the reference, so the RMSD is always 0.

**Comment by ljmartin** [comment]
Of course. Thanks.
