### ISSUE TITLE
OpenMM Modeller - randomly place proteins in a box (like PackMol)

### ISSUE THREAD

**Issue by razvanmarinescu** [openmm/openmm#3724]
Is there a Modeller functionality in OpenMM that randomly samples proteins in a box? Of course, ensuring no clashes in the final output. Something like the functionality of [PackMol](http://leandro.iqm.unicamp.br/m3g/packmol/home.shtml), but integrated with the workflow of Modeller, or something that works with MDAnalysis. Thanks!

**Comment by peastman** [comment]
OpenMM doesn't provide anything like that.  Its modelling features are meant to cover the most common cases, but it isn't trying to replace dedicated modelling tools.  As long as a tool can write its results in a standard format like PDB or PDBx/mmCIF, OpenMM should be able to load it.

**Comment by razvanmarinescu** [comment]
Gotcha! In the meantime I found this Python wrapper for PackMol with MDAnalysis: 

https://github.com/MDAnalysis/MDAPackmol
