### ISSUE TITLE
Performing deepcopy on OpenMM system object?

### ISSUE THREAD

**Issue by ziyuanzhao2000** [openmm/openmm#3725]
Hi developers! So I was trying to use this package [atomsmm](https://atomsmm.readthedocs.io/en/latest/readme.html) built upon OpenMM's ecosystem for doing some additional logging during simulations. However, there's some problem with their code. Specifically, when they initializes their system object, which wraps OpenMM's, they require the platform to be set. And they also deepcopy the entire system. Hence, in practice, when I tried to use their code, it throws off an error when deepcopying:

```
...

File ~/opt/anaconda3/envs/openmm2/lib/python3.9/site-packages/atomsmm-0.1.0-py3.9.egg/atomsmm/systems.py:884, in ComputingSystem.__init__(self, system)
    883 def __init__(self, system):
--> 884     super().__init__(system, copyForces=False)
    885     dispersionGroup = 0
    886     bondedGroup = 1

File ~/opt/anaconda3/envs/openmm2/lib/python3.9/site-packages/atomsmm-0.1.0-py3.9.egg/atomsmm/systems.py:28, in _AtomsMM_System.__init__(self, system, copyForces)
     27 def __init__(self, system, copyForces=True):
---> 28     self.this = copy.deepcopy(system).this
     29     if not copyForces:
     30         for index in reversed(range(self.getNumForces())):

...

**TypeError: cannot pickle 'SwigPyObject' object**
```

Please advise on if it's proper to deepcopy OpenMM system objects. If not, what might be the best way to perform the copying. Then I will probably try to fix their code. Thank you!

**Comment by peastman** [comment]
Deep copy works fine with OpenMM System objects:

```python
>>> from openmm import *
>>> from copy import deepcopy
>>> s1 = System()
>>> s2 = deepcopy(s1)
```

From the stack trace, it looks like the object you're trying to copy is an AtomsMM System object, not an OpenMM System object.  They don't seem to have implemented deepcopy support for it.

**Comment by ziyuanzhao2000** [comment]
Thanks! I just debugged once more, and, indeed, it's not OpenMM but another package's problem.
