### ISSUE TITLE
ForceField is empty after reading a xml

### ISSUE THREAD

**Issue by zlcrrrr** [openmm/openmm#3728]
Hi,

I've parameterized a small molecule and saved the system as a xml file. Then I used ForceField to read that xml, but I found the ForceField is empty. Can you please help with this?

The motivation here is to incorporate multiple parameterized small molecules in one force field. Can you please let me know how to properly do this?

Thanks.

The xml reads

```
<?xml version="1.0" ?>
<System openmmVersion="7.7" type="System" version="1">
	<PeriodicBoxVectors>
		<A x="3.5408000000000004" y="0" z="0"/>
		<B x="0" y="3.601" z="0"/>
		<C x="0" y="0" z="5.301200000000001"/>
	</PeriodicBoxVectors>
	<Particles>
		<Particle mass="12.01"/>
		<Particle mass="1.008"/>
		<Particle mass="1.008"/>
		<Particle mass="1.008"/>
		<Particle mass="1.008"/>
	</Particles>
	<Constraints>
		<Constraint d=".1097" p1="0" p2="1"/>
		<Constraint d=".1097" p1="0" p2="2"/>
		<Constraint d=".1097" p1="0" p2="3"/>
		<Constraint d=".1097" p1="0" p2="4"/>
...
```

But using 

```
> forcefield = ForceField('xxx.xml')
> forcefield.__dict__
```

forcefield is empty

```
> {'_atomTypes': {},
>  '_templates': {},
>  '_patches': {},
>  '_templatePatches': {},
>  '_templateSignatures': {None: []},
>  '_atomClasses': {'': set()},
>  '_forces': [],
>  '_scripts': [],
>  '_templateMatchers': [],
>  '_templateGenerators': []}
```

**Comment by peastman** [comment]
A saved System is different from a ForceField.  They both happen to use XML files, but they're not the same.  Here is a description of [how to load a saved System](https://openmm.github.io/openmm-cookbook/dev/notebooks/cookbook/Saving%20Systems%20to%20XML%20Files.html).

**Comment by zlcrrrr** [comment]
Thanks! But how to use multiple pre-parameterized small molecules in one complex system? Say I have two separately parameterized molecules A and B, and I would like to use the force field parameters for a complex system AB.

**Comment by peastman** [comment]
It's easiest to parametrize the whole system all at once.  Where are the individual molecules and parameters coming from?

**Comment by zlcrrrr** [comment]
> A saved System is different from a ForceField. They both happen to use XML files, but they're not the same. Here is a description of [how to load a saved System](https://openmm.github.io/openmm-cookbook/dev/notebooks/cookbook/Saving%20Systems%20to%20XML%20Files.html).
Thanks! But how to use multiple pre-parameterized small molecules in one complex system? Say I have two separately parameterized molecules A and B, and I would like to use the force field parameters for a complex system that consists of A and B.

**Comment by zlcrrrr** [comment]
> here are the individual molecules and parameters coming from?

Yes, but the thing is I have many guest-host systems. The guests are small and different and host is large and the same. If I parametrize the whole system for each guest-host system, I have to parameterize the large host many times.

**Comment by peastman** [comment]
> I have to parameterize the large host many times.

Is that a problem?  Is the speed of `createSystem()` a bottleneck to your simulation protocol?

> I would be nice if I can do things like
>
> `forcefield = ForceField('guest_1.xml', 'guest_2.xml', 'host.xml')`

You can.  Does that code not work for you?  A ForceField can load parameters from multiple files.

**Comment by zlcrrrr** [comment]
> > I have to parameterize the large host many times.
> 
> Is that a problem? Is the speed of `createSystem()` a bottleneck to your simulation protocol?
> 
> > I would be nice if I can do things like
> > `forcefield = ForceField('guest_1.xml', 'guest_2.xml', 'host.xml')`
> 
> You can. Does that code not work for you? A ForceField can load parameters from multiple files.

Yes it is a problem, createSystem() is very slow for that host.

Can you please let me know how to save force fields as xml files?

Thanks!

**Comment by peastman** [comment]
The user guide describes the [format of force field files](http://docs.openmm.org/latest/userguide/application/05_creating_ffs.html).  To clarify, you don't save a force field to a file.  You load the force field from a file.  That file has to be created in some other way, either written by hand or created with a tool such as ParmEd.

**Comment by zlcrrrr** [comment]
> That file has to be created in some other way, either written by hand or created with a tool such as ParmEd.

Got it. Thank you very much!

**Comment by zlcrrrr** [comment]
Yes thank you.
