### ISSUE TITLE
Is there any forcefield available for iron ion?

### ISSUE THREAD

**Issue by OkKakao** [openmm/openmm#3733]
Hi

I'm trying to simulate iron ions which are included in metalloporphyrin molecule.

The required ones are Fe+ and Fe2+.

I'm just wondering if there is available or not...

Does tip3p like forcefields contains such forcefield?

**Comment by peastman** [comment]
Amber14 includes parameters for Fe2+ and Fe3+, but not Fe+.  CHARMM36 doesn't seem to have any parameters for isolated iron ions.

Perhaps someone has published parameters you can use?  If so, it's easy to create a new force field file defining them.
