### ISSUE TITLE
Forcefield issue with modified amino acid residue

### ISSUE THREAD

**Issue by ziyuanzhao2000** [openmm/openmm#3734]
Hi, so I was trying to parametrize the CRO (chromophore) residue, and I think I got it almost right, except that I notice the bonds connecting the terminal C, N atoms of CRO to the previous and the later residues in the protein do not have correct geometries. Please see the picture below. However, I'm pretty sure my XML template for CRO is structurally correct, so I just can't quite find the reason for this bad behavior of the connecting bonds. Any insights is appreciated!
<img width="865" alt="Screen Shot 2022-08-11 at 11 11 44 PM" src="https://user-images.githubusercontent.com/78766247/184278125-cc794555-27d9-4bb8-b7dc-11dc86ce8cbe.png">

Above shows a picture of the trimer L-CRO-V inside a protein (the protein and the solvent are hidden). As we can see, the C-N1 bond and the C3-N bond have terrible geometry. This picture is taken after an equilibration step of the protein in water.

A more general question I'd like to ask here is how OpenMM parametrizes the forces across two residues, if they are defined in separate forcefield files. I think understanding that might help me debug my case. Thanks again for your attention!

**Comment by peastman** [comment]
See the [user guide](http://docs.openmm.org/latest/userguide/application/05_creating_ffs.html) for a description of how parametrization works.  It doesn't matter whether the residues are defined in one file or multiple files.  The process is

1. Match templates to residues to assign atom types.
2. Assign parameters based on the types of the connected atoms.

You might want to inspect the System it generates.  Look through the Force objects to find the bonds connecting those atoms and see if their parameters are what you expect.

**Comment by peastman** [comment]
We generally use [ParmEd](https://github.com/ParmEd/ParmEd) for converting force fields.

**Comment by ziyuanzhao2000** [comment]
Right, but say for example I have two frcmod files generated in Amber containing all required parameters for the modified residue, and I'd plan to use ff14SB (as defined [here](https://github.com/openmm/openmmforcefields/blob/master/amber/ffxml/ff14SB.xml)) for simulation of the rest of the protein, then how shall I use parmed correctly to include the parameters in frcmod files but _not_ in the ff14SB xml file? Is there a function in ParmEd for doing set subtraction like this? Thank you! Sorry about asking so many questions!

**Comment by ziyuanzhao2000** [comment]
Okay, I will close this for now, as I found that the problem is: I used protein.ff14sb instead of ff14sb for the main forcefield, and this protein.ff14sb.xml file has a different definitions for atom types than the amber atom type (the "protein-" prefixes), so bonds are not added correctly between my modified residue and the ordinary residues due to this mismatch in type names.
