### ISSUE TITLE
Duplicated forces with multiple forcefields?

### ISSUE THREAD

**Issue by ziyuanzhao2000** [openmm/openmm#3735]
This is probably a continuation of the issue closed [here](https://github.com/openmm/openmm/issues/2481).

The current OpenMM manual [says that](http://docs.openmm.org/latest/userguide/application/05_creating_ffs.html#using-multiple-files) when using multiple XML forcefield files, 

> For other forces, the files are effectively independent. For example, if two files each include a <HarmonicBondForce> tag, bonds will be created based on the rules in the first file, and then more bonds will be created based on the rules in the second file. This means you could potentially end up with multiple bonds between a single pair of atoms.

However, in my use case I didn't notice this, and I noted that in that issue I linked above, the described behavior back then was that in case of duplicated forces, only one will be used. However, consider that was an old issue already closed, I'm opening this issue to clarify what is the current behavior, and why I might haven't seen redundant forces in my System. Thank you!

**Comment by peastman** [comment]
I think https://github.com/openmm/openmm/issues/2481#issuecomment-557921856 is the most detailed description.  Is there a particular type of force you're asking about?

**Comment by ziyuanzhao2000** [comment]
So for example, I'm interested in the harmonic bonding force. But I feel like the comment you referred to says that it is one force per atom pair even if there are duplicate definitions, whereas the paragraph I quoted from the manual says it could be multiple bonding forces one for each definition. Hence, I was thinking that they're contradictory. It must be I'm not comprehending this correctly as intended. Can you help to clarify? Thanks!

Based on your comment, it seems that I should follow the comment.

**Comment by peastman** [comment]
I believe you're right.  The manual should be updated.  I'll tag this issue as documentation.

**Comment by ziyuanzhao2000** [comment]
Thanks for clarifying the correct behavior! It's good to know that the documentation will be updated as well.
