### ISSUE TITLE
Unexpected behavior for "setExceptionParameters" when modifying nonbonded exception forces

### ISSUE THREAD

**Issue by kntkb** [openmm/openmm#3738]
**Background**
I get the following error when I try to modify the nonbonded exception forces. I know that `updateParametersInContext()` has some limitations and sometimes you need to call the `reinitialize()` on the Content instead. 

```
Traceback (most recent call last):
  File "/Users/takabak/work/espaloma_rna/train/playground/subtract_nonbonded/subtract_nonbonded_update_true.py", line 60, in <module>
    force.updateParametersInContext(simulation.context)  
  File "/Users/takabak/mambaforge/envs/espaloma/lib/python3.9/site-packages/openmm/openmm.py", line 9915, in updateParametersInContext
    return _openmm.NonbondedForce_updateParametersInContext(self, context)
openmm.OpenMMException: updateParametersInContext: The set of non-excluded exceptions has changed
```

However, I can successfully update the ExceptionParameters if don't use `force.updateParametersInContext(simulation.context)`. I was expecting some kind of update or reinitialization to update the context after setting a new parameter. Is this the right behavior? 

I posted the script and the mol object as a pickle file for reproducibility.  Openmm version is 7.7.
[mol.pkl.zip](https://github.com/openmm/openmm/files/9330672/mol.pkl.zip)

**Script**
```
import numpy as np
import pickle
from openff.toolkit.topology import Molecule
from openmmforcefields.generators import SystemGenerator
from simtk import openmm, unit
from simtk.openmm.app import Simulation
from simtk.unit import Quantity

TEMPERATURE = 350 * unit.kelvin
STEP_SIZE = 1.0 * unit.femtosecond
COLLISION_RATE = 1.0 / unit.picosecond
EPSILON_MIN = 0.05 * unit.kilojoules_per_mole
forcefield="gaff-1.81"

mol = pickle.load(open("mol.pkl", "rb"))
topology = mol.to_topology().to_openmm()

generator = SystemGenerator(
    small_molecule_forcefield=forcefield,
    molecules=[mol],
    forcefield_kwargs={"constraints": None, "removeCMMotion": False},
)


system = generator.create_system(
    topology,
)

integrator = openmm.LangevinIntegrator(
    TEMPERATURE, COLLISION_RATE, STEP_SIZE
)

simulation = Simulation(
    topology=topology, system=system, integrator=integrator
)

forces = list(system.getForces())            
for force in forces:
    name = force.__class__.__name__

    if "Nonbonded" in name:
        for idx in range(force.getNumExceptions()):                
            #print(idx, force.getNumExceptions())
            idx0, idx1, q, sigma, epsilon = force.getExceptionParameters(idx)
            force.setExceptionParameters(idx, idx0, idx1, 100.0, sigma, epsilon)   # set to 100 for test purpose

        # raises error
        force.updateParametersInContext(simulation.context)  

        # check
        for idx in range(force.getNumExceptions()):
            print(idx, force.getExceptionParameters(idx))
```

**Comment by peastman** [comment]
If an exception sets `chargeProd` and `epsilon` to zero, it's an exclusion.  It means that interaction is completely omitted.  If it sets either of them to a nonzero value, that means the interaction still needs to be computed, just with different parameters.  The API makes these cases look the same, but internally they get handled differently.  That's why `updateParametersInContext()` can't switch between them.  You'll need to use `reinitialize()` in this case.

> However, I can successfully update the ExceptionParameters if don't use force.updateParametersInContext(simulation.context). I was expecting some kind of update or reinitialization to update the context after setting a new parameter. Is this the right behavior?

Changing the NonbondedForce has no effect on existing contexts.  See [the FAQ](https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#system) for more information about this.

**Comment by kntkb** [comment]
Thank you for the reply. Please correct me if I'm still misunderstanding.

>If an exception sets chargeProd and epsilon to zero, it's an exclusion. It means that interaction is completely omitted. If it sets either of them to a nonzero value, that means the interaction still needs to be computed, just with different parameters. The API makes these cases look the same, but internally they get handled differently. That's why updateParametersInContext() can't switch between them. You'll need to use reinitialize() in this case.

So I need to use `reinitialize()` if I want to update my nonbonded exception paramters. However, I could update the parameters obtained by `getParticleParameters` using `updateParametersInContext()`. The document [here](http://docs.openmm.org/latest/api-python/generated/openmm.openmm.NonbondedForce.html#openmm.openmm.NonbondedForce) may have confused me because it explains that `updateParametersInContext` can "_update the particle and exception parameters in a Context to match those stored in this Force object_".

>Changing the NonbondedForce has no effect on existing contexts. See [the FAQ](https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#system) for more information about this.

I now understand that only global parameters can be update on the fly.

**Comment by peastman** [comment]
> So I need to use reinitialize() if I want to update my nonbonded exception paramters.

It depends on the particular change.  The only time you get that error is if the interaction originally was completely excluded (`chargeProd` and `epsilon` both 0), then you change it to no longer be excluded.  If it originally was calculated and you change it to be calculated with different parameters, that's ok.

**Comment by kntkb** [comment]
Oh, I see! I cannot change the `chargeProd` and `epsilon` parameters in a way that the set of non-excluded exception pairs change (which is exactly what the error message was saying!). I can easily see what's going on if I do something like:

```
if q._value != 0.0 and epsilon._value != 0.0:
    print(idx, q._value, epsilon._value)
    force.setExceptionParameters(idx, idx0, idx1, 0, sigma, 0)
force.updateParametersInContext(simulation.context)  
```

This will raise an error because by setting q and epsilon to zero will change the non-exception pairs.

Thank you!
