### ISSUE TITLE
Substituting energy value from external calculation into openmm for coordinates generation

### ISSUE THREAD

**Issue by yipy0005** [openmm/openmm#3744]
Hi, I would like to know where in the code can I substitute the energy value obtained from external software calculation, and use that in OpenMM for forces computation and coordinates generation?

Thank you. :D

**Comment by peastman** [comment]
I think [this describes](https://openmm.github.io/openmm-cookbook/dev/notebooks/cookbook/Applying%20a%20Constant%20External%20Force.html) what you want to do?

**Comment by yipy0005** [comment]
It's not really that. I have also seen the custom forces functions. But it's more like instead of using an energy function to find the position and velocity of the next time step, I want to substitute Single Point Energy of the whole frame which I may have used (e.g. Gaussian) to calculate, and substitute it back to OpenMM for the determination of the position and velocity of the next time step. :D

**Comment by peastman** [comment]
Do you have forces as well?  If all you have is an energy, it isn't possible to do dynamics with that.

**Comment by yipy0005** [comment]
I was thinking, if force is a derivative of energy, then I can probably try taking the difference of 2 energy values and divide it by the distance/radius/bond length, something like finding the gradient of the energy function at a point, and use that as a force to apply to the system. Reason being I'm trying to replace the force field equations with just SPEs, and make it more like ab initio MD. :D

**Comment by peastman** [comment]
You would need to take a difference along every coordinate.  With N atoms, that means 3N energy evaluations!  That will be much slower than getting forces directly from your QM method, as well as being less accurate.

In any case, the code in the cookbook should still work.  By whatever means, you need to determine the forces to apply to all the particles.  Once you do that, you can use the CustomExternalForce to apply them.

**Comment by peastman** [comment]
Closing this since I believe the question has been answered.  Feel free to reopen it if I missed something.
