### ISSUE TITLE
Issues implementing residue level CG model in OpenMM

### ISSUE THREAD

**Issue by k2o0r** [openmm/openmm#3749]
I am trying to set up a residue level coarse-grained model for use in OpenMM but running into issues with setting up initial topologies and getting OpenMM to understand them. 

The model consists of 20 beads, each representing one of the natural amino acids. To implement this in OpenMM I've defined 20 atom type, with each assigned to a unique element. As I understand, this is necessary because the residue can only be recognised by the elements and bonds contained within it. In this simple model, that means each atom type must have a unique element as each 'residue' is just a single atom. The problem is that it seems that OpenMM does not like 2 letter element symbols for some reason, as these are unable to be recognised.

To reproduce the problem I'm having I've included the xml file and 2 short test pdb files.
[test.xml.txt](https://github.com/openmm/openmm/files/9383418/test.xml.txt)
[test1.pdb.txt](https://github.com/openmm/openmm/files/9383419/test1.pdb.txt)
[test2.pdb.txt](https://github.com/openmm/openmm/files/9383420/test2.pdb.txt)

Very simple code like 
`pdb = PDBFile('test2.pdb') 
  ff = ForceField('test.xml')
 print(ff.getUnmatchedResidues(pdb.topology))
`
can be used to see the problem.

Most likely this is just an issue with me understanding how the pdb reader works but this has been frustrating me all day.
Thanks!

**Comment by peastman** [comment]
Your PDB file doesn't specify elements.  The element symbol is supposed to be in columns 77-78, which are missing in your file.  See [the spec](http://www.wwpdb.org/documentation/file-format-content/format33/sect9.html#ATOM) for details.

**Comment by k2o0r** [comment]
Aha, definitely one for the silly mistakes category. Thanks.

In the case of the ones it can read correctly it's because it correctly infers the element from the name column?

**Comment by peastman** [comment]
Right.  If you don't specify elements it tries to guess elements from the atom name.  But that isn't reliable.

**Comment by k2o0r** [comment]
Perfect, thanks!
