### ISSUE TITLE
Performance issue with RTX A6000 ?

### ISSUE THREAD

**Issue by tubiana** [openmm/openmm#3751]
Hi :)

I'm using AlphaFold2 Through a local colabfold implementation (https://github.com/sokrypton/ColabFold) on Singularity (the receipe is present here https://github.com/tubiana/colabfold_singularity).
One optional step is a Amber minimisation through OPENMM 7.5.1 and unfortunatly i'm experiencing performance issues with my RTX A6000:  the relaxation time is 3 to 4 times slower than on another desktop with an RTXA5000 or RTXA4000. The usage of the GPU is also very low (< 5%).
It's the same singularity image than it is used and I only experience issue on the desktop with an RTXA6000. The only difference is the cuda driver version (I used the 515 while other desktop are a bit older).

Is anyone got similar issue? Because I tried to reinstall singularity, all the drivers, use openMM 7.7 (and patching Alphafold relaxation code) but without luck.. Are you aware of a performance issue on RTX A6000 ?

Thank you for your help :)
Thibault.

**Comment by peastman** [comment]
I don't think it has anything to do with the GPU model.  Are you sure it's actually using the GPU at all?  Which platform is it using?

**Comment by peastman** [comment]
Just following up on this, since there was no reply to my last post.  Can you answer the above questions?  Thanks!

**Comment by tubiana** [comment]
oh I'm so sorry I haven't seen the notification before... 
I am using Ubuntu 20.04, the GPU is not used at 100% at all, but it's the same singularity image that I used on different computers. Maybe I have a clue about that : Some of my colleagues have an issue with the same DELL configuration (custom Ubuntu 20.04 installation). 
Unfortunatly I don't have time to reinstall everything until end of next month, so I will make a fresh install and update you :) 

I will also try to use the benchmark.py script to check the performance directly (without container) on multiple computers.

I close the issue for now because it seems to be very specific to my DELL computer, and put the update when I'm done with testing..

(once again, Sincerely sorry about my responce delay...)
Best,
Thibault.
