### ISSUE TITLE
Add support for other water models for Modeller.addSolvent

### ISSUE THREAD

**Issue by kntkb** [openmm/openmm#3752]
I would like to request a feature enhancement for `Modeller.addSolvent`. According to the [document](http://docs.openmm.org/latest/api-python/generated/openmm.app.modeller.Modeller.html), the supported water models are currently tip3p, spce, tip4pew, and tip5p. Can we add support for other water models such as OPC models?

**Comment by peastman** [comment]
All three point water models are pretty similar.  If you tell it to build a TIP3P water box, then build a System with OPC and call `minimizeEnergy()`, I think it ought to work fine.  Can you try that?

**Comment by kntkb** [comment]
@peastman  Thank you! I was able to solve the problem!
