### ISSUE TITLE
Installing OpenMM v7.5

### ISSUE THREAD

**Issue by Maxim-93** [openmm/openmm#3754]
Hi there!

I am trying to install Tinker-OpenMM to perform AMOEBA free energy calcs but in order to do that, I need to use a pre March 4 2021 version of OpenMM (i.e anything up to and including version 7.5 *I think*). Can’t seem to do this in anaconda as it juts automatically opts for the newest version. Is my only option building from source in this particular case or is there a more simple way?

Many thanks,
Max

**Comment by peastman** [comment]
When installing with conda, you can specify a particular version to install.

```
conda install -c conda-forge openmm=7.5.1
```

**Comment by Maxim-93** [comment]
Cheers!
