### ISSUE TITLE
CUDA platform error

### ISSUE THREAD

**Issue by vemaparna** [openmm/openmm#3756]
Hi! Im trying to install openmm using conda in ubuntu 20.04 with nvidia graphic card Quadro K2000. Have installed cuda 11.4. my testinstallation gives the following error
OpenMM Version: 7.7
Git Revision: 130124a3f9277b054ec40927360a6ad20c8f5fa6

There are 4 Platforms available:

1 Reference - Successfully computed forces
2 CPU - Successfully computed forces
3 CUDA - Error computing forces with CUDA platform
4 OpenCL - Successfully computed forces

CUDA platform error: Error compiling program: nvrtc: error: invalid value for --gpu-architecture (-arch)

Median difference in forces between platforms:

Reference vs. CPU: 6.29738e-06
Reference vs. OpenCL: 6.76359e-06
CPU vs. OpenCL: 8.11707e-07

nvidia-smi gives the following:
NVIDIA-SMI 470.141.03   Driver Version: 470.141.03   CUDA Version: 11.4 

kindly help me to resolve the issue and enjoy openmm

**Comment by peastman** [comment]
Quadro K2000 is a very old GPU that isn't supported anymore in CUDA 11.  I believe CUDA 10 should still work with it.  Wikipedia has a useful [list of supported architectures](https://en.wikipedia.org/wiki/CUDA#GPUs_supported) for each CUDA version.  When you install OpenMM, you can specify the CUDA version to use like this:

```
conda install -c conda-forge openmm cudatoolkit=10.2
```

**Comment by vemaparna** [comment]
Thanks a lot. It worked

**Comment by vemaparna** [comment]
Thanks a lot. It worked
