### ISSUE TITLE
C-terminal Proline issues

### ISSUE THREAD

**Issue by KP-303** [openmm/openmm#3761]
I have problems when trying to load a peptide with a C-terminal Proline. I have been using the amber-14 and charm-36 forcefield but it works for neither. I generated the .pdb file from Avogadro but then used openmm-setup to clean up the pdb. When I download the cleaned pdb file I get the following error:

ValueError: No template found for residue 8 (PRO).  The set of atoms is similar to GLN, but it is missing 1 atoms.

The relevant part of my input file looks like this:
`pdb = PDBFile('test.pdb')'

'forcefield = ForceField('charmm36.xml', 'implicit/GBn2.xml')'

'topology = pdb.topology'

'positions = pdb.positions'

'system = forcefield.createSystem(topology, nonbondedMethod=nonbondedMethod, nonbondedCutoff=nonbondedCutoff,
    constraints=constraints)`

The full error output is this:

Traceback (most recent call last):
  File "/Users/.../run.py", line 161, in <module>
    system = forcefield.createSystem(topology, nonbondedMethod=nonbondedMethod, nonbondedCutoff=nonbondedCutoff,
  File "/Users/.../mambaforge/envs/openmm/lib/python3.9/site-packages/openmm/app/forcefield.py", line 1212, in createSystem
    templateForResidue = self._matchAllResiduesToTemplates(data, topology, residueTemplates, ignoreExternalBonds)
  File "/Users/.../mambaforge/envs/openmm/lib/python3.9/site-packages/openmm/app/forcefield.py", line 1427, in _matchAllResiduesToTemplates
    raise ValueError('No template found for residue %d (%s).  %s' % (res.index+1, res.name, _findMatchErrors(self, res)))
ValueError: No template found for residue 8 (PRO).  The set of atoms is similar to GLN, but it is missing 1 atoms.

Here is my pdb file, which I got from openmm-setup, in full:

REMARK   1 CREATED WITH OPENMM 7.7, 2022-09-01
ATOM      1  N   VAL A   1     -18.268  -4.663   0.000  1.00  0.00           N  
ATOM      2  H2  VAL A   1     -18.652  -5.813   0.131  1.00  0.00           H  
ATOM      3  CA  VAL A   1     -16.807  -4.663   0.000  1.00  0.00           C  
ATOM      4  C   VAL A   1     -16.365  -4.663   1.477  1.00  0.00           C  
ATOM      5  O   VAL A   1     -17.160  -4.663   2.415  1.00  0.00           O  
ATOM      6  CB  VAL A   1     -16.245  -3.483  -0.825  1.00  0.00           C  
ATOM      7  CG2 VAL A   1     -16.531  -2.117  -0.192  1.00  0.00           C  
ATOM      8  CG1 VAL A   1     -14.748  -3.626  -1.108  1.00  0.00           C  
ATOM      9  HA  VAL A   1     -16.485  -5.612  -0.449  1.00  0.00           H  
ATOM     10  H   VAL A   1     -18.731  -4.298   0.827  1.00  0.00           H  
ATOM     11  HB  VAL A   1     -16.747  -3.492  -1.803  1.00  0.00           H  
ATOM     12 HG21 VAL A   1     -17.603  -1.977  -0.020  1.00  0.00           H  
ATOM     13 HG22 VAL A   1     -16.196  -1.311  -0.853  1.00  0.00           H  
ATOM     14 HG23 VAL A   1     -16.012  -1.998   0.765  1.00  0.00           H  
ATOM     15 HG11 VAL A   1     -14.423  -2.871  -1.833  1.00  0.00           H  
ATOM     16 HG12 VAL A   1     -14.520  -4.610  -1.531  1.00  0.00           H  
ATOM     17 HG13 VAL A   1     -14.145  -3.489  -0.205  1.00  0.00           H  
ATOM     18  H   VAL A   1     -18.776  -4.586  -0.877  1.00  0.00           H  
ATOM     19  N   PRO A   2     -15.061  -4.663   1.786  1.00  0.00           N  
ATOM     20  CA  PRO A   2     -14.644  -4.663   3.181  1.00  0.00           C  
ATOM     21  C   PRO A   2     -13.110  -4.663   3.332  1.00  0.00           C  
ATOM     22  O   PRO A   2     -12.315  -4.663   2.398  1.00  0.00           O  
ATOM     23  HA  PRO A   2     -15.032  -3.767   3.678  1.00  0.00           H  
ATOM     24  CD  PRO A   2     -15.626  -5.931   1.377  1.00  0.00           C  
ATOM     25  HD3 PRO A   2     -16.707  -5.801   1.261  1.00  0.00           H  
ATOM     26  HD2 PRO A   2     -15.201  -6.252   0.421  1.00  0.00           H  
ATOM     27  CG  PRO A   2     -15.296  -6.874   2.525  1.00  0.00           C  
ATOM     28  HG3 PRO A   2     -14.307  -7.321   2.372  1.00  0.00           H  
ATOM     29  HG2 PRO A   2     -16.025  -7.684   2.626  1.00  0.00           H  
ATOM     30  CB  PRO A   2     -15.263  -5.947   3.740  1.00  0.00           C  
ATOM     31  HB3 PRO A   2     -14.712  -6.387   4.576  1.00  0.00           H  
ATOM     32  HB2 PRO A   2     -16.290  -5.749   4.071  1.00  0.00           H  
ATOM     33  N   ALA A   3     -12.557  -4.663   4.553  1.00  0.00           N  
ATOM     34  CA  ALA A   3     -11.108  -4.663   4.696  1.00  0.00           C  
ATOM     35  C   ALA A   3     -10.780  -4.663   6.198  1.00  0.00           C  
ATOM     36  O   ALA A   3     -11.641  -4.662   7.076  1.00  0.00           O  
ATOM     37  H   ALA A   3     -13.136  -4.571   5.383  1.00  0.00           H  
ATOM     38  HA  ALA A   3     -10.720  -5.589   4.256  1.00  0.00           H  
ATOM     39  CB  ALA A   3     -10.484  -3.455   4.007  1.00  0.00           C  
ATOM     40  HB1 ALA A   3     -10.732  -3.433   2.941  1.00  0.00           H  
ATOM     41  HB2 ALA A   3     -10.843  -2.520   4.452  1.00  0.00           H  
ATOM     42  HB3 ALA A   3      -9.392  -3.466   4.098  1.00  0.00           H  
ATOM     43  N   PRO A   4      -9.503  -4.663   6.605  1.00  0.00           N  
ATOM     44  CA  PRO A   4      -9.192  -4.662   8.027  1.00  0.00           C  
ATOM     45  C   PRO A   4      -7.674  -4.663   8.293  1.00  0.00           C  
ATOM     46  O   PRO A   4      -6.811  -4.663   7.422  1.00  0.00           O  
ATOM     47  HA  PRO A   4      -9.617  -3.766   8.493  1.00  0.00           H  
ATOM     48  CD  PRO A   4     -10.035  -5.931   6.155  1.00  0.00           C  
ATOM     49  HD3 PRO A   4     -11.105  -5.801   5.957  1.00  0.00           H  
ATOM     50  HD2 PRO A   4      -9.540  -6.252   5.234  1.00  0.00           H  
ATOM     51  CG  PRO A   4      -9.794  -6.874   7.324  1.00  0.00           C  
ATOM     52  HG3 PRO A   4      -8.795  -7.321   7.247  1.00  0.00           H  
ATOM     53  HG2 PRO A   4     -10.528  -7.683   7.370  1.00  0.00           H  
ATOM     54  CB  PRO A   4      -9.851  -5.946   8.538  1.00  0.00           C  
ATOM     55  HB3 PRO A   4      -9.366  -6.386   9.414  1.00  0.00           H  
ATOM     56  HB2 PRO A   4     -10.900  -5.748   8.791  1.00  0.00           H  
ATOM     57  N   ILE A   5      -7.215  -4.662   9.552  1.00  0.00           N  
ATOM     58  CA  ILE A   5      -5.776  -4.663   9.805  1.00  0.00           C  
ATOM     59  C   ILE A   5      -5.597  -4.662  11.335  1.00  0.00           C  
ATOM     60  O   ILE A   5      -6.541  -4.661  12.123  1.00  0.00           O  
ATOM     61  CB  ILE A   5      -5.066  -3.484   9.088  1.00  0.00           C  
ATOM     62  CG1 ILE A   5      -3.531  -3.582   9.214  1.00  0.00           C  
ATOM     63  CD1 ILE A   5      -2.786  -2.672   8.246  1.00  0.00           C  
ATOM     64  HA  ILE A   5      -5.382  -5.611   9.417  1.00  0.00           H  
ATOM     65  CG2 ILE A   5      -5.581  -2.119   9.567  1.00  0.00           C  
ATOM     66 HG13 ILE A   5      -3.214  -4.613   9.017  1.00  0.00           H  
ATOM     67 HG12 ILE A   5      -3.215  -3.335  10.234  1.00  0.00           H  
ATOM     68 HD11 ILE A   5      -2.980  -1.615   8.451  1.00  0.00           H  
ATOM     69 HD12 ILE A   5      -3.070  -2.883   7.210  1.00  0.00           H  
ATOM     70 HD13 ILE A   5      -1.706  -2.832   8.339  1.00  0.00           H  
ATOM     71  H   ILE A   5      -7.811  -4.272  10.276  1.00  0.00           H  
ATOM     72  HB  ILE A   5      -5.314  -3.560   8.021  1.00  0.00           H  
ATOM     73 HG21 ILE A   5      -5.171  -1.308   8.958  1.00  0.00           H  
ATOM     74 HG22 ILE A   5      -5.304  -1.928  10.609  1.00  0.00           H  
ATOM     75 HG23 ILE A   5      -6.671  -2.054   9.487  1.00  0.00           H  
ATOM     76  N   PRO A   6      -4.366  -4.662  11.865  1.00  0.00           N  
ATOM     77  CA  PRO A   6      -4.196  -4.662  13.311  1.00  0.00           C  
ATOM     78  C   PRO A   6      -2.711  -4.662  13.725  1.00  0.00           C  
ATOM     79  O   PRO A   6      -1.767  -4.663  12.943  1.00  0.00           O  
ATOM     80  HA  PRO A   6      -4.664  -3.765  13.733  1.00  0.00           H  
ATOM     81  CD  PRO A   6      -4.852  -5.931  11.365  1.00  0.00           C  
ATOM     82  HD3 PRO A   6      -5.897  -5.800  11.063  1.00  0.00           H  
ATOM     83  HD2 PRO A   6      -4.269  -6.252  10.497  1.00  0.00           H  
ATOM     84  CG  PRO A   6      -4.726  -6.873  12.553  1.00  0.00           C  
ATOM     85  HG3 PRO A   6      -3.725  -7.321  12.574  1.00  0.00           H  
ATOM     86  HG2 PRO A   6      -5.461  -7.682  12.527  1.00  0.00           H  
ATOM     87  CB  PRO A   6      -4.903  -5.945  13.755  1.00  0.00           C  
ATOM     88  HB3 PRO A   6      -4.506  -6.385  14.674  1.00  0.00           H  
ATOM     89  HB2 PRO A   6      -5.971  -5.747  13.904  1.00  0.00           H  
ATOM     90  N   PHE A   7      -2.378  -4.661  15.023  1.00  0.00           N  
ATOM     91  CA  PHE A   7      -0.970  -4.662  15.416  1.00  0.00           C  
ATOM     92  C   PHE A   7      -0.942  -4.661  16.954  1.00  0.00           C  
ATOM     93  O   PHE A   7      -1.962  -4.660  17.642  1.00  0.00           O  
ATOM     94  CB  PHE A   7      -0.232  -3.438  14.850  1.00  0.00           C  
ATOM     95  CG  PHE A   7       1.265  -3.627  14.774  1.00  0.00           C  
ATOM     96  CD2 PHE A   7       2.116  -3.022  15.709  1.00  0.00           C  
ATOM     97  CE2 PHE A   7       3.495  -3.224  15.641  1.00  0.00           C  
ATOM     98  CZ  PHE A   7       4.036  -4.024  14.636  1.00  0.00           C  
ATOM     99  CE1 PHE A   7       3.199  -4.622  13.696  1.00  0.00           C  
ATOM    100  CD1 PHE A   7       1.819  -4.427  13.765  1.00  0.00           C  
ATOM    101  H   PHE A   7      -3.059  -4.381  15.724  1.00  0.00           H  
ATOM    102  HA  PHE A   7      -0.530  -5.601  15.059  1.00  0.00           H  
ATOM    103  HB3 PHE A   7      -0.464  -2.544  15.445  1.00  0.00           H  
ATOM    104  HB2 PHE A   7      -0.587  -3.209  13.836  1.00  0.00           H  
ATOM    105  HD2 PHE A   7       1.711  -2.390  16.497  1.00  0.00           H  
ATOM    106  HE2 PHE A   7       4.150  -2.752  16.370  1.00  0.00           H  
ATOM    107  HZ  PHE A   7       5.111  -4.174  14.579  1.00  0.00           H  
ATOM    108  HE1 PHE A   7       3.620  -5.237  12.905  1.00  0.00           H  
ATOM    109  HD1 PHE A   7       1.176  -4.896  13.021  1.00  0.00           H  
ATOM    110  N   PRO A   8       0.230  -4.661  17.602  1.00  0.00           N  
ATOM    111  CA  PRO A   8       0.257  -4.660  19.058  1.00  0.00           C  
ATOM    112  C   PRO A   8       1.694  -4.661  19.617  1.00  0.00           C  
ATOM    113  O   PRO A   8       2.711  -4.662  18.931  1.00  0.00           O  
ATOM    114  HA  PRO A   8      -0.250  -3.763  19.432  1.00  0.00           H  
ATOM    115  CD  PRO A   8      -0.204  -5.930  17.058  1.00  0.00           C  
ATOM    116  HD3 PRO A   8      -1.214  -5.799  16.654  1.00  0.00           H  
ATOM    117  HD2 PRO A   8       0.462  -6.252  16.251  1.00  0.00           H  
ATOM    118  CG  PRO A   8      -0.196  -6.872  18.252  1.00  0.00           C  
ATOM    119  HG3 PRO A   8       0.797  -7.319  18.372  1.00  0.00           H  
ATOM    120  HG2 PRO A   8      -0.926  -7.681  18.154  1.00  0.00           H  
ATOM    121  CB  PRO A   8      -0.490  -5.943  19.431  1.00  0.00           C  
ATOM    122  HB3 PRO A   8      -0.186  -6.383  20.385  1.00  0.00           H  
ATOM    123  HB2 PRO A   8      -1.568  -5.745  19.474  1.00  0.00           H  
ATOM    124  OXT PRO A   8       1.788  -4.660  20.964  1.00  0.00           O  
ATOM    125  HO  PRO A   8       0.906  -4.659  21.559  1.00  0.00           H  
TER     126      PRO A   8
END

Thanks in advance.

**Comment by peastman** [comment]
You have an extra atom that shouldn't be there:

```
 ATOM 125 HO PRO A 8 0.906 -4.659 21.559 1.00 0.00 H
```

**Comment by KP-303** [comment]
It works fine without that atom, thanks!

**Comment by peastman** [comment]
Glad to hear it!
