### ISSUE TITLE
Adding interaction groups on customNonbondedForce

### ISSUE THREAD

**Issue by smlee99** [openmm/openmm#3762]
Hi Devs.
I'm trying to simulate the solvated peptide on graphene interface using CHARMM36 forcefield. Although the interaction between peptide and carbon atoms in graphene surface is set to be purely LJ (no charge on surface), I'd like to change it to the hard sphere one and see the variation for it. Looking at #2698, I think it would work by excluding the `CustomNonbondedForce` between peptide and graphene and add a new `CustomNonbondedForce` with `addInteractionGroup`. The code is summarized as follows:

```
forcefield = ForceField(strff+'charmm36.xml', strff+'charmm36_spce.xml')
system = forcefield.createSystem(pdb.topology, nonbondedMethod=PME, nonbondedCutoff=cutoff, constraints=HBonds, rigidWater=True)

# Set force group
nbondedForce = [f for f in [system.getForce(i) for i in range(system.getNumForces())] if type(f) == NonbondedForce][0]
customNonbondedForce = [f for f in [system.getForce(i) for i in range(system.getNumForces())] if type(f) == CustomNonbondedForce][0]

nbondedForce.setNonbondedMethod(NonbondedForce.PME)
nbondedForce.setCutoffDistance(cutoff)
customNonbondedForce.setNonbondedMethod(customNonbondedForce.CutoffPeriodic)
print('nbMethod : ', customNonbondedForce.getNonbondedMethod())

###

cvHSforce = CustomNonbondedForce("4*epsilon*((sigma/r)^12 - (sigma/r)^6); sigma = 0.5*(sigma1+sigma2); epsilon = sqrt(epsilon1*epsilon2)")
cvHSforce.addPerParticleParameter('sigma')
cvHSforce.addPerParticleParameter('epsilon')

cvHSforce.setNonbondedMethod(CustomNonbondedForce.CutoffPeriodic)
cvHSforce.setCutoffDistance(cutoff)

for idx in range(system.getNumParticles()):
    [q, sig, eps] = nbondedForce.getParticleParameters(idx)
    cvHSforce.addParticle([sig, eps])

for i in range(nbondedForce.getNumExceptions()):
    (idx0,idx1,q,sig,eps) = nbondedForce.getExceptionParameters(i)
    exforce = cvHSforce.addExclusion(idx0, idx1)

groupGRP = [int(i.index) for i in pdb.topology.atoms() if i.residue.name in ['grp']]
groupPEP = [int(i.index) for i in pdb.topology.atoms() if i.residue.name in ['PEP']]
cvHSforce.addInteractionGroup(groupGRP, groupPEP)
system.addForce(cvHSforce)

```

In here, cvHSforce is not defined to be a hard sphere one but this is just for test. Although it seems like cvHSforce is properly added to the system with proper index in InteractionGroup, the energy for cvHSforce is constantly evaluated to be zero. Since the pre-existing LJ interaction between peptide and graphene interface is excluded, peptide molecule keeps penetrating the graphene interface, which is definitely not a desired consequence. 

I wonder why such situation is happened. Is this due to the crash between preexisting `customNonbondedForce` and newly added one?

**Comment by peastman** [comment]
Is it possible you're adding the force to the system after you've already created your context?  I can't tell since you didn't post the full script.

**Comment by peastman** [comment]
Following up on this, since there was no reply to my last post.  Did you figure out the problem?  If not, can you post enough information to reproduce it?

**Comment by smlee99** [comment]
Sorry for the late response! I figured it out and it turns out that other factor (not mentioned in this issue) was the problem. Let me close this issue.
