### ISSUE TITLE
Constraining group of residues in openmm

### ISSUE THREAD

**Issue by smith-matrix** [openmm/openmm#3763]
Hello openmm users, I am trying to apply a distance restraint on two group of residues. I tried to use system.addConstraint() for it. It is working fine for applying restraint between two atoms but not for group of residues (I am trying one group as all protein residues and another group as all ligand atoms). I tried something like system.addConstraint(:1-358, :359, 10.3*unit.angstroms) but it says illegal atom indices. Does anyone has any idea how to do it?
Thanks in advance.
Rakesh Srivastava, PhD

**Comment by peastman** [comment]
Can you define exactly what you want to do?  A group of atoms doesn't have a single well defined position, so what is the distance you want to constrain?  The distance between what two points?

Also, do you want a constraint or a restraint?  In some places you said one and in some places you said the other.  They're different things.  A constraint is an exact mathematical requirement that a distance must always have a particular value.  A restraint is a force that pushes it toward a certain value while still allowing it to vary.

**Comment by smith-matrix** [comment]
Thanks, Peter, for your kind reply. Sorry for the confusion. I want to restrain the distance between the center of mass of protein atoms and the center of mass of the ligand atoms with a specific force constant.

**Comment by peastman** [comment]
[CustomCentroidBondForce](http://docs.openmm.org/latest/api-python/generated/openmm.openmm.CustomCentroidBondForce.html) is the class you're looking for.  Your code will look something like this.

```python
force = CustomCentroidBondForce(2, '0.5*k*distance(g1, g2)^2')
force.addGlobalParameter('k', force_constant)
force.addGroup(protein_atoms)
force.addGroup(ligand_atoms)
force.addBond([0, 1])
system.addForce(force)
```

Be sure to do this *before* you create the Simulation/Context.  Once it's created, it won't see any further changes you make to the System.

**Comment by smith-matrix** [comment]
Thanks, Peter, for your quick help.

**Comment by peastman** [comment]
I'm closing this since the question has been answered.  Feel free to reopen it if you're still having problems getting it to work.

**Comment by Dead-fisher** [comment]
Hi,

I am wondering if there is a way to constriain the distance between two center of mass? I know I can do the constrain of distance of two particles, but I am not sure if it is feasible to COM.

**Comment by peastman** [comment]
You can add a harmonic *restraint* between the COMs.  That's what this question was about.  The code above shows how to do it.  There's no way to add a *constraint* between them.
