### ISSUE TITLE
Restarining distance between protein center and ligand center in a complex

### ISSUE THREAD

**Issue by smith-matrix** [openmm/openmm#3765]
I want to restrain the distance between the center of mass of the protein and the center of mass of the ligand in a complex. Yesterday I put this query and Peter answered it very well. I applied the suggestions, still I want to make sure if I am doing it correct, as I am very new to openmm. Could you please have a quick look on following piece of code and let me know if its correct?

`p =parsePDB('complex_solvated.pdb')
protein = p.select('protein')
ligand = p.select('resname LIG')
protein_atoms = protein.getIndices()
ligand_atoms = ligand.getIndices()
f = CustomCentroidBondForce(2, '0.5*k*distance(g1, g2)^2')
f.addGlobalParameter('k', 10.0*kilocalories_per_mole/angstrom**2)
f.addGroup(list(protein_atoms))
f.addGroup(list(ligand_atoms))
f.addBond([0, 1])
f.setUsesPeriodicBoundaryConditions(True)
system.addForce(f)`

Thanks in advance.
Rakesh Srivastava, PhD

**Comment by peastman** [comment]
That mostly looks fine.  I don't know what library `parsePDB()` is coming from, but assuming it correctly identifies the atoms you want that should work.  The indices should be 0-based indices of the particles in the System, *not* the atom IDs stored in the PDB file (which can start at any number and may not be consecutive).

**Comment by smith-matrix** [comment]
The parsePDB() function comes from the prody library, and yes, I am saving zero-based indices. Thank you very much, Peter, for your valuable support. It was really quite helpful.
