### ISSUE TITLE
Implicit value substitution when two  `CustomExternalForce` have global parameters with the same name

### ISSUE THREAD

**Issue by yihengwuKP** [openmm/openmm#3768]
# general description
I found that if two custom external forces have global parameters with the same name, the value of the latter one would be substitue by the first one. Also, when I tried to get the parameter value through `getGlobalParameterDefualtValue` it will not print the 'substituted' value but the original value setted by me. (I know that naming two global parameter with the same name is probably not best practice, but this behaviour makes it difficult to debug). I recommand either emphasizing this behaviour in the documentation or throwing errors when two global parameters have the same name.

# version info
```python
print(openmm.__version__)
```
7.7

# procedures to reproduce
```python
import openmm as mm
from openmm import app
from openmm import unit
mass = 40 * unit.amu
system = mm.System()
system.addParticle(mass)

external1 = mm.CustomExternalForce("k*x")
external1.addGlobalParameter("k", 1*unit.kilojoule_per_mole/unit.nanometer)
external1.addParticle(0, [])

external2 = mm.CustomExternalForce("k*y")
external2.addGlobalParameter("k", 2*unit.kilojoule_per_mole/unit.nanometer)
external2.addParticle(0, [])
system.addForce(external1)
system.addForce(external2)
```

When I query through the force object, the paramter values are correct
```python
for i in range(system.getNumForces()):
    f = system.getForce(i)
    print(f" name of the force: {f.getName()}")
    print(f" energy function of the force: {f.getEnergyFunction()}")
    for j in range(f.getNumGlobalParameters()):
        print(f"{f.getGlobalParameterName(j)}: {f.getGlobalParameterDefaultValue(j)}")

for i, f in enumerate(system.getForces()):
    f.setForceGroup(i)
```
name of the force: CustomExternalForce
energy function of the force: k*x
k: 1.0
name of the force: CustomExternalForce
energy function of the force: k*y
k: 2.0

But when i initialize and calculate the potential energy, it's wrong
```python
topology = app.Topology()
element = app.Element.getBySymbol('Ar')
chain = topology.addChain('A')
residue = topology.addResidue('OSC', chain)
topology.addAtom('Ar', element, residue)
integrator = mm.VerletIntegrator(2*unit.femtosecond)
simulation = app.Simulation(topology, system, integrator)
simulation.context.setPositions(np.array([[1, 2, 0]])*unit.nanometer)
for i, f in enumerate(system.getForces()):
    state = simulation.context.getState(getEnergy=True, groups={i})
    print(f.getName(), state.getPotentialEnergy())
```
CustomExternalForce 1.0 kJ/mol
CustomExternalForce 2.0 kJ/mol
Where the second customexternalforce should have 2*2=4kJ/mol as potential energy

**Comment by peastman** [comment]
This is as intended.  Don't think of it as "two parameters".  There's just one parameter that multiple forces depend on.  This is a pretty common thing to do.  For example, in an alchemical simulation you might have a `lambda` parameter to interpolate between end states, and that single parameter would modify multiple bonded and nonbonded forces.

The default value is different from the current value.  The default value sets what the initial value will be for newly created Contexts.  It's a fixed property of the force, so `getGlobalParameterDefaultValue()` doesn't tell you the current value in any particular Context.  If two different forces provide different default values for the same parameter, no guarantee is made about which will take precedence.  It's best not to do that.

**Comment by yihengwuKP** [comment]
Ok, this explanation makes sense, especially the alchemical use case. It's good that this is intended behaviour. Personally I would appreciate it if a short explanation of this is added to the documentation! Thanks for your quick response.

**Comment by peastman** [comment]
Where in the documentation would it be most useful to add it?  Where would you have found it?

Another possibility is to make it throw an exception if two forces define different default values for the same parameter.

**Comment by yihengwuKP** [comment]
the idea to throw an exception when the default value is different also makes sense to me!

**Comment by peastman** [comment]
That makes sense.  Both changes are in #3769.
