### ISSUE TITLE
Feature discussion: Evaluate potential energy for current Positions with different System.

### ISSUE THREAD

**Issue by leeping** [openmm/openmm#377]
As a non-GPU programmer I would like to gauge the difficulty of the following task: storing alternative parameter sets in the Context and being able to evaluate the alternative potential on the fly.  If possible, I think it would speed up the ForceBalance calculation by a fair amount and help @frankmenglin even more than me, and it could potentially have a wider impact than force field parameterization (i.e. improve the efficiency of reweighting approaches, Hamiltonian replica exchange, or on-the-fly parameter adjustment).  

Since this is something I've been thinking about for a while, I'd like to get input from @vijaypande and @jchodera if possible.

The fundamental problem is that ForceBalance needs to evaluate numerical potential energy derivatives for a trajectory by recalculating the potentials using a slightly perturbed force field.  This is normally done in an outer loop over parameters (i.e. ForceBalance creates a `System` object for the perturbed parameter) and an inner loop over the stored coordinates.  The outer loop copies the parameters for the new `System` to the `Context`, and the inner loop sets the positions and computes the potential.

The main issue is that setting the positions takes a significant amount of time and could even become the bottleneck.  For the iAMOEBA and TIP4P calculations, the entire postprocessing step (double loop above) takes roughly as long as the MD simulations itself.  However, for a different system it could take significantly longer as the cost of the postprocessing increases with the # of parameters and the communication overhead of copying the coordinates to the GPU.  For example, Frank's calculation uses RPMD, and copying the coordinates is 32 times more expensive for him.

I've discussed a number of solutions with Peter that are untenable, but here's another idea: the `Context` contains a list of different `System` objects called, for example, `Perturbations`, which are set at `Context` creation time.  (In my case, these `System` objects are almost the same as the original, but with slightly perturbed parameters).  This allows the `Context` to do sanity checks in order to make sure the `Perturbations` really are valid Systems.  Then in order to evaluate the potential for the perturbed parameters, we call `evaluatePerturbationPotentials()` for a list of energies.  

My hope is that OpenMM will be able to easily calculate the potentials for the `Perturbations` for the current set of coordinates on the GPU.  It could even be optimized where only the Forces that are different need to be evaluated, which would be an even greater performance increase for my parameterization calculations.

If you need more evidence that this feature would be worth it, e.g. profiling results, let me know.  I know it would definitely be a great help for me.

**Comment by jchodera** [comment]
@leeping: Is this still a major performance concern that can't be addressed with `Force.updateParametersInContext()` or context variables?

**Comment by leeping** [comment]
I think so.  The performance bottleneck came from resetting the virtual sites when I set the positions in the context, and `Force.updateParametersInContext()` does not address this.  I'm not sure if context variables can address this as I haven't used them before.

**Comment by peastman** [comment]
What exactly do you mean by "resetting the virtual sites"?  Virtual site positions only get calculated when you call one of the following methods: `Context.applyConstraints()`, `Context.computeVirtualSites()`, or `Integrator.step()`.  If you already know the positions, you can just set them and then call `getState()` immediately.  There's no need for it to recompute the virtual site positions first.

**Comment by leeping** [comment]
Hi Peter,

In my application, I am creating new Systems with different virtual site parameters from the existing Context.  I want to rapidly recompute the energy for an existing trajectory with the new virtual site parameters.  If I could copy the virtual site parameters to the Context, then I could simply call `Context.computeVirtualSites()`.  As far as I know, there's no `updateParametersInContext` function for the virtual site parameters (i.e. the weights), so I have to compute the new positions outside of OpenMM and then call `setPositions()`.  The calculation of new positions outside of OpenMM is the most time-consuming.  

The `ResetVirtualSites` command computes the positions in the following script:
https://bpaste.net/show/Uman0KPpforLmu78BThI

Thanks,

- Lee-Ping

**Comment by peastman** [comment]
Ok, I can see why that's slow.  My first thought is to try to speed it up with cython.  This looks like a case where just changing the file type from .py to .pyx and adding a few cdefs might speed it up a lot.

**Comment by peastman** [comment]
Closing this old issue.  I don't think we have any current plans to add this.
