### ISSUE TITLE
Problems with residue template matching when atoms have incorrect names

### ISSUE THREAD

**Issue by rosemary-cresset** [openmm/openmm#3775]
Hi, 

I'm having some issues with template matching when atom names are wrong in PDB files. 

I've added an H to A ASP 68 in the following file to make the residue neutral, and as the H atom is correctly called HD2, everything works OK. 
[input_OK.pdb.txt](https://github.com/openmm/openmm/files/9549438/input_OK.pdb.txt)

I can prove this is OK by running the following python snippet that prints out residues that didn't match any templates and I don't see ASP printed. 

```
import openmm.app as app
pdb_file = app.PDBFile('input.pdb')
force_field = app.ForceField('amber/protein.ff14SB.xml', 'amber/tip3p_standard.xml')
unmatched_residues = force_field.getUnmatchedResidues(pdb_file.topology)
for r in unmatched_residues:
    print(r.name)
```

However, in the following PDB file, I have given the H atom the incorrect name H1 and this time ASP is printed when using the above python snippet, i.e. it didn't match any residue templates. 
[input_notOK.pdb.txt](https://github.com/openmm/openmm/files/9549437/input_notOK.pdb.txt)

I was under the impression that things like atom and residue names did not have to be correct for template matching to occur - is that right? 

Thanks, 

Rosie

**Comment by peastman** [comment]
Take a look at https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template.  It discusses the issues involved here.  The short version is that names do matter, not because the template matcher cares about them but because the PDB loader needs names to know where to add bonds.

**Comment by rosemary-cresset** [comment]
Thanks very much for your help, that makes sense. I will close this ticket.
