### ISSUE TITLE
How to implement a flat-bottom RMSD restraining force?

### ISSUE THREAD

**Issue by apayne97** [openmm/openmm#3776]
I have state A and state B structures, and I am running metadynamics with RMSDForce with the RMSD from state A to state B as my collective variable. Doubts about whether this will work aside, one of the things I would like to do is add a flat-bottom potential for the RMSD to state A which would keep it from going too far away from state A.

The functional form would look something like:
```
E = step(RMSD - RMSDmax) * (K/2) * (RMSD - RMSDmax)^2
K = spring constant
RMSD = RMSD(to state A)
RMSDmax = the point at which we want the restraint to kick in
step(RMSD - RMSDmax) = 0; if RMSD - RMSDmax < 0
step(RMSD - RMSDmax) = 1; if RMSD - RMSDmax > 0
```
The goal is to get from state A to state B without spending a lot of time that is further away from State A than the maximum RMSD to state B.

I feel like between the RMSDForce, CustomForce, and the openmmtools FlatBottomRestraintForce I should be able to implement this relatively trivially but I can't quite put the pieces together.

Thanks!

--
EDITED: I guess the `step` function here is just a binary transfer function! And this 'well' is one sided.

**Comment by peastman** [comment]
You can definitely do that.  The class you want is [CustomCVForce](http://docs.openmm.org/latest/api-c++/generated/CustomCVForce.html).  You add other forces inside it to compute collective variables, and it computes an energy as a function of them.  In your case you will use an RMSDForce to compute the RMSD, and then have CustomCVForce apply the potential `"(k/2)*max(0, rmsd-rmsdmax)^2"`.

**Comment by apayne97** [comment]
Thanks @peastman !
so something like this?
```
rmsd_cv = openmm.RMSDForce(positions, atom_indicies)
energy_expression = f"(k/2)*max(0, RMSD-RMSDmax)^2"
restraint_force = openmm.CustomCVForce(energy_expression)
restraint_force.addCollectiveVariable('RMSD', rmsd_cv)
restraint_force.addGlobalParameter('RMSDmax', 0.4)
restraint_force.addGlobalParameter("k", 50)
```

And then to write it out would best practice be to:
1) add this force to a force group
2) get the state with that force group in a custom reporter
3) write out `state.getPotentialEnergy()`, `state.getForces()`

**Comment by peastman** [comment]
Exactly.

**Comment by apayne97** [comment]
This doesn't seem to be working for me. I've uploaded a jupyter notebook to play around with it.

The simple "negative control" I'm trying to run is, if make this customCVforce in its own force group (20), and then set the spring_constant to 0, then my resulting potential energy should be 0, right? But it isn't. And if I increase the value of the force or change the values of RMSDmax then nothing seems to be happening.

Thanks for helping out with this! I'm trying to get the hang of this kind of thing because I want to run some different kinds of enhanced sampling, all of which will involve playing around with adding and reporting various CVs and forces.

[for_openmm_issue.zip](https://github.com/openmm/openmm/files/9582750/for_openmm_issue.zip)

**Comment by peastman** [comment]
In your call to `getState()`, you specify the groups incorrectly.  It should be `groups={force_group}`, not `groups=force_group`.  If you pass a single int instead of a set, it gets interpreted as a set of bit flags.

**Comment by apayne97** [comment]
Ohhhh I can't read. My eyes just glazed over "groups (set={0,1,2,...,31})" in the documentation and for some reason assumed just that it meant that the integer input had to be between 0 and 31. And I had no idea what the rest of the sentence meant. Thanks so much!!! Super simple fix.

**Comment by peastman** [comment]
It can be kind of confusing.  In the C++ API, the argument is always bit flags.  The Python wrapper adds the option to pass a `set` as a convenience.

**Comment by CayetanaZF** [comment]
Hey guys, 
In relation to flat bottom restraining forces, can OpenMM generate this type of potential with a custom geometry and inverted? For example an yz plane to maintain separate two spaces.

BR,

Caye

**Comment by peastman** [comment]
If you can express it as a custom force, it can do it.  I don't know what you mean by "custom geometry" or by "inverted".

**Comment by CayetanaZF** [comment]
By custom geometry I meant for different geometries like a cylinder, layer, plane, etc restraint potential. And by inverted, in Gromacs there's a tool to create this kind of potential and it does a force toward the geometry to set the molecule/protein inside (like a container), so and inverted potential would be the opposite; that maintain everything outside the container.

**Comment by peastman** [comment]
Sure, you can do any of those.  With CustomExternalForce, you can write any function of the `x`, `y`, and `z` coordinates you want.

**Comment by CayetanaZF** [comment]
Dear Peter, 

TYVM for those answers! But, I’ve not been able to write the potential mathematical expression of a plate with a hole. How could it be?

Best regards, 

Cayetana

**Comment by peastman** [comment]
You want something that pushes atoms away from a zone centered on x=0, using a similar function to [the one in Gromacs](https://manual.gromacs.org/current/reference-manual/functions/restraints.html)?  I think this should work.

```python
force = CustomExternalForce('0.5*k*min(0, abs(x)-rfb)^2`)
force.addGlobalParameter('k', k)
force.addGlobalParameter('rfb', rfb)
```

where you need to provide the values you want for `k` and `rfb`.  If $|x|>r_{fb}$ the energy is 0.  Once $|x|$ falls below $r_{fb}$ the energy increases quadratically.  Be aware this has a cusp at $x=0$, as shown in figure 30 at the above link.  That will cause problems for integration, so you want to set `k` large enough that particles never reach it.

**Comment by CayetanaZF** [comment]
Dear Peter, 

Something that pushes atoms away with the hole region as exception (because It would be the entrance to my system) is exactly what I need. I’ll try it and I’ll let you know if it works!
TYVM in advanced!

Best regards, 

Cayetana

**Comment by CayetanaZF** [comment]
> You want something that pushes atoms away from a zone centered on x=0, using a similar function to [the one in Gromacs](https://manual.gromacs.org/current/reference-manual/functions/restraints.html)? I think this should work.
> 
> ```python
> force = CustomExternalForce('0.5*k*min(0, abs(x)-rfb)^2`)
> force.addGlobalParameter('k', k)
> force.addGlobalParameter('rfb', rfb)
> ```
> 
> where you need to provide the values you want for `k` and `rfb`. If |x|>rfb the energy is 0. Once |x| falls below rfb the energy increases quadratically. Be aware this has a cusp at x=0, as shown in figure 30 at the above link. That will cause problems for integration, so you want to set `k` large enough that particles never reach it.

Dear Peter,

It worked! But, now I need to add a component in the mathematical expression to null the potential around a circle centered in the X axe with a radius r because it would be the entrance to the translocation system. Also, I was thinking to add a cylindrical restraint to displace the protein to the entrance. 

TYVM! And, If you come up with any idea please contact me!

Best regards, 

Cayetana

**Comment by peastman** [comment]
I don't quite understand what you mean.  You talk about a circle, but the potential is a slab.  It isn't circular.  I'm also not sure what you mean by "null the potential."  Can you describe as precisely as possible exactly what you want the potential to be?  Draw a picture of it, if that would help.

**Comment by peastman** [comment]
> The restraining potential must be zero for the region of the gray circle.

Do you really mean the potential should be zero, or just that it should be constant (so the force is zero)?

What happens when a particle moves outside the gray cylinder?  Should the force abruptly jump to a non-zero value, or should it grow smoothly?

What does the blue plane represent?

Outside of the cylinder, do you still want a force that repels particles from a region around $x=0$?

**Comment by CayetanaZF** [comment]
Dear Peter, 

The blue plane represent the geometry of the inverted potential that pushes the atoms away restraining to the cylinder region. And yes, you're right, the potential can't be zero inside the grey circle region, rather constant so the force is 0. Inside the gray cylinder the particles experiment a potential:

        energy_function = "U_cylinder;"
        energy_function += "U_cylinder = V*(((p_yz/R_cylinder)^(2*Smooth_step_like_fnc))*x_step_fcn*Smooth_step_like_fnc;"
        energy_function += "Smooth_step_like_fnc= (1 + tanh(alpha*x_fcn))/2;"
        energy_function += "x_fcn = x*(L-x);"
        energy_function += "p_yz = sqrt(y^2+z^2);"

So, outside the grey cylinder the energy increment exponentially. Finally,  in relation to your last question, yes I still want want a force that repels particles from a region around, but on second thought, my cylinder potential already do that, right? (maintain the protein inside the cylinder)

Best regards,

Cayetana
