### ISSUE TITLE
Efficiency of nonbonded custom force

### ISSUE THREAD

**Issue by LipikaBaidya** [openmm/openmm#3777]
Hi,
I am trying to implement the custom nonbonded force for my system. I have some doubts about the efficiency of the method I am using. To give an example:
Let's say, I have 10 particles with different epsilon and radii. The energy expression for custom force is E_ij = eps_ij * [(sigma_ij/r_ij)^12 - 2* (sigma_ij/r_ij)] where r_ij distance between two particle, sigma_ij = radii_i + radii_j. eps_ij has different values for different pairs defined by the matrix:

[0.                  0.                 0.1            0.2                0. 1        0. 11      0.2693609       0.21848162 0.2693609  0.21848162]
 [0.                 0.                 0.2            0.23              0.12       0.           0.18555973     0.2783396  0.18555973 0.2783396 ]
 [0.1               0.2               0.              0.2                0. 45      0.33       0.2                   0.11            0.2693609  0.21848162]
 [0.2               0.23             0.2            0.                   0.1         0.11       0.12                 0.4           0.17957393 0.16460944]
 [0.1               0. 12            0.45          0.1                  0.           0.01       0.11                 0.2           0.                 0.        ]
 [0. 11            0.                 0.33           0.11                0.01         0.         0.1                   0.2          0.3               0.4        ]
 [0.2693609  0.18555973  0.2             0.12                0.11         0.1        0.                   0.21         0.                0.        ]
 [0.21848162 0.2783396   0.11            0.4                  0.2         0.2         0.21               0.         0.3                  0.4        ]
 [0.2693609  0.18555973  0.2693609  0.17957393     0.         0.3         0.                   0.3         0.                   0.33        ]
 [0.21848162 0.2783396   0.2184816  0.16460944    0.         0.4           0.                  0.4         0.33               0.        ]

To implement this energy E_ij I used the tabulated function: 

nonLocal_interaction = openmm.CustomNonbondedForce("epsNL*(((sigmaNL/r)^12-2*(sigmaNL/r)^6); sigmaNL=fsigmaNL(type1,type2);epsNL=fepsNL(type1,type2);rcut=frcut(type1,type2)")
nonLocal_interaction.addTabulatedFunction('fsigmaNL',openmm.Discrete2DFunction(ntot,ntot,sigma_bead_linear))
nonLocal_interaction.addTabulatedFunction("fepsNL",openmm.Discrete2DFunction(ntot,ntot,epsilonNL_linear))
nonLocal_interaction.addPerParticleParameter('type')

But implementing E_ij using tabulated is taking a lot of computational time. Is there any efficient way to implement this energy and force?

**Comment by peastman** [comment]
Using a tabulated function is generally more expensive than a combining rule, just because of the way computers work.  How much more expensive depends on a few factors.  Which platform are you using?  If it's CUDA or OpenCL, what kind of GPU?  And how many particles are in the system?

Since your table is so small, only 100 numbers, it ought to get kept in L1 cache and not add much memory latency.  But it depends on the details.

In your code I see you're using tabulated functions for both sigma and epsilon.  Since sigma can be computed from per-particle parameters as `sigmaNL=sigma1+sigma2`, that might be faster.

> But implementing E_ij using tabulated is taking a lot of computational time.

How much time?  That is, how much slower is it when using a tabulated function than when using a combining rule?

**Comment by LipikaBaidya** [comment]
My matrix can be 1000x1000 or more than that. I am using cpu right now. I have around 250 particle.  The performance of openmm code is 7 times slower than my hard written c code running on single core. 

I think I can convert the energy function  in such a way that I can use combination rule without using tabulated function.  


If I use normal combination rule does it reduce the computation time?

**Comment by peastman** [comment]
A 1000x1000 matrix with 250 particles???  Does that mean you have more types than particles?

A tabulated function should be reasonably efficient when you have a relatively small number of atom types so the table isn't too big.  If you need a separate row of the table for every atom, that will be really slow.  It requires O(n^2) memory, which leads to very inefficient cache usage and a lot of time wasted on latency.

Note that on the CPU platform, custom forces can be significantly slower than standard forces.  On CUDA and OpenCL, there's very little difference in speed between standard and custom forces.  Also note that the upcoming 8.0 release has a lot of optimizations to custom forces on the CPU platform, so the speed difference will become a bit smaller.

> If I use normal combination rule and exclusion (force.addexclusion) does it reduce the computation time compare to tabulated function?

Yes, it should be much faster.  In that case the memory only scales as O(n) instead of O(n^2) with the number of atoms.

**Comment by LipikaBaidya** [comment]
Thanks Peter. It helped a lot. The matrix is of NXN length where N is the number of particles. Although I am running the system with N = 250 but later I will use this script to run other systems which has N = 10000 or more than that. So, it is very important to implement this energy function efficiently. I hope using normal combination rule with exclusion will reduce the computation time. I will check that and compare the with the tabulated function.

**Comment by LipikaBaidya** [comment]
Can I use cutoff in the custom bonded force? Then I can convert the previously discuss potential in the system using the script below:

NBforce = openmm.CustomBondForce("eps * ((sigma/r)^12-2*(sigma/r)^6)")
NBforce.addPerBondParameter('eps')
NBforce.addPerBondParameter('sigma')
for i in range(N):
    for j in range(N):
          NBforce.addBond(i,j,[eps_ij,sigma_ij])
         
I only need to add a cutoff distance but in the documentation, I did not get any information regarding the cutoff of custom bonded force. Is it possible to use a cutoff for the custom bonded force?

**Comment by peastman** [comment]
You can write an expression that goes to zero beyond some cutoff distance, but it won't make the calculation faster.  It will still get evaluated for every bond.  That would be a very slow way of evaluating nonbonded forces.

Can you give some background on what you're trying to do?  What kind of model is this?  How does the epsilon for each pair get determined?

**Comment by LipikaBaidya** [comment]
1) `Can you give some background on what you're trying to do? What kind of model is this? How does the epsilon for each pair get determined?
`
I am trying to implement the equation 4 from article: https://doi.org/10.1021/acs.jpcb.2c03476

In this model, first and second term of equation 4 can be implemented with custom nonbonded force + combination rule for epsilon (ep_ij = sqrt(ep_i * ep_j) ). But the epsilon values corresponds to third term of equation 4 is different for every pair.  

For example: We can write the terms like this:

First term: (Backbone-Backbone)

```
for i in range(0,N-6,2):
    for j in range(i+6,N,2):
           energy = eps * ( (sig/r)^12 - 2 * (sig/r)^6 ) ; eps = sqrt(eps_i * eps_j); sig = sig_i + sig_j
```


Second term:(Backbone-Sidechain) && (Sidechain-Backbone)

```
for i in range(0,N-6,2):
    for j in range(i+7,N,2):
           energy = eps * ( (sig/r)^12 - 2 * (sig/r)^6 ) ; eps = sqrt(eps_i * eps_j); sig = sig_i + sig_j

for i in range(1,N-6,2):
    for j in range(i+5,N,2):
           energy = eps * ( (sig/r)^12 - 2 * (sig/r)^6 ) ; eps = sqrt(eps_i * eps_j); sig = sig_i + sig_j
```
Third term: (sidechain-sidechain)

```
for i in range(1,N-6,2):
    for j in range(i+6,N,2):
           energy = eps_ij * ( (sig/r)^12 - 2 * (sig/r)^6 ) ;  sig = sig_i + sig_j
```

Here, in the third term eps_ij is given for each pair ij,  not for i and j separately.

2) I have another issue. When I am running the my openmm script on my macbook pro (M1 chip) using OpenCL platform, It was getting  killed after ~2*10^8 steps every time with the error message:

`zsh: killed     python simulate.py`

Can you please tell how can solve this?

**Comment by peastman** [comment]
Based on the paper, it looks to me like the epsilon depends only on the amino acid types?  You should only need a 20x20 table, no matter how large your system is.  If that's not the case, how do you calculate the value for each pair?

**Comment by LipikaBaidya** [comment]
Yes, you are right But I need to exclude force between some other pairs also. For example:

```
for i in range(N):
     for j in range(i+3,i+6):
             force.addexclusion(i,j)
```

But the problem is I want to exclude these pairs only for the nonlocal potential mentioned in equation 4 from article: https://doi.org/10.1021/acs.jpcb.2c03476. I dont want to exclude these pairs for other nonbonded force like electrostatic. 
If I exclude these pairs from customNonbonded force, it will exclude the force for other nonbonded force also.

How to take care of this?
