### ISSUE TITLE
Installing openmm on the cluster without root access

### ISSUE THREAD

**Issue by LipikaBaidya** [openmm/openmm#3778]
I am trying to install openmm on a cluster where I don't have root access. I am getting an error when providing the installing command 

conda install -c conda-forge openmm

I am getting error

Collecting package metadata (current_repodata.json): failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/conda-forge/linux-64/current_repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
'https://conda.anaconda.org/conda-forge/linux-64'

How can I solve the issue?

**Comment by peastman** [comment]
Did you try repeating it like it suggested?  That indicates a network problem.  It wasn't able to connect to the repository.  This has nothing to do with root access.

**Comment by LipikaBaidya** [comment]
Yes I run the command below multiple times. 

conda install -c conda-forge openmm

But it is giving the same error.

**Comment by peastman** [comment]
That means there's a problem with the network.  You need to talk to the cluster administrators.

**Comment by LipikaBaidya** [comment]
Ok thanks for the suggestion. But I am installing openmm on my home directory. I think conda-forge is included in the anaconda distribution. Do you think there might be a problem in installing anaconda?

**Comment by peastman** [comment]
There shouldn't be any problem installing it in your home directory.

**Comment by LipikaBaidya** [comment]
But I am getting the error and openmm is not getting installed due to the this error. Do you have any suggestions?

**Comment by peastman** [comment]
Again, you need to talk to your cluster administrator.  This has nothing to do with OpenMM.  It indicates a problem in your network connection.

**Comment by LipikaBaidya** [comment]
Ok thanks.
