### ISSUE TITLE
How to get the free energy corrections when we applied position restraints during the simulations?

### ISSUE THREAD

**Issue by divya938** [openmm/openmm#3784]
I am using the following code to restrain the position of a molecule during the simulations. 
```
restraint = HarmonicBondForce()
restraint.setUsesPeriodicBoundaryConditions(True)
system.addForce(restraint)
nonbonded = [f for f in system.getForces() if isinstance(f, NonbondedForce)][0]
atomsToRestrain=[0,1000,10000]
dummyIndex = []
positions = pdb.positions
for i in atomsToRestrain:
    j = system.addParticle(0)
    nonbonded.addParticle(0, 1, 0)
    nonbonded.addException(i, j, 0, 1, 0)
    restraint.addBond(i, j, 0*nanometers, 100*kilojoules_per_mole/nanometer**2)
    dummyIndex.append(j)
    positions.append(positions[i])
```
I am using MMPBSA to estimate the binding affinity from the simulations. As the positions restraints are applied to a molecule, how to et the correction term for free energy?

**Comment by peastman** [comment]
Unless you have a good reason for needing to add dummy atoms, [this method](https://openmm.github.io/openmm-cookbook/dev/notebooks/cookbook/Restraining%20Atom%20Positions.html) will probably be simpler.  It uses a CustomExternalForce.

Anyway, I think the question you're asking is how to query the energy of the restraint force?  You do it by placing that force in its own force group.  [This cookbook entry](https://openmm.github.io/openmm-cookbook/dev/notebooks/cookbook/Analyzing%20Energy%20Contributions.html) shows how to do it, except it's a little more complicated than you need.  It fully decomposes the energy, while you just need the energy of that one force.  But the idea is the same: call `setForceGroup()` on it to assign it to a group, then use the `groups` argument to `getState()` to query it.

**Comment by peastman** [comment]
I'm closing this, since I believe the question has been answered.  If something still isn't clear, let me know.
