### ISSUE TITLE
How can I add solvent into system with CHARMM input?

### ISSUE THREAD

**Issue by OkKakao** [openmm/openmm#3786]
Hi.

I'm trying to simulate CB7 in the H2O molecules.

I tried adding solvent molecules into system with modeller class, however, did not work.

I think that str and prm file must have contribution to modeller, but I don't know how to achieve such state.

How can I add solvent molecules into the system?
```
from openmm.app import *
from openmm import *
from openmm.unit import *
from sys import stdout

forcefield = ForceField('amber14/tip3p.xml')

conc = 0.38
box = 4.0
name = '../parameters/cb7'

params = CharmmParameterSet('../parameters/cb1.str', '../parameters/par_all36_cgenff.prm')
print(params)
psf = CharmmPsfFile('../parameters/cb7.psf')
pdb = PDBFile(f'{name}.pdb')
modeller = Modeller(psf.topology, pdb.positions)
modeller.addSolvent(forcefield, ionicStrength=conc*molar, boxSize=Vec3(box, box, box)*nanometers)
```

**Comment by peastman** [comment]
There are two ways of setting up a simulation like this, depending on whether you're doing the modelling and parameter assignment in CHARMM or in OpenMM.  Using a PSF file and parameter files means you're doing it all in CHARMM and loading files that have parameters already assigned.  The alternative is to do them in OpenMM, using Modeller for modelling operations and then ForceField to assign parameters.

You're trying to mix those approaches, using OpenMM for modelling but CHARMM for parameter assignment, which doesn't work.  You either need to add the solvent in CHARMM (which will produce a PSF file with parameters for everything), or else you need to use ForceField to assign parameters (which means converting the parameters for your nonstandard molecule to OpenMM's format).

**Comment by OkKakao** [comment]
> There are two ways of setting up a simulation like this, depending on whether you're doing the modelling and parameter assignment in CHARMM or in OpenMM. Using a PSF file and parameter files means you're doing it all in CHARMM and loading files that have parameters already assigned. The alternative is to do them in OpenMM, using Modeller for modelling operations and then ForceField to assign parameters.
> 
> You're trying to mix those approaches, using OpenMM for modelling but CHARMM for parameter assignment, which doesn't work. You either need to add the solvent in CHARMM (which will produce a PSF file with parameters for everything), or else you need to use ForceField to assign parameters (which means converting the parameters for your nonstandard molecule to OpenMM's format).

Then what I need is tip3p psf file or CB7 xml file, right?

**Comment by peastman** [comment]
If you want to do the setup in CHARMM, you need to use it to build the water box.  If you want to do the setup in OpenMM then yes, you need an xml file for CB7.

**Comment by OkKakao** [comment]
I somehow built the water box...
