### ISSUE TITLE
Register new template : unsuccessful

### ISSUE THREAD

**Issue by ststevanovic** [openmm/openmm#3787]
Greetings ! 

I am having trouble with the broken bonds after minimization / simulations:

Here's the setup:
```
pdb = PDBFile(test.pdb)
forcefield = ForceField('amber14-all.xml', 'amber14/tip3pfb.xml')
unmatched_residues = forcefield.getUnmatchedResidues(pdb.topology)
```
from the output:
> {'test.pdb': [[<Residue 2 (NEW) of chain 0>]]}

After which I generate parameters like so:

```
template_info = json.load(open("params/template_params.json"))
[templates, residues ] = forcefield.generateTemplatesForUnmatchedResidues(pdb.topology)

for template in templates:
    
    template_name = template.name
    atoms = template.atoms 

    for en, atom in enumerate(atoms):
        atoms[en].type = template_info[template.name]['atom_types'][atom.name]
        charge = template_info[template.name]['atom_charges'][atom.name]
        atoms[en].parameters = {"charge": charge}

    template.atoms = atoms 

    if not template_name in forcefield._templates.keys():
             forcefield.registerResidueTemplate(template)
```
    
Note: I also tried importing my_template_params.xml into forcefiled, but it just won't recognize the template (I have looked into: https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template) but was unsuccessful.  

After I save the structure using ```PDBFile.write``` it looks like everything is in order. 
![image](https://user-images.githubusercontent.com/33319518/191245186-7e580cf6-e019-44f5-9eb7-75562ddcbd29.png)

After I create simulation obj. and do ```simulation.minimzeEnergy()```, I get broken bonds at specific places, like so:
![image](https://user-images.githubusercontent.com/33319518/191246270-05085011-3c84-472e-845d-92de5a584994.png)

Now, the triazole ring seems to be destroyed for some reason. What I thought to be the issue is the order of atoms and bonds in the pdb: after `C9` jumping to `N8` and then connecting the ring backwards. Or maybe the name of the atoms, but I am not confident it should be the issue (?) I did change the order of atoms and bonding in the pdb but had no success. 

Moreover, the bonding seems correct (as registered by the forcefield):

```
Bond(<Atom 81 (C9) of chain 0 residue 2 (NEW)>, <Atom 83 (C10) of chain 0 residue 2 (NEW)>)      
Bond(<Atom 81 (C9) of chain 0 residue 2 (NEW)>, <Atom 84 (N10) of chain 0 residue 2 (NEW)>)      
Bond(<Atom 82 (N9) of chain 0 residue 2 (NEW)>, <Atom 80 (N8) of chain 0 residue 2 (NEW)>)       
Bond(<Atom 82 (N9) of chain 0 residue 2 (NEW)>, <Atom 84 (N10) of chain 0 residue 2 (NEW)>)      
Bond(<Atom 83 (C10) of chain 0 residue 2 (NEW)>, <Atom 80 (N8) of chain 0 residue 2 (NEW)>)      
Bond(<Atom 83 (C10) of chain 0 residue 2 (NEW)>, <Atom 97 (H10) of chain 0 residue 2 (NEW)>)     
Bond(<Atom 80 (N8) of chain 0 residue 2 (NEW)>, <Atom 85 (C11) of chain 0 residue 2 (NEW)>)      
Bond(<Atom 85 (C11) of chain 0 residue 2 (NEW)>, <Atom 86 (C12) of chain 0 residue 2 (NEW)>)     
Bond(<Atom 85 (C11) of chain 0 residue 2 (NEW)>, <Atom 105 (H111) of chain 0 residue 2 (NEW)>)   
Bond(<Atom 85 (C11) of chain 0 residue 2 (NEW)>, <Atom 107 (H112) of chain 0 residue 2 (NEW)>) 
```

Any help is much appreciated!  
I believe I am missing something trivial, although crucial. 

Thanks in advance!

**Comment by peastman** [comment]
I can't really tell what you're doing from the brief bits of code you quoted.  Can you provide a complete example?

There are various places things might be going wrong.  Your input topology might be incorrect.  For example, it might have the wrong bonds.  Or you might be setting up the template incorrectly, for example by assigning the wrong atom types.  Or the template could be fine but there's a problem in the force field, for example if you have a bond between two atoms, but the force field doesn't define any parameters for a bond between those types.

To debug it, I suggest starting at the end.  Identify a particular pair of atoms that you expect to be bonded, but behave as if they aren't.  Given the System returned by `createSystem()`, call `getForces()` to find the HarmonicBondForce and see if you can find a bond between those atoms.  Is it there?  If so, are the parameters for it correct?

Assuming it's either missing or has incorrect parameters, work backward.  Does the topology have a bond between them?  What about the template?  What atom types does it assign to them?  Does the force field define bond parameters between those types?

**Comment by ststevanovic** [comment]
Dear Peter, 

Thank you so much for the debugging hint! 
I actually made some progress and got an insight how to work this out. 

So the thing was with the force field's HarmonicBondForces and what I got when applied mock params was this:
![image](https://user-images.githubusercontent.com/33319518/191457851-68d05e30-5d7e-487d-9c58-4f489514a5e9.png)

Now, I believe the additional `N-C` bonds emerge because of the wrong atom-types for N8 to N10. These are ...the same... and being wrong - bonds form based on the given params from amber14-all.xml.
 
It that is the case, I think I figured it out. 
Again, thank you so much!

Here is the most of the workable code:
```
from openmm.app import PDBFile, ForceField, Modeller, Simulation, PME, HBonds
from openmm.unit import nanometers, kelvin, picosecond, picoseconds, nanometer
from openmm import LangevinMiddleIntegrator 
import json
# OpenMM Version: 7.7
# Git Revision: 130124a3f9277b054ec40927360a6ad20c8f5fa6

pdb = PDBFile("test.pdb")
forcefield = ForceField('amber14-all.xml', 'amber14/tip3pfb.xml')

template_info = json.load(open("params/template_params.json"))
[templates, residues ] = forcefield.generateTemplatesForUnmatchedResidues(pdb.topology)

for template in templates:
    
    template_name = template.name
    atoms = template.atoms 

    for en, atom in enumerate(atoms):
        atoms[en].type = template_info[template.name]['atom_types'][atom.name]
        charge = template_info[template.name]['atom_charges'][atom.name]
        atoms[en].parameters = {"charge": charge}

    template.atoms = atoms 

    if not template_name in forcefield._templates.keys():
             forcefield.registerResidueTemplate(template)

# Testing if anything changes, with manual harmonic bond forces assignment:
def add_harmonic_bonds(system, params):
    harmonic_bond_forces = system.getForces()[0]
    for param in params:
        p1,p2,l,k = param
        harmonic_bond_forces.addBond(p1,p2,l,k)
    system.getForces()[0] = harmonic_bond_forces
    return system

# Mock some params:
test_params = [
    # c9-n10
    [81, 84, 0.1298, 399153.5999999999],
    # n10-n9
    [84, 82, 0.1396, 462800.5999999999],
    # n9-n8
    [82, 80, 0.1396, 462800.5999999999],
    # n8-c10
    [80, 83, 0.1298, 399153.5999999999],
    # n8-c11 
    [80, 85, 0.1449, 282001.5999999999],
    # c11 - c12
    [85, 86, 0.1525, 259407.99999999994]
]

# Creating the system:
modeller = Modeller(pdb.topology, pdb.positions)
modeller.addSolvent(forcefield, padding=1.0*nanometers)
PDBFile.writeFile(modeller.topology, modeller.positions, open('modeller.pdb', "w"))

system = forcefield.createSystem(modeller.topology, nonbondedMethod=PME,
        nonbondedCutoff=1*nanometer, constraints=HBonds)

system = add_harmonic_bonds(system, test_params)

integrator = LangevinMiddleIntegrator(300*kelvin, 1/picosecond, 0.004*picoseconds)
simulation = Simulation(modeller.topology, system, integrator)
simulation.context.setPositions(modeller.positions)
simulation.minimizeEnergy(1.0)

PDBFile.writeModel(simulation.topology, simulation.context.getState(getPositions=True).getPositions(), open('system.minim.pdb', "w"))
```

Topology file (partial):
```
ATOM     81  N8  NEW W  11      24.629  30.805  20.961  1.00  0.00           N  
ATOM     82  C9  NEW W  11      26.571  30.513  21.845  1.00  0.00           C  
ATOM     83  N9  NEW W  11      24.528  29.760  21.806  1.00  0.00           N  
ATOM     84  C10 NEW W  11      25.895  31.321  20.966  1.00  0.00           C  
ATOM     85  N10 NEW W  11      25.722  29.570  22.351  1.00  0.00           N  
ATOM     86  C11 NEW W  11      23.502  31.198  20.132  1.00  0.00           C  
ATOM     98  H10 NEW W  11      26.257  32.128  20.434  1.00  0.00           H  
ATOM    106 H111 NEW W  11      22.616  30.731  20.508  1.00  0.00           H  
ATOM    108 H112 NEW W  11      23.420  32.264  20.167  1.00  0.00           H  
CONECT   79   77   80   82
CONECT   82   79   84   85
CONECT   83   81   85
CONECT   84   81   82   98
CONECT   81   83   84   86
CONECT   85   82   83
CONECT   86   81   87  106  108
CONECT   87   86   88   92
CONECT   98   84
CONECT  106   86
CONECT  108   86
END
```

And finally the template in `json`.
Params carrying the source of err. in the same atom types :)
 ```
{
    "NEW": {
        "atom_types": {
            "N8": "DNA-NA",
            "N9": "DNA-NA",
            "N10": "DNA-NA",
            "C9": "DNA-CT",
            "C10": "DNA-CM",
            "C11": "DNA-CJ",
            "C12": "DNA-CM",
            "H10": "DNA-H4",
            "H111": "DNA-H1",
            "H112": "DNA-H1",
        },
        "atom_charges": {
            "N8": "-0.2643",
            "N9": "-0.0678",
            "N10": "-0.1295",
            "C9": "-0.2269",
            "C10": "0.0504",
            "C11": "-0.0011",
            "C12": "-0.0431",
            "H10": "0.0846",
            "H111": "0.0361",
            "H112": "0.1900",
        }
    }
}
```

**Comment by peastman** [comment]
Glad to hear it!  I'm going to close this since you have it working.  Feel free to reopen it if you find it still isn't working.
