### ISSUE TITLE
Slow context creation with very large Discrete3DFunction

### ISSUE THREAD

**Issue by tristanic** [openmm/openmm#3789]
Very large serialised system available at https://drive.google.com/file/d/1OsuZS0vpHrcBcOPECZZmU7z_38mN8dS9/view?usp=sharing if necessary, but from the behaviour I suspect I know what's happening. ISOLDE's MDFF force is based on a `CustomCompoundBondForce` with the map terms contained in a `Discrete3DFunction` (implementation at https://github.com/tristanic/isolde/blob/c2a2ddc167afda8cca6d41308fde5f421fcd1e1a/isolde/src/openmm/custom_forces.py#L440). The map values are provided as a C-contiguous Numpy array, but I strongly suspect that during context creation they're still being type-checked element-by-element in Python. Starting this case (one of ISOLDE's built-in tutorials) using %prun from the ChimeraX shell (using the OpenCL platform in Windows... will have to see why exactly my CUDA platform isn't loading, but that's an aside):

```
from chimerax.core.commands import run
%prun run(session, 'isolde sim start sel')

         2476890 function calls (2471882 primitive calls) in 26.995 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1   25.510   25.510   25.510   25.510 {built-in method openmm._openmm.new_Context}
        1    0.150    0.150    0.151    0.151 forcefield.py:624(<listcomp>)
     2684    0.084    0.000    0.085    0.000 {openmm.app.internal.compiled.matchResidueToTemplate}
        1    0.074    0.074    0.163    0.163 forcefield.py:2163(createForce)
        1    0.064    0.064    0.088    0.088 forcefield.py:2059(createForce)
        1    0.060    0.060    0.767    0.767 forcefield.py:1145(createSystem)
        
```

If I turn off the MDFF and try again with an otherwise identical system:
```
         2476442 function calls (2471435 primitive calls) in 1.590 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.240    0.240    0.240    0.240 {built-in method openmm._openmm.new_Context}
    14357    0.167    0.000    0.168    0.000 forcefield.py:744(__init__)
     2684    0.078    0.000    0.078    0.000 {openmm.app.internal.compiled.matchResidueToTemplate}
        1    0.069    0.069    0.156    0.156 forcefield.py:2163(createForce)
        1    0.061    0.061    0.085    0.085 forcefield.py:2059(createForce)
        1    0.055    0.055    0.751    0.751 forcefield.py:1145(createSystem)
``` 

The other possibility is something similar to #2474, but from the discussion there that seems unlikely.

**Comment by peastman** [comment]
I wrote the following script to test it:

```python
from openmm import *

print('load')
with open('slow_context_creation.xml') as input:
    system = XmlSerializer.deserialize(input.read())
print('context')
integrator = VerletIntegrator(1.0)
platform = Platform.getPlatformByName('OpenCL')
context = Context(system, integrator, platform)
```

It spends about ten seconds loading the System, but less than a second creating the Context.  Is this different in some way from what you're doing?  Make sure you have the latest development code, since #3649 sped this up a lot.

**Comment by tristanic** [comment]
Ah! Of course - that would be it. The version of ISOLDE built into ChimeraX 1.4 is still 7.7.0.dev-130124a, which is prior to that. Will make sure it's updated for ChimeraX 1.5.
