### ISSUE TITLE
Adding PBC to prmtop before calling createSystem

### ISSUE THREAD

**Issue by ststevanovic** [openmm/openmm#3793]
Hi all,

I am trying to update the system generated from amber with no periodic properties. But I am not sure whats the best way to do it. If given just the "single molecule-containing" files (prmtop/inpcrd) I would want to add periodic boundary and solvent and to proceed with the simulations. I tried editing using Modeller, but without success. I also found that PBC is the property of the force, what I don't understand is how to make it happen when starting from prmtop, as describe in docs. 

Here is the thing:
```
prmtop.topology.setPeriodicBoxVectors(MyBoxVectors)
prmtop.topology.getPeriodicBoxVectors()
\# this returns the box correctly, but
prmtop._prmtop.getIfBox()
\# returns 0
```
And the usual err occurs when creating system from prmtop when given `nonbondedMethod`: `ValueError: Illegal nonbonded method for a non-periodic system`.

Thanks in advance!

**Comment by peastman** [comment]
You're trying to mix two different workflows that aren't compatible with each other.  Here are two ways of setting up a simulation.

1. Use Amber to do all your modelling and parametrization.  It produces a prmtop file which includes a complete description of what to simulate, including all force field parameters.  You load it with AmberPrmtopFile and call `createSystem()` to construct a System for it.
2. Use OpenMM to do the modelling and parametrization.  In that case you use `Modeller.addSolvent()` to add the solvent, then `ForceField.createSystem()` to parametrize it and build a System.

If you're using the second approach, you can still load a prmtop file as a way to get an initial Topology.  But once you start modifying the Topology and adding solvent, it no longer matches what was in the prmtop file.  It contains extra molecules for which the prmtop file doesn't contain parameters.  So now you need to parametrize it using ForceField.

**Comment by ststevanovic** [comment]
Thanks for clearing things out promptly!
