### ISSUE TITLE
Python API does not accept passing arguments with keywords

### ISSUE THREAD

**Issue by xqding** [openmm/openmm#3794]
The following Python script:

```python
integrator = openmm.LangevinMiddleIntegrator(
    temperature = 300*unit.kelvin,
    frictionCoeff = 5/unit.picosecond,
    stepSize = 2*unit.femtosecond)
```

throws `TypeError: __init__() got an unexpected keyword argument 'temperature'`.  Is this expected?

**Comment by peastman** [comment]
You need to leave off the names and just write

```python
integrator = openmm.LangevinMiddleIntegrator(300*unit.kelvin, 5/unit.picosecond, 2*unit.femtosecond)
```

This is a quirk of how SWIG generates Python wrappers for C++ classes.  C++ allows method overloading, where two methods have the same name but completely different arguments, while Python doesn't.  When possible SWIG tries to let you specify arguments either by name or by position, but that's only possible for non-overloaded methods.  And most classes have at least two overloaded constructors: the standard constructors and the copy constructor which takes a single object of the same class.  So you usually can't use named arguments when calling constructors.

**Comment by xqding** [comment]
Thanks for the explanation.
