### ISSUE TITLE
Question about creating custom XML files

### ISSUE THREAD

**Issue by TheRealSalmon** [openmm/openmm#3798]
I want to learn more about molecular dynamics so I started with parameterizing methane. However, I'm having issues when I try to implement an anharmonic CustomBondForce:

```
<ForceField>
  <AtomTypes>
    <Type name="C" class="C" element="C" mass="12.01078"/>
    <Type name="H" class="H" element="H" mass="1.007947"/>
  </AtomTypes>

  <Residues>
    <Residue name="UNL">
      <Atom name="C1" type="C"/>
      <Atom name="H1" type="H"/>
      <Atom name="H2" type="H"/>
      <Atom name="H3" type="H"/>
      <Atom name="H4" type="H"/>
      <Bond atomName1="C1" atomName2="H1"/>
      <Bond atomName1="C1" atomName2="H2"/>
      <Bond atomName1="C1" atomName2="H3"/>
      <Bond atomName1="C1" atomName2="H4"/>
    </Residue>
  </Residues>

  <CustomBondForce energy="(k1 * (r - r0)^2) + (k2 * (r - r0)^3)">
    <PerBondParameter name="k1"/>
    <PerBondParameter name="k2"/>
    <PerBondParameter name="r0"/>
    <Bond type1="C" type2="H" k1="178417.879" k2="-2691279" r0="0.1099"/>
  </CustomBondForce>

  <HarmonicAngleForce>
    <Angle type1="H" type2="C" type3="H" angle="1.911" k="292.88"/>
  </HarmonicAngleForce>
</ForceField>
```

When I use this xml file to create my openmm `ForceField`, my simulation immediately goes crazy. After calling `simulation.minimizeEnergy(maxIterations=1)`, my atom coordinates immediately fly out to like `1e+11`. It seems the `k2` parameter is the problem, when I set `k2="-269127"`, the simulation converges. Could you please help me understand what I'm doing wrong with the CustomBondForce?

Thank you,
Sam

**Comment by TheRealSalmon** [comment]
I just realized that the true minimum of this cubic function is r=infinity, my bad. I'll have to explore other ways of introducing anharmonicity.

**Comment by TheRealSalmon** [comment]
`LocalEnergyMinimizer` also sends the coordinates to infinity. Is there a minimizer that just does a direct gradient descent?

**Comment by peastman** [comment]
The minimizer just guarantees that it will find some minimum, but it doesn't guarantee anything about which one it will find.
