### ISSUE TITLE
Question on unexpected protein drift after simulation (keeping removeCMMotion=True)

### ISSUE THREAD

**Issue by leiqian-temple** [openmm/openmm#3800]
Dear users, 
Could I ask a question on unexpected protein drift after simulation (while keeping removeCMMotion=True)? Thanks!
My simple script for testing:
from openmm.app import *
from openmm import *
from openmm.unit import *
pdb = PDBFile('4w52_no_benzene.pdb')
forcefield = ForceField('amber99sb.xml', 'tip3p.xml')
modeller = Modeller(pdb.topology, pdb.positions)
modeller.addHydrogens(forcefield)
modeller.addSolvent(forcefield, model='tip3p', padding=1*nanometer)
system = forcefield.createSystem(modeller.topology, nonbondedMethod=PME)
integrator = VerletIntegrator(0.001*picoseconds)
simulation = Simulation(modeller.topology, system, integrator)
simulation.context.setPositions(modeller.positions)
simulation.minimizeEnergy(maxIterations=100)
**# before simulation, protein is at center of box (See below: bef_sim_4w52.pdb)**
positions = simulation.context.getState(getPositions=True).getPositions()
PDBFile.writeFile(simulation.topology, positions, open('bef_sim_4w52.pdb', 'w'))
**# after simulation, protein is on the edge of box (See below: aft_sim_4w52.pdb )**
simulation.reporters.append(PDBReporter('aft_sim_4w52.pdb', 1000))
simulation.reporters.append(StateDataReporter(stdout, 1000, step=True, potentialEnergy=True, temperature=True))
simulation.step(10000)
I attach input file 4w52_no_benzene.pdb as 4w52_no_benzene.txt (for uploading file type requirement) to this issue
[4w52_no_benzene.txt](https://github.com/openmm/openmm/files/9748013/4w52_no_benzene.txt)
When I compare these two output files, protein is at center of box in bef_sim_4w52.pdb; while protein is on the edge of box in aft_sim_4w52.pdb (even removeCMMotion remains True). 
Thanks in advance!

**Comment by peastman** [comment]
This is due to periodic boundary conditions.  See https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#periodic for a discussion of why it happens.  In your particular case, you load a protein that does not happen to be centered in the particular periodic box that OpenMM uses (from `0` to `box_width`).  Modeller adds water around it, producing a water box that is centered in a different place.  When you run the simulation, PDBReporter applies periodic boundary conditions to its output, so everything seems to jump to a new location.

This isn't really a problem.  The simulation is still running correctly.  There are tools you can use to make visualization easier, as discussed at the above link.

**Comment by leiqian-temple** [comment]
@peastman Thank you for your kind reply! I read the link you sent to me and it is helpful.
Is it possible that we could change the openmm system default PBC(0 to box_with) to fit user's initial protein position?
I remember Gromacs may do this adjustment automatically.

**Comment by peastman** [comment]
Can you elaborate on what you have in mind?  It isn't clear to me how that would work.  They're pretty far removed from each other, with a lot of processing in between and no point where anyone clearly specifies a particular box range.  You start by reading a file which might contain a single protein in vacuum, or in a water box, or maybe a membrane patch.  It could be centered anywhere.  Then you might or might not perform additional modelling steps, such as adding more solvent.  That gives you a Topology, from which you build a System and run a simulation.  During the simulation, molecules drift around not restricted to any particular range.  The box size might also change, if you have a barostat.  After some number of steps, the PDBReporter gets called and is expected to move everything into a single periodic box.  How would it figure out what box that should be?
