### ISSUE TITLE
cannot open PDBfile

### ISSUE THREAD

**Issue by MJfadeaway** [openmm/openmm#3811]
I am new to openmm.  

I want to compute the potential energy function values at positions. When I use the following code to achieve my goal, the error raised "FileNotFoundError: [Errno 2] No such file or directory: 'alanine-dipeptide-implicit.pdb"

How can I solve this problem? 

```
from openmm.app import *
from openmm import *
from openmm.unit import *
from sys import stdout


pdb = PDBFile('alanine-dipeptide-implicit.pdb')
#print(pdb.topology)
#pdb = PDBFile('ala_ala_ala.pdb')
forcefield = ForceField('amber14-all.xml')
system = forcefield.createSystem(pdb.topology, constraints=HBonds)
integrator = LangevinIntegrator(300*kelvin, 1/picosecond, 0.002*picoseconds)
simulation = Simulation(pdb.topology, system, integrator)
simulation.context.setPositions(pdb.positions)
state = simulation.context.getState(getEnergy=True)
```

**Comment by peastman** [comment]
The line

```python
pdb = PDBFile('alanine-dipeptide-implicit.pdb')
```

tells it to load a file called "alanine-dipeptide-implicit.pdb" found in the current directory.  If you want to load a file from a different directory, you can give a full path to the file.  Is that the actual file you want to load?  Is it in the correct location?

Perhaps this is the file you want?  https://github.com/openmm/openmm/blob/master/wrappers/python/tests/systems/alanine-dipeptide-implicit.pdb

**Comment by MJfadeaway** [comment]
Thanks.

**Comment by MJfadeaway** [comment]
> The line
> 
> ```python
> pdb = PDBFile('alanine-dipeptide-implicit.pdb')
> ```
> 
> tells it to load a file called "alanine-dipeptide-implicit.pdb" found in the current directory. If you want to load a file from a different directory, you can give a full path to the file. Is that the actual file you want to load? Is it in the correct location?
> 
> Perhaps this is the file you want? https://github.com/openmm/openmm/blob/master/wrappers/python/tests/systems/alanine-dipeptide-implicit.pdb

Thank you very much
