### ISSUE TITLE
Positional restraint - time-dependent

### ISSUE THREAD

**Issue by anicoli** [openmm/openmm#3817]
Dear OpenMM developers,

I am new to openmm, and I am currently building a protocol to simulate membrane protein using CHARMM as a force field following the different tutorials and available material. I would like to ask if it is possible to set positional restraints (as indicated here: https://openmm.github.io/openmm-cookbook/dev/notebooks/cookbook/Restraining%20Atom%20Positions.html) where the constant force reduces slowly with time. Is there any function in openmm? Thank you in advance.

**Comment by peastman** [comment]
In the cookbook example, `k` is a global parameter.  It can be changed at any time by calling `setParameter()` on the Context.  For example, if you want the force constant to initially be 100, then decrease to 0 over 100000 steps, you could do this.

```python
for i in range(100):
    simulation.context.setParameter('k', 100-i)
    simulation.step(1000)
# Now run the rest of the simulation without restraints.
simulation.context.setParameter('k', 0)
simulation.step(steps)
```

**Comment by anicoli** [comment]
Dear @peastman,
thank you very much for your fast and kind reply. I have a last question regarding the positional restraint. In this case, I would like to run i.e. 50ns of simulations in which I would apply two or more group restraints (i.e. LIG and name CA, please see in the code below), and if possible also scale down two or more k of the different groups in different times (LIG: 100 to 0 in X steps, and name CA in Y steps) but within a single run, is also this be possbile?

```
restraint = CustomExternalForce('k*periodicdistance(x, y, z, x0, y0, z0)^2')
system.addForce(restraint)
restraint.addGlobalParameter('k', 100.0*kilojoules_per_mole/nanometer)
restraint.addPerParticleParameter('x0')
restraint.addPerParticleParameter('y0')
restraint.addPerParticleParameter('z0')

for atom in pdb.topology.atoms():
    if atom.name == 'CA':
        restraint.addParticle(atom.index, pdb.positions[atom.index])

##### Other group of restraint on ligand

restraint2 = CustomExternalForce('k_a*periodicdistance(x, y, z, x0, y0, z0)^2')
system.addForce(restraint2)
restraint2.addGlobalParameter('k_a', 100.0*kilojoules_per_mole/nanometer)
restraint2.addPerParticleParameter('x0')
restraint2.addPerParticleParameter('y0')
restraint2.addPerParticleParameter('z0')

for residues in pdb.topology.residues():
    if residues.name == 'LIG':

```
then apply a for cycle as mentioned above. Thank you again.

**Comment by peastman** [comment]
Your code looks correct.  It's fine to have two CustomExternalForces that apply to different particles and use different global parameters.

**Comment by anicoli** [comment]
Thank you, I am struggling a bit with the topology and selection of LIG atoms. Could be safe to use MDAnalysis to get atom indexes?

**Comment by peastman** [comment]
Assuming the atoms are in the same order, that should be fine.  But if you just want to get atoms with a particular residue name, you can do it like this.

```python
atom_indices = [a.index for a in topology.atoms() if a.residue.name == 'LIG']
```

**Comment by anicoli** [comment]
Dear @peastman thank you for the suggestion  and the kind answer.
Even if the error is not related with this topic. I was also trying to set the MonteCarloMembraneBarostat, I was encountered the following error (please see code and error below). Thank you in advance.


```
XYmode = 0
Zmode = 0


print(type(MonteCarloMembraneBarostat.XYIsotropic))

system.addForce(MonteCarloMembraneBarostat(pressure, MonteCarloMembraneBarostat.SurfaceTension(),
                                           temperature,
                                           MonteCarloMembraneBarostat.XYIsotropic,
                                           MonteCarloMembraneBarostat.ZFree,
                                           barostatInterval))

error from jupyter:

File ~/anaconda2/envs/gpcrmd_run/lib/python3.9/site-packages/openmm/openmm.py:4112, in MonteCarloMembraneBarostat.__init__(self, *args)
   4108 if unit.is_quantity(args[2]):
   4109     args[2] = args[2].value_in_unit(unit.kelvin)
-> 4112 _openmm.MonteCarloMembraneBarostat_swiginit(self, _openmm.new_MonteCarloMembraneBarostat(*args))

TypeError: Wrong number or type of arguments for overloaded function 'new_MonteCarloMembraneBarostat'.
  Possible C/C++ prototypes are:
    OpenMM::MonteCarloMembraneBarostat::MonteCarloMembraneBarostat(double,double,double,OpenMM::MonteCarloMembraneBarostat::XYMode,OpenMM::MonteCarloMembraneBarostat::ZMode,int)
    OpenMM::MonteCarloMembraneBarostat::MonteCarloMembraneBarostat(double,double,double,OpenMM::MonteCarloMembraneBarostat::XYMode,OpenMM::MonteCarloMembraneBarostat::ZMode)
    OpenMM::MonteCarloMembraneBarostat::MonteCarloMembraneBarostat(OpenMM::MonteCarloMembraneBarostat const &)
 ```

**Comment by peastman** [comment]
Closing this since the question has been answered.
