### ISSUE TITLE
Finding openmm libraries to link against

### ISSUE THREAD

**Issue by zjp** [openmm/openmm#3820]
Hi all, 

I'm one of the developers on the UCSF ChimeraX team. We have a number of compiled extensions that we ship in ChimeraX, scattered across several modules. To facilitate our modules including headers and libraries from other modules, and let extension developers build with/link to our libraries, we took inspiration from numpy and added ``get_include()`` and ``get_lib()`` to the ``__init__.py`` files in those modules. We'd like to see that practice become the standard among the Python community.

We have an extension developer whose extension needs to find OpenMM libraries to link against and we have a workaround for them, but we wondered if you'd want to add to the get_include()/get_lib() momentum.

**Comment by peastman** [comment]
That sounds like a reasonable idea.  `get_lib()` isn't a function in numpy.  Do you have it point to the `lib` directory or to a particular library?

**Comment by zjp** [comment]
Sorry, I should have clarified better that ``get_include()`` is from numpy and ``get_lib()`` is our addition :) 

In our packages it points to the ``lib`` directory.

**Comment by zjp** [comment]
I'm willing to write the PR on this, but could I get some guidance for conda vs PyPi? 

When I install packages on PyPi, typically the include and lib directories are inside the package. On conda, however, I can see that OpenMM's headers are installed in the python environment's top-level include and lib directories. 

I'm not suggesting that that should change, I just wonder if that will still be the case on PyPi (I hear from Tristan Croll that you are considering a PyPi release), or if I need to think about how to handle the case of libraries at both paths, or if conda has some other way of finding libraries that doesn't even need to be accounted for.

**Comment by peastman** [comment]
Conda and PyPI handle this differently, and we plan to follow the standard on each one: the per-environment lib directory for conda and the per-package lib directory for PyPI.  We have some open questions about how to handle this.  See the ongoing discussion at #3796.

In terms of implementation, note that we already store a reference to the `lib` directory.  It's in the variable `openmm.version.openmm_library_path`.  There's a function in `setup.py` called `writeVersionPy()` that creates the `version.py` file containing version information.  Here's how I would suggest implementing this change:

1. Add another line to `version.py` containing the include directory.  You can retrieve it with `os.getenv('OPENMM_INCLUDE_PATH')`.
2. Add the `get_include()` and `get_lib()` functions, which just return the corresponding fields from `version`.

**Comment by zjp** [comment]
I don't think that method will work. On my machine, I see 

```
/Users/runner/miniforge3/conda-bld/openmm_1646184856012/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib
```

as the value of ``openmm.version.openmm_library_path``. That's clearly for a CI VM, but the idea is to find libraries and headers on the user's own machine. 

What about querying sys.executable to see if ``conda`` appears in the path, and setting the directories accordingly?

**Comment by peastman** [comment]
That just tells you what python you're running.  It doesn't tell you if OpenMM was installed with pip, conda, or from source.

How do you implement it in your package?

**Comment by zjp** [comment]
Because the include and lib folders are always right next to ``__init__.py``, we can do:

```python3
def get_include():
    return os.path.join(os.path.dirname(__file__) + 'include')

def get_lib():
    return os.path.join(os.path.dirname(__file__) + 'lib')
```

**Comment by isuruf** [comment]
> I don't think that method will work. On my machine, I see

> /Users/runner/miniforge3/conda-bld/openmm_1646184856012/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib

This might have been a bug that's already fixed. I get

```python
>>> import openmm.version
>>> openmm.version.openmm_library_path
'/Users/isuruf/miniforge3/envs/openmm/lib
```

**Comment by zjp** [comment]
It looks like the PyPi version correctly points at `/Users/zjp/git/rbvi/ChimeraX/ChimeraX.app/Contents/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/openmm/../OpenMM.libs/lib`. Sweet!
