### ISSUE TITLE
Circular variance term for nonbonded interactions

### ISSUE THREAD

**Issue by ZiZ1** [openmm/openmm#3821]
Dear OpenMM developers,

I am trying to implement a circular variance term with openMM. This term includes the norm of the sum of unit vectors in the direction from a target particle to all the neighbors within a cutoff, divided by the number of neighbors (see eq. 9  https://pubs.acs.org/doi/10.1021/ct3007925). Is it possible to implement such a term using  `CustomForce` classes? `CustomManyParticleForce` in `UniqueCentralParticle` mode seems to be the most appropriate, but it is unclear to me how to get the number of neighbors and avoid explicitly listing all the pairs. Thank you!

**Comment by peastman** [comment]
I don't think any of the custom force classes is capable of computing that.  It requires two sums over neighbors, one to add up the vectors and one to count the number of neighbors.  And it depends on the displacement vector between each pair of particles, not just the distance.  And then you need to compute an energy based on those sums, which I couldn't find in the paper.  They give a formula for CV, but I didn't see one for E_sol.

If you want to implement that force field, I think there are two options.  One is to write a plugin.  See the [developer guide](http://docs.openmm.org/latest/developerguide/) and the [example plugin](https://github.com/openmm/openmmexampleplugin).  That's the most powerful extension mechanism, but also the most work.

Another possibility is to use the [PyTorch plugin](https://github.com/openmm/openmm-torch), which lets you use an arbitrary PyTorch model as force.  That will probably have much worse performance than a well optimized plugin, but it also takes a lot less work to write.

**Comment by ZiZ1** [comment]
@peastman, thank you very much! 
The E_sol, is a polynomial of CV (described in this paper https://pubs.acs.org/doi/full/10.1021/ct3001552 ). I made a PyTorch implementation., but it is inefficient, and one of the problems is that as far as I know, PyTorch plugins do not have access to OpenMM's neighbor list, so it needs to be recomputed within the PyTorch plugin. Will take a look at plugins then.
