### ISSUE TITLE
Issues of simulation speed in membrane bound system

### ISSUE THREAD

**Issue by rubinanoor9** [openmm/openmm#3822]
Dear Openmm Users!

I am trying to simulate a membrane bound protein system having 0.5 million atoms. The structure has been built from the CharmmGui and parameters files were saved in openmm and gromacs format  also. I found Gromacs has become more efficient than OpenMM because, during bench-marking, Gromacs show a speed of 7ns/day whereas Openmm is at 5ns/day. It was surprisingly for me, because instead of a membrane bound system, when I tested the protein-ligand complex, the OpenMM efficiency was double and the same as I had thought for a membrane bound system. 

I am a little bit confused. Where I am doing error?

Looking forward to hearing from you,

Regards

Rubina

**Comment by peastman** [comment]
Can you post the files to reproduce what you're doing?  It's impossible to say what's happening without seeing the details.  Speed depends on many factors, including which platform you use, what hardware you run on, the precision mode, the nonbonded cutoff, the integration step size, etc.

You can find benchmarks at https://openmm.org/benchmarks.  On the STMV benchmark, which has over a million atoms, even older consumer GPUs like the RTX 2080 are significantly faster than what you quoted.

**Comment by rubinanoor9** [comment]
Thank you so much for your response. We are running this job on a GTX 1080 Ti system with CUDA version of 11.4. Kindly find the enclosed file of the openmm script and the input file that we are using. 

Thanks in advance
[openmm_issues_files.zip](https://github.com/openmm/openmm/files/9886994/openmm_issues_files.zip)

**Comment by peastman** [comment]
That still isn't enough to reproduce what you're doing.  Your script imports lots of modules like `omm_readinputs` and `omm_readparams` that you didn't include.  You also didn't provide the input files to read or the command line arguments.  Without that, I can only guess about what might be happening.  Here are some things I do notice from your files to consider changing.

You use a LangevinIntegrator with a step size of 2 fs.  We generally recommend LangevinMiddleIntegrator which uses a newer algorithm.  When combined with a small amount of hydrogen mass repartitioning (1.5 amu tends to work well), it allows a step size of 4 fs with no loss in accuracy.  This will give a large speedup.

You use a fairly large cutoff of 1.2 nm.  A shorter of around 0.9 or 1.0 nm will probably give better performance.  With PME, changing the cutoff just shifts work between the direct space and reciprocal space calculations without changing the accuracy of the result.

You use mixed precision mode.  For many purposes, single precision is sufficiently accurate and is a bit faster.  Note that the "mixed precision" mode in Gromacs is actually closer to OpenMM's single precision mode.  It still stores all positions and velocities as single precision, where OpenMM's mixed precision mode stores them as double precision.
