### ISSUE TITLE
How to obtain the charge of Drude particles in Charmm_polar_2019 ?

### ISSUE THREAD

**Issue by mdionic** [openmm/openmm#3823]
Dear all OpenMM users,
     Hi, I find the charge of Drude particles  in _charmm_polar_2019.xml_ in OpenMM is different from the result by myself. For example, the charge of Drude partilces (drude type : Drude-FETH-F11, the polarizability $\alpha = 1.45 Å^3$), the force constant $k_D = 500 kcal/mol/Å/Å$ ([J. Chem. Theory Comput. 2018, 14, 1083−1098](https://pubs.acs.org/doi/10.1021/acs.jctc.7b01086)), and the charge of Drude is 
$\sqrt{4\pi\epsilon_0 k_D \alpha\/N_A } /e$ 
$=\sqrt{4\pi\times 8.85\times10^{-12} \times 500 \times 4.184 \times 1000 \times 1.45 \times 10^{-10}/(6.02 \times 10^{23})}/(1.602\times 10^{-19}) $
$=1.47768$
which is $\sqrt{2}$ times different from the value (2.0896487603588736) in the OpenMM force field file. I guess that the force constant $k_D$ used in OpenMM is $1000 kcal/mol/Å/Å$, but why?

Thank you very much!

Best Wishes!
MA

**Comment by smlee99** [comment]
First, the unit of force constant used in openMM is kJ/mol/nm^2. And the convention of harmonicbondforce is different. OpenMM uses the potential energy term of the form E=1/2k(x-x0)^2 and CHARMM FF uses E=k'(x-x0)^2, so k=2k'. That's the reason why the charge of Drude is evaluated as $\sqrt{2}$ times different from the OpenMM xml file.

**Comment by mdionic** [comment]
@smlee99 Oh, I got it! Thank you very much!
