### ISSUE TITLE
Support Python 3.11

### ISSUE THREAD

**Issue by peastman** [openmm/openmm#3824]
Python 3.11 was just released.  We should investigate whether it's reasonable to support it in the OpenMM 8.0 release candidate.

**Comment by zhenyuwei99** [comment]
I believe there are two main improvement in python 3.11:
1. A better traceback experssion
2. A faster speed
I think these two improvement will not make big difference as openmm use swig to build the api.

**Comment by peastman** [comment]
The speed improvements would be nice for the parts of OpenMM written in python, like processing files and building systems.  But the most important reason is for compatibility.  People may want to use OpenMM together with other python packages.  If it doesn't support 3.11, they can't use it for the other packages either.

**Comment by zhenyuwei99** [comment]
That sounds reasonable. I am also curious about the help from the new traceback when debugging the code. Looking forward to seeing the support

**Comment by peastman** [comment]
This is done in 8.0.
