### ISSUE TITLE
Particle position = nan in CHARMM Drude 2109

### ISSUE THREAD

**Issue by andrewsb8** [openmm/openmm#3828]
Hi,

I was originally having this problem as in #3415 and I think I've found that it's an issue similar to #3815. 

I can successfully minimize and start a production simulation for the following system (solvated but waters aren't shown because the file is large): 

```
MODEL        1
ATOM	  1  N   GLY     1	11.370  20.100   6.000  1.00  0.00           N
ATOM	  2  H1  GLY     1	11.610  20.830   5.300  1.00  0.00           H
ATOM	  3  H2  GLY     1	12.190  19.460   5.920  1.00  0.00           H
ATOM	  4  H3  GLY     1	10.480  19.610   5.780  1.00  0.00           H
ATOM	  5  CA  GLY     1	11.290  20.770   7.360  1.00  0.00           C
ATOM	  6  HA1 GLY     1	12.240  21.260   7.530  1.00  0.00           H
ATOM	  7  HA2 GLY     1	10.480  21.480   7.250  1.00  0.00           H
ATOM	  8  C   GLY     1	11.000  19.870   8.550  1.00  0.00           C
ATOM	  9  O   GLY     1	10.840  18.700   8.270  1.00  0.00           O
ATOM     10  N   GLY     2	11.010  20.400   9.810  1.00  0.00           N
ATOM     11  HN  GLY     2	11.260  21.360   9.920  1.00  0.00           H
ATOM     12  CA  GLY     2	10.670  19.710  11.040  1.00  0.00           C
ATOM     13  HA1 GLY     2	11.570  19.210  11.350  1.00  0.00           H
ATOM     14  HA2 GLY     2	10.430  20.520  11.710  1.00  0.00           H
ATOM     15  C   GLY     2	 9.490  18.840  11.090  1.00  0.00           C
ATOM     16  O   GLY     2	 8.450  19.230  10.640  1.00  0.00           O
ATOM     17  N   GLY     3	 9.650  17.670  11.660  1.00  0.00           N
ATOM     18  HN  GLY     3	10.620  17.520  11.810  1.00  0.00           H
ATOM     19  CA  GLY     3	 8.750  16.580  11.890  1.00  0.00           C
ATOM     20  HA1 GLY     3	 8.500  16.020  11.000  1.00  0.00           H
ATOM     21  HA2 GLY     3	 9.140  16.020  12.730  1.00  0.00           H
ATOM     22  C   GLY     3	 7.380  16.940  12.400  1.00  0.00           C
ATOM     23  OT1 GLY     3	 6.390  16.770  11.770  1.00  0.00           O
ATOM     24  OT2 GLY     3	 7.360  17.440  13.660  1.00  0.00           O
ATOM     25  HT GLY     3	 6.440  17.680  13.780  1.00  0.00           H
TER
ENDMDL
```

Changing the final line atom type from `HXT` to `HT` got rid of the template error I described at the bottom of #3415. However, early in a production simulation I get this stack trace:

```
Traceback (most recent call last):
  File "/ifs/groups/urbancMRIGrp/andrews/GGG_CHARMM_Drude_2019_SWM4-NDP_water/openmm_setup.py", line 74, in <module>
    simulation.step(600000000)
  File "/ifs/groups/urbancMRIGrp/opt/miniconda/envs/openMM/lib/python3.9/site-packages/openmm/app/simulation.py", line 141, in step
    self._simulate(endStep=self.currentStep+steps)
  File "/ifs/groups/urbancMRIGrp/opt/miniconda/envs/openMM/lib/python3.9/site-packages/openmm/app/simulation.py", line 206, in _simul$
    self.integrator.step(10) # Only take 10 steps at a time, to give Python more chances to respond to a control-c.
  File "/ifs/groups/urbancMRIGrp/opt/miniconda/envs/openMM/lib/python3.9/site-packages/openmm/openmm.py", line 5009, in step
    return _openmm.VerletIntegrator_step(self, steps)
openmm.OpenMMException: Particle coordinate is nan
```

I did some testing and finally tried a simulation with charged C-terminus by deleting the hydrogen HT from the above pdb. Everything worked fine after the removal of the COOH hydrogen. I went into the CHARMM drude xml file to look at the patches and I think I found something similar to #3815. The patch options for C-terminal glycine are:

```
<AllowPatch name="GNTE"/>
<AllowPatch name="ACE"/>
<AllowPatch name="CTEG"/>
<AllowPatch name="CNEG"/>
<AllowPatch name="CT1G"/>
<AllowPatch name="CT2G"/>
<AllowPatch name="CT3"/>
```

The only option of those that puts a hydrogen on one of the oxygens is here : 

```
<Patch name="CNEG">
      <ChangeAtom charge="2.0363207668819214" name="N" type="CNEG-N"/>
      <ChangeAtom charge="-2.4183207668819215" name="DN" type="Drude-CNEG-N"/>
      <ChangeAtom charge="0.272" name="HN" type="CNEG-HN"/>
      <ChangeAtom charge="1.8202974717429852" name="CA" type="CNEG-CA"/>
      <ChangeAtom charge="-1.7002974717429853" name="DCA" type="Drude-CNEG-CA"/>
      <ChangeAtom charge="-0.017" name="HA1" type="CNEG-HA1"/>
      <ChangeAtom charge="-0.017" name="HA2" type="CNEG-HA2"/>
      <ChangeAtom charge="2.764526857311924" name="C" type="CNEG-C"/>
      <ChangeAtom charge="-1.906526857311924" name="DC" type="Drude-CNEG-C"/>
      <AddAtom charge="1.6663059805572338" name="OT1" type="CNEG-OT1"/>
      <AddAtom charge="-1.6663059805572338" name="DOT1" type="Drude-CNEG-OT1"/>
      <AddAtom charge="1.9633344060265052" name="OT2" type="CNEG-OT2"/>
      <AddAtom charge="-1.9633344060265052" name="DOT2" type="Drude-CNEG-OT2"/>
      <AddAtom charge="0.374" name="HT" type="CNEG-HT"/>
      <AddAtom charge="-0.319" name="LPT1" type="CNEG-LPT1"/>
      <AddAtom charge="-0.319" name="LPT2" type="CNEG-LPT2"/>
      <AddAtom charge="-0.285" name="LPT3" type="CNEG-LPT3"/>
      <AddAtom charge="-0.285" name="LPT4" type="CNEG-LPT4"/>
      <RemoveAtom name="O"/>
      <RemoveAtom name="DO"/>
      <RemoveAtom name="LPOA"/>
      <RemoveAtom name="LPOB"/>
      <AddBond atomName1="C" atomName2="OT1"/>
      <AddBond atomName1="C" atomName2="OT2"/>
      <RemoveBond atomName1="C" atomName2="O"/>
      <RemoveExternalBond atomName="C"/>
      <VirtualSite atomName1="OT1" atomName2="C" atomName3="OT2" p1="-0.0005235721931185042" p2="-0.029995430854691738" p3="0" siteName="LPT1" type="localCoords" wo1="1" wo2="0" wo3="0" wx1="-1.0" wx2="0.0" wx3="1.0" wy1="0" wy2="-1" wy3="1"/>
      <VirtualSite atomName1="OT1" atomName2="C" atomName3="OT2" p1="-0.0005235721931185042" p2="0.029995430854691738" p3="0" siteName="LPT2" type="localCoords" wo1="1" wo2="0" wo3="0" wx1="-1.0" wx2="0.0" wx3="1.0" wy1="0" wy2="-1" wy3="1"/>
      <VirtualSite atomName1="OT2" atomName2="C" atomName3="HT" p1="-0.012485829976186883" p2="0.0005706440663482743" p3="0.03269217666591343" siteName="LPT3" type="localCoords" wo1="1" wo2="0" wo3="0" wx1="-1.0" wx2="0.0" wx3="1.0" wy1="0" wy2="-1" wy3="1"/>
      <VirtualSite atomName1="OT2" atomName2="C" atomName3="HT" p1="-0.012485829976186883" p2="0.0005706440663482743" p3="-0.03269217666591343" siteName="LPT4" type="localCoords" wo1="1" wo2="0" wo3="0" wx1="-1.0" wx2="0.0" wx3="1.0" wy1="0" wy2="-1" wy3="1"/>
    </Patch>

```

But there is no bond added for the hydrogen

```
<RemoveAtom name="O"/>
<RemoveAtom name="DO"/>
<RemoveAtom name="LPOA"/>
<RemoveAtom name="LPOB"/>
<AddBond atomName1="C" atomName2="OT1"/>
<AddBond atomName1="C" atomName2="OT2"/>
<RemoveBond atomName1="C" atomName2="O"/>
<RemoveExternalBond atomName="C"/>
```

So I guess the particle acts like an unconstrainted charge in the simulation? Either way, I saw that in #3815 they manually added the bond. So I can also do that. I just wanted to report this as also an issue within the drude force field and also, more importantly, ask if manually changing this entry would affect updates within conda when new versions release.

**Comment by peastman** [comment]
Thanks for the report!  I just submitted a pull request to ParmEd earlier today with a fix for the missing bonds: https://github.com/ParmEd/ParmEd/pull/1275.  There's one other issue that also needs to be fixed, and then we can produce a new version of the converted force field.

**Comment by andrewsb8** [comment]
Sounds great. I did try to add the bond to the xml manually and got an error like this:

```
<RemoveAtom name="O"/>
<RemoveAtom name="DO"/>
<RemoveAtom name="LPOA"/>
<RemoveAtom name="LPOB"/>
<AddBond atomName1="C" atomName2="OT1"/>
<AddBond atomName1="C" atomName2="OT2"/>
<AddBond atomName1="OT2" atomName2="HT"/>  <--------
<RemoveBond atomName1="C" atomName2="O"/>
<RemoveExternalBond atomName="C"/>
```

But this resulted in a template error:

```
Traceback (most recent call last):
  File "/data/B/bandrews/OpenMM/GGG_CHARMM_Drude_2019_SWM4-NDP_water/openmm_setup.py", line 34, in <module>
    modeller.addExtraParticles(forcefield)
  File "/home/bandrews/miniconda3/envs/openMM/lib/python3.9/site-packages/openmm/app/modeller.py", line 1048, in addExtraParticles
    templates = forcefield._matchAllResiduesToTemplates(ForceField._SystemData(self.topology), self.topology, {}, False, True, False)
  File "/home/bandrews/miniconda3/envs/openMM/lib/python3.9/site-packages/openmm/app/forcefield.py", line 1420, in _matchAllResiduesToTemplates
    raise ValueError('No template found for residue %d (%s).  %s' % (res.index+1, res.name, _findMatchErrors(self, res)))
ValueError: No template found for residue 3 (GLY).  The set of atoms is similar to SER, but it is missing 12 atoms.

```

I also tried `<AddBond atomName1="OT1" atomName2="HT"/>` with the same stack trace. So I'm probably missing additional lines within that patch designation. Is there something I'm missing?

Thanks,

Brian

**Comment by andrewsb8** [comment]
I'm commenting back here because my issue is not related with the Parmed issue in #3851 and I changed the title to reflect this. 

I looked at the FAQ. I am not applying external forces or constraints. Here is my current worflow:

- Solvate the system using CHARMM36m parameters
- I even energy minimized it to help avoid large energies when adding the drude particles in the subsequent step

```
modeller = Modeller(pdb.topology, pdb.positions)
forcefield1 = ForceField('charmm36.xml', 'charmm36/water.xml')
modeller.addSolvent(forcefield1, boxSize=Vec3(5, 5, 5)*nanometers, neutralize=True, negativeIon='Cl-', positiveIon='Na+')

system = forcefield1.createSystem(modeller.topology, nonbondedMethod=PME,
        nonbondedCutoff=1*nanometer, constraints=HBonds)

system.addForce(MonteCarloBarostat(1*bar, 300*kelvin)) 

system.addForce(AndersenThermostat(300*kelvin, 1/picosecond)) 
integrator = VerletIntegrator(0.0005*picoseconds)

#run simulation on single GPU
platform = Platform.getPlatformByName('CUDA')
#properties = {'DeviceIndex': '0', 'Precision': 'double'}

simulation = Simulation(modeller.topology, system, integrator, platform) #, properties)
simulation.context.setPositions(modeller.positions)

#Energy minimization
simulation.minimizeEnergy(tolerance=0.000001*kilojoule/mole, maxIterations=2000000)

PDBFile.writeFile(modeller.topology, modeller.positions, open('common/solvated_minimized.pdb', 'w'))
```

Then, to run the simulation, I
-  load solvated and minimized pdb from above, which includes the box vectors
-  add extra particles
-  minimize the energy again
-  take the time step down to 0.1 fs from 0.5 fs
-  increase the number of allowed minimization steps and decrease tolerance

```
modeller = Modeller(pdb.topology, pdb.positions)
forcefield = ForceField('forcefield/charmm_polar_2019.xml')
modeller.addExtraParticles(forcefield)

system = forcefield.createSystem(modeller.topology, nonbondedMethod=PME,
        nonbondedCutoff=1*nanometer, constraints=HBonds)

#Add barostat for NPT instead of NVT simulation
system.addForce(MonteCarloBarostat(1*bar, 300*kelvin)) 

system.addForce(AndersenThermostat(300*kelvin, 1/picosecond)) 
integrator = VerletIntegrator(0.0001*picoseconds)

#run simulation on single GPU
platform = Platform.getPlatformByName('CUDA')
#properties = {'DeviceIndex': '0', 'Precision': 'double'}

simulation = Simulation(modeller.topology, system, integrator, platform) #, properties)
simulation.context.setPositions(modeller.positions)

#Energy minimization
simulation.minimizeEnergy(tolerance=0.0000001*kilojoule/mole, maxIterations=200000000)

#output minimized state
positions = simulation.context.getState(getPositions=True).getPositions()
PDBFile.writeFile(simulation.topology, positions, open('minimization/minimized.pdb', 'w'))

#output minimized state to load for production simulation
simulation.saveState('md-equilibration/pep_md.xml')

simulation.reporters = []
simulation.reporters.append(DCDReporter('md-equilibration/traj.dcd', 4000))
simulation.reporters.append(StateDataReporter(stdout, 4000, step=True,
                                              temperature=True, elapsedTime=True)) 
simulation.reporters.append(StateDataReporter("md-equilibration/log.csv", 4000, time=True,
                                              potentialEnergy=True, totalEnergy=True, temperature=True, elapsedTime=True))

simulation.step(600000000)

#output minimized state to load for production simulation
simulation.saveState('md-equilibration/state1.xml')
```

I still reliably get this stack trace after a variable number of time steps executed:

```
Traceback (most recent call last):
  File "/ifs/groups/urbancMRIGrp/andrews/GGG_CHARMM_Drude_2019_SWM4-NDP_water/openmm_setup.py", line 74, in <module>
    simulation.step(600000000)
  File "/ifs/groups/urbancMRIGrp/opt/miniconda/envs/openMM/lib/python3.9/site-packages/openmm/app/simulation.py", line 141, in step
    self._simulate(endStep=self.currentStep+steps)
  File "/ifs/groups/urbancMRIGrp/opt/miniconda/envs/openMM/lib/python3.9/site-packages/openmm/app/simulation.py", line 206, in _simulate
    self.integrator.step(10) # Only take 10 steps at a time, to give Python more chances to respond to a control-c.
  File "/ifs/groups/urbancMRIGrp/opt/miniconda/envs/openMM/lib/python3.9/site-packages/openmm/openmm.py", line 5009, in step
    return _openmm.VerletIntegrator_step(self, steps)
openmm.OpenMMException: Particle coordinate is nan
```

I also have tried using a different iterator, the `DrudeLangevinIntegrator` (with no thermostat), and got the same stack trace (but with `DrudeLangevinIntegrator_step` instead of `VerletIntegrator_step`). Here are my inputs for the changed integrator:

`integrator = DrudeLangevinIntegrator(300*kelvin, 1/picosecond, 1*kelvin, 20/picosecond, 0.0005*picoseconds)`

The parameters for the temperature and friction coefficients mimic the work of this paper, which used OpenMM and Drude 2013 to carry out simulations (https://aip.scitation.org/doi/10.1063/5.0022135). I'm really not sure what I'm doing wrong at this point but any help is appreciated. Sorry for the novel of a comment.

**Comment by peastman** [comment]
I'm running a slightly modified version of your script with the force field from #3851.  It's up to 3 million steps with no sign of problem.  Here's the integrator I'm using:

```python
integrator = DrudeLangevinIntegrator(300*kelvin, 1/picosecond, 1*kelvin, 10/picosecond, 0.001*picoseconds)
```

I also removed the second energy minimization, which doesn't seem to be necessary.  It runs fine without it.

How many steps does it take for the error to happen when you run it?

**Comment by andrewsb8** [comment]
Hope you had a nice holiday and are enjoying the long weekend!

The prior two attempts, using the Drude integrator, terminated with the same stack trace at time steps 176000 and 28000. My current attempt failed at step 40000 with your parameters in the drude integrator.

I went to load the dcd file of the most recent run into VMD so I could try to see what particle was acting weird. ...and no visualization loads. It loads the number of frames and particles, but I can't select a group of atoms ('protein' comes up as empty, for example). I'm attaching the pdb I use as input for the second script and the output dcd file which does not load any particles in VMD. I added .txt to the end so they would play nicely with github.

[solvated_minimized.pdb.txt](https://github.com/openmm/openmm/files/10094045/solvated_minimized.pdb.txt)
[traj.dcd.txt](https://github.com/openmm/openmm/files/10094050/traj.dcd.txt)

I can load the dcd file into a python script with the mdtraj package and see particle coordinates and information about the system. Looking at the positions in each of the nine frames, nothing looks suspicious, and I'm assuming OpenMM is not writing the coordinates of the frame with NaN to the dcd trajectory file. So I can't see if it's one particle or the entire system blowing up. The box vectors are also fine. 

I'm really at a loss here. Thanks again for looking into this and I apologize this has taken up so much of your time.

Brian

**Comment by smlee99** [comment]
Hi? I also had a similar issue while running a single amino acid residue (but not GLY) with negatively charged C residue. From here, this is a bit my guess about this issue. (I did not try it yet) For `charmm_polar_2019.xml` file, `<AllowPatch name="CTEG"/>` is used for C-termius residue. If you check the original .str file for such force field in [here](http://mackerell.umaryland.edu/charmm_drude_ff.shtml) (file: drude_toppar_2019.str), below is the definition of `CTEG` residue.

```
PRES CTEG         -1.000 ! C-terminus for polypeptide terminating with a glycine
!
!     OT2(-)
!    /
! --C
!    \\
!     OT1
!
DELETE ATOM O
DELETE ATOM DO
DELETE ATOM LPOA
DELETE ATOM LPOB
```
I don't know the specific detail about force field parameterization but at least it shows that this residue is suitable for polypeptide terminating with a glycine. Well for your single amino acid case, there is another C-terminus residue used for single amino acid.
```
PRES CTES         -1.000 ! C-terminus for single amino acid
! Note: with ACE use CTER
!
!     OT2(-)
!    /
! --C
!    \\
!     OT1
!
DELETE ATOM O
DELETE ATOM DO
DELETE ATOM LPOA
DELETE ATOM LPOB
```
In current `charmm_polar_2019.xml` file, `forcefield.createsystem` does not automatically check whether C-terminus patch is for single amino acid or polypeptide, since both `CTES` and `CTEG` have same topology information and only one of them is defined in xml file. I'm not sure if it would work or not but you may add parameters for `CTES` patch, change the `<AllowPatch>` from `CTEG` to `CTES`, and run the simulation for trobleshooting.

**Comment by andrewsb8** [comment]
I may have figured this out.

I added this line of code to my script:

```
integrator = DrudeLangevinIntegrator(300*kelvin, 1/picosecond, 1*kelvin, 10/picosecond, 0.001*picoseconds)
print(integrator.getMaxDrudeDistance())
integrator.setMaxDrudeDistance(0.02) #nm
print(integrator.getMaxDrudeDistance())
```

The output I get from this is 
```
0.0 nm
0.02 nm
```

This means the default value for the MaxDrudeDistance is 0. This is stated here: http://docs.openmm.org/7.1.0/api-python/generated/simtk.openmm.openmm.DrudeLangevinIntegrator.html. But a previous issue #2513 indicated that 0.02 nm should be the default value.

I wasn't previously aware of this parameter until I saw its description in the literature: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8741736/. That made me look at the documentation for that type of parameter and lead me to the previous github issue. It would make sense that my system would blow up if the Drude particles are not sufficiently constrained.

I will test this and report back.

**Comment by peastman** [comment]
Of course, I should have thought of that.  #3508 changed the default to 0.02, but that change was made after 7.7 was released.

**Comment by andrewsb8** [comment]
I can close this. I am up to over 100 million time steps on a simulation without this issue occurring. Thanks again.

**Comment by peastman** [comment]
Thanks!  I think that means we can merge #3851 then.
