### ISSUE TITLE
system.getForce() returns a force object not identical to the one added

### ISSUE THREAD

**Issue by z-gong** [openmm/openmm#3830]
E.g. in the following code, `system.getForce()` returns a force object that is not identical to the one added. If I want to iterate over the forces in a system, how can I know that `bforce` and `force` are actually the 'same' force object?
```
In [5]: system = mm.System()

In [6]: bforce = mm.HarmonicBondForce()

In [7]: system.addForce(bforce)
Out[7]: 0

In [8]: force = system.getForce(0)

In [9]: force is bforce
Out[9]: False
```

**Comment by peastman** [comment]
That has to do with how SWIG generates wrappers.  In this case, you have two different Python objects pointing to the same C++ object.  I believe the way to check for that is with `force.this == bforce.this`.

**Comment by z-gong** [comment]
Thanks! `force.this == bforce.this` works.
