### ISSUE TITLE
Implementing GROMOS type forcefield into OpenMM

### ISSUE THREAD

**Issue by smlee99** [openmm/openmm#3835]
Hi OpenMM Devs. 

These days I'm trying to implement the 2016H66 forcefield, which is one of the GROMOS-compatible force field for small organic molecules. (link: https://pubs.acs.org/doi/full/10.1021/acs.jctc.6b00187) (Most parameters are from the GROMOS 53A6.) The original file was written in`.itp` format, as you may check on [here](https://github.com/mssm-labmmol/pypolybuilder/blob/main/pypolybuilder/gromos2016h66.ff/ffnonbonded.itp). They excluded 1-3 nonbonded interaction and although LJ interaction parameters in this forcefield are a little bit complicated, they separately defined the normal pairwise LJ interaction parameters (1-n pair for n>4, [here](https://github.com/mssm-labmmol/pypolybuilder/blob/main/pypolybuilder/gromos2016h66.ff/ffnonbonded.itp#L715)) and the third-neighbor pairwise LJ interaction parameters (1-n pair for n=4, [here](https://github.com/mssm-labmmol/pypolybuilder/blob/main/pypolybuilder/gromos2016h66.ff/ffnonbonded.itp#L5140)) including self-type interactions. 

 It seems like OpenMM and parmed `load_file` cannot handle this force field with this format so I need to convert this `.itp` file into `.xml` file. Here comes the problem. First, as far as I know, the way to handle such pairwise LJ interaction is to use `NBFIX` in xml file. Would the computation be slow if I define all the pairwise LJ interaction in xml file? And is there any way to separately handle the 1-4 nonbonded interaction? This is not just a scaling problem and I guess it would work if I manually check all the 1-4 interaction pairs and separately define the nonbonded parameters for them but wondering if there is any shortcut for this.

**Comment by smlee99** [comment]
And I didn't try it yet but OpenMM supports reading `.gro` and `.top` files. Can OpenMM handle such force field properly? I'm not really sure and that's the reason why I'm trying to convert this force field into `.xml` format.

**Comment by peastman** [comment]
> Would the computation be slow if I define all the pairwise LJ interaction in xml file?

As long as the number of atom types is reasonable, that's not a problem.  It builds lookup tables for the LJ coefficients for each pair of atom types.  Once you're doing that, it doesn't matter how the coefficients were calculated, from a combining rule or a separately specified NBFIX term.  All that matters is the size of the lookup tables, which is determined by the number of atom types.

> And is there any way to separately handle the 1-4 nonbonded interaction?

I assume you're using NonbondedForce for the Coulomb interaction and CustomNonbondedForce (created from a `<LennardJonesForce>` tag) for the LJ interactions?  In that case, the NonbondedForce can calculate both parts for the 1-4 interactions.  It already has exceptions added for them, but of course they specify `epsilon=0`.  So you need to modify them to set the correct sigma and epsilon values for each pair.  That will require Python code.

**Comment by smlee99** [comment]
Thanks for your comment. I got your point. Just for one more question. While looking for CHARMM FF xml file, I've found the following line: `<Atom class="-" epsilon="-" epsilon14="-" sigma="-" sigma14="-"/>`

Are the parameters `epsilon14` and `sigma14` in here for the 1-4 LJ interactions? If it is so, will this work?
`<NBFixPair class1="-" class2="-" epsilon="-" epsilon14="-" sigma="-" sigma14="-"/>`

**Comment by smlee99** [comment]
Got it! Let me close this issue.
