### ISSUE TITLE
computing potential energy is too slow

### ISSUE THREAD

**Issue by MJfadeaway** [openmm/openmm#3836]
I want to compute the potential energy at some given positions. So I try to write the following code. However, it is very slow when I use it to compute the potential function for a given set of positions. It takes a few minutes even for 100 data points. Did I miss anything？

`
import numpy as np
from openmm import *
from openmm.app import *
from openmm import unit
import os
def compute_potential_ad(x):

    n_sample, n_dim = x.shape
    assert n_dim == 66
    initial_pdb = os.path.join("data", "alanine-dipeptide.pdb")
    pdb = PDBFile(initial_pdb)
    forcefield = ForceField('amber14-all.xml')
    system = forcefield.createSystem(pdb.topology, constraints=HBonds)
    integrator = LangevinIntegrator(300*unit.kelvin, 1/unit.picosecond, 0.002*unit.picoseconds)
    simulation = Simulation(pdb.topology, system, integrator)
    potential_energy = []
    for k in range(n_sample):
        positions = []
        for i in range(22):
            # this is just for the need of structure in openmm
            x_pos = Vec3(x[k, 3*i], x[k, 3*i+1], x[k, 3*i+2])
            positions.append(x_pos)
        simulation.context.setPositions(positions)
        simulation.minimizeEnergy(maxIterations=100)
        f_energy = simulation.context.getState(getEnergy=True).getPotentialEnergy()/unit.kilojoule_per_mole
        potential_energy.append(f_energy)

    pfs = np.reshape(np.array(potential_energy),(-1,1))
    return pfs
`

**Comment by peastman** [comment]
Here are a few things I notice from your code.

You aren't just loading conformations and evaluating their potential energies.  You first run an energy minimization for each one.  That's an expensive operation.  100 energy minimizations can take a while.

It looks like you're working with a tiny system that has only 22 atoms.  I can't tell what platform you're using, and of course I don't know what hardware you're running on, but for such tiny systems the Reference or CPU platform will usually be faster than using a GPU.

Make sure the conformations you're giving it as input are sane.  If you give it wildly unphysical conformations with huge energies, that can make the optimizer really struggle and take a long time.

Here's a slightly modified version of your code I wrote to test it.  Since you didn't provide your input conformations, I just duplicated the input conformation from the PDB 100 times.

```python
import numpy as np
from openmm import *
from openmm.app import *
from openmm import unit

initial_pdb = '/Users/peastman/workspace/openmm/wrappers/python/tests/systems/alanine-dipeptide-implicit.pdb'

def compute_potential_ad(x):
    n_sample, n_dim = x.shape
    assert n_dim == 66
    pdb = PDBFile(initial_pdb)
    forcefield = ForceField('amber14-all.xml')
    system = forcefield.createSystem(pdb.topology, constraints=HBonds)
    integrator = LangevinIntegrator(300*unit.kelvin, 1/unit.picosecond, 0.002*unit.picoseconds)
    simulation = Simulation(pdb.topology, system, integrator)
    potential_energy = []
    for k in range(n_sample):
        positions = []
        for i in range(22):
            # this is just for the need of structure in openmm
            x_pos = Vec3(x[k, 3*i], x[k, 3*i+1], x[k, 3*i+2])
            positions.append(x_pos)
        simulation.context.setPositions(positions)
        simulation.minimizeEnergy(maxIterations=100)
        f_energy = simulation.context.getState(getEnergy=True).getPotentialEnergy()/unit.kilojoule_per_mole
        potential_energy.append(f_energy)

    pfs = np.reshape(np.array(potential_energy),(-1,1))
    return pfs

pdb = PDBFile(initial_pdb)
x = pdb.getPositions(asNumpy=True)
x = np.stack(100*[x.flatten()])
pfs = compute_potential_ad(x)
print(pfs)
```

Running on a laptop (a Mac M1 Pro), it takes about 24 seconds.  It picks OpenCL as the default platform.  If I tell it to use Reference instead, it goes down to only half a second.

**Comment by MJfadeaway** [comment]
> "You aren't just loading conformations and evaluating their potential energies. You first run an energy minimization for each one."

If I only want to compute the potential energy, can I delete the line `simulation.minimizeEnergy(maxIterations=100)` ?

I test it on a Mac M1 Pro laptop and it is fast after removing the energy minimization step. In fact, for 10000 data points, it takes about 27 seconds after removing the energy minimization step, but it will take a long time if keeping the energy minimization step. I am not sure this is correct for my purpose of computing the potential energy. Is that right?

**Comment by peastman** [comment]
`minimizeEnergy()` searches for a new conformation that is a local energy minimum.  If you want to compute the potential energy of the particular conformation you specified, you should not run an energy minimization first.  If you do, you will compute the energy of a different conformation.

**Comment by MJfadeaway** [comment]
Thanks @peastman .

This line `simulation.minimizeEnergy()` is usually appear in the MD simulation, e.g. a first example in OpenMM documentation. 

> This line tells OpenMM to perform a local energy minimization. It is usually a good idea to do this at the start of a simulation, since the coordinates in the PDB file might produce very large forces.

The gradient of the potential energy is the force. In the MD simulation, the energy minimization step is used to avoid producing very large forces. There is a constant difference between the original potential energy and the potential after the energy minimization step. So it does not affect the force and hence the MD simulation. 

But if one wants to compute the potential energy exactly, the energy minimization step should be removed.

**Comment by peastman** [comment]
> So it does not affect the force and hence the MD simulation.

No!  It makes all the forces zero, or at least very small.  That's what a local minimum is, after all--a point where the forces are zero.

> But if one wants to compute the potential energy exactly, the energy minimization step should be removed.

If you want to compute it *at all*, you should remove it.  If you run an energy minimization, you will compute the energy of a different conformation, not the one you gave it.

**Comment by MJfadeaway** [comment]
A little confused. 

> If you run an energy minimization, you will compute the energy of a different conformation, not the one you gave it.

Why should the potential energy be a local minimum at the beginning of MD simulations? If there is an energy minimization step in the MD simulation, then the initial conformation is not the same as the pdb file gives

**Comment by peastman** [comment]
Correct.  Depending on where the PDB file came from, the initial conformation may involve very large forces that would cause the simulation to immediately blow up.  That's why it's often useful to run an energy minimization before starting.

**Comment by MJfadeaway** [comment]
The physical process can often be formulated as the following stochastic partial differential equation 
$dx = -\nabla V(x) dt + dW_t$.  The starting point say $x_0$ comes from the PDB file. To avoid very large forces, run an energy minimization before starting. But the initial point is not $x_0$ anymore after the energy minimization step. So what is the real initial point $x_0$ in the MD simulation?
