### ISSUE TITLE
Jumping protein

### ISSUE THREAD

**Issue by jsruizc** [openmm/openmm#3841]
[https://drive.google.com/file/d/1lX3K406KrUcl--BUASQ1JSNxHRKvMPz8/view?usp=sharing](url)

Excuse me, I am new in using molecular dynamics softwares, and I was trying to figure out how it works on my own and this happened...I am not sure what is happening in the video, so I wanted to askyou if any of you can help me with it

I don't know if this is the correct place to ask this

Thank you

**Comment by peastman** [comment]
The above link doesn't work for me.  Can you describe what the issue is?

**Comment by jsruizc** [comment]
The protein  behaves normally some time and suddenly it  dissapears and apprears in different places around the waterbox

**Comment by peastman** [comment]
Is it just periodic boundary conditions?  Take a look at https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#periodic.  It may just be getting wrapped to different periodic locations.
