### ISSUE TITLE
Creating independent replica simulations

### ISSUE THREAD

**Issue by kong1-731** [openmm/openmm#3843]
Right now, I have a MARTINI system that I equilibrate in GROMACs. I then move the system to OpenMM with the  martini_openmm @jlmaccal package and energy minimize and quickly re-equilibrate again before continuing with my production run. (It has appeared that doing the majority of the equilibration in GROMACs makes this second equilibration in OpenMM a lot smoother.)

I want to redo my simulations with independent replicas. I am not sure if that means that I should redo the whole equilibration process starting in GROMACs and porting to OpenMM etc. or if I can use the same frame from GROMACs and after energy minimization in OpenMM, simply rerun Context.setVelocitiesToTemperature(self, temperature). I did not originally specify a randomSeed. Does this mean that if I rerun Context.setVelocitiesToTemperature(self, temperature) the seed will automatically be different or will it be the same?

Alternatively, is it possible to use the last frame of my equilibration in OpenMM and just continue the equilibration for another 5 ns or so, assuming that there is some fluctuation in particle position so that I have new atomic starting positions as well as slightly different velocities? I am just not sure what the standard is for creating an independent replica simulation. I have seen mentioned elsewhere that one should slightly perturb all the particle positions, but since I have a membrane-water simulation, I wasn't sure how to do this easily without making my system blow up.

Thank you for any advice!

**Comment by peastman** [comment]
If you omit the `randomSeed` argument when you call `setVelocitiesToTemperature()`, it will pick a different seed every time.  Likewise if you use a stochastic integrator such as LangevinMiddleIntegrator and you don't call `setRandomNumberSeed()` on it, you'll get a different seed every time.

What exactly do you mean when you say you want the simulations to be "independent"?  They'll each start with different velocities and apply different random forces, so in that sense they are independent.  But they all start from the same conformation, so in that sense they are not independent.  With time they will gradually drift apart.  The longer you equilibrate each one, the further apart they'll be.  But many proteins have motions that happen on time scales of milliseconds or longer, so 5 ns of equilibration will still leave them strongly correlated with each other.

It comes down to what your application is, what are the slowest time scales that you care about in your system, and what you hope to learn from the replicas.

**Comment by kong1-731** [comment]
Thank you! I am also calling LangevinMiddleIntegrator without setting the seed. I am interested in the deformation of the membrane and embedded protein on the order of hundreds of nanoseconds in response to a stimulus, so I am concerned that 5 ns of equilibration will mean that the conformations will be too correlated with each other. Would it be better to redo the entire equilibration process from scratch? Or to continue equilibrating for milliseconds to obtain 3-4 more starting configurations?

**Comment by peastman** [comment]
There's no single answer to that: it depends what you're trying to learn, and why you want multiple replicas.

For example, maybe you want to map out a free energy surface?  If so, all your simulations will start out in a similar part of the landscape.  That will make them less efficient at exploring the full landscape.  It doesn't mean you should throw them out, but it does mean you will get less efficient exploration than if they started in more distant places.  (Of course, if your goal is to explore the landscape, you shouldn't just run simulations and see what they do.  An enhanced sampling method like simulated tempering, replica exchange, metadynamics, etc. will be a lot more efficient.)

Or maybe you want to see a conformational transition, for example, between an active and inactive state?  Having all your replicas start in the active state might be exactly what you want, or it might be inefficient because it makes it harder to observe transitions in the other direction.

You said you want to observe changes in response to a stimulus.  Do you assume the system is in a particular state when the stimulus occurs?  Or do you want to sample what happens if it's in a variety of states when the stimulus occurs?

**Comment by kong1-731** [comment]
Thank you. I don't want to map out the free energy surface; I just want to repeat my simulation to obtain an average mechanical response to a stimulus. Under my initial conditions, the membrane is going to already be in the stable conformation, and I just want to repeat my simulations so that my results are not just a quirk of one simulation. Right now, I just want my replicas to start in this original stable state so I can see what the deformation would be to the stable state. I will try starting in an unstable state in another set of simulations. If I am trying to start from the same state, how long should I equilibrate in between each replicate to make sure that I am not just getting the same result as before because my replicates are not independent enough? Would it be better to restart the whole equilibration process in this case?

**Comment by peastman** [comment]
> how long should I equilibrate in between each replicate to make sure that I am not just getting the same result as before because my replicates are not independent enough?

I don't think there's any single answer to that question.  It depends on the time scales present in your system, and the time scales of the behaviors you want to observe, and how much compute time you can afford to spend on equilibration.

**Comment by kong1-731** [comment]
Thank you for your explanation. I see how this is a nuanced question. However, I haven't been able to tell whether it is commonplace in literature to repeat every single equilibration step from the initial assembly of the system or just to generate replica simulations at some point after the initial equilibration steps to configure the system. Is there any general rule of thumb whatsoever for generating replica simulations?

**Comment by peastman** [comment]
I don't know if there's a universal rule for this.  If you're able to equilibrate each one separately that's probably preferable, as long as it's not too expensive.  Equilibration should only take up a very small fraction of your total computation time.

**Comment by kong1-731** [comment]
Thank you! I really appreciate your advice.
