### ISSUE TITLE
Simulated Tempering - attempt move to only nearest neighbors

### ISSUE THREAD

**Issue by zjarin** [openmm/openmm#3846]
It appears that the current implementation of simulated tempering attempts to move to the lowest temperature every exchange attempt. Specifically, the loop over "j" in the _attemptTemperatureChange begins with 0 and iterates up to the number of temperature windows and accepts the first possible exchange. 

Can there be an option for moving to only the nearest neighboring temperatures with equal probability? At the highest (or lowest) temperature, there's a 50% chance to remain in the same window and 50% chance to move to adjacent temperature. The current temperature moves does not currently reflect the method as described by the Marinari and Parisi paper cited in Openmm documentation.

**Comment by peastman** [comment]
That is correct.  A few paragraphs further down it says,

https://github.com/openmm/openmm/blob/3a2124649d154e6fe94134bdee2c5ca1ef97997a/wrappers/python/openmm/app/simulatedtempering.py#L73-L74

This method is much more efficient than the one described in the original paper.

**Comment by zjarin** [comment]
Thank you for the clarification.
