### ISSUE TITLE
Accessing CustomHBondForce neighbor information?

### ISSUE THREAD

**Issue by k2o0r** [openmm/openmm#3849]
Hello, I have quite a niche question about the CustomHBondForce that I couldn't find much helpful material for elsewhere.

I am working on systems where CustomHBondForces act between sets of two bonded particles (we can imagine AB dimers), each dimer is both a donor and an acceptor for the purposes of the force, depending on whether the interaction is depends on distance Ai-Bj and angle Bi-Ai-Bj or the distance Bi-Aj and angle Ai-Bi-Aj.

What I want to do is check which groups are already acting as donors/acceptors at fixed intervals, create a mask for donors and acceptors and then use CustomHBondForce.updateParametersInContext() to increase the strength of donor bonding (which in this case means updating just a parameter) for those groups already acting as acceptors, and vice versa.

The basic structure of the code I have in mind is below.

```
for i in range(iterations):
         d_mask = check_donors(context)
         a_mask = check_acceptors(context)
         hbond_force.setDonorParameters(a_mask)
         hbond_force.setAcceptorParameters(d_mask)
         hbond_force.updateParametersInContext(context)
         sim.run(n)
    
```

The question really comes down to defining the `check_donors/check_acceptors` functions. I know I can use `sim.context.getState(getPositions=True).getPositions()` and use that to calculate all the relevant distances and angles but that comes with significant overhead, especially if you calculate the distances between every pair of AB dimers. Is there a way I can access the neighbor list of the CustomHBondForce at regular intervals? This would be convenient, as obviously the distance and angle information that is relevant here must be being calculated by OpenMM every timestep as forces are calculated, so is it possible to access a list of every donor/acceptor pair evaluating to non-zero in a CustomHBondForce?

If not, are there other ways to go about this? One idea is to include a per-donor/per-acceptor parameter that is reports on when a dimer is acting as an acceptor/donor and could then be accessed. I guess the problem here is don't think it's possible to have a per-donor/per-acceptor parameter that depends on the evaluated value of the energy function rather than the other way round.. 

Anyway, I hope I have been clear enough about what I'm trying to do,, but please let me know if any other information would be useful- any advice from experts or devs would be greatly appreciated!

**Comment by peastman** [comment]
I don't have any good solution for this.  There's no way to access that information directly.  It doesn't get stored.  I've tried to think of some sort of hack, but haven't come up with anything.  I think you'll just need to query the positions and identify the interactions yourself.

**Comment by k2o0r** [comment]
OK I see, well thanks for the info.

In that case I will see how efficiently I can query the positions to see if this is feasible, unfortunately I think that's always going to be quite slow but maybe it won't be too bad if it's implemented well- I will try to persevere with this as I'm very interested in this kind of simulation but appreciate it might be difficult to make work. Probably the most important thing here to minimize the number of calculations per iteration, I'll have a think about it other the next few days.

Thanks again!

**Comment by peastman** [comment]
You could, of course, write a plugin to do the analysis on the GPU.  That's a lot more work, but it has the possibility of being fast.

**Comment by k2o0r** [comment]
Right, I'll definitely look into it, thanks.

Maybe I'll try implementing it using `Context.getState(getPositions=True).getPositions()` to test the idea and see how slow it is and then after that look into writing a plugin.

Would it be possible to write a new Force that is like CustomHBondForce but could be queried to get the energy of the strongest interaction each D/A is involved in at the last timestep? Or is the better approach to just write a plugin that calculates the distances and angles using the GPU?

**Comment by peastman** [comment]
Those two options do different things.  If you want to find the strongest interaction, that requires actually calculating every interaction, so you might as well build it into the force.  If there's some simpler calculation you can do that gives the information you need, then keeping it separate may be simpler.

**Comment by k2o0r** [comment]
Hi, just returning to this idea- I am thinking of writing a python function to do this and using numba to compile it into device code. As far as I understand, if the checking function is basically just numpy and and iteration it can be compiled into rather fast device code, including in CUDA. As far as I can see this should be the best balance between performance and ease of implementation
