### ISSUE TITLE
Cannot use openMM to run em on a solavted system from Gromacs topology with HBond constrain

### ISSUE THREAD

**Issue by xiki-tempula** [openmm/openmm#3856]
I have a system where a single methane is solavted in a box of TIP3p water that is generated for Gromacs and the simulation is running fine on the system. I tried to load the Gromacs topology into the openMM and run a em with it. However, I struggle to run the EM with HBond constrain, which works fine in Gromacs.
The input is the Gromacs coordinate `"methane.gro"` and Gromacs topology `"methane.top"` [Archive.zip](https://github.com/openmm/openmm/files/10093917/Archive.zip). The openMM script that I'm using is
```python
from openmm import LangevinIntegrator, Platform
from openmm.app import (
    HBonds,
    PME,
    GromacsGroFile,
    GromacsTopFile,
    Simulation,
    DCDReporter,
    StateDataReporter,
)
from openmm.unit import nanometer, kelvin, picosecond, picoseconds

# Load the topology and coordinate files.
gro = GromacsGroFile("methane.gro")
top = GromacsTopFile(
    "methane.top",
    periodicBoxVectors=gro.getPeriodicBoxVectors(),
)


# Initialise the molecular system.
system = top.createSystem(
    nonbondedMethod=PME, nonbondedCutoff=1 * nanometer, constraints=HBonds
)
#
# # Define the integrator.
integrator = LangevinIntegrator(0 * kelvin, 1 / picosecond, 0.002 * picoseconds)

# Set the simulation platform.
platform = Platform.getPlatformByName("CPU")
properties = {}

# Initialise and configure the simulation object.
simulation = Simulation(top.topology, system, integrator, platform, properties)
simulation.context.setPositions(gro.positions)
simulation.context.setPeriodicBoxVectors(*gro.getPeriodicBoxVectors())
simulation.minimizeEnergy()

# Add reporters.
simulation.reporters.append(DCDReporter("openmm.dcd", 100, append=False))
log_file = open("openmm.log", "a")
simulation.reporters.append(
    StateDataReporter(
        log_file,
        100,
        step=True,
        time=True,
        potentialEnergy=True,
        kineticEnergy=True,
        totalEnergy=True,
        temperature=True,
        volume=True,
        totalSteps=True,
        speed=True,
        remainingTime=True,
        separator=" ",
    )
)

# Run the simulation.
simulation.step(10000)
```
However, this will fail with `openmm.OpenMMException: Particle coordinate is nan`, If I change the `constraints` to `None`, it will work fine.

I have checked the constraints, and which seem to be working fine.
```python
>>> system.getForces()
[<openmm.openmm.NonbondedForce; proxy of <Swig Object of type 'OpenMM::NonbondedForce *' at 0x7f8f086a7330> >,
 <openmm.openmm.HarmonicAngleForce; proxy of <Swig Object of type 'OpenMM::HarmonicAngleForce *' at 0x7f8f086a74b0> >,
 <openmm.openmm.CMMotionRemover; proxy of <Swig Object of type 'OpenMM::CMMotionRemover *' at 0x7f8f086a7570> >]
```
I can see there isn’t bond parameter, which is what I’m expecting as the methane only has C-H bond and water doesn’t have a harmonic bond.
I have also checked the constraint
```python
>>> system.getConstraintParameters(0)
[0, 1, Quantity(value=0.10939, unit=nanometer)]
>>> system.getConstraintParameters(1)
[0, 2, Quantity(value=0.10939, unit=nanometer)]
>>> system.getConstraintParameters(2)
[0, 3, Quantity(value=0.10939, unit=nanometer)]
>>> system.getConstraintParameters(3)
[0, 4, Quantity(value=0.10939, unit=nanometer)]
>>> system.getConstraintParameters(4)
[5, 6, Quantity(value=0.09572, unit=nanometer)]
```
So the constrain numbers 0-3 belong to methane, which seems to be the right one as well. The 4-th one is from water which seems to be right as well.
So the Hbond constrain is all good.

**Comment by sef43** [comment]
Hi, the issue will be due to the Methane molecule. It has 5 atoms with 4 bonds, If you constrain all 4 bonds it becomes over-constrained.  (If you remove one of the constraints you will find that it runs:`system.removeConstraint(0)`)

Gromacs uses a different constraints algorithm (LINCS) to OpenMM which will be trying to use CCMA. @peastman will be able to confirm if CCMA should be able to deal with Methane.

Note that by default OpenMM uses rigid water, so when you are running with 
```
system = top.createSystem(
    nonbondedMethod=PME, nonbondedCutoff=1 * nanometer, constraints=None
)
```
All water molecules will be rigid, the only bond forces in the system will be the C-H bonds in the methane.

**Comment by xiki-tempula** [comment]
> if CCMA should be able to deal with Methane

Many thanks for the explanation. I wonder if you felt that this is something that openMM will try to deal with or it is up to the user to fix the topology?

> Gromacs uses a different constraints algorithm (LINCS) to OpenMM which will be trying to use CCMA.

Would the same issue apply to amber as well? SHAKE is pretty close to LINCS.

**Comment by peastman** [comment]
That's it exactly.  Enforcing constraints always involves solving a system of equations, either explicitly or implicitly.  If you add constraints for all bonds and angles in methane, the system of equations is singular (overdetermined).  Removing any one constraint fixes the problem.

CCMA solves the equations explicitly.  If they're singular, it tends to fail spectacularly with immediate nans.  LINCS approximates the constraint matrix with a series expansion, which doesn't converge if they're singular.  And it uses  an iterative solver, but it hardcodes only two iterations regardless of whether the solution has converged.  That prevents it from failing as obviously, but don't assume that means it's working.  It likely isn't enforcing the constraints very accurately, and it may also be doing a poor job of energy conservation.  Those are more subtle types of failures, but just as important.

**Comment by sef43** [comment]
> Many thanks for the explanation. I wonder if you felt that this is something that openMM will try to deal with or it is up to the user to fix the topology?
> 
For this specific simulation with methane yes you will need to change the scripts such that some its bonds are un-constrained. (and probably use a timestep of 1fs)

**Comment by peastman** [comment]
No need to reduce the timestep.  With only rigid molecules, a large timestep should be fine.  The methane will still be completely rigid.  The problem right now is that it has too many constraints, more than it takes to make it completely rigid.  By removing one constraint, you'll be left with exactly the right number to make it completely rigid.
