### ISSUE TITLE
Calculation of reweighting factor in metadynamics (Tiwary, Parrinello, J. Phys. Chem. B 2015, 119, 3, 736–742)

### ISSUE THREAD

**Issue by sbhakat** [openmm/openmm#3858]
Very new to OpenMM-metadynamics interface. I was wondering if it is possible to implement calculation of time-dependent reweighting factor `c(t)` during well-tempered metadynamics run (equation 22 of the paper: https://www.dropbox.com/s/vcwrlxylp10iwkm/metad-reweight.pdf?dl=0)? This will able us to calculate `rbias =metad.bias - c(t)` . `rbias` will help us to calculate unbiased free energy surface according to _Tiwary & Parrinello_ algorithm. Any pointer, comments on this will be greatly appreciated. I know this is possible to achieve via `OpenMM-Plumed` implementation but it will be nice to have this function integrated with Metadynamics app.

**Comment by peastman** [comment]
If I understand correctly, you need to integrate a function of the bias potential $V(s)$ over the domain defined by the collective variables?  The biases are stored in `metadynamics._totalBias`.  For example, `getFreeEnergy()` just returns that field multiplied by a scale factor:

https://github.com/openmm/openmm/blob/344463118f402cb6b3fc28474c015f56f2d5aff9/wrappers/python/openmm/app/metadynamics.py#L182-L189

Given that, it's mostly easy to compute the integral over it.  The one complication is that the values in that array should really by interpreted as control points that a natural or periodic (depending on whether the CVs are periodic) cubic spline surface gets fit to.  So for best accuracy, you should fit a spline (for example with `scipy.interpolate`) and then either compute the integral of each spline patch analytically, or just evaluate it on a finer grid that you integrate numerically.  Though it's possible just integrating the control points numerically would be accurate enough for your needs.
