### ISSUE TITLE
Solvating protein structure using Modeller.AddSolvent() vs using a pre-equilibrated water box

### ISSUE THREAD

**Issue by noahharrison64** [openmm/openmm#3862]
Hi,

I'm attempting to calculate residue depth by measuring the distance between protein residue and nearest bulk water. I'm following [this protocol](https://www.sciencedirect.com/science/article/pii/S0969212699800975), which suggests taking a PDB file and solvating it. You repeat this a number of times, at each iteration rotating and translating the protein a small amount in order to approximate the dynamics of a molecule in solution. 

In this method, the authors use a pre-equilibrated water box and merge this with the PDB. I wonder whether this is going to be that different to just using Modeller.AddSolvent(), or are they basically achieving the same thing?

 Is the solvent distal to protein surface going to be reasonably well-equilibrated without having subsequent rounds of simulation? Will rotations/translations between .AddSolvent() stages cause new relative locations for the water molecules or are their positions dependent on the protein orientation and position? 

**Edit: I have just seen in the source code the following documentation:** Therefore I assume the answer is going to be yes to all of the above questions.

>   There exist many different water models, many of which are very similar to each other. This method creates
>         preequilibrated water boxes for a limited set of water models.

Thanks,
Noah

**Comment by sef43** [comment]
Yes that is correct. AddSolvent does the same procedure as the paper mentions. It loads a pre-equilibrated water box and then deletes water molecules that overlap with the protein atoms.

**Comment by noahharrison64** [comment]
Great - thanks
