### ISSUE TITLE
Gaussian width in metadynamics

### ISSUE THREAD

**Issue by sbhakat** [openmm/openmm#3863]
Looking at the metadynamics implementation at OpenMM it seems like there is no option to specify Gaussian width (`SIGMA`= keyword in Plumed). Is there a way to define a the width of Gaussians within OpenMM metadynamics ?

**Comment by peastman** [comment]
I think you're talking about the `biasWidth` parameter?  See docs.openmm.org/latest/api-python/generated/openmm.app.metadynamics.BiasVariable.html.

**Comment by sbhakat** [comment]
Perfect, exactly. Got it
