### ISSUE TITLE
Import Error: most likely due to a circular import

### ISSUE THREAD

**Issue by 1heman** [openmm/openmm#3864]
Hi

I have been using OpenMM regularly for running MD simulations. I do this in Google Colab which means I install OpenMM and other necessary packages in every instance.

However, today when I try to `import openmm`, I get the following error
```---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[<ipython-input-4-f7b8d175e4b0>](https://localhost:8080/#) in <module>
----> 1 import openmm

1 frames
[/usr/local/lib/python3.7/site-packages/openmm/openmm.py](https://localhost:8080/#) in <module>
     11 # Import the low-level C/C++ module
     12 if __package__ or "." in __name__:
---> 13     from . import _openmm
     14 else:
     15     import _openmm

ImportError: cannot import name '_openmm' from partially initialized module 'openmm' (most likely due to a circular import) (/usr/local/lib/python3.7/site-packages/openmm/__init__.py)

---------------------------------------------------------------------------
```

I am using OpenMM v7.6 in python v3.7.13

Please help me out here.
-Hemant

**Comment by sef43** [comment]
Could you please share the commands showing how you setup the Colab environment, Ideally a minimal working example that produces the error? E.g. this is how we set up our cookbooks:
```
!pip install -q condacolab
import condacolab
condacolab.install_mambaforge()
!mamba install openmm
```
Which you can see an example of here:
https://colab.research.google.com/github/openmm/openmm-cookbook/blob/gh-pages/dev/colab/notebooks/cookbook/Changing%20Temperature%20and%20Pressure.ipynb

**Comment by 1heman** [comment]
```
!wget -qnc https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
!bash Miniconda3-latest-Linux-x86_64.sh -bfp /usr/local
!conda install -y -q -c conda-forge openmm=7.6 python=3.7
```
This is how I have been installing all this while

If you try `import openmm` after this, you can get the error I've posted earlier.

Having said that, I also tried the approach used in your cook book. OpenMM import worked!
I hope I can integrate this with the other dependencies in my MD pipeline.
Thanks
