### ISSUE TITLE
iAMOEBA (direct polarization) water model no longer working.

### ISSUE THREAD

**Issue by leeping** [openmm/openmm#3865]
Recently I've wanted to start running some OpenMM simulations using the iAMOEBA water model.  I've been running into a problem that energy minimizations and dynamics are giving me errors where the particle position quickly becomes nan; the simulations used to work well before, so I'm not sure if anything changed in the API or implementation over the past few years.  The minimization and MD simulations work correctly if I use version 7.4, so something must have changed between that version and v7.7.

I've attached the files to reproduce the issue.  The pdb file in the archive was previously okay for running iAMOEBA simulations (starting with minimization).  Please let me know if you have time to help, and if there's anything else I can provide to help with this issue.

[test_iamoeba.zip](https://github.com/openmm/openmm/files/10196823/test_iamoeba.zip)

Thanks,

- Lee-Ping

**Comment by peastman** [comment]
Your script is working for me with the most recent development code.  Can you try installing the latest dev build with

```
conda install -c conda-forge/label/openmm_dev -c conda-forge openmm
```

or alternatively build the latest code from source?  If that still doesn't work, what platform/hardware/OS are you running it on?

**Comment by sef43** [comment]
The error comes from the `iamoeba.xml` file:   
```
<Vdw class="74" sigma="0.0" epsilon="0.0" reduction="1.0"/> 
```
The value of sigma = 0.0 can cause divide by zero errors in the code, e.g. [here](https://github.com/openmm/openmm/blob/cd5029c2e7b686d12e865bd3a4c6ed0ea9498025/plugins/amoeba/platforms/reference/src/SimTKReference/AmoebaReferenceVdwForce.cpp#L139).
If you change it to 1e-6 it will run.

**Comment by peastman** [comment]
Thanks for figuring this out.

You can set sigma to pretty much anything *except* 0.  The energy term will get multiplied by 0, after all.  The problem happens because sigma appears in the denominator for 14-7 (unlike LJ where it only appears in the numerator) leading to nan.

**Comment by peastman** [comment]
Throwing an exception sounds like the right behavior to me, since sigma=0 is never a valid choice with 14-7.

**Comment by leeping** [comment]
Thanks for finding and fixing the problem, everyone.  

If `iamoeba.xml` currently has `sigma=0` set, then maybe we should change the value to a nominal non-zero value (say 1e-6) in the force field file.  Should I do this, or would you like to do it?

**Comment by peastman** [comment]
A PR would be welcome!  Let's just set it to 1.  It's a nice round number for something that has no physical meaning.

**Comment by leeping** [comment]
Thanks a lot - I just created a PR. :)
