### ISSUE TITLE
Protein outside the water box

### ISSUE THREAD

**Issue by jsruizc** [openmm/openmm#3869]
Greetings 
I write to you because I am trying to run a MD of a Protein that interacts with a strain of RNA, but somehow the protein and the strain in the PDB are perfectly centered, but as soon as I run the MD It seems to change the coordinates because they are always outside the water box.
This brings some other issues like disappearing a reappearing in other place because of periodic boundary conditions. In summary, I was wondering how can I center both molecules before I run the MD?
I took this Screenshot of the MD I ran. 

Thank you
![image](https://user-images.githubusercontent.com/79607460/207295262-adf6df33-6408-46f1-8a65-ad75b544eaa4.png)

**Comment by sef43** [comment]
This will just be effect of the periodic boundary conditions, take a look at the FAQ: https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#periodic
particularly the last part about output and visualisation.
