### ISSUE TITLE
Tracking periodic boundary crossings

### ISSUE THREAD

**Issue by bbye98** [openmm/openmm#3874]
Hello!

I'd like to get some clarification on how OpenMM handles boundary crossings with periodic boundary conditions.

For reference, when dumping a trajectory in LAMMPS, you can request the unwrapped particle positions `xu`, `yu`, and `zu` using [`dump_modify unwrap yes`](https://docs.lammps.org/dump_modify.html). The logic behind this is simple: LAMMPS keeps track of both wrapped particle positions (`x`, `y`, `z`) and the number of times the particles have crossed the boundaries (`ix`, `iy`, `iz`). For example, in the x-direction, if the particle crosses the left x = 0 (resp. x = L_x) boundary to jump from the left (resp. right) side of the simulation box to the right (resp. left) side, then 1 is subtracted from (resp. added to) `ix`. The unwrapped positions are then assumedly calculated using just `xu = x + ix * dimx`, `yu = y + iy * dimy`, etc., where `dimx` is the box length in the x-direction and so on.

I need the unwrapped positions because I am trying to calculate diffusivity/transport coefficients. My trajectories currently have only the wrapped positions (easy to tell from visualizing in OVITO since the particles are contained within the simulation box). I am manually unwrapping them in post-processing by checking if a particle has travelled more than half of the box size, but this is *not* a fool-proof approach since it may be possible for my particles to actually travel more than half of the box size with a large enough timestep and a small enough output frequency.

I was hoping OpenMM would report the number of periodic boundary crossings, but I don't believe this is a feature yet. The `enforcePeriodicBox` argument for the reporters and `Simulation.Context.getState()` only "unwraps" molecules/bonded particles on the boundary, if my understanding is correct (I saw [this issue](https://github.com/openmm/openmm/pull/1895)).

Is there an easy way to get the real unwrapped particle positions the way that LAMMPS currently has it implemented?

Thank you in advance for any feedback or suggestions!

**Comment by peastman** [comment]
See [the FAQ](https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#periodic).  I think it will clarify the matter for you.  Positions never get "unwrapped".  They are what they are.  Every particle has a position, and that doesn't need to have any connection to the box dimensions.  When retrieving positions with `getState()`, you can optionally tell it to wrap the positions and bring all the molecules into a single periodic box.  If you don't do that, you get the positions with no wrapping applied, whatever they happen to be.

**Comment by bbye98** [comment]
I read the section on how periodic boundary conditions work in the FAQ, and I concur--particle positions are what they are.

However, let's consider a simple toy example. Suppose we have a box that is 10x10x10 large (irrelevant units). I have two (bonded) particles at (0, 0, 0) and (1, 0, 0).

Suppose they both move to the "left" by 0.5. This means their new "real" positions are (-0.5, 0, 0) and (0.5, 0, 0).

Presumably, if I specify `enforcePeriodicBox=True` for the reporter, the outputted coordinates will be (-0.5, 0, 0) and (0.5, 0, 0) because the particles are bonded and the whole molecule is shifted so that they are in the same "image". This is fine and what I want.

If I specify `enforcePeriodicBox=False`, then I will probably get (9.5, 0, 0) and (0.5, 0, 0). Still fine since the first particle moved by well over half the box x-length, which means that I can tell that its position needs to be unwrapped from (9.5, 0, 0) to (-0.5, 0, 0).

However, that's for a single timestep. Let's say I output to a trajectory file infrequently, say every 12 timesteps, with the particle travelling directly left in the x-direction at the same velocity v=-0.5. Then, the final "real" positions should be (-6, 0, 0) and (-5, 0, 0).

In this case, regardless of what `enforcePeriodicBox` is, the outputted coordinates will be (4, 0, 0) and (5, 0, 0). Taking these coordinates at face value would suggest that the particles have moved "right" by 4, respectively, instead of moving "left" by 6. This will give me the wrong MSD/diffusion coefficient if I calculate it using the coordinates in my trajectory.

I am looking for a way to somehow recover (-6, 0, 0) and (-5, 0, 0) so that I get the correct displacement, but I'm not sure if it's possible or I'm missing something simple.

**Comment by peastman** [comment]
> If I specify enforcePeriodicBox=False, then I will probably get (9.5, 0, 0) and (0.5, 0, 0).

No, you will get (-0.5, 0, 0) and (0.5, 0, 0).  The first particle started at (0, 0, 0) and moved by -0.5 along the x axis.  That puts it at -0.5, not 9.5.  After 12 steps of that size it will be at (-6, 0, 0).  That's the position it will return.  Since you specify `enforcePeriodicBox=False` it won't do anything to move the particle into a particular periodic box.  It will just return the position.

Remember this important point from the FAQ: periodic boundary conditions are applied to displacements, not positions.  Unless you specifically tell it to wrap the positions (with `enforcePeriodicBox=True`), the presence of periodic boundary conditions has no impact on the position of any particle.  It can still have any position.

**Comment by bbye98** [comment]
Interesting, looks like my understanding of how `enforcePeriodicBox` works was incorrect, and `enforcePeriodicBox=False` indeed is the behavior that I was looking for (giving me "raw" "unwrapped" positions always, regardless of connectivity).

Super appreciate your help as always--keep up the awesome work!
