### ISSUE TITLE
Batch computation for different positions in the same simulation context

### ISSUE THREAD

**Issue by joseph-c-kim** [openmm/openmm#3875]
I'm relatively new to using OpenMM, and I've been trying to find out if there is support for batch computations. In other words, given the same simulation context, I wish to compute potential energies and forces for different conformations of a protein system in parallel. My current setup is to just run `context.setPositions(x)` followed by `context.getState(getForces=True, getEnergy=True)` for different conformations `x` in a for loop. This works, but I was just wondering if there is a more efficient way to do this given that the simulation context does not change at all for each input set of positions `x`.

For further context, I checked openmm-torch (since I am primarily using OpenMM with PyTorch), but it doesn't seem like they have support for batch computations either.

Edit: Another thing I've tried is using python's `multiprocessing` module, but this did not provide much of a speedup when I'm using a GPU with the CUDA platform.

**Comment by peastman** [comment]
There isn't currently any way to do that.  We do have an open feature request for it (#2535).  If this would be useful for you, perhaps post there and describe your use case.

**Comment by peastman** [comment]
(Closing this as a duplicate.)
