### ISSUE TITLE
No serialization proxy registered for type 'DrudeLangevinIntegrator'

### ISSUE THREAD

**Issue by hsinlan2** [openmm/openmm#3876]
I am trying to run polarizable force field simulations using xml files. I get this error: 

ERROR:exception: There is no serialization proxy registered for type 'DrudeLangevinIntegrator'

I would really appreciate if anyone could share any insights to this issue. Thanks!

**Comment by peastman** [comment]
Can you show the full code for what you're doing?  Also, which version of OpenMM and how did you install it?

**Comment by hsinlan2** [comment]
Hi, thank you! I am trying to run these simulations on folding at home. I equilibrated the system using scripts provided by charmm-gui  drude prepper, which ran with no problem using openmm 7.7 installed on my local cluster. The only thing I added to the script was serializing the integrator, system, and state at the end of the simulation. Attached are the script and files that I used to generate the system. I ran the command `python openmm_run.py -i step5_production.inp -p step3_charmm2omm.psf -c step3_charmm2omm.crd -t toppar.str `

[openmm.zip](https://github.com/openmm/openmm/files/10264014/openmm.zip)

**Comment by peastman** [comment]
That sounds like maybe the Folding@home core doesn't support Drude?  It only includes a subset of the plugins, and possibly it's missing the Drude one.  I haven't been involved with F@H development in a few years.  Maybe one of the active developers can comment.

**Comment by hsinlan2** [comment]
Thanks! I am trying to get in touch with them. Although I don't have access to the OpennMM FAHcore repo, I think I will try posting this issue on the FAH github. Thanks again!

**Comment by dotsdl** [comment]
@peastman here are the full contents of the current OpenMM core for Folding@Home:
```
FahCore_22                 libOpenMMAmoebaCUDA.so       libOpenMMDrudeReference.so
libcufft.so.10             libOpenMMAmoebaOpenCL.so     libOpenMMOpenCL.so
libfftw3f.so.3             libOpenMMAmoebaReference.so  libOpenMMPME.so
libfftw3f_threads.so.3     libOpenMMCPU.so              libOpenMMRPMD.so
libnvrtc-builtins.so.11.2  libOpenMMCUDA.so             libOpenMMRPMDCUDA.so
libnvrtc.so.11.2           libOpenMMCudaCompiler.so     libOpenMMRPMDOpenCL.so
libOpenCL.so.1             libOpenMMDrude.so            libOpenMMRPMDReference.so
libOpenMM.so.7.7           libOpenMMDrudeCUDA.so        libstdc++.so.6
libOpenMMAmoeba.so         libOpenMMDrudeOpenCL.so
```
Is there anything obviously missing from here that could cause the exception `There is no serialization proxy registered for type 'DrudeLangevinIntegrator'`?

**Comment by peastman** [comment]
Are the libraries now loaded dynamically instead of being linked statically?  The serialization proxy should be compiled into `libOpenMMDrude.so`, and `registerDrudeSerializationProxies()` should be invoked automatically when it's loaded.

@hsinlan2 what OS are you on?

**Comment by jchodera** [comment]
If this is a Folding@home core issue, we should move the discussion to the [Folding@home OpenMM core issue tracker](https://github.com/FoldingAtHome/openmm-core/issues).

**Comment by hsinlan2** [comment]
I'm using the following:

**Comment by jchodera** [comment]
On the FAH core, I believe we disable automatic loading of dynamic libraries and manually specify which plugins are to be loaded---we can continue the conversation on that repo once you have access.
