### ISSUE TITLE
CustomCentroidBondForce using issue

### ISSUE THREAD

**Issue by Byun-jinyoung** [openmm/openmm#3878]
Dear OpenMM users and developers,
Recently I've tried to write a code that performs steered MD.
 ```
 self.force = CustomCentroidBondForce(2, '0.5*fc_pull*(r-r0)^2')                                                                      
 self.force.addPerBondParameter('fc_pull')                                                                                            
 self.force.addPerBondParameter('r0')                                                                                                 
 self.force.addGroup(pull_g1)                                                                                                         
 self.force.addGroup(pull_g2)                                                                                                         
 self.force.addBond([0, 1], [fc_pull, r0])
 system.addForce(self.force)
```
When I run the above code, I got the error below..
```
...
  File "/home/byun/anaconda3/envs/MD_env/lib/python3.7/site-packages/openmm/app/simulation.py", line 103, in __init__
    self.context = mm.Context(self.system, self.integrator, platform, platformProperties)
  File "/home/byun/anaconda3/envs/MD_env/lib/python3.7/site-packages/openmm/openmm.py", line 16305, in __init__
    _openmm.Context_swiginit(self, _openmm.new_Context(*args))
openmm.OpenMMException: CustomCentroidBondForce: Unknown variable 'r
```
I want the distance between `pull_g1` and `pull_g2` to increase during steered MD.
Actually, I can not fully understand **addGlobalParameter** and its **defaultvalue**.

How can I solve this problem?

Thank you for all  your efforts.

**Comment by peastman** [comment]
See the [API documentatiion](http://docs.openmm.org/latest/api-python/generated/openmm.openmm.CustomCentroidBondForce.html#openmm.openmm.CustomCentroidBondForce), which lists the variables and functions you can use in the expression.  In your case the expression should be `'0.5*fc_pull*(distance(g1,g2)-r0)^2'`.

A global parameter is just a number.  The default value sets what its initial value is when you first create the Context.  You can change it at any time.  Since you want the distance to increase, that suggests you want `r0` to be a global parameters:

```python
self.force.addGlobalParameter('r0', r0_initial)
```

At any point in the simulation, you can set a new value with

```python
simulation.context.setParameter('r0', new_r0)
```

**Comment by Byun-jinyoung** [comment]
Thank you for your reply!
And I have another question:
Whereas **addGlobalParameter** can be updated by `simulation.context.setParameter('r0', new_r0)`, is the **addPerBondParameter** constant at any point in the simulation?

**Comment by peastman** [comment]
It's also possible to change per-bond parameters, but it's more expensive.  You call `setBondParameters()` to set new values for bonds.  Once you're done setting them, call `updateParametersInContext()`.  Until you do that, the changes won't affect any existing Context.

**Comment by Byun-jinyoung** [comment]
Oh Thank for your quick reply!. @peastman 
It was the point what I wondering because I think there is no difference  between `addGlobalParameter` and `addPerBondParameter` at my first glance. But there is a  some expensive resource!
Thank you!

**Comment by peastman** [comment]
`updateParametersInContext()` is expensive to call.  Calling `setParameter()` on the Context is very cheap.  Of course, the other difference is that a per-bond parameter can have a different value for every bond.

Is it ok to close this issue?
