### ISSUE TITLE
The recommended way of doing type hinting and type checking with openMM units

### ISSUE THREAD

**Issue by xiki-tempula** [openmm/openmm#3881]
Hi, I wonder what is the recommended way of doing type hinting and checking for openMM units?
Say I have a function that I want the user to input time, the inverse of time and length. What is the best way to do the type hinting?
`def run(time: openmm.unit.time_base, collision_rate: 1/openmm.unit.time_base, cutoff: openmm.unit.length_base)`
Also I wonder what is the best way to check if a variable is for example a time and it is not a length unit or inverse of time unit? Thanks.

**Comment by peastman** [comment]
Unfortunately, the recommended way of doing it is not to do it. :(  I tried to figure out a realistic way of specifying types, but couldn't come up with anything practical.

To start with, almost all methods that accept quantities with units also accept simple numbers.  So just specifying that would require a lot of specification like `Union[Quantity, float, int]`.

But that just says you're allowed to specify units.  It doesn't say what the expected units are.  Checking for correct units requires the type analyzer (e.g. mypy) to understand units math and be able to figure out what type of object you're passing for an argument.  What is the type of `x*nanometers`?  If `x` is a float, that's a Quantity wrapping a float with dimension of distance.  Or `x` might be a numpy array, in which case it's a Quantity wrapping an array with dimension of distance.  But maybe `x` is itself a Quantity.  Then the result is a Quantity with a different dimension... unless `x` is an inverse distance, in which case the result is a simple object (float?  int?  array?  list?) with no units.

Even using the class of the wrapped value is complicated.  `(5*nanometers)/nanometers` is an int, but `(5*angstroms)/nanometers` is a float.

I eventually concluded it was impossible to make it work consistently and gave up on it.

**Comment by peastman** [comment]
> Also I wonder what is the best way to check if a variable is for example a time and it is not a length unit or inverse of time unit?

Do you mean at runtime?  The simplest way is just to cast it and see if it works.  `x.value_in_unit(nanometers)` will return the correct value if `x` has units of distance, but throw an exception if it has any other units.

**Comment by xiki-tempula** [comment]
@peastman  Thanks but it seems that this method cannot handle the inverse of a unit.
```
collision_rate = 1 / openmm.unit.picosecond
collision_rate. value_in_unit(1 / openmm.unit.nanosecond)
```
would give TypeError

**Comment by peastman** [comment]
`value_in_unit()` expects you to pass a Unit, not a Quantity.  You can do it like this:

```python
collision_rate.value_in_unit(openmm.unit.nanosecond**-1)
```

**Comment by xiki-tempula** [comment]
Great Thanks.
