### ISSUE TITLE
Cuda compiler error

### ISSUE THREAD

**Issue by namyh** [openmm/openmm#3883]
Dear users and developers, 

I installed newest OpenMM with conda and I had this error 

Traceback (most recent call last):
  File "/home/unsit/Downloads/opemm_test/openmm/openmm_run.py", line 113, in <module>
    simulation = Simulation(top.topology, system, integrator, platform, prop)
  File "/home/unsit/anaconda3/lib/python3.9/site-packages/simtk/openmm/app/simulation.py", line 105, in __init__
    self.context = mm.Context(self.system, self.integrator, platform, platformProperties)
  File "/home/unsit/anaconda3/lib/python3.9/site-packages/simtk/openmm/openmm.py", line 9250, in __init__
    _openmm.Context_swiginit(self, _openmm.new_Context(*args))
simtk.openmm.OpenMMException: Error compiling program: nvrtc: error: invalid value for --gpu-architecture (-arch)

So I tried with a 
source code and the only test failed was TestCudaCompiler 
(exception: Error compiling program: nvrtc: error: invalid value for --gpu-architecture (-arch))

My environment is cuda 11.2 and python 3.9 

Is this issue related to CUDA installation?

**Comment by peastman** [comment]
This usually means your CUDA toolkit is too old for your GPU.  What kind of GPU do you have?  Also, what driver version?  You can check with `nvidia-smi`.

Try upgrading to a newer CUDA toolkit.

**Comment by namyh** [comment]
My GPU is RTX3090
and my driver version 460.27.04
Is there any recommended CUDA toolkit version for those?

**Comment by peastman** [comment]
Does that mean you already got it working?

Your driver is new enough to support any 11.x toolkit, so I would try 11.8.
