### ISSUE TITLE
Analytic derivatives with respect to parameters

### ISSUE THREAD

**Issue by leeping** [openmm/openmm#389]
This topic is to discuss the idea of implementing analytic (first and second) derivatives of energies (and forces) with respect to force field parameters.  It is something I once implemented in Gromacs, but it was an exceedingly time consuming thing to do.  It would be good to talk about:

1) What the applications would be
2) What the API might look like
3) The difficulty level of doing this efficiently and correctly

This would help us determine whether the benefits are worth the costs.

**Comment by peastman** [comment]
We now support derivatives with respect to global parameters.  We don't have current plans to support them for other types of parameters (per-particle, per-bond, etc.).
