### ISSUE TITLE
Reporting periodic box vectors

### ISSUE THREAD

**Issue by kong1-731** [openmm/openmm#3891]
I noticed that System.[getDefaultPeriodicBoxVectors](http://docs.openmm.org/7.1.0/api-python/generated/simtk.openmm.openmm.System.html#simtk.openmm.openmm.System.getDefaultPeriodicBoxVectors)(self) reports the default box vectors, but are these vectors the same as the instantaneous vectors as the system changes shape say due to pressure control? I would like to report the X, Y, and Z length at every timestep of my simulation, and I just want to check that getDefaultPeriodicBoxVectors will provide me with the instantaneous reading of those lengths at each timestep. Thank you!

**Comment by craabreu** [comment]
You should use [Context.getState](http://docs.openmm.org/latest/api-python/generated/openmm.openmm.Context.html#openmm.openmm.Context.getState) followed by [State.getPeriodicBoxVectors](http://docs.openmm.org/latest/api-python/generated/openmm.openmm.State.html#openmm.openmm.State.getPeriodicBoxVectors) to get the instantaneous box state.

**Comment by kong1-731** [comment]
Thank you!
