### ISSUE TITLE
setting positions

### ISSUE THREAD

**Issue by mbatgh** [openmm/openmm#3892]
Hi,

I am trying to explicitly set the coordinates of some atoms in my system (AFTER defining context, forcefield, etc)
Since I only want to assign coordinates to a small subset of my system I'd
rather avoid reading in all coordinates, e.g., from a PDB file, instead I tried:
 
[...]
simulation = Simulation(modeller.topology, system, integrator)
print(modeller.positions[4241])
# the print command works and gives  me
[-1.1126 -0.1914 -0.1932] nm

# then I try:
vec = [ 1, 2, 3 ]
modeller.positions[4241] = vec.value_in_unit(unit.nanometer)
# which gives me:
AttributeError: 'list' object has no attribute 'value_in_unit'

any suggestions how to get what I want?

thanks!
Michael

**Comment by Lnaden** [comment]
The `value_in_unit` method works on unit bearing `Vec3` objects, or `simtk.unit.Unit` objects, which is what you get out of the `.positions` object. 

The `vec = [ 1, 2, 3 ]` command makes a list, to make it a `Unit` object, multiply by the unit you are setting it as:

```python
vec = [ 1, 2, 3 ] * unit.nanometer
modeller.positions[4241] = vec
```

**Comment by mbatgh** [comment]
Thank you for the swift reply.

that works, however, turns out I need to say:
vec = [ 1, 2, 3] * openmm.unit.nanometer

since 
vec = [ 1, 2, 3] * unit.nanometer
gives me:
AttributeError: module 'openmm.unit.unit' has no attribute 'nanometer'

as further up in the script i load:
from openmm import *
from openmm.unit import *

If I just remove the second import I get another complaint about a missing definition of kelvin.

thanks,
Michael
