### ISSUE TITLE
Tolerance value for minimization

### ISSUE THREAD

**Issue by jnoske** [openmm/openmm#3894]
What tolerance value for minimization is generally recommended, does it make sence to go lower than the default value of 10 kcal/mol? In which cases would one want to do that? Should the tolerance value be changed at all?

**Comment by peastman** [comment]
There's no universal answer.  It depends on your application and why you're minimizing it.  The most common reason is to eliminate bad clashes at the start of a simulation.  For that a high tolerance value is fine.  You just need to eliminate forces that are high enough to cause problems for the simulation.  In other situations someone might want to locate a minimum more precisely for other purposes.  In that case they would choose a lower tolerance.

**Comment by z-gong** [comment]
I have difficulty understanding what this tolerance means exactly. In the document it says

> Minimization will be halted once the root-mean-square value of all force components reaches this tolerance.

This root-mean-square is calculated on each atom `all(rms(Fix, Fiy, Fiz) < tolerance for atom in atoms)` ? Or is it calculated on the whole system `rms(F0x, F0y, F0z, ..., Fnx, Fny, Fnz) < tolerance` ?

**Comment by peastman** [comment]
The latter.  It's the RMS over all atoms.
