### ISSUE TITLE
How to make molecules rigid?

### ISSUE THREAD

**Issue by aizvorski** [openmm/openmm#3895]
I'm wondering if there is a general way to make molecules fully rigid using constraints.  I think making water rigid just involves adding H-O and H-H distance constraints.  But how about (for example) methane, or a formate ion?  

In the case of methane, adding an H-H constraint between every pair of hydrogens as well as C-H would over-constrain the molecule.  In the case of formate, having C-H, C-O, O-O and O-H constraints would over-constrain as well; dropping the O-O would possibly work, but it seems the constraints may have trouble making the molecule entirely planar in this case.

**Comment by peastman** [comment]
Making very small molecules rigid is surprisingly complicated.  For methane, removing any one constraint should produce a set that works well.  Planar molecules are more difficult: constraints are enforced by applying constraint forces along the bond directions, which aren't effective at preventing motion out of the plane.  You end up with a poorly conditioned matrix.  Instead you need to add a dummy atom out of the plane and constraint its distance to the real atoms.

For larger molecules you can use [this script](https://simtk.org/svn/pyopenmm/trunk/simtk/pyopenmm/extras/rigid.py).  It selects just a few atoms to define the rigid body and turns all the others into virtual sites.

**Comment by aizvorski** [comment]
@peastman Thanks, that's a nice script - I'll give it a try
