### ISSUE TITLE
Failed compilation from source code

### ISSUE THREAD

**Issue by GuoHao150** [openmm/openmm#3903]
Dear openmm team,

I compiled the source code of openmm-7.7.0 on my ubuntu machine, when I run the `make test` command to test the installation, two steps failed.
```
The following tests FAILED:
        145 - TestCudaNoseHooverIntegratorMixed (Failed)
        158 - TestCudaRandomDouble (Failed)
```

Next, I checked the `LastTest.log` file, and the error messages were like the below:

![截屏2023-01-12 13 51 13](https://user-images.githubusercontent.com/35798699/211988207-45dbf9ef-0cdb-4b21-bf53-510379f12d68.png)

![截屏2023-01-12 13 51 29](https://user-images.githubusercontent.com/35798699/211988230-6c052f12-6d9d-4636-93d8-fbf3eb36ce50.png)

And here is some hardware information about my machine.
```
5.15.0-46-generic #49~20.04.1-Ubuntu SMP Thu Aug 4 19:15:44 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

GPU 0: NVIDIA GeForce RTX 3090
```
Any idea about how should I fix this?

Thanks

**Comment by RaulPPelaez** [comment]
See the tip in your first image, it says: This test is stochastic and may occasionally fail
Those tests involve random numbers and somehow averaging them, which is bound to give you some outliers if you run it enough times.
Those numbers look fine to me, I'd say you can consider all tests passing if these two were the only ones to "fail" in make test.

**Comment by GuoHao150** [comment]
> See the tip in your first image, it says: This test is stochastic and may occasionally fail Those tests involve random numbers and somehow averaging them, which is bound to give you some outliers if you run it enough times. Those numbers look fine to me, I'd say you can consider all tests passing if these two were the only ones to "fail" in make test.

Thank you so much, I'll treat all the tests as passed
