### ISSUE TITLE
Strange behavior in CustomNonbondedForce  in OpenMM 7.7

### ISSUE THREAD

**Issue by qvv5013** [openmm/openmm#3904]
Hi all,
I implemented Wang-Frenkel's potential in my coarse-grain simulation and found `CustomNonbondedForce`  in `OpenMM 7.7` behaves very strangely.
`(openmm                    7.7.0           py310hccf1d78_1    conda-forge)`
Here is the simple code, which calculates nonbonded force between two particles.

```python
 
import openmm as mm
import openmm.app as app
import numpy as np

sys = mm.System()
# 2 GLY
sys.addParticle(57.05*mm.unit.amu)
sys.addParticle(57.05*mm.unit.amu)

# build topology
top=mm.app.topology.Topology()
top.addChain('prot')
prot_chain = list(top.chains())[-1]
top.addResidue('GLY', prot_chain)
res1 = list(top.residues())[-1]
top.addAtom('CA', app.Element.getBySymbol('C'), res1)

top.addResidue('GLY', prot_chain)
res2 = list(top.residues())[-1]
top.addAtom('CA', app.Element.getBySymbol('C'), res2)

# # first implementation
# energy_function = '((rc/r)^(4)-1)^(2)'
# wang_frenkel_force = mm.CustomNonbondedForce(energy_function)
# wang_frenkel_force.addGlobalParameter('rc', 1.408533*mm.unit.nanometer)

# second implementation
energy_function = '((rc/r)^(2*mu)-1)^(2*nu);'
wang_frenkel_force = mm.CustomNonbondedForce(energy_function)
wang_frenkel_force.addGlobalParameter('rc', 1.408533*mm.unit.nanometer)
wang_frenkel_force.addGlobalParameter('mu', 2)
wang_frenkel_force.addGlobalParameter('nu', 1)

for i in top.atoms():
    wang_frenkel_force.addParticle(())
    
sys.addForce(wang_frenkel_force)

integrator = mm.LangevinIntegrator(1*mm.unit.kelvin, 1/mm.unit.picosecond, 0.000001*mm.unit.picosecond)
sim = mm.app.Simulation(top, sys, integrator)

# pos=np.array([[0,0,0],[1.409,0,0]])
pos=np.array([[0,0,0],[1.9,0,0]])

sim.context.setPositions(pos)
state = sim.context.getState(getForces=True, getEnergy=True)
print(state.getPotentialEnergy())
print(state.getForces())
```

* The first implementation, where I simplify the potential by explicitly multiple $\mu$ and $\nu$ then it is consistent with the manually calculated (within some decimal of the precision)

* The second implementation, where I ask OpenMM to calculate with $\mu$ and $\nu$ (in my system, each pair of interacting particles has different values of $\mu$ and $\nu$)
The potential energy is `NaN` if distance `r>rc`

Code to manually calculate:
```python
nu, mu = 1, 2
rc=1.408533
# r=0.545
# r=1.409
r=1.9

energy_function = ((rc/r)**(2*mu)-1)**(2*nu)
print(energy_function)
```

**Comment by peastman** [comment]
I can't reproduce this with the latest version of the code.  Everything looks fine:

```
$ python test.py 
0.48715850710868835 kJ/mol
[Vec3(x=0.8876163363456726, y=0.0, z=0.0), Vec3(x=-0.8876163363456726, y=0.0, z=0.0)] kJ/(nm mol)
```

What platform and hardware are you using?  I tried both CPU and OpenCL, and they both worked correctly.

**Comment by qvv5013** [comment]
I am using the GPU CUDA platform.

The CPU platform is working well but GPU is `nan`
Here is the result comes from GPU:

```bash
nan kJ/mol
[Vec3(x=-2147483648.0, y=-2147483648.0, z=-2147483648.0), Vec3(x=-2147483648.0, y=-2147483648.0, z=-2147483648.0)] kJ/(nm mol)
```

Cuda toolkit 11.6 with driver 510.85.02:
```
cudatoolkit               11.6.0              hecad31d_10    conda-forge
```

**Comment by peastman** [comment]
Can you try installing the OpenMM 8 release candidate and see if you still get the problem?

```
conda install -c conda-forge/label/openmm_rc openmm
```

**Comment by peastman** [comment]
Did you execute the command I listed?  It should have installed 8.0.0rc1, not 8.0.0beta.

I just tested CUDA and it also works correctly for me.

**Comment by qvv5013** [comment]
Hi Peter, 
I just create a new Conda environment and execute your command. It is the same as what I got before:

```
(openmm8) qvv5013@masli6:~/work5/test_OpenMM$ conda list|grep openmm
# packages in environment at /home/qvv5013/anaconda3/envs/openmm8:
openmm                    8.0.0rc1        py310h2996cf7_0    conda-forge/label/openmm_rc
(openmm8) qvv5013@masli6:~/work5/test_OpenMM$ python sim.py 
nan kJ/mol
[Vec3(x=-2147483648.0, y=-2147483648.0, z=-2147483648.0), Vec3(x=-2147483648.0, y=-2147483648.0, z=-2147483648.0)] kJ/(nm mol)

```

So from my side, the problem occurs at v7.7, 8.0 beta, and 8.0rc1

**Comment by peastman** [comment]
That's really strange.  I can't reproduce it.  Your expression looks very straightforward.  I don't see anything in it that would cause problems for those values of the parameters.

Can anyone else reproduce this?

Can you narrow down what part of the expression leads to the problem?  Try hardcoding the value of either mu or nu while leaving the other as a parameter.  Does the problem require both of them to be parameters, or just one?  If the latter, does it matter which one?

**Comment by qvv5013** [comment]
Thanks Peter,
$\nu$ (`nu`) as the parameter causes the problem.

This expression works well: `energy_function = '((rc/r)^(2*mu)-1)^2;'`

Any thoughts on `r` and `rc`?  I found if `r>rc` causes the problem in the expression of `nu` as parameter, i.e: r=1.40853**4**

**Comment by peastman** [comment]
So this is the expression that fails?

```
energy_function = '((rc/r)^4-1)^(2*nu);'
```

I think I see the problem.  If $r>rc$, then $rc/r < 1$, which means $(rc/r)^4-1$ is negative.  Raising a negative number to a non-integral power produces a complex number, or `nan` when dealing with real floating point numbers on computers.

Of course, you're raising it to an integral power which *should* be ok.  And it works fine when I run it.  But floating point math is really finicky and often subject to roundoff errors.  Will `nu` always be an integer, such that you're raising to an even power?  If so, try this:

```
energy_function = 'abs((rc/r)^4-1)^(2*nu);'
```

On the other hand, are you really sure you want to be doing that?  That expression looks to me like a potential that is only ever supposed to be used for $r < rc$.  I think you're supposed to set `rc` equal to the cutoff distance.

**Comment by qvv5013** [comment]
Thanks Peter.
`nu` will be an integer so I will use the `abs` function, which solves the problem.

I wonder why didn't you get NaN when `r>rc`? it is related to the precision where I used mixed on GPU?
and Why CPU can work well but GPU produces the error?
