### ISSUE TITLE
Segmentation fault (core dumped) at setFrequency of Barostat

### ISSUE THREAD

**Issue by UmeshRoy** [openmm/openmm#3906]
Dear Developers,
         I'm using openmm version 7.7 with cudatool kit 11.2. I got the segmentation fault error at the [setFrequency ](http://docs.openmm.org/7.4.0/api-c++/generated/OpenMM.MonteCarloBarostat.html#_CPPv2N6OpenMM18MonteCarloBarostatE)(in timestep) of the MonteCarlo barostat.  I tried with different setFrequency, I observed that this error occurs at this time step. This error occurs only when I tried to restart a job on a different machine.  

 Can you please suggest anything about how can I avoid this issue?

Thank you 

Umesh

**Comment by peastman** [comment]
How exactly did you install it?  (Please give the exact commands.)  This usually indicates some sort of binary incompatiblity, for example using an OpenMM package that was built for a different Python version than what you're running it under.

**Comment by UmeshRoy** [comment]
Hi!
Here are the commands that I applied to install openmm

1. $nvcc --version

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Nov_30_19:08:53_PST_2020
Cuda compilation tools, release 11.2, V11.2.67
Build cuda_11.2.r11.2/compiler.29373293_0

I first installed the miniconda3 on a local directory ( Python version: 3.9.15)

2. $which python

~/apps/miniconda3/bin/python

3. $cd ~/apps/miniconda3/bin

4. $ conda install -c conda-forge openmm cudatoolkit=11.2
5. $ python -m openmm.testInstallation
OpenMM Version: 7.7
Git Revision: 130124a3f9277b054ec40927360a6ad20c8f5fa6

There are 4 Platforms available:

1 Reference - Successfully computed forces
2 CPU - Successfully computed forces
3 CUDA - Successfully computed forces
4 OpenCL - Successfully computed forces

Median difference in forces between platforms:

Reference vs. CPU: 6.29837e-06
Reference vs. CUDA: 6.72967e-06
CPU vs. CUDA: 7.33526e-07
Reference vs. OpenCL: 6.76294e-06
CPU vs. OpenCL: 8.01158e-07
CUDA vs. OpenCL: 2.73279e-07

All differences are within tolerance.

I also checked with a different version of python it didn't work out. Please let me know if you need any other information.


Thank you.

Umesh

**Comment by peastman** [comment]
> $cd ~/apps/miniconda3/bin

Why are you doing that?  If conda is properly installed and activated, it will have already added the bin directory for your current environment to your path.  If it isn't properly installed and activated, there's a high risk of it pulling incompatible libraries from different locations.  It also looks like you're installing into the base environment, which is not a good idea.

Is it showing the name of the current environment (e.g. `(base)`) in the command prompt?

**Comment by UmeshRoy** [comment]
Yes, it does show '(base)' in the command prompt. I have checked without doing $cd ~/apps/miniconda3/bin (after reinstalling miniconda3). The error is the same.

**Comment by UmeshRoy** [comment]
There might be some compatibility issues that you pointed out. I tried to restart the simulation on another machine, it is working fine. Not sure why it is not working on the previous one.

**Comment by peastman** [comment]
It's because Nothing Ever Works. ;)

Weird segfaults like this usually mean that in some way two libraries are getting loaded that weren't compiled to be compatible.  The hard part is figuring out why.  Is your conda environment corrupt?  Do you have a second copy of OpenMM installed somewhere else that has gotten added to your library path?  Has conda just gotten confused and installed two incompatible libraries?  Figuring out can be a challenge.

**Comment by UmeshRoy** [comment]
I have checked there is no second copy. But, unable to fix it. Anyway, thank you for your response.



Umesh

**Comment by peastman** [comment]
Here are some other things to try.

- Run it inside gdb.  Let it run until it segfaults, then type `bt`.  It will print a stack trace showing where the segfault happened.
- You can use the `ldd` command to list dependencies for a library.  That will show what location on disk it's pulling in each library from.  Check for cases where it's pulling in the wrong one.
