### ISSUE TITLE
Deadlock while using multiple gpus 

### ISSUE THREAD

**Issue by juliakacher** [openmm/openmm#3907]
Hello,
I am trying to run a simulation (~400k atoms) with OpenMM 7.7. Everything works fine with one GPU unless I allocate several GPUs at once. I am working on a cluster under slurm, but directly on the machine, this deadlock appears too. I even tried downgrading CUDA 11.8 to 11.2 (the version my colleague, who could run his jobs without problems on the same machines, has .. after trying more evident things), but it did not help. Of course, there are other components (e.g.slurm-related stuff) that could somehow evoke this issue, however, I am really puzzled how it could be that the script works fine when I use only one GPU and gets stuck with several... 
I also checked the Beta-2-adrenergic receptor (B2AR) membrane protein simulation with CHARMM (the one from the[ tutorial](https://openmm.org/tutorials)) and it runs all right on 2 GPUs. 

The properties are specified in both cases exactly the same way: 
```
platform = Platform.getPlatformByName('CUDA') 
properties = {'Precision': 'mixed', 'DeviceIndex': '0,1'}
```
And in submit.sh file as: 
`#SBATCH --gres=gpu:2` 

If you want/could/are curious to check the files (scripts and inputs), I could send them directly to you since I do not want to make the content public yet.
 
I will appreciate any suggestions! Several people had a look at my files and did not provide me with any plausible advice... 
Many thanks in advance!

**Comment by peastman** [comment]
If you can send files to reproduce it, that would be great.  I also have a few questions.

- What OS and what kind of GPUs are you using?
- When you say it's a deadlock, do you mean that in the technical sense or do you just mean that it appears to hang?  If the former, what evidence leads you to conclude it's a deadlock?  If the latter, can you check `top` and `nvidia-smi` while it's hung to see whether it's still using CPU and/or GPU time?  (If you can only run jobs through a queuing system, I realize that may not be possible.)
- Could you try the OpenMM 8.0 release candidate and see if it also has the problem?  You can install it with

```
conda install -c conda-forge/label/openmm_rc openmm
```

**Comment by juliakacher** [comment]
@peastman , thank you for the response! 

Installing OpenMM 8.0 release solved my issue! 

As for the details you asked about: 
-  **OS**: CentOS Linux release 7.9.2009; **GPU**s: I tried on GTX GeForce 3090, RTX A5000, GTX 2080Ti, TX 1080, GTX 1080 Ti
 
- Sorry for not specifying it more concisely,  I mean it hangs and does not calculate anything (and no outputs for hours compared to immediate response with 1gpu). Of course, I checked with` top `and `nvidia-smi`. GPUs are not occupied at all and `top` shows that the process still uses memory. (I also mentioned that I tried running directly on the machines without the queuing system to make sure that the problem is not connected with slurm) 

If you are curious about my input files, please, contact me via email yulia.kacher@univ-lorraine.fr

**Comment by peastman** [comment]
Great, it sounds like the problem has already been fixed.  I suspect it was #3560.  Thanks for reporting it.
