### ISSUE TITLE
GLH residue bonds

### ISSUE THREAD

**Issue by Dan-Burns** [openmm/openmm#3909]
Hello,

I protonated a structure on a web server and now have a GLH residue.  Modeller doesn't seem to recognize it although I see in the docs that its a supported residue type.

The preceding residue in the topology threw the error since it is not showing a bond to GLH and is presumed to be terminal.

The only GLH bonds that appear is:
[Bond(<Atom 6778 (C) of chain 0 residue 430 (GLH)>, <Atom 6792 (N) of chain 0 residue 431 (ILE)>)]

I'm using OpenMM 7.6.0.  Is there some sort of residue template for GLH I can add with loadBondDefinitions()?

Thank you,
Dan

**Comment by Dan-Burns** [comment]
I can create the system with that protonation state but I had to manually edit the pdb and remove the hydrogen and then add it back in with modeller.addHydrogen(variants_list).

Is there a way to avoid this in some scenario where I need to set up many simulations and don't want to identify and manually edit the input structure?  

Thank you,
Dan

**Comment by peastman** [comment]
>  Modeller doesn't seem to recognize it

I don't understand what you mean by that.  What exactly did you do (post the script if possible), and what error did it report?

> I had to manually edit the pdb and remove the hydrogen and then add it back in with modeller.addHydrogen(variants_list).

That means there probably was a problem in your PDB file.  Can you post the original file and the working one produced by removing and adding back the hydrogen?

**Comment by Dan-Burns** [comment]
This should reproduce it. 
```
from openmm.app import *
from openmm import *
from openff.toolkit.topology import *
from openmm.unit import *
```
This works:
```
# Manually edited PDB to turn GLH to GLU
pdb = PDBFile('tEI_af_GLH_to_GLU.pdb')
forcefield = ForceField('amber14-all.xml', 'amber14/tip3pfb.xml')
modeller = Modeller(pdb.topology, pdb.positions)
# specify the tautomer for both chains
variant_list = ['GLH' if i in [430,1003] else None for i in range(len(list(modeller.topology.residues())))]
modeller.addHydrogens(variants=variant_list)
modeller.addSolvent(forcefield, model='tip3p', padding=1*nanometer, ionicStrength=0.1*molar )
```


This one breaks at the residue preceding GLH
```
pdb = PDBFile('reflrpd292.pqr')
forcefield = ForceField('amber14-all.xml', 'amber14/tip3pfb.xml')
modeller = Modeller(pdb.topology, pdb.positions)
modeller.addSolvent(forcefield, model='tip3p', padding=1*nanometer, ionicStrength=0.1*molar )

```
`ValueError: No template found for residue 430 (VAL).  The set of atoms matches VAL, but the bonds are different.`
[structures.zip](https://github.com/openmm/openmm/files/10420850/structures.zip)
Thank you,
Dan

**Comment by peastman** [comment]
Your file uses nonstandard names.  The residue needs to be called GLU, not GLH, regardless of which protonation state it's in.  See [the FAQ](https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template) for a discussion of why this matters.

**Comment by Dan-Burns** [comment]
I see. Thank you!
