### ISSUE TITLE
VkFFT integration for optimizing PME

### ISSUE THREAD

**Issue by philipturner** [openmm/openmm#3915]
Spinoff of #3911 - [VkFFT](https://github.com/DTolm/VkFFT) is a very fast FFT library, designed to be portable and faster than cuFFT. It started on Vulkan, then expanded to CUDA, OpenCL, and all the major GPU APIs. A very recent addition was Metal.

It's heavily tested and I'd be surprised if it breaks old hardware. However, it's a good idea to only run it on tested hardware. We can first run it only on Apple GPUs - Apple7 and Apple8 are practically identical. Then slowly expand to other vendors and architectures within vendors.

VkFFT is a header-only library; most people just copy the 40,000-line header verbatim. A separate idea, is that since HIP and Metal plugins use VkFFT, why not eliminate the code duplication? Make it part of the common platform. Of course backends can still copy VkFFT internally to use the most recent commits.

**Comment by peastman** [comment]
I implemented it for OpenCL.  Testing the apoa1pme benchmark on RTX 4080, I get about a 10% speedup, from 426 to 470 ns/day.  On M1 Pro it's about a 5% speedup, from 32.4 to 34.0 ns/day.  I'll try CUDA next.  The speedup there will presumably be smaller, since cuFFT is faster than our built in FFT.

**Comment by philipturner** [comment]
Awesome! For the VkFFT Metal backend, there's a planned overhaul that will use SIMD-group shuffles on the M1. You saw less speedup on M1 Pro because current VkFFT uses mostly threadgroup memory. RTX has fast threadgroup memory, M1 has slower. Conversely, M1 has faster SIMD-group shuffles than RTX.

> On M1 Pro it's about a 5% speedup, from 32.4 to 34.0 ns/day.

Did you use the new branch with the correct SIMD width and tuned threadgroup sizes?

**Comment by peastman** [comment]
It used the correct SIMD width.  It didn't change the number of workgroups, but that has minimal impact.

**Comment by philipturner** [comment]
Also, even if you don't provide an API way for plugins to use in-tree VkFFT, your work makes porting them to VkFFT easier. They can copy your code, much like I'm stripping out OpenCL calls and replacing them with Metal (how I discovered the SIMD width issue).

**Comment by craabreu** [comment]
I implemented VkFFT for CUDA (and also OpenCL) in [this plugin](https://github.com/craabreu/openmm-nonbonded-slicing/tree/main/platforms/cuda/include/internal). In my tests, cuFFT was slightly faster than VkFFT, but this might be due to the GPU I used (GeForce MX150).

**Comment by craabreu** [comment]
BTW, an idea to improve LJPME efficiency: if the electrostatic and dispersion grids are equally sized (or enforced to be), it is possible to use batched FFT to perform both transforms simultaneously, which is way faster than doing them in sequence. This feature is available in both cuFFT ([cufftPlanMany](https://docs.nvidia.com/cuda/cufft/#fourier-transform-setup)) and vkFFT (page 53 of [this manual](https://raw.githubusercontent.com/DTolm/VkFFT/master/documentation/VkFFT_API_guide.pdf)).
