### ISSUE TITLE
Add support for writing atom subsets to reporters?

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#3925]
It would be useful to enable the [OpenMM `Simulation` reporters](http://docs.openmm.org/latest/api-python/app.html#reporting-output) that output PDB, PDBx, or DCD trajectories to write only atom subsets. Often, in explicit solvent simulations, only the positions of a subset of atoms (such as the solute) are of interest.

**Comment by peastman** [comment]
What should the API for this look like?  Presumably you would specify the subset when you create the reporter.  A list of particle indices?  Or Atom objects?

**Comment by jchodera** [comment]
I propose we adopt the [same API as MDTraj reporters that support this](https://www.mdtraj.org/1.9.8.dev0/api/generated/mdtraj.reporters.DCDReporter.html#mdtraj.reporters.DCDReporter), and include an optional `atomSubset` keyword argument that takes an array-like object specifying the zero-indexed atom index subset to write, defaulting to `None`.

**Comment by peastman** [comment]
This was implemented in #3931.

**Comment by jgreener64** [comment]
Are there any plans to allow this for `DCDReporter`? I might be able to have a go at implementing it.

**Comment by peastman** [comment]
Sure, go ahead!

**Comment by sef43** [comment]
Worth noting that the MDTraj DCD reporter does have this feature: https://www.mdtraj.org/1.9.8.dev0/api/generated/mdtraj.reporters.DCDReporter.html#mdtraj.reporters.DCDReporter

**Comment by jgreener64** [comment]
> Worth noting that the MDTraj DCD reporter does have this feature

Thanks for pointing that out. It doesn't seem to have the ability to append though, which would be useful in my case (https://github.com/mdtraj/mdtraj/issues/441).
