### ISSUE TITLE
Multiple GPU integration problem with Openmm

### ISSUE THREAD

**Issue by rijuaxt** [openmm/openmm#3927]
Hello,

I have recently installed two GPUs on my PC. While I was running MD simulation through Open-MM, I saw only one GPU is running while the other one is not working. I found that I didn't set GPU indexing in my Python Script. I don't know how to set device/GPU indexing for Openmm. Can anybody help me ?  

steps = 25000000
equilibrationSteps = 5000 
platform = Platform.getPlatformByName('CUDA')
platformProperties = {'Precision': 'single'}
dcdReporter = DCDReporter('trajectory.dcd', 1000)

**Comment by peastman** [comment]
To specify which GPU to run on, add `'DeviceIndex':'0'` to `platformProperties`.  The value is the index of the device to use.  If you want to parallelize the simulation across both GPUs, give it a comma separated list of indices: `'DeviceIndex':'0,1'`.

The scaling with number of GPUs is less than linear.  Using two GPUs will generally be faster than using only one, but not twice as fast.  You'll usually get more speedup when simulating large systems than small ones.  Depending on your application, it might be more efficient to just run a separate simulation on each one.

**Comment by rijuaxt** [comment]
Hello I have found another problem today. I was trying to simulate a system having ~94 K atoms on/across four Nvidia RTX 6000 GPUs with mixed precision mode. 

I am using Openmm 8.0 for simulation work. It shows that simulation speed is super slow on four GPUs than two GPUs, while it should be more faster on four GPUs.  I am not expecting simulation speed times four rather expecting some better performance than Two GPUs could do. 

Can you help me figuring out this problem?

**Comment by rijuaxt** [comment]
#Toplogy 

nvidia-smi topo -m
	GPU0	GPU1	GPU2	GPU3	CPU Affinity	NUMA Affinity
GPU0	 X 	NV4	SYS	SYS	0-15,32-47	0
GPU1	NV4	 X 	SYS	SYS	0-15,32-47	0
GPU2	SYS	SYS	 X 	NV4	16-31,48-63	1
GPU3	SYS	SYS	NV4	 X 	16-31,48-63	1

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks


## lscpu

-bash-4.2$ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                64
On-line CPU(s) list:   0-63
Thread(s) per core:    2
Core(s) per socket:    16
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) Gold 6226R CPU @ 2.90GHz
Stepping:              7
CPU MHz:               1199.896
CPU max MHz:           3900.0000
CPU min MHz:           1200.0000
BogoMIPS:              5800.00
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              22528K
NUMA node0 CPU(s):     0-15,32-47
NUMA node1 CPU(s):     16-31,48-63
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb cat_l3 cdp_l3 invpcid_single intel_ppin ssbd mba rsb_ctxsw ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku ospke avx512_vnni md_clear spec_ctrl intel_stibp flush_l1d arch_capabilities

**Comment by peastman** [comment]
Using more GPUs won't necessarily speed it up.  It depends on many factors: the size of the system you're simulating (larger systems parallelize better), the speed of the connections between the GPUs (NVLink is a lot faster than PCIe), the speed of the individual cards (the faster they are, the greater the relative cost of communication), and the specific forces in your system.

In this case, you're simulating a not very large system on Quadro cards that are individually very fast and don't support NVLink.  Parallelizing across multiple GPUs won't work very well in that case.

For comparison, see the cellulose and STMV benchmarks at https://openmm.org/benchmarks.  It shows the effect of parallelizing across up to four A100s connected by NVLink when simulating a much larger system (400,000 or 1 million atoms).

**Comment by teshort** [comment]
Regarding the above on setting device index for the platform, I'm running replica exchange and am looking to assign each replica to its own gpu/numa device.

The two options I'm considering are:

1) Set the platform device index to the rank of that mpi process (where n processes = n replicas) and have the processes be distributed amongst the gpus.

e.g. with 4 replicas:

proc 1 : platformProperty['DeviceIndex'] = 1
proc 2 : platformProperty['DeviceIndex'] = 2
...

2) Set the platform device index to a comma separated list of indices (equal to the number of gpus) and allow openmm to parallelise across those devices.

e.g. with 4 replicas:

platformProperty['DeviceIndex'] = '0,1,2,3' for all processes.

Do you know if either of these methods is preferable/faster/etc or if they're essentially doing the same thing in the setups I have described ? Any information on this is greatly appreciated. Thanks!

**Comment by peastman** [comment]
Having each replica run entirely on a single GPU, with different replicas on different GPUs, will probably be much more efficient than splitting every replica across all GPUs.  It involves a lot less communication.
