### ISSUE TITLE
Too high temperature for unstable configuration

### ISSUE THREAD

**Issue by smlee99** [openmm/openmm#3932]
Hi OpenMM Devs.
This is a bit funny question and I actually solved the below issue but there was something that I've not fully understood. I had an initial configuration with high energy. Now I equilibrated this structure but at first stage, I though I could handle this problem by using an integrator with a very small timestep (~0.001 fs). I know this is generally not recommended and might cause unphysical situation (actually it did!) but just for a test, I ran a simulation at 300K and found the energy log file as below.
```
#"Step","Time (ps)","Potential Energy (kJ/mole)","Kinetic Energy (kJ/mole)","Total Energy (kJ/mole)","Temperature (K)","Density (g/mL)","Speed (ns/day)"
0,0.0,4865505.057671552,5.50341518241297,4865510.561086734,0.08258889572234096,0.09681811190345123,0
5000,0.005000000000000339,1990608.6729129674,2849452.881452401,4840061.554365369,42761.29623002832,0.10889112690408016,0.297
10000,0.009999999999999105,1924753.0256597926,2886511.519380782,4811264.545040574,43317.42944586487,0.10930047123136899,0.286
15000,0.014999999999995432,1791898.6877703313,2992119.657433302,4784018.345203633,44902.274348884894,0.10962556032129686,0.282
20000,0.019999999999999348,1772115.1627494157,2982554.463479946,4754669.626229362,44758.730970856246,0.11022205379299974,0.28
25000,0.02500000000000435,1756940.2362877042,2968151.2197227944,4725091.456010498,44542.58373186104,0.1100765979844287,0.278
30000,0.03000000000000935,1730142.1094430247,2965631.854116132,4695773.963559156,44504.77600402688,0.1110423020131982,0.277
...
49965000,49.96499996586715,-42481.8773992254,19637.236883672926,-22844.640515552474,294.6929598267173,0.6110909204087808,0.328
49970000,49.96999996585453,-42651.156822017576,19792.160136332837,-22858.99668568474,297.0178689849039,0.6108813507635139,0.328
49975000,49.9749999658419,-42742.3403932636,19846.480183345822,-22895.860209917777,297.83304148228785,0.6110432773536205,0.328
49980000,49.97999996582928,-42582.09773147319,19717.642963399136,-22864.454768074058,295.89960135999127,0.6112477929538255,0.328
49985000,49.984999965816655,-42347.99669073384,19453.466293683912,-22894.530397049926,291.9351431637227,0.6122867367341394,0.328
49990000,49.98999996580403,-42673.37601910974,19783.975290269063,-22889.400728840676,296.8950402729753,0.610459396357166,0.328
49995000,49.99499996579141,-42664.2187719042,19826.4397435905,-22837.779028313696,297.5322977196745,0.6115048851017048,0.328
50000000,49.999999965778784,-42527.19438850664,19689.62108350644,-22837.5733050002,295.47908136655207,0.6120142062955923,0.328
```
Again, I knew this is generally not recommended and I'll never use such ad hoc again but it was a bit interesting for me to observe the initial temperature near at ~40000 K. Can I ask why this happened? Below is the integrator I've used for the above simulation.
```
freq = 1/picosecond
eqtimestep = 0.001*0.001*picoseconds
integ_eq = LangevinIntegrator(temperature, 1/picosecond, eqtimestep)
```

**Comment by sef43** [comment]
The temperature is just a measure of the average speed of the atoms. An initial high energy configuration will produce large forces, which in turn create large velocities, which produces the large temperatures. 

The `LangevinIntegrator` does [Langevin dynamics](https://en.wikipedia.org/wiki/Langevin_dynamics). This has a friction term and a noise term which control the temperature. The friction term coupled with the very small timestep you are using means that the simulation is able to remain stable and equilibrate to 300K.

**Comment by smlee99** [comment]
@sef43 Thanks for your clear answer! Why didn't I think of that.. Let me close this issue.
