### ISSUE TITLE
OpenCL reduceEnergy low utilization

### ISSUE THREAD

**Issue by bdenhollander** [openmm/openmm#3933]
The code look like it's doing partial sums in blocks of 512 and then accumulating those sums to a single value. Could the second loop be done more efficiently using `atomic_add` to a global?
https://github.com/openmm/openmm/blob/434d7afb1266da6d0b5fcd190593c470a0954c51/platforms/opencl/src/kernels/utilities.cl#L108-L121

reduceForces vs. reduceEnergy
![image](https://user-images.githubusercontent.com/44237618/215003365-5a78d374-4238-45c7-8cd3-40c58d6da921.png)
![image](https://user-images.githubusercontent.com/44237618/215003567-e7794aa7-76dd-4223-b53e-ba2f753a21dc.png)
![image](https://user-images.githubusercontent.com/44237618/215004126-1b1054ab-63d4-439c-947f-8edf93a74986.png) ![image](https://user-images.githubusercontent.com/44237618/215003500-b81964dd-230f-4ee0-83de-54bf4f35afb6.png)

4038 atom system from FAH project [13415](https://github.com/openmm/openmm/files/10515181/13415.zip).

**Comment by peastman** [comment]
Try #3902.  It makes this more efficient.

**Comment by bdenhollander** [comment]
That PR improves performance by about 14x on `reduceEnergy`, linear scaling with the number of wavefronts 112/8=14. Well done! The `for` loop does shift some load to the CPU but overall performance is up by 3.6% from 109 ns/day to 113 ns/day on RX 6600.

![image](https://user-images.githubusercontent.com/44237618/215200778-17f556ee-f0ea-4083-97f9-11bf10e67923.png)

**Comment by peastman** [comment]
I'll merge it as soon as we release 8.0, which should be any day now.
