### ISSUE TITLE
Accelerate use cases with many small simulations

### ISSUE THREAD

**Issue by philipturner** [openmm/openmm#3942]
Proposal based on discussion from https://github.com/openmm/openmm/issues/3937#issuecomment-1416636408:

Objective: Make OpenMM more competitive in workloads suited for the CPU, such as small simulations in the 1000-10000 atom range. These traditionally run better with multiple small, independent tasks utilizing weak, independent CPU cores. Also to accelerate DL or GA where the loss function comes from the result of an OpenMM simulation.

---

The previous thread discussed past attempts to decrease CPU-GPU communication overhead, including offloading much real-time logic onto the GPU. Potential pathways include buffering up GPU commands, to gather enough data to optimize a DAG and then submit. This would not work when the user calls short functions like `calcForcesAndEnergy` and expects to immediately see the return value. It could work with lazily materializing the return value. Also, long-running calls such as `integrator->step()` would surely benefit. Optimizing exclusively that function would require less effort. Alternatively, we scrap this approach and just reduce latency where possible (macOS M1 GPU and certain AMD setups).

Another unrelated improvement is, provide abilities to run several small simulations concurrently on one GPU. An entire Apple GPU only runs commands from 2 independent queues simultaneously. But, it can run 3-4 commands/core (96 per M1 Max) from the same queue. Such concurrency can only be harnessed through low-level concurrent dispatching API like Metal [concurrent commands](https://developer.apple.com/documentation/metal/mtldispatchtype/concurrent). With Metal, using concurrent instead of serial invokes significant encoding overhead, so use concurrent execution judiciously.

Another implementation strategy, we index into arrays of resources within the GPU kernels, tracking similar replica simulations. Each simulation may differ slightly in number of atoms, but has almost identical performance patterns. This incurs negligible encoding overhead just like batched FFTs from VkFFT. It mirrors the ML optimization of running training batches of ~32, turning a bandwidth-intensive SGEMV into a compute-intensive SGEMM. The new capability would be integrated into Folding@Home whenever the number of compute tasks vastly exceeds to number of processors.

**Comment by peastman** [comment]
This is closely related to https://github.com/openmm/openmm/issues/2535

**Comment by philipturner** [comment]
Closing as discussion should occur in the other thread.
