### ISSUE TITLE
confused on the AttributeError

### ISSUE THREAD

**Issue by wayuer19** [openmm/openmm#3944]
Hi, I'm test a NPT system using OpenMM 7.7 on ubuntu 20.04. Here is the simplified version of my running script:

`from openmm.app import *
from openmm import *
import numpy as np

psf_file = argv[2]
pdb_file = argv[1]
top_inp = 'top-hyres2.inp'
param_inp = 'param-hyres2.inp'
IONC = 0.15
eps_eff = 20.0
dt = 0.004*unit.picoseconds
total_step = 1
T = 300*unit.kelvin
gpu_id = argv[3]

L = 50.0*unit.nanometer
a = Vec3(L, 0.0, 0.0)
b = Vec3(0.0, L, 0.0)
c = Vec3(0.0, 0.0, L)

pdb = PDBFile(pdb_file)
xyz = np.array(pdb.positions/unit.nanometer)
xyz[:,0] -= np.amin(xyz[:,0])
xyz[:,1] -= np.amin(xyz[:,1])
xyz[:,2] -= np.amin(xyz[:,2])
pdb.positions = xyz*unit.nanometer

psf = CharmmPsfFile(psf_file)
psf.setBox(L, L, L)
params = CharmmParameterSet(top_inp, param_inp)
system = psf.createSystem(params, nonbondedMethod=CutoffPeriodic, constraints=HBonds)
system.setDefaultPeriodicBoxVectors(a, b, c)

for force in system.getForces():
    if force.getName() == "NonbondedForce":
        nbforce = force
print('get the NonBondedForce:', nbforce.getName())

CNBForce = CustomNonbondedForce(formula)
Force14 = CustomBondForce(formula)
Hforce = CustomHbondForce(formula)

system.removeForce(nbforce.getForceGroup())

system.addForce(MonteCarloBarostat(1*unit.atmosphere, T, 25))
integrator = LangevinMiddleIntegrator(T, 1/unit.picosecond, dt)
plat = Platform.getPlatformByName('CUDA')
prop = {'Precision': 'mixed', 'DeviceIndex': gpu_id}
simulation = Simulation(psf, system, integrator, plat, prop)
simulation.context.setPositions(pdb.positions)
simulation.context.setVelocitiesToTemperature(T)
simulation.minimizeEnergy()

simulation.reporters.append(PDBReporter('system.pdb', total_step))
simulation.reporters.append(DCDReporter('system.dcd', 10000))
simulation.reporters.append(DCDReporter('system_fine.dcd', 1000))
simulation.reporters.append(StateDataReporter('system.log', 10000, step=True, progress=True, totalSteps=total_step))

print('# production simulation')
simulation.step(total_step)

simulation.saveCheckpoint('system.chk')`

I got an error said:

![image](https://user-images.githubusercontent.com/24451788/216852225-3755685a-47e8-4571-aca7-498b5c104e9f.png)

I'm confused on where could this error come from. Any suggestions? Thank you so much!

**Comment by peastman** [comment]
The first argument to Simulation should be a Topology object, not a CharmmPsfFile.  Pass `psf.topology` instead.
