### ISSUE TITLE
Restarting simulation does delete my previous dcd but it runs from checkpoint. 

### ISSUE THREAD

**Issue by rijuaxt** [openmm/openmm#3946]
It seems I can restart simulation but can't append/merge previous trajectory info. Any idea? 

#!/usr/bin/env python
# coding: utf-8

#load modules

from openmm import *
from openmm.app import *
from openmm.unit import *

# Input Files

pdb = PDBFile('protein-processed.pdb')
forcefield = ForceField('amber14-all.xml', 'amber14/tip3pfb.xml')

#Input Parameters 

nonbondedMethod = PME   
nonbondedCutoff = 1*nanometers
ewaldErrorTolerance = 0.0005
constraints = HBonds 
rigidWater = True
constraintTolerance = 0.00001

dt = 0.002*picoseconds
temperature = 310*kelvin
friction = 1/picosecond
pressure = 1*atmospheres
barostatInterval = 25

steps = 25000000
equilibrationSteps = 5000
platform = Platform.getPlatformByName('CUDA')
platformProperties = {'Precision': 'mixed', 'DeviceIndex':'0,1'}

# Topology Definition 

topology = pdb.topology
positions = pdb.positions
system = forcefield.createSystem(topology, nonbondedMethod=nonbondedMethod, nonbondedCutoff=nonbondedCutoff,
    constraints=constraints, rigidWater=rigidWater, ewaldErrorTolerance=ewaldErrorTolerance)
system.addForce(MonteCarloBarostat(pressure, temperature, barostatInterval))
integrator = LangevinMiddleIntegrator(temperature, friction, dt)
integrator.setConstraintTolerance(constraintTolerance)
simulation = Simulation(topology, system, integrator, platform, platformProperties)
with open('trajectory.chk', 'rb') as f:
   simulation.context.loadCheckpoint(f.read())

dataReporter = StateDataReporter('trajectpry.csv', 100000, totalSteps=steps,
    step=True, time=True, speed=True, progress=True, elapsedTime=True, remainingTime=True, potentialEnergy=True, kineticEnergy=True, totalEnergy=True, temperature=True, volume=True, density=True, separator='\t')

checkpointReporter = CheckpointReporter('trajectory.chk' , 100000)
dcdReporter = DCDReporter('trajectory.dcd', 100000)

print('restarting simulation...')
simulation.reporters.append(dcdReporter)  
simulation.reporters.append(dataReporter)
simulation.reporters.append(checkpointReporter)
simulation.currentStep = 0
simulation.step(steps)

**Comment by peastman** [comment]
Add the argument `append=True` to the DCDReporter.  See [the API docs](http://docs.openmm.org/latest/api-python/generated/openmm.app.dcdreporter.DCDReporter.html).

**Comment by peastman** [comment]
Closing this since the question was answered.
