### ISSUE TITLE
Blow up encountered when loading from amber topology

### ISSUE THREAD

**Issue by xiki-tempula** [openmm/openmm#3948]
I have generated the amber topology for a small molecule (Smiles: `C([C@H]([C@H]([C@@H]([C@@H](CO)O)O)O)O)O`).
The system is just a small molecule running in vacuum.
This topology and coordinate runs fine in amber but if I load it into openMM and run it, it blows up in less than 200 steps.

[Archive.zip](https://github.com/openmm/openmm/files/10674156/Archive.zip)

**Comment by sef43** [comment]
What integration settings do you use when running it with Amber ?
If I change the timestep in your script to  0.001*picoseconds then it appears to give stable dynamics

**Comment by xiki-tempula** [comment]
The same 2fs with HBond shake. I think the H bond constrain should make 2fs stable?

**Comment by sef43** [comment]
In general the constraints make 2fs stable when the H bond vibrations are the highest frequency movement in the simulation. 

However, for this specific molecule and forcefield there seems to be high frequency oscillations of the hydroxy groups due to interactions with the neighbouring H and O atoms e.g. between H atom with position index 25 and O atom with position index 10. Perhaps you can check the various non-bonded parameters have been set as you are expecting them to be:
```
forces = { force.__class__.__name__ : force for force in system.getForces() }
nbforce = forces['NonbondedForce']
for i in range(nbforce.getNumParticles()):
    print(nbforce.getParticleParameters(i))
```
I am not familiar with Amber but it could have other settings, potentially the thermostat, than can keep the simulation appearing stable with a 2fs timestep, at least for this system in OpenMM a 1fs timestep seems to be the appropriate choice

**Comment by xiki-tempula** [comment]
I have created the amber topology with the same SDF file that I use for openff, so that each atom would have the same order.
```
import os

import numpy as np
from openeye import oechem
from openff.toolkit.topology import Molecule as off_Molecule, Topology as off_Topology
from openff.toolkit.typing.engines.smirnoff import ForceField as off_ForceField
from openmm import *
from openmm.app import *
from openmm.unit import *

# Load the topology and coordinate files.
prmtop = AmberPrmtopFile('openmm.prm7')
inpcrd = AmberInpcrdFile('openmm.rst7')

# Initialise the molecular system.
system = prmtop.createSystem(nonbondedMethod=NoCutoff,
                             constraints=HBonds)

forces = { force.__class__.__name__ : force for force in system.getForces() }
nbforce = forces['NonbondedForce']
nbforce_list_1 = []
for i in range(nbforce.getNumParticles()):
    nbforce_list_1.append(nbforce.getParticleParameters(i))

ifs = oechem.oemolistream()
if ifs.open('foo.sdf'):
    for mol in ifs.GetOEGraphMols():
        oemol = mol

        molecule = off_Molecule.from_openeye(oemol)
        
        topology = off_Topology.from_molecules(molecule)
        forcefield = off_ForceField("openff_unconstrained-2.0.0.offxml")
        
        # Create an OpenMM system representing the molecule with SMIRNOFF-applied parameters
        system = forcefield.create_openmm_system(topology)
        forces = { force.__class__.__name__ : force for force in system.getForces() }
        nbforce = forces['NonbondedForce']
        nbforce_list_2 = []
        for i in range(nbforce.getNumParticles()):
            nbforce_list_2.append(nbforce.getParticleParameters(i))

for nb1, nb2 in zip(nbforce_list_1, nbforce_list_2):
    assert np.isclose(nb1[0]._value, nb2[0]._value)
    assert np.isclose(nb1[1]._value, nb2[1]._value)
    assert np.isclose(nb1[2]._value, nb2[2]._value)
```
 So here I check the charge and nb paramters and they are exactly the same.

**Comment by sef43** [comment]
you could also check the exceptions: http://docs.openmm.org/latest/api-python/generated/openmm.openmm.NonbondedForce.html#openmm.openmm.NonbondedForce.getExceptionParameters

**Comment by sef43** [comment]
it looks like the 1-4 interactions between the two O atoms with indexes 10 and 11 are being set to zero. While the 1-4 interactions between other similar O atoms, e.g. 6 and 7 is not being set to zero, if you set the ExceptionParameters for (10,11) to the same as (6,7) then I can run with the 2fs timestep without it going unstable:
```
from openmm import *
from openmm.app import *
from openmm.unit import *
from sys import stdout

# Load the topology and coordinate files.
prmtop = AmberPrmtopFile('openmm.parm7')
inpcrd = AmberInpcrdFile('openmm.rst7')

# Initialise the molecular system.
system = prmtop.createSystem(nonbondedMethod=NoCutoff,
                             constraints=HBonds)



forces = { force.__class__.__name__ : force for force in system.getForces() }
nbforce = forces['NonbondedForce']

exception_dict = {}
for i in range(nbforce.getNumExceptions()):
    exception = nbforce.getExceptionParameters(i)
    exception_dict[(exception[0], exception[1])] = exception

print("exception parameters between O index [6] and O index [7]:")
print(exception_dict[(6,7)])
print("exception parameters between O index [10] and O index [11]:")
print(exception_dict[(10,11)])

# set to the correct values, copied from (6,7)
nbforce.addException(10,11,0.30083673055995863, 0.2997159987248637, 0.43821862980778686,replace=True)

```
```
exception parameters between O index [6] and O index [7]:
[6, 7, Quantity(value=0.3008367330239653, unit=elementary charge**2), Quantity(value=0.2997159987512761, unit=nanometer), Quantity(value=0.43821862972836056, unit=kilojoule/mole)]
exception parameters between O index [10] and O index [11]:
[10, 11, Quantity(value=0.0, unit=elementary charge**2), Quantity(value=0.1, unit=nanometer), Quantity(value=0.0, unit=kilojoule/mole)]
```

I am not sure why the Exceptions are getting set to this value.

**Comment by xiki-tempula** [comment]
@sef43 Thank you very much.
