### ISSUE TITLE
Modify standard forces along MD

### ISSUE THREAD

**Issue by LeonardoBarneschi** [openmm/openmm#3952]
Dear OpenMM developers,
I would like to use openmm as the MD driver using forces calculated ab-initio or with a machine-learned potential. I was wondering if, at each time step, is there some simple way, using the python API, to modify the N×3 "standard" forces vector possibly without resorting to the CustomForce construct.  I mean, supposing I have for instance a text file with the gradient I want to use, how can I have openmm read it?  
Thank you in advance,
Leo

**Comment by LeonardoBarneschi** [comment]
Thank you for pointing out this thread. 
I guess I will try to figure out a way to do that using CustomExternalForce. On a more general level, as you suggest, since I need to perform this action on forces at every time step, is that a particular syntax or an example that shows how to run a simulation using a for/while loop?

**Comment by sef43** [comment]
it would involve something like this:
```
# placeholder for externally calculated forces
my_forces=np.random.normal(size=(system.getNumParticles(),3))

# setup external force
external = CustomExternalForce('-fx*x-fy*y-fz*z')
system.addForce(external)
external.addPerParticleParameter('fx')
external.addPerParticleParameter('fy')
external.addPerParticleParameter('fz')
for i in range(system.getNumParticles()):
    external.addParticle(i, my_forces[i]*kilojoules_per_mole/nanometer)

# simulate for nsteps
nsteps=1000
for t in range(nsteps):
    
    # get new forces
    my_forces=np.random.normal(size=(system.getNumParticles(),3))

    # assign them to each particle
    for i in range(system.getNumParticles()):
        

        external.setParticleParameters(i,i, my_forces[i]*kilojoules_per_mole/nanometer)


    # update the context
    external.updateParametersInContext(simulation.context)
    
    # take a step
    simulation.step(1)
```

**Comment by LeonardoBarneschi** [comment]
Thank you very much! I really appreciate it!

**Comment by LeonardoBarneschi** [comment]
Dear Stephan, 
sorry for re-opening the thread. Taking inspiration from your suggestion I created the following snippet of code. I am trying to bias the force at every time step by adding a dummy "1". I can see that this external perturbation, via updateParametersInContext(), works well at the very first time step, but not for the following. Can you spot something wrong? 
Thanks again 


`# Run MD
i = 0
steps = 10000

external = CustomExternalForce('-kx*x-ky*y-kz*z')
system.addForce(external)
fxidx = force.addPerParticleParameter("kx")
fyidx = force.addPerParticleParameter("ky")
fzidx = force.addPerParticleParameter("kz")
for n in range(system.getNumParticles()):
    external.addParticle(n, [0, 0, 0] * kilojoules_per_mole/nanometer)

for i in range(steps):

    state = simulation.context.getState(getEnergy=True,getPositions=True,getForces=True,getVelocities=True)
    old_forces = state.getForces(asNumpy=True)
    position = state.getPositions()
    print("Standard Forces %d" % i)
    print(old_forces)

    for n in range(system.getNumParticles()):
        external.setParticleParameters(n, n, [1, 1, 1] * kilojoules_per_mole/nanometer)
    external.updateParametersInContext(simulation.context)

    state = simulation.context.getState(getEnergy=True,getPositions=True,getForces=True,getVelocities=True)
    new_forces = state.getForces(asNumpy=True)
    print("Updated Forces %d" % i)
    print(new_forces)

    simulation.step(1)
`

**Comment by sef43** [comment]
You will need to provide a fully runnable script and input (i,e. including the setting up the system/simulation part) for it to be debuggable.

Note that this script will not be adding [1,1,1] to the current force, but setting the current force on each particle to [1,1,1]

**Comment by peastman** [comment]
What is the additional step you tried to add?  In what way do you want to modify the forces?

**Comment by sef43** [comment]
As @peastman has said some more specific information about your use case would be helpful

the general way to have different forces acting at different steps of the integrator would be to use force groups, there is an [example in the docs](http://docs.openmm.org/latest/api-python/generated/openmm.openmm.CustomIntegrator.html#openmm.openmm.CustomIntegrator:~:text=.addConstrainVelocities()%3B-,CustomIntegrator,-can%20be%20used)

in Python syntax you could do something like this:
```
for force in system.getForces():
    if force.__class__.__name__== "CustomExternalForce":
        force.setForceGroup(1)


# setup custom integrator
integrator = CustomIntegrator(0.001*picoseconds)
integrator.addPerDofVariable("x1", 0);
integrator.addUpdateContextState();
# use just f0 which is all other forces, excluding custom external one
integrator.addComputePerDof("v", "v+0.5*dt*f0/m");
integrator.addComputePerDof("x", "x+dt*v");
integrator.addComputePerDof("x1", "x");
integrator.addConstrainPositions();
# use f which is all forces, including the custom external one
integrator.addComputePerDof("v", "v+0.5*dt*f/m+(x-x1)/dt");
integrator.addConstrainVelocities();
```

**Comment by LeonardoBarneschi** [comment]
Hello again, 
Here I attach a test that I have tried to run based on @sef43 suggestions. There are two python scripts; vv.py integrates the classical MD with a Verlet Integrator. cmpnd.py uses a Compound Integrator where I have split the velocity verlet algorithm in two parts because I need to act on forces in between these two parts. 

You can find the results of the MD runs in the corresponding ".csv" files. You will notice that the potential energy obtained with the Compound Integrator is roughly twice as big as the one obtained with the standard Verlet Integrator. 
Attached you can also find topologies and geometries to reproduce the behaviour I see in my data.
I guess I am missing some small detail on how to correctly setup the Compound Integrator to achieve what I want. 

Can you please help me?  

Leo 

[compound_integrator.tgz](https://github.com/openmm/openmm/files/10744092/compound_integrator.tgz)

**Comment by peastman** [comment]
It still isn't clear to me what you're trying to do, but this definitely isn't the right way to do it.

Here's how to think about integration.  At any moment, the state of the system is a point in a very high dimensional space.  It's defined by all the positions and velocities of all the particles.  If there are N particles, it's a 6N dimensional space.  When you specify all the positions and velocities, you specify a point in that space.

Every point has an energy.  The energy changes continuously as you move through the space.  If you consider all the points with exactly the same energy, they form a continuous surface.  Verlet integration is designed to move along that surface.  Its steps always move parallel to the surface, such that the energy doesn't change.

Your integrator doesn't do that.  It first takes a step ignoring the custom external force.  That will preserve the energy of all other forces excluding that one, but it will not preserve the total energy including it.  Then you take a step based only on the custom external force.  That will preserve the energy of that one force, but again change the total energy of the whole system.  The result is an algorithm that doesn't conserve energy.

Can you explain exactly what you're trying to accomplish?

**Comment by peastman** [comment]
Closing this due to lack of response.
