### ISSUE TITLE
System hangs during Context creation on OpenCL

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#3955]
The following minimal test case shows an example of a `System` that is able to create a `Context` without problem for the `CPU` and `Reference` platforms, but hangs for `OpenCL`:
[minimal.zip](https://github.com/openmm/openmm/files/10691415/minimal.zip)
It doesn't appear to be just slightly slow kernel compilation---either it is abnormally slow or something is hanging.

The system was set up by @apayne97 using reasonably standard inputs (`amber14-all.xml`, `tip3bfb.xml`, PME, rigid waters, HMR, 1e-6 PME tolerance), so it's not clear why it would fail to create an OpenCL system.

We (@ijpulidos and I) have tested this with both OpenMM 7.7 and 8.0 on linux with NVIDIA GPUs:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.43.04    Driver Version: 515.43.04    CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:02:00.0 Off |                  N/A |
| 28%   40C    P0    59W / 250W |      1MiB / 11264MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by peastman** [comment]
The Ewald error tolerance is set to a tiny value, 1e-6.  As a result, it needs to create a huge grid, 392 on each side.  It's getting stuck in a loop trying to compile the FFT kernels.  The OpenCLFFT class requires that each 1D FFT be small enough to do entirely in local memory with one thread per element.  It tries to build a kernel, then finds the kernel it just built exceeds the resources of the GPU.  It tries to address that by reducing the number of threads, but it can't reduce the number below the grid width, and gets stuck in an infinite loop.

Here are a couple of solutions.

- This doesn't apply to the current master branch, because we've replaced OpenCLFFT with VkFFT.  It shouldn't have this problem.
- You almost certainly want a larger value for the Ewald error tolerance.  Unless you're doing all calculations in double precision, it's probably well below the point where making the grid larger actually increases the error rather than decreasing it.

**Comment by apayne97** [comment]
I can give credit to @kendallrlemons for setting the system up! He was exploring openmm-setup. I guess normally we would just let the Ewald Error Tolerance be the default, which is lower? I can't find the documentation for what the defaults would be.

**Comment by jchodera** [comment]
> The Ewald error tolerance is set to a tiny value, 1e-6. As a result, it needs to create a huge grid, 392 on each side. It's getting stuck in a loop trying to compile the FFT kernels.

Thanks for tracking this down so quickly! 

Would it be useful to raise some kind of exception in this case if OpenMM is unable to handle the provided (legal) argument value?

**Comment by jchodera** [comment]
@peastman: I don't think we've actively maintained [openmm-setup](https://github.com/openmm/openmm-setup) for some time. Is this something we want to continue to maintain? Perhaps it's something @sef43 could help out with, if so?

**Comment by peastman** [comment]
> Would it be useful to raise some kind of exception in this case if OpenMM is unable to handle the provided (legal) argument value?

Like I said, this doesn't apply to the main branch.  That class has been replaced.

> I don't think we've actively maintained openmm-setup for some time.

Yes I have!

**Comment by peastman** [comment]
> I can't find the documentation for what the defaults would be.

The default value is 5e-4.

**Comment by jchodera** [comment]
Just as a heads up: 5e-4 is an extremely loose tolerance, and changing it to 1e-4 or 1e-5 can have a big impact on the energies compared to kT. It's potentially reasonably safe for plain dynamics, but we have to use tighter tolerances for free energy calculations.

**Comment by peastman** [comment]
Make sure you understand what the tolerance means: it's the relative error in the *total force* on an atom, including both direct and reciprocal space and summing over all interactions.  Some other codes have Ewald tolerances that mean totally different things.  For example, in Gromacs it's the maximum error in the direct space interaction between a single pair of atoms.  5e-4 is actually pretty good accuracy.  1e-5 is usually higher accuracy than it's possible to get in single precision.

**Comment by jchodera** [comment]
@peastman : I don't know how to turn a relative error in the total force on an atom into an energy quantity I would care about, or an energy quantity that would significantly impact the Boltzmann weight of individual conformations, but I do know how to run a simulation of a system I care about (Src kinase in explicit solvent) and compute the standard deviation of the potential energy deviation between tight PME tolerance that computes a potential close to what the force field intended (1e-6) and the PME tolerance that OpenMM uses by default (5e-4). Here's a table of the potential energy deviations in kT as a function of PME tolerance:
```
ewaldErrorTolerance 1.000e-06 :    0.000
ewaldErrorTolerance 5.000e-06 :    0.020
ewaldErrorTolerance 1.000e-05 :    0.035
ewaldErrorTolerance 5.000e-05 :    0.200
ewaldErrorTolerance 1.000e-04 :    0.425
ewaldErrorTolerance 5.000e-04 :    2.422
```
With a standard deviation of 2.4 kT, this means there is a significant chance (32%) that we have deviations > 2.4 kT, which is a probability density error of > exp(2.4) ~ 11x, which is a pretty major error.

This, of course, assumes that (1) the forces are truly the negative gradient of the potential without significant error, (2) that the integrator samples the probability density induced by the potential faithfully, but that (3) the potential is slightly wrong. I'm taking (1) as given, we know BAOAB does well with (2), and we're seeing that (3) is worrisome for 5e-4 here.

As a result, we usually use 1e-4 or smaller, though this has significant impact on performance. Some of this can be mitigated by increasing the cutoff to better balance the work between reciprocal and direct space.

The errors here are of course size-dependent: For smaller systems, you can use a looser PME tolerance and achieve the same stddev in error. Because of the significant impact on performance, this could potentially be a way to squeeze more performance out---if we had an idea of the absolute stddev of deviations we were willing to accept (e.g. 0.5 kT).

**Comment by peastman** [comment]
Here is how I analyze it.  I first calculate the energy using double precision, a tiny error tolerance, and a long cutoff (otherwise it runs out of memory trying to create the grid).  I take that as the "true" energy.  Then I repeat the calculation in mixed precision for various tolerances and see how close it gets.

Here is the code.

```python
from openmm import *
from openmm.app import *

ff = ForceField('amber14/protein.ff14SB.xml', 'amber14/lipid17.xml', 'amber14/tip3p.xml')
pdb = PDBFile('5dfr_solv-cube_equil.pdb')
system = ff.createSystem(pdb.topology, nonbondedMethod=PME, nonbondedCutoff=1.5, ewaldErrorTolerance=1e-7, constraints=HBonds)
platform = Platform.getPlatformByName('CUDA')
integrator = VerletIntegrator(0.001)
context = Context(system, integrator, platform, {'Precision':'double'})
context.setPositions(pdb.positions)
reference = context.getState(getEnergy=True).getPotentialEnergy()
print('Reference energy:', reference)
nonbonded = [f for f in system.getForces() if isinstance(f, NonbondedForce)][0]
for tol in [5e-4, 1e-4, 5e-5, 1e-5, 5e-6, 1e-6, 5e-7, 1e-7]:
    nonbonded.setEwaldErrorTolerance(tol)
    integrator = VerletIntegrator(0.001)
    context = Context(system, integrator, platform, {'Precision':'mixed'})
    context.setPositions(pdb.positions)
    energy = context.getState(getEnergy=True).getPotentialEnergy()
    print(tol, energy, energy-reference)
```

Here is the output for DHFR.

```
Reference energy: -298170.66846523667 kJ/mol
0.0005 -298145.0781633785 kJ/mol 25.590301858144812 kJ/mol
0.0001 -298156.9889538728 kJ/mol 13.679511363850906 kJ/mol
5e-05 -298159.6914676649 kJ/mol 10.976997571764514 kJ/mol
1e-05 -298164.12882011314 kJ/mol 6.539645123528317 kJ/mol
5e-06 -298165.5092297711 kJ/mol 5.159235465573147 kJ/mol
1e-06 -298168.07258357503 kJ/mol 2.5958816616330296 kJ/mol
5e-07 -298168.92685757554 kJ/mol 1.7416076611261815 kJ/mol
1e-07 -298170.76112900744 kJ/mol -0.09266377077437937 kJ/mol
```

In this case, the accuracy steadily improves with decreasing tolerance.  Now for ApoA1, which is much larger and therefore requires a larger grid.

```
Reference energy: -1363573.6074411971 kJ/mol
0.0005 -1363580.8170274291 kJ/mol -7.209586231969297 kJ/mol
0.0001 -1363573.3530102693 kJ/mol 0.25443092780187726 kJ/mol
5e-05 -1363572.5503685484 kJ/mol 1.0570726487785578 kJ/mol
1e-05 -1363573.306753912 kJ/mol 0.30068728514015675 kJ/mol
5e-06 -1363573.6502008773 kJ/mol -0.042759680189192295 kJ/mol
1e-06 -1363574.1421321994 kJ/mol -0.5346910022199154 kJ/mol
5e-07 -1363574.0086483276 kJ/mol -0.4012071304023266 kJ/mol
1e-07 -1363574.4656374417 kJ/mol -0.8581962445750833 kJ/mol
```

In this case there's no systematic improvement beyond 1e-4.  It goes up and down, but I think that's just noise.
