### ISSUE TITLE
Decomposition of energy

### ISSUE THREAD

**Issue by UmeshRoy** [openmm/openmm#3957]
Dear Developers,
                            I have production-run data. I wish to calculate the different components (van der Waals and coulomb energies) of energy. Is it possible to get these values separately from the trajectory? Or do I need to run a different simulation where it is possible to get decomposed values at each timestep?

Thank you.

With best regards,

Umesh

**Comment by sef43** [comment]
You can get the energy components of each Force object from an existing trajectory. You will need to do two things:
1. load in the trajectory and use the positions from it to compute the potential energy - http://docs.openmm.org/latest/userguide/application/04_advanced_sim_examples.html#computing-energies

2. Get the energy components from each force group - https://openmm.github.io/openmm-cookbook/latest/notebooks/cookbook/Analyzing%20Energy%20Contributions.html

Note that the OpenMM non-bonded force contains both the Lennard Jones and Coulomb energy, they are not accumulated separately for performance reasons. You could define some CustomForces to compute the specific energy terms you need and evaluate them on each frame in the trajectory using the same method as point 2 above.

**Comment by peastman** [comment]
What force field are you using?  You mentioned polarization, which suggests you're using a polarizable force field?

**Comment by UmeshRoy** [comment]
@peastman  Yes, I'm using polarizable Amoeba forcefield 2018.

**Comment by UmeshRoy** [comment]
Yeah, you are right. I will modify my question. Can I separate energy contributions for hydrophilic-water, hydrophobic-water, and protein-water cases by defining the hydration shell?

**Comment by peastman** [comment]
Not really.  With a point charge force field that would be possible.  With AMOEBA it just isn't defined.  The interaction energy between two atoms depends on every other atom, since each one has an induced dipole moment that depends on everything around it.  It can't be decomposed into pairwise interactions.

**Comment by UmeshRoy** [comment]
Thanks. Since decomposition is not possible, I would like to do the following: 
I'm using amoeba2018 for both protein and water. Is it possible to switch off the polarization for the protein and water system for the same forcefield and simulate the system? 


Thank you

**Comment by peastman** [comment]
I suppose you could set the polarizability of every atom to 0.  But don't expect that give you meaningful results.  The force field was parametrized to reproduce experimental data and quantum chemistry calculations with polarization enabled.  If you make it non-polarizable, it will no longer come anywhere close to reproducing the training data.  You'll get much better results by using a force field that was parametrized without polarization.

**Comment by UmeshRoy** [comment]
Thanks. For meaningful results, yes, we should use the water model which was developed for a particular type of problem.

**Comment by spadavec** [comment]
Sorry for reopening this, but I'm looking to do something similar here, but not with an AMOEBA FF. 

I have a protein/ligand system that I would like to breakout the coulomb and LJ energies for ligand/protein, ligand/ligand, and ligand/solvent. After having already created the trajectory, is there some equivalent of gromacs' `rerun` capability to extract these values for the complex?

**Comment by peastman** [comment]
You're asking a couple of different question.  Reloading a trajectory and calculating energies from it is easy.  You can do something similar to http://docs.openmm.org/latest/userguide/application/04_advanced_sim_examples.html#computing-energies.  It loads PDB files from a directory, but it doesn't matter where you get the positions from.  For example, if you saved the trajectory to a DCD file, you could use MDTraj or MDAnalysis to load it in and get the positions for each frame.

Decomposing the energy is more complicated, as discussed above.  Get the contributions for different Force objects is easy.  But separating out protein-ligand, solvent-ligand, etc. is very complicated.  See https://github.com/openmm/openmm/issues/3971, which talks about some ways of doing it.
