### ISSUE TITLE
problem about getting energy by force group

### ISSUE THREAD

**Issue by udlich** [openmm/openmm#3958]
There are two forces created by charmmpsffile.createSystem(), i.e., a standard NonbondedForce named "force" and a CustomNonbondedForce named "cforce". If the potential energy of the two forces are obtained sequentially and added up , or obtained simultaneously, the results are quite inconsistent

```
from openmm.unit import *
from openmm import *
from openmm.app import *
from openmm.app import forcefield as ff

psf = CharmmPsfFile('wt.psf')
prm = CharmmParameterSet('par_all36m_prot.prm', 'toppar_water_ions.str')
system = psf.createSystem(prm, nonbondedMethod=ff.NoCutoff, constraints=ff.HBonds)
for force in system.getForces():
    if force.__class__.__name__ == 'CustomNonbondedForce':
        force.setForceGroup(31) 
        break
platform = Platform.getPlatformByName('CUDA')
crd = CharmmCrdFile('wt.crd')
integrator = LangevinIntegrator(300.0*kelvin, 1.0/picosecond, 0.001*picoseconds)
context = Context(system, integrator, platform)
context.setPositions(crd.positions)

state1 = context.getState(getEnergy=True, groups={psf.NONBONDED_FORCE_GROUP})
state2 = context.getState(getEnergy=True, groups={31})
state3 = context.getState(getEnergy=True, groups={psf.NONBONDED_FORCE_GROUP, 31})

print(f'NONBONDED_FORCE_GROUP energy = {state1.getPotentialEnergy()}')
print(f'FG31 energy = {state2.getPotentialEnergy()}')
print(f'NONBONDED_FORCE_GROUP energy + FG31 energy = {state1.getPotentialEnergy() + state2.getPotentialEnergy()}')
print(f'NONBONDED_FORCE_GROUP && 31 energy = {state3.getPotentialEnergy()}')
```
![image](https://user-images.githubusercontent.com/83390705/218079024-2ef58d28-9140-49b0-9bbb-b596c8fe9231.png)

however, after switched to Reference platform, this discrepance vanishes
![image](https://user-images.githubusercontent.com/83390705/218083266-3f3fb5b5-27d2-4c81-af61-906318a6a0b4.png)

**Comment by sef43** [comment]
What happens if you use the CPU platform? or with the different CUDA platform precision modes: single, mixed, double ?
e.g. 
`context = Context(system, integrator, platform, {"Precision":"double"}
)`

**Comment by peastman** [comment]
What version of OpenMM are you using?  Can you post the input files needed to reproduce it?

**Comment by udlich** [comment]
> What version of OpenMM are you using? Can you post the input files needed to reproduce it?

it's openm7.7.0, and all relevant files are attached
[test.zip](https://github.com/openmm/openmm/files/10712429/test.zip)

**Comment by udlich** [comment]
> What happens if you use the CPU platform? or with the different CUDA platform precision modes: single, mixed, double ? e.g. `context = Context(system, integrator, platform, {"Precision":"double"} )`

single:
![image](https://user-images.githubusercontent.com/83390705/218235978-4696dcc0-8537-413d-84a0-70847affdc60.png)

mixed:
![image](https://user-images.githubusercontent.com/83390705/218236002-db395287-2ad3-4f41-842b-e1137f31e4b0.png)

double:
![image](https://user-images.githubusercontent.com/83390705/218236051-c73748ac-6a10-47d9-b01d-2d93cc8dd341.png)

CPU:
![image](https://user-images.githubusercontent.com/83390705/218236529-ea114e3a-36e9-49fe-9b5e-dd04d8b0fbf2.png)

**Comment by peastman** [comment]
This appears to be an issue of limited precision.  If I add `{'Precision':'double'}` to the Context constructor, I get excellent agreement:

```
NONBONDED_FORCE_GROUP energy = -1559652.8777422174 kJ/mol
FG31 energy = 120810.95741950136 kJ/mol
NONBONDED_FORCE_GROUP energy + FG31 energy = -1438841.920322716 kJ/mol
NONBONDED_FORCE_GROUP && 31 energy = -1438841.9203227172 kJ/mol
```

In your post above, I think you either posted the same image twice, or forgot to actually change the precision from mixed to double.  All of the numbers are identical to the last digit, which shouldn't be the case if it's actually using different precision.

I think the problem is coming from the huge number of interactions being added up.  You have over 100,000 atoms, and you specify `NoCutoff` as the nonbonded method.  If you change it to `CutoffNonPeriodic` the agreement gets much better even in single precision mode.

```
NONBONDED_FORCE_GROUP energy = -1468895.0 kJ/mol
FG31 energy = 127199.96875 kJ/mol
NONBONDED_FORCE_GROUP energy + FG31 energy = -1341695.03125 kJ/mol
NONBONDED_FORCE_GROUP && 31 energy = -1341694.75 kJ/mol
```

**Comment by udlich** [comment]
> This appears to be an issue of limited precision. If I add `{'Precision':'double'}` to the Context constructor, I get excellent agreement:
> 
> ```
> NONBONDED_FORCE_GROUP energy = -1559652.8777422174 kJ/mol
> FG31 energy = 120810.95741950136 kJ/mol
> NONBONDED_FORCE_GROUP energy + FG31 energy = -1438841.920322716 kJ/mol
> NONBONDED_FORCE_GROUP && 31 energy = -1438841.9203227172 kJ/mol
> ```
> 
> In your post above, I think you either posted the same image twice, or forgot to actually change the precision from mixed to double. All of the numbers are identical to the last digit, which shouldn't be the case if it's actually using different precision.
> 
> I think the problem is coming from the huge number of interactions being added up. You have over 100,000 atoms, and you specify `NoCutoff` as the nonbonded method. If you change it to `CutoffNonPeriodic` the agreement gets much better even in single precision mode.
> 
> ```
> NONBONDED_FORCE_GROUP energy = -1468895.0 kJ/mol
> FG31 energy = 127199.96875 kJ/mol
> NONBONDED_FORCE_GROUP energy + FG31 energy = -1341695.03125 kJ/mol
> NONBONDED_FORCE_GROUP && 31 energy = -1341694.75 kJ/mol
> ```

thanks for your kind help!
