### ISSUE TITLE
facing problem in building openmm

### ISSUE THREAD

**Issue by heman3333** [openmm/openmm#3962]
Every time I try to build openmm, I am getting the following error:
openmm/libraries/pocketfft/include/pocketfft_hdronly.h:165:35: error: ‘max_align_t’ was not declared in this scope
   align = std::max(align, alignof(max_align_t));    

which I am not able to solve by any means.

**Comment by RaulPPelaez** [comment]
This could be caused by using an old C++ compiler, which compiler and version are you using?

**Comment by heman3333** [comment]
Thanks for the response.
I am using GNU version 4.8.5.

**Comment by peastman** [comment]
You need to use a newer compiler.  I don't think that version supports C++11.

**Comment by heman3333** [comment]
Yes, The issue was with the compiler, I found it.
Thanks for the suggestion.
