### ISSUE TITLE
compile failed as generateWrappers.py has an Invalid syntax 

### ISSUE THREAD

**Issue by black6816** [openmm/openmm#3963]
ir/DependInfo.cmake --color=
make[2]: Leaving directory '/workspace/openmm/build'
make  -f wrappers/CMakeFiles/ApiWrappers.dir/build.make wrappers/CMakeFiles/ApiWrappers.dir/build
make[2]: Entering directory '/workspace/openmm/build'
[  0%] Generating OpenMMCWrapper.h, OpenMMCWrapper.cpp, OpenMMFortranModule.f90, OpenMMFortranWrapper.cpp
cd /workspace/openmm/build/wrappers && /usr/bin/python /workspace/openmm/wrappers/generateWrappers.py /workspace/openmm/build/wrappers/doxygen/xml /workspace/openmm/build/wrappers
  File "/workspace/openmm/wrappers/generateWrappers.py", line 931
    iDef = '/'.join(f'{x}_dp' for x in iDef.split('/'))
                            ^
**SyntaxError: invalid syntax**
wrappers/CMakeFiles/ApiWrappers.dir/build.make:79: recipe for target 'wrappers/OpenMMCWrapper.h' failed
make[2]: *** [wrappers/OpenMMCWrapper.h] Error 1
make[2]: Leaving directory '/workspace/openmm/build'
CMakeFiles/Makefile2:1865: recipe for target 'wrappers/CMakeFiles/ApiWrappers.dir/all' failed
make[1]: *** [wrappers/CMakeFiles/ApiWrappers.dir/all] Error 2
make[1]: Leaving directory '/workspace/openmm/build'
Makefile:148: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by black6816** [comment]
commit 611bd817d5d753de89f9b7cf10f019f819c61675 (origin/master, origin/HEAD)
Author: bdenhollander <44237618+bdenhollander@users.noreply.github.com>
Date:   Mon Feb 13 20:14:18 2023 -0500

    Remove unused offset variables (#3961)
    
    - Appear to be copy and pasted from getPositions and were not removed

**Comment by black6816** [comment]
cmake version 3.25.0
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04) 
Cuda compilation tools, release 11.7, V11.7.99
Python 2.7.17

**Comment by peastman** [comment]
You need to use Python 3.  2.7 has been deprecated for a long time.
