### ISSUE TITLE
Openmm script errors generated in Enhanced Sampler Section 

### ISSUE THREAD

**Issue by friedrickhch** [openmm/openmm#3964]
I had intended to perform an accelerated molecular dynamics (aMD) simulation on a short peptide to analyze its folding process into a helix using the Enhanced Sampler Section. However, I encountered multiple difficulties during the normal execution of the script files generated by the Enhanced Sampler. Despite my attempts at debugging, I have yet to resolve these issues:

(1)the first problem I got is when I do the "csh README" in the fold "openmm_amd_dihedral", the error showed:

```
usage: openmm_run.py [-h] [--platform PLATFORM] -i INPFILE -p PSFFILE -c
                     CRDFILE -t TOPPAR [-b SYSINFO] [-icrst RSTFILE]
                     [-irst RSTFILE] [-ichk CHKFILE] [-opdb PDBFILE]
                     [-orst RSTFILE] [-ochk CHKFILE] [-odcd DCDFILE] [-rewrap]
openmm_run.py: error: the following arguments are required: -t
```

so in the openmm_run.py generated by Enhanced Sampler, there is no "-ff" parameter defined, and after I check the openmm_run.py generated in other sections like Solution builder, I found the editing date for the openmm_run.py by Enhanced Sampler is "Last update: March 29, 2017" and other "normal" openmm_run.py is "Last update: June 18, 2021" with the "-ff" definition. So I use the 2021 version openmm_run.py and run the code in README:

```
set input_param = "-ff amber -p ${init}.parm7 -c ${init}.rst7"
python -u openmm_run.py -i ${equi_prefix}.inp ${input_param} -orst ${equi_prefix}.rst -odcd ${equi_prefix}.dcd > ${equi_prefix}.out
```

now it can be normally executed.

(2) Here came the second problem when executing the next line in README:
```
set aMD_prerun = step4.1_aMD_prerun
python -u openmm_amd.py -i ${prod_prefix}.inp ${input_param} -orst ${aMD_prerun}.rst -odcd ${aMD_prerun}.dcd -prerun > ${aMD_prerun}.out
```
the error messages showed:

```
File "openmm_amd.py", line 123
    simulation.context.setPositions(crd.positions)
    ^
SyntaxError: invalid syntax
(standard_in) 1: syntax error
```

so I check the openmm_amd.py and I found the problem in this part：

```
#OpenMM aMD dihedral mode
if args.prerun == False:
    system.addForce(AndersenThermostat(300*kelvin, 1/picosecond))
    integrator = AMDForceGroupIntegrator(inputs.dt*picoseconds, 3, #DihA, #DihE)

# Build simulation context
simulation = Simulation(top.topology, system, integrator, platform, prop)
simulation.context.setPositions(crd.positions)
```

It seems the "#" symbol is turning the "#DihA, #DihE" and it's following parts into a comment so when python executed these line, it will give the syntax error(it's took me lot of time to notice that XD), so I change it into the following:

```
#OpenMM aMD dihedral mode
if args.prerun == False:
    system.addForce(AndersenThermostat(300*kelvin, 1/picosecond))
    integrator = AMDForceGroupIntegrator(inputs.dt*picoseconds, 3, __DihA, __DihE)

# Build simulation context
simulation = Simulation(top.topology, system, integrator, platform, prop)
simulation.context.setPositions(crd.positions)
```

and change the cooresponding parts in README file from :

`sed "s/#DihE/$DihE/;s/#DihA/$DihA/" openmm_amd.py  > openmm_amd_run.py`

to:

`sed "s/__DihE/$DihE/;s/__DihA/$DihA/" openmm_amd.py  > openmm_amd_run.py`

and the problem got solved for now

(3)the third problem still came by running the line in README:
`python -u openmm_amd.py -i ${prod_prefix}.inp ${input_param} -orst ${aMD_prerun}.rst -odcd ${aMD_prerun}.dcd -prerun > ${aMD_prerun}.out`

the error messages:

```
Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
Traceback (most recent call last):
  File "openmm_amd.py", line 122, in <module>
    simulation = Simulation(top.topology, system, integrator, platform, prop)
NameError: name 'integrator' is not defined
(standard_in) 1: syntax error
```

it seems the integrator is defined in openmm_amd.py as:
```
#OpenMM aMD dihedral mode
if args.prerun == False:
    system.addForce(AndersenThermostat(300*kelvin, 1/picosecond))
    integrator = AMDForceGroupIntegrator(inputs.dt*picoseconds, 3, __DihA, __DihE)
```

But I don't really understand the logic in this part, it seems need a prerun to calculte the parameters needed in custom integrator, in this case, the alphaGroup (energy) and the EGroup (energy). I thought the prerun can give me the parameters I need because in README, it use "bc" to calculate the value of "DihA" and "DihE", but it seem that the prerun has no integrator to use in this case? I don't really understand the code provided by Enhanced Sampler. I put the openmm_amd.py and README file as txt in the attachment 

 
[openmm_amd.txt](https://github.com/openmm/openmm/files/10743159/openmm_amd.txt)
[README.txt](https://github.com/openmm/openmm/files/10743160/README.txt)

**Comment by peastman** [comment]
What is Enhanced Sampler?  That isn't part of OpenMM.

**Comment by friedrickhch** [comment]
In Charmm-gui website it wrote: 
```
Enhanced Sampler helps the user to generate inputs for various kinds of enhanced sampling method simulations with collective variables.
Currently available enhanced sampling methods are:
Accelerated MD (aMD)
Gaussian accelerated MD (GaMD)
Conformational Flooding (CF)
Metadynamics (MTD)
Adaptive Biasing Force (ABF)
Steered MD (SMD)
Temperature Replica Exchange MD (T-REMD)
Replica Exchange Umbrella Sampling (REUS)
Replica Exchange Solute Tempering 2 (REST2)
The methods are implemented in each of the following packages:
AMBER:  aMD, GaMD, MTD, SMD, T-REMD, and REUS.
CHARMM:  SMD, T-REMD, REUS, and REST2.
GENESIS:  GaMD, SMD, T-REMD, REUS, and REST2.
GROMACS:  CF, MTD, SMD, T-REMD, REUS, and REST2.
NAMD:  aMD, GaMD, MTD, ABF, SMD, T-REMD, REUS, and REST2.
OpenMM:  aMD, MTD, SMD, T-REMD, and REUS.
```
It might simply be the name of a section on the CHARMM-GUI website, similar to the 'Solution Builder' section, but with the added functionality of using custom integrators such as aMD or GaMD. I used this section to generate the necessary files for running my simulations with the FF14SB force field, in order to study the folding process of a linear peptide using OpenMM.

**Comment by peastman** [comment]
If there's a problem in the script generated by CHARMM-GUI, you need to report it to the developers.  That isn't an issue with OpenMM.

**Comment by friedrickhch** [comment]
OK I see, thank you!
