### ISSUE TITLE
`findBlocksWithInteractions` optimization idea

### ISSUE THREAD

**Issue by bdenhollander** [openmm/openmm#3966]
`findBlocksWithInteractions` trails off differently than other kernels. When examining wavefront run times, I noticed that the total kernel run time is equal to the length of the longest wavefront. From the loop conditions, I get the impression that the kernel is running like this:

| Block1 | Block2 | Block2 | Block2 | Block2 | Block2 | Block2 | Block2 |
|--------|--------|--------|--------|--------|--------|--------|--------|
| 7      |        |        |        |        |        |        |        |
| 6      | 7      |        |        |        |        |        |        |
| 5      | 6      | 7      |        |        |        |        |        |
| 4      | 5      | 6      | 7      |        |        |        |        |
| 3      | 4      | 5      | 6      | 7      |        |        |        |
| 2      | 3      | 4      | 5      | 6      | 7      |        |        |
| 1      | 2      | 3      | 4      | 5      | 6      | 7      |        |
| 0      | 1      | 2      | 3      | 4      | 5      | 6      | 7      |

The wavefront that gets block 0 has the most comparisons to do and will finish last.

Would it be possible to spread the load more evenly by comparing each block against no more than half + 1 other blocks? This could theoretically speedup `findBlocksWithInteractions` by 40%.

| Block1 | Block2 | Block2 | Block2 | Block2 |
|--------|--------|--------|--------|--------|
| 7      |        | 0      | 1      | 2      |
| 6      | 7      |        | 0      | 1      |
| 5      | 6      | 7      |        | 0      |
| 4      | 5      | 6      | 7      |        |
| 3      | 4      | 5      | 6      | 7      |
| 2      | 3      | 4      | 5      | 6      |
| 1      | 2      | 3      | 4      | 5      |
| 0      | 1      | 2      | 3      | 4      |

<details><summary>Radeon GPU Profiler Screenshot</summary>
<p>
<img src="https://user-images.githubusercontent.com/44237618/219535552-0db96f87-dabb-4a23-8aa5-7040a185e9f3.png" />
</p>
</details>

**Comment by peastman** [comment]
It shouldn't be as bad as that, though there could be a slight effect.  Here is the outer loop.

```c++
for (int block1 = startBlockIndex+warpIndex; block1 < startBlockIndex+numBlocks; block1 += totalWarps) {
```

Inside that is an inner loop.

```c++
    for (int block2Base = block1+1; block2Base < NUM_BLOCKS; block2Base += 32) {
```

The inner loop is from `block1+1` to `NUM_BLOCKS`, which means there will tend to be more work to do for lower values of `block1`.  But notice that they're interleaved.  The first warp processes blocks `0`, `totalWarps`, `2*totalWarps`, etc.  The second warp processes blocks `1`, `totalWarps+1`, etc.  The earlier warps will on average have slightly fewer iterations of the inner loop, but it should be a small difference.

There's a second factor that causes some groups to take longer than others: not all atom blocks are the same.  For each one, it first identifies other blocks that are potentially near enough to interact, then does a much more expensive analysis checking individual atoms against each other.  Blocks that have more neighbors (for example, because they're less compact) require running that analysis more times.

**Comment by bdenhollander** [comment]
> The inner loop is from `block1+1` to `NUM_BLOCKS`, which means there will tend to be more work to do for lower values of `block1`. But notice that they're interleaved. The first warp processes blocks `0`, `totalWarps`, `2*totalWarps`, etc. The second warp processes blocks `1`, `totalWarps+1`, etc. 

It takes a lot of atoms for a wavefront to do one more than one iteration of the outer loop. On my RX 6600, `rf` only does one iteration so there is no interleaving and produces the triangular profile shape in the initial comment. `apoa1rf` does about 1.25 iterations. The interleaving ends up taking the next slice with the most potentially comparisons to do.
![image](https://user-images.githubusercontent.com/44237618/219907119-62510c8a-f801-47bf-9bf8-6c757ffa2fe6.png)

I attached a version of [findInteractingBlocks](https://github.com/openmm/openmm/files/10775500/findInteractingBlocks.txt) that tries to balance the potential work by giving the first warp the least work in the next loop iteration. This reduces the maximum time spent by a single warp during `findBlocksWithInteractions` in `apoa1rf` from about 800 us to 650 us. Unfortunately, the total run time of the kernel hardly budges from 1650-1720 us.
![image](https://user-images.githubusercontent.com/44237618/219907199-a9bae04d-4746-42b6-9e16-de7809f52421.png)

> There's a second factor that causes some groups to take longer than others: not all atom blocks are the same. For each one, it first identifies other blocks that are potentially near enough to interact, then does a much more expensive analysis checking individual atoms against each other. Blocks that have more neighbors (for example, because they're less compact) require running that analysis more times.

This is good to know, thank you. I was envisioning a fairly consistent grid rather than boxes of 32 atoms with various sizes located in 3D space.

**Comment by peastman** [comment]
> Unfortunately, the total run time of the kernel hardly budges from 1650-1720 us.

What really matters is compute units, not warps/wavefronts.  The number of wavefronts for the kernel is much larger than the number of compute units.  So even if some wavefronts finish quickly, that's not a problem.  It just means those compute units will become free to start working on something else.

Can you measure how much variation there is between when different compute units finish all their work?

**Comment by bdenhollander** [comment]
> Can you measure how much variation there is between when different compute units finish all their work?

Radeon GPU Profiler provides wavefront information but no detailed scheduling information about what wavefronts were running on which CU that I'm aware of. The best I can do is estimate utilization based on the height of the bars on the graph.

`rf` does one outer loop iterations per wavefront. Utilization of CUs is high until 100 wavefronts are completed.

![image](https://user-images.githubusercontent.com/44237618/220476786-ce06c07a-0eed-4f1b-87ed-4c97ff9e122e.png)

`apoa1rf` does 1.25 outer loop iterations per wavefront. Utilization of CUs is high until wavefronts start to finish and then dips and rises before trailing off at the end.

![image](https://user-images.githubusercontent.com/44237618/220477226-67c337a2-e3ee-4e2e-a34e-34b1b3ba664a.png)

**Comment by peastman** [comment]
What does "wavefronts remaining" mean?  Clearly it isn't just total threads divided by 32, because then it would only decrease, not increase.  What do the orange bars represent?

**Comment by bdenhollander** [comment]
> What does "wavefronts remaining" mean? Clearly it isn't just total threads divided by 32, because then it would only decrease, not increase. What do the orange bars represent?

If I highlight the graph from when the kernel is finished and head left, some statistics appear in the right hand panel. An example showing the full kernel is in the collapsed screenshot in the first comment of this thread.

Wavefronts are thread blocks/groups of 32 threads. 
```
rf:       744 wavefronts * 32 = 23808 threads
apoa1rf: 2688 wavefronts * 32 = 86106 threads
```

The vertical bars on the graphs are GPU utilization, which goes varies as the kernel progresses. Wavefront counts only decrease and are shown at the top of the orange bar. They mark points of interest to show when the first wavefront completes, where performance falls off, etc. to give some context on how the kernel is executing over time.

**Comment by peastman** [comment]
Look at the second graph in your post, the green one.  The graph mostly goes down, but not entirely.  There are lots of points where it goes back up a bit before starting to go back down again.  What does it mean for the number of "remaining" wavefronts to increase?

At various points there are vertical orange lines through the graph.  What do those points correspond to?  What happened at those particular times?

**Comment by bdenhollander** [comment]
> Look at the second graph in your post, the green one. The graph mostly goes down, but not entirely. There are lots of points where it goes back up a bit before starting to go back down again. What does it mean for the number of "remaining" wavefronts to increase?

The green bars on the y-axis of the graph are GPU utilization, not wavefronts. GPU utilization fluctuates throughout the runtime of the kernel. Numbers at the top of the orange bars are wavefronts remaining and they always go down.

> At various points there are vertical orange lines through the graph. What do those points correspond to? What happened at those particular times?

The orange lines indicate when the kernel reached a certain number of wavefront remaining. What exactly happened I don't know, they're just potentially interesting. If they could be correlated with what the kernel is currently doing then they might point to bottlenecks in the code.

**Comment by peastman** [comment]
Got it.  Here's what I see.

For the rf benchmark, the utilization remains steady for about the first 1/3 of the run time, then gradually declines.  That suggests it may be suffering from lack of work to keep the compute units busy, and distributing the work more evenly could help.

For apoa1rf, utilitization is fairly flat for most of the run, only dropping off at the very end.  That suggests it's already keeping the compute units busy, and redistributing the work would be unlikely to have much benefit.

**Comment by bdenhollander** [comment]
Closing this issue since #4070 and #4147 are both great performance improvements to `findBlocksWithInteractions`.

The HIP plugin takes an interesting approach for this kernel that appears to use [more wavefronts and less nested looping](https://github.com/amd/openmm-hip/commit/5912f7f70dd053890e1508ed22ed8a693598d113). This could potentially be faster if ported to CUDA or OpenCL.
