### ISSUE TITLE
TypeError: CustomCentroidBondForce.addGroup() got an unexpected keyword argument 'weights'/ openmm.OpenMMException: CustomCentroidBondForce: Weights for group 1 add to 0

### ISSUE THREAD

**Issue by mainguyenanhvu** [openmm/openmm#3967]
I am using conda to install openMM 8.0.0. The code below threw an error:
```
 upper_wall_rest.addGroup(lig_ha_idx, weights=[1.0]*len(lig_ha_idx))
TypeError: CustomCentroidBondForce.addGroup() got an unexpected keyword argument 'weights'
```

My code:
```
    # Create the CustomCentroidBondForce object
    upper_wall_rest = CustomCentroidBondForce(2, fb_eq)
    upper_wall_rest.addGroup(lig_ha_idx, weights=[1.0]*len(lig_ha_idx))
    upper_wall_rest.addGroup(anchor_atom_idx, weights=[1.0]*len(anchor_atom_idx))
    upper_wall_rest.addBond([0, 1])
    upper_wall_rest.addGlobalParameter('k', k)
    upper_wall_rest.addGlobalParameter('upper_wall', upper_wall)
    upper_wall_rest.setUsesPeriodicBoundaryConditions(True)
```

If I use the other code, it had an error:
```
    _openmm.Context_swiginit(self, _openmm.new_Context(*args))
openmm.OpenMMException: CustomCentroidBondForce: Weights for group 1 add to 0
```

My other code:
```
    # Add an 'empty' flat-bottom restraint to fix the issue with PBC.
    # Without one, RMSDForce object fails to account for PBC.
    k = 0*kilojoules_per_mole  # NOTE - 0 kJ/mol constant
    upper_wall = 10.00*nanometer
    fb_eq = '(k/2)*max(distance(g1,g2) - upper_wall, 0)^2'
    upper_wall_rest = CustomCentroidBondForce(2, fb_eq)
    upper_wall_rest.addGroup(lig_ha_idx)
    upper_wall_rest.addGroup(anchor_atom_idx)
    upper_wall_rest.addBond([0, 1])
    upper_wall_rest.addGlobalParameter('k', k)
    upper_wall_rest.addGlobalParameter('upper_wall', upper_wall)
    upper_wall_rest.setUsesPeriodicBoundaryConditions(True)
```

**Comment by peastman** [comment]
You need to pass the argument by position rather than name.  Just remove `weights=` and it should work.

```python
>>> f.addGroup([1,2,3])
0
>>> f.addGroup([1,2,3], [1.0, 2.0, 3.0])
1
>>> f.addGroup([1,2,3], weights=[1.0, 2.0, 3.0])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: addGroup() got an unexpected keyword argument 'weights'
```

**Comment by evamartin1240** [comment]
I am using your code and I have the same problem.

When using:

`
    upper_wall_rest = openmm.CustomCentroidBondForce(2, fb_eq)`
    `upper_wall_rest.addGroup(lig_ha_idx)`
    `upper_wall_rest.addGroup(anchor_atom_idx)`
    `upper_wall_rest.addBond([0, 1])`
    `upper_wall_rest.addGlobalParameter('k', k)`
    `upper_wall_rest.addGlobalParameter('upper_wall', upper_wall)`
    `upper_wall_rest.setUsesPeriodicBoundaryConditions(True)`
    `system.addForce(upper_wall_rest)`

I get the following error:

`OpenMMException: CustomCentroidBondForce: Weights for group 0 add to 0`

And when using your code (but corrected without the 'weights'):

   ` # Create the CustomCentroidBondForce object`
    `upper_wall_rest = CustomCentroidBondForce(2, fb_eq)`
    `upper_wall_rest.addGroup(lig_ha_idx, [1.0]*len(lig_ha_idx))`
    `upper_wall_rest.addGroup(anchor_atom_idx, [1.0]*len(anchor_atom_idx))`
    `upper_wall_rest.addBond([0, 1])`
    `upper_wall_rest.addGlobalParameter('k', k)`
    `upper_wall_rest.addGlobalParameter('upper_wall', upper_wall)`
    `upper_wall_rest.setUsesPeriodicBoundaryConditions(True)`

I also get the same error:

`OpenMMException: CustomCentroidBondForce: Weights for group 0 add to 0`

Did you manage to solve it?

**Comment by evamartin1240** [comment]
No, the `anchor_atom_idx` is not empty, when I print it I get this output:

`[2084, 2085, 2092, 2094, 2095, 2104, 2124, 2126, 2128, 2129, 2138, 2140, 2142, 2143, 2154, 2294, 2313, 2315, 2330, 2335]`

**Comment by peastman** [comment]
Can you open a new issue, and post a complete test case to reproduce the problem?  This issue has already been closed, and it involves a different problem.
