### ISSUE TITLE
Tempfiles fill quickly in /tmp

### ISSUE THREAD

**Issue by insukjoung** [openmm/openmm#3970]
I run multiple simulations. I frequently encounter the problem that /tmp is full.
I checked files and most of them started with the header like below:

```
//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: CL-28845127
// Cuda compilation tools, release 11.0, V11.0.221
// Based on LLVM 3.4svn
//

.version 7.0
.target sm_80
.address_size 64

        // .globl       generateRandomNumbers
// _ZZ40computeCCMAPositionConstraintForceKernelE14groupConverged has been demoted
// _ZZ40computeCCMAVelocityConstraintForceKernelE14groupConverged has been demoted
// _ZZ7runCCMAE14groupConverged has been demoted
```

According to the messages inside the file, it looks like they are generated during OpenMM build process.
The problem is that they remain even after the simulation is done. Is there a way to remove the files automatically?

**Comment by swails** [comment]
The header shows these are created by the nvidia compiler (that essentially JIT compiles GPU kernels) building the OpenMM kernels.  You can usually configure a Unix machine to periodically clean up `/tmp`.  For instance, [this link](https://askubuntu.com/a/983848) shows some advice that will likely help you configure this kind of auto-cleanup.

**Comment by peastman** [comment]
Those are cached compiled kernels.  The CUDA compiler isn't all that fast.  It typically takes around one second for each kernel.  That can add a lot of time to every time you create a new Context.  To speed it up, OpenMM stores the compiled kernels in `/tmp`.

Those files aren't very large, typically only a few tens of KB each.  How many of them are there?  Does your system have a very low limit set on `/tmp`?

**Comment by insukjoung** [comment]
Ok. Then, I think I should create a runtime tempdir or clean /tmp regularly.  Thank you!

**Comment by peastman** [comment]
Is it ok to close this?

**Comment by insukjoung** [comment]
Sure!
