### ISSUE TITLE
Hydrogen in a wrong position?

### ISSUE THREAD

**Issue by Aunity** [openmm/openmm#3980]
Hi,

I'm using the `openmm.app.Moduler.addHydrogens` to add hydrogens to my pdb file:
```Python
from simtk.openmm import app
pdb = app.PDBFile('2fvy-noh.pdb')
m = app.Modeller(pdb.topology, pdb.positions)
m.addHydrogens(pH=7.0)
with open('2fvy-H.pdb', 'w') as fw:
    app.PDBFile.writeFile(m.topology, m.positions, file=fw)
```

But some hydrogens added by `openmm.app.Moduler.addHydrogens` were in unphysical positions like:

<table border="0">

 <tr>
    <td><img src="https://user-images.githubusercontent.com/18044835/221465875-6f9df285-6460-467f-8c0c-2aafa0269619.png" width="200" height="200"></td>
    <td><img src="https://user-images.githubusercontent.com/18044835/221466020-8bade593-7fec-457a-86a1-998377af776a.png" width="200" height="200"></td>
 </tr>
</table>

These are my pdb files:
[2fvy.zip](https://github.com/openmm/openmm/files/10835788/2fvy.zip)

**Comment by peastman** [comment]
`addHydrogens()` has an optional `forcefield` argument.  If you provide it, you'll get hydrogen positions that are minimized with that force field.  If you omit it, then it does its best to provide positions that aren't too wildly unphysical, but may not be very accurate.  Either way, you should always energy minimize the complete system before simulating.  That fixes minor issues like this.

**Comment by peastman** [comment]
Closing this since the question has been answered.
