### ISSUE TITLE
CustomCentroidBondForce restrains bond to center of box

### ISSUE THREAD

**Issue by ywelhady** [openmm/openmm#3986]
I'm trying to use the CustomCentroidBondForce to restrain the distance between two groups, but I want the system of both groups to be able to move around a box, and wrap back in with periodic boundary conditions.

Right now, the system of both groups stays centered at the middle of the box (if g1 moves left, then g2 moves right), and I'm not sure why. Below is the code, and I'm also not sure if my comments in the restraint setup are accurate. Could you help me understand?

```
    #### System setup ####
    pdb = PDBFile(inputFile)
    forcefield = ForceField('amber14-all.xml', 'amber14/tip3pfb.xml', 'implicit/gbn.xml')
    system = forcefield.createSystem(pdb.topology, nonbondedMethod=CutoffPeriodic, 
            nonbondedCutoff=cutoff*nanometer, constraints=HBonds)

    #### add a harmonic biasing potential ####
    restraint = CustomCentroidBondForce(2, "0.5*k*(distance(g1,g2)-r0)^2")
    restraint.addGlobalParameter('r0', r0)
    restraint.addGlobalParameter('k',k)
    g1 = [0]
    g2 = [1]
    restraint.addGroup(g1) # index will be 0
    restraint.addGroup(g2) # index will be 1
    restraint.addBond([0,1], []) #([g1_index,g2_index], [per-bond parameter list])
    system.addForce(restraint)

    #### Simulation setup ####
    if (intName=="Lang"): integrator = LangevinMiddleIntegrator(300*kelvin, 1/picosecond, dt*picoseconds)
    if (intName=="Verl"): integrator = VerletIntegrator(dt*picoseconds)
    simulation = Simulation(pdb.topology, system, integrator)
    simulation.context.setPositions(pdb.positions)
    simulation.context.setVelocitiesToTemperature(300)
    simulation.minimizeEnergy()
    
    #### Simulation reporters ####
    simulation.reporters.append(PDBReporter(outputFile+'.pdb', pdbFreq))
    simulation.reporters.append(StateDataReporter(stdout, reportFreq, step=True, time=True,
            potentialEnergy=True, totalEnergy=True, temperature=True))
    
    #### run MD ####
    simulation.step(int(round(simTime/dt)))
```

The system is just two atoms right now, no explicit water molecules.

**Comment by peastman** [comment]
Call `setUsesPeriodicBoundaryConditions(True)` on the CustomCentroidBondForce.  That tells it to use periodic boundary conditions when computing displacements between particles.

> Right now, the system of both groups stays centered at the middle of the box

By default, the force field adds a CMMotionRemover to the System.  That prevents any drift of the center of mass.  If you don't want that, you can add the argument `removeCMMotion=False` to `createSystem()`.

**Comment by ywelhady** [comment]
Thank you!
