### ISSUE TITLE
Swig issue with %factory

### ISSUE THREAD

**Issue by jlmaccal** [openmm/openmm#3989]
We're running into a new problem compiling our plugin against OpenMM.

The error is:
```
[100%] Generating MeldPluginWrapper.cpp
/usr/share/miniconda/envs/build/include/swig/OpenMMSwigHeaders.i:12: Error: Unknown directive '%factory'.
```

As you can see, the errors here arise from OpenMM's swig header.

This is a new issue that has only recently popped up. I suspect it might have something to do with an updated version of swig in anaconda. For reference, this is `4.1.1`. We do not pin the swig version, so we get this version by default.

Any idea about how to resolve this? Is pinning to an older version of swig the only solution? If so, which one?

**Comment by peastman** [comment]
This was broken by a SWIG update.  To fix it, you just need to add `%include "factory.i"` to your interface file.  See https://github.com/openmm/openmm-torch/pull/96.  Though we should add the include to OpenMMSwigHeaders.i so downstream packages don't need to.

**Comment by jlmaccal** [comment]
Thanks, that did the trick.

**Comment by peastman** [comment]
Let's keep this open as a reminder to add it to OpenMMSwigHeaders.i.
