### ISSUE TITLE
Conda Install Documentation Change from Omnia to Conda-Forge

### ISSUE THREAD

**Issue by Sulstice** [openmm/openmm#3991]
I went through a python 3.6 to 3.9 version rabbit hole because I thought the documentation online says to install `openmm` this way because I think omnia doesn't work on above 3.6:

```python

conda install -n env -c omnia openmm

```

Reading through some forums the installation should be:

```python

conda install -n env -c conda-forge openmm

```

**Comment by sef43** [comment]
Can you please link to where the omnia references appear? the latest user guide has instructions for using conda-forge: 
http://docs.openmm.org/latest/userguide/application/01_getting_started.html#installing-openmm

**Comment by Sulstice** [comment]
Huh, I guess when I put it in google it routes me to the old version on the first link with the omnia.

`openmm installation`

<img width="1284" alt="Screenshot 2023-03-08 at 7 07 24 AM" src="https://user-images.githubusercontent.com/11812946/223709441-ba56467c-2a61-46dc-9fa5-79f02154bbf4.png">

http://docs.openmm.org/7.0.0/userguide/application.html

**Comment by mattwthompson** [comment]
This is unfortunately a known and widespread problem with what they index and how often they update it; OpenMM isn't the only package affected. As a heavy user, I wish there was a better solution than getting into the habit of starting at https://openmm.org/ but we just have to make do.
