### ISSUE TITLE
Massless particles move during NPT simulation

### ISSUE THREAD

**Issue by zhenyuwei99** [openmm/openmm#3994]
Hi:
I am trying to simulate a fixed carbon nanotube, as shown below, by setting the mass of particles of CNT and graphene to zero.

![image](https://user-images.githubusercontent.com/46258713/224326007-c4679dfd-2e96-4c4b-a259-3717bc277dd1.png)

However, when I relax the system in the NPT ensemble by using `openmm.MonteCarloAnisotropicBarostat`, the distance between the nanotube and graphene increases. I think the rescaling of the PBC box influences the fixed particle positions. I am wondering if there is any solution to fix particle position even in the NPT ensemble.

![image](https://user-images.githubusercontent.com/46258713/224326941-859d8236-3ce8-4e68-9a60-4ec275944fc1.png)

Thanks!

**Comment by peastman** [comment]
The barostat treats each molecule as a rigid object.  It moves the molecule's center but doesn't alter its internal geometry.  In this case you have three molecules (the nanotube and the two sheets), which each get moved separately.  If you add bonds connecting the nanotube to the sheets, even ones with zero spring constant so they don't apply any forces, then it will interpret the whole thing as a single molecule and move it rigidly.  Will that do what you want?

**Comment by zhenyuwei99** [comment]
Thanks! I think this trick works.
