### ISSUE TITLE
Restart from checkpoint or state

### ISSUE THREAD

**Issue by SianXiaoCHN** [openmm/openmm#3995]
This might be a really dumb question.
I saw people restart their simulations from the CheckpointReporter generated file, I also saw people restart their simulation from serialized context.getState(position and velocity) file. It seems two simulations starting from same serialized context.getState file can be different so the real situation is that we should use the .chk file right?

**Comment by peastman** [comment]
See the documentation on [CheckpointReporter](http://docs.openmm.org/latest/api-python/generated/openmm.app.checkpointreporter.CheckpointReporter.html).  It describes the differences between checkpoints and states.
