### ISSUE TITLE
make test illegal error.

### ISSUE THREAD

**Issue by mobinat** [openmm/openmm#3996]
hi, I am following installing instructions and I run make test but I run into illegal error for 16 of tests.
can anyone let me know what must get fixed?

Errors while running CTest
Output from these tests are in: /home/mobina/Desktop/openmm-8.0.0/build/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
make: *** [Makefile:71: test] Error 8

**Comment by sef43** [comment]
Could you let us know what operating system you are on?

**Comment by mobinat** [comment]
hi, I'm on ubuntu under vmware virtual machine. I am compiling openmm from
source code.

**Comment by sef43** [comment]
what is the output of `lscpu` from the vm terminal? what is the host machine?

**Comment by mobinat** [comment]
This is the cpu infos. The host is Windows 10. 64bits

**Comment by peastman** [comment]
Can you run one of the failing tests individually and see what the output is?

**Comment by mobinat** [comment]
Sure, here it is.

It just says:

Illegal instruction (core dumped)

**Comment by mobinat** [comment]
it's an old cpu. most probably that's the case. So should I change the
system?

**Comment by peastman** [comment]
That's the reason.  OpenMM requires the CPU to be new enough to support AVX.

**Comment by peastman** [comment]
Closing this since the question has been answered.
