### ISSUE TITLE
XTC reporters

### ISSUE THREAD

**Issue by giadefa** [openmm/openmm#3997]
We would like to be able to use XTC reporters. It should be quite easy to do and we can do the PR.

Using XTC reporters is important because the size is 1/3 of DCD. When we run tons of simulations we have space problems. Yes, we can convert it later but it does not solve the size problem, in particular for GPUGRID.

@peastman ok?

**Comment by mattwthompson** [comment]
There are some previous attempts: https://github.com/openmm/openmm/issues/2755 https://github.com/openmm/openmm/issues/1186

You can already do this via MDTraj: https://github.com/mdtraj/mdtraj/blob/1.9.7/mdtraj/reporters/xtcreporter.py

**Comment by peastman** [comment]
I'd be ok with adding a XTC reporter, though the one in MDTraj might be fine for you.

**Comment by sef43** [comment]
Also this for XTC and other formats: https://github.com/sef43/openmm-mdanalysis-reporter

But I think that an internal XTC reporter for OpenMM is a good idea!

**Comment by giadefa** [comment]
we are doing the PR
