### ISSUE TITLE
Keeping multiple proteins with simulation box during simulation? (Wraping)

### ISSUE THREAD

**Issue by LipikaBaidya** [openmm/openmm#3998]
Hi, 
I am trying to simulate 64 proteins within a box with dimensions vector : [ [550,0,0], [0, 550, 0] , [0,0, 550]] in the angstrom unit. I have four different force modules from the paper https://doi.org/10.1021/acs.jpcb.2c03476 . It has four different forces:

1) Fene potential: modelled using custom bonded force
2) Repulsive nonbonded local potential: modelled using custom bonded force 
2) Debye Huckel electrostatic potential: modelled using custom bonded force
4) LJ type nonbonded nonlocal potential: modelled using custom nonbonded force and periodicCutoff nonbonded method
5) CM motion remover

I expect that all the protein chains will be within the box [ [550,0,0], [0, 550, 0] , [0,0, 550]] during the simulation. But after starting the simulation, the protein molecules start diffusing and it went outside of the box. 

How can I wrap all the proteins within the box?

**Comment by peastman** [comment]
See https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#periodic.  It discusses this issue and what to do about it.
