### ISSUE TITLE
Strange result when using MonteCarloAnisotropicBarostat

### ISSUE THREAD

**Issue by zhenyuwei99** [openmm/openmm#4003]
Hi, I am using MonteCarloAnisotropicBarostat to relax a carbon nanotube system in the NPT ensemble. In my system, the box is split by two pieces of graphene and connected with a carbon nanotube, between which is a vacuum. So I use the MonteCarloAnisotropicBarostat to relax the system's pressure only in the z-direction by creating a barostat instance like

```temperature = 300 * unit.kelvin
pressure = 1 * unit.atmosphere
barostat = openmm.MonteCarloAnisotropicBarostat(
    openmm.Vec3(pressure, pressure, pressure),
    temperature,
    False,
    False,
    True,
    25,
)
system.addForce(barostat)
```

To fix the carbon nanotube and graphene in the correct positions, I also add a constraint force on all carbon particles like:

`restrain_force = openmm.CustomExternalForce("k*periodicdistance(x, y, z, x0, y0, z0)^2")`

And I run the simulation for 1ns, the result is strange as shown below:
![2023-03-19_21-57](https://user-images.githubusercontent.com/46258713/226181194-9a984baf-97b4-44d2-9ab4-23026254919e.png)
After simulation, the system gives some water cavities near the graphene. However, in some other systems, the cavity also appears in the box boundary like
![2023-03-19_22-04](https://user-images.githubusercontent.com/46258713/226181363-785e5936-df6e-4b30-9841-40d25a3e2fac.png)

I am wondering which part is incorrect in this simulation and whether the MonteCarloAnisotropicBarostat is suitable in this case

Best,

**Comment by peastman** [comment]
I'm not sure exactly what problem you're describing.  The images show lots of water on either side of the tube, and a smaller amount of water passing through it.  I assume that's what you expect?  The irregular shape of the water on either side suggests it hasn't been wrapped to a single periodic box, so I can't tell much about the distribution of water within the box.  It looks like the density of water right next to the graphene may be reduced, but since it's hydrophobic that's not surprising.

What should I be looking at?

**Comment by zhenyuwei99** [comment]
Sorry for the misleading description. Actually, I have already wrapped all the positions in the single pbc box. However aqueous box is not uniformly distributed, while some dilute volume exists in the result as shown in the picture denoted by the red curve
![95DA3C6F7F9817E402816156F9AB4CE5](https://user-images.githubusercontent.com/46258713/226230079-c6979f57-7bf3-4c4f-a14c-bc6c5b0abb21.png)
![EA9B60C187AC42705D1A3A92400B9848](https://user-images.githubusercontent.com/46258713/226230089-b619cf33-85fd-48b4-a335-595f53ae4b18.png)

**Comment by peastman** [comment]
That looks like a bubble, which usually indicates the box is too big for the amount of water.  The barostat ought to fix it.  Can you monitor the box size?  Is it getting smaller?

**Comment by zhenyuwei99** [comment]
It is getting smaller, the box size in z-direction shrink from 100A to 94A but it seems still to big

**Comment by zhenyuwei99** [comment]
When I keep increasing the simulation time to 25ns, the result seems better

![image](https://user-images.githubusercontent.com/46258713/226369480-81d15fa4-f9a6-4474-9f15-d483b22989f6.png)

Maybe relaxing pressure in only one direction has a big influence on the relaxing efficiency. I am wondering if there is any better choice for this condition. I notice there is a MonteCarloMembranceBarostat. But I am not sure whether is suitable in this case and how to determine the surface tension in my system.

**Comment by peastman** [comment]
That looks much better.  This is just a guess, but having such a big completely rigid block right in the middle may be making things harder for the barostat.  It still works, but that forces it to use very small steps.

Reducing the barostat interval so it takes more frequent steps might help.  If you change it from 25 to 10, that might help it relax faster.  It's probably only an issue for equilibration, though.  Once you get into the production stage, 25 should be fine.  And it looks like you've successfully equilibrated it.

**Comment by zhenyuwei99** [comment]
Good idea. We don't need the dynamic to be completely physical in the equilibrium part. When I turn the barostat frequency to 5, it converges faster.

Thanks a lot!

**Comment by zhenyuwei99** [comment]
It seems that decreasing the barostat frequency will also decrease the simulation speed. Maybe the barostat requires reading data from GPU and modifying the positions of particles?

**Comment by zhenyuwei99** [comment]
Great! I think all my questions have been solved. Really thanks!
