### ISSUE TITLE
Water recognition in forcefiled.py

### ISSUE THREAD

**Issue by szaand** [openmm/openmm#4007]
In forcefield.py, water molecules are recognized by their names, i.e. whether they are called "HOH":

https://github.com/openmm/openmm/blob/3dc2f12ff20efcb609dfa5508431065d2c98d028/wrappers/python/openmm/app/forcefield.py#L1220
The topology is then checked for the corresponding resnames:

https://github.com/openmm/openmm/blob/3dc2f12ff20efcb609dfa5508431065d2c98d028/wrappers/python/openmm/app/charmmpsffile.py#L771
This can lead to issues with water molecules that have a different name, such as TIP3, SPCE, etc.
Would it make sense to check whether the resname is part of a collection of common water names? Something like in

https://github.com/openmm/openmm/blob/3dc2f12ff20efcb609dfa5508431065d2c98d028/wrappers/python/openmm/app/charmmpsffile.py#L952

**Comment by peastman** [comment]
A Topology object is required to follow standard PDB naming.  Any Topology that uses different names is invalid.  The file readers try to translate to ensure that other names found in a file will get converted to the correct name.
