### ISSUE TITLE
Calculation of the non-polar part of the GBSA implicit solvents

### ISSUE THREAD

**Issue by katzberger** [openmm/openmm#4016]
Dear OpenMM developers,

I am currently studying the implicit solvent implementations in the customgbforces.py file as well as the GBSAOBC C++ implementation. In both cases it seems that the equation used for the nonpolar part of the solvation free energy for atom i $G^{np}_i$ is given by:

$$ G^{np}_i = 4\pi \sigma \cdot (R_i + R_s)^2 \cdot \left (\frac{R_i}{B_i} \right)^6 $$

with R<sub>i</sub>, B<sub>i</sub>, and R<sub>s</sub> the radius of atom i, the Born radius of atom i and the radius of the probe (e.g., water), respectively. $\sigma$ denotes the non-polar solvation parameter (in the C++ code denoted as energy).

In the customgbforces.py this is conveniently written as:
```python
if SA=='ACE':
    force.addEnergyTerm("28.3919551*(radius+0.14)^2*(radius/B)^6; radius=or+offset"+params, CustomGBForce.SingleParticle)
```
I have now tried to find the citation for this expression and based on the name ACE and the OpenMM bibliography found this paper (Journal of Molecular Biology, 284(3):835–848, 1998, doi: https://doi.org/10.1006/jmbi.1998.2172) by Schaefer et al. in which they introduce an approximation of the non-polar solvation free energy based on the Born radius. In equation 2 they define it as:

$$ G^{np}_i = 4\pi \sigma \cdot (R_i + R_s)^2 \cdot \frac{R_i}{B_i} $$

This leads me to the question; Is the equation used in OpenMM correct and a newer version of the one cited?

It could also be that I am missing something in the code or that I misinterpreted the equations.  

Thank you very much in advance for your help!

**Comment by peastman** [comment]
The implementation in OpenMM is based on the one in Tinker.  Here's the relevant comment in the source code.

https://github.com/openmm/openmm/blob/ae42c911a951dbc03004ddaf2b988c5eca67e163/platforms/reference/src/SimTKReference/ReferenceObc.cpp#L240-L252

So this difference is intentional, but no one ever published it. :(

**Comment by katzberger** [comment]
Ah I see, that is good to hear.

Thank you a lot for the super fast and very helpful reply!
