### ISSUE TITLE
DCD box size lost during warming up, but recovered later

### ISSUE THREAD

**Issue by pipitoludovico** [openmm/openmm#4020]
Hail everyone!
I'm super new to OpenMM so please forgive me if I'm missing something trivial!

I am running a simple equilibration protocol (local minimization, adding restraints -> warming up, equilibrating with restraints, easing the restraints gradually).

This is the spaghetti code before actually putting everything into a more tidy form, just to understand if the sequence worked! :) 

```
import openmm as mm
from openmm import app
from openmm.app import *
from openmm import *
from openmm.unit import *
from sys import stdout, exit, stderr
import numpy as np

# load the PDB file
pdb = app.PDBFile('NEUTRAL_fis.pdb')

def getBox():
    print('Getting box size from the pdb...')
    import numpy as np

    with open('NEUTRAL_fis.pdb', 'r') as f:
        lines = f.readlines()

    x_coords = []
    y_coords = []
    z_coords = []

    for line in lines:
        if line.startswith('ATOM'):
            x = float(line[30:38])
            y = float(line[38:46])
            z = float(line[46:54])
            x_coords.append(x)
            y_coords.append(y)
            z_coords.append(z)

    x_range = np.max(x_coords) - np.min(x_coords)
    y_range = np.max(y_coords) - np.min(y_coords)
    z_range = np.max(z_coords) - np.min(z_coords)

    print("System size: {:.2f} x {:.2f} x {:.2f} Å".format(x_range, y_range, z_range))
    return x_range/10, y_range/10, z_range/10

`x, y, z = getBox()

# set of parms...
params = app.CharmmParameterSet(
    '/home/scratch/MD_utilities/toppar_c36_jul20/top_all36_prot.rtf',
    '/home/scratch/MD_utilities/toppar_c36_jul20/par_all36_prot.prm',
    '/home/scratch/MD_utilities/toppar_c36_jul20/par_all36_cgenff.prm',
    '/home/scratch/MD_utilities/toppar_c36_jul20/top_all36_cgenff.rtf',
    '/home/scratch/MD_utilities/toppar_c36_jul20/par_all36_lipid.prm',
    '/home/scratch/MD_utilities/toppar_c36_jul20/top_all36_lipid.rtf'
)
topology = app.CharmmPsfFile('NEUTRAL_fis.psf')

topology.setBox(x*nanometer, y*nanometer, z*nanometer) # here we set the PBC

# we create the system
print('Building the system...')
system = topology.createSystem(
    params,
    nonbondedMethod=app.PME,
    nonbondedCutoff=1*nanometer,
    constraints=app.HBonds,
    rigidWater=True
)

# set the integrator
integrator = mm.LangevinIntegrator(300*kelvin, 1/picosecond, 0.002*picoseconds)

# setting GPU for later
GPU_platform = Platform.getPlatformByName('CUDA')
properties = {'DeviceIndex': '0,1', 'Precision': 'mixed'}

# while letting OPENMM decide what's best for minimization...then switch to GPU.
simulation = app.Simulation(topology.topology, system, integrator)

# adding one reporter for all our steps
simulation.reporters.append(app.StateDataReporter(stdout, 1000, step=True, potentialEnergy=True, temperature=True))

# set the starting positions
simulation.context.setPositions(pdb.positions)


# this part was hard to understand! :) 
print('\nAdding restraints to atoms Name CA')
# set the restrain the alpha carbons
restraint = mm.CustomExternalForce('k', )
restraint.addGlobalParameter('k', 5.0*kilocalories_per_mole/nanometer**2)
restraint.addGlobalParameter('t0', 0.0*picoseconds)
restraint.addPerParticleParameter('x0')
restraint.addPerParticleParameter('y0')
restraint.addPerParticleParameter('z0')
for atom in pdb.topology.atoms():
    if atom.name == 'CA':
        restraint.addParticle(atom.index, pdb.positions[atom.index].value_in_unit(nanometers))
system.addForce(restraint)

print('\nMinimizing local energy...')
simulation.minimizeEnergy(tolerance=0.1*kilojoule/mole)
# we snapshot the final  minimized state
state = simulation.context.getState(getPositions=True, getVelocities=True, getParameters=True, getIntegratorParameters=True)

# here we switch to GPU for the actual simulation:
integrator_GPU = mm.LangevinIntegrator(300*kelvin, 1/picosecond, 0.002*picoseconds)
new_simulation = app.Simulation(topology.topology, system, integrator_GPU, GPU_platform, properties)

# and we inherit our results from minimization...
new_simulation.context.setState(state)

# adding the reporter for the new simulation
new_simulation.reporters.append(app.StateDataReporter(stdout, 1000, step=True, potentialEnergy=True, temperature=True))

# applying the parameters by initializing the system
print('\nACTIVATING RESTRAINT')
new_simulation.context.reinitialize(preserveState=True)

# warm up with restraints
print('\nWarming up the complex with the restraints...')
T = 5
mdstepsT = 6200

for i in range(62):
  temperature = (T+(i*T))*kelvin
  integrator.setTemperature(temperature)
  # updating with new T before the steps
  new_simulation.context.reinitialize(preserveState=True)
  new_simulation.step(int(mdstepsT/62))

print('\nEquilibrating with restraints and temperature...')

# perform equilibration using last temp, with restraints
new_simulation.context.setVelocitiesToTemperature(300*kelvin) # do I need to reinint this as well?
new_simulation.reporters.append(app.DCDReporter('equilibrated.dcd', 1000, enforcePeriodicBox=True))
new_simulation.step(10000)

# checking the set parameters
p = new_simulation.context.getParameters()
for kk in p:
  print(kk, p[kk])

print('\n10 cycles easing "k" restraint...:') # no cell box from this step.
for i in range(10):
    state = new_simulation.context.getState(getPositions=True)
    new_simulation.context.setParameter('k', (-i*0.5*kilocalories_per_mole/nanometer**2))
    new_simulation.context.reinitialize(preserveState=True)
    positions = state.getPositions()
    new_simulation.reporters.append(app.DCDReporter('equilibration_1.dcd', 1000, enforcePeriodicBox=True))
    new_simulation.step(1000)

print('\nEquilibrating NPT with k=0: ') # cell box appears here. 
state = new_simulation.context.getState(getPositions=True)
new_simulation.context.setParameter('k', 0)
new_simulation.context.reinitialize(preserveState=True)
positions = state.getPositions()
new_simulation.reporters.append(app.DCDReporter('equilibration_2.dcd', 1000, enforcePeriodicBox=True))
`new_simulation.step(10000)``

```
Now: it all works as intended (by looking at the energy, and the visual results) but for unknown reasons the .dcd trajectory I create in the 10 cycles "easing" loop (equilibration1.dcd) doesn't have the cell box size.

I can get the cell box size in all of them, but not on equilibration_1.
What am I missing? 
I have tried the solutions from issue #3586 but that didn't work out (the problem is still in equilibration_1 only).

I am using:
MDAnalysis 2.4.2
OpenMM version 7.7

Do you believe it could be of any use to include a protocol like this in the tutorial section (once corrected) ? 
If you think it might be worth it I am more than happy to write everything down and see if this can help new users looking for a protocol.

Thank you!

Ludovico

**Comment by peastman** [comment]
Every time through the loop, you add a new DCDReporter to the Simulation.  By the tenth iteration of the loop, you have ten different reporters, all trying to write to the same file!  That isn't going to work correctly.

You can just add a single reporter at the start and it will keep writing through all the loops.  If you want different parts of the process to be written to different files like `equilibration_1.dcd` and `equilibration_2.dcd`, you probably want to remove the old reporter before adding the new one.

**Comment by peastman** [comment]
Based on a skim through your code, it mostly looks correct.  Some of it is more complicated than it needs to be.  For example, your `getBox()` function doesn't need to reload and parse the PDB file.  It's already been loaded.  You can just write

```python
pos = pdb.positions.value_in_unit(nanometers)
range = np.max(pos, axis=0) - np.min(pos, axis=0)
```

You first create a Simulation letting OpenMM pick the platform, then create a second one where you specify to use CUDA.  That's redundant.  If CUDA is available, that's the platform it will pick for the first Simulation.

You don't need all the calls to `reinitialize()`.  Changing a Context parameter or the integrator temperature can be done at any time.  You only need to reinitialize the Context if you modify the System.

**Comment by pipitoludovico** [comment]
Thank you for your help!
I have amended the getBox() as you suggested. 
I was switching platforms because I was following the advice on #1857 (and also because GPU is usually faster in minimizing calculation, to the best of my knowledge?).

I will amend the code and see how it goes...and see if I don't lose the cell info on the "easing restraints" part.

Thank you again!

**Comment by peastman** [comment]
That advice isn't necessary anymore.  If it encounters forces that are too large, it will automatically switch to CPU for just that evaluation.  Anyway, you aren't using CPU.  You let it pick the platform itself, and it picks CUDA whenever possible.

**Comment by pipitoludovico** [comment]
Thank you again! I have changed the whole code as follows:

`from sys import stdout

import numpy as np
import openmm as mm
import openmm.app as app
from openmm.unit import *

# load the PDB and PSF
pdb = app.PDBFile('NEUTRAL_fis.pdb')
topology = app.CharmmPsfFile('NEUTRAL_fis.psf')

# get box size for PBC
pos = pdb.positions.value_in_unit(nanometers)
boxLength = np.max(pos, axis=0) - np.min(pos, axis=0)
x, y, z = boxLength[0], boxLength[1], boxLength[2]
topology.setBox(x * nanometer, y * nanometer, z * nanometer)
# set of parms...
params = app.CharmmParameterSet(
    '/home/scratch/MD_utilities/toppar_c36_jul20/top_all36_prot.rtf',
    '/home/scratch/MD_utilities/toppar_c36_jul20/par_all36_prot.prm',
    '/home/scratch/MD_utilities/toppar_c36_jul20/par_all36_cgenff.prm',
    '/home/scratch/MD_utilities/toppar_c36_jul20/top_all36_cgenff.rtf',
    '/home/scratch/MD_utilities/toppar_c36_jul20/par_all36_lipid.prm',
    '/home/scratch/MD_utilities/toppar_c36_jul20/top_all36_lipid.rtf'
)

# we create the system
print('Building the system...')
system = topology.createSystem(params, nonbondedMethod=PME, nonbondedCutoff=1 * nanometer,
                               constraints=HBonds, rigidWater=True)

# set the simulation settings
integrator = mm.LangevinIntegrator(300 * kelvin, 1 / picosecond, 0.002 * picoseconds)
GPU_platform = mm.Platform.getPlatformByName('CUDA')
properties = {'DeviceIndex': '0,1', 'Precision': 'mixed'}
simulation = app.Simulation(topology.topology, system, integrator, GPU_platform, properties)
# setting initial position and initializing the reporter to print out our data
simulation.context.setPositions(pdb.positions)
simulation.reporters.append(app.StateDataReporter(stdout, 1000, step=True, potentialEnergy=True, temperature=True))

print('\nAdding restraints to Name CA')
restraint = mm.CustomExternalForce('k', )
restraint.addGlobalParameter('k', 5.0 * kilocalories_per_mole / nanometer ** 2)
restraint.addGlobalParameter('t0', 0.0 * picoseconds)
restraint.addPerParticleParameter('x0')
restraint.addPerParticleParameter('y0')
restraint.addPerParticleParameter('z0')
for atom in pdb.topology.atoms():
    if atom.name == 'CA':
        restraint.addParticle(atom.index, pdb.positions[atom.index].value_in_unit(nanometers))
system.addForce(restraint)

print('\nMinimizing local energy...')
simulation.minimizeEnergy(tolerance=0.1 * kilojoule / mole)
# we snapshot the final state
state = simulation.context.getState(getPositions=True, getVelocities=True, getParameters=True,
                                    getIntegratorParameters=True)

simulation.reporters.pop(-1)
# Minimization finished: we now switch to GPU for the actual simulation.
integrator_GPU = mm.LangevinIntegrator(300 * kelvin, 1 / picosecond, 0.002 * picoseconds)

simulation.reporters.append(app.StateDataReporter(stdout, 1000, step=True, potentialEnergy=True, temperature=True))
# and we inherit our results from minimization...
simulation.context.setState(state)

print('\nWarming up the complex with the restraints...')
T = 5
mdstepsT = 6200
for i in range(62):
    temperature = (T + (i * T)) * kelvin
    integrator.setTemperature(temperature)
    simulation.step(int(mdstepsT / 62))

print('\nEquilibrating with restraints and temperature...')
simulation.context.setVelocitiesToTemperature(300 * kelvin)
simulation.reporters.append(app.DCDReporter('equilibrated.dcd', 1000, enforcePeriodicBox=True))
simulation.step(10000)


simulation.reporters.pop(-1)
state = simulation.context.getState(getPositions=True)

simulation.reporters.append(app.DCDReporter('equilibration1.dcd', 1000, enforcePeriodicBox=True))
print('\n10 cycles easing "k" restraint...:')
for i in range(10):
    simulation.context.setParameter('k', (-i * 0.5 * kilocalories_per_mole / nanometer ** 2))
    positions = state.getPositions()
    simulation.step(1000)
simulation.reporters.pop(-1)
print('\nEquilibrating NPT with k=0: ')
checkpointReporter = app.CheckpointReporter('output_x.chk', 1000)
simulation.context.setParameter('k', 0)
simulation.reporters.append(app.DCDReporter('equilibration2.dcd', 1000, enforcePeriodicBox=True))
simulation.step(10000)
`
Later on I will tweak this a bit more, but for now to me this issue is closed.
I just wanted to thank you for your help!
If you feel like any of this could be useful for someone else, I'd be more than happy to help!
Thank you!

**Comment by peastman** [comment]
Glad you got it working!
