### ISSUE TITLE
Protein flying away when using MonteCarloBarostat

### ISSUE THREAD

**Issue by asiomchen** [openmm/openmm#4021]
Hi, I starting to explore OpenMM and want implement simple pipeline using input files from *CHARMM-GUI* to simulate protein-ligand complex in NPT ensemble with position restrains, from my point of view this includes following:
* add restrains as `CustomExternalForce`:
```python
def add_backbone_posres(system, positions, atoms, restraint_force):
  force = CustomExternalForce("k*periodicdistance(x, y, z, x0, y0, z0)^2")
  force_amount = restraint_force * kilocalories_per_mole/angstroms**2
  print(f'Backbone posres k: {force_amount}')
  force.addGlobalParameter("k", force_amount)
  force.addPerParticleParameter("x0")
  force.addPerParticleParameter("y0")
  force.addPerParticleParameter("z0")
  for i, (atom_crd, atom) in enumerate(zip(positions, atoms)):
    if atom.name in  ('CA', 'C', 'N'):
      force.addParticle(i, atom_crd.value_in_unit(nanometers))
  posres_sys = deepcopy(system)
  posres_sys.addForce(force)
  return posres_sys
```
* minimize complex and run **NVT** simulation to stabilize temperature ( up do this step everything works smoothly)
* add barostat to system, reinitialize context and run **NPT** and after this run production **NPT**. - here strange thing happens, in early stages protein is flying away up to 5A and then keeps this distance, while ligand stays in place whole time, I believe, that this is somehow connected to #1854 , but have no idea how to deal with it
```python
barostat = MonteCarloBarostat(p, T, 25)
system.addForce(barostat)
simulation.context.reinitialize(preserveState=True)
print('Running NPT equilibration...')
simulation.step(NPT_steps)
```
RMSD plot for backbone and ligand
![image](https://user-images.githubusercontent.com/41703271/229623260-d7d86905-24a2-4f69-8709-98fa9a0385c9.png)

Whole code is available here: 
[barostat_issue.zip](https://github.com/openmm/openmm/files/11142390/barostat_issue.zip)

My supervisor is not really interested in helping me with thesis, so you would appreciate any help

**Comment by z-gong** [comment]
I have a similar issue. When MonteCarloBarostat is applied, some molecules jump between images occasionally, making the calculation of diffusion complicated.

>  I'd guess the molecule is just getting reimaged to a different box.

With these two fixes (https://github.com/openmm/openmm/pull/3260 and https://github.com/openmm/openmm/pull/3490), the trajectory is excepted to be continuous. Is there any other internal mechanism to reimage the molecules?

**Comment by asiomchen** [comment]
@peastman thank you a lot it helped, @z-gong in my case solution was to use `image_molecules()` method on trajectory to translate molecules:
```python
import mdtraj as md
top = md.load(path + 'step3_pbcsetup.pdb')
dcd = md.load_dcd('lyz_jz4_sol.dcd', top=top)
#solution
dcd.image_molecules(inplace=True)
#... rmsd calculation
```
And now RMSD and visualization looks good
![image](https://user-images.githubusercontent.com/41703271/229721427-87b87909-f158-414b-850f-1331d92e356b.png)

**Comment by peastman** [comment]
> Is there any other internal mechanism to reimage the molecules?

It might just be the reporter doing it on output.  Try adding the argument `enforcePeriodicBox=False` to the reporter.

**Comment by asiomchen** [comment]
I'm closing it, because the described issue was solved
