### ISSUE TITLE
conda-forge openmm_dev channel is missing Python 3.11

### ISSUE THREAD

**Issue by bdenhollander** [openmm/openmm#4026]
The [main channel](https://anaconda.org/conda-forge/openmm/files?channel=main) has py311 builds but [openmm_dev](https://anaconda.org/conda-forge/openmm/files?channel=openmm_dev) has py310 as the newest Python version.

I was able to install the dev version by specifying `python=3.10`, which forced mamba to downgrade the environment from Python 3.11.

**Comment by mattwthompson** [comment]
Could you open this as an issue on the feedstock repo? https://github.com/conda-forge/openmm-feedstock/issues

**Comment by bdenhollander** [comment]
OK, opened https://github.com/conda-forge/openmm-feedstock/issues/104.

**Comment by mikemhenry** [comment]
Closed with https://github.com/conda-forge/openmm-feedstock/pull/106

**Comment by mikemhenry** [comment]
@peastman you can close this issue

**Comment by peastman** [comment]
Thanks!
