### ISSUE TITLE
MonteCarloBarostat reimages molecules

### ISSUE THREAD

**Issue by z-gong** [openmm/openmm#4032]
I'm using the following script to simulate a box of 60 molecules. Each molecule contains 50 particles. When `MonteCarloBarostat` is applied, some molecules are jumping between cells. This jumping does not happen if the barostat is commented out. It seems that the barostat is forcing the center of each molecule to stay in the main cell.

```python
import sys
import numpy as np
from openmm import openmm as mm, app

pdb = app.PDBFile('omm-top.pdb')
with open('omm-sys.xml')  as f:
    system = mm.XmlSerializer.deserializeSystem(f.read())
system.addForce(mm.MonteCarloBarostat(1.0, 300.0))

integrator = mm.LangevinMiddleIntegrator(300.0, 1.0, 0.01)
platform = mm.Platform.getPlatformByName('CUDA')
properties = {'CudaPrecision': 'mixed'}
sim = app.Simulation(pdb.topology, system, integrator, platform, properties)
sim.context.setPositions(pdb.positions)
sim.minimizeEnergy(tolerance=100.0)

sim.reporters.append(app.StateDataReporter(sys.stdout, 1000, step=True, temperature=True, density=True, separator='\t'))
sim.reporters.append(app.DCDReporter('dump.dcd', 1000, enforcePeriodicBox=False))
positions_prev = sim.context.getState(getPositions=True, enforcePeriodicBox=False).getPositions(asNumpy=True)._value
for i in range(10):
    sim.step(1000)
    state = sim.context.getState(getPositions=True, enforcePeriodicBox=False)
    positions = state.getPositions(asNumpy=True)._value
    box_length = state.getPeriodicBoxVectors()._value[0][0]
    if np.any(positions - positions_prev > box_length * 0.8):
        print('  Jump')
    positions_prev = positions
```

These are two adjacent snapshots taken from the DCD output.

![image](https://user-images.githubusercontent.com/379616/231389943-2e76f96d-e911-4966-b78d-5530d94eea4f.png)

I'm using OpenMM 8.0.0 installed from conda-forge. The PDB and XML files to reproduce the issue are attached.

[pdb-xml.zip](https://github.com/openmm/openmm/files/11208531/pdb-xml.zip)

**Comment by sef43** [comment]
Note that this does not happen with the Reference/CPU platform. So this is differing behaviour between CPU/Reference and CUDA/OpenCL code

**Comment by peastman** [comment]
Thanks for the excellent test case!  This was a bit subtle, but having such a clear test made it easy to track down.

Internally, molecules always get wrapped to a single periodic box to improve accuracy.  It keeps track of how many box widths they've been translated by so it can put them back when you call `getState()`.  Every 250 force/energy evaluations, it checks all the positions and updates the wrapping if necessary.

If that wrapping happened to take place during the barostat step, and if it caused a molecule to move to a different periodic box, and if the barostat then rejected the step, the list of offsets wouldn't get restored correctly.  That would cause the molecule to jump to a different periodic box.

The fix is in #4034.

**Comment by z-gong** [comment]
This fix works well. Thanks a lot!

**Comment by z-gong** [comment]
This fix may have broken the `MonteCarloAnisotropicBarostat`
```python
import sys
import numpy as np
from openmm import openmm as mm, app

pdb = app.PDBFile('omm-top-linked.pdb')
with open('omm-sys-linked.xml')  as f:
    system = mm.XmlSerializer.deserializeSystem(f.read())
# system.addForce(mm.MonteCarloBarostat(1.0, 300.0))
system.addForce(mm.MonteCarloAnisotropicBarostat([1.0] * 3, 300.0))

integrator = mm.LangevinMiddleIntegrator(300.0, 1.0, 0.01)
platform = mm.Platform.getPlatformByName('CUDA')
properties = {'CudaPrecision': 'mixed'}
sim = app.Simulation(pdb.topology, system, integrator, platform, properties)
sim.context.setPositions(pdb.positions)
sim.minimizeEnergy(tolerance=100.0)

sim.reporters.append(app.StateDataReporter(sys.stdout, 100, step=True, temperature=True, density=True, separator='\t'))
sim.reporters.append(app.DCDReporter('dump.dcd', 100, enforcePeriodicBox=False))
sim.step(10000)
```

With the pull request #4034 , the system blows up in less than 2000 steps. But if I replace the `MonteCarloAnisotropicBarostat` with the `MonteCarloBarostat`, the simulation runs smoothly.
With OpenMM 8.0.0, the simulation does not blow up with either barostat, even though some molecules are jumping around.

The PDB and XML files to reproduce the issue are attached.
[pdb-xml-anisotropic.zip](https://github.com/openmm/openmm/files/11269523/pdb-xml-anisotropic.zip)

**Comment by z-gong** [comment]
The system does not crash with `MonteCarloAnisotropicBarostat` if I use the  revision immediately before the fix

**Comment by peastman** [comment]
Wow, that was a subtle one!  It took a long time to track down.  The fix is in #4049.  Could you test it and verify it now works for you?

**Comment by z-gong** [comment]
Yes, this fix works. Thanks a lot!

**Comment by peastman** [comment]
Thanks!  The fix is merged.
