### ISSUE TITLE
CharmmParameterSet generator unpacking

### ISSUE THREAD

**Issue by pipitoludovico** [openmm/openmm#4033]
Hail everyone!
I am trying to use a generator to pass a list of file paths to CharmmParameterSet the following way:

```
extensions = ('prm', 'rtf')
prmTops = ['/scratch/ludovico3/mwsumd/openMM_version/parameters/' + str(parFile) for parFile in os.listdir('/scratch/ludovico3/mwsumd/openMM_version/parameters') if parFile.endswith(extensions)]

pars = app.CharmmParameterSet(*prmTops).condense()

system = topology.createSystem(params, nonbondedMethod=PME, nonbondedCutoff=0.9*nanometer, switchDistance=0.75*nanometer, constraints=HBonds, rigidWater=True, hydrogenMass=4*amu)
```

But it returns the following error:
```
system = topology.createSystem(pars, nonbondedMethod=PME, nonbondedCutoff=0.9*nanometer, switchDistance=0.75*nanometer, constraints=HBonds, rigidWater=True, hydrogenMass=4*amu)
  File "/home/pipitol/.conda/envs/openMM/lib/python3.10/site-packages/openmm/app/charmmpsffile.py", line 1228, in createSystem
    force.addParticle(atm.charge, sigma_scale*atm.type.rmin*length_conv,
TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'

```
OpenMM version 8.0.0
python version: 3.10.10

What am I missing?
Thank you!

**Comment by peastman** [comment]
Can you provide your full script and the files needed to reproduce it?

**Comment by pipitoludovico** [comment]
[files.zip](https://github.com/openmm/openmm/files/11220112/files.zip)

Thank you so much for your reply!
Here they are!

I was wondering if it wouldn't be appropriate to tweak the CharmmParameterSet class so that it identifies if args is a generator and automatically unpacks all the iterable in it.
Thank you again!

**Comment by peastman** [comment]
You didn't include the parameter files.  I can't run the script without them.

I think it's very unlikely that the problem has anything to do with using a list comprehension.  Based on the error message, it's much more likely there's a problem in one of your files.

**Comment by pipitoludovico** [comment]
Sorry here are the parameter files, thank you!
[toppar.zip](https://github.com/openmm/openmm/files/11225355/toppar.zip)

If I put the filenames one by one it works fine, but the list comprehension returns that error instead.
Thank you again!

**Comment by peastman** [comment]
I get an error when I try to expand your zip file:

```
Archive:  toppar.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of toppar.zip or
        toppar.zip.zip, and cannot find toppar.zip.ZIP, period.
```

**Comment by pipitoludovico** [comment]
[toppar_2.zip](https://github.com/openmm/openmm/files/11225881/toppar_2.zip)
Sorry, see if this goes now.

Thank you!

**Comment by peastman** [comment]
I'm not seeing the problem.  When I run your script, `createSystem()` returns successfully.  (I didn't try running any further than that.)

**Comment by pipitoludovico** [comment]
![image](https://user-images.githubusercontent.com/67153855/231867186-c852f80f-7f84-4092-9520-fff97025fbf9.png)
I have just tried and it still doesn't work :( 
The "parameter" folder is one level above the cwd.

**Comment by peastman** [comment]
What do you mean by specifying the files one by one?  What is the value of `prmTops` when it works?  If you print out the two values, the one that works and the one that doesn't, it should be clear what the difference is.

Here is the output I get.

```
toppar/top_all36_cgenff.rtf toppar/par_all36_prot.prm toppar/par_all36_cgenff.prm toppar/top_all36_lipid.rtf toppar/par_all36_lipid.prm toppar/top_all36_prot.rtf
/Users/peastman/miniconda3/envs/openmm/lib/python3.9/site-packages/openmm/app/charmmparameterset.py:391: UserWarning: Replacing dihedral <DihedralType: k=1.3; phase=180.0; per=3> with <DihedralType: k=0.3; phase=180.0; per=3>
  warnings.warn('Replacing dihedral %r with %r' %

Building the system...

Adding restraints to Name CA
```

**Comment by pipitoludovico** [comment]
Sorry for the late reply!
What I mean is that if instead of using  list comrephension
```
`prmTops = ['parameters/' + str(parFile) for parFile in os.listdir('parameters') if parFile.endswith(extensions)]
    params = CharmmParameterSet(*prmTops)
`
```
I do:
```
` prmTops = app.CharmmParameterSet(
    '/home/scratch/MD_utilities/toppar_c36_jul20/top_all36_prot.rtf',
    '/home/scratch/MD_utilities/toppar_c36_jul20/par_all36_prot.prm',
    '/home/scratch/MD_utilities/toppar_c36_jul20/par_all36_cgenff.prm',
    '/home/scratch/MD_utilities/toppar_c36_jul20/top_all36_cgenff.rtf',
    '/home/scratch/MD_utilities/toppar_c36_jul20/par_all36_lipid.prm',
    '/home/scratch/MD_utilities/toppar_c36_jul20/top_all36_lipid.rtf'
)
`
```
it works although both ways should be accepted.

Thank you!

**Comment by peastman** [comment]
A list comprehension is just another way of creating a list.  Can you print out the list it creates?

**Comment by pipitoludovico** [comment]
The following lines:
```
extensions = ('rtf','prm')
prmTops = ['./parameters/' + str(parFile) for parFile in os.listdir('./parameters') if parFile.endswith(extensions)]
for prmTop in prmTops:
    print(prmTop)
params = CharmmParameterSet(*prmTops)

```

prints:
```
./parameters/par_all36_lipid.prm
./parameters/par_all36_prot.prm
./parameters/top_all36_lipid.rtf
./parameters/top_all36_prot.rtf
./parameters/par_all36_cgenff.prm
./parameters/top_all36_cgenff.rtf
```

and produces this error:
```
Traceback (most recent call last):
  File "/scratch/ludovico3/openMM/openmm_equilibration/ludovico/myEq.py", line 33, in <module>
    params = CharmmParameterSet(*prmTops)
  File "/home/pipitol/.conda/envs/openMM/lib/python3.10/site-packages/openmm/app/charmmparameterset.py", line 148, in __init__
    for par in pars: self.readParameterFile(par, permissive=permissive)
  File "/home/pipitol/.conda/envs/openMM/lib/python3.10/site-packages/openmm/app/charmmparameterset.py", line 575, in readParameterFile
    raise RuntimeError('Atom type %s not present in AtomType list' %
RuntimeError: Atom type NHL not present in AtomType list
```
Thank you for your patience!

**Comment by peastman** [comment]
You're loading files from different locations in the two cases.  In one case they're in `/home/scratch/MD_utilities/toppar_c36_jul20`, and in the other they're in `./parameters`.  Are you sure the files are identical?  Try using the comprehension to load the files from `toppar_c36_jul20`.

**Comment by pipitoludovico** [comment]
Yes, I have copied those files from `/home/scratch/MD_utilities/toppar_c36_jul20`.
However, I have also tried to use the list comprehension from toppar_c36_jul20 and it produced a similar error with a different atom type:

```
Traceback (most recent call last):
  File "/scratch/ludovico3/openMM/openmm_equilibration/ludovico/myEq.py", line 34, in <module>
    params = CharmmParameterSet(*prmTops)
  File "/home/pipitol/.conda/envs/openMM/lib/python3.10/site-packages/openmm/app/charmmparameterset.py", line 148, in __init__
    for par in pars: self.readParameterFile(par, permissive=permissive)
  File "/home/pipitol/.conda/envs/openMM/lib/python3.10/site-packages/openmm/app/charmmparameterset.py", line 575, in readParameterFile
    raise RuntimeError('Atom type %s not present in AtomType list' %
RuntimeError: Atom type SPT not present in AtomType list

**Comment by peastman** [comment]
There are two other obvious differences.

1. The files are listed in a different order.
2. They're specified with relative paths rather than absolute ones.

Try testing each of those to see if it's responsible.  Specify the files individually as before, but specify them with relative paths instead of absolute ones.  Does it work?  Now try specifying them in the order the list comprehension produces.  Does it work?

**Comment by pipitoludovico** [comment]
I have tried the order (both rtf then prm, or type in sequence (lipid lipid, prot prot etc etc) in any possible combination.

It seems to work only in these cases:
```
params = app.CharmmParameterSet(
    "parameters/par_all36_prot.prm",
    "parameters/top_all36_prot.rtf",
    "parameters/par_all36_cgenff.prm",
    "parameters/top_all36_cgenff.rtf",
    "parameters/par_all36_lipid.prm",
    "parameters/top_all36_lipid.rtf")
```

or 

```
params = app.CharmmParameterSet(
    '/home/scratch/MD_utilities/toppar_c36_jul20/par_all36_prot.prm',
    '/home/scratch/MD_utilities/toppar_c36_jul20/top_all36_prot.rtf',
    '/home/scratch/MD_utilities/toppar_c36_jul20/par_all36_cgenff.prm',
    '/home/scratch/MD_utilities/toppar_c36_jul20/top_all36_cgenff.rtf',
    '/home/scratch/MD_utilities/toppar_c36_jul20/par_all36_lipid.prm',
    '/home/scratch/MD_utilities/toppar_c36_jul20/top_all36_lipid.rtf'
)
```
List comprehension (sorted, reported "as it is", "reverse") doesn't work regardless of relative or absolute path.

```
extensions = ('rtf','prm')
prmTops_unsorted = ['parameters/' + str(parFile) for parFile in os.listdir('parameters/') if parFile.endswith(extensions)]
prmTops = sorted(prmTops_unsorted)
for prmTop in prmTops:
    print(prmTop)
print('\nCHECK')
params = CharmmParameterSet(*prmTops)
```
Thank you for your patience

**Comment by peastman** [comment]
This is pushing my knowledge of CHARMM files, but here's what's going on.  The files `par_all36_lipid.prm` and `par_all36_prot.prm` each define a type with the name `CEL1`.  The lipid file defines it as

```
MASS  -1  CEL1      12.01100 ! for alkene; RHC=CR
```

and then in the `NONBONDED` section defines nonbonded parameters for it:

```
CEL1     0.0       -0.068     2.09   ! alkene, yin,adm jr., 12/95
```

The protein file also defines a type with that name,

```
MASS  -1  CEL1       12.01100
```

but does not define any nonbonded parameters for it.  The result therefore depends on the order the files get processed in.  If the lipid file is processed second, it overwrites the incomplete definition from the protein file, and therefore it works.  But if the protein file is processed second, it overwrites the earlier definition with its incomplete type, leading to an error.

Is it legal in CHARMM to load multiple files that define types with the same name?  I can't find any mention of the possibility in the documentation.

**Comment by pipitoludovico** [comment]
Sorry for the late reply! From my experience, usually the engine take the "last declared" parameter and use it over the system. So even if you have duplicates, the last one will dictate the variables.

One way around could be to strictly load the necessary parameters in a single file but I have never tried this route (or use a single file that "contains" everything). I'm trying to experiment and figure out how to use OpenMM in the meantime.
Thank you for your support!

**Comment by peastman** [comment]
Parameters yes, but what about types?  If we find two different declarations for types with the same name, are we supposed to treat them as the same type, or does it indicate files are being combined that aren't meant to be used together?

**Comment by pipitoludovico** [comment]
To the best of my knowledge, this indicates that the files combined aren't meant to be used together to avoid reference issues.

From what I've seen if an atomtype is defined twice the last definition is used anyway and a warning is reported.

**Comment by pipitoludovico** [comment]
In any case: the order in which  CHARMM files are processed matters and it will require a couple of tries and adjustments.
If you feel like, feel free to close this issue.
Thank you very much for your help!
