### ISSUE TITLE
Integrate Alchemical Transfer Method (ATM) plugin into OpenMM main?

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#4040]
I'd like to propose we consider bringing in @egallicc's excellent Alchemical Transfer Method (ATM) plugin into the main OpenMM repo.

ATM has now been extensively validated for computing absolute ([[1]](https://pubs.acs.org/doi/10.1021/acs.jctc.1c00266) [[2]](https://link.springer.com/article/10.1007/s10822-021-00437-y) [[3]](https://pubs.acs.org/doi/full/10.1021/acs.jctc.9b01119)) and relative ([[1]](https://pubs.acs.org/doi/full/10.1021/acs.jcim.3c00178) [[2]](https://pubs.acs.org/doi/full/10.1021/acs.jcim.1c01129)) binding affinities.

@egallicc has created an [OpenMM plugin](https://github.com/Gallicchio-Lab/openmm-atmmetaforce-plugin) that is currently distributed separately, but (1) ensuring full compatibility with OpenMM releases and conda packages is challenging, (2) the current [LGPL license](https://github.com/Gallicchio-Lab/openmm-atmmetaforce-plugin/blob/main/LICENSE) may limit use, and (3) there may be opportunities to further generalize the `ATMMetaForce` when bringing it in to OpenMM to further expand its domain of use.

Currently, the API supports creating an `ATMMetaForce` object that mixes the current potential `U(x)` and a translated potential `U(x + direction)` according to a fixed expression:
```python
atmforce = ATMMetaForce(lambda1, lambda2,  alpha * kilojoules_per_mole, u0/kilojoules_per_mole, w0coeff/kilojoules_per_mole, umsc/kilojoules_per_mole, ubcore/kilojoules_per_mole, acore, direction, atmvariableforcegroups )
```
The `atmvariableforcegroups` specifies the force groups represented by `U(x)`. 

The functional forms that the parameters `alpha`, `u0`, `w0coeff`, `umsc`, `ubcore`, `acore` appear in are fixed expressions (reproduced below).

Integration with OpenMM would solve (1), which would also allow us to deploy it easily on Folding@home.

With the permission of @egallicc, we could incorporate this with a license compatible with OpenMM (such at MIT) to solve (2).

Are there opportunities to further generalize the implementation for (3)? Some thoughts:
* Is the current API that accepts a set of force groups the appropriate approach here, or would an API reminiscent of `CustomCVForce`---where forces are added to the `ATMMetaForce` one at a time---be more appropriate?
* Are there opportunities to generalize the expression involving the various parameters (`alpha`, `u0`, `w0coeff`, `umsc`, `ubcore`, `acore`) using a `Custom*Force` API? That is, we could have an `atmExpression` argument that would allow the user to specify some global context parameters (such as `lambda`) and provide others as constants, enabling a variety of samplers (such as replica exchange or nonequilibrium switching) that control global parameters to be used with ATM.
* Are there opportunities to generalize the transformation applied to the coordinates? Currently, there is a fixed displacement specified per particle. Is there some utility in generalizing this? For example, the displacement operations could also be generalized with `Custom*Force` expressions to allow other kinds of displacements that depend on global parameters.
* Is there utility in generalizing the _number_ of displacement states that are combined? Instead of two states, what if we could have three? One could envision translating a ligand from a protein environment to a solvent environment to a lipid bilayer inside a single simulation, or between a whole array of protein binding sites.
* Any other ideas?

![image](https://user-images.githubusercontent.com/3656088/233474560-abadad82-6931-4866-b90c-4e4f8d163964.png)
![image](https://user-images.githubusercontent.com/3656088/233474717-5206a820-0cc4-4fdf-9e39-c1e47451f989.png)

**Comment by peastman** [comment]
Thanks for opening this.  @egallicc I'd be interested to hear your thoughts on the questions above.  Based on your experience with the method, which generalizations do you think would be useful and which would just add complexity without practical benefit?

**Comment by egallicc** [comment]
Thank you, @jchodera and @peastman. Integrating ATM into OpenMM would be great for the community. I'm looking forward to working together to make it happen. And I agree that It would also be a great opportunity to further enhance and expand ATM's features. 

Yes, prior to integration, we should relax ATM's plugin license to make it compatible with OpenMM. I will proceed with MIT if it is the most suitable choice and there are no objections.

Yes, fundamentally, ATM works like CustomCVForce by defining a target perturbed potential energy function U<sub>1</sub>(x). The perturbation energy is then simply u(x) = U<sub>1</sub>(x) - U<sub>0</sub>(x), where U<sub>0</sub>(x) is the reference unperturbed potential. Everything else follows from this. The other fundamental ingredient is the relation between U<sub>1</sub>(x) and U<sub>0</sub>(x). As you mentioned, the current API is limited to a displacement coordinate transformation and the selection of the System's Forces that enter the calculation of the perturbation energy (the Nonbonded Force typically).

All the enhancements you mentioned would be great to consider:

1. Generalizing the API to explicitly specify the Forces that go into U<sub>1</sub>(x) would be a very useful enhancement. One could imagine, for example, a transformation in which the ligand is translated while, at the same time, a transfer of charge between two chemical groups occurs. This could be accomplished by providing a copy of the Nonbonded Force with different charge parameters, for example.

2. Generalizing the form of the alchemical perturbation potential energy function could also be a very useful enhancement. The softplus function works great for binding processes. But in other circumstances, other functions and parameterizations could be more appropriate. Functions of only the perturbation energy W<sub>λ</sub>(u) have particularly favorable properties, and I recommend sticking with this ansatz to start, unless we have specific applications in mind that require something more elaborate.

3. Complex coordinate transformations could be a powerful way to model some processes. Affine transformations (translation + rotations) come to mind to, for example, relate alternative binding poses. We would need to devise derivative chaining to propagate gradients. (Fixed coordinate displacements are straightforward in this respect.)

4. The current ATM implementation is already being used to transfer molecules from one receptor to another and from one phase to another. It works surprisingly well. @peastman can confirm, but I think there is no limit in principle on the number of inner Contexts that could be created to define multiple target states,  U<sub>1</sub>(x), U<sub>2</sub>(x), U<sub>3</sub>(x), ..., composed of individual Forces, with different parameters, and coordinate transformations. Each would be associated  with a perturbation energy u<sub>1</sub>(x) , u<sub>2</sub>(x) , u<sub>3</sub>(x), ...  and the  alchemical perturbation potential energy would then generalize to a function of many variables: W<sub>λ1,λ2,λ3,...</sub>[u<sub>1</sub>(x) , u<sub>2</sub>(x) , u<sub>3</sub>(x), ...]

There are likely other interesting things to explore. This is already a lot to think about.

The challenge is to devise an API that is general enough to cover these ideas while not so cumbersome that it becomes unintelligible. I feel that the customCVForce API has essentially most of what we are talking about except for the coordinate transformation. I wonder if we should consider just adding a coordinate transformation feature to customCVForce. [That's where it all started, after all.](https://github.com/openmm/openmm/issues/3045#issuecomment-789064720)

**Comment by jchodera** [comment]
Excellent points @egallicc.

There's another important use case to make sure we can accommodate: Applying ATM to ML/MM potentials built with the openmm-ml package.

**Comment by egallicc** [comment]
> There's another important use case to make sure we can accommodate: Applying ATM to ML/MM potentials built with the openmm-ml package.

Yes, absolutely. Are there specific requirements to support ML potentials? In addition to the trained model, it's just the atomic coordinates. Right?

ATM should be able to support any many-body potential without change. Polarizable potentials, QM/MM, ML, etc. They could be tested immediately with the [current plugin](https://github.com/Gallicchio-Lab/openmm-atmmetaforce-plugin) before integration. @sheenam1509 recently tested implicit solvent models. They work as expected.

**Comment by egallicc** [comment]
@peastman : any thoughts about the suggestions of a coordinate transformation applied optionally to Forces?

Something like a setCoordinateTransformation method of the Force class? If present, the transformation is applied to the system's coordinates before computing the Force. A chain rule would be applied to the resulting gradients. A _N_ to _N_ transformation would probably result in a significant performance loss in evaluating the matrix/vector multiplication. However, a coordinate transformation involving a small number of particles (such as a ligand's atoms) would be easier to handle, presumably.

The CoordinateTransformation API could be similar to that of customCompoundBonfForce where the x, y, z coordinates of a set of particles are transformed into new values. Unlike Forces, the CoordinateTransformation expression would return multiple values (the new values of the coordinates) rather than a single value. 

Anyway, it seems to me that the ATM Meta Force could be implemented as a customCVForce where a coordinate transformation is applied to a subset of the input Forces. If modifying the Force class itself is overkill, maybe the coordinate transformation option could be limited to customCVForce.

**Comment by jchodera** [comment]
> Are there specific requirements to support ML potentials? In addition to the trained model, it's just the atomic coordinates. Right?

The openmm-ml package currently constructs the ML/MM system in a particular way using a CustomCVForce, I believe. We just want to make sure that it's easy to mix and match ATM and ML/MM, or at least provide helper functions/classes to make that easy.

**Comment by egallicc** [comment]
> The openmm-ml package currently constructs the ML/MM system in a particular way using a CustomCVForce, I believe.

Interesting. I don't know if ATM can be given a customCVForce. They both make use of "inner" Contexts. Is there a minimum example we could test with the ATM plugin? 

More generally: can a customCVForce be one of the CVs for another customCVForce?

**Comment by egallicc** [comment]
Any thoughts regarding implementing ATM as a special customCVForce with a coordinate transformation, @peastman?

The choice is, I think, between (i) a nearly verbatim integration of the existing ATM plugin with its limited features or (ii) a more integrated implementation using a new coordinate transformation API. I would rather invest my efforts in the second option if it is at all possible/feasible.

**Comment by peastman** [comment]
I think we want to keep it as a separate class, rather than trying to force it into CustomCVForce.  It has unique features, and will likely get more in the future.  I do think we should consider making the API more like CustomCVForce, where you add the Forces to it directly rather than adding them to the System and then specifying their force groups.  I think that will be a cleaner and potentially less confusing API.  This does imply a conceptual change in how you think about it.  Instead of *adding a perturbation* to the existing energy, you are *interpolating the energy between two states*.  Do you think this makes sense?

So I think this is the list of API changes we're considering.

1. Add the forces directly to the ATMMetaForce.  This is fundamental to the API, so we need to decide one way or the other.
2. Allow specifying a rotation as well as translation.  This could potentially be added later.  But it also should be pretty easy to add now.  How useful do you think it is?
3. Allow specifying multiple coordinate transformations.  Same as above.
4. Allow different Forces for the different states.  I'm less clear on how this would work or what applications it's needed for.
5. Allow different forms for the energy function.  I'm also not too clear on what this would be used for.

**Comment by jchodera** [comment]
Can you clarify 4 and 5? I'm not quite sure how these map to what we discussed above.

Also, would CustomCVForce be combinable with CustomATMForce? Could you have one inside the other?

**Comment by jchodera** [comment]
Another question is how we envision this working with ML/MM systems from openmm-ml (presuming we may need to rework how openmm-ml creates hybrid systems)

**Comment by peastman** [comment]
> Can you clarify 4 and 5?

Those refer to

> Generalizing the API to explicitly specify the Forces that go into U1(x) would be a very useful enhancement. One could imagine, for example, a transformation in which the ligand is translated while, at the same time, a transfer of charge between two chemical groups occurs. This could be accomplished by providing a copy of the Nonbonded Force with different charge parameters, for example.

and

> Generalizing the form of the alchemical perturbation potential energy function could also be a very useful enhancement. The softplus function works great for binding processes. But in other circumstances, other functions and parameterizations could be more appropriate.

> Also, would CustomCVForce be combinable with CustomATMForce?

CustomCVForce would be no different from any other force.  It wouldn't require any special handling.

> Another question is how we envision this working with ML/MM systems from openmm-ml (presuming we may need to rework how openmm-ml creates hybrid systems)

A TorchForce would work exactly like any other force.  Building systems with ATMMetaForce is probably outside the scope of OpenMM-ML.  But once it builds a standard system for you, creating a new system in which some forces are moved into an ATMMetaForce would work the same as for any other force.

**Comment by egallicc** [comment]
> I think we want to keep it as a separate class, rather than trying to force it into CustomCVForce. It has unique features, and will likely get more in the future.

 Agreed.

>I do think we should consider making the API more like CustomCVForce, where you add the Forces to it directly rather than adding them to the System and then specifying their force groups. I think that will be a cleaner and potentially less confusing API.

Yes, I think this should be a primary design goal.

> This does imply a conceptual change in how you think about it. Instead of _adding a perturbation_ to the existing energy, you are _interpolating the energy between two states_. Do you think this makes sense?

I think it all fits well. The ATM Force does not do the interpolation. It provides the perturbation potential energy W(x) and its gradients. The other system Forces, the ones not given to the ATM Force, define the portion of the potential energy U0(x) that does not change upon the coordinate transformation. The total potential is then U0(x) + W(x).

It will be up to the user to ensure that a Force given to the ATM Force is not inadvertently retained in U0(x). For example, if the user gives a NonBonded Force to ATM because they want it to change upon the coordinate transformation, the same Force should not be part of U0(x).

> 2. Allow specifying a rotation as well as translation.  This could potentially be added later.  But it also should be pretty easy to add now.  How useful do you think it is?
> 3. Allow specifying multiple coordinate transformations.  Same as above.

Generalized coordinate transformations would be extremely useful, I think. Implementing rotations is probably just as complex as implementing any other transformation. The main issue is, of course, the gradients for the chain rule. The gradients of a rotation around a coordinate-dependent axis are not straightforward. We might as well tackle the general case, I think.

I will address 4 and 5 in separate comments.

**Comment by peastman** [comment]
> The other system Forces, the ones not given to the ATM Force, define the portion of the potential energy U0(x) that does not change upon the coordinate transformation. The total potential is then U0(x) + W(x).

Maybe I'm misunderstanding.  In your current implementation, you add all forces directly to the system, including the one that computes $U_0(x)$.  Right?  And therefore when you evaluate the energy, it gets included automatically.  And then the ATMMetaForce computes $W_\lambda(x)$, which is a function of both $U_1(x)$ and $U_0(x)$, and is intended to be added to $U_0(x)$ (which is already included).

In the alternate implementation, the force would not be added to the system.  It would be contained within the ATMMetaForce, which would be responsible for adding all terms to the energy including $U_0(x)$.

> We might as well tackle the general case, I think.

What would be the general case?  Aside from parity transformations, a rotation and translation are already the most general transformation that doesn't distort the internal geometry of the molecule.  What else would be useful?

**Comment by egallicc** [comment]
> What would be the general case? Aside from parity transformations, a rotation and translation are already the most general transformation that doesn't distort the internal geometry of the molecule. What else would be useful?

There is a lot that can be done with those. But there are others that we are already exploring. 

The point is that a Force capable of taking a general coordinate transformation x --> y  among a set of atoms and that could compute the gradients of U(y(x)), would implement standard transformations as well as those that we have not yet considered.

Do we have tools that could be adapted to accomplish something like this?

**Comment by peastman** [comment]
Are you thinking of letting the user specify arbitrary nonlinear transformations `f(x)`?  I don't think that's practical.  To apply the forces we need to invert the transformation, which we don't know how to do for arbitrary functions.  We could try to do it numerically, but there's no guarantee the function is invertible at all.  And any nonlinear transformation will distort the internal geometry of the molecule.  I can't think of any situation where someone would want that.

**Comment by egallicc** [comment]
Why would the inverse be needed? The transformed Force returns U(y) and the gradients dU/dx = dU/dy dy/dx.

**Comment by peastman** [comment]
Maybe you're right.  Though it still leaves the question, is there ever a situation where a nonlinear transform would be useful?  Conversely, are there useful cases that couldn't be handled that way?  For moving a molecule between two binding pockets, I would think any transform that depends only on $x$ wouldn't be sufficient.  Wouldn't you want to define a coordinate system based on the atoms in one pocket, a different coordinate system based on the atoms in the other, and then specify a transformation between those two coordinate systems?

**Comment by egallicc** [comment]
Well, if the placement and orientation of a coordinate frame depend on a set of atoms, a linear transformation _R_ in that frame would depend in general on the positions of those atoms. That is _R = R(x)_. Then the transformation _y  = R x = R(x) x_ would be non-linear.

**Comment by peastman** [comment]
It would be linear in the positions of the atoms being translated, and thus wouldn't distort the internal geometry.  You're translating the ligand based on a coordinate frame defined by the binding pocket: different atoms.

**Comment by egallicc** [comment]
Right. Nevertheless, we would still need to calculate the gradients of the transformed force with respect to the atoms that define the reference frames. Even though their coordinates are not changed, they influence the positions of the transformed atoms.

I appreciate that there might not be a straightforward way to handle a general coordinate transformation _y(x)_ in an automated fashion. A solution could involve some kind of numerical back-propagation algorithm. On the other hand, an analytical formulation of combinations of reflections, rotations, and translations relative to moving molecular frames could be already too complex to consider at this stage.

Shall we integrate the ATM plugin as is with fixed displacements and revisit this issue later?

**Comment by jchodera** [comment]
Here's my understanding of the API components we're considering:

Specify an arbitrary number of modified states and assign them names:
```python
atmforce.addState('U0')
atmforce.addState('U1')
atmforce.addState('U2')
```
Specify the expression for combining these state energies so that we can explore more general use cases or more optimal/statistically efficient expressions:
```python
# Define a suitable expression for an absolute binding free energy with global parameter 'lambda'
atmforce.addGlobalParameter('lambda', <value>)
atmforce.addGlobalParameter('lambda_1', <value>) # constant for ATM
atmforce.addGlobalParameter('lambda_2', <value>) # constant for ATM
atmforce.addGlobalParameter('alpha', <value>) # constant for ATM
atmforce.addGlobalParameter('u_0', <value>) # constant for ATM
atmforce.addGlobalParameter('w_0', <value>) # constant for ATM
atmforce.addGlobalParameter('u_max', <value>) # constant for ATM
energy_expression = """
U0 + W_lambda; 
u = U1 - U0; 
W_lambda = (lambda_2 - lambda_1) / alpha * log(1 + exp(-alpha*(u_sc - u_0))) + lambda2*u_sc + w_0;
u_sc = step(u_0 - u) * u + step(u - u_0) * (u_max - u_0) * f_sc + u_0;
f_sc = (z^a - 1) / (z^a + 1);
z = 1 + 2*y/a + 2*(y/a)^2;
y = (u - u_0) / (u_max - u_0);
"""
atmforce.setEnergyExpression(energy_expression)
```
Specify the transformation we want for each state, and consider allowing affine transformations since they are still linear (so the chain rule makes it easy to calculate forces):
```python
# U0 has no transformation by default
# Specify that state U1 is only a translation by providing an natoms x 3 array of the transformation vectors for each atom
atmforce.setTranslation('U1', translation_vectors)
# Specify that state U2 is an affine transformation by providing an natoms x 4 x 4 array specifying the 4x4 affine transformation for each atom
# This feature could be added later
atmforce.setAffineTransformation('U2', affine_transformation)
```
Add the forces directly to the `ATMMetaForce` like `CustomCVForce`:
```python
atmforce.addForce(force)
```
We could potentially allow different `Force` objects for the different states, but we should figure out how useful this would be. For example, do we want to be able to translate a ligand and switch its intramolecular energetics from MM to ML?
If we did want to do this, we could modify the API to specify the name of the state it is to be added to:
```python
# Add force to state U1
atmforce.addForce('U1', force)
```

One issue is that the ATMMetaForce handles a lot of the complexity of that energy expression for the user, while it would still be extremely useful to be able to generalize this and modify the energy expression. It's possible that a Python `ATMMetaForce` class with the same API as the current one could be included that uses the `CustomCVForce`-like API we discussed above to provide the same level of convenience for Python users as with the current plugin.

Another issue is that, to carry out ATM free energy calculations with ML/MM systems, we would need to change how `openmm-ml` creates modified systems. Is it possible to have a `CustomCVForce` be one of the `Force` objects that goes into the ATM force we are discussing above? If so, this might make things easy to combine.

**Comment by peastman** [comment]
We had a meeting to discuss this.  These were the main conclusions:

- We do want to let the user specify their own energy expression.  The API suggested above looks good.
- For the moment we're going to stick to simple lab frame translations.  It's possible we'll want to generalize it in the future (allow rotations, or allow the transformation to be defined in a local coordinate system), so we should consider how that API might look and make sure it can be implemented in the future while maintaining compatibility.
- We are not going to allow different forces for the different endpoints.
- We are not going to allow more than two endpoints.

**Comment by giadefa** [comment]
The main problem with the current code is that it is 3 times slower than a regular MD, while it should be two times slower. Raimondas pointed out that it is computing forces 3 times, so it is as fast as it should be. We think that it should be possible to be only two times slower, but maybe we are missing something. Let's chat today at the conference.

g

**Comment by peastman** [comment]
Let's enumerate the specific API changes.  They'll generally make it more similar to CustomCVForce.

First, the Forces will be directly added instead of specified by group.  That means we'll remove the `VariableForceGroups` constructor argument and the `getVariableForceGroups()` method.  And we'll add the following methods:

`int getNumForces() const`
`int addForce(Force* force)`
`Force& getForce(int index)`

Next, the energy expression will be user defined.  We'll remove the methods related to the old hardcoded parameters and add the following, which can be copied directly from CustomCVForce.

`const std::string& getEnergyFunction() const`
`void setEnergyFunction(const std::string& energy)`
`int getNumGlobalParameters() const`
`int addGlobalParameter(const std::string& name, double defaultValue)`
`const std::string& getGlobalParameterName(int index) const`
`void setGlobalParameterName(int index, const std::string& name)`
`double getGlobalParameterDefaultValue(int index) const`
`void setGlobalParameterDefaultValue(int index, double defaultValue)`

The energy expression will be an arbitrary function of the two energies `u0` and `u1` and whatever global parameters are defined.  The constructor will take a string for the energy expression instead of all the current hardcoded parameters.  On the other hand, we might want to also have a constructor similar to the current one that sets the default energy function and adds the appropriate global parameters.  If we expect that function to be appropriate in a lot of cases, that will save users effort.

Next we want to reconsider the API for defining the transformation, keeping forward compatibility in mind.  I don't completely understand the current API.  It has you specify a different displacement vector for every particle.  When would you want to displace different ones by different amounts?  Would a single global transformation for the whole molecule be sufficient?  There also is a global scalar parameter called `direction`.  How is that related?

**Comment by jchodera** [comment]
@peastman @egallicc : I spoke to @giadefa, who once again mentioned the performance considerations. For a pairwise-additive force field (e.g. reaction field), there's no reason ATM should be 2x as slow: The `Force`s could be partitioned into environment, ligand1-environment, and ligand2-environment, and all three set of interactions should barely take more than 1x the cost of a single system. However, the API we're considering doesn't support this kind of partitioning and reconstruction of total system energies to feed to ATM. If we allowed for multiple states and the possibility of different `Force`s associated with each state, we could easily get this performance gain. But there may be other ways to achieve this as well.

**Comment by egallicc** [comment]
> The main problem with the current code is that it is 3 times slower than a regular MD, while it should be two times slower. Raimondas pointed out that it is computing forces 3 times, so it is as fast as it should be. We think that it should be possible to be only two times slower, but maybe we are missing something.

Yes, it would be good to benchmark the plugin to see where the bottlenecks are. What's the best way to do it?

Yes, ATM calls the energy routines 3 times per time-step, but only twice involving the non-bonded Force. With multiple time stepping, it calls the nonbonded Force twice per outer time-step.

Anything significantly slower than 2X probably calls for investigation and optimization.

**Comment by peastman** [comment]
The best way of profiling is to run a short simulation script (10-20 time steps is fine) inside Nsight Systems.  It will display a timeline showing every kernel so you can see exactly where the time is being spent.

**Comment by mjschnie** [comment]
@jchodera and @peastman -- I'm really excited about the ATM framework by @egallicc for relative free energy calculations for polarizable force fields like AMOEBA, Drude, etc (and for relative polymorph free energies). Regarding #3757 and #1437 the proposal for using virtual sites to handle symmetry constraints -- I think this may be a "clean" solution, but I have some questions that maybe haven't come up? Do virtual sites "see each other"? If so, I think induced dipoles will be converged correctly, but the symmetry has not be leveraged to eliminate non-bonded interactions during the SCF and give a performance win. If the virtual sites do not see each other (i.e. real and virtual interact, but not virtual - virtual) then there is performance win, but we'll need to apply symmetry operators after each SCF cycle to update virtual site induced dipoles. Does this make sense?

**Comment by peastman** [comment]
As far as interactions are concerned, virtual sites are exactly like any other particle.  The only difference is that their positions are computed from other particles instead of being integrated directly.

**Comment by mjschnie** [comment]
@peastman  -- Understood - thank you! I believe this will lead to a symmetry implementation like that in CHARMM, where symmetry constraints are handled very elegantly, but where the real space compute cost is O(N_atomsites * Nsymm). An alternative approach (e.g., in CNS, Phenix, FFX, etc) is to try and achieve a real space compute cost of O(N_atomsites), but the drawback is increased code complexity. For example, I showed some free energy simulations yesterday of the small molecule CCDC crystal ACBNZA01, which needs 192 symmetry operators to satisfy a 12 A non-bonded cutoff.  Another example would be refinement of a large Ribosome crystal (e.g., https://www.rcsb.org/structure/4V4G from Jamie Cate) in the I422 space group. This has ~1 million atoms in the asymmetric unit and 8 space group symmetry operators, so you're looking at ~7 million virtual sites). Despite these extreme examples, my gut instinct is that the right way for the OpenMM community to go is to use virtual sites. Perhaps there could be an evolution toward a "flag" where virtual sites do not see each each to reduce redundant real space interactions (there are complexities to this for another day)?

**Comment by egallicc** [comment]
> For a pairwise-additive force field (e.g. reaction field), there's no reason ATM should be 2x as slow: The `Force`s could be partitioned into environment, ligand1-environment, and ligand2-environment, and all three set of interactions should barely take more than 1x the cost of a single system.

This is true. How common would this circumstance be? 

Presumably, it could be handled by providing to the ATM plugin a non-bonded Force involving only ligand-environment interactions.

**Comment by egallicc** [comment]
> First, the Forces will be directly added instead of specified by group. 

Agreed. 

Do you have any suggestions on how to "intercept" Forces added to the System by high-level APIs such as AmberPrmtopFile.createSystem()? It would be good to continue to take advantage of these facilities and cause the least disruption to existing users' workflows. I expect that in most circumstances, the user would want to give only the NonbondedForce to the ATM Force.

> Next, the energy expression will be user defined. 

Yes, thank you for summarizing the API. 

> The energy expression will be an arbitrary function of the two energies `u0` and `u1` and whatever global parameters are defined. 

Actually, unless there are alternative proposals, this function will take only the energy argument `u`, the perturbation energy, plus the global parameters.

> On the other hand, we might want to also have a constructor similar to the current one that sets the default energy function and adds the appropriate global parameters.

Yes, this is a good idea.

> I don't completely understand the current API. It has you specify a different displacement vector for every particle. When would you want to displace different ones by different amounts?

For example, two molecules are displaced in opposite directions in relative binding free energy calculations. I acknowledge that this has been the most complex setup so far. Is there a useful simplification here, you think? The current API gives each atom a displacement and is already quite clean. The atomic displacement defaults to (0, 0, 0) if not assigned.

> There also is a global scalar parameter called `direction`. How is that related?

This is one of the global parameters, similar to `lambda1`, `lambda2`, etc., [currently defining the alchemical energy expression](https://www.compmolbiophysbc.org/atom-openmm/the-science-behind-atom#h.3qeey5n7nhwi). It will not be part of the official API.

**Comment by peastman** [comment]
> Do you have any suggestions on how to "intercept" Forces added to the System by high-level APIs such as AmberPrmtopFile.createSystem()?

You don't intercept them, as such.  You just remove them and add a copy to the ATMMetaForce.

```python
atm.addForce(copy(system.getForce(i)))
system.removeForce(i)
```

> Actually, unless there are alternative proposals, this function will take only the energy argument u

Are you assuming the energy will have the form $U_0+f(U_1-U_0)$?  Why limit it?  The other version is more general and no more complicated.

> For example, two molecules are displaced in opposite directions in relative binding free energy calculations.

Can you explain how that works?

**Comment by egallicc** [comment]
> ```python
> atm.addForce(copy(system.getForce(i)))
> system.removeForce(i)
> ```

Thank you. This is good.

> Are you assuming the energy will have the form $U_0+f(U_1−U_0)$?

Yes

> Why limit it? The other version is more general and no more complicated.

I guess it goes to the core concept of a perturbative approach. All should follow from the change of the potential energy upon the perturbation, or its $\partial U/\partial \lambda$ equivalent. I can't think of an application requiring an alchemical potential energy function that depends on the individual potential energies before and after the perturbation.

Of course, the user could collect the individual `u0` and `u1` energy samples and take their difference to, for example, calculate the free energy change by multi-state reweighting. But this would add extra steps and additional API functions.

On this subject, similar to the plugin, the API will have `getPerturbationEnergy()` function to retrieve the value of the perturbation energy `u`. This is needed for the free energy calculation.

> 
> > For example, two molecules are displaced in opposite directions in relative binding free energy calculations.
> 
> Can you explain how that works?

In relative binding free energy calculations, the initial state corresponds to ligand A interacting with the receptor and ligand B interacting with the solvent. In the final state, it is the other way around. In ATM, this transformation is implemented by a coordinate transformation that swaps the positions of the two ligands initially placed in the binding site and in the solvent. [The general idea is explained here.](https://www.compmolbiophysbc.org/atom-openmm/the-science-behind-atom)

**Comment by peastman** [comment]
That makes sense.  Thanks.

**Comment by peastman** [comment]
This is in #4110.

**Comment by egallicc** [comment]
Thank you @peastman !

And thank you to @jchodera for getting the ball rolling.

We now have a new Force (ATMForce) to build free energy estimation applications using Alchemical Transfer. It is a generalized and more robust version of the [plugin](https://github.com/Gallicchio-Lab/openmm-atmmetaforce-plugin). The API is also significantly improved.

To maintain generality, ATMForce does not provide ancillary things such as restraints, free energy analysis, etc. to run binding free energy calculations. I plan to release a beta version of AToM-OpenMM using the new API soon for this purpose. Of course, everyone is welcome to build applications using ATMForce().

As discussed, ATMForce() is currently limited to linear atomic displacements in the lab frame. The design of the API attempts to facilitate the introduction of more complex coordinate transformations (rotations, etc.) down the road.

**Comment by egallicc** [comment]
[AToM-OpenMM](https://github.com/Gallicchio-Lab/AToM-OpenMM/tree/v8.0.0rc) has been ported to the ATMForce(). All the host-guest and protein-ligand binding free energy tests check out so far. The ATMForce() implementation looks good on our end.
