### ISSUE TITLE
Cost of CustomHbondForce

### ISSUE THREAD

**Issue by wayuer19** [openmm/openmm#4042]
Hi, 

I'm working on a multi-protein system with massive hydrogen bonds, using CustomHbondForce. But the test shows that almost half of the total time was spent on the calculation of hydrogen bonds (the sum of the donor force and acceptor forces). It will get worse and worse with the increase in system size, as shown in the figure below.
![image](https://user-images.githubusercontent.com/24451788/233815448-3091d1f8-a5ee-4d92-9e6a-8b368fe2286f.png)

This is the CustomHbondForce part of my script:
`
formula  = 'epsilon*(5.0*(sigma/r)^12-6.0*(sigma/r)^10)*swrad*cosd^4*swang; '+ \
'swrad = step(rcuton-r)+step(r-rcuton)*(step(rcutoff-r)-step(rcuton-r))*'+ \
'roff2*roff2*(roff2-3.0*ron2)/roffon2^3; '+ \
'roff2 = rcutoff*rcutoff-r*r; '+ \
'ron2 = rcuton*rcuton-r*r; '+ \
'roffon2 = rcutoff*rcutoff-rcuton*rcuton; '+ \
'rcutoff = CTOFHB; rcuton = CTONHB; r = distance(a1, d2); '+ \
'swang = step(cosdcuton-cosd)+step(cosd-cosdcuton)*(step(cosdcutoff-cosd)-step(cosdcuton-cosd))*'+ \
'cosdoff2*cosdoff2*(cosdoff2-3.0*cosdon2)/cosdoffon2^3; '+ \
'cosdoff2 = cosdcutoff*cosdcutoff-cosd*cosd; '+ \
'cosdon2 = cosdcuton*cosdcuton-cosd*cosd; '+ \
'cosdoffon2 = cosdcutoff*cosdcutoff-cosdcuton*cosdcuton; '+ \
'cosdcutoff = -cos(CTOFHA); cosdcuton = -cos(CTONHA); cosd = cos(angle(a1,d1,d2));'

Hforce = CustomHbondForce(formula)
Hforce.setNonbondedMethod(nbforce.getNonbondedMethod())
Hforce.addGlobalParameter('CTOFHB', 0.5*unit.nanometer)
Hforce.addGlobalParameter('CTONHB', 0.4*unit.nanometer)
Hforce.addGlobalParameter('CTOFHA', 91*unit.degree)
Hforce.addGlobalParameter('CTONHA', 90*unit.degree)
Hforce.addGlobalParameter('sigma', sigma_hb)
Hforce.addGlobalParameter('epsilon', eps_hb)
Hforce.setCutoffDistance(r_cut)

Ns, Hs, Os, Cs = [], [], [], []
for atom in psf.topology.atoms():
    if atom.name == "N" and atom.residue.name != 'PRO':
        Ns.append(int(atom.index))
    if atom.name == "H":
        Hs.append(int(atom.index))
    if atom.name == "O":
        Os.append(int(atom.index))
    if atom.name == "C":
        Cs.append(int(atom.index))

for idx in range(len(Hs)):
    Hforce.addDonor(Hs[idx], Ns[idx], -1)
    Hforce.addAcceptor(Os[idx], -1, -1)
system.addForce(Hforce)
`

Do you have any suggestions to improve the performance of CustomHbondForce. Or what should I do to improve the efficiency of the calculation of CustomHbondForce?

Thank you very much!

**Comment by peastman** [comment]
What is the value of `r_cut`?  That's going to have a big effect on the speed.

Could you edit your post to add lines with \``` immediately before and after the code?  Right now github is rendering it as markdown, which makes it hard to read.  If you can post a complete, working test case, that would be even better.

One thing that's hurting your performance a lot is all the global parameters.  Could some of them be made into constants?  For example, instead of the parameter

```python
Hforce.addGlobalParameter('CTONHA', 90*unit.degree)
```

add `CTONHA = {math.pi/2}` to the energy expression.  That will allow it to precalculate large parts of the expression.  It's only possible if the values won't change during the simulation, though.

**Comment by peastman** [comment]
I can't run your script, because you didn't include the input files for the CharmmParameterSet.

The cutoff distance for your CustomHbondForce is huge: 1.8 nm.  Typically the range of a hydrogen bond is only a few angstroms.  Is that really intended?

**Comment by wayuer19** [comment]
Sorry for the missing files. Cutoff of 1.8 nm is set for CustomNonbondedForce. The hydrogen bond force part was in line 109 to line 148, where the cutoff is 0.5 nm. 

Thank you so much!
[test.zip](https://github.com/openmm/openmm/files/11315766/test.zip)

**Comment by peastman** [comment]
> The hydrogen bond force part was in line 109 to line 148, where the cutoff is 0.5 nm.

That may be what you intended, but it's not what the code does.  You call `Hforce.setCutoffDistance(r_cut)`.  The value of `r_cut` is only ever set once, at line 29 when you set it to 1.8 nm.

I tested your script on a RTX 4080.  It gets 4560 ns/day.  If I remove the CustomHBondForce, it increases to 6720 ns/day, meaning the force is slowing it down by about 32%.

I then reduced the cutoff distance 0.5 nm.  That increased the speed to 4850 ns/day, about a 28% slowdown due to the force.

Finally I replaced the global parameters by constants as suggested above.  That gave another small speed increase to 4960 ns/day, a 26% slowdown.

At this point, I think the main issue is just that the system is too small to keep the GPU busy.  The kernels for CustomHbondForce use one thread for each donor or acceptor.  With only 49 donors and acceptors, there isn't enough work to fill even a single thread block.  So most of the GPU is sitting idle.

**Comment by wayuer19** [comment]
Your efforts are truly appreciated. I manage a significantly larger system consisting of around 3000 particles, and I have found that the slowdown caused by the HydrogenForce is considerably more significant in my case. On my RTX 2080ti, it runs at 250ns/day. However, when I eliminate the CustomHBondForce, the speed improves to approximately 1300ns/day. I have attached the details if you're interested. Furthermore, I am currently testing the cutoff distance as per your suggestion. Thank you for your valuable contribution!
[test.tar.gz](https://github.com/openmm/openmm/files/11339246/test.tar.gz)

**Comment by peastman** [comment]
Let me see what I can figure out.  CustomHbondForce doesn't get used that much, which means it tends to get passed by when we're doing optimizations.  It may be time to give it some attention.  There ought to be ways to make it scale better.

**Comment by peastman** [comment]
Note that your new script has the same problem as the old one: the cutoff is set much too large.  Reducing it to 0.5 nm speeds it up by 25%.

**Comment by wayuer19** [comment]
Yes, I'm testing using 0.5 nm. Thank you.

**Comment by peastman** [comment]
I have an improved implementation in #4060.  Can you try it out and see how it works for you?

**Comment by peastman** [comment]
@wayuer19 have you had a chance to try out the new implementation and see if it works better for you?

**Comment by wayuer19** [comment]
Hi, I have re-install OpenMM from the source code. But I got the same result as before. It's still 250 ns/day. And from the result of nvprof, it seems that nothing changed.
![image](https://github.com/openmm/openmm/assets/24451788/74a53244-b2da-4d23-b554-69767b7e3e64)

So I'm doubting that I have not compiled OpenMM with the improved implementation. But the result of "git log" shows the date is very new although I have not found "#4060" in the log.
![image](https://github.com/openmm/openmm/assets/24451788/b5226206-3d1c-4fa5-ab4d-b5e18a484ac7)

**Comment by sef43** [comment]
You will need to fetch the PR because it has not been merged into the main branch yet. The follow lines will do that:
```
git clone https://github.com/openmm/openmm.git
cd openmm
git fetch origin pull/4060/head
git checkout -b pr4060 FETCH_HEAD
```

**Comment by wayuer19** [comment]
> You will need to fetch the PR because it has not been merged into the main branch yet. The follow lines will do that:
> 
> ```
> git clone https://github.com/openmm/openmm.git
> cd openmm
> git fetch origin pull/4060/head
> git checkout -b pr4060 FETCH_HEAD
> ```

You are right. I also found it. Thank you so much.

**Comment by wayuer19** [comment]
I have tested the new improved CustomHbondForce. It works much better. Especially for the smaller system of GY-23, almost 3 times faster. For the bigger system, it was speeded up by 30%.
![image](https://github.com/openmm/openmm/assets/24451788/a11f25bb-1fba-40e6-8e8a-e835d954768e)

Thank you very much!

**Comment by peastman** [comment]
Great, thank you!
