### ISSUE TITLE
implicit solvent with pbc condition?

### ISSUE THREAD

**Issue by slweng0321** [openmm/openmm#4046]
Dear all,
I am running the implicit solvent simulation to relax my configuration. I use the code below:

pdb = app.PDBFile('protein.pdb')
​
forcefield = app.ForceField('amber99sbildn.xml', 'amber99_obc.xml')
​
system = forcefield.createSystem(pdb.topology, nonbondedMethod=app.CutoffNonPeriodic, constraints=app.HBonds)
integrator = mm.LangevinMiddleIntegrator(300*unit.kelvin, 1.0/unit.picoseconds, 2.0*unit.femtoseconds)
platform = mm.Platform.getPlatformByName('CUDA')
prop = dict(CudaPrecision='mixed') # Use mixed single/double precision
simulation = app.Simulation(pdb.topology, system, integrator, platform, prop)
​
simulation.context.setPositions(pdb.positions)
simulation.context.setVelocitiesToTemperature(300*unit.kelvin)
​
state = simulation.context.getState(getEnergy=True, getForces=True)

simulation.step(500000)
positions = simulation.context.getState(getPositions=True).getPositions()
app.PDBFile.writeFile(simulation.topology, positions, open('protein_relaxed.pdb', 'w'))

I have defined the box vector in the pdb file but when I checked the generated pdb with VMD, there were some overlap between periodic copies. Does this imply that the simulation didn't run with pbc condition or it ran correctly and just needed to run a longer time to  be equilibrium? 
Thanks for any help.

**Comment by peastman** [comment]
In the call to `createSystem()` you specified `nonbondedMethod=app.CutoffNonPeriodic`.  That means it does not use periodic boundary conditions, and the box vectors are ignored.  This is the normal way to run implicit solvent simulations.

**Comment by slweng0321** [comment]
Thanks for replying. So if I want to run implicit solvent relaxation with pbc condition, I just turn CutoffNonPeriodic to CutoffPeriodic and leave others the same?

**Comment by slweng0321** [comment]
Thanks for suggestion. I will try them. Now I think we can close this issue. Thanks again for your help.
