### ISSUE TITLE
Does openmm support forcefield like UFF?

### ISSUE THREAD

**Issue by OkKakao** [openmm/openmm#4057]
Hi

I'm trying to simulate phosphotunstic acid anion, which has a composition of [PW12O40]-3

This ion contains tungsten, which is not supported by common forcefield.

At first, I wanted to simulate it with rigidbody simulation, but my professor wants me to simulate it without such assumption...

I want to try forcefield like UFF, but I can't find how to simulate molecules with UFF forcefield with openmm.

Is there any possible way to simulate molecules with UFF?

Alternatively, if there is other possible methods, please let me know...

Thank you

**Comment by peastman** [comment]
So far as I know, no one has created an implementation of UFF for OpenMM.  In principle it could be done, though it would be a lot of work.

Note that UFF is a very old force field and not very accurate.  You might consider GFN-FF, which is a much more modern and accurate force field that also supports the whole periodic table.  Also not currently available in OpenMM, unfortunately.

**Comment by OkKakao** [comment]
Thanks!

I'll try xtb then.

Also, I found other forcefield from a paper.

I think that I should try both.
