### ISSUE TITLE
OpenMM 7.6 addSolvent() with padding parameter, but the solute not in center

### ISSUE THREAD

**Issue by tom-vanderboom** [openmm/openmm#4064]
When I followed *protein in water* tutorial in [openmm official site](https://openmm.github.io/openmm-cookbook/latest/notebooks/tutorials/protein_in_water.html), I used `modeller.addSolvent(forcefield, padding=1.0 * nanometer)` to add solvent around the protein, however, it seems that the solute did not appear in the center of the box. Just like this:
![图片](https://user-images.githubusercontent.com/51500479/236628756-bf1c0fd5-a114-4813-887c-61701f5961ae.png)

**Comment by sef43** [comment]
Hi, this is just the periodic boundary conditions, see the FAQ: https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#periodic

**Comment by tom-vanderboom** [comment]
Thank you for reply. The picture above shows the starting frame after the energy minimization step, does this mean that the protein is already outside the periodic boundary at the beginning of the simulation?

**Comment by peastman** [comment]
There is no "outside the periodic boundary".  Everything is inside, by definition.  The page linked above explains all of this.

**Comment by tom-vanderboom** [comment]
Ok, thank you for your patient in replying. I think I understand what happened.
