### ISSUE TITLE
system.remove forces does not work

### ISSUE THREAD

**Issue by dspoel** [openmm/openmm#4068]
Maybe I am doing something wrong, but  ```system.removeForce(0)``` does not remove the NonbondedForce for me. After calling it I do 
```
        for myforce in self.system.getForces():
            print(myforce.getName())
```
and NonbondedForce is still there. 
Some older posts suggest to set epsilon and charges to zero, but is that really the only way?

**Comment by peastman** [comment]
Can you show your complete code?  `removeForce()` is about as simple a method as you can get.  I don't see a lot of ways for it to fail.

https://github.com/openmm/openmm/blob/ed049af1b34cab4dd47f20dcfddb99bcad6c7913/openmmapi/src/System.cpp#L112-L116

**Comment by dspoel** [comment]
Never mind, I messed up my own script.
