### ISSUE TITLE
MonteCarloAnisotropicBarostat doesn't allow negative pressure

### ISSUE THREAD

**Issue by sef43** [openmm/openmm#4076]
`MonteCarloAnisotropicBarostat` does not allow negative pressures. The other MC Barostats do not seem to have this check. Is there a good reason for the Anisotropic one having this? I have a use case that needs negative pressure applied to the system and the box size to only change in one direction.

**Comment by peastman** [comment]
No, I just missed that one when I removed the other checks in #3870!
