### ISSUE TITLE
AmberPrmTop calls computePeriodicBoxVectors using same angle for alpha, beta, and gamma

### ISSUE THREAD

**Issue by lohedges** [openmm/openmm#4078]
I am trying to use OpenMM to run simulations using a rhombic dodecahedron box (both hexagonal and square forms). The system is prepared outside of OpenMM and the box is already in reduced form, using the approach by Wassenaar described [here](https://research.rug.nl/files/2839528/01_c1.pdf), which I believe is the same as is [used internally](https://github.com/openmm/openmm/blob/0607d41c18ee1b52efe872b7b951e097f670ad4e/wrappers/python/openmm/app/internal/unitcell.py#L83-L99) by OpenMM.

The entry point into OpenMM is AMBER format files, which I am loading with `AmberPrmTopFile` and `AmberInpcrdFile`. Internally these are calling the [computePeriodicBoxVectors](https://github.com/openmm/openmm/blob/d6cca3903aa0be02c105aed4febcfa2747f48fc1/wrappers/python/openmm/app/internal/unitcell.py#L40) function. In the case of the `AmberPrmTopFile`, the _same_ angle is being passed in for alpha, beta, and gamma when the function is called, even though the single angle in the topology file _only_ corresponds to beta, i.e. from the AMBER format specification:

```
%FLAG BOX_DIMENSIONS
%FORMAT(5E16.8)  OLDBETA, BOX(1), BOX(2), BOX(3)
  OLDBETA   : periodic box, angle between the XY and YZ planes in
              degrees. This is now redundant, as it is present in the
              inpcrd files. It is ignored here.
  BOX       : the periodic box lengths in the X, Y, and Z directions.
              This is now redundant, as it is present in the inpcrd files.
              It is ignored here.
```

For the system that I am using, this results in a crash when trying to compute `cz` within the function, since the argument to the square root is negative. Here is a modified version of the function that prints the angles passed to the function:

```python
def computePeriodicBoxVectors(a_length, b_length, c_length, alpha, beta, gamma):
    """Convert lengths and angles to periodic box vectors.

    Lengths should be given in nanometers and angles in radians (or as Quantity
    instances)
    """

    if is_quantity(a_length): a_length = a_length.value_in_unit(nanometers)
    if is_quantity(b_length): b_length = b_length.value_in_unit(nanometers)
    if is_quantity(c_length): c_length = c_length.value_in_unit(nanometers)
    if is_quantity(alpha): alpha = alpha.value_in_unit(radians)
    if is_quantity(beta): beta = beta.value_in_unit(radians)
    if is_quantity(gamma): gamma = gamma.value_in_unit(radians)

    # My debugging    
    print("#alpha            #beta             #gamma")
    print(alpha, beta, gamma)

    # Compute the vectors

    a = [a_length, 0, 0]
    b = [b_length*math.cos(gamma), b_length*math.sin(gamma), 0]
    cx = c_length*math.cos(beta)
    cy = c_length*(math.cos(alpha)-math.cos(beta)*math.cos(gamma))/math.sin(gamma)
    cz = math.sqrt(c_length*c_length-cx*cx-cy*cy)
    c = [cx, cy, cz]

    # If any elements are very close to 0, set them to exactly 0.

    for i in range(3):
        if abs(a[i]) < 1e-6:
            a[i] = 0.0
        if abs(b[i]) < 1e-6:
            b[i] = 0.0
        if abs(c[i]) < 1e-6:
            c[i] = 0.0
    a = Vec3(*a)
    b = Vec3(*b)
    c = Vec3(*c)

    # Make sure they're in the reduced form required by OpenMM.

    c = c - b*round(c[1]/b[1])
    c = c - a*round(c[0]/a[0])
    b = b - a*round(b[0]/a[0])
    return (a, b, c)*nanometers
```

If I run the following code snippet with [this](https://github.com/openmm/openmm/files/11536651/input.prm7.txt) topology file...

```python
from openmm.app import *

prmtop = AmberPrmtopFile("input.prm7")
```

...I get:

```python
#alpha            #beta             #gamma
2.094395224566243 2.094395224566243 2.094395224566243
Traceback (most recent call last):
  File "test.py", line 16, in <module>
    prmtop = AmberPrmtopFile('openmm.prm7')
  File "/home/lester/.conda/envs/openbiosim/lib/python3.10/site-packages/openmm/app/amberprmtopfile.py", line 156, in __init__
    top.setPeriodicBoxVectors(computePeriodicBoxVectors(*(box[1:4] + box[0:1]*3)))
  File "/home/lester/.conda/envs/openbiosim/lib/python3.10/site-packages/openmm/app/internal/unitcell.py", line 60, in computePeriodicBoxVectors
    cz = math.sqrt(c_length*c_length-cx*cx-cy*cy)
ValueError: math domain error
```

The code where beta is passed in for all three angles is [here](https://github.com/openmm/openmm/blob/d6cca3903aa0be02c105aed4febcfa2747f48fc1/wrappers/python/openmm/app/amberprmtopfile.py#L154-L156).

In the case of loading the [coordinate file](https://github.com/openmm/openmm/files/11536688/input.rst7.txt), the correct angles are used and all is okay, i.e.:

```python
from openmm.app import *

inpcrd =  AmberInpcrdFile("input.rst7")
```

gives:

```python
#alpha            #beta             #gamma
1.283997034776398 2.0943952315475602 1.5592498428195989
```
This issue is the same for all triclinic boxes, only the particular angles and box dimensions here happen to trigger the crash. For example, using a truncated octahedron box (I can post if needed) and running the following...

```python
# Load the topology and coordinate files.
prmtop = AmberPrmtopFile("test.prm7")
inpcrd = AmberInpcrdFile("test.rst7")

# Initialise the molecular system.
system = prmtop.createSystem(nonbondedMethod=PME,
                             nonbondedCutoff=1*nanometer,
                             constraints=HBonds)
```

...gives:

```python
#alpha            #beta             #gamma
1.2309592434098255 1.2309592434098255 1.2309592434098255
#alpha            #beta             #gamma
1.9106323821810383 1.2309592434098255 1.230959737338004
#alpha            #beta             #gamma
1.2309592434098255 1.2309592434098255 1.2309592434098255
```

Here `computePeriodicBoxVectors` is called three times, but only the second call (via `AmberInpcrdFile`) is correct. Later in my script the box vectors are set explicitly to the values in the coordinate file using:

```python
if inpcrd.boxVectors is not None:
    simulation.context.setPeriodicBoxVectors(*inpcrd.boxVectors)
```

This _doesn't_ call `computePeriodicBoxVectors`. Following a single step of simulation I have checked the box in the output DCD file and it does indeed match that of the coordinate file, as desired.

Are the calls to `computePeriodicBoxVectors` in `AmberPrmTopFile`, `AmberInpcrdFile`, and `AmberPrmTopFile.createSystem` necessary, and if so, is there a way to fix the call from `AmberTopFile` in the case of non-cubic boxes? In our case, we can work around this in two ways:

* Modify the topology file so that dummy cubic box values are written. This allows the topology to be loaded, then correct box values are set explicitly via the context as shown above.
* Monkey-patch `AmberPrmTopFile` so that `computePeriodicBoxVectors` is skipped.

Unfortunately it's not possible to simply remove the `BOX_DIMENSIONS` record from the topology file. (Here it is completely redundant, since the full information is in the coordinate file.) When this is done `AmberPrmTopFile` crashes with:

```python
Traceback (most recent call last):
  File "test.py", line 16, in <module>
    prmtop = AmberPrmtopFile('openmm.prm7')
  File "/home/lester/.conda/envs/openbiosim/lib/python3.10/site-packages/openmm/app/amberprmtopfile.py", line 155, in __init__
    box = prmtop.getBoxBetaAndDimensions()
  File "/home/lester/.conda/envs/openbiosim/lib/python3.10/site-packages/openmm/app/internal/amber_file_parser.py", line 653, in getBoxBetaAndDimensions
    beta=float(self._raw_data["BOX_DIMENSIONS"][0])
KeyError: 'BOX_DIMENSIONS'
```

Cheers.

**Comment by peastman** [comment]
I'm a bit confused about what the intended interpretation of the prmtop file is.  As you note, it only stores a single angle, which isn't enough for general triclinic boxes.  The documentation seems to suggest that the `BOX_DIMENSIONS` flag is obsolete and should be ignored?

The relevant code in OpenMM was written by @swails, who also wrote ParmEd.  Jason, do you have any insight on how to handle this?

**Comment by lohedges** [comment]
> I'm a bit confused about what the intended interpretation of the prmtop file is. As you note, it only stores a single angle, which isn't enough for general triclinic boxes.

Yes, exactly. It seems like the current code is assigning box vectors always assuming that the information from the prmtop file relates to a cubic box, which isn't the case in general. I've applied a fix on my fork [here](https://github.com/lohedges/openmm/commit/7275772209f75ce6a7c639f1b5d0323eead183f8). Let me know if this is satisfactory and I'll raise a PR. I'm not sure if there are any unintended consequences of not setting box information using the prmtop information if it is present, although I assume that this would always be set elsewhere anyway, i.e. using the info from the inpcrd.

Cheers.

**Comment by peastman** [comment]
@swails you added the code for triclinic cells in Amber files in #802.  That was a long time ago though!

When building a System and Topology from a prmtop file, we need to fill in default periodic box vectors.  If we don't, it will break things that look at the Topology to figure out whether the model is periodic.  I suggest making two changes.

1. When interpreting `BOX_DIMENSIONS`, set the two missing angles to pi/2 instead of beta.  I think that's how they were interpreted in Amber?
2. Allow the user to specify the box dimensions when constructing an AmberPrmtopFile object.  In that case, it will ignore the `BOX_DIMENSIONS` information and use the provided ones instead.  This is how GromacsTopFile works too.

Part 2 involves a few pieces:

1. Make code changes to AmberPrmtopFile and PrmtopLoader.  The API should be identical to GromacsTopFile.
2. Update documentation to show the new way of setting box vectors.  This will include at least the section in the user guide on loading Amber files, and the simulateAmber.py example script.  We also need to check for any other examples in the user guide, tutorials, and cookbook and update them.
3. Update OpenMM-Setup so it generates code using the new mechanism.

**Comment by lohedges** [comment]
Thanks @peastman, that makes sense. I think it would be great from a user perspective if the API of `AmberPrmtopFile` matches that of `GromacsTopFile`.

**Comment by peastman** [comment]
The code changes and documentation updates are in #4094.  Can you try it out and see if it works for you?

This leaves a few remaining steps:

1. Go through the tutorials and cookbook to see if anything needs to be updated.
2. Update OpenMM-Setup.

Those need to wait until we have a release that includes this change.

**Comment by lohedges** [comment]
Thanks, @peastman. I can confirm that the changes work for me :+1:

**Comment by peastman** [comment]
Thanks!  I merged the change.

**Comment by peastman** [comment]
I made the changes to OpenMM-Setup in https://github.com/openmm/openmm-setup/pull/35.  That means this is now complete and can be closed.
