### ISSUE TITLE
RPMDIntegrator is sometimes unreliable

### ISSUE THREAD

**Issue by cihe13375** [openmm/openmm#4080]
Summary: depend on the system size, number of beads and the hardware configuration, the position of atoms may change abruptly even with no external forces and timestep=0.

Please find a reproduce example here:
[repro_issue.tar.gz](https://github.com/openmm/openmm/files/11539566/repro_issue.tar.gz)
run it with: `python run_nve.py`

Theoretically the energy and position of atoms should not change since the timestep is zero. However, the position of atoms may change significantly as well as the energy. Below is a typical output on my own computer (GTX 1660Ti, 525.105.17, kubuntu 22.04):
```
# step time/ps temperature/k potential/Ha kinetic/Ha conserved/Ha
       0   0.0000  90.09187   0.00000 8424.47362 15560.05720
     100   0.0000  90.09187   0.00000 8424.47362 15560.05720
6.441516347877041e-06
     200   0.0000  90.09187   0.00000 8424.47362 15560.03001
0.02292674034833908
     300   0.0000  90.09187   0.00000 8424.47362 15560.03001
0.02292674034833908
     400   0.0000  90.09187   0.00000 8424.47362 15560.03001
0.02292674034833908
     500   0.0000  90.09187   0.00000 8424.47362 15560.00093
0.02292674034833908
     600   0.0000  90.09187   0.00000 8424.47362 15560.00093
0.02292674034833908
     700   0.0000  90.09187   0.00000 8424.47362 15560.00093
0.02292674034833908
     800   0.0000  90.09187   0.00000 8424.47362 15560.00093
0.02292674034833908
     900   0.0000  90.09187   0.00000 8424.47362 15560.00093
0.02292674034833908
    1000   0.0000  90.09187   0.00000 8424.47362 15560.00093
0.02292674034833908
    1100   0.0000  90.09187   0.00000 8424.47362 15560.00093
0.02292674034833908
    1200   0.0000  90.09187   0.00000 8424.47362 15560.00093
0.02292674034833908
    1300   0.0000  90.09187   0.00000 8424.47362 15560.00093
0.02292674034833908
    1400   0.0000  90.09187   0.00000 8424.47362 15560.00093
0.02292674034833908
    1500   0.0000  90.09187   0.00000 8424.47362 15559.90316
0.03205388784408569
    1600   0.0000  90.09187   0.00000 8424.47362 15559.90316
0.03205388784408569
    1700   0.0000  90.09187   0.00000 8424.47362 15559.90316
0.03205388784408569
    1800   0.0000  90.09187   0.00000 8424.47362 15559.85532
0.03205388784408569
```
The atom positions may change up to 0.03A, which cannot be explained by floating point errors. In real simulations, it results in the energy not conserving, or the diverge of simulation.

Note 1: the situation seems to be related to the system size and number of beads. The problem is seemingly gone if I use a smaller system, or change number of beads to 32.

Note 2: the problem is also seemingly depends on the hardware environment. Here are some test results from other machines:
1) RTX 2080Ti, 470.57.02: the problem only happens rarely (about once in ~1M steps), but once it occurs the simulation diverge like this:
```
# step time/ps temperature/k potential/Ha kinetic/Ha conserved/Ha
  904000 452.0000  49.94005 -886.52156 4669.8844 7310.3555
  906000 453.0000  50.05179 -889.38279 4680.3333 7299.3979
  908000 454.0000  49.98447 -891.64389 4674.0382 7290.6302
  910000 455.0000 120447793751.23415 1.9097571e+24 1.1263051e+13 1.9097571e+24
  912000 456.0000 123072457710.74934 2.2043167e+19 1.1508483e+13 2.2043181e+19
```
2) Tesla V100, 460.73.01: the simulation diverges at the first step if nbeads=64 or 60, but not for 32, 72, or 128.

Note 3: I'm not very sure on this, but the problem is seemingly gone if I comment out the following lines in `rpmd.cc`:
```
KERNEL void integrateStep(GLOBAL mixed4* posq, GLOBAL mixed4* velm, GLOBAL mm_long* force, mixed dt, mixed kT) {
    const int numBlocks = (GLOBAL_SIZE)/NUM_COPIES;
    const int blockStart = NUM_COPIES*(LOCAL_ID/NUM_COPIES);
    const int indexInBlock = LOCAL_ID-blockStart;
    const mixed nkT = NUM_COPIES*kT;
    const mixed twown = 2.0f*nkT/HBAR;
    const mixed forceScale = 1/(mixed) 0x100000000;
    LOCAL mixed3 q[2*THREAD_BLOCK_SIZE];
    LOCAL mixed3 v[2*THREAD_BLOCK_SIZE];
    LOCAL mixed3 temp[2*THREAD_BLOCK_SIZE];
    LOCAL mixed2 w[NUM_COPIES];

    // Update velocities.
    
    for (int particle = (GLOBAL_ID)/NUM_COPIES; particle < NUM_ATOMS; particle += numBlocks) {
        int index = particle+indexInBlock*PADDED_NUM_ATOMS;
        int forceIndex = particle+indexInBlock*PADDED_NUM_ATOMS*3;
        mixed4 particleVelm = velm[index];
        // comment out these lines
        // particleVelm.x += forceScale*force[forceIndex]*(0.5f*dt*particleVelm.w);
        // particleVelm.y += forceScale*force[forceIndex+PADDED_NUM_ATOMS]*(0.5f*dt*particleVelm.w);
        // particleVelm.z += forceScale*force[forceIndex+PADDED_NUM_ATOMS*2]*(0.5f*dt*particleVelm.w);
        if (particleVelm.w != 0)
            velm[index] = particleVelm;
    }
```
but how does this even makes sense since dt is zero anyway...

Note 3: I believe there was a post on SimTK forum on the same issue before, but it was abandoned probably because of being so weird...

Note 4: The problem seems to occur at both mixed and double precision, and both CUDA and OpenCL platform (at least for that Tesla V100, for some reason I cannot compile OpenCL on my own machine...).

**Comment by cihe13375** [comment]
I did some investigations today and here are my findings.
Disclaimer: I have little experience in CUDA programming, and the findings below are mostly based on my observation and online knowledge bases. I'm probably doing or explaining things wrongly.

So I used Compute Sanitizer to run the repro example above (after some work to enable `nvcc` debug flags for the runtime compilation): `compute-sanitizer --tool racecheck python3.10 run_nve.py`. And the output is like this:
```
========= COMPUTE-SANITIZER
# step time/ps temperature/k potential/Ha kinetic/Ha conserved/Ha
       0   0.0000  90.09187   0.00000 8424.47362 15560.05720
========= Error: Race reported between Read access at 0x33de0 in /tmp/openmmTempKernel0x55bd27a5fc10_790344.cu:1137:integrateStep
=========     and Write access at 0x3b880 in /tmp/openmmTempKernel0x55bd27a5fc10_790344.cu:1168:integrateStep [387072 hazards]
=========     and Write access at 0x3d670 in /tmp/openmmTempKernel0x55bd27a5fc10_790344.cu:1170:integrateStep [387072 hazards]
=========     and Write access at 0x40050 in /tmp/openmmTempKernel0x55bd27a5fc10_790344.cu:1172:integrateStep [387072 hazards]
=========     and Write access at 0x42a30 in /tmp/openmmTempKernel0x55bd27a5fc10_790344.cu:1174:integrateStep [387072 hazards]
========= 
========= Error: Race reported between Read access at 0x33e50 in /tmp/openmmTempKernel0x55bd27a5fc10_790344.cu:1137:integrateStep
=========     and Write access at 0x3b830 in /tmp/openmmTempKernel0x55bd27a5fc10_790344.cu:1168:integrateStep [387072 hazards]
=========     and Write access at 0x3d620 in /tmp/openmmTempKernel0x55bd27a5fc10_790344.cu:1170:integrateStep [387072 hazards]
=========     and Write access at 0x40000 in /tmp/openmmTempKernel0x55bd27a5fc10_790344.cu:1172:integrateStep [387072 hazards]
=========     and Write access at 0x429e0 in /tmp/openmmTempKernel0x55bd27a5fc10_790344.cu:1174:integrateStep [387072 hazards]
..... (with more similar outputs)
```
Compute Sanitizer points out race conditions like this at every step for 64 beads, and never for 32 or 72. The content of relevant lines are (I had to modify OpenMM source code so it doesn't delete on-the-fly generated code after compile):
```
KERNEL void integrateStep(GLOBAL mixed4 *posq, GLOBAL mixed4 *velm, GLOBAL mm_long *force, mixed dt, mixed kT)
{
    /* omitted */
    // Forward FFT.

        /* omitted */
        SYNC_THREADS;
        {
            LOCAL_ARG mixed3 *real0 = qreal;
            LOCAL_ARG mixed3 *imag0 = qimag;
            LOCAL_ARG mixed3 *real1 = &temp[blockStart];
            LOCAL_ARG mixed3 *imag1 = &temp[blockStart + LOCAL_SIZE];
            {   // Pass 1 (radix 4) (omitted)   }
            {   // Pass 2 (radix 4) (omitted)   }
            {   // Pass 3 (radix 4) (omitted)   }
                SYNC_THREADS;
            }
            real0[indexInBlock] = real1[indexInBlock];     // read access here
            imag0[indexInBlock] = imag1[indexInBlock];     // read access here
            SYNC_WARPS;
        }

        {
            LOCAL_ARG mixed3 *real0 = vreal;
            LOCAL_ARG mixed3 *imag0 = vimag;
            LOCAL_ARG mixed3 *real1 = &temp[blockStart];
            LOCAL_ARG mixed3 *imag1 = &temp[blockStart + LOCAL_SIZE];
            {
                // Pass 1 (radix 4)
                if (indexInBlock < 16)
                {
                    int i = indexInBlock;
                    int j = i / 1;
                    /* omitted */
                    real1[i + 3 * j * 1] = d0r + d2r;  // write access here
                    imag1[i + 3 * j * 1] = d0i + d2i;  // write access here
                    real1[i + (3 * j + 1) * 1] = multiplyComplexRealPart(w[j * 64 / 64], d1r + d3r, d1i + d3i);  // write access here
                    imag1[i + (3 * j + 1) * 1] = multiplyComplexImagPart(w[j * 64 / 64], d1r + d3r, d1i + d3i);  // write access here
                    real1[i + (3 * j + 2) * 1] = multiplyComplexRealPart(w[j * 128 / 64], d0r - d2r, d0i - d2i);  // write access here
                    imag1[i + (3 * j + 2) * 1] = multiplyComplexImagPart(w[j * 128 / 64], d0r - d2r, d0i - d2i);  // write access here
                    real1[i + (3 * j + 3) * 1] = multiplyComplexRealPart(w[j * 192 / 64], d1r - d3r, d1i - d3i);  // write access here
                    imag1[i + (3 * j + 3) * 1] = multiplyComplexImagPart(w[j * 192 / 64], d1r - d3r, d1i - d3i);  // write access here
                }
                SYNC_THREADS;
            } 
    /* omitted */
```
So the problem is probably that `SYNC_WARPS` is not synchronizing enough so the change to `real1` and `imag1` below (indeed values in the array `temp`) may affect the read accesses above. The read accesses above only appears if the FFT has an odd number of stages, so 60 (3x4x5) and 64 (4x4x4) are problematic, while 72 (2x3x3x4) and 128 (4x4x4x2) are fine. Anything <= 32 are also seemingly fine because `SYNC_WARPS` is probably enough in that case (since the wrap size is 32).
After changing the final `SYNC_WARPS` in `CommonRpmdKernels.cpp` to `SYNC_THREADS` the problem is seemingly gone (Compute Sanitizer does not report errors and the atom positions don't change abruptly in many steps). Or maybe the better solution is to insert a `SYNC_THREADS` between two consecutive FFT sections (like `FFT_Q_FORWARD` and `FFT_V_FORWARD`), though I had not tried that yet.

**Comment by peastman** [comment]
I've been unable to reproduce this.  Your script works correctly for me.  Here's the output with 64 beads:

```
# step time/ps temperature/k potential/Ha kinetic/Ha conserved/Ha
       0   0.0000  90.09187   0.00000 8424.47362 15560.05720
     100   0.0000  90.09187   0.00000 8424.47362 15560.05720
6.441516347877041e-06
     200   0.0000  90.09187   0.00000 8424.47362 15560.05720
6.441516347877041e-06
     300   0.0000  90.09187   0.00000 8424.47362 15560.05720
6.441516347877041e-06
...
```

If you change `SYNC_WARPS` to `SYNC_THREADS` at line 575 of CommonRpmdKernels.cpp, does that fix the problem for you?

**Comment by cihe13375** [comment]
1)
> I've been unable to reproduce this. Your script works correctly for me. Here's the output with 64 beads:

I think it's probably related to the specific hardware. In my tests the problem occurs almost immediately on a Tesla V100, but is much less frequent (but still exists) on a RTX2080Ti (see my first comment). Also cite from NVIDIA's [Computer Sanitizer documentation:](https://docs.nvidia.com/compute-sanitizer/ComputeSanitizer/index.html#racecheck-tool)

> [4. Racecheck Tool]
[4.2. What are Hazards?]... Race conditions manifest as intermittent application failures or as failures when attempting to run a working application on a different GPU.

2)
> If you change `SYNC_WARPS` to `SYNC_THREADS` at line 575 of CommonRpmdKernels.cpp, does that fix the problem for you?

Yes (at least seemingly), that's how I fixed the problem in my second post (verified on that Tesla V100).

**Comment by peastman** [comment]
If you want to open a pull request with that change, I think it would be fine.  There are already other calls to `SYNC_THREADS` inside that same block, so it ought to be safe.
