### ISSUE TITLE
using amber generated ligand parameter files to create system in OpenMM

### ISSUE THREAD

**Issue by 1heman** [openmm/openmm#4082]
Hi

I am trying to create a membrane bound protein-ligand system for MD. I have already generated the ligand parameter files using tleap.
I want to generate the system for MD using OpenMM where I believe I can easily add membrane using the `addMembrane` function.

Any inputs as to how I should go about doing this will be deeply appreciated.
Thanks,
Hemant

**Comment by peastman** [comment]
You can't mix the input pipelines.  You either need to build and parametrize your system entirely in AmberTools, or do it entirely in OpenMM.  There's no way to load a parametrized model from Amber files, add more molecules, and keep the parameters that were loaded from the files.

If you want to do everything in OpenMM, the [openmmforcefields](https://github.com/openmm/openmmforcefields) package provides template generators that can parametrize your ligand with either OpenFF or GAFF.

**Comment by 1heman** [comment]
I see. Thanks for the quick response. I'll try using the `openforcefields` package.
