### ISSUE TITLE
`Modeller.addSolvent`'s `numAdded` option forces the output periodic box to be cubic

### ISSUE THREAD

**Issue by yaoyic** [openmm/openmm#4085]
In the docstring of `openmm.app.Modeller.addSolvent` it says
```
boxShape: str='cube'
    the box shape to use.  Allowed values are 'cube', 'dodecahedron', and 'octahedron'.  If padding and numAdded
    are both None, this is ignored.
```
which implies that the boxShape can be set independently when using `padding` or `numAdded` to determine the box dimensions. However, when boxShape is not `"cube"` and `numAdded` is set, **the output periodic box is always cubic** and comes with much void space in the box. 

The cubic box vectors are set by this line
https://github.com/openmm/openmm/blob/c7efe3d48d005fa00124b4a13722f5df6b86b855/wrappers/python/openmm/app/modeller.py#L604
It looks like the functionality to add a predetermined number of solvent molecules is only considering cubic situation and will generate an unintended result for other box shapes.

The best thing to have is to update this functionality to properly deal with other box shapes as well. But if that does not fit your schedule, then maybe just raise an `Exception` when there is a combination of `numAdded` and `boxShape`

Relevant: PR #894

**Comment by peastman** [comment]
Thanks for catching this.  A fix is in #4086.  Can you try it out and confirm whether it fixes the problem for you?

**Comment by yaoyic** [comment]
Thanks a lot for your fast response and effective bug fix. It nicely solves the problem that I had, and the function works totally as expected.

**Comment by peastman** [comment]
Great, thanks!
