### ISSUE TITLE
Default values for AMOEBA polarization

### ISSUE THREAD

**Issue by piia600** [openmm/openmm#4092]
Hi,

I know that it is possible to select the polarization method in forcefield.createSystem by using the parameter polarization. However, I can't seem to find what are the default settings? So if I don't specify the polarization method and mutualInducedTargetEpsilon, what are their default values?

**Comment by piia600** [comment]
Thanks for the reply. Does the too large epsilon value cause some known issues in the simulations? Good to ask now that the simulations are done and I am trying to answer reviewers' questions.. 

Does the polarization type 0 mean that it is the "mutual"? It would probably be a good idea to put these in the documentation...

**Comment by peastman** [comment]
> Does the too large epsilon value cause some known issues in the simulations?

It leads to poor energy conservation, which means inaccurate statistics.

> Does the polarization type 0 mean that it is the "mutual"?

Correct.

**Comment by peastman** [comment]
I decreased the default value in #4098.  Sorry about that.  I think this value was chosen a very long time ago, back when the AMOEBA developers were trying to improve speed by using the largest value they could get away with.  But they eventually concluded it wasn't worth the loss in accuracy, and found better ways to speed it up.

**Comment by peastman** [comment]
Fixed by #4098.
