### ISSUE TITLE
TypeError: Cannot append item without units into list with units

### ISSUE THREAD

**Issue by evamartin1240** [openmm/openmm#4093]
When running this line:

`modeller.add(ligand.to_topology().to_openmm(), ligand.conformers[0])`

I get the following error:

```
  File "openmm/app/modeller.py", line 132, in add

    newPositions.append(deepcopy(addPositions[atom.index]))

  File "openmm/unit/quantity.py", line 773, in append

    raise TypeError("Cannot append item without units into list with units")

TypeError: Cannot append item without units into list with units
```

**Comment by jeff231li** [comment]
Hi @evamartin1240, I'm assuming you're using the OpenFF-Toolkit. This could be a conflict with the units of `ligand.conformers[0]`. Openmm units was replaced by OpenFF-Units (based on Pint) in the OpenFF-Toolkit since version 0.11. If this is case, try
```python
from openff.units.openmm import to_openmm

modeller.add(ligand.to_topology().to_openmm(), to_openmm(ligand.conformers[0]))

```

**Comment by evamartin1240** [comment]
Thank you very much @jeff231li , now it works!

**Comment by evamartin1240** [comment]
Thank you very much @jeff231li , now it works!
