### ISSUE TITLE
segmentation fault on mamba openmm install

### ISSUE THREAD

**Issue by dominicrufa** [openmm/openmm#4097]
hi, I'm seeing some weird behaviour when i mamba install openmm from conda forge: `mamba create -n openmm8-new -c conda-forge openmm` tries to install this: 
![image](https://github.com/openmm/openmm/assets/46943710/c09f6547-3342-4388-ac42-1ff42d747f69)
but trying to call python gives me a seg fault:

> (base) ~$ mamba activate openmm8-new
> (openmm8-new) ~$ python
> Segmentation fault

is there a known fix for this?

**Comment by sef43** [comment]
hmm my system installs the exact same environment and I do not get a seg fault. What happens if you just install python with mamba?
```bash
mamba create -n openmm8-new -c conda-forge python
mamba activate openmm8-new
python
```

**Comment by dominicrufa** [comment]
hm, im getting a seg fault again, so this isn't an openmm issue yet. sorry.

**Comment by jaketanderson** [comment]
What happens when you run this after creating the environment with mamba?
```
mamba activate openmm8-new
which python
```

And what about this?
```
conda activate openmm8-new
which python
```

You might also try activating with conda and see if it still seg faults:
```
conda activate openmm8-new
python
```

**Comment by dominicrufa** [comment]
this is a consequence of my having corrupted my conda env. closing as this is unrelated to omm
