### ISSUE TITLE
Can't follow up from equilibration.xml or .chk - Particle is NaN

### ISSUE THREAD

**Issue by pipitoludovico** [openmm/openmm#4101]
Good afternoon,
I have successfully run an enemy minimization and saved the final steps of the equilibration, the state and the checkpoint.

In the equilibration.py I try to run a local minimization, then equilibrate with restraints, only to gradually remove them in a third cycle.
After that I set the 'k' parameter to 0 and run a quick simulation, only to save the .chk and XML at the end.

However, there's no way I can start a new simulation from either the saved .chk or XML file from the second script production.py.

The system and the parameters are exactly the same but regardless of what I try, I get the "particle coordinate is NaN" error.
I have tried to restart it from both the XML and the chk file but to no avail.

I have already looked around the issues for a problem similar to mine (#3810, #3782, #3071) but none of the solutions are working.
I don't understand what's wrong with the scripts.

I am attaching the two scripts if anyone could help me figure out why they are not working.
Thank you for your help
[scripts.zip](https://github.com/openmm/openmm/files/11678521/scripts.zip)

Before I forget, these are the equilibration results for a system of around 120K atoms:

Building the system...

Adding restraints to Name CA

Minimizing local energy...

Warming up the complex with the restraints...
#"Step","Potential Energy (kJ/mole)","Temperature (K)"
1000,-2752885.8317084443,247.78040094284987
2000,-2624809.8317084443,283.85231988195557
3000,-2589489.8317084443,295.4573502811835
4000,-2578501.8317084443,298.47052432983327
5000,-2574951.8317084443,300.6906233151054
6000,-2575665.8317084443,300.7931635264231

Equilibrating with restraints and temperature...
7000,-2573230.8317084443,300.28196190126

10 cycles easing "k" restraint...:
8000,-2592358.8317084443,300.40054246281045

Equilibrating NPT with k=0:
9000,-2586026.8317084443,299.71134165983375

**Comment by sef43** [comment]
Hi, I can't reproduce this unless you also add the input files. 

However, looking at your script `OPENMM_production.py` its doesnt look quite right. 

You should be creating the `System` from the saved "system.xml" file and you should be using the `Simulation.loadcheckpoint` to read in the "checkpoint.chk" file

There is now a new example of restarting from a checkpoint in the OpenMM workshop. Take a look at this and see if you can get it working:
https://github.com/openmm/openmm_workshop_july2023/blob/main/section_1/protein_in_water.ipynb

**Comment by pipitoludovico** [comment]
Sorry for the late reply!
Following the link you sent I was able to move forward. 
Thank you!
