### ISSUE TITLE
Exclude specific waters from ion replacement `Modeller.addSolvent`

### ISSUE THREAD

**Issue by IAlibay** [openmm/openmm#4103]
In some systems, we have structurally significant waters (e.g. involved in binding site interactions), that we would like to keep during our simulations.

However, when calling `Modeller.addSolvent`, there is a chance that those waters could get picked up and replaced by ions in `_addIons`.

As far as I am aware, there is no way to avoid this beyond renaming your crystallographic waters to a residue name that isn't `HOH`. If this is indeed the case, I was wonder if it might be possible to consider an enhancement where we could either pass in a list of excluded residues, or maybe just tell `addSolvent` to not pick up any water residues that already existed ahead of calling it?

**Comment by peastman** [comment]
I'd call this a bug.  The intention was that only newly added waters would get replaced by ions.  Existing ones should be left alone.  That's how it used to work, but #2274 inadvertently changed the behavior.
