### ISSUE TITLE
Stop simulation on the fly when a value (of a CV/OP) is hit

### ISSUE THREAD

**Issue by bodhivani** [openmm/openmm#4107]
Hi!
Is there an easy way to add this functionality? I basically just want to stop the simulation when a specific condition for a CV I'm computing is reached (for instance to restrict simulations in Voronoi polyhedra)? (e.g. restrict a dihedral to being in $(0,\pi/2)$

There is an equivalent Plumed function, if that's clearer: https://www.plumed.org/doc-v2.8/user-doc/html/_c_o_m_m_i_t_t_o_r.html

Thank you!
Bodhi

**Comment by bodhivani** [comment]
Yes-- my question is, can I inspect the state on the fly and then quit the simulation midway through (before my total timesteps are up)? (this would be useful for methods like WE or NEUS)

One way I can imagine doing this is writing a custom reporter for this CV and then having a line in there that stops the simulation when a condition is met, but I'm not sure what that line would be.

Thank you for your quick response!

**Comment by peastman** [comment]
You can do something like this.

```python
for i in range(total_steps//100):
    simulation.step(100)
    if end_condition_reached():
        break
````

**Comment by bodhivani** [comment]
That's what I've currently implemented! I guess I'm a little concerned about the potential overhead of exiting to the API every 100 steps, but I haven't benchmarked it. I'll stick to this for now! Thanks!

**Comment by peastman** [comment]
Reporters are implemented in Python, so the overhead would be just as high.  The overhead from checking every 100 steps should be pretty small, though of course it depends on what your check involves and how expensive it is.  If you have any doubts, you can measure what the change in speed is.
