### ISSUE TITLE
Add timestep CLI option to `benchmark.py` example

### ISSUE THREAD

**Issue by hmacdope** [openmm/openmm#4111]
Recently benchmarking OpenMM against the OpenMM folding@home core (Core 22) on a set of matching benchmark systems, I ran into the issue that the timestep for the `benchmark.py` script is auto selected based on the benchmark type.

 It may be useful to add an option to fix the timestep to a certain value in the CLI rather than having it auto-generated. Would people be open to this?

**Comment by peastman** [comment]
See #4116.
