### ISSUE TITLE
Modeller.add ignores bond orders and types

### ISSUE THREAD

**Issue by zanebeckwith** [openmm/openmm#4112]
In Modeller.add ([modeller.py line 120](https://github.com/openmm/openmm/blob/add2bbeee88933f4ffe9066fb8a41fce561c8086/wrappers/python/openmm/app/modeller.py#L120)), the new bond ignores the old bond's `type` and `order`.

Would it be as easy as making this `newTopology.addBond(newAtoms[bond[0]], newAtoms[bond[1]], bond.type, bond.order)`?

Or is there something subtle I'm missing?

If it is that simple, I'm more than happy to submit a PR!

Thanks for the great project!

**Comment by peastman** [comment]
A PR would be great!  Yes, it's as easy as that.  Probably we just missed that line when we added support for bond types and orders

**Comment by zanebeckwith** [comment]
Ah, great!

> Probably we just missed that line when we added support for bond types and orders

I was hoping that was all it was!

I just opened PR #4113 with the little fix

Thanks!
