### ISSUE TITLE
Error adding membrane - NonbondedForce: There is already an exception for particles...

### ISSUE THREAD

**Issue by rosemary-cresset** [openmm/openmm#4114]
Hi, 

I am trying to add membrane to my system and running into the error: 

```
Traceback (most recent call last):
  File "/tmp/FieldEngine-rosemary.mantell/OpenMM_Force_Fields_1177440_1/test.py", line 8, in <module>
    modeller.addMembrane(force_field, lipidType='POPC', minimumPadding=1.0, neutralize=True)
  File "/home/rosemary.mantell/.conan/data/OpenMM/8.0.0/cresset/stable/package/ba107ff23e2262f45993d21b4b16ca56bd0b5dfc/python/openmm/app/modeller.py", line 1480, in addMembrane
    f1.addException(i+numMembraneParticles, j+numMembraneParticles, 0.0, 1.0, 0.0)
  File "/home/rosemary.mantell/.conan/data/OpenMM/8.0.0/cresset/stable/package/ba107ff23e2262f45993d21b4b16ca56bd0b5dfc/python/openmm/openmm.py", line 15377, in addException
    return _openmm.NonbondedForce_addException(self, particle1, particle2, chargeProd, sigma, epsilon, replace)
openmm.OpenMMException: NonbondedForce: There is already an exception for particles 200005 and 199992
```

A short example that reproduces the problem: 
```
import openmm
import openmm.app as app

pdb_file = app.PDBFile('input.pdb')
force_field = app.ForceField('amber/protein.ff14SB.xml', 'amber/lipid17.xml', 'amber/tip3p_standard.xml')
modeller = app.Modeller(pdb_file.topology, pdb_file.positions)
modeller.topology.setUnitCellDimensions((17.1, 11.4, 12.0872))
modeller.addMembrane(force_field, lipidType='POPC', minimumPadding=1.0, neutralize=True)
```

File input.pdb can be found [here](https://gist.github.com/rosemary-cresset/38fcef578c7428f3b7119e5ead9876c6). 

I had a bit of a look at the problem myself and it looks as though modeller._CellList.neighbors is intended to find 27 different cells, but at the point it crashes some of those cells seem to be the same. If the passed position is right on the boundary of the box it can find the same cell again. I managed to bypass this issue by changing line `return tuple((int(floor(pos[j]/self.cellSize[j]))%self.numCells[j] for j in range(3)))` in the cellForPosition function to `return tuple((int(floor(round(pos[j]/self.cellSize[j], 12)))%self.numCells[j] for j in range(3)))`, but I expect there is probably a more robust way of fixing this. 

I would appreciate your input on this. 

Thank you, 

Rosie

**Comment by peastman** [comment]
Thanks for the excellent debugging work.  You're right, this is a literal edge case.  Before calling `floor()`, one cell index is -25.0 and another is -24.000000000000004.  `floor()` turns both of them into -25.

My solution is to keep track of every cell it processes and make sure each one only gets processed once.  Can you take a look at #4120 and see if it looks right to you?

**Comment by rosemary-cresset** [comment]
If the position is right on the edge of a cell, I see that it is not necessary to find all 27 cells, so this solution makes sense for finding at least the neighbours within the cutoff distance. The change looks good to me - thanks very much!
