### ISSUE TITLE
Problem with jumping molecules

### ISSUE THREAD

**Issue by leeping** [openmm/openmm#4117]
I alluded to an issue with "jumping" molecules in #4071 and wanted to post a follow up.  It seems that the problem still exists after the barostat fix was merged in #4106.  The system is the same as I have been describing in the previous issue (8000 iAMOEBA water molecules @ 184 K and 1800 atm with a Monte Carlo anisotropic barostat along the z-direction).

In the following movies, I'm showing the trajectories of the water molecule O atoms in one octant of the box only.  The intended behavior is very slow diffusion because the temperature is very low.  The trajectory frames are written once per 10 ps.

The omm_75.mp4 movie shows the behavior I have been getting with versions 7.4 and 7.5, which is the expected behavior.  However, in omm_80.mp4 you can see that at certain times in the trajectory all of the molecules "jump" relatively large distances to new positions.  These jumps do not happen at every single barostat move because there are 100 attempts per trajectory frame written.  However it's possible that with every barostat move there is the possibility of a jump.  I have not tested with a NVT run but I will do that next.

When I analyze the trajectories, the diffusion coefficients calculated using the version 8.0 trajectory are too high, presumably because of the jumping problem.  However, the thermodynamic properties seem okay, which makes me think it's just the atom indices that are getting scrambled.  Please let me know if you have thoughts on next steps for tracking this down.

https://www.dropbox.com/s/usrbf58q370nk35/omm_75.mp4?dl=0
https://www.dropbox.com/s/i1d7nfjrvfth4o5/omm_80.mp4?dl=0

**Comment by sef43** [comment]
Can you please verify the git hash of the version you are using that shows the jumping behavior? and also provide an example script to reproduce?

I have made a similar test to what you have described. It computes the Mean Squared Displacement of atoms in a waterbox with NPT. The input files are attached.


I have plotted the MSD for three code versions:
- 8.0 release  (SHA a7800059645f4471f4b91c21e742fe5aa4513cda). This shows incorrect behavior due to the original wrapping issue #4032 .
- 8.0dev4 the latest version installed from `conda-forge/label/openmm_dev` (SHA a6c3641861896e69db584e4e0e87f70d37389252). This shows incorrect behavior due to the atom indices getting scrambled. Looking at trajectory I see the same behavior as your video above. This is before the fix in #4106 after the fix in #4049 .
- 8.0 latest build from source (SHA 3ef129919177cec471308c31e57689ce177ebc28). This looks correct.

![msd](https://github.com/openmm/openmm/assets/25941757/c32be44b-0901-48df-8e07-fd16a3f6b7d1)

**Comment by leeping** [comment]
Thanks for the reply!  Here are the files to reproduce.  Please let me know when you've received the files - I'd prefer that they aren't publicly available for too long because the work is unpublished.  The command to run the simulation is in `command.sh`.

https://www.dropbox.com/s/3k0pp0w91kvlbbk/simulation.tar.gz?dl=0

You might get a faster result if you set the number of equilibration steps to 0 in the input file.

The closest SHA is https://github.com/openmm/openmm/commit/3b3def0e3efe0bd76f2754b0b65417d6c9cc5e70.  My local repo is not the exact same SHA because when I pulled the changes git made a merge commit with my local branch, even though my local branch did not have any actual changes from this commit.  I just blew everything away and I'm now rebuilding with https://github.com/openmm/openmm/commit/3ef129919177cec471308c31e57689ce177ebc28 (the one that you said looks correct).  I will let you know how things are after I've gotten some data.

**Comment by leeping** [comment]
I can now confirm that the NVT run that I mentioned in the original post does not contain any jumps.

**Comment by sef43** [comment]
> Thanks for the reply! Here are the files to reproduce. Please let me know when you've received the files 

I have the files thanks

> The closest SHA is 3b3def0
Okay that one is just before the latest barostat fix so my hope is that once you rebuild with the latest it will work correctly

**Comment by leeping** [comment]
I'm seeing several jumps in less than 1 ns of simulation.  The trajectory is attached, written with a saving interval of 10 ps.

https://www.dropbox.com/s/i1jwbs7kvexxlls/dynamics_0.dcd?dl=0

**Comment by sef43** [comment]
For me PR #4119 appears to fix this problem in my test case

**Comment by sef43** [comment]
I think an alternative possible fix would be to stop MonteCarloBarostat from calling reorderAtoms() on a trial move.

**Comment by leeping** [comment]
Thanks so much for your efforts. :) I'll sit tight until you and @peastman agree on a good solution.

**Comment by leeping** [comment]
Unfortunately, I think I saw this error rear its head again in commit 5e9134005d3ca013572979289ce00ec32038e4f1.  It only occurred for the simulation with a very large number for the barostat attempt interval (once every 500 steps).  Notably, it does not occur when the barostat attempt interval is set to every 50 steps with everything else being the same.

After running for about 20 ns, the simulation with the jumps will segfault.  It also produces a core dump but gdb does not print anything useful (presumably because OpenMM wasn't compiled with debug flags).

The error message from the segfault was:
```
Traceback (most recent call last):
  File "/home/leeping/src/OpenMM-MD/OpenMM-MD.py", line 1611, in <module>
    simulation.step(args.production)
  File "/home/leeping/opt/miniconda3/envs/openmm_80_fixmc/lib/python3.9/site-packages/openmm/app/simulation.py", line 141, in step
    self._simulate(endStep=self.currentStep+steps)
  File "/home/leeping/opt/miniconda3/envs/openmm_80_fixmc/lib/python3.9/site-packages/openmm/app/simulation.py", line 206, in _simulate
    self.integrator.step(10) # Only take 10 steps at a time, to give Python more chances to respond to a control-c.
  File "/home/leeping/opt/miniconda3/envs/openmm_80_fixmc/lib/python3.9/site-packages/openmm/openmm.py", line 9263, in step
    return _openmm.CustomIntegrator_step(self, steps)
openmm.OpenMMException: Error invoking kernel: CUDA_ERROR_ILLEGAL_ADDRESS (700)
```

I've attached the scripts to reproduce.  The first jump occurs within the first 0.5 ns or so.

[jump_molecule2.tar.gz](https://github.com/openmm/openmm/files/11864248/jump_molecule2.tar.gz)
