### ISSUE TITLE
Problem with SMD

### ISSUE THREAD

**Issue by hang921727** [openmm/openmm#4126]
How to implement SMD simulations on OpenMM?
I've read the SMD part of the example form https://openmm.github.io/openmm-cookbook/latest/notebooks/tutorials/umbrella_sampling.html
.but I don't know how to get force from customCVforce.

**Comment by sef43** [comment]
For a harmonic moving restraint used in the example the `customCVforce` energy is `V=0.5 * fc_pull * (cv-r0)^2`.
The force is therefore `f = -  fc_pull*(cv-r0)`.
Remember, `r0` is the target location of the restraint which we update in stepwise manner to approximate constant velocity pulling and `cv` is the current value of the CV as measured from the atomic coordinates at the timestep we query it.
You can compute this force in the steered MD loop of the tutorial code as:
`f = - fc_pull*( unit.Quantity(current_cv_value[0], unit.nanometer) - r0)`

**Comment by hang921727** [comment]
Thank you very much!

**Comment by hang921727** [comment]
> For a harmonic moving restraint used in the example the `customCVforce` energy is `V=0.5 * fc_pull * (cv-r0)^2`. The force is therefore `f = - fc_pull*(cv-r0)`. Remember, `r0` is the target location of the restraint which we update in stepwise manner to approximate constant velocity pulling and `cv` is the current value of the CV as measured from the atomic coordinates at the timestep we query it. You can compute this force in the steered MD loop of the tutorial code as: `f = - fc_pull*( unit.Quantity(current_cv_value[0], unit.nanometer) - r0)`
> 
> (The `unit.Quantity(current_cv_value[0], unit.nanometer) ` part just converts the tuple into a float quantity with the right units)

Thank you very much!

**Comment by hang921727** [comment]
Thank you very much!
But i still have another question: Do i need a Fix Atom when calculating CV？
cv = R_smd_atom - R_fix_atom

**Comment by peastman** [comment]
What do you mean by a "fix atom"?  What do you want the CV to be?

**Comment by hang921727** [comment]
> What do you mean by a "fix atom"? What do you want the CV to be?
Sorry, my expression is not very clear. The CV is the distance between atom A and atom B. I want to move atom A away from atom B. Do I need to fix atom B during the simulation?

**Comment by peastman** [comment]
Only if you have some other reason for not wanting it to move.  There's no problem with using the distance between two mobile atoms as a CV.

**Comment by hang921727** [comment]
> 



> Only if you have some other reason for not wanting it to move. There's no problem with using the distance between two mobile atoms as a CV.

**Comment by hang921727** [comment]
> Only if you have some other reason for not wanting it to move. There's no problem with using the distance between two mobile atoms as a CV.

Thank you for your reply! 
`k_fix = 1000*unit.kilojoules_per_mole
 fix = mm.CustomExternalForce("k_fix")
 fix.addParticle(self.atom1-1)
 fix.addGlobalParameter("k_fix",k_fix)`
I used CustomExternalForce to apply a fixing force to atom B. Subsequently, I computed the pulling Force (F) of each step, and calculated the pull work of each step based on F*(v * dt), and finally added up all the work values to calculate the pmf. However, the pmf I obtained was significantly higher than the SMD results obtained using NAMD. I don't know what's wrong. Can you give me some advice?
