### ISSUE TITLE
platform properties ignored unless platform specified explicitly

### ISSUE THREAD

**Issue by lgsmith** [openmm/openmm#4129]
`Simulation`'s init method seems to ignore the platformProperties kwarg supplied to it if the `platform` kwarg is not supplied. I've found this issue on both openMM 7.7 and 8.0. I have not gone further back to check whether older versions exhibit this behavior.

I'm getting this behavior by creating a simulation like this:
```
platform_properties = {'Precision': 'mixed'}
simulation = Simulation(prmtop.topology, system, integrator, platformProperties=platform_properties)
```
I noticed that this was happening because I was running some NVE simulations and was seeing a surprising amount of heating per million steps, so I thought there was some issue with the verlet integrator I was using. Turns out it was just running single precision. So if I print  it by getting the name and precision from the context after it's initialized, I see that precision is `'single'`.

```
platform = simulation.context.getPlatform()
plat_name = platform.getName()
plat_prec = platform.getPropertyValue(simulation.context, 'Precision')
print('name:', plat_name)
print('prec:', plat_prec, flush=True)
```

I can resolve this issue by also specifying the platform like so:
```
platform = Platform.getPlatformByName('CUDA')
platform_properties = {'Precision': 'mixed'}
simulation = Simulation(prmtop.topology, system, integrator, platform=platform, platformProperties=platform_properties)
```
I don't know if this is actually expected behavior, but it certainly was surprising for me. I'm a bit worried that in contexts where people are relying on the [behavior mentioned in the tutorial](http://docs.openmm.org/latest/userguide/application/02_running_sims.html#simulation-parameters) to pick the fastest available platform, but are expecting to get mixed precision integration on any GPU they land on by specifying platform properties, they'll be unpleasantly surprised by this.

**Comment by peastman** [comment]
That's the intended behavior.  Really it should throw an exception if you do that.  Simulation is a thin wrapper around a Context, which is a C++ class.  Context [doesn't have any constructor](http://docs.openmm.org/latest/api-c++/generated/Context.html) that takes properties but not a Platform.

The reason for this is that platform properties are, by definition, platform-specific.  It doesn't make sense to specify them if you don't know what Platform it's going to use.

**Comment by lgsmith** [comment]
Yeah an exception would have been helpful. Because the GPU platforms have 'mixed' precision as an option I supposed it would do something like create a default platform, then try to apply the provided platform properties and if those don't exist for the platform it 'got', then it could throw an exception at that point. 

I think a sentence in the docs could also be helpful, in addition to an exception, but an exception would be really nice. Your explanation makes sense. Do you want this issue to stay open until someone submits a PR with code to throw the exception in it?

**Comment by peastman** [comment]
Agreed, let's add an exception.
