### ISSUE TITLE
Platform parameter settings

### ISSUE THREAD

**Issue by Drawthe** [openmm/openmm#4131]
May I ask if the openmm8.0.0 version does not support HIP acceleration? It is normal for me to use the same method on version 7
![image](https://github.com/openmm/openmm/assets/93109645/19c3cfb7-beee-493f-b999-b60be9b8f051)

**Comment by peastman** [comment]
HIP support is provided by a separately installed plugin: https://github.com/StreamHPC/openmm-hip

**Comment by Drawthe** [comment]
Thank you very much. My server is not connected to the network and the configuration is quite troublesome.
