### ISSUE TITLE
Equations for calculating non-bonded energies

### ISSUE THREAD

**Issue by asgharrazavi** [openmm/openmm#4132]
Where can I find equations that OpenMM uses for calculating non-bonded energies? I am trying to calculate these energies without using neighbor list or cutoffs and would like to use the same equations that openMM uses. Thanks!

**Comment by Lnaden** [comment]
The Theory docs have the equations for the [Nonbonded Force here](http://docs.openmm.org/latest/userguide/theory/02_standard_forces.html#nonbondedforce) (and the other forces OpenMM uses). The actual implementation for what you're doing may have a solution already, if you can provide more details, we may be able to point you to options. For instance, you can disable cutoffs by [specifying the nonbonded force us `NoCuttof`](http://docs.openmm.org/latest/userguide/application/02_running_sims.html?highlight=nocutoff#nonbonded-interactions)

**Comment by asgharrazavi** [comment]
Thanks for quick reply. I think I am trying to get interaction energies of a ligand and its surroundings, similar to what is done in this post: https://github.com/openmm/openmm-cookbook/pull/26

I am defining my ligand atoms and other atoms into 2 sets and calculate coulomb and Lennard-Jones interactions between them, but worried that parameters of equations that I using are not properly defined.


```python

def _get_r(i,j,positions):
    i_x, i_y, i_z = positions[i]._value[0], positions[i]._value[1], positions[i]._value[2]
    j_x, j_y, j_z = positions[j]._value[0], positions[j]._value[1], positions[j]._value[2]
    r = np.sqrt((i_x - j_x)**2 + (i_y - j_y)**2 + (i_z - j_z)**2)
    return r

def get_q(i,j,r,nonbonded):
    i_q = nonbonded.getParticleParameters(i)[0].value_in_unit(unit.elementary_charge)
    j_q = nonbonded.getParticleParameters(j)[0].value_in_unit(unit.elementary_charge)
    c = (i_q * j_q) / (4 * np.pi * r) # ignoring epsilon_0
    return c

def get_lj(i,j,r,nonbonded):
    i_sig = nonbonded.getParticleParameters(i)[1].value_in_unit(unit.nanometer)
    i_eps = nonbonded.getParticleParameters(i)[2].value_in_unit(unit.kilojoule_per_mole)
    lj = i_eps * ( (i_sig/r)**12 - 2*(i_sig/r)**6 )
    return lj

nonbonded = [f for f in system.getForces() if isinstance(f, NonbondedForce)][0]
unl_idx =  [atom.index for atom in topology.atoms() if atom.residue.name == "UNL"]
other_idx = [atom.index for atom in topology.atoms() if atom.residue.name != "UNL"]
ener_col = 0
ener_lj = 0
for i in unl_idx:
        for j in other_idx:
            r = _get_r(i,j,positions)
            col = get_q(i,j,r,nonbonded)
            lj = get_lj(i,j,r,nonbonded)
            ener_col += col
            ener_lj += lj

**Comment by peastman** [comment]
You need to query sigma and epsilon for both particles, not just one.  Then you combine them using the Lorentz-Berthelot combining rules as described in http://docs.openmm.org/latest/userguide/theory/02_standard_forces.html#lennard-jones-interaction.

If you're going to be doing this calculation a lot and you want it to be fast, the method described in the cookbook will be much faster.

**Comment by asgharrazavi** [comment]
Now that makes a lot of sense! Thanks very much! Will check the cookbook as well.

**Comment by Lnaden** [comment]
> get interaction energies of a ligand and its surroundings

Can you be more clear about what you mean from "A ligand and its surroundings?" The way I read that that, and based on your sample code, is you want the Nonbonded Force acting between all of the [ligand]-[non-ligand] atoms pairs.

In my head, there are 3 interaction classes: ligand-ligand, ligand-else, else-else. Else in this context is the solvent, the host, the protein, the whatever-isin't-your-ligand. It sounds like what you need is a combination of multiple nonbonded forces + ForceGroups + Exceptions.

Every OpenMM `Force` object (including `NonbondedForce`) can be put into a separate [`ForceGroup`](http://docs.openmm.org/latest/userguide/theory/05_other_features.html?highlight=forcegroup#force-groups). You can assign the forces to one of 32 force groups, and then get the energy of any combination of them at will without affecting simulation (which defaults to roughly "propagate with all force groups together"). So, depending on what you meant by "A ligand and its surroundings;" you can do is create a few `NonBonded` Forces which will capture the interactions with additional `Exceptions` to negate certain interactions but will add together to be a fully interacting system.

Psudo-real code below

### Example: You wanted ligand/else + ligand/ligand interactions
```python
base_nb = [f for f in system.getForces() if isinstance(f, NonbondedForce)][0]
ligand_nb = copy.deepcopy(base_nb)

for i in range(atoms):
    for j in range(i, atoms):    # Don't double up
        # I dont do anything with these, but if you need them, here they are.
        qi, si, ei = base_nb.getParticleParameters(i)
        qj, sj, ej = base_nb.getParticleParameters(j)
        if i in ligand_atoms and j in ligand_atoms:    # Ligand/Ligand interactions
            base_nb.addException(i, j, 0, 1, 0)    # Disable interaction in base_nb, so long as charge and epsilon are 0 the interaction is disabled.
        elif (i in ligand_atoms and j in other_atoms) or (i in other_atoms and j in ligand_atoms):  # Ligand/other interactions
            base_nb.addException(i, j, 0, 1, 0)    # Disable interaction in base_nb
        else:    # Other/Other interactions
            ligand_nb.addException(i, j, 0, 1, 0)    # Disable interaction in ligand Nonbonded force
ligand_nb.setForceGroup(1)
system.addForce(ligand_nb)

...   # Run remaining setup and Simulation here

ligand_energy = context.getState(getEnergy=True, groups=1).getPotentialEnergy()  # This will get only force group 1 with the ligand NB force.
```
This isn't going to do quite everything you might need to, but it shows you the process for an option.

However, if @peastman's comment is good enough for you, then you wont need this.

**Comment by asgharrazavi** [comment]
@Lnaden you are correct that I mean `ligand vs. everything else` when I say "A ligand and its surroundings". Thanks for the code and explanation. I tried to adjust your code as bellow, but I am getting error:

```python 
    base_nb = [f for f in system.getForces() if isinstance(f, NonbondedForce)][0]
    ligand_other_nb = copy.deepcopy(base_nb)
    other_other_nb = copy.deepcopy(base_nb)
    ligand_ligand_nb = copy.deepcopy(base_nb)
    atoms = [atom.index for atom in topology.atoms()]
    ligand_atoms = [atom.index for atom in topology.atoms() if atom.residue.name == "UNL"]
    other_atoms = [atom.index for atom in topology.atoms() if atom.residue.name != "UNL"]
    for i in atoms:
        for j in atoms:    # Don't double up
            # I dont do anything with these, but if you need them, here they are.
            qi, si, ei = base_nb.getParticleParameters(i)
            qj, sj, ej = base_nb.getParticleParameters(j)
            if i in ligand_atoms and j in ligand_atoms:    # Ligand/Ligand interactions
                ligand_ligand_nb.addException(i, j, 0, 1, 0)    # Disable interaction in base_nb, so long as charge and epsilon are 0 the interaction is disabled.
            elif (i in ligand_atoms and j in other_atoms) or (i in other_atoms and j in ligand_atoms):  # Ligand/other interactions
                ligand_other_nb.addException(i, j, 0, 1, 0)    # Disable interaction in base_nb
            else:    # Other/Other interactions
                other_other_nb.addException(i, j, 0, 1, 0)    # Disable interaction in ligand Nonbonded force
    ligand_other_nb.setForceGroup(1)
    system.addForce(ligand_other_nb)
```

```    
    other_other_nb.addException(i, j, 0, 1, 0)    # Disable interaction in ligand Nonbonded force
  File "/Users/asgharrazavi/miniconda3/envs/openff/lib/python3.9/site-packages/openmm/openmm.py", line 9558, in addException
    return _openmm.NonbondedForce_addException(self, particle1, particle2, chargeProd, sigma, epsilon, replace)
openmm.OpenMMException: NonbondedForce: There is already an exception for particles 0 and 1
```

I think these is something wrong in the `if statements`. I am also a bit confused about using `addExceptions`. I think what it does (from your comments) is to remove interactions between specified atoms, however, what I want, is a group that gives me energy (i.e. `getPotentialEnergy`) between **_ligand_** and _**everything else**_.

**Comment by Lnaden** [comment]
Right, the code wont be perfect, its only meant to be a psuedo-code which uses actual code, so its close but not exact to your case. If there are already exceptions (such as 1-4 interaction exceptions), then you can't overwrite them without the [`replace` keyword](http://docs.openmm.org/latest/api-python/generated/openmm.openmm.NonbondedForce.html?highlight=nonbondedforce#openmm.openmm.NonbondedForce.addException), hence the error you're seeing.

For your use case, you would need to make it so the modified `NonbondedForce` only accepts the ligand/other interactions, so something like (no promises this is perfect):

```python
    for i in atoms:
        # LNN Note: Started from index i here so you dont loop over every pair twice.
        for j in atoms[i:]:    # Don't double up
            # I dont do anything with these, but if you need them, here they are.
            qi, si, ei = base_nb.getParticleParameters(i)
            qj, sj, ej = base_nb.getParticleParameters(j)
            if i in ligand_atoms and j in ligand_atoms:    # Ligand/Ligand interactions
                # Disable atoms in ligand/other, leave the normal NB in place
                ligand_other_nb.addException(i, j, 0, 1, 0, replace=True)    # Disable interaction in ligand/other, so long as charge and epsilon are 0 the interaction is disabled.
            elif (i in ligand_atoms and j in other_atoms) or (i in other_atoms and j in ligand_atoms):  # Ligand/other interactions
                # Enable this group in the Ligand/other force, disable in the base NB force so we don't double count for the interactions. Since it starts "enabled," only disable in the base
                base_nb.addException(i, j, 0, 1, 0, replace=True) 
            else:    # Other/Other interactions
                # Disable atoms in other/other, leave the normal NB in place
                ligand_other_nb.addException(i, j, 0, 1, 0, replace=True)    # Disable interaction in ligand Nonbonded force
    ligand_other_nb.setForceGroup(1)
    system.addForce(ligand_other_nb)
```

This way the ligand/other nonbonded group force only has ligand/other interactions, not ligand/ligand nor other/other. It might take some additional tinkering, but the [API docs are quite good](http://docs.openmm.org/latest/api-python/index.html) so I encourage you to look over those.

In my two examples, i've folded two sets of the interactions into one nonbonded force. You could split each one into a different `NonbondedForce` object as you started to do, but for the exact type of interactions youre looking for you dont need to. Every `Force` you add to a `System` does add some overhead to running, which is why I negate what I can and minimize the impact.

**Comment by Lnaden** [comment]
> I think what it does (from your comments) is to remove interactions between specified atoms

Correct, the code is removing interactions with `addExceptions.` The `NonbonedForce` in OpenMM requires the number of particles in it to match the number of particles of the system. So I can't make a `NonbondedForce` without every particle. What I *can* do is create two (or more) `NonbondedForce`s and then `addException` to subsets of particle pairs such that one force negates all the interactions I care about; and one force negates all interactions I dont care about. If I were to add the effects of these forces **I get out an identical force to the unmodified original Nonbonded Force I started with**. Then I put one of them in a different force group so I can get the interesting energy.

Theres a couple other ways to do this which I'll spare the details of but just give their objective here so you can see there are options (I think these are a harder to implement correctly than above, which is why I spare the details):
* Leave the original nonbonded force, create one where only the interactions you care about are allowed, push the new one into a different force group, and then propagate the simulation using only one force group.
* Create a `CustomNonbondedForce` where you try to replicate the same energies as the normal `NonbondedForce` with custom strings, use `InteractionGroup`s and do the same thing as the item above.

Again, both these other options I think are harder and more complicated than you need to get the unmodified energies of your system out.

**Comment by asgharrazavi** [comment]
Thanks @Lnaden for the code. Unfortunately, seems that the `for` loops in `for i in atoms:` and `for j in atoms[i:]:` are making the process really slow (over an hour on my machine). 
On the other hand, I was able to adopt the example in the cookbook that @peastman mentioned. However, I see discrepancy in energies, specially the`Lennard-Jones Interaction`, when using my approach and the one in cookbook. Here is the code. I am using the same `villin.pdb` from cookbook.

```python
from openmm import *
from openmm.app import *
from openmm.unit import *
from openmm import app
from openmm import unit
import time
import numpy as np


def _get_r(i,j,positions):
    i_x, i_y, i_z = positions[i]._value[0], positions[i]._value[1], positions[i]._value[2]
    j_x, j_y, j_z = positions[j]._value[0], positions[j]._value[1], positions[j]._value[2]
    r = np.sqrt((i_x - j_x)**2 + (i_y - j_y)**2 + (i_z - j_z)**2)
    return r

def get_q(i,j,r,nonbonded):
    r = r * 1E-9 # convert to meter
    eps_0 = 8.854187817E-12 #C**2/(N.m**2)
    mol = 6.02214076E23
    i_q = nonbonded.getParticleParameters(i)[0].value_in_unit(unit.coulombs)
    j_q = nonbonded.getParticleParameters(j)[0].value_in_unit(unit.coulombs)
    c = (i_q * j_q) / (4 * np.pi * eps_0 * r) #J
    c = c * 0.001 #kJ
    c = c * mol #kJ/mol
    return c

def get_lj(i,j,r,nonbonded):
    i_sig = nonbonded.getParticleParameters(i)[1].value_in_unit(unit.nanometer)
    j_sig = nonbonded.getParticleParameters(j)[1].value_in_unit(unit.nanometer)
    i_eps = nonbonded.getParticleParameters(i)[2].value_in_unit(unit.kilojoule_per_mole)
    j_eps = nonbonded.getParticleParameters(j)[2].value_in_unit(unit.kilojoule_per_mole)
    sig = (i_sig + j_sig) / 2.0
    eps = np.sqrt(i_eps * j_eps)
    lj = 4 * eps * ( (sig/r)**12 - (sig/r)**6 )
    return lj


def energies1(simulation,system):
    initial_time = time.time()
    print('calculating energies using explicit equations...')
    positions = simulation.context.getState(getPositions=True).getPositions()
    nonbonded = [f for f in system.getForces() if isinstance(f, NonbondedForce)][0]
    ener_col = 0
    ener_lj = 0
    for i in ligand:
        for j in others:
            r = _get_r(i,j,positions)
            col = get_q(i,j,r,nonbonded)
            lj = get_lj(i,j,r,nonbonded)
            ener_col += col
            ener_lj += lj
    print("coulomb energy:",ener_col, "kJ/mol")
    print("lj energy:",ener_lj, "kJ/mol")
    final_time = time.time()
    elapsed_time = final_time - initial_time
    print('Time elapsed: %f seconds' % elapsed_time)

def energies2(simulation,system,topology):
    initial_time = time.time()
    print('calculating energies using force separations...')
    for force in system.getForces():
        if isinstance(force, NonbondedForce):
            force.setForceGroup(0)
            force.addGlobalParameter("others_coulomb_scale", 1)
            force.addGlobalParameter("others_lj_scale", 1)
            force.addGlobalParameter("ligand_coulomb_scale", 1)
            force.addGlobalParameter("ligand_lj_scale", 1)
            for i in range(force.getNumParticles()):
                charge, sigma, epsilon = force.getParticleParameters(i)
                force.setParticleParameters(i, 0, 0, 0)
                if i in others:
                    force.addParticleParameterOffset("others_coulomb_scale", i, charge, 0, 0)
                    force.addParticleParameterOffset("others_lj_scale", i, 0, sigma, epsilon)
                else:
                    force.addParticleParameterOffset("ligand_coulomb_scale", i, charge, 0, 0)
                    force.addParticleParameterOffset("ligand_lj_scale", i, 0, sigma, epsilon)
            for i in range(force.getNumExceptions()):
                p1, p2, chargeProd, sigma, epsilon = force.getExceptionParameters(i)
                force.setExceptionParameters(i, p1, p2, 0, 0, 0)
        else:
            force.setForceGroup(2)
    def energy(others_coulomb_scale, others_lj_scale, ligand_coulomb_scale, ligand_lj_scale):
        simulation2.context.setParameter("others_coulomb_scale", others_coulomb_scale)
        simulation2.context.setParameter("others_lj_scale", others_lj_scale)
        simulation2.context.setParameter("ligand_coulomb_scale", ligand_coulomb_scale)
        simulation2.context.setParameter("ligand_lj_scale", ligand_lj_scale)
        return simulation2.context.getState(getEnergy=True, groups={0}).getPotentialEnergy()
    positions = simulation.context.getState(getPositions=True).getPositions()
    integrator2 = LangevinMiddleIntegrator(310*unit.kelvin, 1/unit.picosecond, 0.002*unit.picoseconds)
    simulation2 = app.Simulation(topology, system, integrator2)
    simulation2.context.setPositions(positions)
    total_coulomb = energy(1, 0, 1, 0)
    others_coulomb = energy(1, 0, 0, 0)
    ligand_coulomb = energy(0, 0, 1, 0)
    total_lj = energy(0, 1, 0, 1)
    others_lj = energy(0, 1, 0, 0)
    ligand_lj = energy(0, 0, 0, 1)
    print('Coulomb interaction energy:', total_coulomb - others_coulomb - ligand_coulomb)
    print('LJ interaction energy:', total_lj - others_lj - ligand_lj)
    final_time = time.time()
    elapsed_time = final_time - initial_time
    print('Time elapsed: %f seconds' % elapsed_time)


pdb_file = 'villin.pdb'
omm_forcefield = app.ForceField('amber14-all.xml', 'amber14/tip3pfb.xml')
prot_pdb_file = app.PDBFile(pdb_file)
top = prot_pdb_file.topology
modeller = app.Modeller(top, prot_pdb_file.positions)
print('adding hydrogens...')
modeller.addHydrogens(omm_forcefield)
modeller.topology.setUnitCellDimensions(modeller.topology.getUnitCellDimensions())
positions = modeller.positions
topology = modeller.topology
system = omm_forcefield.createSystem(topology, nonbondedMethod=app.PME, nonbondedCutoff=0.9*unit.nanometer, constraints=app.HBonds)
barostat = MonteCarloBarostat(1.0*unit.bar, 310.0*unit.kelvin)
system.addForce(barostat)

others = set([a.index for a in topology.atoms() if a.residue.name in ('HOH', 'Cl')])
ligand = set([a.index for a in topology.atoms() if a.index not in others])

integrator = LangevinMiddleIntegrator(310*unit.kelvin, 1/unit.picosecond, 0.002*unit.picoseconds)
simulation = app.Simulation(topology, system, integrator)
simulation.context.setPositions(positions)
print('Initial potential energy = %s' % simulation.context.getState(getEnergy=True).getPotentialEnergy())
initial_time = time.time()
simulation.minimizeEnergy() 
final_time = time.time()
print('Final potential energy   = %s' % simulation.context.getState(getEnergy=True).getPotentialEnergy())
print('simulating for 10ps...')
simulation.step(5000) 


energies1(simulation,system)
energies2(simulation,system,topology)

```

Here are the results:
```
adding hydrogens...
Initial potential energy = -114900.75694803393 kJ/mol
Final potential energy   = -166641.06944803393 kJ/mol
simulating for 10ps...
calculating energies using explicit equations...
coulomb energy: -6539.591920789317 kJ/mol
lj energy: -465.69818285716696 kJ/mol
Time elapsed: 142.280638 seconds
calculating energies using force separations...
Coulomb interaction energy: -5314.449145761744 kJ/mol
LJ interaction energy: 497.9489255273179 kJ/mol
Time elapsed: 0.308145 seconds```

**Comment by asgharrazavi** [comment]
Thanks @Lnaden for the comments. I used `system = omm_forcefield.createSystem(topology, nonbondedMethod=NoCutoff)` and disables barostas. Now I get exact same results between two approaches:
```
adding hydrogens...
Initial potential energy = -99938.5625 kJ/mol
Final potential energy   = -160353.546875 kJ/mol
simulating for 10ps...
calculating energies using explicit equations...
coulomb energy: -6415.70501341282 kJ/mol
lj energy: -448.6560642879805 kJ/mol
Time elapsed: 164.073994 seconds
calculating energies using force separations...
Coulomb interaction energy: -6415.705078125 kJ/mol
LJ interaction energy: -448.65289306640625 kJ/mol
Time elapsed: 0.379628 seconds
```

What tis still disturbing me is that when I used the PME with cutoff, the energy values are different, specially for LJ interactions that I was getting positive energies. 
If using PME, which values should I trust? the ones calculating directly using equations (the `energies1` function) to the one that used force separation (the `energies2` function)?

**Comment by Lnaden** [comment]
Without sitting down with this for longer, I can't really say why your energy is positive. Its quite possible to have a positive lennard-jones contribution under any number of configurations, especially when you have solvent packed into a dense box around a solute of some kind, especially when you're looking only at the LJ terms for ligand-solvent which will be dominated by the solvents close to the ligand atoms, which will tend to be positive. (`r^-6` and `r^-12` scaling will mostly negate anything far away.)

Overall, I would trust the `energies2` output more since its more reliable for the system you're actually simulating. When you specified `NoCutoff` and no Barostat, you're now simulating a pseudo-vacuum system where the solvent are allowed to drift, which is probably why you now see a negative energy.

**Comment by asgharrazavi** [comment]
Thanks again. I agree with your judgments. Since `energies1` is not considering periodic image effects its results can be different from `energies2` when system setup and simulation is using periodic image. Once periodicity is disabled, both approaches give similar results. I am just surprised that periodic image is having such a big impact, something to keep in my mind.

**Comment by peastman** [comment]
By omitting periodic boundary conditions, you omit a lot of interactions.  Most of those interactions are at longer distances where LJ is attractive (energy is negative).  So it's not surprising it would make the total energy more positive.

**Comment by asgharrazavi** [comment]
Thanks, but the issue is that the LJ interactions calculated by the second method `energies2` which uses approach outlined in the cookbook is giving more positive energies (not more negative) compared to simpler function `energies1` that doesn't consider periodic images. 
I also tried the `CutoffNonPeriodic ` option as well: `system = omm_forcefield.createSystem(topology, nonbondedMethod=CutoffNonPeriodic)`. In this case, energies differ more than `NoCutoff` option but still not as much as the `PME` [method from above](https://github.com/openmm/openmm/issues/4132#issuecomment-1623717430): 
```
Results when using "energies1" function that loops over all atoms and doesn't consider periodic images:
coulomb energy: -6415.70501341282 kJ/mol
lj energy: -448.6560642879805 kJ/mol

Results when using "system = omm_forcefield.createSystem(topology, nonbondedMethod=NoCutoff)"
Coulomb interaction energy: -6415.705078125 kJ/mol
LJ interaction energy: -448.65289306640625 kJ/mol

Results when using "system = omm_forcefield.createSystem(topology, nonbondedMethod=CutoffNonPeriodic)"
Coulomb interaction energy: -5913.4677734375 kJ/mol
LJ interaction energy: -325.240234375 kJ/mol

Results when using "omm_forcefield.createSystem(topology, nonbondedMethod=app.PME, nonbondedCutoff=0.9*unit.nanometer, constraints=app.HBonds)"
Coulomb interaction energy: -5314.449145761744 kJ/mol
LJ interaction energy: 497.9489255273179 kJ/mol

```

**Comment by asgharrazavi** [comment]
I realized that if I not zero out the "ExceptionParametes" , the reported energies are vary different values. In other words, if I comment out the code below from cookbook, I get different energy values.

```python
            for i in range(force.getNumExceptions()):
                p1, p2, chargeProd, sigma, epsilon = force.getExceptionParameters(i)
                force.setExceptionParameters(i, p1, p2, 0, 0, 0)
```

Could you please let me know where to find out more details about the intended use of `Exception` and how openMM is using those during MD simulations. Thanks!

**Comment by asgharrazavi** [comment]
Thanks for the explanation. I am still confused about the nature of the "exceptions" energy. What is the exception energy calculating? Is it part of the non-bonded interactions? Sorry of this is more like a fundamental MD simulation question, but any more details or where to read more on this topic would be very helpful for me. Thanks!

**Comment by peastman** [comment]
In typical MD force fields, you omit or reduce the nonbonded interactions between atoms that are closely connected by bonds.  It varies between force fields, but most often you omit the interactions for atoms that are directly bonded (1-2 interactions), or that are separated by two bonds (1-3 interactions).  You include the nonbonded interactions between pairs that are separated by three bonds (1-4 interactions), but you reduce their strength.  That's what exceptions are for.

So exceptions are really a bonded force, but they replace a nonbonded force.  And critically, they only affect pairs of atoms that are actually connected by bonds.  Each atom still interacts in the normal way with all the other periodic copies of the other atom.
