### ISSUE TITLE
Undefined reference -- OpenMM 8.0.0 installation #2075

### ISSUE THREAD

**Issue by pietro-sillano** [openmm/openmm#4133]
When I try to install OpenMM 8.0.0 run into what feels like a linking issue; 

**Environment:**
Operating System: EndeavourOS Linux x86_64, kernel 6.3.9
Compiler: clang version 13.0.0

**How I install:**
I use ccmake as descripted on the docs adding in the ccmake advanced settings:

CMAKE_CXX_COMPILER               /usr/bin/clang-13
CMAKE_CC_COMPILER               /usr/bin/clang-13
CMAKE_CXX_FLAGS                  -std=c++11  -stdlib=libstdc++

then configure, generate and make.

Error message (only the last lines, the full log is in the attachment)
```
/usr/bin/ld: ../../../libOpenMM.so.8.0: undefined reference to `std::ostream& std::ostream::_M_insert<bool>(bool)'
/usr/bin/ld: ../../../libOpenMM.so.8.0: undefined reference to `std::ostream::operator<<(int)'
/usr/bin/ld: ../../../libOpenMM.so.8.0: undefined reference to `cos'
/usr/bin/ld: ../../../libOpenMM.so.8.0: undefined reference to `std::istream::operator>>(int&)'
/usr/bin/ld: ../../../libOpenMM.so.8.0: undefined reference to `__cxa_rethrow'
/usr/bin/ld: ../../../libOpenMM.so.8.0: undefined reference to `std::bad_alloc::~bad_alloc()'
/usr/bin/ld: ../../../libOpenMM.so.8.0: undefined reference to `typeinfo for std::invalid_argument'
/usr/bin/ld: ../../../libOpenMM.so.8.0: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_mutate(unsigned long, unsigned long, char const*, unsigned long)'
/usr/bin/ld: ../../../libOpenMM.so.8.0: undefined reference to `std::__throw_system_error(int)'
/usr/bin/ld: ../../../libOpenMM.so.8.0: undefined reference to `vtable for __cxxabiv1::__si_class_type_info'
clang-13: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [platforms/reference/tests/CMakeFiles/TestReferenceBrownianIntegrator.dir/build.make:99: TestReferenceBrownianIntegrator] Error 1
make[1]: *** [CMakeFiles/Makefile2:2227: platforms/reference/tests/CMakeFiles/TestReferenceBrownianIntegrator.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

```

[output_file.txt](https://github.com/openmm/openmm/files/11949177/output_file.txt)

**Comment by peastman** [comment]
```
CMAKE_CXX_COMPILER /usr/bin/clang-13
```

I think that needs to be `clang++-13`?  Or `clang-13++`, or whatever it's called.  You're telling it to compile C++ code with a C compiler.

**Comment by pietro-sillano** [comment]
oh yeah, it makes sense! I dont know that there is clang++ too! Now it is compiled also with clang++ 15.
I have another issue with `sudo make PythonInstall`. I launch the commands and:
```
sudo make PythonInstall

[  0%] Built target ApiWrappers
[ 44%] Built target OpenMM
[ 44%] Building OpenMM Python binary module...
OPENMM_LIB_PATH = /usr/local/lib
OPENMM_INCLUDE_PATH = /home/pietro/Desktop/openmm-8.0.0/./include/home/pietro/Desktop/openmm-8.0.0/./include/openmm/home/pietro/Desktop/openmm-8.0.0/./include/openmm/internal/home/pietro/Desktop/openmm-8.0.0/openmmapi/include/home/pietro/Desktop/openmm-8.0.0/openmmapi/include/openmm/home/pietro/Desktop/openmm-8.0.0/openmmapi/include/openmm/internal/home/pietro/Desktop/openmm-8.0.0/olla/include/home/pietro/Desktop/openmm-8.0.0/olla/include/openmm/home/pietro/Desktop/openmm-8.0.0/olla/include/openmm/internal/home/pietro/Desktop/openmm-8.0.0/serialization/include/home/pietro/Desktop/openmm-8.0.0/serialization/include/openmm/home/pietro/Desktop/openmm-8.0.0/serialization/include/openmm/internal/home/pietro/Desktop/openmm-8.0.0/plugins/amoeba/openmmapi/include/home/pietro/Desktop/openmm-8.0.0/plugins/amoeba/openmmapi/include/openmm/home/pietro/Desktop/openmm-8.0.0/plugins/amoeba/openmmapi/include/openmm/internal/home/pietro/Desktop/openmm-8.0.0/plugins/rpmd/openmmapi/include/home/pietro/Desktop/openmm-8.0.0/plugins/rpmd/openmmapi/include/openmm/home/pietro/Desktop/openmm-8.0.0/plugins/rpmd/openmmapi/include/openmm/internal/home/pietro/Desktop/openmm-8.0.0/plugins/drude/openmmapi/include/home/pietro/Desktop/openmm-8.0.0/plugins/drude/openmmapi/include/openmm/home/pietro/Desktop/openmm-8.0.0/plugins/drude/openmmapi/include/openmm/internal
```
I don't understand why there is such a long Include.

From issue [2652](https://github.com/openmm/openmm/issues/2652) I also run manually the commands:
```
export OPENMM_INCLUDE_PATH=/usr/local/openmm/include
export OPENMM_LIB_PATH=/usr/local/openmm/lib
python setup.py build
python setup.py install
```
I don't receive any output from launching this scripts.

**Comment by peastman** [comment]
How long did you wait?  Compiling the python wrapper does take a while.

If you need sudo, that suggests you're trying to install into the system python?  I generally don't recommend doing that.  It's better to install a python into your home directory where you'll have full control over it, and you can choose which python version to use.  The instructions in the user guide recommend miniconda, which is a good choice.

**Comment by pietro-sillano** [comment]
I wait like 10-20 minutes, but what I don't understand if the `python setup.py build` is actually doing something..it seems just stuck.
I can also try with python installed in the home directory but I don't think that it is the problem

**Comment by pietro-sillano** [comment]
@peastman 
I give it a try to miniconda:

1. I follow the instructions on their website to install miniconda in my home folder
2. create a conda environment called openmmConda38 `conda create -n openmmConda38 python=3.8`
3. activate this environment with `conda activate openmmConda38`
4. install openMM with `conda install -c conda-forge openmm cudatoolkit`
5. launched `python -m openmm.testInstallation` and it gets stuck, no errors, I can't interrupt the process with ctrl+c
6. I tried also launching python shell (inside conda env) and try to import part of the openmm modules like openmm.app or openmm.platform but nothing happen. 

I tried with other versions of python and CUDA, but it seems there are no difference.

**Comment by peastman** [comment]
That certainly doesn't seem right.  What happens if you install the standard OpenMM package with conda?  Does it work correctly?  I'm trying to tell whether the problem is with OpenMM on your computer, or if it's something in how you're building it.

**Comment by pietro-sillano** [comment]
I tried both compiling from source and standard conda installation.
I reported in my previous message what I did to install with conda

**Comment by pietro-sillano** [comment]
@peastman I found what was causing the issue: it was related to OpenCL, `clinfo`  was hanging forever due to a conflict with intel-oneapi ICD. I solved following this advice: https://forum.manjaro.org/t/clinfo-and-codes-using-opencl-hangs-forever-after-last-update/138541 
Now Python wrapper works! 

Thank you for your time and availability
