### ISSUE TITLE
Continuing the metadynamics simulation

### ISSUE THREAD

**Issue by smlee99** [openmm/openmm#4134]
Hi OpenMM devs. I have a small question regarding the metadynamics simulation. I previously performed the metadynamics simulation but since the convergence of free energy was not satisfactory, I have to continue the simulation by adding more Gaussian hills. Is it guaranteed that re-running the metadynamics simulation would recognize the previously generated bias_*.npy file and add the Gaussian hills based on such information?(I hope so) For instance,
```
meta = Metadynamics(system, [biaspsi, biasphi], temperature, 40, 0.1*kilojoules_per_mole, 2000, 2000, biasDir='./colvar/')
```
If the previously generated bias_*.npy file is on the colvar directory, I wonder if the metadynamics object would load the bias_*npy.file and recognize the previous information.

**Comment by peastman** [comment]
Correct, that's exactly what they're for.  See http://docs.openmm.org/latest/api-python/generated/openmm.app.metadynamics.Metadynamics.html.

**Comment by smlee99** [comment]
Thanks for your reply. Just one more question. Re-running the metadynamics simulation with different biasFactor, height, frequency options would be fine, right? The reason for this is to shorten the simulation time, I would like to first start the metadynamics simulation with increased gaussian hill height and then after lower it for free energy convergence. I guess only the definition of BiasVariables (the grid size) would be matter.

**Comment by smlee99** [comment]
Thanks for your reply! Let me close this issue.
