### ISSUE TITLE
Wrong formula for Langevin Integrator (at least in the documentation)

### ISSUE THREAD

**Issue by plainerman** [openmm/openmm#4135]
I believe that I have found an issue with the current documentation of the theory behind the integrators. I only looked more closely into the Langevin Integrator, but maybe this impacts the documentation of the other intergrators as well.

More specifically, it is about the equations of the documentation in this section.

https://github.com/openmm/openmm/blob/644dc1ecc9e95b3c8e831803bb3e2ac925999f74/docs-source/usersguide/theory/04_integrators.rst?plain=1#L41-L76
(Probably, it is easier to look [at the official documentation with equation rendering](http://docs.openmm.org/latest/userguide/theory/04_integrators.html#langevinintegator)).

I assume that the implementation in openmm of the `LangevinIntegrator` is as specified in [this paper](https://doi.org/10.1142%2F9789814295291_0026) (which is listed as reference).

There are a few discrepancies between the equations in the documentation and the paper
* Inconsistent timestep size $\Delta t$, which is sometimes assumed to be a half step, but in other instances, a full step
* Different variance in the random variable
* Unclear notation when dividing by $m$

This is the implementation suggested by the referenced paper
![image](https://github.com/openmm/openmm/assets/6825443/8f3d28c2-5a6d-47d5-b02e-b4c144ba3d03)

And this the formula in the documentation
$$\mathbf{v}_{i}(t+\Delta t/2) = \mathbf{v}_i(t-\Delta t/2)\alpha + \mathbf{f}_i(t)(1 - \alpha) / \gamma m_i + \sqrt{kT(1-\alpha^2)/m}R$$

If we assumed $R_i$ to have a variance of $2 m_i k_B T$ (as specified in the documentation) , then the last part of the equation with a standard-normal random variable $Z$ becomes

$$\sqrt{kT(1-\alpha^2)/m} \sqrt{2 m_i k_B T} Z$$

which would simplify to

$$\sqrt{2 k ^ 2 T^2(1-\alpha^2)} Z$$

This is very different from what we have in this paper, for example all the masses cancel out and the temperature is squared.

I believe the documentation should be updated to say the following.
Z is a random normal variable with zero mean and unit variance. Then the LangevinIntegrator is defined as

$$\mathbf{v}_{i}(t+\Delta t/2) = \mathbf{v}_i(t-\Delta t/2)\alpha + \mathbf{f}_i(t)(1 - \alpha) / (\gamma m_i) + \sqrt{k_B T(1-\alpha^2)/m_i}Z$$

and fixing the step size inconsistency

$$\mathbf{r}_i(t+\Delta t) = \mathbf{r}_i (t) + \mathbf{v}_i(t+\Delta t/2)2\Delta t$$

In other words, this means that 1) the variance of the random variable R is incorrect 2) it is a bit unclear whether to multiply or divide by m (thus introduce brackets) 3) and the timestep is sometimes assumed to be half and sometimes the full timestep. Since in openmm the timestep refers to the complete step, not just half, I would even suggest writing the formula with the same timesteps as in the paper.

If I should make anything clearer, please let me know. But if you agree with me that this is wrong, I am happy to create a PR and update the documentation. The only question would be whether the other integrators are affected as well. Especially if we change the timesteps, I would be hesitant to update the documentation for the other integrators.

I strongly believe that the code is not impacted by this.

**Comment by peastman** [comment]
I believe the documentation is correct.  The paper is kind of confusing because, although it refers to it as a "Langevin leapfrog" integrator, the formulas do not actually describe a leapfrog integrator!  The implementation in OpenMM combines the initial and final velocity updates to turn it into a true leapfrog integrator.

Compare to the code that implements it:

https://github.com/openmm/openmm/blob/644dc1ecc9e95b3c8e831803bb3e2ac925999f74/platforms/reference/src/SimTKReference/ReferenceStochasticDynamics.cpp#L95-L109

Notice that the coefficient of the noise term is `noisescale*sqrtInvMass`, where `noisescale` is $\sqrt{kT*(1-\alpha^2)}$, exactly as in the documentation.

> If we assumed $R$ to have a variance of $2 m_i k_B T$ (as specified in the documentation)

The documentation says it's normally distributed, which means it has a variance of 1.

**Comment by plainerman** [comment]
Thank you very much for pointing me to the code!
With your argument about the leap frog integration and the pointer to the reference implementation, I think you are right regarding the timestep.

Regarding the variance, it says specifically in the documentation

> $\mathbf{R}_i$ is an uncorrelated random force whose components are chosen from a normal distribution with mean zero and **variance** $2m_i \gamma k_B T$.

which is confusing, as it should actually be a standard normally distributed variable.

I propose we change it
https://github.com/openmm/openmm/pull/4138

**Comment by peastman** [comment]
I see what you mean.  Yes, you're right.
