### ISSUE TITLE
Using LJPME on a CustomNonbondedForce

### ISSUE THREAD

**Issue by AnastasiaCroitoru** [openmm/openmm#4136]
Hi. 

I am currently using openmm with CHARMM force field and as I understand NB fixes are contained in a CustomNonbondedForce.
When using the LJPME nonbonded method for a system, are these NB fixes considered in the LJPME?

**Comment by peastman** [comment]
No, CustomNonbondedForce doesn't support PME.  The NBFIX terms are the reason we have to use CustomNonbondedForce, and also the reason LJPME isn't really possible with that force field.  PME works by spreading "charge" (literal charge for Coulomb, a similar mathematical quantity for LJ) onto a grid, then computing the interaction of that charge distribution with itself.  Once charge spreading is complete, there's no record of which atom a particular bit of charge came from.  All charge interacts the same.  So there's no way to make it behave differently for certain pairs of atom types.

In principle you could ignore NBFIX in the reciprocal space calculation, then correct for it in direct space.  That would lead to correct behavior up to the cutoff, and then a discontinuity where it jumps to using different parameters.  That might be acceptable if the cutoff were long enough.  I don't know if anyone does that.

**Comment by AnastasiaCroitoru** [comment]
_"In principle you could ignore NBFIX in the reciprocal space calculation, then correct for it in direct space. That would lead to correct behavior up to the cutoff, and then a discontinuity where it jumps to using different parameters. That might be acceptable if the cutoff were long enough. I don't know if anyone does that."_
From https://pubs.acs.org/doi/epdf/10.1021/acs.jctc.7b00948 NBfixes are only used in the real space. However, NBfixes are used in the shifting function. It is the shifting function is used in to account for the abrupt shift in the potential that happens at the  real space cutoff in a LJPME method with Lorentz−Berthelot Combination Rule . Is OpenMM using a similar function? I think yes. It is described in https://pubs.acs.org/doi/epdf/10.1021/acs.jctc.5b00726

And what was the reason to put the NBfixes in CustomNonbondedForce? Couldn't they have been added as exceptions to the NonbondedForce?  Could this be a solution so LJPME would be functional with CHARMM forcefield? 

I understand that the reaction field approximation is not applied to nonbonded exceptions in CutoffNonPeriodic or CutoffPeriodic nonbonded methods, so in this situation NBfixes can't be exceptions in the NonbondedForce .

**Comment by peastman** [comment]
An exception is really a bonded interaction.  It's used to adjust the interaction between two atoms that are covalently connected to each other (1-2, 1-3, and 1-4 interactions).  It doesn't affect the interaction of each atom with other periodic copies of the other atom, only the one it's bonded to.

NBFIX terms affect all interactions between atoms of two types, whether or not they're bonded to each other, and including all periodic copies.

If you want to try implementing what's described in that paper, you could do it by using a CustomNonbondedForce to compute the direct space part and a NonbondedForce to compute the reciprocal space part.  Call `setIncludeDirectSpace(False)` on the NonbondedForce so it won't try to compute the direct space part too.

**Comment by AnastasiaCroitoru** [comment]
Thank you.
