### ISSUE TITLE
 GRADIENT  --  Illegal Value for the Total Potential Energy

### ISSUE THREAD

**Issue by heman3333** [openmm/openmm#4137]
So I am running the simulation in NVE ensemble. For few picoseconds the simulation is ruuning fine but after that 
it gives the warning " Warning, system moved too much since last neighbor list update, try lowering nlupdate VDW ", which 
I am not able to understand. Further the simulation got terminated giving the error "  GRADIENT  --  Illegal Value for the Total Potential Energy ".  Currently I am stuck here.
I am using Tinker-HP v1.2.

**Comment by peastman** [comment]
I think you're posting in the wrong place.  This repository is for OpenMM, not Tinker-HP.

**Comment by heman3333** [comment]
Yes I realized lately. I will post my query in Tinker-HP community.
