### ISSUE TITLE
GBNeck2 Energy

### ISSUE THREAD

**Issue by ajtyadav** [openmm/openmm#4139]
Hello, OpenMM devs,
How can one separate GB energy from total energy when using the system generated from
```system = prmtop.createSystem(nonbondedMethod=NoCutoff, constraints=HBonds, implicitSolvent=GBn2)```

**Comment by peastman** [comment]
Take a look at https://openmm.github.io/openmm-cookbook/latest/notebooks/cookbook/Analyzing%20Energy%20Contributions.html.  GBn2 is calculated by a CustomGBForce.  You move it into its own force group, then use the `groups` argument of `getState()` to query its energy.
