### ISSUE TITLE
TestCudaCompiler fails when OPENMM_CUDA_COMPILER set, but passes when unset

### ISSUE THREAD

**Issue by Gareth-elliott** [openmm/openmm#4145]
Dear OpenMM devs,

I am trying to compile OpenMM from source (OpenMM 8.0.0 from GitHub, Cuda 12.0.0 and GCC 11.1.0 on the NCI Gadi supercomputer running Rocky Linux 8). Everything built fine and all the tests run, with the exception of TestCudaCompiler. I know there have been several tickets (#1624, #1485) regarding this, but I think my issue is slightly different.

To run the tests I run `export OPENMM_CUDA_COMPILER=$(which mvcc)` (they fail without setting this), and they all pass correctly, except the CudaCompiler test. I found that if I run `unset OPENMM_CUDA_COMPILER` this test then passes:

```
[greXXX@gadi-gpu-v100-0032 build]$ export OPENMM_CUDA_COMPILER=$(which nvcc)
[greXXX@gadi-gpu-v100-0032 build]$ ./TestCudaCompiler 
sh: this does not exist/openmmTempKernel0x1ee1040_3191748.log: No such file or directory
exception: Error launching CUDA compiler: 256
[greXXX@gadi-gpu-v100-0032 build]$ unset OPENMM_CUDA_COMPILER
[greXXX@gadi-gpu-v100-0032 build]$ ./TestCudaCompiler 
Done
```

Running `ldd TestCudaCompiler` shows everything is linked and available including libnvrtc which seemed to be the problem in the other tickets:
```
[gre575@gadi-gpu-v100-0032 build]$ ldd TestCudaCompiler 
	linux-vdso.so.1 (0x00007fffaace0000)
	librt.so.1 => /lib64/librt.so.1 (0x0000145579a54000)
	libOpenMMCudaCompiler.so => /home/XXX/greXXX/software/src/openmm-8.0.0/build/libOpenMMCudaCompiler.so (0x000014557984c000)
	libnvrtc.so.12 => /apps/cuda/12.0.0/lib64/libnvrtc.so.12 (0x0000145576035000)
	libOpenMMCUDA.so => /home/XXX/greXXX/software/src/openmm-8.0.0/build/libOpenMMCUDA.so (0x0000145575bfc000)
	libOpenMM.so.8.0 => /home/XXX/greXXX/software/src/openmm-8.0.0/build/libOpenMM.so.8.0 (0x00001455755ee000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00001455753ea000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00001455751ca000)
	libcuda.so.1 => /lib64/libcuda.so.1 (0x000014557350f000)
	libcufft.so.11 => /apps/cuda/12.0.0/lib64/libcufft.so.11 (0x0000145569f33000)
	libstdc++.so.6 => /apps/gcc/11.1.0/lib64/libstdc++.so.6 (0x0000145569b1d000)
	libm.so.6 => /lib64/libm.so.6 (0x000014556979b000)
	libgcc_s.so.1 => /apps/gcc/11.1.0/lib64/libgcc_s.so.1 (0x0000145569582000)
	libc.so.6 => /lib64/libc.so.6 (0x00001455691bc000)
	/lib64/ld-linux-x86-64.so.2 (0x0000145579c5c000)
```

I'm not sure if I'm doing something wrong, or whether the test failing is an issue if it is linked to libnvrtc anyway?

Thanks,

Gareth

**Comment by Alexandrina-Chen** [comment]
Second for this issue. But it seems that this issue actually doesn't affect OpenMM working fine?

**Comment by peastman** [comment]
You can ignore that.  It's really working as expected.  And once we implent #4105, the TestCudaCompiler test case and the `OPENMM_CUDA_COMPILER` environment variable will both go away.

**Comment by Gareth-elliott** [comment]
Ok great, thanks for the quick reply as usual @peastman :-)
Shall I close the ticket, or did you want to wait until #4105 is done?

**Comment by peastman** [comment]
You can close it.  It's working as intended.

**Comment by Gareth-elliott** [comment]
Thanks @peastman :-)
