### ISSUE TITLE
OpenMM CUDA matches but still get CUDA_ERROR_UNSUPPORTED_PTX_VERSION (222)

### ISSUE THREAD

**Issue by ianbongalonta** [openmm/openmm#4149]
Hi everyone,

I have newly installed OpenMM 8.0 (a7800059645f4471f4b91c21e742fe5aa4513cda) and am attempting to use it with CUDA. However, when I run `python -m openmm.testInstallation` , I get:

```
OpenMM Version: 8.0
Git Revision: a7800059645f4471f4b91c21e742fe5aa4513cda

There are 4 Platforms available:

1 Reference - Successfully computed forces
2 CPU - Successfully computed forces
3 CUDA - Error computing forces with CUDA platform
4 OpenCL - Successfully computed forces

CUDA platform error: Error loading CUDA module: CUDA_ERROR_UNSUPPORTED_PTX_VERSION (222)

Median difference in forces between platforms:

Reference vs. CPU: 6.30551e-06
Reference vs. OpenCL: 1  *** LARGE DIFFERENCE **
CPU vs. OpenCL: 1  *** LARGE DIFFERENCE **

```
Seeing the previous threads, I've made sure that the cudatoolkit and cuda match up in the installation by running `conda install -c conda-forge openmm cudatoolkit=11.7`:

```
(openmm) [XXX ~]$ module list
Currently Loaded Modulefiles:
 1) XXX   2) XXX   3) cuda/11.7(default)
(openmm) [XXX ~]$ conda list | grep cudatoolkit
cudatoolkit               11.7.1              h4bc3d14_12    conda-forge
```
And running `nvidia-smi` does not work on my cluster, so I can't obtain the driver version.

Does anyone have any suggestions to resolve the issue? Thanks!

**Comment by peastman** [comment]
That error usually indicates an incompatibility between the CUDA toolkit and driver.  Can you post the output of `nvidia-smi`?

**Comment by ianbongalonta** [comment]
Hi Peter,

Group members and I did some digging and it was indeed an issue with incompatibility between the CUDA toolkit and driver, and it ended up working if I did `conda install -c conda-forge openmm cudatoolkit=11.2.`

Thanks and have a good day!

**Comment by jchodera** [comment]
@peastman : Perhaps a good candidate for the [FAQ](https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions)?
