### ISSUE TITLE
Parametrize protein with uncapped residues

### ISSUE THREAD

**Issue by aizvorski** [openmm/openmm#4152]
I'd like to parametrize a (fragment of) a protein where the backbone has been cut at certain residues but no caps have been added: it would look like NH-CA1-C(=O)- ... -NH-CAn-C(=O) 

The first and last residue here aren't ionized (NH3+ and COO-) and also aren't capped with ACE/NME, and aren't capped with hydrogens either.  This would be very useful in many cases where it's necessary to simulate a partial protein but adding ACE/NME can introduce clashes.

Desired behavior: treat these like normal (middle of chain, not terminal) residues, and add any terms where all participating atoms exist; so for example in the first residue there would be a H-N-CA1 angle term, but not a previousC-N-H angle term.

Is it possible to do this with the Patches mechanism?

Using the CTER/NTER patches in charmm36.xml as example, would something really simple like this work?

```
<Patch name="NCUT">
    <RemoveExternalBond atomName="N"/>
</Patch>

<Patch name="CCUT">
    <RemoveExternalBond atomName="C"/>
</Patch>
```

(I'm mainly interested in doing this on top of amber14-all.xml)

**Comment by peastman** [comment]
I think that ought to work.  You'll also need `<ApplyToResidue>` tags to tell it which residues the patch can be applied to.

**Comment by aizvorski** [comment]
@peastman I kinda have this working, but I think I found a bug that gets triggered by patches that neither add nor change atoms but only modify bonds.

Minimal reproduction:
```
import openmm as mm
import openmm.app as app
import openmm.unit as unit
ff = app.ForceField('amber14-all.xml', 'cut.xml')
pdb = app.PDBFile('ala_cut.pdb')

system = ff.createSystem(
    pdb.topology,
    nonbondedMethod=app.CutoffNonPeriodic,
    nonbondedCutoff=1 * unit.nanometer,
)
```

Result:
```
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
Cell In[5], line 1
----> 1 ff = app.ForceField('amber14-all.xml', 'cut.xml')
      2 pdb = app.PDBFile('ala_cut.pdb')
      4 system = ff.createSystem(
      5     pdb.topology,
      6     nonbondedMethod=app.CutoffNonPeriodic,
      7     nonbondedCutoff=0.9 * unit.nanometer,
      8 )

File ~/anaconda3/envs/main-env/lib/python3.10/site-packages/openmm/app/forcefield.py:214, in ForceField.__init__(self, *files)
    212 self._templateMatchers = []
    213 self._templateGenerators = []
--> 214 self.loadFile(files)

File ~/anaconda3/envs/main-env/lib/python3.10/site-packages/openmm/app/forcefield.py:394, in ForceField.loadFile(self, files, resname_prefix)
    392     atom = ForceField._PatchAtomData(bond.attrib['atomName'])
    393     patchData.deletedExternalBonds.append(atom)
--> 394 atomIndices = dict((atom.name, i) for i, atom in enumerate(patchData.addedAtoms[atomDescription.residue]+patchData.changedAtoms[atomDescription.residue]))
    395 for site in patch.findall('VirtualSite'):
    396     patchData.virtualSites[atomDescription.residue].append(ForceField._VirtualSiteData(site, atomIndices))

UnboundLocalError: local variable 'atomDescription' referenced before assignment
```

Input files attached.

[ala_cut.pdb.txt](https://github.com/openmm/openmm/files/12189928/ala_cut.pdb.txt)
[cut.xml.txt](https://github.com/openmm/openmm/files/12189929/cut.xml.txt)


I think what's going on is that `atomDescription` would be set by any AddAtom/ChangeAtom/RemoveAtom, but here there aren't any so it is never set, and hence trying to use `atomDescription.residue` fails

Changing the line that errors out to `atomIndices = dict()` seems to work in this case, but is probably not the correct general fix.

openmm=8.0.0           py310h5728c26_1    conda-forge on ubuntu 20.04LTS

**Comment by peastman** [comment]
That code is definitely broken.  It's trying (incorrectly) to handle a particular combination of features: a multi-residue patch that involves virtual sites.  But that case doesn't work for deeper reasons: see #2848.  And in the process, it's causing your code to fail.  I'll fix it in the simple way, and leave a more complete fix to when we address the other issue.
