### ISSUE TITLE
Compiling on very old compilers needs <cstddef> include for pocketfft support 

### ISSUE THREAD

**Issue by hmacdope** [openmm/openmm#4154]
When compiling on a very old compiler `gcc-4.8.5` in a docker container as part of exploring some GLIBC symbol  versioning issues, I came across the problem that `openmm/libraries/pocketfft/include/pocketfft_hdronly.h` fails with 
` 'max_align_t' was not declared in this scope`

This is because std:max_align wasn't a thing in gcc versions that old. Can be fixed with a simple #include <cstddef>.

**Comment by peastman** [comment]
OpenMM requires a compiler that supports C++11.  If I recall correctly, the earliest GCC version with full support was 5.1.

**Comment by hmacdope** [comment]
If I am reading this table correctly right I think it might by 4.8.1 https://gcc.gnu.org/projects/cxx-status.html#cxx11

**Comment by peastman** [comment]
4.8.1 had experimental support for ["all of the major features"](https://gcc.gnu.org/gcc-4.8/cxx0x_status.html) of C++11.  But it wasn't fully compliant yet.

**Comment by peastman** [comment]
4.8.1 had experimental support for ["all of the major features"](https://gcc.gnu.org/gcc-4.8/cxx0x_status.html) of C++11.  But it wasn't fully compliant yet.

Is there a reason you need to use such an old compiler?  Much newer versions are available even for fairly old OSes.

**Comment by hmacdope** [comment]
The aim was to build on oldest possible GLIBC but I may be barking up the wrong tree with that one. I have sent you some private correspondence. Would you be happy talking further offline?

**Comment by peastman** [comment]
Sure, let's talk offline.  You can still use a newer compiler while building against an old glibc.

**Comment by jchodera** [comment]
@hmacdope : My understanding is that we're using the [conda-forge compiler suite](https://anaconda.org/conda-forge/compilers), which should be sufficiently recent since we use the same compilers to build the OpenMM conda-forge package, which is our primary distribution mechanism. If we're not doing that, something is wrong.

**Comment by hmacdope** [comment]
Closing as no official support for compilers this old.
