### ISSUE TITLE
Strange protein and water position in MD trajectory

### ISSUE THREAD

**Issue by GuhLelouch** [openmm/openmm#4158]
Dear all,

When I open on PyMOL the resulting trajectory (pdb) of a simulation of my homotetrameric protein, the tetramer appears to be split into two dimers that are located in weird positions in the simulation box. In addition, the water molecules also appear to be weirdly distributed. The script I used to run this is the same as the lysozyme tutorial, except for the input pdb file. In fact, the original script yields a similar result for lysozyme. Is this a problem with defining the simulation box or merely an artifact and the simulation is probably OK? How can I fix this?

![image](https://github.com/openmm/openmm/assets/101325985/e800581d-3b3a-4fc5-bdf6-d7419a2f696d)
![image](https://github.com/openmm/openmm/assets/101325985/da68931a-06ff-40f0-889f-83f308404037)

Thank you for any help you can provide.

P.S.: I apologize for my second post in a row. I haven't run MD simulations in 7 years and I wasn't an expert back then. I'm also new to OpenMM.

**Comment by peastman** [comment]
See [this FAQ entry](https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#periodic).  It explains what's going on.

**Comment by GuhLelouch** [comment]
@peastman Thanks for the information. I'll try the proposed solutions and update the post after I've done that.

**Comment by peastman** [comment]
Were you able to solve it?  Is it ok to close this issue?
