### ISSUE TITLE
setPositions not working

### ISSUE THREAD

**Issue by helmutcarter** [openmm/openmm#4165]
When I try running `simulation.context.setPositions(modeller.positions)` I get the error `ValueError: in method Context_setPositions, argument 2 could not be converted to type std::vector< Vec3,std::allocator< Vec3 > > const &`

I tried using `from openmm.vec3 import Vec3`and it isn't making a difference. 

I see that this issue has been encountered [before](https://github.com/openmm/openmm/issues/2385).

OpenMM Version: 8.0.0.dev-a780005
Numpy Version: 1.25.1

**Comment by peastman** [comment]
Can you post your code?  You're passing the wrong value, but without seeing your code I can't tell what you're passing.

**Comment by helmutcarter** [comment]
Thank you so much for the reply! My code is as follows:
```
from openmm.app import *
from openmm import *
from openmm.unit import *
from sys import stdout
from openmmforcefields.generators import SystemGenerator
from rdkit import Chem
from openff.toolkit import Molecule

ligand_mol = Molecule.from_pdb_and_smiles('/home/helmut/tutorials/GIST_tutorial/BTN_from_SMILES.pdb', '[H][C@]12CS[C@@H](CCCCC(O)=O)[C@@]1([H])NC(=O)N2')

modeller = Modeller(ligand_mol.to_topology().to_openmm(), ligand_mol.conformers[0])


system_generator = SystemGenerator(small_molecule_forcefield='gaff-2.11')
system = system_generator.create_system(modeller.topology, molecules=ligand_mol)

integrator = LangevinMiddleIntegrator(300*kelvin, 1/picosecond, 0.004*picoseconds)

simulation = Simulation(modeller.topology, system, integrator)

# from openmm.vec3 import Vec3
simulation.context.setPositions(modeller.positions.to_openmm)
```

**Comment by helmutcarter** [comment]
I don't know why the error is occuring in the first place, but I have found that if I invoke the __array__() method of my modeller positions to convert it to a numpy array, and change my integrator from LangevinMiddleIntegrator (gave a different error) to LangevinIntegrator it works. How well, I'm not sure. 

Below is the results of a short MD sim:
Step|Total Energy (kJ/mole)|Temperature (K)|Box Volume (nm^3)|Speed (ns/day)
|---|-------------------|-----------------|---|---|
1000|-20.135841557913167|305.2844911731301|8.0|0
2000|-57.440602477550854|289.12677656177084|8.0|513
3000|19.070475597042986|319.33207183409866|8.0|515
4000|-21.984676785888723|327.5337707353236|8.0|521
5000|4.307792869669029|279.5674094721199|8.0|524
6000|-47.025387225071825|192.325288153385|8.0|525
7000|-25.470890858819928|215.442532347302|8.0|524
8000|-15.75756628272805|340.8574157242899|8.0|524
9000|-24.919885090535573|283.2755104277406|8.0|523
10000|39.75885128752219|396.8011243233574|8.0|522

So I don't know if I just forced it to work and it's still failing or if this is just how it is.

**Comment by peastman** [comment]
You need to call `to_openmm()` on the conformer before passing it to Modeller.  It's an object from OpenFF-Toolkit that OpenMM doesn't know what to do with.

You should definitely use LangevinMiddleIntegrator rather than LangevinIntegrator.  It uses a better algorithm.

**Comment by peastman** [comment]
I'm closing this since I believe the question has been answered.  Feel free to reopen it if I missed something.
