### ISSUE TITLE
Building virtual site based on an arbitrary amount of atoms?

### ISSUE THREAD

**Issue by AlexanderJussupow** [openmm/openmm#4166]
Hi,

I want to add virtual atoms at protein domain centers to add non-bonded forces between them. However, I see only approaches to build virtual sites based on two or three atoms (TwoParticleAverageSite, ThreeParticleAverageSite, OutOfPlaneSite, LocalCoordinatesSite), but not based on an arbitrary amount of particles. Am I missing something?

Best

Alex

**Comment by peastman** [comment]
LocalCoordinatesSite supports more than three atoms.  Can you explain what you want to do?  How do you want to compute the virtual site positions, and what will you use them for?

**Comment by AlexanderJussupow** [comment]
> LocalCoordinatesSite supports more than three atoms. Can you explain what you want to do? How do you want to compute the virtual site positions, and what will you use them for?

Thanks for the quick response! I want to simply create virtual atoms based on all C-alpha atoms in a protein domain. I would like to add additional non-bonding interactions between the virtual atoms to slightly adjust the average interaction strength between the individual protein domains. I will look closer into LocalCoordinatesSite. My impression was that it defined a coordinate system based on three atoms!

**Comment by peastman** [comment]
How do you want to calculate the virtual site positions?  You said they're based on the CA atoms, but presumably they depend on more than just that?  Can you give the exact formula you want to use?

**Comment by AlexanderJussupow** [comment]
> How do you want to calculate the virtual site positions? You said they're based on the CA atoms, but presumably they depend on more than just that? Can you give the exact formula you want to use?


No, I just want to use the geometrical center of a group of CA atoms, nothing fancy.

**Comment by peastman** [comment]
That should be easy to do with LocalCoordinatesSite.  Set `originWeights` to put the origin at the average of their positions, and set `localPosition` to (0, 0, 0).

**Comment by peastman** [comment]
I'm closing this since I believe the question has been answered.  Feel free to reopen it if I missed something.
