### ISSUE TITLE
Neighbor lists without cutoffs

### ISSUE THREAD

**Issue by philipturner** [openmm/openmm#4169]
I was trying to profile performance of a diamondoid simulation, and was finding where $O(n^2)$ scaling set in when not using a cutoff. There was a runtime crash when calling `setVelocitiesToTemperature(298)`, which ultimately stemmed from the problem below.

A few months ago, I suggested an optimization for very small systems. Skip the neighbor list when the overhead exceeds the theoretical benefit of $O(n)$ scaling. Before then, the code base had always used cutoffs in tandem with neighbor lists. Now I get a crash at runtime because I use the neighbor list without a cutoff.

**Comment by peastman** [comment]
Can you post a script to reproduce the problem?

**Comment by philipturner** [comment]
I made a rather long file implementing the MM4 forcefield, but here is the line where it crashed: https://github.com/philipturner/molecular-renderer/blob/08d657cfb417c3516e4df7c23b041c0a5a866196/Sources/MolecularRendererApp/Simulation/MM4/MM4.swift#L822

Here is the nonbonded force: https://github.com/philipturner/molecular-renderer/blob/08d657cfb417c3516e4df7c23b041c0a5a866196/Sources/MolecularRendererApp/Simulation/MM4/MM4.swift#L166-L260

I activated nearest neighbor lists without a cutoff. Here is how I activated it in OpenMM-Metal. In the permalink, it's force-enabled (`"1"` instead of `"0"`): https://github.com/philipturner/molecular-renderer/blob/08d657cfb417c3516e4df7c23b041c0a5a866196/Sources/MolecularRendererApp/Simulation/initOpenMM.swift#L15-L16

Here is the file in OpenMM-Metal, which detects `useNeighborList`. Is it based on "OpenCLNonbondedUtilities" from the main repo: https://github.com/philipturner/openmm-metal/blob/main/platforms/metal/src/MetalNonbondedUtilities.cpp

I do intend to use a cutoff for efficiency, so fixing this bug isn't too much of a priority. Just have to omit some data from my benchmarks.

**Comment by peastman** [comment]
Does the error happen with OpenCL, or only with Metal?

**Comment by philipturner** [comment]
I haven't tried the OpenCL backend, but the one from OpenMM 8.0.0 is missing a lot of recent features. I'm pairing OpenMM-Metal with the OpenMM 8.0.0 conda binary instead of compiling OpenMM 8.1.0 from sources.

**Comment by peastman** [comment]
It would be helpful to know whether this problem is present in the OpenCL and CUDA platforms, or whether it was introduced in adapting the changes to Metal.

What exactly is the error that happens?  Can you give more detail about what goes wrong?

**Comment by philipturner** [comment]
It crashes because none of the objects are initialized. The CLKernel for `findBlockBounds` is null, some OpenCL arrays are null, etc. Then it throws a `cl::Error` (`clSetKernelArg`) without a helpful description.

> It would be helpful to know whether this problem is present in the OpenCL and CUDA platforms

I skimmed through the current impl and it doesn't seem much different than mine. Unless there's specifically code there to handle the case, it will probably still happen.

> or whether it was introduced in adapting the changes to Metal.

My change was, due to inability to implement OpenMM 8.1.0 changes, I had to decouple usage of the NNL from usage of the cutoff. The user needs to force-activate or force-deactivate the nearest neighbor list. Probably force-activated in a situation OpenMM never expected.

**Comment by peastman** [comment]
> The CLKernel for findBlockBounds is null

That's not the case in the OpenCL implementation.  The kernel gets created inside `createKernelsForGroups()`, which is called at the start of `prepareInteractions()`.  The check for the `useNeighborList` flag comes several lines later.

https://github.com/openmm/openmm/blob/116aed3927066b0a53eba929110d73f3dafb64bd/platforms/opencl/src/OpenCLNonbondedUtilities.cpp#L346-L356

**Comment by philipturner** [comment]
The crash originally occurs at the call to `setPeriodicBoxArgs`. `(!useNeighborList)` evaluates to **false** and the function **doesn't** return early. Then it crashes while setting the periodic arguments of a null CLKernel.

> That's not the case in the OpenCL implementation. The kernel gets created inside createKernelsForGroups(), which is called at the start of prepareInteractions(). The check for the useNeighborList flag comes several lines later.

I backtrace the original crash to `createKernelsForGroups`, where it hadn't actually created kernels. I had to change `if (useCutoff)` to `if (useCutoff || useNeighborList)` for it to create them. Then it crashed when calling `getDeviceBuffer()` on the null CLBuffer `interactionCount`.

https://github.com/philipturner/openmm-metal/blob/ebe7307049491096dc8dc232fa27f887bc82450b/platforms/metal/src/MetalNonbondedUtilities.cpp#L608C61-L608C77

**Comment by philipturner** [comment]
I can't recall whether I traced it to this. Adding a check for `useCutoff || useNeighborList` might fix the crash.

https://github.com/philipturner/openmm-metal/blob/ebe7307049491096dc8dc232fa27f887bc82450b/platforms/metal/src/MetalNonbondedUtilities.cpp#L349

**Comment by peastman** [comment]
If `!useNeighborList` is false, that means `useNeighborList` is true.  Hence it isn't using the optimization we're talking about.

**Comment by philipturner** [comment]
Yeah, the point was to measure the overhead of neighbor lists without the benefit of skipping interactions beyond the cutoff.

**Comment by peastman** [comment]
Neighbor lists are never used when there's no cutoff.  Lots of places in the code assume that.

If you want to measure the overhead of the neighbor list, compare `NoCutoff` to `CutoffNonPeriodic` with a cutoff larger than the very largest distance between any two particles in the system.
