### ISSUE TITLE
Unexplained crash in OpenMM_CustomIntegrator_create

### ISSUE THREAD

**Issue by philipturner** [openmm/openmm#4172]
I currently use a 2.5 fs timestep, and am trying to extend that to a hybrid scheme. I wish to compute bonded forces at 2.5 fs and nonbonded forces at 5 fs, improving simulation speed. As MTSIntegrator is not accessible through the C API, the only way to do this is through a custom integrator. I tried to copy the Python code for MTSIntegrator into Swift (via the C bindings). However, the first line of code immediately crashed.

```swift
let integrator = OpenMM_CustomIntegrator(stepSize: 2.5 * OpenMM_PsPerFs) // <- crash here
integrator.addPerDofVariable(name: "x1", initialValue: 0)
integrator.addUpdateContextState()

func createSubsteps(parentSubsteps: Int, groups: [SIMD2<Int>].SubSequence) {
  let (group, substeps) = (groups.first!.x, groups.first!.y)
  let stepsPerParentStep = substeps / parentSubsteps
  precondition(substeps % parentSubsteps == 0)
  precondition((0..<32).contains(group))
  
  for _ in 0..<stepsPerParentStep {
    let velocity = """
      v + 0.5 * (dt / \(substeps)) * f\(group) / m
      """
    integrator.addComputePerDof(variable: "v", expression: velocity)
    if groups.count == 1 {
      integrator.addComputePerDof(variable: "x", expression: """
        x + (dt / \(substeps)) * v
        """)
      integrator.addComputePerDof(variable: "x1", expression: "x")
      integrator.addConstrainPositions()
      integrator.addComputePerDof(variable: "v", expression: """
        v + (x - x1) / (dt / \(substeps))
        """)
      integrator.addConstrainVelocities()
    } else {
      
    }
    integrator.addComputePerDof(variable: "v", expression: velocity)
  }
}
createSubsteps(parentSubsteps: 1, groups: [SIMD2(0, 1)])
integrator.addConstrainVelocities()
```

I narrowed it to `OpenMM_CustomIntegrator_create` returning a null pointer. When no plugins are loaded, it works just fine. When I call `loadPluginsFromDirectory()` to load the Metal plugin, it starts returning null. It doesn't do this when calling the Python API from Python REPL, or the C++ API from the OpenMM test suite. There is no error message to diagnose this, but I pasted the assembly code at the crash site.

<img width="587" alt="Screenshot 2023-08-04 at 10 01 48 PM" src="https://github.com/openmm/openmm/assets/71743241/79848104-3293-49ca-acc3-52ef7cdf7b92">

I also disabled environment variables typically used with the Metal plugin, so that the Python and C++ environments would have the same setup. It still crashed.

<img width="626" alt="Screenshot 2023-08-04 at 10 13 29 PM" src="https://github.com/openmm/openmm/assets/71743241/33b1d25c-e2a5-41e8-8320-592ed8e81cda">

**Comment by peastman** [comment]
Here's the implementation of that function:

```c++
OPENMM_EXPORT OpenMM_CustomIntegrator* OpenMM_CustomIntegrator_create(double stepSize) {
    return reinterpret_cast<OpenMM_CustomIntegrator*>(new OpenMM::CustomIntegrator(stepSize));
}
```

Loaded plugins shouldn't have any impact.  They don't get invoked until you create a Context.  That makes we wonder if it's memory corruption, perhaps caused by something in loading the plugin?  Try loading the plugins one at a time with `Platform::loadPluginLibrary()` instead of all at once.  Can you narrow down which is responsible?

**Comment by philipturner** [comment]
Found the issue! It was here:

https://github.com/openmm/openmm/blob/0c7f2501f31934c87a12271a3557782f7ce63615/openmmapi/src/CustomIntegrator.cpp#L47-L52

https://github.com/openmm/openmm/blob/0c7f2501f31934c87a12271a3557782f7ce63615/openmmapi/src/CustomIntegrator.cpp#L346-L350

In the plugin's CMake file, I had added `-DLEPTON_USE_JIT`. However, the OpenMM main branch seems to have that disabled by default. I checked this box in the Xcode project and it didn't crash.

```
# Make sure that Lepton::CompiledExpression class has the same structure as in the main library
INCLUDE_DIRECTORIES(BEFORE ${OPENMM_SOURCE_DIR}/libraries/asmjit)
SET(EXTRA_COMPILE_FLAGS "${EXTRA_COMPILE_FLAGS} -DLEPTON_USE_JIT")
```

<img width="288" alt="Screenshot 2023-08-05 at 8 23 56 AM" src="https://github.com/openmm/openmm/assets/71743241/f9809bd5-b8b0-495e-937e-546655045f3a">

**Comment by peastman** [comment]
Interesting.  That must be a security feature.

**Comment by philipturner** [comment]
It works, and I got a 25% speedup, only because I had to revert to 2.0 fs bonded and 4.0 fs nonbonded. 5.0 fs was not stable.
