### ISSUE TITLE
One flush significantly affects AMD HIP on Windows

### ISSUE THREAD

**Issue by bdenhollander** [openmm/openmm#4173]
I've been testing the OpenMM-HIP plugin on Windows since AMD released the HIP SDK. I noticed that gbsa and rf did not improve as significantly as other tests compared to [Linux](https://github.com/openmm/openmm/pull/3934#issuecomment-1407969726).

Using Radeon GPU Profiler, I tracked the slowdown to this particular flush after `integrateLangevinMiddlePart3`.

https://github.com/openmm/openmm/blob/0c7f2501f31934c87a12271a3557782f7ce63615/platforms/common/src/CommonKernels.cpp#L5564-L5568

Eliminating that flush for HIP by adding an `#ifndef __HIP_PLATFORM_AMD__` inside `#ifdef WIN32` saves 170-200 us between `integrateLangevinMiddlePart3` and `calcCenterOfMassMomentum` and gives a massive speedup on gbsa.

Results for Radeon RX 6600 on Windows 10:

| Benchmark     | OpenCL (ns/day) | HIP (ns/day) | HIP Ratio | HIP No Flush (ns/day) | HIP No Flush Ratio |
|---------------|-----------------|--------------|-----------|-----------------------|--------------------|
| gbsa          | 416.193         | 640.257      | 153.84%   | 1069.68               | 257.02%            |
| rf            | 431.23          | 556.657      | 129.09%   | 773.387               | 179.34%            |
| pme           | 257.497         | 463.566      | 180.03%   | 525.933               | 204.25%            |
| apoa1rf       | 114.647         | 190.589      | 166.24%   | 216.402               | 188.76%            |
| apoa1pme      | 73.8864         | 148.097      | 200.44%   | 153.661               | 207.97%            |
| apoa1ljpme    | 57.8713         | 122.838      | 212.26%   | 126.787               | 219.08%            |

Amoeba tests are currently crashing on Windows OpenMM-HIP and are not included.

**Comment by peastman** [comment]
Interesting.  What effect does it have on OpenCL?

Note that flushing the queue is expected to hurt performance, but it helps keep the UI responsive.  Windows is rarely used to run production simulations, with one big exception: Folding@home.  There were a lot of complaints from donors that it was making their computers unresponsive.  Adding the flush fixed the problem, and on larger systems it only has a small effect on speed.

**Comment by bdenhollander** [comment]
Eliminating that flush without changing any other flushes doesn't help OpenCL.

| Benchmark     | OpenCL (ns/day) | OpenCL No Flush (ns/day)| Ratio OpenCL No Flush |
|---------------|-----------------|--------------------------|-----------------------|
| gbsa          | 416.193         | 414.454                  | 99.58%                |
| rf            | 431.23          | 426.827                  | 98.98%                |
| pme           | 257.497         | 257.296                  | 99.92%                |
| apoa1rf       | 114.647         | 114.821                  | 100.15%               |
| apoa1pme      | 73.8864         | 71.9531                  | 97.38%                |
| apoa1ljpme    | 57.8713         | 56.5574                  | 97.73%                |

A different flush change is more effective for AMD using OpenCL on Windows: #3973 

Flushes were added over 10 years ago in https://github.com/openmm/openmm/commit/65c389ff1d8d93be1769216fdfb107c80f898936. GFLOPS, GPU scheduling and task switching have improved a lot since then. Instead of a flush after specific calls, a timer based flush might make more sense and have a similar frequency on small and large systems. For example, a flush in `computeNonbonded` could check if it's been more than 200 ms since a flush was done and reset the timer after calling flush.

**Comment by peastman** [comment]
That's a good idea.  200 ms is probably much too long.  To keep the UI smooth, you want to maintain 30 fps.  Flushing if it has been more than 20 ms should be about right.

**Comment by bdenhollander** [comment]
I took screenshots from profiling each of the six tests above in HIP. Even during heavy utilization in apoa1ljpme, there is still significant white space when the GPU is not fully utilized and can update UI.

gbsa
![gbsa-utilization](https://github.com/openmm/openmm/assets/44237618/23a776ca-cc9a-4b99-8ac7-2d5054478d7a)

rf
![rf-utilization](https://github.com/openmm/openmm/assets/44237618/b6a3bd71-8880-4855-b3c3-81e1bd8c4774)

pme
![pme-utilization](https://github.com/openmm/openmm/assets/44237618/c76cacd6-51eb-4207-b140-2be873ee25dc)

apoa1rf
![apoa1rf-utilization](https://github.com/openmm/openmm/assets/44237618/2c7c8292-5436-4438-9f12-22858970a53f)

apoa1pme
![apoa1pme-utilization](https://github.com/openmm/openmm/assets/44237618/380543bd-3c1a-4efd-8859-574d0b73fdba)

apoa1ljpme
![apoa1ljpme-utilization](https://github.com/openmm/openmm/assets/44237618/56e34d5b-2647-4cbb-9be1-fc8b3c3d8809)

Side note: Unlike OpenCL on AMD, HIP enables a separate PME stream so there are far more overlapping kernels.
