### ISSUE TITLE
PME implementation using the CustomNonbondedForce?

### ISSUE THREAD

**Issue by zhenyuwei99** [openmm/openmm#4175]
Hi,
I printed out all the force object when I create a system from a CharmmPsfFile object, and here is the result:

```<openmm.openmm.HarmonicBondForce; proxy of <Swig Object of type 'OpenMM::HarmonicBondForce *' at 0x7ff850f52990> >
<openmm.openmm.HarmonicAngleForce; proxy of <Swig Object of type 'OpenMM::HarmonicAngleForce *' at 0x7ff850f52c00> >
<openmm.openmm.HarmonicBondForce; proxy of <Swig Object of type 'OpenMM::HarmonicBondForce *' at 0x7ff850f529c0> >
<openmm.openmm.PeriodicTorsionForce; proxy of <Swig Object of type 'OpenMM::PeriodicTorsionForce *' at 0x7ff850f52cf0> >
<openmm.openmm.CustomTorsionForce; proxy of <Swig Object of type 'OpenMM::CustomTorsionForce *' at 0x7ff850f52d80> >
<openmm.openmm.CMAPTorsionForce; proxy of <Swig Object of type 'OpenMM::CMAPTorsionForce *' at 0x7ff850f52e10> >
<openmm.openmm.NonbondedForce; proxy of <Swig Object of type 'OpenMM::NonbondedForce *' at 0x7ff850f52ea0> >
<openmm.openmm.CustomNonbondedForce; proxy of <Swig Object of type 'OpenMM::CustomNonbondedForce *' at 0x7ff850f52f30> >
<openmm.openmm.CMMotionRemover; proxy of <Swig Object of type 'OpenMM::CMMotionRemover *' at 0x7ff850f52fc0> >
``` 

I notice that two NonbondedForce: NonbondedForce and CustomNonbondedForce object exists. I thought that may correpsonds to the seperation of LJ and coulombic interaction. I also try to set all the charges to be zero and this operation did not effect the energy of NonbondedForce object so I guess this object is correpsponding to the LJ part. However, I think the NonbondedForce object has already has a implementation of long-range solver like PME. So why (1) we seperatly create a CustomNonbondedForce and (2) How to implement the PME for coulombic force by using the CustomNonbondedForce?

Best,

**Comment by peastman** [comment]
The CustomNonbondedForce implements LJ.  The Coulomb interaction is handled by NonbondedForce.

If you modify the NonbondedForce after the Simulation/Context has already been created, it won't have any effect.  You can call `updateParametersInContext()` on the NonbondedForce to copy the changes over.  Or just make the changes before you create the Context.

**Comment by zhenyuwei99** [comment]
Hi Peter,
Thanks for your reply. You are right! I am also curious why openmm seperatly calculate the lj interaction by using an CustomNonbondedForce? I notice that the NonbondedForce object also take the epislon and simga as the parameters. I think this seperation requires a double calculation of the inter distance between pairs which is the main computational cost in the MD simulation.

Best,

**Comment by peastman** [comment]
CHARMM uses NBFIX terms, which NonbondedForce doesn't support.  That's why we implement it with a CustomNonbondedForce instead.

There's no extra cost.  Everything gets merged together into a single GPU kernel.

**Comment by zhenyuwei99** [comment]
> Everything gets merged together into a single GPU kernel.

This quiet surprising me. I mean, in my idea, we have different kernel for every Force object and excute them sequencely. But this seems we have a kernel dynamicly created based on different combination of Force object?

**Comment by peastman** [comment]
Correct.  [Here](https://github.com/openmm/openmm/blob/master/platforms/cuda/src/kernels/nonbonded.cu) is the nonbonded kernel.  You'll see that the symbol `COMPUTE_INTERACTION` appears in it at various points.  At runtime that gets replaced with the code to compute whatever nonbonded interactions are in your System.

**Comment by peastman** [comment]
I'm closing this since I believe the question has been answered.  Feel free to reopen it if I missed something.
