### ISSUE TITLE
Loadin Allo form of amino acids

### ISSUE THREAD

**Issue by SudhanshuShanker** [openmm/openmm#4178]
Hi,
I have generated openMM ffxml files for ALLO versions of ILE (IIL) and THR (ALO) [ref: swisssidechain.ch] but whenever I am trying to load these parameters, I am getting errors like: 
"Multiple non-identical matching templates found for residue 226 (ALO): THR, ALO."
Can someone please suggest to me a standard way to use both ALLO and non-ALLO parameters together?

Best,
Sudhanshu

**Comment by peastman** [comment]
You can use the `residueTemplates` argument to `createSystem()`.  If two templates have identical chemical graphs (elements and bonds), the ForceField can't figure out on its own which to use for each residue.  You need to tell it.  For example, if you want to use ILE for residue 15 and IIL for residue 71, you can do this:

```python
residues = list(template.residues)
residueTemplates = {residues[15]:'ILE', residues[71]:'IIL'}
system = forcefield.createSystem(topology, residueTemplates=residueTemplates, ...)
```
