### ISSUE TITLE
How to solvate a gro/top system?

### ISSUE THREAD

**Issue by ale94mleon** [openmm/openmm#4180]
Hello, I am trying to solvate a system for which I have the `gro` and `top` GROMACS' files and retrieve the new `gro` and `top` files. In my case is not an option the salvation through `gmx solvate`; in addition I would like to get access to the solvent model that comes with OpenMM. My idea is something like:

```python
gro = app.GromacsGroFile('conf.gro')
top = app.GromacsTopFile('topology.top', periodicBoxVectors=gro.getPeriodicBoxVectors())

modeller = app.Modeller(top, gro.positions) # This line is not valid, it just to expose the idea
modeller.addSolvent(dummy_forcefield, model='tip3p', padding=1*omm.unit.nanometer) # This line is not valid, it just to expose the idea

sytem = modeller.system # This line is not valid, it just to expose the idea

struct = parmed.openmm.load_topology(topology = top, system = system, xyz = gro.positions) # This line is not valid, it just to expose the idea

structure.save('solvated.top', overwrite=True)
structure.save('solvated.gro', overwrite=True)
```
IS there a way to do this?

**Comment by peastman** [comment]
There are a few types of objects to understand.

A Topology is a chemical description of something you want to simulate.  It's formulated in terms of atoms, elements, and bonds.

A System is a mathematical description.  It describes how to compute forces.  It is formulated in terms of force constants, partial charges, etc.

A ForceField connects the two.  It defines how to create a System from a Topology.  It specifies, for example, that a particular bond should be modeled as a harmonic energy term with a particular equilibrium length and force constant.  A different ForceField might use a different force constant for that bond, or even a different functional form.

Modeller works only with Topologies, not Systems.  It starts from a chemical description of your initial model and manipulates it to create a new chemical description.  If you want to get a System from it, you need to use a ForceField.  For example,

```python
forcefield = ForceField('amber14-all.xml', 'amber14/tip3pfb.xml')
system = forcefield.createSystem(modeller.topology, ...)
```

See the [API documentation](http://docs.openmm.org/latest/api-python/generated/openmm.app.forcefield.ForceField.html#openmm.app.forcefield.ForceField.createSystem) for more information about `createSystem()`.

**Comment by ale94mleon** [comment]
Thank you immensely for your lucid response. I now grasp the concept I had misunderstood regarding "topology." However, a new query has arisen. Let's delve into a concrete example: the interaction of a small molecule within a water environment. I am aware that utilizing the `generators` available from the [openmmforcefields](https://github.com/openmm/openmmforcefields) repository enables the derivation of parameters for GAFF, OpenFF, and Espaloma force fields.

Suppose I have already acquired force field parameters for a unique and unconventional small molecule. These parameters stem from a high-level quantum mechanics approach, resulting in a notably superior depiction of my system compared to the existing small molecule force fields.

Building upon your prior response, it appears that I must compile a force field representation in the `xml` format. This newly crafted representation would then be provided during the initialization of the `ForceField` module. Given this context, I am intrigued to ascertain if there exists a method through which I can derive the requisite `xml` force field directly from a GROMACS topology.

**Comment by peastman** [comment]
I don't think so.  ParmEd might be able to help.  But generally you can't go in that direction.  A ForceField defines the rules for assigning parameters.  You can't determine the rules from a single instance of a system that has had parameters assigned to it.

**Comment by peastman** [comment]
I'm closing this since I believe the question has been answered.  Feel free to reopen it if I missed something.
