### ISSUE TITLE
Supervised Molecular Dynamics with openmm

### ISSUE THREAD

**Issue by syedzayyan** [openmm/openmm#4183]
Are there any resources or code examples of SuMD and openmm. I know of a repo that does [SMD](https://github.com/tdudgeon/simple-simulate-complex) with open mm. But I was looking for something with SuMD.

Thank You!

**Comment by peastman** [comment]
I'm not familiar with the term supervised molecular dynamics.  Can you explain what you're asking about?

**Comment by syedzayyan** [comment]
The abstract of this paper explains it best :
https://pubs.acs.org/doi/10.1021/ci400766b

So essentially meddle with the ligand binding pathway until it binds, but scientific meddling with a tabu like search algorithm. I think 🤔.

https://github.com/molecularmodelingsection/SuMD

I also found this repo with minimal comments, and they are I think using AceMD.

For now I am closing this issue as I think the simulation part with openmm is similar. It's the between simulation runs thats the figuring out part. 

Thanks for all the help so far 🙂! You have been incredibly helpful with all my silly MD questions.
