### ISSUE TITLE
Virtual site weights outside of [0, 1]

### ISSUE THREAD

**Issue by mattwthompson** [openmm/openmm#4186]
I'm working through implementing some virtual sites in OpenMM and I'm confused about what practical limitations there are on the values of weights. The case I'm interested in is basically `TwoParticleAverageSite` but with the virtual site placed outside of the two atoms, though still on the line specified by their positions. I thought I'd try pulling this off by setting the weights to values above 1 and below 0, though still adding up to 1. (It can definitely be done with `LocalCoordinatesSite` as you [advised](https://github.com/openmm/openmm/issues/1855) many moons ago, but I wanted to see if I could use some of the more specific classes as they're easier for humans to read and understand.) The [API docs](http://docs.openmm.org/8.0.0/api-python/generated/openmm.openmm.TwoParticleAverageSite.html) say this is not allowed - fair enough, I figure, but I wanted to try it anyway. The API allows it and, to my surprise, I can minimize and run brief dynamics without a crash or obvious physical oddity. Am I missing something here? Are there sharp edges ahead that I haven't encountered yet?

I've tried to tie everything into a small example that uses only OpenMM, although I did have to use MDTraj to load this PDB file since it's particularly cursed. It's just a (funny-looking) carbon tet floating around in vacuum.

```python
import mdtraj
import openmm
import openmm.app
import openmm.unit

integrator = openmm.LangevinIntegrator(
    300 * openmm.unit.kelvin,
    1 / openmm.unit.picosecond,
    1 * openmm.unit.femtoseconds,
)

trajectory = mdtraj.load("carbontet.pdb")

system = openmm.XmlSerializer.deserialize(open("system.xml").read())

simulation = openmm.app.Simulation(
    topology=trajectory.topology.to_openmm(),
    system=system,
    integrator=integrator,
)
simulation.context.setPositions(
    openmm.unit.Quantity(
        trajectory.xyz[0],
        openmm.unit.nanometer,
    ),
)
simulation.context.computeVirtualSites()
simulation.minimizeEnergy()
simulation.context.setVelocitiesToTemperature(openmm.unit.kelvin * 300)
simulation.reporters.append(
    openmm.app.StateDataReporter(
        "data.csv",
        1000,
        step=True,
        potentialEnergy=True,
        temperature=True,
    ),
)
simulation.step(10000)
```

And I get not-insane-looking results locally, indicating at least that it's moving about and not crashing:
```
#"Step","Potential Energy (kJ/mole)","Temperature (K)"
1000,10.366592407226562,357.89840944126183
2000,11.538765907287598,123.68051871915941
3000,10.054015159606934,441.2415902627995
4000,20.30474090576172,136.20720054687015
5000,13.771326065063477,159.33941447911283
6000,13.755878448486328,253.83965547314492
7000,13.739048957824707,166.48700234459756
8000,18.948383331298828,384.7448110286437
9000,14.222991943359375,290.29142453569955
10000,16.02277374267578,279.0562601463154
```
[system.xml.txt](https://github.com/openmm/openmm/files/12352202/system.xml.txt)
[carbontet.pdb.txt](https://github.com/openmm/openmm/files/12352203/carbontet.pdb.txt)

**Comment by peastman** [comment]
I can't think of any reason it wouldn't work.  It just takes a weighted average of the two positions.  Maybe we should change the documentation to say "*usually* between 0 and 1".

**Comment by mattwthompson** [comment]
Thanks! That's certainly what I intuited as well. My confusion stemmed mostly from how clearly the documentation stated that detail and I think that slight change in wording would more than suffice here.

Hopefully we're both right here and there aren't dragons ahead - I'll close this for now as my question is answered.

**Comment by peastman** [comment]
I'm going to reopen this and mark it as documentation.  If you're right, we should clarify it.  Let us know how it goes and whether you run into any problems.
