### ISSUE TITLE
Using [constraints] vs [settles] in TIP4P/2005 water model .itp file 

### ISSUE THREAD

**Issue by Praveen-Muralikrishnan** [openmm/openmm#4187]
I wanted to use .gro and .top GROMACS files to run a simulation of a coarse-grained linear polymer in TIP4P/2005 water in OpenMM. I initially used the GromacsGroFile and GromacsTopFile to load these files but I got an error stating 'Virtual sites are not yet supported by Gromacs parsers'. I solved this error by importing ParmEd and using pmd.load_file, which, as I understand, supports virtual sites. 

However, I still faced an error with the simulation of polymer in [TIP4P/2005 water model](http://catalan.quim.ucm.es/gromacs/topol.top) (which I took from the [Carlos Vega group website](http://catalan.quim.ucm.es/)), stating 'Parent atom not bound to other 2 atoms in frame'. I was able to use the tip4pew water model without this error, so I looked at the differences between the .itp files and found out that using [settles] instead of [constraints] for constraining the distances resolved this error. The [constraints] option uses LINCS or SHAKE algorithm whereas [settles] uses SETTLE algorithm, which is specific for water. I am curious why using [constraints] doesn't work and if there is a way currently to use [constraints] and make it work.

 
[tip4p05.txt](https://github.com/openmm/openmm/files/12352456/tip4p05.txt)

**Comment by peastman** [comment]
GromacsTopFile supports the `[ virtual_sites2 ]` and `[ virtual_sites3 ]` directives.  The latter is what appears in your file, so it ought to work.  I'll see if I can figure out what's happening.

I can't comment on why the ParmEd parser isn't handling the constraints properly.  It's a completely separate library.

**Comment by peastman** [comment]
I can't reproduce the problem.  Your top file loads correctly with GromacsTopFile for me.  What OpenMM version are you using?

**Comment by Praveen-Muralikrishnan** [comment]
I am using OpenMM version 7.7.0. Is the issue because of not using a newer version of OpenMM? 

If not, I have included more details of the error message I am getting when I used GromacsTopFile with [constraints] in TIP4P/2005 model (Gromacstopfile_constraint_error.txt attached) and when I used pmd.loadfile with [constraints] in TIP4p/2005 model (parmed_constraint_error.txt attached), hope that is of some use.
[parmed_constraint_error.txt](https://github.com/openmm/openmm/files/12353703/parmed_constraint_error.txt)
[Gromacstopfile_constraint_error.txt](https://github.com/openmm/openmm/files/12353704/Gromacstopfile_constraint_error.txt)

**Comment by peastman** [comment]
I believe it should work correctly in 8.0.

**Comment by Praveen-Muralikrishnan** [comment]
It did work correctly in version 8.0 on my end as well. Seems like it is a version issue. Thank you so much for the help!

**Comment by peastman** [comment]
Great!  I'm glad it was that simple.
