### ISSUE TITLE
Integrator for system subregion a la heat exchange

### ISSUE THREAD

**Issue by SSchott** [openmm/openmm#4189]
I'd like to run some non-equilibrium sims with temperature gradient, by using a heat exchange algorithm [ref](https://pubs.aip.org/aip/jcp/article/143/12/124104/194840/An-enhanced-version-of-the-heat-exchange-algorithm). For implementing this, one would need to specify a subregion within the simulation box, or be able to make an if statement within a CustomIntegrator for each particle coordinate value. For what I could see in the documentation, this is not possible with the current implementation? Would something like this be possible with the current CustomIntegrator constructor?

**Comment by peastman** [comment]
Do you mean you want different parts of the system to be coupled to thermostats with different temperatures?  Yes, you can do that with CustomIntegrator.  Use the example code in [the API docs](http://docs.openmm.org/latest/api-c++/generated/CustomIntegrator.html) that reproduces LangevinMiddleIntegrator, but make the temperature a per-DOF variable instead of a global one.

NoseHooverIntegrator also can do it.

**Comment by SSchott** [comment]
Yes I mean different parts, but based on a specific predefined space in the simulation box, and not an immutable selection of molecules within the system. Something like a hot bath on one side of the box, and a cold bath in the opposite side.

**Comment by peastman** [comment]
You can implement that in the same way, with the temperature being a per-DOF variable, but add an extra step to calculate it based on position at each step.  For example, the following will set `T` to 300 for any particle in the region $x<2$ and 400 for any particle in the region $x>2$.

```python
integrator.addComputePerDof('T', 'select(step(_x(x)-2), 400, 300)')
```

**Comment by SSchott** [comment]
Ok, nice, I will give it a try. Theoretically, I could make a slice between 4 and 8 along the z axis by doing something like:
`integrator.addComputePerDof('T', 'select(step(_z(x)-4)*(1-step(_z(x)-8)), 400, 300)')`
?

**Comment by peastman** [comment]
Exactly.  You also could simplify it a little by replacing `(1-step(_z(x)-8))` with `step(8-_z(x))`.

**Comment by SSchott** [comment]
Just tried with a quickly built integrator, to see if  get the hang of it. I got the following error:
`Parse error in expression "select(step(_z(x)-hot_lo)*(hot_hi-step(_z(x))), m, 0)": unknown function: _z`

I have openMM 8.0. Anything I might be doing wrong here?

**Comment by peastman** [comment]
Can you show the full code?

The function `_z()` can only appear in ComputePerDof and ComputeSum steps.

**Comment by SSchott** [comment]
Thanks for the help. Right, my bad, was using the wrong function. I am getting to the point of making positions NaN now, so maybe you spot something obviously wrong here:

```
class HEXVelocityVerlet(CustomIntegrator):
    def __init__(self, dt=0.002*picoseconds, axis="z", energy_flux=0.025*kilocalories_per_mole/femtoseconds, hot=10*angstrom, cold=-10*angstrom, width=4*angstrom):
        CustomIntegrator.__init__(self, dt)

        self.energy_flux = energy_flux
        self.hot_hi = hot+width/2
        self.hot_lo = hot-width/2
        self.cold_hi = cold+width/2
        self.cold_lo = cold-width/2

        self.addGlobalVariable("energy_flux", self.energy_flux)
        self.addGlobalVariable("hot_hi", self.hot_hi)
        self.addGlobalVariable("hot_lo", self.hot_lo)
        self.addGlobalVariable("cold_hi", self.cold_hi)
        self.addGlobalVariable("cold_lo", self.cold_lo)

        self.addGlobalVariable("HOT_MASS", 1.0)
        self.addGlobalVariable("HOT_V", 1.0)
        self.addGlobalVariable("HOT_COM_KE", 0)
        self.addGlobalVariable("HOT_NT_KE", 0)
        self.addGlobalVariable("HOT_rescale", 1.0)

        self.addGlobalVariable("COLD_MASS", 1.0)
        self.addGlobalVariable("COLD_V", 1.0)
        self.addGlobalVariable("COLD_COM_KE", 0.0)
        self.addGlobalVariable("COLD_NT_KE", 0.0)
        self.addGlobalVariable("COLD_rescale", 1.0)

        self.addComputeSum("HOT_MASS",f"select(step(_{axis}(x)-hot_lo)*(hot_hi-step(_{axis}(x))), m, 0)")
        self.addComputeSum("HOT_V",f"select(step(_{axis}(x)-hot_lo)*(hot_hi-step(_{axis}(x))), m*v/HOT_MASS, 0)")
        self.addComputeGlobal("HOT_COM_KE","0.5*HOT_MASS*HOT_V*HOT_V")
        self.addComputeSum("HOT_NT_KE",f"select(step(_{axis}(x)-hot_lo)*(hot_hi-step(_{axis}(x))), 0.5*m*v*v-HOT_COM_KE, 0)")
        self.addComputeGlobal("HOT_rescale","sqrt(1+energy_flux/HOT_NT_KE)")

        self.addComputeSum("COLD_MASS",f"select(step(_{axis}(x)-cold_lo)*(cold_hi-step(_{axis}(x))), m, 0)")
        self.addComputeSum("COLD_V",f"select(step(_{axis}(x)-cold_lo)*(cold_hi-step(_{axis}(x))), m*v/COLD_MASS, 0)")
        self.addComputeGlobal("COLD_COM_KE","0.5*COLD_MASS*COLD_V*COLD_V")
        self.addComputeSum("COLD_NT_KE",f"select(step(_{axis}(x)-cold_lo)*(cold_hi-step(_{axis}(x))), 0.5*m*v*v-COLD_COM_KE, 0)")
        self.addComputeGlobal("COLD_rescale","sqrt(1-energy_flux/COLD_NT_KE)")

        self.addComputePerDof("v", f"select(step(_{axis}(x)-hot_lo)*(hot_hi-step(_{axis}(x))), HOT_rescale*v+(1-HOT_rescale)*HOT_V, v)")
        self.addComputePerDof("v", f"select(step(_{axis}(x)-cold_lo)*(cold_hi-step(_{axis}(x))), COLD_rescale*v+(1-COLD_rescale)*COLD_V, v)")
        self.addComputePerDof("v", "v+0.5*dt*f/m")
        self.addComputePerDof("x", "x+dt*v")
        self.addComputePerDof("v", "v+0.5*dt*f/m")

        self.addComputeSum("HOT_MASS",f"select(step(_{axis}(x)-hot_lo)*(hot_hi-step(_{axis}(x))), m, 0)")
        self.addComputeSum("HOT_V",f"select(step(_{axis}(x)-hot_lo)*(hot_hi-step(_{axis}(x))), m*v/HOT_MASS, 0)")
        self.addComputeGlobal("HOT_COM_KE","0.5*HOT_MASS*HOT_V*HOT_V")
        self.addComputeSum("HOT_NT_KE",f"select(step(_{axis}(x)-hot_lo)*(hot_hi-step(_{axis}(x))), 0.5*m*v*v-HOT_COM_KE, 0)")
        self.addComputeGlobal("HOT_rescale","sqrt(1+energy_flux/HOT_NT_KE)")

        self.addComputeSum("COLD_MASS",f"select(step(_{axis}(x)-cold_lo)*(cold_hi-step(_{axis}(x))), m, 0)")
        self.addComputeSum("COLD_V",f"select(step(_{axis}(x)-cold_lo)*(cold_hi-step(_{axis}(x))), m*v/COLD_MASS, 0)")
        self.addComputeGlobal("COLD_COM_KE","0.5*COLD_MASS*COLD_V*COLD_V")
        self.addComputeSum("COLD_NT_KE",f"select(step(_{axis}(x)-cold_lo)*(cold_hi-step(_{axis}(x))), 0.5*m*v*v-COLD_COM_KE, 0)")
        self.addComputeGlobal("COLD_rescale","sqrt(1-energy_flux/COLD_NT_KE)")

        self.addComputePerDof("v", f"select(step(_{axis}(x)-hot_lo)*(hot_hi-step(_{axis}(x))), HOT_rescale*v+(1-HOT_rescale)*HOT_V, v)")
        self.addComputePerDof("v", f"select(step(_{axis}(x)-cold_lo)*(cold_hi-step(_{axis}(x))), COLD_rescale*v+(1-COLD_rescale)*COLD_V, v)")

```

**Comment by SSchott** [comment]
Oki, thanks again a lot for your help. I have to figure out how to apply constraints in the other case then, and how to implement the enhanced algorithm version, but I am onto something. I'll close this for now.

**Comment by SSchott** [comment]
One last thing. I am correct in thinking I should be careful whenever I call `addComputeSum` and the mass is involved, as it will be times 3, and I should correct for this whenever calculateg, e.g., the kinetic energy?

**Comment by peastman** [comment]
The sum is over all degrees of freedom.  Whether you need to divide by three depends on what you're computing.  For kinetic energy, summing `m*v^2/2` gives the correct value, since that expands to $m(v_x^2+v_y^2+v_z^2)/2$ for each particle.  But if you really want to sum over particles rather than degrees of freedom then yes, you should divide by three.

**Comment by SSchott** [comment]
Hi Peter,
While I am getting things partially working, I am still getting significant energy drifts (beyond what has been described previously), even with a timestep of 0.5fs, so I probably have something off somewhere. I think I might be misunderstanding how the per DOF math is being done. Each DOF stores mass, x,y,z coordinates, but only v and f for the given DOF, correct? Then, for a given "y" DOF one would have m,m,m/x,y,z/0,vy,0/0,fy,0?

Below an example of where I am getting confused. So, first, I am flagging the DOFs within a region

```python
self.addComputePerDof("HOT","0")
self.addComputePerDof("HOT", f"select(step(_{axis}(x)-hot_lo)*(step(hot_hi-_{axis}(x))), 1, 0)")
```

In one of the steps, I need to calculate the velocity of the COM of one of the regions. For that I use

```python
self.addComputeSum("HOT_MASS","select(HOT, m, 0)")
#The factor 3 corrects the mass summation per DOF
self.addComputeSum("HOT_V","select(HOT, 3*m*v/HOT_MASS, 0)")
```

Here, I tried replacing the mass summation with `self.addComputeSum("HOT_MASS","select(HOT*_x(v), m, 0)")`, thinking that summing the mass only for one axis would give the value without dividing by 3, but that didn't work as I expected.

Now,  HOT_MASS and HOT_V are "scalars", which would be stored as a vector in reality, but then, I need to sum/substract the velocity of each particle within a region with respect to the region COM

```python
self.addComputePerDof("v", "select(HOT, HOT_rescale*v+(1-HOT_rescale)*HOT_V, v)")
```

As this is done per DOF, then I would be calculating for the example "y" DOF `[0,vy,0]-[HOT_V,HOT_V,HOT_V]`? Would calculating the velocity per DOF be needed then? Something like `self.addComputeSum("HOT_Vx",f"select(HOT, 3*m*_x(v)/HOT_MASS, 0)")`

Sorry for poking again about this, but I haven't found enough examples with a similar use case as what I am looking for.

**Comment by peastman** [comment]
A particle moving in 3D space has three degrees of freedom: its x, y, and z coordinates.  Each degree of freedom has a velocity associated with it: the x, y, or z coordinate of velocity.  In principle you could imagine having a separate mass associated with each degree of freedom, but we don't do that.  All three degrees of freedom for a particle use the same mass.

The mathematical notation is a little confusing, because a per-DOF calculation uses `x` to refer to the value of the degree of freedom, which might actually be the particle's y or z coordinate.  Further confusing it is that you can treat the DOFs for a particle either as three independent coordinates or as the elements of a vector.  The latter is necessary for calculations that mix up axes, like cross products.  When using vector calculations, think of x as being written in bold.  It's the vector $\mathbf{x}$, which has components $x_x$, $x_y$, and $x_z$.

**Comment by SSchott** [comment]
Ok, I had that notion already, but I guess my question is what is exactly happening for every DOF whenever I have 
```python
self.addComputePerDof("v", "v-MY_VEC")
```
If `MY_VEC` is a precomputed vector with $xyz$ components,  will I be substracting from DOFs that don't have a every component and "adding" velocities wrongly, mixing up axes whenever I don't want to? (e.g., for a given $y$ DOF, I could be substracting the $x$ and $z$ components of "MY_VEC")

And I guess this goes with me not understanding why doesn't `self.addComputeSum("MASS","select(_x(v), m, 0)")` give me the proper mass. So if I understand your last statement, for such a summation, even when it is done per DOF, it will use the particle $v_x$ component on every DOF?

**Comment by peastman** [comment]
> self.addComputePerDof("v", "v-MY_VEC")

That will set `v.x` to `v.x-MY_VEC.x`, `v.y` to `v.y-MY_VEC.y`, and `v.z` to `v.z-MY_VEC.z`.

> will I be substracting from DOFs that don't have a every component

There's no such thing as a DOF that doesn't have every component.  Every particle has three DOFs.  A per-DOF variable has a value for each DOF, meaning three for each particle.

> self.addComputeSum("MASS","select(_x(v), m, 0)")

I don't understand what that expression is meant to do.  `_x(v)` is the x component of velocity.  The select statement will evaluate to `m` if the x component of velocity is non-zero, or 0 if the x component of velocity is 0.  Is that really what you want to sum over?

**Comment by SSchott** [comment]
> There's no such thing as a DOF that doesn't have every component. Every particle has three DOFs. A per-DOF variable has a value for each DOF, meaning three for each particle.

Yes, I got that, I mean substracting by mixing components, i.e., adding y and z to a x DOF.


> I don't understand what that expression is meant to do. _x(v) is the x component of velocity. The select statement will evaluate to m if the x component of velocity is non-zero, or 0 if the x component of velocity is 0. Is that really what you want to sum over?

And here exactly is probably where I have the misunderstanding. In my head, I would be summing over one third of the DOFs, that don't have the x component as 0. But clearly this seems to be wrong 😬

**Comment by SSchott** [comment]
Ok, got it. So I just have to be careful whenever summing over `_x`,`_y`,`_z` or the mass. I managed to get the energy drift down a significant amount, thanks. :+1:.

Related to this, one option they describe in one the references is to apply the rescaling to whole molecules only. Do you see anyway in which one could do a selection per molecule?

**Comment by peastman** [comment]
Can you describe the exact selection rule you'd like to implement?

**Comment by SSchott** [comment]
Either as originally proposed, if the COM of the molecule is within the region, or if all bonded particles are in the region.

**Comment by peastman** [comment]
If you're doing this only for one molecule or a very small number of molecules, you could do it with global variables to compute the COM.  But otherwise, I don't think that's possible with CustomIntegrator.  A per-DOF computation for a particle can only depend on properties of that particle and on global variables.  It can't see other particles.

**Comment by SSchott** [comment]
Ok. Thanks again for all the input 👍
