### ISSUE TITLE
No template found for Residues after pdbfixer

### ISSUE THREAD

**Issue by allisonbarkdull** [openmm/openmm#4193]
I am trying to use openmm (version 8.0.0) to build models of protein structures in a lipid bilayer. My initial protein structures are downloaded from OPM, and then processed using pdb4amber (version 22.0) using the command "pdb4amber -i pdb_file -o output_pdb -p --add-missing-atoms". Then, I am also using pdbfixer (version 1.9.0) to prepare the structures using the commands:
fixer = pdbfixer.PDBFixer(str(pdb_file))
fixer.removeHeterogens()
fixer.findMissingResidues()
fixer.findNonstandardResidues()
fixer.replaceNonstandardResidues()
fixer.findMissingAtoms()
fixer.addMissingAtoms()
fixer.addMissingHydrogens(ph)

Then, I am trying to create a forcefield for the system with: 
forcefield = app.ForceField(amber14-all.xml, amber14/tip3pfb.xml)
system = forcefield.createSystem(modeller.topology, nonbondedMethod=CutoffNonPeriodic) #this is the line where the error message is occuring

My systems also contain ligands which I am parameterizing with espaloma:
espaloma = EspalomaTemplateGenerator(molecules=Molecule.from_rdkit(rdkit_mol, allow_undefined_stereo=True), forcefield='espaloma-0.3.1')
forcefield.registerTemplateGenerator(espaloma.generator)

The general error message I am getting is:
'No template found for residue %d (%s).  %s  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template'
For different .pdbs, I try to set up, the error is saying no template found for different residues, but when I inspect the .pdb file I cannot see anything wrong with that residue. I will attach a few examples

- for PDBID: 4PHU ([4phu_edited.txt](https://github.com/openmm/openmm/files/12373663/4phu_edited.txt)), my error message says:
No template found for residue 37 (ARG).  The set of atoms matches ARG, but the bonds are different.
Residue 37 in my input .pdb looks like:
ATOM    551  N   ARG    37      -7.213   1.345 -25.662  1.00  0.00           N  
ATOM    552  H   ARG    37      -6.933   1.805 -24.808  1.00  0.00           H  
ATOM    553  CA  ARG    37      -6.565   0.071 -26.013  1.00  0.00           C  
ATOM    554  HA  ARG    37      -6.771  -0.129 -27.064  1.00  0.00           H  
ATOM    555  CB  ARG    37      -5.048   0.175 -25.823  1.00  0.00           C  
ATOM    556  HB2 ARG    37      -4.660   0.993 -26.431  1.00  0.00           H  
ATOM    557  HB3 ARG    37      -4.825   0.366 -24.773  1.00  0.00           H  
ATOM    558  CG  ARG    37      -4.391  -1.133 -26.252  1.00  0.00           C  
ATOM    559  HG2 ARG    37      -4.778  -1.951 -25.645  1.00  0.00           H  
ATOM    560  HG3 ARG    37      -4.613  -1.324 -27.302  1.00  0.00           H  
ATOM    561  CD  ARG    37      -2.881  -1.029 -26.063  1.00  0.00           C  
ATOM    562  HD2 ARG    37      -2.494  -0.211 -26.671  1.00  0.00           H  
ATOM    563  HD3 ARG    37      -2.658  -0.838 -25.013  1.00  0.00           H  
ATOM    564  NE  ARG    37      -2.209  -2.283 -26.470  1.00  0.00           N  
ATOM    565  HE  ARG    37      -2.776  -3.044 -26.815  1.00  0.00           H  
ATOM    566  CZ  ARG    37      -0.891  -2.453 -26.404  1.00  0.00           C  
ATOM    567  NH1 ARG    37      -0.079  -1.497 -25.962  1.00  0.00           N  
ATOM    568 HH11 ARG    37      -0.462  -0.611 -25.665  1.00  0.00           H  
ATOM    569 HH12 ARG    37       0.917  -1.662 -25.925  1.00  0.00           H  
ATOM    570  NH2 ARG    37      -0.392  -3.621 -26.796  1.00  0.00           N  
ATOM    571 HH21 ARG    37      -1.011  -4.345 -27.131  1.00  0.00           H  
ATOM    572 HH22 ARG    37       0.605  -3.780 -26.757  1.00  0.00           H  
ATOM    573  C   ARG    37      -7.119  -1.108 -25.200  1.00  0.00           C  
ATOM    574  O   ARG    37      -7.721  -2.023 -25.757  1.00  0.00           O 

for PDBID: 1M8T,  the error message is:
 No template found for residue 5 (PHE).  The set of atoms matches PHE, but the bonds are different.
Residue 5 in the input pdb looks like:
ATOM     73  H   PHE     5       5.580   0.680  20.636  1.00  0.00           H  
ATOM     74  CA  PHE     5       4.807  -0.681  22.085  1.00  0.00           C  
ATOM     75  HA  PHE     5       5.305  -0.862  23.037  1.00  0.00           H  
ATOM     76  CB  PHE     5       3.689   0.347  22.304  1.00  0.00           C  
ATOM     77  HB2 PHE     5       4.109   1.293  22.645  1.00  0.00           H  
ATOM     78  HB3 PHE     5       3.140   0.507  21.376  1.00  0.00           H  
ATOM     79  CG  PHE     5       2.673  -0.074  23.340  1.00  0.00           C  
ATOM     80  CD1 PHE     5       1.358   0.391  23.280  1.00  0.00           C  
ATOM     81  HD1 PHE     5       1.066   1.069  22.478  1.00  0.00           H  
ATOM     82  CE1 PHE     5       0.423  -0.003  24.233  1.00  0.00           C  
ATOM     83  HE1 PHE     5      -0.603   0.361  24.179  1.00  0.00           H  
ATOM     84  CZ  PHE     5       0.803  -0.866  25.259  1.00  0.00           C  
ATOM     85  HZ  PHE     5       0.076  -1.175  26.010  1.00  0.00           H  
ATOM     86  CE2 PHE     5       2.110  -1.332  25.324  1.00  0.00           C  
ATOM     87  HE2 PHE     5       2.408  -2.010  26.124  1.00  0.00           H  
ATOM     88  CD2 PHE     5       3.030  -0.937  24.376  1.00  0.00           C  
ATOM     89  HD2 PHE     5       4.056  -1.300  24.428  1.00  0.00           H  
ATOM     90  C   PHE     5       4.218  -1.963  21.485  1.00  0.00           C  
ATOM     91  O   PHE     5       4.013  -2.953  22.177  1.00  0.00           O  

For the PDBID: 4M48, my error says:
"ValueError: No template found for residue 64 (GLY).  The set of atoms matches GLY, but the bonds are different."
but residue 64 in my pdb looks like
ATOM    989  N   GLY    64       5.701   2.846 -16.483  1.00  0.00           N  
ATOM    990  H   GLY    64       5.457   3.517 -15.768  1.00  0.00           H  
ATOM    991  CA  GLY    64       4.773   1.766 -16.758  1.00  0.00           C  
ATOM    992  HA2 GLY    64       5.317   0.822 -16.717  1.00  0.00           H  
ATOM    993  HA3 GLY    64       3.998   1.771 -15.992  1.00  0.00           H  
ATOM    994  C   GLY    64       4.123   1.901 -18.116  1.00  0.00           C  
ATOM    995  O   GLY    64       4.216   1.002 -18.952  1.00  0.00           O  

However, PDBID: 3NAL ([3nal_edited.txt](https://github.com/openmm/openmm/files/12373669/3nal_edited.txt)) is set up the same way and works without returning an error message

**Comment by peastman** [comment]
Your 4PHU file contains a single CONECT record:

```
CONECT  567 1166
```

Here is atom 567:

```
ATOM    567  NH1 ARG    37      -0.079  -1.497 -25.962  1.00  0.00           N  
```

And here is 1166:

```
ATOM   1166 HD12 LEU    78     -18.115   9.622   9.271  1.00  0.00           H  
```

You don't really intend those two atoms to be bonded, do you?
