### ISSUE TITLE
One loop hangs Amoeba on Windows HIP

### ISSUE THREAD

**Issue by bdenhollander** [openmm/openmm#4194]
After hundreds of display driver resets, I finally tracked down what hangs in `solveDIISMatrix` when `iteration > 0` on Windows HIP. 

https://github.com/openmm/openmm/blob/065e34ab56259d56dae81655f14fcfcbdb077788/plugins/amoeba/platforms/common/src/kernels/multipoleInducedField.cc#L765-L769

The issue is resolved by adding `#pragma unroll 1`. This hang only happens on Windows HIP. Ubuntu 20.04 compiles kernels using Clang 15.x and Windows HIP bundles Clang 17.0.0 and could affect how the kernel is optimized by `/O3`. Since this is OS dependent and the code is in common, I'm not sure what the best way to implement the fix would be.

RX 6600 on Windows HIP. The massive amoebagk improvement is inline with previously reported Linux HIP results.
| Benchmark         | OpenCL ns/day | HIP ns/day | Ratio |
|-------------------|---------------|------------|------------|
| amoebagk          | 1.38817       | 15.4375    | 1112.08%   |
| amoebapme         | 3.61985       | 6.11883    | 169.04%     |

**Comment by peastman** [comment]
That sounds like a compiler bug.  It's a really simple loop, and unrolling should never affect correctness.  We should probably notify AMD about it.

@ex-rzr do you have any insight about this?

**Comment by ex-rzr** [comment]
Deja vu. This swapping code reminds me one compiler bug. We had an issue with one test in rocPRIM:
https://github.com/ROCmSoftwarePlatform/rocPRIM/blob/develop/rocprim/include/rocprim/warp/detail/warp_sort_stable.hpp#L105

As you can see, the code is very similar. So I found the exact place in a compiled code where the compiler missed one instructions (or more precisely: incorrectly removed one instruction). Then AMD's compiler developer fixed this bug: https://reviews.llvm.org/rGdf1782c2a2af9938ba4c5bacfab20d1ddebc82dd

I wonder if this is indeed the same compiler bug and if the compiler from HIP SDK for Windows includes the fix.
@bdenhollander Could you check clang's version (with a commit hash) with hipconfig?

**Comment by bdenhollander** [comment]
I generated .s files with and without `#pragma unroll 1` on Windows. Diffing ignoring whitespace and numbers shows differences in lines 3561-4090.

[unroll-windows-hip-amdgcn-amd-amdhsa-gfx1032.s.txt](https://github.com/openmm/openmm/files/12383288/unroll-windows-hip-amdgcn-amd-amdhsa-gfx1032.s.txt)
[hang-windows-hip-amdgcn-amd-amdhsa-gfx1032.s.txt](https://github.com/openmm/openmm/files/12383289/hang-windows-hip-amdgcn-amd-amdhsa-gfx1032.s.txt)

hipcc.bin.exe prints `clang version 17.0.0 (git@github.amd.com:Compute-Mirrors/llvm-project e3201662d21c48894f2156d302276eb1cf47c7be)` when it launches.

**Comment by bdenhollander** [comment]
Retested this with Windows [HIP SDK 5.7.1](https://www.amd.com/en/developer/resources/rocm-hub/hip-sdk.html) and `#pragma unroll 1` is still needed. The clang hash reported by hipcc.bin.exe has changed since 5.5.1.

```
C:\AMD\ROCm\5.7\bin\hipcc.bin.exe --version
HIP version: 5.7.32000-193a0b56e
clang version 17.0.0 (git@github.amd.com:Compute-Mirrors/llvm-project 6e709f613348e5258188527d11ee8d78376f26b7)
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\AMD\ROCm\5.7\bin
```

**Comment by bdenhollander** [comment]
Retested with Windows [HIP SDK 6.1.2](https://www.amd.com/en/developer/resources/rocm-hub/hip-sdk.html) and the compiler issue is resolved. `#pragma unroll 1` is no longer required.

```
C:\AMD\ROCm\6.1\bin>hipcc.bin.exe --version
HIP version: 6.1.40252-53f3e11ac
clang version 19.0.0git (git@github.amd.com:Compute-Mirrors/llvm-project b3dbdf4f03718d63a3292f784216fddb3e73d521)
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\AMD\ROCm\6.1\bin
```
