### ISSUE TITLE
Problem in getting correct pair-correlation function

### ISSUE THREAD

**Issue by praban07** [openmm/openmm#4197]
I have tried my first 'serious' MD run with openMM. This is a peptide+water (+ions) system with AMBER ff14SB field with TIP3P water.
The minimization + MD ran fine. However, when I calculated the Oxygen-Oxygen pair-correlation function using CPPTRAJ, I see that there are non-zero values for very small distances between (even for 0.1 Angs ) Oxygens, which is of course not possible. As the simulations were stable, my guess is that this is due to some issue in writing the coordinates using DCDreporter (PBC related?). I have attached the input files for openMM and cpptraj (analysis)

(1) First I did minimization by keeping the ions restrained. Then minimization without any restraint.
(2) Then NVT simulation followed by NPT. 
[min_nores.docx](https://github.com/openmm/openmm/files/12398869/min_nores.docx)
[md_NVT.docx](https://github.com/openmm/openmm/files/12398875/md_NVT.docx)
[md_NPT_2nd.docx](https://github.com/openmm/openmm/files/12398879/md_NPT_2nd.docx)

The data is analyzed from the NPT simulation. Please note that I renamed the checkpoint files, so the write and read checkpoint files in the attached input files do not match but this is a continuous run.

Can someone please point out where I am going wrong?

[min_ion_restraint.docx](https://github.com/openmm/openmm/files/12398868/min_ion_restraint.docx)

[analysis.docx](https://github.com/openmm/openmm/files/12398881/analysis.docx)

**Comment by peastman** [comment]
Can you post them as txt files rather than Word files?

**Comment by praban07** [comment]
[min_ion_restraint.txt](https://github.com/openmm/openmm/files/12399411/min_ion_restraint.txt)
[min_nores.txt](https://github.com/openmm/openmm/files/12399421/min_nores.txt)
[md_NVT.txt](https://github.com/openmm/openmm/files/12399415/md_NVT.txt)
[md_NPT_2nd.txt](https://github.com/openmm/openmm/files/12399416/md_NPT_2nd.txt)
[analysis.txt](https://github.com/openmm/openmm/files/12399417/analysis.txt)

**Comment by peastman** [comment]
I don't see any obvious problems in your scripts.  There are two possibilities.

1. Your atoms really are coming very close together.  This shouldn't happen if they repel each other as expected, so it would suggest a problem in how you've modeled and parametrized the system.  I can't tell what parameters you use.  They come from the prmtop file, which you didn't attach.

2. The simulation is fine, but the analysis is wrong.  Without access to your trajectory, I can't judge that either.  Make sure CPPTRAJ is using the box vectors from the DCD trajectory, not from the prmtop file.

**Comment by praban07** [comment]
The main problem was in the analysis. Somehow RMSD command before the 'rdf' command in CPPTRAJ is giving incorrect results. Now my openMM g(r) for several pairs match with published results.

There was a bug in the script I sent.  By mistake, the box information was read from the original AMBER coordinate file (inpcrd) during the restart from the checkpoint file due to the following two lines (now commented).

`````````````````````````````````````````````````````````````````````
#if inpcrd.boxVectors is not None:
#    simulation.context.setPeriodicBoxVectors(*inpcrd.boxVectors)
````````````````````````````````````````````````````````````````````

**Comment by peastman** [comment]
Glad you figured it out!
