### ISSUE TITLE
Getting step readout from simulation.minimizeEnergy()

### ISSUE THREAD

**Issue by scal444** [openmm/openmm#4198]
Is there a way to get a reporter to attach to minimizeEnergy? I'm trying to figure out how many steps are actually ran, compared to the maximum number of iterations you can specify in the method signature.

If not, I can switch to using [GradientDescentMinimizationIntegrator](https://openmmtools.readthedocs.io/en/stable/api/generated/openmmtools.integrators.GradientDescentMinimizationIntegrator.html#openmmtools.integrators.GradientDescentMinimizationIntegrator) in OpenMMTools, which isn't the end of the world, but is a bit annoying, and uses a different minimization algorithm.

**Comment by peastman** [comment]
No, there's no way to do that.  See #1155.

**Comment by peastman** [comment]
I'm closing this as a duplicate.
