### ISSUE TITLE
Make HIP a standard platform

### ISSUE THREAD

**Issue by peastman** [openmm/openmm#4199]
AMD GPUs seem to be getting more attention these days, and the HIP platform has much better performance than OpenCL.  We should consider whether at some point we want to make it into a standard platform and bundle it with OpenMM.

In technical terms, the biggest obstacle is that conda-forge doesn't support building or distributing packages that use HIP.  Several months ago I asked about adding support (https://github.com/conda-forge/conda-forge.github.io/issues/1923).  The answer was that they have no plans, but would be open to it if someone else does the work.  AMD would of course be the obvious party to take on implementing and supporting HIP on conda-forge.  No idea if that's something they're interested in.

cc @ex-rzr @jdmaia

**Comment by jdmaia** [comment]
Hey Peter, 
I'm touching base with our system software team again to see where we stand on adding ROCm on conda-forge, and will send an update once I get a definitive answer.

**Comment by peastman** [comment]
It looks like there's finally some motion toward getting it supported on conda-forge.  The feedstock at https://github.com/conda-forge/hip-feedstock has been updated to version 6.0.2 (not quite the latest release, but they're working on that).  That means we can start thinking about moving forward with this.

**Comment by peastman** [comment]
I'm trying to get it working using the conda-forge HIP packages.  Here are the code changes I've made so far.

- I had to bring it up to date with the latest changes in OpenMM, particularly #4346 and #4435.
- There isn't currently a package for hipFFT, so I removed all code related to it.  I think it would be fine to always use vkFFT and remove the support for alternate FFTs.  It's the default anyway.
- It wasn't finding any of the HIP header files.  The fix was just to add this line to CMakeLists.txt:

```
INCLUDE_DIRECTORIES("${HIP_INCLUDE_DIR}")
```

- The following line in HipContext.cpp failed to compile, so I removed it.  `gcnArch` seems to no longer exist in the latest version of HIP.

```c++
int major = thisDevice.gcnArch;
```

Once I made those changes it was able to compile, but running a test case failed with this error:

```
exception: Error launching HIP compiler: 256
clang: error: cannot find ROCm device library; provide its path via '--rocm-path' or '--rocm-device-lib-path', or pass '-nogpulib' to build without ROCm device library
```

I'm not sure whether this means I'm missing a library or something has to be done to let it find the libraries.  Here are the relevant conda packages installed in my environment.

```
hip-devel                 6.0.2                ha770c72_2    conda-forge
hip-runtime-amd           6.0.2                he02047a_2    conda-forge
hipcc                     6.0.2                he02047a_2    conda-forge
rocm-cmake                6.1.0                h59595ed_0    conda-forge
rocm-comgr                6.0.2                h1566cd9_0    conda-forge
rocm-device-libs          6.1.0                ha6fb4c9_0    conda-forge
rocminfo                  6.0.2                hd3aeb46_1    conda-forge
rocr-runtime              6.0.2                h84ce1b7_1    conda-forge
roct-thunk-interface      6.0.2                hd3aeb46_1    conda-forge
```

**Comment by ex-rzr** [comment]
`gcnArch` is fixed here: https://github.com/amd/openmm-hip/pull/14

I'll try to find time today or tomorrow and make hipFFT optional, then investigate what what is happening with the missing device lib during kernel compilation.

**Comment by ex-rzr** [comment]
I have pushed a commit with optional hipFFT to this PR: https://github.com/amd/openmm-hip/pull/14

**Comment by ex-rzr** [comment]
I'm trying to build my recipe that I use for https://anaconda.org/streamhpc/openmm-hip with changes for using hip/rocm conda packages instead of installing them from repo.radeon.com
I'm getting this error when I run `python3 build-locally.py`:
```
CMake Error in platforms/hip/CMakeLists.txt:
  Imported target "hip::host" includes non-existent path

    "/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
```

I don't know what exactly happens, it looks like hip-config.cmake or hip-config-amd.cmake is incorrect.

@peastman How did you manage to build OpenMM-HIP with the new hip/rocm conda packages?

At this moment I can't help with the problem with building kernels in runtime. Probably the best solution would be to use hipRTC and remove the "explicit" compilation with the compiler (like you did with the CUDA backend).
Though, there are still some issues with ambiguous vector operators even on ROCm 6.1: operators from `// Multiply two vectors.` and `// Divide two vectors.` of `vectorOps.hip` must be removed for hipRTC. My quick and dirty change shows that this allows all tests to run. So I guess this is the direction we should take.

**Comment by peastman** [comment]
I'm not sure what's causing that.  I found [this PR](https://github.com/CHIP-SPV/chipStar/pull/192) which fixed a very similar error in another project, although it isn't obvious to me if the cause is the same.

**Comment by peastman** [comment]
I think I tracked down the problem, and I'm pretty sure it's a bug in the CMake files installed by HIP.  The immediate cause is in hip-config-amd.cmake:

```cmake
set_target_properties(hip::amdhip64 PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)
```

`_IMPORT_PREFIX` is set in the same file by

```cmake
set(_IMPORT_PREFIX ${HIP_PACKAGE_PREFIX_DIR})
```

and `HIP_PACKAGE_PREFIX_DIR` is set in hip-config.cmake:

```cmake
# TODO:once file reorg backward compatibility is turned off this can be removed.
if(IS_SYMLINK ${CMAKE_CURRENT_LIST_FILE})
  get_filename_component(CONFIG_FILE_PATH "${CMAKE_CURRENT_LIST_FILE}" REALPATH)
  get_filename_component(PACKAGE_PREFIX_DIR "${CONFIG_FILE_PATH}/../../../../" ABSOLUTE)
endif()
# end of TODO
set(HIP_PACKAGE_PREFIX_DIR  ${PACKAGE_PREFIX_DIR})
```

This only works if the path to hip-config.cmake is a symlink.  If it isn't, `PACKAGE_PREFIX_DIR` never gets set, which means `HIP_PACKAGE_PREFIX_DIR` and `_IMPORT_PREFIX` are both empty.

**Comment by ex-rzr** [comment]
Thanks!

Indeed, it's a bug because `PACKAGE_PREFIX_DIR` is set only when hip-config.cmake is a symlink.

This workaround allow me to build conda package using my recipe and `python3 build-locally.py`:
```
# Workaround for an error in hip-config.cmake:
# the path CMAKE_CURRENT_LIST_FILE is not a symlink => PACKAGE_PREFIX_DIR is not set
CMAKE_FLAGS+=" -DPACKAGE_PREFIX_DIR=${PREFIX}"
```
For a local build in anaconda environment `PACKAGE_PREFIX_DIR` must be something like `~/anaconda3/`

**Comment by peastman** [comment]
That works!  With that change, I'm back to the error about `cannot find ROCm device library`.  I don't know why I didn't get it at first?

I tried to fix this error by modifying this line in `HipContext::createModule()`:

```c++
string options = "-ffast-math -munsafe-fp-atomics -Wall";
```

I added the option `--rocm-path=/home/peastman/miniconda3/envs/openmm/lib` to it.  With that change it instead failed with a different message:

```
clang: error: unable to execute command: Executable "lld" doesn't exist!
clang: error: amdgcn-link command failed with exit code 1 (use -v to see invocation)
```

So I installed the `lld` conda package, and the error changed to

```
clang: error: unable to execute command: Executable "clang-offload-bundler" doesn't exist!
clang: error: amdgcn-link command failed with exit code 1 (use -v to see invocation)
```

I can't tell what package, if any, would provide that.  I already have the `clang` package installed, but apparently it doesn't have that particular tool.

**Comment by peastman** [comment]
Found it: it's in the `clangdev` package.  After installing it, here's the new error:

```
exception: Error creating kernel applySettleToPositions: hipErrorNotFound (500)
```

**Comment by ex-rzr** [comment]
I have some progress.

It looks like hip/rocm conda packages don't include the "official" clang from ROCm. It should be possible to use upstream versions of clang to compile kernels (because most of the changes go from https://github.com/ROCm/llvm-project to https://github.com/llvm/llvm-project eventually, I think some linux distributions use the upstream clang).
But after installing hip/rocm conda packages my env has clang 14 which is quite old considering that the recent ROCm versions use clang 17.

I decided not to spend more time on this problem and focus on hipRTC. I think that at this moment there are no benefits in compiling kernels with the external compiler, previously kernels compiled with hipRTC were a bit slower because hipRTC used different compilation/optimization flags. I think it's not an issue anymore though I need to check performance just to be sure.

Here is my WIP code: https://github.com/StreamHPC/openmm-hip/commits/make-hip-standard-platform/
I use hipRTC, also there are 2 changes:
1. the "embedded" headers used by hipRTC (unlike the regular headers used by clang) include arithmetic operations for vector types that redefined in `platforms/hip/src/kernels/vectorOps.hip`
2. hipRTC from ROCm 6.0 defines some operators for complex types but since complex types are typedefs for float2 and double2, there are conflicts. This issue is fixed in ROCm 6.1 (https://github.com/ROCm/clr/commits/rocm-6.1.x/hipamd/include/hip/amd_detail/amd_hip_complex.h), I added a workaround.

I will clean these changes and remove other traces of the compiler properly similarly to your changes for CUDA.

Here is a conda package: https://anaconda.org/StreamHPC/openmm-hip/files (8.1.1dev)
It should work even on a system without `/opt/rocm`, i.e. it requires uses 

It can be installed with
```
conda create -n openmm-env -c jaimergp/label/unsupported-cudatoolkit-shim -c conda-forge -c streamhpc --strict-channel-priority openmm-hip==8.1.1dev
```
and tested with these commands https://github.com/StreamHPC/openmm-hip?tab=readme-ov-file#installing-with-conda

**Comment by peastman** [comment]
> I decided not to spend more time on this problem and focus on hipRTC.

Sounds good to me.

**Comment by ex-rzr** [comment]
I have updated the branch: https://github.com/StreamHPC/openmm-hip/commits/make-hip-standard-platform/
* a proper commit with hipRTC-only compilation;
* recent changes in the CUDA platform ported to HIP (so OpenMM-HIP can be build with the current OpenMM master).

**Comment by hmacdope** [comment]
We have been working parallel with Quansight (@isuruf, @zklaus and others) to allow a build of OpenMM-HIP on conda-forge. I believe we have the deps in place, including packing or changes to: 

* HIPFFT
* RocFFT
* HIP hostside libraries
* changes to LLVM infra (hipcc, rocm-device-libs, rocm-comgr)

This should make getting a working 8.1.1 OpenMM-HIP on conda-forge a lot easier. Indeed we may be able to get this done in its entirety. In turn this would allow easier integration of HIP platform into Openmm main repo. 

The main question is how to best coordinate this? What do people think the best way forward is (@ex-rzr  @jdmaia @peastman)?

Should we proceed to try and package OpenMM-HIP 8.1.1 for conda-forge as a proof that it works and then go from there? For the streamHPC folks should  we be using a different commit? I.e is there anything important between a bleeding edge build and 8.1.1? 

Then we can address merging of the two libraries at a possible later date if desired? 

Let me know what you think. CC @mikemhenry

**Comment by ex-rzr** [comment]
I have `openmm-hip-feedstock`  which is basically a usual conda-forge recipe but I build it locally. Currently it's a bit messy, but it allows to build openmm-hip using these conda packages:
    - openmm ==8.1.1
    - hipcc
    - hip-devel
    - hip-runtime-amd
    - rocm-device-libs
    
rocFFT/hipFFT are not longer a mandatory dependency.

For example, `8.1.1dev` (https://anaconda.org/StreamHPC/openmm-hip/files) is built this way, iirc it uses https://github.com/StreamHPC/openmm-hip/commit/5d1a3478cef98523df406b43a1a4e779b00d3384 (actually, its older WIP version) from https://github.com/StreamHPC/openmm-hip/commits/make-hip-standard-platform/, more recent commits are for supporting the current OpenMM master branch (for compatibility with commits after 8.1.1, so they should not be used for packaging).

**Comment by hmacdope** [comment]
@ex-rzr  would you be open to us working together (likely with quansight also) to clean it up and convert it to a proper conda-forge feedstock?

If so, we can either work on that repo or start afresh in a new `openmm-hip-feedstock` repo using what you already have?  Which would you prefer? I don't want to disrupt a working build system that you use for StreamHPC purposes of course.

**Comment by ex-rzr** [comment]
> would you be open to us working together (likely with quansight also) to clean it up and convert it to a proper conda-forge feedstock?

Sure! I just want let you know that I'm working on OpenMM-HIP in my spare time (our, StreamHPC's, "official" work work has long been completed), so it may take time. But I'll clean it up asap.

I suppose we should create a new conda-forge repo based on my recipe, I'll try to do it and ask your assistance if needed.

> I don't want to disrupt a working build system

My "build system" for conda is manual `conda smithy rerender --feedstock_directory . && python3 build-locally.py`, and then `anaconda upload ...`, so you are not disturbing anything :)

**Comment by hmacdope** [comment]
> Sure! I just want let you know that I'm working on OpenMM-HIP in my spare time (our, StreamHPC's, "official" work work has long been completed), so it may take time. But I'll clean it up asap.

We have some money to do this at the moment, so happy to shoulder the majority of the burden.  If you post a link to the feedstock, or even just the key files (meta.yaml, build.sh, build.bat) etc. We can get the quansight people to knock  a new feedstock together. 

Sound like a plan?

**Comment by zklaus** [comment]
I did not realize you were working on this that actively, that's great! Thanks, @hmacdope, for pointing me to this discussion. I have a PR in staged-recipes for adding openmm-hip at conda-forge/staged-recipes#26772, so absolutely let's join forces.

I'll also say that we built the rocm packages in conda-forge more or less specifically to enable openmm-hip, so they are quite new and have not seen much application testing. For example, the `cannot find ROCm device library` error mentioned above can probably be fixed more generically in the rocm-device-libs-feedstock.

Let's see if we can get this up and running quickly and then possibly sand some of the rough edges?

**Comment by hmacdope** [comment]
Aha, well it looks like that proposed conda forge feedstock already exists!

**Comment by zklaus** [comment]
Well, for now it's a PR in staged-recipes only, but as soon as everything's working, it will become a feedstock.

I did sneak some hints for the recipe directly from the recipe embedded in the StreamHPC package, but having the sources linked might still be useful. Also, perhaps some or all of you would like to be maintainers on the feedstock?

**Comment by hmacdope** [comment]
I would love to be, @peastman @ex-rzr I would say you are both great candidates also.

**Comment by ex-rzr** [comment]
Ok, here is my feedstock, feel free to use anything you need from it: [openmm-hip-feedstock.zip](https://github.com/user-attachments/files/16008573/openmm-hip-feedstock.zip)

It uses the commit I mentioned: https://github.com/StreamHPC/openmm-hip/commit/5d1a3478cef98523df406b43a1a4e779b00d3384
If you need I can create a tag/release for it.

So the error `cannot find ROCm device library` should not be a problem, this version does not use a command line compiler to build kernels, only hipRTC.
This is also mean that packages like clangdev and lld are not required.

hipfft and rocfft are also not required (the cmake script detects if they are present and build with hipfft support in this case).

Also `recipe/build.sh` contains a workaround:
```
# Workaround for an error in hip-config.cmake:
# the path CMAKE_CURRENT_LIST_FILE is not a symlink => PACKAGE_PREFIX_DIR is not set
CMAKE_FLAGS+=" -DPACKAGE_PREFIX_DIR=${PREFIX}"
```
I guess it can be **removed** since there is a fix for this issue in hip-feedstock: https://github.com/conda-forge/hip-feedstock/commit/4b5f80afe2b7c32065694868a37e3ba2a799742d

> Also, perhaps some or all of you would like to be maintainers on the feedstock?

Sure, I'd like to.

**Comment by zklaus** [comment]
Great, I have added y'all as maintainers, so please leave a comment on the PR affirming that you are indeed willing to do that. I have also included you, @peastman, but let me know if you prefer not to.

It seems everything is building fine right now, but it is based on the slightly older tag 8.1.1beta. It would be good to have a real 8.1.1 release (pre-releases are generally a bit frowned-upon in conda-forge's main channel), but if you prefer the commit you mentioned, we can base things of that and shape everything up before doing the tag.

Do you still consider amd/openmm-hip upstream, or is it now StreamHPC/openmm-hip?

**Comment by zklaus** [comment]
Two more questions:
- Did I understand correctly that the plugin openmm-hip itself is released under the MIT license?
- The commit message for the commit you linked above mentions that ROCm 6.0 has some problem with `operator*`. Does that mean that ROCm 6.0.2 is not enough to completely switch to hiprtc? If that is the case, we may need to keep things with clang for now or finish the update of ROCm (for the current status, see https://github.com/conda-forge/conda-forge.github.io/issues/1923#issuecomment-2065144973).

**Comment by hmacdope** [comment]
@zklaus I think we can consider StreamHPC/openmm-hip upstream.

**Comment by ex-rzr** [comment]
> Do you still consider amd/openmm-hip upstream, or is it now StreamHPC/openmm-hip?

I'm still waiting for 8.1.1 to be merged to amd/openmm-hip :/ So technically it's upstream, but very outdated.

> Did I understand correctly that the plugin openmm-hip itself is released under the MIT license?

I mentioned used licenses here: https://github.com/StreamHPC/openmm-hip?tab=readme-ov-file#license
As far as I know, AMD is ok with this list. I suppose all of them should be listed in the recipe?

> The commit message for the commit you linked above mentions that ROCm 6.0 has some problem with operator*. Does that mean that ROCm 6.0.2 is not enough to completely switch to hiprtc? If that is the case, we may need to keep things with clang for now or finish the update of ROCm (for the current status, see https://github.com/conda-forge/conda-forge.github.io/issues/1923#issuecomment-2065144973).

https://github.com/StreamHPC/openmm-hip/commit/5d1a3478cef98523df406b43a1a4e779b00d3384 works with your ROCm 6.0.* packages (at least it worked a few weeks ago when I tried it), it has a workaround for ROCm 6.0. But afaik hipRTC is not working with ROCm 6.0 for the tag you're currently using in the recipe (8.1.1beta).

In my opinion, switching completely to hipRTC is a reasonable thing to do considering that it is simpler and requires less dependencies to build and run.

**Comment by ex-rzr** [comment]
The tag 8.1.1 points to https://github.com/StreamHPC/openmm-hip/commit/5d1a3478cef98523df406b43a1a4e779b00d3384:  https://github.com/StreamHPC/openmm-hip/tags

**Comment by peastman** [comment]
That's great!  Yes, I'd be glad to be a maintainer.

Back to the actual topic of this issue (making it a standard platform), trying out Anton's latest code is on my list.  I've just been bogged down with other things lately.  I'll try to do it very soon.

**Comment by peastman** [comment]
I successfully compiled the latest version of the code, and all tests pass.

Is there a list of what GPUs it works on?  I found the [list of supported GPUs](https://rocblas.readthedocs.io/en/rocm-6.0.0/about/compatibility/linux-support.html) for ROCm, which only includes very recent ones.  But it seems to work fine on my Radeon 5700 XT, which is two generations older than anything on the list.

Assuming it really does have stricter hardware requirements than OpenCL, we should make `registerPlatforms()` check whether you have a compatible GPU and not register the HIP platform if you don't.  That way, users with older GPUs will get OpenCL by default instead of having it default to a platform that doesn't work on their computer.

**Comment by ex-rzr** [comment]
It seems that the list of officially supported GPUs is much shorter than the list of supported architectures by the ROCm runtime and the compiler. For example, there is gfx1010 (your GPU) in llvm, hiprtc and clr (the runtime). And OpenMM-HIP does not depend on the compiled binaries for all architectures but compiles everything in runtime,

I think checking if `hipGetDeviceCount` returns `hipErrorNoDevice` in `registerPlatforms()` should be enough for filtering out older/incompatible GPUs.

**Comment by peastman** [comment]
That sounds perfect, thanks.

Are there any other changes that still need to be made?  Or are we ready to start merging it into this repo?  I can get started on that quite soon, if you think everything is ready.

**Comment by ex-rzr** [comment]
I'll create a commit with this small change (after testing).

And I'll check my notes if there is anything I wanted to do before merging. There was one small optimization for bonded forces, I'd like to check if it is still worth to use with AMD and if Nvidia GPUs can also benefit from it (but this investigation can be done later).

Regarding the merging process: considering that I intentionally made the current OpenMM-HIP based on the OpenMM source tree and history, it seems that only conflicts of the direct merge are the main CMakeLists.txt and README.md, there are 175 commits. Of course, some tinkering is also required like (re)moving licenses/ as a duplicate of  docs-source/licenses/, extending docs etc.

Another approach is to make one huge commit and lose all the history of OpenMM-HIP changes. I don't know what you prefer (I prefer the "real" merging).

**Comment by peastman** [comment]
I'll trust your judgement on the best way to do it.  Some parts will clearly require a manual merge, particularly the CMake files.

**Comment by peastman** [comment]
I've been thinking about this more, trying to figure out what it would mean to keep the history.  I assume you don't mean merging the histories of the two repositories?  That would create a history that doesn't reflect the actual history of this repository, which seems like a bad idea.  So I assume you mean replaying the commits, creating a huge block of 175 sequential commits all with the same timestamp?  That seems like it would be more confusing than useful.

So I suggest merging it as a single commit.  The history will still be available in the other repo if we want it.

**Comment by ex-rzr** [comment]
I've pushed the check of compatible devices: https://github.com/amd/openmm-hip/commit/6b08e19df77f32eec3916117e437594755378e90
Though I've been thinking about changing `HipPlatform::getSpeed()` to make it return a small value if there are no devices, so the HIP platform will have a low priority. I'm not sure if this is a good idea.

> That would create a history that doesn't reflect the actual history of this repository, which seems like a bad idea.

As far as I understand this creates hisrory like an ordinary merge commit.

I'll start working on a single-commit solution soon.

**Comment by peastman** [comment]
HIP can also run on Nvidia GPUs, right?  Let's make `getSpeed()` return 75.  That way, AMD GPUs will prefer it over OpenCL, and Nvidia GPUs will prefer CUDA over HIP.

Do we really need to support the different FFT libraries?  If we support them, we need to test them.  If there's no good reason to prefer the others over VkFFT, let's simplify the test matrix by removing the support for them.

Speaking of testing, we need to figure out how to do it.  Github doesn't provide GPUs.  We can still test that HIP compiles, but we can't run any of the tests.  For Nvidia we use Jenkins to run CI on an actual GPU.  Do you know if AMD or StreamHPC would provide access to a runner for doing CI on an AMD GPU?  Otherwise we need to get a box for it and figure out where to put it and how to administer it.

**Comment by hmacdope** [comment]
If AMD can provide infra that would be amazing, however wanted to make you aware of a possible option from within OMSF ecosystem. 

We may be to use an AWS self hosted runner on a G4ad (low end AMD GPU EC2 instance) or similar. Some OMSF folks have been working on a [project](https://github.com/omsf-eco-infra/gha-runner) on self hosted GPU runners. Tagging them here @dwhswenson @ethanholz.

**Comment by peastman** [comment]
That would be fantastic.

**Comment by zklaus** [comment]
Conda-forge is using https://cirun.io/ to use sponsored runners for some special builds, e.g. Pytorch or Tensorflow, iirc.

**Comment by dwhswenson** [comment]
Regarding the tool that @ethanholz and I have been working on: It is very early alpha. If you're willing to play with it in its current state, we'd welcome feedback, but also completely understand that you might not want it until it is a bit more polished. You can find the action on GitHub Marketplace: https://github.com/marketplace/actions/gha-runner.

Our solution is largely inspired by an existing action that was specifically tied to AWS (the difference in ours is that we're planning to allow other cloud platforms). That tool is a bit more battle-tested, and can be found here: https://github.com/marketplace/actions/on-demand-self-hosted-aws-ec2-runner-for-github-actions.

We haven't tried either of these with AMD GPU instances, so I'm not sure what other hiccups might show up in that use case.

**Comment by swails** [comment]
It looks like maybe GPU runners on GitHub are generally available? https://github.blog/changelog/2024-07-08-github-actions-gpu-hosted-runners-are-now-generally-available/

I don't think this hits AMD cards, though.

**Comment by peastman** [comment]
That's good to know!  It looks like you need to pay for them, but it could still be useful.  NVIDIA only at the moment, and a really old model at that (T4, released in 2018).  I wonder if these are GPUs they'd been using for something else, retired them as obsolete, and then decided they could repurpose them for CI?

**Comment by ex-rzr** [comment]
I've added Windows support: https://github.com/StreamHPC/openmm-hip/commits/make-hip-standard-platform/
It seems to work well on RX 6900 XT on ROCm 6.1.
However, I need explicitly set `PATH` to point to HIP and OpenMM dlls to run tests and benchmarks:
```
set PATH=C:\Users\anton\openmm\install\lib;C:\Users\anton\openmm\install\lib\plugins;C:\Program Files\AMD\ROCm\6.1\bin;%PATH%
```

@peastman 

> HIP can also run on Nvidia GPUs, right? Let's make getSpeed() return 75. That way, AMD GPUs will prefer it over OpenCL, and Nvidia GPUs will prefer CUDA over HIP.

HIP can run on Nvidia (by calling CUDA equivalent functions), but unfortunately OpenMM-HIP does not support it, and I'm not sure if it's worth supporting.

I added this solution: https://github.com/StreamHPC/openmm-hip/commit/4c17b2b59d282552852c81fcf00dcf51d1182923
However, I don't know if it's possible that with the same driver some device can be supported by OpenCL but not by HIP. On linux the runtimes are like siblings (https://github.com/ROCm/clr/).

@bdenhollander

You have Windows+HIP SDK on your machine, right? If it's not difficult for you, could you check if this branch works? Thanks!
Here are commands I use:
```
cd build-hip
cmake ..\openmm-hip -D OPENMM_DIR=..\install -D OPENMM_SOURCE_DIR=..\openmm -D CMAKE_INSTALL_PREFIX=..\install -D CMAKE_PREFIX_PATH="C:\Program Files\AMD\ROCm\6.1"

Open build-hip/OpenMMHIPPlugin.sln in VS 2022
Select Release
ALL_BUILD project > Build
INSTALL project > Build

add to RUN_TESTS Build Events > Post-Build Event > Command Line
set PATH=C:\Users\anton\openmm\install\lib;C:\Users\anton\openmm\install\lib\plugins;C:\Program Files\AMD\ROCm\6.1\bin;%PATH%
RUN_TESTS project > Build

set PATH=C:\Users\anton\openmm\install\lib;C:\Users\anton\openmm\install\lib\plugins;C:\Program Files\AMD\ROCm\6.1\bin;%PATH%
cd C:\Users\anton\openmm\install\examples
python benchmark.py --verbose --style=table --platform=HIP --precision=single
```

----

Meanwhile I'm (slowly) starting to prepare a merge request (one huge commit as discussed)...

**Comment by peastman** [comment]
> HIP can run on Nvidia (by calling CUDA equivalent functions), but unfortunately OpenMM-HIP does not support it, and I'm not sure if it's worth supporting.

That's fine.  If they have an Nvidia GPU, they'll use CUDA.

> Meanwhile I'm (slowly) starting to prepare a merge request (one huge commit as discussed)...

Looking forward to it!  (Well, not to the very large amount of time it will undoubtedly take to review all that code, but still a good thing.)

**Comment by bdenhollander** [comment]
> You have Windows+HIP SDK on your machine, right? If it's not difficult for you, could you check if this branch works? Thanks!

The branch works and the benchmarks run successfully. One additional tweak you can check on your GPU is defaulting `DisablePmeStream` to `true` on Windows. You can see older water box tests here: https://github.com/openmm/openmm/issues/4220.

Here are the standard benchmarks with separate PME stream enabled (default) and disabled on my RX 6600 on Windows 10 on your branch. Not all tests use PME so they're not all affected and systems with fewer atoms gain more. I had picked 40000 atoms on my Windows branch but GPU TFLOPS may influence when the performance difference between the settings becomes negligible.

| PME Stream   | Enabled | Disabled | Ratio |
|--------------|---------|----------|-------|
| gbsa         | 971.359 | 970.443  | 1.00  |
| rf           | 748.788 | 750.112  | 1.00  |
| pme          | 492.039 | 624.091  | 1.27  |
| apoa1rf      | 225.285 | 225.39   | 1.00  |
| apoa1pme     | 166.881 | 168.84   | 1.01  |
| apoa1ljpme   | 141.325 | 144.617  | 1.02  |
| amoebagk     | 14.7215 | 14.755   | 1.00  |
| amoebapme    | 6.68829 | 6.71745  | 1.00  |
| amber20-dhfr | 502.208 | 638.765  | 1.27  |

**Comment by zklaus** [comment]
> I've been thinking about this more, trying to figure out what it would mean to keep the history. I assume you don't mean merging the histories of the two repositories? That would create a history that doesn't reflect the actual history of this repository, which seems like a bad idea. So I assume you mean replaying the commits, creating a huge block of 175 sequential commits all with the same timestamp? That seems like it would be more confusing than useful.
> 
> So I suggest merging it as a single commit. The history will still be available in the other repo if we want it.

A bit of unsolicited git advice, obviously feel free to ignore: Replaying all commits can create a long and convoluted, i.e. unhelpful history. Bunching everything in a single commit can make it hard to review the PR because the commits don't tell a story and it's difficult to see the various stages of the work as they build on each other.
In these cases I often prefer the third alternative: rewriting the history to create a small number of meaningful commits. The two principal ways to do that are with an interactive rebase on the source repo, which allows one to remove obsolete commits, combine or reorder commits to show which parts belong together; or to do a `git reset --soft main` leaving the working tree at the state of the feature branch but resetting the branch head itself to `main` and then committing the changes that make up the feature in a small number of commits that tell a story.

**Comment by ex-rzr** [comment]
I just want to let everyone know that I haven't abandoned this issue.

@zklaus 

> In these cases I often prefer the third alternative: rewriting the history to create a small number of meaningful commits. The two principal ways to do that are with an interactive rebase on the source repo, which allows one to remove obsolete commits, combine or reorder commits to show which parts belong together;

This is exactly what I'm doing: I'm reordering and combining commits: there will be a huge commit with an initial "hipification" and a bunch of smaller commits: optimizations of related parts, ports of the changes of the CUDA/common platforms from the main repo etc. 175 commits have already became <70, my goal is to combine them to 20-30.

@bdenhollander

Sorry, I forgot to report my results with disabling PME stream on Windows: on V620 there were improvements in small water box simulations, but iirc no improvements in the main benchmarks. I guess the threshold should be tuned depending on the GPU. I'll get back to it later.

**Comment by mikemhenry** [comment]
We did get the openmm-hip package onto conda-forge https://anaconda.org/conda-forge/openmm-hip

**Comment by peastman** [comment]
@ex-rzr do you have an ETA for this?  I'd love to get it into 8.2, but I don't know whether I should wait for it.  Alternatively if you don't have the time, I could merge it myself.

**Comment by ex-rzr** [comment]
@peastman Then I'll try to finalize it this weekend. And when do you plan to create the 8.2 release?

**Comment by peastman** [comment]
That will be perfect, thanks!  There's no fixed timeline.  Once HIP is in, I'm hoping to create the beta quite soon.

**Comment by ex-rzr** [comment]
Update: almost done, I need to rerun benchmarks and tests to ensure that there are no regressions (currently the GPUs are a bit busy). Also I've encountered sporadic failures in some Amoeba tests, I'd like to debug it first (at least to understand where the issue is: the HIP platform, the HIP compiler or Amoeba kernels). After that I'll open a pull request (hopefully tomorrow).

**Comment by ex-rzr** [comment]
The pull request: #4632

**Comment by bdenhollander** [comment]
Now that HIP is merged and HIP for Linux is part of CI, what will it take get Windows HIP builds on conda forge? I'm guessing there are a number of [HIP packages](https://github.com/conda-forge/conda-forge.github.io/issues/1923#issuecomment-2065144973) that will need to be enabled on Windows. Since conda forge appears to using HIP 6.0.2, it would be good to target HIP 6.1.2 since it's available for [Windows](https://www.amd.com/en/developer/resources/rocm-hub/hip-sdk.html) and Linux. @zklaus Is this something that would be in your wheelhouse?

**Comment by zklaus** [comment]
@bdenhollander, yes, that is something I'd be keen to work on. Together with general updates of the hip stack and hopefully eventually rocm builds of pytorch, tensorflow, and friends. However, this was part of my day job and the associated contract has concluded. If we find further funding, I'd be more than happy to work on this.

**Comment by peastman** [comment]
Now that HIP is merged, we need to figure out packaging and testing.

How can we build conda packages for it?  With CUDA, we have packages built against different toolkit versions, and conda automatically installs the appropriate version based on your installed driver, including all necessary CUDA libraries.

- Is it possible to do the same thing for HIP?  Is conda able to distinguish whether you have a compatible driver installed?
- If it's not possible, should we require the user to specify that they want a HIP build?  Or just include it in every package?  The OpenMM libraries for HIP support are probably small enough that it's not a big deal to always include them, but it also means making the HIP packages dependencies so they would always get installed, even though most users don't need them.
- Long term will we need multiple builds for different HIP versions like with CUDA?  How does it handle binary compatibility across versions?

Another question we need to figure out is testing.  I added a CI build, but it only checks that it compiles.  To run the tests, we need to get a machine with an AMD GPU.  I read through the Github documentation on self-hosted runners, but they warn they should ["almost never"](https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#hardening-for-self-hosted-runners) be used for public repositories.  The runner is inherently insecure, and an attacker can use it to compromise both the machine it's running on and the repository it's being used for.  Is there some way we can test it safely?

**Comment by hmacdope** [comment]
> * If it's not possible, should we require the user to specify that they want a HIP build?  Or just include it in every package?  The OpenMM libraries for HIP support are probably small enough that it's not a big deal to always include them, but it also means making the HIP packages dependencies so they would always get installed, even though most users don't need them.


@peastman Just for completeness we also have the `openmm-hip` conda-forge build that I was building the OpenMM-core HIP prototype from https://github.com/conda-forge/openmm-hip-feedstock. Having users install that could be another option.

**Comment by peastman** [comment]
Good point.  Yes, that's another option.  We could keep it as a separate conda package, just revising the feedstock to make it build from this repo.

**Comment by hmacdope** [comment]
@peastman I have added you as an admin to the feedstock in case you want to experiment with some changes there :)

**Comment by peastman** [comment]
Can you take a look at my draft PR at https://github.com/conda-forge/openmm-hip-feedstock/pull/5?  Some of the details will need to be cleaned up once there's an OpenMM package for the same version, but see if the overall approach looks ok.

**Comment by hmacdope** [comment]
All looked good to me. Do you want me to merge or shall we leave in place for now?

**Comment by peastman** [comment]
It's still a draft.  We can't build the real thing until after we have a corresponding OpenMM build.  The plan is to create the 8.2 beta next week.

**Comment by peastman** [comment]
Closing this now that 8.2 is released.
