### ISSUE TITLE
Add CMake variables to require OpenCL or CUDA. 

### ISSUE THREAD

**Issue by hmacdope** [openmm/openmm#4201]
The pattern used to set up the CUDA and OpenCL platforms:

```CMake
FIND_PACKAGE(CUDAToolkit QUIET)
IF(CUDAToolkit_FOUND)
    SET(OPENMM_BUILD_CUDA_LIB ON CACHE BOOL "Build OpenMMCuda library for Nvidia GPUs")
ELSE(CUDAToolkit_FOUND)
    SET(OPENMM_BUILD_CUDA_LIB OFF CACHE BOOL "Build OpenMMCuda library for Nvidia GPUs")
ENDIF(CUDAToolkit_FOUND)
IF(OPENMM_BUILD_CUDA_LIB)
    ADD_SUBDIRECTORY(platforms/cuda)
ENDIF(OPENMM_BUILD_CUDA_LIB)
```

Doesn't have a bit of logic that can enforce that CUDA or OpenCL build is required. 

Something like 

```CMake
FIND_PACKAGE(CUDAToolkit QUIET)
IF(CUDAToolkit_FOUND)
    SET(OPENMM_BUILD_CUDA_LIB ON CACHE BOOL "Build OpenMMCuda library for Nvidia GPUs")
ELSE(CUDAToolkit_FOUND)
    IF(OPENMM_CUDA_REQUIRED)
        MESSAGE(FATAL_ERROR "CUDA support was required but the CUDA Toolkit could not be found")
    ENDIF()
    SET(OPENMM_BUILD_CUDA_LIB OFF CACHE BOOL "Build OpenMMCuda library for Nvidia GPUs")
ENDIF(CUDAToolkit_FOUND)
IF(OPENMM_BUILD_CUDA_LIB)
    ADD_SUBDIRECTORY(platforms/cuda)
ENDIF(OPENMM_BUILD_CUDA_LIB)
```

Would do the job. @peastman would this be something you would be interested in? I ran into this issue when building OpenMM for the OpenMM core, and I need to require that the CUDA and OpenCL libs are being built.

**Comment by peastman** [comment]
That just sets the default value.  When you run CMake, set `OPENMM_BUILD_CUDA_LIB` to `ON`.  If it can't be found, you'll get an error.

**Comment by hmacdope** [comment]
Doesn't it get auto set to off if `IF(CUDAToolkit_FOUND)` is False? I will double check.

**Comment by peastman** [comment]
The `CACHE` keyword means the variable gets stored in the cache and can be modified by the user.  The value specified on that line is the default.  You can override it either through the ccmake UI or with `-DOPENMM_BUILD_CUDA_LIB=ON` on the cmake command line.

**Comment by hmacdope** [comment]
Sorry you are right just re-tested. Not sure what was going on on the windows github runner over on the FAH core.
