### ISSUE TITLE
Generating short length trajectory multiple times

### ISSUE THREAD

**Issue by smlee99** [openmm/openmm#4203]
Hi. OpenMM devs. These days I'm trying to follow the transition path sampling method. In here, it's crucial to generate short length trajectory (4ps, for instance) multiple times (>6000) to sample the transition path ensemble. Below is the python script that I used for this while skipping several unimportant things.

```
from parmed.openmm.reporters import NetCDFReporter as Reporter
from simtk.openmm import *
from stmtk.openmm.app import *

def generate_tpstraj(simtps,conf,vels,nsteps,dt):
    start = time()
    simtps.context.setPositions(conf)
    simtps.context.setVelocitiesToTemperature(300)
    reporter = Reporter('candidate.nc', dt, vels=True)
    simtps.reporters.append(reporter)
    simtps.step(nsteps)
    end = time()
    print('Time elapsed:',end-start)
    
 pdb = PDBFile('init.pdb')
 integ_tps = LangevinIntegrator(temperature, freq, timestep)
 # forcefield definition, createSystem, add several forces (this takes a bit long time)
 
platform = Platform.getPlatformByName('CUDA')
properties = {'CudaPrecision': 'mixed'}
properties["DeviceIndex"] = "0"
simtps = Simulation(pdb.topology, system, integ_tps, platform, properties)

for i in range(6000):
    generate_tpstraj(simtps,conf,vels,nsteps,dt)

```

I've found that the major problem of this code is that the computation time for running generate_tpstraj function in loop keeps increasing repeatedly in a nearly linear manner. One guess for this is that same `Simulation` object (`simtps` in the above code) is used multiple times for generating trajectory, but have not much idea on how to resolve such issue. Is there any solution for this issue without constructing the `Simulation` object every time while executing `generate_tpstraj` function?

![image](https://github.com/openmm/openmm/assets/54790642/2a395062-d1c4-491d-a8a1-c2336666807e)

**Comment by smlee99** [comment]
How dumb I am! Thanks for your clear answer. Now the time for running simulation is kept constant. Just one more question related to context initialization. For generating each reactive trajectory from original trajectory, perturbation is required to fully harvest the sampling region. This can be done in Langevin dynamics by the generated random number. Does this imply that the context of `simtps` has to be reinitialized through `Context.reinitialize()` method to do so? (To add, I'm currently applying the PME for computing electrostatic energy.)

**Comment by peastman** [comment]
I'm not sure what you mean.  The integrator applies random forces at every step.  That's true whether or not you reinitialize it.

Are you saying you want it to use exactly the same sequence of random forces on every trajectory?  You can do that by setting the random seed and then reinitializing before each trajectory.  The default seed is 0, which actually means to pick a different random seed for every run.  You need to set it to a non-zero value if you want the forces to be repeatable.

**Comment by smlee99** [comment]
Oh I see. The random seed is the thing that I'd like to know. Many thanks for your kind answer and let me close this issue.
