### ISSUE TITLE
Running a simulation in AMOEBA

### ISSUE THREAD

**Issue by GustavoG9** [openmm/openmm#4204]
Hi everyone,

I have run the equilibration of a polyelectrolyte in AMBER with the ff19SB forcefield and I'm currently attempting to use this output as an input to run simulations using the AMOEBA force field in OpenMM. But when I try to generate the topology as follows:

pdb = PDBFile('polymer.pdb')

**forcefield = ForceField('amoeba2018.xml')

system = forcefield.createSystem(pdb.topology, nonbondedMethod=PME, nonbondedCutoff=1*nanometer, constraints=HBonds)**

Throws the following error:

**ValueError: No template found for residue 1 (UNL).  The set of atoms is similar to GLY, but it is missing 3 atoms.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template**
------------------------------------------------------------
Does anyone knows a better procedure or alternative that could be of help?
Thanks!

**Comment by peastman** [comment]
Did you read the FAQ entry linked in the error message?  What is UNL?  It isn't a standard residue.

**Comment by GustavoG9** [comment]
Yes, but I don't know how to correct that. DO you have any suggestions?

> Did you read the FAQ entry linked in the error message? What is UNL? It isn't a standard residue.

**Comment by peastman** [comment]
Again, what is UNL?

**Comment by GustavoG9** [comment]
It is the name of the ligand.
I believe the problem is AMOEBA doesn't has the parameter for this ligand.
The ligand topology in the normal MD simulation ws generated using GAFF2 according to this tutorial:

https://colab.research.google.com/drive/1Q-2G_XCpqRmDf4fVqRSZE9Ng2XWqvhgE?hl=es#scrollTo=mgKohjejhhMr

In order to be able to use the output PDB file in AMOEBA I propose the following solution:
a) Parametrize the output pdb file using Poltype for AMOEBA

If you think this won't work, do you have any suggestions?
Thanks!

**Comment by peastman** [comment]
According to Ligand-Expo, the code UNL stands for "unknown ligand".  So it's not the name of the ligand.  Do you know what it is?  If it's similar to glycine but missing three atoms, it's something quite small.

OpenMM can't read files generated by poltype.  You might be able to use ParmEd to convert it, though I'm not sure how complete its support for AMOEBA is.

**Comment by GustavoG9** [comment]
Yes I know what the ligand is, I created it.
I think I'll just use Tinker to do everything. 
Thanks

**Comment by peastman** [comment]
Ok.  Can this issue be closed?
