### ISSUE TITLE
Dynamically changing a global parameter in Context doesn't update it for CustomIntegrator

### ISSUE THREAD

**Issue by eruijsena** [openmm/openmm#4205]
Hello,

In the code below, I am using a `CustomIntegrator` and I want to update a context parameter after some simulation steps. However, using `context.setParameter` only seems to change the value stored in the context, but not the one accessed by the `CustomIntegrator`. Interestingly, if you comment out the first `simulation.step(1)`, the integrator gets the right value, so it seems that the global parameters are only fixed after initialization by calling `step`.

I would therefore like to know:
* Is this behavior expected?
* Is there a way to update a CustomIntegrator's variables on-the-fly?

Thanks in advance!

```
from openmm.app import *
from openmm import *
from openmm.unit import *

class MyIntegrator(CustomIntegrator):
    
    def __init__(self):
        
        CustomIntegrator.__init__(self, 0.002 * picoseconds)
        
        self.addGlobalVariable("integrator_foo", 1.0)
        self.addComputeGlobal("integrator_foo", "foo")


pdb = PDBFile('input.pdb')
forcefield = ForceField('amber14-all.xml', 'amber14/tip3pfb.xml')
system = forcefield.createSystem(pdb.topology, nonbondedMethod=NoCutoff, constraints=HBonds)

integrator = MyIntegrator()
simulation = Simulation(pdb.topology, system, integrator)
cvforce = CustomCVForce("foo")
cvforce.addGlobalParameter("foo", 1)
system.addForce(cvforce)
simulation.context.reinitialize()


print("i_foo:", simulation.integrator.getGlobalVariableByName("integrator_foo"))
print(dict(simulation.context.getParameters()))

simulation.step(1)
print("Updating parameter...")
simulation.context.setParameter("foo", 2)
simulation.step(1)

print("i_foo:", simulation.integrator.getGlobalVariableByName("integrator_foo"))
print(dict(simulation.context.getParameters()))
```

OUT:
```
i_foo: 1.0
{'foo': 1.0}
Updating parameter...
i_foo: 1.0
{'foo': 2.0}
```

**Comment by peastman** [comment]
Thanks for the excellent test case!  The fix is in #4206.  This problem happened on the CUDA and OpenCL platforms, but not on CPU or reference.  If you modified a Context parameter by calling `setParameter()` between steps, the CustomIntegrator did not pick up the change.  It did correctly see the change if the integrator itself modified the parameter through a ComputeGlobal step.

**Comment by peastman** [comment]
Also note this only happened with context parameters.  Setting global variables with `setGlobalVariable()` worked correctly.

**Comment by peastman** [comment]
And one other note: this only applied to global calculations, which take place on the CPU.  Per-DOF calculations, which take place on the GPU, were using the correct value.
