### ISSUE TITLE
Python ImportError (undefined symbol) with custom plugin

### ISSUE THREAD

**Issue by bbye98** [openmm/openmm#4210]
Hello!

I'm currently in the process of developing a new OpenMM plugin. I have successfully run `make`, `make install`, and `make PythonInstall` (albeit with a number of `typemap`-related warnings), but when I try to import my plugin in Python, I get the error:

```
❯ python
Python 3.9.17 | packaged by conda-forge | (main, Aug 10 2023, 07:02:31)
[GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import openmm_ic
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bye/miniconda3/envs/research/lib/python3.9/site-packages/openmm_ic-1.0-py3.9-linux-x86_64.egg/openmm_ic.py", line 15, in <module>
    import _openmm_ic
ImportError: /home/bye/miniconda3/envs/research/lib/libOpenMMIC.so: undefined symbol: _ZTIN6OpenMM10DrudeForceE
```

I am currently on OpenMM 7.7 (pinned for compatibility reasons), which was installed via conda-forge:

```
❯ mamba list | grep openmm
openmm                    7.7.0            py39h15fbce5_1    conda-forge
openmm-ic                 1.0                      pypi_0    pypi
openmm-plumed             1.0              py39hcf40d7a_6    conda-forge
```

`ldd` shows that `libOpenMMIC.so` is linked against `libOpenMM.so.7.7`:

```
❯ ldd /home/bye/miniconda3/envs/research/lib/libOpenMMIC.so
        linux-vdso.so.1 (0x00007ffe509a6000)
        libOpenMM.so.7.7 (0x00007fa9faf92000)
        libstdc++.so.6 (0x00007fa9fadaf000)
        libgcc_s.so.1 (0x00007fa9fad94000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa9fab8d000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fa9fab87000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fa9fab7b000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fa9fab58000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fa9faa09000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fa9fb341000)
```

When I `grep` for `DrudeForce` in `libOpenMMIC.so`, the mangled symbol (demangled: `typeinfo for OpenMM::DrudeForce`) from before is indeed undefined:

```
❯ nm -D libOpenMMIC.so | grep DrudeForce
                 U _ZTIN6OpenMM10DrudeForceE
```

However, that exact symbol appears to be a weak object in `libOpenMMDrude.so`:

```
❯ nm -D libOpenMMDrude.so | grep _ZTIN6OpenMM10DrudeForceE
0000000000017320 V _ZTIN6OpenMM10DrudeForceE
```

Would it be possible to link `libOpenMMIC.so` to `libOpenMMDrude.so` so that the symbol can be found? Or is there a more foolproof solution?

Thank you!

**Comment by peastman** [comment]
Can you say more about what your plugin does?  Since it's trying to import DrudeForce, I assume your plugin interacts with the Drude plugin in some way?  If so, you probably need to modify your setup.py file to list that library as a dependency.  Or does your plugin have nothing to do with DrudeForce, and it's just trying to important that symbol by accident?

**Comment by bbye98** [comment]
@peastman The plugin implements two Langevin integrators that work on systems with image charges (whose movement is dependent on that of the "real" charges). There's one for "normal" systems and one for Drude particles, so indeed it does interact with the Drude plugin.

Originally, in the `setup.py` file in the `python` subdirectory, I only had `libraries=['OpenMM', 'OpenMMIC']`. However, changing that to `libraries=['OpenMM', 'OpenMMDrude', 'OpenMMIC']` did not resolve the issue. Is there someplace else I need to reference the Drude plugin?

**Comment by peastman** [comment]
That's the only one that should be needed in that file.  Looking at your original post, I see that libOpenMMDrude.so isn't listed in the output of ldd.  That suggests the problem is in building libOpenMMIC.so.  Did you base your plugin on the example plugin?  In the top level [CMakeLists.txt](https://github.com/openmm/openmmexampleplugin/blob/6340817d2c53105c0cb8c862d83653b7ebc079db/CMakeLists.txt#L70) you'll find the line

```
TARGET_LINK_LIBRARIES(${SHARED_EXAMPLE_TARGET} OpenMM)
```

In the corresponding line for your plugin, add OpenMMDrude:

```
TARGET_LINK_LIBRARIES(${SHARED_EXAMPLE_TARGET} OpenMM OpenMMDrude)
```

Does that fix it?

**Comment by bbye98** [comment]
That will probably do it, but I'll have to check in later. Not sure what I did, but now I'm getting the error

```
❯ make PythonInstall
ICPluginWrapper.cpp:178:11: fatal error: Python.h: No such file or directory
  178 | # include <Python.h>
      |           ^~~~~~~~~~
compilation terminated.
error: command '/usr/bin/gcc' failed with exit code 1
make[3]: *** [python/CMakeFiles/PythonInstall.dir/build.make:78: PythonInstall] Error 1
make[2]: *** [CMakeFiles/Makefile2:170: python/CMakeFiles/PythonInstall.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:177: python/CMakeFiles/PythonInstall.dir/rule] Error 2
make: *** [Makefile:205: PythonInstall] Error 2
```

which suggests I somehow messed up my include path and it's no longer finding `Python.h`, despite it being in my `/home/bye/miniconda3/envs/research/include/python3.9` directory.

**Comment by bbye98** [comment]
@peastman It works perfectly! Thank you so much!

**Comment by peastman** [comment]
Great, glad it's working!  Is it ok to close this issue?

**Comment by bbye98** [comment]
Yes, of course! I'll go ahead and close this issue now.
