### ISSUE TITLE
Simulation speed decreases with time in a loop

### ISSUE THREAD

**Issue by amin-sagar** [openmm/openmm#4215]
Dear openmm users and developers,
I am seeing a curious behavior with the simulation speed decreasing with multiple simulations in a simple for loop. My script is
```
NVTsteps=50000
NPTsteps=12500000
num_steps=NVTsteps+NPTsteps
for i in range(1,6):
    integrator = copy(integrator)
    simulation = Simulation(protein_modeller.topology, system, integrator, platform)
    simulation.context.setPositions(protein_modeller.positions)
    simulation.minimizeEnergy(maxIterations=5000)
    print('Saving...')
    positions = simulation.context.getState(getPositions=True).getPositions()
    pdbfilename = 'Protein_Bic_min_run_'+str(i)+'.pdb'
    PDBFile.writeFile(simulation.topology, positions, open(pdbfilename, 'w'))
    print('Minimization Done')
    dcdname = 'Protein_Bic_min_NVT_NPT_'+str(i)+'.dcd'
    simulation.reporters.append(DCDReporter(dcdname,5000))
    logfilename = 'Protein_Bic_min_NVT_NPT_'+str(i)+'.log'
    simulation.reporters.append(StateDataReporter(logfilename, 5000, step=True, potentialEnergy=True, temperature=True, progress=True, remainingTime=True, speed=True,totalSteps=num_steps))
    print('Running NVT\n')
    simulation.step(NVTsteps)
    system.addForce(MonteCarloBarostat(1*bar, 300*kelvin))
    simulation.context.reinitialize(preserveState=True)
    print("Running NPT")
    simulation.step(NPTsteps)
```
The speed printed in the log file keeps decreasing. I have plotted it.
![Speed](https://github.com/openmm/openmm/assets/118898409/30eae1a5-595b-42a0-a908-38c972974bec)

Is there something wrong with setting up simulations in a for loop like I did?
I would be really grateful for any suggestions.
Amin.

**Comment by peastman** [comment]
Every time through the loop you add another barostat to the System.  By the fifth iteration, you have five barostats all trying to control the pressure.

**Comment by peastman** [comment]
If you want to repeatedly enable and disable pressure control in a loop, the best way to do it is to include a barostat from the beginning and call `setFrequency()` on it.  Setting the frequency to 0 disables the barostat.

**Comment by amin-sagar** [comment]
Thanks @peastman.
I didn't realize that I was adding more barostats in each loop.
Thanks for the solution as well.
I have run a couple of simulations like this. Does this make these simulations unusable? i.e. would this change the sampled ensemble as well? Or is this relatively innocuous as it just adds more barostats controlling the pressure?

**Comment by peastman** [comment]
I believe the results should still be correct, in that the ensemble is the same.  It was just attempting a lot more barostat moves than you intended.  But in the initial segment when you meant to be running NVT, you were actually running NPT (except on the first iteration).

**Comment by amin-sagar** [comment]
Thanks @peastman
