### ISSUE TITLE
Problems with enforcePeriodicBox

### ISSUE THREAD

**Issue by tdudgeon** [openmm/openmm#4218]
I'm having problems with the `enforcePeriodicBox` option, both when writing a PDB file like this:
```
PDBFile.writeFile(modeller.topology, context.getState(getPositions=True, enforcePeriodicBox=True).getPositions(), file=outfile, keepIds=True)
```

and when using the DCD reporter like this:
```
DCDReporter(output_traj_dcd, reporting_interval, enforcePeriodicBox=True)
```
In both cases setting `enforcePeriodicBox=True` does not do what is expected, which is that all atoms would be within the same periodic box. In fact it works better if it is set to False, though still not totally correctly.

A full example of this happening can be found here: https://github.com/tdudgeon/simple-simulate-complex/blob/openmm-77/simulateComplexWithSolvent.py

As an example here is the minimised PDB that is created: https://gist.github.com/tdudgeon/97838384969c23e4440af5d57e9c34a9
Clearly the ligand is not in the same box as the protein.

Possibly I'm not using this correctly, but it seems that enforcePeriodicBox is not working as expected.

**Comment by RaulPPelaez** [comment]
I do not usually work with PDB files, so excuse me if I am missing something obvious here.

I took your pdb file and extracted all coordinates from it, I put all of the values into an array and made an histogram of that:
![image](https://github.com/openmm/openmm/assets/13015792/2576f1a1-98b8-40b9-be68-d4bedab05f84)
From this line in the PDB I assume you have a cubic box of size 84.813, the vertical lines above:
```
CRYST1   84.813   84.813   84.813  90.00  90.00  90.00 P 1           1 
```
This means everything is in fact contained within the limits of the box, right?

**Comment by tdudgeon** [comment]
That doesn't look right to me.
What is done in the script is add the protein, add the ligand then add solvent in a box with 10A padding around the protein/ligand. It seems that that box is then used for the CRYST1 line (the input PDB doesn't have a CRYST1 line).
At that point everything looks correct.

Then I minimise and write the PDB out again. That's where things go wrong.
If you display the PDV it looks like this:
![image](https://github.com/openmm/openmm/assets/647419/5305f8b7-d3c7-4af8-94cc-0ae0df3b8a1f)

And if you look at the last few atoms of the protein and the first few of the ligand then you can see that they are clearly in a very different bit of space. 

```
ATOM   4643  OG1 THR A 304       5.244  -9.345 -11.556  1.00  0.00           O  
ATOM   4644  HG1 THR A 304       6.147  -9.181 -11.275  1.00  0.00           H  
ATOM   4645  OXT THR A 304       7.384  -8.169 -10.525  1.00  0.00           O  
TER    4646      THR A 304
HETATM 4647  C1x UNK X   0       8.562  82.266  28.354  1.00  0.00           C  
HETATM 4648  C2x UNK X   0       9.395  83.557  28.269  1.00  0.00           C  
HETATM 4649  O1x UNK X   0      10.109  83.529  27.021  1.00  0.00           O
```

**Comment by peastman** [comment]
Take a look at the [FAQ entry](https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#periodic) on periodic boundary conditions.  It explains how they work, and how it's different from the way you might initially expect them to work.

**Comment by tdudgeon** [comment]
@peastman The FAQ was useful, but it doesn't really answer the question. The docs for the `enforcePeriodicBox` param of System.getState() state:

enforcePeriodicBox (bool=False) – if false, the position of each particle will be whatever position is stored in the Context, regardless of periodic boundary conditions. If true, particle positions will be translated so the center of every molecule lies in the same periodic box.

But when I use this to write the PDB file like this:

```
with open(output_min, 'w') as outfile:
    PDBFile.writeFile(modeller.topology, context.getState(getPositions=True, enforcePeriodicBox=True).getPositions(), file=outfile, keepIds=True)
```

the ligand clearly seems to be in a different box to the protein (see the screenshot from above)

**Comment by tdudgeon** [comment]
Yes, I had come to the same conclusion. The problem seems to be that when I add solvent (using `Modeller.addSolvent()`) the system looks good - a box of water with protein and ligand in the middle, and the centre being at 0,0,0. But in doing so the periodic box is set to a box of ~8.4nm originating from 0,0,0. e.g. the middle of the protein. So when OpenMM does the minimisation you end up with something that looks very strange, even though it is valid with respect to the periodic box.
So I presume I would need to redefine the periodic box vectors manually with some maths to reflect the "box" created when adding the solvent?
Or is there a simpler way to achieve this?

**Comment by peastman** [comment]
Keep in mind, it's really all the same thing.  As it says in the FAQ, there is no "right" periodic box.  Periodic boundary conditions are applied to displacements, not positions, so as far as the simulation is concerned it makes no difference at all which box an atom is in.  In fact, the positions in the file aren't necessarily even the ones used in the minimization and simulation.  Because you specify `enforcePeriodicBox=True` in the call to `getState()`, it performs its own wrapping at that point.  That's really all you're seeing here, the particular box boundaries chosen by `getState()`.

If you want to make the PDB file easier to visualize, try using the `image_molecules()` function from MDTraj.  It's there for situations like this.

**Comment by tdudgeon** [comment]
Thanks. `image_molecules()` does the trick.
