### ISSUE TITLE
Particle coordinate is NaN on CUDA after a certain number of calculations

### ISSUE THREAD

**Issue by andrewtarzia** [openmm/openmm#4221]
I recognise this is a commonly asked question here, but hopefully the points below highlight that something odd is occurring that is unrelated to the physical models. My main question is about how to diagnose and understand the issue with a small understanding of CUDA.

I am running Python 3.11, OpenMM 8.0.0, in WSL 2 (Ubuntu 22.04) on a machine that defaults to the CUDA platform.

The `Particle coordinate is NaN error`, seems to consistently occur for a given optimisation in a series of simulations (forcefield, method, models change throughout this series; I am performing a sequence of calculations on a series of molecules). The step that seems to fail consistently is local energy minimisation, not dynamics.

If I rerun from the failed step (i.e. it is now first in line, not third in line), it works fine, which implies to me that the model is not unphysical (also because the CPU platform runs fine), unless something "remembered" by CUDA or carried over is changing the model in a way I am not aware of? Do I need to uninitialise and reinitialise the platform between calculations or something?

The other thing to note is that the same infrastructure worked perfectly fine when I defined my forcefield through `force.add_force` commands, rather than having a forcefield `xml` file, which I now load in like so: `forcefield = app.ForceField('path_to_xml')`.

**Comment by peastman** [comment]
Can you post files to reproduce the problem?  Without that, it's hard to even guess what might be happening.

**Comment by andrewtarzia** [comment]
Hey @peastman , I will try to put together a minimum working example for this, but it is not straightforward to separate the simulations from the python library that runs them/defines the models in them.

However, I have confirmed today that the issue does not occur on a different machine (same setup otherwise). So, my current guess is a problem with CUDA/WSL/my laptop.

**Comment by peastman** [comment]
You can write out the System and State to XML files.  See https://openmm.github.io/openmm-cookbook/latest/notebooks/cookbook/Saving%20Systems%20to%20XML%20Files.html.  Then it only takes a minimal Python script to load the files and hopefully reproduce the problem.

**Comment by andrewtarzia** [comment]
Thank you for that information, I had no idea and that would be super useful in the future.

As for my issue, I think I found the bug (some issue with mishandling variables in Python). Hence, I will close this issue.

Thank you!
