### ISSUE TITLE
MTSLangevinIntegrator missing method getTemperature()

### ISSUE THREAD

**Issue by yanze039** [openmm/openmm#4226]
Hi,

I am using `openmmtools` to do REMD simulation with `MTSLangevinIntegrator `. 
But `openmmtools` found this `MTSLangevinIntegrator` is not thermostated due to lack of get/set attribute `temperature` or `kT`.

Is it possible to add those class methods?

**Comment by peastman** [comment]
MTSLangevinIntegrator is implemented with CustomIntegrator.  It stores kT in a global variable:

https://github.com/openmm/openmm/blob/e2453f5ec1fc1fd7916e0b398033c3e9ed341877/wrappers/python/openmm/mtsintegrator.py#L174

You can use `getGlobalVariableByName()` and `setGlobalVariableByName()` to get or set that variable.

**Comment by jchodera** [comment]
@mikemhenry @ijpulidos : Can you see if this requires we fix anything in our `MTSLangevinIntegrator` wrapping in `openmmtools`?

**Comment by peastman** [comment]
We could add `getTemperature()` and `setTemperature()` as wrappers around it, if that would make things easier.

**Comment by ijpulidos** [comment]
I am a bit confused, we don't have an `MTSLangevinIntegrator` in `openmmtools`. We do [have an `MTSIntegrator`](https://github.com/choderalab/openmmtools/blob/6cef59b67327d1a16685304368e87e99a37a441c/openmmtools/integrators.py#L322), though. Is this the one that we should be changing or should it be the one that lives in `openmm` (pointed by @peastman )?

**Comment by Dead-fisher** [comment]
Sorry for the confusion. I am using `MTSLangevinIntegrator` from `openmm` and writing new sampler in `openmmtools` for REMD simulations. I currently solved this by inheriting `MTSLangevinIntegrator` and adding `getTemperature` method mannually.
