### ISSUE TITLE
Valid to skip neighbor list for more forces?

### ISSUE THREAD

**Issue by bdenhollander** [openmm/openmm#4227]
#4070 added `numParticles > #` to two calls to `addInteractions`. Since `useNeighborList` has a default value of true, there are 5 other calls to `addInteraction` that do not attempt to skip the neighbor list for small systems. Would simulations be valid if they also skipped?

gbsa performance doubled on Windows HIP when I added the check for `numParticles > 3000` in `CommonCalcGBSAOBCForceKernel::initialize` but that seems a bit excessive and one of the GBSAOBC force unit tests is failing:
`exception: Assertion failure at TestGBSAOBCForce.h:237.  Expected 0, found 1594.62`

I'm not sure if updating some instances of `USE_CUTOFF` to `USE_NEIGHBOR_LIST` would fix this, similar to what was done for nonbonded kernels, or if there is some other dependency on the neighbor list for gbsa to work.

**Comment by bdenhollander** [comment]
@peastman Did you get a chance to check if [gbsaObc.cc](https://github.com/openmm/openmm/blob/master/platforms/common/src/kernels/gbsaObc.cc) could be adjusted for `USE_NEIGHBOR_LIST` so that a particle count check could be added as a parameter to the following line of code? https://github.com/openmm/openmm/blob/31abb2f7a34e8ef5c17bc52207fb0d226bf5d703/platforms/common/src/CommonKernels.cpp#L2535

The gbsa benchmark spends nearly half its time idle on Windows HIP while downloading interaction counts so I would expect a big boost if that can be avoided. I haven't found a HIP command similar to OpenCL's flush to use to minimize gaps.
![image](https://github.com/openmm/openmm/assets/44237618/6c41a7ee-d53d-4dc1-813f-e03f40565418)

**Comment by peastman** [comment]
How does it compare to OpenCL after the changes in #3973?  That is, is the problem building the neighbor list, or is the problem inefficient communication with HIP?

Here's how we implement `flushQueue()` for CUDA.  It's probably something similar for HIP.

https://github.com/openmm/openmm/blob/31abb2f7a34e8ef5c17bc52207fb0d226bf5d703/platforms/cuda/src/CudaContext.cpp#L812-L814

**Comment by bdenhollander** [comment]
The gaps in OpenCL are shorter than HIP after the addition of flushes.

OpenCL - gbsa
![image](https://github.com/openmm/openmm/assets/44237618/a067f4a0-db39-4ce1-9a65-0fb961a78c54)

I'm starting to wonder if device-to-host memory copy has a latency of 500-600 us. Since gbsa spends more time computing in OpenCL, there is more time for the copy to happen asynchronously. The copy is nearly finished by the time it hits the event whereas with HIP, the compute is so much faster that it must wait longer for the memory copy to complete.

| Kernel            | OpenCL | HIP    |
|-------------------|--------|--------|
| computeBornSum    | 84 us  | 68 us  |
| computeGBSAForce1 | 66 us  | 55 us  |
| computeNonbonded  | 391 us | 75 us  |
| Total             | 541 us | 198 us |

`hipStreamSynchronize` is the equivalent of `cuStreamSynchronize`. Unfortunately they are both akin to OpenCL `clFinish` rather than `clFlush`.

**Comment by peastman** [comment]
> I'm starting to wonder if device-to-host memory copy has a latency of 500-600 us.

The latency should only be a few µs.  There's also the issue of bandwidth for large transfers, but in this case we're only sending a few bytes.

Answering your original question, it should be possible to use the same optimization for GB.  It takes more changes than just the value passed to `addInteraction()`.  For example, we need to make changes to the code in gbsaObc.cc similar to the ones in nonbonded.cu and nonbonded.cl.  None of that should be difficult.

I'll mark this as a feature request.

**Comment by peastman** [comment]
@bdenhollander I've started thinking about how to implement this, but I'm not sure if it actually makes sense.  Would there be any advantage over just telling it not to use a cutoff?

Explicit solvent simulations use periodic boundary conditions, so they have to use a cutoff.  GB simulations usually don't use periodic boundary conditions, and it's common to run them without a cutoff.  For large systems you might choose to use a cutoff anyway to improve speed, but this change isn't relevant to those cases.  It's for small systems where applying a cutoff and building a neighbor list doesn't help the speed.

**Comment by bdenhollander** [comment]
I don't have a biochemistry background to know if not using a cutoff would be effective. 

During the gbsa benchmark, the first time `OpenCLNonbondedUtilities::addInteraction` is called `this->useNeighborList` ends up false because of the size of the system. Then it gets called a second time when GBSA related forces are added and `this->useNeighborList` ends up true because `useNeighborList` is hard-coded to true and `useCutoff` is true. Would a different combination of options here work to keep `this->useNeighborList` false?
https://github.com/openmm/openmm/blob/796ffaaa97decdf1593ed75afa5fbb21b6b32e9c/examples/benchmark.py#L226-L230

**Comment by peastman** [comment]
Try changing `CutoffNonPeriodic` to `NoCutoff`.  The only reason to use a cutoff with GB is to improve speed (at the cost of accuracy).

DHFR is big enough that it's probably faster with the cutoff.  The relative overhead of building the neighbor list is much lower for implicit solvent simulations than for explicit ones.  You build the neighbor list once, then use it to accelerate three different nonbonded kernels.  And the calculations done in those kernels are more complicated than the standard nonbonded kernel.  So the threshold where it's faster to skip the cutoff will be at a lower number of atoms.

**Comment by bdenhollander** [comment]
The additional computation without the cutoff does not quite cover skipping finding interactions and downloading the counts.

| gbsa RX 6600 | OpenCL<br>ns/day | HIP<br>ns/day |
|--------|--------|--------|
| `CutoffNonPeriodic` | 635.3 | 1023.1 |
| `NoCutoff` | 537.8 | 994.66 |

>  You build the neighbor list once, then use it to accelerate three different nonbonded kernels.

Does building the neighbor list once mean that it only needs to find interacting blocks once and will never need to be rebuilt or resized? If so, could that be taken advantage of to use cutoff and skip everything related to neighbor list maintenance after it's built the first time?

**Comment by peastman** [comment]
I meant per time step.  You still have to rebuild the neighbor list when the atoms move too far.  But building the neighbor list is a much smaller fraction of the computation time than in explicit solvent simulations, and the benefit of having it is larger.

**Comment by bdenhollander** [comment]
It sounds like we've ruled out skipping the neighbor list for gbsa. Is there an easy way to test whether Amoeba performance would improve? There are two instances of `cc.getNonbondedUtilities().addInteraction`, one `nonbonded->addInteraction`, and one `nb.addInteraction` that could potentially benefit.

**Comment by peastman** [comment]
We never want to skip the neighbor list for AMOEBA.  Computing nonbonded interactions is about 10-20x more expensive than for point charge force fields.  The cost of building the neighbor list is negligible compared to the cost of computing extra nonbonded interactions.

**Comment by bdenhollander** [comment]
In that case, I think this issue can be closed since I don't see any other `addInteraction` calls where skipping the neighbor list could help.

**Comment by peastman** [comment]
Ok.  Thanks for raising the question for discussion.
