### ISSUE TITLE
Neighbor list artifacts

### ISSUE THREAD

**Issue by lvotapka** [openmm/openmm#4230]
Hey @peastman, you may already know about this paper, but it looks like the Gromacs people ran into a problem with the algorithm they use for anisotropic barostat when used for large system, that caused membrane deformations, and such.

https://chemrxiv.org/engage/chemrxiv/article-details/64b55faeb053dad33a692084

I just wanted to make sure you were aware of this.

**Comment by peastman** [comment]
It sounds like that's specific to Gromacs.  They only update the neighbor list at fixed intervals, accepting that sometimes it will miss interactions as a result.  This is, in my opinion, a Really Bad Idea (TM).  They justify it by saying the effect on results is negligible, but from this paper it sounds like there are situations where it leads to significant artifacts.

OpenMM, like most MD codes, doesn't do that.  It monitors how far atoms move, and rebuilds the neighbor list whenever they've moved far enough to create a risk of missing interactions.

**Comment by lvotapka** [comment]
Alright, sounds good @peastman. If you think this won't be an issue for OpenMM, then I think we are good.
