### ISSUE TITLE
energy decomposiition discrepancies retrieving energies from the state object vs parmed

### ISSUE THREAD

**Issue by MarieTJ** [openmm/openmm#4232]
I cannot  wrap my head around the energy decomposion discrepancies I observe using the parmed parmed.openmm.energy_decomposition_system ( which agrees with pytraj )  and  openmm, retrieving the energy from the  state.

Am I missing something obvious ?

#### CODE #######

parm = parmed.load_file('system-wet.prmtop','equil_system.pdb')
coords = PDBFile('equil_system.pdb').positions

 #>>>>>>>Parmed <<<<<<<<<
system = parm.createSystem() 
print(parmed.openmm.energy_decomposition_system(parm, system))

 #>>>>>>>OpenMM <<<<<<<<<
integrator = LangevinIntegrator(
        300 * u.kelvin, 1.0 / picosecond, 0.004 * picoseconds
    )
simulation = Simulation(parm, system, integrator, platform)
simulation.context.setPositions(coords )
for i, f in enumerate(system.getForces()):
            state = simulation.context.getState(getEnergy=True, groups={i})
            print(f.getName(), state.getPotentialEnergy())

#>>>>>>>pytraj <<<<<<<<<

import pytraj
trajectory = pytraj.iterload('equil_system.pdb', 'system-wet.prmtop' )
print( pytraj.energy_decomposition(trajectory, igb=0)) 

########
#Results#
########

>>>>>> parmed 
[('HarmonicBondForce', 592.4794067616216), ('HarmonicAngleForce', 1536.8696690517447), ('PeriodicTorsionForce', 2379.2729277455783), ('NonbondedForce', -89590.74749043977), ('CMMotionRemover', 0.0)]

>>>>>> openmm 
HarmonicBondForce 3104.6149687248403 kJ/mol
HarmonicAngleForce 6729.003016003211 kJ/mol
PeriodicTorsionForce 10088.86935413198 kJ/mol
NonbondedForce 0.0 kJ/mol
CMMotionRemover 0.0 kJ/mol

>>>>> pytraj 
OrderedDict([('amd_boost', array([0.])),
             ('angle', array([1536.87126237])),
             ('angle_ub', array([0.])),
             ('bond', array([592.47926493])),
             ('cmap', array([0.])),
             ('constraint', array([0.])),
             ('ct', array([0.])),
             ('dihedral', array([2379.27320458])),
             ('disp', array([0.])),
             ('dvdl', array([0.])),
             ('elec', array([-105603.00683254])),
             ('elec_14', array([4791.51626482])),
             ('emap', array([0.])),
             ('gb', array([0.])),
             ('hbond', array([0.])),
             ('imp', array([0.])),
             ('les', array([0.])),
             ('noe', array([0.])),
             ('pb', array([0.])),
             ('polar', array([0.])),
             ('rism', array([0.])),
             ('scf', array([0.])),
             ('surf', array([0.])),
             ('tot', array([-85078.70514034])),
             ('vdw', array([10543.30940791])),
             ('vdw_14', array([680.85228759]))])

**Comment by peastman** [comment]
Can you provide your complete script?  It's hard to tell exactly what you're doing from just those lines.

**Comment by swails** [comment]
Also note that ParmEd and pytraj report units in the AKMA system while OpenMM (like GROMACS) uses the MD unit system. 

For energies this means that ParmEd and pytraj specify in kcal/mol while OpenMM specifies in kJ/mol.

**Comment by MarieTJ** [comment]
Thanks for the reply, sorry i should have been more specific I am more bothered about the non bonded energy ( 0 kJ/mol) that openmm returns, as i said I must be missing something obvious all the remaining terms match indeed. I attached a smaller test case. 
 
[issue-4232.zip](https://github.com/openmm/openmm/files/12607265/issue-4232.zip)

**Comment by sef43** [comment]
The index of the force groups of each force in system are not 0,1,2,3 as you have assumed. Rather NonBondedForce has been set to force group 11 (I assume by the parmed createSystem code). If you change your last bit of code to this it will give the same energies:

```python
for f in system.getForces():
    i = f.getForceGroup()
    state = simulation.context.getState(getEnergy=True, groups={i})
    print(f.getName(), i, state.getPotentialEnergy())
```
```
HarmonicBondForce 0 85.80510165924807 kJ/mol
HarmonicAngleForce 1 434.1445184836825 kJ/mol
PeriodicTorsionForce 2 2375.237750150592 kJ/mol
NonbondedForce 11 -12518.38855250176 kJ/mol
CMMotionRemover 0 85.80510165924807 kJ/mol
```

Or you can set up the decomposition into force groups yourself with OpenMM:
```python
# put each force into its own group
for i, f in enumerate(system.getForces()):
    f.setForceGroup(i)

simulation.context.setPositions(xyz )
energy = simulation.context.getState(getEnergy=True).getPotentialEnergy()

for i,f in enumerate(system.getForces()):
    state = simulation.context.getState(getEnergy=True, groups={i})
    print(f.getName(), state.getPotentialEnergy())
```
```
HarmonicBondForce 85.80510165924807 kJ/mol
HarmonicAngleForce 434.1445184836825 kJ/mol
PeriodicTorsionForce 2375.237750150592 kJ/mol
NonbondedForce -12518.38855250176 kJ/mol
CMMotionRemover 0.0 kJ/mol
```

**Comment by MarieTJ** [comment]
Thanks so much ! that's explain!
