### ISSUE TITLE
Drude ion template not recognized

### ISSUE THREAD

**Issue by vkwan8** [openmm/openmm#4234]
No template found when trying to generate a system from a pdb file containing only drude ions. 

The pdb file was generated with VMD's psfgen with the charmmff file `toppar_drude_master_protein_2019g.str`. 
The equivalent .xml file `charmm_polar_2019.xml` is used. 
MWE is attached.

```
Traceback (most recent call last):

  File ~/miniconda3/lib/python3.9/site-packages/spyder_kernels/py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File ~/openmm_bk3/mwa/run.py:14
    system = forcefield.createSystem(topology)

  File ~/miniconda3/lib/python3.9/site-packages/openmm/app/forcefield.py:1218 in createSystem
    templateForResidue = self._matchAllResiduesToTemplates(data, topology, residueTemplates, ignoreExternalBonds)

  File ~/miniconda3/lib/python3.9/site-packages/openmm/app/forcefield.py:1433 in _matchAllResiduesToTemplates
    raise ValueError('No template found for residue %d (%s).  %s  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template' % (res.index+1, res.name, _findMatchErrors(self, res)))

ValueError: No template found for residue 1 (CLA).  This might mean your input topology is missing some atoms or bonds, or possibly that you are using the wrong force field.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template
```
[test.zip](https://github.com/openmm/openmm/files/12640065/test.zip)

**Comment by peastman** [comment]
Your PDB file marks the Drude particle as being a second chlorine atom.  See the last column:

```
ATOM      1  CLA CLA A   1       5.000   5.000   5.000  1.00  0.00      I   CL
ATOM      2 DCLA CLA A   1       5.000   5.000   5.000  1.00  0.00      I   CL
```

The force field is looking for a template containing two chlorine atoms, and of course not finding one.

There's no standard way of marking an atom in a PDB file as not being a real atom.  OpenMM provides a non-standard mechanism of putting a special value into the element symbol column to mark it as an extra particle.  By default it uses `EP`.  You can choose a different value with the `extraParticleIdentifier` argument to the PDBFile constructor.

Try changing the element symbols for the Drude particles to `EP`.  Does that work?

**Comment by vkwan8** [comment]
Changing that to EP works. Looks like when psfgen generate drude particles, it inherited the host's element.

Thanks a lot!
