### ISSUE TITLE
How to set PBC only in the XY direction?

### ISSUE THREAD

**Issue by 9527567** [openmm/openmm#4236]
I am conducting a simulation of a membrane where a large number of ions are placed on one side and not on the other, with the aim of studying the ion transport process. But during the simulation process, ions entered from the outside, and I'm not sure if this is related to the PBC setting? If possible, without setting the PBC in the Z direction, ions can only pass through the membrane through transport proteins?

**Comment by peastman** [comment]
You can't make a system periodic in some directions but not others.  It's all or none.

Instead, you can make the box large enough in the perpendicular direction so different copies have minimal interaction with each other.  And then use a CustomExternalForce to create a barrier between copies.  Make a high energy region that blocks atoms from diffusing between different periodic boxes.  See https://openmm.github.io/openmm-cookbook/latest/notebooks/cookbook/Applying%20a%20Constant%20External%20Force.html.  You might use an energy expression like `1/periodicdistance(0, 0, z, 0, 0, 5)^12`.  That would repel particles from the plane z=5.

**Comment by 9527567** [comment]
This is really a wonderful idea, I will try it out. Thank you.

**Comment by z-gong** [comment]
Just a comment, for a half-periodic system, if you have a large number of ions on one side of the simulation box, you probably need to apply a slab correction to eliminate the dipole-dipole interaction between periodic copies.
https://github.com/openmm/openmm/issues/2480
https://pubs.aip.org/aip/jcp/article-abstract/111/7/3155/294442/Ewald-summation-for-systems-with-slab-geometry?redirectedFrom=fulltext

**Comment by 9527567** [comment]
Thank you. I will try it out.
