### ISSUE TITLE
Create complete force field xml file from CHARMM-style force field

### ISSUE THREAD

**Issue by wayuer19** [openmm/openmm#4237]
Hi,

I'm doing some coarse-grained simulations based on CHARMM top and parameter files. So now, in my running script, the system was created based on "CharmmPsfFIle", "CharmmParameterSet" and "psf.createSystem". But I'm trying to build a clear protocol, where only XML force field file and PDB file are needed to run the CG simulation. Is it possible to export a complete XML force field file from these Charmm-style files?

Thank you!

**Comment by peastman** [comment]
If you have the force field definition in CHARMM files, you can use [ParmEd](https://github.com/ParmEd/ParmEd) to convert them to OpenMM format.  That's how we created the files for CHARMM36.

**Comment by wayuer19** [comment]
Thank you for your reply. I've read the charmm36.xml created from c36_jul20 through openmmforcefield package. But I'm a little confused about the CMAP part.
For example, for alanine map (C    NH1  CT1  C    NH1  CT1  C    NH1) in charmm force field (c36_jul20), when phi = -180.0, it's
 `! phi = -180.0
     0.126790      0.768700      0.971260      1.250970      2.121010
     2.720430      2.089440      1.789790      0.780870     -0.688474
     1.001130     -2.200520     -4.827670     -4.821447     -4.913223
    -3.591106     -2.766446     -2.784200     -2.454589     -2.346991
    -2.335350     -1.522656     -0.951542     -0.036650 `
but in charmm36.xml, it's like
`0.50115952 -0.99185904 -1.7044779200000002 -13.74992104 -16.38069472 -18.76507264 -21.8061712 -25.32788584 -25.626205040000002 -25.574951040000002 -7.375806240000001 -19.095064720000003 -20.198971280000002 -16.775651768000003 -10.808343104 -8.349084136 -8.862833312000001 -8.747986696000002 -6.325254048 -0.517200976 -1.4961984 -3.3356103200000002 5.49928224 2.13831688`

They are very different even converted from kcal/mol to kj/mol I think. Is there any difference in CMAP organization (like the order of phi and psi) between CHARMM and OpenMM?

**Comment by peastman** [comment]
The OpenMM values begin from 0, not -180.  Converting the first CHARMM value to kJ/mol, `0.126790*4.184 = 0.53048936`.  So I search for that value in the OpenMM file, and sure enough I find `0.5304893600000001` right in the middle of the first map.

**Comment by wayuer19** [comment]
Got it. Thank you!
