### ISSUE TITLE
[BUG] Mismatch between documentation and code

### ISSUE THREAD

**Issue by chem-william** [openmm/openmm#4241]
In the [documentation](http://docs.openmm.org/7.5.0/userguide/application.html#adding-solvent) the following is said:

> By default, addSolvent() creates TIP3P water molecules, but it also supports other water models:

> ```python
> modeller.addSolvent(forcefield, model='tip5p')
> ```

> Allowed values for the model option are 'tip3p', 'tip3pfb', 'spce', 'tip4pew', 'tip4pfb', and 'tip5p'. Be sure to include the single quotes around the value.

Yet, [in the code](https://github.com/openmm/openmm/blob/b247e7d8cf772f22e9ab559047d1721d42660673/wrappers/python/openmm/app/modeller.py#L460-L472), only the following is specified:
```python
        vdwRadiusPerSigma = 0.5612310241546864907
        if model == 'tip3p':
            waterRadius = 0.31507524065751241*vdwRadiusPerSigma
        elif model == 'spce':
            waterRadius = 0.31657195050398818*vdwRadiusPerSigma
        elif model == 'tip4pew':
            waterRadius = 0.315365*vdwRadiusPerSigma
        elif model == 'tip5p':
            waterRadius = 0.312*vdwRadiusPerSigma
        elif model == 'swm4ndp':
            waterRadius = 0.318395*vdwRadiusPerSigma
        else:
            raise ValueError('Unknown water model: %s' % model)
```

meaning that 'tip3pfb' and 'tip4pfb' is unspecified.
I ran into the problem with the following code:
```python
pdb = PDBFile("your_choice_of_input_pdb.pdb)
forcefield = ForceField("amber14-all.xml", f"amber14/tip3pfb.xml")
modeller = Modeller(pdb.topology, pdb.positions)
modeller.deleteWater()
residues = modeller.addHydrogens(forcefield)
modeller.addSolvent(forcefield, model=tip3pfb)
```

that should produce the following error:
```bash
  File "test.py", line 31, in main
    modeller.addSolvent(
  File "python3.11/site-packages/openmm/app/modeller.py", line 460, in addSolvent
    raise ValueError('Unknown water model: %s' % model)
```

I'm on the latest version installed through conda:
```bash
Python 3.11.5
openmm                    8.0.0           py311h59c6c42_1    conda-forge
```

**Comment by peastman** [comment]
Thanks for catching that.  We should fix the manual.  The [API documentation](http://docs.openmm.org/latest/api-python/generated/openmm.app.modeller.Modeller.html#openmm.app.modeller.Modeller.addSolvent) correctly lists the allowed options.
