### ISSUE TITLE
Shifting nonbonded interactions 

### ISSUE THREAD

**Issue by ksy141** [openmm/openmm#4243]
How does openMM handle nonbonded potential energy at the cutoff distance? I think it uses a plain cutoff unless I set a switching function. Is there a way I can shift the potential so that the nonbonded potential energy becomes 0 at the cutoff distance? Thank you.

**Comment by peastman** [comment]
It depends on the type of nonbonded interaction.  If you're using a NonbondedForce, there are a few possibilities for the Coulomb interaction:

- If the nonbonded method is CutoffNonPeriodic or CutoffPeriodic, it uses reaction field, which makes the energy go to zero at the cutoff.
- If it's PME or LJPME, then there is no cutoff.  All interactions are included regardless of distance.

For the LJ interaction:

- If you use LJPME then similarly there is no cutoff.  All interactions are included.
- For other methods, if the switching function is enabled, that causes it to go to zero smoothly at the cutoff.
- If it's disabled then you get a sharp cutoff.

Other forces may handle it differently.  For example, AmoebaMultipleForce only gives the option of PME or no cutoff.  There's no option to discard interactions beyond a cutoff distance.  If you use CustomNonbondedForce, you can implement any interaction you want.  It's up to you whether it goes to zero at the cutoff or not.

**Comment by ksy141** [comment]
This is a very helpful answer, Peter. Thank you very much.

Best,
Siyoung
