### ISSUE TITLE
how to implement gromacs virtual site type 4fdn using LocalCoordinatesSite?

### ISSUE THREAD

**Issue by wenyan4work** [openmm/openmm#4244]
The gromacs 4fdn type is defined here: 
https://manual.gromacs.org/current/reference-manual/functions/interaction-methods.html#from-four-atoms-with-a-fixed-distance-see-separate-fig-s 
This is useful for lone pairs of N atoms in molecules such as Trimethylamine. The coordinate of the vsite depends on 4 atoms.

In OpenMM, we have LocalCoordinatesSite. According to document, it has two constructors, one of them accepts `This constructor assumes the site depends on exactly three other particles.`  The other constructor seems more flexible, but the document is not clear. Does LocalCoordinatesSite support `4fdn`-like vsite definition?

http://docs.openmm.org/latest/api-c++/generated/LocalCoordinatesSite.html?highlight=localcoordinatessite#_CPPv4N6OpenMM20LocalCoordinatesSite20LocalCoordinatesSiteERKNSt6vectorIiEERKNSt6vectorIdEERKNSt6vectorIdEERKNSt6vectorIdEERK4Vec3

Thank you very much!

**Comment by peastman** [comment]
If I understand the definition correctly then yes, I believe it should be possible.  Comparing equation 298 to the [equations defining LocalCoordinatesSite](http://docs.openmm.org/latest/userguide/theory/05_other_features.html#virtual-sites), they match up directly.  $\mathbf{r}\_{ja}$ and $\mathbf{r}_{jb}$ correspond to $\mathbf{dx}$ and $\mathbf{dy}$.  They're a linear combination of the particle positions, just as in LocalCoordinatesSite.  It takes their cross product, so $\mathbf{r}_m$ directly corresponds to $\mathbf{dz}$.  $\mathbf{o}$ is set equal to the position of particle $i$, and the virtual site is placed a distance $c$ along the $z$ axis of the local coordinate system.

**Comment by wenyan4work** [comment]
> If I understand the definition correctly then yes, I believe it should be possible. Comparing equation 298 to the [equations defining LocalCoordinatesSite](http://docs.openmm.org/latest/userguide/theory/05_other_features.html#virtual-sites), they match up directly. rja and rjb correspond to dx and dy. They're a linear combination of the particle positions, just as in LocalCoordinatesSite. It takes their cross product, so rm directly corresponds to dz. o is set equal to the position of particle i, and the virtual site is placed a distance c along the z axis of the local coordinate system.

Really appreciate your quick response. I have implemented the conversion as you have pointed out.
