### ISSUE TITLE
Potential Tools for Calculating Energy Post-Simulation

### ISSUE THREAD

**Issue by Bailyford** [openmm/openmm#4248]
Hi all,
I am currently looking for a tool or method that is able to calculate the total energy of the solute post-simulation. I see this can be tracked during the simulation, but for my project, it would be more convenient to do so after each step. Example 5.4 from the user guide is fairly close, but I would like to be able to specify just the solute and not the total system. The temperature will also not remain constant between steps, thus I would like information on the kinetic energy as well. Does anyone have any recommended tools or methods that may help? 
Thank you!

**Comment by peastman** [comment]
If you want to compute the energy of just the solute, you should create a new System that contains only it.  You can use `Modeller.delete()` to remove everything else from your Topology, then create the new System using the same ForceField you used for the original one.

What exactly do you want to know about the kinetic energy?  StateDataReporter can record the total kinetic energy at regular intervals.  Or do you want to know the kinetic energy of only the solute?  And is this another case where you want to compute it later, not during the simulation?  That's only possible if you have saved the velocities.
