### ISSUE TITLE
question on implicit solvent gbn2 with amber ff99

### ISSUE THREAD

**Issue by rowanwalker96** [openmm/openmm#4252]
Hi there,

This a question about using implict solvent with OpenMM. I am trying to replicate some results from this paper: https://pubs.acs.org/doi/10.1021/acs.jctc.0c00931 where they show that AMBER ff99 parameters in combination with implicit solvent igb8 can perform pretty well in capturing the conformation of polydT.

I realise there have been some questions on this before: #3708, #3104 but I am still a little confused.

My approach was to generate rst7 and prmtop files with tleap specifying mbondi3 radii (file attached), then loading with AmberTopFile into openmm:
[tleap.txt](https://github.com/openmm/openmm/files/12767790/tleap.txt)

```
prmtop = AmberPrmtopFile('dna.prmtop')
inpcrd = AmberInpcrdFile('dna.rst7')
system = prmtop.createSystem(nonbondedMethod=NoCutoff,constraints=HBonds,implicitSolvent=app.GBn2,implicitSolventSaltConc=0.1*un.moles/un.liter) 
```

My simulations result in globular conformations of the dna which do not at all resemble the conformations in the paper which are highly extended. I contacted the author who said that the nucleic acid parameters ought to be used. My understanding reading #2391 is that they are since my residues are nucleic residues 'DT'.

I seem to be getting similar results if using Amber's pmemd. I just wanted to make sure I hadn't made any obvious mistakes with my OpenMM implementation. Thanks.

**Comment by peastman** [comment]
I'm not an Amber user, so I can't comment on your tleap script.  Your OpenMM code tells it to use GBn2, which I believe is igb 8.

**Comment by rowanwalker96** [comment]
Ok, I believe I could also achieve the same thing by just using OpenMM?

`pdb = PDBFile('amber.pdb')
forcefield = ForceField('amber99sb.xml', 'implicit/gbn2.xml')
system = forcefield.createSystem(pdb.topology, nonbondedMethod=NoCutoff, constraints=HBonds)
`

My pdb file is a poly DT molecule. Will OpenMM automatically assign the correct mbondi3 atomic radii and use the nucleic acid parameters (#2391)?

**Comment by sef43** [comment]
Also check you are setting the `implicitSolventKappa` value correctly. Its definition has an extra 0.73 factor compared to normal when computing it from the salt concentration: http://docs.openmm.org/latest/userguide/application/02_running_sims.html#implicit-solvent

You can see here this is done automatically if you use `prmtop.createSystem( .. implicitSolventSaltConc= ...)`:
https://github.com/openmm/openmm/blob/432b5838f6a045882adfe2c4b3941bd65d6f0f12/wrappers/python/openmm/app/amberprmtopfile.py#L278-L291

**Comment by rowanwalker96** [comment]
Thanks both, energy is the same which is a good sign.

**Comment by peastman** [comment]
Great!  It sounds like it works then.
