### ISSUE TITLE
no registered Platform called "OpenCL"

### ISSUE THREAD

**Issue by GuShaocheng** [openmm/openmm#4256]
Hi,

My code is running on Ubuntu 22.04. I module load cuda/11.2. Then opemm.py gave such error:

openmm.OpenMMException: There is no registered Platform called "OpenCL"
File "xxx/lib/python3.9/site-packages/openmm/openmm.py", line 11790, in getPlatformByName

I checked libOpenCL.so is actually in side lib folder under cuda/11.2.

Is there any cue to solve the issue?

Thanks!

**Comment by peastman** [comment]
That suggests the plugin didn't load properly.  Try this:

```python
from openmm import *
print(Platform.getPluginLoadFailures())
```

That will print out any plugins that didn't load, and hopefully helpful error messages explaining why.  This line will also list all plugins that did get loaded:

```python
print(pluginLoadedLibNames)
```

**Comment by peastman** [comment]
Did you figure out the problem?

**Comment by Vance-Raiti** [comment]
Hello, running into the same issue. When I try the probe you mentioned above (`getPluginLoadFailures()`), it just prints what looks like an empty tuple:

```
[vraiti@gubby-prime openmm]$ python simulatePdb.py
()
Traceback (most recent call last):
  File "/home/vraiti/mdhpc/openmm/simulatePdb.py", line 12, in <module>
    platform = Platform.getPlatform("opencl")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vraiti/.local/lib/python3.12/site-packages/openmm/openmm.py", line 9440, in getPlatform
    return _openmm.Platform_getPlatform(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

It looks like at the very least OpenCL.so.1 is properly loading (from LD_DEBUG=all)
```
       257:     file=/home/vraiti/.local/lib/python3.12/site-packages/OpenMM.libs/lib/plugins/libOpenMMOpenCL.so [0];  dynamically loaded by /home/vraiti/.local/lib/python3.12/site-packages/openmm/../OpenMM.libs/lib/libOpenMM.so [0]
       257:     file=/home/vraiti/.local/lib/python3.12/site-packages/OpenMM.libs/lib/plugins/libOpenMMOpenCL.so [0];  generating link map
       257:       dynamic: 0x00007f7f6e226e40  base: 0x00007f7f6df1b000   size: 0x000000000030f5b8
       257:         entry: 0x00007f7f6df1b000  phdr: 0x00007f7f6df1b040  phnum:                 10
       257:
       257:
       257:     file=libOpenCL.so.1 [0];  needed by /home/vraiti/.local/lib/python3.12/site-packages/OpenMM.libs/lib/plugins/libOpenMMOpenCL.so [0]
       257:     find library=libOpenCL.so.1 [0]; searching
       257:      search cache=/etc/ld.so.cache
       257:       trying file=/lib64/libOpenCL.so.1
       257:
       257:     file=libOpenCL.so.1 [0];  generating link map
       257:       dynamic: 0x00007f7f6df13c48  base: 0x00007f7f6deea000   size: 0x000000000002a620
       257:         entry: 0x00007f7f6deea000  phdr: 0x00007f7f6deea040  phnum:                 12
```

Any idea what's going on?

**Comment by epretti** [comment]
Platform names are case-sensitive; they [should be](http://docs.openmm.org/latest/userguide/application/02_running_sims.html#platforms) one of `"OpenCL"`, `"CUDA"`, `"HIP"`, `"CPU"`, or `"Reference"`, so `"opencl"` won't work.
