### ISSUE TITLE
Constructing a box of water without input pdb?

### ISSUE THREAD

**Issue by andrewsb8** [openmm/openmm#4258]
I'm working on a small project for an undergraduate class which will just include simulations of water. We would utilize Google Collab. To avoid as much confusion as possible with file locations and paths within Google Drive and Colab, I was hoping I could construct a box of water within the python script and without an input pdb or other structure file. Something like the following:

```
pdb = PDBFile("tip3p.pdb")
forcefield = ForceField("amber14-all.xml")
modeller = Modeller(pdb.topology, pdb.positions)
modeller.addSolvent(forcefield, boxSize=Vec3(3, 3, 3)*nanometers, model='tip3p', neutralize=True, negativeIon='Cl-', positiveIon='Na+')
system = forcefield.createSystem(modeller.topology, nonbondedMethod=PME,
        nonbondedCutoff=1*nanometer, constraints=HBonds)
```

Where `tip3p.pdb` could just be the (3 nm)^3 box of waters found [here](https://github.com/openmm/openmm/tree/master/wrappers/python/openmm/app/data). But it does not seem to appear in the path automatically like the inputs for ForceField.

I also tried something like:

```
forcefield = ForceField("amber14-all.xml")
modeller = Modeller()
modeller.addSolvent(forcefield, boxSize=Vec3(3, 3, 3)*nanometers, model='tip3p', neutralize=True, negativeIon='Cl-', positiveIon='Na+')
system = forcefield.createSystem(modeller.topology, nonbondedMethod=PME,
        nonbondedCutoff=1*nanometer, constraints=HBonds)
```

So I would just construct a box of water from an "empty" `Modeller` object. But `Modeller` expects two arguments from an input structure file. I haven't come across a good solution from searches on Google or existing Issues here. So, thanks for any help!

**Comment by peastman** [comment]
You almost have it.  Here's the way to create it:

```python
modeller = Modeller(Topology(), [])
```

That starts with an empty Topology and an empty list of positions.  Then you can call `addSolvent()` to build the water box.

**Comment by andrewsb8** [comment]
Worked great! Thanks so much.
