### ISSUE TITLE
Does openmm supports spherical boundary condition?

### ISSUE THREAD

**Issue by OkKakao** [openmm/openmm#4259]
Hi.

I'm trying to reproduce a paper's calculation.

They utilized spherical boundary condition which is implemented in NAMD.

I already recognizes that custom external force method in openmm can imitate the system described in the paper, however, I want to use spherical boundary condition for the exact calculation.

Is the function implemented in openmm?

Thank you

**Comment by peastman** [comment]
[This example](http://docs.openmm.org/latest/userguide/application/04_advanced_sim_examples.html#applying-an-external-force-to-particles-a-spherical-container) in the user guide shows how to do it.  What NAMD calls "spherical boundary conditions" aren't really boundary conditions in the standard sense.  It's just a harmonic potential to prevent particles from moving too far beyond a certain distance.

**Comment by OkKakao** [comment]
> [This example](http://docs.openmm.org/latest/userguide/application/04_advanced_sim_examples.html#applying-an-external-force-to-particles-a-spherical-container) in the user guide shows how to do it. What NAMD calls "spherical boundary conditions" aren't really boundary conditions in the standard sense. It's just a harmonic potential to prevent particles from moving too far beyond a certain distance.

I thought that it is similar to PBC, which means that the particle re-enters opposite side of virtual spherical wall, when it hits the wall.

Thanks for the explanation!
I'll try that method you've mentioned

**Comment by peastman** [comment]
Here's the [NAMD documentation](https://www.ks.uiuc.edu/Research/namd/2.9/ug/node33.html) about it.
