### ISSUE TITLE
Units of virtual site weights

### ISSUE THREAD

**Issue by mattwthompson** [openmm/openmm#4262]
The [critical term](http://docs.openmm.org/latest/userguide/theory/05_other_features.html?highlight=threeparticleaveragesite#virtual-sites) in `outOfPlaneSite` takes the cross product of two vectors $\vec{r_{12}}$ and $\vec{r_{13}}$, multiplies them through by a weighting factor, and adds that result (say $\vec{r_{cross}} = \vec{r_{12}} \times \vec{r_{13}}$) to a running sum that computes the position of the virtual site. If my understanding of vectors is correct[^1][^2] the units of  $\vec{r_{cross}}$ are distance squared. This would imply that $w_{cross}$ must have units of inverse distance for this term to safely be added to the equation it's defined in. The documentation doesn't necessarily state that the other weight factors are unitless, but I think it's fair for the user to assume this after looking at the simpler equations for the other virtual site types. The [API documentation](http://docs.openmm.org/latest/api-python/generated/openmm.openmm.OutOfPlaneSite.html?highlight=outofplanesite#outofplanesite) for the class doesn't mention that $w_{cross}$ might have units of inverse distance. The [TIP5P](https://github.com/openmm/openmm/blob/8.0.0/wrappers/python/openmm/app/data/tip5p.xml#L14-L15) shipped with OpenMM doesn't include units, but I guess that's to be expected since most (everything?) else is in implicit units.

I came across this while working on something else that benefited from me re-deriving TIP5P parameters in OpenMM's models. I was getting something off by a factor of 10 because the [page I was following](https://docs.lammps.org/Howto_tip5p.html) happened to use Angstroms. When everything internally and externally uses the same units (nanometers for TIP5P) I don't think this would be an issue. I can post my back-of-the-envelope math in its ugly detail if that's useful - I figure nobody here is that much of a masochist.

I realize I could be the only person in the world who cares about this ... I'm posting just as much as a sanity check as an offer to update the documentation to mention this.

[^1]: Mostly that a vector has, or acts like it has, position units. So you can have a particle at a point in space, add a vector to it, and the result is a new point in space. It makes sense to me that the vector 
[^2]: Also that taking the magnitude of a vector preserves its units in some way, or at least the magnitude of a distance vector has the same units (of distance).

**Comment by peastman** [comment]
I believe your understanding is correct.  It would be worth adding a sentence to the documentation, something like, "Note that while w12 and w13 are unitless, wcross has units of inverse distance."

**Comment by peastman** [comment]
Fixed by #4263.
