### ISSUE TITLE
Couldn't find cuda CUB library

### ISSUE THREAD

**Issue by ccccclw** [openmm/openmm#4273]
While building the [MELD](https://github.com/maccallumlab/meld) plugin in OpenMM, the compilation step can be done successfully, but the `make test` on cuda platform failed with 
 
> exception: Error compiling program: default_program(689): catastrophic error: could not open source file "cub/cub.cuh" (no directories in search list)
>   #include <cub/cub.cuh>

Also error after running from python API: 

>   File "/home/program/Meld_cuda12_2023/lib/python3.11/site-packages/Meld-0.6.1-py3.11.egg/meld/runner/openmm_runner.py", line 631, in _create_openmm_simulation
>     return app.Simulation(topology, system, integrator, platform, properties)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/program/Meld_cuda12_2023/lib/python3.11/site-packages/openmm/app/simulation.py", line 103, in __init__
>     self.context = mm.Context(self.system, self.integrator, platform, platformProperties)
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/program/Meld_cuda12_2023/lib/python3.11/site-packages/openmm/openmm.py", line 15887, in __init__
>     this = _openmm.new_Context(*args)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
> openmm.OpenMMException: Error compiling program: default_program(689): catastrophic error: could not open source file "cub/cub.cuh" (no directories in search list)
>   #include <cub/cub.cuh>
>                         ^
> 1 catastrophic error detected in the compilation of "default_program".
> Compilation terminated.
> 
> ----------------------
> 

It appears that the similar issue was discussed before in #3097, could you provide any tips on how to resolve it now? There are a couple of functions in CUB library used [here](https://github.com/maccallumlab/meld/blob/5e7e093f71c5f460ed9aec2e919ee558a80fe126/plugin/platforms/cuda/src/kernels/computeMeld.cu#L6). The problem likely comes from removing nvcc as optional cuda compiler after this [commit](https://github.com/openmm/openmm/blob/10c909dd1c63988bfee4197d8befecb911b792a1/platforms/cuda/src/CudaContext.cpp#L31). 

The env - `cuda/12.2.2  gcc/12.2.0  openmpi/4.1.5  python/3.11  cmake/3.26.4  swig/3.0.8  doxygen/1.8.3.1  netcdf/4.2` with [latest openmm](https://github.com/openmm/openmm/tree/0363c38dc7ba5abc40d5d4c72efbca0718ff09ab).

**Comment by peastman** [comment]
We talked about adding a way to specify an include path to nvrtc, but nothing has been implemented yet.  Since CUB is implemented entirely in headers, what about loading the header yourself and prepending it to the kernel source?  Pass `cubHeader + CudaMeldKernelSources::computeMeld` to `createModule()`.

**Comment by peastman** [comment]
You need to figure out which headers contain the actual code you want to include and prepend those ones.

**Comment by ccccclw** [comment]
We use BlockRadixSort and BlockReduce, and I tried to prepend these two but it couldn't fix as they also requires including other headers in cub, so I guess being able to locate the cub folder is probably the only route if we want to keep using these functions with current openmm.

**Comment by ccccclw** [comment]
Thanks. I tried to do the following after figuring out all headers for CUB functions we need, but it gave similar error of header finding since whichever header file is loaded/added first, the headers needed in it couldn't be located.

>     std::string cubcubHeaderContents = LoadHeaderFile("/home/compilers/cuda/12.2.2/include/cub/cub.cuh");
>     std::string cubblock_reduceHeaderContents = LoadHeaderFile("/home/compilers/cuda/12.2.2/include/cub/block/block_reduce.cuh");
>     std::string cubblock_reduce_rakingHeaderContents = LoadHeaderFile("/home/compilers/cuda/12.2.2/include/cub/block/specializations/block_reduce_raking.cuh");
>     std::string cubblock_reduce_raking_commutative_onlyHeaderContents = LoadHeaderFile("/home/compilers/cuda/12.2.2/include/cub/block/specializations/block_reduce_raking_commutative_only.cuh");
>     std::string cubblock_reduce_warp_reductionsHeaderContents = LoadHeaderFile("/home/compilers/cuda/12.2.2/include/cub/block/specializations/block_reduce_warp_reductions.cuh");
>     std::string cubconfigHeaderContents = LoadHeaderFile("/home/compilers/cuda/12.2.2/include/cub/config.cuh");
>     std::string cubutil_ptxHeaderContents = LoadHeaderFile("/home/compilers/cuda/12.2.2/include/cub/util_ptx.cuh");
>     std::string cubutil_typeHeaderContents = LoadHeaderFile("/home/compilers/cuda/12.2.2/include/cub/util_type.cuh");
>     std::string cubthread_operatorsHeaderContents = LoadHeaderFile("/home/compilers/cuda/12.2.2/include/cub/thread/thread_operators.cuh");
>     std::string cubutil_cpp_dialectHeaderContents = LoadHeaderFile("/home/compilers/cuda/12.2.2/include/cub/util_cpp_dialect.cuh");
>     std::string cubuninitialized_copyHeaderContents = LoadHeaderFile("/home/compilers/cuda/12.2.2/include/cub/detail/uninitialized_copy.cuh");
>     std::string cubutil_archHeaderContents = LoadHeaderFile("/home/compilers/cuda/12.2.2/include/cub/util_arch.cuh");
>     std::string cubutil_compilerHeaderContents = LoadHeaderFile("/home/compilers/cuda/12.2.2/include/cub/util_compiler.cuh");
>     std::string cubutil_deprecatedHeaderContents = LoadHeaderFile("/home/compilers/cuda/12.2.2/include/cub/util_deprecated.cuh");
>     std::string cubutil_macroHeaderContents = LoadHeaderFile("/home/compilers/cuda/12.2.2/include/cub/util_macro.cuh");
>     std::string cubutil_namespaceHeaderContents = LoadHeaderFile("/home/compilers/cuda/12.2.2/include/cub/util_namespace.cuh");
>     std::string cubutil_debugHeaderContents = LoadHeaderFile("/home/compilers/cuda/12.2.2/include/cub/util_debug.cuh");
>     std::string cubwarp_reduceHeaderContents = LoadHeaderFile("/home/compilers/cuda/12.2.2/include/cub/warp/warp_reduce.cuh");
>     std::string cubthread_reduceHeaderContents = LoadHeaderFile("/home/compilers/cuda/12.2.2/include/cub/thread/thread_reduce.cuh");
>     std::string cubtype_traitsHeaderContents = LoadHeaderFile("/home/compilers/cuda/12.2.2/include/cub/detail/type_traits.cuh");
>     std::string cubblock_raking_layoutHeaderContents = LoadHeaderFile("/home/compilers/cuda/12.2.2/include/cub/block/block_raking_layout.cuh");
> 
>     CUmodule module = cu.createModule(cu.replaceStrings(cubconfigHeaderContents
>                                                         + cubblock_reduceHeaderContents 
>                                                         + cubblock_reduce_rakingHeaderContents
>                                                         + cubblock_reduce_raking_commutative_onlyHeaderContents
>                                                         + cubblock_reduce_warp_reductionsHeaderContents
>                                                         + cubutil_ptxHeaderContents
>                                                         + cubutil_typeHeaderContents
>                                                         + cubthread_operatorsHeaderContents
>                                                         + cubutil_cpp_dialectHeaderContents
>                                                         + cubuninitialized_copyHeaderContents
>                                                         + cubutil_archHeaderContents
>                                                         + cubutil_compilerHeaderContents
>                                                         + cubutil_deprecatedHeaderContents
>                                                         + cubutil_macroHeaderContents
>                                                         + cubutil_namespaceHeaderContents
>                                                         + cubutil_debugHeaderContents
>                                                         + cubwarp_reduceHeaderContents
>                                                         + cubthread_reduceHeaderContents
>                                                         + cubtype_traitsHeaderContents
>                                                         + cubblock_raking_layoutHeaderContents
>                                                         + CudaMeldKernelSources::vectorOps + CudaMeldKernelSources::computeMeld, replacements), defines);
>

**Comment by peastman** [comment]
You need to understand a bit about how header files work, and what the preprocessor does.  The preprocessor's job is to modify your source files before they get sent to the compiler.  All the lines starting with `#` are commands to the preprocessor.  They get replaced by something else before the compiler sees the file.

A `#include` command gets replaced by the complete content of whatever file you specify.  If that file itself contains preprocessor commands they get processed recursively, so any `#include` commands in those files also get replaced with the content of further files.

Since nvrtc doesn't know where to find the CUB headers, your kernel source can't contain any `#include` that refers to one.  You need to replace them with the proper source code (not including any further `#include` commands).  You could do that manually, selecting the relevant code definitions and putting them into your file.  Or you could do it automatically by running `cpp` (the C preprocessor) on your source file as part of your build process.

**Comment by ccccclw** [comment]
Thanks a lot @peastman ! Since it's looking for cuda header file, cpp couldn't find them, I tried `nvcc -E` to preprocess it and it can generate output definitions for the header we need. Btw, before I tried to add them in the `createModule`, `#include <cub/cub.cuh>` didn't throw error now, which surprised me as nothing changed including build process, os, compiler version, etc.., and I was expecting the nvrtc would still cause the issue, not sure why it works.

**Comment by ccccclw** [comment]
Yes, I will go ahead closing it. Thanks for your help!
