### ISSUE TITLE
Heme protein simulations with OpenMM 8.0 do not behave as in OpenMM 7.4-7.7

### ISSUE THREAD

**Issue by JoaquinTamargo** [openmm/openmm#4275]
Dear all OpenMM community,

Thank you all for reaching out to try to find a way around the issue I am having. It is my first time posting an issue report and I hope to be clear enough. 

I am running a MD simulation of a **heme protein** system, for which I have created topology (prmtop) and coordinate (prmcrd) files with AmberTools23, using parameters files that we have previously developed at our lab. MD calculations using OpenMM 7.4.5 and 7.7 versions were succesful. However, using OpenMM 8.0, I have encountered the following issue:

`Traceback (most recent call last):`
 ` File "XXX/run_openmm_simulation_Cc_WT.py", line 71, in <module>
    simulation.step(steps)`
`  File "XXX/apps/spack/opt/spack/linux-rocky8-x86_64/gcc-13.1.0/anaconda3-2022.10-pg67khif5b75ifpje2yftbg2scuqreml/envs/openmm/lib/python3.11/site-packages/openmm/app/simulation.py", line 141, in step
    self._simulate(endStep=self.currentStep+steps)`
`  File "XXX/apps/spack/opt/spack/linux-rocky8-x86_64/gcc-13.1.0/anaconda3-2022.10-pg67khif5b75ifpje2yftbg2scuqreml/envs/openmm/lib/python3.11/site-packages/openmm/app/simulation.py", line 206, in _simulate
    self.integrator.step(10) # Only take 10 steps at a time, to give Python more chances to respond to a control-c.
    ^^^^^^^^^^^^^^^^^^^^^^^^`
`  File "XXX/spack/opt/spack/linux-rocky8-x86_64/gcc-13.1.0/anaconda3-2022.10-pg67khif5b75ifpje2yftbg2scuqreml/envs/openmm/lib/python3.11/site-packages/openmm/openmm.py", line 14755, in step
    return _openmm.LangevinIntegrator_step(self, steps)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`
`openmm.OpenMMException: Particle coordinate is NaN.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#nan`

I used smaller integration times (0.0001 ps), and by checking the trajectories, I could see that the bond of 4 meso-protons of the heme group (i.e., 4 protons that are in the vecinity of the heme iron) was lost, and these protons moved towards the edges of the water box. In some cases, the bond was not broken although the protons still moved away from their original position in the prmtop and prmcrd, which may have caused large forces that lead to the error.

Using the very same input files and MD parameters in earlier versions of OpenMM (i.e., OpenMM 7.4.5) does not lead to that error, and protons behave normally; they do not break free from the heme moeity. 

I have tested the simulations in CPU and GPUs (CUDA, OpenCL) platforms, but it does not make any difference. The issue might therefore be due to a change in the version, but I do not know exactly what could be wrong. Do you have any clue about what could be happening here? I did not find any issue like this in the forums.

I am attaching the input files (I have added a .txt extension so to upload them).

[WT_prmtop.txt](https://github.com/openmm/openmm/files/13004322/WT_prmtop.txt)
[WT_prmcrd.txt](https://github.com/openmm/openmm/files/13004315/WT_prmcrd.txt)
[run_openmm_simulation_WT.txt](https://github.com/openmm/openmm/files/13004311/run_openmm_simulation_WT.txt)

Best,
Joaquín

**Comment by peastman** [comment]
I think there's something wrong in the element specifications for your heme group.  I first notice this in the output PDB file:

```
HETATM  320 HV2Y HEM A  18      36.482  24.291  31.384  1.00  0.00           H  
HETATM  321 C4B  HEM A  18      33.864  25.245  30.195  1.00  0.00          EP  
HETATM  322 CHC  HEM A  18      34.183  23.998  29.572  1.00  0.00          EP  
HETATM  323  HAM HEM A  18      34.794  23.881  29.325  1.00  0.00           H  
HETATM  324 C1C  HEM A  18      33.286  23.024  29.226  1.00  0.00          EP  
HETATM  325 NC   HEM A  18      31.939  22.988  29.468  1.00  0.00          EP  
HETATM  326 C2C  HEM A  18      33.637  21.775  28.621  1.00  0.00          EP  
HETATM  327  CMC HEM A  18      35.011  21.269  28.310  1.00  0.00           C  
HETATM  328 HM31 HEM A  18      35.764  22.002  28.601  1.00  0.00           H  
```

Notice all the lines with `EP` in the last column.  That stands for "extra particle" and indicates it isn't a real atom.  Tracing it back to your prmtop file, lots of atoms have -1 in the `ATOMIC_NUMBER` section:

```
       6       1       7       6       1      -1       7      -1      -1       6
       1       1       6       1       1       6       8       8      -1       6
       1       1       1      -1      -1       1      -1      -1      -1       6
       1       1       1      -1       6       1       6       1       1       1
```

This prevents OpenMM from properly adding constraints to some of the hydrogens.

**Comment by JoaquinTamargo** [comment]
I appreciate your kind answer @peastman. I directly changed the -1 values to 6 or 1 in the prmtop , and the MD works smoothly, with no such weird behavior.

I will double check the parameters to see if there is any reason for indicating these atoms to be "extra particle". Super interesting observation, thank you a lot!
