### ISSUE TITLE
How is openmm licensed?  (confused)

### ISSUE THREAD

**Issue by KirkDCO** [openmm/openmm#4278]
I've seen a couple of issues regarding how openmm is licensed, but I'm a bit confused by different sources of information.

I see here (http://docs.openmm.org/latest/userguide/library/01_introduction.html#license) that the MIT and LGPL licenses appear to cover openmm and any libraries that it uses.  It refers to the licenses directory (https://github.com/openmm/openmm/tree/master/docs-source/licenses) where I see a licenses.txt file with most MIT or BSD types of licenses, the LGPL, but also a GPL-3 license.  I don't see where the GPL-3 license applies, however.  There was also in issue regarding the FFTW libraries having a GPL license (https://github.com/openmm/openmm/issues/3171), but that seems outside openmm itself.

Where can I find more specific details of which licenses apply to which portions of openmm?

**Comment by peastman** [comment]
The paragraph you linked to describes which parts are covered by each license.  The CUDA and OpenCL platforms are LGPL.  Everything else we wrote (the public API, the Reference and CPU platforms, all the Python parts) are MIT.  We use some third party libraries that are covered by other licenses as described in the licenses.txt file.

What part is not clear?

**Comment by KirkDCO** [comment]
Thanks for the quick response.

I'm unclear on what is covered by GPL-3.  As you mentioned, MIT and LGPL seem to cover everything  and are the only two licenses mentioned in the paragraph.  GPL-3 is included in the licenses folder, but I'm not able to find what portion is GPL-3 licensed.  (As I mentioned, there was a discussion around FFTW libraries, but those are not distributed with openmm.)

**Comment by peastman** [comment]
Nothing is covered by GPL.  That file is there because LGPL incorporates it by reference.  Look at the LGPL file and you'll see what I mean.

**Comment by KirkDCO** [comment]
Thank you for that explanation.  I hadn't considered LGPL's reference to it.
