### ISSUE TITLE
Diffusion coefficient of water models calculated by OpenMM is 20% lower than literature values

### ISSUE THREAD

**Issue by KingOfChuXuan** [openmm/openmm#4280]
Hello, 

I am using OpenMM 8.1 beta version to calculate the diffusion coefficient of the mW water model. I found that my results (about 5.1e-5cm²/s) are always 20% lower than the values (6.4e-5cm²/s) reported in the literature (Chan H, Cherukara M J, Narayanan B, et al. Machine learning coarse grained models for water[J]. Nature communications, 2019, 10(1): 379.).

I simulated the system at 1 atm and 298 K, and calculated the diffusion coefficient by dividing the slope of the MSD vs time curve by 6.
My co-worker used Lammps to simulate the same system under the same conditions, and got the diffusion coefficient consistent with the literature.
I tried adding/removing removeCMMotion, increasing the equilibration time by ten times, and reducing the integration step by half, but none of them worked.
I also tried calculating ML-mW, tip3p (with corresponding simulation parameters such as integration step, cutoff radius, etc. adjusted according to the model), and the diffusion coefficient error was also 20%. It seems that for different water models (at least these three water models), the ratio of the theoretical values in the literature to the results calculated by my code is the same.

I wonder if there is something wrong with my code or if there is a bug in OpenMM. Any suggestions or comments would be appreciated. Thank you very much.

Here is my code:

```
from openmm import *
from openmm.app import *
from openmm.unit import *
import pandas as pd
import numpy as np
from scipy.stats import linregress

class MSDReporter:
    def __init__(self, interval, simulation, dt):
        self.interval = interval
        state0 = simulation.context.getState(getPositions=True, enforcePeriodicBox=False)
        self.x0 = state0.getPositions(asNumpy=True).value_in_unit(centimeter)
        self.dt = dt.value_in_unit(second)
        self.label = dict(Time=[], MSD=[])

    def describeNextReport(self, simulation):
        steps = self.interval - simulation.currentStep % self.interval
        return (steps, True, False, False, False, False)

    def report(self, simulation, state):
        x = state.getPositions(asNumpy=True).value_in_unit(centimeter)
        msd = np.mean(np.linalg.norm((x - self.x0), axis=1) ** 2)
        time = state.getStepCount() * self.dt
        self.label['Time'].append(time)
        self.label['MSD'].append(msd)
        
# Input Files

pdb = PDBFile('mW.pdb')
forcefield = ForceField('mW.xml')

# System Configuration

nonbondedMethod = PME
nonbondedCutoff = 0.43*nanometers
constraints = None
rigidWater = False

# Integration Options

dt = 0.005*picoseconds
temperature = 298*kelvin
friction = 1.0/picosecond
pressure = 1.0*bar
barostatInterval = 25

# Simulation Options

steps = 600000
equilibrationSteps = 1000
platform = Platform.getPlatformByName('CUDA')
platformProperties = {'Precision': 'single'}
platformProperties["DeviceIndex"] = "0"
dcdReporter = DCDReporter('trajectory.dcd', 1000, enforcePeriodicBox=False)
dataReporter = StateDataReporter('log.txt', 1000, totalSteps=steps, remainingTime=True,
    step=True, speed=True, progress=True, potentialEnergy=True, temperature=True, density=True, separator='\t')

# Prepare the Simulation

print('Building system...')
topology = pdb.topology
positions = pdb.positions
system = forcefield.createSystem(topology, nonbondedMethod=nonbondedMethod, nonbondedCutoff=nonbondedCutoff,
                                 constraints=constraints, rigidWater=rigidWater, removeCMMotion=False)
integrator = LangevinMiddleIntegrator(temperature, friction, dt)
simulation = Simulation(topology, system, integrator, platform, platformProperties)
simulation.context.setPositions(positions)

# Minimize and Equilibrate

print('Performing energy minimization...')
simulation.minimizeEnergy()
print('Equilibrating...')
simulation.context.setVelocitiesToTemperature(temperature)
simulation.step(equilibrationSteps)
system.addForce(MonteCarloBarostat(pressure, temperature, barostatInterval))
simulation.context.reinitialize(preserveState=True)
simulation.step(equilibrationSteps)

# Simulate

print('Simulating...')
msdReporter = MSDReporter(100, simulation, dt)
simulation.reporters.append(dcdReporter)
simulation.reporters.append(dataReporter)
simulation.reporters.append(msdReporter)
simulation.currentStep = 0

simulation.step(steps)

print('done')
df = pd.DataFrame(msdReporter.label)
linear_model = linregress(df['Time'], df['MSD'])
slope = linear_model.slope
D = slope / 6
print(D)
```

**Comment by KingOfChuXuan** [comment]
[diffusion_coefﬁcient.zip](https://github.com/openmm/openmm/files/13068009/diffusion_coef.cient.zip)

**Comment by RaulPPelaez** [comment]
Could you post an image/file of the MSD curve you are getting? Thanks

**Comment by peastman** [comment]
> nonbondedCutoff = 0.43*nanometers

Do you really mean that?  That's a tiny cutoff.  You're not going to get realistic water properties if you ignore all interactions beyond 4.3 A.  And while you specify `nonbondedMethod = PME`, that really just means a sharp cutoff since your force field doesn't have any forces that use PME.

**Comment by KingOfChuXuan** [comment]
> Could you post an image/file of the MSD curve you are getting? Thanks

Sure, here is the figure:
![mW](https://github.com/openmm/openmm/assets/146178267/d30990fa-b8ae-44dd-8ba1-36693dbab1a6)

Please note that if you are using OpenMM version 8.0 or earlier, the MSD curve under NPT will have problems and will no longer be a straight line.

**Comment by KingOfChuXuan** [comment]
> > nonbondedCutoff = 0.43*nanometers
> 
> Do you really mean that? 

Yes, because the mW model is a coarse-grained water model such that it has only one oxygen atom, and its cutoff radius should be equal to aσ, which is 0.43nm.

> And while you specify nonbondedMethod = PME, that really just means a sharp cutoff since your force field doesn't have any forces that use PME.

This is also one of my confusions. For CustomNonbondedForce, there is no way to use PME, right? So what method should be used?

As I said before, I also got similar conclusions about tip3p. This is my code and image for tip3p. The result I got (4.32) is still nearly 20% less than the result (5.2) in the literature.

```
from openmm import *
from openmm.app import *
from openmm.unit import *
import pandas as pd
import numpy as np
from scipy.stats import linregress
import matplotlib.pyplot as plt

class MSDReporter:
    def __init__(self, interval, simulation, dt):
        self.interval = interval
        atoms = list(simulation.topology.atoms())
        self.ids = [atoms.index(atom) for atom in atoms if atom.element == Element.getBySymbol('O')]
        state0 = simulation.context.getState(getPositions=True, enforcePeriodicBox=False)
        self.x0 = state0.getPositions(asNumpy=True).value_in_unit(centimeter)[self.ids]
        self.dt = dt.value_in_unit(second)
        self.label = dict(Time=[], MSD=[])

    def describeNextReport(self, simulation):
        steps = self.interval - simulation.currentStep % self.interval
        return (steps, True, False, False, False, False)

    def report(self, simulation, state):
        x = state.getPositions(asNumpy=True).value_in_unit(centimeter)[self.ids]
        msd = np.mean(np.linalg.norm((x - self.x0), axis=1) ** 2)
        time = state.getStepCount() * self.dt
        self.label['Time'].append(time)
        self.label['MSD'].append(msd)
        
# Input Files

pdb = PDBFile('/home/jiangxuan/OpenMM/app/data/tip3p.pdb')
forcefield = ForceField('/home/jiangxuan/OpenMM/app/data/tip3p.xml')

# System Configuration

nonbondedMethod = PME
nonbondedCutoff = 0.9*nanometers
ewaldErrorTolerance = 0.0005
constraints = HBonds
rigidWater = True

# Integration Options

dt = 0.002*picoseconds
temperature = 298*kelvin
friction = 1.0/picosecond
pressure = 1.0*bar
barostatInterval = 25

# Simulation Options

steps = 1500000
equilibrationSteps = 2500
platform = Platform.getPlatformByName('CUDA')
platformProperties = {'Precision': 'single'}
platformProperties["DeviceIndex"] = "0"
dcdReporter = DCDReporter('trajectory.dcd', 1000, enforcePeriodicBox=False)
dataReporter = StateDataReporter('log.txt', 1000, totalSteps=steps, remainingTime=True,
    step=True, speed=True, progress=True, potentialEnergy=True, temperature=True, density=True, separator='\t')

# Prepare the Simulation

print('Building system...')
topology = pdb.topology
positions = pdb.positions
system = forcefield.createSystem(topology, nonbondedMethod=nonbondedMethod, nonbondedCutoff=nonbondedCutoff,
                                 constraints=constraints, rigidWater=rigidWater, removeCMMotion=False,
                                 ewaldErrorTolerance=ewaldErrorTolerance)
integrator = LangevinMiddleIntegrator(temperature, friction, dt)
simulation = Simulation(topology, system, integrator, platform, platformProperties)
simulation.context.setPositions(positions)

# Minimize and Equilibrate

print('Performing energy minimization...')
simulation.minimizeEnergy()
print('Equilibrating...')
simulation.context.setVelocitiesToTemperature(temperature)
simulation.step(equilibrationSteps)
system.addForce(MonteCarloBarostat(pressure, temperature, barostatInterval))
simulation.context.reinitialize(preserveState=True)
simulation.step(equilibrationSteps)

# Simulate

print('Simulating...')
msdReporter = MSDReporter(100, simulation, dt)
simulation.reporters.append(dcdReporter)
simulation.reporters.append(dataReporter)
simulation.reporters.append(msdReporter)
simulation.currentStep = 0
simulation.step(steps)

print('done')
df = pd.DataFrame(msdReporter.label)
linear_model = linregress(df['Time'], df['MSD'])
slope = linear_model.slope
D = slope / 6
print(D)
plt.plot(df['Time'], df['MSD'])
plt.xlabel('Time/s')
plt.ylabel('MSD/cm²')
plt.show()
```

![tip3p](https://github.com/openmm/openmm/assets/146178267/ed3951f9-4eae-4afd-a36c-126be81d2d16)

**Comment by AnthoniAlcaraz** [comment]
I think TIP3P needs the hydrodynamic correction, it depends on viscosity, simulation cell, etcetera and this term is almost 20% of the final value.

**Comment by KingOfChuXuan** [comment]
> I think TIP3P needs the hydrodynamic correction, it depends on viscosity, simulation cell, etcetera and this term is almost 20% of the final value.

Thank you for your reply, but how can I use it in OpenMM? And do other TIP series models also need this modification?

**Comment by z-gong** [comment]
You are using a Langevin integrator, which damps the dynamics.
You could try the NoseHooverIntegrator, and see if the underestimation persists.

**Comment by KingOfChuXuan** [comment]
> You are using a Langevin integrator, which damps the dynamics. You could try the NoseHooverIntegrator, and see if the underestimation persists.

Thank you for your reply, but the result is quite strange.
The result is 4.1e-3cm²/s, nearly a hundred times bigger than the theoretical values(6.4e-5cm²/s).
Here is my code, could you please help me to check it? Thank you very much!
```
from openmm import *
from openmm.app import *
from openmm.unit import *
import pandas as pd
import numpy as np
from scipy.stats import linregress
import matplotlib.pyplot as plt

class MSDReporter:
    def __init__(self, interval, simulation, dt):
        self.interval = interval
        state0 = simulation.context.getState(getPositions=True, enforcePeriodicBox=False)
        self.x0 = state0.getPositions(asNumpy=True).value_in_unit(centimeter)
        self.dt = dt.value_in_unit(second)
        self.label = dict(Time=[], MSD=[])

    def describeNextReport(self, simulation):
        steps = self.interval - simulation.currentStep % self.interval
        return (steps, True, False, False, False, False)

    def report(self, simulation, state):
        x = state.getPositions(asNumpy=True).value_in_unit(centimeter)
        msd = np.mean(np.linalg.norm((x - self.x0), axis=1) ** 2)
        time = state.getStepCount() * self.dt
        self.label['Time'].append(time)
        self.label['MSD'].append(msd)
        
# Input Files

pdb = PDBFile('diffusion_coefﬁcient/mW.pdb')
forcefield = ForceField('diffusion_coefﬁcient/mW.xml')

# System Configuration

#nonbondedMethod = PME
nonbondedMethod = CutoffPeriodic
nonbondedCutoff = 0.43*nanometers
constraints = None
rigidWater = False

# Integration Options

dt = 0.005*picoseconds
temperature = 298*kelvin
friction = 1.0/picosecond
pressure = 1.0*bar
barostatInterval = 25

# Simulation Options

times = 13 * nanosecond
steps = round(times / dt)
equilibrationSteps = 10000
platform = Platform.getPlatformByName('CUDA')
platformProperties = {'Precision': 'single'}
platformProperties["DeviceIndex"] = "0"
dcdReporter = DCDReporter('trajectory(mw_unwrap).dcd', 1000, enforcePeriodicBox=False)
dataReporter = StateDataReporter('log(mw).txt', 1000, totalSteps=steps, remainingTime=True,
    step=True, speed=True, progress=True, potentialEnergy=True, temperature=True, density=True, separator='\t')

# Prepare the Simulation

print('Building system...')
topology = pdb.topology
positions = pdb.positions
system = forcefield.createSystem(topology, nonbondedMethod=nonbondedMethod, nonbondedCutoff=nonbondedCutoff,
                                 constraints=constraints, rigidWater=rigidWater, removeCMMotion=False)
integrator = NoseHooverIntegrator(temperature, friction, dt)
simulation = Simulation(topology, system, integrator, platform, platformProperties)
simulation.context.setPositions(positions)

# Minimize and Equilibrate

print('Performing energy minimization...')
simulation.minimizeEnergy()
print('Equilibrating...')
simulation.context.setVelocitiesToTemperature(temperature)
simulation.step(equilibrationSteps)
system.addForce(MonteCarloBarostat(pressure, temperature, barostatInterval))
simulation.context.reinitialize(preserveState=True)
simulation.step(equilibrationSteps)



# Simulate

print('Simulating...')
msdReporter = MSDReporter(100, simulation, dt)
simulation.reporters.append(dcdReporter)
simulation.reporters.append(dataReporter)
simulation.reporters.append(msdReporter)
simulation.currentStep = 0
simulation.step(steps)

print('done')
df = pd.DataFrame(msdReporter.label)
linear_model = linregress(df['Time'], df['MSD'])
slope = linear_model.slope
D = slope / 6
print(D)
plt.plot(df['Time'], df['MSD'])
plt.xlabel('Time/s')
plt.ylabel('MSD/cm²')
plt.show()
```
Images of MSD versus time are also here, also strange:
![MSD](https://github.com/openmm/openmm/assets/146178267/37dbe065-a1d5-448c-b27a-a85409037c48)

**Comment by KingOfChuXuan** [comment]
I finally get the right result by using NoseHooverIntegrator and  turning 
```system = forcefield.createSystem(topology, nonbondedMethod=nonbondedMethod, nonbondedCutoff=nonbondedCutoff, constraints=constraints, rigidWater=rigidWater, removeCMMotion=False)```
to
```system = forcefield.createSystem(topology, nonbondedMethod=nonbondedMethod, nonbondedCutoff=nonbondedCutoff, constraints=constraints, rigidWater=rigidWater, removeCMMotion=True)```
But why?

**Comment by KingOfChuXuan** [comment]
I see, so is it necessary to force a remover to be added to the system when using weak-coupling thermostats? In addition, what is the frequency of remover generally based on?

**Comment by peastman** [comment]
It's usually applied every step.  It's inexpensive enough that there's no reason not to.

What happens if you use the Langevin integrator but with a smaller friction coefficient, maybe 0.1/picosecond?

**Comment by KingOfChuXuan** [comment]
> It's usually applied every step. It's inexpensive enough that there's no reason not to.

I removed the remover before because of https://github.com/openmm/openmm/issues/4254#issuecomment-1743301758 , so it's no need to remove it, right?

> What happens if you use the Langevin integrator but with a smaller friction coefficient, maybe 0.1/picosecond?

I get 6.07e-5cm²/s which is more accurate but still not accurate enough as I get 6.52e-5cm²/s via NoseHooverIntegrator , but this takes me more than twice as long.

Besides, is there a way to use PME while using custom forces?

**Comment by peastman** [comment]
> Besides, is there a way to use PME while using custom forces?

The math for PME has only been worked out for a few specific cases, I think only functions of the form $q_1 q_2 / r^n$ where $n$ is a positive integer.  It can't be applied to arbitrary functional forms.

**Comment by KingOfChuXuan** [comment]
Oh I see. I'll read the original text of PME later. Thank you very much for your reply!

**Comment by peastman** [comment]
I followed up a bit on this issue to make sure I understood what was happening, and that I could get consistent results with the Langevin integrator.  Simulating a box of TIP3P water with a 1/ps friction coefficient, I get 4.7 in your units.  Reducing the friction to 0.1/ps increases the diffusion coefficient to 5.4.  Further reducing the friction to 0.01/ps has no further effect on the result, so it seems to have reached a point where the thermostat isn't significantly affecting the diffusion.

For comparison, I also tried TIP3P-FB.  It gave a much lower value, 2.0.  It's also much closer to the experimental value 2.3.  TIP3P is known to produce water that has too little structure, and consequently too fast diffusion.

Here is my code.

```python
from openmm import *
from openmm.app import *
from openmm.unit import *
import numpy as np

ff = ForceField('tip3p.xml')
modeller = Modeller(Topology(), [])
modeller.addSolvent(ff, boxSize=Vec3(3, 3, 3))
system = ff.createSystem(modeller.topology, nonbondedMethod=PME, nonbondedCutoff=0.9, rigidWater=True, removeCMMotion=True)
integrator = LangevinMiddleIntegrator(300*kelvin, 1.0/picosecond, 0.004*picoseconds)
simulation = Simulation(modeller.topology, system, integrator)
simulation.context.setPositions(modeller.positions)
oxygens = [atom.index for atom in modeller.topology.atoms() if atom.element == element.oxygen]
print('minimize')
simulation.minimizeEnergy()
print('equilibrate')
simulation.context.setVelocitiesToTemperature(300*kelvin)
simulation.step(1000)
simulation.context.setVelocitiesToTemperature(300*kelvin)
print('simulate')
r0 = simulation.context.getState(getPositions=True).getPositions(asNumpy=True)[oxygens].value_in_unit(nanometer)
integrator.setFriction(0.1/picosecond)
for i in range(100):
    simulation.step(2500)
    state = simulation.context.getState(getPositions=True)
    r = state.getPositions(asNumpy=True)[oxygens].value_in_unit(nanometer)
    t = state.getTime().value_in_unit(picosecond)
    d = r-r0
    d2 = np.average(np.sum(d**2, axis=1))
    print(t, d2, d2/(6*t))
```

**Comment by KingOfChuXuan** [comment]
>Simulating a box of TIP3P water with a 1/ps friction coefficient, I get 4.7 in your units. Reducing the friction to 0.1/ps increases the diffusion coefficient to 5.4. 

According to the literature, the diffusion coefficient at 298K is 5.2, so does it mean if I want to get consistent results with the Langevin integrator, the friction coefficient need to be 0.1/ps rather than 1/ps?
If this is the case, when should I use 0.1/ps and when should I use 1/ps?
Thank you for your reply!

**Comment by peastman** [comment]
I found a bunch of different values for it in different sources, ranging from 5.2 to over 6.  It seems to depend on a lot of details: how long range interactions were handled, whether it's done at constant volume or pressure, etc.  What source did you get your number from?

The best friction coefficient depends on what you're simulating and what you want to learn.  If you want accurate values for dynamical quantities like diffusion, you should use a small friction value.  If you want to sample equilibrium properties, a value around 1/ps generally gives slightly faster convergence.

**Comment by KingOfChuXuan** [comment]
> I found a bunch of different values for it in different sources, ranging from 5.2 to over 6.

Even within this range, 4.7 isn't a correct number, is it? But it really depends on lots of details.



> If you want accurate values for dynamical quantities like diffusion, you should use a small friction value. If you want to sample equilibrium properties, a value around 1/ps generally gives slightly faster convergence.

I think I have got this, thank you for your reply!

**Comment by peastman** [comment]
> Even within this range, 4.7 isn't a correct number, is it?

Right.  That's from using too much friction.  When I reduced the friction to 0.1/ps, the diffusion coefficient increased to 5.4.

**Comment by KingOfChuXuan** [comment]
> If you want accurate values for dynamical quantities like diffusion, you should use a small friction value. If you want to sample equilibrium properties, a value around 1/ps generally gives slightly faster convergence.

Yes, so I think we can finally draw this conclusion.
Thank you very much for your patient answer！
