### ISSUE TITLE
Efficient way to update many particle charges every timestep

### ISSUE THREAD

**Issue by bbye98** [openmm/openmm#4283]
Hello!

I would like to simulate electrolytes placed between two planar walls and apply a potential difference between the two surfaces by assigning charges to the particles that make up the walls. However, the potential difference should vary with time in some sort of oscillatory nature, i.e., dV = sin(t). This would necessitate updating the charges of all wall particles every (or every few) timesteps. I believe this is an extremely slow process. Is there a more efficient way to implement this?

(To continue using the 3D PME method to evaluate electrostatics for this pseudo-2D slab system, I have to use the Yeh-Berkowitz slab correction, which essentially removes the interactions between the real cell and all the image cells in the z-direction. Normally, I would use a CustomExternalForce to add an electric field and change the global parameter E for the electric field magnitude in each timestep. However, this approach is incompatible with the Yeh-Berkowitz slab correction since the surface charge is not accounted for when calculating the dipole moment to subtract.)

**Comment by peastman** [comment]
You can do this with parameter offsets.  NonbondedForce lets you define a global parameter with `addGlobalParameter()` and specify that the charges on certain atoms should be modified based on it with `addParticleParameterOffset()`.  Changing a global parameter is inexpensive.  See [the API docs](http://docs.openmm.org/latest/api-c++/generated/NonbondedForce.html) for details.

**Comment by bbye98** [comment]
Apologies for the late response!

I believe this is exactly what I'm looking for. However, how would I set a global parameter so that I can use it when registering my particles to a `CustomNonbondedForce`?

For example, I typically follow this procedure when setting up my systems:

1. Create a `CustomNonbondedForce` that accepts a per-particle parameter `q` for charge.
2. Register the particles to the `CustomNonbondedForce` using a loop, in which I specify the `q` for each given atom.
3. Create the integrator, system, etc.
4. Register the force field to the system.

In step 2, I use `CustomNonbondedForce.addParticle((1,))`, for example, to register a cation. Of course, I can use `CustomNonbondedForce.addGlobalParameter("LEFT_WALL_CHARGE", 0.5)` to add the global parameter specifying the left wall particle's charges, but how do I pass `LEFT_WALL_CHARGE` to `CustomNonbondedForce.addParticle()`? Is it as simple as just calling `CustomNonbondedForce.addParticle(("LEFT_WALL_CHARGE",))`?

**Comment by peastman** [comment]
If you're using a custom force, you can compute the energy however you want using functions of both per-particle and global parameters.  In your case you might define per-particle parameters called `q` and `wallScale`.  You would set `wallScale` to 1 for particles on the left wall, -1 for particles on the right wall, and 0 for others.  The actual charge on a particle would be `q+wallScale*LEFT_WALL_CHARGE`.

**Comment by bbye98** [comment]
Makes perfect sense; not sure how I didn't think of this. I will give this a shot. Thank you!
