### ISSUE TITLE
CUDA tests not run in CI

### ISSUE THREAD

**Issue by bdenhollander** [openmm/openmm#4286]
For the most recent merge into master, none of the following jobs ran any tests with CUDA in the name.
[Linux CUDA 10.0](https://github.com/openmm/openmm/actions/runs/6660586432/job/18101969504#step:17:40)
[Linux CUDA 11.2](https://github.com/openmm/openmm/actions/runs/6660586432/job/18101969759#step:17:43)
[Windows CUDA 11.2 Python 3.11](https://github.com/openmm/openmm/actions/runs/6660586432/job/18101969265#step:11:36)
Older builds no longer have logs but here's a CI run from [3 months ago](https://github.com/openmm/openmm/actions/runs/5721183708) that didn't run CUDA tests as well. Is there a reason for this or did it quietly stop working?

**Comment by peastman** [comment]
Those just test building the CUDA platform.  They can't run the tests because Github doesn't provide runners with GPUs.  They're tested on Jenkins instead.

**Comment by bdenhollander** [comment]
That makes sense. I saw AMD OpenCL running successfully and didn't think of the GPU hardware requirement. Looking more closely, I see that it's AMD's OpenCL CPU implementation running on an Intel CPU.
