### ISSUE TITLE
About benchmark test meaning

### ISSUE THREAD

**Issue by yichez16** [openmm/openmm#4287]
Hi,

I found the benchmark.py help test several test examples: 'gbsa', 'rf', 'pme', 'apoa1rf', 'apoa1pme', 'apoa1ljpme', 'amoebagk', 'amoebapme', 'amber20-dhfr', 'amber20-cellulose', 'amber20-stmv.
Could I get information/meaning or related paper about each test for benchmark.py?
Thanks!

**Comment by peastman** [comment]
You can find descriptions of the benchmark systems at https://openmm.org/benchmarks.

**Comment by yichez16** [comment]
Thanks for your information. 
I looked through the benchmark descriptions. Could you check if the descriptions below are correct or not?
Thus, the tests of 'gbsa', 'rf', 'pme' are benchmarked on dihydrofolate reductase (DHFR) models.
The tests of 'apoa1rf', 'apoa1pme', and 'apoa1ljpme' are benchmarked on Apolipoprotein A1 (ApoA1).
The tests of  'amoebagk' and 'amoebapme' are benchmarked on dihydrofolate reductase (DHFR) models with AMOEBA polarizable force field. 
The tests of 'amber20-dhfr', 'amber20-cellulose', 'amber20-stmv' are benchmarked on Amber benchmark.

**Comment by peastman** [comment]
Correct.

**Comment by yichez16** [comment]
Thanks a lot.
