### ISSUE TITLE
Extending MonteCarloBarostatImpl to Handle Two Contexts for GEMC Simulations

### ISSUE THREAD

**Issue by ruyeli** [openmm/openmm#4297]
Hi,

I am working on implementing Gibbs Ensemble Monte Carlo (GEMC) simulations using OpenMM. GEMC simulations require handling two simulation boxes (contexts) simultaneously, each representing different phases of a system. In GEMC, a potential MC move is to simultaneously alter the volume of both boxes, akin to the functionality provided by OpenMM's MonteCarloBarostat class. I have extended it to handle two contexts by modifying the MonteCarloBarostatImpl function to accept two ContextImpl instances in MonteCarloBarostatImpl.cpp, although I haven't tested it. Here's the signature of the modified method:

```
void MonteCarloBarostatImpl::updateContextState(ContextImpl& contextI, ContextImpl& contextII, bool& forcesInvalid) {

    // Compute the current potential energies for two contexts I and II.

    int groupsI = contextI.getIntegrator().getIntegrationForceGroups();
    int groupsII = contextII.getIntegrator().getIntegrationForceGroups();
    double initialEnergyI = contextI.getOwner().getState(State::Energy, false, groupsI).getPotentialEnergy();
    double initialEnergyII = contextI.getOwner().getState(State::Energy, false, groupsII).getPotentialEnergy();

    // Modify the periodic box size for two contexts.

    Vec3 boxI[3];
    Vec3 boxII[3];
    contextI.getPeriodicBoxVectors(boxI[0], boxI[1], boxI[2]);
    contextII.getPeriodicBoxVectors(boxII[0], boxII[1], boxII[2]);
    double volumeI = boxI[0][0]*boxI[1][1]*boxI[2][2];
    double volumeII = owner.getTotalVolume() - volumeI;
    double lnVolume = log(volumeI/volumeII) + volumeScale*(SimTKOpenMMUtilities::getUniformlyDistributedRandomNumber()-0.5);
    double newVolumeI = owner.getTotalVolume()*exp(lnVolume)/(1+exp(lnVolume));
    double newVolumeII = owner.getTotalVolume() - newVolumeI;
    double lengthScaleI = pow(newVolumeI/volumeI, 1.0/3.0);
    double lengthScaleII = pow(newVolumeII/volumeII, 1.0/3.0);
    kernel.getAs<ApplyMonteCarloBarostatKernel>().scaleCoordinates(contextI, lengthScaleI, lengthScaleI, lengthScaleI);
    kernel.getAs<ApplyMonteCarloBarostatKernel>().scaleCoordinates(contextII, lengthScaleII, lengthScaleII, lengthScaleII);
    contextI.getOwner().setPeriodicBoxVectors(boxI[0]*lengthScaleI, boxI[1]*lengthScaleI, boxI[2]*lengthScaleI);
    contextII.getOwner().setPeriodicBoxVectors(boxII[0]*lengthScaleII, boxII[1]*lengthScaleII, boxII[2]*lengthScaleII);

    // Compute the energy of the modified system.
    
    double finalEnergyI = contextI.getOwner().getState(State::Energy, false, groupsI).getPotentialEnergy();
    double finalEnergyII = contextII.getOwner().getState(State::Energy, false, groupsII).getPotentialEnergy();
    double kT = BOLTZ*context.getParameter(MonteCarloBarostat::Temperature());
    double wI = -((finalEnergyI-initialEnergyI)+ (contextI.getMolecules().size()+1)*log(newVolumeI/volumeI)*kT)/kT 
    double wII = -((finalEnergyII-initialEnergyII)+ (contextII.getMolecules().size()+1)*log(newVolumeII/volumeII)*kT)/kT
    if ( (wI+wII) > 0 && SimTKOpenMMUtilities::getUniformlyDistributedRandomNumber() > exp(wI+wII)) {
        // Reject the step.

        kernel.getAs<ApplyMonteCarloBarostatKernel>().restoreCoordinates(contextI);
        kernel.getAs<ApplyMonteCarloBarostatKernel>().restoreCoordinates(contextII);
        contextI.getOwner().setPeriodicBoxVectors(boxI[0], boxI[1], boxI[2]);
        contextII.getOwner().setPeriodicBoxVectors(boxII[0], boxII[1], boxII[2]);
    }
    else {
        numAccepted++;
        forcesInvalid = true;
    }
    numAttempted++;

}
```

However, I am now facing a challenge with adjusting the SWIG wrapper to cater for the changes made in the C++ code to ensure correct Python wrapping. Alternatively, is crafting a completely new class like "volumeChange" a more viable route? I know little about OpenMM's Python wrapper workings. I am seeking guidance or suggestions on how to proceed with modifying the SWIG wrapper or any other necessary files to accommodate these changes.

Any assistance or insights would be greatly appreciated!

**Comment by peastman** [comment]
Can you give more background on how the algorithm works?  From your code, I gather that the two contexts are required to have a fixed total volume.  Are there other connections between them?  How do the two contexts get created?

**Comment by ruyeli** [comment]
Thank you for your reply.

GEMC utilizes two distinct simulation boxes simultaneously, one representing vapor phase and the other liquid phase . While the total volume V and the total number of particles N are constant, these two boxes are allowed to exchange particles and adjust volume. Upon achieving the final vapor-liquid equilibrium, both boxes should align in temperature, pressure, and chemical potential. The provided code manages volume change, keeping the total volume fixed, with the acceptance rule being derived from the Gibbs ensemble's partition function.
![image](https://github.com/openmm/openmm/assets/149922982/d3a6573b-9bca-4c3d-97f8-9c8d3aa9c8e9)
The two contexts are created independently. Here's an example for Charmm36 force field.
```from openmm.app import *
from openmm import *
from openmm.unit import *
from sys import stdout

pdb1 = PDBFile('pentane_liquid.pdb')
pdb2 = PDBFile('pentane_vapor.pdb')
psf1 = CharmmPsfFile('n_pentane_liq.psf')
psf2 = CharmmPsfFile('n_pentane_vap.psf')
params = CharmmParameterSet('top_all36_cgenff.rtf', 'par_all36_cgenff.prm')

system1 = psf1.createSystem(params, nonbondedMethod=PME, nonbondedCutoff=1*nanometer)
system2 = psf2.createSystem(params, nonbondedMethod=PME, nonbondedCutoff=1*nanometer)

integrator1 = LangevinMiddleIntegrator(300*kelvin, 1/picosecond, 0.004*picoseconds)
integrator2 = LangevinMiddleIntegrator(300*kelvin, 1/picosecond, 0.004*picoseconds)

simulation1 = Simulation(psf1.topology, system1, integrator1)
simulation2 = Simulation(psf2.topology, system2, integrator2)

simulation1.context.setPositions(pdb1.positions)
simulation2.context.setPositions(pdb2.positions)

state1 = simulation1.context.getState(getEnergy=True)
state2 = simulation2.context.getState(getEnergy=True)

print(state1.getPotentialEnergy())
print(state2.getPotentialEnergy())
```
If the above MonteCarloBarostatImpl function can accept these two contexts as parameters, it would enable simultaneous volume adjustment of both boxes. Although these boxes do not interact directly with each other, the acceptance rule is imposed to simulate the vapor-liquid equilibrium.

**Comment by peastman** [comment]
You can't change the signature of `updateContextState()`.  It's defined by the parent ForceImpl class.  That's so the ContextImpl can invoke all of them.

https://github.com/openmm/openmm/blob/31abb2f7a34e8ef5c17bc52207fb0d226bf5d703/openmmapi/src/ContextImpl.cpp#L338-L343

Every ForceImpl belongs to a single ContextImpl (which belongs to a Context).  Conceptually you can think of the ForceImpls as being part of the Context.  The job of `updateContextState()` is to modify the Context it belongs to.

A better approach might be to create a new Integrator class to define the algorithm.  Take a look at the RPMD plugin, which has some similarities to what you're doing.  Internally, RPMDIntegrator stores multiple contexts.  (Effectively, that is.  It stores the data in its own arrays rather than using actual Context objects, but the idea is similar.)  When you take a step, it updates all of them in a way that makes them depend on each other.  It also has its own barostat class, RPMDMonteCarloBarostat, since pressure regulation needs to be done differently.  You could do something similar, creating GEMCIntegrator and GEMCBarostat classes that store data for multiple contexts and update them according to the correct algorithm.

**Comment by ruyeli** [comment]
Creating a new Integrator class like RPMD is a great idea! Thank you for letting me know. It appears that this will require a substantial amount of work, so I will close this issue while I focus on this development. Thank you again for your help.
