### ISSUE TITLE
Another Issue Where Simulation Gets Slower as Time Progresses

### ISSUE THREAD

**Issue by toddjm** [openmm/openmm#4298]
I have a ca. 33,000 atom system, comprised of a ligand, a protein, 4 Cl- ions, and the rest water.

The prmtop and crd files (AMBER) were prepared using the AmberTools suite; note that I used tLEaP in order to make use of the OPC water model and the amber19sb force field.

This particular run is set to go to 1 microsecond and the initial estimate was about 19 hours; 3 hours later, it's now forecasting 31 hours.

I have seen this before and it was related, in part, to a failing NVMe stick; however, that has been replaced.

Machine is a 128 GB RAM + GeForce RTX 4090 + AMD Ryzen 9 5900X 24-core Threadripper + 2 TB Samsung NVMe, Ubuntu 22.04, CUDA driver version 12.3. Python version 3.10.12.

OpenMM is 8.0.0 and all things have been compiled on the machine (excluding some libs for AmberTools such as ARPACK and the like).

For reference, when I run a 300,000 all atom simulation, I get about 100 ns/day.

I have cobbled together the following (which is executed on the command line with `python3 script.py`):

```from openmm import app
import openmm as mm
from openmm import unit
from sys import stdout
from mdtraj.reporters import NetCDFReporter

# Set these, defaults are fine.
total_steps = 250000000  # Default is 100 ns
write_to_chk = int(total_steps / 2)  # Default is 10 ns
write_to_file = 2500  # Default is 10 ps
write_to_stdout = 1000  # Default for stdout
time_step = 4.0 * unit.femtoseconds  # Default 2 fs, go higher use rigidWater=True
temperature = 300.0 * unit.kelvin
friction_coeff = 5.0 / unit.picoseconds
min_step = 1000  # Default for energy minimization

# load Amber input files
prmtop = app.AmberPrmtopFile('complex_initial.prmtop')
inpcrd = app.AmberInpcrdFile('complex_initial.crd')

# prepare system and integrator
system = prmtop.createSystem(nonbondedMethod=app.PME,
                             nonbondedCutoff=1.0*unit.nanometers,
                             constraints=app.HBonds,
                             rigidWater=True,
                             ewaldErrorTolerance=0.0005,
                             hydrogenMass=4.0*unit.amu)

# add barostat for NPT
system.addForce(mm.MonteCarloBarostat(1.0 * unit.bar, 300.0 * unit.kelvin))

integrator = mm.LangevinMiddleIntegrator(temperature,
                                         friction_coeff,
                                         time_step)

# prepare simulation
simulation = app.Simulation(prmtop.topology, system, integrator)
simulation.context.setPositions(inpcrd.positions)
if inpcrd.boxVectors is not None:
    simulation.context.setPeriodicBoxVectors(*inpcrd.boxVectors)

# minimize
print("Minimizing energy")
simulation.minimizeEnergy()

# Scale velocities for target temperature
simulation.context.setVelocitiesToTemperature(temperature)
print('Equilibrating to {0} K for {1} steps'.format(temperature, min_step))
simulation.step(min_step)

# append reporters
simulation.reporters.append(NetCDFReporter('trajectory.nc', write_to_file)) # 10 ps

simulation.reporters.append(app.StateDataReporter(stdout, write_to_stdout, step=True,
    potentialEnergy=True, temperature=True, progress=True,
    remainingTime=True, speed=True, totalSteps=total_steps, separator='\t'))

simulation.reporters.append(app.CheckpointReporter('checkpnt.chk', write_to_chk))

# run 100 ns production
print("Running prodcution")
simulation.step(total_steps)
print("Done")
```

(1) Am I doing something blatantly obviously incorrect?

(2) If not (1), is this because I'm using the NetCDF reporter from `mdtraj`, a library that is not maintained by you (OpenMM team);

(3) Other, such as solar flares and so on.

Thank you in advance,

Todd Minehardt

**Comment by sef43** [comment]
I believe there is a memory leak in MDTraj's NetCDF reporter: https://github.com/mdtraj/mdtraj/issues/1345

Indeed If I set the report frequency to be very high than I can clearly see the memory leak running a test example on an m2 macbook

**Comment by toddjm** [comment]
Thanks so much, appreciated.
