### ISSUE TITLE
[Question] Computation speed doesn't seem to be improved from v8.0.0 to 8.1.0b on CUDA Platform

### ISSUE THREAD

**Issue by passive-radio** [openmm/openmm#4300]
Hi! 
I've tested OpenMM v8.1.0b to figure out how performance with CUDA GPU has been improved from 8.0.0.
I expected MD computing speed would be improved as it was mentioned in the release note, however, it seems I couldn't reproduce the improvements. Moreover, the computing performance decreased in tested systems (2% speed decrease on average).

If there's any additional works to do to reproduce the performance improvements on CUDA Platforms?

Thank you.

### Testing Spec
1. Ubuntu 22.04 LTS
2. OpenMM versions: 8.0.0 and 8.1.0b (both from conda-forge)
3. GPU: Nvidia RTX 3050
4. Tested proteins sizes: 888 atoms, 6790 atoms (only protein atoms)
5. python script: example below

```python
# Input Files

pdb = PDBFile(f'{INPUT_DIR}/{INPUT_PDB}.pdb')
forcefield = ForceField('amber14-all.xml', 'amber14/tip3pfb.xml')

# System Configuration

nonbondedMethod = PME
nonbondedCutoff = 1.0*nanometers
ewaldErrorTolerance = 0.0005
constraints = HBonds
rigidWater = True
constraintTolerance = 0.000001

# Integration Options

dt = 0.001*picoseconds # 1 fs
temperature = 300*kelvin
friction = 1.0/picosecond
pressure = 1.0*atmospheres
barostatInterval = 25

# Simulation Options

steps = 1000000 # 1ns
equilibrationSteps = 100000 # 0.1 ns
platform = Platform.getPlatformByName('CUDA')
platformProperties = {'Precision': 'single'}
dcdReporter = DCDReporter(f'{OUT_DIR}/trajectory.dcd', 10000)
dataReporter = StateDataReporter(f'{LOG_DIR}/log.txt', 10000, totalSteps=steps,
    step=True, elapsedTime=True, remainingTime=True, speed=True, separator='\t')

# Prepare the Simulation

print('Building system...')
topology = pdb.topology
positions = pdb.positions
system = forcefield.createSystem(topology, nonbondedMethod=nonbondedMethod, nonbondedCutoff=nonbondedCutoff,
    constraints=constraints, rigidWater=rigidWater, ewaldErrorTolerance=ewaldErrorTolerance)
system.addForce(MonteCarloBarostat(pressure, temperature, barostatInterval))
integrator = LangevinMiddleIntegrator(temperature, friction, dt)
integrator.setConstraintTolerance(constraintTolerance)
simulation = Simulation(topology, system, integrator, platform, platformProperties)
simulation.context.setPositions(positions)

# Write XML serialized objects
# ...

# Minimize and Equilibrate

print('Performing energy minimization...')
simulation.minimizeEnergy()
print('Equilibrating...')
simulation.context.setVelocitiesToTemperature(temperature)
simulation.step(equilibrationSteps)

# Simulate

print('Simulating...')
simulation.reporters.append(dcdReporter)
simulation.reporters.append(dataReporter)
simulation.currentStep = 0
simulation.step(steps)

# Write file with final simulation state
# ...
```

**Comment by peastman** [comment]
The amount of speedup will vary between systems.  There are a lot of different optimizations, each one only helping in some cases.  I'm surprised you don't see some speedup in your 888 atom system, though, since the change from #4070 ought to be helping in that case.  If you can post your input files, I'd be glad to profile it and see what's happening.

**Comment by passive-radio** [comment]
Hello peastman.
Input files for each proteins
[6lzg-processed.txt](https://github.com/openmm/openmm/files/13273512/6lzg-processed.txt)
[1tq3-processed.txt](https://github.com/openmm/openmm/files/13273514/1tq3-processed.txt)

These were generated using openmm-setup

(file ext changed 'pdb' to 'txt' for unsupported file type on comment)

One more question I want to ask is are there any benefit for thousands of atoms systems (with or without CUDA)?

Thank you!

**Comment by peastman** [comment]
These systems are much bigger than what you said.  1tq3 has about 17,000 atoms, and 6lzg is over 181,000 atoms.  The optimization I referred to only benefits small systems with less than 3000 atoms.

There are lots of optimizations in this release, each affecting different situations.  There are a couple that mainly benefit very large systems, at least several hundred thousand atoms.  There are optimizations that specifically apply to AMD GPUs, or to OpenCL.  CustomHbondForce is a lot faster.  It isn't a matter of all simulations being uniformly faster.  Some will be a lot faster, and others not at all.  It depends on the details.

**Comment by passive-radio** [comment]
Thanks!
It solved!
