### ISSUE TITLE
Encode long-range Coulomb interaction with distance-dependent dielectric into openmm

### ISSUE THREAD

**Issue by smliu1997** [openmm/openmm#4301]
Hi, 

I want to encode such a Coulomb potential into openmm: $U=\frac{q_i q_j}{4 \pi \epsilon_0 (41.6+41.6\tanh((r-\mu)/\sigma)) r_{ij}}$. So this potential is a Coulomb potential with a distance-dependent dielectric. After some searching, it seems like the correct way is: 
(1) Find a cutoff value, when r > cutoff, the potential can be approximated as $U=\frac{q_i q_j}{4 \pi \epsilon_0 \epsilon_r r_{ij}}$, where $\epsilon_r=83$ is the constant dielectric at large distance limit. This part should be handled by `NonbondedForce` with PME.
(2) For r <= cutoff, this part can be handled by `CustomNonbondedForce`. 
May I ask if my understanding is correct? Also, may I ask how to set the dielectric constant as 83 for the long-range `NonbondedForce`?

Thank you so much!

**Comment by peastman** [comment]
Can you explain what you're trying to accomplish?

I haven't heard of anyone using a distance dependent dielectric in many years.  They're a method people used to use to try to approximate solvent screening, back before better methods like reaction field and PME were developed.  By having the dielectric go to a large value (83) at long distances, you greatly decrease the strength of those interactions.  That's done so you can ignore the ones further apart than some cutoff.  PME, on the other other, explicitly includes all interactions with no need for a cutoff.  Why do you want to combine those two methods?

**Comment by smliu1997** [comment]
Thank you for the reply! So I am actually trying to implement an explicit-ion, implicit-solvent model, following this study: https://pubs.aip.org/aip/jcp/article-abstract/135/16/165104/71135/A-coarse-grain-three-site-per-nucleotide-model-for?redirectedFrom=fulltext
Equation 3 in the main text is the equation I showed. Also I know for some implicit-ion models, distance-dependent dielectric is applied, but because implicit-ion model uses an exponentially decaying potential, long-range part can be ignored. 

So my question is about how to implement that Coulomb potential with distance-dependent dielectric by considering all the long-range part. It seems like `CustomNonbondedForce` does not support including the long-range interactions, while `NonbondedForce` does not support a distance-dependent dielectric, so I have to ask for help here.

**Comment by peastman** [comment]
I don't see any way of combining that functional form with PME.  It's not a question of what features are or aren't supported.  They're just inherently incompatible with each other.  PME can only be applied to interactions of the form $q_1 q_2/r^n$.

There are ways of combining the PME reciprocal space term with an altered short range term, such that you get a different behavior at short differences but standard Coulomb at longer distances.  If you want to do something like that, you need to figure out what the exact functional form you want is, and it has to be identical to a standard Coulomb interaction at any distance longer than the cutoff.

**Comment by smliu1997** [comment]
I see, when you say "identical to a standard Coulomb interaction at any distance longer than the cutoff", do you mean the dielectric constant is also fixed at a specific value, and I cannot change dielectric to 83?

**Comment by peastman** [comment]
Right.  But beyond the cutoff, the dependence on $r$ has to be exactly $1/r$.

**Comment by smliu1997** [comment]
Thanks, I think I know what to do, my plan is to use `NonbondedForce` to capture large distance behavior, and use another `CustomNonbondedForce` to correct the short range behavior as distance-dependent dielectric. 

A final question is, when using `addParticle` in `NonbondedForce`, if the ion is a sodium ion, shall I set charge as +1 or elementary charge?
