### ISSUE TITLE
 A bug that occurs when I use LennardJonesForce and CustomNonbondedForce at the same time in an XML file

### ISSUE THREAD

**Issue by KingOfChuXuan** [openmm/openmm#4304]
Hello!
When I build my own XML file including LennardJonesForce and CustomNonbondedForce at the same time, I get
```OpenMMException: CustomNonbondedForce: Multiple exclusions are specified for particles 0 and 1```
after I run my code.
No matter how I change the format of CustomNonbondedForce, the exception is always there.
Then I check the code of forcefield.py, I believe the problem is with this part of the code:
```
class CustomNonbondedGenerator(object):
    """A CustomNonbondedGenerator constructs a CustomNonbondedForce."""

    def __init__(self, forcefield, energy, bondCutoff):
        self.ff = forcefield
        self.energy = energy
        self.bondCutoff = bondCutoff
        self.globalParams = {}
        self.perParticleParams = []
        self.computedValues = {}
        self.functions = []

    @staticmethod
    def parseElement(element, ff):
        generator = CustomNonbondedGenerator(ff, element.attrib['energy'], int(element.attrib['bondCutoff']))
        ff.registerGenerator(generator)
        for param in element.findall('GlobalParameter'):
            generator.globalParams[param.attrib['name']] = float(param.attrib['defaultValue'])
        for param in element.findall('PerParticleParameter'):
            generator.perParticleParams.append(param.attrib['name'])
        for value in element.findall('ComputedValue'):
            generator.computedValues[value.attrib['name']] = value.attrib['expression']
        generator.params = ForceField._AtomTypeParameters(ff, 'CustomNonbondedForce', 'Atom', generator.perParticleParams)
        generator.params.parseDefinitions(element)
        generator.functions += _parseFunctions(element)

    def createForce(self, sys, data, nonbondedMethod, nonbondedCutoff, args):
        methodMap = {NoCutoff:mm.CustomNonbondedForce.NoCutoff,
                     CutoffNonPeriodic:mm.CustomNonbondedForce.CutoffNonPeriodic,
                     CutoffPeriodic:mm.CustomNonbondedForce.CutoffPeriodic,
                     Ewald:mm.CustomNonbondedForce.CutoffPeriodic,
                     PME:mm.CustomNonbondedForce.CutoffPeriodic,
                     LJPME:mm.CustomNonbondedForce.CutoffPeriodic}
        if nonbondedMethod not in methodMap:
            raise ValueError('Illegal nonbonded method for CustomNonbondedForce')
        force = mm.CustomNonbondedForce(self.energy)
        for param in self.globalParams:
            force.addGlobalParameter(param, self.globalParams[param])
        for param in self.perParticleParams:
            force.addPerParticleParameter(param)
        for name in self.computedValues:
            force.addComputedValue(name, self.computedValues[name])
        _createFunctions(force, self.functions)
        for atom in data.atoms:
            values = self.params.getAtomParameters(atom, data)
            force.addParticle(values)
        force.setNonbondedMethod(methodMap[nonbondedMethod])
        force.setCutoffDistance(nonbondedCutoff)
        sys.addForce(force)

    def postprocessSystem(self, sys, data, args):
        # Create the exclusions.

        bondIndices = _findBondsForExclusions(data, sys)
        nonbonded = [f for f in sys.getForces() if isinstance(f, mm.CustomNonbondedForce)][0]
        nonbonded.createExclusionsFromBonds(bondIndices, self.bondCutoff)
```
In my case, the nonbonded of the postprocessSystem method refers to LennardJonesForce instead of the CustomNonbondedForce I defined, so the createExclusionsFromBonds method of LennardJonesForce has been called twice.
So after I change
```
nonbonded = [f for f in sys.getForces() if isinstance(f, mm.CustomNonbondedForce)][0]
```
to
```
nonbonded = [f for f in sys.getForces() if isinstance(f, mm.CustomNonbondedForce) if f.getName() != 'LennardJones'][0]
```
, my code works well.
So I wonder if this is a bug of OpenMM, or caused by my irregular operation?
Besides, I find that compared to creating the CustomNonBondedForce in code and adding it to the System, writing it into XML seems to be 1.5 times slower. Is there any way that may improve it?
I'm afraid that I can't provide my code and the XML file for some reasons.
Thank you for your reply!

**Comment by peastman** [comment]
Good point, it's assuming the system will only contain a single CustomNonbondedForce.  We should try to fix that.

> I find that compared to creating the CustomNonBondedForce in code and adding it to the System, writing it into XML seems to be 1.5 times slower.

If the speed is different, that means the forces you're creating in the two cases are different in some way.

**Comment by KingOfChuXuan** [comment]
> If the speed is different, that means the forces you're creating in the two cases are different in some way.

I think you are right. 
When I created the `CustomNonBondedForce` in code, I called `addInteractionGroup()` to specify the interaction particles, which causes `getNumExclusions()` to be zero.
However, when I just used the XML file and create the `System` via `Forcefield.createSystem()`, `getNumExclusions()`could be a large number. 
I believe this is why the two cases occur at different speeds.
So, I wonder if there is a way to specify interaction groups in an XML file without adding exclusions(i.e. set `bondCutoff="0"`)?
Thank you for your reply!

**Comment by peastman** [comment]
I believe that would work.  Did you try it?

Of course, when you use a `<CustomNonbondedForce>` tag to create it, ForceField won't add interaction groups to it.  So those are rather different situations.

**Comment by KingOfChuXuan** [comment]
> I believe that would work. Did you try it?

I'm sorry that I' m afraid I can't understand what do you mean? 

> Of course, when you use a `<CustomNonbondedForce>` tag to create it, ForceField won't add interaction groups to it. So those are rather different situations.

So does it mean that the simulation is faster when I use `addInteractionGroup()` than using `addExclusion()`, and the formmer can't be specified via the XML file?

**Comment by peastman** [comment]
> I'm sorry that I' m afraid I can't understand what do you mean?

Setting `bondCutoff="0"` like you suggested.  Did you try it?

> So does it mean that the simulation is faster when I use addInteractionGroup() than using addExclusion()

They're not the same thing, and they're used for different purposes.  Exclusions are for when you want to include almost all interactions, but exclude a few specific ones such as between atoms that are directly bonded to each other.  Interaction groups are for when you only want to include a fraction of all interactions, such as ones between solvent and solvent.

**Comment by KingOfChuXuan** [comment]
> Setting `bondCutoff="0"` like you suggested. Did you try it?

Oh, yes, it does work. But if I do so, I need to call `addInteractionGroup()` in code, so I'm wondering that if I can just specify the interaction groups in the XML file so that I needn't to call the method in code.



> They're not the same thing, and they're used for different purposes.

I think I have got this, thank you for your reply!
