### ISSUE TITLE
Which algorithm is used to resolve bond constraints?

### ISSUE THREAD

**Issue by SchroedingersLion** [openmm/openmm#4308]
Greetings,

I did not find conclusive descriptions on which algorithms are being used to resolve molecular bond constraints. For water molecules, Settle seems to be used. But what about other bonds?
Is the information in #3013 still up-to-date? How can I check which is being used on a CPU platform? 

Regards.

**Comment by peastman** [comment]
The information in that issue is still correct.

**Comment by SchroedingersLion** [comment]
Does that mean the CPU platform uses CCMA for anything but water?

**Comment by peastman** [comment]
Correct.

**Comment by SchroedingersLion** [comment]
Thanks Peter! I just read your original paper to CCMA. Is there any intuition of whether CCMA is less restrictive in terms of stepsize than Shake? The 2fs limit of Shake seems to be related to the Shake-projection failing for larger stepsizes.

**Comment by peastman** [comment]
It depends which one is a better approximation of the inverse jacobian, which depends on how much the angles fluctuate.  In practice, convergence of the constraints is rarely the limiting factor on step size.  If constrained distances change so much in one step that convergence is a problem, you're probably way outside the stability limit of the integrator.

**Comment by SchroedingersLion** [comment]
Cheers!
