### ISSUE TITLE
Topology from `Modeller` does not match templates from AMBER force field

### ISSUE THREAD

**Issue by nielskm** [openmm/openmm#4309]
[2vci.pdb.txt](https://github.com/openmm/openmm/files/13349632/2vci.pdb.txt)

Using the topology from `Modeller` after deleting a heterogen breaks the template matching for the AMBER ff14SB force field.

```
from copy import deepcopy
from io import StringIO

from openmm.app import ForceField, Modeller, PDBFile

pdb = PDBFile("2vci.pdb")

modeller = Modeller(deepcopy(pdb.topology), deepcopy(pdb.positions))
modeller.delete([c for c in modeller.topology.chains() if c.index == 1])

ff = ForceField("amber14/protein.ff14SB.xml")

# Fails with "No template found for residue 1 (GLU). The set of atoms matches NGLU, but the bonds are different.
system_from_modeller = ff.createSystem(modeller.topology)

# Running through PDBFile makes it work
pdb_io = StringIO()
PDBFile.writeFile(modeller.topology, modeller.positions, pdb_io)
pdb_io.seek(0)
reloaded_pdb = PDBFile(pdb_io)

system_from_reloaded = ff.createSystem(reloaded_pdb.topology)
```

**System information**
OS: Ubuntu 22.04
OpenMM version: 8.0.0 installed from conda forge
Python version: 3.9.18

**Comment by peastman** [comment]
The problem is your calls to `deepcopy()`.  They aren't necessary: Modeller always creates new objects rather than modifying the existing ones.  And they break the Topology, which relies on lots of objects having references to each other.

**Comment by nielskm** [comment]
Thanks for clarifying this @peastman !
