### ISSUE TITLE
Access Quaternions from Gay-Berne Force

### ISSUE THREAD

**Issue by erb24** [openmm/openmm#4312]
Hi,

I'm performing simulations of a box of Gay-Berne particles with an eye towards eventually performing enhanced sampling simulations using PLUMED by biasing along the nematic order parameter. When running unbiased simulation using the Gay-Berne force in OpenMM, is there a way to extract the quaternions for each particle from each frame during the simulation so that the nematic order parameter as a function of time can be calculated?

Thanks,

Eric

**Comment by peastman** [comment]
When you say "quaternions", I assume you actually mean the local coordinate frames computed for each particle?  We don't use quaternions in computing the interaction.  There's no option to extract them, though they're quite easy to compute yourself.  Here's the code from the reference platform that does it.

https://github.com/openmm/openmm/blob/31abb2f7a34e8ef5c17bc52207fb0d226bf5d703/platforms/reference/src/SimTKReference/ReferenceGayBerneForce.cpp#L136-L155

**Comment by erb24** [comment]
That's what I was looking for! I have been doing these simulations in LAMMPS, where the quaternions can be output in a dump file. Thanks!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by peastman** [comment]
Great!  Can this issue be closed, or do you have other questions about it?

**Comment by erb24** [comment]
Close it. Thanks again.
