### ISSUE TITLE
Compute RMSD correctly in a periodic system

### ISSUE THREAD

**Issue by smliu1997** [openmm/openmm#4315]
May I ask in a periodic system, how does RMSDForce work? So in openmm, most bonded forces have a method called `setUsesPeriodicBoundaryConditions`, which sets the periodic boundary condition (PBC). For RMSDForce, I did not find such method to set PBC. My understanding is, if the reference coordinate is an intact whole molecule, then RMSDForce should compute RMSD correctly in PBC system, is this understanding correct?

**Comment by peastman** [comment]
Correct.  The first step in the RMSD calculation is to translate and rotate the two groups to superimpose them.  As long as each group is intact, not split across multiple periodic copies, it doesn't matter whether you have periodic boundary conditions.

**Comment by smliu1997** [comment]
Thank you for your clarification! So I think this means by viewing the target atoms a group, these atoms are first translated so that they are in the same periodic image, is this understanding correct?

**Comment by peastman** [comment]
> these atoms are first translated so that they are in the same periodic image

In the same periodic image as the reference positions, yes.  The atoms all need to be in the same periodic image as each other, not split across multiple images.  But it doesn't matter if they're in the same image as the reference positions.

**Comment by smliu1997** [comment]
I see, thank you so much!
