### ISSUE TITLE
two "HarmonicBondForce" in my system

### ISSUE THREAD

**Issue by wayuer19** [openmm/openmm#4321]
Hi,

When I printed out the forces of the system, I found there were two terms named "HarmonicBondForce", as shown in the figure
![image](https://github.com/openmm/openmm/assets/24451788/9f1e2466-ba4f-47eb-930f-4073637672a4)

I don't know why, any suggestions?
[test.zip](https://github.com/openmm/openmm/files/13398689/test.zip)

**Comment by peastman** [comment]
I think one is for the bonds and the other is for the Urey-Bradley terms.  They could be combined into a single object, but it doesn't make much difference one way or the other.

**Comment by wayuer19** [comment]
Thank you for your reply. I'm trying to get the bondlist from harmonicbondforce. And I found the second one has nothing in it. So it should be the Uery-Bradly terms as you said. Hope the real bonds are in the first one, or I will get a wrong bond list. 

Thank you.

**Comment by peastman** [comment]
If you want to only get actual covalent bonds, not other force field terms that happen to be modeled as pairwise harmonic terms (like Urey-Bradley or distance restraints), the best way is to get them from `topology.bonds()`.

**Comment by wayuer19** [comment]
Right, it's the best way! Thank you so much. And I will close this comment.
