### ISSUE TITLE
Changing the virtual site on the fly during the simulation

### ISSUE THREAD

**Issue by smlee99** [openmm/openmm#4329]
Hi. I'm currently trying to simulate the proton hopping based on TIP4P/2005 FF. This model is implemented in openMM via defining the OM particle as a virtual site, where its position is fixed during the simulation. This is not a problem for simulating hydronium ion in nonreactive condition since there would be no change on the bond topology. But for reactive condition, the bond topology information should be changed according to the proton transfer (which is straightfoward to do so) and also for the relative geometry of virtual site in hydronium ion compared to that in neutral water molecule. Can I ask how to change the virtual site location on the fly during the simulation? Thanks in advance!

![image](https://github.com/openmm/openmm/assets/54790642/f4002a20-ee57-41b3-afa4-85dae410a31a)

**Comment by peastman** [comment]
To change the virtual site information for a particle, construct a new VirtualSite object for it and call `setVirtualSite()` on the System.  Doing this will not immediately affect your running simulation.  To make it see the changes, call `reinitialize(True)` on the Context.  That's an expensive method (equivalent to recreating the Context from scratch), so you don't want to call it too often.

**Comment by smlee99** [comment]
Thanks for your answer. One more question is that modifying the bond topology on the fly during the simulation would also require the `reinitalize(True)` on the Context, right? There are some reactiveMD simulation paper in which the bond breaking/formation process is done by the Monte Carlo move during the simulation. For instance, it seems like the proton hopping move is proposed for 10fs time interval by several papers. I expect that there should be a significant slowdown on the computational cost when this is directly implemented in OpenMM via reinitializing the context every time when MC move is proposed. Could writing a openMM plugin be much better option for such process? (I have no experience for this)

**Comment by peastman** [comment]
Most forces have an `updateParametersInContext()` method you can use to update certain parameters.  It's faster than reinitializing the whole context, though still somewhat expensive.  Check the documentation for each class to see exactly what can and can't be updated that way.  For example, you usually can change the force constant for a bond, but not which atoms the bond connects.  You could effectively turn off a bond by setting its force constant to zero, but you couldn't move it to connect different atoms.

**Comment by smlee99** [comment]
I see.Thanks for your answer and let me close this issue.
