### ISSUE TITLE
ATM Force python API example is C++

### ISSUE THREAD

**Issue by hmacdope** [openmm/openmm#4332]
The ATMForce example given for the Python API [here](http://docs.openmm.org/latest/api-python/generated/openmm.openmm.ATMForce.html#openmm.openmm.ATMForce) is actually C++, which is a bit confusing.

**Comment by peastman** [comment]
That's true of all the API docs.  The Python API is generated automatically from the C++ API.  I don't know of any good solution to that.

**Comment by sef43** [comment]
this is an issue I have heard people asking about often. I think most users are using the Python Application layer and the Python API, not the C++ Api. Many will not be aware that the python api has been automatically generated from C++ resulting in confusion when reading the docs.  

I know there is a not an easy fix but there must be a way of automatically converting the examples in the doc strings into real python code. I am sure gpt could do it

**Comment by hmacdope** [comment]
Apologies, I didn't realise that all the examples are in C++. This is a difficult problem for sure.

**Comment by hmacdope** [comment]
I might close this as I don't think given the above this specific issue about ATM is very helpful.
