### ISSUE TITLE
[Q] Explicitly named parameters

### ISSUE THREAD

**Issue by chem-william** [openmm/openmm#4347]
In the following minimal example, I will get an error if I use explicitly named parameters:
```python
from openmm import LangevinMiddleIntegrator
from openmm.unit import kelvin, picoseconds

integrator = LangevinMiddleIntegrator(
    # uncomment for no error
    #300.0 * kelvin,
    #1 / picoseconds,
    #2.0 * picoseconds,

    temperature=300.0 * kelvin,
    frictionCoeff=1 / picoseconds,
    stepSize=2.0 * picoseconds,
)
```
Running this, I get the following error:
```bash
Traceback (most recent call last):
  File "/home/william/workspace/q4bio/git/fep/mre.py", line 4, in <module>
    integrator = LangevinMiddleIntegrator(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: LangevinMiddleIntegrator.__init__() got an unexpected keyword argument 'temperature'
```

If I don't provide the explicitly named parameters, it works without error.

Is this intended? Other parts of the API works fine when supplying explicit named parameters, e.g., `openmm.app.GromacsGroFile`

```bash
openmm                    8.1.0           py311h6d2dbb8_1    conda-forge
Python 3.11.6
```

**Comment by peastman** [comment]
This has to do with the way SWIG generates wrappers for C++ classes.  For most methods it can support specifying arguments by name, but not for constructors.

**Comment by chem-william** [comment]
That's a shame, but I guess that's life. Thanks for the quick reply!
