### ISSUE TITLE
Supplying NonBondedForce LJ parameters where C12 = 0

### ISSUE THREAD

**Issue by selimsami** [openmm/openmm#4349]
Hi,

I would like to use NonBondedForce for Coulomb and C6, because I'd like to use LJPME for long-range interactions.

However, I have a completely different functional form instead of C12 to account for the repulsion, for which I use CustomNonBondedForce.

My question is - can I somehow supply LJ parameters so that C12 is equal to 0 while C6 is not? 

If not, what alternative you would have for solving my case?

**Comment by peastman** [comment]
Not exactly like that, but what you can do is have the NonbondedForce compute only the reciprocal space term.  Do that by calling `setIncludeDirectSpace(False)`.  Then you can use a CustomNonbondedForce to compute the direct space part, both Coulomb and LJ, in whatever way you want.

**Comment by selimsami** [comment]
Ah great thanks, that would cover my use case indeed!
