### ISSUE TITLE
copy.deepcopy for topology

### ISSUE THREAD

**Issue by okbckim** [openmm/openmm#4357]
The topology_copy created by copy.deepcopy(topology) encounters KeyError when used in PDBFile.writeFile while original topology has no issue. Is Topology safe for copy.deepcopy? Is there better way to get completely separate copy of topology object? I am posting simple script to reproduce the error and error message.

import openmm.app as app
import openmm as mm
import openmm.unit as unit
import copy

pdb = app.PDBFile('a.pdb')
topology_copy = copy.deepcopy(pdb.topology)

app.PDBFile.writeFile(topology_copy, pdb.positions, open('a_copy.pdb', 'w'))

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Untitled-2.ipynb Cell 1 line 1
      8 pdb = app.PDBFile('30.pdb')
      9 topology_copy = copy.deepcopy(pdb.topology)
---> 11 app.PDBFile.writeFile(topology_copy, pdb.positions, open('30_copy.pdb', 'w'))

File ~/mambaforge/envs/openff-toolkit/lib/python3.11/site-packages/openmm/app/pdbfile.py:292, in PDBFile.writeFile(topology, positions, file, keepIds, extraParticleIdentifier)
    290 PDBFile.writeHeader(topology, file)
    291 PDBFile.writeModel(topology, positions, file, keepIds=keepIds, extraParticleIdentifier=extraParticleIdentifier)
--> 292 PDBFile.writeFooter(topology, file)

File ~/mambaforge/envs/openff-toolkit/lib/python3.11/site-packages/openmm/app/pdbfile.py:439, in PDBFile.writeFooter(topology, file)
    437 atomBonds = {}
    438 for atom1, atom2 in conectBonds:
--> 439     index1 = atomIndex[atom1]
    440     index2 = atomIndex[atom2]
    441     if index1 not in atomBonds:

KeyError: <Atom 0 (H1) of chain 0 residue 0 (UNL)>

**Comment by peastman** [comment]
As you discovered, using `deepcopy()` breaks the Topology.  The different objects within the Topology all reference each other.  Deepcopy breaks those references.  Try using `copy()` instead.

**Comment by okbckim** [comment]
Thank you so much for the confirmation. My intention is to modify topology_copy while keeping the original topology intact. I achieve this goal by creating new Topology instance same way as the original topology was created.

**Comment by peastman** [comment]
That would work too.  Though I really think `copy()` ought to work, just not `deepcopy()`.

Is it ok to close this issue?

**Comment by okbckim** [comment]
Thank you again. Absolutely you can close the case.
