### ISSUE TITLE
Trajectory reporters not writing the box dimensions

### ISSUE THREAD

**Issue by selimsami** [openmm/openmm#4359]
Not sure if I am missing something but I have tried both PDBReporter and XTCReporter and none of them seems to be writing the box dimensions to the file. in case of XTCReporter all dimensions are printed as zero, and in PDBReporter, there is no line specifying the dimensions.
If I am not missing something, what is the logic behind this?
Thanks!

**Comment by peastman** [comment]
That indicates your model isn't periodic.  Try calling `getPeriodicBoxVectors()` on your Topology.  Is it `None`?

Be aware that PDB files can only store a single set of box vectors for the whole file, not for each frame.  That's a limitation of the file format.  XTC can store them for each frame.

**Comment by selimsami** [comment]
It is indeed None.

But what does it mean for a Topology to be non-periodic? 
I would have thought that has more to do with the System? 
I find it weird that you can set box vectors but not atom coordinates in an object - those two seem inseparable to me.

Why is there both `system.setDefaultPeriodicBoxVectors` and `topology.setUnitCellDimensions`?
And why having PeriodicCutoff forces in system doesn't automatically make the simulation periodic?

I've been setting my box so far with:
`system.setDefaultPeriodicBoxVectors` and `simulation.context.setPeriodicBoxVectors`
Was I running non-periodic simulations so far? it did not seem like that.
What other consequences was there besides box vectors not being printed in XTC file?

What is the correct way to set up everything then?
Should I use `topology.setPeriodicBoxVectors`? How does that interact with other two commands I've been using?

**Comment by peastman** [comment]
A Topology is a chemical description of the model.  It formulates it in terms of physical objects: atoms, elements, bonds, etc.  If your model is periodic, that's a fundamental difference from a nonperiodic one.  It represents a different set of atoms.

A System is a mathematical description.  It specifies the equations to use for computing forces.  A System taken as a whole is not fundamentally periodic or nonperiodic.  It's up to each Force it contains to decide whether or not to use periodic boundary conditions.  Usually some of them do and others don't.

See [the FAQ](https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#periodic) for more information about this.

The Topology and System store complementary information.  They're expected to be consistent with each other.  All the standard ways of building a System ensure that.  If you call `createSystem()` on a ForceField, it copies the periodic box vectors from the Topology over to the System it creates.  If the Topology doesn't have periodic box vectors and you ask for a nonbonded method that requires them, it throws an exception.  If you load Amber, CHARMM, or Gromacs files, it ensure the System and Topology it creates are consistent.  But if you create each of them from scratch, it's possible to make them inconsistent, a System that uses periodic boundary conditions but a nonperiodic Topology.  It's your job to make sure you don't do that.

**Comment by selimsami** [comment]
Thank Peter, that makes sense.

I imagine there could be a check when you call generate the Simulation object, providing both Topology and System though.

My final question is - what other consequences besides the missing periodic box dimensions is there having a non-periodic topology for my previous simulations? I even managed to get the box dimensions with the mdtraj reporters. So I wonder if there could some hidden errors.

**Comment by peastman** [comment]
Running the simulation is done entirely based on the System, so it won't affect that.  The two main purposes the Topology is used for are building the System in the first place and writing output.  Those are the places it matters.
