### ISSUE TITLE
How to get the every item of Potential Energy?

### ISSUE THREAD

**Issue by Liaokang123456** [openmm/openmm#4361]
If I set up the simulation ahead, and 

I use this "state = simulation.context.getState(getEnergy=True, getForces=True, getPositions=True, getVelocities=True)
potential_energy = state.getPotentialEnergy()" to get the Potential Energy, and I want to check the every item of it, like bond item, angle, proper, improper, LJ-14, LJ(SR), etc.
What can I do ?

Thanks!

**Comment by peastman** [comment]
See https://openmm.github.io/openmm-cookbook/latest/notebooks/cookbook/Analyzing%20Energy%20Contributions.html.

**Comment by Liaokang123456** [comment]
Thanks, 
I used the code 
for i, f in enumerate(system.getForces()):
    state = simulation.context.getState(getEnergy=True, groups={i})
    print(f.getName(), state.getPotentialEnergy())
And I am confused, because the sum of every items is not equal to the Potential Energy (simulation.context.getState(getEnergy=True))

**Comment by Liaokang123456** [comment]
Thanks!
I only test one simply molecule, ethanol

import openmm as mm
import openmm.app as app
from openmm.unit import kelvin, picoseconds, femtoseconds, nanometer
"""
integrator = mm.LangevinIntegrator(
    300 * kelvin,  # Temperature of heat bath
    1.0 / picoseconds,  # Friction coefficient
    2.0 * femtoseconds,  # Time step
)
system = self.ps.createSystem(nonbondedMethod=app.NoCutoff, constraints=app.HBonds)
sim = app.Simulation(self.ps.topology, system, integrator)

for i, f in enumerate(system.getForces()):
    sim.context.setPositions(self.coords[0])
    state = sim.context.getState(getEnergy=True, groups={i})
    print(f.getName(), state.getPotentialEnergy())

sim.context.setPositions(self.coords[0])
state = sim.context.getState(getEnergy=True)
"""

self.coord: [[[ 0.0095 -0.0003  0.0008]
  [ 0.0246 -0.0004  0.0008]
  [ 0.0295 -0.0108 -0.0076]
  [ 0.0057  0.0078  0.0071]
  [ 0.0056 -0.0098  0.0045]
  [ 0.0056  0.001  -0.0094]
  [ 0.0286 -0.0019  0.0109]
  [ 0.0285  0.0091 -0.0031]
  [ 0.0261 -0.0192 -0.004 ]]]

And at last, I got the output:
HarmonicBondForce 13388.714810947236 kJ/mol
HarmonicAngleForce 1.4721371610999185 kJ/mol
PeriodicTorsionForce 6.466315037467555 kJ/mol
NonbondedForce 0.0 kJ/mol
CMMotionRemover 0.0 kJ/mol
energy: 2918599044228.329 kJ/mol

And I am confused the Potential Energy is too large(because the unit?) and the sum of the every item is not equal it.

**Comment by peastman** [comment]
The code you posted doesn't make any sense.  Most of it is inside a block quote, which means it doesn't get executed.  And it refers to `self`, even though it isn't inside a method and no `self` object exists.  Please post a *complete*, *working* test case that reproduces the problem.
