### ISSUE TITLE
Create 8.1.1 release

### ISSUE THREAD

**Issue by peastman** [openmm/openmm#4365]
We've now found a couple of bugs that justify doing a 8.1.1 release: #4351 and #4364.  Doing a release during the holidays is probably not a good idea.  Let's plan to create a release candidate right after the new year.

**Comment by sef43** [comment]
#4364 is particularly important, perhaps worth making a post somewhere about. If people are using 8.1 to compute dynamic proprieties this could be giving them slightly incorrect results ?

**Comment by peastman** [comment]
I'm building the conda packages for the release candidate at https://github.com/conda-forge/openmm-feedstock/pull/123.

**Comment by peastman** [comment]
The conda packages for the release candidate are now up.  Please try them out and report back whether they work for you.

```
mamba install -c conda-forge/label/openmm_rc -c conda-forge openmm
```

**Comment by sef43** [comment]
it works for me

**Comment by peastman** [comment]
Thanks!

**Comment by peastman** [comment]
It's now released and the conda packages are up.
