### ISSUE TITLE
OpenMM 8.1.0 Installation for CUDA 10.1

### ISSUE THREAD

**Issue by 4li77l3n00b** [openmm/openmm#4368]
I tried to install OpenMM with Conda and got the following outputs.

$ conda install -c conda-forge openmm cudatoolkit=10.1
Collecting package metadata (current_repodata.json): done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
Solving environment: unsuccessful attempt using repodata from current_repodata.json, retrying with next repodata source.(Ctrl-C)

Does this mean there are no longer builds for cuda 10.1?

**Comment by peastman** [comment]
There haven't been CUDA 10.1 builds for the last several versions.  That isn't what the output you quoted means though.  It just means that conda is very very slow, and you stopped it before it finished solving the environment.  I recommend using mamba, which is much faster and also gives better error messages about why it couldn't install something.
