### ISSUE TITLE
A mess DCD trajectory file

### ISSUE THREAD

**Issue by KingOfChuXuan** [openmm/openmm#4369]
Hello, I got a mess DCD trajectory file via DCDReporter, it feels like the element mapping is wrong.
Here is the initial topology:
![image](https://github.com/openmm/openmm/assets/146178267/96e72819-ec20-49b7-b03e-b7b989b71d36)
and here is a snap shot of the DCD trajectory file:
![image](https://github.com/openmm/openmm/assets/146178267/8a3c36a6-3c1c-4d3c-a206-f5346bb5bd80)
I wonder how to fix it, thank you for your reply!
Here is the related document:
[dcd_bug.zip](https://github.com/openmm/openmm/files/13764944/dcd_bug.zip)
By the way, the PDB file is created by OpenMM directly, the related document is here:
[build_pdb.zip](https://github.com/openmm/openmm/files/13765031/build_pdb.zip)

**Comment by peastman** [comment]
Are you sure you loaded the right PDB file into your viewer?  I just loaded 16_water_init.pdb into VMD.  Then I selected "Load Data Into Molecule" and loaded output.dcd.  Everything looks exactly the way it should.

![image](https://github.com/openmm/openmm/assets/4379786/2c1ef1d4-918b-4d01-8d8a-36900bed4f3e)

**Comment by KingOfChuXuan** [comment]
Oh, yes. I tried VMD and it looks right. Maybe it's a bug of ovito. Thank you for your reply!
