### ISSUE TITLE
openmm.OpenMMException: There is no registered Platform called "CUDA"

### ISSUE THREAD

**Issue by OkKakao** [openmm/openmm#4370]
Hi

I ran into this error while I setting up Openmm.

```
Traceback (most recent call last):
  File "/home/compu/pythonProject/PTA/swm4_droplet.py", line 18, in <module>
    platform = Platform.getPlatformByName('CUDA')
  File "/home/compu/anaconda3/envs/pythonProjects/lib/python3.10/site-packages/openmm/openmm.py", line 18453, in getPlatformByName
    return _openmm.Platform_getPlatformByName(name)
openmm.OpenMMException: There is no registered Platform called "CUDA"
```

I tried previous Issue, which was shown in https://github.com/openmm/openmm/issues/3656

```
print(Platform.getPluginLoadFailures())
-> ()
```
This gave empy tuple.

```
print(version.openmm_library_path)
-> /home/compu/anaconda3/envs/pythonProjects/lib
```
This is obviously not plugins directory, I modified bashrc file for modifying environment variable.

```
export OPENMM_PLUGIN_DIR="/home/compu/anaconda3/envs/pythonProjects/lib/plugins"
```

After modification, here's the results
```
print(version.openmm_library_path)
-> /home/compu/anaconda3/envs/pythonProjects/lib

print(Platform.getPluginLoadFailures())

-> ('Error loading library /home/compu/anaconda3/envs/pythonProjects/lib/plugins/libOpenMMCUDA.so: 
libcuda.so.1: cannot open shared object file: No such file or directory', 'Error loading library 

/home/compu/anaconda3/envs/pythonProjects/lib/plugins/libOpenMMRPMDCUDA.so: 
libcuda.so.1: cannot open shared object file: No such file or directory', 'Error loading library 

/home/compu/anaconda3/envs/pythonProjects/lib/plugins/libOpenMMDrudeCUDA.so:
 libcuda.so.1: cannot open shared object file: No such file or directory', 'Error loading library 

/home/compu/anaconda3/envs/pythonProjects/lib/plugins/libOpenMMAmoebaCUDA.so:
 libcuda.so.1: cannot open shared object file: No such file or directory', 'Error loading library 

/home/compu/anaconda3/envs/pythonProjects/lib/plugins/libOpenMMCudaCompiler.so:
 libcuda.so.1: cannot open shared object file: No such file or directory')
```

I checked the file paths and there were those files.
![image](https://github.com/openmm/openmm/assets/101975748/83242f6f-db47-454b-9144-29ebb1b3d317)

What can I try next?

**Comment by peastman** [comment]
libcuda.so is installed with the CUDA driver.  I assume you have an NVIDIA GPU, and you've installed the appropriate driver?  Can you run `nvidia-smi` and post the output?  And also the output of `conda list`.

**Comment by peastman** [comment]
> I can't use nvidia-smi since it is not installed.

That means you don't have a CUDA compatible driver installed.  You can't use CUDA without it.  See https://www.nvidia.com/download/index.aspx.

**Comment by OkKakao** [comment]
> > I can't use nvidia-smi since it is not installed.
> 
> That means you don't have a CUDA compatible driver installed. You can't use CUDA without it. See https://www.nvidia.com/download/index.aspx.

The graphic driver  installed was not compatible with the system, so it was not even booted.

I removed the driver using recovery mode and re-installed nvidia-utils-470 version, and it worked.

The following is the ouput of nvidia-smi.
![image](https://github.com/openmm/openmm/assets/101975748/d70a2966-bdc6-4a92-ae13-c59bc8578b36)

Thank you for helping me!
