### ISSUE TITLE
getEnergyParameterDerivatives returns Empty

### ISSUE THREAD

**Issue by Pkulyte** [openmm/openmm#4372]
There is an issue with obtaining gradients when using getEnergyParameterDerivatives() method. It always returns empty. Everything else works fine.

Here is the code:
`
ENERGY = unit.kilocalories_per_mole
LENGTH = unit.angstroms
FORCE = unit.kilocalories_per_mole / unit.angstrom  

    def _minimize_with_gradient(self, pdb_str, flexible_residue_first=None, flexible_residue_last=None):
        
        pdb = openmm_app.PDBFile(io.StringIO(pdb_str))
        force_field = openmm_app.ForceField("amber99sb.xml")
        constraints = openmm_app.HBonds
        system = force_field.createSystem(pdb.topology, constraints=constraints)
        force = openmm.CustomExternalForce("0.5 * k * ((x-x0)^2 + (y-y0)^2 + (z-z0)^2)")
        force.addGlobalParameter("k", self.stiffness)
        for p in ["x0", "y0", "z0"]:
            force.addPerParticleParameter(p)
        
        if flexible_residue_first is not None and flexible_residue_last is not None:
            for i, a in enumerate(pdb.topology.atoms()):
                ch_rs_ic = (a.residue.chain.id, int(a.residue.id), a.residue.insertionCode)
                if not _is_in_the_range(ch_rs_ic, flexible_residue_first, flexible_residue_last) and a.element.name != "hydrogen":
                    force.addParticle(i, pdb.positions[i])
                
        system.addForce(force)

        integrator = openmm.LangevinIntegrator(0, 0.01, 0.0)
        platform = openmm.Platform.getPlatformByName("CUDA")
        simulation = openmm_app.Simulation(pdb.topology, system, integrator, platform)
        simulation.context.setPositions(pdb.positions)

        ret = {}
        state = simulation.context.getState(getEnergy=True, getPositions=True, getForces=True, getParameters=True, getParameterDerivatives=True)
        ret["einit"] = state.getPotentialEnergy().value_in_unit(ENERGY)
        ret["posinit"] = state.getPositions(asNumpy=True).value_in_unit(LENGTH)
        ret["forcesinit"] = state.getForces(asNumpy=True).value_in_unit(FORCE)
        ret["derivativesinit"] = state.getEnergyParameterDerivatives()

        simulation.minimizeEnergy(maxIterations=self.max_iterations, tolerance=self.tolerance)

        state = simulation.context.getState(getEnergy=True, getPositions=True, getForces=True, getParameters=True, getParameterDerivatives=True)
        ret["efinal"] = state.getPotentialEnergy().value_in_unit(ENERGY)
        ret["pos"] = state.getPositions(asNumpy=True).value_in_unit(LENGTH)
        ret["forces"] = state.getForces(asNumpy=True).value_in_unit(FORCE)
        ret["derivatives"] = state.getEnergyParameterDerivatives()

        print(ret["derivatives"])
        is_empty = len(ret["derivatives"]) == 0  # Check if the derivatives dictionary is empty
        print(is_empty) # ALWAYS RETURNS TRUE! 

        ret["min_pdb"] = self._get_pdb_string(simulation.topology, state.getPositions())

        return ret['min_pdb'], ret
`

The input file first lines looks like this:
ATOM      1  N   ASP B   1      12.544 -18.831  29.248  1.00  0.00           N  
ATOM      2  CA  ASP B   1      13.696 -19.368  29.967  1.00  0.00           C  
ATOM      3  C   ASP B   1      14.527 -18.258  30.611  1.00  0.00           C

Do I need to add something like this?

 force.addGlobalParameter("k", self.stiffness)
_force.addEnergyParameterDerivative("k")_

for p in ["x0", "y0", "z0"]:
  force.addPerParticleParameter(p)
  _force.addEnergyParameterDerivative(p)_

However, it does not seem possible to call method on addEnergyParameterDerivative() on CustomExternalForce..

Could you please tell me what the issue is?

Thank you.

**Comment by peastman** [comment]
CustomExternalForce doesn't support parameter derivatives.  There's no `addEnergyParameterDerivative()` method.  There's an easy workaround though: use CustomCompoundBondForce instead.

```python
force = openmm.CustomCompoundBondForce(1, "0.5 * k * ((x1-x0)^2 + (y1-y0)^2 + (z1-z0)^2)")
force.addGlobalParameter("k", self.stiffness)
force.addEnergyParameterDerivative("k")
```

You can only compute derivatives with respect to global parameters, not per-particle parameters.  For this particular force that isn't a problem, though, because it's just the force on the particle.  $dE/dx0 = -dE/dx1$.

**Comment by Pkulyte** [comment]
Hello @peastman ,

Thank you for the explanation!

Just to confirm, since I need to compute derivatives for per-particle parameters (I do not need a derivative of global parameter "k"), would the following approach be acceptable?

`

        force = openmm.CustomExternalForce("0.5 * k * ((x-x0)^2 + (y-y0)^2 + (z-z0)^2)")

        force.addGlobalParameter("k", self.stiffness)

        for p in ["x0", "y0", "z0"]:
                force.addPerParticleParameter(p)
        system.addForce(force)

        ret = {}
        state = simulation.context.getState(getEnergy=True, getPositions=True, getForces=True, getParameters=True, getParameterDerivatives=True)
        ret["einit"] = state.getPotentialEnergy().value_in_unit(ENERGY)
        ret["posinit"] = state.getPositions(asNumpy=True).value_in_unit(LENGTH)
        ret["forcesinit"] = state.getForces(asNumpy=True).value_in_unit(FORCE)

        simulation.minimizeEnergy(maxIterations=self.max_iterations, tolerance=self.tolerance)

        state = simulation.context.getState(getEnergy=True, getPositions=True, getForces=True, getParameters=True, getParameterDerivatives=True)
        ret["efinal"] = state.getPotentialEnergy().value_in_unit(ENERGY)
        ret["pos"] = state.getPositions(asNumpy=True).value_in_unit(LENGTH)
        ret["forces"] = state.getForces(asNumpy=True).value_in_unit(FORCE)

        # Calculate derivatives for each particle
        pos_init = ret["posinit"]  
        pos_final = ret["pos"] 
        k = self.stiffness
        derivatives = []
        for i in range(len(pos_init)):
            x0, y0, z0 = pos_init[i]
            x, y, z = pos_final[i]
            df_dx = k * (x - x0)
            df_dy = k * (y - y0)
            df_dz = k * (z - z0)
            derivatives.append((df_dx, df_dy, df_dz))
        
        ret["derivatives"] = derivatives
        ret["min_pdb"] = self._get_pdb_string(simulation.topology, state.getPositions())

        return ret['min_pdb'], ret
`

Since as far as I understand, even with CustomCompoundBondForce, I would need to compute derivatives for per-particle parameters myself (addEnergyParameterDerivative doesn't apply here). Therefore, switching CustomCompoundBondForce would not change things here.

Thank you!

**Comment by peastman** [comment]
You don't need to compute them yourself.  Put the CustomExternalForce into its own force group

```python
force.setForceGroup(1)
```

Then when you want the derivatives, just query the forces.

```
derivatives = simulation.context.getState(getForces=True, groups={1}).getForces()
```

That doesn't work for general forces.  It just happens to be true for yours because it has the property $dE/dx_0 = -dE/dx = F_x$.

**Comment by Pkulyte** [comment]
Thank you for the response.

I have tried the approach suggested and would like to clarify the differences in values obtained.

Namely, I have tried the following code:
`

        pdb = openmm_app.PDBFile(io.StringIO(pdb_str))
        force_field = openmm_app.ForceField("amber99sb.xml")
        constraints = openmm_app.HBonds
        system = force_field.createSystem(pdb.topology, constraints=constraints)

        force = openmm.CustomExternalForce("0.5 * k * ((x-x0)^2 + (y-y0)^2 + (z-z0)^2)")
        force.addGlobalParameter("k", self.stiffness)

        for p in ["x0", "y0", "z0"]:
            force.addPerParticleParameter(p)
        
        if flexible_residue_first is not None and flexible_residue_last is not None:
            for i, a in enumerate(pdb.topology.atoms()):
                ch_rs_ic = (a.residue.chain.id, int(a.residue.id), a.residue.insertionCode)
                if not _is_in_the_range(ch_rs_ic, flexible_residue_first, flexible_residue_last) and a.element.name != "hydrogen":
                    force.addParticle(i, pdb.positions[i])

        force.setForceGroup(1)      
        system.addForce(force)

        integrator = openmm.LangevinIntegrator(0, 0.01, 0.0)
        platform = openmm.Platform.getPlatformByName("CUDA")
        simulation = openmm_app.Simulation(pdb.topology, system, integrator, platform)
        simulation.context.setPositions(pdb.positions)

        ret = {}
        state = simulation.context.getState(getEnergy=True, getPositions=True, getForces=True, getParameters=True, getParameterDerivatives=True, groups={1})
        ret["einit"] = state.getPotentialEnergy().value_in_unit(ENERGY)
        ret["posinit"] = state.getPositions(asNumpy=True).value_in_unit(LENGTH)
        ret["forcesinit"] = state.getForces()

        simulation.minimizeEnergy(maxIterations=self.max_iterations, tolerance=self.tolerance)

        state = simulation.context.getState(getEnergy=True, getPositions=True, getForces=True, getParameters=True, getParameterDerivatives=True, groups={1})
        ret["efinal"] = state.getPotentialEnergy().value_in_unit(ENERGY)
        ret["pos"] = state.getPositions(asNumpy=True).value_in_unit(LENGTH)
        ret["forces"] = state.getForces()

        # Calculate derivatives for each particle
        pos_init = ret["posinit"]  
        pos_final = ret["pos"] 
        k = self.stiffness
        derivatives = []
        for i in range(len(pos_init)):
            x0, y0, z0 = pos_init[i]
            x, y, z = pos_final[i]
            df_dx = k * (x - x0)
            df_dy = k * (y - y0)
            df_dz = k * (z - z0)
            derivatives.append((df_dx, df_dy, df_dz))
        
        ret["derivatives"] = derivatives

`

And received the following values:
<img width="1152" alt="Screenshot 2023-12-28 at 23 51 42" src="https://github.com/openmm/openmm/assets/16861291/e1b54f59-f216-4a91-88a6-eebc5340b5c5">
<img width="1147" alt="Screenshot 2023-12-28 at 23 50 40" src="https://github.com/openmm/openmm/assets/16861291/34c36c28-4102-4396-8430-b159a85724bd">

The values do seem somewhat similar (1.0856151580810547 and -10.856151580810547, meaning that 1.0856151580810547 is the derivative for x0 and  -10.856151580810547 is the derivative for x).

However, I have a few questions:
1. I understand that "forces" provide derivatives of x0, y0, z0. Meanwhile, my custom implementation for x, y, z. This explains the difference in +/- sign, but where does the *10 difference come from? I would think it's from 'k' being 10 (after differentiating the formula becomes k*(x−x0))? Which value would be the correct derivative then?
2.  Some values in the "forces" variable seem to have derivatives of (0,0,0) for quite a few particles. This is not the case with my custom implementation although. How this could be explained?

If it does not clarify my issue, I am happy to expand it further. 

Thank you for the help once again.

**Comment by peastman** [comment]
I can't definitely say what you're doing without seeing the complete code, but I suspect they're in different units.  The value returned by `getForces()` is a Quantity with attached units.  It can handle unit conversions automatically.  You must be stripping off the units somewhere, converting it to a simple number in different units from what you use for your own calculation.

I suspect the particles with zero force are hydrogens.  You skip them when building the CustomExternalForce, but not when computing the derivatives.

**Comment by Pkulyte** [comment]
Thank you for your response, that does explain very well.

- Just one last thing to confirm, would it be correct to express the force/gradient as 
"**FORCE = unit.kilocalories_per_mole / unit.angstrom**"? Given that energy and length are expressed in unit.kilocalories_per_mole and unit.angstroms correspondingly. 

- And afterwards obtain the gradients for x,y,z positions per particle with 
"**ret["gradients"] = state.getForces(asNumpy=True).value_in_unit(FORCE)**
 **ret["gradients"] = -(ret["gradients"])**"? Given that getForces() returns gradients for x0,y0,z0 .

Attaching the code:
`

    ENERGY = unit.kilocalories_per_mole
    LENGTH = unit.angstroms
    FORCE = unit.kilocalories_per_mole / unit.angstrom  

    def _minimize_with_gradient(self, pdb_str, flexible_residue_first=None, flexible_residue_last=None):
        
        pdb = openmm_app.PDBFile(io.StringIO(pdb_str))
        force_field = openmm_app.ForceField("amber99sb.xml")
        constraints = openmm_app.HBonds
        system = force_field.createSystem(pdb.topology, constraints=constraints)

        force = openmm.CustomExternalForce("0.5 * k * ((x-x0)^2 + (y-y0)^2 + (z-z0)^2)")

        # self.stiffness is specified in units of kcal/mol/Å²
        force.addGlobalParameter("k", self.stiffness)

        for p in ["x0", "y0", "z0"]:
            force.addPerParticleParameter(p)
        
        if flexible_residue_first is not None and flexible_residue_last is not None:
            for i, a in enumerate(pdb.topology.atoms()):
                ch_rs_ic = (a.residue.chain.id, int(a.residue.id), a.residue.insertionCode)
                if not _is_in_the_range(ch_rs_ic, flexible_residue_first, flexible_residue_last) and a.element.name != "hydrogen":
                    force.addParticle(i, pdb.positions[i])

        force.setForceGroup(1)      
        system.addForce(force)

        integrator = openmm.LangevinIntegrator(0, 0.01, 0.0)
        platform = openmm.Platform.getPlatformByName("CUDA")
        simulation = openmm_app.Simulation(pdb.topology, system, integrator, platform)
        simulation.context.setPositions(pdb.positions)

        ret = {}
        state = simulation.context.getState(getEnergy=True, getPositions=True, getForces=True, getParameters=True, getParameterDerivatives=True, groups={1})
        ret["einit"] = state.getPotentialEnergy().value_in_unit(ENERGY)
        ret["posinit"] = state.getPositions(asNumpy=True).value_in_unit(LENGTH)

        simulation.minimizeEnergy(maxIterations=self.max_iterations, tolerance=self.tolerance)

        state = simulation.context.getState(getEnergy=True, getPositions=True, getForces=True, getParameters=True, getParameterDerivatives=True, groups={1})
        ret["efinal"] = state.getPotentialEnergy().value_in_unit(ENERGY)
        ret["pos"] = state.getPositions(asNumpy=True).value_in_unit(LENGTH)
        ret["gradients"] = state.getForces(asNumpy=True).value_in_unit(FORCE)
        ret["gradients"] = -(ret["gradients"]) # Interested in x,y,z , not in x0,y0,z0 gradients
        
        ret["min_pdb"] = self._get_pdb_string(simulation.topology, state.getPositions())

        return ret['min_pdb'], ret

`

And a snippet of the first lines of a PDB file (system of atoms):
'
ATOM      1  N   ASP B   1      12.544 -18.831  29.248  1.00  0.00           N 
ATOM      2  H   ASP B   1      11.797 -18.253  29.991  1.00  0.00           H
ATOM      3  H2  ASP B   1      12.659 -17.978  28.423  1.00  0.00           H
ATOM      4  H3  ASP B   1      11.777 -19.671  28.867  1.00  0.00           H
ATOM      5  CA  ASP B   1      13.696 -19.368  29.967  1.00  0.00           C 
'


Thank you.

**Comment by peastman** [comment]
I'm not quite sure what question you're asking.  `value_in_unit()` is the correct way to strip units and get a simple number.  It's up to you to choose what units you want.

>  ret["gradients"] = -(ret["gradients"])"? Given that getForces() returns gradients for x0,y0,z0 .

`getForces()` returns the forces on the particle, which are defined as the negative of the gradient.  Is that what you meant?

**Comment by Pkulyte** [comment]
Hello @peastman, thank you, it is all clear now.

**Comment by peastman** [comment]
Ok, great!
