### ISSUE TITLE
Error while compiling with CUDA

### ISSUE THREAD

**Issue by selimsami** [openmm/openmm#4373]
I'm trying to compile openmm on the cluster with CUDA, however, I'm getting the following error.
I don't really understand what this error means.
Do you have an idea what could be wrong?
Let me know if there is an additional info I can give.
Thanks!

I have:
cudatools11.7
cmake 3.28.1

```
[ 25%] Built target CommonKernels
[ 25%] Building CXX object platforms/cuda/sharedTarget/CMakeFiles/OpenMMCUDA.dir/__/__/common/src/CommonKernels.cpp.o
during GIMPLE pass: vect
/global/common/software/m3036/openmm/platforms/common/src/CommonKernels.cpp: In member function 'void OpenMM::CommonCalcGayBerneForceKernel::sortAtoms()':
/global/common/software/m3036/openmm/platforms/common/src/CommonKernels.cpp:5371:6: internal compiler error: in vect_get_vec_defs_for_operand, at tree-vect-stmts.c:1450
 5371 | void CommonCalcGayBerneForceKernel::sortAtoms() {
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
0x6879f5 vect_get_vec_defs_for_operand(vec_info*, _stmt_vec_info*, unsigned int, tree_node*, vec<tree_node*, va_heap, vl_ptr>*, tree_node*)
	../../cpe-gcc-11.2.0-202108140355.9bf1fd589a5c1/gcc/tree-vect-stmts.c:1450
0xf1f4a4 vect_build_gather_load_calls
	../../cpe-gcc-11.2.0-202108140355.9bf1fd589a5c1/gcc/tree-vect-stmts.c:2728
0xf1f4a4 vectorizable_load
	../../cpe-gcc-11.2.0-202108140355.9bf1fd589a5c1/gcc/tree-vect-stmts.c:8718
0xf28350 vect_transform_stmt(vec_info*, _stmt_vec_info*, gimple_stmt_iterator*, _slp_tree*, _slp_instance*)
	../../cpe-gcc-11.2.0-202108140355.9bf1fd589a5c1/gcc/tree-vect-stmts.c:10922
0xf2c0f1 vect_transform_loop_stmt
	../../cpe-gcc-11.2.0-202108140355.9bf1fd589a5c1/gcc/tree-vect-loop.c:9214
0xf4397d vect_transform_loop(_loop_vec_info*, gimple*)
	../../cpe-gcc-11.2.0-202108140355.9bf1fd589a5c1/gcc/tree-vect-loop.c:9650
0xf6bbdc try_vectorize_loop_1
	../../cpe-gcc-11.2.0-202108140355.9bf1fd589a5c1/gcc/tree-vectorizer.c:1104
0xf6c7c1 vectorize_loops()
	../../cpe-gcc-11.2.0-202108140355.9bf1fd589a5c1/gcc/tree-vectorizer.c:1243
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <https://gcc.gnu.org/bugs/> for instructions.
make[2]: *** [platforms/cuda/sharedTarget/CMakeFiles/OpenMMCUDA.dir/build.make:301: platforms/cuda/sharedTarget/CMakeFiles/OpenMMCUDA.dir/__/__/common/src/CommonKernels.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:4621: platforms/cuda/sharedTarget/CMakeFiles/OpenMMCUDA.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

**Comment by peastman** [comment]
It means what it says: you found a bug in the compiler!  Follow the directions at the URL they gave for how to report it.

**Comment by sef43** [comment]
Is this a managed cluster? Can you try using a different compiler tool chain? I would suggest raise an issue with the cluster support team about the bug

I just tested building from source on a Cray-EX with cpe-gcc-11.2 and I cannot reproduce the bug

**Comment by selimsami** [comment]
Thanks both. I was just wondering if there was a known incompatibility.
This is on the Perlmutter cluster, @peastman, maybe you have experience with it?

I tried different versions of GNU compiler and still got the same error.

I also tried Intel and NVIDIA compilers, which in both cases managed to compile.
However, in both cases I got the following error while running a test case:

```
Traceback (most recent call last):
  File "/global/u1/s/ssami/openmm_test/gpu_test/test.py", line 28, in <module>
    simulation = Simulation(modeller.topology, system, integrator, platform)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/s/ssami/.conda/envs/test/lib/python3.11/site-packages/openmm/app/simulation.py", line 104, in __init__
    self.context = mm.Context(self.system, self.integrator, platform)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/s/ssami/.conda/envs/test/lib/python3.11/site-packages/openmm/openmm.py", line 7810, in __init__
    _openmm.Context_swiginit(self, _openmm.new_Context(*args))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
openmm.OpenMMException: Error compiling program: default_program(698): error: no instance of overloaded function "dot" matches the argument list
            argument types are: (real4, real4)

default_program(703): error: no instance of overloaded function "dot" matches the argument list
            argument types are: (real4, real4)

2 errors detected in the compilation of "default_program".
```

Is this something anyone has encountered before? It's still not clear to me what is wrong based on the error message.

**Comment by peastman** [comment]
Which version of the code are you compiling?  That looks like an error I got while working on #4354, but I fixed it before it was merged.

**Comment by selimsami** [comment]
Ah it seems that I had an earlier version. It works now, thank you! 

Final question before closing this issue, what kind of a difference do you expect between Reference and CUDA double precision energies/forces?

My single point (no atom or drude optimization) water dimer energies differ in the 3rd decimal (-16.101770 vs -16.102918 kJ/mol). Is that expected?

**Comment by peastman** [comment]
The energy of just two water molecules should match to many significant digits.  Something else must be different.

**Comment by selimsami** [comment]
I attach a test case where I only change the platforms.

Energies I get are:
Reference:  -16.275236328479682 kJ/mol 
CUDA: -16.276383391124902 kJ/mol 

Do you either have different results or an explanation for what might be happening?

Thanks again for your help.

[test_cuda.zip](https://github.com/openmm/openmm/files/13814985/test_cuda.zip)

**Comment by selimsami** [comment]
Also to note:

With `python -m openmm.testInstallation`, I get: 
Reference vs. CPU: 6.32306e-06
Reference vs. CUDA: 6.73449e-06
CPU vs. CUDA: 6.60847e-07

Few tests fail:
	 15 - TestReferenceCustomGBForce (Failed)
	188 - TestCpuCustomGBForce (Failed)
	190 - TestCpuCustomNonbondedForce (Failed)  (exception: Assertion failure at TestCustomNonbondedForce.h:70.   Expected [-1.2, 0, 0], found [0, 0, 0])

Especially the 'TestCpuCustomNonbondedForce' is a bit worrisome but I am not using the CPU plaform in this test case.

**Comment by selimsami** [comment]
@peastman, tried it on a different computer cluster (no failed tests this time), different GPUs, compilers and everything, I get the exact same CUDA energy as before, which is still different than the Reference energy and the OpenCL energy is also different than both.

**Comment by peastman** [comment]
Even when you tell it to do calculations in double precision, the CUDA platform still stores most per-particle and per-bond parameters in single precision.  That causes small differences when you specify their values to more than seven digits.  For example, the CustomBondForce gives slightly different values starting in the sixth decimal place:

```
Platform: reference
Bond 0.2665147286685029
Platform: cuda
Bond 0.2665127753202406
```

But if I force the parameters to be representable in single precision

```python
r0 = np.float32(r0)
b_param = np.float32(b_param)
```

then they agree perfectly:

```
Platform: reference
Bond 0.2665127753202406
Platform: cuda
Bond 0.2665127753202406
```

**Comment by selimsami** [comment]
Thanks Peter, this fixed the issue with bonds and angles (which already had quite minor discrepancies), but most other terms are still not the same between reference and CUDA even though I made all parameters float32. 

More problematically, I tested my system in condensed phase, with Reference platform I can converge shell particles to RMSD force of 1e-7. However with CUDA, it only converges down to 1e-3. 

I attach both the dimer and condensed phase systems in case you get a chance to look at them.

[openmm_cuda_test.zip](https://github.com/openmm/openmm/files/13836859/openmm_cuda_test.zip)

**Comment by selimsami** [comment]
Hi @peastman, I've been trying to figure this one out and kinda got stuck. 
I'd appreciate any help you could provide.

**Comment by peastman** [comment]
That's really subtle!  The difference again comes from storing the per-particle parameters in single precision.  Here's the actual code it generates to compute the energy.

```c++
real custom5_temp6 = custom5_params11*custom5_params12;
real custom5_temp7 = custom5_globals[0]*custom5_temp6;
real custom5_temp8 = custom5_temp7*invR;
real customEnergy = custom5_temp8;
```

`custom5_params11` and `custom5_params12` are the charges, and `custom5_globals[0]` is `ONE_4PI_EPS0`.  Since it's in double precision mode, `real` is a typedef for `double`, but the charges are `float`.  Notice what happens in the first line.  It multiplies the charges together, and because the inputs are single precision, it also represents the result in single precision before converting it to double and assigning it to the output variable.  That's different from the reference platform, where everything is in double from the start.  Representing the product in double precision gives 8.702460718780804.  But representing it in single precision and then converting it to double gives 8.70246028900146.

I can modify how it generates the code so the conversion happens before the multiplication:

```c++
real custom5_temp6 = ((real) custom5_params11)*((real) custom5_params12);
```

That leads to excellent agreement between the energies

**Comment by selimsami** [comment]
Thanks again Peter. 

So what is a good solution if I want to ensure that both CUDA and Reference are giving me the same results? - I guess I could use float16 for the parameters for testing purposes, is there another option?

Is it not possible to request that CUDA per-particle parameters are also in double precision?

I want to check next whether the differences I see in the condensed phase are also due to this issue or something else is happening. A bit worried about the low convergence of CUDA compared to the Reference.

**Comment by peastman** [comment]
I don't think you can effectively work around it from the outside.  I'll make the changes so that it preserves full accuracy in doing the multiplication.

It's hard to see how this would affect minimization.  It's still computing a well defined potential in double precision, just with a very slightly different interaction strength.

**Comment by selimsami** [comment]
Thanks! 

I think the same, but having the same single point energy will be useful in narrowing down the difference.
Perhaps you are already aware of other differences in precision between CUDA and reference that could effect the optimization?

**Comment by peastman** [comment]
The fix is in #4392.  Running your test with these changes, here is the total energy with each platform.

Reference
-16.2752252108215
CUDA
-16.275225210824793

They agree to 13 significant digits.

**Comment by selimsami** [comment]
Awesome @peastman!

I have tested it, agreement has definitely improved in the condensed phase and interestingly CUDA now converges to 1e-7. I have some ideas precision of parameters might have improved this.

There is however one final difference. In the condensed phase all energies agree up to 12 digits if I use CutoffPeriodic. But if I use PME, this is only up to 6th digit, which then during the shell minimization lead to slightly different energies.

It's not very significant but if you have an idea why CUDA and Reference PME would lead to slightly different energies, that would be interesting to address.

**Comment by peastman** [comment]
Are they using the same grid dimension?  Call `getPMEParametersInContext()` to check.

PME is a much more complicated calculation with a lot more places things could diverge.  Is the difference in direct space, reciprocal space, or both?

**Comment by selimsami** [comment]
It was:
[3.372060287522547, 32, 32, 32] (CUDA)
vs
[3.372060287522547, 31, 31, 31] (Reference)

Setting them both to CUDA values did not reduce the difference in energies noticeably.

Checking with setIncludeDirectSpace(False), the difference appears at the 11th digit,  so it seems the main difference is due to the direct space.

**Comment by peastman** [comment]
How do you modify the script to use PME?  There's no NonbondedForce, only CustomNonbondedForces.  I do see some commented out code for a NonbondedForce.  Should I switch it to use that?  One of the commented out lines is obviously incorrect:

```python
#     point_es_term.createExceptionsFromBonds(bonds, 10, lj14Scale=0)
```

You don't really mean it to multiply the Coulomb interaction for 1-4 pairs by 10, do you?

**Comment by selimsami** [comment]
It's the `test_cuda_condensed.py` file in the last ZIP I shared. It should already be using PME.
But here's the updated file with my latest changes.

I don't have any 1-4 interactions in the system, so I don't think it matters, but I corrected the statement after you pointed it out.

[openmm_cuda_test.zip](https://github.com/openmm/openmm/files/13956869/openmm_cuda_test.zip)

**Comment by selimsami** [comment]
Sorry I had the wrong file:

[test_cuda_condensed.zip](https://github.com/openmm/openmm/files/13956887/test_cuda_condensed.zip)

**Comment by peastman** [comment]
That took a good bit of debugging to track down!  The problem is in your virtual site definition:

```python
site = ThreeParticleAverageSite(h1_c.index, o_c.index, h2_c.index, np.float32(0.2847805118330395), np.float32(1-2*0.2847805118330395), np.float32(0.2847805118330395))
```

The effect of converting each of the weights to single precision independently is that they add up to 0.99999997019769 rather than 1.  When you run a simulation with periodic boundary conditions, the CUDA platform internally translates all the coordinates to put them inside a single periodic box.  If your weights exactly added up to 1, translating each particle by a box vector would translate the virtual site by exactly the same box vector.  But since they don't quite add up to 1, it produces a tiny change in the position of the virtual site.

Remove the `np.float32()` conversions in your code and the agreement in the forces gets much better.

**Comment by selimsami** [comment]
Wow that's some debugging skills! Thanks for that. And the translation is done only in the case of PME? Why only PME energies are affected?

I'll close this issue since everything is addressed.

I guess it's slightly confusing that some FF terms have to be provided as float32 and some shouldn't, but this is super niche stuff that probably no one else will encounter. I also never really understood why the 3rd weight has to be provided for ThreeParticleAverageSite, shouldn't it always be 1-a-b?

**Comment by peastman** [comment]
The translation is done whenever you use periodic boundary conditions.  CutoffPeriodic has the same issue.

Keep in mind that you never *have* to use float32 for anything.  That's only if you want to get the absolute best possible agreement between the platforms.  Both platforms still do calculations in double precision, and each one is computing a potential function and its gradients to very high accuracy.  It's just that they use very slightly different potential functions.
