### ISSUE TITLE
What should I do to perform infinitely-long-CNT simulation?

### ISSUE THREAD

**Issue by OkKakao** [openmm/openmm#4378]
Hi.

I'm trying to perform Carbon Nano Tube (CNT) simulation with Z-direction periodicity.

I generated input CNT files using CHARMM Nanomaterial modeler with Z periodicity.

Here's the input made by CHARMM.
[charmm-gui-0419573623.zip](https://github.com/openmm/openmm/files/13809573/charmm-gui-0419573623.zip)

Before simulation, a periodic box vector is added to the pdb file since there is no specified pbc in the file.

```
CRYST1   40.000   40.000   40.000  90.00  90.00  90.00 P 1           1
```

I simulated the system with the following code.

```
from openmm.app import *
from openmm import *
from openmm.unit import *
from sys import stdout

name = 'CNT_54_Cl'

params = CharmmParameterSet('../parameters/par_all36_cgenff.prm', 'tip3p.str')
pdb = PDBFile(f'{name}.pdb')
box = pdb.topology.getPeriodicBoxVectors()
psf = CharmmPsfFile(f'{name}.psf')
psf.setBox(box[0][0], box[1][1], box[2][2])

platform = Platform.getPlatformByName('CUDA')
system = psf.createSystem(params, nonbondedMethod=PME)

integrator = LangevinMiddleIntegrator(300*kelvin, 1/picosecond, 0.002*picoseconds)
simulation = Simulation(psf.topology, system, integrator, platform)
simulation.context.setPositions(pdb.positions)
simulation.minimizeEnergy()
simulation.reporters.append(PDBReporter('test.pdb', 1000))
simulation.reporters.append(StateDataReporter(stdout, 1000, step=True, potentialEnergy=True, temperature=True))
simulation.step(100000)
```

The starting structure is the following
![image](https://github.com/openmm/openmm/assets/101975748/b79f6605-86cc-411c-ae87-80bac048925d)

And the output is the following.
![image](https://github.com/openmm/openmm/assets/101975748/324dc04d-8f4b-44a6-b6ca-858d63a4c87e)

And here's the output file.
[test.zip](https://github.com/openmm/openmm/files/13809951/test.zip)

What did I missed?

Thank you

**Comment by selimsami** [comment]
I am not sure if this solves your issue but why did you set the box dimensions to 40.0 40.0 40.0? 
sysinfo.dat says 40.0, 40.0, 38.176 for the solvated box
step1_nanomaterial.str says 5.472, 5.472, 38.176 for the CTN-only system

**Comment by OkKakao** [comment]
> I am not sure if this solves your issue but why did you set the box dimensions to 40.0 40.0 40.0? sysinfo.dat says 40.0, 40.0, 38.176 for the solvated box step1_nanomaterial.str says 5.472, 5.472, 38.176 for the CTN-only system

I modified the PBC but still didn't work.

Thanks for the information.

But I found that I have to use setUsesPeriodicBoundaryConditions() function for the forces of the system.

```
for i in range(system.getNumForces()):
    if type(system.getForce(i)) in [HarmonicBondForce, HarmonicAngleForce, PeriodicTorsionForce]:
        system.getForce(i).setUsesPeriodicBoundaryConditions(True)
```

This was done by adding this code.
