### ISSUE TITLE
Custom nonbonded force for tabulated function of distance, r

### ISSUE THREAD

**Issue by hmaity** [openmm/openmm#4381]
Hi, I am trying to create a custom nonbonded force for which I have a tabulated energy value as a function of distance, r, between two types of particle. However, I do not have an analytical energy function to the potential energy form. Can I use the openmm custom nonbonded force object to set up the simulations? Or, is there any other options to take into account the Tabulated energy values in the force object? Thank you.

**Comment by peastman** [comment]
Yes, that's exactly what [CustomNonbondedForce](docs.openmm.org/latest/api-python/generated/openmm.openmm.CustomNonbondedForce.html) is for.  Use a [Continuous1DFunction](http://docs.openmm.org/latest/api-python/generated/openmm.openmm.Continuous1DFunction.html) to define the tabulated function.
