### ISSUE TITLE
Usage of NonBondedForce.setIncludeDirectSpace(False)

### ISSUE THREAD

**Issue by selimsami** [openmm/openmm#4387]
Hi,

I've created a very simple test case where I have 3 Coulomb forces:

1) NonBondedForce with PME
2) CustomNonbondedForce of a Coulomb potential with PeriodicCutoff
3) NonBondedForce.setIncludeDirectSpace(False) with PME

So if I'm not mistaklen, Force1 should be the sum of Force2 and Force3

Force1 and Force2 has values that I would except. Force3 seems completely off though.

Is this a bug? or am I missing something?

Thanks!

[test_includedirectspace.zip](https://github.com/openmm/openmm/files/13881756/test_includedirectspace.zip)

**Comment by peastman** [comment]
The direct space part of PME is not the same as the total energy.  It's scaled by $\text{erfc}(\alpha r)$.  See [the manual](http://docs.openmm.org/latest/userguide/theory/02_standard_forces.html#nonbondedforce) for details.

**Comment by selimsami** [comment]
Thanks Peter, I added the scaling to the direct space contribution Force2, but the Force3 is still extremely large and Force2 and Force3 do not sum up to Force1. What am I still missing? See the updated file.

[test_includedirectspace2.zip](https://github.com/openmm/openmm/files/13891382/test_includedirectspace2.zip)


Also, I think you have small typo in the manual: Reciprocal space equation in 19.6.4 should be divided by k squared rather than m squared.

**Comment by peastman** [comment]
Yeah, this is kind of confusing.  The difference comes from the exceptions.  When you add an exception to a NonbondedForce, it means the interaction between a pair of particles should be computed with different parameters.  But there's no way to do that in reciprocal space.  PME spreads charge onto a grid and computes the interaction of the grid points with each other.  There's no way to distinguish which bit of charge came from which particle.  So it always includes all interactions, regardless of exceptions.

To compensate for that, we subtract them back off in real space.  For most pairs of particles, we add $\text{erfc}(\alpha r)$ times the regular Coulomb energy.  But for pairs that have exceptions, we instead *subtract* $\text{erf}(\alpha r)$ times the Coulomb energy, that being the energy that was incorrectly added in reciprocal space.  You can use a CustomBondForce to do the same thing.

By the way, take a careful look at the API docs for `NonbondedForce.createExceptionsFromBonds()`.  The second argument is the scale factor to apply to the Coulomb part of 1-4 interactions, *not* a number of bonds.

**Comment by selimsami** [comment]
Thanks, that makes sense, a bit fiddly though haha. 

However, I am still unable to get the right energy. Probably more things missing? 

[test_includedirectspace3.zip](https://github.com/openmm/openmm/files/13895867/test_includedirectspace3.zip)

Wouldn't it also make sense to do all these corrections automatically when someone requests NonBondedForce.setIncludeDirectSpace(False)?

**Comment by peastman** [comment]
You're almost there.  You're just missing one exception in each molecule.  Add this line

```python
        bond_force.addBond(h1.index, h2.index, [q_h*q_h])
```

and then you get perfect agreement.

```
Point Electrostatics Combined -16738.596759002205 kJ/mol
Point Electrostatics SR -15283.173279924033 kJ/mol
Exception correction 84096.7892801077 kJ/mol
Point Electrostatics LR -85552.21275918589 kJ/mol

total combined: -16738.596759002205
total split: -16738.59675900222
```

**Comment by peastman** [comment]
> Wouldn't it also make sense to do all these corrections automatically when someone requests NonBondedForce.setIncludeDirectSpace(False)?

The correction is computed in direct space, so if you say not to do direct space calculations, it doesn't get included.  I know, it's confusing since it's a correction to the reciprocal space term and therefore conceptually seems like it should be part of the reciprocal space calculation.  But that isn't where it's computed.

**Comment by selimsami** [comment]
> bond_force.addBond(h1.index, h2.index, [q_h*q_h])

Oh my bad, thanks for catching that.

> The correction is computed in direct space, so if you say not to do direct space calculations, it doesn't get included. I know, it's confusing since it's a correction to the reciprocal space term and therefore conceptually seems like it should be part of the reciprocal space calculation. But that isn't where it's computed.

That makes sense. And splitting the SR / LR Coulomb is special enough case that it's okay that it's involved to do it.
But considering my starting point was just adding a C6 PME term without C12 (#4349), I wonder if that should be somewhat easier (specially considering openmm already only uses C6 term for PME). 

(side note - actually now I'm thinking with respect to #4349 it might be better to have a normal LJ PME with both SR and LR  with an arbitrary C12 and then just subtract the C12 term with a custom force)


But I don't really mind the additional steps - what I wonder is the computation cost. Do you think I'm accruing a lot more computational cost by for example splitting the Coulomb term this way with all the additional force terms? Or is that done efficiently inside openmm that it doesn't make much difference? Does it also depend on the platform?

**Comment by peastman** [comment]
> it might be better to have a normal LJ PME with both SR and LR with an arbitrary C12 and then just subtract the C12 term with a custom force

That would certainly be the simplest way to implement it.  The performance will be a bit worse because you're paying the cost of computing repulsion three times: once to add the C12 term, once to subtract it again, and once to compute whatever form you actually want to use.

Generally speaking, the cost of a CustomNonbondedForce is very similar to NonbondedForce, assuming they compute exactly the same function.  There's one extra twist though, if you really want to get down into the details and get the fastest possible performance.  erfc() is an expensive function to compute.  When working in single precision, we instead use an approximation that's almost as accurate but a lot faster:

https://github.com/openmm/openmm/blob/71b2a93e09d9d5f110310448c9ff503eb2e71d55/platforms/common/src/kernels/coulombLennardJones.cc#L12-L21
