### ISSUE TITLE
Can openmm automatically find multiple faster GPUs?

### ISSUE THREAD

**Issue by 9527567** [openmm/openmm#4388]
When I submit a computing task in Slurm, do not force exclusive nodes, and then apply for multiple GPUs, I only know the GPU ID after applying. Is it possible to only provide the number of GPUs and let it automatically select?

**Comment by everyday847** [comment]
This sounds like a task first and foremost for python outside of openmm; the most generic option would be to parse nvidia-smi output to determine each visible device and its current load, but I bet you there is a library you could use for that.

**Comment by peastman** [comment]
Queuing systems generally set CUDA_VISIBLE_DEVICES so you only see the devices allocated to your job.  For example, if you asked for two GPUs, OpenMM will see them as devices 0 and 1, whichever ones they happen to be.
