### ISSUE TITLE
While it is reading the pdb file it is throwing error. Openmm=8

### ISSUE THREAD

**Issue by The4thOne** [openmm/openmm#4389]
I was trying to read some PDB files. But I am not sure why it is not reading it correctly in openmm=8. It shows the positions partially, but not all of them.
 
I tried loading with mdtraj, and it loaded properly there.
I am attaching the zip file with the code and input PDB files.

[Test2.zip](https://github.com/openmm/openmm/files/13886750/Test2.zip)

Even a small PDB like the following is showing only 2 positions.

ATOM      0  P   STK A   0      10.000  10.000  10.000  1.00  0.00           P
ATOM      1  C   STK A   0      10.000  15.100  10.000  1.00  0.00           C
ATOM      2  C   STK A   0      10.000  15.100  13.800  1.00  0.00           C
ATOM      3  P   STK A   0      10.000  20.200  13.800  1.00  0.00           P
ATOM      4  C   STK A   0      10.000  15.100  17.600  1.00  0.00           C
ATOM      5  C   STK A   0      10.000  15.100  21.400  1.00  0.00           C
ATOM      6  C   STK A   0      10.000  15.100  25.200  1.00  0.00           C
ATOM      7  C   STK A   0      10.000  15.100  29.000  1.00  0.00           C
ATOM      8  C   STK A   0      10.000  15.100  32.800  1.00  0.00           C
ATOM      9  P   STK A   0      10.000  20.200  32.800  1.00  0.00           P
ATOM     10  C   STK A   0      10.000  15.100  36.600  1.00  0.00           C
ATOM     11  P   STK A   0      10.000  10.000  36.600  1.00  0.00           P

Note: It is loaded properly with openmm=7.6 and worked as well. Even 7.7 is not working.

**Comment by peastman** [comment]
When I load your file, my console fills up with pages of warnings like this:

> /Users/peastman/miniconda3/envs/openmm/lib/python3.9/site-packages/openmm/app/internal/pdbstructure.py:537: UserWarning: WARNING: duplicate atom (ATOM      2  C   STK A   0      10.000  15.100  13.800  1.00  0.00           C  , ATOM      1  C   STK A   0      10.000  15.100  10.000  1.00  0.00           C  )

The warning means what it says: you have duplicate lines for the same atom.  Every atom in a residue must have a unique name.  If it finds two lines with the same name, it assumes they're alternate locations for the same atom.  But in that case there really ought to be alternate location identifiers as well, and since there aren't it shows a warning.

**Comment by The4thOne** [comment]
Got it!
Thank you.
