### ISSUE TITLE
Stack smashing when use the ParsedExpression::createCompiledExpression()

### ISSUE THREAD

**Issue by yongyouhe** [openmm/openmm#4390]
Hi, I tried to write an integrator plugin, but encountered an error `*** stack smashing detected ***: <unknown> terminated` when trying to call the function `Lepton::Parser::parse(kineticEnergy).createCompiledExpression();` within the constructor of the class. Could you please provide insights into what might be causing this issue?
I have checked the other part of the constructor. Only when I call the function ParsedExpression::createCompiledExpression(), comes the error. The function createCompiledExpression() is in the class lepton/ParsedExpression.h.
The OpenMM version is 7.7.0.
The constructor codes are shown below.
```
ImageCustomIntegrator::ImageCustomIntegrator(double stepSize, int numCells) : globalsAreCurrent(true), forcesAreValid(false) {
    setStepSize(stepSize);
    setConstraintTolerance(1e-5);
    setRandomNumberSeed(0);
    cout<<"set random seed done!"<<endl;
    //setKineticEnergyExpression("m*v*v/2");
    //Lepton::CompiledExpression expr = Lepton::Parser::parse(kineticEnergy).createCompiledExpression();
    Lepton::ParsedExpression expr1 = Lepton::Parser::parse("m*v*v/2");
    cout<<"parse done!"<<endl;
    expr1.createCompiledExpression();
    cout<<"compiled expr done!"<<endl;
    //Lepton::Parser::parse("m*v*v/2").createCompiledExpression();
    //cout<<"set kinetic expression done!"<<endl;
    setNumCells(numCells);
    setUseImageParticle(true);
    cout<<"ImageCustomIntegrator init done!"<<endl;
}
```

**Comment by yongyouhe** [comment]
I have tested the ParsedExpression::createCompiledExpression() with a minimal code. The error still exists.
```
#include "OpenMM.h"
#include "lepton/CompiledExpression.h"
#include "lepton/CustomFunction.h"
#include "lepton/ExpressionProgram.h"
#include "lepton/ExpressionTreeNode.h"
#include "lepton/Operation.h"
#include "lepton/ParsedExpression.h"
#include "lepton/Parser.h"
#include <iostream>
using namespace std;
int main(){
    
    Lepton::ParsedExpression ex = Lepton::Parser::parse("x+y^2");
    Lepton::CompiledExpression expr = ex.createCompiledExpression();
    for(const auto& str : expr.getVariables()){
        cout<<str<<endl;
    }
    return 0;
}
```
The following are the output and error messages.
```
m
v
*** stack smashing detected ***: <unknown> terminated
Aborted (core dumped)
```

**Comment by peastman** [comment]
How did you compile your code, and how did you install OpenMM?  This most likely indicates a binary incompatibility of some sort: your code and the library it invokes were compiled in different ways that make them somehow incompatible with each other.  The result is memory corruption.

**Comment by yongyouhe** [comment]
> How did you compile your code, and how did you install OpenMM? This most likely indicates a binary incompatibility of some sort: your code and the library it invokes were compiled in different ways that make them somehow incompatible with each other. The result is memory corruption.

I used conda to install the OpenMM. My code is compiled with gcc 7.5.0. They are in the same virtual conda envs. Should I try to compile OpenMM from the source code?

**Comment by yongyouhe** [comment]
I have tried to use the OpenMM compiled from the source code, but the issue still persists. The simple test code is compiled with `g++ -I/home/yyh/miniconda3/envs/openmm/include ./test.cpp -o test -L/home/yyh/miniconda3/envs/openmm/lib -lOpenMM -Wl,-R /home/yyh/miniconda3/envs/openmm/lib`

**Comment by craabreu** [comment]
This happens, I guess, because `lepton/CompiledExpression.h` is installed in your conda environment without any preprocessing. For this reason, depending on your OpenMM installation, you need to define `LEPTON_USE_JIT` and either `__ARM__` or `__ARM64__` when compiling the plugin. The problem is that you may also need one of the `asmjit` header files. In my conda env, at least, these headers are missing.

**Comment by yongyouhe** [comment]
> This happens, I guess, because `lepton/CompiledExpression.h` is installed in your conda environment without any preprocessing. For this reason, depending on your OpenMM installation, you need to define `LEPTON_USE_JIT` and either `__ARM__` or `__ARM64__` when compiling the plugin. The problem is that you may also need one of the `asmjit` header files. In my conda env, at least, these headers are missing.

Thank you! You are right. The issue lies with Lepton_USE_JIT.

**Comment by yongyouhe** [comment]
The issue was resolved after I added the code in CMakeList.txt.
```
IF(X86 AND NOT (WIN32))
    FILE(GLOB src_files ${CMAKE_CURRENT_SOURCE_DIR}/libraries/asmjit/*/*.cpp)
    FILE(GLOB incl_files ${CMAKE_CURRENT_SOURCE_DIR}/libraries/asmjit/*.h)
    SET(SOURCE_FILES ${SOURCE_FILES} ${src_files})
    SET(SOURCE_INCLUDE_FILES ${SOURCE_INCLUDE_FILES} ${incl_files})
    INCLUDE_DIRECTORIES(BEFORE "${CMAKE_CURRENT_SOURCE_DIR}/libraries/asmjit")
    SET(EXTRA_COMPILE_FLAGS "${EXTRA_COMPILE_FLAGS} -DLEPTON_USE_JIT")
ENDIF()
```
Also, the asmjit files need to be manually added in the plugin project, because OpenMM did not generate corresponding libraries and header files for them.
