### ISSUE TITLE
Control number of CPU threads 

### ISSUE THREAD

**Issue by SchroedingersLion** [openmm/openmm#4391]
Greetings,

I am a bit confused about the number of CPU threads OpenMM uses. I try to control it from within the code using the corresponding platform property `Threads`, but when examining the number of threads associated to the launched process, Linux sees the wrong number. If I set the property to 1, Linux gives 51 threads. If I set it to 2, it gives 52 threads.  It looks as if 50 threads are always launched by default... I am using the linux command `ps -o thcount <PID>` to view the number of threads. 
With `htop`, however, the CPU work load is ~140% for one thread, and ~240 % for two threads, which makes more sense. Can someone shed light on what happens here?

OpenMM version 8.0.0

This is my minimal script:
```python
import openmm
from openmm import app, unit
from openmm.app import ForceField
import openmmtools as tools
import numpy as np

#Simulation parameters
timestep = 2* unit.femtoseconds

n_iterations = 10000
collision_rate = 0.5 / unit.picoseconds  
temperature = 300 * unit.kelvin

# load some system (already energy-minimized)
pdb_path = '1AKI_minimized.pdb' 
pdb = app.PDBFile(pdb_path)

forcefield = ForceField("amber14-all.xml", "amber14/tip3p.xml")

platform = openmm.Platform.getPlatformByName('CPU')  # will it use a single CPU?
n_threads = '1'  # number of threads

# create system and prepare simu
system = forcefield.createSystem(pdb.topology, nonbondedMethod=app.PME, rigidWater=True, 
                                 constraints=app.HBonds)

integrator = openmm.LangevinIntegrator(temperature, collision_rate, timestep)

simulation = app.Simulation(pdb.topology, system, integrator, platform, {'Threads': n_threads}) # set thread number

simulation.context.setPositions(pdb.positions)


# run simulation
simulation.step(n_iterations)

```

**Comment by SchroedingersLion** [comment]
If I just run a normal python program (no OpenMM), I only observe a single thread.

What I observe in the OpenMM case is that most of the displayed threads are "sleeping". It might indeed only use `Threads` threads at any given point in time, but is it possible that it tries to spawn more than for all the other CPU cores?

**Comment by peastman** [comment]
It creates threads for a variety of purposes, so the number will be larger than what you specify.  But I don't know any reason it would be that much larger.

**Comment by jamesmkrieger** [comment]
Are you sure n_threads should be a string?

I am trying to do this now and I'm also getting all threads used. I can change that with environment variable OPENMM_CPU_THREADS but I can't get it to change from instead the Python API

**Comment by peastman** [comment]
Yes, it's a string.  The environment variable sets the default value of the `"Threads"` property.

https://github.com/openmm/openmm/blob/6c6bc628bf95bb9ec90344400a671c55a4a6d5b1/platforms/cpu/src/CpuPlatform.cpp#L79-L85

You can check what value is actually being used by your Context.

```python
print(platform.getPropertyValue(simulation.context, 'Threads'))
```

**Comment by jamesmkrieger** [comment]
Thanks. I've figured it out now and I can get it to only use the threads I ask for.

**Comment by peastman** [comment]
Great!

I'm going to close this issue, since I believe all questions in it have been answered.  @SchroedingersLion if I missed something, feel free to reopen it.

**Comment by jamesmkrieger** [comment]
I am wondering how to limit the number of threads in PDBFixer. Is this possible?

**Comment by peastman** [comment]
PDBFixer doesn't create any threads beyond what OpenMM creates.  If you use the web UI, the web server probably creates some additional threads.

**Comment by jamesmkrieger** [comment]
I'm using it inside the Python API as part of ProDy where we have a module called ClustENM (https://github.com/jamesmkrieger/ProDy/blob/scipion_minim/prody/dynamics/clustenm.py)

I was hoping to limit the threads throughout the whole thing and one of the last steps now is the fixer.

**Comment by jamesmkrieger** [comment]
There is a platform argument in modeller.addHydrogens, but this isn't exposed to PDBFixer.addMissingHydrogens and neither of them have options like Threads

**Comment by peastman** [comment]
If you want to limit the number of threads through the whole program, `OPENMM_CPU_THREADS` is one way to do it.  Alternatively, you can set the default number of threads on the CPU platform.

```python
Platform.getPlatformByName('CPU').setPropertyDefaultValue('Threads', '1')
```

**Comment by jamesmkrieger** [comment]
Thank you. The latter option sounds perfect!
