### ISSUE TITLE
Adding motion restraints (mass = 0) to a range of positions.

### ISSUE THREAD

**Issue by pguillem** [openmm/openmm#4394]
Good day everyone.

I have a protein complex made of chunks from a bigger system, where the first 15 residues of a protein receptor come from a much bigger loop (structurally irrelevant for the purpose of the simulation).

Because of structural constraints (biologically) these 15 residues are suposed stay where they are. Not move around.

I read that a way to do this is to set the mass of every atom to 0, from residues 1 to 15, for example: But I've never done this before.  I'm creating the system from amber PRMTOP/INPCRD files, previously created using Tleap. Should the restraints be applied in TLEAP by setting the mass to 0 there? or is there a way to do this with a one-liner in OpenMM?

This is what I currently do to run from amber sources using OpenMM:

```
prmtop = AmberPrmtopFile(prm) #Built by Tleap
inpcrd = AmberInpcrdFile(inp) #Built by Tleap

system = prmtop.createSystem(nonbondedMethod=nonbondedMethod, nonbondedCutoff=nonbondedCutoff, constraints=constraints)

system.addForce(MonteCarloBarostat(1.0*atmospheres, 300*kelvin, 25)))

integrator = LangevinMiddleIntegrator(300*kelvin, 1.0/picosecond, 2*femtoseconds) 
integrator.setConstraintTolerance(constraintTolerance)

simulation = Simulation(prmtop.topology, system, integrator,  platform, platformProperties)
simulation.context.setPositions(inpcrd.positions)

```

Thanks in advance

All best
Pedro

**Comment by peastman** [comment]
Something like this should do it:

```python
for atom in prmtop.topology.atoms():
    if atom.residue.index < 15:
        system.setParticleMass(atom.index, 0.0)
```

Be sure to do this before you create the Simulation.  Modifying a System doesn't affect any Simulations that have already been created.
