### ISSUE TITLE
Self-defined array in `CustomIntegrator`

### ISSUE THREAD

**Issue by CheukHinHoJerry** [openmm/openmm#4396]
For example, if I define such an integration step in my `CustomIntegrator`

```python
Class MyIntegrator(...):

def __init__(self, ...)
    self.addComputePerDof("x", "x + gaussian")
```

However, I want `gaussian` to be something that I explicitly defined. i.e. If I have 1000 particles, I want gaussian to be a (1000, 3) array that I have exact control with.

Is there a way that I can achieve this? The integrator does not seems to be knowing anything about the number of particles.

**Comment by peastman** [comment]
That's what a per-DOF variable is.  See `addPerDofVariable()` and `setPerDofVariable()`.

**Comment by CheukHinHoJerry** [comment]
Thank you for your reply. Maybe I should explain myself more clearly. Suppose I want to run the integrator with 10 time steps, then I will have something like

```python
self.addPerDofVariable("G1", np.random.normal(0, 1.0, (1000, 3)))
self.addPerDofVariable("G2", np.random.normal(0, 1.0, (1000, 3)))
...
self.addPerDofVariable("G10", np.random.normal(0, 1.0, (1000, 3)))
```

and then at each time step I call the corresponding array. The only problem is that `addPerDofVariable` only allows initialization with `double` and I cannot find a way to init as what I wanted.

**Comment by peastman** [comment]
`addPerDofVariable()` defines a variable.  You only call it once, as part of creating the integrator.  Call `setPerDofVariable()` to change its value.

```python
for i in range(steps):
    integrator.setPerDofVariable(0, np.random.normal(0, 1.0, (1000, 3)))
    integrator.step(1)
```

Of course, I assume you don't really want this for Gaussian random numbers.  Using the built in random number generator is faster.  How do you actually want the values to be calculated?

**Comment by CheukHinHoJerry** [comment]
Thank you for your reply. If I simply want this to be the standard gaussian (in, say LangevinIntegrator with usual BAOAB splitting), do you think setting the random seed each time step would be the faster way? I am now more inclined to this now.

**Comment by peastman** [comment]
You don't need to set the seed on each step.  That's only used when initializing the context.  It generates new random numbers for every step.

**Comment by CheukHinHoJerry** [comment]
> `addPerDofVariable()` defines a variable. You only call it once, as part of creating the integrator. Call `setPerDofVariable()` to change its value.
> 
> ```python
> for i in range(steps):
>     integrator.setPerDofVariable(0, np.random.normal(0, 1.0, (1000, 3)))
>     integrator.step(1)
> ```
> 
> Of course, I assume you don't really want this for Gaussian random numbers. Using the built in random number generator is faster. How do you actually want the values to be calculated?

I think this achieve what I want to do at the end of the day. Thank you for your help. I will close the issue.
