### ISSUE TITLE
How to add an customNonbondedFunction with NBFIX

### ISSUE THREAD

**Issue by Forestsene** [openmm/openmm#4401]
I want to add a customNonbondedFunction like `"ep*exp(al*(1-r/r0))-2*exp(0.5*al*(1-r/r0));ep=sqrt(ep1*ep2); r0=0.5*(r01+r02); al=sqrt(al1*al2)" `

I have added following lines to forcefield.xml

```
<CustomNonbondedForce energy=" ep*exp(al*(1-r/r0))-2*exp(0.5*al*(1-r/r0));ep=sqrt(ep1*ep2); r0=0.5*(r01+r02); al=sqrt(al1*al2) " bondCutoff="1">
 <PerParticleParameter name="ep"/>
 <PerParticleParameter name="r0"/>
 <PerParticleParameter name="al"/>
 <Atom type="C1" ep="4.357043" r0="0.578" al="12.798"  />
 <Atom type="C2" ep="4.357043" r0="0.578" al="12.798"  />
</CustomNonbondedForce>
```
OpenMM can work correctly to calculate CustomNonbondedForce.

Additionally, I want to add NBFIX to customNonbondedFunction. I have tried to add this line to `<CustomNonbondedForce> `tag in xml file:
```
<NBFixPair  ep="3.670914" r0="0.556 " al="12.101"  type1="C1" type2="C2"/>
```
But OpenMM still calculate customNonbondedFunction between C1 and C2 by combinational rules:` ep=sqrt(ep1*ep2); r0=0.5*(r01+r02); al=sqrt(al1*al2)`. 

And I tried another method:
```
custom_nb_force = mm.CustomNonbondedForce(ep*exp(al*(1-r/r0))-2*exp(0.5*al*(1-r/r0));ep=sqrt(ep1*ep2); r0=0.5*(r01+r02); al=sqrt(al1*al2))
custom_nb_force.addPerParticleParameter('ep')
custom_nb_force.addPerParticleParameter('r0')
custom_nb_force.addPerParticleParameter('al')
for atom in topology.atoms():
    custom_nb_force.addParticle([4.357043,0.578,12.798])
```
I found NonbondedForce can use addException to define specific pair parameters, so I tried to use it for customNonbondedFunction:
```
custom_nb_force.addException(0,1,0,4.357043,0.578,12.798,True)
```
But OpenMM told me that 'CustomNonbondedForce' object has no attribute 'addException'

Is it possible to add an customNonbondedFunction with NBFIX? How to do that?

Many thanks!

**Comment by bmd-jpreiksa** [comment]
AddExeption does not exist in CustomNonBondedForce, use AddExclusion

**Comment by peastman** [comment]
It's possible, but you'll have to work at a slightly lower level.  You're trying to combine features from two different XML tags.  `<CustomNonbondedForce>` can create a CustomNonbondedForce with an arbitrary function, but it doesn't know anything about NBFix terms.  `<LennardJonesForce>` does know about NBFix, but it's specialized to create a CustomNonbondedForce with one specific form.

Take a look at the implementation of `<LennardJonesForce>` to understand how it works.  Here is where it creates the force:

https://github.com/openmm/openmm/blob/ed710a0d0f0857ee2ba4de5d2157b4294d75ae87/wrappers/python/openmm/app/forcefield.py#L2644-L2647

It uses a pair of tabulated functions to look up the sigma and epsilon parameters for a pair of particles based on their values of the `type` parameter.  You can do the same thing for your expression, creating a tabulated function for each parameter that might not follow the standard combination rules.

If you click through to the file and look immediately above those lines, you'll find the logic it uses to build the lookup tables.  It tries to keep the lookup tables as small as possible by merging together types that have identical parameters and don't appear in NBFix terms.

**Comment by Forestsene** [comment]
Thank you very much!
I have added CustomNonbondedForce with NBFIX successfully:

```
custom_nb_force = mm.CustomNonbondedForce(ep*exp(al*(1-r/r0))-2*exp(0.5*al*(1-r/r0));ep=eptable(type1,type2); r0=r0table(type1,type2); al=altable(type1,type2))
custom_nb_force.addPerParticleParameter('type')

custom_nb_force.addParticle([0])
custom_nb_force.addParticle([1])

custom_nb_force.addTabulatedFunction('eptable', mm.Discrete2DFunction(2,2,[4.387,4.671,4.671,3.191]))
custom_nb_force.addTabulatedFunction('r0table', mm.Discrete2DFunction(2,2,[0.588,0.566,0.566,0.574]))
custom_nb_force.addTabulatedFunction('altable', mm.Discrete2DFunction(2,2,[12.768,12.155,12.155,11.442]))

system.addForce(custom_nb_force)
```

**Comment by Forestsene** [comment]
> Great! Is it ok to close this issue?

Yes. Thank you!
