### ISSUE TITLE
Force Field getForces() 

### ISSUE THREAD

**Issue by Pkulyte** [openmm/openmm#4407]
Hello,

I would like to inquire about the correctness of my approach for obtaining the Amber forces acting on atoms,  specifically the gradients with respect to atom positions. 

My understanding is that these forces are derived by computing the negative gradient of the energy function with respect to the atomic positions. Is my understanding accurate that state.getForces() gives me the gradients required?

`

    def get_force_gradients(self, pdb_str):
            
            ENERGY = unit.kilocalories_per_mole
            LENGTH = unit.angstroms
            FORCE = unit.kilocalories_per_mole / unit.angstrom  

            pdb = openmm_app.PDBFile(io.StringIO(pdb_str))
            force_field = openmm_app.ForceField("amber99sb.xml")
            constraints = openmm_app.HBonds
            system = force_field.createSystem(pdb.topology, constraints=constraints)

            integrator = openmm.LangevinIntegrator(0, 0.01, 0.0)
            platform = openmm.Platform.getPlatformByName("CUDA")
            simulation = openmm_app.Simulation(pdb.topology, system, integrator, platform)
            simulation.context.setPositions(pdb.positions)

            ret = {}
            state = simulation.context.getState(getEnergy=True, getPositions=True, getForces=True)
            ret["e"] = state.getPotentialEnergy().value_in_unit(ENERGY)
            ret["pos"] = state.getPositions(asNumpy=True).value_in_unit(LENGTH)
            ret["forces"] = state.getForces(asNumpy=True).value_in_unit(FORCE)

            return ret["forces"]

`

Thank you.

**Comment by peastman** [comment]
That's correct.  The forces are the negative gradient of the energy.
