### ISSUE TITLE
Split the Total `CustomGBForce` Created for GBSA Implicit Solvation into Different Energy Components

### ISSUE THREAD

**Issue by hjuinj** [openmm/openmm#4412]
Say I have a system in implicit solvent, e.g. `from openmmtools.testsystems import HostGuestImplicit` and I would like to attribute the overall implicit solvation energy in the `CustomGBForce` to host atom pairs, to guest atom pairs and to host-guest pairs. 

It is not as straight forward as `force.addExclusion` as it seems `force.addEnergyTerm` is applied with `CustomGBForce.ParticlePairNoExclusions`: https://github.com/openmm/openmm/blob/ed710a0d0f0857ee2ba4de5d2157b4294d75ae87/wrappers/python/openmm/app/internal/customgbforces.py#L354-#L391
Perhaps this is intentionally done so to prohibit what I propose above? :)

Is there a straight forward way for me to do this splitting without creating a my own version of `CustomGBForce`?

**Comment by peastman** [comment]
CustomGBForce doesn't provide any mechanism to split the energy up like that.  It isn't clear to me what that would even mean.  GB isn't a pairwise interaction.  It's an inherently many-particle interaction.  If you move one particle, it changes the GB radii of all the other particles, which changes how they interact with each other.
