### ISSUE TITLE
Checkpoint 

### ISSUE THREAD

**Issue by julruiz72** [openmm/openmm#4413]
Hello my name is JUlian and I am a biologist who is currently learning how to run MDs using my PC

I've been runing long MDs, but these take a lot of time so I am trying a way to pause and continue my MDs, for this purpose I've been using the loadCheckpoing command, but when I try to use it, it rewrites the output file (trajectory.dcd)  so I wonder if I am using it wrong 

I checked the page ( 
http://docs.openmm.org/7.1.0/api-python/generated/simtk.openmm.app.checkpointreporter.CheckpointReporter.html )and the frequently asked questions, but I cannot tell what is happening with my Molecular dynamics

`please help me 
# This script was generated by OpenMM-Setup on 2024-01-15.

from openmm import *
from openmm.app import *
from openmm.unit import *
from sys import stdout

# Input Files

pdb = PDBFile('export_pymol-processed.pdb')
forcefield = ForceField('amber14-all.xml', 'amber14/tip3p.xml')

# System Configuration

nonbondedMethod = PME
nonbondedCutoff = 1.0*nanometers
ewaldErrorTolerance = 0.0005
constraints = HBonds
rigidWater = True
constraintTolerance = 0.000001

# Integration Options

dt = 0.0001*picoseconds
temperature = 300*kelvin
friction = 1/picosecond
pressure = 1*atmospheres
barostatInterval = 25

# Simulation Options

steps = 5000000
equilibrationSteps = 200
platform = Platform.getPlatformByName('CUDA')
platformProperties = {'Precision': 'single'}
dcdReporter = DCDReporter('trajectory.dcd', 2000)
dataReporter = StateDataReporter('logtry1', 20000, totalSteps=steps, step=True, progress=True, elapsedTime=True, remainingTime=True, potentialEnergy=True, kineticEnergy=True, totalEnergy=True, separator='\t')
checkpointReporter = CheckpointReporter('checkpoint.chk', 20000)

# Prepare the Simulation

print('Building system...')
topology = pdb.topology
positions = pdb.positions
forcefield = ForceField('amber14-all.xml', 'amber14/tip3pfb.xml')
system = forcefield.createSystem(topology, nonbondedMethod=nonbondedMethod, nonbondedCutoff=nonbondedCutoff, constraints=constraints, rigidWater=rigidWater, ewaldErrorTolerance=ewaldErrorTolerance)
system.addForce(MonteCarloBarostat(pressure, temperature, barostatInterval))
integrator = LangevinMiddleIntegrator(temperature, friction, dt)
integrator.setConstraintTolerance(constraintTolerance)
simulation = Simulation(topology, system, integrator, platform, platformProperties)
simulation.context.setPositions(positions)

# Minimize and Equilibrate

print('Performing energy minimization...')
simulation.minimizeEnergy()
print('Equilibrating...')
simulation.context.setVelocitiesToTemperature(temperature)
with open('checkpoints_try_1', 'rb') as f:
 simulation.context.loadCheckpoint(f.read())
simulation.step(equilibrationSteps)

# Simulate

print('Simulating...')
simulation.reporters.append(DCDReporter('trajectory.dcd',10000))
simulation.reporters.append(StateDataReporter(stdout,10000,step=True, potentialEnergy=True, temperature=True))
simulation.reporters.append(checkpointReporter)
simulation.currentStep = 230000
simulation.step(steps)

simulation.saveState("final_state.xml")
simulation.saveCheckpoint("checkpoint.chk")`

**Comment by peastman** [comment]
When you create your DCDReporter, add the argument `append=True` to tell it to append to an existing file rather than creating a new one.  See [the API docs](http://docs.openmm.org/latest/api-python/generated/openmm.app.dcdreporter.DCDReporter.html#openmm.app.dcdreporter.DCDReporter).

**Comment by julruiz72** [comment]
Thank you for your help, it is  aparently working!!!

**Comment by peastman** [comment]
Glad to hear it!
