### ISSUE TITLE
Adding free ions in topology

### ISSUE THREAD

**Issue by peter-zhang-chem** [openmm/openmm#4414]
Dear openMM team,

I am trying to implement a RNA folding model where divalent ions are added explicitly. I am wondering what is the best way to go about adding free ions into topology? I have concentration of ions as an argument, then base on box size, I calculate number of ions I need to add. And the location of the ions initially should be randomized within the box.

Thank you,

**Comment by peastman** [comment]
`Modeller.addSolvent()` does something fairly close to what you describe.  After adding water, it calculates how many ions to add and replaces a random selection of water molecules with ions.  Most of the logic for it is contained in the private method `_addIons()`.  You can probably adapt the code to do what you need.  Here is the most relevant part.

https://github.com/openmm/openmm/blob/6da98153b5ebb2a887aa7c4ec34d26b189eb4e1a/wrappers/python/openmm/app/modeller.py#L344-L378

**Comment by peter-zhang-chem** [comment]
Hi Peter, thank you. 

I have a different question regarding CustomNonbondedForce. I am trying to implement equation 5 as a CustomNonbondedForce: 
<img width="641" alt="image" src="https://github.com/openmm/openmm/assets/33939722/7b238f88-2e32-4725-8598-c6707443eaba">
I have all the values for W(r) calculated already and was saved in this file.
[pmf_Mg_P_1264.zip](https://github.com/openmm/openmm/files/14204023/pmf_Mg_P_1264.zip). So what I am trying to do is to use the distance (r) from CustomNonbonded to get the corresponding W(r). I have already U_DH implemented already as a CustomNonbonded force. I am thinking it would be great if I can get the numerical value of the U_DH force. What's the correct way to go about this in openMM frameworks?

Thank you so much,

**Comment by peastman** [comment]
If you have tabulated values for W(r), you can create a [Continuous1DFunction](http://docs.openmm.org/latest/api-python/generated/openmm.openmm.Continuous1DFunction.html) from them, then call [`addTabulatedFunction()`](http://docs.openmm.org/latest/api-python/generated/openmm.openmm.CustomNonbondedForce.html#openmm.openmm.CustomNonbondedForce.addTabulatedFunction) on the CustomNonbondedForce.

**Comment by peter-zhang-chem** [comment]
<img width="537" alt="image" src="https://github.com/openmm/openmm/assets/33939722/e3748228-44b5-43f5-a5f9-349f0b1d4e1d">
My tabulated data looks like this, on the x-axis is distance (r) and the y-axis is W(r). From the description of `Continuous1DFunction`, it should work. But I do not know where I have implemented wrong. So currently the distance is 17.21 angstrom, so I am expecting `W(r)` to be around -0.407498, but it is giving me -0.09730611402491537 from openMM.

**Comment by peter-zhang-chem** [comment]
Thank you, yes, I was doing the unit, I just change that line with no unit to this `W_r = omm.Continuous1DFunction(tabulated_data, 1.77500000 * unit.angstrom, 50.000000 * unit.angstrom)`

**Comment by peter-zhang-chem** [comment]
Hey, sorry, and thank you, it was another unit issue, I was reporting in kcal/mol and my tabulated value should be in kJ/mol. Thank you again for your time. The W(r) value matches expected now.
