### ISSUE TITLE
Using CustomNonbondedForce in OpenMM

### ISSUE THREAD

**Issue by NAS-SAA** [openmm/openmm#4415]
Hello,

I'm new to Python and OpenMM and currently working on implementing a custom nonbonded force for my system involving Cs and I ions. Following a tutorial, I created the force field XML file and extracted parameters per particle and the potential function from a relevant paper. I've chosen to work entirely in atomic units and then convert back to avoid dealing with the cumbersome 1/4πε₀ term in the Coulomb potential.

However, I'm uncertain about how to translate this into code. Additionally, the Cs-Cs and I-I interactions are crucial for my simulation. I'm wondering if the existing code already considers these interactions or if I need to add specific lines to account for them.

Any guidance would be greatly appreciated!
[XML fle .zip](https://github.com/openmm/openmm/files/14054857/XML.fle.zip)

The zip file includes forcefield.xml and the paper that I used.

**Comment by peastman** [comment]
You've written a file that's half XML and half Python, but not really either one.  You can't just define variables part way through the file like

```
NM_2_AU = 18.8972598858
```

In an XML file, that's just some arbitrary text that happens to appear part way through the file.  It doesn't get interpreted or executed.  And you can't use variables in attributes like

```xml
 <Atom type="ION-CS" z="1"  c="0.04296*c_converstion" b="0.0098*NM_2_AU" a="0.1969*NM_2_AU"/>
```

The attributes need to be numbers, nothing more.  They don't get executed as code.

I think what you're really trying to do is to write a Python script that generates your XML file.  Something like this?  (I haven't tested it and make no claims it's correct.  This is just to give the idea.)

```python
import numpy as np
N_2_AU = 12137804.11081
NM_2_AU = 18.8972598858
KJ_MOL_2_AU = 0.0003808798033989866
AU_2_KJ_MOL = 1/KJ_MOL_2_AU
BOHR_2_ANG = 1.0/(NM_2_AU/10)
c_conversion = np.sqrt(KJ_MOL_2_AU * NM_2_AU**6)
print(f'<ForceField>
<AtomTypes>
 <Type name="ION-CS" class="CS" element="CS" mass="132.9054"/>
 <Type name="ION-I" class="I" element="I" mass="126.9045"/>
</AtomTypes>
<Residues>
 <Residue name="ION-CS">
  <Atom name="CS" type="ION-CS"/>
 </Residue>
 <Residue name="ION-I">
  <Atom name="I" type="ION-I"/>
 </Residue>
</Residues>
<CustomNonbondedForce energy="((z1*z2)/r+(-c1*c2)/(r**6)+(f0*(b1 + b2))*(np.exp(((a1 + a2) - r)/(b1 + b2))))*{AU_2_KJ_MOL}" bondCutoff="1.5">
 <GlobalParameter name="f0" defaultValue="{6.9511e-11*N_2_AU}"/>
 <PerParticleParameter name="z"/>
 <PerParticleParameter name="c"/>
 <PerParticleParameter name="b"/>
 <PerParticleParameter name="a"/>
 <Atom type="ION-CS" z="1"  c="{0.04296*c_converstion}" b="{0.0098*NM_2_AU}" a="{0.1969*NM_2_AU}"/>
 <Atom type="ION-I"  z="-1"  c="{0.06136*c_converstion}"  b="{0.0215*NM_2_AU}"  a="{0.2386*NM_2_AU}"/>
</CustomNonbondedForce>
</ForceField>')
```

**Comment by peastman** [comment]
I edited the above script to fix a few errors.  I verified that it now runs, though I still don't know whether the output is correct.

**Comment by NAS-SAA** [comment]
Got it, thank you. It solved the problem and I close the issue.

**Comment by NAS-SAA** [comment]
Got it, thank you. It solved the problem and I close the issue.
