### ISSUE TITLE
Error during system preparation

### ISSUE THREAD

**Issue by Kash-Pandz** [openmm/openmm#4417]
Hi,

I'm new to openmm and I'm trying to setup my system using the code (shown below). I'm getting the No template found for residue 22333 (NA) error. 

system = forcefield.createSystem(modeller.topology, nonbondedMethod=app.PME,
    nonbondedCutoff=1.0*nanometers, constraints=app.HBonds, rigidWater=True,
    ewaldErrorTolerance=0.0005)
posres_sys = add_backbone_posres(system, modeller.positions, modeller.topology.atoms(), 100)
integrator = LangevinIntegrator(300*kelvin, 1/picosecond, 0.002*picoseconds)
integrator.setConstraintTolerance(0.00001)
simulation = Simulation(modeller.topology, posres_sys, integrator)
simulation.reporters.append(
    StateDataReporter(
        stdout,
        10000,
        step=True,
        potentialEnergy=True,
        temperature=True,
        volume=True,
        density=True
    )
)

I did correct a prior error like this using PDBFixer but did not work this time round. I would appreciate some guidance on how to fix this new error.

Many thanks,

Kash

**Comment by peastman** [comment]
The FAQ has [a discussion](https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template) of what this error means and how to debug it.  See if you can figure it out from that.  If not, post the complete files to reproduce it and I'll take a look.

**Comment by Kash-Pandz** [comment]
Hi,

I had a look through the FAQ but couldn't quite figure out how to solve the error. I have attached my PDB file and forcefield XML file to this message. The code I used is shown below.

pdb = PDBFile("Scaffold_refined.pdb")
forcefield = ForceField('protein.ff14SB.xml', 'tip3pfb.xml')
modeller = Modeller(pdb.topology, pdb.positions)
modeller.addHydrogens(forcefield, pH=7.0)
modeller.addSolvent(forcefield, padding=1.0*nanometers)

system = forcefield.createSystem(modeller.topology, nonbondedMethod=app.PME,
nonbondedCutoff=1.0nanometers, constraints=app.HBonds, rigidWater=True,
ewaldErrorTolerance=0.0005)
posres_sys = add_backbone_posres(system, modeller.positions, modeller.topology.atoms(), 100)
integrator = LangevinIntegrator(300kelvin, 1/picosecond, 0.002*picoseconds)
integrator.setConstraintTolerance(0.00001)
simulation = Simulation(modeller.topology, posres_sys, integrator)
simulation.reporters.append(
StateDataReporter(
stdout,
10000,
step=True,
potentialEnergy=True,
temperature=True,
volume=True,
density=True
)
)

Many thanks,

Kash

[OpenMM_Test.zip](https://github.com/openmm/openmm/files/14085007/OpenMM_Test.zip)

**Comment by peastman** [comment]
The error message you quoted above ("No template found for residue 22333 (NA)") is not from this file.  It doesn't contain any residue called NA.

An obvious problem with the file is that it's missing hydrogens.  You can use [OpenMM-Setup](https://github.com/openmm/openmm-setup) to add them.

**Comment by Kash-Pandz** [comment]
I've attached the "system.pdb" file. The error refers to the NA+ ions but I assumed the template for this already exists as the OpenMM adds the ions to neutralise the system automatically?

[OpenMM_Test.zip](https://github.com/openmm/openmm/files/14096010/OpenMM_Test.zip)

**Comment by Kash-Pandz** [comment]
It worked thank you!

**Comment by peastman** [comment]
Great!
