### ISSUE TITLE
Rosetta to OpenMM gives NaN (`ValueError: Particle position is NaN.`)

### ISSUE THREAD

**Issue by matteoferla** [openmm/openmm#4418]
> This is note to help others and not an issue fix request

PDB models generated via PyRosetta or Rosetta do not work out of the box, but need a fix.
It is the location of the terminal atoms that causes issues.

This is a Rosetta PDB block:
```
ATOM      1  N   SER A   1      -8.697  12.827  12.734  1.00  0.00           N  
ATOM      2  CA  SER A   1      -9.257  12.935  11.392  1.00  0.00           C  
ATOM      3  C   SER A   1      -8.786  11.791  10.504  1.00  0.00           C  
ATOM      4  O   SER A   1      -9.500  11.360   9.599  1.00  0.00           O  
ATOM      5  CB  SER A   1      -8.870  14.262  10.770  1.00  0.00           C  
ATOM      6  OG  SER A   1      -7.483  14.343  10.582  1.00  0.00           O  
ATOM      7 1H   SER A   1      -9.022  13.589  13.294  1.00  0.00           H  
ATOM      8 2H   SER A   1      -8.985  11.963  13.148  1.00  0.00           H  
ATOM      9 3H   SER A   1      -7.698  12.854  12.682  1.00  0.00           H  
ATOM     10  HA  SER A   1     -10.345  12.886  11.466  1.00  0.00           H  
ATOM     11 1HB  SER A   1      -9.376  14.376   9.812  1.00  0.00           H  
ATOM     12 2HB  SER A   1      -9.200  15.076  11.413  1.00  0.00           H  
ATOM     13  HG  SER A   1      -7.087  13.947  11.362  1.00  0.00           H  
...
ATOM   2451  N   GLU A 150       7.183 -10.982 -16.258  1.00  0.00           N  
ATOM   2452  CA  GLU A 150       7.776 -11.782 -17.322  1.00  0.00           C  
ATOM   2453  C   GLU A 150       8.730 -12.828 -16.760  1.00  0.00           C  
ATOM   2454  O   GLU A 150       9.231 -12.689 -15.644  1.00  0.00           O  
ATOM   2455  OXT GLU A 150       9.231 -12.689 -15.644  1.00  0.00           O  
ATOM   2456  CB  GLU A 150       8.517 -10.884 -18.315  1.00  0.00           C  
ATOM   2457  CG  GLU A 150       9.136 -11.624 -19.493  1.00  0.00           C  
ATOM   2458  CD  GLU A 150       9.849 -10.709 -20.449  1.00  0.00           C  
ATOM   2459  OE1 GLU A 150       9.853  -9.524 -20.217  1.00  0.00           O  
ATOM   2460  OE2 GLU A 150      10.390 -11.196 -21.414  1.00  0.00           O  
ATOM   2461  H   GLU A 150       7.698 -10.195 -15.889  1.00  0.00           H  
ATOM   2462  HA  GLU A 150       6.976 -12.302 -17.851  1.00  0.00           H  
ATOM   2463 1HB  GLU A 150       7.829 -10.137 -18.714  1.00  0.00           H  
ATOM   2464 2HB  GLU A 150       9.315 -10.351 -17.798  1.00  0.00           H  
ATOM   2465 1HG  GLU A 150       9.845 -12.359 -19.114  1.00  0.00           H  
ATOM   2466 2HG  GLU A 150       8.351 -12.158 -20.025  1.00  0.00           H  
TER                   
```
The `1H  `, `2H ` and `3H  ` are after the HAs. OpenMM expect them to be after all atoms of that residue. And expects `1H  ` to be ` H `, like a regular residue's, even if the angle subtended is 109° not 120°.
The `OXT` is the last of the BB atoms. However, OpenMM expects it to be the last HA or FA. As a result the `OXT` needs to be removed and PDBFixer applied or shifted with correction of atom indices. 

The Rosetta score fluff at the end of the file (`BEGIN_POSE_ENERGIES_TABLE`) is not the issue nor is `TER` entries with no atom index.

Lazy fix:

    `grep -v '           H' 👾👾👾.pdb | grep -v 'OXT' > 👾👾👾.fixed.pdb`
    
then:

```python
pdb = PDBFixer(filename='👾👾👾.fixed.pdb')
pdb.findMissingResidues()
pdb.findNonstandardResidues()
pdb.replaceNonstandardResidues()
pdb.findMissingAtoms()
pdb.addMissingAtoms()
```

**Comment by peastman** [comment]
It doesn't care what order the atoms for a residue are listed in.  Nonstandard atom names can cause problems, but generally you would get a "no template found" error in that case.

Perhaps the problem is just that some of the hydrogens are in bad positions?  If you do an initial energy minimization with `simulation.minimizeEnergy()`, does that fix the problem?

**Comment by everyday847** [comment]
I notice

```
ATOM   2454  O   GLU A 150       9.231 -12.689 -15.644  1.00  0.00           O  
ATOM   2455  OXT GLU A 150       9.231 -12.689 -15.644  1.00  0.00           O  
```

I am fairly confident this is not a typical modeling outcome in Rosetta; OXT is typically defined with a 180 torsion to O:

```
SET_ICOOR O    80.0 60 1.2 C CA N
SET_ICOOR OXT 180.0 60 1.2 C CA O ## phi == 180 --> planar
```

OXT is definitionally 180 degrees from O. Did something alter its XYZ coordinates?

**Comment by matteoferla** [comment]
@peastman, `simulation.minimizeEnergy()` was giving the problem.
However, as @everyday847 has spotted the `O` and `OXT` are superimposed, so it is a problem with my file.
I cannot believe I did not notice: spent hours trying to figure out what was wrong.

It was a file created by threading, RosettaCM, but in PyRosetta a sequence generated from ProteinMPNN onto a template generated from RFdiffusion and then minimising with FastRelax. This snippet replicates the issue though:

```python
pose = pyrosetta.pose_from_sequence('ELVIS')
scorefxn: pr_scoring.ScoreFunction = pyrosetta.get_fa_scorefxn()
relax = pyrosetta.rosetta.protocols.relax.FastRelax(scorefxn, 1)
movemap = pyrosetta.MoveMap()
movemap.set_bb(False)
movemap.set_chi(True)
movemap.set_jump(False)
relax.set_movemap(movemap)
relax.apply(pose)
terminal: pr_conf.Residue = pose.residues[pose.total_residue()]
print(terminal.xyz('O').distance(terminal.xyz('OXT')), 'Å O-OXT') # 2Å
terminal.set_xyz('O', terminal.xyz('OXT'))
relax.apply(pose)
print(terminal.xyz('O').distance(terminal.xyz('OXT')), 'Å O-OXT') # 0Å
terminal.set_xyz('O', terminal.xyz('OXT')+5)
relax.apply(pose)
print(terminal.xyz('O').distance(terminal.xyz('OXT')), 'Å O-OXT') # 8.6Å
```
This is because a lower terminus is a patch and subject to the same quirks as CONN3, even if it's a LOWER connection.

So this is fully a Rosetta glitch and not an OpenMM one. Thanks for helping me get to the bottom of it!

**Comment by everyday847** [comment]
Honestly not a Rosetta bug I've seen before. I believe the non-commercial open source repo should be available soon -- it'd be nice to very rapidly illustrate its value by raising this issue there.
