### ISSUE TITLE
XML file for CustomNonbondedForce

### ISSUE THREAD

**Issue by NAS-SAA** [openmm/openmm#4419]
Hello, I'm new to openMM, and I have some question regarding an XML file. My system exclusively involves nonbond interactions, with no bonds present. The system comprises two ions, Cs and I. I'm attempting to implement custom nonbond functions that consist of three terms:
1. Coulomb Term: z1*z2*e^2/4pi*epsilon0*r
2. Van der Waals Term:: -c1*c2/r^6
3. short-range repulsive term: constant(b1+b2)*exp((a1+a2-r))/(b1+b2)

Here are my specific questions:

Should I include the Coulomb term in the CustomNonbondForce along with the other two terms?
Does the implementation account for interactions between Cs-Cs, Cs-I, and I-I?
I appreciate any guidance you can provide on these queries. Thank you!

`import numpy as np`
`print(f"""<ForceField>` 
`<AtomTypes>`
 `<Type name="CS" class="CS" element="CS" mass="132.9054"/>`
 `<Type name="I" class="I" element="I" mass="126.9045"/>`
`</AtomTypes>`
`<Residues>`
` <Residue name="CS">`
`  <Atom name="CS" type="CS"/>`
` </Residue>`
` <Residue name="I">`
`  <Atom name="I" type="I"/>`
` </Residue>`
`</Residues>`
`<CustomNonbondedForce energy="z1*z2*(1.602176634e-19)^2/(r*4*3.14159*8.8541878128e-12)-(c1*c2)/(r^6)+41.8595242*(b1+b2)*exp((a1+a2-r)/(b1+b2))" bondCutoff="0">`
` <PerParticleParameter name="c"/>`
` <PerParticleParameter name="b"/>`
` <PerParticleParameter name="a"/>`
` <PerParticleParameter name="z"/>`
` <Atom type="CS"  c="{0.04296}" b="{0.0098}" a="{0.1969}" z="{1}"/>`
` <Atom type="I"   c="{0.06136}"  b="{0.0215}"  a="{0.2386}" z="{-1}"/>`
`</CustomNonbondedForce>`
`</ForceField>""" , file=open("FF.xml","w"))`

**Comment by peastman** [comment]
> Should I include the Coulomb term in the CustomNonbondForce along with the other two terms?

It's up to you.  The main reason you might choose not to is if you want to use PME for long range interactions.  CustomNonbondedForce doesn't support PME.  In that case, you would use a NonbondedForce for Coulomb and the CustomNonbondedForce for everything else.  If you're happy with just a simple cutoff (or no cutoff), it's fine to include it in the CustomNonbondedForce.

>  Does the implementation account for interactions between Cs-Cs, Cs-I, and I-I?

Correct.  Every atom interacts with every other.

**Comment by NAS-SAA** [comment]
Thank you for your help!
