### ISSUE TITLE
Best practice for customizing disuflide bonds?

### ISSUE THREAD

**Issue by meneshail** [openmm/openmm#4420]
Hi all,
I am currently utilizing OpenMM's Modeller and PDBFixer for preparing a protein model for molecular dynamics simulations. My workflow involves two major steps:

1. Adding the 'OXT' atom for the C-terminal residues.
2. Adding hydrogens, while ensuring all cysteines are in the **reduced form**. (As indicated by the environmental redox state)

When loading my pdb file with either `openmm.app.PDBFile` or `pdbfixer.PDBFixer`, it seems some disulfide bonds are automatically recognized based on their proximity, and I could not find any high-level APIs to correct this behaviour. After finding that the[`Modeller.addHydrogens`](https://github.com/openmm/openmm/blob/162b7c37eda7a4faaa47264688683608fe449b3a/wrappers/python/openmm/app/modeller.py#L870-L875) method uses bond information to decide whether a residue is CYS or CYX, currently I'm adopting the following approach.

```
import pdbfixer
import openmm.app as app

# Load pdb and add OXT
fixer = pdbfixer.PDBFixer(pdb_path)
fixer.findMissingResidues()
fixer.findMissingAtoms()
fixer.addMissingAtoms()

# Pass to modeller, manually delete disulfide bonds and add hydrogen
modeller = app.Modeller(fixer.topology, fixer.positions)
disulfide_bond_list = []
for bond in modeller.topology.bonds():
    if bond.atom1.name == 'SG' and bond.atom2.name == 'SG':
        disulfide_bond_list.append(bond)
modeller.delete(disulfide_bond_list)
forcefield = app.ForceField('amber14/protein.ff14SB.xml', 'implicit/gbn2.xml')
modeller.addHydrogens(forcefield)

app.PDBFile.writeFile(modeller.topology, modeller.positions, open(save_path, 'w'))
```

Could you please advise on whether this method is appropriate for my requirements? Are there potential issues with the resulted topology that I should be aware of? Alternatively, are there more straightforward methods or APIs available within OpenMM or PDBFixer to address this issue directly? Thanks!

**Comment by peastman** [comment]
What you have looks good.  The automatic disulfide bond detection is kind of a hack.  According to the spec, PDB files are supposed to explicitly list all disulfide bonds.  Unfortunately, files found in the wild very often don't.  We need to guess them automatically to avoid frequent failures.

**Comment by meneshail** [comment]
Sorrry for the late reply.  Many thanks for taking the time to review my code! Good to know the design logic and this clear up a lot of questions for me. 
Closing the issue.

**Comment by mainguyenanhvu** [comment]
@peastman which standards do you use to add disulfide bond in your code?

**Comment by peastman** [comment]
The code that implements it is [here](https://github.com/openmm/openmm/blob/2b8ad70394f38d296497215da757aa31ac36b87b/wrappers/python/openmm/app/topology.py#L357).  It requires that neither residue has an `HG` atom (a hydrogen on the sulfur), and that the sulfurs are less than 3Å apart.
