### ISSUE TITLE
CustomNonbondedForce settings based on atom pairs instead of single atomtype

### ISSUE THREAD

**Issue by puying1994** [openmm/openmm#4422]
I have a question about the customnonbondedforce setting. I read the user guide and found that the custumnonbondedforce need to be set based on single atomtype. For example, like most general force field (gaff, oplsaa), I need to set the sigma and epsilon for each single atom type. Then the code will calculate the sigma and epsilon between two atoms according to different combination rules. 

In the following code, I can only give defination of single type.
```
<CustomNonbondedForce energy="scale*epsilon1*epsilon2*((sigma1+sigma2)/r)^12" bondCutoff="3">
 <GlobalParameter name="scale" defaultValue="1"/>
 <PerParticleParameter name="sigma"/>
 <PerParticleParameter name="epsilon"/>
 <Atom type="0" sigma="0.3249" epsilon="0.7112"/>
 <Atom type="1" sigma="0.1069" epsilon="0.0656"/>
 <Atom type="2" sigma="0.3399" epsilon="0.4577"/>
 ...
</CustomNonbondedForce>
```

But, how can I directly define the sigma and epsilon between two atom types? I think this can be done in some way else but I didn't find the solution. Something I want is just like this:
```
 <Atom type="1" type2="2" sigma="0.1069" epsilon="0.0656"/>
```
I know this writing method is incorrect and it's just a show of what I mean.

**Comment by puying1994** [comment]
I checked the implementation of Martini force field in openmm. The LJ potential parameters in Martini force field are given in pair-wise instead of single atom with combination rule.
The code of is firstly load the C6 and C12 parameters into a list. After that, establish a Discrete2DFunction using the C6 and C12 parameters. Finally, feed the 2dfunction(addTabulatedFunction) to the CustomNonbondedForce.

Not sure if my understanding is right.

The code is around here:
https://github.com/maccallumlab/martini_openmm/blob/master/martini_openmm/martini.py#L1484

**Comment by peastman** [comment]
Exactly.  Here's a similar example.  This is how ForceField implements the `<LennardJonesForce>` tag.

https://github.com/openmm/openmm/blob/71f4b3fcb0b07d0fe41302df03f5373c8424cefa/wrappers/python/openmm/app/forcefield.py#L2644-L2647

It assigns a `type` parameter (the index of the atom type) to each particle.  The energy expression uses the types of the two particles to look up what values to use for the parameters.

**Comment by puying1994** [comment]
Thank you very much for your reply!
This helps me a lot.

**Comment by peastman** [comment]
Great!  I'm going to close this issue then.  Feel free to reopen it if I missed something.
