### ISSUE TITLE
Relationship between topology and postion files

### ISSUE THREAD

**Issue by puying1994** [openmm/openmm#4423]
I am a beginner of openmm and I can't understand the openmm well. This quesition is not based on specific issue but a understanding problem about openmm. 

Previously I use gromacs and lammps a lot. Gromacs is really fast but can only support limited of functions, while lammps is really powerful and can do everything I want (exept for biological problems), but lammps is slow. Openmm is fast and also flexible, I really want to make use of this md package.

My research is more about polymers and small molecules instead of proteins or biological system. So most of the time I need to prepare all the topology by myself.

For example, I have a system which contains 100 molecule A and 100 molecule B. If I want to run this simulaiton using gromacs, I need to prepare the itp files of A.itp and B.itp, and also the system.top file. In the top file, I need to tell the code that there are 100 mol A and 100 mol B. Besides, in the pdb/gro file, the order also must be the same with the top file. So I think it's quite clear. I only need to prepare the topology file of A and B, only 2 files.

In lammps, it's completely on the opposite.  Although there are only two types of molecules(A and B), I still need to write the topology of every single molecules, i.e. 200 molecules, in the lammps data file. Usually the data file tends to be very large. However, with the help of moltemplate, I can still deal this well. The logic of lammps is also easy to be understood. I need to give all the posisitons, bonds, angles, dihedrals of the whole system. This is how it works. But lammps is so slow......much slower than gromacs and openmm.

Sometimes gromacs does not support certain type of functions in published papers, so I cannot load the gro and top file to opemm. As a result, I need to prepare the xml file by myself. My question is, how can I understand the working mechanism of openmm? How can I tell openmm my system contains 100 mol A and 100 mol B? 

My current understanding is like this:
Firstly, I need to prepare the pdb file of the whole system. Besides, the pdb file **must** contain the CONECT information of all the molecules. 
Secondly, I need to prepare the XML file/files. In this step, I don't know whether to prepare 2 xml files (A.xml and B.xml) or just one xml file which contains 2 residues.
Finally, load the pdb and XML file to the openmm python script. Then the code will automatically recognize the quatity of A and B. But how can I make sure the code can recognize? What if the order of A/B in the pdb file is just random, will the openmm still recognize?

Is my understanding right? Thanks for any help!!!

**Comment by z-gong** [comment]
I'm also using OpenMM for non-bio polymer simulation. In order to use OpenMM python wrapper to setup a simulation system, some conventions from bio polymers have to be observed. Here is my experience:

> Firstly, I need to prepare the pdb file of the whole system. Besides, the pdb file must contain the CONECT information of all the molecules.

True. Because the molecules in your system are non-standard residues, all the atom lines should start with HETATM instead of ATOM, and CONECT information must be present.

> Secondly, I need to prepare the XML file/files. In this step, I don't know whether to prepare 2 xml files (A.xml and B.xml) or just one xml file which contains 2 residues.

Either way will work.

> Finally, load the pdb and XML file to the openmm python script. Then the code will automatically recognize the quatity of A and B. But how can I make sure the code can recognize? What if the order of A/B in the pdb file is just random, will the openmm still recognize?

OpenMM python wrapper use residue name to recognize different residues (or more accurately 'molecules' in your case), and use atom name to recognize different atoms. You have to make sure that:

- each residue (molecule) has a unique residue ID in PDB
- each atom in a residue has a unique atom name in PDB
- each residue (molecule) has the same residue name in PDB and in XML file
- each atom in a residue has the same atom name in PDB and in XML file

**Comment by puying1994** [comment]
Hi z-gong, thank you for your kind help! This message is important for  me. I'll have a test later so as to understand openmm better.

**Comment by peastman** [comment]
It doesn't actually matter if the atom names or residue names match between the two files.  It matches templates to residues based only on the elements of the atoms and the set of bonds between them.  [This FAQ entry](https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template) discusses more about how template matching works, and some of the problems that can happen.

**Comment by puying1994** [comment]
Thank you for your answer！
