### ISSUE TITLE
[feature request] Manually set OPENMM_CPU_THREADS via Python API

### ISSUE THREAD

**Issue by IAlibay** [openmm/openmm#4424]
Apologies if this issue already exists elsewhere.

## Current status

As far as we are aware, the only way to set the number of CPU threads being using by OpenMM is to do so by setting the environment variable `OPENMM_CPU_THREADS`.

In some cases, particularly vacuum simulations, it would be rather useful to enforce that `OPENMM_CPU_THREADS=1` is always used, making sure that folks don't lose a ton of performance because they forgot to set an environment variable.

## Proposal

Would it be possible to somehow set the number of CPU threads in the platform properties? This would overwrite any environment variable already set.

cc @mikemhenry @richardjgowers

**Comment by peastman** [comment]
You can specify it with a parameter when you create the simulation/context.

```python
platform = Platform.getPlatformByName('CPU')
simulation = Simulation(topology, system, integrator, platform, {'Threads':'1'})
```

Alternatively you can set it as the default value for the platform.

```python
platform.setPropertyDefaultValue('Threads', '1')
```

**Comment by IAlibay** [comment]
Ah that's awesome, sorry about this @peastman re-reading http://docs.openmm.org/latest/userguide/library/04_platform_specifics.html#cpu-platform I'm now realising I completely misread that `Threads` is a platform property 😅 

Thanks a lot!
