### ISSUE TITLE
Residues template for lipids

### ISSUE THREAD

**Issue by nbruciaferri** [openmm/openmm#4427]
Hi, 

I'm trying to build a system with an already existing membrane. 
After loading the PDB file and creating the ForceField object I try to create the system, but I keep receiving the error: `ValueError: No template found for residue 291 (POPI).  This might mean your input topology is missing some atoms or bonds, or possibly that you are using the wrong force field.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template`. 

I tried to check the old issues about this topic as well as the FAQ and tried to understand what's wrong in my PDB but couldn't figure it out. Could you please help me?

The code I used to generate the system:
```python
from openmm.app import *
from openmm import *
import openmm.unit as openmmunit

pdb = PDBFile("membrane.pdb")
ff = ForceField("amber14-all.xml",  "amber14/tip3pfb.xml")
ff.createSystem(pdb.topology, nonbondedMethod=PME, nonbondedCutoff=10*openmmunit.angstrom, constraints=HBonds, hydrogenMass=1.5*openmmunit.amu)
```

Please find the PDB file attached.
Thanks!
[membrane.tar.gz](https://github.com/openmm/openmm/files/14172808/membrane.tar.gz)

**Comment by peastman** [comment]
Amber doesn't support POPI.  Here are all the lipid types it has.

```
$ fgrep "<Residue " lipid17.xml 
    <Residue name="DLPC">
    <Residue name="DLPE">
    <Residue name="DLPS">
    <Residue name="DLPA">
    <Residue name="DLPG">
    <Residue name="DMPC">
    <Residue name="DMPE">
    <Residue name="DMPS">
    <Residue name="DMPA">
    <Residue name="DMPG">
    <Residue name="DPPC">
    <Residue name="DPPE">
    <Residue name="DPPS">
    <Residue name="DPPA">
    <Residue name="DPPG">
    <Residue name="DSPC">
    <Residue name="DSPE">
    <Residue name="DSPS">
    <Residue name="DSPA">
    <Residue name="DSPG">
    <Residue name="DOPC">
    <Residue name="DOPE">
    <Residue name="DOPS">
    <Residue name="DOPA">
    <Residue name="DOPG">
    <Residue name="POPC">
    <Residue name="POPE">
    <Residue name="POPS">
    <Residue name="POPA">
    <Residue name="POPG">
    <Residue name="SDPC">
    <Residue name="DAPC">
    <Residue name="SDPE">
    <Residue name="DAPE">
    <Residue name="SDPS">
    <Residue name="DAPS">
    <Residue name="SDPA">
    <Residue name="DAPA">
    <Residue name="SDPG">
    <Residue name="DAPG">
    <Residue name="CHL1">
```

**Comment by nbruciaferri** [comment]
Hi @peastman thanks for the reply.

Unfortunately, the same error is raised even if I use lipids supported by Amber.
The same code as above raised this error: `ValueError: No template found for residue 291 (CHL1).  The set of atoms matches CHL1, but the bonds are different.  Perhaps the chain is missing a terminal group?  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template`.

Attached the PDB file.
[step5_input_openmm.tar.gz](https://github.com/openmm/openmm/files/14173044/step5_input_openmm.tar.gz)

**Comment by peastman** [comment]
The error message is different this time.  Notice that it says, "The set of atoms matches CHL1, but the bonds are different."  Your PDB file is missing CONECT records for the lipids.  For anything other than standard amino acids, nucleic acids, and water, a PDB file needs to specify which atoms are bonded to each other.  This is discussed in the FAQ entry linked in the error message.

**Comment by peastman** [comment]
How do you define the boundaries?  Given the Topology, it's easy to get a list of atoms that make up the membrane.

```python
membrane = [atom for atom in topology.atoms() if atom.residue.name == 'CHL1']
```

You could then find the minimum and maximum z coordinates of any lipid atom.

```python
lowerz = min(positions[atom.index][2] for atom in membrane)
upperz = max(positions[atom.index][2] for atom in membrane)
```

But the membrane isn't smooth, so a single z value is only a very rough measure of its extent.  Or perhaps you were asking about the boundary where it contacts the protein, not where it contacts the water?  There's also the issue of periodic boundary conditions.  If the membrane has gotten wrapped in a way that splits it between two periodic copies, the "upper" layer could be at the bottom of the box and the "lower" layer at the top of the box.

**Comment by nbruciaferri** [comment]
Thank you, that worked!
