### ISSUE TITLE
xml force field for coarse-grained protein

### ISSUE THREAD

**Issue by eva-not** [openmm/openmm#4428]
Hi, I would like to create a .xml force field file to simulate a coarse-grained protein by keeping only the CA atoms. The plan is to assign a different type to each CA to reflect the residues they came from, in order to specify distinct parameters for each type.

Initial PDB file with only CA atoms:
```
MODEL        1
ATOM      2  CA  TYR A   1      24.935  20.652  10.774  1.00  7.05      0    C  
ATOM     14  CA  TYR A   2      21.801  19.381   9.017  1.00  4.77      0    C  
ATOM     26  CA  ASP A   3      18.477  20.539  10.432  1.00  5.27      0    C  
ATOM     34  CA  PRO A   4      16.223  17.660  11.537  1.00  5.94      0    C  
ATOM     41  CA  GLU A   5      13.040  19.289  10.212  1.00  7.65      0    C  
ATOM     50  CA  THR A   6      14.200  20.806   6.941  1.00  8.29      0    C  
ATOM     57  CA  GLY A   7      17.256  18.676   6.039  1.00  5.88      0    C  
ATOM     61  CA  THR A   8      19.242  21.760   5.125  1.00  5.66      0    C  
ATOM     68  CA  TRP A   9      22.762  22.680   6.241  1.00  4.78      0    C  
ATOM     82  CA  TYR A  10      23.135  25.467   8.794  1.00  5.77      0    C  
ENDMDL
END
``` 

Modified PDB file ('chignolin_CA_mod.pdb'):
```
MODEL        1
ATOM      1  Y01 MOL A   1      24.935  20.652  10.774  1.00  7.05      0    C  
ATOM      2  Y02 MOL A   2      21.801  19.381   9.017  1.00  4.77      0    C  
ATOM      3  D03 MOL A   3      18.477  20.539  10.432  1.00  5.27      0    C  
ATOM      4  P04 MOL A   4      16.223  17.660  11.537  1.00  5.94      0    C  
ATOM      5  E05 MOL A   5      13.040  19.289  10.212  1.00  7.65      0    C  
ATOM      6  T06 MOL A   6      14.200  20.806   6.941  1.00  8.29      0    C  
ATOM      7  G07 MOL A   7      17.256  18.676   6.039  1.00  5.88      0    C  
ATOM      8  T08 MOL A   8      19.242  21.760   5.125  1.00  5.66      0    C  
ATOM      9  W09 MOL A   9      22.762  22.680   6.241  1.00  4.78      0    C  
ATOM     10  Y10 MOL A  10      23.135  25.467   8.794  1.00  5.77      0    C  
ENDMDL
END
```

I then attempted to create a xml file ('chignolin_CG.xml'):
```
<ForceField>
    <AtomTypes>
        <Type name="Y01" class="CA" element="C" mass="12.01078"/>
        <Type name="Y02" class="CA" element="C" mass="12.01078"/>
        <Type name="D03" class="CA" element="C" mass="12.01078"/>
        <Type name="P04" class="CA" element="C" mass="12.01078"/>
        <Type name="E05" class="CA" element="C" mass="12.01078"/>
        <Type name="T06" class="CA" element="C" mass="12.01078"/>
        <Type name="G07" class="CA" element="C" mass="12.01078"/>
        <Type name="T08" class="CA" element="C" mass="12.01078"/>
        <Type name="W09" class="CA" element="C" mass="12.01078"/>
        <Type name="Y10" class="CA" element="C" mass="12.01078"/>
    </AtomTypes>
    <Residues>
        <Residue name="MOL">
            <Atom name="Y01" type="Y01"/>
            <Atom name="Y02" type="Y02"/>
            <Atom name="D03" type="D03"/>
            <Atom name="P04" type="P04"/>
            <Atom name="E05" type="E05"/>
            <Atom name="T06" type="T06"/>
            <Atom name="G07" type="G07"/>
            <Atom name="T08" type="T08"/>
            <Atom name="W09" type="W09"/>
            <Atom name="Y10" type="Y10"/>
            <Bond atomName1="Y01" atomName2="Y02"/>
            <Bond atomName1="Y02" atomName2="D03"/>
            <Bond atomName1="D03" atomName2="P04"/>
            <Bond atomName1="P04" atomName2="E05"/>
            <Bond atomName1="E05" atomName2="T06"/>
            <Bond atomName1="T06" atomName2="G07"/>
            <Bond atomName1="G07" atomName2="T08"/>
            <Bond atomName1="T08" atomName2="W09"/>
            <Bond atomName1="W09" atomName2="Y10"/>
        </Residue>
    </Residues>
    <CustomBondForce energy="scale_bond*k*(r-r0)^2">
        <GlobalParameter name="scale_bond" defaultValue="1"/>
        <PerBondParameter name="k"/>
        <PerBondParameter name="r0"/>
        <Bond type1="Y01" type2="Y02" r0="0.38406684213227765" k="29609.790134061626"/>
        <Bond type1="Y02" type2="D03" r0="0.38292943369105936" k="25449.090880297124"/>
        <Bond type1="D03" type2="P04" r0="0.38830059806854733" k="34437.28960914899"/>
        <Bond type1="P04" type2="E05" r0="0.38922063666027773" k="24429.762352611662"/>
        <Bond type1="E05" type2="T06" r0="0.3844230653946638" k="36595.42219001036"/>
        <Bond type1="T06" type2="G07" r0="0.3822215102878467" k="30763.10400577501"/>
        <Bond type1="G07" type2="T08" r0="0.3822215102878467" k="30763.10400577501"/>
        <Bond type1="T08" type2="W09" r0="0.3808567383432638" k="24405.59066159349"/>
        <Bond type1="W09" type2="Y10" r0="0.3827271108112328" k="25457.37227189603"/>
    </CustomBondForce>
</ForceField>
```

When I try to use these to construct a system, I get the following error:
```
from openmm.app import *
from openmm import *
from openmm.unit import*
from sys import stdout

pdb = PDBFile('chignolin_CA_mod.pdb')
forcefield = ForceField('chignolin_CG.xml')

system = forcefield.createSystem(pdb.topology)
```

`ValueError: No template found for residue 1 (MOL).  This might mean your input topology is missing some atoms or bonds, or possibly that you are using the wrong force field.`

Should the xml file be written differently? Or is this related to the pdb format?

**Comment by peastman** [comment]
This will be a little bit complicated.  I'll go through it step by step.  You might want to look at [this FAQ entry](https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template) before reading further.  It explains how template matching works.  That will be important background for this.

The first problem is that your PDB file contains no bonds.  Normally the PDB reader fills in bonds for standard residues, but there aren't normally bonds between alpha carbons of successive residues, so it doesn't add them.  You need to add [CONECT](http://www.wwpdb.org/documentation/file-format-content/format33/sect10.html#CONECT) records to your PDB file to tell it which atoms should be bonded.

The next problem is that your PDB file and force field aren't consistent with each other.  The force field says the whole thing is a single residue, all described by a single `<Residue>` tag.  But your PDB file describes a series of separate residues.  Notice that every `ATOM` record has a different value in the residue column.  A Topology with a sequence of 1-atom residues doesn't match a template for a single residue with multiple atoms.  You need to make them consistent so they'll match.

The simplest way to do that is to edit the PDB file so every atom has the same residue number (and also a unique name).  Then the Topology and the ForceField will match: they each describe a single residue with a linear chain of carbons.  But there's a problem with that.  They can actually match in two different ways.  Which carbon is the start of the chain and which is the end?  It can match in either direction, and it makes no guarantees about which direction will end up getting chosen.  You could end up with the atom types being assigned in reverse.

So instead it's better to modify the XML file to define separate "residues" for each actual residue, each containing only a single carbon atom.  But that is also ambiguous.  Templates are matched on elements and bonds, and every one of your residues contains only a single carbon atom.  It doesn't know which template to match to each residue.  You therefore need to tell it which one to use with the `residueTemplates` argument to `createSystem()`.  See [the documentation](http://docs.openmm.org/latest/api-python/generated/openmm.app.forcefield.ForceField.html#openmm.app.forcefield.ForceField.createSystem) for details.

There is one other complication.  Templates are matched to residues based on the elements and bonds, including bonds to other residues.  Notice that your first two residues are both TYR, but the first one is a terminal residue with only a single bond, while the second one is bonded to two other residues.  A single template won't match both of them.  There are two possible solutions.  One is to create two templates for each residue type.  One is for terminal residues and has a single `<ExternalBond>` tag.  The other is for non-terminal ones and has two `<ExternalBond>` tags.  The other option is to just pass `ignoreExternalBonds=True` to `createSystem()` so it will completely ignore external bonds and accept each template as matching regardless of how many residues it is bonded to.

**Comment by eva-not** [comment]
Thanks a lot for the detailed reply Peter! I will have another go at it and share an update.

**Comment by peastman** [comment]
It means that residue isn't in `res_dict`.  Can you show your complete code?

**Comment by eva-not** [comment]
Sure!

```
from openmm.app import *
from openmm import *
from openmm.unit import*

pdb = PDBFile('chignolin_CA_mod.pdb')
forcefield = ForceField('chignolin_CG.xml')

res_dict = {
    "YTR": "YTR",
    "CAY": "CAY",
    "CAP": "CAP",
    "CAD": "CAD",
    "CAE": "CAE",
    "CAT": "CAT",
    "CAG": "CAG",
    "CAW": "CAW"
}

system = forcefield.createSystem(pdb.topology, residueTemplates=res_dict)
```
The pdb and xml files are the ones I pasted above. CAY is in the dictionary so not sure what's happening.

**Comment by peastman** [comment]
The keys need to be Residue objects, not strings.  See [the API documentation](http://docs.openmm.org/latest/api-python/generated/openmm.app.forcefield.ForceField.html#openmm.app.forcefield.ForceField.createSystem).  I think this ought to do it:

```python
residues = list(pdb.topology.residues())
res_dict = dict((res, res.name) for res in residues)
res_dict[residues[0]] = 'YTR'
res_dict[residues[-1]] = 'YTR'
```

**Comment by eva-not** [comment]
I see, I missed that detail. Just tested it - building the system and running a test simulation works. Closing this now, thank you very much!
