### ISSUE TITLE
Continue OpenMM simulation without checkpoint/XML

### ISSUE THREAD

**Issue by jgrosskopf** [openmm/openmm#4430]
This was a mistake on my part, and I have fixed my code to include checkpoints. But is there a way to continue a simulation without a checkpoint or XML file? I was thinking that I could load the simulation in MDAnalysis and output the last frame as a pdb, then re-specify the integrator, etc. and append it to the previous simulation runs. Would this work? Are there any other ways to do this?

Thanks!

**Comment by peastman** [comment]
That will more or less continue where you left off.  A saved state includes the following.

- Positions of particles
- Velocities of particles
- Box vectors (important for NPT simulations)
- Values of other parameters (if your simulation involves parameters that change with time)
- The current time

A checkpoint includes all of those plus

- The internal state of the random number generator

If you save and restore only the positions and box vectors, that will more or less continue where you left off.  Whether that's good enough depends on your application.

**Comment by jgrosskopf** [comment]
Right now, I'm looking to just finish the simulation. I hit the wall-clock time and the simulation ended, so picking up where I left off and finishing the remaining steps would be perfect. So the only thing that I wont be able to continue from the previous, using the method I suggested, is the internal state of the random number generator?

**Comment by peastman** [comment]
What format is it saved in?  Most trajectory formats don't store velocities.

**Comment by jgrosskopf** [comment]
It is saved as a DCD

**Comment by peastman** [comment]
Then you won't be continuing from the same velocities.  You'll need to generate new ones.

**Comment by jgrosskopf** [comment]
Okay, that's reasonable for my case. Thanks for the help.
