### ISSUE TITLE
AmberPrmtopFile problem with DCDReporter

### ISSUE THREAD

**Issue by nbruciaferri** [openmm/openmm#4431]
Hello,

I was trying to run a simulation using `openmm` from amber files that I created from an `openmm` `Topology` and `System` with the help of `parmed`.

When I load the topology file and create the system everything is fine, but when I try to save the trajectories using the `openmm DCDReporter` the following error is raised:

`
  File "/home/niccolo/micromamba/envs/cosolvkit/lib/python3.11/site-packages/openmm/app/dcdfile.py", line 84, in __init__
    if topology.getUnitCellDimensions() is not None:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AmberPrmtopFile' object has no attribute 'getUnitCellDimensions'`   

Here the code used to generate the amber files:
```python
def save_topology(self, topology: app.Topology, positions: list, system: System, simulation_format: str, forcefield: app.ForceField, out_path: str):
        """Save the topology files necessary for MD simulations according to the simulation engine specified.

        Args:
            topology (app.Topology): openmm topology 
            positions (list): list of 3D coordinates of the topology
            system (System): openmm system
            simulation_format (str): name of the simulation engine
            forcefield (app.Forcefield): openmm forcefield
            out_path (str): output path to where to save the topology files
        """
        new_system = forcefield.createSystem(topology,
                                             nonbondedMethod=app.PME,
                                             nonbondedCutoff=10*openmmunit.angstrom,
                                             removeCMMotion=False,
                                             rigidWater=False,
                                             hydrogenMass=1.5*openmmunit.amu)
        
        parmed_structure = parmed.openmm.topsystem.load_topology(topology, new_system, positions)   
        
        simulation_format = simulation_format.upper()
        if simulation_format == "AMBER":
            parmed_structure.save(f'{out_path}/system.prmtop', overwrite=True, format="amber")
            parmed_structure.save(f'{out_path}/system.rst7', overwrite=True, format="rst7")
      return
```

**Comment by peastman** [comment]
That means at some place in your code, you're passing an AmberPrmtopFile object to a function that expects you to pass a Topology.  I can't say where without seeing your complete code.  Wherever it is, you should pass `prmtop.topology` instead of `prmtop`.

**Comment by nbruciaferri** [comment]
Found the bug thanks to your comment. I was building the `Simulation` object from the `AmberPrmtopFile` instead of its topology. 

Thanks again for helping!
