### ISSUE TITLE
Minor API improvements

### ISSUE THREAD

**Issue by peastman** [openmm/openmm#4432]
I'd like to suggest a few minor API improvements.  They're for very common operations that I find myself frequently getting annoyed by.  These changes can be made without breaking backward compatibility.

The first is `Platform.getPlatformByName()`.  When I originally wrote it, I just had two overloaded versions of `getPlatform()`, one that took an index and one that took a name.  I grudgingly allowed myself to be argued into giving them different names, and I've regretted it ever since.  It irritates me every time I have to type the more wordy `getPlatformByName()`.  Overloading is a standard feature in C++.  It's well supported by SWIG.  There's no reason not to let people just type `getPlatform()`, and it comes up in almost every script I write.  We can still keep the old version as well for backward compatibility.

The other is `Context.getState()`.  Having to type `context.getState(getPositions=True, getForces=True, getEnergy=True)` is unnecessily long.  It can be shortened to `context.getState(positions=True, forces=True, energy=True)`.  That's both faster to type and easier to read.  We can still support the old versions of the arguments for backward compatibility.

**Comment by RaulPPelaez** [comment]
Good additions!
These could be confusing for new users reading "old" scripts, but nothing that cant be solved with good documenting and some deprecation warnings.

**Comment by peastman** [comment]
Fixed by #4437.
