### ISSUE TITLE
Box size bug

### ISSUE THREAD

**Issue by pitmanme** [openmm/openmm#4439]
Hi OpenMM developers, I am reporting a simulation crashing bug that I saw:

https://github.com/openmm/openmm/blob/e62bdf6adb8c776cdc945f2fb7a947f9b27fefd0/wrappers/python/openmm/app/modeller.py#L508

This creates a bug where for for example, any non-ion solute atom will have 2x padding distance to itself, but not to any other non-ion solute atom in the simulation box.

**Comment by pitmanme** [comment]
@peastman this could be a bug with how other tools interpret the definition of 'padding': the distance from solute to the box edge versus the distance between periodic images. If by padding here, you intended the latter please close this bug as the source isn't OpenMM.

**Comment by peastman** [comment]
The padding argument is defined in [the API documentation](http://docs.openmm.org/latest/api-python/generated/openmm.app.modeller.Modeller.html#openmm.app.modeller.Modeller.addSolvent):

> A bounding sphere containing the solute is determined, and the box size is set to (sphere diameter)+(padding). This guarantees no atom in the solute will come closer than the padding distance to any atom of another periodic copy. If the sphere diameter is less than the padding distance, the box size is set to 2*(padding) to ensure no atom is closer than the padding distance to two periodic copies of any other atom.
