### ISSUE TITLE
Deform simulations settings

### ISSUE THREAD

**Issue by puying1994** [openmm/openmm#4443]
I am right now doing a simulation about deformation along the y axis for my system.
Along the y axis, the vector length is increasing with a constant speed, while add the barostat for the x and z axis. I am wondering if the following settings are right (or the best)?

```python
# barostat setting:
system.addForce(MonteCarloAnisotropicBarostat((1, 0, 1)*bar, 300*kelvin, True, False, True))

# deformation simulation setting: 
y_start = 15.38
y_stop = y_start * 1.20
for step in range(1000):
    x_vec = simulation.context.getState().getPeriodicBoxVectors()[0]
    z_vec = simulation.context.getState().getPeriodicBoxVectors()[2]
    simulation.context.setPeriodicBoxVectors(x_vec, (0, y_start+(y_stop-y_start)*step/999, 0), z_vec)
    simulation.step(1000)



```

**Comment by peastman** [comment]
That mostly looks correct.  The one issue I see is that you need to add the barostat before you create the Simulation.  Once you create a Simulation, it doesn't see any further changes you make to the System.
