### ISSUE TITLE
Switching fn used for LRC of custom NB force different than used for energy

### ISSUE THREAD

**Issue by SimonBoothroyd** [openmm/openmm#4445]
Apologies if I'm forgetting some detail of how the long range correction is calculated when using a switching function, or just misreading the code... but it looks like the [switching function](https://github.com/openmm/openmm/blob/86988b90b82d14ed3d62d5f0671230428e40c9b7/openmmapi/src/CustomNonbondedForceImpl.cpp#L432) used when computing the long range correction of custom non-bonded forces is:

```c++
x*x*x*(10+x*(-15+x*6))
```

such that the thing being integrated is `r^2 * u(r) * (6x^5 - 15x^4 + 10x^3)`, where I believe that the switching function used when computing the energy is normally:

```c++
1-x*x*x*(10+x*(-15+x*6))
```

Am I missing something obvious?

**Comment by peastman** [comment]
The [user guide](http://docs.openmm.org/latest/userguide/theory/03_custom_forces.html#customnonbondedforce) gives the expression for the long range correction.  It involves integrating $E(r)(1-S(r))r^2$.  Inserting the definition of the switching function gives $E(r)(6r^5-15r^4+10r^3)r^2$.

**Comment by SimonBoothroyd** [comment]
Ah I thought I was missing something obvious - thanks I missed the the `1 - S(r)`!
