### ISSUE TITLE
Specifying parameters per pair of particles in CustomNonbondForce

### ISSUE THREAD

**Issue by NAS-SAA** [openmm/openmm#4447]
Hello readers,

I'm new to OpenMM and have a question about using CustomNonbondForce. Typically, we specify parameters per particle, but I need to integrate data from a paper that provides parameters per pair (like NaF, NaNa, and FF), rather than individually for each particle.

Does anyone know how I can define these parameters in my force field.xml file? Here's what I have so far:

`import numpy as np`
`print(f"""<ForceField>`
`<AtomTypes>`
 `<Type name="Na" class="Na" element="Na" mass="22.990"/>`
 `<Type name="F" class="F" element="F" mass="19.000"/>`
`</AtomTypes>`
`<Residues>`
 `<Residue name="Na">`
  `<Atom name="Na" type="Na"/>`
 `</Residue>`
 `<Residue name="F">`
 ` <Atom name="F" type="F"/>`
 `</Residue>`
`</Residues>`
`<NonbondedForce coulomb14scale="0.833333" lj14scale="0.5">`
 `<Atom type="Na" charge="1" sigma="1" epsilon="0"/>`
 `<Atom type="F" charge="-1" sigma="1" epsilon="0"/>`
`</NonbondedForce>`
`<CustomNonbondedForce energy="(a*exp(-r/b))-7117.28713" bondCutoff="0">`
` <PerParticleParameter name="a"/>`
 `<PerParticleParameter name="b"/>`
 `<Atom type="Na"  a="{}"  b="{}" />`
 `<Atom type="F"   a="{}"  b="{}"  />`
`</CustomNonbondedForce>`
`</ForceField>""" , file=open("FF.xml","w"))`

**Comment by peastman** [comment]
See #4422.
