### ISSUE TITLE
Have an average for pdb result

### ISSUE THREAD

**Issue by NAS-SAA** [openmm/openmm#4458]
Hello,
I have a question regarding PDBreporter. For my simulation, I am looking to generate a single frame of PDB output that represents the average of all steps. However, when using PDBreporter, it currently generates multiple frames of results. Is there an option in PDBreporter that allows me to obtain only one frame representing the average of all frames, similar to the output file in Gromacs where the PDB file contains only one frame which is the average of all steps?

**Comment by peastman** [comment]
What do you mean by the average?  If you simply take the average position of each atom over the simulation, you'll end up with almost all atoms on top of each other right at the center of the box.  Averaging over solvent positions is probably meaningless in any case.  For the protein, you probably want a conformation that in some way represents a typical conformation, but there are lots of ways you could define that.

The best approach is probably to save the whole trajectory to a DCD or XTC file, then compute an average structure based on it.  For example, MDTraj has a `compute_average_structure()` function that might work for you, though what it does is still pretty simple.
