### ISSUE TITLE
Problems in defining time-varying force

### ISSUE THREAD

**Issue by JinyinZha** [openmm/openmm#4459]
I am defining a time-varying force under the construction of issue 4305 [https://github.com/openmm/openmm/issues/4305](url). However, an error occurred when setting parameters changed by time:

`in method Context_setParameter, argument 3 could not be converted to type double`

My codes are as followed:
```
def cosForceSim(self,simu_info,pdb_file,cvs,r0s,T,fc_pull0=20000.0):
        w = 2 * 3.14 / simu_info["loop_step"] 
        fc_pull0 = fc_pull0*unit.kilojoules_per_mole*unit.nanometers**2
        system = self.prmtop.createSystem(nonbondedMethod=PME, constraints=HBonds,nonbondedCutoff=1*nanometer)
        system.addForce(MonteCarloBarostat(1*bar, 300*kelvin))
        for i in range(len(cvs)):
            cv_str = "0.5 * fc_pull%d * (cv%d - r0%d)^2"%(i,i,i)
            pulling_force = mm.CustomCVForce(cv_str)
            pulling_force.addCollectiveVariable("cv%d"%(i),cvs[i])
            pulling_force.addGlobalParameter("r0%d"%(i),r0s[i])
            system.addForce(pulling_force)
        integrator = LangevinMiddleIntegrator(T*kelvin, 1/picosecond, 0.002*picoseconds)
        simulation = Simulation(self.prmtop.topology, system, integrator,platform)
        for i in range(len(cvs)):
            fc_pull = fc_pull0 / dxys[i]
            hfc_pull = 0.5 * fc_pull 
            # Here is where the error occurred
            simulation.context.setParameter('fc_pull%d'%(i), hfc_pull*cos(w*simulation.context.getStepCount())+hfc_pull)
            print(fc_pull)
        pdb = app.PDBFile(pdb_file)
        simulation.context.setPositions(pdb.positions)  
        if self.inpcrd.boxVectors is not None:
            simulation.context.setPeriodicBoxVectors(*self.inpcrd.boxVectors)
        simulation.step(n_steps)
        return simulation

```
Here, cv is a torch force defined by openmmm-torch package.

I am wondering how I can fix this problem. I am looking forward to your answer. Thank you~

**Comment by JinyinZha** [comment]
Well if I change that statement into 

`simulation.context.setParameter('fc_pull%d'%(i), 1000*cos(0.000628*simulation.context.getStepCount())+1000)`

It will throw another exception

`Called setParameter() with invalid parameter name: fc_pull0`

Does that means `simulation.context.setParameter` cannot be used to set parameters in CVForce?

**Comment by peastman** [comment]
You need to add it as a global parameter.  You call `addGlobalParameter()` for `r0%d`, but not for `fc_pull%d`.

**Comment by JinyinZha** [comment]
Very thanks! I think I get the point. Firstly, I have to subscribe these parameters as global parameters. Then, can I make the parameter a time-varying parameter by `simulation.context.setParameter`.
