### ISSUE TITLE
Is it possible to add a reporter to an existing Context?

### ISSUE THREAD

**Issue by slochower** [openmm/openmm#4472]
Is it possible to add a reporter to an existing `openmm.Context` directly? 

For example, say I have serialized XML for a system and its state. Then I can create a context from the system, set the positions from the state, define an integrator, and continue to step the integrator. But if I want to take a closer look at the trajectory by adding a reporter, it seems there is no way to do this. I can't easily create a `Simulation` object because I don't have access to the topology information, so that rules out `Simulation.reporters.append(...)`. Is there another way to add a reporter? Using `Simulation.reporters.append(...)` are the only examples I can find in the documentation. 

```python
system = deserialize_xml(...)
state = deserialize_xml(...)

positions = state.getPositions(asNumpy=True)
boxvectors = system.getDefaultPeriodicBoxVectors()

_int = integrators.LangevinIntegrator(
    temperature=300 * unit.kelvin, timestep=4 * unit.femtoseconds
)
context = openmm.Context(system, _int, platform)
context.setPositions(positions)
context.setPeriodicBoxVectors(*boxvectors)
context.setVelocitiesToTemperature(300 * unit.kelvin)

# Would like to do something like...
# context.reporters.append(StateDataReporter(stdout, 10, step=True, potentialEnergy=True, temperature=True))

_int.step(100)
```

**Comment by peastman** [comment]
Reporters are a property of Simulations, not Contexts.  Reporters are written in Python, and Context is a C++ class.

The Topology is mainly used for reporters that need to write out information about molecular topologies, for example to a PDB file.  You can always create a fake topology.

```python
topology = Topology()
chain = topology.addChain()
residue = topology.addResidue("MOL", chain)
for i in range(system.getNumParticles()):
    topology.addAtom(f'H{i}', element.hydrogen, residue)
if system.usesPeriodicBoundaryConditions():
    topology.setPeriodicBoxVectors(system.getDefaultPeriodicBoxVectors())
```

That will work as long as you don't use any reporters that care about the real elements, residues, etc.

**Comment by slochower** [comment]
Great, thanks -- yes this works perfectly for `StateDataReporter`. Is there a way to back the topology out of the serialized system if I did want to write something like a PDB file or actual trajectory? I'm guessing not.

**Comment by peastman** [comment]
No, you need information that isn't present in the System.  It's best to keep that information around from however you originally created the System, for example as a PDB file.

You can still write a trajectory as a DCD file, since it doesn't store information about atoms or residues.  But then you'll have the same issue when you try to load and interpret it.

**Comment by slochower** [comment]
Got it, thanks.
