### ISSUE TITLE
Updating the box dimensions using PDBreporter

### ISSUE THREAD

**Issue by NAS-SAA** [openmm/openmm#4474]
Hi all,
After running the NPT simulation in OpenMM, the box dimensions should be updated to accommodate the system changes. However, when utilizing pdbreporter in OpenMM to generate the output PDB file, only the original box dimensions are recorded, failing to reflect the updated box dimensions post-simulation. Do you have any idea how I can find the final box dimension for at least the last frame of output.pdb file?

**Comment by peastman** [comment]
The PDB format doesn't support storing different box dimensions for each frame.  It only allows for a single box shape at the start of the file.  It's better to use a format like DCD or XTC that supports different box shapes for different frames.

**Comment by NAS-SAA** [comment]
That's a huge help. Thank you!
