### ISSUE TITLE
AMOEBA Parameters Consistency

### ISSUE THREAD

**Issue by sheepforce** [openmm/openmm#4475]
Dear OpenMM developers,
when playing around with the AMOEBA 2018 parameters in `amoeba2018.xml` I've noticed two peculiar things where I'm not sure how they impact the actual calculation and consistency of the force field.

  * In the `AmoebaOutOfPlaneBendForce` are three duplicate lines, e.g. https://github.com/openmm/openmm/blob/master/wrappers/python/openmm/app/data/amoeba2018.xml#L6334 and two more. The out of plane bends are the only forces where this is the case, but also in the original Tinker file: https://github.com/TinkerTools/tinker/blob/release/params/amoebabio18.prm#L1681. Does this imply that the force is added twice for this out of plane bend or simply a redundancy by mistake?
  * The `Multipole` records sometimes use negative atom types. Those are not defined in the `AtomTypes` but seem to have a special meaning in Tinker (to cite the [Tinker manual](https://dasher.wustl.edu/tinker/distribution/doc/sphinx/tinker/_build/html/text/keywords.html?highlight=key) "_The initial integer modifier, if positive, gives the atom type number for which a polarizability parameter is to be defined. If the first integer modifier is negative, then the parameter value to follow applies only to the specific atom whose atom number is the negative of the modifier._" Honestly, I'm not entirely sure how to understand this already from the Tinker perspective, but for OpenMM I couldn't find anything in the manual regarding use of negative type? What would happen for these records, e.g. here: https://github.com/openmm/openmm/blob/b0eb7713043b10edc6af144c7d0c3b222322b8e2/wrappers/python/openmm/app/data/amoeba2018.xml#L9773? Also, for this example in the original tinker file the multipole frame is (233, -234, -234) https://github.com/TinkerTools/tinker/blob/034b7059a18d84e514eab91afbb97f8cfd5ffab2/params/amoebabio18.prm#L5802, while in OpenMM it is (233, 234, -234), so one sign inverted. Reading the `processTinkerForceField.py` script I couldn't find any reasoning why this would change. Is this intended or a bug? 

Best,
Phillip

**Comment by peastman** [comment]
I'm not sure why the angle specifications were duplicated.  Possibly it was just a bug when the Tinker file was created?  OpenMM only adds it once.  It stops as soon as it finds a match.

For the multipoles, OpenMM reproduces the logic of Tinker.  It's a little odd, but trying to rationalize it would just create a risk of inconsistent behavior.  Doing exactly the same thing Tinker does is the best way to make sure we'll get identical results.

Here's the code.

https://github.com/openmm/openmm/blob/b0eb7713043b10edc6af144c7d0c3b222322b8e2/wrappers/python/openmm/app/forcefield.py#L4949-L4963

**Comment by sheepforce** [comment]
Thank you very much for your answer, that clears up some of my confusion. Then my only question left is about the linked multipole records with the inverted sign. While (233, -234, -234) in Tinker, in the OpenMM amoeba file it becomes (233, 234, -234), so a ZBisect in Tinker but a Bisector type in OpenMM? Is this intended?
