### ISSUE TITLE
How to keep total simulation time constant when restarting simulation?

### ISSUE THREAD

**Issue by asgharrazavi** [openmm/openmm#4476]
I notice that when I restart my simulation by using a checkpoint file, the simulation can run past the total number of steps. Is there a way to make sure simulations stop when it reached 100% of requested number of steps and not go beyond that? 

```python
steps = 250000000
dataReporter = app.StateDataReporter('log.log', 25000, totalSteps=steps)

simulation.step(steps)
```

Example output of log file when it runs past 100% requested time:
```107.7%,269150000,1076599.9946664365,-3463917.068206247,653173.4621156435,-2810743.6060906034,309.9146321875427,2153.3160542784763,1.0161847370653698,155
107.7%,269175000,1076699.9946653654,-3467348.9816548936,656348.7217354809,-2811000.2599194124,311.42121424308806,2153.491921707768,1.0161017491536941,155
107.7%,269200000,1076799.9946642944,-3466306.563103702,651643.9605553084,-2814662.6025483934,309.18892157467394,2152.084285494982,1.0167663614217286,155
```

**Comment by peastman** [comment]
`step(steps)` means to run for that number of steps.  If you want to run up to a fixed number of steps, you can write `step(steps-simulation.currentStep)`.

**Comment by asgharrazavi** [comment]
very nice! thanks!
