### ISSUE TITLE
Energy NaN issue trouble shooting

### ISSUE THREAD

**Issue by peter-zhang-chem** [openmm/openmm#4478]
Dear Peter,

I am running into the energy is NaN issue. The simulation fails immediately and I am pretty confident that none of my force functional form would give a NaH exception. I also have `simulation.minimizeEnergy` before simulation began. I wanted to get your opinion of what might be going on.

Here is the attachment for reproducing the results, thank you so much!
[Energy-NaH-testing.zip](https://github.com/openmm/openmm/files/14620005/Energy-NaH-testing.zip)

**Comment by peter-zhang-chem** [comment]
I suspect that I am not minimizing the energy of the structure correctly as I did not run into any issue with much small systems. Is `simulation.minimizeEnergy` the correct way to go about it or do I need to do something like this `openmm.LocalEnergyMinimizer.minimize(context)`?

**Comment by peastman** [comment]
Do you mean NaN?  It stands for "not a number".  If that isn't what you mean, I don't know what NaH refers to.

Have you looked at [this FAQ entry](https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#nan)?  It describes how to debug problems of that sort.

`simulation.minimizeEnergy()` is just a shortcut for calling LocalEnergyMinimizer.

**Comment by peter-zhang-chem** [comment]
Hi Peter, yes, NaN. I followed the steps on the FAQ entry - if I lower the time step to like 0.05 * unit.picoseconds, it runs fine (at least for now), but I think it will prolong my simulation time, right? I ran the same code with a smaller system and it was working fine. Now I added one more force (tested), and the system is much bigger. Is it common as the system size increases, the time step needs to be decreased? Thank you!

**Comment by peastman** [comment]
What sort of system are you simulating?  0.05 ps is 50 fs.  That's a huge step size for atomic systems, which usually have time steps in the range of about 0.5 to 4 fs.  If it's a coarse grained system, a large step size like that might be reasonable.  What step size do you expect to be stable?

**Comment by peter-zhang-chem** [comment]
Hi Peter,

Thank you so much for your time. Yes it is a coarse grained system, I was hoping to get a large time step. I think 20 fs is the largest time step I can get away with without NaN error. Everything else is working ok, thanks!
