### ISSUE TITLE
 Could not convert vdW epsilon term to <class 'float'>

### ISSUE THREAD

**Issue by H-EKE** [openmm/openmm#4479]
Hi,

Im trying to use a charmm parameter files that I generated with HTMD (ACEMD) with openmm8.1. When I run equilibration I got the following error code:

```
toppar_list = []
for file in os.listdir(toppar_path):
    if file.endswith(".prm") or file.endswith(".rtf"):
        toppar_list.append(os.path.join(toppar_path, file))

params = CharmmParameterSet(*toppar_list)

```

```
ls toppar/


par_all22_prot.prm    par_all36_carb.prm    par_all36_lipid.prm  par_all36_na.prm        par_all36_prot.prm
par_all35_ethers.prm  par_all36_cgenff.prm  par_all36m_prot.prm  par_all36_prot_mod.prm
top_all22_prot.rtf  top_all35_ethers.rtf  top_all36_carb.rtf  top_all36_cgenff.rtf  top_all36_lipid.rtf  top_all36_na.rtf  top_all36_prot.rtf



```
Traceback (most recent call last):
  File "/home/.conda/envs/openmm_test/lib/python3.12/site-packages/openmm/app/charmmparameterset.py", line 100, in _convert
    return type(data)
           ^^^^^^^^^^
ValueError: could not convert string to float: 'CTOFNB'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/.conda/envs/openmm_test/lib/python3.12/site-packages/openmm/app/charmmparameterset.py", line 478, in readParameterFile
    epsilon = conv(words[2], float, 'vdW epsilon term')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/.conda/envs/openmm_test/lib/python3.12/site-packages/openmm/app/charmmparameterset.py", line 102, in _convert
    raise CharmmFileError('Could not convert %s to %s' % (msg, type))
openmm.app.internal.charmm.exceptions.CharmmFileError: Could not convert vdW epsilon term to <class 'float'>

During handling of the above exception, another exception occurred:
```
Traceback (most recent call last):
  File "/home/openmm_test/equilibration.py", line 128, in <module>
    params = CharmmParameterSet(*toppar_list)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/.conda/envs/openmm_test/lib/python3.12/site-packages/openmm/app/charmmparameterset.py", line 148, in __init__
    for par in pars: self.readParameterFile(par, permissive=permissive)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/.conda/envs/openmm_test/lib/python3.12/site-packages/openmm/app/charmmparameterset.py", line 488, in readParameterFile
    raise CharmmFileError(str(e))
openmm.app.internal.charmm.exceptions.CharmmFileError: Could not convert vdW epsilon term to <class 'float'>
````

Does anyone have an idea how to fix this issue?

Thanks in advance!

**Comment by peastman** [comment]
Can you post the file producing the error?  Based on the exception, it sounds like an error in the file.  But I don't really know for sure without looking at the file.  It's finding a string ("CTOFNB") where it expects to find a number (the epsilon value for a vdW term).

**Comment by H-EKE** [comment]
Hi @peastman ,

Thanks for you reply! I'm using the following files 

```
#~~~ Main ~~~#
# Loading files
psf = CharmmPsfFile(psf_path)
pdb = PDBFile(pdb_path)

toppar_list = []
specific_params    = os.path.join(input_path, "parameters.prm")
specific_topol     = os.path.join(input_path, "parameters.rtf")

toppar_list.append(specific_topol)
toppar_list.append(specific_params)
params = CharmmParameterSet(*toppar_list)

```

[param.zip](https://github.com/openmm/openmm/files/14836194/param.zip)

**Comment by peastman** [comment]
Your file contains many repetitions of the line

>      CUTNB 14.0  CTOFNB 12.0  CTONNB 10.0  EPS 1.0  E14FAC 1.0  WMIN 1.5

scattered through the file.  Those options can't appear on their own.  They're part of the `NONBONDED` specification.  For example,

https://github.com/openmm/openmm/blob/b32720cc3eae99b98968f5560ac6ff728714f49e/wrappers/python/tests/systems/charmm-solvated/m14.prm#L95-L96

See [the CHARMM documentation](https://academiccharmm.org/documentation/version/c45b1/nbonds) for more details.
