### ISSUE TITLE
CPU Platform Scaling woes

### ISSUE THREAD

**Issue by proteneer** [openmm/openmm#448]
This is more of a self-reminder that I need to take a look at why the CPU platforms scales so craptastically.

4 cores ~10 ns/day (only 3 cores are really being used)
48 cores ~3.35 ns/day (only 20 cores are really being used)

We may be the first MD engine to exhibit reverse scaling.

To quote:

9:29pm] Grandpa_01: proteneer: one thing that was interesting when I started it on the 48 core it flashed a couple seconds at 35/ns day the dropped

**Comment by acadev** [comment]
Is there any plan for supporting OpenMP within openmm? This may be a repeat question but we are also seeing similar performance drop for openmm on intel based co-processors. Hence wondering if there would be a path forward for these types of accelerators. 

Thanks again for the help!

**Comment by peastman** [comment]
We already support multiple threads using pthreads.  OpenMP would have no advantage.

**Comment by peastman** [comment]
Closing this old issue.  We'll always keep looking for ways to improve scaling.
