### ISSUE TITLE
A code question about calculating forces

### ISSUE THREAD

**Issue by yongyouhe** [openmm/openmm#4491]
Hi,I have been reading the code of OpenMM regarding the calculation of forces. As mentioned in the Dev Guide, the calculated forces are accumulated into the force buffers. However, I found that the calculated forces are first converted from `long long` to `unsigned long long` before being added the force buffers. I am puzzled whether this operation would compromise the directionality of forces.
For example, the following are the code for calculating bonded forces. (Lines 149-177, CudaBondedUtilities.cpp in OpenMM 7.7.0)
```
string CudaBondedUtilities::createForceSource(int forceIndex, int numBonds, int numAtoms, int group, const string& computeForce) {
    maxBonds = max(maxBonds, numBonds);
    string suffix[] = {".x", ".y", ".z", ".w"};
    stringstream s;
    s<<"if ((groups&"<<(1<<group)<<") != 0)\n";
    s<<"for (unsigned int index = blockIdx.x*blockDim.x+threadIdx.x; index < "<<numBonds<<"; index += blockDim.x*gridDim.x) {\n";
    int startAtom = 0;
    for (int i = 0; i < (int) atomIndices[forceIndex].size(); i++) {
        int indexWidth = atomIndices[forceIndex][i].getElementSize()/4;
        string indexType = "uint"+context.intToString(indexWidth);
        s<<"    "<<indexType<<" atoms"<<i<<" = atomIndices"<<forceIndex<<"_"<<i<<"[index];\n";
        int atomsToLoad = min(indexWidth, numAtoms-startAtom);
        for (int j = 0; j < atomsToLoad; j++) {
            s<<"    unsigned int atom"<<(startAtom+j+1)<<" = atoms"<<i<<suffix[j]<<";\n";
            s<<"    real4 pos"<<(startAtom+j+1)<<" = posq[atom"<<(startAtom+j+1)<<"];\n";
        }
        startAtom += indexWidth;
    }
    s<<computeForce<<"\n";
    for (int i = 0; i < numAtoms; i++) {
        s<<"    atomicAdd(&forceBuffer[atom"<<(i+1)<<"], static_cast<unsigned long long>((long long) (force"<<(i+1)<<".x*0x100000000)));\n";
        s<<"    atomicAdd(&forceBuffer[atom"<<(i+1)<<"+PADDED_NUM_ATOMS], static_cast<unsigned long long>((long long) (force"<<(i+1)<<".y*0x100000000)));\n";
        s<<"    atomicAdd(&forceBuffer[atom"<<(i+1)<<"+PADDED_NUM_ATOMS*2], static_cast<unsigned long long>((long long) (force"<<(i+1)<<".z*0x100000000)));\n";
        s<<"    __threadfence_block();\n";
    }
    s<<"}\n";
    return s.str();
}
```
In the code above, the force is accumulated into the force buffer using the CUDA `atomicAdd` function, even though it is of type `unsigned long long`. I am wondering if perhaps I overlooked some code where the directional component of the force is added back in. 

Best regards.

**Comment by peastman** [comment]
It makes no difference.  That's the great thing about two's complement integer math.  There's no real difference between signed and unsigned.  All operations produce exactly the same result.  The only difference is in how you interpret the value, and that only matters when converting it to other types.  We first convert the float to a signed integer, which means the sign gets handled correctly.  Then we convert the signed integer to an unsigned integer (because there's no `atomicAdd()` for signed), but that doesn't change the value or the result of adding it to the output buffer.

**Comment by yongyouhe** [comment]
> It makes no difference. That's the great thing about two's complement integer math. There's no real difference between signed and unsigned. All operations produce exactly the same result. The only difference is in how you interpret the value, and that only matters when converting it to other types. We first convert the float to a signed integer, which means the sign gets handled correctly. Then we convert the signed integer to an unsigned integer (because there's no `atomicAdd()` for signed), but that doesn't change the value or the result of adding it to the output buffer.

I see. Since two's complement integer arithmetic is utilized, the binary representation of the `unsigned long long` resulting from accumulating the force into the force buffer is identical to that of a `long long`. Thus, converting forces back to the `long long` integer when calculating acceleration in integrators ensures the accuracy of the result. (this conversion is performed within the function parameters) 
Did I get your point?

Best regards.

**Comment by peastman** [comment]
Correct.

**Comment by yongyouhe** [comment]
> Correct.

I got it! Thank you for your reply!
