### ISSUE TITLE
Question: harmonic position constraints of protein

### ISSUE THREAD

**Issue by RuikangSun** [openmm/openmm#4493]
Hello community!

I want to reproduce the MD part of [this paper](https://pubs.acs.org/doi/full/10.1021/acs.jmedchem.4c00250) with OpenMM. Most steps were easy to reproduce. However, I am confused with these steps: 

> During all equilibration steps, the force constant of the harmonic position constraints on the lipid gradually decreased from 2.5 kcal/(mol Å2) to zero, while the force constant on the protein heavy atoms gradually decreased from 10.0 to 0.1 kcal/(mol Å2).

I am not sure if OpenMM can handle these. So I asked AI first. The answer is:

```
lipid_force_constant_start = 2.5 * unit.kilocalorie_per_mole / unit.angstroms**2
protein_force_constant_start = 10.0 * unit.kilocalorie_per_mole / unit.angstroms**2
lipid_force_constant_end = 0 * unit.kilocalorie_per_mole / unit.angstroms**2
protein_force_constant_end = 0.1 * unit.kilocalorie_per_mole / unit.angstroms**2

lipid_atoms = [atom.index for atom in topology.atoms() if atom.residue.name == 'LIPID']
protein_atoms = [atom.index for atom in topology.atoms() if atom.element.symbol not in ['H'] and atom.residue.name != 'LIPID']

custom_force = openmm.CustomCompoundBondForce(2, "0.5*k*(r-length)^2; k=k1 if (index1 in lipid_atoms) and (index2 in lipid_atoms) else k2 if (index1 in protein_atoms) and (index2 in protein_atoms) else 0")
custom_force.addGlobalParameter("k1", lipid_force_constant_start)
custom_force.addGlobalParameter("k2", protein_force_constant_start)
custom_force.addGlobalParameter("length", 0*unit.angstroms)  


for i in range(topology.getNumAtoms()):
    for j in range(i+1, topology.getNumAtoms()):
        custom_force.addBond(i, j)

system.addForce(custom_force)

simulation = Simulation(topology, system, integrator)
```

I also looked up [Standard Forces](http://docs.openmm.org/latest/userguide/theory/02_standard_forces.html), and [Custom Force](http://docs.openmm.org/latest/userguide/theory/03_custom_forces.html?highlight=small%20molecule).  

** My questions are: **
** 1. Can OpenMM standard forces handle these 'position constraints of protein during energy minimization' tasks? If so, which force should I choose? Is there any example? **
** 2. if the answer of 1 is no, Is the AI generated script above OK to use in this case? **

** Thank you, cheers! **

**Comment by peastman** [comment]
That's some very curious code it's generated!  It wrote a custom expression that is part algebraic expression and part Python.

[This cookbook entry](https://openmm.github.io/openmm-cookbook/latest/notebooks/cookbook/Restraining%20Atom%20Positions.html) shows how to do what you want.  To decrease the force constant you can call `simulation.context.setParameter('k', value)`.

**Comment by RuikangSun** [comment]
> That's some very curious code it's generated! It wrote a custom expression that is part algebraic expression and part Python.
> 
> [This cookbook entry](https://openmm.github.io/openmm-cookbook/latest/notebooks/cookbook/Restraining%20Atom%20Positions.html) shows how to do what you want. To decrease the force constant you can call `simulation.context.setParameter('k', value)`.

Very grateful!  ;  )
