### ISSUE TITLE
NumPy 2.0 support

### ISSUE THREAD

**Issue by mattwthompson** [openmm/openmm#4494]
I didn't find another discussion on this - are there plans to support 2.0? AFAICT, OpenMM doesn't hook deeply into the low-level stuff, so it might not be an onerous transition. 
More info: https://numpy.org/devdocs/numpy_2_0_migration_guide.html

There is now a 2.0.0rc1 releases and built (`conda-forge/label/numpy_dev` and https://pypi.org/project/numpy/2.0.0rc1/). I could blindly fire off the CI runs into the void, but I want to ask first.

**Comment by peastman** [comment]
I don't expect there to be much difficulty.  We only make very little use of numpy, and that is almost entirely through Python.  The only interaction with the native ABI is to get a pointer to the data for an array:

https://github.com/openmm/openmm/blob/b32720cc3eae99b98968f5560ac6ff728714f49e/wrappers/python/src/swig_doxygen/swig_lib/python/extend.i#L603-L604

**Comment by mattwthompson** [comment]
Great! The ABI is supposed to be stable now, so whatever changes are going to happen should be in the rc1 builds.
