### ISSUE TITLE
Dynamic dielectric constant for a coarse grain model

### ISSUE THREAD

**Issue by The4thOne** [openmm/openmm#4504]
Hi,
I am doing a coarse-grained simulation. Is there any way I can set the following conditions for Customnonbondedforce?

Condition: 
For calculating the ion-ion electrostatic interactions:
If the ions are within a cutoff distance from the center of mass of a group of residues, 
then we will use "dielectric_constant_1", 
else, outside the cutoff distance, we will use "dielectric_constant_2". 

Any suggestions will be appreciated. Thank you.

**Comment by peastman** [comment]
CustomNonbondedForce is a pairwise interaction between two particles.  It depends on the positions of the two particles, but not on the position of any third particle, much less the center of mass of a group of particles.

You could probably implement this with CustomCentroidBondForce.  For a small number of ions that could be fine, but it won't scale to large numbers of ions.

If you're willing to fix which particles use each dielectric instead of determining it dynamically, you could do it with a per-particle parameter.  Then you could periodically check their positions and update the parameter.

**Comment by peastman** [comment]
https://openmm.github.io/openmm-cookbook/latest/notebooks/cookbook/Restraining%20Atom%20Positions.html gives an example of updating parameters in a different context.  There are a couple of things to be aware of.  First, updating parameters is somewhat expensive.  It's ok to do it occasionally, but doing it every step will slow down your simulation a lot.  Second, this won't conserve energy.  Every time you change the parameters, you change to a different potential function.

**Comment by The4thOne** [comment]
Thanks!
How frequently I can update parameters in my system? Any cross-checking method or recommendations?

**Comment by The4thOne** [comment]
Hi,
I have made some progress. But still need some help!
Let's say I am using setParticleParameters() in a for loop then where should I use the updateParametersInContext(simulation.context) -- inside the for loop or outside??

code1:
for index in all_particle_indices:        
         ESForce.setParticleParameters(index, [float(charge[index])*u.elementary_charge, float(1/e_factor)])
         ESForce_rna_rna.updateParametersInContext(simulation.context)
or 
code2:
for index in all_particle_indices:        
         ESForce.setParticleParameters(index, [float(charge[index])*u.elementary_charge, float(1/e_factor)])
         ESForce_rna_rna.updateParametersInContext(simulation.context)
ESForce_rna_rna.updateParametersInContext(simulation.context)

**Comment by peastman** [comment]
You should loop over the particles and call `setParticleParameters()` on them.  Then call `updateParametersInContext()` just once at the end.

There's no limit on how often you can update them, but doing it too often will make the simulation run slower.  Every 100 steps probably won't affect the speed too much.  Try different frequencies and see how fast it is.

**Comment by The4thOne** [comment]
Fine!
Thanks!

**Comment by The4thOne** [comment]
Thank you!
