### ISSUE TITLE
adapting processTinkerForceField.py for small molecules

### ISSUE THREAD

**Issue by blakemertz** [openmm/openmm#4505]
I've been looking over [processTinkerForceField.py](devtools/forcefield-scripts/processTinkerForceField.py) and [residuesFinal.xml](devtools/forcefield-scripts/residuesFinal.xml) files to determine the best way to modify them for using them on small molecule force field parameters that are produced in poltype2 and had a couple of questions:

1. Would a good starting point be to add a new molecule type to the bioType for atoms in the residueDict? Currently there are only types defined for protein, nucleic acids, and water/ions:
```
    for residue in root.findall('Residue'):

        #  <Residue abbreviation="MET" loc="middle" type="protein" tinkerLookupName="Methionine" fullName="Methionine">
        abbr        = residue.attrib['abbreviation']
        loc         = residue.attrib['loc']
        type        = residue.attrib['type']
        tinkerName  = residue.attrib['tinkerLookupName']
        residueName = residue.attrib['fullName']
        isProtein   = False
        isWater     = False
        isDNA       = False
        isRNA       = False
        if type == 'protein':
            isProtein = True
        elif type == 'AmoebaWater':
            isWater = True
        elif type == 'dna':
            isDNA = True
        elif type == 'rna':
            isRNA = True
        else:
            continue

        atoms       = getXmlAtoms( residue.findall('Atom') ) 
        bondInfo    = getXmlBonds( residue.findall('Bond') ) 
```
2. How is the python script correctly assigning atom names/bonds from residuesFinal.xml when AMOEBA uses the same atom name for multiple atoms? For example, isoleucine has aliphatic hydrogens in 2s and 3s (e.g. HG2) that is converted to HG21, HG22, and HG23:
```
  <Residue abbreviation="ILE" loc="middle" type="protein" tinkerLookupName="Isoleucine" fullName="Isoleucine">
  <Atom name="C" tinkerLookupName="C" bonds="3" />
  <Atom name="CA" tinkerLookupName="CA" bonds="4" />
  <Atom name="CB" tinkerLookupName="CB" bonds="4" />
  <Atom name="CD1" tinkerLookupName="CD" bonds="4" />
  <Atom name="CG1" tinkerLookupName="CG1" bonds="4" />
  <Atom name="CG2" tinkerLookupName="CG2" bonds="4" />
  <Atom name="H" tinkerLookupName="HN" bonds="1" />
  <Atom name="HA" tinkerLookupName="HA" bonds="1" />
  <Atom name="HB" tinkerLookupName="HB" bonds="1" />
  <Atom name="HD11" tinkerLookupName="HD" bonds="1" />
  <Atom name="HD12" tinkerLookupName="HD" bonds="1" />
  <Atom name="HD13" tinkerLookupName="HD" bonds="1" />
  <Atom name="HG12" tinkerLookupName="HG1" bonds="1" />
  <Atom name="HG13" tinkerLookupName="HG1" bonds="1" />
  <Atom name="HG21" tinkerLookupName="HG2" bonds="1" />
  <Atom name="HG22" tinkerLookupName="HG2" bonds="1" />
  <Atom name="HG23" tinkerLookupName="HG2" bonds="1" />
  <Atom name="N" tinkerLookupName="N" bonds="3" />
  <Atom name="O" tinkerLookupName="O" bonds="1" />
  <Bond from="C" to="CA" />
  <Bond from="C" to="O" />
  <Bond from="CA" to="CB" />
  <Bond from="CA" to="HA" />
  <Bond from="CA" to="N" />
  <Bond from="CB" to="CG1" />
  <Bond from="CB" to="HB" />
  <Bond from="CB" to="CG2" />
  <Bond from="CD1" to="CG1" />
  <Bond from="CD1" to="HD12" />
  <Bond from="CD1" to="HD11" />
  <Bond from="CD1" to="HD13" />
  <Bond from="CG1" to="HG12" />
  <Bond from="CG1" to="HG13" />
  <Bond from="CG2" to="HG21" />
  <Bond from="CG2" to="HG23" />
  <Bond from="CG2" to="HG22" />
  <Bond from="H" to="N" />
  </Residue>
```
This ambiguity in atom naming becomes even more of an issue with output from poltype2, as atom names are defined with element names, since sdf is the input file format for FF parameter generation in polytype2. I understand that I would need to generate a lookup table for each of the molecules parameterized in poltype2 (i.e., a separate "residue" block in residuesFinal.xml for each small molecule) but I am unclear how the python script is identifying and correctly assigning atoms, bonds, and additional parameters based on what is included in residuesFinal.xml. Thanks.

**Comment by peastman** [comment]
That script was written a very long time ago, and was really only intended to convert the one force field.  Don't think of it as a general AMOEBA converter.  You're probably better off writing something from scratch, perhaps looking at that script just for guidance on how to do the conversion.

A general loader or converter for molecules parametrized with polytype *would* be very useful.

**Comment by blakemertz** [comment]
@peastman thanks for the quick response and explanation. I will bump this up my priority list even though I don't have a ton of bandwidth for it now.

Will mark this issue as closed and reopen when I get a working solution close to being ready.
