### ISSUE TITLE
How to set a periodic infinite long DNA system? by setUsesPeriodicBoundaryConditions

### ISSUE THREAD

**Issue by yjianzhu** [openmm/openmm#4507]
I have read some tutorials and documents. Redefining the forces `setUsesPeriodicBoundaryConditions(True)` may solve this problem.

How to modify my system (with topology and atoms, forces)? I have set the bond between the top atom and with bottom atom. 

Sorry for my confusing statements.

**Comment by peastman** [comment]
What you described sounds correct.  You need to add the correct bonds to your Topology.  Then use a ForceField to create a System from it, and call `setUsesPeriodicBoundaryConditions(True)` on each of the bonded forces in the System.

**Comment by yjianzhu** [comment]
> What you described sounds correct. You need to add the correct bonds to your Topology. Then use a ForceField to create a System from it, and call `setUsesPeriodicBoundaryConditions(True)` on each of the bonded forces in the System.

thanks a lot. I initialize my topology from gromacs topology file. If I bond two atoms, how does the system know the real bond atoms? If the distance is small enough, bond the atoms in the same box. Otherwise, bond the atom with the mirror box? 

I tried to list the force of the system by `system.getForces()` and modify them to `setUsesPeriodicBoundaryConditions(True)`. But it didn't work.

**Comment by peastman** [comment]
How do you create your System?  Do you call `createSystem()` on a GromacsTopFile or a ForceField?

If you create it directly from the Gromacs file, that file needs to describe an infinite molecule with the ends bonded to each other.  Modifying the Topology won't affect the System.  You'll still get whatever the Gromacs file describes.

> I tried to list the force of the system by system.getForces() and modify them to setUsesPeriodicBoundaryConditions(True). But it didn't work.

Please be more specific.  What exactly did you do, and what exactly happened?  Show your code.

**Comment by yjianzhu** [comment]
`
forcefield = ForceField( 'amber14/tip3pfb.xml',"amber14/DNA.OL15.xml")

pdb = PDBFile('2dna.pdb')


gmx_top_2 = GromacsTopFile('topol.top')
print(type(gmx_top_2.topology))

modeller = Modeller(gmx_top_2.topology, pdb.positions)
modeller.addSolvent(forcefield, model='tip3p', ionicStrength=0.15 * molar,boxSize=Vec3(8, 8, 3.375)*nanometers)` ceate my modeller and then 

`system = forcefield.createSystem(modeller.topology, nonbondedMethod=PME, nonbondedCutoff=1.0*nanometer, constraints=HBonds)` create system.

**Comment by yjianzhu** [comment]
> How do you create your System? Do you call `createSystem()` on a GromacsTopFile or a ForceField?
> 
> If you create it directly from the Gromacs file, that file needs to describe an infinite molecule with the ends bonded to each other. Modifying the Topology won't affect the System. You'll still get whatever the Gromacs file describes.
> 
> > I tried to list the force of the system by system.getForces() and modify them to setUsesPeriodicBoundaryConditions(True). But it didn't work.
> 
> Please be more specific. What exactly did you do, and what exactly happened? Show your code.

I want to simulate an infinite long DNA chain in the periodic box. The topology file has defined the bonds between the bottom atoms and top atoms. `Bond(<Atom 317 (O3') of chain 0 residue 9 (DC)>, <Atom 0 (P) of chain 0 residue 0 (DG)>)`

**Comment by peastman** [comment]
You didn't answer the questions.  See my post above.

**Comment by yjianzhu** [comment]
> You didn't answer the questions. See my post above.

```
from openmm.app import *
from openmm import *
from openmm.unit import *
from sys import stdout
from parmed.openmm import load_topology
# 使用前面的拓扑和结构，combined_traj
# 创建系统

# 这里由于cohex的力场需要自定义
forcefield = ForceField( 'amber14/tip3pfb.xml',"amber14/DNA.OL15.xml")

pdb = PDBFile('2dna.pdb')


gmx_top_2 = GromacsTopFile('topol.top')
print(type(gmx_top_2.topology))

modeller = Modeller(gmx_top_2.topology, pdb.positions)
modeller.addSolvent(forcefield, model='tip3p', ionicStrength=0.15 * molar,boxSize=Vec3(8, 8, 3.375)*nanometers)
system = forcefield.createSystem(modeller.topology, nonbondedMethod=PME, nonbondedCutoff=1.0*nanometer, constraints=HBonds)
integrator = LangevinMiddleIntegrator(300*kelvin, 1/picosecond, 0.002*picoseconds)
simulation = Simulation(modeller.topology, system, integrator)
simulation.context.setPositions(modeller.positions)
```

**Comment by yjianzhu** [comment]
> You didn't answer the questions. See my post above.

Refer to the code provided above. If the simulation is executed in that manner, the bond Bond(<Atom 317 (O3') of chain 0 residue 9 (DC)>, <Atom 0 (P) of chain 0 residue 0 (DG)>) will link the two atoms within the same box. I hope that the bond can automatically connect the nearest atoms within the periodic boxes.

**Comment by peastman** [comment]
Immediately after creating the System (and before creating the Simulation), you need to call `setUsesPeriodicBoundaryConditions(True)` on each of the bonded forces in it.  Otherwise the bond will connect atoms within the same periodic copy.

**Comment by yjianzhu** [comment]
> Immediately after creating the System (and before creating the Simulation), you need to call `setUsesPeriodicBoundaryConditions(True)` on each of the bonded forces in it. Otherwise the bond will connect atoms within the same periodic copy.

Thanks a lot. I made a mistake in that I set `setUsesPeriodicBoundaryConditions(True)` before the simulation.
