### ISSUE TITLE
How can I perform rigidbody simulation?

### ISSUE THREAD

**Issue by OkKakao** [openmm/openmm#4509]
Hi.

I'm trying to simulation alkali halide clusters in gas phase.

I want to maintain its structure during the simulation, and it must move, rotate during the simulation.

Therefore, I can't use massless particle method for the simulation.

Also, I tried custom forcefield for the  alkali halide cluster with high spring constants, but the simulation occasionally blew away.

I also recognize that there already exist the python script in https://github.com/openmm/openmm/issues/1604, However, I want to simulate it with expilcitly rigid molecules.

I noticed that there is a constraint algorithm for water molecules with SETTLE algorithm, Can I exclusively apply this method to other molecules?

Also, Here's one of my forcefield file and pdb file of my system. 

The forcefield was used in combnation with charmm_polar_2019.xml, and water molecules in the pdb file are omitted for convenience.

```
#Na2I.xml
<ForceField>
    <AtomTypes>
        <Type name="SOD-Na1" class="SODD" mass="23.0" element="Na"/>
        <Type name="SOD-Na2" class="SODD" mass="23.0" element="Na"/>
        <Type name="Drude-SOD-Na1" class="DRUD" mass="0.0"/>
        <Type name="Drude-SOD-Na2" class="DRUD" mass="0.0"/>
    </AtomTypes>
    <Residues>
        <Residue name="AHC">
            <Atom name="I" type="I-I" charge="3.733109717291181"/>
            <Atom name="DI" type="Drude-I-I" charge="-4.733109717291181"/>
            <Atom name="Na1" type="SOD-Na1" charge="1.687605146739124"/>
            <Atom name="DNa1" type="Drude-SOD-Na1" charge="-0.6876051467391241"/>
            <Atom name="Na2" type="SOD-Na2" charge="1.687605146739124"/>
            <Atom name="DNa2" type="Drude-SOD-Na2" charge="-0.6876051467391241"/>
            <Bond atomName1="I" atomName2="Na1"/>
            <Bond atomName1="I" atomName2="Na2"/>
        </Residue>
    </Residues>
    <HarmonicBondForce>
        <Bond class1="I-I" class2="SOD-SOD" length="0.296" k="1000000"/>
    </HarmonicBondForce>
    <HarmonicAngleForce>
        <Angle class1="SOD-SOD" class2="I-I" class3="SOD-SOD" angle="1.570796326794896" k="2000"/>
    </HarmonicAngleForce>
    <DrudeForce>
        <Particle type1="Drude-SOD-Na1" type2="SOD-Na1" charge="-0.6876051467391241" polarizability="0.00015700000000000005" thole="1.3"/>
        <Particle type1="Drude-SOD-Na2" type2="SOD-Na2" charge="-0.6876051467391241" polarizability="0.00015700000000000005" thole="1.3"/>
    </DrudeForce>
</ForceField>
```
```
HETATM 5492  I   AHC B   1       0.000   0.000   0.000  1.00  0.00           I
HETATM 5493 DI   AHC B   1       0.000   0.000   0.000  1.00  0.00          EP
HETATM 5494 Na1  AHC B   1       0.000   0.000   2.960  1.00  0.00          Na
HETATM 5495 DNa1 AHC B   1       0.000   0.000   2.960  1.00  0.00          EP
HETATM 5496 Na2  AHC B   1       0.000   0.000  -2.960  1.00  0.00          Na
HETATM 5497 DNa2 AHC B   1       0.000   0.000  -2.960  1.00  0.00          EP
TER    5498      AHC B   1
CONECT 5492 5496 5494
END
```

**Comment by peastman** [comment]
> I also recognize that there already exist the python script in https://github.com/openmm/openmm/issues/1604, However, I want to simulate it with expilcitly rigid molecules.

That's exactly what the script is for.  Did you try it?

**Comment by OkKakao** [comment]
> > I also recognize that there already exist the python script in #1604, However, I want to simulate it with expilcitly rigid molecules.
> 
> That's exactly what the script is for. Did you try it?

I read the https://github.com/openmm/openmm/issues/1604, but this simulation converts atoms into virtual sites.

So I didn't try.

Also, I found error in my custom xml file, and it worked well with some modification.

```
# original file

<HarmonicBondForce>
    <Bond class1="I-I" class2="SOD-SOD" length="0.296" k="1000000"/>
</HarmonicBondForce>
<HarmonicAngleForce>
    <Angle class1="SOD-SOD" class2="I-I" class3="SOD-SOD" angle="1.570796326794896" k="2000"/>
</HarmonicAngleForce>
```

```
# modified file

<HarmonicBondForce>
    <Bond class1="IAD" class2="SODD" length="0.296" k="1000000"/>
</HarmonicBondForce>
<HarmonicAngleForce>
    <Angle class1="SODD" class2="IAD" class3="SODD" angle="1.570796326794896" k="2000"/>
</HarmonicAngleForce>
```

**Comment by peastman** [comment]
It converts *particles* into virtual sites.  Any type of particle can represent an atom, whether or not it's a virtual site.
