### ISSUE TITLE
Unit.sqrt( )  consistency error

### ISSUE THREAD

**Issue by SchroedingersLion** [openmm/openmm#4518]
Greetings!

Calling the numpy `std` routine on a list containing a single `unit` element does lead to an error rather than to the correct value 0.

```python
import numpy as np
import openmm.unit as unit

unit_list1 = [10*unit.femtoseconds, 20*unit.femtoseconds]
print(np.std(unit_list1))   ## gives correct value 5.


unit_list2 = [10*unit.femtoseconds]
print(np.std(unit_list2))   ## should give 0 but gives error.

```

> ArithmeticError: Exponents in Unit.sqrt() must be even.

While it makes no practical sense to ask for the standard deviation of a single element, often the number of elements in a list is set automatically (based on iteration number and measurement frequency), so that this error can occur and won't make sense to the user.

**Comment by peastman** [comment]
Numpy isn't compatible with OpenMM units.  It would be nice if you could pass quantities with units into arbitrary functions and have them always work, but that's often not the case.  If you want to call Numpy functions, you should first convert the quantities to ordinary numbers in a chosen set of units.

**Comment by SchroedingersLion** [comment]
Thanks Peter, so mixing the two isn't best practice then.
To be frank I was surprised that one could even use numpy functions on OpenMM objects. How does numpy know what to do with the units anyway?

**Comment by peastman** [comment]
A lot of numpy operation are implemented by calling methods on objects.  As long as an object implements those methods, many things will "just work".  You could actually make your code work by attaching units to a numpy array instead of to each element individually.

```python
>>> unit_list1 = np.array([10, 20])*unit.femtoseconds
>>> np.std(unit_list1)
Quantity(value=5.0, unit=femtosecond)
>>> unit_list1 = np.array([10])*unit.femtoseconds
>>> np.std(unit_list1)
Quantity(value=0.0, unit=femtosecond)
```
