### ISSUE TITLE
Brownian CustomIntegrator Algorithm 

### ISSUE THREAD

**Issue by lvotapka** [openmm/openmm#4520]
Hello All,

I just wanted to get your confirmation (or not) on whether this is a valid CustomIntegrator algorithm to recreate the OpenMM BrownianIntegrator. (I want to make a slight variation on the OpenMM Brownian Integrator without creating a whole plugin).

```
import openmm
from openmm import unit
class MyBrownianIntegrator(openmm.CustomIntegrator):
  def __init__(self, temperature, friction_coeff, dt):
    super(MyBrownianIntegrator, self).__init__(dt)
    kB = unit.BOLTZMANN_CONSTANT_kB * unit.AVOGADRO_CONSTANT_NA
    thermal_energy = kB * temperature
    self.addGlobalVariable("thermal_energy", thermal_energy)
    self.addGlobalVariable("friction_coeff", friction_coeff)
    self.addGlobalVariable("fscale", 0.0)
    self.addGlobalVariable("noiseAmplitude", 0.0)
    self.addPerDofVariable("oldx", 0)
    self.addComputeGlobal("fscale", "dt/friction_coeff")
    self.addComputeGlobal("noiseAmplitude", 
                                    "sqrt(2*thermal_energy*dt/friction_coeff)")
    self.addComputePerDof("oldx", "x")
    self.addComputePerDof("x", "x + fscale*f/m + noiseAmplitude*gaussian/sqrt(m)")
    self.addConstrainPositions()
    self.addComputePerDof("v", "(x-oldx)/dt")
```

**Comment by peastman** [comment]
As far as I can tell that mostly looks correct.  You should test it to be sure, of course.  The one thing I would add is this line at the start:

```python
self.addUpdateContextState()
```

If you use this with a barostat, for example, that's when the barostat will get a chance to change the box size.

**Comment by lvotapka** [comment]
Thanks @peastman, I will add the "addUpdateContextState" line as you said. How do you suggest that I test it? It does run successfully, and it does seem to run stably. Maybe I could try a single-particle system, and examine the distribution of positions after a certain number of timesteps with varying forces using this CustomIntegrator and the native BrownianIntegrator?

**Comment by peastman** [comment]
That would be a good test to make sure it's getting the diffuse rate correct.  Another simple test would be a harmonic oscillator, and check that the distribution of potential energies is correct.

**Comment by lvotapka** [comment]
Very good. Thanks @peastman

**Comment by lvotapka** [comment]
Additional tests that compared the point distributions and energy distributions generated by both the native OpenMM BrownianIntegrator, and the CustomIntegrator scheme shown above, seem to show similar enough results, for both harmonic potential energy surfaces, and also when a constant force is imposed. I feel confident that the algorithm above is correct - with @peastman 's improvement suggestion.
