### ISSUE TITLE
NaN forces with CustomCentroidBondForce as collective variable in CustomCVForce

### ISSUE THREAD

**Issue by nielskm** [openmm/openmm#4535]
Using a centroid distance as collective variable leads to `NaN` forces at the origin. This is understandable as the expression for the force is basically 0/0 at this point. But would it be possible to force OpenMM to return zero forces at this point?

Using OpenMM 8.1 this behavior can be produced by:
```
import openmm

system = openmm.System()
system.addParticle(1.0)
system.addParticle(1.0)
system.addParticle(16.0)
centroid_cv = openmm.CustomCentroidBondForce(1, "sqrt(x1^2 + y1^2 + z1^2)")
centroid_cv.addGroup([0, 1, 2])
centroid_cv.addBond([0])

force = openmm.CustomCVForce("0.5*centroid^2")
force.addCollectiveVariable("centroid", centroid_cv)
system.addForce(force)

platform = openmm.Platform.getPlatformByName("Reference")
context = openmm.Context(system, openmm.VerletIntegrator(1.0), platform)
context.setPositions([[-1.0, 0.0, 0.0], [1.0, 0.0, 0.0], [0.0, 0.0, 0.0]])
state = context.getState(getEnergy=True, getForces=True)
state.getForces(asNumpy=True)
```
returns
```
Quantity(value=array([[nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan]]), unit=kilojoule/(nanometer*mole))
```

**Comment by peastman** [comment]
Handling it automatically would be challenging.  If it were a standard force that we knew became singular at the origin, we could add a check for it.  But in this case it's just an arbitrary function of the coordinates.  It symbolically differentiates the expression with respect to the three coordinates and generates machine code to evaluate the derivative expressions, which happen to evaluate to nan at that point.

You might be able to handle it as part of your expression.  Something like `"select(r2, sqrt(r2), 0); r2 = x1^2 + y1^2 + z1^2"`.  Or if that still has numerical issues, you could force it to zero within some small radius of the origin by setting the first argument to `select()` to `max(0, r2-1e-14)`.

**Comment by nielskm** [comment]
Thank you for the good suggestions. I will close the issue!
