### ISSUE TITLE
OpenMM 8.1.1 on Summit failing CUDA specific make tests

### ISSUE THREAD

**Issue by JSLJ23** [openmm/openmm#4541]
## Summary:
I am trying to compile OpenMM 8.1.1 on [Summit](https://www.olcf.ornl.gov/summit/) and I've been running into test failures.
Just wondering are these critical to running MD simulations?
Nothing fancy for the MD simulations, just protein & ligand in explicit solvent.

## Build:
```
module load cuda/12.2.0
module load gcc
module load cmake

export OPENMM_CUDA_COMPILER="$(which nvcc)"
export CC="$(which gcc)"
export CXX="$(which g++)"

mkdir build && cd build
cmake .. \
    -D CMAKE_BUILD_TYPE=RELEASE \
    -D OPENMM_BUILD_OPENCL_LIB=OFF \
    -D CMAKE_INSTALL_PREFIX=$CONDA_PREFIX \
    -D PYTHON_EXECUTABLE="$(which python)"
    
make -j 8

make test
```

## Errors:
```
113/292 Test #113: TestCudaFFT3DSingle ............................***Exception: SegFault  1.06 sec
        Start 114: TestCudaFFT3DMixed
114/292 Test #114: TestCudaFFT3DMixed .............................***Exception: SegFault  2.14 sec
        Start 115: TestCudaFFT3DDouble
115/292 Test #115: TestCudaFFT3DDouble ............................***Exception: SegFault  2.35 sec
```

**Comment by swails** [comment]
The FFT solver is used in the electrostatic calculation of explicit solvent systems. 

It would be very strange if those tests segfaulted but the PME tests worked fine. Were those the only tests that failed?

**Comment by JSLJ23** [comment]
Yes only those test failed.

**Comment by peastman** [comment]
I think you can safely ignore them.  CudaFFT3D is an internal FFT implementation that isn't used anymore.  It now uses cuFFT instead.

**Comment by JSLJ23** [comment]
Ok thanks!
