### ISSUE TITLE
reporter that doesn't use reportInterval (help wanted)

### ISSUE THREAD

**Issue by bbharland** [openmm/openmm#4552]
Is there a way to write configurations to file upon request (by calling a function)?  The reporters I see in mdtraj and openmm all seem to require it.

**Comment by peastman** [comment]
See the [API documentation](http://docs.openmm.org/latest/api-python/app.html#loaders-and-setup) for the classes for different formats like DCDFile, XTCFile, and PDBxFile.  For example, if you want to write DCD frames at times of your choosing, create a DCDFile object at the start of a simulation and call `writeModel()` on it whenever you want to save a new frame.

```python
dcd = DCDFile('output.dcd', topology, dt)
...
state = simulation.context.getState(getPositions=True)
dcd.writeModel(state.getPositions(), periodicBoxVectors=state.getPeriodicBoxVectors())
```

**Comment by bbharland** [comment]
Thank you!
