### ISSUE TITLE
make failed for openmm (:EOF: Error: Unable to find 'swig.swg' :2: Error: Unable to find 'python.swg')

### ISSUE THREAD

**Issue by srilekha1993** [openmm/openmm#4555]
Hi,
Installing openmm from source getting make error(cmake execution successfully done):
[ 63%] Built target OpenMM
make: *** [Makefile:146: all] Error 2
 After 48% complete getting below error
:EOF: Error: Unable to find 'swig.swg'
:2: Error: Unable to find 'python.swg'
OpenMM.i:2: Error: Unable to find 'factory.i'
Even if the path of swig is connected to environment still getting above error. So please let us know the solution to this problem

**Comment by peastman** [comment]
How did you install swig and what version is it?  It sounds like it isn't able to find a lot of the files that should be included with it.

**Comment by srilekha1993** [comment]
I have installed it through conda and version is 4.2.1. Can you tell me how to resolve this issue

**Comment by peastman** [comment]
No idea.  I've never seen that error before.  It might indicate a corrupt swig installation.  Can you try uninstalling and reinstalling swig?  But I'm just guessing.  If that doesn't work, can you post the following?  Maybe one of them will contain a clue.

- The output of `conda list`
- The output of `which swig`
- The complete output when you try to build

**Comment by srilekha1993** [comment]
@peastman I uninstalled and reinstalled swig. 
Below is the **conda list file**
[conda_list.txt](https://github.com/user-attachments/files/15664100/conda_list.txt)
output of **which swig**:
/nfs/work05/srilekhax/miniconda3/envs/openmm_env_test/bin/swig
output of **make**
[outputof_make.txt](https://github.com/user-attachments/files/15665576/outputof_make.txt)

**Comment by peastman** [comment]
I don't see any error reported in your build output.  The last line of the file is

> [ 63%] Built target OpenMM

Was there any more to the output, where it said that something didn't work?

**Comment by srilekha1993** [comment]
After doing again make its showing below error
:EOF: Error: Unable to find 'swig.swg'
:2: Error: Unable to find 'python.swg'
OpenMM.i:2: Error: Unable to find 'factory.i'
OpenMM.i:4: Error: Unable to find 'std_string.i'
OpenMM.i:5: Error: Unable to find 'std_iostream.i'
OpenMM.i:6: Error: Unable to find 'std_map.i'
OpenMM.i:7: Error: Unable to find 'std_pair.i'
OpenMM.i:8: Error: Unable to find 'std_set.i'
OpenMM.i:9: Error: Unable to find 'std_vector.i'
OpenMM.i:26: Error: Unable to find 'windows.i'
OpenMMSwigHeaders.i:6: Error: Unable to find 'factory.i'
make[2]: *** [wrappers/python/CMakeFiles/BuildModule.dir/build.make:958: python/src/swig_doxygen/OpenMMSwig.cxx] Error 1
make[1]: *** [CMakeFiles/Makefile2:4829: wrappers/python/CMakeFiles/BuildModule.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by srilekha1993** [comment]
@peastman I uninstall swig and reinstall swig using **sudo apt install swig**
 which swig shows: (/usr/bin/swig)
  ln -s /usr/bin/swig ~/miniconda3/envs//nfs/work05/srilekhax/miniconda3/envs/openmm_env_test_sudoswig/bin/swig/bin/swig
After that cmake,make, make install,make test was successful
But make PythonInstall is failed. Showing below error
error: command '/nfs/work05/srilekhax/miniconda3/envs/openmm_env_test_sudoswig/bin/gcc' failed with exit code 1

**Comment by srilekha1993** [comment]
We have resolved this error by **export SWIG_LIB=/path/to/swig/share/swig/<version>/** before cmake run

**Comment by sjrdc** [comment]
for future reference: the SWIG executable location needs to be set on Windows and in the example, it is hardcoded in the CMakeLists.txt file to be in the Users/sorus directory. It won't be there for most users of this code except the author :).
