### ISSUE TITLE
Recommended approach to writing out a subset of atoms with XTCReporter/DCDReporter?

### ISSUE THREAD

**Issue by sukritsingh** [openmm/openmm#4564]
I was going through the docs about [XTCReporter](https://docs.openmm.org/latest/api-python/generated/openmm.app.xtcreporter.XTCReporter.html) and [DCDReporter](https://docs.openmm.org/latest/api-python/generated/openmm.app.dcdreporter.DCDReporter.html) and I realized there's not really a well-documented way to use these reporters to save out a subset of atoms (or maybe I'm missing it somewhere else?). 

Is there a general recommended way to achieve this "writing out a subset of atoms" if we're writing out into XTC or DCD files? I'm imagining a basic scenario where it is known which atom indicies are desired to be saved, but the rest do not need to be written out. I'm currently envisioning having to write some kind of `subsetXTCReporter` or the like - would this be the best way to go about this?Just looking for any guidance here!

Addendum: You can do this subsetting of atoms using the [XTCReporter](https://github.com/mdtraj/mdtraj/blob/ccd0c874361e4e31127e3803d3670d08d57f7933/mdtraj/reporters/xtcreporter.py#L42-L68) and [DCDReporter](https://mdtraj.readthedocs.io/en/latest/api/generated/mdtraj.reporters.DCDReporter.html#mdtraj.reporters.DCDReporter) in MDTraj - I'm just wondering if there are alternative approaches now that OpenMM has it's own native XTCReporter

**Comment by peastman** [comment]
It's not just a question of documentation.  They don't provide any easy way to do that.  PDBReporter does have an `atomSubset` option, but DCDReporter and XTCReporter don't.  That would be a useful option to add.

**Comment by sukritsingh** [comment]
> It's not just a question of documentation. They don't provide any easy way to do that. 

Ah ok! I was worried I was missing something lol.

>  They don't provide any easy way to do that. PDBReporter does have an atomSubset option, but DCDReporter and XTCReporter don't. That would be a useful option to add.

I assume the addition of the atomSubset option for `DCDReporter` and `XTCReporter` should look identical to `PDBReporter`? 

I know this would be useful for @Justin-J-Miller so depending on constraints/priorities, I'm happy to work with you on a PR for this, Justin!

**Comment by peastman** [comment]
That would be great.  Yes, the implementation can be copied directly.

**Comment by jakublala** [comment]
This would be very helpful, but the comment by @sef43 is a great alternative! Thanks!

**Comment by peastman** [comment]
This is implemented in #4741 if you want to try it out.
