### ISSUE TITLE
Raised error in using MonteCarloAnisotropicBarostat

### ISSUE THREAD

**Issue by junren00** [openmm/openmm#4566]
Hi

I am using .MonteCarloAnisotropicBarostat to equlibrate my system in only z direction by code:

```
barostat = mm.MonteCarloAnisotropicBarostat([1*unit.atmosphere,1*unit.atmosphere,1*unit.atmosphere], temp,scaleX=False,scaleY=False,scale=True, frequnecy = 25)
```

But I get an error reads:

```
TypeError: MonteCarloAnisotropicBarostat.__init__() got an unexpected keyword argument 'scaleX'
```

I have no idea why this will happen as the docs says the argument is scaleX

Best,

**Comment by peastman** [comment]
This is a quirk of how SWIG generates the Python wrappers for C++ classes.  For most methods it allows arguments to be specified either by position or by name.  But for constructors, it only supports position, not name.  Change it to

```python
barostat = mm.MonteCarloAnisotropicBarostat([1, 1, 1]*unit.atmosphere, temp, False, False, True, 25)
```

**Comment by junren00** [comment]
I got it. Thank you :)
