### ISSUE TITLE
Simulation in non-water explicit solvent

### ISSUE THREAD

**Issue by NooraAz** [openmm/openmm#4569]
Hi All. 

I want to simulate my protein in hexane. I pack the protein using packmol, which adds the solvent and NaCl ions to the solvated pdb. When I'm making the system in openMM it gives this error:
```
 No template found for residue 259 (UNL).
```

What happens is that in packmol, the hexane molecules are each added as a residue with name UNL and HETATM type, so the forcefield can't decode it. 

My question is, how is it possible to do such a simulation in openMM? is it possible at all? 

I use `amber14/protein.ff14SB.xml` forcefield.

**Comment by peastman** [comment]
Try using CHARMM36.  I believe it supports hexane.

```python
forcefield = ForceField('charmm36.xml', 'charmm36/water.xml')
```

You need to include the water file because it contains the ion definitions.

Another option if you want to stick with Amber is to parameterize the hexane with GAFF or OpenFF.  You can find instructions on how to do that at https://github.com/openmm/openmmforcefields.

**Comment by NooraAz** [comment]
Thanks so much! Just for future reference if someone else runs into this issue: 

For CHARMM forcefield to recognize your molecule, the atom names and bonds should be exactly the same as forcefield file. 
Here you can find a list of all small molecules in CHARMM, and if you download the files from here, these atom names with match. so in my case, I downloaded the pdb file for Hexane. 

However, you need to make two changes to these files:
1. changing ATOM to HATATM, 
2. Adding CONECT records. (defining bonds)

Then I used this modified file to solvate my protein using packmol. Packmol has a script called solvate_tcl which is originally written for solvating a protein with water, be it can be easily modified to use any other solvent. This script is easy to use because it neutralizes the system by adding ions automatically. 

and then in openmm charmm36 should be able to recognize the template.
