### ISSUE TITLE
Reset simulation step counter 

### ISSUE THREAD

**Issue by asiomchen** [openmm/openmm#4571]
I'm running simulations in stages:

NVT --> NPT --> Production 

Is it possible to somehow reset the simulation step counter to 0, instead of continuing from the last step from the previous stage?

Thank you in advance

**Comment by peastman** [comment]
```python
simulation.currentStep = 0
```

should do what you want.

**Comment by asiomchen** [comment]
Thank you very much, this is exactly what I need!
