### ISSUE TITLE
Create 8.1.2 patch

### ISSUE THREAD

**Issue by peastman** [openmm/openmm#4572]
We've had a few bug fixes since 8.1.1 that I think would be worth doing an 8.1.2 patch for.  I suggest including the following ones.

#4410: Write DCD version as 24 instead of 21 to fix ability of CHARMM to read DCD trajectories written by OpenMM.  This causes problems when using CHARMM to analyze trajectories saved to DCD files.
#4461: Fixed memory leak
#4485: Avoid overflow in large XTC files
#4501: reinitialize() remembers whether positions have been set.  This one is a very minor bug, so I don't care too much about whether it gets fixed, but the fix is a very simple one.
#4508: Fixed error when using both CustomNonbondedForce and LennardJonesForce
#4531: Allow multiple registrations of the same atom type if definitions identical.  This one is important, since it can cause parameterizing molecules with GAFF to fail.

**Comment by mikemhenry** [comment]
Will we get an RC before this is deployed on the main conda-forge channel?

**Comment by peastman** [comment]
Yes.  I'm aiming to do that today.

**Comment by peastman** [comment]
The release candidate packages are now up.  You can install them with

```
mamba install -c conda-forge/label/openmm_rc -c conda-forge openmm
```

Please try them out and see whether they work.  @j-wags can you verify that GAFF works correctly?

**Comment by j-wags** [comment]
I've tested the GAFFTemplateGenerator both in the [OpenMMForceFields CI](https://github.com/openmm/openmmforcefields/pull/342) and by calling it directly in a notebook using the OpenMMForceFields branch from @mikemhenry's [PR,](https://github.com/openmm/openmmforcefields/pull/334) and both look good. So I think this is good to go!

**Comment by mattwthompson** [comment]
No surprises elsewhere in the OpenFF stack

**Comment by peastman** [comment]
The packages for 8.1.2 are now up.
