### ISSUE TITLE
non-water solvent getting densed in minimization

### ISSUE THREAD

**Issue by NooraAz** [openmm/openmm#4574]
I have a PDB with a protein solvated in hexane (with ions) and here you can see it before minimization. I make this system using **Packmol**: 
<img src="https://github.com/openmm/openmm/assets/75523565/f705e48e-235a-4f02-8bb3-2514e6d03f54" width="400" height="400"/>

Then I run the following code to do an initial minimization on the system, and here is the output of minimization:
<img src="https://github.com/openmm/openmm/assets/75523565/0da99022-04ea-472e-b075-f891fc794e9b" width="400"/>

```
from openmm.app import *
from openmm import *
from openmm.unit import *
from sys import stdout
import sys

name = sys.argv[1]

# load pdb structure and set force fields
pdb = PDBFile('solvated.pdb')
forcefield = ForceField('charmm36.xml', 'charmm36/water.xml')

# add solvent
modeller = Modeller(pdb.topology, pdb.positions)

# local energy minimization
system = forcefield.createSystem(modeller.topology)
integrator = VerletIntegrator(0.001*picoseconds)
simulation = Simulation(modeller.topology, system, integrator)
simulation.context.setPositions(modeller.positions)
simulation.minimizeEnergy()

# save results
state = simulation.context.getState(getPositions=True, getVelocities=True, getForces=True, getEnergy=True, getParameters=True, enforcePeriodicBox=True)
with open('output'+name+'.pdb', 'w') as f:
    PDBFile.writeFile(simulation.topology, state.getPositions(), f)
with open('state_min'+name+'.xml', 'w') as f:
    f.write(XmlSerializer.serialize(state))
with open('system_min'+name+'.xml', 'w') as f:
    f.write(XmlSerializer.serialize(simulation.system))
```
I think I set my `createSystem` options wrong, but I couldn't figure out which settings I should use. I would appreciate your help. 

Here is the initial PDB file: 
[solvated.txt](https://github.com/user-attachments/files/16018053/solvated.txt)

**Comment by peastman** [comment]
The code above isn't complete.  You use a variable called `forcefield` that you never create.  Can you post the complete code to reproduce it?

**Comment by NooraAz** [comment]
Sorry, I had accidentaly removed it here. I added the forcefield now. 

I think I partially figured out what was wrong. 

I have a box, but the PDB didn't contain the `CRYST1` record, so I guess **OpenMM** would set the box size to some default value. Based on [this issue](https://github.com/openforcefield/smarty/issues/196), I added the `CRYST1` record as :
`CRYST1   76.524   89.024   81.917  90.00  90.00  90.00 P 21 21 21    0`
based on my box size in **Packmol** input file which was:
`inside box -38.262 -44.512 -40.9585 38.262 44.512 40.9585`

Now the box that I see after minimization has the same size, however there are two issues:
1. protein is out of box
2. it seems like the box is partitioned into 8 smaller boxes, you can see there is an empty space. 
Here is how it looks now:
<img src="https://github.com/openmm/openmm/assets/75523565/a655bd85-ba50-48e9-ae24-cf01d97cf965" width="400"/>

**Comment by peastman** [comment]
That looks fine to me.  I think it's just a different convention about where to center the box.  See [the FAQ](https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#periodic) for an explanation of why this happens and what you can do about it.

The division into smaller boxes is probably caused by the way Packmol builds the box.  I'm not familiar with it specifically, but building solvent boxes is often done by tiling a smaller, pre-equilibrated box.  The smaller boxes don't seem to fit together perfectly, leading to the lower density where they meet.  Equilibrating with a barostat for a little while should fix it.

**Comment by NooraAz** [comment]
Perfect then! Thanks!
