### ISSUE TITLE
Restraining the COM of a molecule on a plane

### ISSUE THREAD

**Issue by stefdoerr** [openmm/openmm#4576]
Hi, I am trying to restrain the center of mass (or even geometric center, I don't care) of a molecule to the xy plane at a fixed z coordinate.

I am using the python API of OpenMM. The only force I could find which calculates center of masses is the `CustomCentroidBondForce`, however it seems like it requires the user to specify at least two groups (since it's a bond force). I assume I could add some invisible particle at the position which I want to create the second group and then use something like `mm.CustomCentroidBondForce(2, "periodicdistance(x1, y1, z1, x1, y1, z2)")` which only calculates the periodic distance of z1 to z2?

Could you give me some hints on how to do this?

**Comment by peastman** [comment]
It's fine to specify 1 for the number of groups in each bond.  You can do something like

```python
force = CustomCentroidBondForce(1, 'k*periodicdistance(0, 0, z1, 0, 0, 0)^2')
```

which will restrain it to the plane z=0.

**Comment by stefdoerr** [comment]
Lovely! I'll try that. Thanks for the quick response!

**Comment by stefdoerr** [comment]
I have to reopen this. I got the following error:
```
OpenMMException: Parse error in expression "periodicdistance(x1, 0, 0, x0, 0, 0)": unknown function: periodicdistance
```
There is an option to do `setUsesPeriodicBoundaryConditions(True)` in the force which makes `distance` return the periodic distance.

However the `distance` function only accepts as input two groups and not individual x/y/z coordinates.

```
OpenMMException: Parse error in expression "distance(x1, 0, 0, x0, 0, 0)": wrong number of arguments to function: distance
```

So I am a bit stuck

**Comment by stefdoerr** [comment]
Steve helped me out. There is a `pointdistance` function. So the correct way to do it for say z=15.5 is this:
```py
    fc_pull_z = kz * unit.kilocalories_per_mole / unit.angstrom**2
    cv_z = mm.CustomCentroidBondForce(1, "pointdistance(0, 0, z1, 0, 0, z0)")
    cv_z.addGlobalParameter("z0", 15.5)
    cv_z.addGroup(atm_idx)
    cv_z.addBond([0])  # Required even for single groups
    cv_z.setUsesPeriodicBoundaryConditions(True)
    pullz = mm.CustomCVForce("0.5 * fc_pull_z * cv_z^2")
    pullz.addGlobalParameter("fc_pull_z", fc_pull_z)
    pullz.addCollectiveVariable("cv_z", cv_z)
    system.addForce(pullz)
```

**Comment by peastman** [comment]
Why do you wrap it in the CustomCVForce rather than putting the whole expression into the CustomCentroidBondForce?  It adds overhead.

**Comment by stefdoerr** [comment]
I need to keep track of those distances in a log file similar to this tutorial https://openmm.github.io/openmm-cookbook/latest/notebooks/tutorials/umbrella_sampling.html
