### ISSUE TITLE
A single PDB file with a single Ion - No template found for residue 1 (POT) 

### ISSUE THREAD

**Issue by DanielWicz** [openmm/openmm#4579]
I'm trying to simulate a single ion (POT) with OpenMM. But I can't create a system for no specific reason with built-in force field. 

The error I'm getting is:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/x/.local/x/envs/openmm_env/lib/python3.11/site-packages/openmm/app/forcefield.py", line 1218, in createSystem
    templateForResidue = self._matchAllResiduesToTemplates(data, topology, residueTemplates, ignoreExternalBonds)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/.local/x/envs/openmm_env/lib/python3.11/site-packages/openmm/app/forcefield.py", line 1433, in _matchAllResiduesToTemplates
    raise ValueError('No template found for residue %d (%s).  %s  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template' % (res.index+1, res.name, _findMatchErrors(self, res)))
ValueError: No template found for residue 1 (POT).  This might mean your input topology is missing some atoms or bonds, or possibly that you are using the wrong force field.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template

```

The system:
```
ATOM  11111  POT POT   111      -8.487   2.867  68.245  1.00  1.00      IONS
```
I tried here to set atom number and residue number to 1. Also to standardize it to the standard PDB file (this looks like a CHARMM-style pdb file and comes from mdtraj). But the result is the same. If I change POT to SOD or CLA, the error is with SOD or CLA. 

The code to run

```
from openmm.app import *
from openmm.unit import *
from openmm import *
pdb = PDBFile("initial_structure.pdb")
forcefield = ForceField('charmm36.xml', 'charmm36/water.xml')
system = forcefield.createSystem(pdb.topology, nonbondedMethod=PME, nonbondedCutoff=1*nanometer, constraints=HBonds)
```

Tried with OpenMM8.1.1 and Openmm8.0. Furthermore, with e.g. POPC lipid membrane it works. But with SOD/POT/CLA it doesn't

**Comment by peastman** [comment]
The problem is that the element column in your PDB file is missing.  See http://www.wwpdb.org/documentation/file-format-content/format33/sect9.html#ATOM.  Without that, it doesn't know what element it's supposed to be.

**Comment by DanielWicz** [comment]
> The problem is that the element column in your PDB file is missing. See http://www.wwpdb.org/documentation/file-format-content/format33/sect9.html#ATOM. Without that, it doesn't know what element it's supposed to be.

Thanks a lot! It works!  I was sitting 3h figuring out what's wrong ...

Though it would helpful to have a sanity check of the pdb file, like "This column is wrong or missing". I will even think about that to add this to OpenMM

**Comment by peastman** [comment]
See the FAQ entry linked in the error message for more information.  It discusses this problem.  When the element column is missing, it tries to guess the element from the atom name, which often works.  But in this case the atom name started with P, so it was guessing potassium.
