### ISSUE TITLE
Restricting protein movement, moving only solvent

### ISSUE THREAD

**Issue by NooraAz** [openmm/openmm#4590]
I have a series of conformations that are relaxed in Rosetta. I want to get the potential energy of those exact conformations in explicit solvents in MD. Even though I simulate for a very short time (0.2ns) the protein moves ~1 A. 

I want to know if there is a way to fix the protein atoms, and only let the solvent move around.

**Comment by peastman** [comment]
If you want to completely immobilize an atom, set its mass to zero by calling `system.setParticleMass(index, 0)`.  Be sure to do that *before* you create the Simulation.

**Comment by NooraAz** [comment]
If I set the mass to 0, would the solvent still feel the protein? for example, if it is water, will it be organized around polar groups? and will the potential energy include protein as well?

**Comment by peastman** [comment]
It only affects dynamics.  Massless atoms don't move, but forces are still calculated in the normal way.

**Comment by NooraAz** [comment]
Perfect then. Just to make sure, is the index the same as the second column index in the PDB file?

**Comment by NooraAz** [comment]
Okay, I figured out it's the same. Thanks! I'm closing the issue.

**Comment by peastman** [comment]
Did you intend to reopen this?  Is it not working?

**Comment by NooraAz** [comment]
Yes, sorry I needed to search a bit meanwhile. The issue is that in water, I get this error, which I think is because of Hbonds. Does it mean I can't set the protein's mass to 0 in water? or is there a way around it? 

Error:
```
Traceback (most recent call last):
  File "MD.py", line 33, in <module>
    simulation = Simulation(modeller.topology, system, integrator)
  File "open_mm/8.1.0.beta/.openmm_env/lib/python3.9/site-packages/openmm/app/simulation.py", line 102, in __init__
    self.context = mm.Context(self.system, self.integrator)
  File "open_mm/8.1.0.beta/.openmm_env/lib/python3.9/site-packages/openmm/openmm.py", line 17867, in __init__
    _openmm.Context_swiginit(self, _openmm.new_Context(*args))
openmm.OpenMMException: A constraint cannot involve a massless particle
```

my code:
```
 17 # load pdb structure and set force fields
 18 pdb = PDBFile(f'{input_folder}/{name}.pdb')
 19 forcefield = ForceField('charmm36.xml', 'charmm36/water.xml')
 20 # forcefield = ForceField('amber14/protein.ff14SB.xml', 'amber14/tip3p.xml')
 21 # forcefield.registerTemplateGenerator(gaff.generator)
 22
 23 # set up system
 24 modeller = Modeller(pdb.topology, pdb.positions)
 25 # modeller.addSolvent(forcefield, padding=1.0*nanometers, ionicStrength=0.15*molar)
 26 system = forcefield.createSystem(modeller.topology, nonbondedMethod=PME)
 27 number_of_protein_atoms = int(os.popen(f'grep -c "^ATOM" {input_folder}/{name}.pdb').read())
 28 for index in range(1,number_of_protein_atoms+1):
 29     system.setParticleMass(index,0)
 30
 31 # local energy minimization
 32 integrator = VerletIntegrator(1*femtoseconds)
 33 simulation = Simulation(modeller.topology, system, integrator)
 34 simulation.context.setPositions(modeller.positions)
 35 simulation.minimizeEnergy()
```

**Comment by peastman** [comment]
A constraint can't involve a massless particle.  That means you can't have constraints in whatever part of the system you're going to immobilize.  There's no need for constraints there, since they won't move anyway.

Your code above doesn't specify anything about constraints in the call to `createSystem()`.  That means you get the default options: `constraints=None` (no constraints in the protein) and `rigidWater=None`, which means to use the default set of constraints for the water model.  For the CHARMM36 water model, that means constraining all distances to make it fully rigid.

Your problem may be this line:

```python
for index in range(1,number_of_protein_atoms+1):
```

Atom indices start from 0, not 1.  You're probably skipping the first protein atom, then making one water atom massless.  That would explain the error.

**Comment by NooraAz** [comment]
Yes, that was it! Thanks so much!
