### ISSUE TITLE
Particle Not Being Impacted by CustomExternalForce

### ISSUE THREAD

**Issue by wlai0611** [openmm/openmm#4596]
I am trying to implement a Damped Harmonic Oscillator.  The issue I am facing is that the particle shows harmonic motion which does not get dampened even though I have a CustomExternalForce that specifies the damping.

  My approach is I start with the Harmonic Oscillator from openmmtools test systems which has harmonic motion but does not have any damping.  I planned to add the damping behavior by adding a CustomExternalForce below.  Below I create a custom damping force:

```
def get_damping_force(gamma):
    damping_force = openmm.openmm.CustomExternalForce('-gamma * px')
    damping_force.addGlobalParameter('gamma', gamma.value_in_unit_system(openmm.unit.md_unit_system))
    damping_force.addPerParticleParameter('px')
    damping_force.addParticle(0,[0])
    return damping_force

mass = 1.0 * openmm.unit.amu
K = 1 * openmm.unit.kilocalories_per_mole / openmm.unit.angstroms**2
ho = HarmonicOscillator(K=K, mass=mass)
(system, positions) = ho.system, ho.positions
damping_force = get_damping_force(gamma=10/openmm.unit.femtosecond)
system.addForce(damping_force)

```

And below I create a simulation with the system and step through the simulation:

```
initial_x = np.array([[10**-2,0,0]])
topology  = get_topology()  # just 1 H atom
integrator = get_integrator(cf=50.0) # NoseHooverChainVelocityVerletIntegrator
integrator.setRandomNumberSeed(123)
platform   = openmm.Platform.getPlatformByName('CUDA')
simulation = openmm.app.Simulation(topology,system,integrator,platform)
simulation.context.setPositions(initial_x)

def simulate(simulation,nsteps=100):
    positions = np.zeros(nsteps)
    mass = next(simulation.topology.atoms()).element.mass
    for step in range(nsteps):
        state = simulation.context.getState(getPositions=True,getVelocities=True,getForces=True)
        positions[step] = state.getPositions(asNumpy=True).value_in_unit(openmm.unit.nanometer)[0,0]
        damping_force = simulation.system.getForce(1)
        v = state.getVelocities(asNumpy=True)
        horizontal_momentum = mass * v[0][0]*openmm.unit.nanometer/openmm.unit.picosecond
        damping_force.setParticleParameters(0,0,[horizontal_momentum]) #does units of velocity be in default units?
        damping_force.updateParametersInContext(simulation.context)
        simulation.step(1)
    return {'x': positions,}

outputs = simulate(simulation, nsteps=10000)
fig, ax = plt.subplots()
ax.plot(outputs['x'])
ax.set_xlabel('Femtoseconds')
ax.set_ylabel('Nanometers in X Direction')
plt.show()
```
The plot below shows the x-coordinate of the particle which has harmonic motion but does not get dampened.  I tried different values of gamma to increase damping but the particle motion does not dampen.  Would you know how I can properly define the damping force?  
Thank you in advance!

![no-damp](https://github.com/user-attachments/assets/be09ddee-c43e-4d8f-805b-c186013136d8)

**Comment by peastman** [comment]
I think your problem may be this:

```
integrator = get_integrator(cf=50.0) # NoseHooverChainVelocityVerletIntegrator
```

Nose-Hoover is a type of velocity rescaling thermostat.  It maintains the desired temperature by scaling the velocities to maintain the correct total kinetic energy.  In your case, you have a system with effectively only one degree of freedom.  (The particle can move in three directions, but you arranged that it only actually moves in one of them.)  At each step you apply a damping force to slow the particle down.  And then thermostat sees that the temperature is too low, so it starts increasing the velocity to try to bring it back up to the target temperature again!

**Comment by wlai0611** [comment]
Thanks for the reply!  So I retried the code but swapping that line with a Verlet Integrator because  I believe Verlet doesn't have a thermostat:
```integrator = openmm.openmm.VerletIntegrator(1.0*openmm.unit.femtosecond)```

But the oscillations still seem to be undampened:

![image](https://github.com/user-attachments/assets/539c7ed9-133b-4a34-9046-af51769fe409)

Would you happen to have any examples of simulations with CustomExternalForce that are based on velocities of the atoms?

**Comment by peastman** [comment]
CustomExternalForce isn't normally used to create damping forces.  It only depends on positions, not velocities.  You're forcing it to do it by updating parameters at every step, but that's expensive.

Can you describe more about what you want to do?  The normal way of implementing damping forces is through the integrator.  For example, if you really just want a damped harmonic oscillator you can use a LangevinMiddleIntegrator with the temperature set to 0.  (You also should use the reference platform, since it will be much faster than CUDA for such a small system.)  But maybe this is just a demonstration, and you really want a large system with a damping force applied to just one or a few particles?  There are multiple ways you might do that, depending on your specific needs.

Here is [one of our test cases](https://github.com/openmm/openmm/blob/e30e5b69c25a132f7471827a6b1f4d61fa75aef2/tests/TestLangevinMiddleIntegrator.h#L49-L90) that uses LangevinMiddleIntegrator to simulate a damped harmonic oscillator.

**Comment by wlai0611** [comment]
Thanks for the reply!  This LangevinMiddleIntegrator based damped harmonic oscillator looks like what I am looking for.  So my current goal is to analyze the mathematical properties of the damped harmonic oscillator and the functionalities I was hoping to access were the ability to control the level of damping on the particle and get the resulting positions.   

Is there a way to access this test case in Python and increase/decrease the damping coefficient of this system?  Thanks again!

**Comment by peastman** [comment]
The Python API is almost identical to the C++ one.  Directly translating that code into Python gives

```python
system = System()
system.addParticle(2.0)
system.addParticle(2.0)
integrator = LangevinMiddleIntegrator(0, 0.1, 0.01)
forceField = HarmonicBondForce()
forceField.addBond(0, 1, 1.5, 1)
system.addForce(forceField)
context = Context(system, integrator, platform);
positions(2) = [Vec3(-1, 0, 0), Vec3(1, 0, 0)]
context.setPositions(positions)
```

The arguments to LangevinMiddleIntegrator are the temperature, the friction coefficient, and the step size.  For your purpose you'll probably prefer a single particle with a CustomExternalForce:

```python
force = CustomExternalForce('0.5*k*x^2')
```

**Comment by wlai0611** [comment]
Thanks so much!!  This is perfect!  I greatly appreciate the support.  I will close the issue.
