### ISSUE TITLE
Python CustomIntegrator slow with multiple beginWhileBlocks

### ISSUE THREAD

**Issue by c-matthews** [openmm/openmm#4599]
Hi all, I've been looking at introducing polishing iterations pre/post the usual Verlet loop, but I found that when I increased the number of iteration blocks (_not the number of iterations themselves_!) OpenMM seemed to hang.

I tracked down the problem to the number of While blocks that I introduce into the integrator. Below is a MWE that instantiates a blank integrator and adds N _while_ blocks to it. Note that the while blocks never actually run (because the argument is never satisfied), hence the slowdown is in the compilation of the method that happens in the initial step.

```
import openmm as mm
from openmmtools import testsystems
from time import time
import tabulate

results = []
for NumberOfWhiles in range(9):
    ig = mm.CustomIntegrator(0)
    ig.addGlobalVariable("iteration", 0 ) 
    ig.addPerDofVariable("dummyvar", 0)
    ig.addUpdateContextState()
    for i in range(NumberOfWhiles): 
            ig.beginWhileBlock("iteration<0")
            ig.addComputePerDof("dummyvar","f") 
            ig.endBlock()
        
    adp = testsystems.AlanineDipeptideVacuum(constraints=None)
    sim = mm.app.Simulation( adp.topology, adp.system, ig )
    sim.context.setPositions(adp.positions) 
    sim.context.setVelocitiesToTemperature(300*mm.unit.kelvin)
    t0 = time()
    sim.step(1)
    t1 = time()
    sim.step(100)
    t100 = time()
    results.append( (NumberOfWhiles, round(t1-t0,3), round(t100-t1,3) ) )
    
print( tabulate.tabulate( results, 
        headers=['Number of WHILE statements','Initial step time (s)','Time for 100 steps (s)'] ) )
```

This gives results on my local machine:
```
  Number of WHILE statements    Initial step time (s)    Time for 100 steps (s)
----------------------------  -----------------------  ------------------------
                           0                    0.004                     0.001
                           1                    0.005                     0.001
                           2                    0.006                     0.001
                           3                    0.008                     0.001
                           4                    0.019                     0.001
                           5                    0.155                     0.001
                           6                    1.573                     0.001
                           7                   13.685                     0.001
                           8                  138.234                     0.001
```
This was tested with OpenMM 8.1.1. I found similar results on a remote machine with an A100 GPU, though I don't think the GPU matters as I'd expect the method compilation is done on the CPU.

Roughly a factor of 10x in time per new While statement introduced. The presence of the `"f"` in the while computation makes all the difference here as well.
Thought this was interesting - apologies if there's an obvious solution here!

**Comment by peastman** [comment]
See #2866 for details about what's going on.  The startup time scales exponentially with the number of if or while blocks.  I introduced an optimization in response to that issue that helped for the particular case reported there.  But it won't help if you're actually doing integration within the loops.

**Comment by c-matthews** [comment]
Thanks @peastman! This explains what I'm seeing. I didn't realize it extended to `IF` blocks as well, that makes things more difficult.

- I will need to do integration in the loops. I had hoped a workaround might be to reduce things to one `WHILE` loop and approximate a switch statement using multiple `IF` statements, but I'm not convinced that'll help -- I expect nested `WHILE` and `IF`s probably compound things.
- As the blocks are composed serially it feels like there _should_ be (at least in principle) a way to prevent the exponential growth? Though perhaps that requires adding new code to the source.

**Comment by peastman** [comment]
In principle, yes.  It just requires a much more complicated analysis!

Can you post your actual integrator?  Doing the general algorithm would be very difficult, but there might be some special cases that would be easy to implement and would fix the problem for you.  One that occurs to me: if an integrator never looks at the energy (a lot of them don't), we can completely skip this analysis.

**Comment by c-matthews** [comment]
Haha yes I can believe it can be extremely complicated in the general case!

My integrator uses a Metropolis test, so it needs to compute the change in energy at the end of the step. The energy is not needed within the `WHILE` blocks.

The integrator looks like:

1. Compute energy
2. 3x serial `WHILE` blocks, doing some integration
3. Some Verlet steps 
4. 3x serial `WHILE` blocks, doing some integration
5. Compute new energy and Accept/Reject (using `IF` block) depending on energy delta

Happy to share the code with you via email if you think that's the best path forward.

**Comment by peastman** [comment]
If you can send the actual code that would be great.

**Comment by peastman** [comment]
I looked it over, and that's a pretty complicated case.  I don't see any easy fixes.

The best I can think of, which would still be pretty complicated to implement, is to identify steps in the algorithm that invalidate the forces and are outside of any if or while block.  Those are points where it's guaranteed the forces will be invalidated.  Anything that happens before one of them cannot affect anything after.  Break up the algorithm into segments bounded by those points.  Instead of tracing complete paths through the whole algorithm, we can trace each segment independently.

This doesn't help if the invalidation happens inside a block.  To optimize that case would take something more complicated.  But it would help your integrator, since you unconditionally modify the positions (thus invalidating the forces) at the end of every call to `_pre_solve()` and `_post_solve()`.

**Comment by c-matthews** [comment]
Thanks for looking it over, I've managed to do some rewrites so that it uses fewer `while` blocks, which solves my original problem.

Great to learn a bit more about how OpenMM works under the hood. Thanks for all your help!
