### ISSUE TITLE
energy is NaN error when increase in system size

### ISSUE THREAD

**Issue by LeoFHall** [openmm/openmm#4600]
Hi !
I've been running into an "Energy is NaN" issue when increasing the size of my system in a simulation of a crystal in a cube of water.
The molecules in the crystal are initially held in place by a restraint on their atoms
it works fine when I have 116 or 227 Glycine residues in my crystal, but crashes when I have over 300, so it doesn't seem to be a timestep issue or the restraint being poorly defined, the periodic box vectors are defined from a PDB file using openmm-setup to create the solvation box.
The energy minimisation step works, but then the simulation crashes on the first step of the equilibration.
I use GPUs on computecanada clusters, I tried doing the energy minimisation with CPU before switching back to GPU for the equilibration but that doesn't change the issue.
any ideas ?

**Comment by peastman** [comment]
[This FAQ entry](https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#nan) discusses causes of this problem and ways to debug them.  Since it fails on the very first step, you probably have some atoms with very large forces on them.  If you identify which atoms they are, you can probably tell what's causing the forces.

**Comment by LeoFHall** [comment]
I looked at the entry, but I'm surprised that it works fine in the smaller systems but not the larger ones given I'm building them from the same file originally, using the same protocol.
Could it be that it's a small issue on all atoms and so it grows out of proportion in larger systems even if it's compensated on the smaller one ?
How would I identify what atoms would cause this, because there's a lot...

thanks for the help

**Comment by peastman** [comment]
Do something like this.

```python
forces = simulation.context.getState(getForces=True).getForces()
for a, f in zip(simulation.topology.atoms(), forces()):
    if norm(f) > 10000*kilojoules_per_mole/nanometer:
        print(a, f)
```

**Comment by LeoFHall** [comment]
Hi !
Sorry it took me a while to test that turns out there was other issues in my code and I wasn't doing the energy minimization with CPU. I fixed that and put in the code snippet you suggested and different spots in the code to see where the issue arose, I now manage to optimise energy and equilibrate for 90000 steps (0.9% of the total, I have a 1fs time step and want 1ns) before getting the error again.

the print code doesn't output anything, should I try with a lower threshold for norm(f) ?

This is what my code looks like :
`
# System Configuration

nonbondedMethod = PME
nonbondedCutoff = 1.2*nanometers
ewaldErrorTolerance = 0.0005
constraints = None
rigidWater = False

# Integration Options

dt = 0.001*picoseconds #1 femtoseconds
temperature = 298*kelvin #25 celsius
friction = 1.0/picosecond
pressure = 1.0*atmospheres
barostatInterval = 25

# Simulation Options

steps = 10000000 #10ns with the 1fs timestep
equilibrationSteps = 1000000 #1ns equilibration
CPUplatform = Platform.getPlatformByName('CPU')
GPUplatform = Platform.getPlatformByName('CUDA')
platformProperties = {'Precision': 'single'}
pdbReporter = PDBReporter('trajectory-sphere-298-16-water-1.pdb', 10000)
dataReporter = StateDataReporter('trajectory-sphere-298-16-water-1.csv', 10000, totalSteps=steps,
    step=True, speed=True, progress=True, potentialEnergy=True, temperature=True, separator=',')
checkpointReporter = CheckpointReporter('checkpoint-298-16-1.chk', 10000)

# Create the system
print('Building system...')
topology = pdb.topology
positions = pdb.positions
system = forcefield.createSystem(topology, nonbondedMethod=nonbondedMethod, nonbondedCutoff=nonbondedCutoff,
    constraints=constraints, rigidWater=rigidWater, ewaldErrorTolerance=ewaldErrorTolerance)


#Adding a force to restrain atoms
kspring = 1000000
restraint = CustomExternalForce('k*periodicdistance(x,y,z,x0,y0,z0)^2')
restraint.addGlobalParameter('k',kspring*kilojoules_per_mole/nanometer)
restraint.addPerParticleParameter('x0') #for each particle a reference position is determined
restraint.addPerParticleParameter('y0')
restraint.addPerParticleParameter('z0')
for atom in topology.atoms(): #Apply restraint to all the particles except the fixed one
    if atom.residue.name == "ZGY":
        restraint.addParticle(atom.index,pdb.positions[atom.index]) #pdb.positions[i] gives the desired reference position ?
system.addForce(restraint)
print(system.getForces())
print("this should indicate Custom Force : ",system.getForce(5))

#setup system
system.addForce(MonteCarloBarostat(pressure, temperature, barostatInterval))
minimisationIntegrator = LangevinMiddleIntegrator(temperature, friction, dt)
inisim = Simulation(topology, system, minimisationIntegrator, CPUplatform)
inisim.context.setPositions(positions)

# Minimize and Equilibrate
print('Performing energy minimization with frozen nucleus...')
inisim.minimizeEnergy()
#inisim.minimizeEnergy(tolerance=Quantity(value=5, unit=kilojoule / nanometer * mole))
inistate = inisim.context.getState(getPositions=True,getEnergy=True)
minimpos = inistate.getPositions()
#minimnrj = inistate.getPotentialEnergy() #only useful for debugging

print('debug round 1')
forces = inisim.context.getState(getForces=True).getForces()
for a, f in zip(inisim.topology.atoms(), forces):
    if norm(f) > 10000*kilojoules_per_mole/nanometer:
        print(a, f)
        
print('generating system from frozen nucleus energy minimised system...')
equilibrationIntegrator = copy(minimisationIntegrator)
equisim = Simulation(topology,system,equilibrationIntegrator,GPUplatform)
equisim.context.setPositions(minimpos)

print('debug round 2')
forces = equisim.context.getState(getForces=True).getForces()
for a, f in zip(equisim.topology.atoms(), forces):
    if norm(f) > 10000*kilojoules_per_mole/nanometer:
        print(a, f)
        
        
print('Equilibrating with frozen nucleus...')
miniporter = PDBReporter('FrozenEquipos-298-16-1.pdb',equilibrationSteps) #save the last step of this equilibration run
equisim.context.setVelocitiesToTemperature(temperature)
equisim.reporters.append(miniporter) #report equilibration steps for tests
equisim.reporters.append(dataReporter)

print('debug round 3')
forces = equisim.context.getState(getForces=True).getForces()
for a, f in zip(equisim.topology.atoms(), forces):
    if norm(f) > 10000*kilojoules_per_mole/nanometer:
        print(a, f)
        
equisim.step(equilibrationSteps)
inter = perf_counter()
print("first equilibration time (mn)= ",(inter-start)/60)
`

and as an output I get
logfile :
`Traceback (most recent call last):
  File "/scratch/hall2401/OPENMM/Ball_dissolution/Simulate-Gly-ball_16_298_water_1.py", line 119, in <module>
    equisim.step(equilibrationSteps)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/MPI/gcc9/cuda11.4/openmpi4/openmm/8.0.0/lib/python3.10/site-packages/openmm/app/simulation.py", line 141, in step
    self._simulate(endStep=self.currentStep+steps)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/MPI/gcc9/cuda11.4/openmpi4/openmm/8.0.0/lib/python3.10/site-packages/openmm/app/simulation.py", line 243, in _simulate
    self._generate_reports(unwrapped, False)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/MPI/gcc9/cuda11.4/openmpi4/openmm/8.0.0/lib/python3.10/site-packages/openmm/app/simulation.py", line 263, in _generate_reports
    reporter.report(self, state)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/MPI/gcc9/cuda11.4/openmpi4/openmm/8.0.0/lib/python3.10/site-packages/openmm/app/statedatareporter.py", line 206, in report
    self._checkForErrors(simulation, state)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/MPI/gcc9/cuda11.4/openmpi4/openmm/8.0.0/lib/python3.10/site-packages/openmm/app/statedatareporter.py", line 365, in _checkForErrors
    raise ValueError('Energy is NaN.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#nan')
ValueError: Energy is NaN.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#nan
`

printed output:
`Building system...
Performing energy minimization with frozen nucleus...
debug round 1
generating system from frozen nucleus energy minimised system...
debug round 2
Equilibrating with frozen nucleus...
debug round 3
`

thanks for the help

**Comment by peastman** [comment]
Can you edit your post and add lines with \`\`\` immediately above and below the code?  It's getting rendered as markdown, which makes it hard to read.

You may need to use a smaller time step, since you use no constraints and flexible water.  I think people typical use a step size of 0.5 fs for that case.  Make sure that's really what you want, though.  You didn't include the part of the code where you create the ForceField, so I don't know what water model you're using.  Most of the common ones are designed to be rigid.

**Comment by LeoFHall** [comment]
oops sorry about that
I'm using TIP3P and Ambreff99sb

the 1fs timestep isn't an issue with the simulations run on a smaller system, I guess I could use 0.5fs on the equilibration but bump it up to 1fs on the production run ?

**Comment by peastman** [comment]
Instead of reducing the step size, I would change `rigidWater` to `True`.  TIP3P is designed to be rigid.

You're also using a pretty old force field and water model.  Unless you have a good reason for them, I would switch to Amber14 and TIP3P-FB.  They're more accurate.

**Comment by LeoFHall** [comment]
to compare new methodology with a paper that uses those in a similar system, but if that works I'll switch to the more recent ones.
I'll try that, thanks !

**Comment by LeoFHall** [comment]
ok so I tried both, the one with rigid water immediately crashed.
the other one I had a 0.5fs timestep for the first 1ns equilibration (with frozen glycine nucleus), then 1fs timestep for the 1ns of equilibration with free nucleus and 1fs for the 10ns production run, and I get the "ValueError: coordinate "136179621.18146703" could not be represented in a width-8 field" after ns

So I'll keep to a 0.5fs timestep from now I guess, the results will probably be more reliable anyway...

thanks again for the help !
