### ISSUE TITLE
General questions on choosing between constrained simulations and harmonic positional restraints

### ISSUE THREAD

**Issue by peter-zhang-chem** [openmm/openmm#4603]
Hey Peter,

I have a general question about choosing between constrained simulations by setting particle mass to 0 and applying harmonic positional restraints. I observed different results when answering one of my research questions using these two methods. Notably, the potential energy was significantly lower when setting the mass to 0 compared to applying harmonic restraints, and the temperature was about 3 K lower in the mass 0 scenario. In what situations would one choose constrained simulations over restrained simulations?

Thanks!

**Comment by peastman** [comment]
I don't think there's any universal answer to that.  It depends on what question you're trying to answer.  Each of them restricts the part of configuration space your simulation can explore, but they restrict it to different subsets.  In some cases you want it to explore an extended region around some point, for example in umbrella sampling.  In that case, a restraint is clearly the right thing to do.  In other cases you want to rigidly fix a degree of freedom and average only over the other degrees of freedom, for example when computing a PMF.  In that case a constraint is the right thing to do.  And in some cases either one could be effective at answering your question.

> the potential energy was significantly lower when setting the mass to 0 compared to applying harmonic restraints

Was that including the potential energy of the restraints?  Or were there other energy terms that got frozen by immobilizing the particles?  For example, if you freeze two particles that are bonded to each other, you also freeze the energy of the bond connecting them.

> the temperature was about 3 K lower in the mass 0 scenario

Perhaps your time step was a bit too large to integrate the restraint potential accurately?  A general rule is that the time step should be no larger than 10% the period of any harmonic motion in the system.  If it's larger than that, you'll add error which tends to increase the temperature.

**Comment by peter-zhang-chem** [comment]
Thank you. In my simulation, I am studying ions interaction with RNA. When I constrain the RNA by setting mass to 0, the preferential interaction coefficient, a thermodynamic parameter, increased from its ensemble average, which is strange. When I implemented restrained simulation, the thermodynamics is consistent with the ensemble average, which is expected. 

```
 #~~~~~~~~~~~~~~ for constraint RNA simulations~~~~~~~~~~~~~~~~#
 system = forcefield.createSystem(topology, constraints=AllBonds)
 for atom in topology.atoms():
     if atom.residue.name != 'Mg':
         system.setParticleMass(atom.index, 0 * unit.amu)
         print(f"{atom} mass was set to 0")
```

```
 #~~~~~~~~~~~~~~ for restraint RNA simulations~~~~~~~~~~~~~~~~#
 system = forcefield.createSystem(topology)
 restraint = CustomExternalForce('k*periodicdistance(x, y, z, x0, y0, z0)^2')
 system.addForce(restraint)
 restraint.addGlobalParameter('k', 500.0*unit.kilojoules_per_mole/unit.nanometer**2)
 restraint.addPerParticleParameter('x0')
 restraint.addPerParticleParameter('y0')
 restraint.addPerParticleParameter('z0')
 
 for atom in topology.atoms():
     if atom.name != "Mg":
         restraint.addParticle(atom.index, positions[atom.index])
```

Initially, I thought completely "freeze" the RNA confirmation is the way to go with constrained simulation. But things seems off. My timestep should be at 2 fs/step as that is what I used for the ensemble too.

**Comment by peastman** [comment]
I'm not familiar with the details of that situation, but it's not surprising if the interaction with a frozen RNA molecule is different from the interaction with a flexible one.  They're different physical situations.

**Comment by peter-zhang-chem** [comment]
The strange thing was the frozen RNA simulation had a output that is way higher than the ensemble average (and a distribution we did not see in the ensemble), it represents situations we observed in the low temperature RNA. Thank you for your inputs, it seems the harmonic positional restraints are preferred methods for the restrained conformation simulations to explore part of the ensemble.

**Comment by peastman** [comment]
> it represents situations we observed in the low temperature RNA.

You mean frozen = low temperature? :)

That's not just a joke.  You expect it to move less at low temperature and stay close to the energy minimum.

Is it ok to close this issue?

**Comment by peter-zhang-chem** [comment]
yes haha, thank you.
