### ISSUE TITLE
Get xtc_read() RuntimeError when restart simulation

### ISSUE THREAD

**Issue by devinzxmeng** [openmm/openmm#4604]
Hi, 
I keep getting this error when I restart my simulation. The simulation is prepared using Charmm-GUI membrane builder. Error shown below:

```
Traceback (most recent call last):
  File "main.py", line 165, in <module>
    main(args)
  File "main.py", line 136, in main
    simulation.step(inputs.nstep)
  File "anaconda3/envs/gpcr/lib/python3.10/site-packages/openmm/app/simulation.py", line 147, in step
    self._simulate(endStep=self.currentStep+steps)
  File "anaconda3/envs/gpcr/lib/python3.10/site-packages/openmm/app/simulation.py", line 247, in _simulate
    self._generate_reports(wrapped, True)
  File "anaconda3/envs/gpcr/lib/python3.10/site-packages/openmm/app/simulation.py", line 269, in _generate_reports
    reporter.report(self, state)
  File "anaconda3/envs/gpcr/lib/python3.10/site-packages/openmm/app/xtcreporter.py", line 73, in report
    self._xtc.writeModel(
  File "anaconda3/envs/gpcr/lib/python3.10/site-packages/openmm/app/xtcfile.py", line 117, in writeModel
    xtc_rewrite_with_new_timestep(
  File "openmm/app/internal/xtc_utils/xtc.pyx", line 143, in openmm.app.internal.xtc_utils.xtc_rewrite_with_new_timestep
RuntimeError: xtc_read(): could not get natoms
```

I have tried restarting using different file format like xml or chk, but they all get the same error. Simulation runs normally.

Thanks!

**Comment by peastman** [comment]
Can you post a set of files (script, input files) that can be used to reproduce the problem?  Thanks!

**Comment by devinzxmeng** [comment]
Below are my code, xml restart file, and charmm-gui input files. Simulation run using main.sh within the code.zip file. Some paths need to be revised to run the code.
Thanks!


[code.zip](https://github.com/user-attachments/files/16395273/code.zip)
[restart.xml.zip](https://github.com/user-attachments/files/16395274/restart.xml.zip)
[charmm-gui-openmm.zip](https://github.com/user-attachments/files/16395286/charmm-gui-openmm.zip)
[charmm-gui-toppar.zip](https://github.com/user-attachments/files/16395289/charmm-gui-toppar.zip)

**Comment by peastman** [comment]
That's a lot of code!  It's more than I can really go through.

Am I correct that the error only happens after the simulation has been running for a while?  XTC files record the total number of time steps that have been executed for each frame.  But they only use a 32 bit integer, which limits your total simulation length to about 2 billion steps.  If that happens we go back and rewrite the earlier part of the file to claim there was only one (much larger) time step between each pair of frames, so we can continue the simulation longer without exceeding what the format can store.  The error is happening in the code that does that.  It should only reach that code after 2 billion steps.

Looking back at your original post I'm a little confused:

> I have tried restarting using different file format like xml or chk, but they all get the same error. Simulation runs normally.

What did you mean when you said it runs normally?

**Comment by devinzxmeng** [comment]
Hi, 

The error will occur the first time OpenMM try to save trajectory to a xtc file.

What I mean by it runs normally is the simulation can continue run once I comment out the xtc reporter.

I think you are right about 32 bit integer creating this issue. Do you have any code to automate this process? I run every of my production run in 1250000000 steps, so probably the steps are inherited when I restart it.

**Comment by peastman** [comment]
You can reset the counter with

```python
simulation.currentStep = 0
```

before calling `step()` for the first time.  Would that work?

Still, it ought to be working.  We have [a test case](https://github.com/openmm/openmm/blob/792028058b6c1d698d7a5fc56a8d67d3b07938c3/wrappers/python/tests/TestXtcFile.py#L138-L149) that verifies this behavior.  I don't know why it works there but fails in your simulation.

**Comment by devinzxmeng** [comment]
Hi, 

`simulation.currentStep = 0` solves the problem. Thanks!
