### ISSUE TITLE
CV consider pbc

### ISSUE THREAD

**Issue by junren00** [openmm/openmm#4608]
Hi，

I am running a simulation of umbrella sampling.An ion is passed through a nanopore, and the distance between the ion and the center of the nanopore in the z direction is taken as the cv value.

I've read the  the example from https://openmm.github.io/openmm-cookbook/latest/notebooks/tutorials/umbrella_sampling.html

Then I made some changes:

    cv = mm.CustomExternalForce(f'z-{pore_center[2]}')
    cv.addParticle(index1, [])
    fc_pull = 1000.0 * unit.kilojoules_per_mole / unit.nanometers**2
    v_pulling = -4 * unit.nanometers / (1000 * unit.picosecond) 
    dt = simulation.integrator.getStepSize()
    total_steps = 1000000 
    increment_steps = 10

    pullingForce = mm.CustomCVForce('(0.5 * fc_pull * (cv-r0)^2)')
    pullingForce.addGlobalParameter('fc_pull', fc_pull)
    pullingForce.addGlobalParameter('r0', r0)
    pullingForce.addCollectiveVariable("cv", cv)
    system.addForce(pullingForce)
    simulation.context.reinitialize(preserveState=True)

The ion does smd on the upper half of the pore without problem.But the lower half will go directly to my lowest membrane.I think it's a matter of my cv values not taking into account the pbc Settings.But I don't know how to solve this problem in CustomExternalForce.

**Comment by peastman** [comment]
You mean you want the CV to be the distance from the center, taking periodic boundary conditions into account?  Try this.

```python
cv = mm.CustomExternalForce(f'periodicdistance(0, 0, z, 0, 0, {pore_center[2]})')
```

That's a distance, whereas your current expression is a signed value (positive on one side, negative on the other).  But I'm not sure how to reconcile that with periodic boundary conditions.

**Comment by junren00** [comment]
Thank you for your answer！
