### ISSUE TITLE
Slow Performance on GPU Using CustomNonBonded ( Custom Lennard Jones Pairs )

### ISSUE THREAD

**Issue by hongsrich** [openmm/openmm#4609]
Hi all,

I am relatively new to OpenMM and had a question about simulations with CustomNonBonded forces.  I am running a simulation using a CustomNonBonded Force such that each atom type has a distinct Lennard Jones pair with another atom type.  I am specifying these pairs in my system.xml file ( which I obtained through parmed and the gromacs -> openmm conversion functions).

![image](https://github.com/user-attachments/assets/bfb43d7a-e06c-4d30-91e9-bc62d39f4e26)

![image](https://github.com/user-attachments/assets/ef94cebb-b6ad-449b-b942-e8f6d27b1c59)

So in total, I have 27 atom types, hence 729 entries for "acoef" and "bcoef" from a 27 x 27 matrix.

However when I am running MD using a standard integrator, the performance is significantly slower than when I had used Lennard Jones pairs that have mixing rules ( ~ 300 ns/day vs 20 ns/day ).  

Submission script:
![image](https://github.com/user-attachments/assets/e5b2327c-f5e3-489c-8237-821205ffc2e0)

I was wondering if anyone might know what the issue may be and if there is any way to speed up this up.  Thanks!

**Comment by peastman** [comment]
There shouldn't be anything close to that much difference.  One thing that jumps out at me is the way you wrote the expression: `(a/r6)^2-b/r6; r6=r2*r2*r2; r2=r^2`.  You're thinking of it as if it were a procedural programming language and you needed to tell it how to do the computation.  Actually it's an algebraic expression, and you're making it unnecessarily complicated.  Instead write it as `a^2/r^12 - b/r^6`.  OpenMM knows how to compute integer powers efficiently.  Writing it as a sequence of multiplications prevents it from optimizing the evaluation properly.

Even with that, though, I'd be surprised to see such a large difference in speed.  Is there anything else different between the two simulations?

**Comment by Justin-J-Miller** [comment]
Tagging onto this issue (let me know if it ought to be a separate one), but I'm seeing something similar with a separate system from the above. In particular, we're seeing very poor scaling of the system on larger GPUs (4070 & 4090s, low TDP/power draw despite 100% utilization). One of the Folding@home testers had this for a GPU utilization profile on his 4090, where each of the long events (157, 236, 317) are invocations of `computeNonbonded`: 
![image](https://github.com/user-attachments/assets/4213b057-0746-42db-8226-f164469e3a90)

The system is huge (~1.2M atoms, largely tip4pd water) so I'm a bit surprised the system isn't scaling well on the larger cards, but our suspicition is that this is a result of the `CustomNonBondedForce` which has the same definition as [hongsrich](https://github.com/hongsrich)'s. 

I may have made a mistake in setting up the system, but these force definitions came about after I'd used `tleap` to solvate with tip4pd water in [amber99SBdisb](https://github.com/paulrobustelli/Force-Fields/tree/master/Amber_FFs/a99SBdisp) and loaded the system into openmm with the following:

```
import parmed
prmtop_crds = parmed.load_file('system.prmtop', 'system.inpcrd')
```

and used `prmtop_crds.createSystem` to initiate the system. This is all done with OpenMM 8.1.1 which has dramatic improvements over 8.0.0 in speed (thank you!). Happy to send any files along.

**Comment by hongsrich** [comment]
I have tried to change the algebraic expression and seems like I am still observing the slower performance ( 40,000 atoms on a mig mode H100 or A100s - I am getting 20 -25 ns/day ).  

There are some differences in the bonded parameters - but the functional form is still the same so I wouldn't expect those to significantly affect the performance.

**Comment by peastman** [comment]
Can you post a complete test case (include all scripts and input files) that reproduces the problem?  It's hard to guess what's happening without being able to try it.

**Comment by Justin-J-Miller** [comment]
Certainly, attached are the output files from amber, the script I used to initialize, heat, and equilibrate the solvated structures. 
[simulation-inputs.zip](https://github.com/user-attachments/files/16461891/simulation-inputs.zip)

The output xml files which are what I was actually running when we noticed the poor scaling were too large to attach here. If you'd like to skip ahead to those let me know and I'll upload in a repository.

Thanks!

**Comment by peastman** [comment]
I tried to run your script, but it failed with the exception

> openmm.OpenMMException: PeriodicTorsionForce: periodicity must be positive

Maybe best to post the XML files.

**Comment by Justin-J-Miller** [comment]
Uploaded the XML files here - https://github.com/Justin-J-Miller/low-gpu-utilization. Apologies about uploading off-thread, the state.xml is massive even after compression.

**Comment by peastman** [comment]
I wrote the following script to benchmark your system.

```python
from openmm import *
from openmm.app import *
from openmm.unit import *
import time

system = XmlSerializer.deserialize(open('system.xml').read())
state = XmlSerializer.deserialize(open('state.xml').read())
integrator = XmlSerializer.deserialize(open('integrator.xml').read())
context = Context(system, integrator)
context.setState(state)
integrator.step(10)
t1 = time.time()
integrator.step(1000)
t2 = time.time()
elapsedDays = (t2-t1)/86400.0
elapsedNs = (1000*integrator.getStepSize()).value_in_unit(nanosecond)
print(elapsedNs/elapsedDays)
```

Running on a RTX 4080, it gets 29.7 ns/day.  As a comparison, I ran the STMV benchmark which is a little smaller (1.07 million atoms rather than 1.22 million), and uses NonbondedForce for all nonbonded interactions.  It gets 50.7 ns/day.  So there's maybe a bit of a slowdown from using the lookup tables for the LJ parameters, but nothing like what @hongsrich reported.

**Comment by hongsrich** [comment]
Here is an example test case of Alanine pentapeptide in a very large box of water - using the system.xml that I have ( converted from GROMACS to a system.xml using the parmed functions), where I see slower than expected MD runs.  Wonder if there are some redundancies/issues in the system.xml file?

[CUSTOM.tar.gz](https://github.com/user-attachments/files/16465185/CUSTOM.tar.gz)

**Comment by peastman** [comment]
All of your nonbonded forces are set to NoCutoff.  That means they're computing the full set of N^2 interactions at every step, which is very slow.  It also means they aren't using periodic boundary conditions.

**Comment by hongsrich** [comment]
Ah got it thanks !!  I did not catch that.  Looks like the "method=0" was set for both of them which did not use cutoffs nor PBC.  I now set method = 4 for non bonded and method = 2 for the custom LJ and seems to be running  fine ( significantly faster) now.

**Comment by peastman** [comment]
Great!  Glad it was that simple.
