### ISSUE TITLE
Fails to recognize small molecule in PDB

### ISSUE THREAD

**Issue by andrew0901** [openmm/openmm#4615]
Hi,

I'm trying to run an MD simulation with several small molecules bound to the protein. I keep getting the following error even I have already registered the forcefield generator for corresponding small molecule (STE is the residue name of one of the molecules):

`ValueError: No template found for residue 574 (STE).  This might mean your input topology is missing some atoms or bonds, or possibly that you are using the wrong force field.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template`

[inputs.zip](https://github.com/user-attachments/files/16553024/inputs.zip)
I have tried loading the template both from smiles or from a .sdf file. And I have checked that the CONECT entries for ligands are present. I'm assuming there's something wrong with how my input PDB is formatted so it fails to recognize and map the residue to small molecule? This is how it looks in the input PDB (PS: the input PDB is prepared with openMM setup tool):

> ATOM   8475  HD3 PRO A 649      39.627   7.093  50.701  1.00  0.00           H  
> ATOM   8476  OXT PRO A 649      38.176   4.316  49.996  1.00  0.00           O  
> TER    8477      PRO A 649
> HETATM 8478  C1  STE A 701      22.842  44.882  22.433  1.00  0.00           C  
> HETATM 8479  O1  STE A 701      23.299  43.797  21.976  1.00  0.00           O  
> HETATM 8480  C2  STE A 701      22.840  46.100  21.550  1.00  0.00           C  
> HETATM 8481  O2  STE A 701      22.366  44.918  23.565  1.00  0.00           O  
> HETATM 8482  C3  STE A 701      21.971  47.239  22.038  1.00  0.00           C  
> HETATM 8483  C4  STE A 701      22.848  48.185  22.834  1.00  0.00           C  
> HETATM 8484  C5  STE A 701      22.030  49.330  23.422  1.00  0.00           C  
> HETATM 8485  C6  STE A 701      23.103  50.327  23.774  1.00  0.00           C  
> HETATM 8486  C7  STE A 701      22.594  51.324  24.737  1.00  0.00           C  
> HETATM 8487  C8  STE A 701      21.644  52.355  24.294  1.00  0.00           C  
> HETATM 8488  C9  STE A 701      21.774  52.737  22.911  1.00  0.00           C  
> HETATM 8489  C10 STE A 701      22.910  53.667  22.659  1.00  0.00           C  
> HETATM 8490  C11 STE A 701      22.330  54.545  21.532  1.00  0.00           C  
> HETATM 8491  C12 STE A 701      23.313  55.357  20.731  1.00  0.00           C  
> HETATM 8492  C13 STE A 701      22.861  55.560  19.283  1.00  0.00           C  
> HETATM 8493  C14 STE A 701      22.939  54.393  18.266  1.00  0.00           C  
> HETATM 8494  C15 STE A 701      24.319  54.375  17.588  1.00  0.00           C  
> HETATM 8495  C16 STE A 701      24.563  53.130  16.763  1.00  0.00           C  
> HETATM 8496  C17 STE A 701      25.978  52.632  16.692  1.00  0.00           C  
> HETATM 8497  C18 STE A 701      26.095  51.170  16.230  1.00  0.00           C  
> HETATM 8498  C1  STE A 702      31.821  42.888   3.990  1.00  0.00           C  
> HETATM 8499  O1  STE A 702      32.545  43.029   4.985  1.00  0.00           O  
> HETATM 8500  C2  STE A 702      30.497  43.534   4.021  1.00  0.00           C  
> HETATM 8501  O2  STE A 702      32.129  42.232   2.967  1.00  0.00           O  
> HETATM 8502  C3  STE A 702      30.273  44.207   2.683  1.00  0.00           C  
> HETATM 8503  C4  STE A 702      30.759  45.643   2.636  1.00  0.00           C  
> HETATM 8504  C5  STE A 702      30.030  46.204   1.417  1.00  0.00           C  
> HETATM 8505  C6  STE A 702      30.462  47.599   1.068  1.00  0.00           C  
> HETATM 8506  C7  STE A 702      29.883  48.540   2.076  1.00  0.00           C  
> HETATM 8507  C8  STE A 702      28.403  48.589   1.793  1.00  0.00           C  
> HETATM 8508  C9  STE A 702      27.947  50.012   1.967  1.00  0.00           C  
> HETATM 8509  C10 STE A 702      28.046  50.307   3.438  1.00  0.00           C  
> HETATM 8510  C11 STE A 702      26.720  49.901   3.985  1.00  0.00           C  
> HETATM 8511  C12 STE A 702      26.753  50.141   5.464  1.00  0.00           C  
> HETATM 8512  C13 STE A 702      25.649  49.287   6.008  1.00  0.00           C  
> HETATM 8513  C14 STE A 702      25.715  49.321   7.485  1.00  0.00           C  
> HETATM 8514  C15 STE A 702      25.060  50.554   7.985  1.00  0.00           C  
> HETATM 8515  C16 STE A 702      24.630  50.328   9.408  1.00  0.00           C  
> HETATM 8516  C17 STE A 702      23.683  51.450   9.743  1.00  0.00           C  
> HETATM 8517  C18 STE A 702      23.629  51.486  11.215  1.00  0.00           C  
> HETATM 8518  P   FAD A 703      24.007  29.274  21.677  1.00  0.00           P  
> HETATM 8519  PA  FAD A 703      22.414  30.463  19.533  1.00  0.00           P  
> HETATM 8520  O1P FAD A 703      24.713  28.323  20.784  1.00  0.00           O  
> HETATM 8521  O2P FAD A 703      23.620  28.845  23.064  1.00  0.00           O  
> HETATM 8522  O3P FAD A 703      22.652  29.722  20.941  1.00  0.00           O  
> HETATM 8523  C5' FAD A 703      24.349  31.767  22.462  1.00  0.00           C  
> HETATM 8524  O5' FAD A 703      24.888  30.602  21.796  1.00  0.00           O  
> HETATM 8525  C4' FAD A 703      25.351  32.898  22.380  1.00  0.00           C  
> HETATM 8526  O4' FAD A 703      25.607  33.263  21.025  1.00  0.00           O  
> HETATM 8527  C3' FAD A 703      24.838  34.106  23.157  1.00  0.00           C  
> HETATM 8528  O3' FAD A 703      24.902  33.804  24.594  1.00  0.00           O  
> HETATM 8529  C2' FAD A 703      25.547  35.413  22.793  1.00  0.00           C  
> HETATM 8530  O2' FAD A 703      25.367  35.816  21.380  1.00  0.00           O  
> HETATM 8531  C1' FAD A 703      24.942  36.474  23.669  1.00  0.00           C  
> HETATM 8532  C1B FAD A 703      18.431  27.552  16.186  1.00  0.00           C  
> HETATM 8533  N1  FAD A 703      27.395  37.573  23.648  1.00  0.00           N  
> HETATM 8534  N1A FAD A 703      15.216  23.813  14.773  1.00  0.00           N  
> HETATM 8535  O1A FAD A 703      23.698  31.030  19.008  1.00  0.00           O  
> HETATM 8536  C2  FAD A 703      28.646  38.016  23.509  1.00  0.00           C  
> HETATM 8537  C2A FAD A 703      16.453  24.151  14.358  1.00  0.00           C  
> HETATM 8538  C2B FAD A 703      18.423  29.075  16.129  1.00  0.00           C  
> HETATM 8539  O2  FAD A 703      29.575  37.307  23.856  1.00  0.00           O  
> HETATM 8540  O2A FAD A 703      21.231  31.356  19.730  1.00  0.00           O  
> HETATM 8541  O2B FAD A 703      17.956  29.563  14.890  1.00  0.00           O  
> HETATM 8542  C3B FAD A 703      19.903  29.386  16.369  1.00  0.00           C  
> HETATM 8543  N3  FAD A 703      28.901  39.367  23.236  1.00  0.00           N  
> HETATM 8544  N3A FAD A 703      17.239  25.146  14.773  1.00  0.00           N  
> HETATM 8545  O3B FAD A 703      20.621  29.487  15.156  1.00  0.00           O  
> HETATM 8546  C4  FAD A 703      27.904  40.269  23.002  1.00  0.00           C  
> HETATM 8547  C4A FAD A 703      16.623  25.854  15.746  1.00  0.00           C  
> HETATM 8548  C4B FAD A 703      20.388  28.202  17.228  1.00  0.00           C  
> HETATM 8549  C4X FAD A 703      26.573  39.739  22.886  1.00  0.00           C  
> HETATM 8550  O4  FAD A 703      28.215  41.405  22.671  1.00  0.00           O  
> HETATM 8551  O4B FAD A 703      19.300  27.244  17.253  1.00  0.00           O  
> HETATM 8552  C5A FAD A 703      15.370  25.626  16.277  1.00  0.00           C  
> HETATM 8553  C5B FAD A 703      20.768  28.567  18.638  1.00  0.00           C  
> HETATM 8554  C5X FAD A 703      24.408  39.892  22.166  1.00  0.00           C  
> HETATM 8555  N5  FAD A 703      25.564  40.524  22.550  1.00  0.00           N  
> HETATM 8556  O5B FAD A 703      22.084  29.189  18.617  1.00  0.00           O  
> HETATM 8557  C6  FAD A 703      23.426  40.623  21.460  1.00  0.00           C  
> HETATM 8558  C6A FAD A 703      14.627  24.544  15.759  1.00  0.00           C  
> HETATM 8559  N6A FAD A 703      13.378  24.251  16.149  1.00  0.00           N  
> HETATM 8560  C7  FAD A 703      22.315  40.003  20.928  1.00  0.00           C  
> HETATM 8561  C7M FAD A 703      21.362  40.789  20.063  1.00  0.00           C  
> HETATM 8562  N7A FAD A 703      15.088  26.560  17.262  1.00  0.00           N  
> HETATM 8563  C8  FAD A 703      22.154  38.608  21.101  1.00  0.00           C  
> HETATM 8564  C8A FAD A 703      16.166  27.311  17.329  1.00  0.00           C  
> HETATM 8565  C8M FAD A 703      20.931  37.896  20.575  1.00  0.00           C  
> HETATM 8566  C9  FAD A 703      22.999  37.934  21.997  1.00  0.00           C  
> HETATM 8567  C9A FAD A 703      24.187  38.528  22.443  1.00  0.00           C  
> HETATM 8568  N9A FAD A 703      17.126  26.941  16.421  1.00  0.00           N  
> HETATM 8569  C10 FAD A 703      26.424  38.345  23.224  1.00  0.00           C  
> HETATM 8570  N10 FAD A 703      25.174  37.834  23.152  1.00  0.00           N  
> HETATM 8571  O   HOH A 801       9.014  36.716  33.651  1.00  0.00           O  
> HETATM 8572  H1  HOH A 801       8.901  36.751  34.833  1.00  0.00           H  
> HETATM 8573  H2  HOH A 801       8.881  37.811  33.308  1.00  0.00           H  
> HETATM 8574  O   HOH A 802      26.963  67.147   7.973  1.00  0.00           O  
> HETATM 8575  H1  HOH A 802      27.870  67.856   7.680  1.00  0.00           H

And the script I'm running looks like:

```
from openmm.app import *
from openmm import *
from openmm.unit import *
from openff.toolkit import Molecule
from openmmforcefields.generators import GAFFTemplateGenerator
from sys import stdout
from pathlib import Path

pdb = PDBxFile("/wynton/home/degradolab/fhy/scripts/openMM/08_07_FAP_original/6yru.pdb",)
forcefield = ForceField('amber14-all.xml', 'amber14/tip3pfb.xml')

#add the ligands
input_ligand_files = ["/wynton/home/degradolab/fhy/scripts/openMM/08_07_FAP_original/FAD.sdf",
                      "/wynton/home/degradolab/fhy/scripts/openMM/08_07_FAP_original/FA1.sdf",
                      "/wynton/home/degradolab/fhy/scripts/openMM/08_07_FAP_original/FA2.sdf",
                      ]

'''
input_ligand_smiles = ["Cc1cc2c(cc1C)N(C3=NC(=O)NC(=O)C3=N2)C[C@@H]([C@@H]([C@@H](CO[P@@](=O)(O)O[P@](=O)(O)OC[C@@H]4[C@H]([C@H]([C@@H](O4)n5cnc6c5ncnc6N)O)O)O)O)O",
                        "CCCCCCCCCCCCCCCCCC(=O)O"
                        ]

for ligand_smile in input_ligand_smiles:
        ligand = Molecule.from_smiles(ligand_smile)
        forcefield.registerTemplateGenerator(GAFFTemplateGenerator(molecules=ligand).generator)
'''

for ligand_file in input_ligand_files:
    if Path(ligand_file).suffix == '.sdf':
        print('Adding ligand {} to the forcefield.'.format(ligand_file))
        # verify file exists:
        if not Path(ligand_file).exists():
            raise ValueError(f'Tried to add a ligand to the forcefield, but the file does not exist. Please check the path.\n\
                            File Not Found: {ligand_file}')
        ligand = Molecule.from_file(ligand_file)
        forcefield.registerTemplateGenerator(GAFFTemplateGenerator(molecules=ligand).generator)

system = forcefield.createSystem(pdb.topology, nonbondedMethod=PME,
        nonbondedCutoff=1*nanometer, constraints=HBonds)
```

**Comment by peastman** [comment]
Your script doesn't register a template generator for that residue.  You register ones for FAD, FA1, and FA2, but nothing for STE.

**Comment by andrew0901** [comment]
Oh so the template needs to match the name of the small molecule as well? Because FA1.sdf is just the STE residue. I thought they are matched by molecular topology

**Comment by peastman** [comment]
I didn't realize it was the same thing.

@mikemhenry @mattwthompson do you have any idea why GAFFTemplateGenerator is failing to match the residue?  The Molecule is created from a SDF file, and as far as I can tell it's identical to what's in the PDB file.

**Comment by mikemhenry** [comment]
We recently changed how the `GAFFTemplateGenerator` works, @andrew0901 what version of `openmmforcefields` do you have installed? Can you try installing version `0.12.0` and see if that fixes the issue?

**Comment by andrew0901** [comment]
I'm using exactly that version of 0.12.0. Could it be that there is requirement of explicit hydrogen in either the input pdb or .sdf for template generation? However, I've tried adding hydrogens in them but that seems not working.

**Comment by peastman** [comment]
Oh, of course!  That's exactly the problem.

```
>>> from openff.toolkit import Molecule
>>> ligand = Molecule.from_file('FA1.sdf')
[11:12:29] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
>>> ligand.atoms
[Atom(name=, atomic number=6), Atom(name=, atomic number=8), Atom(name=, atomic number=8), Atom(name=, atomic number=6), Atom(name=, atomic number=6), Atom(name=, atomic number=6), Atom(name=, atomic number=6), Atom(name=, atomic number=6), Atom(name=, atomic number=6), Atom(name=, atomic number=6), Atom(name=, atomic number=6), Atom(name=, atomic number=6), Atom(name=, atomic number=6), Atom(name=, atomic number=6), Atom(name=, atomic number=6), Atom(name=, atomic number=6), Atom(name=, atomic number=6), Atom(name=, atomic number=6), Atom(name=, atomic number=6), Atom(name=, atomic number=6), Atom(name=, atomic number=1), Atom(name=, atomic number=1), Atom(name=, atomic number=1), Atom(name=, atomic number=1), Atom(name=, atomic number=1), Atom(name=, atomic number=1), Atom(name=, atomic number=1), Atom(name=, atomic number=1), Atom(name=, atomic number=1), Atom(name=, atomic number=1), Atom(name=, atomic number=1), Atom(name=, atomic number=1), Atom(name=, atomic number=1), Atom(name=, atomic number=1), Atom(name=, atomic number=1), Atom(name=, atomic number=1), Atom(name=, atomic number=1), Atom(name=, atomic number=1), Atom(name=, atomic number=1), Atom(name=, atomic number=1), Atom(name=, atomic number=1), Atom(name=, atomic number=1), Atom(name=, atomic number=1), Atom(name=, atomic number=1), Atom(name=, atomic number=1), Atom(name=, atomic number=1), Atom(name=, atomic number=1), Atom(name=, atomic number=1), Atom(name=, atomic number=1), Atom(name=, atomic number=1), Atom(name=, atomic number=1), Atom(name=, atomic number=1), Atom(name=, atomic number=1), Atom(name=, atomic number=1), Atom(name=, atomic number=1), Atom(name=, atomic number=1)]
```

OpenFF automatically added hydrogens, but the PDB file doesn't include hydrogens.  That's why they don't match.

**Comment by andrew0901** [comment]
Unfortunately that doesn't fix my issue. I have inspected the unmatched residues in the topology by:
`l_unmatched = forcefield.getUnmatchedResidues(pdb.topology)`
And I printed out the number of atoms and bonds.

The unmatched residues have exactly the same number of bonds and atoms as in my ligand molecule:

> Adding ligand /wynton/home/degradolab/fhy/scripts/openMM/08_07_FAP_original/6yru_D_FAD.sdf to the forcefield.
> Molecule with name 'FAD' and SMILES '[H][O][C@@]1([H])[C@@]([H])([O][H])[C@]([H])([N]2[C]([H])=[N][c]3[c]([N]([H])[H])[n][c]([H])[n][c]32)[O][C@]1([H])[C]([H])([H])[O][P@@](=[O])([O][H])[O][P@](=[O])([O][H])[O][C]([H])([H])[C@@]([H])([O][H])[C@@]([H])([O][H])[C@@]([H])([O][H])[C]([H])([H])[N]1[C]2=[N][C](=[O])[N]([H])[C](=[O])[C]2=[N][c]2[c]([H])[c]([C]([H])([H])[H])[c]([C]([H])([H])[H])[c]([H])[c]21'
> num_atoms:  86
> num_bonds:  91
> Adding ligand /wynton/home/degradolab/fhy/scripts/openMM/08_07_FAP_original/6yru_B_STE.sdf to the forcefield.
> Molecule with name 'STE' and SMILES '[H][O][C](=[O])[C]([H])([H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[H]'
> num_atoms:  56
> num_bonds:  55
> Adding ligand /wynton/home/degradolab/fhy/scripts/openMM/08_07_FAP_original/6yru_C_STE.sdf to the forcefield.
> Molecule with name 'STE' and SMILES '[H][O][C](=[O])[C]([H])([H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[H]'
> num_atoms:  56
> num_bonds:  55
> <Residue 573 (STE) of chain 1>
> num_atoms: 56
> num_bonds: 55
> <Residue 574 (STE) of chain 1>
> num_atoms: 56
> num_bonds: 55
> <Residue 575 (FAD) of chain 1>
> num_atoms: 86
> num_bonds: 91


Could it be that the atom names also matter? Because reading from .sdf doesn't give any atom name, while the small molecules in the pdb file do have atom names assigned (like C1, H12, etc.)

**Comment by peastman** [comment]
In the PDB file you posted, each STE residue has 18 carbons, 2 oxygens, and 0 hydrogens.  Now inspect `ligand.atoms`.  It contains lots of hydrogens.  Your SDF file doesn't list any hydrogens, so they appear to be the same, but OpenFF adds them when you load the file.

That's based on the files you posted.  If you have an alternate version that includes hydrogens in the PDB file, please post it.

**Comment by andrew0901** [comment]
Thanks for the prompt response! I do have new input files. I also included the code I use to test the unmatched residues:

[input_and_test_script.zip](https://github.com/user-attachments/files/16566899/input_and_test_script.zip)


```
from openmm.app import *
from openmm import *
from openmm.unit import *
from openff.toolkit import Molecule
from openmmforcefields.generators import GAFFTemplateGenerator
from openmmforcefields.generators import SMIRNOFFTemplateGenerator
from sys import stdout
from pathlib import Path

#forcefield = ForceField('amber/protein.ff14SB.xml', 'amber/tip3p_standard.xml', 'amber/tip3p_HFE_multivalent.xml')
#forcefield = ForceField('amber/protein.ff14SB.xml', 'amber/tip3p_standard.xml', 'amber/tip3p_HFE_multivalent.xml')
forcefield = ForceField('amber14-all.xml', 'amber14/tip3pfb.xml','amber/tip3p_HFE_multivalent.xml')
print("created forcefield")

#add the ligands
input_ligand_files = ["/wynton/home/degradolab/fhy/scripts/openMM/08_07_FAP_original/6yru_D_FAD.sdf",
                      "/wynton/home/degradolab/fhy/scripts/openMM/08_07_FAP_original/6yru_B_STE.sdf",
                      "/wynton/home/degradolab/fhy/scripts/openMM/08_07_FAP_original/6yru_C_STE.sdf",
                      ]

for ligand_file in input_ligand_files:
    ligand = Molecule.from_file(ligand_file)
    print(ligand)
    #print(ligand.bonds)
    print("num_atoms: ", len(ligand.atoms))
    print("num_bonds: ", len(ligand.bonds))
    gaff = GAFFTemplateGenerator(molecules=ligand)
    forcefield.registerTemplateGenerator(gaff.generator)
    #smirnoff = SMIRNOFFTemplateGenerator(molecules=ligand)
    #forcefield.registerTemplateGenerator(smirnoff.generator)

pdb = PDBFile("/wynton/home/degradolab/fhy/scripts/openMM/08_07_FAP_original/resave_nowb.pdb")
#system = forcefield.createSystem(pdb.topology)
l_unmatched = forcefield.getUnmatchedResidues(pdb.topology)
for r in l_unmatched:
    print(r)
    #print(list(r.bonds()))
    print("num_atoms:", len(list(r.atoms())))
    print("num_bonds:", len(list(r.bonds())))
#system = forcefield.createSystem(pdb.topology, nonbondedMethod=PME,nonbondedCutoff=1*nanometer, constraints=HBonds)
```

**Comment by peastman** [comment]
Your newest version works fine for me.  I uncommented the first call to `createSystem()`, and it successfully created a system.

It did take a long time, almost eight minutes.  That time is spent in AmberTools computing the partial charges.  I don't know why it's so slow.  It uses AM1-BCC, which is supposed to be a really fast method.

I did this with OpenMM 8.1.2, openmmforcefields 0.14.1, and OpenFF-Toolkit 0.15.2.

**Comment by mattwthompson** [comment]
That's a little slow but not shocking; one of those ligands has 53 heavy atoms, including two phosphates, and AM1 is allegedly $O(N^3)$ scaling with number of heavy atoms

**Comment by peastman** [comment]
GFN2-xTB, which is a more accurate method, can do it in a fraction of a second.  You could even solve it with a decent quality DFT functional in less time than that.

**Comment by andrew0901** [comment]
@peastman Thanks for the instructions. I have the same openMM version but 0.12.1 for OpenFF-Toolkit and 0.12.0 for openmmforcefields. I will try to update the versions and see if this works.

**Comment by mikemhenry** [comment]
> 0.12.1 for OpenFF-Toolkit

That is a very old version of the `openff-toolkit`, did you install that version intentionally (like following some guide that reference that version or reproducing an old environment) or was that the version pulled in with a `conda install -c conda-forge openff-toolkit`

**Comment by mattwthompson** [comment]
If the latter, I recommend creating a new environment - the chances you'll get stuck in dependency hell while updating an older environment is high and the chances that a fresh install would work are also high. (The package versions Peter listed earlier, or newer, are what you want.)

**Comment by andrew0901** [comment]
Thanks for the suggestions! I think it was a python version compatibility issue so conda installed an older version for me. When I created a new environment with python 3.10 it automatically gives me newer versions.

With this new environment I am able to successfully create the system without throwing an error. But it does still throws a message:

> Did not recognize residue STE; did you forget to call .add_molecules() to add it?

And when I call `forcefield.getUnmatchedResidues(pdb.topology)`,
the residues corresponding to small molecules are still there. I'm wondering what effect this will have over the simulation?

**Comment by peastman** [comment]
I think that's because you create a separate template generator for each molecule, rather than a single generator for all of them.  The first generator parameterizes FAD, and prints a warning that it couldn't parameterize STE.  Then the second generator gets called and parameterizes STE.  Instead you could create a single generator and pass a list of molecules for the `molecules` argument.

**Comment by andrew0901** [comment]
This is a very delayed the reply but I have solved the issue with the help you provided. Thanks! I'm closing the issue.
