### ISSUE TITLE
The updateParametersInContext does not work.

### ISSUE THREAD

**Issue by zhenyuwei99** [openmm/openmm#4616]
Hi,

I am trying to implement a time-varying external force, and I need to vary a global parameter step by step. However, when I run code like:
```
force.setGlobalParameterDefaultValue(0, E)
force.updateParametersInContext(simulation.context)
````
And check the force acting on the particle, there is no change at all. When I use code:
```
simulation.context.setParameter("E", E)
```
The force, indeed, varies with time. So I am curious why the first kind of codes can not work. Does the global parameter is unaffected with the method `updateParametersInContext`?

**Comment by peastman** [comment]
`setGlobalParameterDefaultValue()` does exactly what the name says: it sets the default value for newly created contexts.  It's just the default.  Once the context is created, you can change the value to something else.  You do that with `setParameter()`.

See https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#system for more information about how this works.

**Comment by zhenyuwei99** [comment]
Great! Thank you for the quick reply! I think everything is done.
