### ISSUE TITLE
Fixing Box Dimensions and Atom Structure in Last Frame PDB File

### ISSUE THREAD

**Issue by NAS-SAA** [openmm/openmm#4620]
Hi everyone, I tried to generate a last frame in PDB format along with the XTC file using the code below. However, the lastframe.pdb file doesn't have the correct box dimensions—it has the box dimensions from the input.pdb file instead. Also, the structure of atoms in lastframe.pdb is very different from the last frame of the XTC file. Can you help me figure out how to fix the code?

'platform = Platform.getPlatformByName('Reference')
pdb = PDBFile('fixed1.pdb')  
forcefield = ForceField('FF1.xml') 
system = forcefield.createSystem(pdb.topology, nonbondedMethod=PME, nonbondedCutoff=1.5*nanometer)
integrator = LangevinMiddleIntegrator(800*kelvin, 1/picosecond, 0.001*picoseconds)
simulation = Simulation(pdb.topology, system, integrator)

simulation.context.setPositions(pdb.positions)
context = simulation.context

print("Minimizing energy")
simulation.minimizeEnergy()
simulation.reporters.append(XTCReporter('Traj.xtc', 1000))
simulation.reporters.append(StateDataReporter('state.txt', 500, time=True, potentialEnergy=True, volume=True, density=True))
system.addForce(MonteCarloAnisotropicBarostat((1, 1, 1)*bar, 800*kelvin,
        False, False, True))
simulation.context.reinitialize(preserveState=True)
print("Running NPT")
simulation.step(1000000)
PDBFile.writeFile(simulation.topology, context.getState(getPositions=True).getPositions(), open('lastframe.pdb', 'w'), keepIds=True)'

**Comment by peastman** [comment]
`writeFile()` gets the periodic box vectors from the Topology you pass in.  It doesn't know what box vectors are stored in the Context, because you don't pass them to it.  You can copy the current box vectors to the Topology like this:

```python
state = simulation.context.getState()
simulation.topology.setPeriodicBoxVectors(state.getPeriodicBoxVectors())
```

**Comment by NAS-SAA** [comment]
I got it, thank you so much!
