### ISSUE TITLE
Extracting Bead Velocity without Looping

### ISSUE THREAD

**Issue by wlai0611** [openmm/openmm#4624]
I hope you are well.  I was interested in extracting the velocity of the thermostat bead particle of [NoseHooverChainVelocityVerletIntegrator](https://openmmtools.readthedocs.io/en/stable/api/generated/openmmtools.integrators.NoseHooverChainVelocityVerletIntegrator.html)

I am currently using the loop below to extract the bead velocities:
```
bead_velocities = np.zeros(timesteps)
for timestep in range(timesteps):
  bead_velocities[timestep] = simulation.integrator.getGlobalVariableByName('vxi0')
```

But I was wondering if there was a faster way instead of using the loop and just have bead velocities written to a static file similar to when attaching a PDBReporter to a simulation and calling simulation.step()?
Thank you for any guidance you can provide!

**Comment by peastman** [comment]
I'm not familiar with that integrator.  It's part of openmmtools which, contrary to what the name suggests, is not part of OpenMM.  If you have questions about it, you should open an issue at https://github.com/choderalab/openmmtools.
