### ISSUE TITLE
How to change Simulation parameters after equilibration?

### ISSUE THREAD

**Issue by pipitoludovico** [openmm/openmm#4625]
OpenMM = 8.0.0

Hi!
After finishing the equilibration I save both a .chk and the .xml state.
From my understanding, the .chk is used to eventually restart a simulation from the last step, while the .xml is useful to reproduce all the system's information for further use.

```
final_state = simulation_eq.context.getState(getPositions=True, getVelocities=True, enforcePeriodicBox=True,
                                                 getParameters=True)
with open('equilibration_checkpnt.xml', 'w') as output:
    output.write(XmlSerializer.serialize(final_state))
```

Is it possible to subsequentially load the xml file and change the integrator for that?
Is it also possible to add or remove a MonteCarlo Barostat for that Simulation?

```
def RunProduction(GPU, replica, system, top, parameters):
    productionSteps = 1000000
    integrator = mm.LangevinMiddleIntegrator(310 * kelvin, 1 / picosecond, 0.004 * picoseconds)
    properties = {'DeviceIndex': f'{str(GPU)}', 'Precision': 'mixed'}
    platform = mm.Platform.getPlatformByName('CUDA')
    simulation_production = Simulation(top.topology, system, integrator, platform, properties)
    simulation_production.loadState('equilibration_state.xml')
```

Thank you!

**Comment by peastman** [comment]
You won't be able to use a checkpoint, but a saved state ought to work for that.  By the way, an easier way of saving a state is to call [`simulation.saveState()`](http://docs.openmm.org/latest/api-python/generated/openmm.app.simulation.Simulation.html#openmm.app.simulation.Simulation.saveState).

**Comment by pipitoludovico** [comment]
For some reasons I can run the production from the checkpoint:

```
def RunProduction(GPU, replica, system, top, parameters):
    append = False
    productionSteps = 25000000
    integrator, platform, properties = GetMDsettings()
    integrator = mm.LangevinMiddleIntegrator(310 * kelvin, 1 / picosecond, 0.004 * picoseconds)
    properties = {'DeviceIndex': f'{str(GPU)}', 'Precision': 'mixed'}
    simulation_production = Simulation(top.topology, system, integrator, platform, properties)
    simulation_production.loadCheckpoint('equilibration_checkpnt.chk')
    simulation_production.context.setStepCount(0)
    simulation_production.reporters.append(CheckpointReporter(f'run_{replica}/{replica}_checkpnt.chk', parameters['saveFreq']))
    simulation_production.reporters.append(DCDReporter(f"run_{replica}/Traj_{replica}.dcd", parameters['saveFreq'], append=append, enforcePeriodicBox=True))
    simulation_production.reporters.append(StateDataReporter(f'run_{replica}/Traj_{replica}.std', 1000, step=True, totalSteps=productionSteps, remainingTime=True, potentialEnergy=True, temperature=True, speed=True))

    simulation_production.step(productionSteps)
```
The integrator was changed successfully and no NaN particle error occurred. Is there a way to add or remove the barostat here?

Thanks again!

**Comment by peastman** [comment]
You can just add it:

```python
system.addForce(MonteCarloBarostat(...))
```

Or if there's already a barostat that you want to remove, call `removeForce()` on the System.  Do that immediately before creating the Simulation.

Another option is to call `setFrequency(0)` on the barostat.  That disables it so the box volume remains fixed.

**Comment by pipitoludovico** [comment]
I tried to call `removeForce()` but I don't know how to specifically remove the barostat. 
I know I should reinitialize after that.

Alternatively, how do I call setFrequency() on the barostat?
Thanks!

**Comment by peastman** [comment]
```python
for i, f in enumerate(system.getForces()):
    if isinstance(f, MonteCarloBarostat):
        system.removeForce(i)
```

or alternatively

```python
for f in system.getForces()):
    if isinstance(f, MonteCarloBarostat):
        f.setFrequency(0)
```

**Comment by pipitoludovico** [comment]
Thank you for the help!
