### ISSUE TITLE
Non-reciprocal force between two particles

### ISSUE THREAD

**Issue by gohdavid** [openmm/openmm#4626]
Hi,

I'm trying to simulate some non-equilibrium Langevin dynamics with a force between two particles, where A is attracted to B but B is not attracted to A. Is there any way for me to define something similar to a CustomBondedForce with this behaviour?

**Comment by peastman** [comment]
All the custom forces implement conservative forces.  You specify an expression for the energy, and it computes the force as the derivative.  That means they automatically satisfy Newton's 3rd law.

If you want something that doesn't, that will take a different approach.  There may still be a way to do it, for example with a custom integrator that edits the forces.  What is the exact form of the force you want?

**Comment by gohdavid** [comment]
We ended up using a simpler simulation for our project, but I'll keep that advice on the custom integrator in mind for any future work. Thanks!
