### ISSUE TITLE
PDBFile changes atom names when writing PDB files (CH3 -> C).

### ISSUE THREAD

**Issue by leeping** [openmm/openmm#463]
When I set up a system with OpenMM and write a PDB file as the output, the atom names are sometimes different.  In the case of NME, the methyl carbon is called "C", but I think other programs prefer "CH3" (the name of the methyl carbon for "ACE").  Is this worth changing in our force field XML files?

**Comment by peastman** [comment]
Closing this old issue.  We don't plan to implement it.
