### ISSUE TITLE
Deepcopying `AMDIntegrator` swaps values of global parameters

### ISSUE THREAD

**Issue by nielskm** [openmm/openmm#4637]
Making a deepcopy of an `AMDIntegrator` swaps the values of the global parameters (alpha and E).
```
from openmm import AMDIntegrator
amd = AMDIntegrator(0.001, 0.0, 1.0)
amd.getAlpha()
amd.getE()
```
prints 0.0, 1.0.
```
from copy import deepcopy
amd2 = deepcopy(amd)
amd2.getAlpha()
amd2.getE()
```
prints 1.0, 0.0.

I have tried reproducing the behavior with another `CustomIntegrator`, but with no luck. Could the issue be related to the names of the global parameters?

**Comment by peastman** [comment]
Thanks!  It looks like the order of the two global parameters gets swapped.  It's happening because XmlSerializer records the global parameters as attributes of a single tag, which doesn't preserve order.

```xml
<GlobalVariables E="1" alpha="0"/>
```

That should be fixed.
