### ISSUE TITLE
Large performance difference between Amber and GROMACS prepped systems

### ISSUE THREAD

**Issue by Justin-J-Miller** [openmm/openmm#4639]
Python=3.10
OpenMM = 8.1.2

I think I've traced down a source of the large variation in performance I noted here: https://github.com/openmm/openmm/issues/4609#issuecomment-2263914176. If I prepare a system in GROMACS (or OpenMM) I see high power draw on my GPU and simulation performance (ns/day) around where I expect. Conversely, if I prepare the system in AmberTools I see much lower power draw and a significant (3x) decrease in simulation time. Simulations are set up with the same integrator and nominally the same force field/water model. Any guess as to what I might be doing wrong? I ask because for this example I have copies of the force field for each engine, though I'm moving towards simulations where I only have the force field as amber parameters.

System is ~2600 protein atoms with ~144K water. System built with Amber14sb and tip3p water. There is a slight variation in box size/water count between the GROMACS prep and Amber prep which leads to the Amber system having 1% more water. On my A5000 I see ~70 ns/day from the Amber prep as opposed to ~200 ns/day from the GROMACS prep.

Systems were loaded into OpenMM from amber/gromacs according to the examples in the documentation:

Amber:
```
hmass=2
inpcrd = AmberInpcrdFile('center-exact-waters.inpcrd')
prmtop = AmberPrmtopFile('center-exact-waters.prmtop', periodicBoxVectors=inpcrd.boxVectors)
system = prmtop.createSystem(nonbondedMethod=PME, nonbondedCutoff=1*nanometer,
        constraints=HBonds, hydrogenMass=hmass*amu)
simulation = Simulation(prmtop.topology, system, integrator)
simulation.context.setPositions(inpcrd.positions)
```

GROMACS:
```
hmass=2
gro=GromacsGroFile('./start.gro')
top=GromacsTopFile('./topol.top', periodicBoxVectors=gro.getPeriodicBoxVectors(),
        includeDir='./')

system=top.createSystem(nonbondedMethod= PME, nonbondedCutoff= 1 * nanometers, 
                        constraints=HBonds, hydrogenMass=hmass*amu)
simulation = simulation.Simulation(top.topology, system, integrator)
simulation.context.setPositions(gro.positions)
```

System prep files and the performance test I ran are here: https://github.com/Justin-J-Miller/performance-variation-system-prep/tree/main

**Comment by peastman** [comment]
Can you serialize a system and state for each one to XML files, and post them?  See https://openmm.github.io/openmm-cookbook/latest/notebooks/cookbook/Saving%20Systems%20to%20XML%20Files.html.  It should be possible to tell what's different between them.

**Comment by swails** [comment]
@peastman, they're available in the repo he linked at the bottom of his post. The systems are different.

This is what I gleaned:
<img width="1194" alt="image" src="https://github.com/user-attachments/assets/962fbc32-0338-472f-8686-cc456f3685ed">

It's not clear to me why there would be a 3x performance difference. But I haven't dug any deeper.

**Comment by Justin-J-Miller** [comment]
Yes - I've serialized them and dropped them into the GitHub repo in each subdirectories for Amber and GROMACS. The systems are slightly different in box size/water count but both are truncated octahedrons with the same water model and force field. I'm happy to play around with the box size and water count a bit more to get the same atom counts if that's better for testing, but similar to @swails was struck by the large performance difference given the fairly similar systems.

**Comment by peastman** [comment]
I'm not seeing the difference.  I wrote this script to test it.

```python
from openmm import *
import sys
import time

model = sys.argv[1]
system = XmlSerializer.deserialize(open(f'system-{model}.xml').read())
state = XmlSerializer.deserialize(open(f'state-{model}.xml').read())
integrator = XmlSerializer.deserialize(open('integrator.xml').read())
platform = Platform.getPlatform('CUDA')
context = Context(system, integrator, platform)
context.setState(state)
integrator.step(10)
context.getState(getEnergy=True)
t1 = time.time()
integrator.step(10000)
context.getState(getEnergy=True)
t2 = time.time()
print(t2-t1)
```

And here's the result.

```
$ python test.py gromacs
8.12260127067566
$ python test.py amber
8.244266033172607

```

That's on a RTX 4080.

**Comment by peastman** [comment]
The above times were for the current development code.  I just tried with 8.1.2 and I do see the difference:

```
$ python test.py gromacs
8.91559886932373
$ python test.py amber
31.88182234764099
```

It looks like the problem has already been fixed.  I suspect it may be related to #4343.  Can you test with the latest development code?

**Comment by Justin-J-Miller** [comment]
Ah great! I just ran with the latest dev code and also see the difference disappearing. 

Thanks - I assume this is also slotted for 8.2?

**Comment by Justin-J-Miller** [comment]
Woops, just realized this is the same PR as last time. Thanks again, closing now.

**Comment by peastman** [comment]
> Thanks - I assume this is also slotted for 8.2?

Correct.
