### ISSUE TITLE
How to set amount of padding added to the cutoff when building the neighbor list

### ISSUE THREAD

**Issue by asoyemi1** [openmm/openmm#4642]
I am running some MLP-driven MD in OpenMM using Nequip. I saw in another issue that the padding on the cutoff for the neighbor list is currently set to 0.08nm but I was wondering how I can change that value and check how much performance I can gain.

Thanks!

**Comment by peastman** [comment]
That refers to the neighbor list OpenMM uses internally for its own nonbonded interactions.  It isn't exposed externally.  If you're using a NequIP model, it's up to the model to create its own neighbor list in whatever way is appropriate for it.
