### ISSUE TITLE
Interaction energy with energy minimization

### ISSUE THREAD

**Issue by beta-sheet** [openmm/openmm#4643]
I'm trying to run energy minimization of a protein-ligand complex (topology defined by `top`, protein atom indices defined by `protein)` and extract the interaction energy afterwards, based on the snippet in the cookbook https://openmm.github.io/openmm-cookbook/latest/notebooks/cookbook/Computing%20Interaction%20Energies.html (there are no CustomNonbondedForces in my system):

```
for force in system.getForces():
    if isinstance(force, NonbondedForce):
        force.setForceGroup(0)
        force.addGlobalParameter("protein_scale", 1)
        force.addGlobalParameter("ligand_scale", 1)
        for i in range(force.getNumParticles()):
            charge, sigma, epsilon = force.getParticleParameters(i)
            # Set the parameters to be 0 when the corresponding parameter is 0,
            # and to have their normal values when it is 1.
            param = "protein_scale" if i in protein else "ligand_scale"
            force.setParticleParameters(i, 0, 0, 0)
            force.addParticleParameterOffset(param, i, charge, sigma, epsilon)
        for i in range(force.getNumExceptions()):
            p1, p2, chargeProd, sigma, epsilon = force.getExceptionParameters(i)
            force.setExceptionParameters(i, p1, p2, 0, 0, 0)
    else:
        force.setForceGroup(1)
```

However when I run the minimization with both scales set to 1,

```
integrator = LangevinMiddleIntegrator(300*kelvin, 1/picosecond, 0.004*picoseconds)
simulation = app.Simulation(top.to_openmm(), system, integrator)
simulation.context.setPositions(top.get_positions().to_openmm()) 

simulation.context.setParameter("protein_scale", 1)
simulation.context.setParameter("ligand_scale", 1)

simulation.minimizeEnergy()
simulation.context.getState(getPositions=True, getEnergy=True).getPotentialEnergy()
```

the total potential energy is very different (~factor 3) from the result without force modification. Is there a way to fix the force modification, or does minimization not work with particle parameter offsets?

**Comment by beta-sheet** [comment]
Thanks a lot for pointing out the exceptions, I solved it now using exception parameter offsets:

```
for force in system.getForces():
    if isinstance(force, NonbondedForce):
        force.setForceGroup(0)
        force.addGlobalParameter("protein_scale", 1)
        force.addGlobalParameter("ligand_scale", 1)
        for i in range(force.getNumParticles()):
            charge, sigma, epsilon = force.getParticleParameters(i)
            # Set the parameters to be 0 when the corresponding parameter is 0,
            # and to have their normal values when it is 1.
            param = "protein_scale" if i in protein else "ligand_scale"
            force.setParticleParameters(i, 0, 0, 0)
            force.addParticleParameterOffset(param, i, charge, sigma, epsilon)
        for i in range(force.getNumExceptions()):
            p1, p2, chargeProd, sigma, epsilon = force.getExceptionParameters(i)
            if (((p1 in protein) and (p2 in ligand)) or ((p1 in ligand) and (p2 in protein))):
                raise Exception("Something weird is going on")
            param = "protein_scale" if p1 in protein else "ligand_scale"
            force.setExceptionParameters(i, p1, p2, 0, 0, 0)
            force.addExceptionParameterOffset(param, i, chargeProd, sigma, epsilon)
    elif isinstance(force, CustomNonbondedForce):
        force.setForceGroup(1)
        force.addInteractionGroup(protein, ligand)
    else:
        force.setForceGroup(2)
```

In my case I am energy minimizing 100s of conformers with the same target, and am trying to avoid having two simulation objects and moving positions back and forth, unless there is no other way.

On the side note, is this also necessary with NoCutoff / CutoffNonPeriodic / CutoffPeriodic, where energies should be separable?

**Comment by peastman** [comment]
> On the side note, is this also necessary with NoCutoff / CutoffNonPeriodic / CutoffPeriodic, where energies should be separable?

I'm not sure what you mean?  Regardless of how you handle long range interactions, you need to separate out the intermolecular from intramolecular parts.

**Comment by beta-sheet** [comment]
I was just wondering if there is a way to get the energy parts in a single energy calculation such as for the CustomNonbondedForce in the cookbook, in case there is no reciprocal space component of the energy. But I understand that there is no way to add interaction groups for NonbondedForce.

**Comment by peastman** [comment]
If you don't need PME, it's possible to create a CustomNonbondedForce that exactly reproduces the functional form of NonbondedForce.  Then you could use interaction groups.  The equations are all at http://docs.openmm.org/latest/userguide/theory/02_standard_forces.html#nonbondedforce.  If you do that, you'll also need a CustomBondForce to reproduce the exceptions.  CustomNonbondedForce only knows how to completely exclude an interaction, not compute it with different parameters, so you need to exclude it from the CustomNonbondedForce and use a separate bonded force to compute it correctly.

**Comment by beta-sheet** [comment]
That makes sense, thanks a lot for the info and for your help, will look into that!

**Comment by peastman** [comment]
Creating a CustomNonbondedForce that exactly reproduces a NonbondedForce would make a good cookbook entry.  It does come up from time to time.
