### ISSUE TITLE
Want to run multiple OpenMM jobs on a single gpu 

### ISSUE THREAD

**Issue by The4thOne** [openmm/openmm#4658]
Hi,
I have an RTX 4070 Ti 12GB card on my system. While running my Openmm simulation, it uses only ~200MiB. 

![Screenshot from 2024-09-16 09-40-49](https://github.com/user-attachments/assets/08647fe7-a599-46d3-90d1-05ef2830c76b)

Can I run multiple simulations in parallel on the same to use the maximum of the card?
I have tried running three simulations in parallel (just by running them from different terminal windows), but it took 3 times more time to finish the same job.

**Comment by peastman** [comment]
How much of the GPU's compute power is used when running a single simulation?  You can check with `nvidia-smi`.  If it's close to 100%,then you aren't going to get a speedup by running multiple simulations at once.

There sometimes can be a benefit from running multiple simulations at once, but only for small systems where a single simulation can't keep the GPU busy.

**Comment by The4thOne** [comment]
![Screenshot from 2024-09-17 12-13-42](https://github.com/user-attachments/assets/5c8b39de-3919-4e02-b1eb-49b0143b34bc)


Although the GPU memory used is ~200 MiB, the GPU's compute power usage seems 100%. And my system is also big, so no chance. Anyway, thank you.
