### ISSUE TITLE
CONECT block missing with PDBFile.WriteModel

### ISSUE THREAD

**Issue by beta-sheet** [openmm/openmm#4660]
I am writing a trajectory to PDB using

```
with open("trajectory.pdb", "a+") as output:
    app.PDBFile.writeFile(
        simulation.topology,
        state.getPositions(),
        output,
    )
```

which works as expected. However, upon replacing `writeFile` with `writeModel` (and passing `model_index`), the CONECT block is no longer written. I need the MODEL...ENDMDL entries for MDAnalysis to parse it correctly, as well as the connectivity information for small molecules bound to a protein. I am using OpenMM 8.1.2.
What might be slightly non-standard is my topology being created with openff-toolkit and converted to OpenMM.

**Comment by peastman** [comment]
To write out a PDB file with with multiple frames, call `writeHeader()` once at the start, then `writeModel()` once for each frame, and finally `writeFooter()` at the end.  That's all that `writeFile()` does:

https://github.com/openmm/openmm/blob/fed44c579e9ac3136fe38056968a9c6dc1b6931e/wrappers/python/openmm/app/pdbfile.py#L294-L296

PDB is a really bad format for trajectories.  It's usually better to use a binary format like DCD or XTC, combined with a PDB file containing the starting structure to get the topology.

**Comment by beta-sheet** [comment]
Thank you very much, this was helpful!
