### ISSUE TITLE
Allow to request all parameters context.getState hast to offer from a reporters describeNextReport() function

### ISSUE THREAD

**Issue by schuhmc** [openmm/openmm#4663]
At the moment, custom reporters are not able to request parameter derivatives or integrator parameters for their next report.

https://github.com/openmm/openmm/blob/fed44c579e9ac3136fe38056968a9c6dc1b6931e/wrappers/python/openmm/app/simulation.py#L254-L272

Currently, to get parameter derivatives using a custom reporter, the state needs to be fetched separately.

I can make the changes and create a pull request if desired.

**Comment by peastman** [comment]
Yes, that would be a reasonable feature to add.

Continuing to add elements to the tuple seems to be getting a bit out of hand.  Possibly we want to adopt a new API for `describeNextReport()`.  Perhaps something like this:

```python
return {'steps':steps, 'periodic':False, 'include':['positions', 'forces']}
```

That will be more forward compatible.  Simulation would still need to handle reporters that return a tuple in the old format, but we wouldn't need to support any new features in that case.

**Comment by schuhmc** [comment]
I completely agree. The tuple is already quite unreadable as-is.

I will create a draft of a possible solution and we can move the discussion about the implementation to there.
