### ISSUE TITLE
Particle coordinate is NaN

### ISSUE THREAD

**Issue by pradipchm** [openmm/openmm#4665]
Hi,
I am getting a common error of "Particle coordinate is NaN". I did energymin, NVT and NPT for a crystal supercell. Then I was trying to do NPT production run with the last frame of NPT and exaclty similar code with more no number of steps.  But the run stops immediately with this error. If the change the gro file from last frame of NVT, it runs fine again. Am I missing any parameters to add? Also if you can share the any code where can go through some other simulation parameter which are important.
```
# Gromacs with GAFF Energymin
import time
from openmm.app import *
from openmm import *
from openmm.unit import *
from sys import stdout

gro = GromacsGroFile('ROY_N480_NPT.gro')
top = GromacsTopFile('ROY_N480_GAFF.top', periodicBoxVectors=gro.getPeriodicBoxVectors())


platform = openmm.Platform.getPlatformByName('CPU')
n_threads = {'Threads': '36'}

system = top.createSystem(nonbondedMethod=PME, nonbondedCutoff=1*nanometer,
        constraints=HBonds)
integrator = VerletIntegrator(0.002*picoseconds)
system.addForce(AndersenThermostat(300*kelvin, 1/picosecond))
system.addForce(MonteCarloBarostat(1*bar, 300*kelvin))
simulation = Simulation(top.topology, system, integrator, platform, n_threads)
simulation.context.setPositions(gro.positions)

simulation.reporters.append(PDBReporter('output_NPT_Produc_part001.pdb', 500))
simulation.reporters.append(StateDataReporter('data_NPT_Produc_part001.txt', 500, time=True,
        potentialEnergy=True, temperature=True, separator=' '))

start_time = time.time()
simulation.step(2500000)
end_time = time.time()
elapsed_time = end_time - start_time
print(f"Simulation completed in {elapsed_time:.2f} seconds.")
```

**Comment by peastman** [comment]
Did you look at https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#nan?  It discusses common causes of this error and ways to debug them.

**Comment by pradipchm** [comment]
Hi,
The same set of steps work for another molecule. I couldn't able to find the issue. What would you recommend me to check to fix the bugs?

**Comment by pradipchm** [comment]
Hello,
I solved the issue, I need to save the checkpoint file and read the velocity for the next run. Thanks

**Comment by pradipchm** [comment]
Hello,
I'm getting error while running with cuda.
```
Traceback (most recent call last):
  File "/storage/nas_scr/shared/groups/valsson/Pradip_Runs/AMOEBA_test/AMOEBA_openmm_setup/PABA_solvate_System_Setup_amoeba_openmm/openmm_Energymin_GPU.py", line 25, in <module>
    simulation = Simulation(pdb.topology, sys, integrator,
  File "/home/ps0579/.conda/envs/md-python/lib/python3.10/site-packages/openmm/app/simulation.py", line 106, in __init__
    self.context = mm.Context(self.system, self.integrator, platform, platformProperties)
  File "/home/ps0579/.conda/envs/md-python/lib/python3.10/site-packages/openmm/openmm.py", line 13480, in __init__
    _openmm.Context_swiginit(self, _openmm.new_Context(*args))
openmm.OpenMMException: Error loading CUDA module: CUDA_ERROR_UNSUPPORTED_PTX_VERSION (222)

```
I also checked 
```
python -m openmm.testInstallation

OpenMM Version: 8.1.2
Git Revision: 440a9c7ae5df23ea1ab93798a422b6d9fd3ada99

There are 3 Platforms available:

1 Reference - Successfully computed forces
2 CPU - Successfully computed forces
3 CUDA - Error computing forces with CUDA platform

CUDA platform error: Error initializing CUDA: CUDA_ERROR_NO_DEVICE (100) at /home/conda/feedstock_root/build_artifacts/openmm_1726255901612/work/platforms/cuda/src/CudaContext.cpp:91

Median difference in forces between platforms:

Reference vs. CPU: 6.29302e-06

All differences are within tolerance.

```
I am basically loading the module module load cuda11.8 while running the job. Do I have to reinstall opoenmm with cuda (without installing cuda by myself and giving the cuda path)?

**Comment by peastman** [comment]
This usually means your CUDA toolkit is newer than your driver.  If you're going to be using CUDA 11.8, tell it to install the CUDA 11.8 build of OpenMM as [described in the manual](http://docs.openmm.org/latest/userguide/application/01_getting_started.html#installing-openmm).

If that still doesn't fix it, please open a new issue instead of reusing an old issue to ask an unrelated question.
