### ISSUE TITLE
Question on Hilbert Space-Filling Curve implementation

### ISSUE THREAD

**Issue by DaveCerutti** [openmm/openmm#4666]
Do I guess correctly that OpenMM creates (conceptually creates) a single Hilbert-space curve of 2^N units in any given direction, then stretches that across the unit cell?  Could that be why I was seeing erratic scaling behavior with some simulations where the aspect ratios were not 1:1:1?  I have found what appear to be the primary mechanics [here](https://github.com/openmm/openmm/blob/edb74aec35ae8e671004ff4380b6840fb3656bf0/libraries/hilbert/include/hilbert.h).  It would seem simplest to define the HS curve as a cube with lengths of some power of two, then determine the positions with those bitwise operations that seem to be going on.

I am trying to determine the occupancy of various methods for constructing the pairwise tiles, and while I can implement my own HS curve in various ways I'm curious about what existing codes do.

**Comment by peastman** [comment]
You mean Hilbert curve, not Hilbert space?  Very different things. :)  The relevant code [is here](https://github.com/openmm/openmm/blob/edb74aec35ae8e671004ff4380b6840fb3656bf0/platforms/common/src/ComputeContext.cpp#L602-L635).  It sets the spatial resolution to 1/255 of the maximum box dimension.  That usually is much higher resolution than you need.  If your box is 255 Å across, it's still accurate to 1 Å.  For a really huge system that's even larger than that, it might start to affect performance.  How big is your system (box size, number of atoms)?

**Comment by DaveCerutti** [comment]
Yes, title corrected!  Running on not much sleep... hoping to get better rest tonight!  That's instructive, then.  What I am going to do (have already done) is put a HS curve generator into STORMM as a testing apparatus.  I can generate a curve, and I may elaborate the ways I do it, but with that means to co-localize atoms I will be upgrading one of my benchmarking programs to calculate the occupancy of tiles generated with such an HS curve for arbitrary numbers of "receiving" atoms (those atoms selected from contiguous positions along the curve).  I can already calculate the occupancy of pair interaction tiles with my current method based on a "jump with no parachute" tower-plate decomposition, and I will soon be able to calculate the number of interactions I might reasonably cull that down to without making the GPU kernel trip over itself just trying to set up the tiles.

They're very different approaches, and while I agree we don't benefit from "six of one, half dozen of the other, same result" I've outlined the unique benefits of the approach I've undertaken which hint at more than just a zero-sum game. 
 I'm trying to determine at what point, if any, the rate of successful interactions in either of the two methods will overlap.

In regard to your question, the boxes I was trying had aspect ratios of 2:1:1, 3:1:1, 4:1:1, even 5:1:1, then various other primes.  5:2:1 and 5:3:1 were also not great.  The baseline length of a side ("1") was about 5.1 nm, but the real key seems to be that the box was octahedral (so, box angles 109.47 degrees).  The "canonical" octahedron (aspect ratios 1:1:1) generally seems to run near OpenMM's asymptotic limit for system of similar size.  I never saw any erratic behavior for sysems in rectilinear boxes, even with the same aspect ratios.  From my email:
![DHFRMPS](https://github.com/user-attachments/assets/2de510c9-fe7d-43d9-ade2-da95779df6c8)

The circle-marked lines show each code's performance when running with multiple MPS processes, each simulating a cubic or octahedral DHFR benchmark system (23558 atoms, I rebuilt it in the octahedron for testing purposes).  The square-marked lines show in relief indicate each code's performance running a single simulation where the same DHFR benchmark is tiled as many times (hence, 2:1:1 aspect ratios, or 5:2:1, etc.).  The erratic behavior in those triclinic boxes extends well into the dozens of tiled systems (I sent another plot with that data in my email), although MPS doesn't scale above 16 simultaneous systems.

OpenMM really shines on this test!  Kudos!  I would say that it seems to be doing very well to interleave memory and computation, letting technology do its thing and make sure that every resource (RAM bus, SMs, global cache feeds) are being utilized at a high rate.  It's made me rethink how I'm trying to structure STORMM and some of the underlying algorithms.  I think I am on the right track, not wasting extra computation, but I wonder if there are places I could lean more on memory traffic if I could engineer multiple streams to run at the same time (maybe even groups of simulations in separate streams, with little to no need for resynchronization except at a very high level prior to a coordinate swap, for example).

**Comment by DaveCerutti** [comment]
Here is the data for a much larger set of tiled, single simulations (non-MPS):
![DHFRTiling](https://github.com/user-attachments/assets/125b69e2-c26e-46cb-abe4-8e53d541855c)

**Comment by DaveCerutti** [comment]
The OpenMM version in the plots above is the current master branch, and while there is that one dip at 4x tiling in the cubic case the octahedral case zigs and zags more between 200k and 2M atoms (it would, then, be tilings of 2 x 2 x 2, a high point, up to 6 x 5 x 3).  When I was running with an outdated version of OpenMM (my mistake, I'll just blame Gemini for giving me bad advice), I was seeing truly wild fluctuations--up to 75% perf hits between 2 x 2 x 2 and 5 x 2 x 1 octahedral DHFR tiles, for example, with nothing comparable in the cubic case.  Only the vestiges of that behavior remain, but what I started to consider the HS curve mechanics I thought that maybe that had something to do with the way OpenMM can be a bumpier ride.

**Comment by DaveCerutti** [comment]
Here's another data set for two protein crystal simulations.  The HIV capsid octahedral crystal (yes, there are a handful of those in the PDB, but they are RARE) is about 41% protein atoms while the scorpion toxin orthorhombic crystal is about 64% protein atoms.

![CrystalTiling](https://github.com/user-attachments/assets/fe84ae20-ae18-49d9-b9a5-b3cb1ee2494d)

Nota bene: NAMD was the canary in the coal mine here, but it convinced me that no code (at least, none of the present GPU codes) should really be running the system with the original ammonium ions.  I know that Amber and OpenMM don't have the means to SHAKE four bonds connected to the same center, and I doubt that NAMD has the capability either.  It (NAMD) was slowing considerably after a couple of thousand steps (not sure why) and then blowing sky-high and failing with "high-velocity particles!" I took out the ammonium ions (yes, they were mass-repartitioned), replaced them with sodium, and resumed runs with the 4 fs time step.  Things were fine after that.

**Comment by DaveCerutti** [comment]
@peastman Can you tell me the default neighbor list margin (cutoff + margin = distance criterion for selecting particles around those in the HS curve-contiguous group for tile construction)?

I have a little toy engine for determining neighbor list occupancy in various systems given different rules for constructing the HS curve, receiving group sizes, and what to do with the last handful of sending atoms (special tile or not).  It's rather enlightening.

**Comment by peastman** [comment]
That's correct.  The margin (if a margin is used) is 8% of the cutoff distance.  That's changed a bit over the years.  Any code change that affects the cost of either building the neighbor list or computing the interactions means I rerun benchmarks to find the best margin.

The neighbor list consists primarily of blocks of 32 consecutive atoms, and the individual atoms the block interacts with.  So some pairs will be included in the neighbor list even though they're farther apart than that, because some other atom in the block is within the cutoff distance.

**Comment by DaveCerutti** [comment]
Yes, that makes sense.  My engine (which includes your tweak of "if there is only one atom in the remainder of the halo" gives success rates of:

'''
0.9 nm cutoff (0.072 nm margin): 29.2% - 31.8% (octahedral versus cubic system)
1.0 nm cutoff (0.080 nm margin): 32.4% - 34.2% 
1.1 nm cutoff (0.088 nm margin): 34.9% - 37.3%
1.2 nm cutoff (0.096 nm margin): 37.1% - 39.4%
'''

So, your recollection on our call that about a third of the interactions are successful looks to be correct.  The success rates definitely improve with 16-atom receiving groups selected from the space-filling curve.

My success rates with the raw "tower-plate" decomposition are between 14% and 24%.  It's conceivable that I could up this to between 22% and 30%, probably at a reasonable cost in culling the pairs and / or further subdividing the tiles.  If I have to go with a space-filling curve method or any means of remembering explicit lists of "these atoms" and "those atoms," there are ways to graft that onto the system I've got, but I'm keen on maintaining the system as it stands for the cleanliness of not having all... that.

**Comment by peastman** [comment]
> The success rates definitely improve with 16-atom receiving groups selected from the space-filling curve.

Using smaller blocks decreases the number of wasted interactions, but it also increases the amount of memory access.  32x32 tiles load and save data for 64 atoms and compute 1024 interactions.  16x16 tiles load and save data for 32 atoms and compute 256 interactions.  The amount of memory access per interaction is doubled.  It's a tradeoff, and I've found 32x32 usually gives better performance.

**Comment by DaveCerutti** [comment]
Not to quibble but my engine is calculating for 16 from the Hilbert SFC and then by batches of 32 all around it.  One benefit of this (which is a riff on what pmemd.cuda does) is that the load and store for the 16 can be done at the front and the end of a series of additional tiles.  Asymptotic to 2x the memory transactions, which was the happy medium with Amber.

**Comment by DaveCerutti** [comment]
OK, after some additional deliberation, I'm closing this issue.  Thank you for your help here.  I think I have a direction that will bring my unique approach towards parity with the success rates seen in the Hilbert SFC approaches, at least for typical production cutoffs, and after that I'll lean on the dual neighbor lists to do longer cutoffs and / or LJ PME.  Off, off, and away...
