### ISSUE TITLE
Restraining different groups of atoms with different restraint weight constants

### ISSUE THREAD

**Issue by austinweigle** [openmm/openmm#4667]
I would like to set multiple positional restraints with openmm. There has been support for this type of application in AMBER under the Group Specification portion of the AMBER in files ([http://archive.ambermd.org/202110/0057.html](http://archive.ambermd.org/202110/0057.html)). 

Here is part of my openmm script that enumerates an array of forces with different strengths (named `strength` below). I later apply these weighted restraints to different groups I specify later in the script:
```
restraint_array = []

for strength in restraint_list:
        force = CustomExternalForce("k*periodicdistance(x, y, z, x0, y0, z0)^2")
        force.addGlobalParameter("k", strength*kilocalories_per_mole/angstroms**2)
        force.addPerParticleParameter("x0")
        force.addPerParticleParameter("y0")
        force.addPerParticleParameter("z0")
        restraint_array.append(force)
```
Everything works fine until the simulation is about to be run, where I get this error:
`openmm.OpenMMException: Two Forces define different default values for the parameter 'k'`

Any suggestions on a way around this, or a way to maybe throw this exception? I see that similar issues have been raised elsewhere (https://github.com/openmm/openmm/issues/3768 and https://github.com/OpenBioSim/biosimspace/issues/216). While in most cases it is advantageous for global parameters (`addGlobalParameters`) to be shared, is there any way to make the shared parameter `k` here local in scope? (https://github.com/openmm/openmm/issues/127)

Thanks,
Austin

**Comment by peastman** [comment]
Global parameters are, well, global.  They aren't specific to just one force object.  You can have two forces that both depend on the parameter "k", but it's still the same parameter.  You can't specify two different values for it at the same time.

One option is to have two different parameters for the two forces.  For example, one could depend on "k1" and the other on "k2".

Another option is to use a single CustomExternalForce and make "k" a per-particle parameter.

**Comment by austinweigle** [comment]
Thanks! I will try making "k" a per-particle parameter and see how it goes. I'll post back here tomorrow.

**Comment by austinweigle** [comment]
Unfortunately, having separately named global parameters raises the error:
`OpenMMException: Two Forces define different default values for the parameter 'AndersenCollisionFrequency'`.

Given how PerParticleParameters are set up, you cannot introduce a force of variable strength in this way.

I was able to achieve my goal in AMBER, but would be nice if it could be made possible in OpenMM someday (i.e., apply the same type of force to multiple groups but with different constants `k` per force instance). Thanks for answering my question so quickly. I tinkered with it for a few hours but sadly no-go.

**Comment by peastman** [comment]
I think you have a bug in your code.  Did you add two AndersenThermostats to your system?

> Given how PerParticleParameters are set up, you cannot introduce a force of variable strength in this way.

It's possible to modify per-particle parameters, just a bit more expensive.  You have to call [`updateParametersInContext()`](http://docs.openmm.org/latest/api-python/generated/openmm.openmm.CustomExternalForce.html#openmm.openmm.CustomExternalForce.updateParametersInContext) after changing them.  Also, if you want different restraints to have different strengths, but to turn them all on or off together, you can make your force proportional to both a per-particle parameter (setting the strength of the restraint for each particle) and a global parameter (varying between 0 and 1 to turn them on or off).

**Comment by peastman** [comment]
Did you manage to figure this out?  If so, is it ok to close it?

**Comment by austinweigle** [comment]
Thanks for checking in. I was able to achieve what I want to do here with Amber using the group specification.

I'll try again in the future using openmm, but it'll be a lower priority task for me now. Thanks again for all your help and suggestions, sorry about not responding. My resources were limited while I was completing the Amber runs so I was unable to try both at once.

You can close this ticket.

**Comment by peastman** [comment]
Ok, thanks.
