### ISSUE TITLE
getForces returns forces not consistent with the simulation.

### ISSUE THREAD

**Issue by axsk** [openmm/openmm#4670]
I set up a toy system primarily consisting of water, with alanine-dipeptide placed in the corner. 

During a custom energy minimization (essentially gradient descent using the forces from `getForces()`), I observed that water molecules were unexpectedly split apart—the hydrogen atoms were being pulled away from the oxygen.

### Key Observations:

-   The simulation itself runs without issues and maintains the integrity of the water molecules.

 -  To investigate further, I wrote a small visualization that displays the forces retrieved from `context.getState(getForces=True).getForces()`. The visualization shows a state obtained from simulation with the forces returned from OpenMM. One can see that the forces (highlighted in red) are indded consistently pulling the water molecules (in blue) apart.

![image](https://github.com/user-attachments/assets/6e0fd8dc-ffb8-4f60-a285-04f129c5b74c)

 ### Cross-Verification:

I compared the forces obtained from `getForces()` with finite differences of the potential energy. The results were consistent.

### Question:

I'm puzzled by how the water molecules are still being pulled apart, given that the forces seem correct. Is OpenMM applying any additional constraints or corrections during force integration that might not be accounted for when querying the forces directly?

### System Setup:

```python
pdb = PDBFile(pdb) # alaninedipepdite without water
forcefield = ForceField("amber14-all.xml", "amber/tip3p_standard.xml")
modeller.addSolvent(forcefield, model="tip3p",
    padding=20 * angstroms,
    positiveIon="Na+", negativeIon="Cl-",
    ionicStrength=0 * molar, neutralize=True,
    )
system = forcefield.createSystem(modeller.topology,
    nonbondedMethod=CutoffPeriodic,
    nonbondedCutoff=1*nanometer,
    removeCMMotion=False, # this made no difference
    **forcefield_kwargs)

integrator = LangevinMiddleIntegrator(310*kelvin, 1/picosecond, 0.002*picoseconds)
simulation = Simulation(modeller.topology, system, integrator, platform, platformargs)
```

**Comment by peastman** [comment]
Can you provide a complete test case that shows what you're doing?  It's impossible to say what's happening from just the code you showed.  Include the complete script and any input files needed to reproduce it.

**Comment by axsk** [comment]
Here I create the system, fill it with water and minimize.
I then extract the positions and forces of the last (water) molecules and scatter resp. arrow plot them.
The plot shows above behavior, i.e. the forces always pointing outwards, which should not be the case for any generic state (obtained via energy minimization or simulation).

```python
from openmm.app import *
from openmm import *
from openmm.unit import *

pdbfile = "data/alanine-dipeptide-nowater av.pdb"

pdb = PDBFile(pdbfile) # alaninedipepdite without water
forcefield = ForceField("amber14-all.xml", "amber14/tip3pfb.xml")

modeller = Modeller(pdb.topology, pdb.positions)
modeller.addSolvent(forcefield, model="tip3p",
    padding=20 * angstroms,
    positiveIon="Na+", negativeIon="Cl-",
    ionicStrength=0 * molar, neutralize=True,
    )
system = forcefield.createSystem(modeller.topology,
    nonbondedMethod=CutoffPeriodic,
    nonbondedCutoff=1*nanometer,
    removeCMMotion=False, # this made no difference
 )

integrator = LangevinMiddleIntegrator(310*kelvin, 1/picosecond, 0.002*picoseconds)
simulation = Simulation(modeller.topology, system, integrator)

simulation.context.setPositions(modeller.positions)

simulation.minimizeEnergy()
# simulation.step(1000)   # makes no difference in the resulting force orientation

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

nparticles = 12

st = simulation.context.getState(getForces=True, getPositions=True, enforcePeriodicBox=True)
last_positions = st.getPositions(asNumpy=True)._value[-nparticles:]
last_forces = st.getForces(asNumpy=True)._value[-nparticles:]

plt.clf()
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

ax.scatter(last_positions[:, 0], last_positions[:, 1], last_positions[:, 2], color='blue', label='Positions')
for i in range(nparticles):
    ax.quiver(last_positions[i, 0], last_positions[i, 1], last_positions[i, 2],
              last_forces[i, 0], last_forces[i, 1], last_forces[i, 2],
              color='red', length=0.0001)

plt.show()
plt.savefig("out.png")

PDBFile.writeFile(simulation.topology, st.getPositions(asNumpy=True), "out.pdb")
```

output:
![image](https://github.com/user-attachments/assets/610f554b-5ebf-47ea-a918-fced4ffdb1e0)


The behavior was independent of the .pdb, but here I ran it with https://github.com/axsk/ISOKANN.jl/blob/main/data/alanine-dipeptide-nowater%20av.pdb

**Comment by swails** [comment]
Try adding constraints to bonds including hydrogen. TIP3P is a rigid water model and makes no sense to run without constraining the water geometry.

What you're observing would be consistent with missing bonds in the water models (which aren't needed if used with the requisite constraints).

In minimizations, I believe OpenMM replaces bond constraints with simple harmonic forces with a strong force constant (since it's easier to minimize an unconstrained potential).

**Comment by swails** [comment]
An edit to my last post, I should have checked first. [There is a bond and angle force added to that water model in OpenMM](https://github.com/openmm/openmm/blob/master/wrappers/python/openmm/app/data/amber14/tip3pfb.xml#L254-L259).

**Comment by axsk** [comment]
I am not sure if I understand you correctly. You suggest adding constraints, but this is essentially done implicitly at the link you have shown, right?

In any case the resulting "constraint" forces should be mirrored in the forces obtained by `getForces()`, right?

My issue is that the simulation is running correctly, the water is not "exploding". It's just the information from `getForces()` seems to be wrong.

**Comment by swails** [comment]
Ah, I was close.

The default behavior of `forceField(rigidWater)` is to use `True` if it's a rigid water model (as it is in this case) or `False` if it's a flexible water model. As a result, the system adds constraints and *not* forces for your water molecules, meaning the intra-molecular forces within each water molecule are ignored (since those degrees of freedom are ignored).

If you add `rigidWater=False` to your `createSystem` command, you get a much different image:

<img width="638" alt="image" src="https://github.com/user-attachments/assets/fec6242d-aac6-4831-9dff-ab138769d6c0">

You can print out `system.getNumConstraints()` to see how many constraints are added to your system. After setting `rigidWater=False`, the number of constraints drops from 6207 to 0.

**Comment by swails** [comment]
I believe you can effectively recover the behavior of the simulation with the [`Context.applyConstraints` method](http://docs.openmm.org/latest/api-python/generated/openmm.openmm.Context.html#openmm.openmm.Context.applyConstraints)

**Comment by peastman** [comment]
Constraints affect integration, not force calculation.  When it updates the positions and velocities, it doesn't allow any of the constrained distances to change, whatever forces might be acting on them.

Usually when you build a System, the ForceField adds either a constraint or an energy term to each bond, but not both.  Why waste time computing thousands of extra bonds during each step, when you know they can't have any effect on the trajectory?  But there are less common situations when you do want to know what the total force would have been, even though it doesn't affect the simulation.  You can add the argument `flexibleConstraints=True` to `createSystem()`.  That will make it add bonds to the constrained distances.

> I will observe that flexibleConstraints=True I would have expected to result in the same image as above, but it did not.

That's probably because the coordinates were different?  With `rigidWater=False` the atoms will move to positions that minimize the forces.  With `rigidWater=True, flexibleConstraints=True` they'll stay at the constrained distances, which won't always minimize the forces.

**Comment by axsk** [comment]
> [...], the system adds constraints and _not_ forces for your water molecules, meaning the intra-molecular forces within each water molecule are ignored (since those degrees of freedom are ignored).

Oh, now it makes sense. I even looked into the forcefield before but took the bond-lengths for usual harmonic forces.
Should have read [the docs](http://docs.openmm.org/latest/userguide/application/02_running_sims.html?highlight=rigidwater#constraints) more carefully.


> You can print out `system.getNumConstraints()` to see how many constraints are added to your system. After setting `rigidWater=False`, the number of constraints drops from 6207 to 0.

Thats good to know!

> I will observe that `flexibleConstraints=True` I would have expected to result in the same image as above, but it did not. @peastman may have insight there (since that's supposed to override the default behavior of constraints to add both forces and constraints, but it seems not to have for water molecules).

I guess flexibleConstraints is what I want, since I ultimately need to implement my own potential energy minimization that is matching the systems dynamics, so I need the true forces for the system.

**Comment by axsk** [comment]
So `rigidWater` decides whether the distances are handled by fixed constraints (`True`) or forces (`False`) which then would be included in `getForces()` and also `getPotentialEnergy()`?

With `flexibleConstraints=True` the simulation itself is still constraint but the "virtual" force of the constraint is included in `getForces()` and also `getPotentialEnergy()`?

In that case the forces with `flexibleConstraints=True, rigidWater=True` should be the same as with `flexibleConstraints=False, rigidWater=False` at the same position (which however might differ due to different simulation). Is that right?

I suppose restraints are always included in the forces, as they essentially are just forces, right?

**Comment by peastman** [comment]
> In that case the forces with flexibleConstraints=True, rigidWater=True should be the same as with flexibleConstraints=False, rigidWater=False at the same position (which however might differ due to different simulation).

Correct.

> since I ultimately need to implement my own potential energy minimization that is matching the systems dynamics, so I need the true (as in explaining the simulation) forces and potentials for the system.

Keep in mind that TIP3P-FB (like most other water models) is designed to be rigid.  It was parameterized to give correct results that way.  If you specify either `rigidWater=False` or `flexibleConstraints=True`, it will add some plausible bond terms.  But those terms aren't part of the TIP3P-FB water model.  They don't lead to the same coordinates as the real water model, and likely would produce less realistic water behavior.

**Comment by axsk** [comment]
The use of `flexibleConstraints` has solved my issue. Feel free to close it. Thank you very much for the support!
