### ISSUE TITLE
Does OpenMM sum forces in float over the course of each tile?

### ISSUE THREAD

**Issue by DaveCerutti** [openmm/openmm#4673]
Preface: I got an email from a developer on another major MD code, asking me, "If you're converting all forces to fixed precision, why not just damn the torpedoes and full speed ahead with non-bonded pairs?  Contribute all excluded interactions and subtract them off in the bonded calculations.  That's what Anton does." My reponse to him was "no, no, for this and this reason." Upon reflection, I think it would be, "no, no, a thousand times no." The only way I could foresee pulling it off would be to clamp all interactions, then assess whether the clamp was hit when subtracting the excluded force _post-hoc_, and having some mechanism I'm not yet sure of to log when interactions get clamped and seem bad but not the "oh, get a room" kind of too close.  And even with that I'd only be satisfied if I were also converting all interactions to fixed-precision immediately, rather than accumulating them over the course of the tile and then converting the partial sum for global storage.

That last bit is what made me think, that tile-wide accumulation is deterministic and my pmemd.cuda refactor has been getting away with it for years, but I'm about to start doing it on many tiles that are 32-contributions deep, not just 16, and one of the original authors has been needling me like a voodoo doll ever since I put that in.  The gripe is that it can't conserve energy and is numerically unstable, which I've found to be untrue, but I looked in OpenMM for another point of reference.  I found my way to the [nonbonded kernel core](https://github.com/openmm/openmm/blob/0f67a646a93a7fa600ae238b6485c54cd3c553db/platforms/cuda/src/kernels/nonbonded.cu), where it definitely seems that forces are being passed around to collect contributions in `float32_t`  with the single- and mixed-precision modes (`force` is a `real3`, not a `mixed3`).  **Is this correct?**  If OpenMM has been getting away with 32 sequential contributions in `float32_t` like this for however long, then that's reassuring. (Aside, even to convert 'every interaction' is not a bulletproof way to hold down roundoff error, as many electrostatic and van-der Waals values are in opposition and diverge in magnitude as the forces get large.)

As I was perusing, I also noticed that exclusions may or may not be used, for example [here](https://github.com/openmm/openmm/blob/0f67a646a93a7fa600ae238b6485c54cd3c553db/platforms/cuda/src/kernels/nonbonded.cu#L195).
```
#ifdef USE_EXCLUSIONS
            excl = (excl >> tgx) | (excl << (TILE_SIZE - tgx));
#endif
```
Does this mean that OpenMM has a mode to run roughshod over the exclusions during the non-bonded calculation and deal with them later?  To me, the choice of handling exclusions during the non-bonded sum is actually about throughput--to do them in the valence interactions might be possible, but my experience has been that it's not necessarily any faster, even if the risks and gobbledegook of whatever clamping mechanism could be mitigated.

**Comment by peastman** [comment]
That's correct.  I've never found accumulation accuracy to be an issue for forces, unlike energies where it's a big concern.  The number of significant contributions to each force isn't that large, and unlike energies that have an arbitrary zero point, absolute magnitudes are meaningful.  If a contribution is tiny, it doesn't matter if we lose some accuracy in it because the error is still tiny in absolute terms.

You can ignore the `USE_EXCLUSIONS` tests.  I don't think there's ever actually a case where it isn't set.

**Comment by DaveCerutti** [comment]
I have to say, I am coming to appreciate your provisions for different features of the major kernels leading into the JIT compilation.  I've been building variants of each major kernel constitutively, but the combinatorial possibilities, especially with some of the data typing and precision options I've allowed for experimental purposes, times the various GPU architectures, gets to be a long compilation process.  I think I'll trim the compilation at some level, and include some unusual configuraitons of larger kernels as options in the `CMAKE` build to be trapped later if the specific build doesn't support them.  But I'll have to devise a system to allow new and creative functionality that doesn't, in turn, burden everyone who compiles for typical use cases.
