### ISSUE TITLE
Errors CompoundIntegrator with AMDIntegrator

### ISSUE THREAD

**Issue by tonosunn** [openmm/openmm#4681]
I would like to sequentially perform system equilibration and acceleration. At that time, using a CompoundIntegrator might be considered, but in practice, when you try to use it, you may find that the AMDIntegrator has been initialized as a CustomIntegrator
```python
integrator = CompoundIntegrator()
integrator.addIntegrator(
    LangevinMiddleIntegrator(300*kelvin, 1/picosecond, 0.004*picoseconds)
)
integrator.addIntegrator(
    AMDIntegrator(0.002*picoseconds, 2*kilocalorie_per_mole, 10*kilocalorie_per_mole)
)
integrator.setCurrentIntegrator(1)
print(integrator.getCurrentIntegrator())
```
```bash
<openmm.openmm.CustomIntegrator; proxy of <Swig Object of type 'OpenMM::CustomIntegrator *' at 0x7f1898eafe70> >
```

- using the AMDIntegrator alone
```python
integrator = AMDIntegrator(0.1*femtosecond, 0, 2*kilocalorie_per_mole)
print(integrator)
```
```bash
<openmm.amd.AMDIntegrator; proxy of <Swig Object of type 'OpenMM::CustomIntegrator *' at 0x7ff2b08bf930> >
```

**Comment by peastman** [comment]
That's because AMDIntegrator is a Python class that subclasses CustomIntegrator, a C++.  To all the classes in the C++ layer (such as CompoundIntegrator), it's just an ordinary CustomIntegrator.

The solution is to keep a reference to the Python object.

```python
amdintegrator = AMDIntegrator(0.002*picoseconds, 2*kilocalorie_per_mole, 10*kilocalorie_per_mole)
integrator.addIntegrator(amdintegrator)
```

**Comment by tonosunn** [comment]
I see.
Does it mean that you cannot retain the AMDIntegrator when using the CompoundIntegrator? 
I want to use the functions of the AMDIntegrator.

**Comment by peastman** [comment]
The CompoundIntegrator stores a reference to the AMDIntegrator.  If you ask for that reference, it will return it to you as a CustomIntegrator.  But if you keep around your original reference (`amdintegrator` in the above code), it will continue to work normally.

**Comment by tonosunn** [comment]
Like the following?
The AMDIntegrator parameters within CompoundIntegrator will also change, correct?
```python
integrator = CompoundIntegrator()
integrator.addIntegrator(
    LangevinMiddleIntegrator(300*kelvin, 1/picosecond, 0.004*picoseconds)
)
amdintegrator =  AMDIntegrator(0.002*picoseconds, 0, 2*kilocalorie_per_mole)
integrator.addIntegrator(amdintegrator)

# if I need to set parameter
amdintegrator.setE(2*kilocalorie_per_mole)
```

**Comment by peastman** [comment]
Exactly.
