### ISSUE TITLE
TypeError in method 'Platform_getPlatform' while running benchmark.py (openmm 8.1.2 py3.12)

### ISSUE THREAD

**Issue by MuhammadIIsmail** [openmm/openmm#4686]
A TypeError is raised when running benchmark.py

python benchmark.py --platform=CUDA --style=table --test=gbsa,rf,pme,apoa1rf,apoa1pme,apoa1ljpme,amoebapme,amber20-cellulose,amber20-stmv
/home/ismail/Downloads/openmm/examples/benchmark.py:496: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  system_info['timestamp'] = datetime.utcnow().isoformat()
hostname: ismail
timestamp: 2024-10-07T17:57:19.953866
openmm_version: 8.1.2.dev-440a9c7
cpuinfo: 13th Gen Intel(R) Core(TM) i5-13400F
cpuarch: x86_64
system: Linux
nvidia_driver: 555.42.02
gpu: NVIDIA GeForce RTX 4060

Test              Precision   Constraints   H mass (amu)   dt (fs)   Ensemble   Platform   ns/day
Traceback (most recent call last):
  File "/home/ismail/Downloads/openmm/examples/benchmark.py", line 559, in <module>
    runOneTest(test, args)
  File "/home/ismail/Downloads/openmm/examples/benchmark.py", line 350, in runOneTest
    platform = mm.Platform.getPlatform(options.platform)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ismail/anaconda3/envs/openmm/lib/python3.12/site-packages/openmm/openmm.py", line 10114, in getPlatform
    return _openmm.Platform_getPlatform(index)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: in method 'Platform_getPlatform', argument 1 of type 'int'

**Comment by peastman** [comment]
It looks like you're running the version of benchmark.py from 8.2, but trying to use it with 8.1?  You need to use the version of benchmark.py that matches the version of OpenMM you want to benchmark.
