### ISSUE TITLE
Question about LangevinMiddleIntegrator_step

### ISSUE THREAD

**Issue by ArthurBanach3241** [openmm/openmm#4709]
Hello,

I'm relatively new to both github and OpenMM, so please forgive me if I say anything unusual, fail to provide enough information, or overlook an obvious solution.

I'm currently conducting some research based on chemical compositional analysis. Unfortunately, I've run into a problem that states that my particle coordinate is NaN. I believe that this is a fairly common error to have.

I've searched for possible sources of error, which states that it came from the LangevinMiddleIntegrator_step method. However, I don't seem to have the source code for this method. Would it be possible for someone to send the source code or otherwise help me out? Thank you so much for your time and help!

**Comment by peastman** [comment]
[This FAQ entry](https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#nan) discusses what that error means and how to debug it.  Take a look and see if you can figure it out.

**Comment by ArthurBanach3241** [comment]
I've read through that already, and debugged my code multiple times. I suppose I can do it again. In the meantime, is there no other way of obtaining the source code for the method?

**Comment by peastman** [comment]
Certainly you can look at the source code, but it won't tell you what the problem is.  That method is just the point where the nan got noticed.  You need to figure out what caused it.

**Comment by ArthurBanach3241** [comment]
Sorry, I misworded my response. The problem isn't that I can't find a mistake within my code, it's that I've fed so many parameters that it's already difficult to determine where the problem is anyway. I believe it would be much easier with the source code, do you know where I can find that? Thank you!

**Comment by peastman** [comment]
Click the "Code" tab at the top of this page!  But if you can say more specifically what part of the calculation you want the code for, I can point you to that.

**Comment by ArthurBanach3241** [comment]
I see, thank you so much!
