### ISSUE TITLE
`loadCheckpoint()` doesn't reproduce the trajectories for the `LangevinMiddleIntegrator`

### ISSUE THREAD

**Issue by msuruzhon** [openmm/openmm#4716]
Hello,

I have a question about the behaviour around checkpointing a simulation that uses the `LangevinMiddleIntegrator`. It seems that when one saves a checkpoint and then loads it to continue the simulation (on the CPU platform), one does not obtain the same trajectory as simply continuing the simulation without checkpointing. Note that the `openmmtools` custom `LangevinIntegrator` doesn't have this behaviour:

```python
import numpy as np
import openmmtools.integrators
from openmm import openmm
from openmm.app import Simulation
from openmmtools.testsystems import HostGuestExplicit


def get_initial_simulation() -> Simulation:
    test_system = HostGuestExplicit()
    integrator = openmm.LangevinMiddleIntegrator(298, 1, 0.001)
    # The check works with the custom integrator from OpenMMTools
    # integrator = openmmtools.integrators.LangevinIntegrator()
    integrator.setRandomNumberSeed(42)
    simulation = Simulation(test_system.topology, test_system.system, integrator)
    simulation.context.setPositions(test_system.positions)
    return simulation


def get_positions(simulation: Simulation) -> np.ndarray:
    return simulation.context.getState(getPositions=True).getPositions(asNumpy=True)


simulation = get_initial_simulation()
simulation.step(100)
with open("state", "wb") as fh:
    fh.write(simulation.context.createCheckpoint())
simulation.step(100)
ref_positions = get_positions(simulation)
loaded_simulation = get_initial_simulation()
loaded_simulation.context.loadCheckpoint(open("state", "rb").read())
loaded_simulation.step(100)
target_positions = get_positions(loaded_simulation)
assert np.allclose(target_positions, ref_positions)
```

Now, my initial thought was that was a feature of the "middle" integrators because the velocities are at half-step, so maybe the saved state is at half-step but the loaded state assumes a full-step, hence the discrepancy. However, it seems that `VerletIntegrator` also gives reproducible trajectories, and from my understanding that is also leapfrog-like, so it seems to be something about `LangevinMiddle` both being leapfrog-like and having a stochastic component. So at this point I was wondering whether this is expected behaviour, or an issue.

Any comments would be appreciated. Many thanks.

**Comment by peastman** [comment]
Thanks for the good test case.  I can reproduce it, but only on the CPU platform.  With Reference and OpenCL, the positions match perfectly.  I haven't tested CUDA or HIP, but they largely use the same code as OpenCL so I expect they would work correctly too.

The problem is that the CPU platform has its own random number generator (CpuRandom) distinct from the Reference platform's one.  But the CPU platform doesn't provide an implementation of UpdateStateDataKernel, instead relying on the Reference platform's implementation.  That means the state of the CpuRandom doesn't get recorded in the checkpoint.

**Comment by msuruzhon** [comment]
Thank you for the quick feedback, I can confirm this works for me as well!
