### ISSUE TITLE
Decreased ns/day in 8.1.1 for systems over 90k atoms

### ISSUE THREAD

**Issue by matthewcchan** [openmm/openmm#4718]
I am encountering a decrease in performance for large systems (> 90K atoms) when using 8.1.1 compared to 7.7.0. These are the numbers from a single 3090 for a number of different sized systems. I conducted these simulations using CUDA, mixed precision, using a Langevin integrator, 4fs timestep, PME with a 10Å cutoff, and amber19ffsb+OPC waters. 

For systems less than 90K, I see an expected increase in performance, but not for systems greater than 90K. I am wondering if there I'm missing a sort of flag or parameter to run these large systems.  

| System | n_atoms | 7.7.0 ns/day | 8.1.1 ns/day | 
| --- | --- | --- | --- | 
| aE_i | 35705 | 798 | 842 | 
| drHJURP | 57109 | 541 | 565 | 
| a5b1_apo | 79763 | 371 | 403 | 
| a5b1_apo2 | 82615 | 341 |  402 |
| aE_ecad_2 | 92802 | 344 | 127 |
| a5b1_biig2 | 109451 | 270 | 90 | 
| aeb7 | 152916 | 198 | 61.9 | 
 
I'm happy to provide any simulation files or additional details.

**Comment by peastman** [comment]
Can you try 8.2?  It was just released yesterday.  It contains a number of optimizations that may affect this.

**Comment by matthewcchan** [comment]
Thank you for the quick reply. I'll try 8.2 and report back once I rerun the systems.

**Comment by matthewcchan** [comment]
8.2 definitely resolved this. Thanks for your help and all your work on this! 

| System | n_atoms | 7.7.0 ns/day | 8.1.1 ns/day | 8.2.0 ns/day
| --- | --- | --- | --- |  --- | 
| aE_i | 35705 | 798 | 842 | 784 |  
| drHJURP | 57109 | 541 | 565 |  544 | 
| a5b1_apo | 79763 | 371 | 403 | 395 | 
| a5b1_apo2 | 82615 | 341 |  402 | 398 | 
| aE_ecad_2 | 92802 | 344 | 127 | 359 | 
| a5b1_biig2 | 109451 | 270 | 90 | 304 | 
| aeb7 | 152916 | 198 | 61.9 | 198 |

**Comment by peastman** [comment]
Great!
