### ISSUE TITLE
Exception thrown for an unknown variable in CustomNonbondedForce expression though the variable is defined

### ISSUE THREAD

**Issue by varun-go** [openmm/openmm#4723]
When attempting to implement a CustomNonbondedForce in an OpenMM simulation, I receive an error message stating that a variable is not specified. However, the variable definition is in the expression. 

Example:

```
custom_force_expression = "step(r_cut - r)*U; sigma=0.5 * (sigma1 + sigma2); epsilon=sqrt(epsilon1 * epsilon2); r_cut=2^(1/6) * sigma; U=4 * epsilon * ((sigma/r)^12 - (sigma/r)^6) + epsilon"

custom_force = CustomNonbondedForce(custom_force_expression)
```
I subsequently add a `perParticelParameter` for sigma and epsilon, add each particle to the `custom_force`, and add the force to the `System` object. However, when I run the script, I receive the following error: 

```
  File "test_run_1.0.py", line 498, in <module>
    simulation = Simulation(
                 ^^^^^^^^^^^
  File "<file_path>/.conda/envs/dp_opnmm_v4/lib/python3.12/site-packages/openmm/app/simulation.py", line 104, in __init__
    self.context = mm.Context(self.system, self.integrator, platform)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<file_path>/.conda/envs/dp_opnmm_v4/lib/python3.12/site-packages/openmm/openmm.py", line 12171, in __init__
    _openmm.Context_swiginit(self, _openmm.new_Context(*args))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
openmm.OpenMMException: Unknown variable in expression: sigma

```

As a sanity check, I verified this issue does not arise when using the Lennard-Jones potential as per the CustomNonbondedForce [documentation](http://docs.openmm.org/7.1.0/api-python/generated/simtk.openmm.openmm.CustomNonbondedForce.html):
```
custom_force_expression ="4*epsilon*((sigma/r)^12-(sigma/r)^6); sigma=0.5*(sigma1+sigma2); epsilon=sqrt(epsilon1*epsilon2)"
```
I think I am missing something obvious, and any help pointing out the issue in my expression would be appreciated. Thank you!

**Comment by peastman** [comment]
Subexpressions are evaluated from the end to the beginning.  Think of a semicolon as meaning "where".  The definition of `sigma` needs to come after all uses of it.

**Comment by varun-go** [comment]
Thank you! That resolved my issue.
