### ISSUE TITLE
Update offset parameters in context?

### ISSUE THREAD

**Issue by WillGPoole** [openmm/openmm#4724]
Dear Devs, 

Was playing around with particle offsets and realised that you cannot update them in context without reinitializing.

Does it make sense that `updateParametersInContext` should also be suitable for updating offset parameters such as `chargeScale`?

Small example extended from #3054
```
import openmm
from openmm import unit

def generateSystem():
    system = openmm.System()
    system.addParticle(1)
    system.addParticle(1)
    return system

def generateContext(system):
    context = openmm.Context(system, openmm.LangevinIntegrator(298 * unit.kelvin, 1 / unit.picosecond, 2 * unit.femtosecond))
    context.setPeriodicBoxVectors(openmm.Vec3(1, 0, 0), openmm.Vec3(0, 1, 0), openmm.Vec3(0, 0, 1))
    context.setPositions([openmm.Vec3(0, 0, 0), openmm.Vec3(0.4, 0, 0)])
    return context

# generate a simple system of two Lennard-Jones particles
system = generateSystem()
force = openmm.NonbondedForce()
system.addForce(force)
force.addParticle(5 * unit.elementary_charge, 1 * unit.nanometer, 0 * unit.kilocalories_per_mole)
force.addParticle(-5 * unit.elementary_charge, 1 * unit.nanometer, 0 * unit.kilocalories_per_mole)
force.addGlobalParameter("lambda", 0)
force.setNonbondedMethod(openmm.NonbondedForce.CutoffPeriodic)
force.setCutoffDistance(0.5 * unit.nanometer)
context = generateContext(system)

print("Unperturbed:", context.getState(getEnergy=True).getPotentialEnergy())

offset_id = force.addParticleParameterOffset("lambda", 1, 0, 0, 0)  # Charge scale is 0 so will not impact the energy regardless lamba
context = generateContext(system)
print("Should be the same:", context.getState(getEnergy=True).getPotentialEnergy())

context.setParameter('lambda', 1)
print("Should still be the same:", context.getState(getEnergy=True).getPotentialEnergy())

force.setParticleParameterOffset(offset_id, "lambda", 1, 100, 0, 0)  # Change charge scale to something a bit crazy
force.updateParametersInContext(context)
print("Should be different:", context.getState(getEnergy=True).getPotentialEnergy())

context.setParameter('lambda', 0.5)
print("Should be different again:", context.getState(getEnergy=True).getPotentialEnergy())

context.reinitialize(preserveState=True)
print("Does this work?:", context.getState(getEnergy=True).getPotentialEnergy())
```

Many thanks as always!

**Comment by peastman** [comment]
`updateParametersInContext()` methods are always a tradeoff.  One one hand, we want them to update as much as possible.  On the other hand, we want them to be as fast as possible.  The more they update, the slower they are.  So it's a question of whether it's worth slowing them down for all uses to enable another use.

In this case, I think the answer might be yes.  Most NonbondedForces don't have any parameter offsets, so there wouldn't be any extra cost for them.  If you're calling `updateParametersInContext()`, and it does have offsets, there's a good chance you want it to update them.  That makes sense to do it.

I'll mark this as a feature request.

**Comment by WillGPoole** [comment]
Thanks! This will be useful for my use case where I can set the charge offset to either 0 or -basecharge such that I can use the global parameter to scale the charge of any particular atom at any point!

I suppose if you didn't mind another function then `updateOffsetParametersInContext()` will avoid any potential speed issues with  `updateParametersInContext()`. Of course, that would cost someone who may want to update parameters and offsets in one go!

**Comment by peastman** [comment]
The implementation is in #4732.
