### ISSUE TITLE
Minimization error in tleap topology files containing non-standard amino acids

### ISSUE THREAD

**Issue by babysensen** [openmm/openmm#4726]
Hi, I am new to OpenMM.I am trying to build topology and coordinate files containing non-standard amino acids(PTR) using tleap, and then load them into OpenMM for energy minimization.

In tleap, the structure of non-standard amino acids is correct. 
In OpenMM, after loading the Amber topology and coordinate files without making any changes and saving it as PDB, the structure of non-standard amino acids is correct. 
After performing energy minimization in OpenMM, it show:"openmm.OpenMMException: Particle coordinate is NaN(minimize1.py)." or a distorted structure(minimize2.py).

Currently seeking your assistance.
[openMM-error.zip](https://github.com/user-attachments/files/17819832/openMM-error.zip)

**Comment by peastman** [comment]
Take a look at [this FAQ entry](https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#nan).  It discusses causes of that error and how to debug it.

I tried to download your zip file, but I got an error that it was corrupt when I tried to expand it.

**Comment by babysensen** [comment]
> Take a look at [this FAQ entry](https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#nan). It discusses causes of that error and how to debug it.看看[这个常见问题解答条目](https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#nan)。它讨论了该错误的原因以及如何调试它。
> 
> I tried to download your zip file, but I got an error that it was corrupt when I tried to expand it.我尝试下载您的 zip 文件，但在尝试扩展它时收到错误消息，该文件已损坏。

I apologize. I have re-uploaded it to Google Cloud.
https://1drv.ms/f/c/0cdc0cbb1036f373/Ev7t13qpN41LgtFpJKFQjrsBHLn9-ZMZfMsqqx_1i02Y6A?e=WqJGJ5

**Comment by peastman** [comment]
As described in the FAQ, the first step in debugging it is to see how quickly it blows up.  Here's the output of the StateDataReporter, modified to write every step:

```
#"Step","Potential Energy (kJ/mole)","Temperature (K)"
1,-121951.10957628734,2.586974995406453
2,153769.61893933767,35.56681957638143
3,20251077761088.23,748508277.326318
4,19297432232865.07,869623149228.2789
5,251033391310022.22,29124662457418.645
6,144357824622969.78,35706589276433.336
7,302386646231755.8,91035196119807.11
8,1167690921324005.8,885239288940833.4
9,9.562343937515795e+16,1.849157728801226e+17
10,5.702048149344829e+18,1.8460411811039184e+17
```

It's blowing up immediately.  Next we want to see why.  We can monitor how large the very largest force is, and also which atom it's on.

```python
for i in range(5):
    forces = simulation.context.getState(forces=True).getForces(asNumpy=True)
    absforces = np.sum(np.abs(forces), axis=1)
    print(np.max(absforces), np.argmax(absforces))
    simulation.step(1)
```

Here is the output.

```
88549.6630859375 1792
93066.67138671875 1811
5990523.5625 1801
6439311360.0 1812
4568487552.0 1813
```

We see there is already a huge force in the very first step.  Typical forces are no more than a few thousand.  We also see that the largest forces are in the PTR residue.

The next step is to identify what kind of force it is, as described in [this cookbook entry](https://openmm.github.io/openmm-cookbook/latest/notebooks/cookbook/Analyzing%20Energy%20Contributions.html).

```python
for i,f in enumerate(system.getForces()):
    f.setForceGroup(i)
...
for i,f in enumerate(system.getForces()):
    print(f.getName(), np.max(np.abs(simulation.context.getState(forces=True, groups={i}).getForces())))
```

Here is the output.

```
HarmonicBondForce 6363.0107421875 kJ/(nm mol)
HarmonicAngleForce 2724.5224609375 kJ/(nm mol)
PeriodicTorsionForce 1656.6505126953125 kJ/(nm mol)
CMAPTorsionForce 347.4461364746094 kJ/(nm mol)
NonbondedForce 61272.13671875 kJ/(nm mol)
CMMotionRemover 0.0 kJ/(nm mol)
```

It's coming from the NonbondedForce.  I'll leave it to you to figure out what particular nonbonded interactions in your model are producing huge forces on atoms in the PTR residue.

**Comment by babysensen** [comment]
> As described in the FAQ, the first step in debugging it is to see how quickly it blows up. Here's the output of the StateDataReporter, modified to write every step:
> 
> ```
> #"Step","Potential Energy (kJ/mole)","Temperature (K)"
> 1,-121951.10957628734,2.586974995406453
> 2,153769.61893933767,35.56681957638143
> 3,20251077761088.23,748508277.326318
> 4,19297432232865.07,869623149228.2789
> 5,251033391310022.22,29124662457418.645
> 6,144357824622969.78,35706589276433.336
> 7,302386646231755.8,91035196119807.11
> 8,1167690921324005.8,885239288940833.4
> 9,9.562343937515795e+16,1.849157728801226e+17
> 10,5.702048149344829e+18,1.8460411811039184e+17
> ```
> 
> It's blowing up immediately. Next we want to see why. We can monitor how large the very largest force is, and also which atom it's on.
> 
> ```python
> for i in range(5):
>     forces = simulation.context.getState(forces=True).getForces(asNumpy=True)
>     absforces = np.sum(np.abs(forces), axis=1)
>     print(np.max(absforces), np.argmax(absforces))
>     simulation.step(1)
> ```
> 
> Here is the output.
> 
> ```
> 88549.6630859375 1792
> 93066.67138671875 1811
> 5990523.5625 1801
> 6439311360.0 1812
> 4568487552.0 1813
> ```
> 
> We see there is already a huge force in the very first step. Typical forces are no more than a few thousand. We also see that the largest forces are in the PTR residue.
> 
> The next step is to identify what kind of force it is, as described in [this cookbook entry](https://openmm.github.io/openmm-cookbook/latest/notebooks/cookbook/Analyzing%20Energy%20Contributions.html).
> 
> ```python
> for i,f in enumerate(system.getForces()):
>     f.setForceGroup(i)
> ...
> for i,f in enumerate(system.getForces()):
>     print(f.getName(), np.max(np.abs(simulation.context.getState(forces=True, groups={i}).getForces())))
> ```
> 
> Here is the output.
> 
> ```
> HarmonicBondForce 6363.0107421875 kJ/(nm mol)
> HarmonicAngleForce 2724.5224609375 kJ/(nm mol)
> PeriodicTorsionForce 1656.6505126953125 kJ/(nm mol)
> CMAPTorsionForce 347.4461364746094 kJ/(nm mol)
> NonbondedForce 61272.13671875 kJ/(nm mol)
> CMMotionRemover 0.0 kJ/(nm mol)
> ```
> 
> It's coming from the NonbondedForce. I'll leave it to you to figure out what particular nonbonded interactions in your model are producing huge forces on atoms in the PTR residue.

Thank you, peastman.  
I have identified the cause of the issue; there was an error when generating the PTR force field file. When I regenerated the force field file, the problem was resolved.  
Thank you again for your response!

**Comment by gaoxiangcao** [comment]
Hi, I encountered the same issue. Can you tell me how you fixed the force field file?

**Comment by babysensen** [comment]
> Hi

我非天然氨基酸生成的有问题，所以报错了。用下面这个方法重新生成的，就正常MD了
https://blog.csdn.net/sinat_23241095/article/details/53836200?ops_request_misc=%257B%2522request%255Fid%2522%253A%2522e9e7d902f2bb88c384e62a99061416d8%2522%252C%2522scm%2522%253A%252220140713.130102334.pc%255Fall.%2522%257D&request_id=e9e7d902f2bb88c384e62a99061416d8&biz_id=0&utm_medium=distribute.pc_search_result.none-task-blog-2~all~first_rank_ecpm_v1~rank_v31_ecpm-1-53836200-null-null.142^v100^pc_search_result_base2&utm_term=%E6%B0%A8%E5%9F%BA%E9%85%B8%E5%8A%9B%E5%9C%BA%E7%94%9F%E6%88%90&spm=1018.2226.3001.4449
