### ISSUE TITLE
How to control temperature in Drude model?

### ISSUE THREAD

**Issue by Cynthia-0807** [openmm/openmm#4729]
I am confused about how to control temperature using the Dual-Langevin or Dual-NoseHoover thermostats in the Drude model. Recently, I’ve been researching the CHARMM fluctuating charge (CHARMM-FQ) model, which is based on a similar principle to the Drude model, both utilizing the extended Lagrangian to update degrees of freedom. However, the Drude model seems to control protein temperature more effectively, without exhibiting the "hot solvent/cold solute" phenomenon. Could this be because Drude atoms are easier to control than the fluctuating charges?

The CHARMM-FQ model hasn’t been updated in over two decades, and I don’t have the authority to post in the CHARMM forum, so I’m seeking answers elsewhere. While this issue isn’t directly related to OpenMM, I’m considering implementing CHARMM-FQ into OpenMM in the future, which is why this problem has been troubling me for some time.

**Comment by peastman** [comment]
I'm not familiar with that model.  It sounds like you're describing something like a velocity rescaling thermostat?  They can have problems where energy ends up distributed unevenly.  One common case is known as the "flying ice cube" problem, where energy gets transferred from a molecule's internal motion to its center of mass motion.

The DrudeLangevinIntegrator in OpenMM is based on Langevin dynamics, which doesn't have that problem.  Every degree of freedom is independently coupled to a heat bath.  Each one follows the correct thermal distribution, regardless of what other degrees of freedom happen to be doing at that moment.

I don't recommend Nose-Hoover integrators.  Some people seem to like them, but I'm honestly not sure why.  Langevin integrators tend to work better in practice, as well as having theoretical advantages.

**Comment by Cynthia-0807** [comment]
> I'm not familiar with that model. It sounds like you're describing something like a velocity rescaling thermostat? They can have problems where energy ends up distributed unevenly. One common case is known as the "flying ice cube" problem, where energy gets transferred from a molecule's internal motion to its center of mass motion.
> 
> The DrudeLangevinIntegrator in OpenMM is based on Langevin dynamics, which doesn't have that problem. Every degree of freedom is independently coupled to a heat bath. Each one follows the correct thermal distribution, regardless of what other degrees of freedom happen to be doing at that moment.
> 
> I don't recommend Nose-Hoover integrators. Some people seem to like them, but I'm honestly not sure why. Langevin integrators tend to work better in practice, as well as having theoretical advantages.

OK.Thanks for your fast relpy and suggestion.

**Comment by peastman** [comment]
Is it ok to close this issue?

**Comment by Cynthia-0807** [comment]
> Is it ok to close this issue?

ok
