### ISSUE TITLE
modeller.addSolvent() for AMOEBA

### ISSUE THREAD

**Issue by chabi-fin** [openmm/openmm#4750]
Hello!

I have parameterized a small molecule for AMOEBA and want to simulate in explicit solvent in OpenMM. I see that modeller.addSolvent() can't be used with the AMOEBA ff--are there plans to expand this capability?

Otherwise, what is the current protocol for explicit solvation in OpenMM with AMOEBA? I suppose external tools are needed--any advice?

**Comment by peastman** [comment]
It will work fine if you use `model='tip3p'`.  They're both three point water models.  It will use a water box that was pre-equilibrated with a different force field, but since you should always start by energy minimizing the system and then equilibrating it, that won't make any difference.

**Comment by chabi-fin** [comment]
Hey, thanks for the reply. 
Yes, I see your point about using 3 point models to initiate a solvated system. 
I have some trouble to use this approach still. If I set `model="tip3p"`, then I have the error 
> ValueError: The ForceField does not specify a NonbondedForce

while if I include tip3p in my force field as `forcefield = app.ForceField(f"{ input_path }/AMOEBA-BIO-2018.xml",  "amber/tip3p_standard.xml")` then I get a conflict between the forcefields,

> ValueError: Residue template CA with the same override level 0 already exists.

Is there an inbuilt .xml for just tip3p which doesn't conflict with the AMOEBA?

**Comment by peastman** [comment]
Since you closed this, I assume you figured it out?  Anyway, don't include tip3p.xml in the force field.  AMOEBA provides its own water model.

**Comment by chabi-fin** [comment]
Hey, so I did figure it out, but using the above approach, because when I set model="tip3p", then I have the error

>    ValueError: The ForceField does not specify a NonbondedForce

due to using AMOEBA's water model

**Comment by peastman** [comment]
You shouldn't edit the file.  Simply call `addSolvent()` as usual to add the water box and create your force field with `ForceField('amoeba2018.xml')`.

**Comment by chabi-fin** [comment]
OK, must be an issue with my forcefield then.

**Comment by Erikna00** [comment]
Hi,

I can add that i have the same problem as the previous speaker where modeller does not work with amoeba.
It seems that modeller does not recognize the nonbonded amoeba term as it complains of such a error.
I was able to bypass the issue by first creating a amber force field, adding solvent and then remaking my openff system generator with amoeba.

Best, Erik

**Comment by peastman** [comment]
It ought to be easy to make it work with AMOEBA.  The only thing it uses the force field for is to get charges and vdw radii.  It expects the force field to create a NonbondedForce, from which it gets them.  But it could get them just as easily from an AmoebaMultipleForce and AmoebaVdwForce.

I'm going to reopen this and mark it as a feature request.

There's another case we ought to handle better while we're at it.  If you provide a force field that uses CustomNonbondedForce to handle repulsion (such as CHARMM36), it will conclude all the radii are zero and put water closer to the solute than it should.  We should make it detect that case and handle it in some better way.  For example, it could use default radii based on the elements.
