### ISSUE TITLE
proposed ffxml extensions for protomers/tautomers

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#494]
@nilmeier, @swails, and I have been discussing ways we need to extend the OpenMM `app` layer's `ffxml` forcefield specification file format to be able to specify multiple protonation/tautomeric states possible for specific residues that have titratable sites.

The following information for each titratable residue needs to be stored:
- the number of protomer/tautomer states
- list of identifiers associated with atoms in this residue that will change (unless we want to always specify variant parameter sets for _all_ atoms to simplify bookkeeping)
- for each protomer/tautomer state:
  - a reference energy 
  - a reference pKa (which could be combined into the reference energy, but may be useful to keep separate)
  - the relative number of protons associated with this state (or, alternatively, total charge)
  - list of charges associated with each atom for this protomer/tautomer state
  - if we allow other force terms to change (e.g. Lennard-Jones terms), these are also listed

It would be great to keep this format extensible so that we could match the AMBER behavior and only have charges change at first, but allow this to be generalized to let Lennard-Jones parameters change, or multipoles change (for AMOEBA), etc.

Suggestions/comments?

**Comment by peastman** [comment]
Closing this old issue, since we have no current plans to implement it.
