### ISSUE TITLE
state of force groups in fortran

### ISSUE THREAD

**Issue by nullsatz** [openmm/openmm#512]
In fortran OpenMM_Context_getState doesn't take a groups argument. So there's no way access the state of force groups. Is it possible to either add the groups argument to the OpenMM_Context_getState set of wrappers or add a new subroutines?

Also, is there a way to get an array of energy components for each force group that is more efficient than getting each group's state in a loop? Does asking for the state of each force group in a loop introduce lots of device to host memory transfers?

**Comment by peastman** [comment]
We now have a `OpenMM_Context_getState_2()` function that does take force groups.
