### ISSUE TITLE
CMAKE_OSX_DEPLOYMENT_TARGET warnings for 10.9

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#587]
I'm still getting this error on all of my OS X 10.9 machines:

```
(2.7)bash-3.2$ cmake .
CMake Warning at /opt/local/share/cmake-3.0/Modules/Platform/Darwin.cmake:143 (message):
  CMAKE_OSX_DEPLOYMENT_TARGET is '10.7' but the matching SDK does not exist
  at:

   "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.7.sdk"

  Instead using SDK:

   "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk"

  matching the host OS X version.
Call Stack (most recent call first):
  /opt/local/share/cmake-3.0/Modules/CMakeSystemSpecificInformation.cmake:36 (include)
  CMakeLists.txt:20 (PROJECT)


CMake Error at /opt/local/share/cmake-3.0/Modules/Platform/Darwin.cmake:213 (message):
  CMAKE_OSX_DEPLOYMENT_TARGET is '10.7' but CMAKE_OSX_SYSROOT:

   ""

  is not set to a MacOSX SDK with a recognized version.  Either set
  CMAKE_OSX_SYSROOT to a valid SDK or set CMAKE_OSX_DEPLOYMENT_TARGET to
  empty.
Call Stack (most recent call first):
  /opt/local/share/cmake-3.0/Modules/CMakeSystemSpecificInformation.cmake:36 (include)
  CMakeLists.txt:20 (PROJECT)


-- Configuring incomplete, errors occurred!
See also "/Users/Shared/Jenkins/Home/workspace/openmm-conda-dev-mac/openmm/CMakeFiles/CMakeOutput.log".
```

Is anyone else getting this too?

**Comment by jchodera** [comment]
Should we update the `CMAKE_OSX_DEPLOYMENT_TARGET` at some point?

**Comment by peastman** [comment]
Good question.  I guess the arguments are 1) not many people are likely to still be using an OS that old, vs. 2) why break it if there's no reason to?

What would we gain by changing it?

**Comment by rmcgibbo** [comment]
On OSX, something about the cmake set up makes it really tricky. If you change it, it gets automatically changed back when you reconfigure. It's a daily hassle. Couldn't we just leave it blank and have it set automatically, by default?

When we're building binaries to distribute, we can set it to something like 10.7.

**Comment by jchodera** [comment]
> On OSX, something about the cmake set up makes it really tricky. If you change it, it gets automatically changed back when you reconfigure. It's a daily hassle. Couldn't we just leave it blank and have it set automatically, by default?

Best idea I've heard so far.
