### ISSUE TITLE
Feature Discussion: Partial AMOEBA multipoles

### ISSUE THREAD

**Issue by leeping** [openmm/openmm#596]
I'm exploring some force field functional forms that use parts of the AmoebaMultipoleForce (e.g. no quadrupoles / permanent dipoles on certain atoms, or no multipoles / polarizability at all.)  

In principle this should speed things up, but in OpenMM there is little benefit because the AmoebaMultipoleForce calculates interactions through second order in the multipole expansion for all particles.  The only exception is when all quadrupoles in the system are set to zero, then it skips over all interactions involving quadrupoles.

To speed things up I could imagine storing several neighbor lists corresponding to nonzero q-q, q-d, q-Q, d-d, d-Q and Q-Q interactions.  Let me know if this sounds feasible at all.

**Comment by peastman** [comment]
Closing this old issue, since we have no plans to implement it.
