### ISSUE TITLE
GB Performance

### ISSUE THREAD

**Issue by jlmaccal** [openmm/openmm#663]
It's great to see that OpenMM is getting close to Amber for explicit solvent / PME performance. But I have been running some benchmarks and we're lagging behind for GB calculations, especially when CustomGBForce is used.

All benchmarks are done on my laptop (GT 750M). I will rerun these on more representative hardware as soon as I get it setup. I list all the GB models in OpenMM terminology, where OBC1 is equivalent to igb=2, OBC2 is equivalent to igb=5, GBn is equivalent to igb=7, and GBn2 is equivalent to igb=8.

Also, note that OBC1 and OBC2 have identical functional forms, but with different parameters. However, in OpenMM these have different implementations: one native and one through CustomGBForce. GBn and GBn also have equivalent functional forms with different parameters, but both are implemented with CustomGBForce.

The test system is a small protein with 83 residues and ~1400 atoms simulated with no cutoffs. The timings are as follows:

| code | GB model | time for 200 ps | ns per day |
| --- | --- | --- | --- |
| Amber | OBC2 | 199 | 87 |
| Amber | GBn2 | 263 | 66 |
| OpenMM | Vacuum | 45 | 384 |
| OpenMM | OBC1 | 355 | 49 |
| OpenMM | OBC2 | 160 | 108 |
| OpenMM | GBn2 | 689 | 25 |

A few things to notice:
- With OBC2, OpenMM is about 25 faster than Amber for this system!
- In OpenMM, OBC1 is half the speed of OBC2, even though they are the same functional form. CustomGBForce cuts performance by ~50 percent.
- In OpenMM, GBn2 is half the speed of OBC1, which is unexpected. In Amber, this difference is only about 30 percent.

I'm wondering if anything can be done to improve the situation. GBn2 is likely to be widely used, given the recent JACS paper from the Simmerling lab. We have also benchmarked GB model / force field combinations and found GBn2 to be the top performer with recent Amber force fields.

I'm not sure I can really do much to address either of these points myself, but:
- I think it's worth implementing GBn2 as a native force.
- I think it's worth investigating why GBn2 is so slow when implemented as a CustomGBForce. Perhaps there are some low-hanging optimizations?

**Comment by ajasja** [comment]
Not sure if I should reopen this issue or open a new one.

For a system with about 16000 atoms I get about 91 ns/day on a GTX1080Ti.
I construct the system using

```python
        pdb = PDBFile(input_pdb)
        forcefield = ForceField('amber99sb.xml', 'amber99_obc.xml')
```

If however I make the file using tleap and then try the GBn2 implicit forcefield I get about 7 ns/day.

```python
            amberSys    = AmberPrmtopFile(input_top)
            topology    = amberSys.topology
            positions   = PDBFile(input_pdb).positions

            system = amberSys.createSystem(nonbondedMethod=nonbondedMethod, nonbondedCutoff=nonbondedCutoff,
                constraints=constraints, rigidWater=True,  implicitSolvent=solv_map[args.solvent], implicitSolventSaltConc=args.salt*moles/liter)      
```
Is this expected?

**Comment by peastman** [comment]
Please open a new issue.  This one was closed six years ago, so anything you're seeing now is almost certainly unrelated.
