### ISSUE TITLE
Split out simtk.unit into a separate package?

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#680]
It would be very useful to split out `simtk.unit` into a separate package.

We're already using it in some projects that have nothing to do with simulation (e.g. an [isothermal titration calorimetry (ITC) automation toolkit](https://github.com/choderalab/itctools) and a [Bayesian ITC analysis framework](https://github.com/choderalab/bayesian-itc)) and it would be great if `simtk.unit` didn't require installing OpenMM.

**Comment by davidlmobley** [comment]
@jchodera - is your current "authoritative" solution pint? I had the impression I'd seen code from your group newer than this thread using simtk.unit. Also, I believe there is stuff in openmoltools using simtk.unit. 

I'm asking partly because we're investigating using units for some of our own tools (alchemical-analysis, for example) and I would prefer not to make it require simtk, since it's a relatively lightweight analysis tool. 

Can you comment on whether you're satisfied with `pint`?

**Comment by jchodera** [comment]
We have been using `simtk.unit` for any tools that utilize OpenMM (or are OK requiring it as a dependency), and `pint` for tools where it would make no sense to include OpenMM (such as purely experimental tools like `bayesian-itc`).

I still think there is great value in splitting out `simtk.unit` into a separate package that is `pip` and `conda`-installable.

**Comment by rmcgibbo** [comment]
If you're interested in trying a new thing, I might give [astropy.units](http://docs.astropy.org/en/stable/units/quantity.html#quantity) a try, (assuming none of the astronomy focus gets in the way). I think they have better integration with numpy by subclassing ndarray and using a lot of that type of cleverness so that things like `np.sum` work.

```
In [6]: np.sum(np.array([1,2,3])*u.ps)
Out[6]: <Quantity 6.0 ps>
```

**Comment by rmcgibbo** [comment]
But obviously it's not foolproof:

```
In [9]: np.product(np.array([2,3,4])*u.ps)
Out[9]: <Quantity 24.0 ps>
```

**Comment by swails** [comment]
ParmEd also has a copy of `simtk.unit` embedded as part of it (and it transparently "becomes" `simtk.unit` if it's available, so that your tools don't *require* OpenMM, but work perfectly with it should the need ever arise).  It's pure-python, and conda-installable, so it's a simple `import parmed.units as u`.

If you ever think you might want to bring in some ParmEd or OpenMM functionality into whatever tool you're using/making, I'd recommend this route.  Also, getting more people using `unit` is also the best way to make it better (for instance, I've invested some time making the numpy integration better, albeit not to the level that `astropy.units` is I'm sure).

**Comment by rmcgibbo** [comment]
> ParmEd also has a copy of simtk.unit embedded as part of it (and it transparently "becomes" simtk.unit if it's available, so that your tools don't require OpenMM, but work perfectly with it should the need ever arise).

I'm sure this could be done in a units standalone package as well. The limiting factor is anyone caring enough to do it and maintain it.

**Comment by peastman** [comment]
> ParmEd also has a copy of simtk.unit embedded as part of it (and it transparently "becomes" simtk.unit if it's available,

That's an interesting idea.  I have no objection to simtk.unit living as its own independent package, I just don't want to create an extra dependency for people installing OpenMM.  That's a way of balancing those goals, though I'm curious how it works in practice.  Can you give more details?

**Comment by rmcgibbo** [comment]
It's nothing complicated, just https://github.com/ParmEd/ParmEd/blob/master/parmed/unit/__init__.py#L24-L31

**Comment by swails** [comment]
> I'm sure this could be done in a units standalone package as well. The limiting factor is anyone caring enough to do it and maintain it.

I'm sure it could be done.  There's nothing "special" about unit living inside of ParmEd.  But I quasi-learned from `simtk.unit` on PyPI in that if I want it maintained, I need to put it in my own package and maintain it :).

**Comment by rmcgibbo** [comment]
Oh, don't let that stop you. I'm happy to give you the PyPI rights to that name on PyPI. :)

**Comment by davidlmobley** [comment]
I'm enthusiastic about getting this put into a separate package if at all
possible. It's something important enough it has widespread applications,
but if I want to use it in something really "light" (i.e. in a
non-simulation-based class using Python, etc.) it seems silly to have to
install a wide variety of other tools/dependencies to get access to it.



On Fri, Jan 8, 2016 at 12:04 PM, Robert T. McGibbon <
notifications@github.com> wrote:

> Oh, don't let that stop you. I'm happy to give you the PyPI rights to that
> name on PyPI. :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pandegroup/openmm/issues/680#issuecomment-170108661>.
>



-- 
David Mobley
dmobley@gmail.com
949-385-2436

**Comment by swails** [comment]
> It's nothing complicated, just https://github.com/ParmEd/ParmEd/blob/master/parmed/unit/__init__.py#L24-L31

Exactly.  And I can easily customize/extend it inside the `__init__.py` file (as I do for the AKMA unit system below), and it will "just work", using the desired `unit` package.

In practice, it's been awesome.  All of the units improvements that I make, I actually make in ParmEd first and then copy it over if I like it.  The maintenance has been minimal, and I never have to worry about whether OpenMM is there or not if I want to use units.  But as soon as you have, and try to use, OpenMM, the units assigned from ParmEd are understood by default.

It's one of those "set it up and forget about it" things, which I find very nice.

**Comment by swails** [comment]
> Oh, don't let that stop you. I'm happy to give you the PyPI rights to that name on PyPI. :)

Oh, I meant that it's more likely to be maintained by me if it's part of ParmEd proper, rather than housed separately on PyPI.  I like having it bundled with ParmEd for the same reasons @peastman likes having it bundled with OpenMM.  And if I *do* bundle it (the same way we do `six`, for instance), then all ownership transfer means is that I'll ignore it instead of you :).

**Comment by swails** [comment]
> (i.e. in a
> non-simulation-based class using Python, etc.) it seems silly to have to
> install a wide variety of other tools/dependencies to get access to it.

Is ParmEd by itself too much of a dependency?  ParmEd itself only depends on numpy and has only one small, optional C++ extension that prevents it from *truly* being pure-Python.

There are a number of other unit packages out there:
- [units](https://pypi.python.org/pypi/units/)
- [numericalunits](https://pypi.python.org/pypi/numericalunits)
- [pint](https://pint.readthedocs.org/en/0.6/)
- astropy.unit\* (@rmcgibbo gave the link earlier)
- simtk.unit\* and parmed.unit\*
- [quantities](https://pythonhosted.org/quantities/user/tutorial.html)
- [natu](http://kdavies4.github.io/natu/)
- [ScientificPython](http://dirac.cnrs-orleans.fr/ScientificPython/ScientificPythonManual/Scientific.Physics.PhysicalQuantities-module.html)\*
- [unum](http://home.scarlet.be/be052320/Unum.html)

\* Part of larger packages

I'll be honest -- I didn't look at any of the others before choosing `simtk.unit`.  Using OpenMM meant I had to use `simtk.unit` at least a little, it seemed reasonably powerful, and I had no desire to learn about redundant packages.  So I chose early on to invest my time in `simtk.unit`, and I'm not unhappy with the choice so far.

**Comment by davidlmobley** [comment]
Yes, I'm happier with ParmEd as a dependency than openmm. So that might
work.

On Fri, Jan 8, 2016 at 12:26 PM, Jason Swails <notifications@github.com>
wrote:

> (i.e. in a
> non-simulation-based class using Python, etc.) it seems silly to have to
> install a wide variety of other tools/dependencies to get access to it.
>
> Is ParmEd by itself too much of a dependency? ParmEd itself only depends
> on numpy and has only one small, optional C++ extension that prevents it
> from *truly* being pure-Python.
>
> There are a number of other unit packages out there:
>
>    - units <https://pypi.python.org/pypi/units/>
>    - numericalunits <https://pypi.python.org/pypi/numericalunits>
>    - pint <https://pint.readthedocs.org/en/0.6/>
>    - astropy.unit* (@rmcgibbo <https://github.com/rmcgibbo> gave the link
>    earlier)
>    - simtk.unit* and parmed.unit*
>    - quantities <https://pythonhosted.org/quantities/user/tutorial.html>
>    - natu <http://kdavies4.github.io/natu/>
>    - ScientificPython
>    <http://dirac.cnrs-orleans.fr/ScientificPython/ScientificPythonManual/Scientific.Physics.PhysicalQuantities-module.html>
>    *
>    - unum <http://home.scarlet.be/be052320/Unum.html>
>
> * Part of larger packages
>
> I'll be honest -- I didn't look at any of the others before choosing
> simtk.unit. Using OpenMM meant I had to use simtk.unit at least a little,
> it seemed reasonably powerful, and I had no desire to learn about redundant
> packages. So I chose early on to invest my time in simtk.unit, and I'm
> not unhappy with the choice so far.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pandegroup/openmm/issues/680#issuecomment-170114175>.
>



-- 
David Mobley
dmobley@gmail.com
949-385-2436

**Comment by rmcgibbo** [comment]
FWIW, if I were writing a python lib from scratch that didn't depend on OpenMM, I wouldn't use `simtk.unit`. I think it serves OpenMM's purposes just fine, but I don't find it very useful outside of that.

- It doesn't integrate with numpy very well (this makes sense because for openmm's purposes, because openmm doesn't depend on numpy, but for most other purposes, I find tight numpy integration to be a big feature.)
- It doesn't have any independent documentation.

@swails: you should add parmed to pypi 😞

```
$ pip install parmed
Collecting parmed
  Could not find a version that satisfies the requirement parmed (from versions: )
No matching distribution found for parmed
```

**Comment by swails** [comment]
> It doesn't integrate with numpy very well (this makes sense because for openmm's purposes, because openmm doesn't depend on numpy, but for most other purposes, I find tight numpy integration to be a big feature.)

Numpy integration has gotten better, though.  It does what I need it to do, at least...  Where is it falling short for you?

**Comment by swails** [comment]
> @swails: you should add parmed to pypi 😞

I should...

**Comment by rmcgibbo** [comment]
Well, for example `np.sqrt(np.array([1,2,3])*u.nanometer**2)` doesn't work properly.

**Comment by swails** [comment]
Ugh.  I tried doing `python setup.py sdist` and it omits all of the header files.  Which, apparently, people are like "heh. yep. it does."

Well that's no use.

**Comment by peastman** [comment]
> Well, for example np.sqrt(np.array([1,2,3])*u.nanometer**2) doesn't work properly.

Do other units packages manage to make that work?  If so, do you know how?

**Comment by rmcgibbo** [comment]
I tried that with astropy.units, and it worked properly, but no I didn't look at the code.

**Comment by rmcgibbo** [comment]
It also works with pint.

```
>>> import numpy as np
>>> from pint import UnitRegistry
>>> u = UnitRegistry()
>>> np.sqrt(np.array([1,2,3])*u.nanometer*2)
<Quantity([ 1.41421356  2.          2.44948974], 'nanometer ** 0.5')>
```

**Comment by swails** [comment]
Yea, pint has a mapping for several numpy ufuncs to teach them how to handle units.  We could probably copy a decent bit of their numpy-specific code into simtk.unit and resolve a lot of the shortcomings you see.

**Comment by peastman** [comment]
I looked up the pint code, then did a little experimenting, and I see how it works.  If you call np.sqrt() on an object it doesn't know how to deal with, it looks for a sqrt() method on the object.  If it finds one, it calls that method and returns the result.  So we could easily add that method to Quantity.

This does *not* work with math.sqrt(), only numpy.sqrt().

**Comment by rmcgibbo** [comment]
I'm not sure if this is a good idea, but one idea would be to delete `simtk.unit` entirely and just vendor a copy of `pint` into the openmm source tree, like we do for C++ libraries that are developed and maintained elsewhere in `libraries/`

**Comment by salotz** [comment]
I would add that it would be a good idea to think about persistence/serialization of units on disk that is somewhat future proof. Most of the libraries are able to handle strings like "picoseconds", which is workable, but not ideal. The `pint` docs mention [serialization](https://pint.readthedocs.io/en/0.8.1/serialization.html) although it doesn't address the unit basis definitions. `pint` (ad hoc (?) txt format) and `natu` (ini) have their own text formats for the basis definitions but I imagine something like JSON would be a better option for interoperability.

**Comment by peastman** [comment]
We don't currently have any plans to do this.

**Comment by swails** [comment]
fwiw, parmed has its own copy (that pulls in OpenMM's if `openmm` is available).  So you could pull in `parmed.unit`, which only has numpy as a hard dependency and is pip-installable.

That seems good enough for most use-cases here.
