### ISSUE TITLE
Topology object should be more useful

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#721]
I think it's high time we had a discussion about how to make the `Topology` object more useful.

Currently, a lot of information is lost when, say, a `PDBFile` is read.  It would be great if more metadata---such as even chain names---could be stored in the Topology object.  

A more sophisticated selection system, similar to the PyMOL selection syntax, could also be integrated.

I think `MDTraj` has done lots of great things with the `Topology` class, so perhaps this is a model that could be adopted and standardized?

**Comment by peastman** [comment]
This is partly addressed by #813.

**Comment by jchodera** [comment]
Thanks, @peastman!  #813 will definitely help.

I'd love to see a more extensive API for manipulating `Topology` objects, such as:
* **Support for deleting atoms, residues, and chains.** We often want to load in a PDB file and only simulate part of the system.  Some of this is addressed by changes to `pdbfixer`, but the inflexibility of `Topology` means that it is actually really, really hard to extend `pdbfixer` to do things like this.
* **Support for a selection language for selecting atom subsets.**  This would be generally useful for various tools, such as having a user identifying which parts of a PDB file to keep or discard; identifying the part of the system to be alchemically decoupled in YANK; etc.
* **Simplification of downstream tools.** A lot of the `omnia` tools implement their own `Topology`-like object.  If we instead had a more fully featured version in OpenMM, some of these could be greatly simplified.

**Comment by jchodera** [comment]
I'm once again finding myself running into terrible headaches with the OpenMM topology object.  I think it's worth revisiting the issue of a more functional and user-friendly `Topology` object in OpenMM for a future release.

**Comment by swails** [comment]
What kinds of things can't be done with Topology as-is?  And can you do them with MDTraj or ParmEd instead? Both can read in a Topology from OpenMM and regenerate one.

**Comment by jchodera** [comment]
Yes, you can maintain multiple topology objects, but this is not an optimal programming model.  

I was trying to grab a subset of chains of an OpenMM topology and positions, create a System from these, and then determine a subset of atoms involving one of the chains using the MDTraj DSL.  At one point, I was juggling six sets of topology objects (three MDTraj, three OpenMM).  We could have had nine if we had ParmEd in the mix too.  Or twelve if we had PDBFixer in the mix too (which I do, but tried to isolate in a different stage just to avoid this problem).

It would be really nice if we could simplify things down to a single multifunctional root Topology object that did lots of useful things that we could all subclass as needed...

**Comment by swails** [comment]
I've generally found that the MDTraj Topology object is quite nice, and it's on the whole quite similar to OpenMM's (ParmEd's `Structure`, by contrast, is quite different, though also quite flexible IMO).  Perhaps you could experiment with migrating their Topology object over.

You could also do all of this directly in ParmEd, as it is capable of doing these kinds of manipulations and generating `System`s following it (in fact, this is the type of thing ParmEd was *designed* to do).  Then you would only need to deal with one `Topology`-like object ;).

**Comment by jchodera** [comment]
These are all nice tools.  There is no disputing that.  But no one tool does everything.  

Here's the [code I am talking about](https://github.com/jchodera/yank/blob/fix-abl-example/examples/mhc-peptide-tcr/mhc-peptide-tcr.py).  It's not the most well-written thing, but it was an attempt at a quick driver to set up a simulation of a difficult system (peptide binding an MHC and TCR).

The whole point is that I need to shepherd a Topology through a number of tools:
* `pdbfixer` to delete unwanted chains/heteroatoms and add missing atoms and residues
* `simtk.openmm.app.Modeller` to add missing hydrogens and solvent
* `MDTraj` to extract parts of the system using the DSL and then identify atom subsets
* `simtk.openmm.app.Forcefield` to create a system
* `simtk.openmm.app.Simulation` to run a simulation

and so on.  At least `pdbfixer` and `openmm` use the same Topology object, but none of the other tools do.  They support nice `.to_openmm()` functions, but don't gracefully accept OpenMM `Topology` objects.

Is there a simple solution here?  Some ideas:
* Standardize the OpenMM `Topology` object to provide a union of features that everyone can use, so everyone doesn't have to reinvent the wheel.
* Agree on an API and use 'duck typing' so it doesn't matter what implementation we use as long as we stick to the API for Topology objects we pass between tools.
* Gracefully and automatically accept `Topology` objects from any other program, but that means we have to be able to transform from either OpenMM, MDTraj, or ParmEd objects.

**Comment by swails** [comment]
> They support nice .to_openmm() functions, but don't gracefully accept OpenMM Topology objects.

This isn't true.  MDTraj has `Topology.from_openmm`, and ParmEd has `parmed.openmm.load_topology`.

**Comment by jchodera** [comment]
That isn't "gracefully accepting OpenMM topology objects as if they were your own".  That's "a method to import OpenMM topologies bolted on through a separate interface".

**Comment by swails** [comment]
Still should do the trick until better integration can happen.  With limited developer time available, this at least has a temporary workaround...

**Comment by jchodera** [comment]
Yes, we can bolt everything together with lots of hacky workarounds, but the point of this thread is to discuss a path forward to minimize the number of hacky workarounds we need.

Unless we just want to adopt the slogan "Omnia: Because a big pile of hacky workarounds should be good enough for anyone!"

I had some concrete proposals above that I think at least merit discussion about what we eventually want to work toward, even if we don't implement the strategy immediately.

**Comment by jchodera** [comment]
Looks like I'm stuck with my own project.  Even the hacky workarounds won't work because of information loss of chain information during the MDTraj <--> OpenMM conversion process.  How does ParmEd do this?  Do you keep chain ids?  Can I select subsets of atoms with them, and delete them without having all chains renumbered?

**Comment by jlmaccal** [comment]
I'm also +1 on trying to improve this aspect of OpenMM. We also have to jump through hoops to automatically set up simulations. While there are workarounds, it would be better if we could do more of this in pure OpenMM.

**Comment by jchodera** [comment]
This is also an Omnia issue.  If we expect to have interoperability, we need some sort of standardization on ether a more fully functional Topology object in OpenMM or agreement on a minimal API that all other packages will stick to for their own Topology objects.

**Comment by rmcgibbo** [comment]
In MDTraj, we took the approach of just incrementally adding particular methods to the topology object, at the cost of divergence from the OpenMM object. There are a couple of changes that we made that make it impossible to exactly duck type between the two Topologies -- one of them is that generator methods on the OpenMM Topology like `atoms()`, `residues()`, `chains()` became properties.

I'm happy to contribute to adding more functionality to OpenMM, but let's try to keep the tone of the discussion positive, and not denigrate each other's work.

**Comment by jchodera** [comment]
You guys have done a great deal of excellent work with `mdtraj` and `parmed`, and I certainly don't mean to suggest that it isn't incredibly useful.  

It would, however, be nice to figure out how we can take the best ideas from these packages and evolve them into some sort of interoperable API for a Topology class or an improved OpenMM Topology class so that we can make these packages more interoperable.

And apologies for the tone of my earlier comments.  I've spent a few sleepless nights wrestling with these tools and issues caused by the Topology issue in particular.  I think we could simplify things immensely by working toward better interoperability through a few key data structures that are intended to be shared.

**Comment by jchodera** [comment]
Also, given the work that's been put into the `mdtraj` and `parmed` topology representations, we're already probably pretty close to either a useful API or evolved OpenMM implementation.

> There are a couple of changes that we made that make it impossible to exactly duck type between the two Topologies -- one of them is that generator methods on the OpenMM Topology like atoms(), residues(), chains() became properties.

I imagine that very few tools outside of omnia make use of these generators, so it may not be a dealbreaker to pick one or the other (or an entirely new interface) to use.

**Comment by rmcgibbo** [comment]
I actually think they're reasonably commonly used. They feature prominently in many of our examples using list comprehension. But it's hard to say for certain.

**Comment by jchodera** [comment]
The OpenMM version is commonly used or the mdtraj one is commonly used?

**Comment by rmcgibbo** [comment]
I was talking about the MDTraj one, but I suspect both.

**Comment by jchodera** [comment]
Hm. I don't suppose it's possible to support both usages in Python, since they would have the same name.  That makes things much more complicated...

**Comment by swails** [comment]
> How does ParmEd do this? Do you keep chain ids? Can I select subsets of atoms with them, and delete them without having all chains renumbered?

Yes, ParmEd keeps chain IDs, and provides a way of selecting atoms based on them.  It's entirely possible that you can do everything you need within ParmEd (which will use OpenMM under-the-hood).

> Hm. I don't suppose it's possible to support both usages in Python, since they would have the same name. That makes things much more complicated...

I think it's possible with some Pythonic gymnastics (like giving descriptors a `__call__` that returns the generator, for instance).  But it's unsightly to say the least (and confusing).  Unifying the `Topology` API to be fully functional in a duck-typing sense between OpenMM, MDTraj, and ParmEd will be a huge challenge (and impossible to do without breaking *somebody's* backwards-compatibility).

But I've typically found @rmcgibbo and @peastman pretty receptive to suggested improvements via PRs accompanied by my use-case.  That's a great way we can all work together to improve the Omnia suite.

**Comment by jchodera** [comment]
> Yes, ParmEd keeps chain IDs, and provides a way of selecting atoms based on them. It's entirely possible that you can do everything you need within ParmEd (which will use OpenMM under-the-hood).

I'll certainly give this a try, but I think it would still be useful to talk about interoperability strategies.

> I think it's possible with some Pythonic gymnastics (like giving descriptors a __call__ that returns the generator, for instance). But it's unsightly to say the least (and confusing). Unifying the Topology API to be fully functional in a duck-typing sense between OpenMM, MDTraj, and ParmEd will be a huge challenge (and impossible to do without breaking somebody's backwards-compatibility).

I have a feeling that we could have avoided many of these issues if we had this discussion six months ago, but now the codes seem to have evolved to the point where it is hard to unify anything.  

Perhaps there is an alternative to either a common duck-typing API or an enhanced OpenMM Topology object that still has a number of advantages?

> But I've typically found @rmcgibbo and @peastman pretty receptive to suggested improvements via PRs accompanied by my use-case. 

This has not been my experience with OpenMM.

**Comment by rmcgibbo** [comment]
I think all of the people that have been trying to develop these libraries recognize that it's a nontrivial problem. We're also in a very different place than we were six months ago. Things grow organically, and I wouldn't have predicted previously, for example, that someone would be using the atom selection syntax in MDTraj to slice and dice topologies for setting up new simulations from subsets of other systems. That just wasn't a project that was on my radar (as I think of MDTraj as mostly for analyzing already-performed simulations).

I think from our experience, we're seeing now in practice some of the difficult cases. These use cases can be (and are) a spur for new features, and that's great.

But I'm also quite frustrated by the tone of this discussion. Sometimes I get the impression that whenever a certain task is tricky to accomplish, or one hits roadblocks/pain points, or an API isn't 100% designed towards the particular problem at hand, that this is treated as an immediate crisis, that someone is necessarily considered _at fault_, and that it's someone else's responsibility to drop whatever projects they are working on and swoop in to fix the perceived problem.

Progress happens one PR at a time. Let's keep it light, fun, and energetic, and work on incremental, mergable improvements.

**Comment by rmcgibbo** [comment]
As to the particular details of the problem at issue, I think it's true to say that neither the OpenMM or MDTraj topology objects are particularly well-suited for directly constructing new systems by taking subsets of other systems and splitting/combining topologies. The basic reason is that neither object maintains the positions along side the topology, and both topologies maintain an index for each atom that maps to the offset in a positions array for the association position of the atoms. This design means that if you combine two topologies, you have to also combine the position arrays in the appropriate way, and juggle both. Or if you remove atoms / residues, you also have to apply a corresponding sequence of slices to a positions array, or else you'll end up with gobbledygook. So from the perspective of adding/splitting/combining `(positions,Topology)` tuples, they're not encapsulated.

The Modeller class, OTOH, is pretty well suited for this kind of functionality, because it wraps the topology and the positions together. Also, this kind of operation is right in the heartland of the ParmEd `Structure` class.

**Comment by jchodera** [comment]
All excellent points, @rmcgibbo.

**Comment by jchodera** [comment]
Do people like the [`pymol` way of handling selections](http://pymol.sourceforge.net/newman/user/S0220commands.html)?  This permits selection by PDB fields *or* geometry, which I've found pretty handy in essentially every problem I've run into.

It seems like most omnia codes are happy to work with atom indices, so if we had something like this that operated on a merged `(positions,Topology)` and yielded atom indices and sliced positions and (OpenMM?) Topology objects, it might be pretty universally useful.  

This might be a separate entity or, since ParmEd is pretty close to this functionality already, perhaps we could work with @swails to add pymol-like functionality there?

**Comment by swails** [comment]
> This might be a separate entity or, since ParmEd is pretty close to this functionality already, perhaps we could work with @swails to add pymol-like functionality there?

I'm open to anything like that (you could probably even lift the PyMol selection syntax from their source if the license permits).  Better would probably be to use the one in MDTraj (which is more VMD-like than PyMol-like).  The existing selection syntax works for me, though.

**Comment by jchodera** [comment]
The pymol syntax has some advantages, though is decidedly unpythonic in
design.

I guess there wouldn't be harm in supporting multiple types of syntax:
Pymol, mdtraj DSL, Ambermasks / chimera, and Pythonic generators.

Is there some way to break out the code for these selection schemes into a
module so it could be used in multiple projects, rather than having each
project implement its own version?  I suppose that's back to needing some
sort of standard Topology interface for that to work.

**Comment by leeping** [comment]
Hi there,

I support having an object that allows one to easily manipulate and modify simulation input, and it does seem that OpenMM / MDTraj / ParmEd provide some overlapping functionality here. 

Discussing a standard core set of features / API might be nice, and we can continue to allow all three packages to develop new features according to the rapidly changing needs of research. This would have the advantage of providing some interoperability without requiring that all three packages have to be in lockstep. 

As for the atom selection language,  I am mostly accustomed to VMD, and that has worked well for me. I can think of some limitations - like I can't highlight water molecules with exactly four hydrogen bonding partners - but maybe that is beyond the scope. I don't mind learning another atom selection language.

Thanks,

- Lee-Ping

**Comment by leeping** [comment]
I forgot to mention that Modeller does seem to be the best place for these features in OpenMM.

**Comment by Lnaden** [comment]
Should we consider making this topic more general to the Omnia MD project? Although I believe this issue should stay open here as it directly relates to OpenMM, we should have the discussion on the common framework which all Omnia tools follow elsewhere, and bring any decision from there, here.

**Comment by peastman** [comment]
Could we try approaching this question from the opposite direction?  We seem to be starting from the code and asking, "How can we unify these classes?"  That's usually the wrong approach to take.  Instead, we should start by listing important use cases, identifying the pain points in them, and then asking, "How can we make them easier and less painful?"  The answer might end up being, "By making the Topology classes more similar," but then again it might not.  So can everyone describe their use cases and discuss the particular problems they currently have with them?

**Comment by swails** [comment]
+1

**Comment by peastman** [comment]
This old discussion seems to have trailed off without ever reaching a conclusion, so I'm closing it.
