### ISSUE TITLE
Br ions loaded as boron

### ISSUE THREAD

**Issue by OndrejMarsalek** [openmm/openmm#768]
I have trouble loading a PDB file with Br ions in it - the get assigned boron as the element and then the construction of the system fail because I don't have parameters for any boron atom types in my force field. The code that causes this is here:

https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/pdbfile.py#L110

where "BR" is not in the list of "exceptions", which means that the else clause gets executed, passing "B" to get_by_symbol. Adding "BR" to the list in the same way some other elements are already done resolves the issue, but I am not sure that is the way to do it. Is it supposed to be a list of all elements for which there exists another element that starts with the same letter?

**Comment by peastman** [comment]
The problem is almost certainly that your PDB file is missing the element specification.  That's supposed to go in columns 77-78.  See http://www.wwpdb.org/documentation/format33/sect9.html#ATOM.  If it's missing, OpenMM tries to guess the element based on the atom name, but that doesn't always work.

**Comment by OndrejMarsalek** [comment]
Thanks for point that out, when I add it, the atom gets recognized correctly. I can add that by hand in this particular case, but if there already is code to try and guess for PDB files that don't have the element column, would it be helpful to add BR to the list? Other ions with the same issue (and the same fix) are Rb and Cs. Thanks for considering this.

**Comment by jchodera** [comment]
Should a warming be issued when openmm is forced to guess (unless some
argument is set to suppress warnings)?

**Comment by swails** [comment]
> Should a warming be issued when openmm is forced to guess (unless some
> argument is set to suppress warnings)?

How do you propose issuing said warning?  I would vote no to printing to stderr, but taking advantage of the python logging mechanism might work.  (`warnings.warn` could also work, but I think `logging.Logger` is considered more Pythonic, whereas `warnings.warn` is suggested for use in situations where future versions will result in a hard error.)

**Comment by rmcgibbo** [comment]
-1 on using logging. +1 on warnings.warn. deprecation is not the only place
where warnings are used, ex: numpy's default with zero division.
