### ISSUE TITLE
Docs may not be correctly pushed to S3 via travis

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#819]
Looks like there may be something wrong with the travis `after_success` block:
https://travis-ci.org/pandegroup/openmm/builds/51163293#L4696

**Comment by jchodera** [comment]
This was apparently due to a forgotten `cd ../..` after testing in `.travis.yml` after these lines:
https://github.com/pandegroup/openmm/blob/master/.travis.yml#L33-L34

PR #817 fixes this too.

**Comment by jchodera** [comment]
Actually, how should this correctly work? We don't want the git head dev versions replacing the release versions. To avoid thia, do we just have to be diligent about updating the version numbers after releases to represent the next dev release? Any insight @rmcgibbo?

**Comment by swails** [comment]
Why not pull the version number from the git hash?  Something like `dev-ad4824ef` or something...

**Comment by jchodera** [comment]
That could work, but we would end up with a proliferation of versions of the docs which would cost money and time to clean up.

I was thinking we should just increment the version number immediately to 6.3.0 after a 6.2.x release, or use a standard `dev` or `alpha` version number, possibly one conforming to a PEP specification.

**Comment by kyleabeauchamp** [comment]
So for MSMBuilder (http://msmbuilder.org/latest/) we have different pages for different versions of the docs.  The latest release is 3.0, so the current version number in setup.py is `VERSION = '3.1.0.dev0'`.  I think these two things should be sufficient.  However, the pages are a bit different so I'll leave further thoughts to the experts.

**Comment by jchodera** [comment]
It sounds like the MSMBuilder approach would work very well for OpenMM.

**Comment by peastman** [comment]
I'm not too familiar with the issues involved here.  Kyle, can you explain how that works?

**Comment by kyleabeauchamp** [comment]
On the HTML documentation side, AFAIK, we have some custom JS code that gives a dropdown menu for selecting between the different versions of documentation.  

On the version side of things, I think we just need to make sure that the master version number is incremented after each release, so that changes to git master won't overwrite the release documentation versions.  

Again, I'm not the expert here, so I can't really describe things further without digging through the code.

**Comment by rmcgibbo** [comment]
For the previous OpenMM releases since 6.1 or so, I just pushed the docs
from the command line with s3cmd.

**Comment by peastman** [comment]
Is this even something we really *want* to happen?  The online docs are there for end users, and most end users should be using the most recent release, *not* the current development code.  If we automatically post documentation for the latest development code, isn't that just going to confuse users who stumble across it when they should really be looking at the documentation for the latest release instead?

**Comment by kyleabeauchamp** [comment]
I agree that we don't want to have it highly visible.  

On the other hand, it could be cute to have it online but not linked as a service for developers.

**Comment by peastman** [comment]
The danger is that search engines will discover it.  Then when someone searches for "openmm docs", it's anyone's guess whether it will take them to the release or development docs.

**Comment by jchodera** [comment]
Having docs online for developers is helpful. If there is code
available online, there should be docs available for that code online.

I think we just want the online docs to default to the release
version, not the dev version.

If you're worried about google search indexing, you can use webmaster tools:

https://support.google.com/webmasters/answer/4559176?hl=en

**Comment by swails** [comment]
> Having docs online for developers is helpful. If there is code
> available online, there should be docs available for that code online.

I'm not disagreeing, but this does not apply to me.  When I `ccmake`, I just turn on the option to build the API docs and point my web browser to that file.

The upside is that it works wherever I don't feel like paying for internet :), and I'm always 100% sure that it points to the version of the docs corresponding directly to the version I have (as opposed to a newer version if I haven't pulled in awhile).

How many other devs *never* build the docs or do what I do?

**Comment by jchodera** [comment]
> I'm not disagreeing, but this does not apply to me. When I ccmake, I just turn on the option to build the API docs and point my web browser to that file.

That's great, but the point of having an `openmm-dev` package uploaded to binstar automatically is to save us from having to waste 40 minutes compiling OpenMM from source.

**Comment by jchodera** [comment]
If there was a "build the docs only" makefile target (*cough* #677 *cough*) this would be less of an issue.

**Comment by peastman** [comment]
You mean like "make DoxygenApiDocs"?

**Comment by jchodera** [comment]
Does that build the sphinx manual too?

**Comment by peastman** [comment]
"make sphinxhtml".  Or if you want PDF, "make sphinxpdf".

**Comment by jchodera** [comment]
```
[LSKI1497:~/code/openmm/openmm.jchodera] choderaj% make sphinxhtml
make: *** No rule to make target `sphinxhtml'.  Stop.
```
Am I missing something?

**Comment by peastman** [comment]
It works fine for me:

```
$ make sphinxhtml
Scanning dependencies of target sphinxhtml
Generating HTML user guide
Making output directory...
Running Sphinx v1.2.3
...
```

No idea why it wouldn't for you.  Does anyone else have this problem?

**Comment by mpharrigan** [comment]
Works for me. @jchodera have you run cmake to generate the makefile?

**Comment by swails** [comment]
> That's great, but the point of having an openmm-dev package uploaded to binstar automatically is to save us from having to waste 40 minutes compiling OpenMM from source.

And that's why I never run `make clean` or start from a fresh build directory when I pull (but I have to rerun `ccmake -i ../openmm` if new files have been added).  That, along with a `make -j6` on my 6-core machine typically builds OMM _very_ quickly (just took me 1m44s for all 4 platforms, all plugins, and docs and I was ~3 weeks behind).

A fresh build with `make -j6` (following `make clean`) took me 2m59s.

On my MBP (core i5, 13" Retina) with CPU, Reference, plugins, and docs; a simple rebuild (without cleaning) with `make -j2 install` took me 2m33s.  Following a clean, it took me 3m01s (again, with a `make -j2 install`).

As an aside, `make sphinxhtml`, `make sphinxpdf`, and `make DoxygenApiDocs` all worked for me.  You could always alias `make sphinxhtml sphinxpdf DoxygenApiDocs` to something like `makeommdocs` and implement close to what you want now.

Again, I'm not casting my vote against this (as I have no vested interest in it), I'm just trying to be helpful with ideas for simple workarounds if this doesn't make it high on anybody's priority list soon.

**Comment by jchodera** [comment]
From a fresh checkout of OpenMM after successfully running cmake:
```
[LSKI1497:~/code/openmm/openmm.simtk] choderaj% cmake .
-- Configuring done
CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  MACOSX_RPATH is not specified for the following targets:

   OpenMM
   OpenMMAmoeba
   OpenMMAmoebaReference
   OpenMMCPU
   OpenMMDrude
   OpenMMDrudeReference
   OpenMMPME
   OpenMMRPMD
   OpenMMRPMDReference

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /Users/choderaj/code/openmm/openmm.simtk
[LSKI1497:~/code/openmm/openmm.simtk] choderaj% make sphinxhtml
Scanning dependencies of target sphinxhtml
Generating HTML user guide
Making output directory...
Running Sphinx v1.2.3

Extension error:
Could not import extension sphinxcontrib.bibtex (exception: No module named sphinxcontrib.bibtex)
make[4]: *** [html] Error 1
make[3]: *** [sphinx-docs/userguide/html/index.html] Error 2
make[2]: *** [docs-source/CMakeFiles/sphinxhtml.dir/all] Error 2
make[1]: *** [docs-source/CMakeFiles/sphinxhtml.dir/rule] Error 2
make: *** [sphinxhtml] Error 2
```
Clearly it's a bit more complicated than just `make sphinxhtml`, right?

Also, do any of these things build the python docs?

Anyway, the original discussion focused on whether it made sense to have the current github `master` push the S3 docs for the dev version to S3 somewhere people can get to it.  I still think there is value in this, and it would just require we bump the version number scheme to 6.3.dev0 or something.  I don't think this is that hard, and it carries with it sufficient value that it is worth this minimal effort.

**Comment by swails** [comment]
> Clearly it's a bit more complicated than just `make sphinxhtml`, right?

Yes it is, so long as you have the prerequisites installed.  You need the sphinx bibtex extension.  Easy to get with `pip`:

```
[swails@Robin ~ ]$ pip search bibtex
bibtexvcs                 - a Python package for managing a BibTeX database and related documents
pybtex                    - A BibTeX-compatible bibliography processor in Python
  INSTALLED: 0.18 (latest)
sphinxcontrib-bibtex      - A Sphinx extension for BibTeX style citations.
  INSTALLED: 0.3.1 (latest)
...
```

So run the command `sudo pip install sphinxcontrib-bibtex` to install that prereq.

> Also, do any of these things build the python docs?

`make DoxygenApiDocs` does

**Comment by jchodera** [comment]
Ah, excellent point.  That error was indeed due to the missing `sphinxcontrib-bibtext`.

I can indeed do `make sphinxhtml` now.

`make DoxygenApiDocs` doesn't seem to build the Python docs correctly, as `api-python/index.html` shows an empty class tree.  I believe we encountered this problem earlier.

**Comment by swails** [comment]
> `make DoxygenApiDocs` doesn't seem to build the Python docs correctly, as `api-python/index.html` shows an empty class tree. I believe we encountered this problem earlier.

Ah, yea.  It hadn't occurred to me that all of the OMM class documentation (i.e., everything *not* in `simtk.openmm.app`) is generated from `openmm.py`, which is created by SWIG at build time.  What happens if you do a `python setup.py build` inside the `python` directory first?  As long as you have `OPENMM_LIB_PATH` and `OPENMM_INCLUDE_PATH` set from the relevant locations in your conda install, you shouldn't *have* to build OpenMM to get the Python API docs to come out correct... although maybe I'm wrong.

Of course, the `setup.py` script sneaks in an uninstall every time it's run so that it will completely strip out any importable `simtk` package (leaving only `simtk/__init__.py` and `simtk.testInstallation`).  For the record, I *really* dislike that behavior.

**Comment by peastman** [comment]
True, you have to do a full build to get the Python docs.  Otherwise, the Python modules won't have been generated.

**Comment by jchodera** [comment]
OK, so it seems like building a complete set of docs for the `openmm-dev` conda package (which can be installed via `conda install openmm-dev`) is not completely trivial or quick (except for technowizards like @swails and @peastman).  

Is there then still value in having the docs online on S3 under a "dev" drop-down selection?  Or are the docs that get installed in `~/anaconda/docs/openmm/` sufficient for us, and we don't want to confuse anyone further by adding more versions of the docs.

Two corollaries:
* We probably *will* want multiple versions of the docs online anyway if we end up supporting several stable releases of OpenMM simultaneously (e.g. 6.1, 6.2, 6.3)
* If we don't want to have more than one version of the docs online, we should probably remove all the code from travis that tries to push the docs.

**Comment by jchodera** [comment]
This may be a duplicate of #778

**Comment by jchodera** [comment]
@peastman: The [dev docs](http://docs.openmm.org/development/api-python/index.html) are not being correctly pushed, and I am unable to debug because I can't inspect the S3 bucket. Can you fix this?

**Comment by jchodera** [comment]
Interesting! These builds work fine on https://travis-ci.org/omnia-md/conda-dev-recipes

The build environment in the travis tests is different and does not use conda---it uses pip:
https://github.com/pandegroup/openmm/blob/master/.travis.yml#L186

I think we may just want to switch to using conda to build and test.

**Comment by peastman** [comment]
Possibly it's just caused by using a different version of some library (such as Sphinx)?  Anyway, if conda installs versions of everything that make it work, that sounds like a sensible solution.
