### ISSUE TITLE
Unhelpful error message (700)

### ISSUE THREAD

**Issue by mpharrigan** [openmm/openmm#820]
Hi,
I'm getting the following errors sporadically under the cuda platform:

```
 Exception: Error invoking kernel: Invalid error code (700)
```

and

```
Exception: Error synchronizing on event for CCMA: Invalid error code (700) at /home/harrigan/source/openmm/platforms/cuda/src/CudaIntegrationUtilities.cpp:812
```

These are happening after tens of nanoseconds of successful simulation. The energies look fine. I'm going to look at the trajectories. This is happening on icme's Nvidia C2070

**Comment by peastman** [comment]
700 is CUDA_ERROR_ILLEGAL_ADDRESS.  That's basically a segfault inside a kernel.

**Comment by rcrehuet** [comment]
I'm getting the same error. See issue: https://github.com/pandegroup/openmm/issues/2018 
The fact that it is a segfault inside the kernel means that it's a bug and, as users, we cannot do anything about it? If so, why is it so infrequent? (I only found this issue and mine) Did you manage a workaround @mpharrigan ?

**Comment by peastman** [comment]
This error code describes a symptom, but not what problem caused the symptom.  An illegal address access indicates something has gotten messed up on the GPU.  Lots of different problems could potentially cause that.  So we just need to take each case on its own, try to figure out what's going on, and fix the root problem that led to the error.
