### ISSUE TITLE
Standardize approach for handling platform precision

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#909]
This might be an OpenMM 7 feature due to its potential to break backward compatibility (slightly) or introduce API changes, but it would be great to standardize the way that `Platform` objects are queried for which precision models they support and the way that the user selects among available precision models.

Currently, we have the following logic:
- For all platforms, you can query `supportsDoublePrecision()` to see if it supports double precision, but there is no corresponding `supportsSinglePrecision()`.  
- The `Reference` platform only supports double precision, so you need to call `platform.getName()` to check the name to see that it does not support single precision.
- The `CPU` platform only supports single precision
- Selecting among precision models for CUDA and OpenCL is different, an requires you check the platform name to see whether you should set the platform variable `CudaPrecision` or `OpenCLPrecision`
- Querying which precision model is currently selected is similarly bewildering
- Some platforms support `mixed` precision, but there is no way to query for that

Perhaps there is a very simple way to both query and select among precision models?  This doesn't necessarily _have_ to break backwards compatibility, but it may be conceptually more straightforward to do so.  For example, a `platform.getAvailablePrecisionModels()` and `platform.setDefaultPrecisionModel()` may be sufficient.

**Comment by peastman** [comment]
I've been meaning to deprecate the supportsDoublePrecision() method.  It was created back when there was a clear distinction: Reference did everything in double precision, OpenCL and CUDA did everything in single precision.  But today that isn't true.  It doesn't really capture how Platforms work today.

Also, there are three distinct things you might want to know:

1. What precision modes is a Platform capable of?

2. What precision modes is a particular device capable of?

3. What precision mode is a particular Context using?

The definitions of various modes aren't at all standardized.  For example, the CPU platform uses a mixed precision mode, not single.  But it isn't the same as the mixed precision mode used by CUDA and OpenCL.  It uses single precision only for the nonbonded forces, while computing bonded forces in double.  In contrast, CUDA and OpenCL compute all forces in single precision.  The distinction isn't usually important: bonded forces usually contribute less error than nonbonded ones, so if you're using single for nonbonded, there's not much benefit to using double for bonded.  But they also have little effect on performance, so I haven't bothered to created optimized versions of them for the CPU platform.  But even so, "mixed precision" isn't uniquely defined.  And it's entirely possible its behavior could change in the future, for example if I create an optimized CPU implementation of bonded forces, or find a new way to significantly improve accuracy with little performance cost.

**Comment by jchodera** [comment]
We certainly want to be flexible in allowing new behaviors in the future---the platform variables seem to be a good way to allow that kind of flexibility.  But maybe there's a simple way to refactor the functionalities that have stabilized?

If it would be a bad idea to use `single`, `mixed`, and `double` since this means something different for each platform, would it make sense to have each platform have an ordered list of available precision modes that increase in both cost and accuracy?  That might still allow codes to programmatically test and select among precision models.

**Comment by jchodera** [comment]
Would be great to tag this as a `potential enhancement discussion` for future release roadmap.
