### ISSUE TITLE
Energy minimization on GPU using Rosetta forcefield

### ISSUE THREAD

**Issue by BIORAK** [openmm/openmm#932]
How do I perform energy minimization on GPU using Rosetta forcefield ?

Also how do I run torsion angle dynamics in OpenMM. Moreover how do I constrain parts of structure and allow flexibility only in certain parts ?

**Comment by jlmaccal** [comment]
> How do I perform energy minimization on GPU using Rosetta forcefield ?
> 
You can’t. The Rosetta force field is not implemented in OpenMM.
> Also how do I run torsion angle dynamics in OpenMM.
> 
You can’t. OpenMM does not have a torsion angle dynamics integrator.
> Moreover how do I constrain parts of structure and allow flexibility only in certain parts 
> 

You can place restraints on angles, dihedral angles, and/or distances between atoms as appropriate by adding custom forces to the system.

**Comment by peastman** [comment]
In principle you could do torsion angle dynamics by adding appropriate distance constraints to make all the bonds and angles rigid.  You'll have to be careful, though, to avoid overconstraining the system.  If you simply add a constraint for every bond and angle, that can lead to too many constraints, which means the constraint matrix becomes singular.  Think of a methane molecule, for example.  It has 5 atoms, so 15 degrees of freedom.  It has 4 bonds and 6 angles, so if you added a constraint for each one, you would be left with 15-4-6=5 degrees of freedom, whereas a rigid body should have 6 degrees of freedom.  So you would have to omit one constraint.

**Comment by BIORAK** [comment]
Thanks, while running L-BFGS energy minimizer I dont see any GPU cores being used.

**Comment by peastman** [comment]
What platform are you using?

**Comment by BIORAK** [comment]
CUDA 6.5 Tesla K20m

**Comment by peastman** [comment]
And you're actually using the CUDA platform?  If so, it's definitely using a GPU.  That platform doesn't have any other way to calculate forces and energies.  What makes you think the GPU isn't being used?

**Comment by BIORAK** [comment]
Ok so when I add customforces I dont see the GPU being utilized, so how do I make it GPU enabled

**Comment by peastman** [comment]
In just a few messages you've brought up several seemingly unrelated things.  I don't have any idea what you're actually doing!  Could you provide some background?  What problem are you trying to solve, and how precisely are you trying to solve it?  If you could post your code that would be best, since then we can see exactly what you're doing.
