### ISSUE TITLE
Enabling greater control over numerical issues for Custom*Force terms

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#979]
I've encountered an issue where using a softcore Lennard-Jones force involving the following definition of effective interparticle distance `r` causes `nan` in both `mixed` and `double` precision modes our GPUs:

```
reff_sterics = sigma*((softcore_alpha*(1.-lambda_sterics) + (r/sigma)^6))^(1/6);
```

From what I can tell, this is due to the `(r/sigma)^6` term, which can grow quite large for large `r`.

As a workaround, I've used the new `select` function to rewrite this as

```
reff_sterics = select(step(r-sigma), r*(1 + softcore_alpha*(1-lambda_sterics)*(sigma/r)^6)^(1/6), sigma*((softcore_alpha*(1.-lambda_sterics) + (r/sigma)\
^6))^(1/6))
```

I was just wondering if there were additional thoughts on how we can ensure quantities are computed in a numerically stable way and avoid Lepton optimizing away our attempts to encode how quantities that should be computed in a certain way.

I wonder if introducing a special kind of brackets, like `[...]` or `{...}`, or expression separators (as an alternative to `;`) that Lepton would not optimize through would be one way to approach this.

**Comment by peastman** [comment]
I don't think that's really the problem.  Are you sure you haven't defined sigma to be 0?

With any reasonable value for sigma, (r/sigma) should never be much larger than about 10.  Even if it were 1000, (r/sigma)^6 would only be 10^18 which is easily representable in single precision.

**Comment by jchodera** [comment]
Huh.  You're totally right.  It was this atom:
```
ATOM     18  HG  SER A   2     -20.897 -25.820  21.678  1.00  0.00           H  
```
which in the `amber99sbildn.xml` forcefield happens to have `sigma` = 0.

https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/data/amber99sbildn.xml#L7754
```
 <Atom type="296" charge="0.4275" sigma="0.0" epsilon="0.0"/>
```
Is it OK for `NonbondedForce` to have `sigma = 0` passed to it?  If not, maybe I should edit the `ffxml` conversion script to not generate zero `sigma` values and rebuild that file?

Interestingly, in this system, (r/sigma) with a normal value of sigma ~ 1.0A can be ~170, which is 2.4e13---still representable.

Excellent insight here---thanks again!

**Comment by peastman** [comment]
It would definitely be better to change that to sigma="1.0".  Since epsilon is 0, it doesn't matter what sigma is.  It just needs to not produce a divide by zero!

**Comment by Lnaden** [comment]
+1 on this catch! Explains why I have some `NaN` using TIP3P water in `CustomNonbondedForce`. Will be useful to know going forward.

**Comment by jchodera** [comment]
Looks like this line in the forcefield conversion scripts may be the culprit:
https://github.com/pandegroup/openmm/blob/master/devtools/forcefield-scripts/processAmberForceField.py#L408

What if I submit a PR to do the following:
1. Change this to `sigma` = 0.1 nm
2. Run this against the forcefield files shipping with the latest AmberTools to rebuild old forcefields and any new forcefield ffxml files

Would you want to wait to merge this after OpenMM 6.3 is cut and released?

**Comment by peastman** [comment]
That sounds good.  But yes, let's wait till 6.3 is out.

**Comment by jchodera** [comment]
Let's use the issue labeling/tagging system to make sure we don't lose track.
How about you:
* Mark this issue with a label like `minor bug` or `enhancement` or something that captures what this issue is to you.
* Assign this to a Milestone of `OpenMM 6.4`.
* Assign this to `jchodera` so I'll be sure to find it when I sort for issues assigned to me.

I'd be happy to do this, but don't have developer access to do so.

**Comment by peastman** [comment]
I'm closing this since it's mostly obsolete.  We don't use that script for converting force fields anymore, and the newer force fields we recommend for most purposes were converted with ParmEd which doesn't have this problem.
